.github/workflows/tests.yml

Needed by Unit Tests (cmocka)
Fixes #10838
CI
This fix was tested in half a dozen of my spelling PRs. The `Unit Tests (cmocka)` tests fail without it.
This version of the commit supersedes the commits on those other PRs.

Add libzstd-dev

---

README.md
docs/overview/what-is-netdata.md

~~Yannis-San~~ @slimanio  pointed out a typo to me, and it's about time to update the news. Plus, I had a request to update the GIF on the main README, so I'm including that as well.
area/docs

Update news and GIF in README, fix typo

---

health/health.c
health/health_json.c
health/health_log.c
health/notifications/alarm-notify.sh.in

This PR makes some final changes to the email template, removes the replacement of `${family}` variable, and removes the limit of sending just the last 30min alarms to the template.
Health
The PR will be merged to a feature branch, and will be tested in the staging enviroment.

Changes to the email template.

---

health/health_json.c

Fix incorrect health entries that are propagated to the cloud
Pending the re-design of the new away that alerts will reach the cloud, this additional check will verify that
we do not have a more recent alarm entry in the linked list with the same "alarm_id"  and a new_status not in
warning or critical state.
health
- Not easy to test. One needs to manually "tweak" the heath-log.db file and "break" the link between an alarm that has been raised (WARNING or CRITICAL) but have a newer entry that clears the alarm and restart the agent. That alarm will be sent to the cloud.
- The pattern of the offending entry would be: 
- An alarm id **6051ffca** (column B) with a "A" indicator (column A) that has a missing updated_by entry *column 5*  line 5. 
- Line 8 should be used to clear the alarm and …

Fix incorrect health log entries

---

health/notifications/alarm-notify.sh.in

Fix the date in the email.
Health

Fix date in email.

---

health/health.c
health/notifications/alarm-notify.sh.in

Fix a case when an alarm entry would not make it in the table in currently active alerts, in the html email. 
Also move `now` outside the loop.
Health

Fix entries in table in html email

---

packaging/installer/netdata-updater.sh

As in the summary. We should never be using glob expansion in arguments for commands that expect a single argument.
In this case, we can use a combination of `find` and `head` to extract exactly one matching directory based on some additional info we already have, and then pass just that path to `cd`.
area/packaging
Verified using CI.
Fixes: #10931

Don’t use glob expansion in argument to `cd` in updater.

---

health/notifications/alarm-notify.sh.in

Multiple styling updates to alert email template
second part:
Email notification template

Notify template styling update

---

health/notifications/alarm-notify.sh.in

fix "Edit" link in "Need to configure this alert?" section
email notification template

fix "Edit" link in "Need to configure this alert?" section

---

collectors/cgroups.plugin/README.md

Add lists of monitored metrics to the cgroups plugin documentation

---

collectors/proc.plugin/proc_meminfo.c

We added a new dimension to monitor kernel percpu memory allocations in order to make the `mem.kernel` chart consistent.
Fixes #10960
proc plugin
Check the `mem.kernel` chart. It should display a new dimension "Percpu". You can kill the `ebpf.plugin` and see how the amount of used percpu memory changes.

Add a metric for percpu memory

---

Dockerfile.test
build/m4/ax_gcc_func_attribute.m4
build_external/clean-install-arch-debug.Dockerfile
build_external/clean-install-arch-extras.Dockerfile
build_external/clean-install-arch.Dockerfile
build_external/scenarios/aclk-testing/paho-inspection.py
netdata.spec.in

Spelling build

---

libnetdata/clocks/clocks.h
libnetdata/config/appconfig.c
libnetdata/config/appconfig.h
libnetdata/health/health.c
libnetdata/json/json.c
libnetdata/procfile/procfile.c
libnetdata/procfile/procfile.h
libnetdata/socket/security.c
libnetdata/storage_number/storage_number.h
libnetdata/storage_number/tests/test_storage_number.c
libnetdata/url/url.c

Spelling libnetdata

---

tests/node.d/fronius.parse.spec.js
tests/profile/test-eval.c

Spelling tests

---

aclk/legacy/aclk_common.c
aclk/legacy/aclk_lws_wss_client.c
aclk/legacy/aclk_lws_wss_client.h
aclk/legacy/aclk_query.c
aclk/legacy/aclk_rx_msgs.c
aclk/legacy/agent_cloud_link.c
aclk/legacy/agent_cloud_link.h
aclk/legacy/mqtt.c
aclk/legacy/tests/paho-inspection.py

Spelling aclk

---

database/engine/metadata_log/metadatalog.h
database/engine/pagecache.c
database/engine/rrdengine.h
database/engine/rrdengineapi.c
database/rrd.h
database/rrddim.c

Spelling database

---

collectors/all.h
collectors/cgroups.plugin/sys_fs_cgroup.c
collectors/charts.d.plugin/charts.d.conf
collectors/charts.d.plugin/charts.d.plugin.in
collectors/checks.plugin/plugin_checks.c
collectors/cups.plugin/cups_plugin.c
collectors/diskspace.plugin/plugin_diskspace.c
collectors/ebpf.plugin/ebpf.c
collectors/ebpf.plugin/ebpf.h
collectors/ebpf.plugin/ebpf_apps.c
collectors/ebpf.plugin/ebpf_process.c
collectors/ebpf.plugin/ebpf_socket.c
collectors/freebsd.plugin/freebsd_devstat.c
collectors/freebsd.plugin/freebsd_getifaddrs.c
collectors/freebsd.plugin/freebsd_getmntinfo.c
collectors/freebsd.plugin/freebsd_sysctl.c
collectors/ioping.plugin/ioping.plugin.in
collectors/node.d.plugin/named/named.node.js
collectors/node.d.plugin/sma_webbox/sma_webbox.node.js
collectors/node.d.plugin/snmp/snmp.node.js
collectors/perf.plugin/perf_plugin.c
collectors/plugins.d/pluginsd_parser.c
collectors/proc.plugin/ipc.c
collectors/proc.plugin/proc_net_dev.c
collectors/proc.plugin/proc_net_wireless.c
collectors/proc.plugin/proc_pagetypeinfo.c
collectors/proc.plugin/sys_class_infiniband.c
collectors/slabinfo.plugin/slabinfo.c
collectors/statsd.plugin/statsd.c
collectors/tc.plugin/plugin_tc.c

Spelling collectors

---

web/api/badges/web_buffer_svg.c
web/api/health/health_cmdapi.c
web/api/netdata-swagger.json
web/api/netdata-swagger.yaml
web/api/queries/query.c
web/api/queries/rrdr.h
web/api/tests/web_api.c
web/server/static/static-threaded.c

Spelling web api server

---

docs/Running-behind-apache.md

As @JialuZhang recently commented on #6403 
There is no need to have Apache mod_rewrite running with this configuration.
I've tested the change on: 
OS:            Ubuntu 18.04.5 LTS (bionic)
Apache:     2.4.29
Netdata:    v1.29.3-215-nightly

Remove RewriteEngine for dedicated vHost

---

docs/guides/monitor/statsd.md

fix uil in statsd guide

---

collectors/python.d.plugin/nvidia_smi/README.md

Save a little time for the next gpu enabler

nvidia-smi: update README.md

---

web/gui/custom/README.md
web/gui/dash-example.html

* Fixes a race condition that caused graphs to not load
* Moves configuration to the top of the file
* Improves docs
* Other small fixes
**NOTE: This file is not maintained by Netdata, it is just meant to be an example of multi-host streaming capabilities**
`dash-example.html`
**NOTE: This file is not maintained by Netdata, it is just meant to be an example of multi-host streaming capabilities**

Improvements to dash-example.html

---

collectors/apps.plugin/README.md
collectors/ebpf.plugin/README.md
collectors/ebpf.plugin/ebpf.c
docs/configure/nodes.md
docs/guides/troubleshoot/monitor-debug-applications-ebpf.md
netdata-installer.sh

When we merged https://github.com/netdata/netdata/pull/10756/files  it was missed a change for documentation and `ebpf.c`, this PR fixes these rename changes.
ebpf.plugin
We can consider this typo errors, so it is not necessary big tests. If you want you can compile and verify that everything is running fine.

Update eBPF documentation

---

aclk/aclk.c
aclk/aclk.h
aclk/aclk_otp.c
aclk/aclk_otp.h
aclk/aclk_util.c
aclk/aclk_util.h
aclk/https_client.c
aclk/https_client.h

Implements getting data and parsing them from new `/env` endpoint. This will be used in later PRs
ACLK
aclk_env should be properly populated by data from the response from the cloud. Can test with production cloud.
The agent should connect to the cloud successfully.

implements ACLK env endpoint

---

aclk/aclk.c
aclk/aclk_otp.c
aclk/aclk_otp.h
aclk/aclk_tx_msgs.c
aclk/aclk_util.c
aclk/aclk_util.h

Updates password endpoint to match specs of New Architecture.
- Parse response of password endpoint in new format
- Use topics given to us from cloud instead of ones hardcoded in the agent.
ACLK
Connects to cloud without issue,

ACLK Passwd endpoint update

---

.github/workflows/checks.yml

Report dirty files
build
creating a PR into this branch that adds a dirty file should test this change

Report porcelain output

---

docs/guides/monitor/anomaly-detection.md
docs/guides/monitor/raspberry-pi-anomaly-detection.md

we made a change in the collector then means users need 0.0.38 now.

bump to netdata-pandas==0.0.38

---

claim/README.md
docs/collect/application-metrics.md
docs/collect/how-collectors-work.md
docs/guides/monitor/anomaly-detection.md
docs/guides/monitor/lamp-stack.md
docs/guides/monitor/process.md
docs/guides/monitor/raspberry-pi-anomaly-detection.md
docs/guides/python-collector.md
docs/overview/netdata-monitoring-stack.md
docs/overview/what-is-netdata.md
docs/quickstart/infrastructure.md
docs/quickstart/single-node.md
packaging/installer/README.md

A follow-up to #10995. There's already a redirect in place, but changing links to the new location is always preferred.
area/docs

Remove links to old install doc

---

collectors/python.d.plugin/Makefile.am
collectors/python.d.plugin/README.md
collectors/python.d.plugin/python.d.conf
collectors/python.d.plugin/zscores/Makefile.inc
collectors/python.d.plugin/zscores/README.md
collectors/python.d.plugin/zscores/zscores.chart.py
collectors/python.d.plugin/zscores/zscores.conf
web/gui/dashboard_info.js

Python based collector that computes rolling, smoothed, zscores for charts or dimensions. Uses the netdata /data rest api endpoints to do as little computation as possible in python and so be lower overhead on system than the anomalies collector. 
/collectors/python.d.plugin/zscores/
Tested locally on development nodes. 
More details in README of the collector.

Zscores python collector

---

collectors/statsd.plugin/README.md
collectors/statsd.plugin/k6.conf
collectors/statsd.plugin/k6.md

- docs (yay)
- improvements on the chart organization thanks to feedback from @Ferroin 💪

K6 quality of life updates

---

collectors/COLLECTORS.md

Add Third-party collector: nextcloud plugin
\+ fix a typo in docs
Docs
I'm not the author, it's @arnowelzel

Add Third-party collector: nextcloud plugin

---

claim/README.md
packaging/installer/methods/kickstart-64.md
packaging/installer/methods/kickstart.md
packaging/installer/methods/manual.md

As requested, adding in the parameters required to claim a node immediately after installation as part of using `kickstart.sh` or `kickstart-static64.sh` or calling `netdata-install.sh` manually.
area/docs
area/packaging

Add documentation for claiming during kickstart installation

---

collectors/ebpf.plugin/ebpf_cachestat.c

As we discussed in PR https://github.com/netdata/netdata/pull/10855, this PR is changing a chart type to give more meaningful information for users.
ebpf.plugin
1 - Compile this branch
2 - Check if the changed chart is showing lines instead stacked

Change eBPF chart type

---

docs/quickstart/infrastructure.md

Fixed a single typo in documentation

---

health/REFERENCE.md

Fixes: #11085
`health/`
No tests needed.

health: clarify which health configuration entities are required / optional

---

daemon/main.c

A small improvement on the previous agent crash detection
If the shutdown function is called, rename the generated file from `.agent_crash` to `.agent_incomplete_shutdown`. 
If the shutdown is interrupted, on restart the `agent_incomplete_shutdown` will be detected and an INCOMPLETE_SHUTDOWN event will be generated instead of a CRASH event
Note: this only applies when agent anonymous statistics is enabled
agent
- The CRASH event is generated when the agent is killed or terminated abnormally
- Try to kill the agent if it takes a long time to shutdown
- The file `var/lib/netdata/.agent_incomplete_shutdown` will be created and detected on the next agent restart

Add an event when an incomplete agent shutdown is detected

---

Makefile.am
configure.ac

Don't use handwritten makefiles from git submodules. Build it by netdata build system for netdata.
Fixes #10971
autotools build
CI is pretty much the best test. Build with Legacy / NG

build mqtt_websockets with netdata autotools

---

aclk/aclk_util.c

smallest PR ever
@stelfrag noticed typo in log that is quite common with ACLK-NG

minor - fixes typo in ACLK-NG log

---

collectors/python.d.plugin/README.md
daemon/config/README.md
docs/contributing/contributing-documentation.md
docs/dashboard/dimensions-contexts-families.mdx
docs/dashboard/select-timeframes.mdx
packaging/docker/README.md

The GitHub Action that runs on the Learn site pinged me about a few broken links in the docs.

Fix broken links in various docs

---

docs/dashboard/dimensions-contexts-families.mdx

Sadly, I missed one broken link in #11109. A follow-up.
area/docs

Fix broken link in dimensions/contexts/families doc

---

collectors/cgroups.plugin/sys_fs_cgroup.c

SSIA
See https://github.com/netdata/netdata/pull/11102#pullrequestreview-654707106
cgroups plugin

Remove an unnecessary check for cgroup v1

---

aclk/aclk.c

Fixed typo.
```
Successfull -> Successful
```

Fix typo in aclk.c

---

daemon/main.c

These options have been deprecated for a long time and they are probably not used anywhere any more.
CI

Remove deprecated options.

---

README.md
packaging/installer/methods/packages.md

Update news in main README for latest release

---

docs/monitor/enable-notifications.md

Add Microsoft Teams to supported notification endpoints

---

daemon/analytics.c

Only report the `exit_code` when anonymous statistics script fails. Fixes a coverity report.
Analytics

Only report the exit code when anonymous statistics script fails

---

Makefile.am
configure.ac
contrib/debian/rules
netdata-installer.sh
netdata.spec.in

The modified options are set only by the netdata-installer.sh script. The paths always point to the correspondent `externaldeps/xxx` directory when the options are specified.
CI builds

Compile/Link with absolute paths for bundled/vendored deps.

---

aclk/README.md
docs/anonymous-statistics.md

We're adding some links to the company's new data privacy page to condense and clarify the messaging.
area/docs

Add links to data privacy page

---

collectors/apps.plugin/apps_groups.conf

This PR adds support to apps_groups.conf for a couple of very common blockchain technologies. 
Next step is to explore how to gether metrics from the blockchain nodes themselves, starting from Ethereum and blockchain

Decentralized

---

.github/workflows/build-and-install.yml

SSIA
area/ci
New CI check passes.

Add openSUSE 15.3 CI checks.

---

.github/CODEOWNERS

Doing this so that I can keep track of open PRs and be able to review
them quickly.
N/A
N/A
N/A

Add vkalintiris as a code owner for more components

---

.github/workflows/packaging.yml
packaging/scripts/install.sh

Add openSUSE 15.3 package builds.

---

collectors/python.d.plugin/mysql/mysql.chart.py
collectors/python.d.plugin/smartd_log/smartd_log.chart.py
collectors/python.d.plugin/zscores/zscores.chart.py

Discovered several invalid contexts working on netdata/product#2104.
Not needed.

fix various python modules charts contexts

---

collectors/COLLECTORS.md
docs/netdata-security.md
packaging/installer/methods/source.md

Fixes some issues I found in the docs while reading through them.

Fix tiny issues in docs

---

.gitignore

Adds some more entries to gitignore that helped with my dev flow.

Add some more entries to gitignore

---

aclk/aclk.c
aclk/aclk_rx_msgs.c

CID371885 and CID371884 fixes.

Fixes coverity errors in ACLK

---

daemon/analytics.c

Fixed typo.
```
existance -> existence
```

Fix typo in analytics.c

---

database/engine/pagecache.c

If the page cache manager can not reserve the requested number of
pages, it sleeps based on an exponential-backoff value. Normally, this
value is a couple milliseconds. However, in rare cases the sleep duration
can grow up to several seconds. This patch logs an error message
whenever the sleep period is more than 1 second.

Log message when the page cache manager sleeps for more than 1 second.

---

.github/workflows/dashboard-pr.yml
web/gui/bundle_dashboard.py

Properly handle the file list for updating the dashboard.

---

health/Makefile.am
health/health.d/geth.conf

add geth default config

---

.github/CODEOWNERS

Remove myself from CODEOWNERS as I can no longer provide meaningful reviews

CODEOWNERS: Remove knatsakis

---

collectors/statsd.plugin/statsd.c

We will use configuration filenames as module names for stock configuration and `synthetic_chart` otherwise.
Fixes #11388
statsd.plugin
- create user config with synthetic charts.
- send [k6 metrics](https://github.com/netdata/netdata/blob/master/collectors/statsd.plugin/k6.conf), user synthetic charts metrics, some random metric.
- ensure `/api/v1/info` contains the following statsd.plugin modules: k6.conf, synthetic_chart, private_chart, stats.
<details>
<summary>curl -s localhost:19999/api/v1/info</summary>
```cmd
[ilyam@pc ~]curl -s localhost:19999/api/v1/info | jq '.collectors[] | select(.plugin=="statsd.plugin")'
{
"plugin": "statsd.plugin",
"module": "stats"
}
{
"plugin": "statsd.plugin",
"module": "k6.conf"
}
{
"plugin": "statsd.plugin",
"module": "synthetic_chart"
}
{
"plugin": …
```

Use only stock configuration filenames as module names

---

web/gui/custom/README.md

The documentation page of [Custom Dashboards](https://learn.netdata.cloud/docs/agent/web/gui/custom) had some broken links which had to be fixed.
Documentation on Custom Dashboards.
Validate docs and confirm links are working
N/A

replaced reference to raw.githubuser to a relative path

---

aclk/aclk_charts_api.c

In error case (if protobuf fails to generate payload) query would not be queued. Query queue therefore never takes ownership of the ptr leading to that memory being lost.
ACLK

Fix CID372233 to CID 372236

---

database/sqlite/sqlite_aclk.c

Address coverity report (6 issues)
** CID 372248:  Uninitialized variables  (UNINIT)
** CID 372246:  Uninitialized variables  (UNINIT)
** CID 372245:  Uninitialized variables  (UNINIT)
** CID 372243:  Uninitialized variables  (UNINIT)
** CID 372247:  Error handling issues  (CHECKED_RETURN)
** CID 372244:  Incorrect expression  (MISSING_COMMA)
database
- Coverity check after the PR

Address coverity reported issues  372243 - 372248

---

collectors/apps.plugin/apps_groups.conf

Add terra related binaries to blockchains apps groups
Apps groups configuration file
Terra is a blockchain protocol that provides fundamental infrastructure for a decentralized economy and enables open participation in the creation of new financial primitives to power the innovation of money.
The Terra blockchain is secured through distributed consensus over native staked asset Luna, and supports the issuance of price-tracking stablecoins (TerraKRW, TerraUSD, etc.) that are pegged to major world currencies. Smart contracts on Terra run on WebAssembly and can take advantage of core modules like on-chain swaps, price oracle, and staking rewards to power modern DeFi apps. Through fiscal policy managed by community governance, Terra is a democratized economy regulated by its users.
Terra Core …

Add terra to blockchains apps groups

---

Makefile.am
aclk/aclk_charts_api.c
aclk/aclk_charts_api.h
aclk/aclk_query.c
aclk/aclk_query_queue.c
aclk/aclk_query_queue.h
aclk/aclk_util.c
aclk/aclk_util.h
aclk/schema-wrappers/node_info.cc
aclk/schema-wrappers/node_info.h
aclk/schema-wrappers/schema_wrappers.h

Adds NodeInstanceInfo API to be used for new cloud architecture
ACLK

Adds NodeInstanceInfo API

---

packaging/installer/methods/synology.md

Fixes: #8343
`docs/`
Not needed. The fix confirmed to be working in https://github.com/netdata/netdata/issues/8343#issuecomment-596210901 and https://github.com/netdata/netdata/issues/8343#issuecomment-640038811.

update "Install Netdata on Synology" guide

---

health/health.d/ram.conf

Fixes #9059
`health/`
Tested in https://github.com/netdata/netdata/pull/9793

Fix ram level alarms

---

collectors/python.d.plugin/postgres/postgres.chart.py

Fixes: #11453
Postgres plugin
Create a replication slot on a standby server. Before this PR you got this error in postgres logs:
> ERROR:  recovery is in progress
> HINT : WAL control functions cannot be executed during recovery.
After this PR the error should not appear and the charts will be created.
I applied the same fix from https://github.com/OPMDG/check_pgactivity/pull/246 
So thanks for check_pgactivity project and maintainers.

Fix postgres replication_slot chart on standby

---

docs/dashboard/visualization-date-and-time-controls.mdx

the selection of timeframes is covered very well already above. this link was from before datetime picker and is now broken so best to remove it.

remove broken link

---

.github/scripts/pkg-test.sh
backends/WALKTHROUGH.md
backends/prometheus/README.md
build_external/scenarios/aclk-testing/agent_netdata.conf
collectors/statsd.plugin/statsd.c
exporting/WALKTHROUGH.md
exporting/prometheus/README.md
health/notifications/alarm-notify.sh.in
health/notifications/health_alarm_notify.conf
web/api/netdata-swagger.json
web/api/netdata-swagger.yaml
web/gui/dashboard/dashboard.html
web/gui/dashboard/demo.html
web/gui/dashboard/demo2.html
web/gui/dashboard/demosites.html
web/gui/dashboard/demosites2.html
web/gui/dashboard/index-node-view.html
web/gui/dashboard/infographic.html
web/gui/dashboard/tv-react.html
web/gui/dashboard/tv.html
web/server/web_client.c

Replace "NetData" with "Netdata"

Clean netdata naming

---

.travis/create_artifacts.sh
.travis/generate_changelog_for_nightlies.sh
.travis/nightlies.sh

Reverts netdata/netdata#11383
Does not actually work as intended (it’s always acting as if there were no changes).

Revert "add Travis ctrl file for checking if changes happened"

---

.github/workflows/review.yml

Exclude bundled dashboard files from eslint checks.

---

packaging/docker/Dockerfile
packaging/docker/README.md
packaging/docker/run.sh

Reverts netdata/netdata#10683
Seems to have broken things for some existing installs.
Fixes: #11494

Revert "Add support for runtime configuration of UID/GID for Netdata user."

---

.github/scripts/docker-test.sh
.github/workflows/docker.yml

This adds some extra steps to the Docker CI checks to verify that the image itself starts up properly and is actually usable.
area/ci
CI passes.

Add extra verification to Docker builds.

---

.github/workflows/dashboard-pr.yml

This should (finally, truly) fix the issues with automatic PR generation for dashboard releases not working correctly.
area/ci
Not testable until it’s merged and a new dashboard release is created.

Update handling of dashboard PR genertion to handle file deletions.

---

health/REFERENCE.md

Fixes: #10996
`health/`
Not needed

docs(health): add a note about handling backslashes in configuration files

---

CMakeLists.txt
Makefile.am
database/rrd.h
database/rrdhost.c
database/rrdset.c
database/sqlite/sqlite_aclk.c
database/sqlite/sqlite_aclk.h
database/sqlite/sqlite_aclk_chart.c
database/sqlite/sqlite_aclk_chart.h
database/sqlite/sqlite_functions.h

Add initial support for chart/dimension update messages
aclk, database
- The code is not active yet (it is tested with the new architecture in a separate branch)

Add chart message support for ACLK new architecture

---

database/sqlite/sqlite_aclk.h
database/sqlite/sqlite_aclk_chart.c

- Check return code for uuid_parse in various places
- Fix memory leak
- Fix Uninitialized scalar variable issue
aclk, database
- Coverity issues resolved

Address coverity report issues CID_373247-373251

---

.github/workflows/dashboard-pr.yml

Fix branch handling for automated dashoard PRs.

---

.github/CODEOWNERS

Add @DShreve2 to CODEOWNERS
.github
Not needed

add DShreve2 to code owners

---

collectors/proc.plugin/proc_net_stat_synproxy.c

The number of entries in `/proc/net/stat/synproxy` is [always zero](https://elixir.bootlin.com/linux/latest/source/net/netfilter/nf_synproxy_core.c#L295). We delete the confusing chart.
proc plugin

Remove unused synproxy chart

---

.github/CODEOWNERS

Remove @ktsaou from Github's `CODEOWNERS` file. @Ferroin will be added as a reviewer for files that do not belong to any other code owner.

Update global code owners

---

web/gui/dashboard_info.js

This PR adds dashboard info for [apps.plugin](https://github.com/netdata/netdata/tree/master/collectors/apps.plugin#appsplugin) collector's charts.
`web/`
Install this PR; check the apps.plugin charts; ensure the info is on the dashboard.

add apps.plugin charts descriptions

---

collectors/python.d.plugin/varnish/varnish.chart.py

Fixes #11550
`python.d/varnish`
Tested manually using `varnishstat -1` output from https://github.com/netdata/netdata/issues/11550#issuecomment-931194860

fix varnish VBE parsing

---

.github/CODEOWNERS

For the normal Agent SRE stuff.
area/ci
n/a

Add @iigorkarpov to CODEOWNERS.

---

collectors/proc.plugin/proc_net_rpc_nfsd.c

ssia
`collectors/proc.plugin`
Not needed

fix proc nfsd "proc4ops" chart family

---

database/sqlite/sqlite_aclk_alert.c

Fixes coverity CID 373610 by moving the initial generation of `snapshot_proto` inside the loop.
New cloud architecture
Since on local coverity checks I did not get this error, if anyone has, please let me know. Snapshot functionality has been tested, both in chunks of 10 and 1 (to force to fit in even chunks). The code is still under flag in master, but will be deployed in stress and staging.

Fix coverity CID #373610

---

aclk/aclk_query.c

Fixed typo.
```
lenght -> length
```

Fix typo in aclk_query.c

---

.github/CODEOWNERS

Part of welcoming our newest agent SRE.
area/ci
n/a

Add @maneamarius to CODEOWNERS.

---

aclk/aclk.c

minor - popocorn no more

---

.github/labeler.yml

add *.mdx to labeler config

---

database/sqlite/sqlite_aclk_chart.c

When no local metrics are found the retention duration is incorrect. This PR adds a check so
that the retention duration is set to zero in that case. 
aclk, database
- Code has been tested in the testing and staging environment

Fix retention message duration when no local metrics are found

---

collectors/ebpf.plugin/README.md

This is the second PR updating eBPF documentation before next release.
ebpf.plugin
Documentation
Review links and verify possible problems with typo and grammar.

Update eBPF documenation (Filesystem and HardIRQ)

---

aclk/aclk_rx_msgs.c

In case D_ACLK is used we log it as string

fix log if D_ACLK is used

---

aclk/aclk_rx_msgs.c
database/sqlite/sqlite_aclk_alert.c

- Fixes host hop count
- Remove a warning message during health log initialization
aclk, database
- Already tested in testing and staging environment

Fix host hop count reported to the cloud

---

docs/dashboard/interact-charts.mdx

Fix link to new charts.

---

database/rrdset.c
database/sqlite/sqlite_aclk.c

- Do not send hidden dimensions via ACLK (new cloud architecture)
- Add cleanup for dimensions that have been deleted but not send via ACLK
- For hosts that have been deleted or after 7 days of being unprocessed
ACLK, database
- Code has been tested (testing and staging environment)

Skip sending hidden dimensions via ACLK

---

database/rrdhost.c
database/sqlite/sqlite_aclk_chart.c

- Enables the new ACLK sync code that will create 
- The necessary database tables for ACLK sync
- Spawn threads that will handle
- Metadata changes that need to be synced with the cloud
- Charts and dimensions
- Alert state transitions
- Do housekeeping and cleanup when needed
ACLK, database
- Code has been tested (in testing and staging environments)

Remove feature flag for ACLK new cloud architecture

---

docs/guides/step-by-step/step-05.md

The `./edit-config health.d/example.conf` command has been added to the "Write your first health entity" section.
Docs/Guides
n/a

Add command for new health entity file.

---

.github/workflows/build.yml
packaging/installer/kickstart-static64.sh
packaging/installer/methods/kickstart-64.md

Fix the new static archive verification job.

---

.github/data/build-matrix.json
.github/scripts/pkg-test.sh
.github/workflows/packaging.yml
.github/workflows/repoconfig-packages.yml
packaging/installer/install-required-packages.sh

This adds Oracle Linux 8 to our CI and package builds.
area/packaging
CI checks pass on this PR.

Add Oracle Linux 8 to CI and package builds.

---

docs/dashboard/interact-charts.mdx

Link correction picked up by broken link checker.
Docs
n/a

Fix broken link in charts.mdx

---

.travis.yml

Fix for Travis build, the pip command points to pip2 for some reason, instead of pointing to pip3 as it should.
TravisCI build file

specify pip3 when installing git-semver package

---

ml/Host.cc

Run ML and check the precision of the anomaly rate chart.

Use two digits after the decimal point for the anomaly rate.

---

database/sqlite/sqlite_aclk_alert.c
database/sqlite/sqlite_aclk_chart.c
database/sqlite/sqlite_aclk_node.c

Prevent from using `wc` struct, if it might not exist.
ACLK

Don't use wc struct if it might not exist

---

.github/CODEOWNERS

add kickoke to docs codeowners

---

daemon/main.c
database/rrdhost.c
database/sqlite/sqlite_aclk.c
database/sqlite/sqlite_aclk.h
database/sqlite/sqlite_functions.c
database/sqlite/sqlite_functions.h

- Improve the ACLK sync thread shutdown sequence
-  Sets a `shutdown in progress` flag so that no more commands will be accepted and the current queue of the commands will be ignored
- Adds a -W parameter to check database for corruption and also attempt to fix it. 
- Adds a -W parameter to compact the database
- During startup if a database corruption is detected, it will attempt to fix it automatically (only applies
to the dimension and chart tables)
Parameters added (in `netdata -h`) 
```
-W check-sqlite-database        Check metadata database integrity and exit.
-W fix-sqlite-database          Check metadata database integrity, fix if needed and exit.
-W compact-sqlite-database      Reclaim metadata database unused space and exit.
```
aclk sync, database
- Stop the agent and execute …

Add commands to check and fix database corruption

---

docs/guides/deploy/ansible.md

Fixed typos. 
However, the document needs some refinement (adding to my backlog). 
The document contains steps in form of paragraphs, instead of using ordered lists. 
It is also a bit generic at times, for example lines 49-51. 
"First, download the
[playbook](https://github.com/netdata/community/tree/main/netdata-agent-deployment/ansible-quickstart), move it to the
current directory, and remove the rest of the cloned repository, as it's not required for using the Ansible playbook."
What does 'current' mean in this context? Which file should be edited and which ones deleted? This will be explained later in the text, but it's not obvious from the beginning.

Updating ansible steps for clarity

---

collectors/apps.plugin/apps_groups.conf

Add [consul](https://www.consul.io/) to apps_groups.conf
collectors/apps.plugin
Not needed

feat(apps.plugin): add consul to apps_groups.conf

---

packaging/makeself/build-static.sh

SSIA
area/packaging
CI checks pass on this PR

Bump static builds to use Alpine 3.15 as a base.

---

.github/workflows/build.yml

SSIA
area/ci
Merge and wait for the next release (not really any other way to test it...).

Fix token name in release draft workflow.

---

README.md

Update nightly badge link

---

contrib/debian/control

This simplifies transitioning from distor-provided packages to our official packages.
area/packaging
Proper behavior verified locally.
Fixes: #11853

Explicitly conflict with distro netdata DEB packages.

---

packaging/installer/netdata-updater.sh

Split out from #11753 as requested.
This is needed for portability reasons for support for binary packages.
More specifically, the changes involve:
* Updating `source` to `.`. This is a functional no-op given how we are using `source`.
* Replacing `==` in conditionals with `=`. This is also a functional no-op for our current usage in the script.
* Remove usage of `local`. We’ve got things set up so that there is no overlap in variable names so there is no need to declare variables as local.
* Replaced regex-based conditionals with equivalents using `grep`. These are slightly less efficient, but functionally somewhat more flexible.
* Replaced instances of array usage with equivalents using a temporary file and individual variables. The net result is more compact, but arguably easier to …

Make netdata-updater.sh POSIX compliant.

---

health/REFERENCE.md

Add an example showing how to derive a Z Score based alarm.
Added following this question in the community forums: https://community.netdata.cloud/t/zscore-on-health-alarm-calc/1884

add z score alarm example

---

aclk/README.md
claim/README.md
cli/README.md

Bigger changes to documentation will come after Legacy removal.

Minor ACLK docu updates

---

docs/netdata-security.md

The list was broken because Markdown didn't recognize the hierarchy level of the nested list.

Fixed formatting issues.

---

docs/guides/monitor/anomaly-detection-python.md
docs/guides/monitor/anomaly-detection.md
docs/guides/monitor/raspberry-pi-anomaly-detection.md
docs/guides/monitor/visualize-monitor-anomalies.md

Move what is currently at 
https://github.com/netdata/netdata/blob/master/docs/guides/monitor/anomaly-detection.md
to:
https://github.com/netdata/netdata/blob/master/docs/guides/monitor/anomaly-detection-python.md
And copy latest docs from:
https://github.com/netdata/netdata/blob/master/ml/README.md
to:
https://github.com/netdata/netdata/blob/master/docs/guides/monitor/anomaly-detection.md
This will essentially use the new ml docs for this link: https://learn.netdata.cloud/guides/monitor/anomaly-detection
A separate PR will be made in `netdata/learn` to clean up any titles etc in learn as needed.
docs

Clean up anomaly-detection guide docs

---

packaging/installer/netdata-updater.sh

SSIA
area/packaging
CI passes, and when run locally the errors outlined in the linked issue do not show up.
Fixes: #11884

Fix handling of agent restart on update.

---

exporting/WALKTHROUGH.md

Some codes in this tutorial don't work directly and need slight modification
Tutorials
I went through the tutorial myself and all was good; of course a CI can be added but that seems overkill for a tutorial
Again, I just went through the tutorial, and got no errors.

Fix slight errors

---

collectors/python.d.plugin/anomalies/README.md

tiny doc's change to add note with link to guide for installing/using on Pi
/docs/collectors

add note with link to guide for using on Pi

---

exporting/README.md

Quick fix so that the title of this doc in the Learn sidebar isn't a very unhelpful **Reference guide**.
area/docs

Fix title of exporting reference doc

---

packaging/DISTRIBUTIONS.md

Add information about Gentoo to DISTRIBUTIONS.md
DISTRIBUTIONS.md
Netdata is available in Gentoo. See https://packages.gentoo.org/packages/net-analyzer/netdata

Indicate availability on Gentoo

---

ml/Config.cc
ml/Config.h
ml/Host.cc
ml/ml.cc
ml/ml.h
web/api/web_api_v1.c

Use `/info` to expose ml-configuration that remains static throughout an agent's execution. Provide run-time information about ML through a new `/ml-info` endpoint.
area/ml
CI + checked manually the output of each endpoint with ML enabled/disabled.
Swagger information will be updated with a follow-up PR.

Provide runtime ml info from a new endpoint.

---

health/notifications/pagerduty/README.md

We've engaged with PagerDuty on a tiny bit of co-marketing, and they had some requests for updates to this document, including a new screenshot and a bit more in the way of instructions.
area/health

Improve PagerDuty notification doc

---

.github/labeler.yml

ssia
Noticed that no label has been added to #11919
ci
Not needed

chore(ci): add area/claim to PR labeler

---

health/notifications/alarm-notify.sh.in

This PR is part of the enhancement needed for issue [#2614](https://github.com/netdata/product/issues/2614).
Update the link for community forum in alerts notification, along with its wording, in order to redirect the user to the topic of the specific alert
Alarm notification
None

chore: update community link of alert notifications

---

collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py

fix [#10264](https://github.com/netdata/netdata/issues/10264)
(the previos [PR](https://github.com/netdata/netdata/pull/11854) was cleaned by pull-bot :man_facepalming:)
<sub><img src="https://user-images.githubusercontent.com/4775299/87437657-e7332b00-c5ee-11ea-958d-589dfb19d72c.png" alt=" " width="10" height="9"> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

nvidia_smi_chart.py : fixed username for not-local users

---

aclk/aclk.c
aclk/aclk_rx_msgs.c
aclk/aclk_rx_msgs.h

Uses hash map to optimize message name to function translation.

Optimize rx msg name resolution

---

collectors/python.d.plugin/spigotmc/spigotmc.chart.py

spigotMC: fix tps decode, add memory usage chart
spigotMC

fix tps decode, add memory usage chart

---

collectors/python.d.plugin/postgres/postgres.chart.py

Consider an example:
```
test=# create materialized view m1 as select * from pg_class;
SELECT 465
test=# create index m1_oid on m1(oid);
CREATE INDEX
```
In this case, we our DB size increased by the size of mat. view m1 and its index m1_oid:
```
test=# \dm+ m1
List of relations
Schema | Name |       Type        | Owner | Persistence | Access method |  Size  | Description
--------+------+-------------------+-------+-------------+---------------+--------+-------------
nik    | m1   | materialized view | nik   | permanent   | heap          | 104 kB |
(1 row)
test=# \di+ m1_oid
List of relations
Schema |  Name  | Type  | Owner | Table | Persistence | Access method | Size  | Description
--------+--------+-------+-------+-------+-------------+---------------+-------+-------------
nik    | …
```

Postgres: mat. views considered as tables in table size/count chart

---

web/gui/dashboard_info.js

As discussed with @ilyam8, I changed a link that was no longer working to the new working one

Fix a broken link in dashboard_info.js

---

database/sqlite/sqlite_aclk_alert.c

This PR passes the `host->health_enabled` status to the `enabled` attribute of the `AlarmLogHealth` message. It will be used by the cloud to detect agents (or child nodes) with no health running, so as to not then send Start streaming or snapshot messages.
New cloud architecture
Right now cloud backend does not check this attribute. Testing will occur when the functionality is enabled, but test can occur by inspecting the `AlarmLogHealth` message in various situations:
1) Single agent with health enabled/disabled.
2) Parent - child setup with the parent enabling/disabling health for the child in `stream.conf`.
3) Similar testing to https://github.com/netdata/netdata/pull/11928 by adjusting `TIMER_PERIOD_MS` and having children connect before `host` is connected to a worker thread. In that …

Find host and pass host->health_enabled to cloud AlarmLogHealth message

---

collectors/statsd.plugin/README.md

Fixed duplicate H1 & title to fix the table of contents

Fixed formatting

---

packaging/installer/netdata-updater.sh

Fixes: #11983
packaging/
Run the updater manually.

fix(updater): checksum validation for static build

---

collectors/apps.plugin/apps_plugin.c
collectors/cgroups.plugin/cgroup-network.c
collectors/cups.plugin/cups_plugin.c
collectors/ebpf.plugin/ebpf.c
collectors/freeipmi.plugin/freeipmi_plugin.c
collectors/nfacct.plugin/plugin_nfacct.c
collectors/perf.plugin/perf_plugin.c
collectors/slabinfo.plugin/slabinfo.c
collectors/xenstat.plugin/xenstat_plugin.c
tests/profile/test-eval.c

This way each collector does not have to redefine the symbols.
collectors
Local build & CI jobs.

Use libnetdata/required_dummies.h in collectors.

---

collectors/proc.plugin/sys_class_infiniband.c

Fix infiniband counter value that needs to be multiplied by 4 as per [Kernel documentation](https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-class-infiniband).
Fixes #11991

Fix ib counters

---

web/gui/dashboard_info.js

This PR fixes a small typo (`connect -> connected`) on the SpigotMC part of the dashboard

Fix typo in the dashboard_info.js spigot part

---

packaging/installer/kickstart.sh
packaging/installer/methods/kickstart.md

We should obviously use the correct command to uninstall a package.
Verified by local testing.

Fix cleanup from a failed DEB install.

---

.travis.yml

Fixes an issue with how we’re generating tags for releases.
area/ci
n/a

Fix passing of version to GHA release workflow.

---

README.md
aclk/README.md
claim/README.md
collectors/README.md
collectors/REFERENCE.md
collectors/ebpf.plugin/README.md
docs/Add-more-charts-to-netdata.md
docs/guides/monitor/pi-hole-raspberry-pi.md
docs/guides/step-by-step/step-00.md
health/notifications/pushbullet/README.md
packaging/installer/methods/kickstart.md
packaging/installer/methods/manual.md
packaging/installer/methods/synology.md

fix(docs): unresolved file references

---

netdata-installer.sh

No code changes, just tweaks to notes.
Not applicable.

fix typo, tidy up sentence

---

health/notifications/alerta/README.md

I updated the link to the screenshot and improved the copy. 
However, I need a bit more input for the last sentence in the note (line 78). 
I left the Google Analytics link, because I figured that we will sweep them out in a different initiative.
If you feel like another person would be a better reviewer, please add them to the PR.

Updated formatting issues and copy

---

packaging/installer/kickstart.sh
packaging/installer/methods/kickstart.md

Add native installation support for Rocky Linux
Run kickstart.sh in Rocky Linux and make sure it was installed via rpm package from netdata-repo-edge

add native installation for rockylinux

---

packaging/installer/methods/synology.md

docs: add a note that the "Install Netdata on Synology" is maintained by community

---

docs/guides/export/export-netdata-metrics-graphite.md
docs/guides/monitor/lamp-stack.md
docs/guides/monitor/pi-hole-raspberry-pi.md
docs/guides/step-by-step/step-00.md
exporting/prometheus/README.md
packaging/installer/README.md
packaging/installer/methods/kickstart.md

This PR is a clean version of #12090. 
The rebase had gone wrong.

Docs improvement: Added interactive kickstart scripts where possible

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
.github/ISSUE_TEMPLATE/FEAT_REQUEST.yml

This PR adds a feature request form. See [the rendered version](https://github.com/ilyam8/netdata/blob/github_add_feature_from/.github/ISSUE_TEMPLATE/FEAT_REQUEST.yml).
The wording is subject to change I think, my goal was to add all the _sections_ we want users to describe.
Ensure there are no syntax errors by checking the rendered version in my fork.

add feature request form

---

contrib/debian/rules
netdata-installer.sh
netdata.spec.in
packaging/installer/UPDATE.md
packaging/installer/functions.sh
packaging/installer/kickstart.sh
packaging/installer/netdata-updater.sh
packaging/makeself/install-or-update.sh

Because it is in fact broken.
n/a

Revert "Overhaul handling of auto-updates in the installer code. (#12076

---

health/health.c

This PR aims to solve the case of how we can inform the cloud with new architecture of a change in an alert when it's chart becomes obsolete.
Right now, if a chart of a raised alert goes away, the agent "hides" it from api calls etc. But it does not produce an internal health event log for it, rather it keeps the last known one.
Since communication with the cloud via the new architecture happens with alert events, the last known state has been sent to the cloud alas then the consistency of what we show on the agent vs on the cloud is broken. By creating a REMOVED event and sending it to the cloud we try to keep consistency between the two.
Re-creating such a scenario can be done as follows:
1) Use a usb stick. Create a large enough file to fill up it's space (`fallocate -l XXG filename` …

Create a removed alert event if chart goes obsolete

---

claim/README.md

Fixes #11933
Not needed, documentation changes only

docs: document the issue with seccomp and claiming

---

docs/anonymous-statistics.md
docs/netdata-security.md

Fixed two small typos I found while reading the documentation.
Fix "JavaScript" in 'docs/anonymous-statistics.md'
Fix "Netdata" in 'docs/netdata-security.md'
First contribution to the Netdata project, pull request is also used to get familiar with the process.

Fix two small typos in documentation

---

daemon/main.c

When this option is specified the agent will not close any inherited open
FDs. This option is useful when starting the agent under profiling tools that
maintain their own file descriptors, eg. to save profiling data.
Local test by adding an explicit fatal() to the relevant code that closes the FDs (+CI build/test jobs).

Add -W keepopenfds option.

---

configure.ac

Remove NETDATA_WITH_UUID def because it's not used anywhere.

---

aclk/aclk_util.c
aclk/aclk_util.h
daemon/global_statistics.c

Remove unused NETDATA_NO_ATOMIC_INSTRUCTIONS macro

---

.github/CODEOWNERS

Remove @vkalintiris from sre-related paths.
N/A.

Update github's code owners configuration.

---

.github/workflows/build.yml
.github/workflows/coverity.yml
.github/workflows/dashboard-pr.yml
.github/workflows/docker.yml
.github/workflows/packaging.yml
.github/workflows/repoconfig-packages.yml

This tidy’s up our CI, first fixing a number of issues reported by yamllint and actionlint, and then overhauling the CI failure notifications to provide significantly more useful information.
area/ci

Assorted CI cleanup.

---

daemon/main.c

removes dead code that cannot be invoked anymore due to non existent defines
this was missed during ACLK Legacy removal

minor - remove dead code

---

aclk/aclk_query.c
aclk/aclk_query.h
aclk/aclk_query_queue.c
aclk/aclk_query_queue.h
aclk/aclk_stats.c
aclk/aclk_stats.h

aclk_processed_query_type chart was not including all messages from new cloud architecture. This alleviates that issue in an instant. Also reduces code needed to achieve that by almost half (line count)

Adds all query types to aclk_processed_query_type

---

aclk/aclk.c
aclk/aclk_rx_msgs.c
aclk/aclk_rx_msgs.h
aclk/aclk_stats.c
aclk/aclk_stats.h

Adds charts showing incoming cloud messages for new cloud protocol.
ACLK
Connect agent to cloud with new protocol used (check with `api/v1/aclk` check field `used-cloud-protocol == New`), in such case chart should show what messages are incoming from cloud.

Adds chart for incoming proto msgs in new cloud protocol

---

docs/guides/step-by-step/step-10.md

A little mistake :3
The T has been replaced by an X
n/a

Docs: Fix typo in step-10.md

---

aclk/aclk_tx_msgs.c

inform cloud about inability to satisfy request

---

docs/Running-behind-haproxy.md

Fixed a typo I found while reading through documentation in docs/docs/Running-behind-haproxy.md .
First contribution to the Netdata project, pull request is also used to get familiar with the process.

Fixed typos in docs/Running-behind-haproxy.md

---

packaging/installer/kickstart.sh

To avoid bogus false positives on macOS, FreeBSD, and cases on Linux systems where the user is specifying an install prefix.
Without these changes, trying to install on a FreeBSD or macOS system, or on a Linux system with the `--build-only` option and a custom install prefix, the kickstart script will incorrectly claim that there is an existing install even though there is not one.
With these changes, the above-mentioned cases will work correctly again.

Fix detection of existing installs.

---

daemon/system-info.sh

chore: remove unused variable in the system-info script

---

packaging/installer/functions.sh
packaging/installer/netdata-uninstaller.sh

Fix ${INSTALL_PREFIX} duplication issue in netdata-uninstaller.sh when running kickstart.sh with --uninstall flag and fix POSIX issue in functions.sh.
Verified manually  that kickstart.sh --uninstall works as expected.

fix uninstall using kickstart flag

---

docs/guides/monitor/anomaly-detection-python.md

Found a typo when reading the documentation, would like to do a contribution to correct it

Fix 'connect' typo anomaly-detection-python.md

---

daemon/system-info.sh

Related netdata/cloud-frontend#3036
Tested locally.

fix: returning 0 for CPU frequency when unknown

---

collectors/nfacct.plugin/README.md

libnetfilter_acct-dev package should be
libnetfilter-acct-dev

fix underscore in libnetfilter-acct-dev package

---

aclk/aclk.c
database/sqlite/sqlite_aclk_alert.c
database/sqlite/sqlite_aclk_alert.h
database/sqlite/sqlite_aclk_chart.c
database/sqlite/sqlite_aclk_chart.h
web/api/netdata-swagger.json
web/api/netdata-swagger.yaml

Breaking API change. Adds more information as was requested here https://github.com/netdata/netdata/issues/12217 but doesn't exactly copy the format suggested there.
PR is WIP and more data will be added.
- `netdatacli aclk-state`
- `netdatacli aclk-state json`
- `127.0.0.1:19999/api/v1/aclk-state`

Adds more info to aclk-state API call

---

.github/workflows/build.yml
.github/workflows/coverity.yml
.github/workflows/dashboard-pr.yml
.github/workflows/docker.yml
.github/workflows/packaging.yml
.github/workflows/release.yml
.github/workflows/repoconfig-packages.yml
.github/workflows/trigger-learn-update.yml

This is a simple systematic change to how the bodies of Slack notifications in our CI are handled so that we get proper multi-line error messages instead of one big blob of text.
n/a

Fix string handling for Slack CI notification bodies.

---

aclk/aclk_query.c
database/sqlite/sqlite_aclk_chart.c
database/sqlite/sqlite_functions.c

- Uses prepare statements to improve performance in heavily used statements
- Avoids buffer allocation when building small, predictable in size, queries
- Uses memory lookup to do node to host map for incoming cloud queries
- No added functionality to check.

Improve agent to cloud synchronization performance

---

database/sqlite/sqlite_aclk.c
database/sqlite/sqlite_aclk_alert.c
database/sqlite/sqlite_aclk_chart.c
database/sqlite/sqlite_aclk_node.c
database/sqlite/sqlite_functions.c

Replaces write locks with read locks in places where no host manipulation is done. 
Part of this will be tested in staging.

Replace write with read locks

---

.github/workflows/release.yml

Fix pushing version bump commits in release/nightly build workflow.

---

.github/labeler.yml

chore(ci): add area/ebpf to PR labeler

---

database/sqlite/sqlite_aclk_alert.c

This PR tries to fix the case mentioned in https://github.com/netdata/netdata/issues/12391 when the `host` structure is check on the `health_enabled` flag even if `host` is null. It also adds another try in this case to locate the `wc` structure.

Dont check host health enabled if host is null

---

.github/scripts/docker-test.sh

I’m genuinely not sure how this was working previously...
Docker CI passes on this PR.

Fix update/install commands in Docker image test code.

---

packaging/installer/netdata-updater.sh

POSIX shell script requires functions to be defined before first use.
n/a
Partially fixes: #12395

Reorder functions properly in updater script.

---

.github/workflows/packaging.yml

Fix packaging CI failure notifications to actually report all steps.

---

streaming/README.md

Docs: Fix broken link

---

web/api/netdata-swagger.json
web/api/netdata-swagger.yaml

Update the version of the Agent in the Swagger API
Check the version on the Swagger site

Update Agent version in the Swagger API

---

collectors/apps.plugin/apps_plugin.c

apps.plugin: fix for plugin sending unnecessary data in freebsd

---

collectors/statsd.plugin/Makefile.am
collectors/statsd.plugin/README.md
collectors/statsd.plugin/asterisk.conf
collectors/statsd.plugin/asterisk.md

ssia
The file shared by @ktsaou, he has been using it for a long time and it works with the recent version of Asterisk.

feat(statsd.plugin): add Asterisk configuration file with synthetic charts

---

collectors/ebpf.plugin/README.md

We are working to improve our documentation and create a more meaningful dashboard information, this PR is the first PR addressing this task.
The texts inserted here are actually in our dashboard, but they will be removed in next PR.
1. tests are not necessary, because we are only working with documentation.
The next PR will address content on dashboard related to these topics.
<details> <summary>For users</summary>
This PR is updating our documentation to give more information for users when they are monitoring file systems. We will have a PR that will create links for this documentation.
</details>

Add content for eBPF documentation

---

collectors/python.d.plugin/README.md

ssia, not relevant anymore.
Not needed.

docs(collectors/python.d): remove mention of compatibility with py2/py3

---

packaging/installer/netdata-updater.sh

Specifically, if there is a valid install type file _and_ the install is a binpkg-type install, we don’t need an environment file so we shouldn’t fail if one is missing.
Also adds better validation of the environment file before attempting to update when we do need it.
This can be trivially verified by trying to run the `netdata-updater.sh` script on a binpkg-based install. Without these changes it will fail, with them it will at least exit successfully (even if it does nothing).
Partially fixes: #12395

Allow updates without environment files in some cases.

---

aclk/aclk.c

Fixes #12409
Adds information about last connection time(if any), when was previous connection closed (if any), information when next connection attempt will be made(if offline and delaying reconnection)
hit `/api/v1/aclk-state`

Extend aclk-state

---

.github/CODEOWNERS

add suraj to codeowners

---

packaging/installer/netdata-updater.sh

Fixes: #12490
The first possible use of fd 3 before opened:
https://github.com/netdata/netdata/blob/0da8afbaff2101f788697aaa1f3b81df8e4ca00b/packaging/installer/netdata-updater.sh#L81
The 2nd:
https://github.com/netdata/netdata/blob/0da8afbaff2101f788697aaa1f3b81df8e4ca00b/packaging/installer/netdata-updater.sh#L829-L830
I think no tests are needed.

fix: open fd 3 before first use in the netdata-updater.sh script

---

.github/PULL_REQUEST_TEMPLATE.md

As @thiagoftsm and @Ferroin suggested: 
We include a list of our PRs in the release notes. However, when you click on a PR as a user, who isn't involved in the day to day business, you might not understand what the PR does. This PR introduces a new section within "Additional information" to provide additional context for our users. 
N/A
The `details` tag renders a dropdown section and the `summary` tag is used to provide a custom heading. 
Please review this PR as source code and not the rendered version. The `details` tag contains a comment with guiding questions on how to write a good `For users` section.
This PR introduces a summary section for users to understand Netdata PRs better. From now on, all PRs will have …

PR template: Include user information section

---

packaging/installer/kickstart.sh

Fix Bug reported in this issue https://github.com/netdata/netdata/issues/12154.
Install Netdata using kickstart on centos7 and verified that gpg error is resolved.
</details>

fix centos7 gpg key issue

---

.github/workflows/coverity.yml
coverity-scan.sh

Fix issues in the coverity scan script.
n/a

Fix coverity scan.

---

database/sqlite/sqlite_functions.c

Fixes #12567
Respect dimension hidden option when executing a query and building the dimension list directly from the metadata 
database
1. Setup parent - child 
2. Configure `cleanup orphan hosts after seconds = 30` in `netdata.conf`, `[global]` section
3. Start parent and child agents
4. Execute `localhost:19999/host/child/api/v1/data?chart=system.cpu&after=-30` on the parent
- Notice the dimension list returned that does not include the `idle` dimension
5. Shutdown the child and wait for the cleanup process to remove the child (at least 30 seconds)
6. Execute localhost:19999/host/child/api/v1/data?chart=system.cpu&after=-30` on the parent
- Notice the `idle` dimension is returned
Apply the PR and running the tests again should not return the `idle` dimension (unless explicitly asked by …

Respect dimension hidden option when executing a query 

---

.github/workflows/coverity.yml

It’s a bash script, not a POSIX sh script.
n/a

Fix invocation of the coverity script.

---

configure.ac

If we're building on MacOS, do not link with libatomic. Tries to solve the error `ld: library not found for -latomic`
We need some test builds on Mac both on x86 and arm if possible.
</details>

Check if libatomic can be linked

---

ml/Config.cc

https://github.com/netdata/netdata/pull/12574#issuecomment-1087934911
CI jobs

Enable streaming of anomaly_detection.* charts

---

ml/Host.cc

Required to fix the cloud dashboard menu.
N/A

Fix training/prediction stats charts context.

---

packaging/installer/kickstart.sh

This makes numerous improvements to how we are handling messaging to users in the kickstart script, especially around failure conditions.
n/a
The install process will provide much better error messages and information regarding what is going on.
</details>

Kickstart improved messaging

---

packaging/installer/kickstart.sh
packaging/installer/methods/kickstart.md

Add support for clean reinstall in kickstart script.
Installed netdata using kickstart using native, static and build methods, then used kickstart with clean reinstall flag.
</details>

add --reinstall-clean flag for kickstart.sh and update documentation

---

collectors/apps.plugin/apps_groups.conf

add `locust` to `apps_groups.conf`. 
[locust](https://docs.locust.io/) is a very popular load testing library.
Tested locally while running a locust load test.

add `locust` to `apps_groups.conf`

---

.github/workflows/cloud_regression.yml

Run cloud e2e tests when pushing to master against **master**, not **main**, as it previously was.

Trigger cloud intergration workflow for PRs and pushes against master

---

streaming/README.md

Update the docs to reflect the default settings for stream compression.
</details>

[Stream compression Docs] - Enabled by default

---

.github/scripts/prepare-release-base.sh
.github/workflows/release.yml

This fixes the minor release branch handling code in the release workflow so that it functions correctly.
n/a

Fix branch handling for minor releases in release workflow.

---

.github/workflows/build.yml
.github/workflows/docker.yml

This ensures we’ll see proper version tags on Docker images and in our git tags.
n/a

Ensure versioned release tags include a leading `v` in workflows.

---

collectors/apps.plugin/apps_groups.conf

This PR:
- adds Proxmox VE control-plane/worker processes to "proxmox-ve" group.
<details>
<summary>pve* processes</summary>
```cmd
$ ps aux | grep "[p]ve" --color | grep -v kvm
root        1767  0.0  0.0  80140  1408 ?        Ssl  22:03   0:00 /usr/sbin/pvefw-logger
root        1792  0.0  0.0 1630296 2180 ?        Ssl  22:03   0:00 /usr/lib/x86_64-linux-gnu/pve-lxc-syscalld/pve-lxc-syscalld --system /run/pve/lxc-syscalld.sock
root        2898  0.0  0.0 270408 85808 ?        Ss   22:03   0:00 pve-firewall
root        2908  0.1  0.0 269048 86544 ?        Ss   22:03   0:01 pvestatd
root        2960  0.0  0.0 344340 122980 ?       Ss   22:03   0:00 pvedaemon
root        2967  0.0  0.0 352652 127548 ?       S    22:03   0:00 pvedaemon worker
root        2970  0.2  0.0 352976 128360 ?       S …
```

feat(apps.plugin): add proxmox-ve processes to apps_groups.conf

---

.github/workflows/checks.yml
packaging/bundle-judy.sh

The option was added in [disable-dependency-tracking ](https://github.com/netdata/netdata/pull/12701). Thanks go to @vermaete for [spotting the problem](https://github.com/netdata/netdata/commit/3f97fe0355dd809939fb5a73fe1e76b86306908f).
</details>

fix disable-dependency-tracking typo

---

docs/monitor/enable-notifications.md
health/notifications/Makefile.am
health/notifications/alarm-notify.sh.in
health/notifications/gotify/Makefile.inc
health/notifications/gotify/README.md
health/notifications/health_alarm_notify.conf

Adds support for Gotify push notifications
Fixes [#12463](https://github.com/netdata/netdata/issues/12463)
1 - Install Gotify https://gotify.net/docs/install
2 - Generate application token in the Web UI (APPS -> CREATE APPLICATION)
3 - Change the following variables in the configuration file `./edit-config health_alarm_notify.conf`
```
GOTIFY_APP_TOKEN=
GOTIFY_APP_URL=
```
4 - Run the tests `./alarm-notify.sh test`
5 - The alerts should now show up in the Web UI
</details>

Gotify notifications

---

packaging/installer/UNINSTALL.md

… argument
This PR simply updates the Uninstall Netdata docs to present to the users the uninstaller script `-f/--force` argument.
Regarding a recent user issue with the `netdata-uninstaller.sh` script, I ran few end-user workflows to uninstall (uninstaller script) and install netdata (kickstart script). The workflow does not have any technical problems but the interactive mode of the script may confuse a user that won't be so pedantic to read the messages. 
In my opinion, a simple and intuitive user experience with this script would be,
"Use the interactive mode but set the default answer to yes `[Y/n]`. So the user will simply has to press Enter to go to the next netdata asset removal. In this way, the user will benefit from the interactive mode messages and the workflow will be smooth …

[Uninstall Netdata] - Add description in the docs to use uninstaller script with force arg

---

web/api/badges/README.md

Github -> GitHub
github -> GitHub

Docs: fix GitHub format

---

database/rrdset.c

Remove commented code.

---

collectors/plugins.d/README.md

Addresses https://github.com/netdata/netdata/pull/12067#issuecomment-1047640399

Mention serial numbers in chart names in the plugins.d API documentation

---

.github/CODEOWNERS

ssia
Check if the docs will remain at a high level, otherwise revert the change.
</details>

chore: remove kickoke from codeowners 

---

daemon/system-info.sh

Fixes: #12761
- master
```cmd
$ wget -q -O system-info.sh 
https://raw.githubusercontent.com/netdata/netdata/master/daemon/system-info.sh; sh system- 
info.sh | grep DISK_SIZE; rm system-info.sh
NETDATA_SYSTEM_TOTAL_DISK_SIZE=524288000
```
@Ferroin `df` method returns the wrong value, do we need to keep it?
- this PR
```cmd
$ wget -q -O system-info.sh 
https://raw.githubusercontent.com/ilyam8/netdata/fix_mac_disk_size_detection/daemon/system- 
info.sh; sh system-info.sh | grep -i DISK_SIZE; rm system-info.sh
NETDATA_SYSTEM_TOTAL_DISK_SIZE=994662584320
```
</details>

fix: use 'diskutil info` to calculate the disk size on macOS

---

database/rrddim.c

- Skip dimension deletion update
- TBA

Skip ACLK dimension update when dimension is freed

---

ml/README.md

I should have updated the readme as part of [this PR](https://github.com/netdata/netdata/pull/12771) for some small config changes. This PR updates readme to reflect the config changes.
https://github.com/netdata/netdata/pull/12771
</details>

update ml defaults in docs

---

packaging/installer/kickstart.sh
packaging/installer/methods/kickstart.md

Add --repositories-only option. #12801
Tested with `./kickstart.sh --repositories-only`.
</details>

add --repositories-only option

---

libnetdata/storage_number/storage_number.c

The LUT contains precomputed values of multipliers/divisors that are
used to unpack storage numbers into calculated numbers efficiently.
Performance improves by at least 35% when testing with random integers
in `uint32_t`s entire range. Unpacking smaller random values (eg. in the
range [0,1000]) is faster by 200-300%.
1. Compare calculated_numbers in old vs new version,
2. Run agent and check dashboards for any irregularities.

Improve storage number unpacking by using a lookup table.

---

exporting/prometheus/prometheus.c

We need to check if the chart name matches the pattern when `send names instead of ids` is set, otherwise - the chart id. 
- `filter` URL query param: the above logic.
- `send charts matching` URL query param: we check if id OR name matches.
This PR makes `send charts matching` behave the same as the `filter` URL query param.
</details>

fix(exporting)" make 'send charts matching' behave the same as 'filter' for prometheus format

---

database/engine/rrdengine.h
database/engine/rrdengineapi.c
web/api/queries/average/average.c
web/api/queries/query.c

Optimizations to speedup the query engine by eliminating unnecessary pointer dereferences and operations on every point of the database during data queries.

speedup queries by providing optimization in the main loop

---

CMakeLists.txt
Makefile.am
aclk/aclk_tx_msgs.c
aclk/schema-wrappers/capability.cc
aclk/schema-wrappers/capability.h
aclk/schema-wrappers/capability_list.cc
aclk/schema-wrappers/capability_list.h
aclk/schema-wrappers/connection.cc
aclk/schema-wrappers/connection.h
aclk/schema-wrappers/node_info.cc
aclk/schema-wrappers/node_info.h
aclk/schema-wrappers/schema_wrappers.h
database/sqlite/sqlite_aclk_node.c

Implements the new `capability` fields of `aclk_schemas`.
Implement #12482
Check generated messages
```
- Which area of Netdata is affected by the change?
ACLK, Agent/Cloud protocol
- Can they see the change or is it an under the hood? If they can see it, where?
It is under the hood change made by underhood
- How is the user impacted by the change? 
No direct impact but is necessary prerequisite for some future features.
```
</details>

Implements new capability fields in aclk_schemas

---

libnetdata/worker_utilization/worker_utilization.c

ssia, decided to add after #12902
ci
</details>

chore(worker_utilization): log an error when re-registering an already registered job

---

database/sqlite/sqlite_aclk_node.c

Fix release channel in the node info message (was hardcoded to nightly)
- Should be obvious

Fix release channel in the node info message

---

collectors/apps.plugin/apps_plugin.c
collectors/freebsd.plugin/freebsd_ipfw.c
collectors/freebsd.plugin/freebsd_sysctl.c
libnetdata/libnetdata.c

Fix compilation warnings in FreeBSD

---

collectors/cgroups.plugin/sys_fs_cgroup.c

Worker job details to help us reveal where the time is lost on busy k8s environments.

added worker jobs for cgroup-rename, cgroup-network and cgroup-first-time

---

packaging/installer/kickstart.sh

This will make it slightly more maintainable in the long term, and slightly easier for newcomers to understand.
CI passes.
No user-visible changes.
</details>

Move kickstart argument parsing code to a function.

---

daemon/system-info.sh

This limits system-info hanging on curl link-local address to 1 second regardless of the number of Cloud Providers checks. Right now this PR adds no benefits but will be handy when having more Cloud Providers checks (e.g. Azure, Digital Ocean, etc.).
Run updated system-info script on:
- GCP vm.
- AWS vm.
and check "NETDATA_INSTANCE_CLOUD_*" in the response. 
</details>

chore: check link local address before querying cloud instance metadata

---

libnetdata/socket/socket.c

This PR changes `poll_events()` so that it evenly spreads the work over worker threads.
In the previous version, a threads could accept all incoming connections, leaving the other threads without any work to do.
Also, it was not favoring transmissions over receptions, so data could be stack inside netdata for longer periods.
This PR changes the whole logic, so that network I/O happens in this order:
1. socket errors are handled immediately
2. transmission of data to the clients
3. reception of UDP data (i.e. statsd)
4. reception of TCP data (i.e. HTTP requests)
5. if nothing of the above happened and the thread has more capacity (according to the limit set) to receive sockets, accept a single TCP socket - additional sockets will be accepted at the next iteration of the event loop, under …

optimize poll_events() to spread the work over the threads more evenly

---

.github/workflows/build.yml

Intended to deal with the irritatingly regular network errors we have when dealing with some components.
n/a
</details>

Add automatic retries fo static builds during nightly and release builds.

---

claim/README.md

Add note on possibly alternate location of the `cloud.d` directory

Improve reconnect node instructions

---

aclk/aclk_tx_msgs.c
aclk/aclk_util.h
database/metric_correlations.c
database/metric_correlations.h
database/rrd.h
database/rrdhost.c
database/sqlite/sqlite_aclk_node.c
streaming/rrdpush.c
streaming/sender.c

This PR turns MC in the agent to default off, streams the MC version to parents, and will send the status of MC through the capabilities field in UpdateNodeInfo messages.
We will test this PR with the cloud backend to make sure things are in place first.
</details>

Stream and advertise metric correlations to the cloud

---

collectors/python.d.plugin/alarms/README.md
collectors/python.d.plugin/alarms/alarms.chart.py
collectors/python.d.plugin/alarms/alarms.conf

Adds ability to filter the alarms collected by the python alarms collector.
Tested locally with various filters applied.
</details>
Ability to just collect a subset of alarms with the alarms collector.

Alarms py collector add filtering

---

web/api/queries/query.c

Fixes an artificial gap filling at the query engine, when dbengine is having gaps.

prevent gap filling on dbengine gaps

---

web/api/web_api_v1.c

add hostname to mirrored hosts

add hostname to mirrored hosts

---

contrib/debian/netdata.default

This should fix issue #8898 at least until issue #7587 is fixed
Fixes #8898

Write pid file (needed by logrotate)

---

libnetdata/dictionary/README.md
libnetdata/dictionary/dictionary.c
libnetdata/dictionary/dictionary.h

Improve the dictionary to have the ability to merge dictionary items.
(not currently used)
Will be used to eventually replace labels linked list with dictionary.
Also, call the insertion and deletion callbacks when values are replaced.
(also not currently used)

add the ability to merge dictionary items

---

database/rrdset.c
database/sqlite/sqlite_aclk_chart.c
database/sqlite/sqlite_aclk_node.c

Switches the locking access to process chart labels to read instead of write
- N/A

Fix locking access to chart labels

---

packaging/installer/REINSTALL.md

Including explaining how to do a clean reinstall, and how to switch install types.
n/a

Add improved reinstall documentation.

---

collectors/statsd.plugin/README.md

**Before**
**After**
</details>

docs(statsd.plugin): fix indentation

---

database/rrdlabels.c

allow label names to have slashes

allow label names to have slashes

---

streaming/receiver.c

Fixes #13092 
Due the fact we were not checking the status of `SSL` connection, our code was entering in an infinite loop when a child disconnect from parent. This PR is adding the necessary check to close connections independent of the `OpenSSL` version.
1. Create ssl keys in the parent side and store them in `/etc/netdata/ssl/` with the following command:
```sh
openssl req -newkey rsa:2048 -nodes -sha512 -x509 -days 365 -keyout key.pem -out cert.pem
```
2. Change key permissions : 
```sh
````
3. Configure your `/etc/netdatta/netdata.conf`:
````conf
[web]
ssl key = /etc/netdata/ssl/key.pem
ssl certificate = /etc/netdata/ssl/cert.pem
bind to = *=dashboard|registry|streaming|management|netdata.conf|badges *:20000=dashboard|registry|streaming|netdata.conf|badges|management^SSL=optional …
```

Add missing control to streaming

---

contrib/debian/netdata.postinst

Fixes: https://github.com/netdata/netdata/issues/13164
DEB packages built from this PR have the Netdata service enabled after install.

Don’t manipulate positional parameters in DEB postinst script.

---

daemon/analytics.c
daemon/global_statistics.c
daemon/main.c
daemon/unit_test.c
database/engine/rrdengine.c
database/engine/rrdengine.h
database/engine/rrdengineapi.c
database/engine/rrdengineapi.h
database/ram/rrddim_mem.c
database/ram/rrddim_mem.h
database/rrd.c
database/rrd.h
database/rrdhost.c
database/rrdset.c
database/sqlite/sqlite_aclk_chart.c
database/sqlite/sqlite_functions.c
database/storage_engine.c
database/storage_engine.h
web/api/queries/query.c

This reverts commit 100a12c6cc01222b1518e5e50d2147f592d8a111.
A couple parent/child startup/shutdown scenarios can lead to crashes.
CI & local build

Revert "Configurable storage engine for Netdata agents: step 3 (#12892)"

---

health/Makefile.am
health/REFERENCE.md
health/health.d/ml.conf

This PR adds some examples of how to use the ML to define some ML based alerts should users wish to do so.
Currently [Anomaly Advisor](https://learn.netdata.cloud/docs/cloud/insights/anomaly-advisor) is passive and does not actively alert (by design). This PR would document how users who would like to trigger alerts based on anomaly rate can do so within the existing health configurations of Netdata.
I have been using sets of alerts like this in our devml and ml demo spaces, for example: 
https://app.netdata.cloud/spaces/ml-demo-space/rooms/general/overview#chartName=menu_alarms_submenu_value&correlation=false&after=1655457667000&before=1655464867000&utc=Europe%2FLondon&offset=%2B1&timezoneName=Edinburgh%2C%20London&metrics_correlation=false&appliedFilteredIds=&reachableNodesIds=&staleNode …

Add ml alerts examples

---

ml/README.md

make ML configuration example clearer in the README
</details>

make configuration example clearer

---

collectors/proc.plugin/proc_self_mountinfo.c

Systemd produces some fake mount info entries, which make netdata think a filesystem is mounted twice, and it tries to update the charts twice within each iteration.
This PR dedups the mount info list, so that each mount point will only be listed once.

deduplicate mountinfo based on mount point

---

collectors/cgroups.plugin/cgroup-name.sh

Fixes: #13218
Testes by @rafaelwastaken in #13218
</details>

fix(cgroups.plugin): fix qemu VMs and LXC containers name resolution

---

.github/workflows/add-to-project.yml

This should fix the workflow that auto-adds new issues to the Agent Board project.
Merge it and see what happens.

Use correct PAT for add-to-project workflow.

---

database/sqlite/sqlite3.h

Switches to version 3.38.5 -- enables
```
#define SQLITE_UDL_CAPABLE_PARSER 1
#define SQLITE_ENABLE_UPDATE_DELETE_LIMIT 1
#define SQLITE_OMIT_LOAD_EXTENSION 1
#define SQLITE_ENABLE_DBSTAT_VTAB 1
```
- Agent should work as the change is transparent

Updates the sqlite version in the agent

---

collectors/python.d.plugin/python.d.conf

Closes: #13262
Update the config file to reflect https://github.com/netdata/netdata/releases#v1350-deprecation-notice
</details>

chore(python.d): remove deprecated modules from python.d.conf

---

daemon/analytics.c
database/rrd.h
streaming/rrdpush.c
streaming/sender.c

SSIA
Setup two active-active agents and run one of them under helgrind with/without this PR.
https://github.com/netdata/netdata/issues/13298

Fix two helgrind reports

---

database/sqlite/sqlite_aclk_node.c

Fixes coverity `** CID 379241:  Null pointer dereferences  (FORWARD_NULL)`
</details>

Fix coverity 379241

---

README.md

This PR adds the github stars badge to the readme to make it more discoverable for users.
Badge comes from shields similar to the others: https://img.shields.io/github/stars/netdata/netdata?style=social
Can see how this looks here: https://github.com/netdata/netdata/blob/add-github-star-badge/README.md
</details>

add github stars badge to readme

---

web/gui/dashboard_info.js

ssia
Tested locally
</details>

chore(dashboard): update chrony dashboard info

---

daemon/unit_test.c

Fixes an issue with bitmap256 unit tests
- CI should give no errors in unittests

Fix bitmap unit tests

---

collectors/python.d.plugin/haproxy/README.md

Fixes: #10321
Closes: #10322
Not needed.
</details>

chore(python.d): clarify haproxy module readme 

---

collectors/python.d.plugin/zscores/README.md
docs/anonymous-statistics.md
health/notifications/msteams/README.md

minor fixes on the metadata fields of some docs
part of learn
Signed-off-by: Tasos Katsoulas <tasos@netdata.cloud>

minor fixes on metadata fields 

---

README.md

add ML bullet point to features section on README
Can read it here: https://github.com/netdata/netdata/blob/include-ml-in-readme/README.md
</details>

add ML bullet point to features section on README

---

README.md

add discord, youtube, linkedin links to README

---

database/engine/rrdengine.c
database/engine/rrdengine.h
database/engine/rrdengineapi.c
database/engine/rrdengineapi.h
libnetdata/libnetdata.h
web/api/web_api_v1.c

Tiering statistics for the calculator

Tiering statistics API endpoint

---

web/gui/dashboard_info.js

Fix typo in PostgreSQL section header

Fix typo in PostgreSQL section header

---

database/engine/rrdengineapi.c
database/engine/rrdengineapi.h
web/api/web_api_v1.c

added statistics about currently collected metrics and disk space

additional stats

---

.github/CODEOWNERS

Today is their last day at Netdata.
n/a

Remove Igor and Marius as codeowners.

---

docs/guides/monitor/anomaly-detection.md

minor change, Replace heading 1 with heading 2

fix a guide so we can reference it's subsections

---

database/rrdcontext.c

This will enable rrdcontexts by default on the agent
- n/a

Enable rrdcontexts by default

---

web/gui/dashboard_info.js

This PR adds go [Postgres collector](https://github.com/netdata/go.d.plugin/tree/master/modules/postgres#postgresql-monitoring-with-netdata) charts description.
Install updated dashboard_info.js, and check the dashboard.
</details>

update postgres dashboard info

---

web/gui/dashboard_info.js

Dragon because [WireGuard logo](https://www.wireguard.com/) has dragon 😄 
> the [icon](https://fontawesome.com/icons/dragon?s=solid)
Not needed.
</details>

chore: add WireGuard description and icon to dashboard info

---

health/health.d/go.d.plugin.conf
health/health.d/python.d.plugin.conf

Until we will make them more meaningful.
Related: #13310
Not needed.
</details>

health: disable go python last collected alarms

---

packaging/docker/README.md

Fixes: #13389
Not needed.
</details>

docs: add a note about edit-config for docker installs

---

collectors/ebpf.plugin/README.md
database/README.md
docs/guides/troubleshoot/troubleshooting-agent-with-cloud-connection.md

docs: fix unresolved file references

---

.github/ISSUE_TEMPLATE/config.yml

Such issues should be in netdata/netdata with label area/web

Remove prompt to add dashboard issues

---

web/gui/dashboard_info.js

ssia
Check [pgbouncer](https://github.com/netdata/go.d.plugin/tree/master/modules/pgbouncer) collectors' charts on the dashboard.
</details>

add PgBouncer charts description and icon to dashboard info

---

collectors/COLLECTORS.md
docs/collect/application-metrics.md

docs: change postgres links to go version

---

collectors/python.d.plugin/postgres/README.md

~~Should be merged after v1.36.0 is out.~~ ok to merge
Not needed.
</details>

docs: add deprecation notice to python.d/postgres readme

---

database/rrdcontext.c

Fixes https://github.com/netdata/netdata/issues/13500

rrdcontexts allow not linked dimensions and charts

---

ml/README.md

remove reference to charts now in netdata monitoring
</details>

remove reference to charts now in netdata monitoring

---

collectors/cups.plugin/README.md
collectors/freeipmi.plugin/README.md

This adds specific info about the plugins being handled as separate packages for our native packages, as well as consolidating and reorganizing the install instructions for the FreeIPMI plugin to be more concise.
n/a
Fixes: #12893

Update FreeIPMI and CUPS plugin documentation.

---

collectors/cgroups.plugin/cgroup-name.sh

[Docker containers name resolution doesn’t work](https://discord.com/channels/847502280503590932/976961124157243414) when Docker is installed as a snap package. The problem is snap + AppArmor + home dir outside of /home.
I tried to google, found [this advice](https://forum.snapcraft.io/t/how-can-i-use-snap-when-i-dont-use-home-user/3352/2), applied it - no luck.
- Netdata installed from git
- Netdata error.log
> cannot create user data directory: /opt/netdata/var/lib/netdata/snap/docker/1779: 
Permission denied
- Journal logs
> Aug 15 18:32:01 ilyam-ubnt2204-1 audit[1943]: AVC apparmor=“DENIED” operation=“open” 
profile=“/usr/lib/snapd/snap-confine” name=“/opt/” pid=1943 comm=“snap-confine” 
requested_mask=“r” denied_mask=“r” fsuid=998 ouid=0
Aug 15 18:32:01 ilyam-ubnt2204-1 kernel: …

fix(cgroups.plugin): use Docker API for name resolution when Docker is a snap package

---

collectors/apps.plugin/apps_groups.conf

add jupyter which is a very common platform for data science notebooks etc. 
https://jupyter.org/
</details>

add `jupyter` to `apps_groups.conf`

---

packaging/PLATFORM_SUPPORT.md

Removed "Planned for core tier support" from macOS.

Update MacOS community support details

---

daemon/buildinfo.c
web/api/web_api_v1.c

Removes ancient mentions of ACLK-NG/ACLK-Legacy which are obsolete for a long enough time to be removed.
This removes unnecessary confusion for users
</details>

Cleanup of APIs

---

web/gui/dashboard_info.js

This PR adds basic dashboard info for [go.d/docker](https://github.com/netdata/go.d.plugin/tree/master/modules/docker).
Not needed.
</details>

add docker dashboard info

---

database/rrdcalc.c

Adds a check on `rc->rrdset` to fix coverity 380387.
</details>

Fix coverity 380387

---

collectors/python.d.plugin/sensors/sensors.chart.py

Fixes: #13544
This PR:
- adds discovering chips and features at runtime (read as creating charts at runtime).
- removes skipping sensors that report 0.
- install the new version, check the charts.
- ask @ralphm to test.
</details>

feat(python.d/sensors): discover chips, features at runtime

---

collectors/apps.plugin/apps_groups.conf

add `datadog`, `edgedelta`, `newrelic`, `google-agent`, `nvidia-smi`, `htop`
tested locally and working as expected.
</details>

add more monitoring tools to `apps_groups.conf`

---

web/gui/dashboard_info.js

Updating info for: 
- db_buffer_cache_hit_ratio
- db_rows_read_ratio
- db_rows_read
- db_conflicts
- db_conflicts_stat
Tested on local agent dashboard

Updating info for postgreqsql metrics

---

collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py

Fixes: #13576
[Tested by](https://github.com/netdata/netdata/issues/13576#issuecomment-1229225575) @mailinglists35
</details>

fix(python.d/nvidia_smi): repsect update_every for polling

---

collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py

Fixes: #13577
[Tested by](https://github.com/netdata/netdata/issues/13577#issuecomment-1229257634) @mailinglists35
</details>

feat(python.d/nvidia_smi): collect power state

---

daemon/global_statistics.c
daemon/global_statistics.h
daemon/unit_test.c
database/sqlite/sqlite_aclk.c
database/sqlite/sqlite_aclk_alert.c
database/sqlite/sqlite_aclk_chart.c
database/sqlite/sqlite_context.c
database/sqlite/sqlite_db_migration.c
database/sqlite/sqlite_functions.c
database/sqlite/sqlite_functions.h
database/sqlite/sqlite_health.c
ml/Database.cc
ml/Database.h

This PR adds 2 charts in the netdata section to monitor the sqlite3 queries.

sqlite3 global statistics

---

docs/netdata-for-IoT.md

Link to how the footprint can be reduced for IoT devices

Add link to the performance optimization guide

---

web/gui/dashboard_info.js

The python version was [rewritten](https://github.com/netdata/go.d.plugin/pull/786) in go. This PR updates logind dashoard info.
Tested locally.
</details>

update logind dashboard info

---

collectors/cgroups.plugin/sys_fs_cgroup.c

Related issue #13572
@MrZammler will test it
</details>

fix(cgroups.plugin): fix chart id length check

---

.github/workflows/packaging.yml

Long term fix will require writing our own action to scan the PR body, because of environment variable size limits.
n/a

Temporary fix for command injection vulnerability in GHA workflow.

---

database/sqlite/sqlite_context.c

Switch most used context queries to prepared statements
- Changes should be transparent

Use prepared statements for context related queries

---

web/gui/dashboard_info.js

Move the "connections" section general section description from context to submenu level. cc @shyamvalsan 
Use changed dashboard_info.js, and check the dashboard.
</details>

update Postgres "connections" dashboard info

---

health/Makefile.am
health/health.d/postgres.conf

Fixes: #13617 
cc @sashwathn 
Install this branch, and check the alarm.

add Postgres total connection utilization alarm

---

database/rrdcalc.h

remove forgotten avl structure from rrdcalc

---

database/rrdcontext.c

Fixes https://github.com/netdata/netdata-cloud/issues/582

fix typo not deleting collected flag; force removing collected flag on child disconnect

---

packaging/building-native-packages-locally.md

For developers and contributors so they don’t have to bug me every time they need to do it.
n/a
@kickoke Just as a quick note, this is not intended to be for end-users, but for developers/contributors working on the code. Given this I think we can safely assume a reasonably high level of intelligence among our readers.

Add a document outlining how to build native packages locally.

---

collectors/python.d.plugin/nvidia_smi/README.md

We need this note because it is not first time I see a [user confused](https://community.netdata.cloud/t/nvidia-smi-for-a-newbie/3310/3) about using nvidia-smi when Netdata is running in a container.
Not needed.
</details>

docs: nvidia-smi in a container limitation note

---

packaging/installer/UNINSTALL.md

This properly documents the preferred uninstallation method, as well as tidying up the existing documentation as a fallback method.
n/a

Update uninstaller documentation.

---

health/health.d/postgres.conf

Until we ensure those can be applied in general to all tables.
Not needed.
</details>

disable Postgres last vacuum/analyze alarms

---

collectors/cgroups.plugin/tests/test_doubles.c
exporting/tests/exporting_fixtures.c
exporting/tests/netdata_doubles.c
exporting/tests/test_exporting_engine.c

After #13646 the tests were broken. We should change the way we are preparing a fake RRD.
The tests should pass in the CI

Update exporting unit tests

---

collectors/python.d.plugin/python_modules/bases/charts.py

[It is 1](https://github.com/netdata/netdata/blob/cc2586de697702f86a3c34e60e23652dd4ddcb42/database/rrd.h#L205), not zero.
</details>

fix(python.d): set correct label source for _collect_job label

---

health/health.d/ml.conf

also fix a dead link
</details>

add node level AR based example

---

daemon/main.c
libnetdata/socket/security.c
libnetdata/socket/security.h
web/api/web_api_v1.c

fix bad merge

---

database/rrdcontext.c

Post Processing of rrdcontexts had a bug, mixing the constructors and destructors with the Netdata Cloud queue.
Fixed them and added more information to track post-processing via the API.

fix post-processing of contexts

---

exporting/tests/netdata_doubles.c
exporting/tests/test_exporting_engine.c
exporting/tests/test_exporting_engine.h

SSIA
Build Netdata with autotools, run `sudo make check` and check if the exporting unit test is passing.

Fix exporting unit tests

---

collectors/proc.plugin/proc_net_rpc_nfsd.c

The histogram was [removed from the kernel in 2019](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/fs/nfsd/vfs.c?id=501cb1849f865960501d19d54e6a5af306f9b6fd). As far as it wasn't very useful anyway, it doesn't make sense to keep the chart.

Remove NFS readahead histogram

---

database/rrd.h
database/rrddim.c
database/rrdset.c

These functions will be prove helpful in writting tests that are both
(a) memory mode agnostic, and
(b) oblivious of rrd internals.
- Build & run the agent
- CI jobs.

Add variants of functions allowing callers to specify the time to use.

---

collectors/apps.plugin/apps_plugin.c

Added more information to the schema of apps.plugin processes output, to allow building a UI for it.

extended processes function info from apps.plugin

---

.github/workflows/codeql.yml
.github/workflows/packaging.yml
.github/workflows/review.yml

This way it better describes what it’s doing.
n/a

Change CI trigger label prefix from `ci/` to `run-ci/`.

---

docs/guides/step-by-step/step-09.md

n/a
Updating 
'[global]
(no longer used)
-->
</details>

Update step-09 for dbmode update.md

---

web/gui/dashboard_info.js

Blocked by https://github.com/netdata/go.d.plugin/pull/901
</details>

Cassandra dashboard description

---

database/sqlite/sqlite_metadata.c

Store the dimension hidden status when creating or updating metadata. The hidden option can be specified 
separately, but the update metadata (on all fields) on the dimension would not respect it. 
With this PR the option is updated correctly. 
- Start the agent and view the `system.cpu` chart. Set the dashboard to auto update. 
- Restart the agent the notice momentarily that the chart is updated and includes the `idle` dimension which should be hidden. 
- Apply the PR and notice the problem is gone.

Store hidden status when creating / updating dimension metadata

---

docs/collect/system-metrics.md
web/gui/dashboard_info.js

This PR adds additional information for TCP metrics collected with WMI.
Take a look on descriptions.
</details>

Add description for TCP WMI

---

database/rrdcontext.c

Fixes https://github.com/netdata/netdata-cloud/issues/434#issuecomment-1291682537

filtering out charts in context queries, includes them in full_xxx variables

---

collectors/COLLECTORS.md

add pandas collector to collectors.md
</details>

add pandas collector to collectors.md

---

collectors/charts.d.plugin/sensors/README.md

The plugin is the only option for RPi temperatures.  Also fixed formatting.

Improve intro paragraph

---

collectors/apps.plugin/apps_plugin.c

speed up the UI by providing the max value per column at the fields list.

apps.plugin function add max value on all value columns

---

web/api/queries/query.c

fixes https://github.com/netdata/netdata/issues/13918

fix crash on query plan switch

---

daemon/README.md
daemon/main.c

- update to 2022.
- add LinkedIn url.
</details>

Update print message on startup

---

docs/Demo-Sites.md

update link to point at demo spaces

---

collectors/plugins.d/pluginsd_parser.c
database/rrd.h
database/rrddim.c
database/rrdset.c
health/health.c
streaming/replication.c

recalculate last_collected_total

---

database/rrd.h
database/rrdcontext.c
database/rrdcontext.h
database/rrddim.c
database/rrdset.c
exporting/check_filters.c
exporting/prometheus/prometheus.c
health/health.c
ml/Config.cc
ml/Dimension.cc
ml/Dimension.h
ml/Host.cc
ml/Host.h
ml/ml-dummy.c
ml/ml.cc
ml/ml.h
streaming/rrdpush.c
web/api/formatters/rrd2json.c
web/api/web_api_v1.c

Anomaly bits will have to queried directly from each individual chart.
N/A. Built & run locally.

Remove anomaly rates chart.

---

collectors/python.d.plugin/tor/README.md
collectors/python.d.plugin/tor/tor.conf

document `password` param for tor collector
https://stackoverflow.com/questions/74173810/netdata-tor-plugin-configuration
</details>

document password param for tor collector

---

web/gui/dashboard_info.js

ssia
Tested by copying dashboard_info.js to a VM with running Cassandra.
</details>

add Cassandra icon to dashboard info

---

docs/store/change-metrics-storage.md

Change the db-engine calculator to a read only gsheet

---

libnetdata/popen/popen.c

Prevent this crash:
```
(gdb) bt
#0  0x00007fec3ec940d7 in fgets () from /usr/lib/libc.so.6
#1  0x00005562c1e56696 in read_cgroup_network_interfaces (cg=0x5562d4856800) at collectors/cgroups.plugin/sys_fs_cgroup.c:1679
#2  0x00005562c1e5c764 in discovery_process_cgroup (cg=0x5562d4856800) at collectors/cgroups.plugin/sys_fs_cgroup.c:2716
#3  0x00005562c1e5c82c in discovery_find_all_cgroups () at collectors/cgroups.plugin/sys_fs_cgroup.c:2735
#4  0x00005562c1e5ca8c in cgroup_discovery_worker (ptr=0x0) at collectors/cgroups.plugin/sys_fs_cgroup.c:2793
#5  0x00007fec3eca78fd in ?? () from /usr/lib/libc.so.6
#6  0x00007fec3ed29a60 in ?? () from /usr/lib/libc.so.6
(gdb) up
#1  0x00005562c1e56696 in read_cgroup_network_interfaces (cg=0x5562d4856800) at …
```

dont crash when netdata cannot execute its external plugins

---

daemon/main.c
database/engine/rrdengineapi.c
database/engine/rrdenginelib.c
database/rrd.h
database/rrdhost.c

Revert "enable dbengine tiering by default"

---

collectors/plugins.d/pluginsd_parser.c
daemon/global_statistics.c
daemon/main.c
database/engine/datafile.c
database/engine/datafile.h
database/engine/journalfile.c
database/engine/journalfile.h
database/engine/pagecache.c
database/engine/pagecache.h
database/engine/rrdengine.c
database/engine/rrdengine.h
database/engine/rrdengineapi.c
database/engine/rrdengineapi.h
database/engine/rrdenglocking.c
database/engine/rrdenglocking.h
database/rrd.h
database/rrddim.c
database/rrdhost.c
database/rrdset.c
libnetdata/arrayalloc/arrayalloc.c
libnetdata/dictionary/dictionary.c
libnetdata/dictionary/dictionary.h
libnetdata/libnetdata.c
libnetdata/libnetdata.h
streaming/compression.c
streaming/receiver.c
streaming/replication.c
streaming/rrdpush.h
streaming/sender.c
web/api/web_api_v1.c

Revert "New journal disk based indexing for agent memory reduction"

---

packaging/installer/UNINSTALL.md

Just a minor typo in the uninstall curl command

minor typo in the uninstall command

---

aclk/aclk_query.c
aclk/aclk_query.h
aclk/aclk_stats.c

Don't print the error `Unknown query type used 0` at the startup as it is not an error in this case.
</details>

minor - silence misleading error

---

.github/workflows/build.yml

SSIA
Merge it, manually trigger a nightly, and see what happens.

Fix nightly build uploads.

---

streaming/README.md

Fix instruction to have TLS streaming enabled.
- Which area of Netdata is affected by the change? Documentation
- How is the user impacted by the change? It will be simpler to set TLS streaming.
- What are there any benefits of the change? A better documentation
</details>

Fix documentation TLS streaming

---

collectors/plugins.d/pluginsd_parser.c
daemon/service.c
database/rrd.h
database/rrdhost.c
database/rrdset.c
streaming/receiver.c
streaming/replication.c
streaming/replication.h
streaming/rrdpush.h
streaming/sender.c

Fixes:
- https://github.com/netdata/netdata-cloud/issues/669
- https://github.com/netdata/netdata-cloud/issues/668
and probably more...

Replication fixes #3

---

streaming/replication.c

do not merge duplicate replication requests 

---

docs/guides/configure/performance.md

Triggered from https://community.netdata.cloud/t/insane-netdata-memory-usage/3342/9
There are a lot more details in there from @ktsaou, but I kept just some highlights.

Add up to date info on improving performance

---

libnetdata/dictionary/dictionary.c

- dictionary unittest was giving errors because of a wrong flags;
- added pointer registry to dictionary to ensure that pointers are unique (internal checks only)
- added locks to dictionary destroy

fix dictionaries unittest

---

.github/data/distros.yml
packaging/PLATFORM_SUPPORT.md

Add Alpine 3.17 to supported distros.

---

libnetdata/locks/locks.c

Spinlock had a data race condition when multi-threaded. Fixed it.

fix spinlock

---

web/gui/dashboard_info.js

ssia
Tested locally by copying dashboard_info.js to a server that collects metrics from NGINX Plus.
</details>

add basic dashboard info for NGINX Plus

---

.github/data/distros.yml

Fix typo in Fedora 37 build configuration.

---

web/gui/dashboard_info.js

This PR is bringing more chart description for WMI charts.
1. Copy the dashboard_info.js and force a reload in your browser. You should have local dashboard working properly.
- Which area of Netdata is affected by the change? Dashboard
- Can they see the change or is it an under the hood? If they can see it, where?yes, they will have chart description.
- How is the user impacted by the change?  A chart better described.
- What are there any benefits of the change?  Users do not need to move for other sites to get additional information.
</details>

Wmi descriptions

---

packaging/docker/README.md

docs: add a note to set container nofile ulimit for Fedora users

---

collectors/COLLECTORS.md

- Add link for community contributed ClickHouse collector #8682 .
- Add general instructions along with example for installing a third party collector.
</details>

add clickhouse third party collector and install instructions

---

collectors/COLLECTORS.md

minor fix for `<br>`, in plain markdown it breaks docusaurus deployments
</details>

Fix minor typo.

---

libnetdata/arrayalloc/arrayalloc.c
libnetdata/arrayalloc/arrayalloc.h

Added `arrayalloc_destroy()` and optimize `#ifdef` statements to make it simpler to read.

ARAL: add destroy function and optimize ifdefs

---

.github/workflows/repoconfig-packages.yml

We should be uploading on anything except pull requests, but only if running in the main repo.
n/a
Needs to be merged before #14100.

Fix conditions for uploading repoconfig packages to new infra.

---

Makefile.am
aclk/aclk.c
aclk/aclk_util.c
aclk/aclk_util.h

Revert "MQTT 5 publish topic alias support"

---

.github/CODEOWNERS

Add tkatsoulas as a codeowner for documentation.

---

contrib/debian/netdata.postinst

found by @MrZammler in https://github.com/netdata/netdata/pull/14168#discussion_r1055243691
not needed
</details>

fix a typo in debian postinst

---

packaging/docker/README.md

Because of #14177
run docker run/docker-compose on Fedora 37.
</details>

docs: explicitly set the `nofile` limit for Netdata container and document the reason for this

---

collectors/apps.plugin/apps_groups.conf

Add `telegraf` as an app in the monitoring section.
Tested locally - working as expected:
</details>

add `telegraf` to `apps_groups.conf` monitoring section

---

health/Makefile.am
health/health.d/elasticsearch.conf

Fixes: netdata/netdata#14184
Add alarms, reload health, and check the alarms on UI. 
</details>

Add few alarms for elasticsearch

---

health/health.d/consul.conf

fix consul_raft_leadership_transitions alarm units

---

collectors/all.h

rename NETDATA_ML_CHART_FAMILY from `ml - machine learning` to just `machine learning`
this would look a little cleaner if was just "machine learning" and more in line with all the other chart families within "Netdata Monitoring"
</details>

`ml - machine learning` to just `machine learning`

---

packaging/installer/README.md
packaging/installer/methods/kickstart.md

Fix kickstart download counter badges in documentation.

---

.github/scripts/package-upload.sh

This significantly simplifies handling on the server itself.
n/a

Update handling of uploads of DEB packages to our new infrastructure.

---

packaging/installer/install-required-packages.sh
packaging/installer/methods/manual.md

ssia, not needed after #14195.
ci
</details>

chore(packaging): remove python-pymongo

---

CMakeLists.txt
Makefile.am
aclk/aclk_stats.c

Adds charts to be able to see inner workings and state of mqtt_websockets stack on the dashboard
</details>

Adds some introspection into the MQTT_WSS

---

database/engine/journalfile.c

fix for dbengine2 improvements part 3

---

packaging/installer/kickstart.sh

ssia
Not really needed, the changes are straightforward.
</details>

allow multiple local-build/static-install options in kickstart

---

database/sqlite/sqlite3.h

Update the SQLITE version to 3.40.1
- No change, things should just work

Update to SQLITE version 3.40.1

---

.github/workflows/build.yml

- Switch to using Docker images instead of plain OCI images for transferring containers between CI steps.
CI works correctly on this PR.

Fix build CI jobs.

---

health/health.d/consul.conf
web/gui/dashboard_info.js

and license expiration time chart description
Tested locally.
</details>

add consul license expiration time alarm

---

.github/CODEOWNERS

Fix up codeowners based on recent staffing changes.

---

database/engine/datafile.ksy

`ksv $NETDATA_INSTALL_DIR/netdata/var/cache/netdata/dbengine/datafile-1-0000000001.ndf database/engine/datafile.ksy`
</details>

minor - kaitai for netdata datafiles

---

libnetdata/socket/socket.c
web/server/static/static-threaded.c
web/server/web_client.c

Reverts netdata/netdata#14317
Causes high cpu usage in some cases, will be investigated.

Revert "Misc SSL improvements"

---

health/notifications/alarm-notify.sh.in
health/notifications/health_alarm_notify.conf

Currently, if you use `|critical` modifier, you always get at least 2 notifications: critical and clear. There is no way how to stop sending clear/warning notifications afterwards.
This patch adds two more modifiers:
`|nowarn`  = Do not send warning notifications
`|noclear` = Do not send clear notifications
Edit your notification settings in `health_alarm_notify.conf` and check this:
1. `recipient` (no modifier set) - Receive all notifications
2. `recipient|critical` - Same as before. You receive critical notifications and following status changes.
3. `recipient|critical|noclear` - You receive critical notifications and following status changes except clear notifications.
4. `recipient|critical|nowarn` - You receive critical notifications and following status changes except warning …

Add |nowarn and |noclear notification modifiers

---

health/notifications/alarm-notify.sh.in
health/notifications/discord/README.md
health/notifications/health_alarm_notify.conf

Minor fix on Discord naming convention
Ref: https://github.com/netdata/learn/pull/1290
Signed-off-by: Tasos Katsoulas <tasos@netdata.cloud>
Part of learn

minor fix on notification doc (Discord)

---

docs/cloud/netdata-functions.md
docs/cloud/runtime-troubleshooting-with-functions.md

…le function list and callout when error on Cloud appears
Reviewed the docs functions to:
* fix broken links
* add current available functions
* callout for when user gets an error on Cloud
N/A
N/A
</details>

reviewed the docs functions to fix broken links and other additions

---

libnetdata/arrayalloc/README.md
libnetdata/avl/README.md
libnetdata/circular_buffer/README.md
libnetdata/ebpf/README.md
libnetdata/json/README.md
libnetdata/locks/README.md
libnetdata/log/README.md
libnetdata/onewayalloc/README.md
libnetdata/popen/README.md
libnetdata/procfile/README.md
libnetdata/statistical/README.md
libnetdata/storage_number/README.md
libnetdata/string/README.md
libnetdata/threads/README.md
libnetdata/url/README.md

Delete empty readmes, add readmes with content to learn, under Developer
File|Action
-- | --
https://github.com/netdata/netdata/edit/master/libnetdata/threads/README.md | del
https://github.com/netdata/netdata/edit/master/libnetdata/log/README.md | del
https://github.com/netdata/netdata/edit/master/libnetdata/avl/README.md | add
https://github.com/netdata/netdata/edit/master/libnetdata/string/README.md | add
https://github.com/netdata/netdata/edit/master/libnetdata/onewayallocator/README.md | add
https://github.com/netdata/netdata/edit/master/libnetdata/url/README.md | del
https://github.com/netdata/netdata/edit/master/libnetdata/ebpf/README.md | del
https://github.com/netdata/netdata/edit/master/libnetdata/popen/README.md | del
https://github.com/netdata/netdata/edit/master/libnetdata/loc …

Add libnetdata readmes to learn, delete empty

---

docs/guides/deploy/ansible.md

Add ansible.md to learn

---

health/README.md

Add main health readme to learn

---

REDISTRIBUTED.md

Add redistributed to learn

---

libnetdata/arrayalloc/README.md
libnetdata/avl/README.md
libnetdata/circular_buffer/README.md
libnetdata/ebpf/README.md
libnetdata/json/README.md
libnetdata/locks/README.md
libnetdata/log/README.md
libnetdata/onewayalloc/README.md
libnetdata/popen/README.md
libnetdata/procfile/README.md
libnetdata/statistical/README.md
libnetdata/storage_number/README.md
libnetdata/string/README.md
libnetdata/threads/README.md
libnetdata/url/README.md

Reverts netdata/netdata#14371
even empty readmes are required because of the stupid makefiles.

Revert "Add libnetdata readmes to learn, delete empty"

---

libnetdata/dictionary/README.md

Add dictionary readme to learn

---

libnetdata/README.md

Reverts netdata/netdata#14357
empty readmes required.

Revert "Delete libnetdata readme"

---

.github/scripts/gen-docker-tags.py
.github/workflows/docker.yml

This fixes handling of tags for publishing our Docker images so that they get published to GHCR and Quay properly.
n/a

Fix publishing Docker Images to secondary registries.

---

.github/workflows/docker.yml

This fixes publishing of our docker debug images so that they correctly end up in their own repositories.
n/a

Fix typos in Docker debug image tags.

---

database/sqlite/sqlite_aclk_alert.c

This PR adds a new filter for alert events sent to the cloud. This filter will not allow any alert events that come from a configuration that specifies an alert variable (rather than a normal alert) to be sent to the cloud.
Examples of such alerts are `interface_speed`, `load_cpu_number`, etc.
Before this PR, those alert events where sent once during first start (or when their configuration changed). With this PR those alert events will never be sent. This should reduce the total number of alerts on the cloud.
They way to filter those is that their configuration does not include `crit` and `warn` entries.
Check that normal alert events are sent to the cloud.
</details>

Don't send alert variables to the cloud

---

collectors/plugins.d/README.md

fix link to ebpf collector

---

database/engine/journalfile.c
database/engine/rrdengineapi.c

DBENGINE v2 - bug fixes

---

health/health.d/kubelet.conf

ssia, wrong dimension names
Tested using my local k8s cluster.
</details>

fix kubelet alarms

---

collectors/REFERENCE.md
packaging/installer/methods/kickstart.md
packaging/installer/methods/manual.md

Signed-off-by: Tasos Katsoulas <tasos@netdata.cloud>

Minor fixes in markdown links

---

database/engine/pdc.c

better logging of invalid pages detected on dbengine files

---

collectors/plugins.d/README.md

Move under Developer in Learn

---

libnetdata/README.md
libnetdata/adaptive_resortable_list/README.md
libnetdata/aral/README.md
libnetdata/avl/README.md
libnetdata/buffer/README.md
libnetdata/circular_buffer/README.md
libnetdata/config/README.md
libnetdata/dictionary/README.md
libnetdata/ebpf/README.md
libnetdata/json/README.md
libnetdata/july/README.md
libnetdata/locks/README.md
libnetdata/log/README.md
libnetdata/onewayalloc/README.md
libnetdata/popen/README.md
libnetdata/procfile/README.md
libnetdata/simple_pattern/README.md
libnetdata/statistical/README.md
libnetdata/storage_number/README.md
libnetdata/string/README.md
libnetdata/threads/README.md
libnetdata/url/README.md

Libnetdata readmes learn

---

docs/cloud/netdata-functions.md

there was a typo on the netdata functions information page, so I fixed it.

Fix typo on the netdata-functions.md

---

.github/CODEOWNERS

i'd like to help out around docs etc and share the load.
</details>

add @andrewm4894 as docs/ codeowner

---

docs/cloud/manage/role-based-access.md

Added the docs to describe the role-based permissions
Will have another PR in future to explain how users can define/change roles
</details>

Roles permissions docs

---

docs/get-started.mdx

There was only a suggestion to use the local agent UI in the next steps

Add mention of cloud in next steps UI etc

---

docs/cloud/visualize/kubernetes.md

Discussion in https://github.com/netdata/netdata/pull/14345 's review comments.
Remove the prerequisites section, remove the Guide in what's next, and fix all the links in the file.

Update the "Kubernetes visualizations" doc

---

docs/cloud/cloud.mdx

There was no cloud basic page any more.

Fix links and add to learn

---

health/notifications/README.md

See https://github.com/netdata/netdata/issues/3495#issuecomment-1408452259

Add export for people running their own registry

---

docs/get-started.mdx

With the addition of these sections and moving of content around, this document will be moved to replace completely packaging/installer/readme.md

Add contents of packaging/installer/readme.md

---

docs/guides/deploy/ansible.md

Apparently the netdata/community repo was reorganized.

Correct link to ansible playbook

---

docs/Demo-Sites.md

Includes link to the cloud demo

Upgrade demo sites to the getting started section

---

libnetdata/worker_utilization/README.md

This should be fairly straightforward, adding this file to Learn

Add a file to Learn

---

docs/getting-started/introduction.md

brought in the contents of https://github.com/netdata/netdata/edit/master/docs/overview/netdata-monitoring-stack.md updated for Prometheus and Grafana, including our new data source plugin. That file will be deleted.
fixed the edit link

Incorporate interoperability and fix edit link

---

libnetdata/libnetdata.c

Agent fails to build successfully on FreeBSD < 13.1 and on environments with Linux kernel version < 5.11, due to `CLOSE_RANGE_CLOEXEC` missing (bug introduced as a result of https://github.com/netdata/netdata/pull/14213). This PR fixes that issue.
Check that the agent builds successfully on [all supported platforms](https://learn.netdata.cloud/docs/agent/packaging/platform_support) and also on FreeBSD 13.0, 12.4, 12.3. The file descriptor closing behavior shouldn't be altered as a result of this PR.

Fix compiler error when CLOSE_RANGE_CLOEXEC is missing

---

web/gui/dashboard_info.js

After a talk with @shyamvalsan we decided to update the menu title to simplify user understand about content inside a menu.
1. Only verify typos
</details>

Update AD title

---

packaging/PLATFORM_SUPPORT.md

The changes were to make it the main page in Installation, but I decided to have a small dedicated page instead. Reverting these.

Revert changes to platform support policy

---

collectors/COLLECTORS.md
collectors/python.d.plugin/alarms/README.md
collectors/python.d.plugin/anomalies/README.md

This is an ongoing PR, will open it up for review once everything looks good

Fix broken links in collectors/COLLECTORS.md

---

docs/cloud/manage/role-based-access.md

Added a section to explain what happens to the member role.
</details>

added section to explain impacts on member role

---

CMakeLists.txt
libnetdata/parser/README.md

- Keep minimal documentation (overview) and refer to the actual code
- Add parser.c and parser.h under libnetdata

Simplify parser README.md and add parser files to CMakeLists.txt

---

database/engine/README.md
docs/store/change-metrics-storage.md

Put updated info in change metrics storage, which is linked from everywhere else. 
Move some info out of database/engine/README and add links between the two files.

Update main metric retention docs

---

docs/quickstart/infrastructure.md

Closes https://github.com/netdata/learn/issues/1354
This PR uses the component introduced in https://github.com/netdata/learn/pull/1357, so that the ingest process can recognize the links inside the component code. Due to the nature of the component, a pattern of `[](LINK)` was applied in the links, so that the component can send the user to the link using a regular expression.
Also, to make the file GitHub friendly, a list with the links was added below the code so it can render here as well.

Use BoxListItemRegexLink component in docs/quickstart/insfrastructure.md

---

docs/netdata-for-IoT.md

Will make a blog post out of a better version of this.

Hide netdata for IoT from learn.

---

docs/cloud/manage/plans.md
docs/cloud/manage/role-based-access.md

The purpose of this PR is to add the mentions to:
* Early Bird plan on Plans page
* Member roles on Roles and Permissions
</details>

Roles docs: Add Early Bird and Member role

---

docs/category-overview-pages/integrations-overview.md
docs/export/enable-connector.md

Related to netdata/learn#1349
Fix some broken links in markdown files

Fix broken links in integrations-overview

---

docs/Running-behind-apache.md
docs/Running-behind-caddy.md
docs/Running-behind-h2o.md
docs/Running-behind-haproxy.md
docs/Running-behind-lighttpd.md
docs/Running-behind-nginx.md
docs/category-overview-pages/misc-overview.md

Miscellaneous category explanation (that the contents are temporary)
Finalize renaming setup to configuration

Add misc landing page and move proxy guides

---

packaging/installer/methods/cloud-providers.md
packaging/installer/methods/synology.md

Fix kickstart link

---

docs/cloud/manage/view-plan-billing.md

Update page on:
* Remove mention to shipping address on Customer portal
* Remove and update text on the process to move or change current plan
* Review descriptions of the data series that will be displayed on the Usage chart
</details>

reviewed plans page to be according to latest updates

---

aclk/README.md
collectors/COLLECTORS.md
docs/category-overview-pages/integrations-overview.md
docs/cloud/alerts-notifications/notifications.md
docs/cloud/alerts-notifications/view-active-alerts.md
docs/cloud/manage/plans.md
docs/cloud/manage/role-based-access.md
docs/cloud/visualize/nodes.md
docs/configure/common-changes.md
docs/configure/nodes.md
docs/configure/start-stop-restart.md
docs/dashboard/dimensions-contexts-families.md
docs/dashboard/how-dashboard-works.md
docs/export/external-databases.md
docs/guides/configure/performance.md
docs/guides/monitor-cockroachdb.md
docs/guides/monitor/lamp-stack.md
docs/guides/monitor/pi-hole-raspberry-pi.md
docs/monitor/enable-notifications.md
docs/monitor/view-active-alarms.md
docs/visualize/create-dashboards.md
docs/visualize/interact-dashboards-charts.md
exporting/README.md
health/README.md
health/notifications/pagerduty/README.md
ml/README.md
packaging/installer/README.md
packaging/installer/methods/cloud-providers.md

Related to https://github.com/netdata/learn/issues/1349
In this PR several broken links are fixed, and in cases that the section with the link was a "What's Next" section it was completely removed (as discussed with @cakrit it creates a moderate friction point having these sections)

Fix broken links in our documentation

---

cli/README.md
daemon/README.md
daemon/config/README.md
docs/anonymous-statistics.md
docs/category-overview-pages/developers-overview.md
docs/category-overview-pages/integrations-overview.md
docs/category-overview-pages/misc-overview.md
docs/category-overview-pages/references-overview.md
docs/dashboard/reference-web-server.md
docs/metrics-storage-management/reference-streaming.md
registry/README.md
streaming/README.md
web/gui/README.md
web/server/README.md

Moved to operations and references.

Remove References category from learn

---

packaging/makeself/README.md

- Add intro paragraph.
- Reorg in learn
- Cosmetic changes

Update static binary readme

---

build_external/README.md
packaging/building-native-packages-locally.md
packaging/installer/methods/methods.md
packaging/installer/methods/source.md
packaging/maintainers/README.md
packaging/makeself/README.md

package maintainers section with more content.

Learn installation reorg part 2

---

collectors/COLLECTORS.md
collectors/README.md

Making that document a bit sexier.

Change link text to collectors.md

---

database/rrd.h
database/rrdhost.c
health/health.c

The `host->varlib_dir` doesn't seem to be of any use anymore so it is removed

Clean host structure

---

docs/category-overview-pages/deployment-strategies.md

Test of centralization, with a file with no learn headings

Add deployment strategies

---

docs/cloud/visualize/nodes.md
docs/monitor/view-active-alarms.md
docs/quickstart/infrastructure.md

fix links from removed docs

---

docs/netdata-security.md

fix proxy links in netdata security

---

docs/netdata-security.md

made it absolute.
removed metadata
fixed capitalization

fix relative link to anonymous statistics

---

docs/cloud/visualize/interact-new-charts.md

This PR closes https://github.com/netdata/learn/issues/1389

Move images in "interact-new-charts" from zenhub to github

---

docs/monitor/enable-notifications.md

Product discontinued, will check if the notification integration can work with google chat, to update the docs and reenable.
</details>

Remove google hangouts from list of integrations

---

docs/cloud/manage/view-plan-billing.md

Added the Billing FAQ
</details>

add FAQ information provided by Finance

---

docs/cloud/manage/plans.md
docs/cloud/manage/role-based-access.md

Reviewed roles descriptions according to what is on the app
https://github.com/netdata/cloud-frontend/pull/4066
</details>

reviewed role description to be according to app

---

collectors/COLLECTORS.md

add go.d example collector to #etc section

---

docs/guides/configure/performance.md

Update Performance Optimization Options

---

docs/configure/nodes.md

New usage info, a bit more clarity on what it does.

Update edit-config documentation

---

docs/cloud/visualize/node-filter.md
docs/cloud/war-rooms.md
docs/dashboard/visualization-date-and-time-controls.md
docs/quickstart/infrastructure.md

Closes https://github.com/netdata/learn/issues/1040
This PR updates images and other information inside the document, all the images are from our demo sites, so I guess we don't need to blur information in them.
Also some syntax errors are fixed.

Organize information from war-rooms.md to its correct location

---

docs/guides/python-collector.md

Based on discussion for https://github.com/netdata/netdata/pull/14674

Suggest PRs to go to the community project

---

collectors/COLLECTORS.md

Update third party collectors with ethtool collector
Closes: #14674

Add ethtool in third party collectors

---

docs/Running-behind-nginx.md

Moving this info from https://github.com/netdata/netdata/blob/master/docs/guides/configure/performance.md

Add gzip compression info to nginx proxy readme

---

docs/guides/configure/performance.md

Improve performance.md

---

daemon/global_statistics.c
daemon/main.c
daemon/main.h
database/rrdhost.c
ml/Config.cc
ml/ad_charts.cc
ml/ad_charts.h
ml/ml-dummy.c
ml/ml-private.h
ml/ml.cc
ml/ml.h

This reverts commit 5046e034212c008557dd014196b6f6204eda24b2.
Will re-apply once we investigate an issue that occurs during the shutdown of the agent.
N/A

Revert "Use static thread-pool for training. (#14702)"

---

database/contexts/query_scope.c
web/api/queries/weights.c

/api/v2/X part 6

---

collectors/plugins.d/README.md

Fix capitalization on readme

---

aclk/README.md

Update privacy link in aclk doc

---

docs/netdata-security.md

- Change heading
- Make table with directories hidden under details
- Remove TOC

Minor improvements to netdata-security.md

---

database/engine/README.md

Remove info important to users, which is in docs/change-metrics-storage.md

Update database engine readme

---

collectors/COLLECTORS.md

add some third party collectors, comes from here: https://github.com/netdata/community/pull/78
</details>

add some third party collectors

---

claim/README.md
docs/cloud/manage/invite-your-team.md
docs/cloud/manage/plans.md
docs/cloud/manage/sign-in.md
docs/cloud/manage/view-plan-billing.md
docs/cloud/spaces.md
docs/cloud/visualize/interact-new-charts.md
docs/cloud/visualize/node-filter.md
docs/cloud/visualize/overview.md
docs/cloud/war-rooms.md
docs/dashboard/visualization-date-and-time-controls.md
docs/getting-started/introduction.md
docs/guides/troubleshoot/troubleshooting-agent-with-cloud-connection.md
docs/monitor/view-active-alarms.md
docs/quickstart/infrastructure.md
docs/store/distributed-data-architecture.md
packaging/installer/README.md

This PR is related to https://github.com/netdata/learn/issues/1507 and the child issues referenced in it.
I added the description from our map file, in some cases made necessary changes, and also formatted the file and removed "what's next" section.
This batch is some of the first files and the first folder in the heirarchy of Learn, to see how Ahrefs reacts to the changes.

First batch of adding descriptions to the documentation

---

docs/netdata-security.md

Summary:
- Needed to change the wording mostly on Agent related section to mentio "the user" instead of "you"
- Updated the Data retention section to say "...ninety (90) days following a deletion in Netdata Cloud.", with Auditing events this is stored for longer
</details>

review usage of you to say user instead

---

collectors/cgroups.plugin/sys_fs_cgroup.c
collectors/proc.plugin/proc_net_dev.c

First PR bringing https://github.com/netdata/netdata/issues/14799
After a talk with @ilyam8 about docker, we decided to split work in different PRs. This initial PR is bringing cgroup name that is already available in our current parser code. We will have another PR modifying the parser and adding more labels.
1. Start docker images
2. Compile this branch and start `netdata`
3. Query our charts (https://localhost:19999/api/v1/charts?all) and check on your host the labels:
```sh
"cgroup_qemu_qemu_5-ubuntu2004ubuntu2004linux.cpu": 		{
"id": "cgroup_qemu_qemu_5-ubuntu2004ubuntu2004linux.cpu",
"name": "cgroup_qemu_qemu_5-ubuntu2004ubuntu2004linux.cpu",
"type": "cgroup_qemu_qemu_5-ubuntu2004ubuntu2004linux",
"chart_labels": {
"_collect_plugin":"cgroups.plugin", …
```

Add labels for cgroup name

---

docs/netdata-security.md

Simple fix, the link was reported by ahrefs, changed it to its https counterpart.

Update link from http to https

---

docs/cloud/alerts-notifications/add-opsgenie-notification-configuration.md

Ref: https://github.com/netdata/netdata-cloud/issues/775
Add the documentation describing the flow of adding a new Opsgenie integration for Cloud.

Add opsgenie integration docs

---

collectors/python.d.plugin/w1sensor/README.md

As also pointed by a user, no example configuration was provided, thus a link was added to the default .conf file

Add example configuration to w1sensor collector

---

docs/cloud/alerts-notifications/notifications.md
docs/cloud/manage/plans.md

Added Opsgenie as a Business level notification method
</details>

add opsgenie as a business level notificaiton method

---

collectors/ebpf.plugin/README.md
collectors/ebpf.plugin/ebpf.d.conf

Fixes https://github.com/netdata/netdata/issues/14892
1. We are not modifying code, only take a look in documentation for possible grammar and additional hardware information.
- Which area of Netdata is affected by the change? eBPF.plugin
- Can they see the change or is it an under the hood? If they can see it, where? yes, server won't be overloaded when high frequency updates happen.
- How is the user impacted by the change?  Process with time to other software.
- What are there any benefits of the change? Stability.
</details>

Disable threads that update with high frequency

---

aclk/README.md
daemon/config/README.md
docs/cloud/manage/plans.md
docs/cloud/spaces.md
docs/cloud/visualize/interact-new-charts.md
docs/guides/troubleshoot/troubleshooting-agent-with-cloud-connection.md
packaging/installer/README.md

Closes https://github.com/netdata/learn/issues/1548
This PR changes all admonitions that were made with docusaurus syntax into our agreed style, that renders on GitHub too.

change docusaurus admonitions to our style of admonitions

---

aclk/aclk.c

Removes historical limit.
</details>

minor - remove RX_MSGLEN_MAX

---

docs/guides/using-host-labels.md

Add mention of spaces, rooms, virtual nodes and metric labels.

Make the document more generic

---

database/README.md

The screenshot that was previously present is broken, so I took the content from [our blogpost](https://blog.netdata.cloud/ksm/) (the explanations for the charts) and added those images + descriptions to this doc as well.

Fix broken image, in database/README.md

---

database/engine/README.md

Update dbengine README.md

---

packaging/makeself/makeself-header.sh

Prevent pager from preventing non-interactive install

---

cli/README.md
system/netdata.conf

Added in https://github.com/netdata/netdata/pull/14906 but not documented.

Document netdatacli dumpconfig option

---

collectors/python.d.plugin/adaptec_raid/README.md
collectors/python.d.plugin/adaptec_raid/metrics.csv

This is the first of the bunch that is mentioned in https://github.com/netdata/product/issues/3116, couple of things:
1. for `ld_status` I am not sure about the `node` scope
2. If you want, let's keep the wording in the README the same, so I can replace it with the table inside the documentation
From the review comments on this first one, I will move on to the rest.

Add adaptec_raid metrics.csv

---

collectors/timex.plugin/metrics.csv

Implements part of netdata/product#3116. 
Check CSV syntax.
</details>

add metrics.csv to timex.plugin

---

collectors/charts.d.plugin/ap/metrics.csv
collectors/charts.d.plugin/apcupsd/metrics.csv
collectors/charts.d.plugin/libreswan/metrics.csv
collectors/charts.d.plugin/nut/metrics.csv
collectors/charts.d.plugin/opensips/metrics.csv
collectors/charts.d.plugin/sensors/metrics.csv
collectors/charts.d.plugin/sensors/sensors.chart.sh

Implements part of netdata/product#3116. 
Check CSV syntax.
</details>

add metrics.csv to charts.d

---

database/contexts/rrdcontext.h
web/api/queries/query.c

`/api/v2/data`, do not convert to percentage, when the raw option is given

do not convert to percentage, when the raw option is given

---

aclk/aclk_capas.c

Set api v2 version 2

---

CMakeLists.txt
Makefile.am
aclk/aclk_capas.c
aclk/aclk_query.c
aclk/aclk_query.h
aclk/aclk_rx_msgs.c
aclk/schema-wrappers/agent_cmds.cc
aclk/schema-wrappers/agent_cmds.h
aclk/schema-wrappers/proto_2_json.cc
aclk/schema-wrappers/schema_wrappers.h

Allows cloud to cancel long running requests in case nobody is waiting for them meanwhile. Long overdue.
</details>

Cancel Pending Request

---

CMakeLists.txt

Fix cmake errors

---

web/api/queries/weights.c

weights endpoint: volume diff of anomaly rates

---

packaging/makeself/install-or-update.sh

Instead of just making all the files SUID 0, set capabilities when we know which ones are needed and `setcap` is installed.
If setcap is not available, we still fall back properly to SUID on plugins that truly need it.
Confirm that static builds still install correctly.
Prompted by discussion on Discord that point out that we do not use capabilities on plugins in our static installs.

Set file capabilities correctly on static installs.

---

collectors/apps.plugin/apps_groups.conf

I am running Grafana agent and would like to see it separate in apps.
Working as expected - can see after i made update locally. 
</details>

add `grafana` to `apps_groups.conf`

---

database/contexts/api_v2.c
database/contexts/query_scope.c
database/contexts/query_target.c
database/contexts/rrdcontext.h

instances filter now matches also instance_id@node_id

On data and weight queries now instances filter matches also instance_id@node_id

---

packaging/makeself/install-or-update.sh

Fixes a bug pointed out by PyroGem on Discord.
n/a

Fix typo in file capabilities settings in static installer.

---

docs/cloud/visualize/interact-new-charts.md

Closes https://github.com/netdata/learn/issues/1624
Document all the new features that are going to be released with the new release, the structure is made in a way so it explains the chart's elements in a top-down fashion.  
Some terms were also simplified.

Update chart documentation

---

docs/cloud/manage/plans.md
docs/cloud/manage/view-plan-billing.md

With the recent changes on the Billing flow we had to review our documentation.
</details>

review the billing docs for the flow

---

ml/ml.cc

SSIA.
Other than CI jobs:
1. Start an agent,
2. Wait until it writes some ML models in the DB,
3. Delete ml.db from the cache path,
4. Check logs, you should get something like:
```
248  2023-05-04 15:07:46: netdata ERROR : TRAIN[0] : SQLite error 8                                                                                                                                                                                                                                                          
249  2023-05-04 15:07:46: netdata ERROR : TRAIN[0] : Failed to store model, rc = 8 …
```

Rollback ML transaction on failure.

---

database/README.md

While reading a section of this doc, I found a line that hadn't a clear meaning in terms of structure, fixed it.

Slight wording fix on the database readme

---

collectors/cgroups.plugin/sys_fs_cgroup.c
collectors/proc.plugin/proc_diskstats.c
database/rrdset.c

- Adjust some buffers to prevent potential overflow
- Adjust call to strncpyz to prevent overflow

Adjust buffers to prevent overflow

---

docs/cloud/visualize/interact-new-charts.md

Fixed a wording issue while reading the doc.

Wording fix in interact with charts doc

---

database/sqlite/sqlite3.h

- Update SQLITE version from 3.40.1 to 3.41.2
Several compilation warnings have been fixed in this version.
No code changes on the agent -- things should just  work as expected

Update SQLITE to version 3.41.2

---

Makefile.am
cli/cli.c

Reduce the netdatacli binary size

Reduce netdatacli size

---

collectors/proc.plugin/sys_class_infiniband.c

Fixes: #14747
Not needed, the changes are straightforward.
</details>

fix infiniband bytes counters multiplier and divisor

---

docs/netdata-security.md

Minor change on the security doc, we revisit the OSSF guidelines  (best practices) one by one to verify that we meet the passing level

Update Security doc

---

docs/cloud/manage/plans.md
docs/cloud/manage/view-plan-billing.md

Update plan documentation for the waive off of space subscription price
</details>

mentioned waive off of space subscription price

---

health/health.d/cockroachdb.conf

Wrong dimension names were used, fixed.
Not needed, copied correct dim names from the src code.
</details>

fix cockroachdb alarms

---

database/contexts/query_target.c
database/contexts/rrdcontext.h

fix the units when returning percentage of a group

---

web/api/queries/query.c

Another left-over of #15100 
2 key changes in this:

percentage-of-group: fix uninitialized array vh

---

collectors/python.d.plugin/oracledb/oracledb.chart.py
collectors/python.d.plugin/oracledb/oracledb.conf

ssia, fixes an issue reported on [Community Forum](https://community.netdata.cloud/t/oracledb-plugin-not-evaluating-environment-variables/4190/5?u=ilyam8).
Not needed.
</details>

oracledb: make conn protocol configurable

---

web/api/formatters/json/json.c
web/api/formatters/rrd2json.h
web/api/netdata-swagger.yaml
web/api/queries/query.c

The final part of performing percentage of group queries.
This makes the results of such queries aggregatable across multiple agents, at the cloud.

percentage of group is now aggregatable at cloud across multiple nodes

---

packaging/installer/kickstart.sh

Key change is on line 1488 for the error message associated with code F0205, based on internal discussion on Slack.
n/a

Improve some of the error messages in the kickstart script.

---

contrib/debian/control
contrib/debian/rules

Fixes a bug introduced by https://github.com/netdata/netdata/pull/13927.
Packaging CI passes on this PR.

Fix handling of eBPF plugin for DEB packages.

---

contrib/debian/control
contrib/debian/netdata-plugin-apps.postinst
contrib/debian/netdata-plugin-debugfs.postinst
contrib/debian/netdata-plugin-ebpf.postinst
contrib/debian/netdata-plugin-freeipmi.postinst
contrib/debian/netdata-plugin-go.postinst
contrib/debian/netdata-plugin-nfacct.postinst
contrib/debian/netdata-plugin-perf.postinst
contrib/debian/netdata-plugin-slabinfo.postinst
contrib/debian/netdata.postinst
contrib/debian/rules
netdata.spec.in

Fixes an assortment of issues introduced by #13927.
- CI passes on this PR.
- Building the packages locally and then installing by hand works.
Fixes: #15121

Fix package versioning issues.

---

docs/cloud/alerts-notifications/manage-alert-notification-silencing-rules.md
docs/cloud/insights/events-feed.md

Updated Events docs with the auditing events from silencing and others that were missing
Also minor fix on silencing rules table example
</details>

updated events docs and minor fix on silecing rules table

---

configure.ac

detected unmatched quote during libnetdata channel related edits to the file
</details>

minor - fix syntax in config.ac

---

database/sqlite/sqlite_aclk_alert.c

- Check for null transition id and config hash id

Check null transition id and config hash

---

docs/cloud/alerts-notifications/add-discord-notification.md
docs/cloud/alerts-notifications/add-mattermost-notification-configuration.md
docs/cloud/alerts-notifications/add-opsgenie-notification-configuration.md
docs/cloud/alerts-notifications/add-pagerduty-notification-configuration.md
docs/cloud/alerts-notifications/add-slack-notification-configuration.md
docs/cloud/alerts-notifications/add-webhook-notification-configuration.md
docs/cloud/manage/plans.md

These changes add Mattermost integration docs on the Cloud.

Mattermost cloud integration docs

---

.github/scripts/pkg-test.sh
contrib/debian/control
contrib/debian/netdata-base.postinst
contrib/debian/netdata.postinst
netdata.spec.in
packaging/installer/kickstart.sh

May (hopefully) be reverted eventually, but for now this should resolve most if not all, of the current problems with native packages.
Resolves: https://github.com/netdata/netdata/issues/15158

Make plugin packages hard dependencies.

---

.gitignore
CMakeLists.txt
Makefile.am
libnetdata/gorilla/benchmark.sh
libnetdata/gorilla/fuzzer.sh
libnetdata/gorilla/gorilla.cc
libnetdata/gorilla/gorilla.h
libnetdata/libnetdata.h

We use a custom format but the idea remains the same. In our case,
we don't have timestamps so we only XOR values.
- Run it with libFuzzy for quite a while.
- CI jobs.

Add library to encode/decode Gorilla compressed buffers.

---

netdata.spec.in

change mandatory packages for RPMs

---

contrib/debian/control

Change package conflicts policy on deb based packages

---

collectors/ebpf.plugin/ebpf.d.conf

This a temporary fix until https://github.com/netdata/netdata/pull/15174 is merged.
</details>

ebpf: disable sync by default

---

docs/cloud/alerts-notifications/add-rocketchat-notification-configuration.md

These changes add RocketChat integration docs on the Cloud.

RocketChat cloud integration docs

---

daemon/daemon.c
health/health.c
system/systemd/netdata.service.in
system/systemd/netdata.service.v235.in

- Make sure file permissions are as we expect under cache, varlib, lock, log, claiming directories and registry

Fix file permissions under directory

---

libnetdata/locks/locks.c

readers should be able to recursively acquire the lock, even when there is a writer waiting

RW_SPINLOCK: recursive readers support

---

collectors/python.d.plugin/memcached/metrics.csv

Remove erroneous space for unit

---

collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py

Fixes: #15229
The change is straightforward, testing is not needed.
</details>

fix not handling N/A value in python.d/nvidia_smi

---

collectors/apps.plugin/metrics.csv

Add missing module column to the apps.plugin metrics.csv

Add module column to apps.plugin csv

---

collectors/proc.plugin/proc_net_dev.c

Fixes: #15206
- disable cgroups plugin, and make sure the collection of virtual interfaces is delayed.
- enable cgroups plugin, and make sure that the collection of virtual interfaces **starts right after** the interface is mapped to the container.
</details>

delay collecting virtual network interfaces

---

packaging/installer/methods/pfsense.md

The instructions for installing dependencies were unfollowable for me. It may be a pebcak issue but I used the changed instructions and got a successful install.
</details>

Update pfsense.md package install instructions

---

streaming/stream.conf

The current description is confusing/wrong. This PR fixes it.
not needed
</details>

docs: update stream.conf "health enabled by default" description

---

docs/cloud/manage/organize-your-infrastrucutre-invite-your-team.md

As the title suggests.. there was an extra parenthesis there

Remove extra parenthesis from doc

---

database/sqlite/sqlite_db_migration.c

Due to merge of https://github.com/netdata/netdata/pull/15283 an `info` needs to be changed to `netdata_log_info`.
CI should complete
</details>

Change info to netdata_log_info in sqlite_db_migration.c

---

database/rrd.h

stale vitual hosts

---

database/contexts/api_v2.c
database/sqlite/sqlite_health.c

alerts transitions sorting was flipped - fixed it.

fix alerts transitions sorting

---

database/contexts/api_v2.c

Added missing alert instances member.

add add summary linking to alert instances (ati) when options=summary,values is requested

---

database/contexts/api_v2.c
database/contexts/rrdcontext.h

avoid memory allocations for alert transitions facets processing

avoid memory allocations for alert transitions facets processing

---

collectors/plugins.d/local_listeners.c
libnetdata/log/log.c

local-listeners: use host prefix in read_cmdline

---

database/contexts/api_v2.c

alerts_transitions outputs hostnames and items statistics

alerts_transitions outputs hostnames and items statistics

---

collectors/metadata/schemas/single-module.json

Prerequisites was missing a required entry for property `list`

Add missing required field in schema

---

registry/registry.c

bearer protection - additions

---

collectors/freeipmi.plugin/metrics.csv

add missing labels to freeipmi metrics csv

---

packaging/installer/UPDATE.md

While trying to help a user noticed that there was a change on the output of `netdata -W buildinfo` so updated the grep pattern for the new format and kept the old for backwards compatibility
</details>

Fix installation type command

---

aclk/aclk.c
aclk/aclk_query.c
aclk/aclk_rx_msgs.c
collectors/statsd.plugin/statsd.c
database/contexts/rrdcontext.c
database/rrdcalc.c
database/sqlite/sqlite_aclk_alert.c
database/sqlite/sqlite_aclk_node.c
database/sqlite/sqlite_health.c
health/health.c
health/health_config.c
libnetdata/log/log.c
libnetdata/log/log.h
streaming/receiver.c
streaming/rrdpush.c
streaming/sender.c
web/api/queries/query.c
web/rtc/webrtc.c
web/server/h2o/http_server.c
web/server/web_client.c
web/server/web_server.c

Continuing from previous PRs, this one renames `log_access` and `log_health` to `netdata_log_access` and `netdata_log_health` to keep consistency with other similar logging functions.
Ensure logging is ok in `access.log` and `health.log`.
</details>

Rename log_access and log_health

---

web/gui/Makefile.am

A handful of files were missed in recent PRs. This PR fixes things by adding them (and also sorts the modified file list).

Add missing files to web/gui/Makefile.am.

---

collectors/metadata/schemas/definitions.json
collectors/metadata/schemas/single-module.json
collectors/metadata/single-module-template.yaml
docs/.templates/integration/schema.json

Once we got the actual file for the categories, we can mention that the user should refer to that to pick the correct category names.

Updates on JSON schemas

---

registry/registry.c
tests/ebpf/ebpf_thread_function.sh

Revert "dont add all nodes to registry action hello"

---

packaging/installer/netdata-updater.sh

Reported by @stelfrag  
ask @stelfrag to test
</details>

packaging: fix arch detection in update_static

---

collectors/ebpf.plugin/ebpf.c

We are hiding ebpf functions for while until we have new dashboard updates.
TBD. I am waiting for a bug fix.
</details>

Hide eBPF functions

---

README.md

From this request https://github.com/netdata/product/issues/3179 adding the CNCF reference.
</details>

add reference to cncf

---

health/health.d/consul.conf

Minor typo fix on consul.conf

---

.github/data/distros.yml
packaging/PLATFORM_SUPPORT.md
packaging/installer/install-required-packages.sh
packaging/installer/kickstart.sh
packaging/installer/netdata-updater.sh

Add support for openSUSE tumbleweed

---

collectors/cgroups.plugin/multi_metadata.yaml
collectors/charts.d.plugin/apcupsd/metadata.yaml
collectors/charts.d.plugin/nut/metadata.yaml
collectors/ebpf.plugin/multi_metadata.yaml
collectors/freebsd.plugin/multi_metadata.yaml
collectors/freeipmi.plugin/multi_metadata.yaml
collectors/ioping.plugin/metadata.yaml
collectors/macos.plugin/multi_metadata.yaml
collectors/proc.plugin/multi_metadata.yaml
collectors/python.d.plugin/adaptec_raid/metadata.yaml
collectors/python.d.plugin/anomalies/metadata.yaml
collectors/python.d.plugin/beanstalk/metadata.yaml
collectors/python.d.plugin/bind_rndc/metadata.yaml
collectors/python.d.plugin/boinc/metadata.yaml
collectors/python.d.plugin/ceph/metadata.yaml
collectors/python.d.plugin/gearman/metadata.yaml
collectors/python.d.plugin/haproxy/metadata.yaml
collectors/python.d.plugin/ipfs/metadata.yaml
collectors/python.d.plugin/megacli/metadata.yaml
collectors/python.d.plugin/memcached/metadata.yaml
collectors/python.d.plugin/retroshare/metadata.yaml
collectors/python.d.plugin/riakkv/metadata.yaml
collectors/timex.plugin/metadata.yaml

Some alerts were missing and some had wrong `os` tags. Should be fixed.

Bugfix on alerts generation for yamls

---

Makefile.am
configure.ac

Suppress H2O compilation warnings

Suppress H2O compilation warnings

---

README.md

- use "sign in" instead of "sign up" since its less scary 
- add link for netdata cloud and sign-in cta
</details>

readme: add link for netdata cloud and sign-in cta

---

integrations/categories.yaml

As discussed, added the catch all category for uncategorized integrations.

Add catch-all category entry in categories.yaml

---

packaging/docker/Dockerfile
packaging/docker/gen-cflags.sh
packaging/makeself/jobs/70-netdata-git.install.sh

Include optimizations to:
Closes: https://github.com/netdata/netdata/issues/15338
1. CI/CD
2. Deploy and test static builds and Docker build on multiple archs
For users: How does this change affect me?
This PR must overall improve the performance of the Agent. It may negatively impact low-end hardware but in acceptable margins.

Build optimizations

---

collectors/metadata/schemas/single-module.json

Decided to use multi meta + yaml anchors.
not needed
</details>

collector meta: remove meta.alternative_monitored_instances

---

docs/cloud/netdata-assistant.md

Adding learn doc for Netdata Assistant

Create netdata-assistant docs

---

docs/category-overview-pages/accessing-netdata-dashboards.md
web/gui/README.md

PR for the initial documentation updates needed for the release of the new UI on the Agent
</details>

documentation update for the release of the new UI

---

collectors/cgroups.plugin/multi_metadata.yaml

Add cgroups yaml

---

web/gui/v2/LICENSE.md
web/gui/v2/Makefile.am

Manually  hardcode the license of the v2 dashboard. 
TODO: Change the script to automatically add this
</details>

Include license for web v2

---

collectors/cgroups.plugin/multi_metadata.yaml

Add short descriptions needed for cgroups.plugin yaml.

Add short descriptions to cgroups yaml

---

collectors/freeipmi.plugin/multi_metadata.yaml

- Consolidate to one module
- Add description, category, keywords, icon

Freeipmi yaml updates

---

collectors/apps.plugin/apps_plugin.c

apps.plugin fds limits improvements

---

collectors/cgroups.plugin/multi_metadata.yaml
collectors/freeipmi.plugin/multi_metadata.yaml

Fix anchors on yaml files so that the pass the schema.

fix anchors

---

integrations/categories.yaml

So that data collection integration yamls and categories use the same key

Rename most-popular to most_popular in categories.yaml

---

health/REFERENCE.md

docs: note that health foreach works only with template

---

collectors/debugfs.plugin/multi_metadata.yaml

Updated by-hand based on individual knowledge of the areas in question.
This includes adding some info to a handful of fields we’re not actually rendering in all cases yet to save time later when we go through this properly.

Update debugfs plugin metadata.

---

collectors/apps.plugin/multi_metadata.yaml
collectors/ebpf.plugin/multi_metadata.yaml
collectors/freebsd.plugin/multi_metadata.yaml
integrations/categories.yaml

Fill in apps.plugin yaml
put unfinished ebpf and freebsd to their own categories for now

Yaml file updates

---

collectors/freeipmi.plugin/freeipmi_plugin.c

otherwise they get buffered and don't work
n/a
</details>

freeipmi flush keepalive msgs

---

collectors/charts.d.plugin/sensors/metadata.yaml

add minimal info to charts.d.plugin sensors module

Update charts.d.plugin yaml

---

web/api/badges/README.md

The current wording appears to be confusing for users, see https://github.com/netdata/netdata/issues/15482#issuecomment-1646008896
n/a
</details>

docs: clarify health percentage option

---

collectors/idlejitter.plugin/metadata.yaml

This should cover all the data that’s actually needed for this plugin in the integrations page.
n/a

Fill in metadata for idlejitter plugin.

---

integrations/schemas/collection-multi-module.json
integrations/schemas/deploy.json

ssia
Local validation check
</details>

fix collector multi schema

---

collectors/python.d.plugin/hddtemp/metadata.yaml
collectors/python.d.plugin/monit/metadata.yaml
collectors/python.d.plugin/nsd/metadata.yaml
collectors/python.d.plugin/spigotmc/metadata.yaml
collectors/python.d.plugin/squid/metadata.yaml

- hddtemp
- monit
- spigotmc
- nsd
- squid

Python collector yaml updates

---

integrations/deploy.yaml

I have updated all the Linux distros (currently listed), macOS, Docker, Kubernetes and Windows.
This is a quick PR to check how the Deploy sections will be rendered with this content.
Please check and approve.

Updated all Linux distros, macOS and Docker

---

claim/claim.c
collectors/apps.plugin/apps_plugin.c
collectors/debugfs.plugin/sys_devices_virtual_powercap.c
database/sqlite/sqlite_functions.c
registry/registry.c

added cloud status in registry?action=hello

---

collectors/nfacct.plugin/metadata.yaml

Add description for `ioping`  plugin.
</details>

Update nfacct yaml

---

collectors/diskspace.plugin/metadata.yaml

Add description for `diskspace`  plugin.
</details>

Update yaml description (diskspace)

---

collectors/freeipmi.plugin/multi_metadata.yaml

Freeimpi yaml

---

collectors/COLLECTORS.md

- after [merging this](https://github.com/netdata/community/pull/82), this pr adds it to list of third party collectors
</details>

add `diskquota` collector to third party collectors list

---

collectors/apps.plugin/README.md

Fixes: https://github.com/netdata/netdata/issues/15523#issuecomment-1649729955
</details>

docs: fix apps fd badges and typos

---

collectors/python.d.plugin/haproxy/metadata.yaml
collectors/python.d.plugin/puppet/metadata.yaml
collectors/python.d.plugin/smartd_log/metadata.yaml
collectors/python.d.plugin/squid/metadata.yaml

- smart_log
- haproxy comment out as discussed
- puppet
- a fix in squid

Fill in yaml files for some python collectors

---

integrations/categories.yaml
integrations/deploy.yaml

All the Categories have been marked appropriately for their priority.
The `deploy.yaml` has various fixes including the `quick_start` priority handling.

Fix deployment and categories

---

collectors/python.d.plugin/samba/metadata.yaml

the file was also formatted through my text editor

Add Samba collector yaml

---

collectors/python.d.plugin/postfix/metadata.yaml

postfix metadata.yaml - add links and some descriptions

---

integrations/deploy.yaml
integrations/schemas/deploy.json

- Fix syntax and formatting so that the file parses correctly.
- Rename `description` key to `install_description` to avoid collision with the key we were planning on using for the tooltips for the integration cards.
- Add a `most_popular` key.
n/a

Fixes for `deploy.yaml`.

---

integrations/deploy.yaml

Fixed typos in the descriptions and added missing icons.
Please review and approve.

Fixed typos in code blocks and added missing icons

---

.vscode/settings.json
integrations/categories.yaml

Added Exporter and Notifications categories and removed them from Data Collection
