- database/sqlite/sqlite_functions.c
The hop count for a disconnected child is assumed to be 1. This PR will check if the child is connected
and use the correct hop count when registering (or updating) the node information to the cloud.
aclk, database
- Tested in testing and staging environment
- Setup: agent with a child -> proxy -> parent setup
- Start parent and notice the information e.g
- `Queuing status update for node=a50082d1-bca7-4e96-8fc6-90f075d696fe, live=1, hops=1`
After the PR 
- Notice the updated message
- `Queuing status update for node=a50082d1-bca7-4e96-8fc6-90f075d696fe, live=1, hops=2`
> Use correct hop count if host is already in memory

- ml/Config.cc
Check logs after building with format warnings enabled.
> Use the proper format specifier when logging configuration options.

- packaging/makeself/build.sh
- packaging/makeself/jobs/10-prepare-destination.install.sh
- packaging/makeself/jobs/20-openssl.install.sh
- packaging/makeself/jobs/50-bash-5.1.8.install.sh
- packaging/makeself/jobs/50-curl-7.78.0.install.sh
- packaging/makeself/jobs/50-fping-5.0.install.sh
- packaging/makeself/jobs/50-ioping-1.2.install.sh
- packaging/makeself/jobs/70-netdata-git.install.sh
- packaging/makeself/jobs/99-makeself.install.sh
* Fixed handling of `GITHUB_ACTIONS` variable so that we can run outside of GitHub Actions again.
* Added code to clean submodules as well as the main repo prior to actually running the static build. This helps make things more reliable.
* Fixed a handful of shellcheck errors.
area/packaging
CI passes properly, and static builds work correctly when run locally.
> Assorted cleanups to static builds.

- aclk/aclk.c
- aclk/aclk_query.c
- database/sqlite/sqlite_aclk_alert.c
- database/sqlite/sqlite_aclk_chart.c
- database/sqlite/sqlite_aclk_node.c
Adds some logging for new architecture calls (via protobuf) to and from cloud to `access.log`.
Typical format for each message is:
`incoming/outgoing/process` (indicated by `IN`, `OG` or `AC` respectively).
`node id`
`hostname`
`rest of message`
e.g.:
`OG [fd3cb941-c4bf-4170-ad32-9ab63a876c85 (winterland)]: Alarm health log sent, first sequence id 1, last sequence id 1346.`
There is also a change to print the parameters to requests done through ACLK, i.e.:
`2021-11-16 10:28:26: 0: 19271 '[ACLK]:2' 'DATA' (sent/all = 2642/35053 bytes -92%, prep/sent/total = 0.11/0.73/0.84 ms) 200 '/node/fd3cb941-c4bf-4170-ad32-9ab63a876c85/api/v1/data?after=1637050431&before=1637051331&context=system.cpu&dimensions=&format=json&group=average&gtime=0&options=allow_past%7Cflip%7Cjsonwrap%7Cms&points=565'` …
> Add some logging for cloud new architecture to access.log

- .github/workflows/build.yml
- packaging/makeself/build-static.sh
This adds little-endian 64-bit POWER support (supporting POWER8 and newer) to our static builds.
These new artifacts will only be usable by manually downloading them until the new kickstart script is released.
area/ci
area/packaging
> Add POWER8+ static builds.

- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_aclk.h
- database/sqlite/sqlite_aclk_alert.c
- database/sqlite/sqlite_health.c
- database/sqlite/sqlite_health.h
- health/health.c
Queue alerts to aclk even if using the old cloud protocol, as to not miss any events during that time.
Queuing removed alerts will also wait for after the second health loop, to make sure no removed is sent that would otherwise be updated by another alert event.
New architecture
Testing can be performed by claiming an agent to a whitelisted space (i.e. use the new arch), then switch back to old, and then back to new. Alerts should go out that would otherwise wouldn't during this time.
> Always queue alerts to aclk_alert

- database/sqlite/sqlite_aclk_alert.c
- database/sqlite/sqlite_aclk_chart.c
Add checks for wc->host being null and log an error message
- CID 374279:  Null pointer dereferences  (FORWARD_NULL)
Passing null pointer "&host->rrdhost_rwlock" to "__netdata_rwlock_rdlock", which
- CID 374280:  Null pointer dereferences  (FORWARD_NULL)
Passing null pointer "&host->health_log.alarm_log_rwlock" to "__netdata_rwlock_rdlock", which dereferences it.
Alter the query execution to not require to sleep (in a loop). Report an error message on failure -- This query will be retried on the next health log cleanup iteration.
- CID 373611:  Program hangs  (SLEEP)
Call to "sql_health_alarm_log_cleanup" might sleep while holding lock "rrd_rwlock".
health, database
- Trivial checks for host being null
- Trivial change for query execution by calling sqlite3_exec
- Coverity warning vanish
> Fix coverity issues 

- aclk/aclk_util.c
- daemon/global_statistics.c
- database/sqlite/sqlite_aclk_alert.c
- database/sqlite/sqlite_aclk_chart.c
- exporting/check_filters.c
- exporting/mongodb/mongodb.c
- exporting/process_data.c
- exporting/prometheus/prometheus.c
- streaming/receiver.c
- streaming/sender.c
- web/api/queries/query.c
Cleanup the following compilation warnings
- database/sqlite/sqlite_aclk_alert.c:377:74: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'uint64_t' {aka 'long unsigned int'} [-Wformat=]
- database/sqlite/sqlite_aclk_alert.c:377:96: warning: format '%ld' expects argument of type 'long int', but argument 5 has type 'uint64_t' {aka 'long unsigned int'} [-Wformat=]
- database/sqlite/sqlite_aclk_chart.c:409:88: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'uint64_t' {aka 'long unsigned int'} [-Wformat=]
- database/sqlite/sqlite_aclk_chart.c:409:108: warning: format '%ld' expects argument of type 'long int', but argument 5 has type 'uint64_t' {aka 'long unsigned int'} [-Wformat=]
- …
> Cleanup compilation warnings

- daemon/unit_test.c
- database/rrd.h
- database/rrdset.c
1. When an API request is made on the `data` endpoint, `memory mode = dbengine`, and the requested time-frame includes the first stored value - there is no first entry in the response.
2. When an API request is made on the `data` endpoint, `memory mode = save`, Netdata was restarted, and the requested time-frame includes the first stored value - there is no first entry in the response.
The proposed solution fixes both bugs.
While fixing the aforementioned bugs, a few other ones were discovered in the query engine but they are in the scope of upcoming work.
Replaces #11599, 
dbengine, RRD.
As described in #11599,
> Simple fix for the data API query

- database/rrdhost.c
Assigns the result of `NETDATA_CONTAINER_OS_DETECTION` coming from `system-info.sh` script to the appropriate `system_info` variable.
There seems to be no real practical use for this at the moment, besides including it during streaming, and presenting it in `api/v1/info`.
Most likely the variable has been sent as empty string up to now, and after this PR will in most cases include `none` (or a reasonable value). I would not expect anything to break there, but we should check.
From `api/v1/info`, it might be picked up by analytics sent by dashboard, and might provide some false results.
I've checked the [PR](https://github.com/netdata/netdata/pull/7770) introducing this, I can't be sure if it was an oversight or in purpose...
Before this PR, `api/v1/info` doesn't have a …
> Set NETDATA_CONTAINER_OS_DETECTION properly

- collectors/freeipmi.plugin/README.md
In some distributions, the pkg-config file for the ipmi monitoring library is located in an unregistered place and our build system can't find it when it checks for dependencies. We add a note to the documentation with a suggestion of how to fix it.
Fixes #11381
freeipmi plugin documentation
> Add a note about pkg-config file location for freeipmi

- health/health.d/pihole.conf
Upon further discussion, we found out that we don't need this alert for pi-hole.
> Remove pihole_blocked_queries alert

- health/health.d/pihole.conf
[Spotted](https://github.com/netdata/agent-alerts-guides/pull/95#issuecomment-982396295) by @Ancairon 
health/
Not needed
> fix(health): `pihole_blocklist_gravity_file` and `pihole_status` info lines

- aclk/aclk_otp.c
When protobuf was made optional the `aclk_get_env` was not updated accordingly.
> Optional proto support fix

- .github/data/build-matrix.json
- .github/workflows/packaging.yml
- .github/workflows/repoconfig-packages.yml
To be merged when it goes EOL next month (expected EOL date 2021-11-30).
area/ci
n/a
> Remove Fedora 33 from CI.

- .github/data/build-matrix.json
- .github/workflows/packaging.yml
- .github/workflows/repoconfig-packages.yml
To be merged when it goes EOL upstream on 2021-12-01.
area/ci
n/a
> Remove OpenSUSE Leap 15.2 from CI.

- database/sqlite/sqlite_aclk_alert.c
Sets the `enabled` parameter of the `AlarmLogHealth` message to 1.
This specific parameter is not used by the cloud backend, so it should not have any functional difference.
ACLK/New architecture
Claim an agent to the cloud in a whitelisted space. Observe that alerts appear on the cloud as before.
> Initialize enabled parameter to 1 in AlarmLogHealth message

- health/health.d/swap.conf
Fixes: #11861
> calc: ($used + $free) > 0 ? ($used * 100 / ($used + $free)) : 0
A comparison argument should be enclosed in parentheses. W/o it the used_swap alarm calc is either 1 or 0 (if '($used + $free) > 0' is true => 1 else 0).
health/
Check this on a system with swap, ensure the value is not 1%.
> fix(health): used_swap alarm calc

- Makefile.am
- configure.ac
There was already a check for this when building with the bundled
protobuf. Considering that we needed the same check when building for
ML, I moved the check so that it can happen in either case when a
C++ linker is required for the build to succeed.
CI jobs
This should fix https://github.com/netdata/netdata/issues/11812
> Detect whether libatomic should be linked in when using CXX linker.

- packaging/makeself/build-x86_64-static.sh
- packaging/makeself/jobs/50-curl-7.78.0.install.sh
curl not static build in version v1.32.0, 
when run on pre-build netdata on ubuntu , `/opt/netdata/bin/curl` ask for need `libc.musl-x86_64.so.1` 
after install musl in ubuntu, it ask for more library and panic
the extra args not transfer to build.sh script, and can not build debug verion etc..
makeself
I think the issue PR #11490 , update curl version to 7.78.0 make the curl problem happen.
```
root@e6d638b8b4bb:/# ldd /opt/netdata/bin/curl
linux-vdso.so.1 (0x00007ffe4cef4000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fc9e50ef000)
libc.musl-x86_64.so.1 => not found
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc9e4efd000)
/lib/ld-musl-x86_64.so.1 => /lib64/ld-linux-x86-64.so.2 (0x00007fc9e551e000)
root@e6d638b8b4bb:/# /opt/netdata/bin/netdata -v
netdata v1.32.0 …
```
> fix static build, curl will be staict binary; extra args can be transfer

- packaging/installer/netdata-updater.sh
Fixes: #11519
The updater script exits with a non-zero exit code even if the update is successful. 
- Only static installs are affected.
- It happens only if a newer version of the updater script is available.
<details>
<summary>Click to see why it happens</summary>
We pass `--tmpdir-path` when running the downloaded version of the updater script.
https://github.com/netdata/netdata/blob/4a432d99fc7167de6deec8c56aef2c116cd008f8/packaging/installer/netdata-updater.sh#L229
We set `NETDATA_TMPDIR_PATH`
https://github.com/netdata/netdata/blob/4a432d99fc7167de6deec8c56aef2c116cd008f8/packaging/installer/netdata-updater.sh#L386-L387
`create_tmp_directory` always returns its value if `NETDATA_TMPDIR_PATH` is set.
https://github.com/netdata/netdata/blob/4a432d99fc7167de6deec8c56aef2c116cd008f8/pack …
> fix(updater): fix exit code when updating static install && updater script

- packaging/installer/netdata-updater.sh
Another attempt to fix #11519
As @jdelStrother correctly noticed: by default, cron sends an email if a script produces any output.
This PR:
- changes `echo >` to appropriate logging functions (info, error).
- redirects netdata-latest.gz.run output to 3.
- adds logfile removing if static version update is successful.
packaging/installer
- run the updater-script manually, ensure it produces output in the terminal.
- run the update-script in headless mode, ensure it doesn't produce any output if static update is successful, and produces otherwise.
> fix(updater): don't produce output when static update succeeded

- system/netdata.service.in
This fixes an issue with handling of email-based notification delivery on systemd-based systems that are using Postfix for mail delivery.
area/packaging
Verified through limited local testing (and confirmation from multiple users that a functionally equivalent local fix on their systems worked).
Fixes: #8820
> Fix postdrop handling for systemd systems.

- aclk/README.md
To increase visibility of how Netdata Cloud uses data, I moved the data privacy topic into a separate location.
I've included a link to the new page.
> Moved data privacy section into a separate topic

- web/api/formatters/json_wrapper.c
The context query on the agent side currently returns chart name instead of chart ids. 
This affects metric correlation queries as it will attempt  to incorrectly match chart ids (on the cloud side) with chart names. 
Although the chart id and name are identical in most cases,  this is not always the case. 
This PR changes the response to use chart ids.
database
- Simple change from rrdset->name to rrdset->id
- Verified by running metric correlations on the cloud. With this PR more charts match in a K8S enabled configuration
> Use the chart id instead of chart name in response to incoming cloud context queries

- packaging/installer/kickstart-static64.sh
- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart-64.md
- packaging/installer/methods/kickstart.md
- packaging/installer/netdata-updater.sh
Attempts fixing issue https://github.com/netdata/netdata/issues/11906
netdata-installer.sh and kickstart.sh
- Execute kickstart.sh on a clean system and make sure it can install
- Execute netdata-installer.sh on a system with an older version of netdata, and make sure it can update to latest release 1.32.1
The changes will allow working with tags which don't start with 'v' in their name.
> fix getting latest release tag

- .github/dockerfiles/Dockerfile.build_test
This makes the CI jobs less sensitive to external packaging stupidity (like openSUSE making systemd a mandatory dependency of the `sensors` package).
area/ci
> Don’t verify optional dependencies in build test environments in CI.

- packaging/installer/netdata-updater.sh
This fixes the code responsible for checking for the availability of updates to the local copy of Netdata to correctly handle cases where the default install prefix is not used, as well as static installs.
This should prevent cases of the updater unconditionally running on some systems even if there is no available update.
area/packaging
The simplest way to test this is to intentionally install an older static build and then run the updated version of the updater script from this PR against that install with the `--no-updater-self-update` option.
Fixes: #10555
> Fix the code that checks for available updates.

- packaging/installer/methods/kickstart-64.md
- packaging/installer/methods/kickstart.md
kickstart.sh and kickstart-64.sh flags cannot be set with equal sign because the option reading loop is expecting a space delimiter (i.e: shift statement). This PR removes the equal signs in the claim examples.
Documentation
Trying the example with the equal signs lead to a failure to claim a node.
> Fix claim node examples in kickstart(-64) documentation

- aclk/schema-wrappers/node_info.cc
- aclk/schema-wrappers/node_info.h
- database/rrd.h
- database/rrdhost.c
- database/sqlite/sqlite_aclk_node.c
- streaming/rrdpush.c
- streaming/sender.c
We achieve this by adding the `ml_{capable,enabled}` fields in
`system_info`. When streaming, these fields allow a parent to understand if
the child has ML and if it runs ML for itself.
A newly added protobuf message contains the aforementioned field. Inside
`NodeInfo` the information is an exact copy of `system_info`. Inside
UpdateNodeInfo the `ml_capable` field reflects the ability of the localhost
to run ML, and the `ml_enabled` field denotes the training status of the
specified node instance.
aclk
TBD
Setting the `ml_{capable,enabled}` fields inside `rrdhost_create` is a little bit
awkward. The reason we have to do this is because there's an ML configuration
option that allows a user to filter by hostname the nodes to be trained. This means
that we need to create/initialize the …
> Send ML feature information with UpdateNodeInfo.

- .github/workflows/review.yml
ESLint [needs to be installed](https://github.com/reviewdog/action-eslint#example-usage) in order to run reviewdog/action-eslint GHA.
Based on https://github.com/reviewdog/action-eslint/issues/56#issuecomment-832074739
The error we are having currently
```
> Running `npm install` to install eslint ...
/home/runner/work/_actions/reviewdog/action-eslint/v1/script.sh: 20: /home/runner/work/netdata/netdata/node_modules/.bin/eslint: not found
eslint version:
> Running eslint with reviewdog 🐶 ...
/home/runner/work/_actions/reviewdog/action-eslint/v1/script.sh: 23: /home/runner/work/netdata/netdata/node_modules/.bin/eslint: not found
```
ci
Not needed
> fix(ci): install ESLint before running reviewdog/action-eslint

- Makefile.am
This PR adds the `-latomic` reference to the linker after the protobuf libraries, so that `libprotobuf.a` can resolve `__atomic` functions if needed.
Linking is ok without this PR if ml is enabled. If it is not (`--disable-ml`), at the linking stage the error `arena.cc:(.text+0xab4): undefined reference to '__atomic_fetch_add_8'` is produced by the linker for `libprotobuf.a`
Build
This was tested on a clean Raspbian 11 (bullseye), as a response to https://github.com/netdata/netdata/issues/11915.
On a clean Raspbian installation, on a raspberry, try to compile master, or a latest stable release.
Specify `--disable-ml`. Link might fail. Using the changes in this PR, linking should succeed.
> Include libatomic again to allow protobuf to resolve

- claim/netdata-claim.sh.in
ssia, URL_BASE is set to "https://app.netdata.cloud"
https://github.com/netdata/netdata/blob/14c6322c95bf46cb33f9c3afc9a2d641bd1cfe69/claim/netdata-claim.sh.in#L138-L139
We shouldn't overwrite it when passing `-url=""`.
claim
Not needed
> fix(claim): set URL_BASE only if `-url` parameter value is not null

- collectors/python.d.plugin/fail2ban/README.md
- collectors/python.d.plugin/fail2ban/fail2ban.chart.py
- web/gui/dashboard_info.js
Fixes netdata/product#2590
This PR adds "Failed attempts" charts. 
Fail2ban logs [Found](https://github.com/fail2ban/fail2ban/blob/80805cabfcf57dd0454d47d7f86d43c6738ce629/fail2ban/server/filter.py#L705-L719) when it finds a line that matches 'failregex' in the given log file.
collectors/python.d/fail2ban
Tested by adding manually 'Found' lines to the log file.
> feat(python.d/fail2ban): add "Failed attempts" chart, cleanup

- .github/data/build-matrix.json
- .github/workflows/packaging.yml
- .github/workflows/repoconfig-packages.yml
It officially goes EOL on 2022-01-01.
area/ci
area/packaging
n/a
> Remove Ubuntu 21.04 from CI and packaging.

- configure.ac
Fixes error in `configure.ac` causing new cloud protocol to not be built.
If agent with this PR has all deps it should build the new cloud protocol
> Fix error in configure.ac

- collectors/python.d.plugin/postgres/postgres.chart.py
Although most Postgres instances in the world have BLCKSZ = 8*1024, it's not correct to hard-code this value.
current_setting('block_size') is already used in the file (e.g., in QUERY_BGWRITER), this commit fixes a couple of more hard-coded entries.
> Postgres: use block_size instead of 8*1024

- CMakeLists.txt
- configure.ac
- exporting/pubsub/README.md
- exporting/pubsub/pubsub_publish.cc
- netdata-installer.sh
[C++ Client Libraries for Google Cloud Services](https://github.com/googleapis/google-cloud-cpp) are available and stable. We are updating our build system and build instructions in order to use the new library instead of a deprecated one.
pkg-config files for the new libraries include a lot of dependencies so it takes a long time to process the dependency tree. Enable/disable options were added to the installation script to allow bypassing of the package configuration and build of the connector.
Fixes #10193
exporting engine, build system
- Install the `google-clous-cpp` libraries.
- Build netdata.
- Configure the pubsub exporting connector and check if it sends data to Google Cloud PubSub Service.
- Build netdata with `--disable-exporting-pubsub` and `--enable-exporting-pubsub`. Check …
> Update dependencies for the pubsub exporting connector

- configure.ac
The latest release of AWS SDK for C++ can be compiled with the newest GCC at last, but there were changes in `libaws-cpp-sdk-core` - cJSON functions were renamed to avoid name clashes. We remove a corresponding check for symbols from build configuration to allow Netdata to be built with either old or new versions of the SDK.
We also remove checking for AWS SDK dependencies because its build system and existing packages already control them.
build system
Install `aws-sdk-cpp` 1.9.136-1, Build Netdata with AWS Kinesis support enabled `--enable-backend-kinesis`.
> Don't check for symbols in libaws-cpp-sdk-core

- packaging/installer/netdata-updater.sh
* Updated the script to actually be POSIX compliant shell script (this is an ongoing project to improve our portability).
* Restructured the install type detection to leverage the `.install-type` file if present.
* Added updater code to handle installs done with our official DEB/RPM binary packages.
area/packaging
Testing should be as simple as taking the `netdata-updater.sh` script from this PR and running it on a system with an existing install with the option `--no-updater-self-update`.
> Add support to updater for updating native DEB/RPM installs with our official packages.

- packaging/installer/functions.sh
Fixing retriving service commands so that they don't return failure if don't exist.
This way we keep the current behavior (if the command doesn't exist, the variable is empty) but at the same time, we don't get any failures.
This allows us to import functions.sh in other scripts, while using the `set -e` option.
functions.sh (used in netdata installer)
Verify (manually) that the those variables are receiving same values when the command exists, and when it doesn't exist.
Verified that builds passed with this new change in place.
> fix retrieving service commands without failure

- CMakeLists.txt
- backends/prometheus/remote_write/remote_write.cc
There are several flaws in CMake build configuration which prevent normal build using CMake.
- After #11559 `librt` is not linked and CMake build fails.
- `pb.cc` and `pb.h` files for the Prometheus remote write exporter are generated in the root folder which leads to compilation problems in some circumstances.
- Anomaly detection (#11548) wasn't added to the CMake build configuration.
Netdata cmake build
Build Netdata using CMake:
1. Absence of `librt` doesn't prevent linking netdata daemon.
2. `remote_write.pb.cc` and `remote_write.pb.h` are in `exporting/prometheus/remote_write` in the source tree instead of the build root.
3. You can build Netdata either with or without `dlib`.
> Fix cmake build

- health/notifications/alarm-notify.sh.in
- health/notifications/pushbullet/README.md
Allows notifications to be sent to PushBullet channels, in addition to or instead of PushBullet user email addresses.
A combination of user email addresses and/or channels can be specified, they are not exclusive. e.g:
`DEFAULT_RECIPIENT_PUSHBULLET="user1@example.com user2@example.com #channel1 #channel2"`
Channel tags must be prefixed with a hash (e.g. #channel), as explained in the updated README.md.
Backward compatible with only user email addresses being specified; does not remove or affect any existing functionality.
PushBullet notifications
Tested with PushBullet channel names, email addresses and a combination of the two. All notifications received as expected.
> Allow PushBullet notifications to be sent to PushBullet channels

- collectors/proc.plugin/sys_class_infiniband.c
- daemon/unit_test.c
- database/rrdset.c
- health/health.c
- health/health_log.c
- libnetdata/log/log.c
- streaming/receiver.c
- streaming/rrdpush.c
- streaming/sender.c
- web/api/exporters/shell/allmetrics_shell.c
- web/api/formatters/rrdset2json.c
- web/api/web_api_v1.c
`time_t` type may be different on different platforms. We should cast it to a definite type before printing.
Fixes #11830
Thank you @WYC-2020!
The PR was tested on the `openwrt/openwrt` master branch.
1. Prepare an OpenWrt build for 32bit architecture (x86 generic). It's a very lo-o-ong and space-consuming process 😉.
```
git clone https://git.openwrt.org/openwrt/openwrt.git
./scripts/feeds update -a
./scripts/feeds install -a
make menuconfig
make -j8
```
2. Make changes to the netdata package
- `Makefile`
```
PKG_VERSION:=time_t-format
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://codeload.github.com/vlvkobal/netdata/tar.gz/$(PKG_VERSION)?
PKG_HASH:=4c9615cde21e427c0ab3d900a6acdb0ba7468b89507e8ab480e699f182b8d86a
DEPENDS:=+zlib +libuuid +libuv +libmnl +libjson-c …
```
> Fix time_t format

- aclk/aclk.c
- aclk/aclk_rx_msgs.c
- aclk/aclk_rx_msgs.h
Previously we planned to have multiple message types of messages coming to `cmd`. With new cloud architecture that lost its meaning as we will ever only have `http` message. All new messages in future will be proto based.
Additionally it fixes the cloud rx messages ACLK chart in dashboard.
> ACLK-NG remove 'cmd' switch by message type

- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_aclk.h
- database/sqlite/sqlite_aclk_alert.c
- database/sqlite/sqlite_aclk_chart.c
This PR tries to fix a situation, where the agent is slower to activate children threads than the cloud sending start streaming commands.
If a child agent is already known to the parent, then the parent will create a thread for it at the start, but will wait until the child is connected to activate it.
When the child connects, ACLK will send a `status update` message to the cloud for this child. The parent will then connect the thread created at the start with this host. It can happen though that the start streaming commands arrive before the agent has completed this process (runs on the internal timer). If this happens, then the start streaming code will fail to find an active thread and will drop those messages.
This PR adds another check, so that if getting the active thread returns …
> Try to find worker config thread from inactive threads for new architecture

- web/gui/dashboard_info.js
Fixes #11880. See https://github.com/netdata/netdata/issues/11880#issuecomment-990244086 for details.
web/
Not needed
> fix: add a note that netfilter's `new` and `ignore` counters are removed in the latest kernel

- collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py
This PR adds BAR1 memory usage chart. Bar1 memory already exists in nvidia_smi, it's just not displayed with Netdata.
collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py
Successfull build and running in production in our organization for more than 3 weeks (Ubuntu 18.04, Netdata 1.32.1).
> python.d/nvidia_smi: add bar1 chart

- collectors/nfacct.plugin/plugin_nfacct.c
The charts priority reset to default (1000) because we don't set it when adding dimensions
```cmd
CHART netfilter.nfacct_packets '' 'Netfilter Accounting Packets' 'packets/s' 'nfacct' '' stacked 8906 1 nfacct.plugin
CHART netfilter.nfacct_packets '' 'Netfilter Accounting Packets' 'packets/s'
DIMENSION myport '' incremental 1 1
BEGIN netfilter.nfacct_packets
SET myport = 1494
END
CHART netfilter.nfacct_bytes '' 'Netfilter Accounting Bandwidth' 'kilobytes/s' 'nfacct' '' stacked 8907 1 nfacct.plugin
CHART netfilter.nfacct_bytes '' 'Netfilter Accounting Bandwidth' 'kilobytes/s'
DIMENSION myport '' incremental 1 1000
BEGIN netfilter.nfacct_bytes
SET myport = 125776
END
```
collectors/
Checks the Netfilter accounting charts priority, ensure it is correct.
> fix(nfacct.plugin): Netfilter accounting charts priority

- system/netdata.service.in
Fixes: #11895
`CAP_NET_ADMIN` is required for [nfacct.plugin](https://github.com/netdata/netdata/tree/master/collectors/nfacct.plugin#nfacctplugin) to collect Netfilter accounting metrics (bytes, packets).
collectors/
Tested manually. As soon as I added `CAP_NET_ADMIN` Netfilter accounting started to work.
> fix(nfacct.plugin): Netfilter accounting data collection

- system/netdata.service.in
If you try to run the perf plugin there is an error
```
2022-01-12 13:50:14: netdata INFO  : PLUGINSD[perf] : connected to '/usr/libexec/netdata/plugins.d/perf.plugin' running on pid 200441
sh: line 1: /usr/libexec/netdata/plugins.d/perf.plugin: Operation not permitted
```
Since Linux 5.8 you need to set [`CAP_PERFMON` capability](https://manned.org/perf_event_open.2#head8) to access PMUs.
Related: #11957
netdata systemd service settings
Enable perf plugin
```
[plugins]
perf = yes
[plugin:perf]
update every = 1
command options = all
```
check if it's running after Netdata is restarted.
> Add a missing capability for the perf plugin

- collectors/node.d.plugin/snmp/README.md
As Ilya and Manos have identified, the documentation about SNMP v3 asks users to set the version=3 option, but the example didn't reflect this.
I updated the exampled and made minor improvements for clarity.
> Updated SNMP v3 documentation

- database/rrd.h
The order of the struct's fields makes the bitfields irrelevant in this case.
database
- Local & CI builds
- sizeof before/after remains the same at 1256 bytes.
> Remove bitfields from rrdhost.

- ml/kmeans/SamplesBuffer.h
Add a final step to the preprocessing of feature vectors to make them always be absolute values only. This follows on from some internal research showing the impact of this on the distance measure used to generate anomaly scores ([illustrative colab notebook](https://colab.research.google.com/drive/1nBHxaNDzRFcm5fmctv1sY0_bTfa4k-M7?usp=sharing)).
In below chart we add some contamination to the metric in last part of the chart. 
Orange line below then shows impact of ensuring feature vectors are all absolute as opposed to allowing both positive and negative which can lead to a bias in distance measures of metics such as system.cpu that tend to randomly move up and down from second to second. 
In this case the orange line behaves better as an anomaly score and jumps consistently in the …
> Use absolute features when doing training/prediction.

- .gitignore
[ycm](https://github.com/ycm-core/YouCompleteMe)'s clangd completer started creating the indexer's cache in the repository's root.
CI jobs + verified with `git status`.
> Ignore clangd cache directory.

- aclk/aclk_query_queue.c
- aclk/aclk_stats.c
- aclk/aclk_stats.h
Query thread processes also queries that are originated from agent (pushed). Therefore describing this chart as requests from cloud is wrong.
This fixes user facing chart description and also renames variables to not confuse people in future.
> Fixes Wrong Chart Description

- streaming/receiver.c
On a parent child setup, when `health enabled by default = auto` and a child disconnects, the host health_enabled is set to 0. 
When the child reconnects, if the host structure is still in memory, the health_enabled is not properly initialized
streaming, health
- Set up parent child with `health enabled by default = auto` 
- Check the `/api/v1/alarms` for the child. It should indicate `"status" : true`
- Restart the child 
- Check the `/api/v1/alarms` for the child. It should say `"status" : false` 
Apply the PR and repeat the test. The `/api/v1/alarms` for the child should now say `"status" : true`
> Perform a host metadata update on child reconnection

- database/sqlite/sqlite_aclk_alert.c
This PR fixes the coverity error #374746:
```
*** CID 374746:  Resource leaks  (RESOURCE_LEAK)
/database/sqlite/sqlite_aclk_alert.c: 335 in aclk_push_alarm_health_log()
329     
330             if (unlikely(!host)) {
331                 log_access(
332                     "AC [%s (N/A)]: ACLK synchronization thread for %s is not yet linked to HOST.",
333                     wc->node_id,
334                     wc->host_guid);
>>>     CID 374746:  Resource leaks  (RESOURCE_LEAK)
>>>     Variable "claim_id" going out of scope leaks the storage it points to.
335                 return;
336             }
337         }
338     
339         uint64_t first_sequence = 0;
340         uint64_t last_sequence = 0;
```
Sqlite/Health
N/A
> Fixes coverity 374746

- collectors/python.d.plugin/python_modules/bases/FrameworkServices/ExecutableService.py
Fixes: #11977
collectors/python.d.plugin
Tested by @tazard in https://github.com/netdata/netdata/issues/11977#issuecomment-1013614832
> fix(python.d): ignore decoding errors in ExecutableService

- database/sqlite/sqlite_aclk_alert.c
- health/health.c
- health/health_config.c
- health/health_json.c
- health/notifications/alarm-notify.sh.in
This PR, extends the `edit_command` field of an alert event, to include also the localhost's host name, e.g.:
`sudo /home/evas/stuff/netdata/install_netdata_ng_13//netdata/etc/netdata/edit-config health.d/linux_power_supply.conf=3=winterland`
The `edit_command` field is transferred to cloud and is used in the part of the notification email (and in other parts of cloud UI) to indicate which file needs to be edited to adjust the current alarm, .ie:
In case the alert is raised by a parent, on metrics from a child, we need to display to the user to login to the parent to edit this alert's config. This change will help with that, as in the cloud will display the hostname of whatever we include in the `edit_command` field.
Health
Can be tested by running an agent, and observing the `command` …
> Add localhost hostname to the edit_command

- .github/PULL_REQUEST_TEMPLATE.md
As discussed on Slack, "component" is not really useful. area/* labels do the same job and are assigned automatically.
Not needed.
> remove "component" from PR template

- CMakeLists.txt
- Makefile.am
- configure.ac
- daemon/commands.c
- daemon/unit_test.c
- database/engine/pagecache.c
- database/engine/rrdengine.c
- database/engine/rrdengineapi.c
- database/engine/rrdenginelib.h
- libnetdata/Makefile.am
- libnetdata/completion/Makefile.am
- libnetdata/completion/completion.c
- libnetdata/completion/completion.h
- libnetdata/libnetdata.h
- spawn/spawn.c
- spawn/spawn_client.c
Prior to this commit both daemon/commands.c and spawn/spawn.c used to
include database/engine/rrdenginelib.h, ie. a header file that is available
only when enabling the dbengine feature.
Local builds & CI jobs
> Do not use dbengine headers when dbengine is disabled.

- collectors/charts.d.plugin/example/README.md
Old page:
If you viewed this page on the website, you couldn't see that the Github repo hosted the example. 
I added a link so that the website makes sense.
> Included link to charts.d example

- packaging/installer/README.md
- packaging/installer/methods/kickstart.md
macOS includes cURL by default, but not wget.
n/a
> Add alternative install command for macOS.

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
The condition checking for an unprefixed install was insufficient, resulting in trying to use an incorrect path for claiming under some cases.
Fix can be verified by running the updated copy of the script from this PR on a system which has an existing install of Netdata to attempt to claim the node. Without this fix, it will throw an error due to attempting to use an incorrect path for the claiming script. With this fix, it will properly claim the node.
Fixes: #11998
> Fix install prefix handling for claiming code in new kickstart script.

- collectors/python.d.plugin/python.d.plugin.in
This PR allows avoiding explicitly configuring using python3. This is needed because some of our python.d collectors work only with python3.
Fixes https://github.com/netdata/netdata/issues/11874#issuecomment-988876877
Not needed
> fix(python.d.plugin): prefer python3 if available

- packaging/makeself/install-or-update.sh
some plugin need root privileges; but when use pre build version, `perf.plugin` `slabinfo.plugin` lost their privileges;and will start failed.
All plugins that have set permissions at build should be reset permissions when they are installed
area/packaging
> fix permissions of plugins that may be built

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
This fixes two bugs in selection of static archives for installation when doing a static install:
* For stable releases, we were trying to use a file name which did not actually exist.
* For nightly builds, we were unconditionally using the x86_64 build irrespective of the local system architecture.
Verified by testing locally using the `--static-only` option.
Fixes: #12002
> Fix handling of static archive selection for installs.

- CMakeLists.txt
There is a deprecation warning for `libmongoc` configuration in CMake build
```
CMake Warning at /usr/lib64/cmake/libmongoc-1.0/libmongoc-1.0-config.cmake:15 (message):
This CMake target is deprecated.  Use 'mongo::mongoc_shared' instead.
Consult the example projects for further details.
Call Stack (most recent call first):
CMakeLists.txt:320 (find_package)
CMake Warning at /usr/lib64/cmake/libbson-1.0/libbson-1.0-config.cmake:15 (message):
This CMake target is deprecated.  Use 'mongo::bson_shared' instead.
Consult the example projects for further details.
Call Stack (most recent call first):
/usr/lib64/cmake/libmongoc-1.0/libmongoc-1.0-config.cmake:22 (find_package)
CMakeLists.txt:320 (find_package)
```
~We switch to a new [recommended …
> Update libmongoc CMake config

- daemon/main.c
- database/sqlite/sqlite_aclk_alert.c
- health/health.c
This PR tries to fix queuing of removed alerts for the cloud, via the new architecture.
In general, what this tries to accomplish, is that if after a start, or a health reload, there are left over REMOVED alerts (which do not have an updated_by other alert), to send them to the cloud. By default REMOVED are not sent via the streaming protocol.
A REMOVED event can happen in those cases if the configuration of an alert changes.
1) Claim an agent via new architecture to the cloud.
2) Try to raise an alert.
3) Somehow make this alert obsolete, by either changing it's configuration, or removing the chart it runs on.
4) Issue an agent restart, or a health reload. If that alert has gone to REMOVED status without having a newer status than that, it should be sent to the cloud.
The patch was …
> Fix queue removed alerts

- aclk/aclk.c
- aclk/aclk_rrdhost_state.h
- aclk/aclk_tx_msgs.c
- aclk/aclk_util.h
- claim/claim.c
- claim/netdata-claim.sh.in
- database/rrdhost.c
This PR adds some modifications that allow the agent to handle a re-claim while the agent is running for the new architecture. In this scenario, the agent will disconnect, send an `UpdateAgentConnection` which has the old `claim_id`, and then another `UpdateAgentConnection` containing the new `claim_id`. In cloud terms, the old node instance will become unreachable, and the new node instance will start updating.
Without this PR the agent requires a restart to re-appear in the cloud, and if it doesn't restart the cloud will have a node instance which does not update any more, and a new one in unreachable state.
There is also a small change in the `netdata-claim.sh.in` script: If the cloud responds with `ErrAlreadyClaimed` do not overwrite the the `claimed_id` file. This helps with the …
> Handle re-claim while the agent is running in new architecture

- aclk/aclk_tx_msgs.c
Introduces publish that waits for buffer drain and introduces in-flight buffer regrowth (without reconnection),
This will together with upcoming changes both on agent and cloud-be alleviate issue with huge queries (100MB+ uncompressed).
ACLK
Req big data from the cloud or fake the request with your own MQTT/WSS broker. Buffer regrowth should not cause any problems. Connection to the cloud remains stable (no reconnection necessary to grow the TX buffer)
> Blocking publish and in flight buffer regrowth

- spawn/spawn_client.c
Missed in #11967 due to the build system not being able to identify usage of undeclared headers (when building without dbengine).
Local build without dbengine & CI jobs.
> Remove internal dbengine header from spawn/spawn_client.c

- daemon/system-info.sh
One of my machines was reporting a total amount of 0 bytes of disk space for its system info. Running `system-info.sh` revealed:
```
NETDATA_SYSTEM_TOTAL_DISK_SIZE=0
```
This change adds `blkext` to the list of device names so that the devices with the associated major (259), e.g. NVME partitions, are included in the total amount of disk space.
```
ralphm@mag-vii:~$ lsblk -d -e 7
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda       8:0    1   9.1T  0 disk 
sdb       8:16   1   9.1T  0 disk 
nvme0n1 259:0    0 931.5G  0 disk 
nvme1n1 259:5    0 931.5G  0 disk
```
```
ralphm@mag-vii:~$ ls -al /dev/ | grep 259
brw-rw----   1 root disk    259,   0 Jan 18 12:04 nvme0n1
brw-rw----   1 root disk    259,   1 Jan 18 12:04 nvme0n1p1
brw-rw----   1 root disk    259,   2 Jan 18 12:04 nvme0n1p2 …
```
> Add support for NVME disks with blkext driver

- collectors/ebpf.plugin/ebpf.c
eBPF plugin is ignoring when user disable some threads inside `ebpf.d.conf`, because there is an unnecessary call for a function. This PR is removing this call to fix the issue.
1. Rename or remove your `/etc/netdata/ebpf.d.conf'
2. Create the file again using `/etc/netdata/edit-config` script given as argument for script `ebpf.d.conf`.
3. Compile master branch and start netdata. Wait few seconds and run:
```sh
curl -k -o master_branch.txt https://localhost:19999/api/v1/data?chart=netdata.ebpf_threads
```
You will see that all threads will be enabled.
4. Stop netdata and compile this branch
5. Start netdata again and take a look in the final result, now it will work as expected. For more data related to tests, please, take a look a `Additional information`
It is not necessary to test on …
> Remove uncessary call

- collectors/idlejitter.plugin/README.md
Because the documentation for the idlejitter.plugin didn't match with the structure of our plugins and collectors, I made some refinements.
> Updated idlejitter-plugin docs

- streaming/README.md
- streaming/rrdpush.c
This PR comes to deactivate the stream compression by default.
Note: This is a mitigation action to reduce the noise coming from the production environment until the [issue #12020](https://github.com/netdata/netdata/issues/12020#issue-1109717498) with the stream compressor buffer overflow is resolved.
Set up a simple Parent <-> Child Netdata agent stream and verify that the stream compression is actually disabled by default and the child charts are visible in the parent's dashboard.
How to verify,
1. Check for `"stream-compression": "disabled"` in  `/api/v1/info` JSON response.
2. In the `error.log` of the child agent look for msg `established communication with a parent using protocol version 4 - ready to send metrics...`
3. Enable db flag `D_STREAM` (`netdata -W …
> [Stream Compression] - Compressor buffer overflow causes stream corruption.

- streaming/README.md
#11821 made some changes to the streaming readme that break our documentation build pipeline. 
Since this PR is merged already, I'm opening a new PR to fix the Markdown file.
> Docs Bugfix: Fixed Markdown formatting

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
This fixes a particular issue when trying to install on a system where all of the following conditions are met:
* There is no native package available for the system.
* The system CPU architecture is one for which a static build is not available.
* cURL is available on the system in question.
Under those combined circumstances, we fail to properly fall back to a local build because cURL by default returns a 0 exit code if it was able to _make_ the request, even if the status code of the request was not a successful one.
Can be verified by using the updated kickstart script to attempt to install on a system where all the above conditions are met.
Fixes: #12032
> Have cURL properly fail on non-2xx status codes in the installer.

- streaming/receiver.c
The PR for stream compression (https://github.com/netdata/netdata/pull/11821) removed 2 lines relating to clabels streaming which were introduced in PR (https://github.com/netdata/netdata/pull/11675)
Specificaly it removed: https://github.com/netdata/netdata/blame/8a01dabf89add0ef473d37bc8f2310cabfc1db43/streaming/receiver.c#L242-L243
This PR re-adds them. Thanks to @odynik for spotting!
All the rest from PR (https://github.com/netdata/netdata/pull/11675) is still there.
Typically re-testing as in https://github.com/netdata/netdata/pull/11675 should be done, but in this case we can assume it's safe to re-add those 2 lines.
The same fix is done in https://github.com/netdata/netdata/pull/12037/commits/d91e93861b620b0934c2d23612386ec6dc35e88a so at least one of these PRs should make it in.
> Re-instate plugins_action for clabels

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
`dpkg` uses a special partially installed state for packages which have been removed but still have config files left behind. It will still return an exit code of zero for packages in this state even though the software in question is not actually on the system, which interferes with how we were checking for the presence of an existing binary-package based install.
Checked locally by testing installing in a Debian 11 container which had previously had our official package installed and then removed using `apt remove netdata`. Without the changes in this PR, the kickstart script will refuse to attempt an install, thinking there is an existing install even though there is not, while with these changes it will properly install Netdata again.
Fixes: #12025
> Fix handling of removed packages with leftover config files in package check.

- docs/get-started.mdx
I've made some minor changes to the get-started page, such as: 
- Removed outdated tiles
- Added a link to the docker install page
- Restructured the page so that our most important installation option appears right at the top 
- Updated the interactive install box (over in netdata/learn)
> Updated the docs to match new install script

- streaming/compression.c
Include "lz4.h" only when compression is enabled.
Note: Fix [#12043](https://github.com/netdata/netdata/issues/12043). 
1. Remove any lz4 lib from your system.
```
sudo apt-get remove liblz4-dev
sudo apt-get remove lz4
sudo apt autoclean && sudo apt autoremove
```
2. Configure without stream compression
```
./configure --disable-compression
```
Configuration checking messages should report,
```
...
checking for LZ4_initStream in -llz4... no
checking for LZ4_compress_default in -llz4... no
...
checking if netdata compression should be used... no
...
```
3. Build the netdata project. Run `make`.
4. netdata should build without any error. In details,
Should see,
```
CC       streaming/rrdpush.o
CC       streaming/compression.o
CC       streaming/sender.o
CC       streaming/receiver.o
``` …
> [Stream Compression] - Bug fix #12043 - lz4.h compilation error - compile from source

- packaging/installer/netdata-updater.sh
This fixes the updater script so that it properly handles updating static builds for non-x86 architectures.
Testing of the handling of non-x86 systems can be done by installing an older static build in a non-x86 container, and then running the updater script.
> Fix handling of non-x86 static builds in updater.

- .github/data/build-matrix.json
- .github/scripts/pkg-test.sh
- .github/workflows/packaging.yml
- .github/workflows/repoconfig-packages.yml
- packaging/installer/install-required-packages.sh
This is a functional workaround to RHEL’s questionable support policy changes for CentOS 8.
area/packaging
area/ci
CI checks pass on this PR.
This should not be merged prior to v1.32.0 being released.
> Replace CentOS 8 with RockyLinux 8 in CI and package builds.

- netdata-installer.sh
- packaging/installer/install-required-packages.sh
- packaging/installer/methods/macos.md
On macOS OpenSSL is not linked to the standard `include` and `lib` directories because LibreSSL is the main library in the system. In order to save our users from the necessity of linking the library, we provide default paths to the Homebrew package. This PR fixes directories for `openssl` packages.
1. Install `openssl@1.1`, run Netdata installer.
2. Uninstall `openssl@1.1` and install `openssl@3`, run Netdata installer.
3. Uninstall `openssl@3` and install `openssl`, run Netdata installer.
In all cases, Netdata should be compiled and installed correctly.
> Fix compilation errors for OpenSSL on macOS

- aclk/aclk.c
aclk_kill_link was not reset properly
also explicitly log the reason for reconnect to not need to guess
agent should not end up in endless reconnect loop after reclaim during runtime
> Fix aclk_kill_link reconnect endless loop

- packaging/docker/README.md
Fixes #12070
We don't explicitly say that the docker socket needs to be mounted. This PR fixes that.
Not needed
> docs: improve "Docker container names resolution" section

- packaging/installer/methods/macos.md
Since we build `libJudy` during the installation of Netdata on macOS, we don't need to encourage users to install it manually (Homebrew builds it from the source anyway).
> Remove mention of libJudy in installation documentation for macOS

- collectors/ebpf.plugin/ebpf.d.conf
As we were discussing in this [issue ](https://github.com/netdata/netdata/issues/12027), we should not expect that an eBPF program could crash a host, but this is happening in two different distributions. After to talk with @ilyam8 , @cpipilas , and @stelfrag we decide to disable it, while we are working to fix the problem.
1. Clone branch
2. remove or rename `/etc/netdata/ebpf.d.conf`.
3. Clone branch and start netdata.
4. Take a look in your dashboard, you should not have the submenu `Networking stack` -> `kernel function(eBPF)`. You won't see any chart from eBPF socket at `Apps` -> `network`.
> disable_ebpf_socket: Disable thread while race condition is fixed

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
Instead just skip trying native packages and fall back properly to static builds or local builds.
This was the intended behavior originally, it just never got implemented properly.
This can be verified by attempting to install on a system which lacks both `/etc/os-release` and `/usr/lib/os-release`. Without this PR, the installer should fail very early with an error indicating that neither file is present. With this PR, the installer should simply issue a warning about the lack of the files, warn about the inability to determine the distro for native packages, and then ultimately attempt to install with a static build or local build.
Relevant to, but does not completely fix: #12068 
This will eliminate the F0401 error code in our anonymous statistics being sent from the installer by …
> Make a lack of an os-release file non-fatal on install.

- aclk/README.md
ACLK Legacy is removed. This removes information about it from the docs.
> Remove ACLK legacy documentation

- docs/get-started.mdx
As mentioned in #12090, the component for the interactive install boxes was renamed from `OneLineInstall` to `OneLineInstallWget`.
This is a minor docs fix so the component names still match.
> Docs fix: Match the new install box component name

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
This simply adds a property to he events indicating whether they came
from an interactive or non-interactive run, which will allow for better
handling of some of the other data in the events.
n/a
> Add info about installer interactivity to anonymous installer telemetry events.

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
This ensures that `sudo` and `doas` properly fail when we are running non-interactively if they would require the user to input a password.
This can be tested by manually running the kickstart script in non-interactive mode as a non-root user on a system that requires password input to run commands as root with `sudo`. Without the changes in this PR, execution will stop the first time the kickstart code tries to invoke `sudo`, while with the changes an error will be thrown instead.
> Properly handle non-interactive installs as non-root users.

- .github/workflows/repoconfig-packages.yml
This way we get proper confirmation that changes to these packages build properly, and they get automatically deployed when updates are pushed.
n/a
> Update repoconfig package build workflow to run on PRs and pushes.

- packaging/repoconfig/netdata-edge.repo.ol
- packaging/repoconfig/netdata-repo.spec
- packaging/repoconfig/netdata.repo.ol
Currently, the Oracle Linux 8 repository configuration packages we are publishing are actually configuring the RHEL/CentOS/Rocky repos instead of the correct Oracle Linux specific ones. This PR fixes that so that we properly use the OL-specific repos on OL systems.
n/a
> Fix handling of Oracle Linux repoconfig packages.

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
They got missed somehow in the initial implementation.
Also fixes a potential bug in version parsing for CentOS systems.
Once #12100 is merged and the repoconfig packages are updated, this can be tested by simply running the updated `kickstart.sh` from this PR in an OL8 Docker container. Without the changes here, it will fall back to a static install. With these changes, it will instead install using a native package.
> Add proper support for Oracle Linux native packages to installer.

- docs/get-started.mdx
- docs/guides/export/export-netdata-metrics-graphite.md
- docs/guides/monitor/lamp-stack.md
- docs/guides/monitor/pi-hole-raspberry-pi.md
- docs/guides/step-by-step/step-00.md
- exporting/prometheus/README.md
- packaging/installer/README.md
- packaging/installer/methods/kickstart.md
The repo structure in learn doesn't match 100% with the structure on netdata/netdata so I didn't know how to verify the file paths were correct. 
I used the [Netlify deploy log](https://app.netlify.com/sites/netdata-docusaurus/deploys/6204f090a1bb540008dca715) to investigate how the paths change. 
To ensure that the new paths resolve, I navigated to each directory in my terminal and from there, used the `../../../src/Components/OneLineInstall` command to check if I end up in the right place.
So, 🤞 this should be the last PR concerning the install boxes. 
Very sorry for yet another PR about this topic. 
These issues arise because we chose to stick with Markdown. 
If we had switched to MDX, we could use the `@site/src/...` syntax to import components, which would probably require less …
> Docs: Fix paths to install boxes

- aclk/aclk.c
Adds legacy protocol deprecation banner to agent log.
Text will be revised and most probably extended with a link to documentation letting users know how to fix this.
Curent banner looks like this:
```
2022-01-31 18:21:24: netdata ERROR : ACLK_Main : #########################  WARNING  #########################
2022-01-31 18:21:24: netdata ERROR : ACLK_Main : #   Your agent is configured to connect to cloud but has    #
2022-01-31 18:21:24: netdata ERROR : ACLK_Main : # no protobuf protocol support (uses legacy JSON protocol). #
2022-01-31 18:21:24: netdata ERROR : ACLK_Main : #         Legacy protocol will be deprecated soon.          #
2022-01-31 18:21:24: netdata ERROR : ACLK_Main : #  Please update your agent to avoid service interruption.  #
2022-01-31 18:21:24: netdata ERROR : …
```
> Adds legacy protocol deprecation banner to agent log

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
This will allow easy reuse in the future for things like the upcoming `--uninstall` option.
This also adds a special case for users who specified an install prefix explicitly so that we don’t waste time looking for an existing install there.
User-visible behavior should not be any different from the existing code.
> Decouple the install detection code from the handling code for existing installs.

- packaging/installer/methods/kickstart.md
"installations" => "kickstart downloads"
"installations" is misleading.
Check https://github.com/ilyam8/netdata/blob/install_badges_units/packaging/installer/methods/kickstart.md.
> docs: rename kickstart install badges units

- claim/README.md
- docs/guides/step-by-step/step-99.md
- packaging/installer/methods/kickstart.md
- packaging/installer/methods/macos.md
The deploy log in Netlify returned the following broken links: 
```
6:34:19 PM: - On source page path = /docs/agent/claim:
6:34:19 PM:    -> linking to /docs/agent/packaging/distributions
6:34:19 PM: 
6:34:19 PM: - On source page path = /docs/agent/packaging/installer/methods/kickstart:
6:34:19 PM:    -> linking to /docs/agent/packaging/installer/methods/packaging/installer/methods/macos
6:34:19 PM: 
6:34:19 PM: - On source page path = /docs/agent/packaging/installer/methods/macos:
6:34:19 PM:    -> linking to /docs/agent/packaging/installer/methods/claim#troubleshooting (resolved as: /docs/agent/packaging/installer/methods/claim)
6:34:19 PM: 
6:34:19 PM: - On source page path = /guides/step-by-step/step-99:
6:34:19 PM:    -> linking to /docs/agent/#contribute (resolved as: /docs/agent/) …
```
> Documentation: Fixed broken links

- web/gui/dashboard_info.js
Fixes a small typo in the ZFS cache info, namely that Min is present twice (instead of Min/sMax)
Deploy a patched version to my home server when possible.
Apologies if this is not the correct branch name to merge into (I did notice a develop branch), the docs on submitting a PR were unclear as to which branch is desired for PRs.
> Fix typo in ZFS ARC Cache size info

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
Fix badly placed quote in kickstart.sh preventing us from using `--claim-*` options.
Before :
```
sh kickstart.sh --claim-insecure
...
+ [ -n --claim-insecure ]
+ warning Passing unrecognized option '--claim-insecure' to installer script. If this is intended, please add it to $NETDATA_INSTALLER_OPTIONS instead.
+ printf %s\n\n  WARNING  Passing unrecognized option '--claim-insecure' to installer script. If this is intended, please add it to $NETDATA_INSTALLER_OPTIONS instead.
WARNING  Passing unrecognized option '--claim-insecure' to installer script. If this is intended, please add it to $NETDATA_INSTALLER_OPTIONS instead.
+ NETDATA_INSTALLER_OPTIONS= --claim-insecure
+ shift 1
```
After:
```
+ [ -n --claim-insecure ]
+ echo --claim-insecure
+ cut -d - -f 4-
+ optname=insecure
+ …
```
> kickstart.sh: fix quoting for globbing

- daemon/system-info.sh
Fixes: #12158
The following values are in kHz:
- /sys/devices/system/cpu/cpu0/cpufreq/base_frequency
- /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq
We need to multiply the value by 1000 to convert to Hz.
Not needed because the change is very straightforward.
> fix: CPU frequency calculation in system-info.sh

- web/api/queries/query.c
Fixes [product@12135](https://github.com/netdata/netdata/issues/12135)
when using the `allow_past` option in data queries and the agent memory mode is `ram` or `save` it will not
correctly detect that the `after` timestamp requested may be out of range, attempting to map the requested
time in *invalid* locations in the buffer. 
- Start an agent in memory mode RAM and immediately
- Run a query `api/v1/data?chart=system.cpu&after=-60&options=jsonwrap`
- You should only see a few points being returned
- Run a query `api/v1/data?chart=system.cpu&after=-60&options=jsonwrap|allow_past`
- You will  see 60 points returned but the results will be inconsistent; you may get null values for recent timestamps which is wrong
- After applying the PR, run the above tests
- You will notice that the agent …
> Fix data query option allow_past to correctly work in memory mode ram and save

- web/api/formatters/rrd2json.c
- web/api/formatters/ssv/ssv.c
- web/api/formatters/ssv/ssv.h
- web/api/formatters/value/value.c
- web/api/formatters/value/value.h
Fixes #12113 
Fixes the bug described in the linked issue
During the processing of a context query if the `format=array` was given, the output would only include values from the first matched chart 
This also affected "ssv", "ssvcomma"
- Test a context query before and after the PR
- Before the fix the returned value in the array output would only include the value of the first chart that matches the context
The ability to pass a different processing function (other than sum for the format array will be handled in a separate PR)
> Fix the format=array output in context queries

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
Should hopefully help reduce the number of users who have to reach out to us due to 
The changes can be easily tested on any distribution that provides Netdata in their regular package repositories by first installing the distro-provided Netdata package and then attempting to run the kickstart script.
Without the changes in this PR, the script will attempt to update the existing install (and fail to do so).
With the changes in this PR, the script will instead report that we do not support such installs and provide some (terse) instructions for remediation.
> Improve messaging around unknown install handling in kickstart script.

- collectors/apps.plugin/apps_plugin.c
Sometimes it is desirable to [send zeroes for empty groups](https://community.netdata.cloud/t/apps-groups-conf-and-exporter-when-process-is-not-running/2141) in the `apps.processes` chart. ~We add the corresponding option for that: `show-empty-groups`.~ We will still send the number of processes/threads when a previously running apps group becomes empty.
apps plugin
Run `fping -l localhost`, wait a couple of seconds, stop `fping`. Check that the `apps.processes` and `apps.threads` chart shows zeroes for the `fping` group after it has been stopped.
> Show the number of processes/threads for empty apps groups

- collectors/apps.plugin/apps_groups.conf
Fixes #12075
Big thanks @rossburton for the contribution. This PR replaces #12077 because of [signing the CLA nuances](https://github.com/netdata/netdata/pull/12077#issuecomment-1028328557).
~~Assuming~~ @rossburton has tested the changes.
> feat(apps.plugin): group Apple Filing Protocol daemons into `afp` group

- health/health.c
Fixes #10847 
Fix alerts to raise correctly when the delay and repeat parameters are used together.
(health: delay doesn't work when using repeat [#10847](https://github.com/netdata/netdata/issues/10847))
**Bug explanation:**
[delay](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-delay) simply doesn't work when using [repeat](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-repeat). Neither up or down.
**Root problem:**
Repeating of notification code block does not control if there is a delay for the notification.
**Solution:**
Added notification delay control to the related if condition.
Set your notification by `sudo /etc/netdata/edit-config health.d/cpu.conf` command
Solution is tested with the notification below:
```
template: 3s_cpu_usage
on: …
```
> Fix alerts to raise correctly when the delay and repeat parameters are used together.

- packaging/installer/methods/kickstart.md
As discussed, this PR addresses the syntax error in the kickstart script. 
@Ferroin 
Should we mention the option to claim a node by `$(uuidgen)` in the installation options sections? 
CC: @car12o
> Docs fix: Claim nodes in the kickstart script

- claim/netdata-claim.sh.in
**Problem**:
The claiming script fails despite the successful response from the Cloud.
- current implementation requires saving the headers sent by the Cloud.
- we add `--save-headers` when using `wget`.
> Save the headers sent by the HTTP server to the file, preceding the actual contents, with an empty line as the separator.
- `--save-headers` works only when there is content (response body).
- successful response is 204 No Content.
**Solution**:
- use `--server-response` instead of `--save-headers`
> Print the headers sent by HTTP servers and responses sent by FTP servers.
- redirect stderr to the file when using `wget` (`--server-response` is debugging info)
- manually change the script to prefer `wget` over `curl`
- run netdata-claim.sh, ensure claiming is successful
> fix: claiming with wget

- packaging/installer/methods/kickstart.md
As discussed in [this comment](https://github.com/netdata/netdata/pull/11764/files#r780511256), I improved the kickstart docs that discuss the automatic claiming of nodes in the cloud.
> Docs: Improved kickstart's cloud installation docs

- daemon/analytics.c
- daemon/buildinfo.c
- daemon/buildinfo.h
- daemon/main.c
- database/rrd.h
- database/rrdhost.c
As requested by @thiagoftsm this adds the build type info into HTTP API
`GET /api/v1/info` should contain new `host_label` keys if it was possible to know their value
> adds install method to /api/v1/info as label

- aclk/https_client.c
- collectors/macos.plugin/macos_fw.c
- collectors/macos.plugin/macos_sysctl.c
- daemon/daemon.c
- database/engine/journalfile.c
- database/rrdset.c
- libnetdata/libnetdata.h
- libnetdata/threads/threads.c
- web/api/queries/query.c
- web/server/web_client.c
SSIA
There should not be any compilation warnings on macOS.
> Fix compilation warnings on macOS

- collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py
This PR fixes the case when UID is not known on the host.
Fixes https://github.com/netdata/netdata/issues/10264#issuecomment-1046045957
Thanks to @TheTyrius for [testing](https://github.com/netdata/netdata/issues/10264#issuecomment-1046056075).
> fix(python.d/nvidia_smi): use uid when can't find the username

- database/rrdset.c
When charts a created with different ids which differ only by symbols that are not '_' or alphanumeric and no unique names are provided, Netdata crashes with a segmentation fault.
```
#0  0x00007fe374de1515 in __strlen_avx2 () from /usr/lib/libc.so.6
#1  0x00005615a2bd5efd in compute_chart_hash (st=st@entry=0x7fe368e42000) at database/sqlite/sqlite_functions.c:1662
#2  0x00005615a2bcd7f2 in rrdset_create_custom (host=0x5615a501fb10, type=<optimized out>, id=0x5615a5337a53 "job_num_CT_S2000", name=<optimized out>, family=<optimized out>, context=<optimized out>, title=<optimized out>,
units=<optimized out>, plugin=<optimized out>, module=<optimized out>, priority=<optimized out>, update_every=<optimized out>, chart_type=<optimized out>, memory_mode=<optimized out>, …
```
> Add serial numbers to chart names

- .github/workflows/packaging.yml
The jobs for architectures other than 64-bit x86 consistently show no issues unless something is broken for that architecture (which also consistently breaks the static build for the same architecture) or that distribution 9which also consistently breaks the 64-bit x86 build for that distribution), so they functionally serve no real purpose when being run on PRs.
This commit skips running those jobs on PRs only so that we do not waste resources on them. They can be explicitly run by placing the exact words `actions run all ci` in the PR description directly preceded by a `/`.
This also enables running them on merges to master, which we previously did not do, so that we can still confirm for certain that everything is working.
Easily verifiable by observing that the package build jobs for …
> Update packaging CI to only run a limited set of jobs on PRs.

- .github/workflows/packaging.yml
#12156 missed a conditional in the early parts of the package build job template in the packaging workflow that needed to be updated so that it would properly check things out when running on a push to master.
This PR fixes that conditional.
n/a
> Properly check out the repo when running the packaging workflow on push.

- collectors/python.d.plugin/hpssa/hpssa.chart.py
Fixes #12205. Line with `Disk Partition Information` generates parser error of the `hpssa` collector.
As such lines includes not useful information this patch simply excludes them.
Just tested manually by me on failing system, where it works.
On other HP servers where setup is very similar didn't found this issue (no problematic line in `ssacli` output).
So the issue might be quite unique...
Grepping through the repo show no tests of `hpssa` collector.
> Fix `hpssa` parse error

- database/sqlite/sqlite_aclk_alert.c
- health/REFERENCE.md
This PR fixes the case where an alert configuration is missing the `info` field and an alert event from that alert tries to be sent to the cloud, which can result in a crash.
1) Edit an alert and remove the info field.
2) Connect the agent to a whitelisted space.
3) Raise the alert.
4) Without this PR the agent might crash when trying to send it. With this PR it should behave correctly.
5) More checks can be done by messing with the database alert streaming and cause a snapshot. This should be also handled correctly.
The above scenarios have been tested in staging.
We need to plan this with the cloud backend to properly handle this case from their side too. In protobuf the empty string is considered missing, and it's the default value.
> Skip info field in protobuf alerts messages if it doesn't exist.

- database/rrd.c
- database/rrddim.c
- database/rrdset.c
Fixes #9320
Remove support for 'per chart' configuration in `netdata.conf` (except the `enabled` option)
Right now on every chart creation there is a lookup in the config file to determine if a section that matches the chart exists
- For parent nodes the section matches the chart name
- For child nodes the section is in the form guid/chart_name
database
agent
- Fetch netdata.conf using ` http://host:19999/netdata.conf` to notice the absence of chart specific configuration.
> Remove chart specific configuration from netdata.conf except enabled

- daemon/service.c
- database/rrdhost.c
- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_aclk.h
Add orphan host cleanup, in a separate service thread. This thread is currently used to clean up obsolete charts avoiding the overhead of checking for eligible charts during chart creation
Using the same approach an additional check is made for hosts can be obsoleted (eg. children that disconnected and will most likely not reconnect ; ephemeral nodes)
- Setup an agent with a child or mode
- Configure a low value for `cleanup orphan hosts after seconds =` in netdata.conf e.g `cleanup orphan hosts after seconds = 30`
- Start the parent and child
- Shutdown the child and notice the parents error.log indicating that the child is removed from memory approximately 30 seconds later
> Improve cleaning up of orphan hosts

- netdata-installer.sh
During installation, I had the following error
tar: protobuf-3.17.3: Cannot change ownership to uid 576694, gid 89939: Invalid argument
This PR prevents this error and thereby allows for a smoother installation.
Installer
Test the kickstart / netdata-installer scripts as you otherwise would. Unfortunately I have no idea how good these are tested by the CI.
<details><summary>More log related to the original error</summary>
<p>
```bash
[root@SCGdev ~]# bash kickstart-netdata.sh
--- Found existing install of Netdata under: / ---
--- Attempting to update existing install instead of creating a new one ---
[/root]# //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron Thu Jan  6 09:26:11 UTC 2022 : INFO:  Checking if a newer version of the updater script is available.
Thu Jan  6 …
```
> Add `--no-same-owner` to `tar xf` in installer

- ml/Dimension.cc
- ml/Dimension.h
Detect dimensions whose values do not change, and skip them from
training. This allows us to reduce the number of training operations
by ~40-50%.
Notice that we don't skip the very 1st training iteration, because a
dimension's value might change at any point in time, and we need to
have a trained model in order to compute its anomaly score.
- Custom log calls to keep track of which dimensions are skipped vs. trained.
- @andrewm4894 will run on staging.
- CI jobs
Resolves #12180
> Skip training of constant metrics.

- collectors/plugins.d/pluginsd_parser.c
- database/rrddim.c
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
Store the `hidden` option of a dimension (e.g.  cpu idle) in the database. This is to ensure that queries on
archived charts (in a following PR) will correctly skip hidden dimensions unless explicitly requested.
- After applying this PR the `options` column in the `dimension` table in `/var/cache/netdata/netdata-meta.db` will have the value `hidden` for the appropriate dimensions. 
- Example: 
```
select distinct name, options from dimension where options is not null;
name  options
----  -------
idle  hidden 
```
> Store dimension hidden option in the metadata db

- aclk/aclk.c
Removes the ACLK_NEWARCH_DEVMODE to reduce the number of ifdefs. This is not needed anymore (was used in the initial new arch protocol development stages).
Code should not change any behavior in case ACLK_NEWARCH_DEVMODE is false
> minor - remove ACLK_NEWARCH_DEVMODE

- backends/backends.c
- database/rrd.h
- database/rrddim.c
- database/rrdhost.c
- database/rrdset.c
- database/sqlite/sqlite_aclk_node.c
- exporting/check_filters.c
- exporting/prometheus/prometheus.c
- ml/Config.cc
- ml/Config.h
- ml/Dimension.h
- ml/Host.cc
- ml/Host.h
- ml/ml-dummy.c
- ml/ml.cc
- ml/ml.h
- streaming/rrdpush.c
- web/api/formatters/rrd2json.c
- web/api/formatters/rrd2json.h
- web/api/web_api_v1.c
This commit adds support for tracking anomaly rates with DBEngine. We
do so by creating a single chart with id "anomaly_detection.anomaly_rates" for
each trainable/predictable host, which is responsible for tracking the anomaly
rate of each dimension that we train/predict for that host.
The rrdset->state->is_ar_chart boolean flag is set to true only for anomaly
rates charts. We use this flag to:
- Disable exposing the anomaly rates charts through the functionality
in backends/, exporting/ and streaming/.
- Skip generation of configuration options for the name, algorithm,
multiplier, divisor of each dimension in an anomaly rates chart.
- Skip the creation of health variables for anomaly rates dimensions.
- Skip the chart/dim queue of ACLK.
- Post-process the RRDR result of an anomaly rates …
> Track anomaly rates with DBEngine.

- .github/workflows/packaging.yml
- .github/workflows/repoconfig-packages.yml
GitHub Actions understandably does not like passing secrets into step or job outputs, so we need to just use an environment variable for the repo name instead of storing it as a secret.
n/a
> Fix handling of repository name in CI workflows.

- ml/Host.h
`build/m4/ax_c___atomic.m4` wrongly skips setting HAVE_C___ATOMIC on some 32-bit platforms.
This breaks C++ 11 code because of the definition of `rrdset_flag_set`.
CI jobs & local builds after undef-ing the aforementioned macro.
> Fix builds where HAVE_C___ATOMIC is not defined.

- database/sqlite/sqlite_functions.c
Children with agent versions before v1.31 will not register correctly to their claimed parent so that they can be announced
to the cloud. 
This PR adds the missing information to properly register the children to the cloud via the parent by enabling a trigger to store the information in the node instance table whenever a host is created
- Parent agent running the latest version and claimed to the cloud
- Child running any pre 1.31 version (not claimed to the cloud)
- The child will not register properly to the cloud
After the PR
- The child will register properly to the cloud
> Add a fix to correctly register child nodes to the cloud via a parent

- netdata.spec.in
- packaging/bundle-protobuf.sh
CentOS 7 does not provide a new enough version of protobuf for our usage, so we need to bundle a newer copy to get proper support there.
CentOS 7 packages can be downloaded from the checks page and verified locally to confirm that they have a working copy of protobuf (link to relevant artifacts for current CI run: https://github.com/netdata/netdata/suites/5344636126/artifacts/167246445).
Fixes: #12157
> Bundle protobuf on CentOS 7 and earlier.

- web/api/formatters/rrd2json.c
Fix a crash when the chart state is not initialized
```
#0  0x000055e6d3f71593 in rrdset2anything_api_v1 (st=0x55e6eadc8d20, wb=0x55e6ead9bd00, dimensions=0x0, format=8, points=58, after=-900, before=0, group_method=1, group_time=0, options=551, 
latest_timestamp=0x7fd382336898, context_param_list=0x55e6ea26f5a0, chart_label_key=0x0, max_anomaly_rates=0) at web/api/formatters/rrd2json.c:232
232	    if (st && st->state->is_ar_chart)
(gdb) p st
$8 = (RRDSET *) 0x55e6eadc8d20
(gdb) p st->state
$9 = (struct rrdset_volatile *) 0x0
```
- Random crashes when starting the agent (on this piece of code) should be gone
> Add a check to make sure internal chart state is initialized

- docs/guides/monitor/anomaly-detection-python.md
Fixed a typo I found while reading through documentation in docs/guides/monitor/anomaly-detection-python.md .
> Fixed typo in docs/guides/monitor/anomaly-detection-python.md file

- netdata-installer.sh
Fixes #12233 
As described [here](https://github.com/netdata/netdata/issues/12233#issuecomment-1050215744), our logic to install `eBPF.plugin` had a problem, and this PR is fixing the algorithm  to detect `libc` on Linux distributions that changes `ldd` default output.
1. Clone Brach
2. Compile the PR and verify that when `libc` is not detect eBPF.plugin is not installed.
3. Repeat the test on an environment that `libc` is present and install PR to be sure that `eBPF.plugin` is installed without any problems.
To develop the fix, I used a [vagrant image](https://app.vagrantup.com/generic/boxes/gentoo). I am bringing the logs for the two last commit to simplify the review:
| Distribution |Commit | Log |
|-----------------|----------|--------|
| Gentoo        | …
> eBPF installation fixes

- system/netdata.service.in
This is related to #9640. The samba plugin fails its check, being unable to run `/usr/bin/sudo /usr/bin/smbstatus -P`. 
I modified `ExecutableService.py` to print the stdout/stderr from the command:
> 2020-11-04 23:36:54: python.d ERROR: samba[samba] : cmd: '['/usr/bin/sudo', '-n', '-l', '/usr/bin/smbstatus', '-P']', stdout: '', stderr: 'sudo: unable to change to root gid: Operation not permitted'
Note that I can run this manually as the netdata user:
```
[netdata@elbereth /]$ /usr/bin/sudo -n -l /usr/bin/smbstatus -P
/usr/bin/smbstatus -P
```
The `CapabilityBoundingSet` in the systemd service doesn't have sufficient capabilities for sudo:
```
CapabilityBoundingSet=CAP_DAC_OVERRIDE
CapabilityBoundingSet=CAP_DAC_READ_SEARCH
CapabilityBoundingSet=CAP_FOWNER
CapabilityBoundingSet=CAP_SETPCAP …
```
> netdata.service: unbreak Samba plugin

- web/server/web_client.c
When doing an api request through a client that does not close the connection, it is possible to keep the url parameters stored, even when a next request (over the same connection) does not contain them.
As a small test, try from a web browser to request `/api/v1/alarms`, then `/api/v1/alarms?all` and then again `/api/v1/alarms`.
If those calls are made before the connection is closed, then it is possible to receive the output of `?all` when doing the request `/api/v1/alarms`.
The problem is that `w->decoded_query_string` is not cleared between requests. It is only calculated when the agent detects that there is a separator (`?`) in the url requested. If there's not, then nothing is done on `w->decoded_query_string` potentially leaving there the parameters from a previous request.
This PR …
> Null terminate decoded_query_string if there are no url parameters.

- aclk/aclk_api.c
Adds protobuf support as host label to simplify implementation on cloud side.
`/api/v1/info`
> add host labels _aclk_ng_new_cloud_protocol

- aclk/aclk_query.c
- aclk/aclk_tx_msgs.c
- aclk/aclk_tx_msgs.h
Fix for #12243
Uses the error mechanism agreed on with cloud during talks about too big payloads.
Incoming cloud queries should always get a response. Right now an incoming request that refers to a node which is not known to the agent would be silently ignored.
This PR adds a response in this case
- Start a claimed agent with a parent child setup 
- Cloud dashboard should work just fine
- Access the local database `/var/cache/netdata/netdata-meta.db` via the command line tool `sqlite3` and issue `delete from node_instance;` 
- This will make the nodes unknown to the agent for incoming cloud requests
- Notice long timeouts in the cloud (10 second delay)
- Apply the PR and retry
- The errors should appear immediately to the cloud
When this happens cloud should show error badge on chart …
> Use the new error mechanism in case host not found

- health/Makefile.am
- health/health.d/nut.conf
Fixes: #12187
This PR adds the [same set of alarms](https://github.com/netdata/netdata/blob/master/health/health.d/apcupsd.conf) as we have for [charts.d/apcupsd](https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin/apcupsd#apc-ups-monitoring-with-netdata).
[Tested](https://github.com/netdata/netdata/issues/12187#issuecomment-1055779733) by @Mic-Pod
> feat(health): add charts.d/nut alarms

- contrib/debian/rules
- netdata.spec.in
- packaging/installer/UPDATE.md
- packaging/installer/netdata-updater.sh
This restores a subset of the changes that were reverted in #12182 that are generally known to be clean and working correctly.
Specifically, it re-adds the code in the updater script for toggling automatic updates on and off, the changes in the packaging code that include the updater script in our native packages, and the associated documentation changes for both parts.
The kickstart script integration will be handled in a separate PR at some point later this week.
Testing of the new `--enable-auto-updates` and `--disable-auto-updates` options can be done trivially on any existing static or locally built install by downloading the copy of the script from this PR and simply running it with the appropriate option.
> Add support to the updater to toggle auto-updates on and off.

- packaging/installer/kickstart.sh
`id`, `proxy`, `user` and `hostname` claiming parameters syntax is key=value, not key[space]value.
https://github.com/netdata/netdata/blob/23fab077290b61507f65885b52307291f624ae9b/claim/netdata-claim.sh.in#L197-L210
Tested by @erdem2000
> fix(kickstart): use correct syntax for claiming extra parameters

- daemon/system-info.sh
Fixes: #12291
This PR fixes detection of the following parameters on macOS:
- CPU_LOGICAL_CPU_COUNT
- CPU_VENDOR
- CPU_FREQ (only for x86_64)
- CPU_MODEL
Run the system-info.sh script on intel/m1 mac's, check the CPU info.
```
wget -q -O system-info.sh https://raw.githubusercontent.com/ilyam8/netdata/fix_macos_cpu_system_info/daemon/system-info.sh; sh system-info.sh | grep -i cpu
```
- m1 pro
```cmd
NETDATA_SYSTEM_CPU_LOGICAL_CPU_COUNT=10
NETDATA_SYSTEM_CPU_VENDOR=Apple
NETDATA_SYSTEM_CPU_MODEL=Apple M1 Pro
NETDATA_SYSTEM_CPU_FREQ=unknown
NETDATA_SYSTEM_CPU_DETECTION=nproc sysctl
```
- intel
```cmd
NETDATA_SYSTEM_CPU_LOGICAL_CPU_COUNT=8
NETDATA_SYSTEM_CPU_VENDOR=GenuineIntel
NETDATA_SYSTEM_CPU_MODEL=Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
NETDATA_SYSTEM_CPU_FREQ=2300000000 …
```
> fix: cpu system info detection on macOS

- packaging/installer/netdata-updater.sh
Fixes https://github.com/netdata/netdata/issues/12286
Redirect stderr to `/dev/null` when testing tmpdir options.  Stderr is not needed for the tests and can cause systems to notify root of failed cron job.
Tested on a staging server by manually making the changes.
Before changes update script outputs:
```
/etc/cron.daily/netdata-updater: line 120: /tmp/netdata-test.rCn0Lj9eJn: Permission denied
/etc/cron.daily/netdata-updater: line 120: /tmp/netdata-test.w5QyEkgJcA: Permission denied
```
After changes it outputs no errors.
> Fixing stderr output when testing tmpdir

- daemon/system-info.sh
Fixes: #12291
This PR adds an additional method of detecting CPU frequency: using "Model name" from `lscpu` output.
<details>
<summary>lscpu output</summary>
```cmd
bash-5.1# lscpu
Architecture:            x86_64
CPU op-mode(s):        32-bit, 64-bit
Address sizes:         46 bits physical, 48 bits virtual
Byte Order:            Little Endian
CPU(s):                  32
On-line CPU(s) list:   0-31
Vendor ID:               GenuineIntel
Model name:            Intel(R) Xeon(R) CPU @ 2.00GHz
CPU family:          6
Model:               85
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           1
Stepping:            3
BogoMIPS:            3999.99
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx …
```
> fix: CPU frequency detection for some containers

- packaging/installer/kickstart.sh
By properly looking for and parsing the `.environment` file if we do not see a `.install-type` file.
This particular case was not handled in the existing code as it was assumed that a majority of users would have gotten updated since their original install to a version that did properly include the `.install-type` file.
Primary test cases can be replicated with the current kickstart script as follows:
* To simulate a `legacy-build` install type (local source build done with the old kickstart script, or possibly by manually running the `netdata-installer.sh` script), install with the `--build-only` option using the new kickstart script, and then remove `/etc/netdata/.install-type`.
* To simulate a `legacy-static` install type (static install done by the old kickstart-static64.sh script …
> Add proper handling for legacy kickstart install detection.

- packaging/installer/netdata-updater.sh
Due to #11200, older nightly installs that predated the install-type introduction may have ended up incorrectly categorized as `custom` installs. This PR adds a check to fix this in a majority of cases for such installs when they run the updater script.
This can be tested by creating a local build install and then modifying the `.install-type` file to list `custom` for the `INSTALL_TYPE` key, and then running the updater code from this PR. If things are working, the `.install-type` file should show `legacy-build` for the `INSTALL_TYPE` key after the update.
See also: #12273, which fixes detection of affected installs in the kickstart script so they are not incorrectly listed as `custom`.
> Fix incorrect install type on some older nightly installs.

- web/api/web_api_v1.c
Adds `node_id` into mirrored_hosts list of `api/v1/info`
On request of @amalkov, the guys were missing this info during their investigations.
Query `/api/v1/info` see the result
> adds node_id into mirrored_hosts list

- health/health.d/tcp_resets.conf
Fixes: #12315
This PR adjusts [10s_ipv4_tcp_resets_sent](https://github.com/netdata/netdata/blob/c59aacc18c7759dfc958f891914ba04dea6473d3/health/health.d/tcp_resets.conf#L19-L36) warn trigger, so it will be equal to [10s_ipv4_tcp_resets_received](https://github.com/netdata/netdata/blob/c59aacc18c7759dfc958f891914ba04dea6473d3/health/health.d/tcp_resets.conf#L53-L69).
See the [issue](https://github.com/netdata/netdata/issues/12315) for details.
Not needed.
> fix(health): adjust 10s_ipv4_tcp_resets_sent warn trigger

- collectors/ioping.plugin/ioping.plugin.in
Checking the stock config dir `"${NETDATA_STOCK_CONFIG_DIR}/${plugin}.conf"` for .conf files will produce a very confusing error in the logs when a user tries to enable multiple instances of ioping:
> 2022-03-05 11:07:59: ioping2.plugin: WARNING: Cannot find file '/usr/lib/netdata/conf.d/ioping2.conf'.
This is a false warning and the plugin will indeed work. It seems to me that there is no reason whatsoever to even check the stock config since it doesn't contain a workable destination path to monitor until the user edits the file and at that point they will have the file in their /etc/netdata/ directory.
The error makes it seem as though the user should go creating files in /usr/lib/netdata/conf.d/
I had considered fixing this as follows but I think just removing that check altogether is …
> Remove check for config file in stock conf dir

- health/health.d/ioping.conf
Unless I'm missing something here, this alarm does not work the way it is written because there is no dimension called "average" in the chart created by ioping.
Changed to lookup of latency instead.
> Add latency dimension

- packaging/installer/netdata-updater.sh
This ensures that as our dependencies change we can still build properly and still have our minimum required dependencies.
This can be verified by creating an install with an older version that is locally built, and then removing any C++ compiler on the system and running the updater.
Without this change, the resultant agent will not have protobuf support.
With this change, it will have protobuf support.
> Pull in build dependencies when updating a locally built install.

- daemon/system-info.sh
Fixes: #12290
`systemd-detect-virt -c` returns an empty response when executing as systemd unit service on Debian 8 on @ktsaou server (couldn't reproduce it on my deb8 server).
That is not expected here, as the result we treat the server as a container, which is not the case
https://github.com/netdata/netdata/blob/297f02fee3e00205ab69ce2d67312fd043c38034/daemon/system-info.sh#L148-L152
> fix: container virtualization detection with systemd-detect-virt

- system/netdata.conf
Fixes: #12256
This PR removes "bind to" option from the netdata.conf that is used in deb/rpm packages. After this PR "bind to" will be the same regardless of installation method.
Not needed
> fix: use default "bind to" in native packages

- .github/data/distros.yml
Expected release date 2022-03-15.
Depends on https://github.com/netdata/helper-images/pull/150
> Add Fedora 36 to CI and package builds.

- .github/data/distros.yml
Expected release date 2022-03-15.
CI jobs are created and pass on this PR.
Depends on https://github.com/netdata/helper-images/pull/150
> Add Ubuntu 22.04 to CI and package builds.

- .github/workflows/cloud_regression.yml
This PR introduces a new github actions workflow that triggers the Netdata Cloud e2e regression suite once a new PR is issued to be merged against netdata master, or when a push happens in the master branch.
More details:
- Upon PR or merge on master, a workflow_dispatch event will be sent from agent’s public repo to a private repo in the netdata org (netdata/test-automation).
- The workflow that lives on agent’s repo and triggers the cloud workflow will be asynchronous, meaning it won’t wait for our tests to finish, it will just shoot and go, so it won’t delay agent's release process at all.
- Cloud e2e tests run in about 15 minutes and they will verify the **integration between agent and cloud, NOT the agent dashboard functionality.**
- All of the cloud e2e tests run using the netdata …
> Workflow to trigger cloud regression e2e tests

- packaging/installer/netdata-updater.sh
This should make updates quiet again.
Also just run the dependency handling script in non-interactive mode when it’s run from the updater, whether the updater is running interactively or not.
Output from the `install-required-packages.sh` script should no longer be visible in the updater check step of the updater check CI jobs.
> Redirect dependency handling script output to logfile when running from the updater.

- database/rrd.h
- database/rrddim.c
- database/rrdhost.c
- database/rrdset.c
- database/sqlite/sqlite_aclk_chart.c
- database/sqlite/sqlite_aclk_chart.h
Fixes #12283
This PR changes the timing for scheduling a chart and dimension update to cloud as discussed in the linked issue
- A new chart will be sent to the cloud as soon as possible
- A live dimension will be sent to the cloud as soon as possible
- A dimension that switches from live to not being collected will be sent to the cloud after MAX(1.5 * chart_update_every, chart_obsoletion_time) seconds
- Set up a parent child setup (claimed) 
- Compile parent with NETDATA_INTERNAL_CHECKS
- Parent set host obsoletion time to 30 seconds and chart obsoletion time to 20 seconds
- Start parent (with debug flag D_ACLK_SYNC) and child
- When things settle in the cloud dashboard, shutdown the child and wait at least 40 seconds
- Monitor the `debug.log` of the parent and notice after host …
> Adjust cloud dimension update frequency 

- ml/Dimension.h
FE needs this information when they issue a `/data` request on the
anomaly rates chart. However, this information is only available at
the creation time of the anomaly rate dimension.
CI jobs & FE testing on staging.
> Prepend context in anomaly rate dimension id.

- packaging/docker/run.sh
Provides a general warning to catch the case encountered in https://github.com/netdata/netdata/issues/11933 and provide info to the user about it in the container logs.
n/a
Relevant to (but does not fix): https://github.com/netdata/netdata/issues/11933
> Add warning about broken Docker hosts in container entrypoint.

- health/health.d/ioping.conf
This PR adjusts green/red thresholds. The chart units is microseconds, not milliseconds.
Fixes https://github.com/netdata/netdata/pull/12329#issuecomment-1063167058
Not needed.
> fix(health): make ioping_disk_latency alarm less sensitive

- ml/README.md
Currently, the page doesn't display the actual title in learn. I suppose the ingest script strips away h1, so in this case the fallback title is the filename. 
I supplemented frontmatter, so this issue should be resolved.
> Docs fix: Add missing frontmatter

- database/rrdset.c
When a new chart is created (and its dimensions have no previously stored metrics), the dimension payload for the chart
may not have the correct timestamps for collected metrics. This will cause the cloud to delete
the dimension from the chart and the it never appears in the cloud dashboard. 
This PR, waits for one iteration of data collection before sending the chart and dimension metadata to the cloud 
to make sure we have a valid timestamps.
- Trivial change to make sure we have at least one collection iteration for the chart
> Fix chart synchronization with the cloud

- daemon/buildinfo.c
While doing other stuff (which will use output of this function) I noticed `analytics_build_info()` will produce wrong output if db-engine is not compiled in.
This fixes it with macro and removes related TODO comment.
Any decent compiler will remove the conditional jump (related to `first` variable) as its value is known at compile time in every case (conflating it to just the needed buffer_strcat calls without ifs). Sample from gcc:
<details>
<summary>gdb disassemble</summary>
```
0x000000000041248b <+79>:    mov    $0x83a475,%esi
0x0000000000412490 <+84>:    mov    %rbx,%rdi
0x0000000000412493 <+87>:    call   0x42444c <buffer_strcat>
0x0000000000412498 <+92>:    mov    $0x83a489,%esi
0x000000000041249d <+97>:    mov    %rbx,%rdi
0x00000000004124a0 <+100>:   call   0x42444c …
```
> minor - fix analytics_build_info

- .github/scripts/prepare-release-base.sh
- .github/workflows/release.yml
This works around the issue of pushing to protected branches from an actions workflow, and also makes the changelog generation it’s own step like it should be.
Not really testable without merging it and waiting for tonight’s nightly.
> Fix handling of pushing commits for release process.

- database/sqlite/sqlite_health.c
- database/sqlite/sqlite_health.h
- health/health.c
- health/health.h
- health/health_config.c
For every child connected to a parent, the parent will read the stock and user alert configurations, and will try to create alerts for each host from them. This is maybe an optimization we could do at some point.
This PR though reduces the calculation and storing of alert hashes only when the health config iteration is for the localhost. There's no need to do it again for every child.
Start with a clean new agent. Run it, and do a select in sqlite in table `alert_hash`.
Delete the data from the table, apply this PR and re-run.
The table now will have some more hashes than before. Those are configurations that where not applied before because of `os` or `host` values. (Before this PR, if an alert configuration was not to be applied to this specific host, it would not get written in sqlite. …
> Only store alert hashes when iterated from localhost

- .github/workflows/release.yml
"[Generate Nightly Changelog](https://github.com/netdata/netdata/blob/4566c0835e99d1b00542ddbc1600450eb61a6a70/.github/workflows/release.yml#L45-L69)" job [fails](https://github.com/netdata/netdata/runs/5504428611?check_suite_focus=true) because it gets rate limited by GitHub - too many fetches.
Set it to the same value [as we use in travis](https://github.com/netdata/netdata/blob/4566c0835e99d1b00542ddbc1600450eb61a6a70/.travis/create_changelog.sh#L46).
I checked the option syntax in https://github.com/heinrichreimer/action-github-changelog-generator#inputs. It is valid.
> fix(ci/release): limit the number of issues to fetch from GitHub when generating changelog

- .github/scripts/prepare-release-base.sh
- .github/workflows/packaging.yml
- .github/workflows/release.yml
* Pass `nightly` instead of a version for nightly builds.
* Use the correct name for the version input when triggering builds.
* Properly pull the version info for nightly builds in the packaging workflow.
n/a
> Fix version handling issues in release workflow.

- daemon/README.md
- daemon/daemon.c
- system/netdata.service.in
- system/netdata.service.v235.in
SSIA
Should be verified by building locally and confirming the OOM score and scheduling policy of the agent on startup.
Fixes: #12251 
Fixes: #12254
> Change default OOM score and scheduling policy to behave more sanely.

- collectors/ebpf.plugin/ebpf.c
- collectors/ebpf.plugin/ebpf.h
Fixes #12363 
This PR is removing `pid` file used to identify a process that was not correctly closed. This file is removed, if and only if, the process ends successful. 
1. Clone this branch
2. Verify that you have the file `/usr/libexec/netdata/plugins.d/ebpf.d/ebpf.pid` present in your system.
3. Compile this branch and start `netdata`.
4. Wait few minutes and stop `netdata`
5. Now run the following command to confirm the file was removed:
```sh
bash-5.1# ls -lh /usr/libexec/netdata/plugins.d/ebpf.d/ebpf.pid
ls: cannot access '/usr/libexec/netdata/plugins.d/ebpf.d/ebpf.pid': No such file or directory
```
> fix(ebpf.plugin): remove pid file on exit

- packaging/docker/run.sh
This PR fixes shellcheck warnings ([SC2012](https://github-wiki-see.page/m/koalaman/shellcheck/wiki/SC2012)) in our docker run.sh file. Thanks to @maneamarius for [noticing the problem and suggesting the solution](https://github.com/netdata/netdata/pull/12310#issuecomment-1064963210).
Compare the output using the old and new code
```cmd
$ ls -nd /var/run/docker.sock | awk '{print $4}'
997
$ stat -c %g /var/run/docker.sock 2>/dev/null
997
```
> fix: shellcheck warnings in docker run.sh

- health/health.c
This PR adds a delay before creating a REMOVED alert event when a chart goes obsolete. It should help with cases when charts go in OBSOLETE and then back to ok quickly.
Similar testing can be conducted as in https://github.com/netdata/netdata/pull/12021 (using e.g. a usb stick). This time around, with this PR, the REMOVED event should be produced 60 seconds after the last_collected time.
> Delay removed event for 60 seconds after the chart's last collected time

- coverity-scan.sh
This should fix the failing Coverity scan jobs.
Also, report when we actually managed to download something, but the name did not match what was expected.
Coverity scan runs on this PR.
> Bump the version of Coverity we are using to the latest.

- build_external/scenarios/aclk-testing/agent_netdata.conf
- contrib/debian/netdata.postinst
- daemon/main.c
- netdata-installer.sh
- netdata.spec.in
- packaging/installer/README.md
- system/netdata.conf
- tests/alarm_repetition/netdata.conf_with_repetition
- tests/alarm_repetition/netdata.conf_without_repetition
- web/server/README.md
- web/server/web_client.c
- web/server/web_client.h
Fixes  https://github.com/netdata/netdata/issues/12257
This PR is removing the check for owner when web server tries to open files, it also adjusts our package building.
1 - Compile this branch and try to access `netdata` dashboard, you should have not problems to open it.
2 - Copy any file as `root` user to `/usr/share/netdata/web/` and be sure other users can read it. Try to get the file using `http://localhost:19999/FILE`.
It is completely unnecessary to access `api` to get data, because we are not addressing any code related to it, but considering that to add more test will only help us:
3 - Be sure you can also access `http://localhost:19999/api/v1/info`
4 - Start a `child` netdata and verify that you can access its data using `http://localhost:19999/host/CHILD_NAME/`
More details …
> Remove owner check from webserver

- daemon/commands.c
When some command of `netdatacli` produces output bigger than `MAX_COMMAND_LENGTH` netdata will crash with buffer overflow.
This will cut the string and prevent crash.
This will not solve problem of sending long strings trough `netdata-cli`. We have to fix it in future so that `netdatacli` can send long strings.
Host with many children will generate long `netdatacli aclk-state` output. With this patch it should not segfault the agent.
fixes https://github.com/netdata/netdata/issues/12384
This is quick fix so that netdata doesn't crash but is not ideal - we still need to think how to proceed with netdatacli so it can send arbitrary long outputs
> Fix crash when netdatacli command output too long

- packaging/installer/netdata-updater.sh
* Properly handle GitHub’s brain-dead error responses.
* Fix parsing of dates on BSD and macOS systems.
* Make the timestamp conversion more robust.
This can be tested by simply running the updater script from this PR locally. However, due to the nature of API failures, the first case can only be properly tested in a probabilistic manner.
Fixes: https://github.com/netdata/netdata/issues/12364
> Fix handling of checks for newer updater script on update.

- collectors/charts.d.plugin/charts.d.plugin.in
Because of #12413. We are disabling it and will investigate the problem.
Create a docker image, start the container, check CPU usage, and Block IO.
> fix: temporary disable charts.d apcupsd collectors

- claim/netdata-claim.sh.in
- packaging/installer/kickstart.sh
Fixes: #12421
- check there are no other non-fixed uuidgen call cases
```cmd
netdata (lowercase_uuidgen) $ git grep uuidgen -- ':(exclude)*.md' ':(exclude)*.mdx' ':(exclude)*.c' ':(exclude)*.conf'
claim/netdata-claim.sh.in:    if command -v uuidgen > /dev/null 2>&1; then
claim/netdata-claim.sh.in:        id="$(uuidgen | tr '[:upper:]' '[:lower:]')"
claim/netdata-claim.sh.in:                echo >&2 "The cloud may have different credentials already registered for this agent ID and it cannot be reclaimed under different credentials for security reasons. If you are unable to connect use -id=\$(uuidgen) to overwrite this agent ID with a fresh value if the original credentials cannot be restored."
claim/netdata-claim.sh.in:                echo >&2 "The cloud may have different credentials …
```
> fix: lowercase uuidgen

- packaging/installer/functions.sh
The delay is needed on slow servers, that is what I get on my DO droplet (Basic plan):
```cmd
Stopping all netdata threads
[/home/ilyam/netdata]# stop_all_netdata
OK
Starting netdata using command 'systemctl start netdata'
[/home/ilyam/netdata]# systemctl start netdata
OK
Ooops! it seems netdata is not started.
Attempting another netdata start using command 'systemctl start netdata'
[/home/ilyam/netdata]# systemctl start netdata
OK
Hm... it seems netdata is still not started.
Netdata service still not started, attempting another forced restart by running '/opt/netdata/usr/sbin/netdata '
[/home/ilyam/netdata]# stop_all_netdata
OK
[/home/ilyam/netdata]# /opt/netdata/usr/sbin/netdata
OK
OK  netdata started!
```
The reason is:
- `systemctl start netdata` returns as soon as "netdata.service" …
> fix: add a delay between starting Netdata and checking pids

- .github/workflows/build.yml
This particular part of our CI fails relatively frequently due to external infrastructure problems. By retrying on the first few failures
in a run, we should mitigate most of these issues at the cost of making the worst case runtime about 10 minutes longer.
There should be no visible changes in the running CI on this PR relative to any of the others.
> Add retries in preparation of test environments for build CI.

- .github/workflows/packaging.yml
Trying to pass the PR body as an environment variable runs into problems due to how GHA handles environment variables.
Instead of that, simply template the body text in as a triple-quoted string.
This does not eliminate the issue, but makes the list of problematic cases exponentially smaller (changing from anything that could be interpreted as a metacharacter in a double-quoted shell string being problematic to the exact case of three double quotes in sequence).
Filler text below that would excite problematic cases previously...
---
$PATH
$(cat /etc/passwd)
> Sanely handle shell metacharacters in PR bodies in package build CI matrix generation.

- packaging/installer/UPDATE.md
- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
This will report what the script would try to do on the system on which it’s run without actually doing any of it. This is intended to allow for easier testing of changes to the core logic in the script, as well as providing a way for users to see what the script would do on their system without having to suffer through reading the source code.
Also includes a handful of mnior changes to improve the overall UX of the script, as well as a numerous documentation updates relevant to this new option.
Sample output on one of my own systems which has a static install:
```
--- Using /tmp/.private/root/netdata-kickstart-JHjsk11vOV as a temporary directory. --- 
--- Checking for existing installations of Netdata... --- 
--- Found an existing netdata install at /opt/netdata, with installation type …
```
> Add a dry run mode to the kickstart script.

- database/rrdhost.c
Fixes #12362
Older agent versions (e.g. v.1.19, commit 5000257f0171271cb3ee2cf0fe02e8a2154ddf2e) do not properly encode an os name (e.g. "Raspbian GNU/Linux") and that results in an 
invalid json payload when viewing that agent from a parent
This PR is a quick fix to address this.
Before the PR the api/v1/info shows 
```
"os_name": ""Raspbian GNU/Linux"",
"os_id": "raspbian",
"os_id_like": "debian",
"os_version": "10 (buster)",
```
After the PR
```
"os_name": "'Raspbian GNU/Linux'",
"os_id": "raspbian",
"os_id_like": "debian",
"os_version": "10 (buster)",
```
- Setup parent - child (in this setup child is Raspbian and agent running is version 1.19.0)
- Visiting the child node from the parent will result in a blank screen because the /api/v1/info of the child node is an invalid json …
> Fix OS name for older agent versions streaming to a parent

- packaging/installer/kickstart.sh
This completely overhauls the error messages output by the kickstart installer script when the claiming process fails.
Relevant messages are the various `progress` and `warning` lines in the diff.
Exit code 5 is explicitly treated as _not_ being an error case, because the user just needs to restart the agent and things should work.
Exit code 6 is intentionally treated as an ‘unknown error’ case because it should never happen.
Exit code 7 is the catch-all for unknown HTTP errors, so it is also handled as part of the ‘unknown error’ case.
Exit codes 15, 16, and 17 are grouped because the differentiation between the cases is not particularly relevant to users and the required action to attempt to resolve the issue is the same for all three.
Manually inducing specific exit codes from the …
> Revise claiming error message in kickstart script.

- claim/claim.c
Even if for some reason (e.g. user edits claim_id) some character in uuid is uppercase we regenerate it as lowercase after successful parsing.
This makes agent behave as UUID RFC states:
- on input load UUID as case insensitive (be tolerant)
- on output generated uuids should always be lowercase
Change one character in `claim_id` to uppercase. Ensure there is no trailing newline in the claim_id file (otherwise it will fail, this is case also for master). Run `netdatacli aclk-state. Claim ID should be lowercase.
Fixes https://github.com/netdata/netdata/issues/12424
related to https://github.com/netdata/netdata/issues/12383
> fix: ensure claim_id is always sent lowercase as string

- packaging/installer/kickstart.sh
Fixes: #12060
- `sha256sum` has a different syntax on FreeBSD
- `shasum` is not
- the fix is to prefer `shasum` over `sha256sum` when calculating checksums.
Run the kickstart.sh script on a FreeBSD box, ensure there is no checksum validation error.
> fix(kickstart.sh): prefer shasum over sha256sum

- aclk/aclk.c
If `claim_id` contains a valid UUID agent is considered claimed. But if due to some error private key file is missing we were retrying immediately causing high CPU load and noise in log.
claim agent and delete `/var/lib/netdata/cloud.d/private.pem`, agent should retry log once per 5 seconds not go into retry loop
> Add delay on missing priv_key

- collectors/cups.plugin/cups_plugin.c
Fixes: #12447
Using the plugin name as a prefix is a common pattern we use (almost) everywhere. This PR applies this pattern to `cups.plugin`.
Lack of prefix is a problem for the Cloud overview page.
Not needed
> fix(cups.plugin): add `cups` prefix to chart context

- packaging/installer/netdata-uninstaller.sh
Fix detection of install type when static or build installation was performed on a native-supported platform.
Installed netdata using static method on a native platform (e.g Ubuntu) and ran the uninstaller.
> fix install type in netdata-uninstaller.sh

- daemon/system-info.sh
ssia
Tested on `FreeBSD freebsd 12.3-RELEASE FreeBSD 12.3-RELEASE r371126 GENERIC  amd64`:
- master branch
```cmd
wget -q -O system-info.sh https://raw.githubusercontent.com/netdata/netdata/master/daemon/system-info.sh; sh system-info.sh | grep -i freq; rm system-info.sh
NETDATA_SYSTEM_CPU_FREQ=unknown
```
- this PR
```cmd
wget -q -O system-info.sh https://raw.githubusercontent.com/ilyam8/netdata/fix_cpu_freq_freebsd/daemon/system-info.sh; sh system-info.sh | grep -i freq; rm system-info.sh
NETDATA_SYSTEM_CPU_FREQ=2400069742
```
> fix: CPU frequency detection of FreeBSD

- collectors/proc.plugin/proc_net_dev.c
- health/health.d/cgroups.conf
- health/health.d/net.conf
- web/gui/dashboard_info.js
Fixes: #12453
- Start several containers, check their network charts context.
```cmd
curl -sq localhost:19999/api/v1/charts | jq -j -c '.charts | .[] | select( .context | contains("cgroup.net")) | "- id:   \(.id)\n  ctx:  \(.context)\n"'
- id:   cgroup_nginx2.net_packets_eth0
ctx:  cgroup.net_packets
- id:   cgroup_nginx2.net_mtu_eth0
ctx:  cgroup.net_mtu
- id:   cgroup_nginx2.net_carrier_eth0
ctx:  cgroup.net_carrier
- id:   cgroup_nginx2.net_operstate_eth0
ctx:  cgroup.net_operstate
- id:   cgroup_nginx2.net_eth0
ctx:  cgroup.net_net
- id:   cgroup_nginx.net_packets_eth0
ctx:  cgroup.net_packets
- id:   cgroup_nginx.net_mtu_eth0
ctx:  cgroup.net_mtu
- id:   cgroup_nginx.net_carrier_eth0
ctx:  cgroup.net_carrier
- id:   cgroup_nginx.net_operstate_eth0
ctx:  cgroup.net_operstate
- id: …
```
> fix(collectors/cgroups): use different context for cgroup network charts

- collectors/cgroups.plugin/sys_fs_cgroup.c
Fixes: #12434
After this PR [cgroups.plugin](https://github.com/netdata/netdata/tree/master/collectors/cgroups.plugin#cgroupsplugin) will prefer `blkio.*_recursive` when collecting disk family stats.
> **blkio.*_recursive**
> Recursive version of various stats. These files show the
> same information as their non-recursive counterparts but
> include stats from all the descendant cgroups.
Will be tested by @ktsaou
> feat(collectors/cgroups): prefer `blkio.*_recursive` when available

- aclk/aclk_query.c
- aclk/aclk_tx_msgs.c
- aclk/aclk_tx_msgs.h
- aclk/aclk_util.h
Implements #12340 
See the generated message. Cloud hasn't implemented this yet but we got green light to send this (Cloud should for now ignore until they find time to implement) but should not cause errors on cloud.
> Implement fine-grained errors to cloud queries

- packaging/makeself/jobs/99-makeself.install.sh
This ensures that the version reported by `netdata -v` will match up with the version number embedded in the static build archive file names.
n/a
> Use the built agent version for Netdata static build archive name.

- web/gui/dashboard_info.js
This is the second PR that is improving our user navigation among eBPF charts, it is bringing:
- A main menu in `netdata monitoring` -> `ebpf.plugin`
- New description for Process, Hard Disk, File System (File access and Directory Cache).
- Cleanup some content that were already moved for our documentation.
The content of the PR was already discussed with product team (@cpipilas ) and our documentation team (@DShreve2 ), and we know that `cgroups` different of `systemd` does not have specific links. We also avoided exclusive links to disks. This does not mean that in the future we will address this issues, but for the next Netdata release, we are only addressing static content.
1. Compile this branch, or only copy `web/gui/dashboard_info.js` to `/usr/share/netdata/web/dashboard_info.js` …
> Update ebpf dashboard

- collectors/timex.plugin/README.md
- health/health.d/timex.conf
- web/gui/dashboard_info.js
Adjusts the timex plugin dashboard info description, clock_sync error description and readme.md to be more clear about the source of the alarm. This does not change the source of the alarm itself
Fixes: #12405
> Adjust timex.plugin information to be less cryptic

- packaging/makeself/install-alpine-packages.sh
- packaging/makeself/jobs/50-bash-5.1.16.install.sh
- packaging/makeself/jobs/50-curl-7.82.0.install.sh
- packaging/makeself/jobs/50-fping-5.1.install.sh
- packaging/makeself/openssl.version
Changes:
1. `apk update` is run to update alpine packages
2. `apk upgrade` to install any updates alpine packages
3. `bash` updated to version 5.1.16
4. `openssl` updated to version 1.1.1n
5. `fping` updated to version 5.1
6. `curl` updated to version 7.82
It builds and runs. Tested armv7l version.
> Updated static build components to latest versions.

- database/sqlite/sqlite_aclk_alert.c
This PR tries to help with the case where the cloud requests multiple alert snapshots from the agent before the agent had time to respond.
When the cloud requests a snapshot, we store in `wc` the snapshot_id provided by the cloud, and queue a command to reply to that request. The reply will contain the snapshot_id send by the cloud. When the reply is finished, the agent sets this snapshot_id to 0.
There are cases where the cloud sends 2 snapshot requests with the same snapshot_id, at the same time. When this happens, the agent sends back a snapshot reply with the correct snapshot_id and another reply with snapshot_id 0. The cloud can not process the last reply.
With this PR, we cover:
1) Never send back a snapshot with snapshot_id 0.
2) If a second request comes with the same snapshot_id …
> Don't send an alert snapshot with snapshot_id 0

- .github/CODEOWNERS
Today is his last day, so let’s not bother him any further.
n/a
> Remove Konstantinos Kaskavelis from CODEOWNERS.

- daemon/static_threads_linux.c
ssia, big thanks to @vlvkobal for finding the root cause.
Closes: #12507
Install this PR, ensure there is only one TIMEX thread running.
</details>
> fix: Netdata segfault because of 2 timex.plugin threads

- packaging/installer/netdata-updater.sh
This will be quite handy when testing the changes in the updater script. Update forcing works for static and from source builds.
Run the new version with the `--force-update` option, see it updates Netdata even if there is no new version available:
- static isntall.
- from the source install.
@netdata/agent-sre I am not sure that the modification behavior of the `update_available` function is the correct change. If you think we shouldn't do it please comment, I will move out checking `NETDATA_FORCE_UPDATE` from it.
> feat(netdata-updater): add `--force-update` parameter

- .github/workflows/release.yml
Fixes: #12517
We should use "update-changelogs" job outputs, the current code works only when the workflow is triggered by a dispatch event.
Fixed publishing of native packages.
</details>
> fix(ci): properly handle "schedule" event in the release workflow

- daemon/analytics.c
The discrepancy was noticed on a node that had ML enabled. There's a dedicated, hidden chart that tracks anomaly rates. However, the dims in that chart are not hidden because they are meant to be queried by the `/data` endpoint.
Compare `metrics-count` and `charts-count` of `/api/v1/info` against `charts_count` and `dimensions_count` of `/api/v1/charts` with/without ML.
Fixes https://github.com/netdata/netdata/issues/12476.
> Use live charts to count the total number of dimensions.

- database/rrddim.c
Health is not enabled for the anomaly rates chart. This was missed in
the original PR that added support for tracking anomaly rates with
dbengine. The side-effect was that the agent would block when opening
the dashboard before its initialization was done.
- Local & CI jobs.
- Start an agent with `[ml] enabled = true` and quickly visit the dashboard.
Somewhat related to https://github.com/netdata/netdata/issues/12316, in the sense that it made the problem more pronounced because we'd end up write-locking the host ~2x as much.
> Skip `foreach` alarms for dimensions of anomaly rate chart.

- packaging/installer/kickstart.sh
Fixes: #12527
Run the kickstart script with `--auto-update` parameter, ensure auto-updating is enabled.
</details>
> fix(kickstart.sh): use `$ROOTCMD` when setting auto updates

- system/netdata.conf
Both debian/rpm packages use [system/netdata.conf](https://github.com/netdata/netdata/blob/master/system/netdata.conf). We have changed both CPU scheduling policy and OOM score in https://github.com/netdata/netdata/pull/12271. 
Not needed
</details>
> fix: use internal defaults for sched policy/oom score in native packages

- packaging/installer/netdata-updater.sh
Fixes: #12525
This PR:
- removes `[ "${INSTALL_UID}" != "$(id -u)" ]` check for `binpkg` packages (we don't create `.environment` file for deb).
- changes `pkg_installed_check` from `dpkg -l` to `dpkg -s`, because `-l` doesn't really work
<details>
<summary>dpkg -l</summary>
```bash
ilyam@deb-fra1-01:~$ dpkg -l | grep netdata
ilyam@deb-fra1-01:~$ sudo apt-get install netdata-repo-edge >/dev/null
ilyam@deb-fra1-01:~$ dpkg -l netdata-repo && echo $?
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
un  netdata-repo   <none> …
```
> fix(netdata-updater): properly handle update for debian packages

- ml/Config.cc
Reduce the lower bound on the clamp for `dbengine anomaly rate every` from 60s to 30s
</details>
> reduce min `dbengine anomaly rate every` 60s->30s

- daemon/system-info.sh
ssia, I discovered (during PT call with @cboydstun 😄) that my Netdata container CPU freq is "unknown" on the Cloud. The container is on DO Debian 11 droplet.
- master branch
```bash
bash-5.1# wget -q -O system-info.sh https://raw.githubusercontent.com/netdata/netdata/master/daemon/system-info.sh; sh system-info.sh | grep -i freq; rm system-info.sh
NETDATA_SYSTEM_CPU_FREQ=unknown
```
- this PR
```bash
bash-5.1# wget -q -O system-info.sh https://raw.githubusercontent.com/ilyam8/netdata/cpu_freq_add_proccpuinfo/daemon/system-info.sh; sh system-info.sh | grep -i freq; rm system-info.sh
NETDATA_SYSTEM_CPU_FREQ=2494000000
```
</details>
> fix: use `/proc/cpuinfo` for CPU freq detection as a last resort

- collectors/cgroups.plugin/sys_fs_cgroup.c
Fixes: #12555
If Netdata runs in a container, the cgroups plugin hangs on some VMs on `fgets()` while trying to get info from `systemd --version`. We introduce a timeout for the attempt to get the information.
Run containerized Netdata several times. Make sure the group plugin does not hang while reading configuration.
> Unblock cgroup version detection with systemd

- ml/Config.cc
- ml/Config.h
- ml/Dimension.cc
- ml/Dimension.h
- ml/Host.cc
- ml/Host.h
- ml/kmeans/SamplesBuffer.cc
- ml/kmeans/SamplesBuffer.h
- ml/ml.cc
Relevant changes to address comments in:
- https://github.com/netdata/netdata/issues/12173
- https://github.com/netdata/netdata/issues/12177
- https://github.com/netdata/netdata/discussions/12350
At a high-level:
- Allow sleeping for more than one second in the training thread.
- Use a heartbeat for the prediction thread.
- Use getrusage for training/prediction CPU usage.
- Skip only `netdata.*` charts from training.
- Random sampling of extracted features.
Each commit in this PR constitutes a standalone change to make review easier.
Local testing + CI jobs + staging environment
> ML-related changes to address issue/discussion comments.

- database/sqlite/sqlite_aclk_alert.c
Don't try to send alert events if `wc->host` is not yet connected. If that happens, it is better to wait for the next iteration of the function (when eventually `wc->host` will be ok... ?) instead of sending an event with missing timezone data.
Fixes #12539 
Since it's hard to reproduce, basic testing of alerts still going to the cloud after this change should be ok.
> Don't send alert events without wc->host

- packaging/docker/run.sh
This adds a new environment variable to our entrypoint script named `NETDATA_EXTRA_CLAIM_OPTS`. The contents of this variable will be passed directly (with word splitting) to the claiming script if it is invoked by the Docker entrypoint, allowing passing of arbitrary additional options.
A simple test with a locally built Docker image can be done by adding `-e NETDATA_EXTRA_CLAIM_OPTS=-verbose` to the options passed to `docker run` when creating the image.
Without the changes in this PR, the claiming process should produce it’s normal terse output.
With the changes in this PR, the claiming process should produce verbose output.
> Add support for passing extra claiming options when claiming with Docker.

- daemon/main.c
- daemon/unit_test.c
- daemon/unit_test.h
Proactively catch https://github.com/netdata/netdata/pull/12512 in the future.
- CI jobs
- Register the same static thread twice, build/run the agent with internal checks.
The implementation is O(N^2) but it shouldn't matter because we only have a handful of static threads, and the code runs only when building the agent with internal checks enabled.
> Make sure registered static threads are unique.

- configure.ac
- packaging/installer/dependencies/alpine.sh
- packaging/installer/dependencies/centos.sh
- packaging/installer/dependencies/debian.sh
- packaging/installer/dependencies/fedora.sh
- packaging/installer/dependencies/ol.sh
- packaging/installer/dependencies/opensuse.sh
- packaging/installer/dependencies/rockylinux.sh
- packaging/installer/dependencies/ubuntu.sh
- packaging/installer/install-required-packages.sh
The build failed on riscv64 because the build command line lacks libatomic. Fix this by always linking against libatomic since:
- if atomics are not needed, the library will be unused
- if atomics are needed, either atomics are fulfilled by the compiler builtins
and the library is unused or the library is needed anyway.
Fixes #12319
Successfully built on all architectures (https://launchpad.net/~alexghiti/+archive/ubuntu/riscv/+sourcepub/13305735/+listing-archive-extra)
Signed-off-by: Alexandre Ghiti <alexandre.ghiti@canonical.com>
> configure.ac: Unconditionally link against libatomic

- contrib/debian/rules
For some reason, even with moving to compat 10 in #12488, `dh_systemd_enable` isn't called automatically by `dh_installinit`. This patch explicitly calls `dh_systemd_enable` to make sure the service is enabled on install. 
This also cleans up the general call to `dh` dropping the `--with`parameters that are enabled by default in compat >= 10.
Fixes #12250.
- Build a new `.deb` from scratch.
- Verify that the `postinst` in `control.tar.xz` inside the package has a section marked `dh_systemd_enable`, that uses the `deb_systemd_helper` to enable the service.
- Possibly: install the debian on a fresh machine and verify the service is enabled by checking `systemctl status netdata`.
For users: How does this change affect me?
- Enables the Netdata systemd service upon first install of the Debian …
> Explicitly use debhelper to enable systemd service

- packaging/installer/netdata-updater.sh
This ensures that we are actually using the temporary directory we created when trying to pull in build dependencies in the updater.
This can be verified by running the copy of the updater script from this PR on macOS, or in an environment where `$TMPDIR` is not set and `/` is read-only.
Fixes: #12515 
Users on macOS will be able to successfully run the updater script again.
</details>
> Fix temporary directory handling for dependency handling script in updater.

- configure.ac
- netdata-installer.sh
This PR https://github.com/netdata/netdata/pull/12048 silently broke the case where there is a system protobuf copy installed in `/usr/local/include` and bundled protobuf is requested (the default option and sane one if built from source). This was done by adding the system's include path into `CFLAGS` which proceeds every other flag due to:
`CFLAGS="${CFLAGS} ${OPTIONAL_PROTOBUF_CFLAGS} ...` in `configure.ac`
This is wrong for multiple reasons and introduces hidden bugs.
Fixes https://github.com/netdata/netdata/issues/12516
Stacked on top of (review that first) https://github.com/netdata/netdata/pull/12552
This is split into 2 PRs also because reviewers who have FreeBSD and reviewers who have MacOS testing ability might be not the same people. (+ of course 1PR one job rule)
Ensure you …
> Fix Build on MacOS

- packaging/repoconfig/netdata-edge.repo.centos
- packaging/repoconfig/netdata-edge.repo.fedora
- packaging/repoconfig/netdata-edge.repo.ol
- packaging/repoconfig/netdata-repo.spec
- packaging/repoconfig/netdata.repo.centos
- packaging/repoconfig/netdata.repo.fedora
- packaging/repoconfig/netdata.repo.ol
This makes us more reliably pull our won packages instead of installing stuff from EPEL or other sources when we try to install with the kickstart script on CentOS and similar systems.
n/a
Fixes: #12334
> Set repo priority in YUM/DNF repository configuration.

- database/rrd.h
- database/rrddim.c
- health/health.c
The previous approach required us to try wr-lock the host
after locking a chart and sleeping on failure. Lock contention
would lead to alarms not being created and the agent to become
unresponsive.
- Local testing to verify that foreach alarms are created and evaluated.
Resolves https://github.com/netdata/netdata/issues/12316
> Initialize foreach alarms of dimensions in health thread.

- packaging/installer/install-required-packages.sh
- packaging/installer/kickstart.sh
SSIA
This can be tested using an Alma Linux Docker container.
Fixes: #12486
> Properly recognize Almalinux as an RHEL clone.

- database/sqlite/sqlite_aclk_alert.c
- database/sqlite/sqlite_aclk_chart.c
- database/sqlite/sqlite_aclk_node.c
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
Fixes #12325
- Improves logging as described in the linked issue
- Apply the PR to a claimed agent and observe the `access.log`. The messages regarding the ACLK sync communication are more compact.
- For offline nodes, the hostname is recorded properly where previously it would be logged as "N/A"
Easier to understand information logged in access.log for the ACLK sync communication
</details>
> Improve ACLK sync logging 

- contrib/debian/netdata.postinst
Fixes: #12579
ssia, I guess it gets reset after we do
https://github.com/netdata/netdata/blob/6086e2477608441fe11ec7d4fee124cbf31fa6d7/contrib/debian/netdata.postinst#L53
should re-add after if the ioping binary exists.
Install deb package, ensure setuid bit is not removed.
</details>
> fix: re-add setuid bit to ioping after installing Debian package

- collectors/ebpf.plugin/ebpf_socket.c
- web/gui/dashboard_info.js
When PR https://github.com/netdata/netdata/pull/12503 was merged, some of the links used in our dashboard are not redirecting exactly for the sections they should, or they were broken. This PR is fixing these links.
1. Enable the following threads inside your `/etc/netdata/ebpf.d.conf`:
```conf
disk = yes
fd = yes
filesystem = yes
process = yes
```
3. Test updated links. All links must be opened in another tab/window.
It is not necessary to test on different kernels, because this PR is only changing dashboard links.
- Which area of Netdata is affected by the change? Dashboard
- Can they see the change or is it an under the hood? If they can see it, …
> Update links to documentation (eBPF)

- aclk/aclk.c
- aclk/aclk_util.c
- daemon/main.c
- database/engine/datafile.c
- database/engine/journalfile.c
- database/rrdcalctemplate.c
- database/rrddim.c
- database/rrdset.c
- health/health_config.c
- streaming/compression.c
In order to make memory leak debug easier, we fix memory leaks in
There are also errors connected with `uv_thread_create`. It seems they are caused by the library itself, I'm not sure though.
Fixes #12510
Build Netdata, run it with Valgrind, press Ctrl+C. Check if there are no memory leaks on Netdata exit, except those connected with `uv_thread_create`.
> Fix memory leaks on Netdata exit

- database/rrdhost.c
- database/rrdset.c
- database/sqlite/sqlite_aclk_chart.c
- database/sqlite/sqlite_aclk_chart.h
Fixes #12443
- Reverts changes made that delayed (by taking into account the chart obsoletion setting) the propagation of liveness update of dimensions to the cloud
- Adds additional checks to verify the current liveness of charts during the runtime of the agent
- This is done as the agent checks for charts that need to be obsoleted
- Adds check for dimension liveness when the `retention update message` is calculated for each node
- This is done soon after an agent restart (60 seconds after aclk sync messages settle) and periodically (every hour)
- As described in the linked issue
> Fix issue with charts not properly synchronized with the cloud

- database/rrdset.c
We have a huge amount of log messages on child reconnect
https://github.com/netdata/netdata/blob/edea331caf2dc0d407a6c746ac71f57914d25318/database/rrdset.c#L156
This log message doesn't provide much value and is mainly just a noise. This PR changes it severity level to debug.
CI checks.
</details>
> chore: make logs less noisy on child reconnect

- database/rrd.h
- ml/Config.cc
- ml/Config.h
- ml/Host.cc
- ml/ml-dummy.c
- ml/ml.cc
- ml/ml.h
- streaming/rrdpush.c
- move training/prediction stats charts under the netdata section,
- update type/id/name for ml charts,
- assign aforementioned charts to child host instance,
- do not stream ML charts by default
Inspect parent/child dashboards with `build_external/scenarios/parent-child`
with ML enabled and with/without streaming of ML charts.
Resolves https://github.com/netdata/netdata/issues/12549
> Update ML-related charts

- collectors/macos.plugin/macos_fw.c
`__is_identifier()` works only in clang. We need a more robust check for `IOMainPort()`. IOKit SDK version checking is proved to be more reliable and portable than `__is_identifier()`.
Fixes #12560
Build Netdata on macOS.
> Better check for IOMainPort on MacOS

- collectors/cgroups.plugin/sys_fs_cgroup.c
- web/gui/dashboard_info.js
This PR adds two new charts:
- CPU Throttled Runnable Periods
- CPU Throttled Time Duration
Fixes: #12595
Closes: netdata/netdata-cloud#375
Install this PR, run a container with a CPU limit, and ensure the charts have values for both cgroups v1 and v2.
</details>
> feat(cgroups.plugin): add CPU throttling charts

- packaging/installer/kickstart.sh
This fixes a similar issue with gpg keys as reported in https://github.com/netdata/netdata/issues/12154, but for Centos8, AlmaLinux and RockyLinux
Verify kickstart works as expected (native install) on CentOS8, Alma and Rocky.
</details>
> fix centos gpg key issue

- collectors/cgroups.plugin/sys_fs_cgroup.c
Otherwise, it is 0 when we calculate cpu_used the first time. The value is not stored locally but (looks like) transferred when streaming.
https://github.com/netdata/netdata/blob/e7e5e61d655ab44dcf8748fcac60dc02182a0d40/collectors/cgroups.plugin/sys_fs_cgroup.c#L3596-L3597
Test manually.
</details>
> fix(cgroups.plugin): set CPU prev usage before first usage.

- web/api/web_api_v1.c
Fixes #12568 
If for any reason there is trouble committing the Health API management key to disk, don't exit, but instead inform the user to fix the problem and provide the produced api key in the log file. This can be used to access the management API, but only during this session of Netdata.
Specify a readonly path to save the key (e.g. `/root/something` if running as a normal user) in field `netdata management api key file` under `registry` in `netdata.conf`. Using this PR the agent will keep running, and the printed key can be used to access the API.
> Don't do fatal on error writing the health api management key.

- Makefile.am
These were somehow missed when they were originally added.
n/a
Fixes: https://github.com/netdata/netdata/issues/12478
With this change, eBPF will work correctly on newer kernels.
</details>
> Add eBPF CO-RE version and checksum files to distfile list.

- daemon/get-kubernetes-labels.sh.in
Part of netdata/product#2382. The cluster name format is: `gke_${projectID}_${location}_${cluster-name}`.
Install this PR on a GKE cluster, and check the "host_labels" (/api/v1/info).
</details>
> feat: add k8s_cluster_name host tag (GKE only)

- packaging/installer/kickstart.sh
SSIA
Can be verified by attempting to use the kickstart script from this PR to claim a node that was installed by a method other than the kickstart script (for example, via the FreeBSD Ports tree, or through Homebrew).
This also adds an extra sanity check to the claiming code in the kickstart script so that we provide a more user friendly error message if a usable claiming script cannot be found.
> Add handling for claiming non-standard install types with kickstart.

- packaging/installer/kickstart.sh
In a small section of kickstart, for error `F0204` we print `The --install option is only supported together with the --only-build option.` yet the parameter is actually `--build-only`. If you add `--only-build` then it is not recognized.
Try kickstart with `--install` parameter, it will show the above error.
</details>
> Show --build-only instead of --only-build

- packaging/repoconfig/netdata-repo.spec
We should only depend on yum-plugin-priorities on older CentOS systems and no other platforms.
n/a
Installation using native packages on RPM systems other than CentOS works again.
</details>
> Properly limit repository configuration dependencies.

- collectors/plugins.d/plugins_d.c
- collectors/plugins.d/plugins_d.h
- database/rrd.h
- database/rrdset.c
- web/api/netdata-swagger.json
- web/api/netdata-swagger.yaml
- web/api/web_api_v1.c
- web/api/web_api_v1.h
This PR will add a `chart_labels_filter` parameter in data queries. This will apply in context queries when a list of chart label keys and values need to match in order for the chart to be included in that data query
Adds the description in swagger (also adds previously missing description for `chart_label_key` 
- Setup an agent that monitors a k8s cluster 
- Execute a context query e.g
`/api/v1/data?chart_label_key=k8s_cluster_id&context=cgroup.net_packets`
This should return results
- Apply the PR and assuming your k8s_cluster_id is `dcbda642-4c3b-11ea-b701-4201ac100014` execute a modified query using
`/api/v1/data?chart_label_key=k8s_cluster_id&context=cgroup.net_packets&chart_labels_filter=k8s_cluster_id:dcbda642-4c3b-11ea-b701-4201ac100014` 
Note the …
> Add a chart label filter parameter in context data queries

- .github/workflows/cloud_regression.yml
Remove the on pull_request_target trigger for the Cloud tests workflow.
Also fix the pull request event evaluation, in case it's to be used again in the future.
We're triggering too many github actions due to the many pushes on PR branches. 
E2E cloud regression will be only triggered for pushes against master for now, until we re-evaluate the process.
> Remove on pull_request trigger

- collectors/timex.plugin/plugin_timex.c
SSIA
Edit: Ilya's suggestion: we won't collect data as well if the call is failed.
Check the `timex.plugin` collects data if the ADJUST_TIMEX call doesn't fail.
> Show error when clock synchronization state is unavailable

- collectors/ebpf.plugin/ebpf_oomkill.c
- collectors/ebpf.plugin/ebpf_oomkill.h
- collectors/ebpf.plugin/ebpf_vfs.c
- collectors/ebpf.plugin/ebpf_vfs.h
This PR adds missing chart context to the following eBPF modules:
- oom
- vfs
Without this change, the context is not common across all the cgroups charts, but unique per cgroup.
cc @hugovalente-pm 
---
@thiagoftsm, I've checked all other modules, but you know the collector much better, please check if I've missed something.
Check the modified charts in /api/v1/charts, and make sure their context does not contain the cgroup name.
</details>
> fix(ebpf.plugin): add missing chart context for cgroups charts

- database/rrdhost.c
- ml/ml.cc
Initialization of ML-related structures and threads should happen
when the underlying RRD objects have been fully initialized. Destruction
should happen in the opposite way, ie. before deleting an RRD host/dimension.
Reproducing the linked issue is difficult because we need a setup that frequently frees streaming RRD hosts with ML enabled.
I've tested a parent/child setup with ML-enabled by running & killing the parent and/or the child several times, without managing to crash either of them.
Resolves https://github.com/netdata/netdata/issues/12648
> Delete ML-related data of a host in the proper order.

- packaging/installer/kickstart.sh
This way users will be more likely to see them, and we will have an easier time actually helping users who encounter issues.
The actual code currently collects any messages passed to the `warning` function, as well as any commands that failed when run by the `run` function. If any such errors arise, they will be printed when the script exits in most cases as a summarized list sorted by the order in which they occurred during execution.
The relevant code can easily be triggered by passing an option to the kickstart script that would normally be passed to `netdata-installer.sh`.
Fixes: #12631
This also inlines a couple of one-line functions that are only invoked in a single location, slightly simplifying the surrounding code. …
> Summarize encountered errors and warnings at end of kickstart script run.

- packaging/makeself/build-static.sh
- packaging/makeself/build.sh
Also, fix handling of the source directory in the builds so that we don’t leave behind a dirty source directory.
Static build CI passes on this PR.
</details>
> Fix the static build code in light of CVE-2022-24765

- ml/Host.cc
Originally, the main training/detection thread loops where meant to be
run only for the localhost host. They would stop when `netdata_exit` was
set to true during the shutdown process.
By enabling training/detection for children, we have to explicitly
cancel ML threads because the service thread can free a child host at any
point in time without setting `netdata_exit` to true.
To support this:
- We send a cancellation request to the training and the detection
threads when we call rrdhost_free.
- We disable/enable cancelation for the actual training/detection step
on every iteration (in order to protect locks and shared data structures).
Tested manually, by replacing `while (!netdata_exit)` with `while (true)` in the
main loop of the training/detection threads. Without the cancellation …
> Cancel anomaly detection threads before joining.

- .github/labeler.yml
This PR:
- changes 'ACLK' label to 'area/ACLK'.
- adds 'database/sqlite/sqlite_aclk*' path for 'area/ACLK'.
Not needed.
</details>
> chore(ci): adjust ACLK label

- .github/workflows/build.yml
It was always retrying steps instead of only doing so on failures.
Test environment preparation with the updated code from this PR completes quickly, with the retries skipped.
> Fix retry code in build CI.

- aclk/aclk_alarm_api.c
- aclk/aclk_stats.c
- aclk/schema-wrappers/alarm_stream.cc
- database/engine/journalfile.c
- database/engine/rrdengine.c
Fixes
Fixes #12618
1. Build Netdata
```
sudo CFLAGS="-Og -ggdb -Wall -Wextra -Wformat-signedness -fno-omit-frame-pointer -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTiFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --use-system-protobuf --disable-lto --dont-wait --dont-start-it
```
2. Run it with Valgrind
```
sudo valgrind --leak-check=yes /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM score keep
```
3. Press Ctrl+C and check if there are no errors mentioned above in the Valgrind output.
> Fix Valgrind errors

- collectors/ebpf.plugin/ebpf.d.conf
This PR enables socket thread because #12027 (the reason we disabled it) has been fixed.
Not needed
</details>
> chore(ebpf.plugin): re-enable socket module by default

- packaging/docker/health.sh
The port in healthcheck is hardcoded
https://github.com/netdata/netdata/blob/e36fbebaa205c1c3c2304a8395e74a118bcca17b/packaging/docker/health.sh#L7
This is a problem when NETDATA_LISTENER_PORT is set to a non-default value.
https://github.com/netdata/netdata/blob/e36fbebaa205c1c3c2304a8395e74a118bcca17b/packaging/docker/run.sh#L62
</details>
> fix: use NETDATA_LISTENER_PORT in docker healtcheck

- spawn/spawn_client.c
- spawn/spawn_server.c
Fixes #12685
Allocate buffers needed for uv_write and let the callback function release the memory
- Alert notifications should work
> Allocate buffer memory for uv_write and release in the callback function

- collectors/cgroups.plugin/cgroup-network-helper.sh
There is no need to call `lsns` for every task in a cgroup when finding network interfaces. This small change significantly reduces the CPU time.
- I have a server with 50 docker containers
- 1st "spike" is our current code.
- 2nd is this PR.
Check `netdata` process CPU usage (should be lower), check containers on the dashboard (should have network interfaces).
</details>
> chore(cgroups.plugin): reduce the CPU time required for cgroup-network-helper.sh

- collectors/apps.plugin/apps_groups.conf
Caddy is quit widely used and also in the Netdata setup document
I guess its nice to have it
I tested on one of my Netdata instance
Before it was in others, then I tried group under caddy (which is now missing), then httpd
> feat(apps.plugin): add caddy to apps_groups.conf

- streaming/receiver.c
This PR adds a 10 minute timeout on the receiver socket for streaming connections.
When this is set, after 10 minutes of no received data from a child it will exit the parser, and declare the child ORPHAN. This could be useful in cases where the child disappears from the network before sending a disconnect.
The default timeout without setting it, is I believe 0, which can cause the connection to remain open. (If anyone knows, please advise).
Setup a child and parent. 
Disconnect the child from the network, and observe what happens with and without this PR. With this PR after 10 minutes of inactivity the receiving thread should stop, and the child be considered ORPHAN. If the child returns during this 10 minute span, it should continue normally to stream.
> Add a 2 minute timeout to stream receiver socket

- database/rrdcalc.c
- database/rrdcalc.h
- health/health.c
- health/health_json.c
- health/health_log.c
This PR allows repeating alerts to be stored in health log (both in memory and in sqlite). It merely removes code that checked that if the alert is repeating, it should not store it in health log.
If the global option `default repeat warning` or `default repeat critical` is used, then no entries for any alert will be recorded in the health log.
The health code creates a new alarm log entry for every instance of a repeating alert. What this PR changes, is that the first instance of the alert will be stored and recorded in the health log, along with it's initial and removed states when the agent starts and shuts down. 
The entries for the next repeats will not, but will continue to be created and produce a notification.
However, since all it does is remove code that was there to protect …
> Store alert log entries even if alert it is repeating.

- packaging/installer/kickstart.sh
Passing it does nothing after https://github.com/netdata/netdata/pull/12296. Enabling auto updates is handled by
https://github.com/netdata/netdata/blob/a7af7e343e93199b03c5ec7ec261ccdce3fc6ef6/packaging/installer/kickstart.sh#L1060
Not needed.
</details>
> chore(kickstart.sh): remove unused `--auto-update` option when using static/build install method

- collectors/cgroups.plugin/cgroup-name.sh.in
This PR adds [k8s_qos_class](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#qos-classes) label to pod/container charts in Kubernetes.
- install this PR in k8s.
- query api/v1/charts.
- check all the cgroups charts have "k8s_qos_class" label.
</details>
> feat(cgroups.plugin): add k8s_qos_class label

- README.md
Because it hasn't been working for a while and I see no interest in fixing it. If we need it - let's fix it.
[Click](https://github.com/netdata/netdata/blob/be7c36fbd990ba476295bdc6ab6ec5410bde69c3/README.md#netdata-is-high-fidelity-infrastructure-monitoring-and-troubleshootingopen-source-free-preconfigured-opinionated-and-always-real-time).
</details>
> chore: remove Codacy badge from the repo readme

- collectors/cgroups.plugin/sys_fs_cgroup.c
No reason to execute the script for everything except сontainers (e.g. pods), because it is filtered by the "enable by default cgroups matching" option.
Not needed.
</details>
> fix(cgroups.plugin): run renaming script only for containers in k8s

- collectors/cgroups.plugin/sys_fs_cgroup.c
- web/gui/dashboard_info.js
This PR adds collecting a relative share of CPU time available to the tasks in a cgroup by reading 'cpu.shares' (v1) or 'cpu.weight' (v2) file.
> ❗ The chart is enabled by default only when Netdata is running inside a K8s cluster.
For both cgroup v1 and v2: start several containers, check that "CPU Time Relative Share" exists.
</details>
> feat(cgroups.plugin): add "CPU Time Relative Share" chart

- collectors/cgroups.plugin/README.md
- collectors/cgroups.plugin/sys_fs_cgroup.c
We create a "search for cgroups under PATH" entry for every directory, but we **never** remove these entries, which is a memory leak. Fixing it properly looks tricky and I think not worth it. So this PR just removes the option.
Add several containers, ensure there is no "search for cgroups under PATH" under "[plugin:cgroups]".
</details>
> fix(cgroups.plugin): remove "search for cgroups under PATH" conf option to fix memory leak

- collectors/cgroups.plugin/sys_fs_cgroup.c
- daemon/common.h
- libnetdata/config/appconfig.c
We add `enable cgroup X = yes/no` option to the `plugin:cgroup` section for every discovered cgroup. But we never remove it. This PR fixes the problem. 
```cmd
$ docker run -d --rm --name nginx1 nginx > /dev/null
$ docker run -d --rm --name nginx2 nginx > /dev/null
$ curl -s "localhost:19999/netdata.conf" | grep "enable cgroup nginx"
$ docker stop nginx2 > /dev/null
$ curl -s "localhost:19999/netdata.conf" | grep "enable cgroup nginx"
```
</details>
> fix(cgroups.plugin): remove "enable cgroup X" config option on cgroup deletion

- .github/labeler.yml
Noticed that we don't mark the repo readme file as area/docs in https://github.com/netdata/netdata/pull/12742.
Not needed.
</details>
> chore(ci): add the root dir markdown files to area/docs

- libnetdata/config/appconfig.h
Forgot to add it in https://github.com/netdata/netdata/pull/12746
```c
In file included from collectors/cgroups.plugin/sys_fs_cgroup.h:6,
from collectors/cgroups.plugin/sys_fs_cgroup.c:3:
collectors/cgroups.plugin/sys_fs_cgroup.c: In function 'cleanup_all_cgroups':
./daemon/common.h:30:54: warning: implicit declaration of function 'appconfig_section_option_destroy_non_loaded'; did you mean 'appconfig_section_destroy_non_loaded'? [-Wimplicit-function-declaration]
30 | #define config_section_option_destroy(section, name) appconfig_section_option_destroy_non_loaded(&netdata_config, section, name)
|                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./daemon/common.h:30:54: note: in definition of macro 'config_section_option_destroy'
30 | #define …
```
> fix implicit declaration of function 'appconfig_section_option_destroy_non_loaded'

- database/rrdset.c
To my understanding, those lines are not really useful and we don't really them for debugging.
The reason to hide them under NETDATA_INTERNAL_CHECKS
The parent instance with 15 children:
```cmd
$ ls -lh error.log
-rw-r--r-- 1 netdata netdata 1.7G Apr 21 18:52 error.log
$ wc -l error.log
5481155 error.log
$ grep -E "secs in the (future|past)" error.log | wc -l
4434442
```
So it is 80% of error.log.
---
@MrZammler if you think something like "print it if enough of them accumulate", then I suggest making it in a separate PR 😉 
Not needed
</details>
> chore: reduce logging in rrdset

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
This provides a consistent way for users to pass options to either `netdata-installer.sh` (for local builds) or the static installer code (for static installs). It also deprecates all existing methods of doing this, which will ultimately enable us to eventually have `kickstart.sh` explicitly reject unrecognized options passed to it.
The newly added options are:
- `--local-build-options`: Used to specify additional options to be passed to `netdata-installer.sh`. The argument immediately following it will be appended to the list of options being passed to `netdata-installer.sh`. Requires that `--build-only` also be passed to `kickstart.sh`
- `--static-install-options`: Used to specify additional options to be passed to the static installer. The argument immediately following it will be …
> Add options to kickstart.sh for explicitly passing options to installer code.

- .github/scripts/run-updater-check.sh
- netdata-installer.sh
- packaging/installer/functions.sh
- packaging/installer/kickstart.sh
- packaging/installer/netdata-uninstaller.sh
- packaging/installer/netdata-updater.sh
This significantly reworks how the kickstart script handles tracking of warnings and errors from `netdata-installer.sh`, `netdata-updater.sh`, and `netdata-uninstaller.sh`. At a high level, these changes mean that:
- Any errors or warnings generated by these scripts while running will be included (in the correct chronological order) in the warning summary printed by the kickstart script at the end of a run.
- Fatal errors in these scripts will be properly logged by the kickstart script, including the error message generated by the script.
- A handful of cases (mostly in `netdata-installer.sh` which were functionally fatal errors but were not handled as such will be handled correctly as fatal errors now.
- A handful of cases that should have been warnings instead of fatal errors have been …
> Correctly propagate errors and warnings up to the kickstart script from scripts it calls.

- packaging/installer/kickstart.sh
If no options are specified, use the value `default` to indicate that the default behavior is requested. Long-term, this will allow us to easily have different defaults depending on other installation parameters.
Shorter term, it allows us to explicitly indicate in telemetry events whether the user asked for auto updates, asked for no auto updates, or just went with the default.
Basic testing to verify that the script still handles auto-updates correctly is all that is required.
</details>
> Treat auto-updates as a tristate internally in the kickstart script.

- database/engine/pagecache.c
- database/engine/rrdengine.c
- database/engine/rrdengine.h
- database/engine/rrdengineapi.c
- database/rrddim.c
- database/rrdset.c
- libnetdata/libnetdata.c
- libnetdata/libnetdata.h
Fixes: #12744
This PR replaces DBengine page cache allocation/deallocation calls with `mmap()`/`munmap()` when available.
Used options:
- `MADV_DONTFORK`, to prevent these pages from being copied on `fork()`.
- `MADV_MERGEABLE`, to enable these pages to be deduped with KSM (this can half the cache size impact on the system).
- `MADV_DONTDUMP`, to prevent these pages from being included in coredumps.
Start/stop Netdata, keep it running in a stressed env (15-20 children instances), and ensure there are no segfaults.
</details>
> feat(dbengine): make dbengine page cache undumpable and dedupuble

- aclk/aclk_otp.c
Env endpoint can now return the same HTTP payload in case of error as challenge and password endpoint.
`aclk_otp.c` line 846 change the URL so the `cap` is some garbage. For example `cap=sadfsdfsad`. Cloud will return the error payload. We should now honor it also when `/env` endpoint returns it.
For now, only testing cloud env has this working properly (prod/staging is missing fix on cloud side as of now).
</details>
> use aclk_parse_otp_error on /env error

- streaming/receiver.c
Adds a check on the return value on `setsockopt` to fix coverity report:
```
>>>     CID 352524:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "setsockopt(rpt->fd, 1, 20, &timeout, 16U)" without checking return value. This library function may fail and return an error code.
```
Thanks to @thiagoftsm for reporting!
> Fix coverity on receiver setsockopt

- packaging/installer/netdata-updater.sh
We should check that `${REINSTALL_OPTIONS}` is defined, not that it is defined to a non-empty string.
Updater runs correctly on systems where `REINSTALL_OPTIONS` is empty in the `.environment` file instead of running into a fatal error.
The updater will work correctly again in a couple of cases it was broken for.
</details>
> Fix checking of enviornment file in updater.

- packaging/makeself/jobs/70-netdata-git.install.sh
- Switch from `-O3` to `-O2` for optimization CFLAGS, bringing us in-line with all of our other builds. This should help avoid strange edge cases specific to static builds resulting from the build process.
- Stop stripping binaries in static builds so that we can get proper symbolic backtraces when the agent crashes in the static builds.
Static builds created with this PR can produce proper symbolic backtraces when run under GDB.
Relevant to: https://github.com/netdata/netdata/issues/12505
Static builds will have a marginally larger runtime memory footprint, a slightly higher disk space requirement, and may run marginally slower (but should be no slower than the other install types …
> Tweak static build process to improve build speed and debuggability.

- ml/Config.cc
- set `dbengine anomaly rate every` to 30 by default to provide better sorting functionality for anomaly advisor.
- increase upper clamp on `MaxTrainSamples` to 24 hours for those who might like a larger training window on a parent.
- decrease lower clamp on `MinTrainSamples` to 15 minutes to enable faster training of initial models.
Some updates to config options/limits. 
I have created a node with 30s and one with default of 60s and comparisons of some important metrics can be seen below. Basically it seems like they are very similar profiles. But a 30s aggregation vs a 60s aggregation gives much better sorting performance in terms of quality for the Anomaly Advisor in Netdata Cloud. 
We have also previously validated that the ml functionality works fine with a training window of 24 …
> some config updates for ml

- packaging/installer/functions.sh
Fixing a typo in `warning()`.
https://github.com/netdata/netdata/blob/3f45709706a59b431b76443b0fbe23c9115768a8/packaging/installer/functions.sh#L272-L273
The output is:
```sh
Press ENTER to build and install netdata to '/opt/netdata' >
Skipping protobuf
%{TPUT_BGYELLOW} WARNING  You have requested use of a system copy of protobuf. This should work, but it is not recommended as it's very likely to break if you upgrade the currently installed version of protobuf.
```
Not needed
</details>
> fix: printing a warning msg in installer

- netdata-installer.sh
- current
```cmd
The following warnings and non-fatal errors were encountered during the installation process:
\n  - You have requested use of a system copy of protobuf. This should work, but it is not recommended as it's very likely to break if you upgrade the currently installed version of protobuf.\n  - eBPF has been explicitly disabled, it will not be available in this install.
```
- this PR
```cmd
The following warnings and non-fatal errors were encountered during the installation process:
- You have requested use of a system copy of protobuf. This should work, but it is not recommended as it's very likely to break if you upgrade the currently installed version of protobuf.
- eBPF has been explicitly disabled, it will not be available in this install.
```
<details> <summary>For …
> fix(installer): non interpreted new lines when printing deferred errors

- collectors/cgroups.plugin/cgroup-network-helper.sh
- collectors/proc.plugin/proc_net_dev.c
Proxmox networking is the following: 
- `fwbr<VMID>i<network interface X>` is the firewall bridge where the filtering happens.
- `fwpr<VMID>i<network interface X>` is the bridge in the device.
- `fwln<VMID>i<network interface X>` is the bridge out device.
- `tap<VMID>i<network interface X>` is the connector port for the guest (VM).
- `veth<VMID>i<network interface X>` is the connector port for the guest (LXC).
<details>
<summary>brctl show</summary>
```cmd
brctl show
bridge name	bridge id		STP enabled	interfaces
docker0		    8000.024277c16a36	no
fwbr101i0		8000.12482e7ef46e	no		fwln101i0
tap101i0
fwbr102i0		8000.de83bf7b6c17	no		fwln102i0
tap102i0
fwbr103i0		8000.faf93a98e77d	no		fwln103i0
tap103i0
fwbr105i0		8000.120651255bdf	no		fwln105i0
veth105i0
vmbr0		    8000.d85ed30ec5e6	no …
```
> fix(proc/net/dev): exclude Proxmox bridge interfaces 

- libnetdata/libnetdata.c
MADV_DONTDUMP is not defined on non-Linux platforms. Make `madvise_dontdump()` a NOP on MacOS and FreeBSD.
CI jobs + built locally on M1
Fixes https://github.com/netdata/netdata/issues/12793
We need to move OS-specific logic under `libnetdata/os.c` in a follow-up commit.
> Don't use MADV_DONTDUMP on non-linux builds

- netdata-installer.sh
We really lose a lot of time recompiling protobuf every time and there is really nothing we can do to prevent this, apart from disabling protobuf or using the system default. Both of these options are problematic, because then we are testing a version of netdata that is not the final one.
This PR adds a simple check: if a compiled protobuf exists and it is the same version to the one we need, don't compile it again. Just skip protobuf downloading and compilation.
> just a simple fix to avoid recompiling protobuf all the time

- libnetdata/libnetdata.c
- libnetdata/libnetdata.h
- libnetdata/procfile/procfile.c
Speedup `procfile` reads significantly on big files.
On my `/proc/kallsyms` (used by ebpf) this PR is 20% times faster, from 140 ms to 116 ms.
Test:
compile with `-DNETDATA_LOG_ALLOCATIONS=1`. For the master before this PR, copy libnetdata.c and libnetdata.h from this PR to get the same interface for the memory logs.
```c
int main(int argc, char **argv) {
usec_t start = now_realtime_usec();
procfile *ff = procfile_open("/proc/kallsyms", " \t", PROCFILE_FLAG_DEFAULT);
if(unlikely(!ff)) {
error("Cannot open %s%s", netdata_configured_host_prefix, NETDATA_KALLSYMS);
exit(1);
}
ff = procfile_readall(ff);
usec_t end = now_realtime_usec();
printf("file read in %llu usec\n", end-start);
log_allocations();
procfile_close(ff);
exit(0);
}
```
The current master needs 140ms and does 45k reallocs:
``` …
```
> procfile: more comfortable initial settings and faster/fewer reallocs

- netdata-installer.sh
- packaging/docker/Dockerfile
- packaging/makeself/jobs/20-openssl.install.sh
- packaging/makeself/jobs/50-bash-5.1.16.install.sh
- packaging/makeself/jobs/50-curl-7.82.0.install.sh
- packaging/makeself/jobs/50-fping-5.1.install.sh
- packaging/makeself/jobs/50-ioping-1.2.install.sh
- packaging/makeself/jobs/70-netdata-git.install.sh
This trades marginally higher memory usage at build time (on the order of a few hundred kB in the worst case scenario) for improved build times by avoiding using temporary files for passing data from the compiler to commands it invokes.
CI passes on this PR, with builds taking slightly less time than otherwise.
Install and update times are improved for local builds.
</details>
> Add `-pipe` to CFLAGS in most cases for builds.

- collectors/cgroups.plugin/cgroup-network.c
[detect_veth_interfaces()](https://github.com/netdata/netdata/blob/7ae0a2e21d9fcd965c2bde20869b586ea5c1483a/collectors/cgroups.plugin/cgroup-network.c#L410) works correctly only when the cgroup proc (cgroup.procs) is not in the host network namespace.
The bug was discovered when we installed Netdata on a Proxmox host with several VMs.
```bash
$ readlink /proc/self/ns/net
net:[4026532008]
$ nsenter -t $(cat /sys/fs/cgroup/qemu.slice/103.scope/cgroup.procs) -n readlink /proc/self/ns/net
net:[4026532008]
$ ps -o comm= --pid $(cat /sys/fs/cgroup/qemu.slice/103.scope/cgroup.procs)
kvm
```
The end result is adding all double-linked host interfaces to the last discovered VM cgroup.
<details>
<summary>Screenshot</summary>
</details>
<details>
<summary>Screenshot when the patch applied</summary> …
> fix(cgroups.plugin): do not add network devices if cgroup proc is in the host net ns

- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_aclk.h
- database/sqlite/sqlite_aclk_alert.c
- database/sqlite/sqlite_aclk_alert.h
- database/sqlite/sqlite_aclk_chart.h
- health/health.c
- health/health_log.c
The purpose of this PR is to reduce the number of alert events sent to the cloud. Right now the agent does not apply any specific rules on which alert events to send, thus in some situations (mostly during restarts) will send events that are of no use to the cloud experience.
This PR tries to skip consecutive same alert events if:
* The alert configuration has not changed
* There is a less than 15 minutes difference between a REMOVED event and a new WARNING or CRITICAL status. If the new status is CLEAR we skip this check.
It will also handle better the case of an agent claimed while running. On the first start streaming request for batch_id 1 and start sequence 1, it will try to queue the existing alerts to the cloud. The relevant query there also takes into account the alert events …
> Reduce alert events sent to the cloud.

- libnetdata/buffer/buffer.c
- libnetdata/buffer/buffer.h
- web/api/formatters/json/json.c
Optimize BUFFER increases for large web requests.
This PR makes buffer increases about 25% faster for large buffers.
In the following test case, using the BUFFER of the master, it finishes in 65 ms. With this PR it finishes in 50 ms.
Test:
```c
int main(int argc, char **argv) {
BUFFER *wb = buffer_create(1024);
const char *string = "012345678901234567890123456789012345678901234567890123456789";
size_t size_of_string = strlen(string);
size_t total = 0;
usec_t start = now_realtime_usec();
while(total < 40*1024*1024) {
buffer_sprintf(wb, "%s", string);
total += size_of_string;
}
usec_t end = now_realtime_usec();
printf("Buffer of %zu bytes finished in %llu usec\n", buffer_strlen(wb), end-start);
log_allocations();
buffer_free(wb);
exit(0);
}
```
Test results from master:
```
Buffer of …
```
> Speed up BUFFER increases (minimize reallocs)

- CMakeLists.txt
- Makefile.am
- configure.ac
- daemon/unit_test.c
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
- libnetdata/Makefile.am
- libnetdata/libnetdata.h
- libnetdata/onewayalloc/Makefile.am
- libnetdata/onewayalloc/README.md
- libnetdata/onewayalloc/onewayalloc.c
- libnetdata/onewayalloc/onewayalloc.h
- web/api/formatters/rrd2json.c
- web/api/formatters/rrd2json.h
- web/api/queries/query.c
- web/api/queries/rrdr.c
- web/api/queries/rrdr.h
- web/api/web_api_v1.c
Context queries do a gazillion of `mallocz()`, `strdupz()` and `freez()` to create the virtual chart that takes all the dimensions of the context.
This PR adds a `one way allocator`, a set of functions that allocate large blocks using `mmap()` (the fastest possible) and then calls to `onewayalloc_mallocz()` returns blocks of memory within the mmap allocated buffer.
It allocates more and more mmap buffers as needed, transparently, but it takes into account the amount of memory already allocated, to minimize future allocations.
- Allocation are done using `mmap()` with flags: `MAP_ANOMYMOYS|MAP_PRIVATE`. KSM is disabled for them, since this is expected to be short lived
- Allocations are aligned to the CPU `sizeof(size_t)` size. So, the minimum allocation is for that size and all the …
> One way allocator to double the speed of parallel context queries

- daemon/main.c
- libnetdata/Makefile.am
- libnetdata/avl/avl.c
- libnetdata/clocks/clocks.c
- libnetdata/clocks/clocks.h
- libnetdata/locks/README.md
- libnetdata/locks/locks.c
- libnetdata/locks/locks.h
- spawn/spawn_server.c
Allows tracing rwlocks in netdata.
compile with `-DNETDATA_TRACE_RWLOCKS=1`.
Then in error log you may find lines like this:
```
RW_LOCK ON LOCK 0xd3e3a300: 2706979, 'SERVICE' (function service_main() 35@daemon/service.c) WANTS a 'W' lock.
=> 1: RW_LOCK: process 2706977 'HEALTH' (function health_main() 750@health/health.c) is having 1 'R' lock for 2406668 usec.
```
To help solve the issue #12770
---
I did some tests on the performance on clocks, to understand which clock should be used to report usage in locks.
Here is the test:
<details><summary>click to see the test code</summary>
```c
struct clock {
clockid_t clockid;
const char *name;
};
#define HISTOGRAM_SIZE 10000
#define ITERATIONS 10000000
int main(int argc, char **argv) {
struct clock clocks[] = {
{CLOCK_BOOTTIME, "CLOCK_BOOTTIME …
```
> Trace rwlocks of netdata

- database/rrd.h
- database/rrdhost.c
- health/health.c
- streaming/receiver.c
When a child is connected and streams to a parent, the parent has a set of the streamed charts from the child. However, if the child at some point disconnects, and during that disconnection time a chart it has disappear, then on re-connection, the parent will have no information that that specific chart has been gone.
If a chart is gone during the child being connected to the parent, the child will inform the parent about that chart's obsoletion, but not in the above case.
If in addition, there is a raised alert on the gone chart, then the alert will remain on the parent, until the parent restarts. The same alert will also remain on the cloud since there won't be any event after that.
This PR adds a small check on the parent, after a child is connected. It will go through the charts for …
> Check for chart obsoletion on children re-connections

- netdata-installer.sh
- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
Add the new --install-prefix option and add a deprecation warning to the existing --install option. #12659
Tested with `./kickstart.sh --install-prefix /test --build-only `pointed to netdata-installer.sh from local path.
</details>
> Rename --install option for kickstart.sh

- database/engine/rrdengine.h
- database/engine/rrdengineapi.c
- database/rrd.h
- database/rrddim.c
- ml/Dimension.h
- ml/Query.h
- web/api/queries/query.c
Following the idea discussed here:
https://github.com/netdata/netdata/discussions/12216
This PR introduces some minor cleanups and refactoring that can be merged independently from other changes, allowing to introduce more changes in subsequent pull requests.
These commits do the following (in commit order):
* Move `rrddim_collect_ops` and `rrddim_query_ops` out of the `rrddim_volatile` structure, allowing them to be used outside of the context of this structure. Later, we plan to use these structures to allow storage engines to expose their collection and query APIs.
* Make `rrddim_collect_handle` and `rrddim_query_handle` opaque structures instead of a union, allowing for arbitrary handle types, later provided by arbitrary memory modes/storage engines.
These changes don't add any new …
> Configurable storage engine for Netdata agents: step 1

- collectors/cgroups.plugin/README.md
- collectors/cgroups.plugin/cgroup-name.sh
- collectors/cgroups.plugin/sys_fs_cgroup.c
- collectors/cgroups.plugin/sys_fs_cgroup.h
- collectors/cgroups.plugin/tests/test_cgroups_plugin.c
So many changes in one PR because the goal was to fix the following problem:
- Netdata loses some containers on a K8s cluster when:
- the CPU % of the node is high (100% in our case).
- A lot of containers are created in a short time. 
The changes address that problem. After this patch, the amount of CPU time needed for cgroup name resolution is ~40% less.
`enable by default cgroups names matching` is just a nice addition that came naturally 😄 
---
This PR:
- **[feat]**: Adds `enable by default cgroups names matching` filter. It matches the name of the cgroup (as you see it on the dashboard). It is much easier to filter specific containers, e.g.: `!nginx2 *`.
- **[feat]**: K8s: wait for container initialization (`runc:[2:INIT]` may take a while) and don't try to rename/collect …
> feat(cgroups.plugin): add filtering by cgroups names and improve renaming in k8s

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
- Added a new option named `--nightly-channel` for symmetry with `--stable-channel`.
- Added a new option named `--release-channel` for a future-proof way to explicitly specify a particular release channel.
- Added a third release channel value named `default` to indicate that the user has indicated no preference for a specific release channel.
- Decoupled the selected release channel from the one indicated in telemetry events, allowing us to differentiate between the default channel being selected because the user explicitly asked for it, and it being selected because the user indicated no preference.
Simple testing to verify the behavior of the new options and ensure that release channel selection is working correctly is sufficient.
<details> <summary>For users: How does this change …
> Improve handling of release channel selection in kickstart.sh.

- database/rrd.c
- database/rrd.h
- database/rrddim.c
- database/rrdset.c
- exporting/tests/exporting_fixtures.c
- health/health.c
- streaming/rrdpush.c
- web/api/formatters/rrdset2json.c
After https://github.com/netdata/netdata/pull/12209 per-chart configuration was used for (a) enabling/disabling a chart, and (b) renaming dimensions.
Regarding the first use case: We already have component-specific configuration options|flags to finely control how a chart should behave. Eg. `send charts matching` in streaming, `charts to skip from training` in ML, etc. If we really need the concept of a disabled chart, we can
add a host-level simple pattern to match these charts.
Regarding the second use case: It's not obvious why we'd need to provide support for remapping dimension names through a chart-specific configuration from the core agent. If the need arises, we could add such support at the right place, ie. a exporter/streaming config section.
This will allow each flag to act …
> Remove per chart configuration.

- libnetdata/onewayalloc/onewayalloc.c
We have seen a case that the kernel refuses to allocate mmap() memory to netdata (to both dbengine and onewayallocator) under system stress.
We couldn't reproduce this problem with OWA using malloc instead of mmap.
So, this PR switches OWA to use malloc()
> onewayallocator to use mallocz() instead of mmap()

- database/rrdset.c
There is no real reason why we need to replace `-` with `_` in chart names. At the moment there is no way to split the chart name into logical entities because [we have no separator](https://github.com/netdata/netdata/blob/8e46581d822180b2bf6874372492e44203a1406e/database/rrdset.c#L124-L137). 
- Allowing `-` is nice, we will be able to do the following: `it-em1_it-em2_it-em3_...` and splitting by `_` will result in a valid value.
- Also using `-` is a pretty common pattern and mangling original names is wrong imo.
⚠️  This PR is a breaking change for:
- memory mode `save` and `map`: metrics for charts with `-` will be lost.
- exporting: metrics for charts with `-` will have different `chart` label values.
❗ But:
- The only charts with `-` are …
> fix!: do not replace a hyphen in the chart name with an underscore

- CMakeLists.txt
- Makefile.am
- REDISTRIBUTED.md
- daemon/common.h
- daemon/main.c
- database/KolmogorovSmirnovDist.c
- database/KolmogorovSmirnovDist.h
- database/metric_correlations.c
- database/metric_correlations.h
- web/api/web_api_v1.c
This is a first attempt at implementing/copying [ks_2samp](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html) which is used by cloud to run metric correlations. It follows the path for `two-sided` in mode `asymp`.
It will respond to api call at `/api/v1/metric_correlations` where it needs 4 inputs that describe 2 timeframes: baseline (defined by `baseline_after` and `baseline_before`) and a highlight area (defined by `highlight_after` and `highlight_before`) and will return a json similar to what is returned now in the cloud.
Still in testing, mostly to figure out if numbers match the python implementation, and for cloud to be able to consume the json response (differs slightly than cloud implementation in that it contains also chart contexts).
> Metric correlations

- daemon/main.c
- database/engine/rrdengine.c
- database/engine/rrdengineapi.c
Add a new parameter in the global config `libuv worker threads"` to set the number of libuv worker threads that should be automatically pre initialized by the library. The default is 16
- Start an agent before the PR. The default threads that the library uses is 4
- You should be able to use `gdb` to access the thread names. You should see 5 threads with the name `DBENGINE`
After the PR, the thread name will be `LIBUV_WORKER` and you should be able to see 16 threads with the LIBUV_WORKER name and one thread with the DBENGINE name
There is no other effect on the code
> Add a parameter for how many worker threads the libuv library needs to pre-initialize

- web/server/web_client.c
The `/api/v1/data` query now logs just /api/v1/data in the access.log
With this PR it will record the parameters as well 
e.g.
`/api/v1/data?chart=cpu.cpu8_softnet_stat`
- Apply the PR and check the `access.log` while viewing the agent dashboard
> Write the entire request with parameters in the access.log file

- libnetdata/completion/completion.c
Otherwise, `-W createdataset=xxx` blocks.
CI & make sure `-W createdataset=xxx` completes.
> Broadcast completion before unlocking condition variable's mutex

- database/rrddim.c
- health/health.c
Keep the write-lock on host but use read-lock for charts because it's
easy to verify that they aren't modified by the linking of foreach
alarms to dimensions.
Tested on an agent that previously experienced lock starvation when running heavy concurrent queries.
> Optimize linking of foreach alarms to dimensions.

- aclk/aclk_query.c
- aclk/aclk_query_queue.h
- aclk/aclk_rx_msgs.c
The cloud now sends a `timeout` parameter in the incoming query header (in milliseconds). If a query remains in the incoming queue for more than `timeout` milliseconds then it will be cancelled immediately (with an appropriate error code back to the cloud)
- Should be easy to check by adding an artificial delay in the aclk_query message processing to "fake" a long queue wait time
> Accept a data query timeout parameter from the cloud

- database/sqlite/sqlite_health.c
In a normal agent lifecycle, during agent shutdown and alert reload, the agent creates (while unlinking alerts) removed alert events for every alert currently in memory.
When the agent starts up again, it picks up from that removed event and creates new uninitialized, and the clear, etc.
If when it starts some of those alerts are no longer evaluated, we're left with not updated removed events in the database. Those not-updated removed events are then propagated to the cloud. (And in effect any raised alerts from these will be removed since they will no longer be evaluated).
In case of an agent crash though, we lose that intermediate state of removed alert events. This PR tries to detect this case and inject removed events in the database for all alerts that are missing it. This happens …
> Fill missing removed events after a crash

- database/sqlite/sqlite_functions.c
If the host has been deleted from the database, cleanup the related node instance entries from the database
- Should be self explanatory
> Cleanup the node instance table on startup

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
Adding --install-version flag in kickstart.sh for installing specific version of Netdata Agent. #12633
Install Netdata native, static or build on stable or nightly channel from kickstart.sh and specify version with --install-version flag.
centos78
./kickstart.sh --stable-channel --install-version 1.18.0-1.el7
./kickstart.sh --stable-channel --static-only --install-version 1.30.0
./kickstart.sh --stable-channel --build-only --install-version 1.30.0
./kickstart.sh --install-version 1.29.3.215.nightly-1.el7
./kickstart.sh --static-only --install-version 1.33.1-78-g9ef13f190
./kickstart.sh --build-only --install-version 1.33.1-78-g9ef13f190
centos79
./kickstart.sh --stable-channel --install-version 1.18.0-1.el7
./kickstart.sh --stable-channel --static-only --install-version 1.30.0 …
> add --install-version flag for installing specific version of Netdata

- database/engine/rrdengineapi.c
Occasionally due to time drift(?), we may end up with metrics in two pages that overlap. This produces an error e.g.
`Ignoring metric with out of order timestamp.`
The metric itself is not ignored, but this message indicates that it has been found twice.
This PR will avoid the individual messages and only print a summary of metrics that have been ignored. 
Eg.
`Ignored 886 metrics with out of order timestamp in 1 regions.`
- Should be trivial to check
> Reduce the number of messages written in the error log due to out of bound timestamps

- collectors/ebpf.plugin/ebpf.c
- collectors/ebpf.plugin/ebpf.d.conf
- collectors/ebpf.plugin/ebpf_sync.c
- libnetdata/ebpf/ebpf.c
- libnetdata/ebpf/ebpf.h
This PR is fixing warnings reported [here](https://github.com/netdata/netdata/pull/12760#issuecomment-11185521280).
1. Compile this PR 
2. Run `netdata`.
3. After few seconds, run next command and verify warnings were removed:
```sh
$ grep libbpf /var/log/netdata/error.log
```
This PR must be tested on kernel `5.7` or newer and your kernel needs to have BTF enabled.
- Can they see the change or is it an under the hood? If they can see it, where? This is only visible inside logs.
- How is the user impacted by the change?  We won't have `libbpf` warnings inside the `error.log`
- What are there any benefits of the change? The …
> Remove sync warning

- database/engine/pagecache.c
- database/engine/pagecache.h
- Use a timeout when waiting for the page request
- Add a retry count before giving up (caller will assume the page is empty or doesn't exist)
- Change should be obvious
> Set a page wait timeout and retry count

- .github/workflows/packaging.yml
This way, if the tests fail, we can fetch the artifacts manually to inspect the binaries.
CI works correctly on this PR.
</details>
> Save built packages in CI before testing them.

- collectors/plugins.d/pluginsd_parser.c
- collectors/proc.plugin/proc_spl_kstat_zfs.c
- daemon/main.c
- database/engine/metadata_log/logfile.c
- database/engine/rrdengineapi.c
- database/rrdcalc.c
- database/rrddim.c
- parser/parser.c
- streaming/receiver.c
- web/api/queries/des/des.c
there are a few cases where we mix and match allocations and deallocations with the `z` functions...
Also there were the following memory leaks:
1. for every dbengine data query, there was a memory leak
2. on plugins exit (that are joined by their parents threads), there was a memory leak
3. on streaming receiver exit (that are joined by their parent threads), there was a memory leak
There are certain jobs that are hard to detect memory leaks:
1. Database queries that span multiple submodules of netdata
2. Streaming clients (senders) that connect and disconnect all the time
3. Streaming parents (receivers) that get connections and disconnections all the time
4. Streaming proxies (receivers and senders), a special case that spawn threads to implement both functions
Special care is needed …
> fix memory leaks and mismatches of the use of the z functions for allocations

- database/rrddim.c
- database/sqlite/sqlite_aclk_chart.c
Resolve coverity issues
- Variable "hostname" going out of scope leaks the storage it points to.
- Null-checking "rd->name" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
- Run coverity to verify the issues are resolved
> Resolve coverity related to memory and structure dereference

- ml/Dimension.h
- ml/Host.cc
- ml/Host.h
Teach prediction thread to ignore obsolete charts/dims. This will allow `/ml_info` to return back the correct numbers a user would expect to see.
CI & staging
Fixes https://github.com/netdata/netdata-cloud/issues/363
TODO: create a follow-up PR to teach training thread to schedule dims for training without considering obsolete charts/dims.
> Ignore obsolete charts/dims in prediction thread.

- database/sqlite/sqlite_aclk.c
- Adds a database checkpoint command (best effort ; in passive mode) to prevent the WAL file size from growing
[Checkpoint](https://www.sqlite.org/c3ref/wal_checkpoint_v2.html)
_Checkpoint as many frames as possible without waiting for any database readers or writers to finish, then sync the database file if all frames in the log were checkpointed. The [busy-handler callback](https://www.sqlite.org/c3ref/busy_handler.html) is never invoked in the SQLITE_CHECKPOINT_PASSIVE mode. On the other hand, passive mode might leave the checkpoint unfinished if there are concurrent readers or writers._
- N/A
> Add a SQLite database checkpoint command

- collectors/cgroups.plugin/cgroup-name.sh
This PR adds `k8s_cluster_name` for K8s pod/containers cgroups. Works only on GKE.
This PR unblocks netdata/dashboard#395.
The end result is having a proper K8s cluster name instead of ID:
cc @hugovalente-pm 
Install this branch on a GKE cluster, and check cgroups charts labels.
</details>
> feat(cgroups.plugin): add k8s cluster name label (GKE only)

- daemon/main.c
- daemon/unit_test.c
- database/engine/pagecache.c
- database/rrdhost.c
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
When the dbengine stress test runs, there are a lot of errors because the metadata database is not initialized
This PR will create an in-memory database to store the metadata while the test is running
- Run a small stress test using e.g `netdata -W stresstest=120,2000,64,120,32,128`
- Notice a lot of warning messages / errors e.g
```
2022-05-09 21:06:15: netdata ERROR : MAIN : Database has not been initialized
2022-05-09 21:06:15: netdata ERROR : MAIN : Failed to prepare statement to lookup chart UUID in the database  
2022-05-09 21:06:15: netdata ERROR : MAIN : Failed to bind prepare statement to lookup dimension UUID in the database
``` 
- Apply the PR and rerun the test
> Initialize the metadata database when performing dbengine stress test

- packaging/makeself/build-static.sh
This switches to using a pre-generated Docker image for our static builds.
This has two advantages:
- It provides a marginal improvement in build times when running under QEMU userspace emulation like we do for our alt-arch static builds.
- It avoids the complex cleanup needed on developer systems by the current code.
Fixes: #12817 
</details>
> Use prebuilt builder images for static builds.

- collectors/cgroups.plugin/cgroup-name.sh
- collectors/cgroups.plugin/sys_fs_cgroup.c
Fixes: #12774
The default behavior of the `cgroup-name.sh` script in K8s when can't rename a cgroup (regardless of the cause: lack of `jq`, not enough permissions to query K8s API, Kubelet configuration file is not readable, etc) is to disable the cgroup. 
The justification (I guess) was: 
1. can not find the name, it means no labels, it means no Kubernetes section on the Cloud.
2. this was the way we filtered out pause containers.
Since 2. is not applicable anymore after #12778, we can reverse logic: can not rename a cgroup => show the cgroup (using the path as the name, e.g. `kubepod podXXXX YYYYY`). I think it makes more sense than what we're doing now.
Test the change in GKE cluster.
</details>
> fix(cgroups.plugin): do not disable K8s pod/container cgroups if can't rename them

- daemon/global_statistics.c
- libnetdata/clocks/clocks.c
- libnetdata/worker_utilization/README.md
- libnetdata/worker_utilization/worker_utilization.c
1. Eliminated division by zero when running workers exit all together, but the statistics thread is still running
2. Eliminated division by zero when all threads calling `heartbeat_next()` exit, but the statistics thread is still running
3. Updated documentation of workers utilization
4. Added a chart to show the absolute total CPU utilization of all workers together (100% = 1 core)
5. Moved API statistics to the `api` family (were in `netdata` family)
6. When a worker was busy for a long time, the busy time chart of the worker was reflecting this, but the job busy time chart was not. At the job busy time, time was accumulated when the worker switched state. Fixed it, so that the job busy time shows the busy time of running jobs too.
> workers fixes and improvements

- libnetdata/worker_utilization/worker_utilization.c
There are cases that per job busy time is negative:
The problem is that we were adding the same busy time twice while the worker was busy, but when the worker switched state and we found out the actual work time, the chart presented a negative value.
Fixed it: we should not persist the busy time of in-flight busy workers. It is recalculated on every iteration already.
> fix for negative per job busy time

- .github/data/distros.yml
- .github/scripts/pkg-test.sh
- packaging/PLATFORM_SUPPORT.md
This PR switches from using Rocky Linux for RHEL compatible support to using Alma Linux instead. This should translate to no user-visible changes, but is preferable for us for two reasons:
- Alma Linux has commercial support options, while Rocky does not. This is generally indicative of much better long-term staying power for a distro.
- Alma Linux has better cross-architecture support, which is beneficial to us long-term.
This PR also recynchronizes the platform support document with our list of currently supported platforms, as it’s gotten a bit out of sync.
No user-visible changes.
</details>
> Switch to Alma Linux for RHEL compatible support.

- streaming/receiver.c
Fixes #12603
Set the trust durations parameter properly to make sure that data received via streaming is properly aligned with the chart update every. 
- Set up parent with multiple children, claim parent to cloud
- Occasionally you may notice charts being not properly aligned in the overview screen (especially with update every > 1)
- Apply the PR and observe the improved behavior
> Set trust durations to have data from children properly aligned

- health/health_config.c
[Overwriting specific stock alarms/templates](https://community.netdata.cloud/t/overwriting-alerts-configuration/2837) results in duplicate alarm/template configs, which is expected and not an error.
We log the message using `info` level for alarms:
https://github.com/netdata/netdata/blob/dd313048f6907e052cc8da2a5d001ad35635ee25/database/rrdcalc.c#L245-L246
This PR changes the level from `error` to `info` for templates. The issue is [reported on our community forum](https://community.netdata.cloud/t/overwriting-alerts-configuration/2837/4).
Not needed
</details>
> fix(health): change duplicate health template message logging level to 'info'

- CMakeLists.txt
- Makefile.am
- database/ram/rrddim_mem.c
- database/ram/rrddim_mem.h
- database/rrd.c
- database/rrd.h
- database/rrddim.c
- database/storage_engine.c
- database/storage_engine.h
- web/api/queries/query.c
Following the idea discussed here:
https://github.com/netdata/netdata/discussions/12216
This change introduces the new storage engine API for `rrddim_collect` and `rrddim_query`  operations. It introduces the new compile-time list of storage engines and APIs to find an engine by name or id.
These commits do the following (in commit order):
* Add the new storage engine API, and use it to find an engine id by name or name from id.
* Use the new API for dimension collection and query
These changes don't add any new memory modes/storage engines for now, and only refactor existing features, so they are expected to be covered by existing unit tests.
> Configurable storage engine for Netdata agents: step 2

- health/health_config.c
- web/server/web_client.c
This will allow DB lookups to use the stored anomaly-bit values, eg:
> lookup: average -10m unaligned anomaly-bit of user,system,softirq,irq,guest
CI jobs
Resolves https://github.com/netdata/product/issues/2796
> Expose anomaly-bit option to health.

- collectors/cgroups.plugin/sys_fs_cgroup.c
- collectors/cgroups.plugin/tests/test_doubles.c
- collectors/proc.plugin/proc_pressure.c
- collectors/proc.plugin/proc_pressure.h
- web/gui/dashboard_info.js
Closes: #12882
This PR:
- adds [PSI](https://www.kernel.org/doc/html/latest/accounting/psi.html) total stall time for CPU, memory, I/O resources:
- per host.
- per cgroup (v2 only).
<br>
> The total absolute stall time (in us) is tracked and exported as well, to allow detection of latency spikes which wouldn’t necessarily make a dent in the time averages, or to average trends over custom time frames.
- adds collecting `full` for CPU. Despite the [PSI doc](https://www.kernel.org/doc/html/latest/accounting/psi.html) saying the CPU resource has only `some`, our Proxmox server has both:
```cmd
$ cat /proc/pressure/cpu
some avg10=0.00 avg60=0.00 avg300=0.00 total=775799775
full avg10=0.00 avg60=0.00 avg300=0.00 total=651201120
```
Install this branch on a host with PSI and cgroups v2, check …
> feat(proc/cgroups.plugin): add PSI stall time charts

- aclk/aclk_query.c
- web/api/web_api_v1.c
When a data query is executed with a `timeout` parameter, take into account the `in queue` wait time. 
For example a query with a timeout of 9000ms and a response logged as 
`2022-05-11 18:04:04: 0: 1458642 '[ACLK]:0' 'DATA' (sent/all = 2279/14963 bytes -85%, prep/sent/total = 7.04/0.43/7.47 ms) 
200 '/node/d6166b5d-d925-4d4c-9143-0883bd262512/api/v1/data? .. . points=493&timeout=9000'`
Would end up having a timeout of 8993 ms due to a 7ms prep time
- Run a local dashboard query with a small timeout parameter e.g
http://127.0.0.1:19999/api/v1/data?chart=system.cpu&after=-7200&timeout=1
you will get a 503 error due to timeout (unless the query completes in under a ms in which case increase the data requested)
> Take into account the in queue wait time when executing a data query

- web/api/formatters/charts2json.c
Fixes #12888
Parse the program version (actually check for '-') if the existing detection mechanism fails
- Compile and change the `.environment` file to break the detection of the release channel from there
> Return stable or nightly based on version if the file check fails

- collectors/proc.plugin/proc_stat.c
In order to fix chart aggregation on Netdata Cloud, we remove the CPU-specific info from dimension names for cpuidle charts. We also provide more meaningful context for the charts.
Fixes #12889
Make API request `http://localhost:19999/api/v1/chart?chart=cpu.cpu0_cpuidle`. It should show the new context name and dimension names in the response
```
"context": "cpuidle.cpu_cstate_residency_time",
"dimensions": {
"active": { "name": "C0 (active)" },
"poll": { "name": "POLL" },
"c1": { "name": "C1" }
},
```
> Remove CPU-specific info from cpuidle dimensions

- claim/README.md
The information on how to disconnect and reconnect a node was obsolete. `kickstart.sh` has supported this option for a while now. 
Validate the info is correct.
> Update reconnect node with kickstart info

- collectors/cgroups.plugin/sys_fs_cgroup.c
ssia
https://github.com/netdata/netdata/blob/44b9fd0e13f861886ac3e428582c5f9de2c5104c/collectors/cgroups.plugin/sys_fs_cgroup.c#L4892-L4904
ci
</details>
> fix(cgroups.plugin): use correct identifier when registering the main thread "chart" worker job

- collectors/cgroups.plugin/sys_fs_cgroup.c
Uninitialized containers processing postponing is important because:
- K8s API won't return data (pod/container name, etc) for them, and spending `pending_renames` makes no sense.
- we don't really know if that is a pause container (which we should skip) or not.
After #12865 we don't disable K8s pod/container if fail to rename them. It means that identifying pause containers becomes crucial - if we fail, we collect metrics from them.
Start a lot of pods (I did 400), check that all containers discovered/renamed and there are no pause containers being collected.
</details>
> fix(cgroups.plugin): improve check for uninitialized containers in k8s

- daemon/global_statistics.c
- libnetdata/config/appconfig.c
- libnetdata/config/appconfig.h
See "Test Plan"
- master
```ini
[CONFIG_SECTION_GLOBAL_STATISTICS]
```
- this PR
```ini
[global statistics]
```
</details>
> fix `[global statistics]` section in netdata.conf

- daemon/system-info.sh
This PR improves virtualization detection:
- Removes (not really useful) `grep -q "^flags.*hypervisor" /proc/cpuinfo` check.
- Adds using the "Hypervisor vendor" field from `lscpu` output.
The "Hypervisor vendor" field provides more or less the same data as `systemd-detect-virt -v`:
- [systemd-detect-virt]( https://github.com/systemd/systemd/blob/df423851fcc05cf02281d11aab6aee7b476c1c3b/src/basic/virt.c#L999) known virtualization technologies values.
- [lscpu](https://github.com/util-linux/util-linux/blob/581b77da7aa4a5205902857184d555bed367e3e0/sys-utils/lscpu.c#L52) hypervisor vendors table.
Check "virtualization" on a Netdata container in GKE:
- master
```bash
NETDATA_SYSTEM_VIRTUALIZATION=hypervisor
NETDATA_SYSTEM_VIRT_DETECTION=/proc/cpuinfo
```
- this PR
```bash …
```
> fix virtualization detection when `systemd-detect-virt` is not available

- database/sqlite/sqlite_aclk_chart.c
The log entry for incoming cloud start streaming charts was not recording the requested sequence id (it would only record the current recorded sequence id as the agent knows it) 
This PR will add the requested and the local one that the agent knows (also switched a message to uppercase)
Before
```
CHARTS STREAM from 39899 t=1652593866 resets=1
CHART RESET from 39899 t=1652594228 batch=7597
Restarting chart sync from sequence 25460
```
After
```
CHARTS STREAM from 25460 (LOCAL 39899) t=1652596275 resets=1
CHART RESET from 25460 t=1652596275 batch=7602
RESTARTING CHART SYNC FROM SEQUENCE 25460
```
Add the correct requested chart sequence id from the cloud and also record the local one we have
-->
- Only logfile entries changed
> Fix the log entry for incoming cloud start streaming commands

- database/sqlite/sqlite_functions.c
- libnetdata/config/appconfig.c
- libnetdata/config/appconfig.h
This PR allows the users to configure how they want to configure sqlite for netdata.
The following section is added to `netdata.conf`:
```
[sqlite]
```
The idea behind this, is that depending of the role of a netdata agent (child, proxy, parent), users may need to change various optimization settings for sqlite.
This PR gives them the ability to do so.
> user configurable sqlite PRAGMAs

- build_external/scenarios/aclk-testing/agent_netdata.conf
- collectors/cgroups.plugin/sys_fs_cgroup.c
This option is useless/does nothing after #12778
ci
</details>
> chore(cgroups.plugin): remove "enable new cgroups detected at run time" config option

- .dockerignore
A symbolic link (`.dockerignore` -> `.gitignore`) was broken in #12313. The PR restores it. @andrewm4894, if you want to change the file, you should copy the contents of `.gitignore` and then change `.dockerignore`.
> Restore a broken symbolic link

- collectors/fping.plugin/fping.plugin.in
Bump `fping` version to [v5.1](https://github.com/schweikert/fping/releases/tag/v5.1) which contains some Netdata-related fixes.
---
The static build was updated in #12461.
Not needed.
</details>
> chore(fping.plugin): bump default fping version to 5.1

- database/sqlite/sqlite_functions.c
The options were added in #12917. @stelfrag @ktsaou not sure this PR is useful in general (for me personally - yes), feel free to close if you think we don't need the changes.
Would be nice to add support for inline comments in `netdata.conf`.
Not needed
</details>
> chore: add links to SQLite init options in the src code

- collectors/apps.plugin/apps_groups.conf
* added [keepalived](https://github.com/acassen/keepalived) to `ha` group
* added [s3cmd](https://github.com/s3tools/s3cmd) & [s5cmd](https://github.com/peak/s5cmd) tools to `aws-s3` group
* created `netmanager` group, cause `wifi` group was bemused me once - what wifi on my server? Ah, this is [NetworkManager](https://gitlab.freedesktop.org/NetworkManager/NetworkManager) 🤔
* also added [netplan](https://github.com/canonical/netplan) & [systemd-networkd](https://www.freedesktop.org/software/systemd/man/systemd-networkd.service.html#) to `netmanagers`
> collectors: apps.plugin: apps_groups: update net, aws, ha groups

- health/health_json.c
Adjust `/api/v1/alarm_count` to match `/api/v1/alarms`.
When we fill the alarms in `health_alarms2json_fill_alarms` we take into account `rrdset_is_available_for_exporting_and_alarms`. Same consideration should be taken when counting them via `health_aggregate_alarms` to match the number of `WARNING` and `CRITICAL` (when of course we don't use the `all` parameter in `/api/v1/alarms`).
Will be tested via set team to see if it fixes a discrepancy in tests. cc @dimko
> Adjust alarms count

- .github/data/distros.yml
- packaging/PLATFORM_SUPPORT.md
It went EOL upstream on 2022-05-01.
n/a
The Netdata team will no longer provide official support for Alpine Linux 3.12.
</details>
> Remove Alpine 3.12 from CI.

- database/rrd.h
- database/rrddim.c
- database/rrdhost.c
- database/rrdset.c
- database/sqlite/sqlite_aclk_chart.c
- database/sqlite/sqlite_aclk_chart.h
Fixes #12909
Fixes #12662
Adjust the dimension collected state calculation to avoid sending too many messages
when switching from collected to non collected state. 
Switching from collected to non collected state will produce a message after MIN(rrdset_free_obsolete_time, 30 * chart_update_every) seconds. This will also result in reduced network and disk I/O
- Any application monitored by apps plugin that starts and stops frequently will generate dimensions that switch from 
collected to non collected in a short period of time. 
This will generate separate messages to go to the cloud. Notice messages 
in the access.log as CHARTS SENT messages
- Apply the PR and notice less messages being generated (recorded in the metadata database and sent to the cloud)
> Adjust the dimension liveness status check

- daemon/system-info.sh
Continuing from #12938 , this PR instead reduces the timeout to the curl operations to 1 second.
The parameter `-m` however defines the max operation time. So even if connection takes place, but getting data back takes more than 1 second we could miss setting some of those variables. However if we consider agent startup time more important than those variables, then this is the correct setting. Otherwise we could consider `--connect-timeout` instead.
Check the script like in #12938. It should take much less to complete.
</details>
> Reduce timeout to 1 second for getting cloud instance info

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
- packaging/installer/methods/offline.md
This works in three steps:
1. The user creates an offline install source directory using the new `--prepare-offline-install-source` option for the kickstart script.
2. The user exposes that directory to the target system (either by copying it, or by sharing it in some other way).
3. The user runs the `install.sh` script from that directory on the target system, with whatever other install options they want to use.
The offline install source directory consists of:
- The static install archives for the selected version of Netdata (we unconditionally download all architectures at the moment because it’s simpler).
- The checksum file for the static install archives (we verify the checksums as part of creating the offline install source).
- A copy of the kickstart script that was used to …
> Add support for installing static builds on systems without usable internet connections.

- packaging/installer/netdata-updater.sh
Minor fix and improvement of netdata-updater.sh script
1. Added missing warning() function
2. Added Alma and Rocky distros as CentOS compatibility distro
Not needed.
I'm using Netdata with [rockylinux ](https://rockylinux.org/) and noticed that netdata-updater.sh throws errors like that
```
/etc/cron.daily/netdata-updater:
/tmp/netdata-updater-DxSyUpT6B8/netdata-updater.sh: line 729: warning: command not found
```
</details>
> Fix and improve netdata-updater.sh script

- packaging/installer/kickstart.sh
Autodetect channel (nightly or stable) for specific version of netdata.
If passed `--stable-channel` flag will be ignored.
Install specific version of netdata with `kickstart.sh --install-version`, even if version is only for nightly or stable channel the script should autodetect channel and install netdata with the specific version without issues.
</details>
> Autodetect channel for specific version

- libnetdata/libnetdata.c
- libnetdata/popen/popen.c
This PR tries to prevent the variable `command_to_be_logged` from overflowing. If it happens, it can result in corruption and random crashes.
I believe this is the crash reported in #12880.
The analytics commands tend to be more than 2048 bytes that the variable `command_to_be_logged` is defined. During tests the crash is pretty reproducible when analytics tries to execute the external script with many parameters that span more than 2048 bytes. It is more evident in FreeBSD/arm.
The crash is actually reported in line https://github.com/netdata/netdata/blob/4616491f1a2561285197126fe4683edc71001455/daemon/analytics.c#L1018 but actually is caused by previous corruption.
With either this patch, or by using `popen` instead of `mypopen`, I could no longer trigger the crash.
Try it if possible …
> Prevent command_to_be_logged from overflowing

- collectors/plugins.d/pluginsd_parser.c
- database/rrd.h
- database/rrddim.c
Use a flag on the dimension to "cache" the hidden state of the dimension that was stored last in the database to avoid updating it needlessly.
- The dimension count in the database containing the "hidden" option should be the same before and after this PR
- connecting to the `netdata-meta.db` using e.g the sqlite3 CLI and running 
`select count(*) from dimension where options = "hidden";` should return the same count of dimensions before and 
after running this PR.
You can even do an 
`update dimension set options = null where options = "hidden";` 
and restart the agent. The count of dimensions should be the same.
> Optimize the dimensions option store to the metadata database

- database/sqlite/sqlite_aclk_chart.c
- database/sqlite/sqlite_aclk_chart.h
The payload existence test done during the queue_dimension_to_aclk impacts performance of the metrics collection
This PR will defer the check to the ACLK sync thread
- Improvement of https://github.com/netdata/netdata/pull/12933
> Defer the dimension payload check to the ACLK sync thread

- database/sqlite/sqlite_functions.c
Perform a cleanup during startup on the chart_hash and chart_hash_map tables. 
In a following PR this will also happen while the agent is running
- If there are stale entries, restarting the agent will remove them. Check the entries in those tables before and after applying the PR
`select count(*) from chart_hash;`
`select count(*) from chart_hash_map;`
> Cleanup chart hash and map tables on startup

- collectors/statsd.plugin/statsd.c
Ancient bug in statsd SETs.
Passing a NULL as the value to the dictionary means the comparison for NULL on dictionary_get() is always NULL.
Yes, I know... since 2017...
> statsd sets should count unique values

- daemon/system-info.sh
We need this because we don't query Cloud instance metadata for bare metal hosts:
https://github.com/netdata/netdata/blob/675bd3e01a0366610b2a82cbca22fbf2489ca5cf/daemon/system-info.sh#L434-L436
For virtualization detection we use:
- `systemd-detect-virt`
- `lscpu`
- `dmidecode`
If none of those commands are available on the system we shouldn't assume that the host is a bare-metal host.
---
Also, this PR adds virtualization detection for FreeBSD using `sysctl kern.vm_guest` thx to @cpipilas 
Run updated system-info script on:
- bare-metal host
- qemu vm
- freebsd vm on AWS
- linux vm on GCP (k8s host)
and check the output (virtualization and cloud_* data).
---
@cpipilas I think after this PR a lot of "bare metal" hosts will appears as "unknown" on the Cloud. But that is closer to the …
> fix: keep virtualization unknown if all used commands are not available

- database/engine/rrdengine.h
- database/engine/rrdengineapi.c
I noticed that `rrdeng_load_metric_next()` was way too heavy. Using `perf top` while stressing netdata, I found out that `rrdeng_load_metric_next()` was about 5 times heavier than `unpack_storage_number()`.
In this PR, `rrdeng_load_metric_next()` is split into 2 functions:
1. `rrdeng_load_metric_next()` that fetches the next metric
2. `rrdeng_load_page_next()` that is called by the above when a new page needs to be loaded
The interesting part was in the following code:
```c
entries = page_length / sizeof(storage_number);
if (entries > 1) {
usec_t dt;
dt = (page_end_time - descr->start_time) / (entries - 1);
current_position_time = descr->start_time + position * dt;
} else {
current_position_time = descr->start_time;
}
```
The code above calculates the time of the current point in the …
> cleanup and optimize rrdeng_load_metric_next()

- streaming/rrdpush.c
- streaming/sender.c
This PR changes a bit the behavior introduced with https://github.com/netdata/netdata/pull/12866.
In case of a parent agent denying access, the child would mark this destination permanently as don't retry it. However, if the parent would change it's config and restarted, the child would no longer attempt to connect without a restart.
This PR changes this logic, as when this happens, the destination will be marked to be skipped for just one loop, but will be retried on the next ones.
**Many many thanks to @dimko for finding this!!**
We'll test with @dimko on his setup to verify it.
For a local test, setup a parent with no stream.conf or with a stream.conf with different key than the child. Setup the child with proper stream to that parent. Start the parent and the child and wait for a bit. …
> Don't permanetly disable a destination because of denied access

- web/api/queries/query.c
1. move number unpacking close to metric_next
2. fix `value` variable shadowing by introducing the `group_value` variable
3. don't miss group flags when iterating at the inner loop
> query engine optimizations and cleanup

- collectors/apps.plugin/apps_plugin.c
`cpu_system` and `cpu_guest` charts have the same context - `cpu_system`.
https://github.com/netdata/netdata/blob/528378baf9f6f844790f16d069e7a7ad7a9a8e40/collectors/apps.plugin/apps_plugin.c#L3764
https://github.com/netdata/netdata/blob/528378baf9f6f844790f16d069e7a7ad7a9a8e40/collectors/apps.plugin/apps_plugin.c#L3771
This PR changes the` cpu_guest` chart context.
</details>
> chore(apps.plugin): change cpu_guest chart context

- packaging/installer/kickstart.sh
Fixes: #12960
Manually test new `if` condition in the command line.
</details>
> fix(kickstart.sh): handle the case when `tput colors` doesn't return a number

- packaging/installer/functions.sh
- packaging/installer/netdata-uninstaller.sh
When Netdata is running in a docker container, using the host PID namespace is a requirement for associating network interfaces with cgroups.
It means that our installer/uninstaller scripts kill all Netdata containers running on the host (a pretty common setup when developing: Netdata installed on the host + a bunch of containers).
Run the installer, and check that docker containers don't get restarted.
</details>
> fix: don't kill Netdata PIDs if successfully stopped Netdata

- database/rrdset.c
If ENABLE_ACLK is not defined and ENABLE_NEW_CLOUD_PROTOCOL is defined, there will be a ```unused variable``` compile warning.
I try to modify code to remove this compile warning, Pls help to check it. Thanks
N/A
> modify code to resolve compile warning issue

- daemon/global_statistics.c
`update_heartbeat_charts()` is called inside the loop, every second. The `heartbeat` chart is then created every time. This PR changes it so that it is a static variable, and behaves as other similar charts.
Unless there is a specific reason for that behavior, it is perhaps better to turn it into a static one.
Make sure the `heartbeat` chart works as before the PR.
</details>
> Make heartbeat a static chart

- database/engine/rrdengine.h
- database/engine/rrdengineapi.c
- libnetdata/storage_number/storage_number.c
- libnetdata/storage_number/storage_number.h
- web/api/queries/average/average.c
- web/api/queries/average/average.h
- web/api/queries/des/des.c
- web/api/queries/des/des.h
- web/api/queries/incremental_sum/incremental_sum.c
- web/api/queries/incremental_sum/incremental_sum.h
- web/api/queries/max/max.c
- web/api/queries/max/max.h
- web/api/queries/median/median.c
- web/api/queries/median/median.h
- web/api/queries/min/min.c
- web/api/queries/min/min.h
- web/api/queries/query.c
- web/api/queries/rrdr.h
- web/api/queries/ses/ses.c
- web/api/queries/ses/ses.h
- web/api/queries/stddev/stddev.c
- web/api/queries/stddev/stddev.h
- web/api/queries/sum/sum.c
- web/api/queries/sum/sum.h
Minor query engine optimizations that give about 5% additional performance increase.
Each commit is doing one thing, so it is easier to check it by reviewing the individual commits.
1. `rrdeng_load_metric_next()` was doing 2 calculations about page size and current timestamp for every point, which are now cached for the lifetime of each page.
2. `unpack_storage_number()` is now inlined (it is defined in the header file)
3. the grouping functions were doing a check for every point to verify the number is not `NAN`, but the same check was also done at the query engine.
Fixed also a discrepancy in the way the grouping functions were created and destroyed. Nothing about performance. Just a tiny issue for uniformity.
> Faster queries

- database/rrd.h
- database/rrdset.c
Only clear the RRDSET_FLAG_UPSTREAM_EXPOSED chart flag if the chart metadata has changed
- Handle change of units as well
- There is already code that detects chart metadata change, so the RRDSET_FLAG_UPSTREAM_EXPOSED will be cleared only when such a change is detected
> Don't expose the chart definition to streaming if there is no metadata change

- database/rrd.h
- database/rrdhost.c
- database/rrdset.c
- streaming/receiver.c
Fixes #12939
In some cases, especially when an agent is under load, the `rrdset_check_obsoletion` might kick in sooner than needed (even with a 2 minute delay). If it does, it might mark charts as obsolete when in fact their complete definition has not yet been transmitted in full. Moreover the check for cleaning up obsolete charts might as well be triggered.
This PR extends the time for the `rrdset_check_obsoletion` every time a chart definition is received. It will then trigger the check 2 minutes after the last definition.
There's also a check for `rrdset_last_entry_t` being 0 not to trigger any check on that chart. This will make sure the check is not run for the chart since most likely the chart is still being defined.
There are also 2 new timestamps for the host structure. …
> Delay children chart obsoletion check

- packaging/installer/kickstart.sh
This ensures that the formatting is done properly.
Differences can be observed by simply running the script before and after the changes.
Warnings listed at the end of execution of the kickstart script will be properly formatted.
</details>
> Use printf instead of echo for printing collected warnings in kickstart.sh.

- coverity-scan.sh
Coverity Scan is broken, due to the fact that the folder name (after extraction from tar.gz file) is not matching the file name.
Allow github action for coverity scan to complete, and observe that it picked up the correct path for the executable.
> Autodetect coverity install path to increase robustness

- .github/data/distros.yml
- packaging/PLATFORM_SUPPORT.md
SSIA
As of mergint this PR, Alpine 3.16 will be officially supported by the Netdata team, and Alpine 3.15 will be demoted to the intermediate support tier.
</details>
Associated PR updating bases for the Docker images and static builds: https://github.com/netdata/helper-images/pull/165
> Add Alpine 3.16 to CI and platform support document.

- coverity-scan.sh
Fix for COVERITY_PATH when it was added (wrongly) to include the INSTALL_DIR into PATH
run ./coverity-scan.sh locally to make sure it works as expected
> fix COVERITY_PATH added with INSTALL_DIR into PATH

- health/health.c
- health/notifications/alarm-notify.sh.in
Together with changes from the cloud, it should fix #12376.
If the alert is raised by a parent for a child, it will also pass the child's machine guid to the constructed link for the `Go to chart` button. It should help create a correct redirect to view the child's chart.
Will be tested with the cloud.
</details>
> Pass the child machine's guid to the goto_url link

- packaging/installer/netdata-updater.sh
We attempt to update repository metadata twice in the updater script when updating a system that was installed using native packages, once before updating the repository config packages, and once after updating them.
The first attempt was properly guarded so that it only happened if the package manager supported doing so, but the second attempt would run unconditionally, thus causing issues for YUM-based systems (which do not support explicitly updating repository metadata independent of other operations).
Attempt to run the updater script on a CentOS 7 system which has netdata installed using native packages.
Without the changes in this PR, it will crash after updating the repository config packages.
With the changes in this PR, it will run correctly.
Fixes: #12953 
<details> …
> Only try to update repo metadata in updater script if needed.

- .github/scripts/build-static.sh
- .github/scripts/get-static-cache-key.sh
- .github/workflows/build.yml
- packaging/makeself/build-static.sh
- packaging/makeself/functions.sh
- packaging/makeself/jobs/20-openssl.install.sh
- packaging/makeself/jobs/50-bash-5.1.16.install.sh
- packaging/makeself/jobs/50-curl-7.82.0.install.sh
- packaging/makeself/jobs/50-fping-5.1.install.sh
- packaging/makeself/jobs/50-ioping-1.2.install.sh
- packaging/makeself/uname2platform.sh
This adds support for build caching of the components used in our static builds that change only infrequently (OpenSSL, bash, cURL, fping, and ioping). This consists of two parts:
- Support in the static build code itself for caching these components. Cached data is stored in `artifacts/cache` in the build environment, is scoped by architecture, and is keyed by the version of the component itself.
- Use of `actions/cache@v3` in CI to cache this data across CI builds. Keying of these caches is based on the hash of the list of packages and versions in the build environment and the contents of the files responsible for actually building these components.
CI on this PR works correctly.
Effective speedup in CI is roughly 50%, based on comparing static build jobs in …
> Cache invariant components in static builds to reduce build times.

- claim/claim.c
Coverity issue 378598 is:
> CID 378598 (#1 of 1): Thread deadlock (ORDER_REVERSAL)5. lock_order: Calling appconfig_get acquires lock netdata_rwlock_t.rwlock_t while holding lock rrdhost.aclk_state_lock
In https://github.com/netdata/netdata/blob/5c5cf7ea4a621657cfc4bcbd302c9fda7098249d/claim/claim.c#L152
Moving `appconfig_get(&cloud_config, CONFIG_SECTION_GLOBAL, "cloud base url", DEFAULT_CLOUD_BASE_URL);` before `rrdhost_aclk_state_lock(localhost);` should be okay and not cause trouble.
If I understand correctly, call to `appconfig_get` is that so the relavant cloud.conf config will be created if it doesn't exist?
Should not break any claiming procedure.
</details>
> Fix coverity issue 378598

- collectors/statsd.plugin/statsd.c
There is a compilation warning introduced in #12980
```text
collectors/statsd.plugin/statsd.c: In function 'statsd_get_metric_type_and_id':
collectors/statsd.plugin/statsd.c:1600:14: warning: 's' may be used uninitialized [-Wmaybe-uninitialized]
1600 |         *s++ = '\0';
|         ~~~~~^~~~~~
collectors/statsd.plugin/statsd.c:1592:11: note: 's' was declared here
1592 |     char *s;
|           ^
```
The PR fixes it.
> Initialize a pointer and add a check for it

- aclk/aclk.c
- database/sqlite/sqlite_aclk_alert.c
Right now, "orphan" removed events are queued to go to cloud either when the agent starts, or after a health reload. This also includes the events for a child's database as well as the parent's in a parent - child setup.
The removed events are triggered to go out after a couple of health loops to ensure only those left without an update really go out.
However, if a child delays connection to a parent after a restart, it could miss the window of opportunity when the removed alerts are queued. This PR will instead stop trying to do it on agent startup and instead will trigger when the health log is exchanged with the cloud. Again the actual queuing will happen after a couple of health loops after that trigger.
We need a claimed parent for this. On a single setup startup there should be a …
> Trigger queue removed alerts on health log exchange with cloud

- database/sqlite/sqlite_functions.c
Fixes coverity issue 
`378600 [Unchecked return value]`
- Coverity issue should be gone
> Check return value and log an error on failure

- aclk/aclk_query.c
- web/api/queries/rrdr.c
```   	
CID 378617 (#1 of 1): Result is not floating-point (UNINTENDED_INTEGER_DIVISION)
CID 378615 (#1 of 1): Data race condition (MISSING_LOCK)
```
- Coverity warning should disappear
> Fix coverity issue 378617,378615

- ml/Dimension.cc
Ideally, we'd log such cases but this is not currently feasible because
we have to process thousands of dimensions per second.
Testing requires merging this PR and testing it on staging/production
in order to check whether anomaly bit values get stuck on regular dimensions.
AFAICT, Fixes https://github.com/netdata/netdata/issues/12967
> Treat dimensions as normal when we don't have enough/valid data.

- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
The condition for checking netdata_exit was wrong so basically it would just attempt to run the sqlite3_step command only once.  
This PR will properly check the `netdata_exit` and also add a retry count up to SQL_MAX_RETRY (future PRs will add more checks)
- Should be obvious but you can try the following
- Start the agent
- Open the metadata database using `sqlite3`  (the netdata-meta.db file) and do
```
BEGIN TRANSACTION; 
UPDATE chart SET chart_id = chart_id LIMIT 1;
```
Notice there is no `COMMIT;` so this will lock the database. Notice that commands that fail do not get a retry count
-  Apply the PR and retest, you can see attempts similar to 
```
2022-05-31 10:17:01: netdata ERROR : HEALTH : Failed to insert/update, rc = 5 -- attempt 1
2022-05-31 10:17:01: netdata ERROR : HEALTH : …
```
> Fix the retry count and netdata_exit check when running an sqlite3_step command

- web/api/formatters/json_wrapper.c
- web/api/formatters/json_wrapper.h
- web/api/formatters/rrd2json.c
- web/api/formatters/rrd2json.h
- web/api/web_api_v1.c
This is the first part of enhancing the data API call to include additional information that will be used
by the cloud to make dashboard chart refreshes faster. 
The additional metadata will be available if both `show_dimensions=1` and `option=jsonwrap` is passed.
The output in that case will include the following fields
`full_dimension_list` array of `2-element array` with the dimension id and dimension name
`full_chart_list` array of `2-element array` with the chart_id and chart name
`full_chart_labels`  array of `2-element array` with the chart_label_key and chart_label_value
Example:
```
"full_dimension_list": [["softirq","softirq"],["irq","irq"],["iowait","iowait"],["guest","guest"],["system","system"],["user","user"],["nice","nice"],["guest_nice","guest_nice"],["steal","steal"],["idl …
```
> Add additional metadata to the data response

- collectors/ebpf.plugin/ebpf.c
- collectors/ebpf.plugin/ebpf_apps.c
- collectors/ebpf.plugin/ebpf_oomkill.c
- collectors/ebpf.plugin/ebpf_process.c
- libnetdata/ebpf/ebpf.c
This PR is fixing some issues we had when `apps.plugin` was disabled:
- When integration with `apps` plugin was set `ebpf.plugin` was crashing with errors like:
```sh
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/opt/netdata/usr/libexec/netdata/plugins.d/ebpf.plugin 1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000563b3cbafef1 in clean_vfs_pid_structures () at collectors/ebpf.plugin/ebpf_vfs.c:60
60	        freez(vfs_pid[pids->pid]);
[Current thread is 1 (Thread 0x7f78d1d83780 (LWP 1358834))]
(gdb) bt
#0  0x0000563b3cbafef1 in clean_vfs_pid_structures () at collectors/ebpf.plugin/ebpf_vfs.c:60
#1  0x0000563b3cb99699 in ebpf_exit (sig=sig@entry=0) at collectors/ebpf.plugin/ebpf.c:248
#2  0x0000563b3cb9a675 in …
```
> Fix disabled apps (ebpf.plugin)

- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_aclk.h
- database/sqlite/sqlite_aclk_alert.c
- database/sqlite/sqlite_aclk_chart.c
- database/sqlite/sqlite_aclk_chart.h
- database/sqlite/sqlite_aclk_node.h
In a parent - child setup with many children, the retention calculation could happen for all the children at the same time which could cause a high load on the database which stores the metadata. In addition the retention process would block the event loop which is also not good. 
This PR will schedule the retention calculation to a worker thread and also make sure there is just one retention calculation running at a time (hence spread the load). It will also try not to stress the database too much by stopping the retention check if the dimensions that need to be deleted are more than 500
- Run a parent - child setup with several children (parent claimed to the cloud)
- Observe the `workers aclk host sync` charts under `netdata`
- About 3 minutes after the parent restart you will notice …
> Schedule retention message calculation to a worker thread

- libnetdata/dictionary/dictionary.c
Fix dictionary crash walkthrough empty
> Fix dictionary crash walkthrough empty

- libnetdata/dictionary/dictionary.c
- libnetdata/dictionary/dictionary.h
> dictionary improvements

- database/rrdcalc.c
Fixes #12994 
This PR adds a check during alerts linking with charts for the host's labels. 
The alert will be linked to the chart only if all host labels are matched to the ones in the alert.
The check comes during charts linking to alerts. By that time, labels from the child _should_ have already been propagated to the parent.
1) Setup a parent and a child.
2) Pick an alert on the parent that would normally be linked for the child.
3) Find a child label, e.g. `_system_cores = 4`
4) Add this host label to the alert's `host label:` parameter, sligthly different, e.g. `_system_cores = 3`.
5) Without this PR notice that the alert appears in `/host/child/api/v1/alarms?all`.
6) Repeat the same with this PR. The alert should be missing.
7) Try various combinations with e.g. 2 host labels. …
> Check for host labels when linking alerts for children

- web/api/health/health_cmdapi.c
Frees the `jsonb` buffer.
> CID 378625 (https://github.com/netdata/netdata/issues/1 of 1): Resource leak (RESOURCE_LEAK)15. leaked_storage: Variable jsonb going out of scope leaks the storage it points to.
> Fix coverity 378625

- collectors/cgroups.plugin/cgroup-name.sh
Quite by accident, I noticed some cgroup charts have wrong `k8s_cluster_name` value in our K8s cluster:
> "k8s_cluster_name": "namespace=",
The following `IFS= read...` lines should be the same:
https://github.com/netdata/netdata/blob/446ac867e414da2c920e8ea7dbc9f7c9a7faebd1/collectors/cgroups.plugin/cgroup-name.sh#L260-L264
As you can see we read `k8s_cluster_name` from the wrong file in the `else` branch
---
Not needed.
</details>
> fix(cgroup.plugin): read k8s_cluster_name label from the correct file

- packaging/installer/kickstart.sh
This makes temporary directory creation idempotent, and ensures it’s invoked in each place that needs it. It also tidies up the cleanup code so that it only tries to remove the temporary directory if one was created.
Easily tested by trying to uninstall or do a clean reinstall with the kickstart script on a system that does not have a usable uninstaller script locally.
Without this PR, the uninstall process will try to use `/` as a temporary directory to download the uninstaller script and fail as a result if not run as `root`.
With this PR, the uninstall process will work correctly.
Uninstalls and clean reinstalls with the kickstart script work correctly again as a non-root user.
</details>
> Fix handling of temp directory in kickstart when uninstalling.

- CMakeLists.txt
- Makefile.am
- aclk/README.md
- aclk/aclk.c
- aclk/aclk.h
- aclk/aclk_alarm_api.c
- aclk/aclk_api.c
- aclk/aclk_api.h
- aclk/aclk_query.c
- aclk/aclk_query_queue.c
- aclk/aclk_query_queue.h
- aclk/aclk_rx_msgs.c
- aclk/aclk_tx_msgs.c
- aclk/aclk_tx_msgs.h
- aclk/schema-wrappers/node_creation.h
- streaming/receiver.c
Allows usage of the new MQTT 5 custom client. https://github.com/netdata/netdata/issues/12481
By default disabled for now until it is polished and stability is tested well enough.
Main benefit -> removed max publish size limit. The published data don't all have to fit into a fixed size buffer anymore.
As a result also memory usage is reduced.
Currently implements only the bits and pieces of MQTT5 which we actually use. In future more will be implemented (topic aliases might be useful for us).
Following PRs need to implement smarter query thread that actually throttles when there is too much data pending.
Absolutely most important piece to test is this by accident doesn't break the current MQTT by setting `mqtt5 = no`.
Then you can go ahead and have fun with this new implementation
``` …
```
> Allow usage of new MQTT 5 implementation

- .github/data/distros.yml
- .github/scripts/pkg-test.sh
- netdata.spec.in
- packaging/PLATFORM_SUPPORT.md
- packaging/installer/dependencies/centos.sh
- packaging/installer/install-required-packages.sh
This adds RHEL 9 and Alma Linux 9 to CI, packaging, and our official support list.
n/a
Fixes: #13057 
Once merged, Alma Linux 9 and RHEL 9 will be officially supported by the Netdata Agent.
</details>
> Added Alma Linux 9 and RHEL 9 support to CI and packaging.

- ml/Config.cc
Update default value for "host anomaly rate threshold"
The current default value for "host anomaly rate threshold" of 0.01 (1%) is too sensitive and background nosie levels of anomaly rate have been anecdotally found to been in the <2% range. Therefore this PR proposes updating the default value to 2% to not detect spurious anomaly events.
Test on staging once build with change is available to confirm expected behavior.
- Which area of Netdata is affected by the change? 
-- **Anomaly Advisor**
- Can they see the change or is it an under the hood? If they can see it, where? 
-- **The change is under the hood, but the visible change for users will be a reduction in the number of anomaly events**
- How is the user impacted by the change? 
- What are there any benefits of the change? 
-- …
> Update default value for "host anomaly rate threshold"

- .github/data/distros.yml
- packaging/PLATFORM_SUPPORT.md
To be merged when it goes EOL on 2022-06-07.
n/a
End of official support for Fedora 34.
</details>
> Remove Fedora 34 from CI and package builds.

- packaging/installer/netdata-updater.sh
This temporarily disables updates using the netdata-updater.sh script for static installs. This is being done to prevent any further issues caused by a bug we have identified in the static installer code which was causing automatic updates to be unconditionally disabled.
Once the aforementioned bug is fixed, this PR will be reverted to re-enable updates for static installs.
With the code in this PR, attempting to run the updater script on a system with a static install should print a warning informing the user that updates have been temporarily disabled and then exit without updating.
> Temporarily disable updates for static builds.

- packaging/installer/functions.sh
- packaging/makeself/install-or-update.sh
This was causing the updater to be unconditionally disabled on static builds, and we don’t actually _need_ any of it anymore since we’ve already decoupled the auto-update handling state from the installation process (in fact, this should have been removed then, but it got missed somehow).
1. Prepare a static build using the code in this branch by running `packaging/makeslf/build-static.sh <arch>` from the root of the repository (where `<arch>` is one of `x86_64`, `armv7l`, `aarch64`, or `ppc64le` as appropriate to the system you will be testing on, note that this requires a working Docker install on the build system). This will produce a static build archive in the `artifacts` directory.
2. On the test system, run the kickstart script as outlined in our documentation, but add the option …
> Remove unnescesary ‘cleanup’ code.

- packaging/installer/netdata-updater.sh
Reverts netdata/netdata#13100
Fixes: https://github.com/netdata/netdata/issues/13102 (as the last step in doing so).
> Re-enable updates for systems using static builds.

- .github/data/distros.yml
Expected release date 2022-06-08.
CI jobs are created on this PR and pass correctly.
Merging of this should be delayed until 2022-05-21, when the final release build is completed, at which point CI jobs on this PR should be manually re-run to confirm that everything is working.
Once merged we will probably see regular failures on the packaging jobs on nightlies as Package Cloud will probably take way too damn long yet again on adding support for 15.4.
Depends on https://github.com/netdata/helper-images/pull/150
> Add openSUSE Leap 15.4 to CI and package builds.

- daemon/system-info.sh
ssia
It will be tested by @cpipilas 
```
wget -q -O system-info.sh https://raw.githubusercontent.com/ilyam8/netdata/fix_virtualization_detection_on_freebsd/daemon/system-info.sh; sh system-info.sh | grep -i virt; rm system-info.sh
```
</details>
> fix virtualization detection on FreeBSD

- daemon/main.c
- database/metric_correlations.c
- database/metric_correlations.h
- health/health.c
- libnetdata/storage_number/storage_number.h
- web/api/badges/web_buffer_svg.c
- web/api/formatters/json_wrapper.c
- web/api/formatters/json_wrapper.h
- web/api/formatters/rrd2json.c
- web/api/formatters/rrd2json.h
- web/api/netdata-swagger.json
- web/api/netdata-swagger.yaml
- web/api/queries/query.c
- web/api/queries/query.h
- web/api/queries/rrdr.c
- web/api/queries/rrdr.h
- web/api/web_api_v1.c
- web/api/web_api_v1.h
- web/server/web_client.h
This PR improves the performance of metrics correlations by a factor of 73.
The biggest problem of it was this function:
```c
int find_index(double arr[], long int n, double K, long int start)
{
for (long int i = start; i < n; i++) {
if (K<arr[i]){
return i;
}
}
return n;
}
```
It has been replaced with a binary search function, which alone saved 75% of CPU resources required.
Then the next big problem was comparisons of `double` numbers. So, I multiplied the `double` pair diffs by 1 million (to have 6 digits precision) and divided the final `min` and `max` by 1 million, so that we only compare `long int` numbers. This saved 15% more (compared to the original).
Then a number of additional optimizations have been done to optimize the whole logic further:
1. The need to replace NANs with …
> 73x times faster metrics correlations at the agent

- .github/scripts/check-updater.sh
- .github/scripts/ci-support-pkgs.sh
- .github/scripts/run-updater-check.sh
Following changes are implemented:
1. Improve CI coverage to make sure autoupdate is still enabled, after netdata upgrade.
2. Fixed unknown command `pidof` during CI.
Verify the new testcase exists in the updater-check job in the build.yml workflow.
The log should show something like:
`
>>> Updating Netdata...
>>> Checking if update was successful...
Check netdata version after update ...  [ OK ]
Check autoupdate still enabled after update ... [ OK ]
🎉 All Done!`
The errors related to missing `pidof` command should be gone as well.
We had an issue recently where the updater broke the autoupdate process, and we needed to CI coverage, to prevent this from happening in the future.
Issue: https://github.com/netdata/netdata/issues/13105
> Ci coverage

- .github/scripts/prepare-release-base.sh
This fixes a single character omission typo in the release prep script.
The typo itself was causing a workflow command issued by the script to not actually be processed, which in turn meant that minor releases would not end up creating a release branch like they should.
n/a
> Fix typo in release base prep script.

- database/metric_correlations.c
- database/rrdlabels.c
- web/api/formatters/rrd2json.c
All of them are false alarms, but anyway let's fix them
```
*** CID 379136:  Control flow issues  (DEADCODE)
/database/rrdlabels.c: 971 in rrdlabels_unittest_add_a_pair_callback()
965         }
966         else if(value == NULL || t->expected_value == NULL) {
967             fprintf(stderr, "value is wrong, found \"%s\", expected \"%s\"", value?value:"(null)", t->expected_value?t->expected_value:"(null)");
968             t->errors++;
969         }
970         else if(strcmp(value, t->expected_value) != 0) {
>>>     CID 379136:  Control flow issues  (DEADCODE)
>>>     Execution cannot reach the expression ""(null)"" inside this statement: "fprintf(stderr, "values don...".
971 …
```
> fixed coveriry 379136 379135 379134 379133

- parser/parser.c
```
n function 'find_keyword',
inlined from 'parser_action' at parser/parser.c:261:9:
parser/parser.c:16:14: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
16 |     *keyword = '\0';
|     ~~~~~~~~~^~~~~~
parser/parser.c: In function 'parser_action':
parser/parser.c:241:10: note: at offset 1024 into destination object 'command' of size 1024
241 |     char command[PLUGINSD_LINE_MAX];
|          ^~~~~~~
```
gcc version 12.1.0 (GCC)
> buffer overflow detected by the compiler

- aclk/aclk.c
- aclk/aclk_stats.c
- aclk/aclk_stats.h
Adds info about bytes written/read from OpenSSL_write and openssl_read. This will also be used in following PRs to react to situations where more data is produced that can be sent. For example:
- send low priority data only when connection idle (or near idle) e.g. aclk events
- reduce amount of children we expose to cloud if we see the link cannot handle it anymore, instead of kicking random messages
</details>
> Statistics on bytes recvd and sent

- collectors/python.d.plugin/mongodb/mongodb.chart.py
Checking #13134 I noticed that python.d/mongodb module hangs for 30 seconds. 
The reason is that [`serverSelectionTimeoutMS`](https://pymongo.readthedocs.io/en/stable/api/pymongo/errors.html?highlight=serverselectiontimeoutms#pymongo.errors.ServerSelectionTimeoutError) is not set.
> If there is no suitable server for an operation PyMongo tries for serverSelectionTimeoutMS (default 30 seconds) to find one, then throws this exception.
The following check no longer works for pymongo4+ ([v4 breaking changes](https://pymongo.readthedocs.io/en/stable/changelog.html#breaking-changes-in-4-0))
https://github.com/netdata/netdata/blob/6bed6b1519b2937b1b58324deb9243480a68eded/collectors/python.d.plugin/mongodb/mongodb.chart.py#L753-L754
This PR fixes the problem. 
Tested manually in a docker …
> fix(python.d/mongodb): set `serverSelectionTimeoutMS` for pymongo4+

- collectors/python.d.plugin/python_modules/urllib3/_collections.py
- collectors/python.d.plugin/python_modules/urllib3/util/selectors.py
Fixes: #13134
> **Warning**
> The correct fix is to vendor a recent version of urllib3.
This is a quick fix that can go into the nightly release.
---
```py
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import Mapping
<stdin>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
```
Netdata docker image python version: 
```cmd
$ docker exec ndtest python3 --version
Python 3.10.4
``` 
Build a docker image, run python.d.plugin in debug mode, and ensure there are no "cannot import name 'Mapping' from 'collections'" errors.
<details> <summary>For users: How …
> fix(python.d): urllib3 import collection for py3.10+

- collectors/diskspace.plugin/plugin_diskspace.c
`stat()` and `statvfs()` calls are blocking. That causes gaps in diskspace charts, especially if there are network filesystems mounted to a system. We will check for the time needed to process mountpoints and if the calls are slow, process the "slow" mountpoints in a separate thread with a much longer `update_every`.
Fixes #10150
1. Insert `if (!strcmp(mi->mount_point, "/tmp") || !strcmp(mi->mount_point, "/run")) sleep(4);` before or after `stat()`, `statvfs()` calls.
2. Check if `disk_space.` and `disk_inodes.`charts for `/tmp` and `/run` mountpoints work and `update_every` is more than 5 for them.
> Use a separate thread for slow mountpoints in the diskspace plugin

- database/metric_correlations.c
- web/api/netdata-swagger.json
The aim of this PR is to use `ks2` as the default for metric correlations instead of `volume`. 
[Here](https://drive.google.com/file/d/124G-THUZlhQNTXeQzm8hZubfmsweHZKx/view?usp=sharing) is a video of some examples why i think ks2 should be the default over volume.
Basically, ks2 will capture a wider range of changes than volume will be able to. As such just using volume will bias towards a subset of changes that the ks2 algo will capture anyway. 
So while i like that we should have volume as a dropdown option in the FE and it will be the default at first for cross node MC where we have a larger amount of selected nodes. I don't think it should be the default and replace ks2.
</details>
> use ks2 as MC default

- libnetdata/onewayalloc/onewayalloc.c
gcc 12 makes netdata crash if memory allocations that include function pointers are not 16-byte aligned.
According to GNU documentation, on 64-bit systems, malloc returns 16-byte aligned memories (8-byte on 32-bit systems).
So, this fix makes OWA align to `sizeof(void *) * 2` to comply with the GNU libraries.
> fix crashes due to misaligned allocations

- daemon/main.c
- database/engine/rrdengine.c
- database/engine/rrdengineapi.c
- database/engine/rrdengineapi.h
Fixes #13133
Add a config option `page cache uses malloc` to switch from using mmap to malloc. In some cases mmap will fail whereas malloc works just fine. 
In in the netdata.conf `[global]` section
add the following so that the agent will use malloc instead of mmap (the default is `no`) 
`page cache uses malloc = yes`
- Agent should work as this change affects only how the metric page is allocated / deallocated
> Add an option to use malloc for page cache instead of mmap

- collectors/COLLECTORS.md
Features now added on GitHub.
Add links to how to develop own collectors.
Replaces https://github.com/netdata/netdata/pull/13149
> Update docs on what to do if collector not there

- daemon/global_statistics.c
- database/engine/pagecache.c
- database/engine/rrdengine.h
- database/engine/rrdengineapi.c
- Remove the pinned page reference as it is not used (reduce a bit the memory needed per collected metric)
- Remove it from the page cache statistics calculation
The prev_used handle was not used
- Agent should work as expected. You will notice a difference in the calculation of dbengine statistics (dbengine_ram) under the netdata section for `cache` and `collectors`. The collectors will now report half the amount of the memory used as they take into account only the active collected page as a page get filled and moves to the page cache. The memory will now be reported under `cache` 
</details>
> Remove pinned page reference

- collectors/apps.plugin/apps_groups.conf
Adds a couple more binaries to the build group. The names are ubiquitous enough to have them in the build group.
Install the agent, use one of the binaries added and check the apps.cpu chart.
> Add cargo/rustc/bazel/buck to apps_groups.conf

- ml/Config.cc
This PR reverts the default for `host anomaly rate threshold` to `0.01` from `0.02`. 
The default of this param is 1% because the default of `dimension anomaly score threshold` is `0.99`. This means that typically around 1% of metrics will randomly (naturally) by flipping between anomalous and normal. This is why when the node anomaly rate is above 1% we consider a node level anomaly.
</details>
> revert to default of `host anomaly rate threshold=0.01`

- .github/workflows/release.yml
Nightly builds are triggered even when there are no changes in master, causing unnecessary development build artefacts created.
The script [prepare-release-base.sh](https://github.com/netdata/netdata/blob/master/.github/scripts/prepare-release-base.sh) works correctly, but the conditions were wrong.
Tested locally by running the workflow with dispatch option, and verifying it did not trigger the builds.
This PR fixes the issue described in https://github.com/netdata/internal/issues/73
> fix conditions for nightly build triggers

- daemon/main.c
- database/rrdlabels.c
Fix the unit test after the latest changes in the sanitization function
- Run `netdata -W rrdlabelstest` before and after the PR
> Fix labels unit test

- system/netdata.service.in
[Needed](https://github.com/netdata/netdata/issues/10044#issuecomment-1156445663) for freeimpi plugin.
<details>
<summary>CAP_SYS_RAWIO</summary>
- Perform I/O port operations ([iopl(2)](https://man7.org/linux/man-pages/man2/iopl.2.html) and [ioperm(2)](https://man7.org/linux/man-pages/man2/ioperm.2.html));
- access /proc/kcore;
- employ the FIBMAP ioctl(2) operation;
- open devices for accessing x86 model-specific registers (MSRs, see [msr(4)](https://man7.org/linux/man-pages/man4/msr.4.html));
- update /proc/sys/vm/mmap_min_addr;
- create memory mappings at addresses below the value specified by /proc/sys/vm/mmap_min_addr;
- map files in /proc/bus/pci;
- open /dev/mem and /dev/kmem;
- perform various SCSI device commands;
- perform certain operations on …
> add CAP_SYS_RAWIO to Netdata's systemd unit CapabilityBoundingSet

- collectors/freebsd.plugin/freebsd_sysctl.c
- health/health.d/ram.conf
- web/gui/dashboard_info.js
Fixes https://github.com/netdata/netdata-cloud/issues/352
`mem.available` is one of those special charts that we use in the node list in the cloud. It is however missing from FreeBSD. This PR adds it, so that it can be displayed in the cloud.
The relevant alert is also changed to use the new chart.
Compile on FreeBSD. Note the new chart, and the alerts `ram_available` and `ram_in_use` should be displaying correct values.
> Add mem.available chart to FreeBSD

- collectors/plugins.d/plugins_d.c
Avoid setting NULL with a loop (use memset) 
**callgrind reports**
Before the change 
```
4,554,049 ( 1.05%)              s++;
.               }
.           
.               // terminate the words
603,032 ( 0.14%)      j = i;
33,120,826 ( 7.63%)      while (likely(j < max_words))
41,346,952 ( 9.53%)          words[j++] = NULL;
.           
301,516 ( 0.07%)      return i;
1,507,580 ( 0.35%)  }
```
after the change
```
4,503,586 ( 1.22%)              s++;
.               }
.           
.               // terminate the words
3,597,036 ( 0.97%)       memset(&words[i], 0, (max_words - i) * sizeof (char *));
8,362,886 ( 2.26%)  => ???:0x000000000014ee00 (299,753x)
.           
299,753 ( 0.08%)      return i;
1,498,765 ( 0.40%)  }
```
Further optimizations may be possible
- It should not affect …
> Use memset to mark the empty words in the quoted_strings_splitter function

- web/api/queries/query.c
When requesting data for a stale chart it used to do all calculations relative to the last collected timestamp for the chart. This was recently changed to do all calculations on the current time (`now_realtime_sec()`) 
This would allow the chart to generate results (albeit "empty") if such a query would be done. 
This PR removes some restrictions to make this work properly, as currently there are cases where the agent will 
return a 
```
Cannot generate output with these parameters on this chart.
```
- In a parent - child setup, start both agents
- Do do a query on the parent agent requesting data for a chart of the child : eg. 
`localhost:19999/host/child/api/v1/data?chart=system.cpu`
- Stop the child, restart the parent and do again …
> Fix data query on stale chart

- libnetdata/onewayalloc/onewayalloc.c
Coverity reports:
> CID 378587 (#1 of 1): Improper use of negative value (NEGATIVE_RETURNS)9. negative_returns: size is passed to a parameter that cannot be negative. At line: (https://github.com/netdata/netdata/blob/ef7cbc0e21d9bf9afcce4a8cc977379ccf64420e/libnetdata/onewayalloc/onewayalloc.c#L55)
`size` is assigned from `OWA_NATURAL_PAGE_SIZE` which is assigned by the return of `sysconf(_SC_PAGE_SIZE);`
`sysconf` might return -1 on error. Check the value and fatal if that's the case.
Since onewayalloc is used throughout, basic test of agent is running should be enough.
</details>
> Fix coverity 378587

- collectors/proc.plugin/proc_net_dev.c
- web/gui/dashboard_info.js
This PR adds 'up' and 'down' dimensions instead of 'state'. This will allow showing the number of interfaces in the up/down states automatically on the Cloud. 
Check the "Interface Physical Link State" charts.
</details>
> feat(proc/proc_net_dev): add dim per phys link state to the "Interface Physical Link State" chart

- web/gui/dashboard_info.js
This PR adds charts description for [k8s_state](https://github.com/netdata/go.d.plugin/tree/master/modules/k8s_state#kubernetes-cluster-state-monitoring-with-netdata).
Tested using [npm run start:node-view](https://github.com/netdata/dashboard#available-scripts) (container with the dashboard on a local machine, Netdata with k8s_state charts in remote).
</details>
> add k8s_state dashboard_info

- collectors/freebsd.plugin/freebsd_sysctl.c
Fixes: #13172
Install on FreeBSD with ZFS, check the `system.ram` and `mem.available` charts.
- wired
- avail (51TB => 13GB)
</details>
> fix(freebsd.plugin): fix wired/cached/avail memory calculation on FreeBSD with ZFS

- collectors/proc.plugin/proc_net_dev.c
SSIA
Closes #13128
Check the `http://localhost:19999/api/v1/chart?chart=net.<interface name>` endpoint. `chart_labels` should contain `"type":"virtual"` or `"type":"real"`.
> Add type label for network interfaces

- collectors/proc.plugin/proc_net_dev.c
Network interface chart labels are replaced by cgroup labels. We need to keep the existing chart labels and add cgroup labels.
Fixes #13198
Run a docker container. Check if there is the type label in cgroup network interface charts.
> Fix cgroups netdev chart labels

- CMakeLists.txt
- Makefile.am
- database/sqlite/sqlite_db_migration.c
- database/sqlite/sqlite_db_migration.h
- database/sqlite/sqlite_functions.c
This PR adds an easy way to do metadata migration by checking the user_version recorded in the sqlite database
(set by using `PRAGMA user_version`)
It will then call a series of functions that need to perform the actions needed. 
The current version of the database schema is 1 (agents running older versions might have a version of 0). 
Version 0 and 1 are identical (additional tables added but existing tables have not been changed)
This PR will run dummy migration code (noop) from v0 to v1 (if needed) and it will simply set the user version to 1 just as the current agent does.
- Run the agent as usual, notice a `Metadata database version is 1` message as the agent starts in the error.log
- Stop the agent 
- Connect to the database via the sqlite CLI (eg `sqlite3 …
> Allow for an easy way to do metadata migrations

- database/sqlite/sqlite_functions.c
- Allocate thread keys to track the prepared statememts
- Finalize the statements on thread shutdown
- Setup parent - child
- Compile with `NETDATA_INTERNAL_CHECKS` 
- Start child and parent and notice messages on the parent error.log that assign prepared statements to keys
- Stop the child
- Observe that the statements are released
Example:
```
2022-06-22 00:03:46: netdata INFO  : STREAM_RECEIVER[ubuntu1804,[192.168.122.103]:53024] : Thread 483819: Using key 1 on statement 0x55961c5d74d8
2022-06-22 00:03:46: netdata INFO  : STREAM_RECEIVER[ubuntu1804,[192.168.122.103]:53024] : Thread 483819: Using key 2 on statement 0x55961c64dd48
2022-06-22 00:03:46: netdata INFO  : STREAM_RECEIVER[ubuntu1804,[192.168.122.103]:53024] : Thread 483819: Using key 3 on statement 0x55961c49e5b8
2022-06-22 …
```
> Clean sqlite prepared statements on thread shutdown

- daemon/main.c
- database/engine/pagecache.c
- database/engine/pagecache.h
- database/engine/rrdengineapi.c
- database/engine/rrdengineapi.h
Right now the default page fetch wait timeout is set to 1 seconds with a maximum of 3 retries. The agent will rarely need to reform a page cache retry except under extreme load. For example running netdata using valgrind may produce timeouts and in that case you will see in the error.log messages like
```
Page cache timeout while waiting for page 0x5555593ee9e0 : retry count = 0
``` 
This PR will change the default timeout to 3 seconds with a number of retries remaining to 3.
Both options can be changed by by adding the following in `netdata.conf` under the `[global]` section
```
dbengine page fetch timeout = 3
dbengine page fetch retries = 3
```
> Add configuration for dbengine page fetch timeout and retry count

- web/api/queries/query.c
Prints `INTERNAL BUG` messages only when compiled with `NETDATA_INTERNAL_CHECKS`.
> Print INTERNAL BUG messages only when NETDATA_INTERNAL_CHECKS is enabled

- netdata-installer.sh
Was installing Netdata from git and noticed
```bash
Uninstall script copied to: /opt/netdata/usr/libexec/netdata/netdata-uninstaller.sh
--- Installing (but not enabling) the netdata updater tool ---
./netdata-installer.sh: 1862: cleanup_old_netdata_updater: not found
FAILED  Cannot cleanup old netdata updater tool.
Update script is located at /opt/netdata/usr/libexec/netdata/netdata-updater.sh
```
Not needed.
</details>
> chore(netdata-installer): remove a call to 'cleanup_old_netdata_updater()' because it is no longer exists

- collectors/plugins.d/README.md
- daemon/analytics.c
We will expose the list of custom plugin directories as an environment variable.
Closes #13201
Run a custom plugin that reads the `NETDATA_USER_PLUGINS_DIR` environment variable. It should provide the list of directories (except the first one) configured using the `plugins` option in the `[directories]` section of `netdata.conf`.
```python
import os
self.info("NETDATA_USER_PLUGINS_DIR = ", os.environ['NETDATA_USER_PLUGINS_DIR'])
```
> Add user plugin dirs to environment

- aclk/README.md
- aclk/aclk.c
- aclk/aclk_api.c
This will use new MQTT implementation as default. In last release it was necessary to enable it manually as technical preview.
We should be certain of sufficient stability before doing this step.
</details>
> Use new mqtt implementation as default

- packaging/installer/netdata-updater.sh
It appears we have several bugs:
- we don't pass `--force-update` when `exec`uting downloaded `netdata-updater.sh`
https://github.com/netdata/netdata/blob/b67c1026bae0411e863a227214fd4175ff109d0f/packaging/installer/netdata-updater.sh#L420-L423
- at this point, we have another problems
https://github.com/netdata/netdata/blob/b67c1026bae0411e863a227214fd4175ff109d0f/packaging/installer/netdata-updater.sh#L553-L554
1. `netdata-updater.sh` is in the `pwd` (self_update()).
2. `path_version` is not set (because of `--force-update`).
Which results in trying to  `cd` into `netdata-updater.sh`.
To test this PR manually I did:
- created web server that returns the exact `netdata-updater.sh` as in this PR.
- changed `self_update()` so it always downloads the script from my server.
- executed …
> fix(updater): fix updating when using `--force-update` and new version of the updater script is available

- packaging/installer/kickstart.sh
The `set_tmpdir` function is idempotent specifically to allow for this type of usage, and this should help avoid bugs involving temporary directory handling going forwards.
Run the kickstart script on macOS or a Linux system that has `/` mounted as read-only and verify that there is no error due to `/install-type` not existing.
Fixes: https://github.com/netdata/netdata/issues/13185
> Ensure tmpdir is set for every function that uses it.

- packaging/installer/kickstart.sh
It doesn’t work on macOS and leads to a bogus error message being printed.
The replacement code is POSIX-compliant other than requiring a usable `readlink` command (which is present on all platforms we care about). 
Running the kickstart script on macOS no longer produces a line reading `/tmp/netdata-kickstart.sh: line 19: realpath: command not found` at the top of the output.
Discovered in https://github.com/netdata/netdata/issues/13185
> Don’t use realpath to find kickstart source path.

- packaging/installer/kickstart.sh
- packaging/installer/netdata-updater.sh
This adds options to override the default interactivity of the updater code, and leverages those to pass the interactivity of the kickstart script through to the updater when it is invoked from the kickstart script.
It also tidies up the option parsing code in the updater so that it’s easier to maintain going forwards.
Verify that the new `--non-interactive` option does not result in any prompting in the updater when run manually from a terminal.
Fixes: https://github.com/netdata/netdata/issues/13071
> Properly handle interactivity in the updater code.

- .github/workflows/add-to-project.yml
This PR adds [actions/add-to-project](https://github.com/actions/add-to-project#usage) GHA to automatically add all new **issues** to the [Agent Board](https://github.com/orgs/netdata/projects/32) project.
> **Note** the GHA supports adding PRs to projects too. This PR enables the GHA only for issues.
</details>
> ci: add issues to the Agent Board project workflow

- collectors/python.d.plugin/python.d.plugin.in
`NETDATA_USER_PLUGINS_DIRS` env var was added in #13203
- **Current**:
- python.d.plugin loads modules only from `NETDATA_PLUGINS_DIR/python.d`
- **This PR**:
- python.d.plugin loads modules from `NETDATA_PLUGINS_DIRS/python.d` (directories)
- and from `NETDATA_PLUGINS_DIR/python.d` 
- prepare test env
```cmd
deb-work ~ $ tree /opt/netdata/etc/netdata/custom-plugins.d*
/opt/netdata/etc/netdata/custom-plugins.d
└── python.d
├── example2.chart.py
└── example.chart.py
/opt/netdata/etc/netdata/custom-plugins.d2
└── python.d
├── example3.chart.py
└── example.chart.py
```
- check modules loading
```cmd
root@deb-work:/opt/netdata/usr/libexec/netdata/plugins.d# NETDATA_USER_PLUGINS_DIRS="/opt/netdata/usr/libexec/netdata/plugins.d /opt/netdata/etc/netdata/custom-plugins.d …
```
> feat(python.d): load modules from user plugin directories (NETDATA_USER_PLUGINS_DIRS)

- daemon/unit_test.c
This adds additional unit tests for sqlite to check that nothing breaks with certain SQL statements (especially when we update the sqlite version)
- Run unittests with `netdata -W unittest`
> Add more sqlite unittests

- .github/data/distros.yml
- .github/scripts/package-upload.sh
- .github/workflows/packaging.yml
- .github/workflows/repoconfig-packages.yml
This adds package uploads to our new self-hosted infrastructure in parallel with the PackageCloud uploads. It currently does not include metadata generation 
This is unfortunately a case where we need to merge and see what happens, because other than the upload script there’s not much that can be tested directly.
This is just the first part of finally migrating off of PackageCloud to self-hosting of our repositories. We still need to set up metadata generation and package and metadata signing, among other things.
> Upload packages to new self-hosted repository infrastructure.

- collectors/statsd.plugin/statsd.c
- daemon/global_statistics.c
- database/rrdlabels.c
- libnetdata/dictionary/README.md
- libnetdata/dictionary/dictionary.c
- libnetdata/dictionary/dictionary.h
- libnetdata/log/log.c
- libnetdata/log/log.h
This PR:
1. Relaxes the use of atomic operations for statistics (they are faster)
2. Implements reference counters to protect the dictionary items while they are traversed. In case an item is deleted while it is being used, the deletion is deferred until its reference counter becomes zero. While an item is marked for deletion, it is not in the index (it can be added again, and is not found while searching), but it remains in the linked list, although it is not offered to other callers traversing the dictionary.
3. Added public interface to acquire and release item from the dictionary. 
This is the first step to make the dictionaries more generic for using them in long-standing objects like RRDSETs, RRDDIMs, RRDHOSTs, etc.
Another current benefit is that with this version, a caller …
> Dictionaries with reference counters and full deletion support during traversal

- collectors/diskspace.plugin/plugin_diskspace.c
SSIA
Check if there are `fstype` labels in `disk_space` and `disk_inodes` charts uthing the http://localhost:19999/api/v1/charts endpoint.
> Add fstype labels to disk charts

- exporting/graphite/graphite.c
There is an extra semicolon after the metric name in the Graphite exporting output.
```text
netdata.arch-linux.system.processes.running; 2.3000000 1656516736
netdata.arch-linux.system.processes.blocked; 0.0000000 1656516736
```
That is happening when no labels are exported. The bug was introduced in #13070. We should remove the semicolon for empty label sets.
Fixes #13205
1. Configure a Graphite exporting instance.
2. Set `send automatic labels = no`.
3. Check with `nc` if there are no semicolons after the metric names.
> Get rid of extra semicolon in Graphite exporting

- Makefile.am
This PR is removing the following warnings when we compile Netdata on FreeBSD:
```sh
[/home/thiago/Netdata/netdata]# gmake -j2 
In file included from ml/kmeans/dlib/dlib/all/../dnn/../matrix.h:11,
from ml/kmeans/dlib/dlib/all/../dnn/tensor.h:8,
from ml/kmeans/dlib/dlib/all/../dnn/cpu_dlib.h:9,
from ml/kmeans/dlib/dlib/all/../dnn/cpu_dlib.cpp:8,
from ml/kmeans/dlib/dlib/all/source.cpp:82:
ml/kmeans/dlib/dlib/all/../dnn/../matrix/matrix_la.h: In function 'long int dlib::svd4(dlib::svd_u_mode, bool, const dlib::matrix_exp<EXP>&, dlib::matrix<typename EXP::type, uM, uN, MM1, L1>&, dlib::matrix<typename EXP::type, qN, qX, MM2, L1>&, dlib::matrix<typename EXP::type, vM, vN, MM3, L1>&) [with EXP = dlib::matrix_op<dlib::op_trans<dlib::matrix_op<dlib::op_trans<dlib::matrix<double, 1, 2> > > > >; …
```
> Remove warnings while compiling ML on FreeBSD

- collectors/ebpf.plugin/ebpf.c
- collectors/ebpf.plugin/ebpf_apps.h
- collectors/ebpf.plugin/ebpf_cachestat.c
- collectors/ebpf.plugin/ebpf_cachestat.h
- collectors/ebpf.plugin/ebpf_cgroup.c
- collectors/ebpf.plugin/ebpf_cgroup.h
- collectors/ebpf.plugin/ebpf_dcstat.c
- collectors/ebpf.plugin/ebpf_dcstat.h
- collectors/ebpf.plugin/ebpf_disk.c
- collectors/ebpf.plugin/ebpf_fd.c
- collectors/ebpf.plugin/ebpf_fd.h
- collectors/ebpf.plugin/ebpf_filesystem.c
- collectors/ebpf.plugin/ebpf_hardirq.c
- collectors/ebpf.plugin/ebpf_mdflush.c
- collectors/ebpf.plugin/ebpf_mount.c
- collectors/ebpf.plugin/ebpf_oomkill.c
- collectors/ebpf.plugin/ebpf_process.c
- collectors/ebpf.plugin/ebpf_shm.c
- collectors/ebpf.plugin/ebpf_shm.h
- collectors/ebpf.plugin/ebpf_socket.c
- collectors/ebpf.plugin/ebpf_socket.h
- collectors/ebpf.plugin/ebpf_softirq.c
- collectors/ebpf.plugin/ebpf_swap.c
- collectors/ebpf.plugin/ebpf_swap.h
- collectors/ebpf.plugin/ebpf_sync.c
- collectors/ebpf.plugin/ebpf_vfs.c
- collectors/ebpf.plugin/ebpf_vfs.h
Fixes #12775
We are bringing for eBPF the same logic used with `apps` .
1. Compile this PR
2. Run netdata
3. wait few minutes
4. Stop the netdata, you should not have segmentation fault repoted.
- Which area of Netdata is affected by the change? ebpf
- Can they see the change or is it an under the hood? If they can see it, where? When netdata is stopped, users won't receive errors.
- How is the user impacted by the change? No possible core-dumps
- What are there any benefits of the change? We are removing errors from user systems
</details>
> Ebpf issues

- contrib/debian/netdata.postinst
- Run configuration for both configure _and_ reconfigure hooks. This allows users to run `dpkg-reconfigure netdata` to fix any issues with group membership and/or file permissions.
- Use a proper if/then/else construct for handling the file capabilities for the perf plugin. This ensures we get the behavior we want, and should also get rid of the warnings we see on install/update on some systems.
- Run all configuration regardless of whether the configuration hook is happening as part of an install or an upgrade. This ensures that changes we make to configuration always get applied. See [the deb-postinst manpage](https://man7.org/linux/man-pages/man5/deb-postinst.5.html) for info on why the ommit for this particular change works.
1. Build a package from this PR.
2. In the test environment, …
> Fix issues with DEB postinstall script.

- aclk/aclk.c
- aclk/aclk_otp.c
- aclk/aclk_otp.h
- libnetdata/socket/security.h
Fixes https://github.com/netdata/netdata/issues/13139
This PR is adjusting our ACLK code to use the high-level functions instead the low level functions that were deprecated when OpenSSL 3.0 was released, this will help us to avoid possible lost connection between agents and cloud when functions are removed.
We are not using only high-level interface, because low-level interface is faster when it is available. The functions were not removed from OpenSSL tree, instead they are only used [internally](https://github.com/openssl/openssl/blob/master/crypto/pem/pem_all.c)
1. Compile this branch on a distribution that runs `OpenSSL 3.0` or newer. Another option is to compile the library and install on your environment. Verify that we do not have warnings during this step.
2. Start agent
3. Claim …
> Remove warnings when openssl 3 is used.

- .github/workflows/packaging.yml
Changes added as part of https://github.com/netdata/netdata/pull/13240 resulted in the job filtering for native package builds on PRs to not work correctly.
This fixes it.
CI on this PR includes Fedora, Alma, Oracle, and openSUSE package build jobs.
> Fix package build filtering on PRs.

- web/api/formatters/rrdset2json.c
Our current json output for chart labels is not aligned, because we are missing a tab:
```c
"green": null,
"red": null,
"alarms": {
},
"chart_labels": {
"123caniuse":"testing",
"myconstant":"never_change",
"ourconstant":"we talk about",
"yourconstant":"you define"
}
```
This PR is fixing this issue aligning the JSON:
```c
"green": null,
"red": null,
"alarms": {
},
"chart_labels": {
"123caniuse":"testing",
"myconstant":"never_change",
"ourconstant":"we talk about",
"yourconstant":"you define"
}
```
1. Before to compile this branch, start your `netdata` and access http://localhost:19999/api/v1/charts?all, you will have chart labels not aligned.
3. Access the link again https://localhost:19999/api/v1/charts?all (press Ctrl+R) and you will see that chart labels are now …
> Fix alignment in charts endpoint

- collectors/freebsd.plugin/freebsd_sysctl.c
- web/gui/dashboard_info.js
Using the notion of committed memory (`mem.committed` chart) is confusing on FreeBSD. As far as we use `vmtotal.t_rm` as the data source, we need to reflect its meaning in the chart name and info.
Closes #13231
Check the `mem.real` chart on FreeBSD.
> Rename the chart of real memory usage in FreeBSD

- web/api/queries/query.c
The alignment of `before` was going beyond the database on relative queries (like health ones), resulting in random alarm values.
Generally, health queries should be defined `unaligned`, so this was only visible on aligned ones.
Now, instead of aligning ahead, the query engine aligns `before` to the past, so that data are always available.
The new query engine returns data for the specified timestamp including the `after` and `before` timestamp.
This was awkward for relative queries. For example a query with `after=-3&before=0` it was returning 4 points. It is fixed to now return -1 points on relative queries.
Absolute queries still return inclusive timestamps.
The new query engine respected the number of points more than the time-frame. So, it was under conditions returning data for a …
> query engine fixes for alarms and dashboards

- packaging/installer/dependencies/freebsd.sh
- packaging/installer/install-required-packages.sh
This relaxes our dependency handling for local builds to not install GCC if we see an existing install of Clang. We don’t actually have any issues building with Clang, so we should just use it if it’s present.
This will have the biggest impact for FreeBSD users, who will no longer need GCC installed to install Netdata.
Testable by verifying whether the `install-required-pkgs.sh` script tries to install GCC on a system that has Clang installed already.
Relevant to (but does not completely fix): https://github.com/netdata/netdata/issues/13230
Once this is merged, users will be able to install on FreeBSD without GCC being installed.
</details>
> Don’t pull in GCC for build if Clang is already present.

- database/engine/metadata_log/metalogpluginsd.c
- database/rrdhost.c
- database/sqlite/sqlite_db_migration.c
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
When the machine GUID of an agent changes, a new entry is created in the host table and node_instance table. This causes a second registration to the cloud. This new instance is marked with `live=false` causing confusion. 
This PR adds functionality to detect a machine GUID change and migrate all the data from the old machine guid to the new one. It will clean up the host and node instance tables and update the chart table with the new host machine UUID
- Setup agent / claim to the cloud
- Start agent, view cloud dashboard
- Stop agent and change the agent machine GUID
- Restart the agent
Fixes #12890
> Migrate data when machine GUID changes

- packaging/installer/install-required-packages.sh
We no longer need it. The python version of the MySQL collector has been removed from netdata/netdata.
</details>
> chore: remove python-mysql from install-required-packages.sh

- database/rrddim.c
- database/rrdset.c
Fixes
```
*** CID 379225:  Memory - illegal accesses  (STRING_NULL)
/database/rrdset.c: 1915 in rrdset_memory_load_or_create_map_save()
1909             0);
1910     
1911         if(!st_on_file) return false;
1912     
1913         time_t now = now_realtime_sec();
1914     
>>>     CID 379225:  Memory - illegal accesses  (STRING_NULL)
>>>     Passing unterminated string "st_on_file->magic" to "strcmp", which expects a null-terminated string.
1915         if(strcmp(st_on_file->magic, RRDSET_MAGIC_V019) != 0) {
1916             info("Initializing file '%s'.", fullfilename);
1917             memset(st_on_file, 0, size);
1918         }
1919         else if(strncmp(st_on_file->id, st->id, RRD_ID_LENGTH_MAX_V019) != 0) {
1920             error("File '%s' contents are not for chart '%s'. …
```
> Null terminate string if file read was not successful

- collectors/cgroups.plugin/cgroup-name.sh
- collectors/cgroups.plugin/sys_fs_cgroup.c
Fixes: #13251
Test this fix by installing Netdata in [kind](https://github.com/kubernetes-sigs/kind#please-see-our-documentation-for-more-in-depth-installation-etc) cluster.
<details>
<summary>Before fix</summary>
</details>
<details>
<summary>After the fix</summary>
</details>
</details>
> fix(cgroups.plugin): adjust kubepods regex to fix name resolution in a kind cluster

- database/rrdcalc.c
Fixes #13284
Fixes #13304 
Keeps `rc` in another pointer, and uses that after freeing `rc`.
Can be tested on a non k8s cluster. Just change the label of `oom_kill` alarm from `_is_k8s_node = false` to `_is_k8s_node = true`. Using master it should crash. Using this PR it should not.
Checking count of `curl 'http://localhost:19999/api/v1/alarms?all' | grep config_hash_id | wc -l` should be -1 when `_is_k8s_node = true`.
Also tested with single alert `oom_kill`. It should correctly remove the single alert and leave the agent with 0 alerts.
</details>
> Keep rc before freeing it during labels unlink alarms

- health/health.d/go.d.plugin.conf
There is a problem with that module in K8s. Will disable the alarm for prometheus until we get fixed it.
Not needed.
</details>
> fix(health): disable go.d last collected alarm for prometheus module

- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_aclk.h
- database/sqlite/sqlite_aclk_alert.c
- database/sqlite/sqlite_aclk_chart.c
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
- database/sqlite/sqlite_health.c
The new sqlite version 3.38.5 offers a unixepoch() function similar to the strftime('%s'). The difference is that unixepoch() returns an integer vs a string. 
This PR switches to using the unixepoch()
- Nothing should be changed. Internally sqlite will store into the corresponding fields timestamps in integers instead of strings
> Remove strftime from statements and use unixepoch instead

- .github/workflows/build.yml
- .github/workflows/docker.yml
- .github/workflows/packaging.yml
- .github/workflows/repoconfig-packages.yml
This changes how we handle uploads and Slack notifications in our release build workflows so that they are skipped when running in repositories other than our own.
This simplifies testing and verification of the core release code by enabling testers to run a mock release build or mock nightly build to completion without worrying about the uploads and slack notifications failing the whole workflow.
This can be tested by checking out the branch from this PR, pushing it to your local fork, and then running any of the modified workflows by hand using a workflow dispatch event.
Relevant to (but does not fix): https://github.com/netdata/netdata/issues/13222
> Explicitly skip uploads and notifications in third-party repositories.

- collectors/apps.plugin/apps_groups.conf
Fixes: https://github.com/netdata/netdata/issues/13292#issuecomment-1176108180
All the Zimbra Zmstats collection scripts [start with `zmstat-`](https://wiki.zimbra.com/wiki/Zmstats).
Not needed
</details>
> fix(apps.plugin): adjust `zmstat*` pattern to exclude zoneminder scripts

- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_aclk.h
- database/sqlite/sqlite_aclk_alert.c
- database/sqlite/sqlite_aclk_chart.c
- database/sqlite/sqlite_functions.c
Adds the hostname in the worker structures to avoid constant lookups to map the node id to the hostname
- Agent should work as before
> Add hostname in the worker structure to avoid constant lookups

- collectors/cgroups.plugin/sys_fs_cgroup.c
This PR adjusts `enable by default cgroups matching` and `run script to rename cgroups matching` simple patterns to filter out pods when using Kind cluster. Reported in https://github.com/netdata/netdata/issues/13251#issuecomment-1175370710.
Install Netdata in GCP and Kind cluster using a custom image built from this branch.
</details>
> fix(cgroups.plugin): adjust kubepods patterns to filter pods when using Kind cluster

- libnetdata/log/log.c
- libnetdata/log/log.h
Fixes reports by helgrind:
```
==00:00:00:01.769 44512== Possible data race during read of size 8 at 0x9767B0 by thread https://github.com/netdata/netdata/pull/4
==00:00:00:01.769 44512== Locks held: none
==00:00:00:01.769 44512==    at 0x17CB56: error_log_limit (log.c:627)
==00:00:00:01.769 44512==    by 0x17CEC0: info_int (log.c:716)
==00:00:00:01.769 44512==    by 0x18949F: thread_start (threads.c:173)
==00:00:00:01.769 44512==    by 0x484A486: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==00:00:00:01.769 44512==    by 0x4E9CD7F: start_thread (pthread_create.c:481)
==00:00:00:01.769 44512==    by 0x532F76E: clone (clone.S:95)
==00:00:00:01.769 44512==
==00:00:00:01.769 44512== This conflicts with a previous write of size 8 by thread …
```
> Protect shared variables with log lock.

- aclk/aclk_charts_api.c
- aclk/aclk_charts_api.h
- aclk/aclk_query.c
- aclk/aclk_query_queue.c
- aclk/aclk_query_queue.h
- aclk/aclk_util.c
- aclk/aclk_util.h
- aclk/schema-wrappers/node_info.cc
- aclk/schema-wrappers/node_info.h
- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_aclk.h
- database/sqlite/sqlite_aclk_node.c
- database/sqlite/sqlite_aclk_node.h
This PR adds a new `UpdateNodeCollectors` protobuf message. It will contain a list of collector's modules and plugins. From that list the FE will render a series of services, supported by the agent.
The message will follow 30 seconds after the `UpdateNodeInfo` message. This is to allow enough time for collectors to be activated and included in the message.
BE has been prepared to receive it.
There should be a line stating `NODE COLLECTORS SENT` in `access.log`. It has been tested with @vkuznecovas in testing.
</details>
> UpdateNodeCollectors message

- Makefile.am
Silences some compile warnings on `dlib`, `sqlite3` and `KolmogorovSmirnovDist`.
Compile warnings on those files should be gone.
</details>
> Silence compile warnings on external source

- CMakeLists.txt
- Makefile.am
- configure.ac
- database/engine/pagecache.c
- database/engine/pagecache.h
- database/engine/rrdengineapi.c
- database/rrdhost.c
- libnetdata/Makefile.am
- libnetdata/arrayalloc/Makefile.am
- libnetdata/arrayalloc/README.md
- libnetdata/arrayalloc/arrayalloc.c
- libnetdata/arrayalloc/arrayalloc.h
- libnetdata/libnetdata.h
- libnetdata/onewayalloc/onewayalloc.c
This is test to see the effects of moving dbengine page descriptors to a mmap'd file.
This version uses the array allocator either with `malloc()` or with `mmap()`. The configuration option to control this is:
```
[db]
dbengine page descriptors in file mapped memory = no
```
When set to `no`, malloc is used with a max size of 10MB.
When set to `yes`, mmap is used with a max size of 1GB.
> array allocator for dbengine page descriptors

- daemon/main.c
- database/rrdhost.c
We found a condition that ML starts doing queries before dbengine is initialized. The problem was that localhost was initialized before dbengine, and if dbengine had a lot of files to process (or is on slow disks), ML managed to start doing queries before the initialization of dbengine. 
No real code changes. Just moved things around to ensure dbengine is initialized before ML starts.
> fix crash on start on slow disks because ml is initialized before dbengine starts

- libnetdata/arrayalloc/arrayalloc.c
- libnetdata/onewayalloc/onewayalloc.c
Netdata fails to start on 32bit machines. It was a wrong calculation.
fixes https://github.com/netdata/netdata/issues/13337
> fix 32bit calculation on array allocator

- packaging/docker/Dockerfile
It is hardcoded to "-O2 -pipe" now.
https://github.com/netdata/netdata/blob/2cf65ad3774f697e1c618e2172eee9313c594575/packaging/docker/Dockerfile#L26-L29
Tested locally by adding a log message that prints CFLAGS to the installer script.
</details>
> fix(packaging): respect CFLAGS arg when building Docker image

- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_aclk_node.c
This PR tries to fix #13101 where on the first agent connection to the cloud, the NODE INFO message will be delayed to be sent to the cloud.
If it's the value of `wc->host` that we're waiting before sending the NODE INFO message, then the check is moved inside the function. In essence it will try to queue the function until the `wc->host` is there.
We need to test that NODE INFO is sent to the cloud as soon as possible, that is:
1) On an running agent's first claim and first connection.
2) On a first start of an agent after claim.
3) When a child is connected and indicated as active.
</details>
> Send node info message sooner

- exporting/opentsdb/opentsdb.c
There is an extra comma after the host name in the Graphite exporting output.
```text
[
{"metric":"netdata.system.processes.running","timestamp":1657531146,"value":1.0000000,"tags":{"host":"my_hostname",}},
{"metric":"netdata.system.processes.blocked","timestamp":1657531146,"value":0.0000000,"tags":{"host":"my_hostname",}}
]
```
The bug was introduced in #13070. We should remove the comma.
Fixes #13333
1. Configure an OpenTSDB HTTP exporting instance.
3. Check with `nc` if there are no commas after the host name.
> Get rid of extra comma in OpenTSDB exporting

- daemon/main.c
- daemon/unit_test.c
- daemon/unit_test.h
- database/engine/journalfile.c
- database/engine/pagecache.c
- database/engine/rrddiskprotocol.h
- database/engine/rrdengine.h
- database/engine/rrdengineapi.c
- database/engine/rrdengineapi.h
- libnetdata/libnetdata.c
- libnetdata/libnetdata.h
- Detect the page size by the page type (not by tier)
Add additional checks
- Report unknown page type only once during startup
- Detect and skip invalid pages (if page  start_time > page end_time) or start_time = end_time and there seem to be more than one entries in the page
> Detect stored metric size by page type 

- collectors/python.d.plugin/python.d.plugin.in
Fixes: #13360
Before
> 2022-07-11 19:32:48: python.d WARNING: plugin[main] : error on loading '/opt/netdata/etc/netdata/python.d/example.conf' : ParserError('while parsing a block mapping', <pyyaml3.error.Mark object at 0x7f509fc15e50>, "expected <block end>, but found '<block mapping start>'", <pyyaml3.error.Mark object at 0x7f509fb29dc0>)
After
> 2022-07-11 19:47:26: python.d ERROR: plugin[main] : [example] config file invalid YAML format: while parsing a block mapping in "/opt/netdata/etc/netdata/python.d/example.conf", line 72, column 1 expected <block end>, but found '<block mapping start>' in "/opt/netdata/etc/netdata/python.d/example.conf", line 74, column 5
Tested manually.
</details>
> chore(python.d): improve config file parsing error message

- libnetdata/libnetdata.c
Address the following coverity issues
```
*** CID 379258:  Integer handling issues  (BAD_SHIFT)
/libnetdata/libnetdata.c: 1542 in bitmap256_get_bit()
1536     }
1537     
1538     
1539     bool bitmap256_get_bit(BITMAP256 *ptr, uint8_t idx) {
1540         if (unlikely(!ptr))
1541             return false;
>>>     CID 379258:  Integer handling issues  (BAD_SHIFT)
>>>     In expression "1 << idx % 64", left shifting by more than 31 bits has undefined behavior.  The shift amount, "idx % 64", is as much as 63.
1542         return (ptr->data[idx / 64] & (1 << (idx % 64)));
1543     }
1544     
1545     void bitmap256_set_bit(BITMAP256 *ptr, uint8_t idx, bool value) {
1546         if (unlikely(!ptr))
1547             return;
```
```
/libnetdata/libnetdata.c: 1551 in bitmap256_set_bit()
1545 …
```
> Address Coverity issues

- .github/workflows/repoconfig-packages.yml
This ensures that newly added distros get repoconfig packages promptly.
n/a
> Also run repoconfig package builds when distro list is changed.

- web/api/queries/query.c
When querying dbengine for time `t1` to `t2`, dbengine finds the latest page that its first point has an end time less or equal to `t1` and then within that page finds the latest point in the page that has end time less or equal to `t1`.
This works perfectly, but depending on the granularity of the database, it may have 1 issue:
The first point returned may not be useful for the query. It may be entirely past of it.
If the granularity of the database is not 1 (e.g. higher tiers), this point is still very useful and we want it. We use it to interpolate the next point that most likely will end within the query timeframe, so that we can find the exact value of the next point at the query boundaries. But still, this point, the first one that is entirely outside the query time-frame, should …
> query engine: omit first point if not needed

- docs/Running-behind-h2o.md
This adds a document explaining how to configure a [H2O web server](https://h2o.examp1e.net/) to proxy access to the Netdata dashboard.
The document structure is modeled on the equivalent document we already have for NGinx
n/a
This document is based on the configuration I’m successfully using on my own systems to proxy Netdata via H2O.
> Add document explaining how to proxy Netdata via H2O

- .github/data/distros.yml
- packaging/PLATFORM_SUPPORT.md
- packaging/installer/dependencies/ol.sh
- packaging/installer/install-required-packages.sh
As outlined in the title.
Oracle Linux 9 will be officially supported by the Netdata Agent team going forwards.
</details>
> Add Oracle Linux 9 to officially supported platforms.

- packaging/makeself/build-static.sh
- packaging/makeself/install-alpine-packages.sh
- packaging/makeself/jobs/90-netdata-runtime-check.sh
This adds basic runtime startup checks to the static build process, equivalent to the basic checks we have for our native packages. With these in place, the static build will fail if the resultant executable cannot be run at all, or does not start up and provide a usable REST API.
This also adds support to the static build system for using Podman instead of Docker, with autodetection of which is available at build time, and provides a useful error message if neither is found.
> Add basic runtime checks to static build process.

- database/rrdhost.c
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
Add a new `host_info` table to hold additional host information as key / value pairs. Those will be used to 
populate the host->system_info structure when the host is in archived mode.
This PR will only store the system info in the database table. A subsequent PR will make use the stored info to create archived 
hosts in memory. 
- Apply the PR and notice a new table `host_info` in the database. Check to see that the table is populated
Use e.g. the sqlite3 CLI to check the table.
> Store host system information in the database

- database/sqlite/sqlite_functions.c
Handle coverity warning
```
*** CID 379360:  Incorrect expression  (MISSING_COMMA)
/database/sqlite/sqlite_functions.c: 35 in ()
29         "on_key text, class text, component text, type text, os text, hosts text, lookup text, "
30         "every text, units text, calc text, families text, plugin text, module text, charts text, green text, "
31         "red text, warn text, crit text, exec text, to_key text, info text, delay text, options text, "
32         "repeat text, host_labels text, p_db_lookup_dimensions text, p_db_lookup_method text, p_db_lookup_options int, "
33         "p_db_lookup_after int, p_db_lookup_before int, p_update_every int);",
34     
>>>     CID 379360:  Incorrect expression  (MISSING_COMMA)
>>>     In the initialization of "database_config", a suspicious …
```
> Add missing comma (handle coverity warning CID 379360)

- .github/workflows/add-to-project.yml
- .github/workflows/cloud_regression.yml
- .github/workflows/packagecloud.yml
This will avoid pestering developers with failed workflow run messages for workflows that should not even be running in their repos.
n/a
> Skip repo-specific CI on forks.

- .github/data/distros.yml
- packaging/PLATFORM_SUPPORT.md
To be merged on 2022-07-31 when it goes EOL upstream.
n/a
Ubuntu 21.10 (Impish Indra) will no longer receive official support from the Netdata team, and we will stop publishing packages for it.
</details>
> Remove Ubuntu 21.10 from CI and package builds.

- database/engine/rrdengine.c
- database/engine/rrdengineapi.c
- database/ram/rrddim_mem.c
- database/rrd.h
- database/rrdset.c
- libnetdata/storage_number/storage_number.c
- libnetdata/storage_number/storage_number.h
- web/api/queries/query.c
_Tries_ to fix #13353 
`unpack_storage_number` has a check for the value being `SN_EMPTY_SLOT` here: https://github.com/netdata/netdata/blob/fccfc02d2c1966b814b6babcd8dddb0c6e822d45/libnetdata/storage_number/storage_number.h#L122-L123
However, `pack_storage_number` doesn't seem to ever store a value as `SN_EMPTY_SLOT`, so we never get NaNs. This PR merely adds a check if the flags is `SN_EMPTY_SLOT` (which is used when storing) it will also set the value to `SN_EMPTY_SLOT`.
It solves the problem on #13353 but I'm not sure if this is the right way to do it.
Setup a child/parent setup. Stream from child to parent. Stop the child for a bit then restart it. There should now be gaps instead of zeroes.
</details>
> Set value to SN_EMPTY_SLOT if flags is SN_EMPTY_SLOT

- exporting/prometheus/remote_write/remote_write.c
The number of buffered bytes in stats for the Prometheus remote write exporting connector is doubled. In addition to the fact that the data is incorrect, it also causes false alarms. We shouldn't update the counter in the remote write exporting connector because it is updated by means of the simple exporting connector that are used for buffer processing.
Fixes #13381
1. Configure a Prometheus remote write exporting connector instance.
2. Receive data using the [remote write adapter](https://github.com/prometheus/prometheus/tree/main/documentation/examples/remote_storage/example_write_adapter).
3. Check if buffered data is the same as sent in `netdata.exporting_my_prometheus_remote_write_instance_bytes`.
> Dont duplicate buffered bytes

- system/netdata.service.in
Hi,
In systemd service unit file, change ProtectControlGroups from true to on
On CentOS 7 , each systemd reload write the following line in /var/log/messages (`systemctl daemon-reload`)
`systemd: [/usr/lib/systemd/system/netdata.service:72] Unknown lvalue 'ProtectControlGroups' in section 'Service'`
No error was reported with new value (on or yes)
Original bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1975343
> Fix boolean value for ProtectControlGroups

- database/sqlite/sqlite_aclk.c
When trying to report the node id, if the host has not been registered to the cloud, the agent will crash.
This PR addresses this issue (also enables this reporting only when compiled with NETDATA_INTERNAL_CHECKS)
- Enable rrdcontexts and do a `update node_instance set node_id = NULL;`  on `netdata-meta.db`. The agent will crash when trying to report the node_id
- Apply the PR and retry (needs to be compiled with NETDATA_INTERNAL_CHECKS)
> Fix agent crash when archived host has not been registered to the cloud

- database/sqlite/sqlite_aclk_alert.c
When a node's metadata is deleted from the cloud, we need to re-sync the alerts. Currently, the metadata are deleted when a user deletes a node, or when some days have passed since a node was connected (this is a new feature under development - and granted, there is a timelimit after which the agent will skip filters and re-send everything to the cloud).
Because the agent is not aware that previous alerts where deleted from the cloud, it will still filter new alerts and not send them, if for example they where previously sent again with the same status. This can lead to the agent having raised alerts, but not on the cloud.
We agreed with the cloud to inform for this case the agent, by requesting to start streaming with batch_id 1 and sequence_id 1. When this occurs, the agent will delete …
> Delete aclk_alert table on start streaming from seq 1 batch 1

- aclk/aclk.c
- aclk/aclk.h
- aclk/aclk_alarm_api.c
- aclk/aclk_charts_api.c
- aclk/aclk_contexts_api.c
- aclk/aclk_query.c
- aclk/aclk_query.h
- aclk/aclk_query_queue.c
- aclk/aclk_query_queue.h
- aclk/aclk_rx_msgs.c
- aclk/aclk_stats.c
- aclk/aclk_stats.h
- aclk/schema-wrappers/context.cc
- aclk/schema-wrappers/context.h
- Removes most types of messages from query queue. Those can be scheduled and sent immediately (queuing is done in MQTT).
- This cleans up and simplifies (+77 -253 lines) the code. Query threads now handle only HTTP queries (which might be long running due to IO etc.).
- This allows/simplifies further work on ACLK. Removes complexity that is not necessary anymore.
- no problems on the cloud
</details>
> Query queue only for queries

- web/api/formatters/rrd2json.c
When a context is queried, the `rebuild_context_param_list` is called. Inside there is a loop for each dimension, which tries to get the `last_entry_t` of the chart, and compare it.
This PR gets `last_entry_t` it only when the chart changes. This can help to speed up queries especially in context of `anomaly_detection.anomaly_rates` where the chart stays the same while there are many dimensions.
Create an agent with many charts and dimensions (20.000 dimensions is good to re-create the issue.)
Do a query on `anomaly_detection.anomaly_rates`, e.g. `api/v1/data?before=1658998800&after=1658998230&context=anomaly_detection.anomaly_rates&dimensions&format=json&group=average&gtime=0&options=allow_past|flip|jsonwrap|ms&points=1`
Notice the time it takes to complete with or without this PR. …
> Get last_entry_t only when st changes

- collectors/plugins.d/pluginsd_parser.c
- database/rrd.h
- database/rrdhost.c
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
Currently we do not store the host label information in the database. A new table `host_label` is added to store the information. 
The host labels stored will be used to properly populate the host structure for archived hosts (in a followup PR)
- After applying this PR, notice a new table `host_label` in `netdata-meta.db`. It will contain information for the localhost and also any children
> Store host label information in the metadata database

- aclk/aclk.c
- aclk/aclk.h
- aclk/aclk_alarm_api.c
- aclk/aclk_charts_api.c
- aclk/aclk_contexts_api.c
- aclk/aclk_query.c
- aclk/aclk_query.h
- aclk/aclk_query_queue.c
- aclk/aclk_query_queue.h
- aclk/aclk_rx_msgs.c
- aclk/aclk_stats.c
- aclk/aclk_stats.h
- aclk/schema-wrappers/context.cc
- aclk/schema-wrappers/context.h
Reverts netdata/netdata#13431
This causes a deadlock on the agent during shutdown
```
2022-07-28 23:38:48: netdata INFO  : MAIN : (0238@daemon/main.c       :cancel_main_thr): Waiting 2 threads to finish...
2022-07-28 23:38:48: netdata ERROR : MAIN : (0250@daemon/main.c       :cancel_main_thr): Main thread SERVICE takes too long to exit. Giving up...
2022-07-28 23:38:48: netdata ERROR : MAIN : (0250@daemon/main.c       :cancel_main_thr): Main thread ACLK_Main takes too long to exit. Giving up...
2022-07-28 23:38:48: netdata INFO  : MAIN : (0056@daemon/main.c       :netdata_cleanup): EXIT: freeing database memory...
```
```
Thread 4 (Thread 0x7f6b52616640 (LWP 129058) "AS_ubuntu1804"):
#0  futex_wait (private=0, expected=2, futex_word=0x560786585f60) at ../sysdeps/nptl/futex-internal.h:146 …
```
> Revert "Query queue only for queries"

- packaging/docker/README.md
Fixes: #6882. I think we need to restructure our Docker readme (minimal feature set default + additional features as section => max feature set default with notes on why we need additional priviliges), but I will do it later 😄 
Not needed.
</details>
> docs: add a note about network interface monitoring when running in a Docker container

- health/health.c
- health/notifications/alarm-notify.sh.in
Fixes #13380
This PR reduces the list on the email notification of the additional active alerts to 15. Such a change has already been done on the cloud.
When we have many active alerts the list can grow, thus growing the command that will be executed by the spawn server. If it reaches a large size, it can potentially error out in the spawn server.
There has been some tests to alleviate this problem from the spawn server, but cloud also reduced the list to 15 alerts, and also such a large list doesn't really make much sense to have in the notification.
Produce a lot of alerts, and watch their notifications. Alerts should be sorted by date in the additional alerts list, i.e.:
If the additional active alerts is more than 15, an additional text will appear in the notification:
<details> …
> Show last 15 alerts in notification

- collectors/cgroups.plugin/cgroup-name.sh
Fixes some cgroup names for containers running under Docker not being detected automatically by the cgroup-name.sh` script.
I've tested the modified script and resulting Netdata build on my nodes and verified that is runs without an issue and doesn't conflict with other existing cgroup rules.
Some Docker containers on a few systems I'm managing live under the `system.slice/containerd.service/cpuset/*` group namespace. These containers are correctly detected by Netdata and shown in the UI, however their names are not detected as they don't match the existing rules in the `cgroup-name.sh` script.
In the image below you can see the top 5 containers have their names correctly extracted (`nomad init *`), but the containers below are just displaying their cgroup paths (`system_slice …
> Fix cgroup name detection for docker containers in containerd cgroup

- CMakeLists.txt
- Makefile.am
- configure.ac
- daemon/common.h
- daemon/main.c
- database/metric_correlations.c
- database/metric_correlations.h
- database/ram/Makefile.am
- database/ram/README.md
- health/health.c
- web/api/badges/web_buffer_svg.c
- web/api/formatters/json/json.c
- web/api/formatters/rrd2json.c
- web/api/formatters/rrd2json.h
- web/api/formatters/value/value.c
- web/api/formatters/value/value.h
- web/api/netdata-swagger.yaml
- web/api/queries/query.c
- web/api/queries/rrdr.c
- web/api/queries/rrdr.h
- web/api/queries/weights.c
- web/api/queries/weights.h
- web/api/web_api_v1.c
- web/api/web_api_v1.h
This PR introduces `/api/v1/weights` endpoint, as a more general method for querying anomaly rates and metric correlations.
It obsoletes the `/api/v1/metric_correlations` endpoint (although it still works).
The new `/api/v1/weights` accepts all the parameters of `/api/v1/metric_correlations` and supports 3 algorithms:
The following improvements have also been implemented:
Fixes: https://github.com/netdata/netdata/discussions/13446
> /api/v1/weights endpoint

- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
When the agent start and `rrdcontexts = yes`, all archived hosts are loaded in memory
This PR is a followup to #13441 so that those hosts have their host label information available. 
- Setup a parent / child agent and make sure you have `rrdcontexts = yes`  on the parent. 
- Start the parent and the child 
- Check the contexts for the child on the parent using `/host/child/api/v1/contexts?options=full` 
- Notice the `host_labels` section in the output
- Stop the parent / child and restart only the parent and check again. Notice the `host_labels` is empty
- Apply the PR, start only the parent and try again
- You should see the `host_labels` of the child
> Load host labels for archived hosts

- database/rrdhost.c
During agent initialization, if data rotation needs to happen, there is a chance to have data corruption in the array
allocator and cause a crash
```
#1  0x000055b3f5911172 in arrayalloc_freez (ar=0x55b3f62b8bc0 <page_descr_aral>, ptr=0x7f90373cb700) at libnetdata/arrayalloc/arrayalloc.c:330
#2  0x000055b3f5c5e3d8 in rrdeng_page_descr_freez (descr=0x7f90373cb700) at database/engine/pagecache.c:29
#3  0x000055b3f5c5f897 in pg_cache_punch_hole (ctx=0x55b3f62ce9a0 <multidb_ctx_storage_tier0>, descr=0x7f90373cb700, remove_dirty=0 '\000', is_exclusive_holder=0 '\000', metric_id=0x7f8ea8b03b70) at database/engine/pagecache.c:540
#4  0x000055b3f5c53def in delete_old_data (arg=0x55b3f62ce9a0 <multidb_ctx_storage_tier0>) at database/engine/rrdengine.c:982
#5  0x00007f9037e3ab43 in start_thread …
```
> Remove the single threaded arrayallocator optiomization during agent startup

- database/sqlite/sqlite_aclk.c
Handle the cases where date_created, date_updated, date_submitted were stored as text
and the cleanup jobs may not work as expected.
With this PR explicit casting to integer will make sure it works as expected
- Agent should work as expected -- you will notice better cleanup of stale events in the various `aclk_chart_xxx` dates, especially when you have enabled rrdcontext
> Handle cases where entries where stored as text (with strftime("%s"))

- daemon/main.c
- database/rrdhost.c
- database/sqlite/sqlite_context.c
Unittests (running the agent with `-W unittest` will access and/or create the `netdata-meta.db` and `context-meta.db` databases). 
This PR will allow the tests to run with in-memory databases so that those files are not created. 
- Before this PR -- install agent in the new directory and run `netdata -W unittest`. Go to the `/var/cache/netdata`  directory and notice there is a `netdata-meta.db` and `context-meta.db`
- Apply the PR and redo the test. The above mentioned files should not be created
- CI should report success on the unit tests
> Fix tests so that the actual metadata database is not accessed

- collectors/cgroups.plugin/cgroup-name.sh
Fixes: #12419
Closes: #13475
This PR adds containers name resolution for Nomad tasks. Name: "NAMESPACE-JOBNAME-TASKNAME-SHORTALLOCID".
> **Note** It works only when using the [Docker driver](https://www.nomadproject.io/docs/drivers).
---
Before this PR:
- use `docker ps ...` if `docker` command **is available** (Netdata running on the host).
- use [ContainerInspect](https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerInspect) endpoint if `docker` command **is not available** (Netdata running inside a Docker container).
This PR changes:
- use `docker inspect ...` if `docker` command **is available**. This is equivalent to the ContainerInspect endpoint (but we can apply additional formatting).
- start several Docker containers and Nomad containers.
- check their names …
> feat(cgroups.plugin): resolve nomad containers name (docker driver only)

- collectors/diskspace.plugin/plugin_diskspace.c
- collectors/proc.plugin/proc_self_mountinfo.c
- collectors/proc.plugin/proc_self_mountinfo.h
This PR adds an extra check when excluding mounts that are protected by systemd via ProtectHome and ProtectSystem. The check added is to make sure that the mount is indeed in the list of mounts protected by systemd.
Without this extra check when `/` is read-only (or appears as read-only to netdata via `ReadOnlyDirectories=/`) will be also skipped and there is no way to at least enable disk space monitoring via a configuration option.
With this check, an entry in `netdata.conf` is required:
```
[plugin:proc:diskspace:/]
space usage = yes
inodes usage = yes
```
but that seems to be [expected](https://github.com/netdata/netdata/tree/master/collectors/diskspace.plugin).
Seems a better "workaround" than what we did in #13383 .
The PR also moves the check whether a mount point is protected to a …
> Check for protected when excluding mounts

- database/sqlite/sqlite_aclk_alert.c
Adds the `chart_context` field to alert snapshots and fixes a crash.
Need to claim an agent and to "force" an alert snapshot e.g. by deleting a sequence id that hasn't been sent to the cloud from the `aclk_alert_XXXXXX` table.
The field should appear in the `aclk.log` in the `AlarmSnapshot` outgoing message.
</details>
> Add chart_context to alert snapshots

- .github/workflows/build.yml
This should fix the versioning issues we’ve been having with the release artifacts.
Relevant upstream issue reference: https://github.com/actions/checkout/issues/290
n/a
This will need to be cherry-picked into all of the existing release branches once merged.
> Explicitly fetch git ref in build workflow.

- health/health_config.c
Moves the calculation of `simple_hash` for alarms and templates after the `rrdvar_fix_name` so that if it changes the name, the hash will be calculated on the changed name rather than on the original.
Change an alarm's name so that it will be fixed, e.g. change `alarm: load_average_15` to `alarm: load average_15`.
Without this PR if you go to the dashboard and list all alerts, the badge on this one will be `alarm not found`. With this PR it should appear correctly.
</details>
> Calculate name hash after rrdvar_fix_name

- contrib/debian/netdata.postinst
- netdata-installer.sh
- netdata.spec.in
- packaging/makeself/install-or-update.sh
Fixes: #13505
The capability required for [wireguard collector](https://github.com/netdata/go.d.plugin/tree/master/modules/wireguard#wireguard-monitoring-with-netdata).
Fixed install cases:
Install and check go.d.plugin capabilities:
- deb package
- rpm package
- static build
- from source
</details>
> fix(packaging): add CAP_NET_ADMIN for go.d.plugin

- database/rrdcontext.c
- database/sqlite/sqlite_context.c
This PR uses `PRIu64` whenever it is required to print rrdcontext's version which is `uint64_t`.
Without this patch the agent might crash in 32bit distributions (at least on arm 32bit) whenever a print is made that includes the version number.
It should not change any functionality other than fix the crashes.
We need some tests on 32bit distributions. I have only checked on Raspbian 32bit, but without cloud functionality. Not sure if there is a problem on x86 32bit. I need to properly setup it to include cloud, but since rrdcontext runs even without cloud, I believe it should be ok.
1. Setup a 32bit environment. The problem exists at least on `Raspbian GNU/Linux 11` on rpi4.
2. Build the master, use `-DNETDATA_INTERNAL_CHECKS=1` which will cause rrdcontexts to print a lot of information …
> Print rrdcontexts versions with PRIu64

- netdata-installer.sh
This is a minor cosmetic change that removes an extraneous `U` from a `fatal`-level log message.
Since this is a minor cosmetic change, I have no test plan.
> Remove extra U from log message

- collectors/python.d.plugin/rabbitmq/README.md
Added some tips on collecting per-queue metrics for RabbitMQ. I had some struggles getting per-queue rmq set up, just adding some details to the permissions needed that I found unintuitive on the rmq permissions side.
> docs: add some tips on collecting per-queue metrics for RabbitMQ

- collectors/python.d.plugin/postfix/README.md
Suggested in https://community.netdata.cloud/t/advice-for-unfunctional-postfix-plugin/3172
Not needed.
</details>
> docs(postfix): add a note about `authorized_mailq_users`

- .github/workflows/build.yml
This should fix the problem with building and publishing distribution tarballs (.tar.gz) and static builds (.gz.run).
Previous fix attempt: #13508.
Wait for nighly builds I guess? @Ferroin 
</details>
> fix(ci): fix fetching tags in Build workflow

- aclk/aclk_tx_msgs.c
This allows mqtt5 (if used) to take ownership of data pointer and thus send data directly instead of having to do another malloc/memcopy/free.
The library itself will free the data now after sending has been finished (if mqtt5 used).
Cloud working OK.
</details>
> reduce memcpy and memory usage on mqtt5

- system/netdata.service.in
netdata.service: Update PIDFile to avoid systemd legacy path warning
Resolves warning logged by systemd:
systemd[1]: /lib/systemd/system/netdata.service:14: PIDFile= references a path below legacy directory /var/run/, updating /var/run/netdata/netdata.pid → /run/netdata/netdata.pid; please update the unit file accordingly.
Run the systemd service, note that it works, and no warning is logged.
No visible change except that the systemd logged warning eliminated.
See: https://www.freedesktop.org/software/systemd/man/systemd.service.html#PIDFile=
</details>
Fixes: https://github.com/netdata/netdata/issues/10304
> netdata.service: Update PIDFile to avoid systemd legacy path warning

- collectors/proc.plugin/proc_diskstats.c
Removing old LVM volumes and adding new ones causes the reuse of the devices with the lowest serial numbers. That leads to the reuse of obsolete charts with old metadata. The solution is to distinguish devices by LVM UUIDs, not by names. The UUIDs for `dm-*` (device mapper) devices can be found in `/sys/devices/virtual/block/dm-*/dm/uuid`.
Fixes #9554
1. Create a virtual block device
```
$ dd if=/dev/zero of=/tmp/lvm.test.file bs=1k count=100k
$ sudo losetup /dev/loop0 /tmp/lvm.test.file
```
2. Create an LVM Volume Group
```
$ sudo pvcreate /dev/loop0
$ sudo vgcreate vg /dev/loop0
```
3. Create/remove/create logical volumes with different names
```
$ sudo lvcreate -L 1M -n vol1 vg
$ sudo lvremove vg/vol1
$ sudo lvcreate -L 1M -n vol2 vg
...
```
4. Check if families and chart names are …
> Use LVM UUIDs in chart ids for logical volumes

- health/notifications/alarm-notify.sh.in
This PR adds the `--connect-timeout 5` curl option if not set.
---
It turns out we have no timeout set when sending notifications [using `curl`](https://github.com/netdata/netdata/blob/c3dba899af944853aaf2f4be0f7a3be24ae0e29d/health/notifications/alarm-notify.sh.in#L133).
Discovered in https://community.netdata.cloud/t/can-not-get-matrix-notifications-to-work/3198
Set any notification method that uses `curl`, and ensure that `--connect-timeout 5` is added to the options.
</details>
> fix(health): set default curl connection timeout if not set

- database/sqlite/sqlite_aclk.c
There is currently an agent, streaming to the cloud that sends an `UpdateNodeInfo` message every second.
Looking with @vkuznecovas we deduced that most likely the clock of the user is slowly drifting. At some point a timestamp sent with `UpdateNodeInfo` had the year of 2037.
The `UpdateNodeInfo` message is scheduled to go out every hour, right after the `UpdateRetention` message when `ACLK_DATABASE_UPD_RETENTION` is run. When this command is scheduled, it is then set to repeat in 3600 seconds. (Note that with rrdcontext, the `UpdateRetention` is not run, however the `UpdateNodeInfo` does).
It is repeated though by setting the value to `+ACLK_DATABASE_ROTATION_INTERVAL` which if the clock skews enough can lead to `now` being always more than the scheduled time. This PR just sets this …
> Schedule next rotation based on absolute time

- collectors/python.d.plugin/python.d.plugin.in
[python.d/dockerd](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/dockerd) was [rewritten in go](https://github.com/netdata/go.d.plugin/pull/760) (now works out of the box, no need in installing additional python libraries). 
Go version name is `docker`, and the python version is `dockerd` ("d" was added to resolve import conflict: the docker lib name is "docker"). I don't want to name go version `dockerd`, but we need to have the same so only one of them will be active at a time.
---
In addition, this PR adds a (1.5s, insignificant) delay on python.d.plugin start to reduce the chance of the python.d job running before go.d.
- Get both python and go versions of docker collector enabled
- Check the dashboard, only one data collection job should be active. …
> chore(python.d): rename dockerd job on lock registration

- coverity-scan.sh
THis should fix the fialing Coverity scan CI jobs.
n/a
> Bump Coverity version to latest (2022.06).

- health/notifications/alarm-notify.sh.in
- health/notifications/health_alarm_notify.conf
When sending too many messages in telegram bot - we can encounter rate limit and get 429 error. As a result, the message will be lost. With this proposal we'll never lose a message but try send it again after 1 second until this message could be sended or another error will appear.
FAQ about telegram limits: https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this
> Fix telegram-bot rate limit

- collectors/xenstat.plugin/xenstat_plugin.c
If xen libraries are installed but xen hypervisor isn't present on the host, the `xenstat` plugin crashes
```
==42074== Process terminating with default action of signal 11 (SIGSEGV)
==42074==  Access not within mapped region at address 0x0
==42074==    at 0x4D0F3F0: xtl_logv (in /usr/lib/x86_64-linux-gnu/libxentoollog.so.1.0)
==42074==    by 0x4D0F4B8: xtl_log (in /usr/lib/x86_64-linux-gnu/libxentoollog.so.1.0)
==42074==    by 0x4A065C0: ??? (in /usr/lib/x86_64-linux-gnu/libxenlight.so.4.16.0)
==42074==    by 0x4A067EC: ??? (in /usr/lib/x86_64-linux-gnu/libxenlight.so.4.16.0)
==42074==    by 0x49E726B: libxl_ctx_alloc (in /usr/lib/x86_64-linux-gnu/libxenlight.so.4.16.0)
==42074==    by 0x11419D: main (xenstat_plugin.c:1013)
```
We have to shut down the plugin gracefully in such cases. …
> Fix a crash when xen libraries are misconfigured

- health/health.d/mysql.conf
Fixes: #13427
This PR adds 2 changes:
- changes `absolute` option to `unaligned`.
- changes the timeframe from _last 2 minutes_ to _last 2 minutes starting 1 minute ago_. That is needed for the [warn](https://github.com/netdata/netdata/blob/331b52b94a1b19d3ad03de7560047de1a7e0f661/health/health.d/mysql.conf#L131) condition (otherwise max of last 2 minutes == current).
Set up Galera cluster, and test alerts (stop one node, wait, start the node).
<details>
<summary>set up Galera cluster using Docker</summary>
```bash
docker run -d --name mariadb-galera-0 \
-p 3306:3306 \
-e MARIADB_GALERA_CLUSTER_NAME=my_galera \
-e MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user \
-e MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password \
-e MARIADB_ROOT_PASSWORD=my_root_password \
-e …
```
> fix(health.d/mysql): adjust `mysql_galera_cluster_size_max_2m` lookup to make time in warn/crit predictable

- database/rrdset.c
We have millions of those lines on our AWS parents and it seems there is no action - these messages are just noise.
Not needed.
</details>
> chore: removing logging that a chart collection in the same interpolation point

- collectors/apps.plugin/apps_groups.conf
This is useful to help spot when someone may have been installing something or updating something on the system using `apt`
Example of is working when i did a series of 
`sudo apt install stress`
`sudo apt update`
`sudo apt upgrade`
</details>
> add `apt` to `apps_groups.conf`

- database/rrdcontext.c
Prevent this crash:
```
Core was generated by `/usr/sbin/netdata -P /run/netdata/netdata.pid'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  dictionary_lock (dict=dict@entry=0x0, rw=rw@entry=114 'r') at libnetdata/dictionary/dictionary.c:322
322	        __atomic_add_fetch(&dict->readers, 1, __ATOMIC_RELAXED);
[Current thread is 1 (Thread 0x7f31e9791640 (LWP 31389))]
(gdb) bt
#0  dictionary_lock (dict=dict@entry=0x0, rw=rw@entry=114 'r') at libnetdata/dictionary/dictionary.c:322
#1  0x000055b5b0aca04f in dictionary_get_and_acquire_item (dict=0x0, name=name@entry=0x55b5bf391cb7 "netdata.uptime") at libnetdata/dictionary/dictionary.c:1136
#2  0x000055b5b0c00e7b in rrdcontext_to_json (host=host@entry=0x55b5bf33f300, wb=0x55b5bbd8d560, after=after@entry=0, …
```
> prevent crash on rrdcontext apis when rrdcontexts is not initialized

- database/sqlite/sqlite_context.c
- database/sqlite/sqlite_functions.h
_Fixes_ #13572 
Fixes is in italic since this PR will prevent the agent from crashing if `chart_id` or `dim_id` is missing, but why they where NULL in the first place is still to be found.
Run an agent.
Go to it's sqlite db, pick a row from the `chart` or `dimension` tables and set `chart_id` or `dim_id` to NULL.
Without this PR the agent will crash
With this PR it should continue to work, albeit without loading those rows.
</details>
> Don't try to load db rows when chart_id or dim_id is null

- collectors/apps.plugin/apps_groups.conf
Add [spiceproxy](https://pve.proxmox.com/pve-docs/spiceproxy.8.html) service. Was checking the "other" dimension on the Proxmox server and found that the biggest contributor is spiceproxy (~100MB mem)
Tested locally by using updated apps_groups.conf.
</details>
> add spiceproxy to proxmox group

- web/gui/dashboard_info.js
Spotted by a user in https://community.netdata.cloud/t/inconsistent-memory-usage-of-netdata-across-graphs/3249
</details>
> fix apps plugin users charts descriptipon

- collectors/apps.plugin/apps_groups.conf
This is a sweeping set of updates to the default apps plugin configuration, with the goal of a basic install of most Linux distributions having complete coverage of all basic system services (IOW, everything under `other` on such a system should be user activity).
- The `auth` group is expanded to include sssd (used on Fedora and RHEL systems) and gssproxy, as well as properly categorizing polkitd and saslauthd as authentication tools instead of ‘system’ and ‘mail’ respectively.
- The `httpd` group now includes H2O.
- The `email` group now includes msmtp (widely used on minimalist systems, as well as in our own Docker images) and nullmailer (widely used on Debian systems).
- The `netmanager` group is expanded to include all the common network management daemons.
- A new ‘firewall’ group …
> Assorted updates for apps_groups.conf.

- database/sqlite/sqlite_aclk.c
Incremental cleanup of the chart hash map (after a week of entries not being updated)
This table will eventually be removed. This is used by the old (not context) ACLK communication. 
_The old protocol can still be used if so negotiated._
- Start the agent and notice the row count in the chart_hash / chart_hash_map table drop after a whil
> Clean chart hash map 

- daemon/global_statistics.c
Fixes the worker utilization cleanup that may cause a crash (and issue reported by the sanitizer)
```
#0 0x55a269dba80f in worker_utilization_finish daemon/global_statistics.c:1867
#1 0x55a269dba8e2 in global_statistics_cleanup daemon/global_statistics.c:1903
#2 0x55a269dbaada in global_statistics_main daemon/global_statistics.c:1917
#3 0x55a269e39372 in thread_start libnetdata/threads/threads.c:187
#4 0x7fef441a2b42 in start_thread nptl/pthread_create.c:442
#5 0x7fef442349ff  (/lib/x86_64-linux-gnu/libc.so.6+0x1269ff)
```
eg. Compile adding the following flags
`-fno-omit-frame-pointer -fsanitize=address -fno-sanitize=shift -fno-sanitize-recover=all -fno-sanitize=null -fno-sanitize=alignment -fno-omit-frame-pointer` 
- No error reported by the sanitizer in global_statistics cleanup
> Fix worker utilization cleanup

- collectors/tc.plugin/plugin_tc.c
- libnetdata/dictionary/dictionary.h
> Updated tc.plugin (linux bandwidth QoS)

- collectors/apps.plugin/apps_groups.conf
This splits the `gui` and `email` groups in the apps plugin config into a number of much smaller and more descriptive groups, as well as expanding what we cover for a number of the resultant groups. In particular:
- The `email` group has been explicitly split into two separate groups, `mta` for mail transfer agents (SMTP servers), and `mda` for mail delivery agents (IMAP/POP3 servers). The new `mda` group prrovides slightly better coverage of MDA software than the old `email` group did.
-  A new `mua` group has been added for email clients (formally Mail User Agents), covering Evolution, Thunderbird, and a selection of popular console email clients.
- A new `ntfs` group has been created, matching on NTFS-3G. This particular software is in relatively widespread usage on Linux desktop …
> Deaggregate the `gui` and `email` app groupx and improve GUI coverage.

- collectors/apps.plugin/apps_groups.conf
It’s a relatively common name on some systems, and unintentionally got removed with the recent changes to the GUI application grouping.
n/a
> apps.plugin: Re-add `chrome` to the `webbrowser` group.

- database/rrdcontext.c
- libnetdata/dictionary/dictionary.c
Fixes the first item reported in https://github.com/netdata/netdata/issues/13644
The bug was that the garbage collector was deleting contexts without removing them from the post-processing queue.
These fixes have been added:
> fix rrdcontexts left in the post-processing queue from the garbage collector

- database/rrdhost.c
When creating a host it initializes a host labels dictionary. This is not needed as the labels are 
created after the (archived) host creation on startup (this leads to a small memory leak)
```
Direct leak of 496 byte(s) in 2 object(s) allocated from:
#0 0x7f9944e1aa37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
#1 0x5555e840b069 in callocz /home/stelios/git/netdata/libnetdata/libnetdata.c:176
#2 0x5555e83e65b6 in dictionary_create_advanced /home/stelios/git/netdata/libnetdata/dictionary/dictionary.c:761
#3 0x5555e858a1c2 in rrdlabels_create /home/stelios/git/netdata/database/rrdlabels.c:526
#4 0x5555e8577c99 in rrdhost_create /home/stelios/git/netdata/database/rrdhost.c:277
#5 0x5555e857fa5b in rrdhost_find_or_create …
```
> Fix a memory leak on archived host creation

- collectors/python.d.plugin/python_modules/bases/FrameworkServices/SimpleService.py
- collectors/python.d.plugin/python_modules/bases/charts.py
Adds `_collect_job` label to pyhton.d/* charts. The label value is a data collection job name.
Check python.d/* charts labels using `/api/v1/charts`.
</details>
> add _collect_job label to python.d/* charts

- ml/Dimension.h
Recently introduced changes started removing the AR dimensions outside of the ML code. This PR removes the stale/duplicate call to `rrddim_free` for AR dimensions.
Observe no crash during shutdown when ML is enabled.
I'm a little bit puzzled as to which change introduced the double free for AR dimensions, considering that we haven't introduced any changes in ML for quite a while. I think it's safe to merge this considering the state of things. However, considering this error and the number of changes we've introduced in the agent the last couple weeks, we need to:
- Ensure that the anomaly rates charts is not sent through ACLK (@underhood or @vkalintiris),
- RRD context does not track the anomaly rates PR (currently, it's clear that it does but do we really need to process the ARs chart …
> Do not free AR dimensions from within ML.

- daemon/system-info.sh
The detection of container virtualization technology was prevented by an incorrect check for the corresponding variable.
Fixes #10568
Run `system-info.sh` in a Proxmox container. It should return `NETDATA_SYSTEM_CONTAINER=lxc`
> Fix container virtualization info

- database/engine/journalfile.c
- database/engine/journalfile.h
During agent startup if configured in with dbengine it will do a journal replay. This PR will allow the agent to mmap the journal files and replay the transactions instead of calling uv_fs_read. 
- Agent should start as usual. It will report if journal replay was done using mmap or uv_fs_read
> Use mmap if possible during startup for journal replay

- health/health.d/systemdunits.conf
Needed because of netdata/go.d.plugin#795 that changes charts from a dimension per unit to a dimension per state.
Should be merged after go.d.plugin release with the change.
Use the changed version, and check alarms.
</details>
> adjust systemdunits alarms

- daemon/global_statistics.c
- database/sqlite/sqlite_context.c
- database/sqlite/sqlite_context.h
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
Adds page cache hit / miss statistics for sqlite (under netdata moniting / sqlite3)
- Check that the new statistics chart appears
> Add sqlite page cache hit and miss statistics

- database/engine/journalfile.c
Fix an issue with dbengine journal file replay when mmap is used
- Check that the agent properly has access to older data.
> Advance the buffer properly to scan the journal file

- daemon/global_statistics.c
- Split statistics for metadata and context databases
- Add statistics for cache writes and cache spills
So now we have the following (descriptions from the sqlite documentation)
```
SQLITE_DBSTATUS_CACHE_HIT (cache hits)
Number of pager cache hits that have occurred. 
SQLITE_DBSTATUS_CACHE_MISS (cache miss)
Number of pager cache misses that have occurred.
SQLITE_DBSTATUS_CACHE_WRITE (cache writes)
Number of dirty cache entries that have been written to disk. Specifically, the number of pages written to the wal file in wal mode databases, or the number of pages written to the database file in rollback mode databases. Any pages written as part of transaction rollback or database recovery operations are not included. 
SQLITE_DBSTATUS_CACHE_SPILL (cache spills)
Number of dirty cache entries …
```
> Additional sqlite statistics

- web/gui/dashboard_info.js
Recently [merged go version](https://github.com/netdata/go.d.plugin/pull/703) and noticed we have no icon for ProxySQL collector.
Copy the changed file, and check the dashboard.
</details>
> add proxysql dashboard info

- database/rrdset.c
The label is senseless in 99% of the cases and was added mainly for network interfaces, disks, and mount points (cases where "family" is an instance). Not needed anymore because instance labels (device for network interfaces and disks, mount_point for mountpoints) were added.
ci
</details>
> remove _instance_family label

- database/sqlite/sqlite_health.c
One side effect of #13570 was to store empty strings in health tables instead of nulls. It also affected slightly the way we calculate alert hashes. This PR returns what we had previously.
There should not be any major problems without this PR, so it's mostly to protect from having duplicate alert hashes for configuration at least for stable users. It's also preferable to store NULL's in case of selects needing them.
Two tables are affected: `alert_hash` and `health_log_XXXXX`. If you've run master before and after #13570 you should find duplicate hashes in `alert_hash`. With this PR running in this, no new hashes should be created. If you delete the whole `alert_hash` table, in place of empty strings there should now be NULLs.
Similarly for the `health_log` table, new entries should now …
> Store nulls instead of empty strings in health tables

- health/health.d/go.d.plugin.conf
- health/health.d/python.d.plugin.conf
- health/health.d/timex.conf
This renames the alert classes from Error to Errors, to align with the 125 occurrences of the latter, vs. these three of the former.
> Fix inconsistent alert class names

- collectors/python.d.plugin/alarms/README.md
- collectors/python.d.plugin/alarms/alarms.chart.py
- collectors/python.d.plugin/alarms/alarms.conf
Ability to define what alarms to exclude via config. Useful if you want to have one subset of alarms in one job and then "everything else" in another job for example.
Tested locally with config like this:
```
ml:
update_every: 5
url: 'http://127.0.0.1:19999/api/v1/alarms?all'
status_map:
CLEAR: 0
WARNING: 1
CRITICAL: 2
collect_alarm_values: true
alarm_status_chart_type: 'stacked'
alarm_contains_words: 'ml_1min'
default:
update_every: 5
url: 'http://127.0.0.1:19999/api/v1/alarms?all'
status_map:
CLEAR: 0
WARNING: 1
CRITICAL: 2
collect_alarm_values: true
alarm_status_chart_type: 'stacked'
alarm_excludes_words: 'ml_1min'
```
Works as expected: 
</details>
> alarms collector: ability to exclude certain alarms via config

- ml/ml.cc
In theory, [we already cover this scenario](https://github.com/netdata/netdata/blob/06368384c10e81d15b2c5408cfeff0a29f65b47f/ml/ml.cc#L79). The new check tests if a newly created dimension belongs to the anomaly rates chart by checking directly the chart's flags.
N/A due to not being able to reproduce the bug locally.
Fixes https://github.com/netdata/netdata/issues/13694.
> Do not create train/predict dimensions meant for tracking anomaly rates.

- health/health.d/redis.conf
Part of #13691
Check new alarms on the dashboard.
</details>
> feat(health): add new Redis alarms

- database/rrddim.c
- libnetdata/buffer/buffer.c
- libnetdata/buffer/buffer.h
- streaming/rrdpush.c
We are testing a child-parent setup where the child tries to push 800k metrics / second to the parent.
Without streaming on the child, this works. It can collect 800k metrics / second for go.d.plugin.
With streaming however, the child cannot push more than 450k metrics / second.
With this PR, the child can push about 600k metrics / second to the parent, about 25% - 30% increase.
My observation is the following:
1. The code uses the shared chart flags for keeping sender flags in them. This requires atomic operations for every single chart. These can be eliminated by having a different `sender_flags` member in RRDSET and using it without atomics (there will be no data race in this case, because the sending thread is fixed for each chart - although many charts use different threads, each of …
> Faster streaming by 25% on the child

- database/sqlite/sqlite_aclk.c
On agent startup archived hosts (children) are created with dbengine memory mode. If dbengine is not compiled, 
the agent will not start. 
This PR will create the archived hosts in memory mode RAM. If tthe child connects it will pickup the specified memory mode as needed (in that case if dbengine is specified, because it is not available, it will switch to "save") 
- Setup parent child and start the agents with memory mode dbengine. 
- Stop the agents, compile the parent without dbengine and start the parent only. Notice it will not start
- Apply the PR on the parent and restart
> Do not try to start an archived host in dbengine if dbengine is not compiled

- cli/cli.c
- collectors/proc.plugin/proc_pagetypeinfo.c
- daemon/commands.c
- daemon/unit_test.c
- database/engine/journalfile.c
- database/rrdcontext.c
- database/rrddim.c
- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_aclk_alert.c
- database/sqlite/sqlite_aclk_chart.c
- database/sqlite/sqlite_health.c
- exporting/graphite/graphite.c
- exporting/json/json.c
- exporting/opentsdb/opentsdb.c
- health/health_json.c
- libnetdata/dictionary/dictionary.c
- libnetdata/json/json.c
- streaming/compression.c
Fixes #13637 
While we were developing some PRs, we brought some warnings that appear only on specific platforms. This PR is fixing issues that were appearning on `ArmVL7`. For an update report, please, take a look at  [errors](https://github.com/netdata/netdata/files/9603869/original_err.txt)
1. Compile current master branch on `Raspberry PI`, and you will see a lot of warnings.
2. Now compile this branch and verify that all warnings are gone.
In both scenarios I used the flags `CFLAGS="-Og -ggdb -Wall -Wextra -fno-omit-frame-pointer -Wformat-signedness -fstack-protector-all -Wformat-truncation=2 -Wunused-result -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1"` to compile and take a look in the warnings. …
> Fix warnings during compilation time on ARM (32 bits)

- CMakeLists.txt
- config.cmake.h.in
Self descriptive - `ccmake ..` now shows option to enable/disable ACLK
`ccmake ..` enable/disable ACLK, rebuild project
Supersedes https://github.com/netdata/netdata/pull/13656
> CMake - add possibility to build without ACLK

- database/sqlite/sqlite_aclk_alert.c
- health/health_json.c
Fix Coverity report:
```sh
*** CID 380995:    (Y2K38_SAFETY)
/health/health_json.c: 405 in have_recent_alarm()
399     
400     static int have_recent_alarm(RRDHOST *host, uint32_t alarm_id, time_t mark)
401     {
402         ALARM_ENTRY *ae = host->health_log.alarms;
403     
404         while(ae) {
>>>     CID 380995:    (Y2K38_SAFETY)
>>>     A "time_t" value is stored in an integer with too few bits to accommodate it.  The expression "mark" is cast to "unsigned int".
405             if (ae->alarm_id == alarm_id && ae->unique_id > (unsigned int) mark &&
406                 (ae->new_status != RRDCALC_STATUS_WARNING && ae->new_status != RRDCALC_STATUS_CRITICAL))
407                 return 1;
408             ae = ae->next;
409         }
410         return 0; …
```
> Change cast to remove coverity warnings

- packaging/installer/kickstart.sh
Instead of just checking whether the `$tmpdir` variable is set and short-circuiting if it is, we should additionally check if the directory it references exists. This ensures that code that needs to use temporary directories can do so even if earlier code calls `cleanup()`.
See the steps to reproduce in #13741. When they are attempted using the kickstart script from this PR, things should work correctly instead of failing as outlined in that issue.
Fixes: #13741
> Fix handling of temporary directories in kickstart code.

- packaging/docker/README.md
Inspired by discussion in https://github.com/netdata/netdata-cloud/issues/567.
We are not including this by default as it causes problems if users run multiple Netdata containers on the same node.
Directly mounting the hostname file was chosen as the suggested approach because it’s the most robust option and does not rely on using specific tools for creating or starting the container.
n/a
> Add info for Docker containers about using hostname from host.

- daemon/service.c
- database/rrdhost.c
During a parent child setup, if the child disconnects and the parent removes it's data from memory (default 3600 seconds)
when the child tries to reconnects the parent will crash
- Setup a parent and child, configure the parent with a short child removal 
-  e.g `cleanup orphan hosts after seconds = 30`
- Start the parent and child
- Disconnect the child and wait for the child to be removed from memory
- Notice a message in the error.log such as
`Host 'xxxxx' with machine guid 'xxxxxx' is obsolete - cleaning up.`
- Restart the child and notice the crash
- Retest after applying the PR
> Fix streaming crash when child reconnects and is archived on the parent

- packaging/installer/netdata-updater.sh
The netdata updater also doesn't have CloudLinux OS detection, thus resulting in a warning when installing.
`WARNING: netdata-updater.sh:  We do not provide native packages for cloudlinux.`
Tested as working on our CloudLinux machines
Related to: #13750
> Add CloudLinux OS detection to the updater script

- health/health.d/tcp_resets.conf
Fixes: #13742
Tested locally
</details>
> add 1m delay for tcp reset alarms

- .gitignore
- build/subst.inc
- configure.ac
- packaging/installer/functions.sh
- system/Makefile.am
- system/install-service.sh.in
This is a comprehensive overhaul of how we handle installation of the Netdata agent as a system service.
It involves the following changes:
- The templated files from `system/` are now installed to `/usr/lib/netdata/system`, allowing them to be utilized by scripts in the installed system instead of requiring them to be handled by the install script.
- A new script named `install-service.sh` has been added. It gets installed to `/usr/libexec/netdata` and bundles all of the logic for detecting what init system or service manager is in use and then actually installing the appropriate service files. It also supports providing information about how to properly start or stop the agent as a system service.
- The installer code has been updated to use the aforementioned script when it is present, …
> Overhaul handling of installation of Netdata as a system service.

- libnetdata/socket/security.c
When we modified `ssl` variables, there was one that were not modified and it affects all ancient versions of OpenSSL. This PR is renaming it.
1. Compile `netdata` on `CentOS 7.9` and verify it is compiled with success, another possibility is to take a look in our CI for this distribution.
- Which area of Netdata is affected by the change? Webserver and streaming
- Can they see the change or is it an under the hood? If they can see it, where? only if they use TLS.
- How is the user impacted by the change?  Users are able to compile netdata against ancient TLS versions.
- What are there any benefits of the change?  Fix a bug.
</details>
> Rename variable for old CentOS version

- aclk/aclk.c
- aclk/aclk_otp.c
@MrZammler identified bug on 32 bit systems 🙇🏻‍♂️  with keep-alive (long int is different size), this brings his fix into netdata.
Meanwhile mqtt_websockets got basic proxy auth support, this bump brings those changes too so minimal changes in agent were done to reflect the new API
connection on 32 bit RPi should be more stable
</details>
> Bump websockets submodule

- daemon/main.c
Fixes: #12736
The main (and probably only) reason for this feature I have in mind is to be able to disable Cloud (read as remove Cloud UI elements from the dashboard) when using the Docker version of Netdata.
With that said, maybe we better update the [entrypoint file](https://github.com/netdata/netdata/blob/master/packaging/docker/run.sh), but not sure.
- Build a docker image with enabled Cloud.
- `docker run -d --name nd -p 19999:19999 --env NETDATA_DISABLE_CLOUD=1 ilyam8/netdata-test`.
- `docker run -d --name nd -p 19999:19999 ilyam8/netdata-test`.
- Build a docker image with disabled Cloud.
- `docker run -d --name nd -p 19999:19999 --env NETDATA_DISABLE_CLOUD=1 ilyam8/netdata-test`.
- `docker run -d --name nd -p 19999:19999 ilyam8/netdata-test`.
In all cases check the dashboard and …
> feat: disable cloud if `NETDATA_DISABLE_CLOUD` is set to 1

- aclk/aclk_tx_msgs.c
- daemon/global_statistics.c
- daemon/main.c
- daemon/service.c
- database/engine/journalfile.c
- database/engine/rrdengine.c
- database/ram/rrddim_mem.c
- database/rrd.h
- database/rrdcontext.c
- database/rrddim.c
- database/rrdhost.c
- database/rrdset.c
- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_functions.c
- libnetdata/arrayalloc/arrayalloc.c
- libnetdata/arrayalloc/arrayalloc.h
- libnetdata/config/appconfig.c
- libnetdata/config/appconfig.h
- libnetdata/dictionary/dictionary.c
- libnetdata/libnetdata.c
- libnetdata/libnetdata.h
- libnetdata/procfile/procfile.c
- streaming/receiver.c
- streaming/rrdpush.c
- streaming/rrdpush.h
- web/api/web_api_v1.c
This PR tracks all `mallocz()`, `callocz()`, `reallocz()`, `strdupz()` and `freez()` calls, per function calling them, and generates 4 charts in the Netdata Monitoring section:
- total currently memory allocated per function
- total currently memory allocations per function
- average memory allocation per function (based on the currently allocated memory)
- rate of operations per function
To enable it, compile netdata with `-DNETDATA_TRACE_ALLOCATIONS=1`. It is slower that running without it, so it is only available as a compile time option.
It works like this:
While implementing this, I found that a few modules of netdata do not use these functions, or mix these functions with the libc ones:
Example charts generated:
---
It all started this this forum thread: …
> full memory tracking and profiling of Netdata Agent

- database/rrdset.c
- health/health.c
Fixes #13781 
This PR brings back the initialization of `st->rrdvars` to be done during the `rrdset_insert_callback`.
If left to be initialized during health, it will delay, and `rrdsetvar_update_rrdvars_unsafe` will not find `st->rrdvars` to populate it.
On a build from master, check e.g. chart `system.active_processes`. Notice it's missing `chart_variables`. With this PR, it should have there a `pidmax`.
Similarly, please test with a pi-hole installation. There should be a `file_exists` (not sure of the exact name) chart variable under the `pihole.blocklist_last_update`.
Not sure if we need to also move back initialization of `st->rrdfamily` and `rrddimvar_index_init(st);` back there as well. Most likely yes, but haven't tested yet.
<details> <summary>For users: How does this change …
> Initialize st->rrdvars from rrdset insert callback

- database/engine/pagecache.c
- libnetdata/arrayalloc/arrayalloc.c
- libnetdata/arrayalloc/arrayalloc.h
- libnetdata/log/log.h
> Array Allocator Memory Leak Fix

- collectors/python.d.plugin/python_modules/bases/FrameworkServices/SimpleService.py
- collectors/python.d.plugin/python_modules/bases/charts.py
Implements part of #13788
Run python.d with/without NETDATA_INTERNALS_MONITORING set.
</details>
> feat(python.d): respect NETDATA_INTERNALS_MONITORING

- collectors/plugins.d/pluginsd_parser.c
- collectors/plugins.d/pluginsd_parser.h
- database/engine/metadata_log/logfile.c
- database/engine/metadata_log/metalogpluginsd.c
- database/engine/metadata_log/metalogpluginsd.h
- parser/parser.c
- parser/parser.h
- streaming/receiver.c
Removes the need to have to register a keyword and an action separately. A function registered with a keyword will need to do the parsing and the actual work needed.
> Parser cleanup 

- health/health.c
Brings back initialization of rrdvars that was removed with #13786
</details>
> Also enable rrdvars from health

- libnetdata/dictionary/dictionary.c
Return the memory freed properly depending on the DICT_OPTION_VALUE_LINK_DONT_CLONE dict option
- N/A
> Return memory freed properly

- libnetdata/arrayalloc/arrayalloc.c
We did several tests to find how RSS and VM size of netdata are affected by ARAL, that allocates dbengine page descriptors.
We found that VM size grows significantly with the default ARAL max size of 10MB, compared to plain `mallloc()`.
On our tests we got the same VM size with malloc and ARAL, for max allocation size of up to 256k.
We decided to go with 64k as a safe option that should work as expected among different libc versions and operating systems.
> ARAL optimal alloc size

- database/rrdhost.c
- health/health.c
- health/health.h
This allows the user to mark the node as ephemeral or as a node with an unstable connection. This will be used by the cloud to know for example it can delete this node more quickly from the list etc.
Fixes https://github.com/netdata/netdata/issues/13160
`/api/v1/info`
</details>
> minor - add host labels for ephemerality and nodes with unstable connections

- .github/data/distros.yml
- .github/scripts/pkg-test.sh
- packaging/PLATFORM_SUPPORT.md
Expected release date is 2022-10-20.
n/a
Depends on: https://github.com/netdata/netdata/pull/13787
> Add Ubuntu 22.10 to supported distros, CI, and package builds.

- .github/data/distros.yml
- packaging/PLATFORM_SUPPORT.md
Tentative beta release date is no earlier than 2022-09-13.
Tentative full release date is no earlier than 2022-10-18
The Netdata team will officially start supporting Fedora 37.
</details>
> Add Fedora 37 to CI and package builds.

- aclk/aclk_otp.c
In case of failed decryption of challenge there was a wrong freez called.
```
In function 'freez',
inlined from 'aclk_get_otp_challenge' at aclk/aclk_otp.c:383:9,
inlined from 'aclk_get_mqtt_otp' at aclk/aclk_otp.c:503:9,
inlined from 'aclk_attempt_to_connect' at aclk/aclk.c:566:15:
libnetdata/libnetdata.c:275:5: warning: 'free' called on unallocated object 'challenge' [-Wfree-nonheap-object]
275 |     free(ptr);
|     ^
libnetdata/libnetdata.c: In function 'aclk_attempt_to_connect':
aclk/aclk_otp.c:493:20: note: declared here
493 |     unsigned char *challenge;
|                    ^
```
</details>
> fix warning when -Wfree-nonheap-object is used

- aclk/aclk.c
- collectors/apps.plugin/apps_plugin.c
- collectors/checks.plugin/plugin_checks.c
- collectors/ebpf.plugin/ebpf.c
- collectors/ebpf.plugin/ebpf_cachestat.c
- collectors/ebpf.plugin/ebpf_dcstat.c
- collectors/ebpf.plugin/ebpf_disk.c
- collectors/ebpf.plugin/ebpf_fd.c
- collectors/ebpf.plugin/ebpf_filesystem.c
- collectors/ebpf.plugin/ebpf_hardirq.c
- collectors/ebpf.plugin/ebpf_mdflush.c
- collectors/ebpf.plugin/ebpf_mount.c
- collectors/ebpf.plugin/ebpf_process.c
- collectors/ebpf.plugin/ebpf_shm.c
- collectors/ebpf.plugin/ebpf_socket.c
- collectors/ebpf.plugin/ebpf_softirq.c
- collectors/ebpf.plugin/ebpf_swap.c
- collectors/ebpf.plugin/ebpf_sync.c
- collectors/ebpf.plugin/ebpf_vfs.c
- collectors/statsd.plugin/statsd.c
- daemon/global_statistics.c
- daemon/global_statistics.h
- daemon/main.c
- daemon/static_threads.c
- daemon/static_threads.h
- daemon/static_threads_linux.c
- exporting/send_internal_metrics.c
This PR adds the netdata.conf option:
```
[plugins]
netdata monitoring = yes | no
```
It disables global statistics of Netdata Agent.
Users may need to disable netdata internal monitoring to lower the number of collected metrics, thus lowering the memory and CPU footprint of Netdata Agents.
An environment variable is exposed to let the plugins know:
```
NETDATA_INTERNALS_MONITORING=YES|NO
```
When set to `NO`, plugins are expected to disable reporting of their internal metrics.
@thiagoftsm @ilyam8 please help me finish this. I can't do the rest. You can check apps.plugin to see what you need to do.
> allow disabling netdata monitoring section of the dashboard

- aclk/aclk.c
- aclk/aclk.h
- database/rrd.h
- database/rrdhost.c
- streaming/receiver.c
Fixes https://github.com/netdata/netdata-cloud/issues/598
The above image on cloud, on Home tab, shows the current status of streaming for the nodes on that room.
The number of parents is taken from the count of host's labels `_is_parent = true`, and of the children from the same label being `false`.
Currently we mark a localhost as a parent just because it has been configured as a parent, or there are more than one hosts in memory.
We would like instead to show there as parent only those hosts that are currently receiving metrics from other hosts. This PR adds a counter on localhost of how many senders are currently streaming to it. Depending on this counter it will adjust the `_is_parent` label, and send an `UpdateNodeInfo` message to send it to the cloud.
Observe the above part of the …
> Count currently streaming senders on the localhost

- packaging/installer/kickstart.sh
Due to issues relating to https://github.com/netdata/netdata/issues/13242, install type detection for existing installs is broken on some systems. This fixes things so that the detection works correctly on such systems without needing to fix the root cause.
This can be tested by running the kickstart.sh script on a FreeBSD or macOS system that has an existing install of the agent created by running the kickstart script.
Using the kickstart script in the master branch, this will throw an error due to not being able to identify the install type.
Using the kickstart script from this PR, it will correctly detect the install type and proceed normally.
Relevant to (but does not completely fix): https://github.com/netdata/netdata/issues/13230
<details> <summary>For users: How does this change …
> Fix existing install detection for FreeBSD and macOS.

- collectors/fping.plugin/README.md
Also adds a bit more info about installing it on systems that don’t provide it.
n/a
> Update fping plugin documentation with better details about the required version.

- database/engine/rrdengineapi.c
Updates the reference count on the storage handle
Does not release the storage handle since it is needed to commit data
- Use a clean setup (remove files under /var/cache/netdata)
- Set up parent child with the parent having 
```
cleanup obsolete charts after seconds = 30
cleanup orphan hosts after seconds = 30
delete obsolete charts files = yes
delete orphan hosts files = yes
```
- Start the parent and the child and let it run for a few seconds
- Stop the child and wait until the parent sets it to archive mode 
- Start the child, notice the parent will crash
- Repeat the test and this time stop and restart the parent while observing the dashboard
- Notice that after each stop and restart data may be missing from the dashboard 
---
- Apply the PR and retest
> Fix crash on child reconnect and lost metrics

- .github/codeql/python-config.yml
- .github/workflows/codeql.yml
This currently is limited to checking C/C++ code and Python code. Analysis is run on PRs, pushes to the master branch, and as a scheduled run every Monday morning.
The PR checks include special logic to skip checking files for languages that have no changes in the PR unless the PR is labelled with a label named `ci/codeql`.
The full checks will run on this PR due to the presence of the label mentioned above.
The Python checking has been intentionally limited to only caring about the code that actually goes to end users so we don’t waste time on things like build scripts.
> Add a CodeQL analysis workflow.

- health/health.d/pihole.conf
As we [found out](https://github.com/netdata/netdata/issues/13781#issuecomment-1277864715), the `gravity.list` file has been removed (2019 or earlier). The metric removed in netdata/go.d.plugin#914
n/a
</details>
> chore(health): rm pihole_blocklist_gravity_file_existence_state

- packaging/installer/functions.sh
- system/install-service.sh.in
- Fixed false reports of failed service installation.
- Fixed excessively verbose deferred warnings for failure to install the agent as a system service.
- Added explicit support for [systemd in WSL](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/). Currently handled via a relatively naive approach of checking for a usable systemd setup if we detect we’re running in WSL and then updating the detected service manager type appropriately.
- Improved OpenRC detection to be more efficient. Additionally, when checking for OpenRC we now explicitly check for the commands we need being present, and also check for an additional common indicator that the system uses OpenRC.
- Fixed issues with the runit detection. We no longer require `/lib/rc/sv.d`, as that was …
> Further improvements to the new service installation code.

- .github/workflows/review.yml
Labels that are being checked are of the general form `ci/name`, where `name` is the name of the linting tool to be run.
Note that all the Review jobs run on this PR, even though only actionlint and yamllint would normally run.
Primarily intended to allow forcing the checks to run due to incomplete matches for detecting relevant changes.
> Add PR labels to force running Reviewdog checks.

- CMakeLists.txt
- Makefile.am
- aclk/helpers/mqtt_wss_pal.h
- aclk/helpers/ringbuffer_pal.h
- aclk/schema-wrappers/connection.cc
- aclk/schema-wrappers/node_connection.cc
- aclk/schema-wrappers/node_creation.cc
- aclk/schema-wrappers/node_info.cc
Allows the specialized netdata memory functions/macros to be used from within mqttwebsockets and its children. Supported is MQTT5 implementation.
MQTT3 will be removed soon and therefore not implemented there.
Build with/without trace allocations
</details>
> Inject costallocz to mqtt_websockets library and its children

- system/install-service.sh.in
Instead of using the correct path for installing the system service file, we were always hard-coding `/etc/init.d/netdata`. This happened to work correctly on Linux, but obviously breaks horribly on FreeBSD.
Without this PR, installing on FreeBSD will not properly configure the Netdata agent as a system service.
With this PR, installing on FreeBSD will correctly set up the Netdata agent as a system service.
> Fix service installation on FreeBSD.

- database/rrddim.c
- database/rrdset.c
The calculation of tiers update every is wrong with 2 results:
1. tier2 becomes totally invalid
2. changing data collection frequency on the fly is wrong for tier1 and tier2
Fixed both of them.
> fix tiers update frequency

- .github/workflows/packaging.yml
Instead of requiring a specific string in the PR body, use the presence of a PR label to trigger running all the packaging CI jobs.  This is more robust, more secure, and also provides a much cleaner way for maintainers to trigger the CI jobs on contributor’s PRs.
The specific label used for this is `ci/packaging`
Observe that all packaging jobs ran on this PR because of the presence of the above-mentioned label.
> Use PR label to trigger full packaging CI instead of PR body contents.

- system/netdata-freebsd.in
- system/netdata-init-d.in
- system/netdata-lsb.in
- system/netdata-openrc.in
Followup to #13780.
This fixes most of the init script types.
Install from this branch as a non-root user, and confirm that the agent rusn as the proper user when started as a system service.
> Fix runtime directory ownership when installed as non-root user.

- packaging/installer/functions.sh
- packaging/installer/kickstart.sh
- packaging/installer/netdata-updater.sh
This should result in errors in these scripts being properly deaggregated, instead of being always reported as ‘generic’ failures, thus simplifying diagnosis of end-user problems with the installation or update process.
These changes can most easily be tested by running the kickstart script on a system with an existing Netdata install when it is known that the updater script will exit with a failure code.
Without this PR, the kickstart script should provide only a non-specific error message at the end in the list of deferred warnings.
With this PR, the kickstart script should provide both the above-mentioned non-specific message, as well as a more specific message from the updater script in the list of deferred warnings.
This provides more concrete messaging to users when a failure …
> Properly propagate errors from installer/updater to kickstart script.

- system/install-service.sh.in
The service installation code supports installing the agent as a system service for systemd or OpenRC on offline systems (that is, those not booted into those service managers), but in a number of places it was either blindly assuming the service manager was online or not properly checking that it was online. This PR fixes those cases, ensuring that installation in these cases proceeds correctly.
Testing for the OpenRC code can be done easily using the `gentoo/stage3:latest` Docker image. Without this PR, installation should fail to start the agent properly. With this PR, it should start the agent properly, albeit not as a system service.
Systemd testing is much more complicated, as I have not found a Docker image that provides an offline systemd installation. The easiest approach here is …
> Properly guard commands when installing services for offline service managers.

- aclk/aclk.c
- aclk/aclk.h
- daemon/main.c
- daemon/static_threads.c
- database/rrd.h
- database/rrdhost.c
- database/sqlite/sqlite_aclk_alert.c
- database/sqlite/sqlite_health.c
- health/health.c
- health/health.h
- health/health_config.c
- libnetdata/log/log.c
- libnetdata/log/log.h
- streaming/receiver.c
This PR runs a health thread per host. It's main purpose it so simplify a bit the health loop, and do the following:
1) Remove the health initialization from the host creation. This should speed up the latter.
2) Allow each host's health checks not to be delayed by another host's checks.
3) Skip on a host lock during the health loop.
4) We can have different health loop intervals per host.
5) When a child host is disconnected (but the host is in memory), nothing to run for it during the health loop.
6) Have a separate health.log file with related health logging.
7) Better functionality from aclk health (e.g. removed events now will be sent only for affected host).
8) Provide a base to further simplify/clean health (e.g. remove saving health log to files).
I'm not dead set on merging it if …
> Health thread per host

- collectors/proc.plugin/proc_net_dev.c
When a network interface is down, `carrier`, `duplex`, and `speed` files are not present in `proc` filesystem for this interface. We shouldn't stop trying to read them permanently. We will retry reading them every minute instead.
Fixes #13673
> Retry reading carrier, duplex, and speed files periodically

- web/api/web_api_v1.c
Anomalies Tab on cloud is broken as it calls `ml_info` endpoint which was not allowed to be accessed using ACLK in https://github.com/netdata/netdata/pull/13720
Go to  production cloud where your node lives and access anomalies tab. In debug console of browser you should see:
- before this PR `ml_info` URL will return failed request
- after this PR OK
</details>
> add ACLK access to ml_info (fix anomalies tab in cloud)

- collectors/cgroups.plugin/cgroup-network-helper.sh
Fixes: #13865
Tested the updated `sed` match expression manually.
</details>
> fix(cgroup.plugin): handle qemu-1- prefix when extracting virsh domain

- configure.ac
Fixes #13527 
This PR check for the C compiler vendor, and if it's `clang` sets `ar` and `ranlib` to `llvm-ar` and `llvm-ranlib`. It should fix the linker problem on FreeBSD with clang and lto enabled.
Need to cover various compile setups, i.e. a mix of Systems (FreeBSD/Linux) with compilers (clang/gcc) and enabled or disabled LTO.
Compiling on FreeBSD with gcc and LTO enabled, doesn't work. I think it's because `ar` and `ranlib` are not linked to gcc's one (whereas on Linux I believe it does). When installing gcc it includes e.g. `gcc-ar11` but not sure if we need to explicitly set configure to use that...
Not a configure expert, so if there is a better way to do it, please let me know!
</details>
> Use llvm's ar and ranlib when compiling with clang

- database/engine/rrdengine.c
- database/engine/rrdengine.h
Try to use mmap to read an extent from a datafile. If mmap fails, fallback to the usual uv_fs_read operation. 
Using mmap saves us from one additional malloc / free as the data will be decompressed directly from the mmaped region of the file. 
- No visual change in the operation of the agent. If you compile with `TRACE_ALLOCATIONS` you will notice less malloc operations assosiated with reading extents from the datafiles.
> Use mmap to read an extent from a datafile
