web/api/web_api_v1.c
Fixes https://github.com/netdata/netdata-cloud/issues/434
When a single chart was given in a context query, the query engine mistakenly was turning the query from a context query to a chart query.
When both chart and context are given, the query engine now run the query as a context one, with a chart filtering.
=> allow single chart to be filtered in context queries

database/rrdcalc.c
When a chart becomes obsolete and we create a REMOVED event, when the agent shutsdown it creates another REMOVED event on top of that during the unlink procedure.
This PR adds a check to prevent from creating a second REMOVED if the alarm status is already REMOVED.
1) Mount a storage device
2) Start netdata, make sure it creates an alert for it. (e.g. disk space)
3) Unmount the device.
4) There should be a REMOVED event for that device's alert.
5) Shutdown the agent. Without this PR there will be another REMOVED event. With this PR there should not.
</details>
=> Don't create a REMOVED alert event after a REMOVED.

collectors/apps.plugin/apps_plugin.c
=> apps.plugin function processes cosmetic changes

system/netdata-openrc.in
- Get rid of `NETDATA_START_AFTER_SERVICES`. OpenRC already provides a robust configuration system for managing service dependencies, including overrides. The variable itself thus provides no real benefit but makes the script somewhat harder to read, so this PR removes it and just sets the default `after` list to what we had been using as the default value of the variable.
- Add less ambiguous and more accurate descriptions for the `reload`, `rotate`, and `save` commands. This way they concretely describe exactly what they are doing using standard terminology typically seen in other OpenRC scripts.
- Add the ability to use `netdatacli` for the above mentioned commands instead of `start-stop-daemon`. This is controlled by a new variable called `NETDATA_USE_NETDATACLI` variable, which, if …
=> Assorted cleanup in the OpenRC init script.

Makefile.am
This PR suppresses ml and dlib ABI warnings that appear on some local builds, such as the one reported in https://github.com/netdata/netdata/issues/13820 .
The warnings aren't useful to us since all involved object files are compiled using the same compiler version, so we are not crossing library boundaries in this particular case (i.e. linking to libraries built using a much older compiler with a different ABI).
Similar warnings show up when building `protobuf`, which needs to be fixed in a separate PR.
Try a local build with dlib library present and `--enable-ml`. There shouldn't be any warnings when compiling ml and dlib, such as there are on `master`. Try on a 32-bit Rapsbian if possible, since the warnings definitely appear there : 
```
/usr/include/c++/10/bits/stl_algo.h:1318:5: …
```
=> Suppress ML and dlib ABI warnings

.github/data/distros.yml
The file listed the incorrect repository name for the Fedora 36 entry.
n/a
=> Fix typo in CI distribution data file.

packaging/installer/kickstart.sh
The `F0106` error code was being used in two unrelated places. Fix this by updating the less commonly encountered instance to a different code.
n/a
=> Fix duplicate error code in kickstart.sh.

collectors/proc.plugin/proc_net_dev.c
`speed_file_exists` and `speed_file_lost_time` are used when deciding if we need to retry reading network interface speed. We should reset the flags only when the speed is successfully read.
Changes are straightforward, don't plan to test them. 
</details>
=> fix(proc.plugin): fix read retry logic when reading interface speed

database/rrdhost.c, health/health.c
The health init function was dropped by accident. This restores it and make sure the `[health]` enable configuration 
option is respected
Attempt to configure agent with health disabled before and after this PR
=> Fix reading health "enable" from the configuration

packaging/installer/kickstart.sh
This way we can differentiate what type of thing users were trying to do for a given run of the kickstart script.
This adds a new parameter to telemetry events called `install_command` on the PostHog install events. Currently possible values for this and their meanings are:
- `default`: Used when no specific operation has been requested.
- `reinstall`: User requested a regular reinstall.
- `reinstall-clean`: User requested a clean reinstall.
- `unsafe-reinstall`: User requested a reinstall, even if it would be considered unsafe.
- `claim-only`: User required that the kickstart script only try to claim an existing install.
- `uninstall`: User requested that an existing install be uninstalled.
- `repositories`: User requested that only repository configuration be installed.
- …
=> Record installation command in telemetry events.

aclk/README.md, aclk/aclk.c, aclk/aclk.h, aclk/aclk_alarm_api.c, aclk/aclk_query_queue.c, aclk/aclk_tx_msgs.c
As we use MQTT 5 for multiple months and it is deemed stable enough now it is time to remove the feature to use MQTT 3. This allows also cleanup in mqtt_websockets library after the next stable release (with this PR in).
Reason: There is no real benefit to using MQTT 3 over MQTT 5 for user. Actually MQTT 3 is more problematic. We allowed MQTT 3 usage until now only as fallback until confidence in stability of new MQTT 5 implementation was high enough.
- MQTT 5 is always used
- nothing explodes
</details>
=> Remove option to use MQTT 3

collectors/python.d.plugin/sensors/README.md
RPi temperatures not possible with this plugin, add a note to point to the bash one
=> Reference the bash collector for RPi

packaging/installer/kickstart.sh
Instead of blindly claiming a lack of support when dealing with an install of an unknown type and not running a reinstall:
- If the `--claim-only` option was provided, just continue and attempt to claim the install.
- If the `--claim-only` option was not specified, and we’re running interactively, prompt the user about whether they want to continue or not, warning them that the update may break things.
- If the `--claim-only` option was not specified, and we’re not running interactively, throw a fatal error just like we are already doing.
- In both of the above two cases, add info about the existence of the `--claim-only` option to the user-visible messaging.
This should significantly reduce the number of users getting stuck trying to claim installs made through third-party package …
=> Prompt users about updates/claiming on unknown install types.

database/rrdcontext.c
The new query engine did a match on the timeframe requested, but it didn't take into account the update frequency of the chart. Fixed it.
=> timeframe matching should take into account the update frequency of the chart

database/rrdhost.c
Fixes this crash:
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140437224445504) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140437224445504) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140437224445504, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fba27772476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fba277587f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000556594534f61 in crash_netdata () at libnetdata/log/log.c:867
#6  0x00005565945352af in fatal_int (file=0x556594be9e30 "libnetdata/dictionary/dictionary.c", function=0x556594bec8f0 <__FUNCTION__.28> "api_internal_check_with_trace", line=1630, fmt=0x556594bea8a8 "DICTIONARY: attempted to %s() but dict is NULL") at …
```
=> do not free hosts if a change on db mode is not needed

contrib/debian/netdata.postinst, netdata-installer.sh, netdata.spec.in, packaging/makeself/install-or-update.sh
The capability required for [ping collector](https://github.com/netdata/go.d.plugin/tree/master/modules/ping#ping-monitoring-with-netdata).
Install and check go.d.plugin capabilities:
- deb package
- rpm package
- static build
- from source
</details>
=> feat(packaging): add CAP_NET_RAW to go.d.plugin

collectors/ebpf.plugin/ebpf_cachestat.c, collectors/ebpf.plugin/ebpf_cgroup.c, collectors/ebpf.plugin/ebpf_cgroup.h, collectors/ebpf.plugin/ebpf_dcstat.c, collectors/ebpf.plugin/ebpf_fd.c, collectors/ebpf.plugin/ebpf_oomkill.c, collectors/ebpf.plugin/ebpf_process.c, collectors/ebpf.plugin/ebpf_shm.c, collectors/ebpf.plugin/ebpf_socket.c, collectors/ebpf.plugin/ebpf_swap.c, collectors/ebpf.plugin/ebpf_vfs.c
This PR fix:
```sh
2022-10-23 03:18:30: netdata ERROR : PLUGINSD[ebpf] : (0258@collectors/plugins.d:pluginsd_dimens): requested a DIMENSION, without a CHART, on host 'box'. Disabling it.
2022-10-23 03:18:30: netdata IERR  : PLUGINSD[ebpf] : (0337@parser/parser.c     :parser_action  ): action_function() failed with rc = 2
2022-10-23 03:18:30: netdata IERR  : PLUGINSD[ebpf] : (0348@parser/parser.c     :parser_action  ): parser_action() failed.
2022-10-23 03:18:30: netdata ERROR : PLUGINSD[ebpf] : (0133@collectors/plugins.d:pluginsd_worker): '/usr/libexec/netdata/plugins.d/ebpf.plugin' (pid 21184) disconnected after 59773 successful data collections (ENDs).
2022-10-23 03:18:34: netdata ERROR : PLUGINSD[ebpf] : (0412@libnetdata/popen/pop:netdata_pclose ): child pid 21184 exited with code 15. …
```
=> Fix systemd chart update (eBPF)

.github/data/distros.yml, packaging/PLATFORM_SUPPORT.md
To be merged on 2022-11-01 when it goes EOL upstream.
n/a
As of 2022-11-01, Alpine Linux 3.13 will no longer be officially supported by the Netdata team.
</details>
=> Remove Alpine 3.13 from CI and official support.

database/ram/rrddim_mem.c
ssia
Compile with `--disable-dbengine`.
</details>
=> fix compiling without dbengine

libnetdata/log/log.c, libnetdata/log/log.h, libnetdata/socket/socket.c
This PR adds the function:
```c
error_limit(ERROR_LIMIT *erl, const char *format, ...);
```
The `ERROR_LIMIT *erl` parameter can be defined as either global static variable (so that all threads logging will share the same limits) with this:
```c
error_limit_static_global_var(var, log_every_secs, sleep_usecs);
```
or thread static variable (so that each thread will have its own log limits), with this:
```c
error_limit_static_thread_var(var, log_every_secs, sleep_usecs);
```
It can be used like this:
```c
error_limit_static_global_var(erl, 10, 1000);
error_limit(&erl, "POLLFD: LISTENER: too many open files - used by this thread %zu, max for this thread %zu",
p->used, p->limit);
```
The `error_limit()` function will:
1. Sleep the defined amount of time, if `sleep_usecs` is not zero.
2. Lock …
=> error_limit() function to limit number of error lines per instance

collectors/plugins.d/pluginsd_parser.c, database/engine/rrdengineapi.c, database/rrd.h, database/rrdcontext.c, database/rrddim.c, database/rrdset.c
Prevent dimensions from vanishing while replication is running on them.
Fixes this SIGSEGV:
```
#0  0x00005648d37246dc in rrdeng_store_metric_next (collection_handle=0x0, point_in_time_ut=1667313623000000, n=nan(0x8000000000000), min_value=0, max_value=0, count=1, anomaly_count=0, flags=SN_FLAG_NOT_EXISTS_MUL100)
at database/engine/rrdengineapi.c:453
#1  0x00005648d35f9a2b in rrddim_store_metric (rd=0x56497aa7cc20, point_end_time_ut=1667313623000000, n=nan(0x8000000000000), flags=SN_FLAG_NOT_EXISTS_MUL100) at database/rrdset.c:1073
#2  0x00005648d35cb4d0 in pluginsd_replay_set (words=0x7f17460fb890, num_words=4, user=0x7f17460ff5b0, plugins_action=0x56497998e000) at collectors/plugins.d/pluginsd_parser.c:1060
#3  0x00005648d3753995 in parser_action (parser=0x564979977d90, …
```
=> Rrddim acquire on replay set

collectors/statsd.plugin/statsd.c, libnetdata/dictionary/README.md
The original dictionaries were supporting concurrent lockless multi-threaded use, under certain conditions.
With the addition of reference counters, these use cases are no longer supported. All multi-threaded uses of dictionaries should use multi-threaded dictionaries.
This PR makes statsd use multi-threaded dictionaries.
=> Statsd dictionaries should be multi-threaded

packaging/installer/kickstart.sh
- IDs are now tagged with the way they were generated. This will allow differentiation between duplicate IDs resulting from cloning of systems and those that are duplicates due to collisions.
- On macOS, try asking the IOKit registry for the machine ID. Unlike `/etc/machine-id` this will usually work correctly and avoid falling back to uuidgen.
- If `/etc/machine-id` does not exist, try the legacy paths for DBus machine IDs before falling back to uuidgen. This will often work on non-systemd systems (including some BSD installs).
n/a
=> Overhaul generation of distinct-ids for install telemetry events.

collectors/plugins.d/pluginsd_parser.c, streaming/replication.c, streaming/rrdpush.c
Some 32-bit machines do not report their retention to parents properly.
This PR uses the retention from the db, when the last_updated time is zero and also log debug messages in case retention from a child is malformed.
=> fix chart definition end time_t printing and parsing

collectors/plugins.d/pluginsd_parser.c, database/rrd.h, database/rrdhost.c, database/rrdsetvar.c, streaming/rrdpush.c, streaming/rrdpush.h, streaming/sender.c
Before this PR, chart variables updates force the entire chart to be pushed upstream again, triggering replication for that chart.
With this PR, chart variables updates are pushed upstream in BEGIN, SET, END, like the plugins do.
Also, there were 3 atomic operations on the chart flags for each BEGIN, SET, END loop. With this PR there is only 1 atomic operation.
Finally, there was a bug and proxies were not propagating metrics to their parents, if the host turned to be archived. Fixed it.
=> do not resend charts upstream when chart variables are being updated

libnetdata/socket/security.c, streaming/rrdpush.c, streaming/stream.conf
Fixes #13283 
When a parent is using properly signed ssl certificate (e.g. via letsencrypt) the child will try to validate it (if `ssl skip certificate verification` is not set to `yes`).
If we want to validate using the system's OpenSSL default CA certificates, we need to call `SSL_CTX_set_default_verify_paths`. Before this PR though, this happened only if `CAfile` in `stream.conf` actually existed. If it didn't exist (as in my machine `/etc/ssl/certs/certs.pem` which is the default doesn't), the streaming child could not validate the parent's certificate.
The change is to do the call to `SSL_CTX_set_default_verify_paths` irregardless of whether `CAfile` exists or not. If it does, it will be added with `SSL_CTX_load_verify_locations`.
If the user has also specified custom paths (using …
=> Setup default certificates path

database/sqlite/sqlite_aclk.h, database/sqlite/sqlite_aclk_alert.c, database/sqlite/sqlite_db_migration.c, database/sqlite/sqlite_functions.c
This PR tries to reduce unnecessary alert events sent to the cloud.
Each alert event is passed through a filter to decide if it is to be sent or not. The main idea is to not send an event that is of the same status as the last one sent to the cloud, unless the alert configuration has changed, or 15 minutes have passed between agent being off and on (except for CLEAR and UNDEFINED statuses).
The PR enhances the filter in 2 ways:
1) Adds the `RRDCALC_STATUS_UNDEFINED` to the checks.
2) Since the check for what was last sent to the cloud is based on the `aclk_alert` table, it had a problem when the table was cleaned up.
How it worked is that if we had a specific alert going from UNINITIALIZED -> CLEAR -> REMOVED -> UNINITIALIZED -> CLEAR -> REMOVED -> UNINITIALIZED -> CLEAR -> REMOVED etc.., …
=> Reduce unnecessary alert events to the cloud

libnetdata/libnetdata.h, packaging/installer/kickstart.sh, registry/registry.c
- Fixes Sign in button in local agent dashboard (by workaround)
- Fixes message in kickstart script
point 1 will ideally be fixed in future on agent UI by using new api endpoint returning both urls
Sign in button in local agent dashboard should point to `app.netdata.cloud` instead of `api.netdata.cloud`
</details>
=> Fix local dashboard cloud links

health/health.d/ping.conf
ping charts have `host` label. This PR updates ping alerts info.
Check alarms infos.
</details>
=> health/ping: use 'host' label in alerts info

packaging/installer/kickstart.sh
This PR consists largely of two separate sets of changes:
- The first significantly improves our detection of Netdata being installed through the system package manager. With these changes, we now properly detect when Netdata is installed via APK (on Alpine Linux), Pacman (on Arch Linux and some derivatives), Homebrew on macOS, or the native FreeBSD package management infrastructure.
- The second shows the user different messages and prompts for handling of reinstallation or updates on systems where we know that Netdata was installed through the system package manager in a way we do not officially support. These will provide clearer explanations of what may go wrong, and how to resolve the issue.
This can be easily tested by running the kickstart script on a system where Netdata was …
=> Provide improved messaging in the kickstart script for existing installs managed by the system package manager.

libnetdata/libnetdata.c
Using `dlsym()` when compiling with `-DNETDATA_TRACE_ALLOCATIONS=1` does not work on many systems, including debian.
This PR will enable the use of `dlsym()` only when compiling with `-DENABLE_DLSYM=1`, so that `-DNETDATA_TRACE_ALLOCATIONS=1` will be available on all systems, even on systems that `dlsym()` fails to work.
`dlsym()` is used only to intercept allocation using the regular `malloc()`, `calloc()`, `free()`, etc system calls. Even without `dlsym()` netdata will trace all allocations made with `mallocz()`, `callocz()`, `freez()`, etc.
=> require -DENABLE_DLSYM=1 to use dlsym()

database/rrd.h, streaming/receiver.c, streaming/rrdpush.c, streaming/sender.c
When a child disconnects from a parent, and the parent has a grand-parent, the parent manages to spawn a sender thread for the just disconnected child.
This was not a problem if parent and grand-parent do not replicate to each other.
When they replicate to each other, then the 2 parents connect to each other, without any child connected and they stay like that forever, preventing the child from connect back to any of them.
This PR adds a flag that prevents any parent to spawn a sender thread while the child is disconnected.
=> break active-active loop from replicating non-existing child to each other

collectors/proc.plugin/sys_devices_system_edac_mc.c
It is 2 charts only and as a user, I'd like to see the charts with 0 values + alarms by default then.
</details>
=> enable collecting ECC memory errors by default

exporting/prometheus/remote_write/remote_write.c
The remote write exporting connector should follow the same metric naming scheme as the Prometheus API. We should add the `_total` suffix for incremental metrics when the data source is `raw`.
Fixes #13963
1. Configure the remote write exporting connector
```
[prometheus_remote_write:my_prometheus_remote_write_instance]
enabled = yes
destination = localhost:1234
data source = raw
```
2. Run [Remote write adapter example](https://github.com/prometheus/prometheus/tree/main/documentation/examples/remote_storage/example_write_adapter)
3. Check the output. It should contain metrics with the `_total` suffix, like `netdata_cpu_cpu_total`, `netdata_system_interrupts_total` etc.
=> Add _total suffix to raw increment metrics for remote write

collectors/plugins.d/pluginsd_parser.c, database/rrdcontext.c, database/rrdcontext.h, database/rrdset.c, streaming/replication.c, streaming/sender.c
=> replication improvements

database/rrdcontext.c, web/api/queries/query.c, web/api/queries/rrdr.c, web/api/web_api_v1.c
We see a very rare condition that QUERY_TARGET is not released.
This PR adds an internal log error and a temporary fix, until we figure out how this happens.
=> added debug info on left-over query targets

.github/workflows/build.yml
The target repo is currently private, but will be made public when we have established that publishing to it is working correctly.
Merge it and wait for a nightly build.
This is the first step in migrating our nightly build storage from GCS to GitHub. Once this is verified to be publishing data correctly, a followup PR will be created to switch the updater to use the new location for fetching nightly builds.
=> Publish nightly builds to netdata/netdata-nightlies repository.

CMakeLists.txt, Makefile.am, aclk/aclk.c, aclk/aclk_capas.c, aclk/aclk_capas.h, aclk/aclk_rx_msgs.c, aclk/aclk_tx_msgs.c, aclk/schema-wrappers/capability.cc, aclk/schema-wrappers/capability.h, aclk/schema-wrappers/connection.cc, aclk/schema-wrappers/connection.h, aclk/schema-wrappers/node_connection.cc, aclk/schema-wrappers/node_connection.h, database/sqlite/sqlite_aclk_node.c
Fixes #13950. 
Adds "funcs" capability (that reports functions from plugins are available for the cloud to use).
Does a bit of cleanup (as we had this in 4 different places before)
Check capabilities reported by agent to cloud.
</details>
=> Add 'funcs' capability

docs/store/change-metrics-storage.md
I think we should use the app instead of a spreadsheet. 
- It's a better user experience.
- It's easier to maintain and open for all since it just lives here: https://github.com/netdata/netdata-storage-calculator.
- Anyone who wants to customize it or play with it can also just open the notebook in colab.
- It feels a bit more polished.
p.s. we should be able to make any other look and feel improvements easy too as just PR's to the repo.
</details>
=> use calculator app instead of spreadsheet

docs/get-started.mdx, docs/guides/export/export-netdata-metrics-graphite.md, docs/guides/monitor/lamp-stack.md, docs/guides/monitor/pi-hole-raspberry-pi.md, docs/guides/step-by-step/step-00.md, exporting/prometheus/README.md, packaging/installer/README.md, packaging/installer/methods/kickstart.md
We shouldn't use relative links when we want to reference components or/and pages in learn, they introduce to many breaking points if you move files, plus it's a pain when you want to calculate the relative path. This PR changes the relative links to absolute based on `@site` from the docusarus framework.
Part of learn
=> Change relative links to absolute for learn components

collectors/statsd.plugin/statsd.c, database/rrdset.c
This PR allows statsd tags to modify chart metadata on the fly:
=> allow statsd tags to modify chart metadata on the fly

libnetdata/socket/socket.c, web/server/web_client.c
It seems that retrying reading or writing corrupts the data.
Temporarily remove the retries that were introduced with PR #14023
=> remove retries from SSL

health/notifications/alarm-notify.sh.in
With the recent change from `app.netdata.cloud` to `api.netdata.cloud`, some static images in alarm notifications where lost. This points them back to `app.netdata.cloud`.
There is also an issue with the `go to chart` link. If the agent is unclaimed, or claimed without providing an `-url https://app.netdata.cloud` it will default to using `api.netdata.cloud` for the link, which doesn't appear to work. But this is pending tbd how to fix exactly.
Raise a couple of alerts and see the html mail. Check if severity images are missing, i.e. 
</details>
=> Change static image urls to app.netdata.cloud in alarm-notify.sh

database/rrd.h, database/rrddim.c, database/rrdset.c, libnetdata/dictionary/dictionary.c, streaming/replication.c, streaming/replication.h, streaming/rrdpush.c, streaming/rrdpush.h, streaming/sender.c
Speed up replication thread on very busy parents.
Instead of using the JudyL and a linked list, now it uses 2 JudyL nested to each other. The first JudyL uses the `after` timestamp as key and for each timestamp there is another JudyL that uses a unique id to store the entries.
During deletion, instead of traversing the linked list, it now uses the inner JudyL to find the entry to delete, using its unique id, without any traversal.
=> use 2 levels of judy arrays to speed up replication on very busy parents

daemon/global_statistics.c, libnetdata/libnetdata.h, libnetdata/worker_utilization/worker_utilization.c, libnetdata/worker_utilization/worker_utilization.h
On very busy parents, the internal worker statistics charts are not refreshed on time and present gaps, because there are thousands of workers.
This PR makes the workers statistics optimal by utilizing 2 Judy arrays (a JudyHS to index the workers by name and a JudyL to index the worker threads by pid).
Also, it also maintains the max number of jobs used by each worker, to avoid unnecessary loops to collect their metrics.
=> improve performance of worker utilization statistics

collectors/plugins.d/pluginsd_parser.c, daemon/global_statistics.c, database/rrd.h, database/rrdset.c, libnetdata/dictionary/dictionary.c, libnetdata/dictionary/dictionary.h, libnetdata/log/log.c, streaming/replication.c, streaming/rrdpush.c, streaming/sender.c
1. Fixed bug in replication which allowed the first BEGIN/SET/END to travel before the replication starts
2. Rewrite in a simpler and more traceable way the logic of the initial replication request for each chart
3. Cleanup plugins.d logic to reuse the same error handling
=> replication fixes #5

collectors/diskspace.plugin/plugin_diskspace.c
The slow disk thread in diskspace plugin can delay the shutdown sequence for the duration of it's `step` sleep.
If `step` is 5 seconds, it can sleep as much, and can delay the shutdown for up to that time depending when during sleep shutdown was requested. This PR lowers the sleep time to 1 second, while respecting the real `step` time to perform work.
Observe the log file during shutdown before and after this PR. If requested to shutdown during the start of the while loop in `diskspace_slow_worker`, it could take up to `step` seconds to end the thread. With this PR it should be during the first second.
</details>
=> Don't let slow disk plugin thread delay shutdown

collectors/plugins.d/pluginsd_parser.c, database/rrd.h, database/sqlite/sqlite_metadata.c, libnetdata/worker_utilization/worker_utilization.c, streaming/replication.c, streaming/replication.h, streaming/rrdpush.c
- use the faster monotonic clock in workers and replication
- avoid unecessary statistics functions on every request on replication - gather them all together once every second
- when replication completes, check the chart flags on all hosts to make sure streaming is enabled (this does not fix the possible issues, it just reports them)
- cleanup and unify replication logs
- added child world time to CHART_DEFINITION_END, RBEGIN and REND, so that the parent verifies all timestamps based on the child's clock, not its own
- fix first BEGIN been transmitted when replication starts
- dimensions replicated are not losing their OBSOLETE flag
=> replication fixes #6

daemon/global_statistics.c, daemon/global_statistics.h, daemon/static_threads.c, daemon/unit_test.c, database/rrd.h, database/rrdcontext.h, database/rrdset.c, database/sqlite/sqlite_functions.c, exporting/process_data.c, health/health.c, libnetdata/clocks/clocks.c, libnetdata/dictionary/dictionary.c, libnetdata/locks/locks.c, libnetdata/locks/locks.h, ml/ADCharts.cc, ml/Query.h, streaming/replication.c, streaming/replication.h, web/api/badges/web_buffer_svg.c, web/api/formatters/rrd2json.c, web/api/formatters/rrd2json.h, web/api/formatters/value/value.c, web/api/formatters/value/value.h, web/api/queries/query.c, web/api/queries/rrdr.h, web/api/queries/weights.c, web/api/web_api_v1.c, web/server/web_client.c, web/server/web_client_cache.c
- move global statistics workers to a separate thread
- query statistics per query source; query statistics for ML, exporters, backfilling, replication, etc
- optimize replication sender when most senders are full; reset replication point in time every 10 seconds
- fix compilation warnings when compiling without internal checks
- optimize the replication queries code
- prevent long tail of replication requests (big sleeps)
- optimize replication_request_get_first_available() (it had 75% overhead in `perf`)
- reset replication completion calculation;
=> replication fixes No 7

libnetdata/ebpf/ebpf.c
Remove next warning
```sh
Nov 27 10:07:45 lab-nd-dev-parent2 ebpf.plugin[1835034]: pointer 0x55fe893d5c30 is not our pointer (called freez_int() from 242@libnetdata/ebpf/ebpf.c, kernel_is_rejected()).
```
because we were cleanup memory with `z` functions where we should not.
1. Compile PR with flag `-DNETDATA_TRACE_ALLOCATIONS=1` and start netdata
2. Wait few minutes and stop plugin, you should not have the warning.
3. Recompile now master branch and execute previous step. You will have the error again.
- Can they see the change or is it an under the hood? If they can see it, where? o
- How is the user impacted by the …
=> Remove eBPF plugin warning

packaging/installer/netdata-updater.sh
Fixes: #12824
Run the updater script with `--no-updater-self-update --non-interactive --force-update`, check the output and exit code.
```cmd
$ ./netdata-updater.sh --no-updater-self-update --non-interactive --force-update
$ echo $?
0
```
</details>
=> fix(updater): don't produce any output if static update completed successfully

daemon/global_statistics.c, daemon/static_threads.c, libnetdata/locks/locks.c, streaming/replication.c, streaming/replication.h, streaming/rrdpush.h, streaming/sender.c
Replication requests with `start_streaming=true` are executed immediately upon reception, instead of being placed in the queue.
Mostly re-arranging code to make it possible for the sender thread to execute replication requests from its own thread, without putting them in the replication thread pending requests queue.
=> replication fixes No 8

daemon/main.c, daemon/unit_test.c, daemon/unit_test.h, health/health.c, health/notifications/alarm-notify.sh.in, libnetdata/inlined.h, spawn/spawn.c, spawn/spawn.h
This PR escapes single quotes and removes leading dashes from command arguments executed by the health component.
Not applicable. This should be a transparent change for users considering the values we are passing to the alarm notification script.
This issue has been identified by [Stefan Schiller](https://github.com/stefan-schiller-sonarsource) of SonarSource.com
Thank you Stefan!
=> Sanitize command arguments.

streaming/rrdpush.c, streaming/stream.conf
This PR applies strict rules on UUIDs defined in `stream.conf`.
`MACHINE_GUID` UUIDs can no longer be used as API keys and vice versa. A new option is introduced in `stream.conf` to define what an UUID section defines:
```
[UUID]
type = api | machine
```
If this option is absent, the default value depends on the first use of the `UUID`. If it is used first as an API key, it will automatically get `type = api`, if it is first used as MACHINE GUID, it will get `type = machine`. Once this is set, it can only be used as such.
UUIDs that are indirectly created by Netdata, always get `type = machine` and cannot be used as API keys.
- Users who are only setting API keys in `stream.conf` are advised to set `type = api` to their configuration, although it is not required. All their UUID sections …
=> Strict control of streaming API keys and MACHINE GUIDs in stream.conf

web/api/queries/query.c
Backfilling reports that it writes metrics to tier0 and tier1, but it writes to tier1 and tier2.
Fixed it.
=> fix backfilling statistics

libnetdata/socket/security.c, streaming/sender.c
The code had 2 issues:
1. multiple threads could initialize SSL concurrently, which resulted in crashes on busy parents that children connect suddenly all together. Now the code prevents concurrent initialization of SSL from multiple threads.
3. SSL globals were re-initialized without reason, probably triggering other side effects on established connections. Now the code does not re-initialize SSL.
=> fix SSL related crashes

collectors/proc.plugin/ipc.c, daemon/global_statistics.c, libnetdata/procfile/procfile.c, libnetdata/procfile/procfile.h, libnetdata/worker_utilization/worker_utilization.c, libnetdata/worker_utilization/worker_utilization.h
On very busy parents, workers charts have gaps.
This optimizes workers statistics in the following ways:
Also, in this PR:
=> optimize workers statistics performance

daemon/global_statistics.c, daemon/service.c, database/engine/pagecache.c, database/engine/rrdengine.c, database/engine/rrdengine.h, database/engine/rrdengineapi.c, database/rrddim.c, database/sqlite/sqlite_context.c, database/sqlite/sqlite_functions.c
There are 2 crashes reported:
---
During database file rotation there may be a situation where a page read is in progress and while the datafile
being removed destroys the associated descriptor.
Make sure the description destruction waits for the page read to complete (as it will access descriptor metadata) before it continues.
This PR attempts to fix this. 
- Avoid a crash related to a `uuid_compare` operation after a page read completes.
- Avoid fatal message about changed page alignment.
=> Fix 1.37 crashes

.github/scripts/gen-matrix-build.py, .github/scripts/gen-matrix-packaging.py, .github/scripts/gen-matrix-repoconfig.py, .github/scripts/get-static-cache-key.sh, .github/scripts/prepare-release-base.sh, .github/workflows/build.yml, .github/workflows/cloud_regression.yml, .github/workflows/codeql.yml, .github/workflows/docker.yml, .github/workflows/packaging.yml, .github/workflows/repoconfig-packages.yml, .github/workflows/review.yml
Relevant GitHub blog post: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
CI still works correctly on this PR.
=> Update workflows to use $GITHUB_OUTPUT instead of ::set-output::

collectors/diskspace.plugin/plugin_diskspace.c, database/rrdcontext.c, libnetdata/dictionary/dictionary.c, libnetdata/string/string.c
=> Fix __atomic_compare_exchange_n() atomics

database/engine/pagecache.c, database/engine/pagecache.h, database/engine/rrdengine.h, database/engine/rrdengineapi.c, database/engine/rrdengineapi.h, database/ram/rrddim_mem.c, database/ram/rrddim_mem.h, database/rrd.h, database/rrdcontext.c, database/rrddim.c
Page alignment related crashes persist.
Page alignment is a property of metric collection, so it has been moved to metric collection only.
=> fix v1.37 dbengine page alignment crashes

.gitignore, packaging/docker/run.sh, system/Makefile.am, system/edit-config, system/edit-config.in
This is a clean reimplementation of the `edit-config` script we install in the user config directory. It adds a few new features, and fixes a number of outstanding issues with the script.
Overall changes from the existing script:
- Error messages are now clearly prefixed with `ERROR:` instead of looking no different from other output from the script.
- We now have proper support for command-line arguments. In particular, `edit-config --help` now properly returns usage information instead of throwing an error. Other supported options are `--file` for explicitly specifying the file to edit (using this is not required, but we should ideally encourage it), and `--editor` to specify an editor of choice on the command-line.
- We now can handle editing configuration for a Docker container on the …
=> Cleanly reimplement system/edit-config.in.

packaging/installer/install-required-packages.sh
There is no `tar` package to be installed on FreeBSD, when the `--ignore-installed` argument is passed on to `install-required-packages.sh`, so the script fails. This PR fixes this issue (BTW the script works correctly without the `--ignore-installed` argument, probably why we haven't noticed so far). 
Run `./packaging/installer/install-required-packages.sh -i netdata` before and after this PR on FreeBSD.
=> Fix missing required package install of tar on FreeBSD

daemon/commands.c, daemon/commands.h
A small PR to add the `version` command to `netdatacli`. It returns the netdata version.
Ensure that `netdatacli version` returns the version of netdata.
</details>
=> Add version to netdatacli

packaging/docker/README.md, packaging/docker/run.sh
Fixes #14103
Start container with read-only/not read-only `/etc/netdata` mount.
</details>
=> fix docker host editable config

health/health.c
Fixes: #14084
`_is_ephemeral` and `_has_unstable_connection` labels [src is config](https://github.com/netdata/netdata/blob/bf8f277746cf912b2e12c5c5248866cd126767b9/health/health.c#L1557-L1561)
Exporting configured labels is [enabled by default](https://github.com/netdata/netdata/blob/bf8f277746cf912b2e12c5c5248866cd126767b9/exporting/read_config.c#L256).
It causes problems even though the format is [correct](https://graphite.readthedocs.io/en/latest/tags.html#carbon) (🤷)
> my.series;tag1=value1;tag2=value2
I doubt we were going to export those labels anyway. I am not sure my fix is correct, but I think it is acceptable as a quick fix.
Build docker images, configure graphite exporter, and check exporter metrics. …
=> fix health emphemerality labels src

.github/workflows/packaging.yml
I checked the logs and the error is
> cgroup-parent for systemd cgroup should be a valid slice named as "xxx.slice"
ci
</details>
=> ci: fix cgroup-parent name in packaging

collectors/apps.plugin/apps_plugin.c
This PR allows a function to define the type of filtering it expected on each column.
2 kinds for filtering are supported:
1. `multiselect`, to allow the user select individual instances from the values of the column
2. `range` to allow the user select a range of values (`from` - `to`).
=> add filtering options to functions table output

streaming/receiver.c, streaming/rrdpush.c, streaming/sender.c
When there are active-active parent clusters and hundreds of children streaming to them, netdata logs every 5 seconds really a lot about each child connection attempt that fails (it fails because the other parent already has this child - they are active-active in a loop)
In the streaming code there is back-off, but this did not affect logging.
In this PR connection attempts are logged as they happen and the back-off is printed at the time it was applied, so there is no need to repeat it every 5 seconds. In order to find out why a destination is not tried, users have to find the latest log line about it, which now states the time it will be retried, like these:
```
2022-12-09 12:50:40: netdata ERROR : STREAM_SENDER[rpi4b-2] : (0427@streaming/sender.c  :rrdpush_sender_): STREAM rpi4b-2 …
```
=> don't log too much about streaming connections

libnetdata/clocks/clocks.c
On overloaded systems, heartbeat logs way too much. This adds a limit of one log line every 10 seconds.
=> heartbeat: don't log every discrepancy

aclk/aclk.c, collectors/apps.plugin/apps_plugin.c, collectors/proc.plugin/proc_stat.c, daemon/main.c, libnetdata/os.c, libnetdata/os.h, web/server/static/static-threaded.c
`get_system_cpus()` is now caching its results by itself.
There are 2 macros defined:
- `get_system_cpus()`
- `get_system_cpus_uncached()`, which reads again the system cpus from the system
`get_system_cpus()` respects the host prefix. There are cases however that the code may need:
1. the current number of system cpus on the container or VM netdata is running
2. the current number of system cpus of the monitored host
The code currently does not distinguish between the two. Probably the best way would be to have 2 such functions. To make things more complex, for Darwin and FreeBSD the function call completely ignores the host prefix, so it always returns the cpus of the system netdata runs at.
For the moment I decided not to touch that part. The only possibility of these 2 processor …
=> fix get_system_cpus()

collectors/ebpf.plugin/ebpf.h, collectors/ebpf.plugin/ebpf_cachestat.c, collectors/ebpf.plugin/ebpf_cachestat.h, collectors/ebpf.plugin/ebpf_dcstat.c, collectors/ebpf.plugin/ebpf_disk.c, collectors/ebpf.plugin/ebpf_fd.c, collectors/ebpf.plugin/ebpf_fd.h, collectors/ebpf.plugin/ebpf_filesystem.c, collectors/ebpf.plugin/ebpf_hardirq.c, collectors/ebpf.plugin/ebpf_mdflush.c, collectors/ebpf.plugin/ebpf_mount.c, collectors/ebpf.plugin/ebpf_process.c, collectors/ebpf.plugin/ebpf_shm.c, collectors/ebpf.plugin/ebpf_socket.c, collectors/ebpf.plugin/ebpf_softirq.c, collectors/ebpf.plugin/ebpf_swap.c, collectors/ebpf.plugin/ebpf_sync.c, collectors/ebpf.plugin/ebpf_vfs.c, libnetdata/ebpf/ebpf.c
This PR is fixing some issues on RH 8.x family found while I was developing https://github.com/netdata/ebpf-co-re/pull/33 .
1. Clone branch and compile it.
2. Set `cachestat` and `fd` as `yes` in your `/etc/netdata/ebpf.d.conf`.
3. Start netdata.
4. After few seconds run next command:
```sh
curl http://localhost:19999/api/v1/charts?all | grep -E "(mem\.cachestat_ratio|filesystem.file_descriptor)"
```
You must have charts loaded and running.
| Distribution | Kernel | Result |
|-------------------|-----------|-----------|
| Slackware Current  |     5.19.17     | [slacware_5_19.txt](https://github.com/netdata/netdata/files/10182007/slacware_5_19.txt) | 
| Arch Linux         |  6.0.10-arch2-1 | [arch_6_0.txt](https://github.com/netdata/netdata/files/10182008/arch_6_0.txt …
=> Fix eBPF load on RH 8.x family and improve code.

Makefile.am, aclk/aclk.c, aclk/aclk_util.c, aclk/aclk_util.h
Implements topic aliases bi-directional for PUBLISH packets.
Fixes #12989
Decreases message size in both directions at expense of some of them sweet bytezzz of your RAM
</details>
=> MQTT 5 publish topic alias support

health/health.d/httpcheck.conf
This PR:
- Deletes alarms that use other alarms in calculations (this doesn't work correctly when having more than one HTTP check).
- Removes the `no-clear-notification` option.
- Adds `warn` and `crit` for `timeout` and `no_connection` statuses (`bad_content` and `bad_status` alarms had them).
- Adds the `url` label value to the info line.
Tested locally by copying the httpcheck.conf file.
</details>
=> fix httpcheck alarms

.github/data/distros.yml, packaging/PLATFORM_SUPPORT.md
It’s EOL upstream as of 2022-12-13.
n/a
=> Remove Fedora 35 from the list of supported platforms.

Makefile.am, aclk/aclk.c, configure.ac
- not exposed trough installer on purpose - not meant to be used by users only by devs etc.
- allows netdata to be built in such way that developer can debug and inspect decrypted real traffic between agent and cloud
- this helps debug-ability (example if there is a suspected bug in MQTT parser we can capture the offending packet easily)
- while software like firefox allows this to be enabled by environment variable, I decided to be extra paranoid and make it a compile time optional thing
generates file in https://firefox-source-docs.mozilla.org/security/nss/legacy/key_log_format/index.html format that can be used with Wireshark and other tools to decrypt the captured traffic
Compile netdata with `./configure ... -enable-aclk-ssl-debug` then the file `SSLKEYLOGFILE` will be created on …
=> expose ACLK SSL KeyLog interface for developers

netdata.spec.in
Fixes: #14132
This PR fixes the lack of setuid bit for:
- cgroup-network
- ebpf.plugin
In fact, it doesn't really fix #14132, but it is up to @Ferroin if we want to keep the issue open.
- Build an rpm package locally.
- Install netdata.
- Check cgroup-network and ebpf.plugin permissions.
</details>
=> fix(packaging): add setuid for cgroup-network and ebpf.plugin in RPM

collectors/ebpf.plugin/README.md, collectors/ebpf.plugin/ebpf.d.conf
Fixes #14138 
This PR is disabling integration between eBPF.plugin and apps.plugin by default avoiding overloading servers with huge sample of process running.
1. Compile this branch and start `netdata` using stock files, you should not have `ebpf.plugin` and `apps` integration enabled. As consequence of this eBPF plugin will allocate less memory and use less resources from computers.
</details>
=> Disable integration by default (eBPF <-> APPS)

packaging/repoconfig/netdata-edge.repo.centos, packaging/repoconfig/netdata-edge.repo.fedora, packaging/repoconfig/netdata-edge.repo.ol, packaging/repoconfig/netdata-edge.repo.suse, packaging/repoconfig/netdata-repo.spec, packaging/repoconfig/netdata.repo.centos, packaging/repoconfig/netdata.repo.fedora, packaging/repoconfig/netdata.repo.ol, packaging/repoconfig/netdata.repo.suse
This updates our repository configuration packages to point to our new self-hosted repository infrastructure for our RPM packages. A secondary PR migrating DEB package infrastructure will be created later.
The repository configuration can be tested by copying the `netdata*.repo.*` file for the distribution to be tested on (`centos` for Alma/CentOS/RHEL/Rocky, `ol` for Oracle Linux, `fedora` for Fedora, `suse` for openSUSE) to the test system and putting it in the appropriate directory (`/etc/yum.repos.d` on most distros, or `/etc/zypp/repos.d` on openSUSE) with the correct name (just remove the `.<distro>` extension).
After setting up the repository configuration, refreshing metadata or attempting to install a package should result in a prompt about accepting a new GPG key for netdatabot.
=> Switch to self-hosted infrastructure for RPM package distribution.

aclk/aclk.c, aclk/aclk_otp.c, aclk/aclk_util.c, aclk/aclk_util.h, aclk/https_client.c, aclk/https_client.h
Fixes #12629
Squid http proxy with Basic auth user and pass should work now
</details>
=> Support HTTP proxy Basic auth

collectors/apps.plugin/apps_groups.conf
Fixes: #14154
I think the assumption in https://github.com/netdata/netdata/pull/5962 was wrong, `proc/PID/comm` is always `node`.
Not needed.
</details>
=> fix nodejs app detection

aclk/aclk_query.c
I could not reproduce this problem personally but @ktsaou reported at agent startup he somethimes gets this:
```
Core was generated by `/opt/netdata/usr/sbin/netdata -P /run/netdata/netdata.pid -D'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055c6b4887457 in mqtt_wss_publish5 (client=0x0, topic=0x55c7000e4b20 "/agent/68d47046-61e8-11ed-a3d8-ceb8dac27b23/outbound/v1/nodeinstance/connection", topic_free=0x0, msg=0x55c721bcfb00, msg_free=0x55c6b47542aa <freez_aclk_publish5a>, msg_len=168, publish_flags=1 '\001', packet_id=0x7f6bc4dc074e) at mqtt_websockets/src/mqtt_wss_client.c:1433
1433	    if (!client->internal_mqtt) {
[Current thread is 1 (Thread 0x7f6bc4dc1700 (LWP 2844291))]
(gdb) bt
#0  0x000055c6b4887457 in mqtt_wss_publish5 (client=0x0, topic=0x55c7000e4b20 …
```
=> Fix race on query thread startup

packaging/installer/README.md, packaging/installer/kickstart.sh, packaging/installer/methods/packages.md
Followup to #14100, this updates the kickstart script to use the new infrastructure, and adds documentation about how to manually set up our RPM repositories.
Running the kickstart script from this PR on a platform we provide native for with the `--native-only` switch should correctly install the agent.
The new documentation added by this PR will be further expanded when we have working repositories for DEB packages on the new infrastructure.
=> Finish switch to self-hosted RPM repositories.

aclk/aclk_capas.c
Correctly report functions are available for localhost nodeinstance.
Connect parent with some kids to cloud all able to execute functions.
Enable functions feature of cloud by setting local storage `functions:true` in your browser debug console.
Parent should now correctly report as supporting functions.
</details>
=> minor - fix localhost nodeinstance fnc caps

contrib/debian/netdata.postinst, netdata-installer.sh, packaging/makeself/install-or-update.sh
This is needed for VMs/containers:
- name resolution.
- reading CPU and memory limits (for CPU, mem % utilization charts, and alarms).
Both are must-haves on Proxmox (server for virtualization management).
- ci
</details>
=> feat(packaging): add netdata to www-data group on Proxmox

collectors/proc.plugin/proc_spl_kstat_zfs.c, health/health.d/cgroups.conf, health/health.d/disks.conf, health/health.d/mdstat.conf, health/health.d/net.conf, health/health.d/zfs.conf
This PR replaces the use of the `$family` variable with the appropriate chart label in all alarms.
Checks the description of the changed alarm, and ensure the $label:name gets replaced.
</details>
=> use specific charts labels instead of family in alarms

collectors/proc.plugin/proc_net_dev.c
Fixes: #14170
Should be merged on the same day as https://github.com/netdata/netdata/pull/14173
@hugovalente-pm this PR removes the interface name from the `net` family. Still, we will get `net` and `net IFACE_NAME` families (Netdata version after/before this commit).
Install this branch, and check cgroup net family.
</details>
=> remove interface name from cgroup net family

system/netdata.logrotate.in
Netdata no longer stores its PID file under the `@localstatedir_POST@/run/netdata/` dir after #13504 => Netdata keeps writing to the old log file after rotating because we don't send HUP
https://github.com/netdata/netdata/blob/4409202f33cd6d20c9f6f2cdffa9d2112d6a437b/system/netdata.logrotate.in#L10
Do `cat /run/netdata/netdata.pid` and see it returns the netdata process PID.
</details>
=> fix logrotate postrotate

.github/data/distros.yml
Because RHEL does things differently than it’s various clones when compsing the value of the `$releasever` variable.
Code to handle these is already in-place on the repository backend system, this is just properly codifying things here in an extensible manner.
n/a
=> Add compatibility links for RHEL repos.

.github/workflows/labeler.yml
This has a number of advantages:
- It allows us to make PR labeling event-driven instead of polling. This, in turn, means that it only runs when a PR is modified, and only evaluates that specific PR, which results in spending far less time running PR labeler jobs.
- This is the ‘official’ way to handle PR labels automatically as code, and thus @ilyam8 will no longer need to maintain a custom labeling action for this purpose.
- The matching syntax supported by this action is more expressive than what is supported by our existing infrastructure, allowing for things such as requiring all of a group of files to be modified in a PR for it to have a specific label applied. We have no need right now for this, but it is useful to have it available long-term.
- Because the labeling is …
=> Switch to actions/labeler@v4 for labeling PRs.

.github/scripts/run_install_with_dist_file.sh, .github/workflows/checks.yml, .github/workflows/codeql.yml, .travis.yml, claim/README.md, netdata-installer.sh, packaging/installer/UNINSTALL.md, packaging/installer/UPDATE.md, packaging/installer/kickstart.sh, packaging/installer/methods/freebsd.md, packaging/installer/methods/kickstart.md, packaging/installer/methods/macos.md, packaging/installer/methods/manual.md, packaging/makeself/jobs/70-netdata-git.install.sh, tests/lifecycle.bats, tests/run-unit-tests.sh, tests/updater_checks.bats
SSIA
Attempting to use `--install` with the kickstart script or netdata-installer.sh should not result in the agent being installed to the specified prefix.
Fixes: #12659 
Should not be merged before #12943 (otherwise the error messages for the user will be more confusing).
=> Finish renaming the `--install` option to `--install-prefix`.

ml/ADCharts.cc
When a parent runs a ML for a child, the relevant-ML charts should be created on the child host. These charts should use the parent's hostname to differentiate multiple parents that might run ML for a child.
The only exception to this rule is the training/prediction resource usage charts. These are created on the localhost of the parent host, because they provide information specific to said host.
- CI Jobs
- Stream a child to a parent with ML enabled and verify the hosts where the ML charts are created.
=> Create ML charts on child hosts.

packaging/docker/Dockerfile
There is no `wheels` after https://github.com/netdata/helper-images/pull/181
ci
</details>
=> fix docker builds

database/rrdcalc.c, database/rrdcalc.h, health/REFERENCE.md, health/health.d/cgroups.conf, health/health.d/consul.conf, health/health.d/disks.conf, health/health.d/dns_query.conf, health/health.d/httpcheck.conf, health/health.d/mdstat.conf, health/health.d/net.conf, health/health.d/nvme.conf, health/health.d/ping.conf, health/health.d/portcheck.conf, health/health.d/postgres.conf, health/health.d/zfs.conf
Fixes #14175 
This PR changes the format of the alert info variables to use `${label:something}` instead of `$label:something`. This will allow the variables to have other characters around them and not be defined by spaces. The old way of defining the variables will not work.
Check that variables are correctly replaced.
The only problem is if a user has custom alerts will need to update them with the new format.
</details>
=> Use brackets around info variables

Makefile.am, aclk/aclk.c, aclk/aclk_util.c, aclk/aclk_util.h
Fixes bug discovered which was reason for (https://github.com/netdata/netdata/pull/14145) - fixes are part of last commits so that is clear to reviewers what was changed since (#14067):
- rx topic alias list was not cleared on reconnect upon failure (according to MQTT spec topic aliases are not to be persisted across connection even if same session is continued
- this in combination with us not allowing topic alias reassignment caused agent not being able to reconnect
Reintroduces https://github.com/netdata/netdata/pull/14067
Automated tests are being worked on to prevent such problems in future.
This has to be tested extensively as it introduces wide changes to the mqtt_websockets incl. both parsers and message generators.
- test connection is stable
- test connection is eventually …
=> MQTT5 Topic Alias

.github/scripts/docker-test.sh
https://github.com/netdata/netdata/blob/cd80dd6a04d4d3467189e63c29f01a01b229c2d8/.github/scripts/docker-test.sh#L25-L29
We need to check the container logs. Otherwise, it is not clear what is happening.
</details>
=> ci: show docker logs if docker-test fails

.github/data/distros.yml, packaging/PLATFORM_SUPPORT.md
They have not been building properly for quite some time now due to upstream bugs in Fedora itself, so stop wasting resources trying to build them.
n/a
No functional changes for users because we were not successfully publishing these packages anyway.
</details>
=> Drop ARMv7 native packages for Fedora 36.

daemon/global_statistics.c, database/engine/datafile.c, database/engine/metric.c, libnetdata/locks/locks.c, libnetdata/locks/locks.h, libnetdata/worker_utilization/worker_utilization.c
gcc versions prior to 5 do not allow initializing static members/variables with this expression:
```c
#define NETDATA_SPINLOCK_INITIALIZER (SPINLOCK){ .locked = false, }
```
They throw a message that the above is not a constant initializer. But they accept the same without the cast:
```c
#define NETDATA_SPINLOCK_INITIALIZER { .locked = false, }
```
This PR changes the code to allow compiling with gcc versions prior to 5.
Also, global statistics fail when dbengine is not enabled. This PR fixes that too.
=> pre gcc v5 support and allow building without dbengine

ml/Host.cc, ml/Host.h, ml/ml.cc, ml/ml.h
On shutdown we needed a way to cancel the ML threads without waiting for them to exit.
This PR introduces a new call to cancel the ML threads without joining them.
=> cancel ml threads on shutdown and join them on host free

daemon/main.c
This PR adds log lines on startup and shutdown to profile each step of the process.
To use it run this on a terminal:
```sh
tail -f /var/log/netdata/error.log | grep -E "NETDATA (STARTUP|SHUTDOWN)" 
```
And then restart the agent with `systemctl restart netdata`.
Example:
```
2023-01-11 17:34:47: netdata INFO  : MAIN : (0307@daemon/main.c       :netdata_cleanup): NETDATA SHUTDOWN: initializing shutdown with code 0...
2023-01-11 17:34:47: netdata INFO  : MAIN : (0311@daemon/main.c       :netdata_cleanup): NETDATA SHUTDOWN: next: create shutdown file
2023-01-11 17:34:47: netdata INFO  : MAIN : (0319@daemon/main.c       :netdata_cleanup): NETDATA SHUTDOWN: in       0 ms, create shutdown file - next: disable maintenance, new queries, new web requests, new streaming connections and aclk …
```
=> profile startup and shutdown timings

database/engine/cache.c, web/api/queries/query.c
When huge queries are running that exceed the target size of the cache, the cache enters a mode trying to aggressively evict pages from it. This makes it extremely slow.
This PR applies 3 fixes:
The cache can now grow up to 1,5 times the size of the referenced pages in it.
So, the target cache size is now calculated like this:
1. `A = max hot size ever encountered x 2`
The hot size is the number of pages concurrently being collected.
2. `B = max hot size ever encountered + twice the max dirty size ever encountered`
The max dirty size is the number of pages that are committed to disk concurrently.
3. `C = currently referenced size x 1.5`
The currently referenced size includes any page that is concurrently used for any reason (hot while being collected, dirty while being saved, clean while …
=> allow the cache to grow when huge queries are running that exceed the cache size

ml/SamplesBuffer.cc, ml/SamplesBuffer.h, ml/ml.cc
This PR replaces two temporary heap allocations with stack arrays. We can do this because our features are produced from single dimensions.
- CI job
- Run ML with address sanitizer
=> Remove temporary allocations when preprocessing a samples buffer

collectors/proc.plugin/proc_net_netstat.c
Fixes: #14235
Netdata doesn't create charts for `/proc/net/netstat`, `/proc/net/snmp` metrics if fails to read `/proc/net/snmp6` (IPv6 is disabled).
This PR fixes it by **moving the processing of `/proc/net/snmp6` to a separate function** - that is the only change, don't get confused with the number of changed LOC.
- Add `ipv6.disable=1` to `GRUB_CMDLINE_LINUX_DEFAULT`; update grub and reboot server.
- Check "Networking Stack" and "IPv4 Networking" charts.
</details>
=> fix(proc.plugin): handle disabled IPv6

libnetdata/arrayalloc/arrayalloc.c
Functionality in libnetdata is meant to be used by both external collectors and the agent itself. We want to keep libnetdata completely independent from agent specific code.
- Build the agent successfully with/without the `ifdefs` referenced in the modified file.
- CI jobs.
=> Remove daemon/common.h header from libnetdata

.github/workflows/build.yml
This compensates for the fact that GitHub’s release sorting is based on a byte-wise sort of the associated tag name, which does not match up with the temporal sorting that we actually want for this.
n/a
=> Always mark nightly build releases as latest.

libnetdata/socket/security.c, libnetdata/socket/socket.c, streaming/receiver.c, streaming/sender.c, web/server/web_client.c, web/server/web_client_cache.c
This PR enables retries for `SSL_read` when the error returned is `SSL_ERROR_WANT_READ`.
This appears to help when a child attempts to connect and stream to a parent over a bad network line when using SSL.
Would like some feedback on testing this scenario.
1) Create a child and parent from master on different machines.
2) Establish between them an SSL streaming configuration.
3) Use [this utility](https://gist.github.com/denilsonsa/5176e1c9b6a119594ce0) to simulate a bad network connection on the parent. For my tests I used `sudo ./slow -d enp4s0f4u2u4 3G -l 600ms -p 10%` (replace enp4s0f4u2u4 with your network adapter).
4) Start child/parent and observe the logs. On my tests the child was throwing `SSL_read() returned -1 bytes, SSL error 2` (Error 2 is `SSL_ERROR_WANT_READ`). The parent …
=> Enable retries for SSL_ERROR_WANT_READ

packaging/installer/netdata-updater.sh
Fixes https://github.com/netdata/netdata/issues/14110 .
1. Install a previous version of Netdata on openSUSE using native packages (can go to an older version using `zypper in -f netdata-1.37.0.121.nightly-1`).
2. Try to run `netdata-updater.sh` manually and see it failing. 
3. Then try to run `netdata-updater.sh` from this branch, it should succeed.
=> Fix binpkg updates on OpenSUSE

aclk/aclk.c, daemon/global_statistics.c, database/engine/cache.c, database/engine/datafile.h, database/engine/journalfile.c, database/engine/metric.c, database/engine/pagecache.c, database/engine/pdc.c, database/engine/pdc.h, database/engine/rrdengine.c, database/engine/rrdengine.h, database/engine/rrdengineapi.c, database/engine/rrdengineapi.h, database/ram/rrddim_mem.c, database/rrdhost.c, database/sqlite/sqlite_metadata.c, libnetdata/july/july.c, libnetdata/july/july.h, ml/Dimension.cc, ml/Host.cc, streaming/compression.c, streaming/rrdpush.c, web/api/queries/query.c, web/api/web_api_v1.c
1. Allow extents to be merged for as long as possible
2. Fix extent failure reasons accounting and reporting
3. Do not block the main event loop while datafiles are being rotated and retention is recalculated for the remaining metrics
4. Buffers are incrementally cleaned up every second, to avoid locking the event loop for longer durations every 10 seconds.
5. Fixed a bug on the planner for queries that refer to time-frames outside the database retention.
6. Fixed calculation of cache memory size on 32-bit - it was wrapping around, allowing the cache to grow without limit
7. Fixed 32-bit compilation warning
=> DBENGINE v2 - improvements 2

health/health.d/load.conf
Fixes: #14258
> It appears the load_cpu_number value isn't being collected and so is defaulting to 2, **ultimately resulting in tons of inappropriate CPU load alarms going off**.
- check loadavg alarms if `$load_cpu_number` is not NaN (should have values).
- check loadavg alarms if `$load_cpu_number` is NaN (should have `-` values).
</details>
=> fix(health): don't assume 2 cores if the number is unknown

daemon/main.c, database/engine/rrdengineapi.c, database/rrd.h, libnetdata/libnetdata.h, ml/Host.cc, streaming/receiver.c, streaming/replication.c, streaming/rrdpush.c, streaming/rrdpush.h, streaming/sender.c, web/api/queries/query.c
1. Query planner uses 64 bit numbers to calculate tier weight
2. Replication adapts its pipeline to the number of cores in the system
3. Replication stops creating too big messages that require increasing the streaming buffer to unrealistic sizes
4. Fixed ML crash when RH is NULL
5. On 32-bit use smaller page sizes, less libuv workers, less cache by default
=> More 32bit fixes

.github/workflows/build.yml
When run on a release build, the cross platform checks are checking code that has been checked with them at least once, and usually twice, and thus the only reason they fail with any regularity is external infrastructure issues or upstream bugs. While we ideally do want to know about such things, it is undesirable for such issues to block releases and nightly builds, so this PR simply stops caring about them for releases and nightly builds.
Provided everyone actually follows the correct procedures for merging PRs, this should not reduce the quality of the code that is published at all, and it has the secondary benefit that it should make releases and nightly builds have less impact on other CI 9and be less impacted by other CI).
n/a
=> Skip cross-platform validation when preparing releases.

collectors/proc.plugin/plugin_proc.c, collectors/proc.plugin/plugin_proc.h, collectors/proc.plugin/proc_meminfo.c, daemon/system-info.sh, system/netdata.service.in
Fixes: #14238
The issue is that the [LXCFS proc](https://github.com/lxc/lxcfs#introduction) is not mounted [because of ProtectControlGroups=on](https://github.com/netdata/netdata/issues/14238#issuecomment-1380719725) which causes Netdata to track the host system and not the LXC container it's running in.
> to track the host system and not the LXC container it's running in.
That is impossible to "fix" completely because an LXC container is not a VM, so we are limited to LXCFC procfs.
A further improvement in this direction will be to disable plugins that collect host system metrics, which do not make sense to collect inside the LXC container (e.g. ZFS, KSM, etc). I am not going to do it in this PR.
---
This PR:
- Updates Netdata systemd unit file: configures [LXCFS proc …
=> fix(pacakging): fix cpu/memory metrics when running inside LXC container as systemd service

.github/scripts/run-updater-check.sh
If it takes more than an hour to run the updater, something has gone horribly wrong, so just kill it instead of letting it keep running.
Watch the checks on this PR.
This should make it easier for us to debug the issues we’re seeing with the Alpine checks.
=> Set an explicit timeout in updater checks.

.github/scripts/gen-matrix-packaging.py
This will bring us back to running only native packaging jobs on most PRs instead of running all packaging jobs on all PRs.
Note that only 64-bit x86 packaging jobs run on this PR.
=> Fix conditional in matrix generation for packaging jobs.

database/engine/journalfile.ksy
Allows to browse contents of journal v2 files like this (in hex editor that interprets the data):
- This helps understanding (e.g. when somebody studies the code) and debugging.
- Also it can be used to generate parser code for various languages
1. install Kaitai struct visualizer as per instructions [here](https://github.com/kaitai-io/kaitai_struct_visualizer) or [there](http://kaitai.io/)
2. add it to PATH and run `ksv $NETDATA_INSTALL_DIR/netdata/var/cache/netdata/dbengine-tier2/journalfile-1-0000000002.njfv2 journalfile.ksy`
</details>
=> minor - add kaitaistruct for journal v2 files

README.md
The infographic was updated to include a single link to www.netdata.cloud/integrations, instead of the tens of individual collector logos. This updates the png in the main README file to match it.
=> Update infographic image on main README

web/server/web_client_cache.c
This PR checks the session variable before attempting to use it. If it's not checked, and the variable is null it can lead to a crash.
Tested locally by specifically setting `session` to null. Indeed the crash reported here -> https://github.com/netdata/netdata/issues/14249#issuecomment-1384666296 occurs. With the check in place there is no crash.
</details>
=> Check session variable before resuming it

streaming/sender.c
Fixes #14258 
`rrdpush_sender_thread_send_custom_host_variables` is called before the flag `RRDHOST_FLAG_RRDPUSH_SENDER_CONNECTED` is set, and because there is a check for this flag the function is not actually executed to transmit host variables over streaming.
Host variables eventually are streamed when the agent connects (by using the `rrdpush_sender_send_this_host_variable_now` function), but not again if the parent is restarted.
This PR just changes to call the function after the flag is set.
Setup a parent/child.
Start parent, start child.
Check the alert on the parent for the child: `system.load.load_cpu_number`. It should have the correct cpu cores of the child.
Restart the parent.
Without this PR the core count will be 0 (or dash). With this PR (running on the child) the parent …
=> Make sure variables are streamed after SENDER_CONNECTED flag is set

claim/claim.c, database/rrdhost.c, database/sqlite/sqlite_metadata.c, database/sqlite/sqlite_metadata.h
In some cases, when the claim procedure happens shortly after the agent start, it might be possible that the `node_instance` and `host` tables are not yet populated. In this case, aclk does not find any nodes and as such does not send out any `CreateNodeInstance` messages.
The result is that the node does not appear as online ever in the cloud. This also affects our set team's test suite.
This PR reverts some recent changes, to populate these tables as soon as there are data for them.
Has been tested in set's test suite (but will be tested again).
If the agent is claimed a couple of seconds after start, it should appear online in the cloud.
</details>
=> Store host and claim info in sqlite as soon as possible

database/engine/rrdengine.c
1. Do not lock the entire datafile list while a datafile is being deleted
=> DBENGINE v2 - improvements part 4

aclk/aclk.c, aclk/aclk.h, daemon/service.c, daemon/static_threads.c, database/rrd.h, database/rrdcalc.c, database/rrddimvar.c, database/rrdhost.c, database/rrdset.c, database/rrdsetvar.c, database/sqlite/sqlite_aclk_alert.c, database/sqlite/sqlite_health.c, database/sqlite/sqlite_metadata.c, health/health.c, health/health.h, health/health_config.c, health/health_json.c, health/health_log.c, streaming/receiver.c
This PR reverts health to run in a single thread for all hosts. It still retains the health initialization in the health thread as so to not delay host creation.
Will be tested that it performs as it should in regards also to the cloud.
</details>
=> Revert health to run in a single thread

health/health.d/load.conf
ssia, related PR #14283
Test the alarm locally
</details>
=> fix(alarms): treat 0 processors as unknown in load_cpu_number

configure.ac, daemon/main.c, libnetdata/libnetdata.c, libnetdata/libnetdata.h, libnetdata/popen/popen.c, spawn/spawn_server.c
Fixes https://github.com/netdata/netdata/issues/14177 , fixes https://github.com/netdata/netdata/issues/14062 .
There are 3 places in the agent where we either try to close all open file descriptors or mark them to be closed by the `exec()` stage of `posix_spawn()`. This is done in a bruteforce way, by looping through all FD IDs up to `_SC_OPEN_MAX`.
While this is a valid approach, it creates issues on platforms that (incorrectly) set the maximum FD limit to infinity (in practice, it can be as high as `1073741816`).
This PR instead of bruteforcing its way through all possible FD IDs, it reads `/proc/self/fd` (if available) to discover which FDs are actually open and closes (or marks to be closed) only them (unless `STDIN`, `STDOUT` and/or `STDERR` are to be excluded).
This should also …
=> Improve file descriptor closing loops

collectors/statsd.plugin/statsd.c
The status field was missing from the struct when building under MacOS.
Build on Apple platform.
=> Fix macos struct definition.

daemon/main.c, database/engine/journalfile.c, database/engine/journalfile.h, database/engine/rrdengine.c
The agent would crash on startup on MacOS systems because:
1. The default soft limit of open file descriptors was too low,
2. `journalfile_v2_mounted_data_unmount()` would iterate tiers that have not been initialized.
- CI jobs
- Build the agent and run it on MacOS.
=> Fixes required to make the agent work without crashes on MacOS

exporting/aws_kinesis/aws_kinesis.c, exporting/pubsub/pubsub.c, exporting/tests/test_exporting_engine.c
Add additional argument avoiding errors like this:
```sh
exporting/aws_kinesis/aws_kinesis.c:55:32: error: too few arguments to function 'buffer_create'
55 |     instance->buffer = (void *)buffer_create(0);
|                                ^~~~~~~~~~~~~
In file included from ./libnetdata/libnetdata.h:456,
from ./daemon/common.h:6,
from ./exporting/exporting_engine.h:6,
from exporting/aws_kinesis/aws_kinesis.h:6,
from exporting/aws_kinesis/aws_kinesis.c:3:
./libnetdata/buffer/buffer.h:65:9: note: declared here
65 | BUFFER *buffer_create(size_t size, size_t *statistics);
|         ^~~~~~~~~~~~~
```
</details>
=> Fix Exporiting compilaton error

CMakeLists.txt, Makefile.am, aclk/aclk.c, configure.ac
Removes support for MQTT-C library and keeps only new MQTT5 implementation.
This cleans up the code and is prerequisite for next improvements and fixes which are coming.
Behavior should be same as before this PR with mqtt5 switched on
</details>
=> remove mqtt-c from websockets

libnetdata/socket/socket.c, web/server/static/static-threaded.c, web/server/web_client.c
Attempts to address the issue #14129 (last posts by @Habetdin on streaming, dashboard loading should be ok).
I could only reproduce the issue on a parent running on Ubuntu 22.04 with openssl 3.0.2, and a child over a long distance line (over DSL) (with openssl 1.1.1).
It appears that in this case the first ssl read on the parent fails with SSL_WANT_WRITE. This is when the parent accepts a new connection, and the child sends the "STREAM" command.
There is no retry there, so the parent assumes a 0 bytes read and responds with BAD_REQUEST.
This PR attempts to set the web_client to wait_read, so as to do a poll on the socket and wait for more data when this happens. It also changes static-threaded.c to only process a request when some bytes have been read.
The socket.c parts where just …
=> Misc SSL improvements

netdata-installer.sh, packaging/installer/functions.sh, packaging/installer/netdata-uninstaller.sh
SSIA, Fixes https://github.com/netdata/netdata/issues/13711 .
1. Install Netdata using `netdata-installer.sh`.
2. Uninstall Netdata using `netdata-uninstaller.sh`
3. Observe group creation, user assignment and group/user deletion runs as expected.
</details>
=> Use "getent group" instead of reading "/etc/group" to get group information

collectors/COLLECTORS.md
This will be changed when the new integrations page is launched.  Also, it needs to be the main page when expanding the contents, not just another page in there (@tkatsoulas will do that)
=> Add collectors list to learn temporarily

docs/get-started.mdx
This PR is related with https://github.com/netdata/documentation/issues/22, it includes:
What else could be changed:
- Do we need the top section "Get started with Netdata"? (Same information should be living at the introduction document)
- ~~Should we rename the file's title to "Install Netdata"?~~ Already done due to naming conflict with the category this file lives at Learn
- Should we add another box in the "other installation options" for the "Install Netdata with kickstart.sh" page? (we have a link to it, but as a reference to the kickstart script)
=> Update the Get started doc

web/api/queries/query.c
Removes an equal sign from a comparison in query.c
It appears that `<=` will return one extra point when querying. It is mostly apparent in health (thanks @dimko for raising the issue).
For example in an alert that states e.g. `sum -3s abs of rand1,rand2` it will read back 4 points instead of 3.
Will be tested from @dimko as well.
Needs a chart with a couple of dimensions, with static values (to be easier to check). Create an alert with a lookup of e.g. `sum -3s abs of rand1,rand2` on that chart, and check the value.
</details>
=> Remove equality when deciding how to use point

collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py
This change enables the calculation of the PCIE bandwidth in percent.  
Tested manually on two different machines. One with a GPU Quadro RTX 4000 and the other one with GPU RTX  A4500
To have a quick overview about the pcie bandwidth available, I though it was useful to have the values of TX/RX bandwidth in percent. To do so it calculates the maximum theoretical bandwidth thanks to the pcie generation and width given by nvidia-smi, thus the value in percent can be deduced.
<details> <summary>For users: metric netdata_nvidia_smi_pci_bandwidth_KiB_persec_average enhanced  </summary>
It changes the nvidia-smi plugin only. And two dimensions _rx_percent_ and _tx_percent_ have been added to the _netdata_nvidia_smi_pci_bandwidth_KiB_persec_average_ metric.
</details>
=> Add nvidia smi pci bandwidth percent collector

collectors/cgroups.plugin/sys_fs_cgroup.c
I noticed that some and full pressure stall times are equal. The problem is using the same value for both some and full. This PR fixes it.
Not needed, the change is obvious.
</details>
=> fix(cgroups.plugin): fix collecting full pressure stall time

packaging/installer/kickstart.sh, packaging/installer/netdata-updater.sh
Fixes https://github.com/netdata/netdata/issues/14346 .
1. Ensure you are only using BusyBox `wget` and no other versions of it or of `curl` exist in your PATH (a Docker Alpine image can be used for this purpose). 
2. Try to run 
```
wget -O /tmp/kickstart.sh https://raw.githubusercontent.com/Dim-P/netdata/fix-kickstart-wget/packaging/installer/kickstart.sh && sh /tmp/kickstart.sh --static-only
``` 
and confirm it works as expected (including a correct call of `telemetry_event()` ).
4. Next, try to run 
```
wget -O /tmp/netdata-updater.sh https://raw.githubusercontent.com/Dim-P/netdata/fix-kickstart-wget/packaging/installer/netdata-updater.sh && sh /tmp/netdata-updater.sh --not-running-from-cron --no-updater-self-update --force-update
```
and confirm updater works as expected.
5. Finally, …
=> Fix kickstart and updater not working with BusyBox wget

collectors/ebpf.plugin/ebpf.c, collectors/ebpf.plugin/ebpf.d.conf, collectors/ebpf.plugin/ebpf_cachestat.c, collectors/ebpf.plugin/ebpf_dcstat.c, collectors/ebpf.plugin/ebpf_disk.c, collectors/ebpf.plugin/ebpf_fd.c, collectors/ebpf.plugin/ebpf_filesystem.c, collectors/ebpf.plugin/ebpf_hardirq.c, collectors/ebpf.plugin/ebpf_mdflush.c, collectors/ebpf.plugin/ebpf_mount.c, collectors/ebpf.plugin/ebpf_oomkill.c, collectors/ebpf.plugin/ebpf_shm.c, collectors/ebpf.plugin/ebpf_socket.c, collectors/ebpf.plugin/ebpf_softirq.c, collectors/ebpf.plugin/ebpf_swap.c, collectors/ebpf.plugin/ebpf_sync.c, collectors/ebpf.plugin/ebpf_vfs.c
This PR reduces the following events :
```sh
8)
MAIN : SERVICE CONTROL: the following 1 service(s) [ COLLECTORS ] take too long to exit: 'PD[ebpf]' (97538); giving up on them...
```
on user hosts. With these changes eBPF will close faster, because new default options won't be expensive to host and it is checking more frequently status to close.
1. Compile branch
2. start netdata and wait few minutes.
3. Stop netdata and take a look in `error.log`.
</details>
=> Reduce service exit

docs/dashboard/visualization-date-and-time-controls.mdx
The control was moved at some point inside the datetime picker, the documentation wasn't updated.
=> Update screenshot of timezone selector

ml/Host.cc, ml/Queue.h
Without these changes, it was possible to delete the host while the ML threads were still running. With this change, we ensure that the training thread keeps processing training requests only as long as the ML threads have not been cancelled.
Connect/disconnect a child with short host cleanup period. The agent should not crash.
=> Stop training thread from processing training requests once cancelled.

collectors/plugins.d/pluginsd_parser.c
Old versions of netdata sometimes send invalid microseconds delta at the BEGIN streaming command.
=> Check on parents the microseconds delta sent by agents

database/ram/rrddim_mem.c
Now that the query engine expands the duration of the queries to satisfy the plans, rrddim modes (`alloc`, `ram`, `save`, `map`) complain about unfinished queries.
Eventually, this statement can be eliminated altogether.
=> turn error() to internal_error()

collectors/python.d.plugin/w1sensor/w1sensor.chart.py
Changed regex to allow for negative temperatures. Previously negative temperatures did not show up in the chart.
Previously, thermometers that were recording negative temperatures did not show up at all in the resulting charts. This PR fixes that by slightly altering a regular expression. 
I tested this locally on my own hardware and it fixed my problem. Negative temperatures are properly displayed now. 
The file content that the regex is matched with has the following format:
**For 46° Celsius**
`e0 02 ff ff 7f ff ff ff c2 : crc=c2 YES
e0 02 ff ff 7f ff ff ff c2 t=46000`
**For -0.5° Celsius**
`e0 02 ff ff 7f ff ff ff c2 : crc=c2 YES
e0 02 ff ff 7f ff ff ff c2 t=-500`
With my change the case with negative temperatures also produces a match. 
<details> <summary>For users: How does this …
=> Updated w1sensor.chart.py

streaming/replication.c, streaming/rrdpush.c
fixes https://github.com/netdata/netdata/issues/14432
This PR makes replication detect that it finished with a gap and allow clock resync between the child and the parent to work. If no gap at the end of replication is detected, the resync timeout is zeroed to have the previous behavior for successfully joining replicated and streamed data at the parent.
The changes are only on the child.
=> replication to streaming transition when there are gaps

packaging/installer/kickstart.sh
Instead of just blindly prompting the user for root privileges when they are needed in the kickstart script, print a message about _why_ we need root privileges. This improves transparency for users about why they are being prompted.
Run the kickstart script from this PR as a non-root user. You should see messages about root privileges being required for specific commands as those commands are run.
=> Indicate what root privileges are needed for in kickstart.sh.

collectors/freebsd.plugin/freebsd_sysctl.c
Fixes https://github.com/netdata/netdata/issues/14375 . 
The bug was introduced as part of https://github.com/freebsd/freebsd-src/commit/1a70101a870015304d5b2446b480d8677d8aad36  that allows `netstat -s` to differentiate between received and sent ECN-marked packets (and after this PR, Netdata will be able to do the same). 
Also, I believe the ECN statistics were incorrect before as:
1. `InECT0Pkts` and `InECT1Pkts` should have been called `ECT0Pkts` and `ECT1Pkts` (as they seem to include not only received but sent ECT packets too).
2. `InNoECTPkts` calculation seems like it was incorrect, so it has been removed as part of this PR (if I have misunderstood it please advise and I will add it back in). 
1. Install `master` on FreeBSD 14.0. An ISO can be downloaded from: …
=> Fix agent build failure on FreeBSD 14.0 due to new tcpstat struct

.github/CODEOWNERS
Owning docs now, we'll remove @tkatsoulas at some point.
=> Add cakrit as docs and md codeowner

docs/get-started.mdx
It's actually hard to find the room id for the default "All nodes" space so we should make it very clear that you dont need a room id to just claim a node into the default "All nodes" room.
For example in the all nodes we dont even show the room id in the app:
So i think for most users defaulting to having them need to find a room id could end up being confusing.
</details>
=> add note about not needing to have room id

.github/workflows/labeler.yml
Instead of flagging on the git ref for the run, flag on the repository ID and PR number. This ensures that previous runs get cancelled only for the correct PR when a new run is triggered.
This should fix the seemingly random cases of PR labeler runs being cancelled for no apparent reason on our PRs.
n/a
=> Fix the concurrency group name for PR labeler workflow.

packaging/docker/README.md
This PR is related with netdata/documentation#22, it includes:
I didn't fix the links, as there is a PR addressing the change already open.
=> update the "Install Netdata with Docker" doc

packaging/installer/methods/kubernetes.md
This PR is related with netdata/documentation#22, it includes:
=> Update the "Deploy Kubernetes monitoring with Netdata" doc

packaging/makeself/jobs/20-openssl.install.sh, packaging/makeself/jobs/50-curl-7.87.0.install.sh, packaging/makeself/jobs/50-ioping-1.3.install.sh, packaging/makeself/openssl.version
* bump openssl to v1.1.1t
* bump ioping to v1.3
* bump curl to v7.87
Future work:
-  Add a lifecycle process to update these packages
- Bump openssl to v3.X
Note:
We didn't update bash, static package build for `armv7l` didn't finish successfully (nee to double down on that)
openssl:
Ioping:
Curl:
General:
</details>
=> Update static build packages

system/netdata.service.v235.in
Fixes #14292 
Adds the template of `sbindir_POST` to `netdata.service.v235.in`. This affects static installs in e.g. Centos 7 (with such version of systemd), where then, the service file will try to run `/usr/sbin/netdata` instead of `/opt/netdata/usr/sbin/`
Compile this PR, even in a local prefix. After the compile check the contents of `system/netdata.service` and `system/netdata.service.v235`. The `ExecStart` line should have the proper path.
</details>
=> Add sbindir_POST template for v235 service file

collectors/cgroups.plugin/sys_fs_cgroup.c
An agent running as non root / EBPF disabled, sometimes crashes during shutdown at
```
#0  cgroup_main_cleanup (ptr=0x559dad6a88d8) at collectors/cgroups.plugin/sys_fs_cgroup.c:4772
4772	        munmap(shm_cgroup_ebpf.header, shm_cgroup_ebpf.header->body_length);
```
The reason is that the agent will not be able to setup a semaphore (when running `netdata_cgroup_ebpf_initialize_shm`) 
and it logs the following message in `collector.log`
```
Cannot create semaphore, integration between eBPF and cgroup won't happen
```
This will also remove the MMAPed area pointed by `shm_cgroup_ebpf.header`  but during the cgroups cleanup (`cgroup_main_cleanup`)  a second attempt to munmap the memory area results in a crash.
=> Fix random crash on agent shutdown

.gitattributes, .gitignore, Makefile.am, database/engine/journalfile_v2.ksy.in
During small chat with Stelios I decided to make it possible to view the file directly in sequence (without virtual members) to be able to do that and not loose the ability to have also the better view I used m4 macros to generate 2 `.ksy` versions from one source during build.
There will be 2 generated files during build:
- `database/engine/journalfile_v2.ksy` - this will be more akin to using hex editor where there is list of structures saved in order, useful when debugging file corruption etc.
- `database/engine/journalfile_v2_virtmemb.ksy` - this is what we had until now where there are virtual members allowing to jump trough file. For example `journal_v2_metric_list` has member `page_ofsset` which points to a page later stored much later in file. Therefore there is virtual member …
=> generates dual ksy for njfv2 + fix for padding after page blocks

docs/getting-started/introduction.md
To achieve this, we:
- add a metadata called "slug" 👉 `slug: "/getting-started"`, this is to change the link that leads to the file, so nobody can find it by it's actual path in Learn
- we move the file (so it is not accessible further down in the same menu) to a folder where all the "slugs" will live in the future
This action also requires a 
```json
"link": {
"type": "doc",
"id": "slugs/introduction"
},
```
to be added inside the sidebars.json, in the same depth as the category's label. The id marks the location of the file in Learn, it is not related to it's link, as we have changed it with the slug metadata.
=> Make the introduction a category link

database/rrdhost.c, database/rrdvar.c, health/health.c
Fix an issue with children with different memory mode from the parent that reconnect and destroy a global health
dictionary that causes a memory corruption / crash.
Fixes #14481
=> Fix crash when child connects

docs/category-overview-pages/concepts-overview.md, docs/category-overview-pages/developers-overview.md, docs/category-overview-pages/getting-started-overview.md, docs/category-overview-pages/installation-overview.md, docs/category-overview-pages/operations-overview.md, docs/category-overview-pages/references-overview.md, docs/category-overview-pages/setup-overview.md, docs/getting-started/introduction.md
This is the PR that along with https://github.com/netdata/learn/pull/1329 will allow us to use the pages introduced as the page that comes up when one clicks a category in Learn.
---
The way this works, is:
We will keep all the files for "category overview pages" (let's call them like this for now) in one folder under `docs/category-overview-pages`.
If we only had the automatic sidebar, then folders not having an overview page will show up with a lowercase label, same as the category's folder name.
So, in the files introduced, we specify the `sidebar_label` and `learn_rel_path` to be exactly the same value as the category we want to cover.
By doing this, the category then gets controlled by it's overview file now, in terms of `sidebar_label` and `sidebar_position`.
For example, for the …
=> Category overview pages

collectors/plugins.d/README.md
The directory needs to appear in the learn_rel_path
=> Make external plugins a category page in learn

web/gui/dashboard_info.js
Current PR is blocked by https://github.com/netdata/go.d.plugin/pull/1055
This PR is bringing detailed information for some metrics delivered for our users.
Reviewers we do not have a proper icon for .NET in our [source](https://fontawesome.com/search?o=a&m=free), so I selected a generic one. I am accepting all suggestions to improve the icon.
</details>
=> Add .NET info

daemon/main.c, daemon/unit_test.c
Fixes #14421
Prepares the environment to run the create dataset action so it doesn't crash.
Test with and without this PR. With the PR there should not be a crash when running `netdata -W createdataset=10`
</details>
=> Prevent crash when running '-W createdataset'

database/engine/rrdengineapi.c, database/rrdset.c, streaming/replication.c
instead of sending RBEGIN/REND without points, jump to the end of the gap on every replication step.
Unfortunately we don't know at which time exactly the gap finishes, when it finishes outside the query boundaries, but this PR should skip gaps that are within the query executed.
Fix a bug during replication when a child node is set to memory node NONE and the stream connection has INTERPOLATE capability
Fixes #14479
=> replicating gaps

packaging/installer/functions.sh, packaging/installer/kickstart.sh, packaging/installer/netdata-updater.sh
Instead of immediately falling back to wget, try using curl from a static build if it is installed. This provides better behavior in a number of cases and also makes the static builds more self-contained.
Initial testing should confirm that there is no change in behavior in cases where there is nostatic build installed.
The other key test here is to install a static build (ideally in a container), uninstall any copy of wget/curl, and then attempt to run the kickstart script from this PR, which should work correctly despite the lack of a system-copy of curl or wget.
Fixes #14401
=> Use curl from static builds if no system-wide copy exists.

.github/data/distros.yml
We don’t need special handling for Alma’s images, so we should not have a `base_iamge` key for it.
CI for Alma Linux works correctly on this PR.
Fixes a bug introduced by https://github.com/netdata/netdata/pull/14529
=> Fix broken Alma Linux entries in build matrix generation.

web/api/queries/README.md
nginx data no longer available, so all the svgs were broken. Pointed to net.eth0 received instead.
Added an example of how to get the same data from the API.
Documentation of this capability, `api/v1/allmetrics` and the API in general will be revisited.
=> Fix broken svgs and improve database queries API doc

.shellcheckrc, netdata-installer.sh, packaging/installer/dependencies/centos.sh, packaging/installer/functions.sh, packaging/installer/install-required-packages.sh, packaging/installer/netdata-uninstaller.sh, packaging/makeself/install-or-update.sh, system/install-service.sh.in
- Add a config file for shellcheck to disable dead code checks. They have an extremely high false positive rate due to how frequently we are making indirect calls to functions, and on the rare occasions when they do flag actual dead code, the impact of said dead code is usually almost nonexistent.
- Fix all the issues reported by shellcheck in the installer code. This should make it easier to review related PRs.
n/a
=> Assorted shellcheck cleanup.

netdata-installer.sh, packaging/docker/Dockerfile
Capabilities needed for go.d.plugin:
1. cap_net_admin (wireguard)
2. cap_net_raw (ping)
This PR:
- Sets 1. and 2. on every netdata-installer.sh run (caps get reset on every update [somewhere here](https://github.com/netdata/netdata/blob/8fdeec2e85cf5b1de742d672c57e2c0f276e8867/netdata-installer.sh#L1210-L1214)).
- Sets 2. in dockerized Netdata. Setting both 1. and 2. here didn't work. `setcap` was successful, but: 
```bash
bash-5.1# getcap go.d.plugin
go.d.plugin cap_net_admin,cap_net_raw=eip
bash-5.1# ./go.d.plugin -d -m ping
bash: ./go.d.plugin: Operation not permitted
```
- Install and check go.d.plugin capabilities; Reinstall and check go.d.plugin capabilities.
- Check if go.d/ping works in Docker container. …
=> fix setting go.d.plugin capabilities

health/notifications/email/README.md
This updates the documentation about configuring email notifications so that it’s clearer what you need to do to set them up in Docker, as well as making the section on using msmtp a bit clearer.
n/a
=> Update email notification docs with info about setup in Docker.

database/rrdhost.c, web/api/web_api_v1.c
Fixes #14293 
This PR tries to fix the above issue. 
We keep a dictionary of hosts, based on hostname, on `rrdhost_root_index_hostname`. This is populated on parent startup, from children info previously connected to the parent (even if not currently connected).
If a child was previously connected with guid X, then changed and connected with Y, the dictionary will only keep a link to the host with guid X, and will not store the one with Y. As such, when requesting /host/child which streams with guid Y there will be nothing there.
This PR just overwrites the dictionary. Assuming X is added to the dictionary during startup, then Y is streaming, the dictionary will delete X and keep Y.
The PR also sorts the list of `mirrored_hosts_status` according to their reachability. This is to make …
=> Re-index when machine guid changes

docs/guides/configure/performance.md
Instruction now points to document that explains dbengine v2 RAM requirements.
=> Remove obsolete instruction to lower memory usage

collectors/cgroups.plugin/README.md
- Removed section on cgroups not being cleaned before v1.6
- Capitalized headings and beginnings of lists/sentences
=> Fix doc capitalization and remove obsolete section

system/edit-config
- If asked to edit a file in a sub-directory of the config directory but that sub-directory does not exist, create it. This is needed for sanity reasons WRT some of our other packaging code.
- If passed a relative path which does not resolve to an absolute path under the config directory, just prefix it with the config directory path instead. This fixes an issue reported by a user.
Two specific test cases:
1. Try to edit a file in a sub-directory of `/etc/netdata` when that sub-directory does not exist. It should be automatically created.
2. Try to edit a file under `/etc/netdata` without using a full path when you’re not in `/etc/netdata`. It should work correctly now.
Fixes: #14384
=> Fix two issues with the edit-config script.

packaging/docker/Dockerfile, packaging/docker/README.md, packaging/docker/run.sh
This enables users to pull in additional packages more easily if they need to. It also allows us to drop optional runtime dependencies from our base images without making life significantly more difficult for users who actually need them, ultimately resulting in smaller base images for our containers.
This is handled via a new environment variable called `NETDATA_EXTRA_APK_PACKAGES`. If this is defined, then the entrypoint code will update APK repositories and attempt to install the packages listed in this variable before starting the agent.
Once Netdata v1.39 is released, we will be removing said optional runtime packages to actually shrink the image sizes. The initial list of candidate packages is apcupsd, libvirt-daemon, lm-sensors, msmtp, and netcat-openbsd. Once we transition to …
=> Support installing extra packages in Docker images at runtime.

collectors/ebpf.plugin/ebpf.c, collectors/ebpf.plugin/ebpf.h, collectors/ebpf.plugin/ebpf_apps.c, collectors/ebpf.plugin/ebpf_apps.h, collectors/ebpf.plugin/ebpf_cachestat.c, collectors/ebpf.plugin/ebpf_dcstat.c, collectors/ebpf.plugin/ebpf_fd.c, collectors/ebpf.plugin/ebpf_oomkill.c, collectors/ebpf.plugin/ebpf_process.c, collectors/ebpf.plugin/ebpf_process.h, collectors/ebpf.plugin/ebpf_shm.c, collectors/ebpf.plugin/ebpf_socket.c, collectors/ebpf.plugin/ebpf_swap.c, collectors/ebpf.plugin/ebpf_vfs.c, libnetdata/libnetdata.c, libnetdata/libnetdata.h
This PR is bringing first step to improve memory management for eBPF before we bring new charts, to reach this goal we are modifying:
- Compatibility that existed when codes were copied from `apps` to `ebpf` to do an independent integration. Now we have inside structures variables that are really used.
- Unification of structures and eliminating necessity to have double structures.
- Reducing processing time removing calls. To do this we are removing `callocz`/`freez`  and now we are using our `ARAL` .
This PR is only modifying `user ring` code and other PRs will come to complement this. With these changes on my environment we saved 10% of memory after to modify only one thread:
1. Modify your `/etc/netdata/ebpf.d/process.conf` with the following configuration:
```sh
[global]
collect pid …
```
=> Memory management eBPF

libnetdata/socket/socket.c, web/server/static/static-threaded.c, web/server/web_client.c
Attempts to address the issue #14129 (last posts by @Habetdin on streaming, dashboard loading should be ok).
The previous attempt in #14317 had an issue where it would raise cpu usage in some cases (thanks @andrewm4894). This was because POLLIN was not reset when reading, leading to a loop.
The only difference of this PR vs the previous is a call to `web_client_disable_wait_receive(w);` before trying to receive data. If it is to be set, then it will be done when reading.
This was tested on a parent (again on a remote machine) and a child on local. Tested streaming over SSL, dashboard loading, and cloud connectivity all at the same time.
We need to test for the above also with a non-SSL configuration, and also on a local environment.
Do note that there seems to be an issue with non-SSL …
=> Misc SSL improvements 2

database/engine/datafile.c, database/engine/journalfile.c
Currently the initial calculation for the update every for a metric per journal file is not correct because it is based on the 
min / max retention for the metric and the number of entries in that journal file for the metric.
This PR accesses the metric metadata for the last page stored in the journal and fetches the update every as stored there.
=> Get update every from page

.flake8, .github/workflows/review.yml
We used to have this in our old Travis jobs, but it got removed at some point before the switch to GitHub Actions and we never re-added it.
While we’re not doing much new development in our Python collectors, we are actively using Python in a number of places in our CI code, so it’s still advantageous for us to have linting for it.
n/a
=> Add flake8 to review CI to check Python files.

database/engine/datafile.c, database/sqlite/sqlite_context.c, database/sqlite/sqlite_functions.c, database/sqlite/sqlite_functions.h
Minor cleanup and fix a core dump when running `netdata -W ctxtest`
```
#0  0x000055dd17705898 in ?? ()
#1  0x00007f16cfe89644 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.3
#2  0x00007f16cfe8d8e2 in OPENSSL_thread_stop () from /lib/x86_64-linux-gnu/libcrypto.so.3
#3  0x00007f16cfe8d945 in OPENSSL_cleanup () from /lib/x86_64-linux-gnu/libcrypto.so.3
#4  0x00007f16cf5a2a56 in __cxa_finalize (d=0x7f16d010b000) at ./stdlib/cxa_finalize.c:83
#5  0x00007f16cfd820f7 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.3
#6  0x00007ffe95aa7c00 in ?? ()
#7  0x00007f16d015124e in _dl_fini () at ./elf/dl-fini.c:142
```
=> Fix context unittest coredump

daemon/main.c, database/sqlite/sqlite_context.c, database/sqlite/sqlite_functions.c, database/sqlite/sqlite_metadata.c
This happens when the agent faces a initialization failure and issues a shutdown
Attempting to cancel threads not initialized
e.g.
```
#0  cancel_main_threads () at daemon/main.c:662
662	                netdata_thread_cancel(*static_threads[i].thread);
[Current thread is 1 (Thread 0x7f874397ecc0 (LWP 1495531))]
(gdb) p static_threads[i].thread
$1 = (netdata_thread_t *) 0x0
```
and
Attempting a metadata event loop shutdown that is not active yet
```
#0  0x00007f76710cc44f in uv_async_send () from /lib/x86_64-linux-gnu/libuv.so.1
#1  0x000055babf6ddebc in metadata_enq_cmd (wc=0x55babfd72e80 <metasync_worker>, cmd=0x7fff8dc9d380) at database/sqlite/sqlite_metadata.c:777
#2  0x000055babf6df9f9 in metadata_sync_shutdown_prepare () at database/sqlite/sqlite_metadata.c:1291
#3 …
```
=> Prevent core dump when the agent is performing a quick shutdown

.github/data/distros.yml, .github/scripts/gen-matrix-eol-check.py, .github/scripts/platform-impending-eol.py, .github/workflows/platform-eol-check.yml
By default, it runs at 03:00 UTC every Monday, and checks the upstream EOL date for each platform we support that needs such checking. If the platform will be EOL upstream within the next 30 days, an issue is opened flagging the platform for removal from CI and our support document and auto-assigned to the agent SRE team members.
The workflow can also be manually triggered (mostly intended for testing).
Data about upstream EOL dates is retrieved from https://endoflife.date via their new public API. Happily, our own definition of what consititutes EOL for our purposes matches up 1:1 with how they categorize platforms as EOL, so the code handling this is relatively simple.
The original idea was to open a PR instead with the required changes, but correctly handling the required changes is …
=> Add a scheduled CI job to flag supported platforms going EOL upstream.

.github/data/distros.yml
Approximately we know the EOL of Debian 12 (not officially announced yet) but the repo we have utilized  https://endoflife.date/ doesn't contain it, we temporarily disable this check.
=> Temporarily remove platform EOL check for Debian 12

collectors/ebpf.plugin/ebpf.c, collectors/ebpf.plugin/ebpf.h, collectors/ebpf.plugin/ebpf_apps.c, collectors/ebpf.plugin/ebpf_cachestat.c, collectors/ebpf.plugin/ebpf_cachestat.h, collectors/ebpf.plugin/ebpf_dcstat.c, collectors/ebpf.plugin/ebpf_dcstat.h, collectors/ebpf.plugin/ebpf_fd.c, collectors/ebpf.plugin/ebpf_fd.h, collectors/ebpf.plugin/ebpf_shm.c, collectors/ebpf.plugin/ebpf_shm.h, collectors/ebpf.plugin/ebpf_socket.c, collectors/ebpf.plugin/ebpf_socket.h, collectors/ebpf.plugin/ebpf_vfs.c, collectors/ebpf.plugin/ebpf_vfs.h
This PR is modifying threads to use `ARAL` instead our `callocz`/`freez` pair. 
1. Compile this branch.
2. Start netdata. 
3. Wait few minutes to take a look in plugin behavior. Everything should run normally. 
It is not necessary to run on different kernels.
After changes `coverity` is reporting errors due this [code](https://github.com/netdata/netdata/blob/59a1a528e3e42e90eda83f7cfe7b04fe8a00e60d/libnetdata/locks/locks.c#L303-L307). @stelfrag my current understanding  is that `coverity` is reporting a false positive, please, let me know if I am wrong.
- Can they see the change or is it an under the hood? If they can see …
=> Use vector allocation whenever is possible (eBPF)

collectors/python.d.plugin/anomalies/anomalies.chart.py
Fixes: #14561
Where the python version check was incorrectly rejecting python 3.10 and higher due to how the float() was casting "10" to "1".
New logic tested as per below: 
```python
for sys_version_info in [(2,7),(3,4),(3,5),(3,6),(3,7),(3,10),(3,11),(3,12)]:
if not (sys_version_info[0] >= 3 and sys_version_info[1] >= 6):
print(f'{sys_version_info} = unsupported')
else:
print(f'{sys_version_info} = supported')
"""
(2, 7) = unsupported
(3, 4) = unsupported
(3, 5) = unsupported
(3, 6) = supported
(3, 7) = supported
(3, 10) = supported
(3, 11) = supported
(3, 12) = supported
"""
```
</details>
=> fix python version check to work for 3.10 and above

packaging/installer/kickstart.sh, packaging/installer/methods/kickstart.md
This consists of a single new option `--distro-override` which takes a single argument consisting of the values of the `ID`, `VERSION_ID`, and `VERSION_CODENAME` fields from the os-release file for the target distribution, separated by `:`. The codename part is optional for non-DEB distros, in which case the final `:` may be left off. The distro name is processed just like if we got it out of `/etc/os-release`, and thus any aliases our code already supports are also supported for this option. Additionally, the distro name and codename are automatically converted to lower case. For example:
- For Debian 11: `debian:11:bullseye`
- For Fedora 37: `fedora:37` or `Fedora:37`
- For RHEL 9: `rhel:9` or `RHEL:9` or `almalinux:9` or `CentOS:9`
This option allows for better handling of platforms …
=> Add an option to the kickstart script to override distro detection.

web/server/static/static-threaded.c, web/server/web_client.c, web/server/web_client.h
This PR is based on the previous one, but takes a more conservative approach, to solve an issue where a very very long api call on a slow connection won't get through (@dimko :bow: ).
It uses 2 new flags specific to SSL, to indicate to wait for receive or send instead of using the existing ones.
Tested (on a remote machine over VPN):
* A very long api call (~12kb) that during read will be split in more than 2 reads, both over SSL and normal connection.
* Attempts to STREAM with an initial message that is broken over 2 reads, over SSL and normal connections.
* General dashboard usability.
Made sure no high cpu usage appeared on the parent during these tests.
</details>
=> Misc SSL improvements 3

packaging/installer/kickstart.sh, packaging/installer/methods/freebsd.md, packaging/installer/methods/kickstart.md
This unifies handling of the (currently) six kickstart.sh options that change the operational mode of the script from the default of attempting to update or install the agent. In particular:
- They are now mutually exclusive, with only the last one specified being honored.
- A warning is now issued every time that one of these options overrides a previously specified option.
- The help text about these options has been updated to better describe them in detail, and to clearly offset them from the ‘normal’ kickstart options.
The affected options are:
- `--reinstall`
- `--reinstall-even-if-unsafe`
- `--reinstall-clean`
- `--uninstall`
- `--claim-only`
- `--repositories-only`
- `--prepare-offline-install-source`
The mutual exclusion and warnings for overrides can be tested by simply running …
=> Ensure consistency of kickstart script options that change operational mode of the script.

packaging/installer/README.md
It somehow got dropped during the docs reorganization.
na
This also cleans up the numerous instances of trailing whitespace in the install document.
=> Re-add link from install page to DEB/RPM package documentation.

system/Makefile.am, system/install-service.sh.in, system/openrc/conf.d/netdata.in, system/openrc/init.d/netdata.in
- Add `/etc/conf.d/netdata`. Files under `/etc/conf.d` are the standard mechanism for service configuration with OpenRC, and get sourced as part of running the service script. By providing this file, we can document various options in a place that the user will actually find them instead of relying on the user to find them themselves.
- Fix handling of the shutdown retry schedule. It needs to be handled after the `conf.d` file gets loaded (thus should be in a `stop_pre` hook), and it should properly handle variables not being defined.
- Add a proper description for the service and for the non-standard service commands we provide.
Testing can be done on Alpine, Gentoo, or some other system that uses OpenRC as it’s init system. 
The new conf.d file can be checked by looking for the new …
=> Assorted improvements to OpenRC support.

configure.ac, packaging/makeself/functions.sh, packaging/makeself/jobs/50-libnetfilter_acct-1.0.3.install.sh, packaging/makeself/jobs/70-netdata-git.install.sh
In this PR we bundle the `nfacct` dependencies `libnetfilter_acct` as static lib from source archives and `libmnl` as static lib from the alpines' packages (regular package manager) into our Netdata static binaries
Changelog:
* `packaging/makeself/functions.sh`: change the `fetch` function to also be able to fetch any tars (previous could fetch only `tar.gz`)
* `configure.ac`: Reorganize the tests to bundle the `nfacct` plugin, the previous one only checked in the system libs, we amended those to also check for our static bundle.
* `packaging/makeself/jobs/50-libnetfilter_acct-1.0.3.install.sh`: Include a new job to create a static bundle of the `libnetfilter_acct`
* `packaging/makeself/jobs/70-netdata-git.install.sh`: Amend the Netdata's static build job to statically link the  `libmnl` …
=> Link statically libnetfilter_acct into our static builds

packaging/docker/README.md
https://github.com/netdata/netdata/pull/14178 changed the Docker documentation as a temporary fix, due to issue https://github.com/netdata/netdata/issues/14177. That issue was fixed in https://github.com/netdata/netdata/pull/14213 , so this PR undoes the changes that https://github.com/netdata/netdata/pull/14178 introduced.
N/A
=> [docs]: Revert #14178 that documents how to set nofile limit for Netdata containers

collectors/freebsd.plugin/freebsd_devstat.c, collectors/freebsd.plugin/freebsd_getifaddrs.c, collectors/freebsd.plugin/freebsd_getmntinfo.c
Reported on [ND Discord](https://discord.com/channels/847502280503590932/1081177412433354752).
Regression bug from #14592
Not needed.
</details>
=> fix simple_pattern_create on freebsd

.github/workflows/build.yml
This is done via a new PR label called `run-ci/no-cache`. When present on a PR, this should skip any `actions/cache` actions and any associated support actions for caching so that the CI runs do not use caches.
Intended to simplify debugging when caching causes issues.
Observe that the static build jobs on this PR do not do any caching.
Also fixes a long-standing bug in the static build workflow.
=> Add support for bypassing static build cache on PRs.

system/install-service.sh.in
This fixes a relatively minor bug in our handling of system service installation, making sure the code properly bails out if autodetection failed. There should be no behavioral changes from a user perspective other than eliminating some error messages.
Attempt to install the agent in a container using a local build or static build.
When not using this branch, a handful of error messages such as `/usr/libexec/netdata/install-service.sh: line 651: install_detect_service: command not found` and `/usr/libexec/netdata/install-service.sh: line 661: detect_cmds: command not found` should be seen near the end of the output (you may have to scroll up to see them).
When using this branch, none of those error messages should be present.
=> Properly handle service type detection failures when installing as a system service.

packaging/docker/Dockerfile, packaging/docker/run.sh
Some builds using Podman/Buildah in place of Docker for the build process seem to leave strange permissions in the resultant containers. This adds code to handle those issues and fix them so that the containers still work.
Confirm that containers still work correctly with this PR (can’t really test the specific problem case this is fixing as nobody else seems to be able to reproduce it).
Fixes: #14237
=> Fix intermittent permissions issues in some Docker builds.

database/sqlite/sqlite_aclk_node.c
Currently, if a parent is claimed to the cloud, but one or more children are not currently connected, the parent will advertise the children's versions as `unknown`.
This creates a bit of confusion on the nodes tab on the cloud.
This change just affects the version we send if the child is not streaming, and it's the last known we've stored in the db.
Create a parent/child and claim the parent. When child is online version should be correctly reported. Stop both and only start the parent. Without this PR the version reported for the child would be `unknown`. Using this PR the version reported in the same situation should be the last known from the child.
</details>
=> If a child is not streaming, send to the cloud last known version instead of unknown

aclk/aclk.c, database/sqlite/sqlite_db_migration.c, database/sqlite/sqlite_functions.c
Fixes #14637 
For some reason, in the user's case on the linked issue (thanks a lot @wmertens for the help!), his `host` table included an entry with a host with no hops information (empty), as long with the proper localhost one.
This likely because of a combination of db migration (updating from an old version) and the creation of a new guid.
If this happens, then `aclk_send_node_instances` will load the bad entry, but `rrdhost_find_by_guid` won't return any `host` for it. This PR just adds a check for NULL `host` there, as well as making sure to load only entries with hops >=0 from db in `get_node_list`. Either of those should fix the crash.
It also add a default value to hops when migrating, similar to what we have when creating the table.
Without this PR, on a claimed agent, make …
=> Guard for null host when sending node instances

contrib/debian/netdata.conffiles, contrib/debian/rules
By default, DEB package tooling blindly assumes that any files under `/etc` are configuration files and thus should be handled specially during updates and removals. This is usually correct behavior, but we install a couple of things in `/etc/netdata` for convenience reasons that should not be handled this way, so we need to override this behavior and explicitly specify the list of files to treat as config files.
1. [Build native packages locally](https://github.com/netdata/netdata/blob/master/packaging/building-native-packages-locally.md) for your test environment.
2. Install the netdata package from step 1 in a clean test environment.
3. Uninstall the netdata package _without_ using `apt-get purge` or the `--purge` option.
4. Manually remove `/etc/netdata`.
5. Install the netdata …
=> Handle conffiles for DEB packages explicitly instead of automatically.

.github/scripts/platform-impending-eol.py, .github/workflows/platform-eol-check.yml
- Handle error cases correctly in the Python script.
- Don’t run with `set -e` for the actual check step, because we need the exit code passed on correctly to interpret the output.
n/a
=> Fix platform EOL checks to properly return success.

packaging/check-kernel-config.sh
Fixes https://github.com/netdata/netdata/issues/14668
This PR is fixing current bug reported when script run on `Gentoo Linux`.
1. Verify `shellcheck` is not reporting error on CI.
2. Compile on your system and check that you do not have warnings.
This PR addresses only installation, so it is not necessary to test on different kernels, neither to take a look on charts.
- Which area of Netdata is affected by the change? Installer
- Can they see the change or is it an under the hood? If they can see it, where? During installation on Gentoo.
- How is the user impacted by the change? On `Gentoo` users won't have issue to install. 
- What are there any benefits of the change? A better …
=> Fix kernel test script

collectors/ebpf.plugin/ebpf.c, collectors/ebpf.plugin/ebpf.h, collectors/ebpf.plugin/ebpf_apps.c, collectors/ebpf.plugin/ebpf_apps.h, collectors/ebpf.plugin/ebpf_cachestat.c, collectors/ebpf.plugin/ebpf_cachestat.h, collectors/ebpf.plugin/ebpf_dcstat.c, collectors/ebpf.plugin/ebpf_dcstat.h, collectors/ebpf.plugin/ebpf_disk.c, collectors/ebpf.plugin/ebpf_fd.c, collectors/ebpf.plugin/ebpf_fd.h, collectors/ebpf.plugin/ebpf_filesystem.c, collectors/ebpf.plugin/ebpf_hardirq.c, collectors/ebpf.plugin/ebpf_mdflush.c, collectors/ebpf.plugin/ebpf_mount.c, collectors/ebpf.plugin/ebpf_oomkill.c, collectors/ebpf.plugin/ebpf_process.c, collectors/ebpf.plugin/ebpf_shm.c, collectors/ebpf.plugin/ebpf_shm.h, collectors/ebpf.plugin/ebpf_socket.c, collectors/ebpf.plugin/ebpf_socket.h, collectors/ebpf.plugin/ebpf_softirq.c, collectors/ebpf.plugin/ebpf_swap.c, collectors/ebpf.plugin/ebpf_vfs.c, collectors/ebpf.plugin/ebpf_vfs.h, libnetdata/ebpf/ebpf.c, libnetdata/ebpf/ebpf.h, web/gui/dashboard_info.js
This PR is adding metrics to monitor how eBPF.plugin memory usage. The new metrics will show:
- Total memory allocated for hash table (Same algorithm used by `bpftool`).
- Charts to monitor calls to allocate ARAL and memory allocated per ARAL.
This PR is also renaming ARAL regions to match what is shown on user dashboard.
1. Compile this branch with CFLAG `NETDATA_DEV_MODE`
2. Modify your configuration file `/etc/netdata/ebpf.d.conf` and enable integration between eBPF and apps:
```sh
[global]
apps = yes
cgroups = yes
```
3. Take a look if charts are shown inside `Netdata Monitoring`.
- Can they see the change or is it an …
=> eBPF new charts (user ring)

daemon/system-info.sh
Fix Azure IMDS to ensure Netdata can detect that it is an Azure instance and the flavor and region
Tested locally on an Azure instance
```
NETDATA_INSTANCE_CLOUD_TYPE=Azure
NETDATA_INSTANCE_CLOUD_INSTANCE_TYPE=Standard_B1s
NETDATA_INSTANCE_CLOUD_INSTANCE_REGION=northeurope
```
- Which area of Netdata is affected by the change? 
The node is displayed as Azure cloud node with the respective flavor on Netdata UI
- Can they see the change or is it an under the hood? If they can see it, where?
On the Netdata UI, in the nodes tab
- How is the user impacted by the change? 
The user now gets more information about the node
- What are there any benefits of the change? 
Same answer as above.
=> Fix Azure IMDS

collectors/charts.d.plugin/charts.d.plugin.in, collectors/plugins.d/plugins_d.h, collectors/plugins.d/pluginsd_parser.c
Fixes #14531 
This PR adds a last will EOF when a charts.d.plugin script exits.
It appears that under some cases, `fgets` in parser will trigger at the exact moment the script is asked to exit, cleans up `/tmp` and exits. `fgets` then will wait forever. The EOF here just makes sure `fgets` will receive something before the script exits.
The issue is more apparent when there are a lot of different charts.d.plugin scripts that are restarted at the same time.
Many many thanks to @vobruba-martin for helping with this!!
Not really easy to reproduce. We've tested this on @vobruba-martin's setup and it seems to fix the issue. I don't expect it to cause any side effects, but for testing, e.g. the example charts.d.plugin, make sure it restart correctly.
<details> <summary>For users: How does this …
=> Send an EOF from charts.d.plugin before exit

daemon/system-info.sh
After migration to Kubernetes CRI containerd netdata-child no longer correctly detects the host OS. It ends up with a situation in that I'm having a host OS like `Alpine Linux` instead of `Amazon Linux`:
As a solution is to provide detection that the container is running in Kubernetes, it allows you to detect the host OS even running in different Kubernetes CRI.
n/a
n/a
=> fix: detect the host os in k8s on non-docker cri

database/sqlite/sqlite_aclk.c
- A recent PR that was merged causes a compilation error when  --disable-cloud is specified. This PR fixes it.
- Suppress a few compilation warnings as well
=> Fix compilation error when --disable-cloud is specified

contrib/debian/netdata.conffiles, contrib/debian/rules
Reverts netdata/netdata#14662
We may introduce a bug here, opening this in advance to run the CI with a head start. Related issue https://github.com/netdata/netdata/issues/14698
=> Revert "Handle conffiles for DEB packages explicitly instead of automatically."

system/edit-config
This allows `edit-config --list` to work if there is no usable `tput` command.
This can be tested by attempting to run `edit-config --list` in an environment that does not have ncurses installed. This is likely most easily done by installing a static build in an Alpine container, and manually copying in the `edit-config` script form this PR for testing.
Using the version of the `edit-config` script in the master branch, running `edit-config --list` will fail in such an environment.
With the changes in this PR, it should instead work, but will only list the config files in one column instead of using multiple columns based on the terminal size.
Issue originally reported by @cakrit on Slack.
=> Don’t try to use tput in edit-config unless it’s installed.

.github/data/distros.yml, .github/scripts/ci-support-pkgs.sh, .github/scripts/pkg-test.sh, .github/scripts/run-updater-check.sh, netdata-installer.sh, packaging/PLATFORM_SUPPORT.md, packaging/installer/kickstart.sh, packaging/installer/netdata-updater.sh, packaging/repoconfig/netdata-edge.repo.al, packaging/repoconfig/netdata-repo.spec, packaging/repoconfig/netdata.repo.al
This initial PR adds it in the Intermediate support tier due to the limited testing so far. The plan is to migrate it to Core tier once we have solid evidence that it works reliably, likely some time after the release of v1.39.0.
New CI passes on this PR.
Any further testing requires this to be merged and wait for nightlies to be published.
Resolves: https://github.com/netdata/netdata/issues/14199
This also includes a number of other minor bug fixes, mostly related to the installer and updater code.
=> Add Amazon Linux 2 to CI and platform support.

claim/README.md
This PR closes netdata/learn#1036
It adds the steps the user needs to take to remove a Docker node from his space and then reconnect it to another Space
=> Add instructions for reconnecting a Docker node to another Space

netdata.spec.in
Find issue with x86_64 mock build
```make
+ /builddir/build/BUILD/netdata-v1.38.1/packaging/bundle-libbpf.sh /builddir/build/BUILD/netdata-v1.38.1 centos8
cp: cannot stat '/builddir/build/BUILD/netdata-v1.38.1/packaging/current_libbpf.checksums': No such file or directory
cp: cannot stat '/builddir/build/BUILD/netdata-v1.38.1/packaging/current_libbpf.version': No such file or directory
v1.1_netdata.tar.gz: OK
make: Entering directory '/builddir/build/BUILD/netdata-v1.38.1/externaldeps/libbpf/libbpf-1.1_netdata/src'
Package libelf was not found in the pkg-config search path.
Perhaps you should add the directory containing `libelf.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libelf', required by 'virtual:world', not found
MKDIR    build//staticobjs
CC …
```
=> RPM: Added elfutils-libelf-devel for build with eBPF

.github/workflows/docker.yml
Triggered by our Docker workflow as the MSI build uses our Docker image to produce the WSL image that gets used by the MSI install process.
Merge it and wait for the next stable release (unfortunately no good way to test this other than that).
Closes: https://github.com/netdata/msi-installer/issues/32
=> Auto-trigger MSI build on release.

build_external/scenarios/children-to-localhost/README.md, build_external/scenarios/children-to-localhost/child_stream.conf, build_external/scenarios/children-to-localhost/docker-compose.yml, build_external/scenarios/children-to-localhost/parent_stream.conf
The new scenario allows someone to easily spawn a custom number of agents that will stream
to a localhost parent. Useful for quick development.
- N/A (See newly added `README.md`).
=> New build_external scenario.

collectors/python.d.plugin/pandas/pandas.chart.py
this was a small typo on my end and we should use `self.warning()` instead of `self.warn()`. `self.warn()` throws error and fails the check().
Tested locally on agents where these lines end up being called, 
</details>
=> pandas collector replace `self.warn()` with `self.warning()`

database/rrd.h
Fixes: #14730
Fixes: #14515
This change affects only memory mode `save`: Netdata fails to use `save` and fallbacks to `ram` for charts with id > 200.
Update existing install and ensure that:
- no metrics lost
- no additional memory usage
- charts with id > 200 can be created
For memory mode `dbengine`.
</details>
=> increase RRD_ID_LENGTH_MAX to 1000

web/api/web_api_v1.c
Fixes #14754 
Accept `/api/v1/alarms?all=true` to show all alerts via the api call, instead of just `?all`.
Check if `http://localhost:19999/api/v1/alarms?all=true` shows all alerts.
</details>
=> Accept all=true for alarms api v1 call

.github/data/distros.yml
Safe merge, 
no CI honor is needed.
=> minor addition to distros matrix

collectors/proc.plugin/sys_block_zram.c
Fixes: #14758
proc zram collector doesn't respect [host access prefix](https://github.com/netdata/netdata/blob/d31cd412c5968021c48891942187a432f1fd50e7/daemon/main.c#L1147) (set to `/host` [in Docker](https://github.com/netdata/netdata/blob/d31cd412c5968021c48891942187a432f1fd50e7/packaging/docker/run.sh#L85)). This PR fixes this issue.
> **Warning**: The additional mount is required for proc zram to work in Docker: `-v /dev:/host/dev:ro`
Setup zram and see that it works:
- Dockerized Netdata.
- Regular Netdata installation.
</details>
=> fix /sys/block/zram in docker

collectors/COLLECTORS.md, collectors/python.d.plugin/alarms/README.md, collectors/python.d.plugin/zscores/README.md, collectors/statsd.plugin/README.md, docs/cloud/cheatsheet.md, docs/cloud/insights/anomaly-advisor.md, docs/cloud/insights/metric-correlations.md, docs/cloud/manage/view-plan-billing.md, docs/cloud/visualize/dashboards.md, docs/guides/monitor/anomaly-detection.md, docs/guides/monitor/kubernetes-k8s-netdata.md, docs/guides/monitor/pi-hole-raspberry-pi.md, docs/guides/troubleshoot/troubleshooting-agent-with-cloud-connection.md, docs/store/distributed-data-architecture.md, health/REFERENCE.md, packaging/installer/methods/kickstart.md, packaging/installer/methods/macos.md, packaging/installer/methods/manual.md, packaging/installer/methods/offline.md
Related to https://github.com/netdata/learn/issues/1522
This PR replaces links inside markdown files that begin with `learn.netdata.cloud` with their `https://github.com/...` counterparts.
Along with this, wherever I saw "what's next" sections I removed them, and also formatted the files.
=> Replace hardcoded links pointing to "learn.netdata.cloud" with github absolute links

database/engine/journalfile.c, database/engine/journalfile.h, database/engine/pagecache.c, database/sqlite/sqlite_functions.c
New version of the journal v2
- Keep the latest update every in the metric directory list
This will make populating the metric registry faster (vs having to jump to the last page per metric to fetch the latest update every)
- Use memcmp to sort and search metric UUIDs
- Faster scan of the v2 journal files during queries
- Skip chart label cleanup during startup (will be done later) 
When applied, this PR will do a full rebuild of the existing journal v2 files
=> Update journal v2

database/contexts/instance.c, database/contexts/metric.c, database/contexts/rrdcontext.c, database/engine/pagecache.c, database/engine/rrdengine.c, database/engine/rrdengine.h, database/engine/rrdengineapi.c, database/sqlite/sqlite_aclk.h, database/sqlite/sqlite_aclk_alert.c, database/sqlite/sqlite_functions.c, libnetdata/inlined.h
=> uuid_compare() replaced with uuid_memcmp()

collectors/cgroups.plugin/sys_fs_cgroup.c
Because it is more native in K8s. Requested by @M4itee.
ci
</details>
=> use mCPU in k8s cgroup cpu charts title

aclk/aclk.c, aclk/aclk.h, database/rrdhost.c, database/sqlite/sqlite_aclk.c, database/sqlite/sqlite_aclk.h, database/sqlite/sqlite_aclk_node.c, database/sqlite/sqlite_metadata.c, streaming/receiver.c
Resolve a timing issue when announcing the capabilities of a child when connecting to cloud via ACLK
During agent startup the capabilities of a child are not known (since the child is not connected and may not connect). The node information related to the child needs to reach the cloud though, based on stored metadata. 
When the child eventually connects the information needs to be updated
Fixes: #14783
=> Schedule node info to the cloud after child connection

daemon/system-info.sh
Reported on [Discord](https://discord.com/channels/847502280503590932/1088195686706716682).
An instance returns unexpected data and 200 to the following query:
https://github.com/netdata/netdata/blob/4da956f37476e791d319a33962f440f00efa2ed2/daemon/system-info.sh#L465
The instance (!)
> has no relation to Google or any other cloud provider. It's a VM on my own Proxmox machine
Response:
```
<html><head><title>metadata.google.internal</title></head><body><h1>metadata.google.internal</h1><p>Coming soon.</p></body></html>
```
</details>
This PR adds an additional data validation step before considering the host to be a GCP cloud host.
Test on a GCP VM and on an instance that returns unexpected data.
</details>
=> add validation step before using GCP metadata

collectors/diskspace.plugin/plugin_diskspace.c
Fixes: #14804
Related [discussion on Discord](https://discord.com/channels/847502280503590932/1072639867785334876/1072639867785334876).
After this PR Netdata will ignore collecting inode stats for mount points with `msdosfs` filesystem.
Implemented by adding the `exclude inode metrics on filesystems` configuration option with default value `msdosfs msdos vfat overlayfs aufs* *unionfs`.
Use `exclude inode metrics on filesystems` to disable inode metrics for configured filesystems.
</details>
=> diskspace: don't collect inodes on msdosfs

.github/workflows/packaging.yml, .github/workflows/repoconfig-packages.yml
- Don’t fail jobs if publishing to PackageCloud fails (it’s expected to fail in a number of circumstances).
- Do fail jobs if we can’t publish to our own hosting infrastructure.
n/a
=> Fix failure logic for publishing packages.

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
This tidies up the list of installation methods in our bug report issue template.
- Remove `kickstart-static64.sh`, as it’s not actually been a thing for more than a year now.
- Remove `native packages (deb/rpm)`, as it’s a consistent source of confusion. The original intent seems to be using this for our official packages, except that they’re mostly just covered under `kickstart.sh` as most users are using them, and many people seem to be getting confused by this and using it for installs done through the system package manager even if they are not our official packages.
- Move the `from git` and `from source` options to the bottom of the list. These are uncommon scenarios, so they should logically be sorted last.
- Add an option indicating manual setup of our official packages. This is …
=> Clean up install method list in bug report template.

daemon/main.c, database/engine/pagecache.c, database/engine/rrdengineapi.c, database/engine/rrdengineapi.h
This PR allows users to configure the extent cache size of dbengine.
Users may need to configure the extent cache size to control the number of I/O operations on very busy servers.
=> configure extent cache size

.github/data/distros.yml, .github/scripts/pkg-test.sh, netdata.spec.in, packaging/PLATFORM_SUPPORT.md
Just like with Amazon Linux 2, this PR adds AL 2023 to the Intermediate tier with plans to move it to Core after 1.39.0 assuming no issues are encountered.
New CI passes on this PR.
Any further testing requires this to be merged and wait for nightlies to be published.
=> Add Amazon Linux 2023 to CI, packaging, and platform support.

collectors/ioping.plugin/README.md, collectors/python.d.plugin/zscores/README.md, docs/guides/collect-apache-nginx-web-logs.md, docs/guides/monitor/kubernetes-k8s-netdata.md, docs/guides/monitor/lamp-stack.md, docs/guides/monitor/raspberry-pi-anomaly-detection.md, docs/guides/using-host-labels.md, packaging/building-native-packages-locally.md
This is related to https://github.com/netdata/learn/issues/1507
It addresses documents that had too long a title. I added below the title one line of description, to lot lose information from the doc, look at the child issues referenced in the issue above.
=> Docs, shorten too long titles, and add a description below

collectors/proc.plugin/proc_spl_kstat_zfs.c
The issue was [reported on Discord](https://discord.com/channels/847502280503590932/1090805963444985896/1090805963444985896).
We don't need the host prefix here
https://github.com/netdata/netdata/blob/0ac8f7c4f0278cdeac5172ee715d0c590a947f3a/collectors/proc.plugin/proc_spl_kstat_zfs.c#L370
because `dirname` already has it.
https://github.com/netdata/netdata/blob/0ac8f7c4f0278cdeac5172ee715d0c590a947f3a/collectors/proc.plugin/proc_spl_kstat_zfs.c#L322-L323
Install netdata on a server with ZFS, check pools charts.
</details>
=> fix double host prefix when reading ZFS pools state

CMakeLists.txt, Makefile.am, aclk/aclk_capas.c, database/contexts/api_v2.c
Small PR - title is pretty much all that can be said about it.
Added as agent and node_instance capa (as each node_instance can be queried about using v2 if agent speaks v2)
Not added to node capas as we do not know currently whether child can speak v2 api by itself
Fixes #14800
</details>
=> minor - add capability signifying this agent can speak apiv2

collectors/python.d.plugin/ceph/ceph.chart.py
Fix Exception TypeError: Argument 'inbuf' has incorrect type (expected bytes, got str) in ceph.chart.py
function call  Rados.mon_command()
```python
Reproduce exception:
>>> import rados, json
>>> cluster = rados.Rados(conffile='/etc/ceph/ceph.conf', conf=dict(keyring='/etc/ceph/ceph.client.admin.keyring'))
>>> cluster.connect()
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'df', 'format': 'json'}), '')[1])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: Argument 'inbuf' has incorrect type (expected bytes, got str)
```
related librados documenation: https://docs.ceph.com/en/latest/rados/api/python/#rados.Rados.mon_command
example from ceph docs:
```python
import json
c = Rados(conffile='/etc/ceph/ceph.conf')
c.connect()
cmd = …
```
=> fix  #14841 Exception funktion call Rados.mon_command()

.github/workflows/review.yml
This adds a new check to the Review workflow which runs `clang-format` against any modified C/C++ files in a PR.
By default, this check is skipped if no C/C++ files are modified.
This check can be forced to run against the entire repository on a given PR by labeling that PR with the `run-ci/clang-format` label.
Observe the run on this PR due to the `run-ci/clang-format` label.
Fixes: https://github.com/netdata/netdata/issues/13769
=> Add basic clang-format checking to PR review.

packaging/installer/kickstart.sh, packaging/installer/netdata-updater.sh
Most of this is internal restructuring of the kickstart.sh and netdata-updater.sh code to make it easier to read and maintain. It additionally includes the following fixes in the updater code:
- The updater script now properly works for native packages on Oracle Linux and Amazon Linux (it previously would crash).
- When using a crontab for scheduling auto updates, we now use the one installed under `/usr/lib/netdata/system` instead of hard-coding it into the updater script. This eases maintenance of this scheduling method (as it ensures what users likely find in the repo is what gets used).
Preliminary testing simply consists of confirming passing CI.
Applied testing of the kickstart changes should focus on confirming that the `--native-only`, `--static-only`, and `--build-only` options …
=> Assorted installer code cleanup.

.github/workflows/review.yml
This will ensure they only run when needed, and only on the files they should be run on, instead of running on every PR and always failing because they try to run on every file changed by the PR.
n/a
=> Fix regex syntax for clang-format checks.

collectors/cgroups.plugin/cgroup-name.sh, collectors/cgroups.plugin/sys_fs_cgroup.c, collectors/cgroups.plugin/sys_fs_cgroup.h, collectors/cgroups.plugin/tests/test_cgroups_plugin.c, collectors/proc.plugin/proc_net_dev.c
Fixes: #14799
This PR adds the `image` label to all cgroups except k8s.
- for docker/podman cgroups: the "image" label value is the actual image name.
- the rest: the "image" label value is "" (no value, Netdata replaces it with `[none]`).
<details>
<summary>Cloud screenshot</summary>
</details>
Test on:
- a host with docker and not docker container
- a k8s host
</details>
=> cgroups.plugin: add image label

.github/workflows/review.yml, packaging/makeself/jobs/99-makeself.install.sh, packaging/makeself/makeself-header.sh, packaging/makeself/makeself-license.txt, packaging/makeself/makeself.lsm, packaging/makeself/makeself.sh
This syncs our bundled version of makeself with [the latest upstream release](https://github.com/megastep/makeself/releases/tag/release-2.5.0), as we’ve been using a version that is almost six years out of date. The update should significantly improve compatibility on more exotic Linux systems.
It also updates the metadata we embed in the archive itself to better reflect the current state of the project.
Testing consists of creating static builds locally from this PR and verifying that they install correctly.
Fixes: https://github.com/netdata/netdata/issues/9517 (probably), and likely a number of other issues related to static installs.
=> Update the bundled version of makeself used to create static builds.

packaging/installer/UNINSTALL.md
Related to https://github.com/netdata/netdata/issues/14889, currently `--dry-run` doesn't function as we want, so we might as well not mention it for now in the docs as something that is expected to work.
=> Remove dry run option from uninstall documentation

collectors/cgroups.plugin/cgroup-name.sh
An attempt to fix: #14843
---
This PR adds an option to retrieve Pods metadata from Kubelet instead of the Kubernetes API Server. This can mitigate the problem when Kube API Server is overloaded with a large number of requests. Larger cluster (more nodes -> more Netdata children instances) - more load on Kube API Server (#14843 is a 100+ nodes cluster).
> **Note** We need Pods metadata to enrich cgroups metrics in K8s: to resolve names and add labels. Each child instance of Netdata executes requests.
Kubelet's `/pods` endpoint is undocumented and shouldn't be relied on (see [1](https://github.com/fluent/fluent-bit/issues/1948#issuecomment-680291735), [2](https://github.com/fluent/fluent-bit/issues/1948#issuecomment-691219053)) - therefore it is disabled by default. But it is nice to have …
=> cgroups: add option to use Kubelet for pods metadata

database/rrd.h, streaming/replication.c, web/api/queries/weights.c
Fix compilation error and warnings when compiling from source using `--disable-dbengine`
=> Fix warnings and error when compiling with --disable-dbengine

collectors/charts.d.plugin/README.md
There were some users asking where they can find the explanations  for `CHART`, `DIMENSION` etc.
They should have first have read (or refer to) [this](https://github.com/netdata/netdata/blob/master/collectors/plugins.d/README.md) page.
We had some links in the file, but they were so many, essentially in every section, 
I added one link inside a note comment, right before explaining what a charts.d module is, so the user can have it as a reference (it is also more visible than a bold link at the end of a sentence) 
Then removed the links inside the individual sections, reformatted the file and used the up-to-date snippet for referring to editing configuration.
=> Fix/introduce links inside charts.d.plugin documentation 

collectors/cgroups.plugin/README.md, packaging/docker/README.md
I'm a heavy Netdata user and have the need to deploy it securely on Docker. Given how critical it is to give a service access to the socket, I've recently developed [CetusGuard](https://github.com/hectorm/cetusguard), a Docker socket proxy that has no dependencies, is distributed in an image built from scratch and allows to define narrower filtering rules than the currently proposed solution.
A complete example of a Netdata deployment with CetusGuard can be found [here](https://github.com/hectorm/cetusguard/blob/master/examples/compose/compose.netdata.yml).
I'm not quite sure whether the best approach to this PR is to add CetusGuard as an alternative to the current solution or to replace it. I have chosen the second option because CetusGuard covers this use case completely.
=> Document CetusGuard as a Docker socket proxy solution

daemon/global_statistics.c, daemon/main.c, daemon/main.h, database/rrdhost.c, ml/Config.cc, ml/ad_charts.cc, ml/ad_charts.h, ml/ml-dummy.c, ml/ml-private.h, ml/ml.cc, ml/ml.h
This PR applies again the changes introduced in https://github.com/netdata/netdata/pull/14810. This time we properly skip ML initialization when ML has been disabled in netdata.conf.
- CI jobs
- Disable ML in netdata.conf and make sure the agent starts successfully without crashing
=> Skip ML initialization when it's been disabled in netdata.conf

daemon/analytics.c, daemon/analytics.h, daemon/main.c, database/rrdhost.c
If the agent fails to initialize before the localhost is created, the machine GUID remains uninitialized and ends up as 
`0000000`s in the collected statistics. This PR allows for proper distinct count of agents that fail to initialize.
=> Initialize machine GUID earlier in the agent startup sequence

collectors/proc.plugin/proc_spl_kstat_zfs.c
This PR adds the missing ZFS pool state (suspended), somehow we missed it. It was added in https://github.com/openzfs/zfs/commit/f0ed6c744872ec6dc4838947ffc597f4d141864a.
Test on a system with ZFS
</details>
=> zfspool: add suspended state

collectors/proc.plugin/README.md
This file didn't have a description, we should explain in brief what it is, and also give a hint that it is not an external plugin. We were explaining it in another file, so I got that description and modified it to fit.
=> Add a description to proc.plugin/README.md

docs/cloud/cheatsheet.md
Closes https://github.com/netdata/learn/issues/1597
This PR tries to make the cheat sheet be again in a printable form.
The sections left out were commented out and some info is condensed to fit A4 pages.
The goal is to be able to save as PDF using your web browser's built-in function.
I'd be happy to discuss what you think should/shouldn't be in this cheat sheet, I used the commands that I seemed to look for when deploying Netdata into my homelab, so maybe you got other things that you deem are necessary to be in this array of pages.
Just keep in mind, that this has to be the least pages possible, and stuff like the drop down in the start helps with space when collapsed and printed. 
I went ahead and saved the cheat sheet in a PDF by right clicking in the page and selecting "print", …
=> Optimize the cheat sheet to be in a printable form factor 

collectors/python.d.plugin/nvidia_smi/README.md
These instructions allow for Nvidia GPU monitoring inside of a docker container. The `gcompat` apk adds a glibc library for binaries linked against glibc, like Nvidia drivers, which don't natively work with musl distributions like Alpine. 
Fixes #4736 
I have tested this on x86_x64 using `netdata/netdata:latest` but I don't have access to any other architectures with an Nvidia GPU. If anyone with other architectures and Nvidia GPUs could test these configs, it would be appreciated.
The use of Alpine as a Netdata docker base creates a problem for users wanting to monitor Nvidia GPUs in a container. Nvidia drivers and binaries like `nvidia-smi` require glibc. These instructions show how to add `gcompat` to a netdata docker container, and the standard way to add a GPU to a docker containers …
=> Add Docker instructions to enable Nvidia GPUs

database/sqlite/sqlite_aclk_alert.c
Continuing from #14325, this PR also adds the same check to alert snapshots, so alert templates that are actually variables will not be transmitted through alert snapshot events.
A bit tricky to test, but with `conversation log` enabled, when a snapshot is triggered (mess a bit with sequence numbers in `aclk_alert_` table, or manually call `aclk_process_send_alarm_snapshot` from health main loop, in e.g. the 10th loop), check if alerts such as `load_cpu_number` or `interface_speed` appear in the snapshot message (they should not).
</details>
=> Skip alert template variables from alert snapshots

cli/cli.c, daemon/commands.c, daemon/commands.h, daemon/main.c, libnetdata/buffer/buffer.h
- Removes the 4K char response size limitation
- Add a `netdatacli dumpconfig` command to get the current `netdata.conf`
Fixes #14755
=> Remove netdatacli response size limitation

ml/ml.cc
This is a temporary change until we figure out
why sqlite degrades the performance of training
threads significantly. To keep the number of
changes to a minimum, a connection is still
opened/closed when initializing/finalizing the
ML component.
- Tested on a parent with ~100 children
- CI jobs
=> Disable SQL operations in training thread

web/gui/custom/README.md
a slash was missing from an image element, thus it was causing Docusaurus to crash.
=> Terminate JSX element in doc file

database/rrdhost.c
There is a crash possibility if we have a parent / child setup as follows: 
- Parent is set to "mode = dbengine" 
- Child is set to "default memory mode = ram"  in stream.conf
When restarting the parent, upon child connection there might be a crash. 
This is because the parent might have a context load in progress and the switch (in this case) to "ram" will attempt to recreate the host with the new memory mode causing corruption.
This PR attempts to fix it by rejecting the child connection until the context load has finished loading.
=> Reject child when context is loading

packaging/installer/functions.sh
- Use `getent` when possible to check if user exists. This makes us correctly find an existing user on systems which use mechanisms other than just flat files for defining users.
- When adding a user, adding a group, or adding a user to a group, only try the first supported command we find, instead of trying each one we find in sequence until one works.  This prevents us from incorrectly making multiple attempts to do these operations when we should not do so.
This should only affect static builds and local installs. Basic testing involves just checking that we install correctly. Ideally we should also test on systems that use mechanisms other than a flat password file for defining system users, but I do not believe any of us at Netdata actually have such a system to test on, so this part …
=> Fix handling of users and groups on install.

database/rrd.h, database/rrddim.c, database/rrdhost.c, database/rrdset.c, ml/ml-private.h, ml/ml.cc
- Adds support for acquiring/releasing RRDHOSTs and RRDSETs,
- Uses aforementioned functionality in ML,
- Skip training requests from obsolete/archived hosts & charts.
Fixes a non-deterministic crash that would occur when child agents
disconnected from a parent with a low cleanup threshold.
- CI jobs.
Fixes #14941
=> Add support for acquire/release operations on RRDSETs

database/contexts/internal.h, database/rrd.h, web/api/web_api_v1.c
=> interrupt callback on api/v1/data

packaging/docker/README.md
Correct spelling in `packaging/docker/README.md` from `Github Acions` to `Github Actions`
Double checked the spelling of the word in the dictionary.
Correct spelling in `packaging/docker/README.md` from `Github Acions` to `Github Actions`. 
Typo's and grammatical errors in documentation can give project a non-professional perception.
</details>
=> Fix TYPO in README.md

libnetdata/config/appconfig.c
This PR fixes the problem introduced in [#14874](https://github.com/netdata/netdata/pull/14874/commits/595074251fb22db333458b384ef50668123b8ee7) - `appconfig_generate()` skips all `[plugins:*]` sections.
Check the `/netdata.conf` endpoint.
</details>
=> fix config generation for plugins

.github/data/distros.yml, packaging/PLATFORM_SUPPORT.md
EOL of Alpine 3.14 during May, 
Closes https://github.com/netdata/netdata/issues/14852
Do not merge this PR until 2023-05-01
</details>
=> Remove alpine 3.14 from the ci

health/notifications/alarm-notify.sh.in
From reading [this comment](https://github.com/netdata/netdata/issues/9858#issuecomment-687116258) I was expecting the opsgenie integration to correctly set the level based on the alert severity. However, it does not set this property which results in all alerts defaulting to priority P3.
This is a minor change that **I HAVE NOT TESTED** as I am not well setup to build from source. If necessary I can attempt to setup a dev environemnt, however, hopefully someone from the team can quickly validate my PR & test it (provided this change is desired).
- This change affects the OpsGenie alert behavior in `health/notifications/*`.
- This will change the default priority on OpsGenie for any users of the integration. This means `WARN` level will remain the same but `CLEAR` and `CRITICAL` will …
=> feat: add OpsGenie alert levels to payload

collectors/COLLECTORS.md
Ingest was crashing due to https://github.com/netdata/go.d.plugin/pull/1166 not removing the links inside our docs
=> Remove lighttpd2 from docs

database/sqlite/sqlite_aclk.c, database/sqlite/sqlite_aclk_alert.c, database/sqlite/sqlite_functions.c, database/sqlite/sqlite_functions.h, database/sqlite/sqlite_health.c, database/sqlite/sqlite_metadata.c, database/sqlite/sqlite_metadata.h, libnetdata/log/log.c, ml/Config.cc, ml/ml-dummy.c, ml/ml-private.h, ml/ml.cc, ml/ml.h
- The metasync queue is used to load models when a dimension is created,
- The training thread batches models to save and flushes them with a single transaction.
- CI jobs
- Local parent with 200 children
- Set the desired `number of models per dimension` under the `[ml] config section, let the agent run for a sufficient time, restart the agent.
=> Load/Store ML models

libnetdata/log/log.c
@stelfrag send me the following error report:
```sh
#0  futex_wait (private=0, expected=2, futex_word=0x56026eae3ae0 <log_mutex>) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x56026eae3ae0 <log_mutex>, private=0) at ./nptl/lowlevellock.c:49
#2  0x00007f8ed2064082 in lll_mutex_lock_optimized (mutex=0x56026eae3ae0 <log_mutex>) at ./nptl/pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x56026eae3ae0 <log_mutex>) at ./nptl/pthread_mutex_lock.c:93
#4  0x000056026e08b9cf in __netdata_mutex_lock (mutex=0x56026eae3ae0 <log_mutex>) at libnetdata/locks/locks.c:84
#5  0x000056026e08c72a in log_lock () at libnetdata/log/log.c:490
#6  0x000056026e08dae2 in error_int (is_collector=0, prefix=0x56026e82b1e7 "ERROR", file=0x56026e82b1d2 …
```
=> Address log issue

ml/Config.cc, ml/ad_charts.cc, ml/ml-private.h, ml/ml.cc
See https://github.com/netdata/netdata/discussions/14993 for more info.
A couple notes:
- We silence dimensions, not models.
- A dimension stops being silenced whenever we fulfill a training request (regardless of whether it is trained successfully or not).
- You can track the number of silenced dimensions in the `netdata.training_status_on_{hostname}` chart.
- CI jobs,
- Manual testing on staging
=> Silence dimensions with noisy ML models

packaging/installer/kickstart.sh
The primary action is not claiming unless --claim-only is used. kickstart.sh shouldn't fatal if claiming failed. 
Install static build as a regular user, and ensure that failed claiming (fails because of #15036) is not fatal.
</details>
=> fatal in claim() only if --claim-only is used

ml/Config.cc, ml/README.md
- Update default for `number of models per dimension` from `1` to `2` as an incremental minimal step to help reduce noise on AR ribbons.
- Update `dimension anomaly rate suppression window` from `1800` to `900` to be a bit more proactive (while still not being too crazy) in supressing noisey dims.
Tested on ml-demo nodes and does help a little (still more to do) with the noisey dim problem.
</details>
=> Small update ml defaults

health/notifications/health_alarm_notify.conf
Fixes #5887
As discussed on that issue, I was recently affected by the issue that was mentioned, and the solution suggested initially worked for me. However, I wondered if there was a better way to fix this.
What this PR does is comment out the default `role_recipients_*` configuration in the `health_alarm_notify.conf` file. The reason for this is that if those values are left in place, and someone is using a custom copy of `health_alarm_notify.conf` that doesn't overwrite these values, then this default value will always be used as this file is evaluated first by `alarm-notify.sh`.
However, `alarm-notify.sh` falls back to the relevant `DEFAULT_RECIPIENT_*` variable if these values aren't set. This means that the current behaviour is maintained, but it allows someone to either overwrite …
=> Comment out default `role_recipients_*` values

collectors/debugfs.plugin/debugfs_zswap.c
ssia, gather Zswap status from `/sys/module/zswap/parameters/enabled`.
Additionally, this PR simplifies the `zswap_collect_data()` function.
- test with disabled Zswap => no Zswap charts.
- test with enabled Zswap => Zswap charts.
</details>
=> fix(debugfs/zswap): don't collect metrics if Zswap is disabled

aclk/aclk_tx_msgs.c
If `payload_len == 0` then `str` was used as payload. Then `json_object_put_wrapper` is used as "destructor" which then calls `json_object_put` on it instead of calling it on `json_object *msg` as intended 🤦🏻‍♂️. 
Therefore we now convert json_object to string regardless of payload presence and use common destructor in both cases (and freeing json_object instantly)
</details>
=> Fix ACLK memleak

.github/data/distros.yml, packaging/PLATFORM_SUPPORT.md
It goes EOL upstream on 2023-05-18.
n/a
First part of: https://github.com/netdata/netdata/issues/14911
=> Remove Fedora 36 from CI and platform support.

aclk/aclk_query.c, aclk/aclk_tx_msgs.c, aclk/aclk_tx_msgs.h
New MQTT broker on cloud size has maximum message size set to less than maximum MQTT message size.
We honor this limit now.
This gives us following change in behavior:
BEFORE:
- if cloud requested data that were too big for the MQTT broker to handle we sent it anyway leading to MQTT broker disconnecting us. This led to temporary disruption of service for user until the agent reconnected.
AFTER:
- if cloud requests data that are too big for MQTT broker we detect this and report it to cloud with special error code. This way cloud can show this to particular user (who initated the request) but all the other charts (and other users) will not experience any disruption.
</details>
=> Honor maximum message size limit of MQTT server

ml/ml.cc
Probably does not affect the code but this should remove the CodeQL warning
- Multiplication result may overflow 'unsigned int' before it is converted to 'size_t'.
=> Fix CodeQL warning 

aclk/aclk_otp.c
Following a `EVP_PKEY_CTX_new` to get a context and perform a `EVP_PKEY_decrypt` 
release the context to avoid memory leak.
=> Free context when establishing ACLK connection

database/sqlite/sqlite_aclk_alert.c
A small PR to simplify the loop in alerts checkpoint. Instead of doing 2 loops (one to count rcs, one to gather them) it does one. As suggested by @stelfrag, it could happen that the count changes between loops (due to changes in rrdsets).
Claim an agent to the cloud. Raise some alerts, and wait 15 minutes after start. Check the access.log which should indicate an incoming request for a checkpoint, and a subsequent sending. There should not be a snapshot following this exchange.
</details>
=> Simplify loop in alert checkpoint

database/rrdcalc.c, database/rrdcalc.h, database/rrdcalctemplate.c, database/rrdcalctemplate.h, database/sqlite/sqlite_health.c, health/REFERENCE.md, health/health_config.c
This PR adds a new configuration key to alerts, called `chart labels`. This key can be used to specify chart labels that should match (based on simple patterns) in order to link or not an alert. It can be used to provide the same functionality as the `families` key (assuming of course the same values exist as chart labels as family values).
For example, the families key in `disks.conf`:
`families: !/dev !/dev/* !/run !/run/* *` can be replaced with:
`chart labels: !mount_point=/dev !mount_point=/dev/* !mount_point=/run !mount_point=/run/* mount_point=*`
It is part of this initiative: https://github.com/netdata/product/issues/3118
Test by replacing `families` (we use them in disks and net confs mostly) with the appropriate chart labels (disks can be `mount_point`, network devices can be …
=> Use chart labels to filter alerts

collectors/python.d.plugin/oracledb/README.md, collectors/python.d.plugin/oracledb/oracledb.chart.py, collectors/python.d.plugin/oracledb/oracledb.conf
Removes the Python module's requirement of [cx_Oracle](https://cx-oracle.readthedocs.io/en/latest/index.html) which requires users to install and manually configure Oracle Client Libraries. Oracle suggests new projects and users install and use [python-oracledb](https://python-oracledb.readthedocs.io/en/latest/index.html) which is what this merge does. Additionally, this merge allows for support of the newer and faster TLS connections in addition to the old mTLS connections.
This code was developed and run on an Oracle server running a Netdata Agent and has been confirmed to work. Individual database connection components and queries were confirmed to work on both a TLS server and mTLS server, both running 21c.
This new module update will **not** break the functionality of existing …
=> Python Dependency Migration - OracleDB Python Module

database/sqlite/sqlite_health.c
- CID 385075:    (RESOURCE_LEAK)
- Release command buffer in case of error while preparing the SQL statement
=> Release buffer in case of error -- CID 385075

exporting/prometheus/prometheus.c
Fixes #14482 
According our user [investigation](https://github.com/netdata/netdata/issues/14482#issuecomment-1427543026) reorder current labels is enough to fix current issue we have, so this PR is inverting order we are presenting labels.
1. Compile this Branch
2. Access http://localhost:19999/api/v1/allmetrics?format=prometheus and confirm you have labels sorted:
```sh
netdata_netdata_statsd_events_events_persec_average{chart="netdata.statsd_events",dimension="gauges",family="statsd"} 0.0000000 1684933603000
netdata_netdata_statsd_events_events_persec_average{chart="netdata.statsd_events",dimension="counters",family="statsd"} 0.0000000 1684933603000
netdata_netdata_statsd_events_events_persec_average{chart="netdata.statsd_events",dimension="timers",family="statsd"} 0.0000000 …
```
=> Address issue with Thanos Receiver

exporting/prometheus/remote_write/remote_write_request.cc
Fix https://github.com/netdata/netdata/issues/14482
After to adjust order for Prometheus, this PR is reordering labels for remote writer.
1. Configure remote write inside `/etc/netdata/exporting.conf`:
```sh
enabled = yes
send configured labels = yes
send automatic labels = yes
send variables = yes
[prometheus_remote_write:my_prometheus_remote_write_instance]
enabled = yes
destination = localhost:9201
remote write URL path = /write
update every = 3
data source = raw
send charts matching = *
```
3. Start netdata
4. Start prometheus
- Which area of Netdata is affected by the change? prometheus remote writer
- Can they see the change or is it an …
=> Invert order in remote write

ml/Config.cc, ml/README.md
This PR updates the below default params for the `[ml]` section in `netdata.conf`
- `maximum num samples to train` from `14400` (4 hours) to `21600` (6 hours).
- `train every` from `3600` (1 hour) to `10800` (3 hours).
- `number of models per dimension` from `2` to `9`.
The aim of this is to have anomaly detection in Netdata by default (in steady state once all models trained) covering last 24+ hours in terms of "what it is trained on". 
Has been dogfooded internally for last few months. Will create some test ML nodes on this branch to be sure behaviour is as expected.
=> update ml defaults to 24h

database/sqlite/sqlite_aclk_alert.c, database/sqlite/sqlite_health.c, health/health_log.c
This PR changes when an alert is queued to the cloud. Before this change, an alert event would be tried to be queued when both created, and updated. There is no need to try to queue it when it's updated.
Ensure basic alert to cloud functionality.
</details>
=> Only queue an alert to the cloud when it's inserted

collectors/charts.d.plugin/README.md, collectors/charts.d.plugin/ap/README.md, collectors/charts.d.plugin/apcupsd/README.md, collectors/charts.d.plugin/libreswan/README.md, collectors/charts.d.plugin/nut/README.md, collectors/charts.d.plugin/opensips/README.md, collectors/charts.d.plugin/sensors/README.md, collectors/nfacct.plugin/README.md, collectors/perf.plugin/README.md, collectors/slabinfo.plugin/README.md, contrib/debian/control, contrib/debian/netdata-plugin-apps.postinst, contrib/debian/netdata-plugin-debugfs.postinst, contrib/debian/netdata-plugin-ebpf.postinst, contrib/debian/netdata-plugin-freeipmi.postinst, contrib/debian/netdata-plugin-go.postinst, contrib/debian/netdata-plugin-nfacct.postinst, contrib/debian/netdata-plugin-perf.postinst, contrib/debian/netdata-plugin-slabinfo.postinst, contrib/debian/netdata.postinst, contrib/debian/rules, netdata.spec.in, packaging/bundle-ebpf.sh, packaging/bundle-libbpf.sh, packaging/installer/kickstart.sh
This continues the trend that was started a few years back with the CUPS and IPMI collectors of using separate packages for individual plugins. The following plugins are being split to their own packages in this PR:
Long term, I hope to decouple the packaging of the Go plugin and the eBPF programs from the main agent repository so that those can be updated on their own.
Local testing is probably most easily done by [building the packages locally](https://github.com/netdata/netdata/blob/master/packaging/building-native-packages-locally.md).
With this PR, there should be additional packages created for each of the plugins listed above, plus one extra package called `netdata-plugin-ebpf-code`. Oracle Linux, CentOS, and Alma Linux should not include the nfacct plugin, as they do not have the …
=> Split plugins to individual packages for DEB/RPM packaging.

aclk/aclk_capas.c, database/contexts/rrdcontext.h, web/api/formatters/json/json.c, web/api/formatters/rrd2json.h, web/api/netdata-swagger.yaml, web/api/queries/query.c
Improvement over #15109 (which was reverted with #15122) to not break backwards compatibility  of `percentage-of-instance`.
Now the output generated by `/api/v2/data` changes when `aggregation = "percentage"` is requested, but does not change when `group_by = "percentage-of-instance"` is requested, making sure that consumers of previous versions of the API still work.
=> Percentage of group aggregatable at cloud - fixed for backwards compatibility

contrib/debian/rules, packaging/bundle-ebpf.sh
The legacy code was not being bundled properly due to an oversight in bundling script.
Testing can be done by simply building the DEB packages locally and then running `dpkg -c` on the `netdata-ebpf-code-legacy` package to see the list of included files.
Without these changes, the package should only include a few directories and the documentation files.
With these changes, the package should include all of the eBPF programs as well as the documentation files.
=> Fix bundling of eBPF legacy code for DEB packages.

health/health.d/boinc.conf, health/health.d/btrfs.conf, health/health.d/disks.conf, health/health.d/exporting.conf, health/health.d/httpcheck.conf, health/health.d/ioping.conf, health/health.d/mdstat.conf, health/health.d/net.conf, health/health.d/nvme.conf, health/health.d/ping.conf, health/health.d/portcheck.conf, health/health.d/redis.conf, health/health.d/vsphere.conf, health/health.d/web_log.conf, health/health.d/windows.conf
Follow-up on #14982 and part of netdata/product#3118.
---
This PR modifies health configurations:
- removes "families: *"
- replaces the rest of the families with [chart labels](https://learn.netdata.cloud/docs/alerts-and-notifications/configure-alerts#alarm-line-chart-labels).
> **Note** This PR doesn't update documentation.
---
@MrZammler we usually align all the entities, which means we need to re-align all the alarms that use "chart labels" because that's the longest entity.
I think that we can rename it to just "labels":
- one word => shorter => looks neater. 
- no re-aligning needed.
- "host labels" is used very rare ([only once actually](https://github.com/netdata/netdata/blob/a53850f534f45bd86971160415befd6957ddb6d6/health/health.d/ram.conf#L45)), so there won't be any confusion. …
=> health: remove "families" from alarms config

packaging/installer/kickstart.sh
At the moment the updater script on the native packages is installed with ownership `root netdata` . Kickstart need to have root access to verify the existence of the netdata-updater script and run it.
Download kickstart script from this PR. 
1. Make an installation with any kind of native packages
2. Verify that the automatic updates are enabled.
Further testing. 
~Enforce other auto update types
`--auto-update-type               Specify a particular scheduling type for auto-updates (valid types: systemd, interval, 
crontab)`~
</details>
=> Provide necessary permission for the kickstart to run the netdata-updater script

aclk/schema-wrappers/alarm_stream.cc, aclk/schema-wrappers/alarm_stream.h, database/rrd.h, database/sqlite/sqlite_aclk_alert.c, database/sqlite/sqlite_db_migration.c, database/sqlite/sqlite_functions.c, database/sqlite/sqlite_health.c, health/health_log.c
This PR produces, stores, and transmits to the cloud a unique uuid for each alert event.
The id will be used by the agent and the cloud (and the ui) to track a unique alert transition.
Although called `hash` it's not actually a hash of anything, rather just a random uuid.
TBD
</details>
=> Generate, store and transmit a unique alert event_hash_id

collectors/debugfs.plugin/debugfs_plugin.c, collectors/freeipmi.plugin/freeipmi_plugin.c
The same change we [did for charts.d.plugin](https://github.com/netdata/netdata/pull/14680).
---
Sometimes external processes become a zombie. This is likely because Netdata's main process doesn't handle `SIGCHLD` (this signal is simply ignored) and we rely on the read parser to fail. But sometimes it doesn't work and the parser gets stuck in [parser_next->fgets()](https://github.com/netdata/netdata/blob/cfc91853eb8ed17572076e9ebc26a40d40391402/libnetdata/parser/parser.c#L127-L129).
Some external plugins periodically exit (e.g. freeipmi every 4 hours, debugfs every 24 hours), and every time they exit there is a chance to get a zombie process 🧟 
This PR addresses only this case, the (alleged) root cause (ignoring `SIGCHLD`) will be fixed in #15113.
ci.
<details> <summary>For users: How …
=> send EXIT before exiting in freeipmi and debugfs plugins

collectors/freeipmi.plugin/freeipmi_plugin.c, health/Makefile.am, health/health.d/plugin.conf
Fixes: netdata/netdata-cloud#840
This PR adds:
- availability status chart to freeipmi.plugin.
- plugin availability status alarm.
Install this branch, check the chart and the alarm.
</details>
=> freeipmi: add availability status chart and alarm

contrib/debian/control
Without this, our DEB packages are broken on non-amd64 platforms.
=> Restrict ebpf dep in DEB package to amd64 only.

health/health_config.c
- Fixes CID 385073
Make sure key will not be used uninitialized
=> Fix CID 385073 -- Uninitialized scalar variable

collectors/plugins.d/pluginsd_parser.c, database/contexts/api_v2.c, database/contexts/rrdcontext.h, database/rrd.h, database/rrdhost.c, streaming/receiver.c, streaming/replication.c, streaming/rrdpush.c, streaming/rrdpush.h, streaming/sender.c, web/api/formatters/json/json.c
=> api v2 nodes for streaming statuses

streaming/sender.c
Fixes #15182 
This PR just `strdupz` the empty string, so that `freez` can work later.
A vnode child is needed, streaming to a parent. Without this PR will crash, it should not with this PR.
</details>
=> Do strdupz on empty string

database/sqlite/sqlite_health.c
The `sqlite_health.c` file was recently changed to add `#include "uuid.h"`, however the library must be accessed as `uuid/uuid.h` on macOS. This PR aims to fix the issue. Spotted in https://github.com/Homebrew/homebrew-core/pull/133756.
Netdata's existing tests should be able to check this, however I'm unsure if there exists a macOS building/testing pipeline here. I have verified that this change works by patching Netdata and building it locally via Homebrew. It is also possible to test that the build is successful on Homebrew CI (in PR https://github.com/Homebrew/homebrew-core/pull/133756) with this change.
This change affects a specific file (sqlite_health.c) in Netdata, and solves a build error on macOS. There …
=> sqlite_health.c: remove `uuid.h` include

netdata.spec.in
This fix merged in https://github.com/netdata/netdata/pull/14552, but currently was missed and x86 builds failing again
=> RPM: Added elfutils-libelf-devel for build with eBPF (again)

daemon/analytics.c, daemon/daemon.c, system/openrc/init.d/netdata.in, system/runit/run.in, system/systemd/netdata.service.in, system/systemd/netdata.service.v235.in
This ensures that we consistently start the agent as root when running as a system service and properly trust it to drop privileges during startup (which it does in fact do correctly). It also updates the relevant scripts to trust the agent to create required directories itself, as starting as root lets it do so properly.
This also tidies up handling of the preparation of required directories during startup, and adds our log directory to the list of directories we attempt to create if it does not exist.
Testing requires installing the agent from this PR on a variety of different systems and confirming that it starts up correctly.
Fixes: https://github.com/netdata/netdata/issues/9701, plus a bunch of other issues we keep seeing intermittently regarding handling of require directories on …
=> Consistently start the agent as root and rely on it to drop privileges properly.

collectors/ebpf.plugin/ebpf.c, collectors/ebpf.plugin/ebpf_cachestat.c, collectors/ebpf.plugin/ebpf_dcstat.c, collectors/ebpf.plugin/ebpf_disk.c, collectors/ebpf.plugin/ebpf_fd.c, collectors/ebpf.plugin/ebpf_hardirq.c, collectors/ebpf.plugin/ebpf_mdflush.c, collectors/ebpf.plugin/ebpf_mount.c, collectors/ebpf.plugin/ebpf_oomkill.c, collectors/ebpf.plugin/ebpf_shm.c, collectors/ebpf.plugin/ebpf_softirq.c, collectors/ebpf.plugin/ebpf_swap.c, collectors/ebpf.plugin/ebpf_vfs.c
This PR is bringing first steps to fix [this](https://github.com/netdata/netdata/pull/15174#issuecomment-1586727435) and [this](https://github.com/netdata/netdata/pull/15146#issuecomment-1586317539) comment. The final solution will come with next PR that will bring functions for eBPF.
1. Remove your `/etc/netdata/ebpf.d.conf`
3. Start netdata and stop netdata while you are working or you have a server running receiving requests, you should have less messages like `take too long to exit: 'PD[ebpf]'`, but they are not completely over yet.
- Which area of Netdata is affected by the change? eBPF.plugin
- Can they see the change or is it an under the hood? If they can …
=> Speed up eBPF exit before to bring functions

collectors/ebpf.plugin/ebpf.d.conf, collectors/ebpf.plugin/ebpf_sync.c
Fixes https://github.com/netdata/netdata/issues/15103
This PR is fixing issued found in Rocky Linux, more details will come after tests to be sure other distributions are not affected.
1. Compile branch
2. Enable `sync` thread before to run:
```sh
$ cd /etc/netdata
$ ./edit-config ebpf.d.conf
sync = yes
```
3. Start netdata, because `sync` thread is enabled by default. 
4. Wait few minutes and query https://localhost:19999/api/v1/data?chart=mem.file_sync&after=-30 . You should have data for this thread.
| Hardware | Linux distribution | Kernel | File | 
|----------------|----------------------------|-----------|-------|
|Bare metal | Slackware Current |6.1.31 | [slackware_6_1.txt](https://github.com/netdata/netdata/files/11711180/slackware_6_1.txt) | …
=> Fix issues in sync thread (eBPF plugin)

contrib/debian/install_go.sh, netdata.spec.in
Fixes: https://github.com/netdata/netdata/issues/15194
> **Note** hide whitespace changes when reviewing
This PR doesn't fix the wrong `Binary architecture` (PREBUILT_ARCH in .install-type), it is x86_64.
ci, check ci logs
</details>
=> fix arch detection on i386 (native packages)

daemon/unit_test.c, database/rrdcalc.c, database/rrdcalc.h, database/sqlite/sqlite_aclk.h, database/sqlite/sqlite_aclk_alert.c, database/sqlite/sqlite_db_migration.c, database/sqlite/sqlite_functions.c, database/sqlite/sqlite_functions.h, database/sqlite/sqlite_health.c, database/sqlite/sqlite_health.h, health/health.c, health/health_config.c
This PR changes health to use a single `health_log` table, instead of a table for each host.
The PR will update database to version 9 and will move data from all the `health_log_XXXX` tables to the new one. A new `host_id` column is added, which is the host's `host_uuid`.
After this PR all of health functionality (including cleaning up and cloud connectivity) should remain as before.
</details>
=> Use a single health log table

database/sqlite/sqlite_db_migration.c, database/sqlite/sqlite_functions.c
- Create index to help speedup migration during startup when a lot of tables need to be migrated
=> Create index for health log migration

database/contexts/api_v2.c, database/contexts/rrdcontext.h, database/rrd.h, database/rrdcalc.c, database/rrdcalc.h, database/rrdcalctemplate.h, database/sqlite/sqlite_health.c, database/sqlite/sqlite_health.h, health/health.c, health/health.h, health/health_json.c, health/health_log.c, web/api/queries/rrdr.h, web/api/web_api_v1.c, web/api/web_api_v1.h, web/api/web_api_v2.c
This PR introduces the first iteration of the new `/api/v2/alerts` endpoint (not currently in use)
Parameters currently supported
---
Parameters affecting output: 
by default only the alerts short definition is returned.
=> New alerts endpoint

packaging/makeself/install-or-update.sh
Just change ownership on everything, instead of only on those plugins we set file capabilities or SUID on.
Testing should be done using static builds created from this PR. When installing on a system that does not have the Netdata user or group, the plugins from such a static build should still have correct file ownership.
Fixes: https://github.com/netdata/netdata/issues/15228
=> Fix handling of plugin ownership in static builds.

netdata.spec.in
CentOS 7 and derivatives need the pre-v235 systemd unit files, not the modern ones.
Packages built from this PR install the correct unit files, and the agent starts up correctly.
Fixes: #15236
=> Install the correct systemd unit file on older RPM systems.

database/sqlite/sqlite_aclk_alert.c
Small fix for coverity reports 393182 & 393183:
```
** CID 393183:  Resource leaks  (RESOURCE_LEAK)
/database/sqlite/sqlite_aclk_alert.c: 312 in aclk_push_alert_event()
306         }
307     
308         rc = sqlite3_bind_blob(res, 1, &wc->host->host_uuid, sizeof(wc->host->host_uuid), SQLITE_STATIC);
309         if (unlikely(rc != SQLITE_OK)) {
310             error_report("Failed to bind host_id for pushing alert event.");
311             sqlite3_finalize(res);
>>>     CID 393183:  Resource leaks  (RESOURCE_LEAK)
>>>     Variable "sql" going out of scope leaks the storage it points to.
312             return;
313         }
314     
315         uint64_t first_sequence_id = 0;
316         uint64_t last_sequence_id = 0;
317     
** CID 393182:  Resource leaks  (RESOURCE_LEAK) …
```
=> Fix coverity 393183 & 393182

packaging/current_libbpf.checksums, packaging/current_libbpf.version
Fix https://github.com/netdata/netdata/issues/15245
This PR is bringing a libbpf version with a [patch](https://github.com/netdata/libbpf/commit/99078942257d49ea272806df5e291301bd7fef68) that allows to run on Debian 10 again.
2. Start netdata
3. Wait around 20 seconds and run the following commands:
```sh
root@debian10:/etc/netdata# grep libbpf /var/log/netdata/* > debian_4_19_logs.txt
root@debian10:/etc/netdata# curl -o debian_4_19_threads.txt  "http://localhost:19999/api/v1/data?chart=netdata.ebpf_threads&after=-30"
``` 
You should not have any `libbpf` error and threads needs to be loaded with success.
This branch was tested on:
| Linux Distribution | Environment | Kernel version | Logs | Threads |
|----------------------------|---------------------|-------------- …
=> Update libbpf version

packaging/installer/kickstart.sh
- Provide a more complete error message for unrecognized options, making more specific suggestions about probable common cases of users passing them.
- Added exceptions for a couple of common and harmless unrecognized options so that they are just ignored instead of being treated as a fatal error. A warning is still issued for these options.
- Added a bit more clarity in a couple of other messages.
- Consolidated the URLs used in the script into a separate section from the other constants.
Only thing to check is that options such as `--`, `--accept`, or `--yes` are ignored instead of failing the install.
=> Assorted kickstart script improvements.

build_external/clean-install-arch-debug.Dockerfile, build_external/clean-install-arch-extras.Dockerfile, build_external/clean-install-arch.Dockerfile, build_external/clean-install.Dockerfile, configure.ac, packaging/makeself/jobs/70-netdata-git.install.sh
This adds checks to our configure script to enable a number of hardening features if they are available (and not overridden by the user), improving the baseline security of the Netdata Agent on many systems.
Currently adds:
- `-fstack-protector`/`-fstack-protector-strong`: This enables stack smashing protection, a form of buffer overflow protection designed to protect against exploits that overwrite parts of the stack. Support is largely ubiquitous and this is enabled by default in the compiler configuration on a vast majority of systems, so this change is unlikely to have a significant impact, but is being done anyway for the sake of correctness.
- `-fstack-clash-protection`: This enables a set of changes to how stack allocations are performed, making it more difficult to bypass the …
=> Add hardening options to CFLAGS by default if they are available.

exporting/process_data.c
Fixes: #15272
Tested on a parent instance with ~250 children, 1.3M metrics. 
Without this change, it takes 2-5 minutes to process `/api/v1/allmetrics?format=prometheus_all_hosts`.
After this change - 10-20 seconds.
</details>
=> exporting: change priority to synchronous when calculating value

collectors/plugins.d/gperf-config.txt, collectors/plugins.d/gperf-hashtable.h, collectors/plugins.d/pluginsd_parser.c, collectors/plugins.d/pluginsd_parser.h, daemon/common.c, database/engine/metric.c, database/engine/metric.h, database/engine/pagecache.c, database/engine/rrdengineapi.c, web/server/web_client.c
=> Optimizations Part 2

exporting/README.md
=> Fixed mistype for 'send automatic labels' Prometheus option

database/rrdcalc.c, database/rrdcalc.h, database/sqlite/sqlite_aclk_alert.c, database/sqlite/sqlite_health.c, database/sqlite/sqlite_health.h, health/health.c
This PR makes a couple of changes and fixes since #15157 : 
* When the config hash changes, we should start a new alert chain (new alarm_id). This is to make sure we transmit the correct config hash to the cloud.
* The alert to cloud filter should work now for statuses `WARNING` and `CRITICAL`.
* Repeating alerts notifications should work now.
Tests should include a repeating alert to make sure the notification is repeated correctly.
</details>
=> Misc alert fixes

database/engine/rrdengineapi.c, web/server/web_client.c
This prevents the agent from entering an infinite redirect loop.
=> use stat() instead of lstat()

CMakeLists.txt, Makefile.am, collectors/profile.plugin/Makefile.am, collectors/profile.plugin/README.md, collectors/profile.plugin/plugin_profile.cc, daemon/global_statistics.c, daemon/static_threads.c
A small plugin that allows someone to backfill the agent with random data.
See `collectors/profile.plugin/README.md`
This is meant for devs and users who want to get an idea of that the worst-case scenario looks like. The generated data are random (ie. not amenable to compression) and all the charts/dims are attached to localhost (ie. the various indexes are stress-tested).
=> Add profile.plugin

aclk/schema-wrappers/alarm_config.cc, aclk/schema-wrappers/alarm_config.h, database/sqlite/sqlite_aclk_alert.c, database/sqlite/sqlite_db_migration.c, database/sqlite/sqlite_functions.c, database/sqlite/sqlite_health.c
This PR sends the `chart labels` key of alerts configuration to the cloud.
* Install this PR, but not start it yet. Claim it to staging. Enable the conversation log of aclk.
* Create a custom version of e.g. `disks.conf`.
* Cloud should request this new configuration (i.e. in access.log notice a `Request to send alert config`)
* In aclk.log there should be the agent's response which should contain the `chart_labels`, i.e. `Request to send alert config`
</details>
=> Send alert chart labels config key to cloud

.github/workflows/review.yml
Because no one formats .c files and this check always fails.
Not needed
</details>
=> ci: disable clang format

database/sqlite/sqlite_health.c
Fixes #15304 
Adds a check for the `source` field when `api/v1/alarm_log` is requested. Will also investigate the missing field in a separate PR.
To trigger the issue:
While an agent is running, update the `source` field of table `alert_hash` to NULL for a couple of alerts (that are running on the system). Request `http://localhost:19999/api/v1/alarm_log`. Without this PR there is a crash, with this PR there is not.
</details>
=> Check for source field when requesting /api/v1/alarm_log

collectors/plugins.d/pluginsd_parser.c
Fixes #15268
- When a chart is obsoleted (e.g from an external collector) release the acquired dimensions to allow proper chart cleanup
This would make the cleanup incomplete as the chart dimensions would not be deleted (thought to be still in use). Additional code may be needed in the service cleanup (as commented in the linked issue) to make this process more robust.
=> Release acquired dimensions

database/sqlite/sqlite_metadata.c
Fixes #15271 
Fixes #15273 
This PR changes slightly how to store the host system info values. It uses inserts with binds, which will address the issue of the values having characters like `'`. Indeed though this will do multiple inserts instead of one, but since they are done once on start it shouldn't be much of an issue.
Change something in your `/etc/os-release`, i.e. put the value `NAME="'my_favorite_os'"`. Without this PR there will be fails to store this information. The table `host_info` would be empty (on a new agent). With this PR it should store the data.
</details>
=> Change query to store host system info values

packaging/docker/README.md
Fixes: netdata/learn#1723
As suggested by https://github.com/netdata/learn/issues/1723, we have swapped wordings in the README.
This PR corrects the README in the two places the user mentioned.
=> Fix wording issue in Docker README

health/notifications/alarm-notify.sh.in
Fixes: #15172
Closes: #15173
Test changes using the `alarm-test.sh` script.
</details>
=> health: respect overriding nc binary for IRC notifications

claim/claim.c
Avoid attempt to write to the file if the open command fails
=> Fix coverity issue 394862 - Argument cannot be negative

libnetdata/os.c
Fix compilation on FreeBSD after we merge a PR renaming generic functions
1. Compile this branch on FreeBSD
- Which area of Netdata is affected by the change? FreeBSD clients
- Can they see the change or is it an under the hood? If they can see it, where? yes, they can compile. 
- How is the user impacted by the change? We fix an issue created when a PR was merged.
- What are there any benefits of the change?  Netdata will compile again on FreeBSD
</details>
=> Fix compilation on BSD

database/contexts/api_v2.c, database/contexts/query_target.c, database/rrd.h, database/rrdcalc.c, database/rrdhost.c, database/rrdset.c, database/sqlite/sqlite_aclk_alert.c, database/sqlite/sqlite_health.c, health/health.c, health/health_log.c, web/api/formatters/json_wrapper.c, web/api/formatters/rrdset2json.c
Use the new rw_spinlock to reduce the memory needed by rrdhost and rrdset by 32 bytes
Chart is now 448 bytes and host is at 896 (previously 480 and 928 respectively)
=> Use spinlock in host and chart

aclk/aclk_capas.c, claim/claim.c, daemon/common.c, database/contexts/api_v2.c, database/contexts/rrdcontext.h, registry/registry.c, web/api/formatters/json_wrapper.c, web/api/queries/weights.c, web/api/web_api.c, web/api/web_api_v2.c, web/server/web_client.c, web/server/web_client.h
=> bearer improvements

collectors/metadata/schemas/single-module.json
As discussed, we don't really need to add it in every metric if it is empty. We have the top level availability list, if that is empty, then we can just not look for this entry in each metric.
=> Remove availability from required fields on metric level

libnetdata/eval/eval.c
Without this change, all alarms that use `nan` in any expression (calc, warn, crit) have UNDEFINED state.
The issue was added in #15257. 
Install this PR and check for alarms that didn't work before (e.g. system load, systemd units).
</details>
=> health: fix evaluating expression with `nan`

.github/workflows/build-dummy.yml, .github/workflows/build.yml, .github/workflows/checks-dummy.yml, .github/workflows/checks.yml, .github/workflows/docker-dummy.yml, .github/workflows/docker.yml, .github/workflows/packaging-dummy.yml, .github/workflows/packaging.yml
The goal here is to reduce how much CI time is taken up by things like PRs that only fix documentation or simply tweak configuration files, which generally do not require build checks at all. Long-term, this should reduce usage of GHA runners, allowing all CI to complete faster, as well as avoiding blocking PRs due to failing build checks that have nothing to do with the PR.
This modifies the following workflows so that they won’t run unless relevant files are changed:
- `build.yml`
- `checks.yml`
- `docker.yml`
- `packaging.yml`
Relevant files in this case are those that impact the result of running at least one of the jobs in the workflow.
Additionally, secondary workflows are added to run with the same name when these workflows do not run, ensuring that we can still flag the jobs as …
=> Attempt to more aggressively skip CI jobs on PRs if those jobs are irrelevant to the PR.

collectors/freeipmi.plugin/freeipmi_plugin.c
We set the value the first time the sensor appears and never update it after that. This PR fixes this problem.
Not needed.
</details>
=> fix(freeipmi): set sensor state on every reading

collectors/metadata/schemas/definitions.json, collectors/metadata/schemas/single-module.json
ssia, so we don't need to change  single-module.json if we want to [add another category](https://github.com/netdata/netdata/pull/15365).
tested locally, schemas are valid
</details>
=> move not really related props single-module.json -> definitions.json

collectors/metadata/schemas/definitions.json, collectors/metadata/schemas/single-module.json, collectors/metadata/single-module-template.yaml
- As per yesterday's discussion, we want categories and icon path both on integration level and inside virtual integrations.
- I added some example categories, but I think we will add to this schemas `enum` entries as the structure grows. That goes for path levels too, if we need a third one, then we will add it. For level0 I have added only data collection, as this is what the schema is about, maybe we need deploy, but I am not sure.
We need a way to limit people on assigning just the categories we want, but we want that for every level of the "category path".
So, if the path is data-collection/web-servers you want to have different values allowed for first level data-collection and different for second level.
- Let's discuss and agree in this PR where these images are going to be …
=> Add keys to integrations schema, categories, icon path, plus some fixes

web/api/formatters/charts2json.c
There is no `.environment` if using native packages. 
We try to open this file on startup
=>
```
netdata ERROR : MAIN : PROCFILE: Cannot open file '/etc/netdata/.environment' (errno 2, No such file or directory)
```
Having this line is [confusing for users](https://community.netdata.cloud/t/non-existent-environment-file/4381). This PR fixes it.
Not needed.
</details>
=> dont log error on opening .environment

collectors/metadata/schemas/definitions.json, collectors/metadata/schemas/single-module.json, collectors/metadata/single-module-template.yaml
It will allow us to have fewer top-level keys and don't mix things with different importance (e.g. icon_path and setup) on the same level. 
- Update single module template
- Validate it against schema
</details>
=> simplify collector schema by moving some props under meta

collectors/metadata/schemas/definitions.json
Discussion: https://netdata-cloud.slack.com/archives/C05F9KAM3HR/p1689166955258749
In short, we can group these in a special category, so we need an entry for them in level1
=> Add most-popular entry in oneOf of categories in definitions.json

health/health.d/windows.conf
Fixes: #15369
We shouldn't use the `os` filter because `os` is an empty string for virtual nodes.
Tested with win11 vnode.
</details>
=> health: fix windows alarms for vnodes

database/rrdhost.c
* Multiplication result converted to larger type
- Properly cast parameters for the multiplication
=> Fix CodeQL alert 

collectors/metadata/schemas/definitions.json, collectors/metadata/schemas/single-module.json, collectors/metadata/single-module-template.yaml
The current schema forces you to add `folding.{title, enabled}` to every example
<details>
<summary>screenshot</summary>
</details>
It is not needed because we want
-  **only one** example to be unfolded
- all folded the same title
The better way is to have global folding for config examples and (optionally) disable the one we need. Folding title overwriting is supported too (but optional).
<details>
<summary>screenshot</summary>
</details>
Use single-module-template.yaml to validate the schema.
</details>
=> collector meta schema: global config examples folding + per example

collectors/metadata/schemas/single-module.json
This PR:
- restricts metrics.scopes.metrics.chart_type values.
- allows config option default value to be boolean
Not needed
</details>
=> collector meta: restrict chart_type to known values

.github/workflows/build-dummy.yml, .github/workflows/packaging-dummy.yml
This removes concurrency limits and pointless inter-dependencies in the dummy workflows that are run when build jobs are being skipped. Because these dummy jobs complete essentially instantaneously and do not depend on each other0s output, there is no reason to limit concurrency or have them depend on each other, and removing those limitations should make these workflows complete even faster.
=> Make skipped CI run even faster.

aclk/aclk_query.c, web/api/badges/web_buffer_svg.c, web/server/web_client.c
The agent was using internally the monotonic clock which was accidentally used for rendering http response headers.
Fixed it.
=> use real-time clock for http response headers

registry/registry.c, registry/registry_internals.c, registry/registry_internals.h
=> fix unlocked registry access and add hostname to search response

integrations/categories.yaml
As discussed, this is a duplicate category, as long as we don't render empty categories, we should be fine about using the categories in this yaml, we can clean them up post-release, but this one was wrong from the start, thus this PR
=> Remove duplicate category from categories.yaml

web/server/web_client.c
Fixes #15344 
Decode the url string before checking for a question mark. Each part of the url (before and after question mark) would be decoded after the check.
Besides checking the case of #15344, tests should include proper dashboard functionality, charts, data, as well as cloud connectivity for anything weird.
</details>
=> Decode url before checking for question mark

health/health.d/file_descriptors.conf
[Reported on Discord](https://discord.com/channels/847502280503590932/847502280503590935/1130797853481127996)
> there seems to be a new metric "Apps File Descriptors Limit" i am getting blasted with useless alerts that ssh gets peaks of 700% no logged events except cronjobs.
I guess we have a problem in our fd limit calculations, this PR disabled the alarm until the calculation is fixed
Not needed.
</details>
=> disable apps_group_file_descriptors_utilization alarm

collectors/apps.plugin/apps_plugin.c
PR https://github.com/netdata/netdata/pull/15417 added the functionality to monitor open file descriptor limits.
In this PR:
=> apps.plugin fds limits improvements

database/contexts/api_v2.c, database/contexts/rrdcontext.h
Added 4 fields that where missing from alerts instances:
1. `to` for recipient
2. `tp` for type
3. `cm` for component
4. `cl` for classification
=> added missing fields to alerts instances

collectors/proc.plugin/multi_metadata.yaml, integrations/categories.yaml
Using [this message from slack](https://netdata-cloud.slack.com/archives/C05F9KAM3HR/p1689334721985819) and googling where needed, updated the proc plugin. Also added our first nested categories inside linux-systems.
This was done manually, by hand, so maybe it is best to review quickly and actually see the result on testing to pick out any mistakes or hiccups.
=> Update proc plugin yaml

web/api/queries/incremental_sum/incremental_sum.h, web/api/queries/query.c
=> fix the calculation of incremental-sum

packaging/installer/kickstart.sh, packaging/installer/netdata-updater.sh
Modify netdata-updater.sh and kickstart.sh adding force-confdef and force-confold to apt-get so that non-interactive runs and replacing `zypper install -y` by `zypper --non-interactive install`.
`netdata-updater.sh --non-interactive --not-running-from-cron`
`kickstart.sh --non-interactive`
- APT updater error (from discord discussion)
```
[/tmp/netdata-kickstart-2mxUecrtAY]# //usr/libexec/netdata/netdata-updater.sh --non-interactive --not-running-from-cron 
Tue Jun 20 18:31:06 CEST 2023 : INFO: netdata-updater.sh:         [LOG TRUNCATED]        
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
netdata-repo is already the newest version (2-1).
0 upgraded, 0 newly installed, 0 to remove and 116 not upgraded.
1 not …
```
=> Fix non-interactive options for apt-get and zypper.

collectors/apps.plugin/apps_plugin.c
- Fix formatting - CID 395940:  API usage errors  (PRINTF_ARGS)
- /collectors/apps.plugin/apps_plugin.c: 1417 in read_proc_pid_limits()
=> Fix coverity issue

database/sqlite/sqlite_health.c, health/health.c
The current approach that tries to update the alert chart name during health init may cause a deadlock (on parents with a lot of children). 
This PR skips the update during health initialization and will do on demand when new alert transition is stored.
=> Improve the update of the alert chart name in the database

collectors/proc.plugin/sys_devices_system_edac_mc.c
- Fix CID 396310:    (RESOURCE_LEAK)
- /collectors/proc.plugin/sys_devices_system_edac_mc.c: 89 in find_all_mc()
=> Fix resource leak - CID 396310

collectors/apps.plugin/apps_plugin.c
This should provide log lines like this, when any process has more fds open than its limit:
```
2023-07-24 13:28:51: apps.plugin INFO  : apps.plugin : (1441@collectors/apps.plug:read_proc_pid_l): FDS_LIMITS: PID 635030 (wakatime-cli-li) is using 0.00 % of its fds limits, open fds = 0 (files = 0, pipes = 0, sockets = 0, inotifies = 0, eventfds = 0, timerfds = 0, signalfds = 0, eventpolls = 0 other = 0 ), open fds limit = 524288, and we have read the limits AFTER counting the fds, original line [Max open files            524288               524288               files     ]
```
This includes the original log line found in `/proc/PID/limits`.
=> apps.plugin limits tracing

.github/data/distros.yml, packaging/PLATFORM_SUPPORT.md
Do not merge this until 07-23-2023
Closes https://github.com/netdata/netdata/issues/15254
=> Drop support for native packages of Ubuntu 22.10

web/api/web_api_v1.c
Fixes #15493 
Replaces the `WEB_CLIENT_ACL_ACLK_WEBRTC_DASHBOARD_WITH_BEARER` with `WEB_CLIENT_ACL_DASHBOARD_ACLK_WEBRTC` so that the `api/v1/manage/health` api endpoint to be used without bearer auth.
Test the health management api end point with and without this PR.
</details>
=> Allow manage/health api call to be used without bearer

.github/data/distros.yml, integrations/schemas/distros.json, packaging/PLATFORM_SUPPORT.md
- Add a proper schema for the distros.yml file.
- Add extra keys to support using this information for integrations (and eventually for generating the platform support document).
- Add Alpine 3.18, which should have been added back when it was released.
- Add info for distros we have support for but do not run CI for.
- Sync up info in the platform support document.
n/a
=> Update platform support info and add a schema.

database/engine/journalfile.c, database/engine/metric.c, database/engine/metric.h, database/engine/rrdengineapi.c
Currently we copy the UUIDs twice. Passing the pointer and doing the copy once seems to improve performance
when creating a lot of entries
=> Avoid an extra uuid_copy when creating new MRG entries

health/notifications/sample-metadata.yaml, integrations/notifications.yaml, integrations/schemas/notification.json
Files can be either a single entry, or a list of entries.
`integrations/notifications.yaml` is intended for metadata for Cloud notification methods. Agent methods should have appropriate metadata files added alongside their README files in `health/notifications` subdirectories.
n/a
=> Add schema and examples for notification method metadata.

collectors/ebpf.plugin/ebpf_swap.c
Fixes
```
PLUGINSD: parser_action('BEGIN') failed on line 46: { "BEGIN" "system.swapcalls" } (quotes added to show parsing)
```
after moving system.swap charts to mem. in #15494
Install this branch and check if ebpf.plugin is running.
</details>
=> fix ebpf.plugin system swapcalls

CMakeLists.txt
Add missing file `collectors/proc.plugin/sys_devices_pci_aer.c` in `CMakeLists.txt`
=> Add missing file in CMakeLists.txt

database/sqlite/sqlite_functions.c
This index is not needed (already exists). Stop creating it and drop existing one if it exists to save some space.
=> Drop duplicate / unused index

README.md
seems like this emoji is not rendering on gh correct so this pr just swaps it out with one that does.
broken: https://github.com/netdata/netdata#information_source-what-does-the-anonymous-telemetry-collected-by-netdata-entail
fixed: https://github.com/netdata/netdata/tree/small-readme-icon-fix#mag_right-what-does-the-anonymous-telemetry-collected-by-netdata-entail
replace
with this
</details>
=> small readme icon fix

collectors/cgroups.plugin/sys_fs_cgroup.c
Noticed that all my deb12 VMs have 1 container - `/system.slice/systemd-udevd.service/udev`. This PR filters it.
```
/sys/fs/cgroup/
├── system.slice
│   ├── systemd-udevd.service
        └── udev
```
Tested the updated filter locally.
</details>
=> filter out systemd-udevd.service/udevd

daemon/system-info.sh
Before
```
NETDATA_SYSTEM_CPU_FREQ=2.494e+09
```
After
```
NETDATA_SYSTEM_CPU_FREQ=2494000000
```
</details>
=> fix cpu MHz from /proc/cpuinfo

database/sqlite/sqlite_health.c
Fix the query that fetches the maximum unique id
The semicolon would make it so that `and hl.health_log_id = hld.health_log_id` would not be parsed
=> Fix health query

health/notifications/alerta/metadata.yaml
using `description: |` breaks the markdown table because it adds newlines.
I tried to fix detailed descriptions, but we don't use them currently and the content at hand would look bad if we did. We can tackle once we actually start using detailed_description
=> Fix descriptions in config objects, make them single line

integrations/schemas/shared.json
This is a new optional key in the `instance` sub-schema. The value should be a mapping of strings that are valid Python identifiers to strings, integers, floats, or booleans.
If this key is present, the script using the metadata files will make a second rendering pass over the keys it’s rendering, passing in the mapping as an object named `variables`.
The keys this second rendering pass is run on can reference this object and it’s properties by using double square brackets. For example, to template in the value of a key in this mapping called `port`, the syntax would be `[[ variables.port ]]`.
This sub-schema is used for the `meta.monitored_instance` section in collector integrations, and the `meta` section in the deploy, exporter, and notification integrations.
n/a
=> Add additional variable section to instance data in schema.

web/server/h2o/http_server.c
Check that its argument is not NULL before using SSL_CTX_set_options.
If the parameter 1 of SSL_CTX_set_options is NULL, there is a null-dereference which will cause crash. So there should be a check against NULL in the code to avoid the problem.
=> fix potential crash bug. 

collectors/plugins.d/plugins_d.c
Because it crashes (freeipmi lib functions) after we made it multi-threaded if there is no access to ipmi (`/dev/ipmi0`) device.
See [coredumps](https://github.com/netdata/netdata/pull/15564#issue-1823064137).
Check that freeipmi is disabled by default only in Docker.
</details>
=> disable freeipmi in docker by default

integrations/categories.yaml
I think it's redundant to have "Metric", it looks better without it.
</details>
=> remove " Metrics" from linux categories

.github/workflows/generate-integrations.yml
- Use correct list of trigger files.
- Properly handle the fact that Ubuntu for some reason completely lacks an extremely popular Python module that’s essentially mandatory to use the jsonschema module.
n/a
=> Fix integrations regen workflow

system/edit-config
Fixes "Unable to find stock config directory" reported in https://github.com/netdata/netdata/discussions/15636
>  edit-config for containerized Netdata when running from host
I guess it never worked, or we changed something 🤷‍♂️ 
- Install [ND with host-editable configuration](https://learn.netdata.cloud/docs/installing/docker#with-host-editable-configuration)
- Execute `edit-config` from the host system
</details>
=> fix edit-config for containerized Netdata when running from host

integrations/gen_integrations.py, integrations/schemas/collector.json, integrations/schemas/exporter.json, integrations/schemas/notification.json, integrations/schemas/shared.json, integrations/templates/troubleshooting.md
- Add optional `troubleshooting` section to notification and exporter schemas.
- Update script to support rendering of optional keys.
- Update script to render troubleshooting key for notification and exporter schemas.
- Fix the troubleshooting template so that it renders things correctly for all integration types where it is rendered.
n/a
=> Fix handling of troubleshooting section in integrations.

database/sqlite/sqlite_aclk_alert.c
Does a better job at cleaning up the alert aclk tables. Every time an alert is filtered, the `date_created` field will be updated. Long (over a week) entries that have not been used to filter events will eventually be deleted.
Needs check on the `aclk_alert_XXXXXX` table. The `date_created` field should be updated whenever a filtered event happens (i.e. not sent to the cloud).
</details>
=> Better cleanup of aclk alert table entries

health/health.d/systemdunits.conf
After enabling [systemdunits collector](https://github.com/netdata/go.d.plugin/tree/master/modules/systemdunits#systemd-units-state-collector) by default we started to receive reports like "[suddenly 386 warnings for systemd, how to identify service](https://discord.com/channels/847502280503590932/1136530477998682192/1136530477998682192)"
This collector tracks the state of systemd units. Alarms trigger if the state is **failed** (which sounds reasonable), but I think we are missing something. Needs investigation, so disabling the alarms for now.
> https://www.freedesktop.org/software/systemd/man/systemd.html
> systemd provides a dependency system between various entities called "units" of 11 different types. Units encapsulate various objects that are relevant for system boot-up and …
=> disable systemdunits alarms

database/contexts/api_v2.c
Fix issue in case there is only one reference and the o->family is then invalid when used
=> Fix memory corruption

integrations/templates/alerts.md, integrations/templates/setup.md
It was missing a `## Alerts`
The script was ran locally, and it works, adds the heading when alerts exist, and has the templated message if there are no alerts.
=> Changes to the templates for integrations

collectors/proc.plugin/proc_pressure.c
Fixes: #15729
No 
> PROCFILE: Cannot open file '/host/proc/pressure/irq' (errno 2, No such file or directory)
in collector.log.
</details>
=> proc.plugin: dont log if pressure/irq does not exist

.github/workflows/generate-integrations.yml
Found it failing on "Create PR" step in my fork.
</details>
=> ci: run "Generate Integrations" only in netdata/netdata

.github/labeler.yml
This PR adds to the labeler config:
- collectors/systemd-journal
- area/metadata
n/a
</details>
=> ci: add systemd-journal and metdata to labeler

.github/labeler.yml
Two changes:
- remove integrations from area/docs (#15749 shouldn't have `area/docs` label)
- simplify config: `**` matches all files and zero or more directories and subdirectories (we don't need `/dir/*` + `/dir/**/*`, `/dir/**` is enough).
Not needed.
</details>
=> ci labeler: remove integrations from area/docs

build_external/scenarios/gaps_lo/mostly_off.conf, collectors/ebpf.plugin/metadata.yaml, collectors/freebsd.plugin/freebsd_sysctl.c, collectors/freebsd.plugin/metadata.yaml, collectors/macos.plugin/macos_mach_smi.c, collectors/macos.plugin/macos_sysctl.c, collectors/macos.plugin/metadata.yaml, collectors/proc.plugin/metadata.yaml, web/gui/dashboard_info.js
`master` is broken on FreeBSD due to https://github.com/netdata/netdata/pull/15494 . This PR fixes it.
It also updates several other references from `system.swap` to `mem.swap` and `system.swapio` to `mem.swapio`.
Check this PR builds successfully on FreeBSD.
</details>
=> Change FreeBSD / macOS system.swap(io) to mem.swap(io)

collectors/apps.plugin/apps_plugin.c, collectors/ebpf.plugin/ebpf_functions.c, collectors/systemd-journal.plugin/systemd-journal.c, libnetdata/buffer/buffer.h, libnetdata/facets/facets.c, web/api/queries/query.c
=> extend the trimming window to avoid empty points at the end of queries

packaging/makeself/jobs/99-makeself.install.sh
Netdata expects claiming script to be in the same directory as the netdata binary.
This PR creates a symlink to `netdata-claim.sh` in `/opt/netdata/bin/srv/`
```
/opt/netdata/bin/
├── bash
├── bashbug
├── curl
├── curl-config
├── netdata
├── netdata-claim.sh
├── netdatacli
└── srv
├── netdata
└── netdata-claim.sh -> /opt/netdata/bin/netdata-claim.sh
```
- Install static image and do claiming via web .
</details>
=> fix claiming via UI for static build

.github/data/distros.yml
I introduced a bug during https://github.com/netdata/netdata/pull/15554. This bug prevent packages of openSUSE 15.5 to be published into our package server. We need to investigate also in what extend this bug affects openSUSE 15.4 packages.
CI/CD
=> Update an oversight on the openSUSE 15.5 packages

packaging/installer/methods/ansible.md
The Ansible tutorial points in a wrong directory for the ansible-quickstart role. Fixed so it points in a correct position.
=> Set correct path for ansible-playbook in deployment tutorial

collectors/plugins.d/pluginsd_parser.c
`systemd-journal` does not expose any metrics, but it restarts from time to time.
After 10 restarts without any metrics collected, plugins.d does not restart the plugin any more.
This PR counts function definitions and results as collections.
=> count functions as collections, to restart plugins

database/engine/rrdengineapi.c
=> prevent reporting negative retention when the db is empty

collectors/systemd-journal.plugin/systemd-journal.c, libnetdata/facets/facets.c, libnetdata/facets/facets.h
Depending on the journal transport, the column was sometimes not populated. Fixed it.
=> Function systemd-journal: always have a nd_journal_process

packaging/makeself/openssl.version
New version of openSSL is published a while back. Major changes introduced in a meanwhile
Introduced in the transition between OpenSSL 1.1.1u and OpenSSL 1.1.1v [1 Aug 2023]
- Fix excessive time spent checking DH q parameter value ([CVE-2023-3817](https://www.openssl.org/news/vulnerabilities.html#CVE-2023-3817))
- Fix DH_check() excessive time with over sized modulus ([CVE-2023-3446](https://www.openssl.org/news/vulnerabilities.html#CVE-2023-3446))
Introduced in the transition between OpenSSL 1.1.1t and OpenSSL 1.1.1u [30 May 2023]
- Mitigate for very slow `OBJ_obj2txt()` performance with gigantic OBJECT IDENTIFIER sub-identities. ([CVE-2023-2650](https://www.openssl.org/news/vulnerabilities.html#CVE-2023-2650))
- Fixed documentation of X509_VERIFY_PARAM_add0_policy() …
=> Bump openssl version of static builds to 1.1.1v

netdata.spec.in
- Don't depend on Python for the core agent, since it's only needed for the python plugin.
- Don't explicitly version Python dependency on RHEL 8 and clones.
=> Clean up python deps for RPM packages.

contrib/debian/control
DEB packages only allow build dependencies on the source package, not the individual packages.
=> Fix systemd journal build deps in DEB packages.

packaging/installer/kickstart.sh
Fixes: #15770
Run `./kickstart.sh --dry-run` and check `/tmp/` after.
</details>
=> fix: the cleanup was not performed during the kickstart.sh dry run

packaging/docker/Dockerfile
Noticed the problem:
```bash
total 12
lrwxrwxrwx    1 netdata  root            11 Aug 15 15:27 access.log -> /dev/stdout
lrwxrwxrwx    1 netdata  root            11 Aug 15 15:27 collector.log -> /dev/stdout
lrwxrwxrwx    1 netdata  root            11 Aug 15 15:27 debug.log -> /dev/stdout
lrwxrwxrwx    1 netdata  root            11 Aug 15 15:27 error.log -> /dev/stderr
-rw-r--r--    1 netdata  netdata      11686 Aug 15 16:12 health.log
```
After this PR
```bash
$ docker exec netdata ls -l /var/log/netdata
total 0
lrwxrwxrwx    1 netdata  root            11 Aug 15 16:21 access.log -> /dev/stdout
lrwxrwxrwx    1 netdata  root            11 Aug 15 16:21 collector.log -> /dev/stdout
lrwxrwxrwx    1 netdata  root            11 Aug 15 16:21 debug.log -> /dev/stdout
lrwxrwxrwx    1 netdata  root …
```
=> fix packaging: link health.log to stdout

libnetdata/dyn_conf/dyn_conf.c
Release the job status message (reason) in the unlikely situation the job doesn't exist
=> Release job message status to avoid memory leak

ml/ml.cc
Init anomaly_rate_rs chart to avoid warning from valgrind
```
==505866== Conditional jump or move depends on uninitialised value(s)
==505866==    at 0x467A87: store_metric_at_tier (rrdset.c:1185)
==505866==    by 0x467D50: rrddim_store_metric (rrdset.c:1258)
==505866==    by 0x4684DD: rrdset_done_interpolate (rrdset.c:1453)
==505866==    by 0x4696E0: rrdset_timed_done (rrdset.c:1893)
==505866==    by 0x468702: rrdset_done (rrdset.c:1502)
==505866==    by 0x244400: ml_update_host_and_detection_rate_charts(ml_host_t*, long long) (ad_charts.cc:333)
==505866==    by 0x400C51: ml_host_detect_once(ml_host_t*) (ml.cc:1048)
==505866==    by 0x401039: ml_detect_main(void*) (ml.cc:1142)
==505866==    by 0x1D5ED0: netdata_thread_init (threads.c:262)
==505866==    by 0x51D5043: start_thread …
```
=> ML improve init

daemon/static_threads.h, libnetdata/dyn_conf/dyn_conf.c, libnetdata/threads/threads.h
Fix #15821 
Cherry picks some of the fixes from other PRs to merge it sooner
You should not see
`2023-08-16 17:59:04: netdata ERROR : MAIN : Main thread DYNCFG takes too long to exit. Giving up...`
on `netdatacli shutdown-agent` and netdata should exit faster
</details>
=> Improve dyncfg exit

web/server/h2o/http_server.c
* CID 384852:  Resource leaks  (RESOURCE_LEAK)
* /httpd/http_server.c: 49 in create_listener()
=> Release fd if setsockopt or bind fails

database/sqlite/sqlite_aclk_alert.c
This PR increases the chunk size of the alert snapshot to 1000 alerts per chunk. It will go into nightlies to check the effect on the load on the backend's db and/or pulsar.
Size of each chunk with 1000 entries was observed to be around 600KB.
</details>
=> Increase alert snapshot chunk size

streaming/replication.c
* CID 382964:  Code maintainability issues  (SIZEOF_MISMATCH)
* /streaming/replication.c: 1579 in replication_main_cleanup()
* CID 382963:  Code maintainability issues  (SIZEOF_MISMATCH)
* /streaming/replication.c: 1599 in replication_thread_main()
Minor as in most cases size of pointer happens to be size of structure
=> Fix CID 382964:  Code maintainability issues  (SIZEOF_MISMATCH)

database/rrdhost.c
* CID 393052:  API usage errors  (LOCK)
* /database/rrdhost.c: 361 in rrdhost_create()
```
>>>     CID 393052:  API usage errors  (LOCK)
>>>     "__netdata_mutex_init" initializes "host->receiver_lock" while it is already initialized.
```
Initialize the receiver_lock mutex early enough because it may be used in `stream_our_capabilities` (lock and unlock)
and then re-initialized
=> Fix coverity 393052:  API usage errors  (LOCK)

database/rrdhost.c, ml/ml.cc
Fix an issue when rrd_init fails. This will try to create  localhost and if it fails it will try to set the environment
so that `fatal` may be able to submit a report (if allowed). The problem is that system_info in this case will
be invalid as it may have been released. 
This PR will preserve system info if we are creating the localhost -- it will not release the memory but we will fail anyway. 
```
if(rrd_init(netdata_configured_hostname, system_info, false)) {
set_late_global_environment(system_info);
fatal("Cannot initialize localhost instance with name '%s'.", netdata_configured_hostname);
}
```
An additional check has been added when shutting down the ml threads. A quick agent shutdown (as in the case above) needs to check if the ml detection_thread is valid.
=> Fix use after free

database/sqlite/sqlite_functions.c
Fixes warning
```
database/sqlite/sqlite_functions.c:829:17: warning: '__atomic_load_4' writing 4 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
829 |             if (rrdhost_flag_check(host, RRDHOST_FLAG_PENDING_CONTEXT_LOAD)) {
```
=> Fix warning when compiling with -flto

netdata-installer.sh
Clears the warning during compilation
```
configure: WARNING: unrecognized options: --with-zlib
```
=> Fix configure: WARNING: unrecognized options: --with-zlib

aclk/aclk_rx_msgs.c
Initialize trace id to avoid warning
```
aclk/aclk_rx_msgs.c:458:5: warning: 'MEM[(struct aclk_cancel_pending_req *)&cmd].trace_id' may be used uninitialized [-Wmaybe-uninitialized]
458 |     netdata_log_access("ACLK CancelPendingRequest REQ: %s, cloud trace-id: %s", cmd.request_id, cmd.trace_id);
|     ^
aclk/aclk_rx_msgs.c:452:36: note: 'MEM[(struct aclk_cancel_pending_req *)&cmd].trace_id' was declared here
452 |     struct aclk_cancel_pending_req cmd;
```
=> Fix compilation warning

collectors/systemd-journal.plugin/systemd-journal.c, packaging/docker/Dockerfile, packaging/makeself/jobs/70-netdata-git.install.sh
- `-Wl,-z,stack-size` is not needed because it sets the process stack size, but we needed to change the threads stack size.
- changing threads stack size is not needed for systemd-journal.plugin because this plugin is glibc only (the problem was musl libc thread stack size).
</details>
=> packaging cleanup after #15842

collectors/proc.plugin/proc_meminfo.c
The bug was introduced in https://github.com/netdata/netdata/pull/15494/files#diff-13ee0998f68cd432ef08fa560ede0b845e8b3100947a8c9e9d70bdc234ffb577
[Reported on Discord](https://discord.com/channels/847502280503590932/1143104256753274983/1143104256753274983): negative ram `used` and huge `cached`.
[KReclaimable includes SReclaimable](https://github.com/torvalds/linux/blob/f7757129e3dea336c407551c98f50057c22bb266/fs/proc/meminfo.c#L106), we shouldn't sum them but use KReclaimable (available since kernel v4.20) or SReclaimable.
</details>
=> fix proc meminfo cached calculation

exporting/exporting.conf, exporting/exporting_engine.h, exporting/prometheus/prometheus.c, exporting/read_config.c
#15099 introduced a bug for metrics utilizing label names that conflict with existing 'special' names: chart, dimension, family, instance.
This bug results in duplicate labels, which Prometheus will reject on intake.
My original fix in #15387 was to replace either the netdata labels or the chart labels when there are duplicates.
@ilyam8 suggested to apply a prefix to netdata labels instead of eliminating one or the other. This PR implements this.
1. Compile Branch and start netdata.
2. Update netdata prometheus exporting conf to apply a label prefix.
3. Query the prometheus exporter. The netdata labels have a prefix.
Example exporting configuration:
```
[prometheus:exporter]
netdata label prefix = nd_
```
Results in labels like:
``` …
```
=> Apply a label prefix for netdata labels

integrations/templates/overview/collector.md
This adds info about the plugin and module for a collector to the top of the integration overview.
n/a
Relevant to: https://github.com/netdata/netdata/issues/15707
=> Add plugin and module information to collector integrations.

libnetdata/facets/facets.c
Small improvement to use `XXH3_128()` instead of `XXH128()`. Faster and works better on small strings.
=> use the newer XXH3 128bits algorithm, instead of the classic XXH128

collectors/systemd-journal.plugin/systemd-journal.c, libnetdata/facets/facets.c, libnetdata/facets/facets.h
In systemd-journal we have the following problem:
1. Many fields are useless for facets, almost all their values are unique, like timestamps, or IDs of some kind.
2. Because of this, there is a hard-coded list of keys that is "interesting" for facets.
3. But since this list is hard-coded, how can a user turn a field he/she is interested to a facet?
To solve the problem, a new function parameter called `facets` is accepted, which gets a comma separated list of the key IDs, which should be treated as facets.
=> allow any field to be a facet

database/sqlite/sqlite_functions.c, database/sqlite/sqlite_metadata.c
- Improve the metadata cleanup jobs to cleanup stale dimensions, charts and chart labels
- Cleanup jobs will incrementally cleanup the corresponding tables. To minimize resource usage jobs will run for max of 5 seconds or if 500 items are deleted and will be rescheduled after one minute. 
- Storing new metadata always takes priority and skips running the cleanup jobs
- Issue a database incremental vacuum to shrink database size if free pages are over 5% of the database size
=> Metadata cleanup improvements

claim/claim.c, configure.ac, database/rrd.h, database/rrdhost.c, exporting/send_data.c, libnetdata/libnetdata.c, netdata-installer.sh, streaming/sender.c, web/server/static/static-threaded.c, web/server/web_client.c
Noticed that our build with `--disable-https` was not working. This PR tries to fix that.
What this PR changes, and we can discuss, is that when using the `--disable-https` switch on the installer, it also disables `dbengine`, `h2o`, `kinesis exporter` and `cloud`. This makes sure that even if openssl libraries are installed on the system, the final binary will not be linked against it.
I'm not sure about `h2o` whether or not it can work without openssl, and if we should disable it like this. However I noticed that if we don't explicitly disable it then it will pull in ssl libs.
All of the other changes are just guards with `ifdefs`.
Ensure a build and run of the agent with and without `--disable-https` works ok. …
=> Fix build with --disable-https

collectors/python.d.plugin/sensors/sensors.chart.py
* Fix a limit that caused my properly functioning PMBus power supply sensor to be skipped as it reported 208VAC.
* The 400V limit was pulled from the [Open Compute Project M-CRPS specification v1.0 Section 5.1.3.2](https://www.opencompute.org/documents/m-crps-r1-v1p0-rc4-pdf)  which defines a power supply input voltage as 380VDC and specifies a Vmax of 400VDC.
* Also decrease the lower limit to -400VDC as some telecom power supplies may report negative voltage, most notable is -48VDC and expect more could as well.
Patch system with PMBus enabled power supply and verify correct operation.
- Increases voltage range to properly handle high voltage PMBus power supplies.
</details>
=> python.d/sensors: Increase voltage limits 127 -> 400

database/sqlite/sqlite_functions.c, database/sqlite/sqlite_health.c, database/sqlite/sqlite_metadata.c
Fixes #15908 
- Use a new index to make cleanup faster
- Check less entries per iteration during metadata cleanup
- A future PR will improve on these even more
- Start agent
- Notice CPU spike 30 minutes after restart  under `Netdata Monitoring` section, there is a `workers` entry --> `libuv`
Apply the PR and check again
- CPU spike should be minimal
=> Reduce workload during cleanup

collectors/plugins.d/pluginsd_parser.c, daemon/service.c, database/contexts/instance.c, database/rrd.h, database/rrdset.c, health/health.c, ml/ml.cc, web/api/formatters/charts2json.c, web/api/formatters/charts2json.h, web/api/web_api_v1.c
This PR makes 2 small changes:
The first is if the service thread does not clean a chart (because of timing factors) to re-set the host wide `RRDHOST_FLAG_PENDING_OBSOLETE_CHARTS` flag to re-try on the next iteration.
The second change is to execute `rrdset_free` in all memory modes.
The goal is to see whether memory usage can be reduced in case of many ephemeral charts.
</details>
=> Reset the obsolete flag on service thread

health/notifications/alarm-notify.sh.in
First, thanks for adding ntfy support!
Many notification methods replace underscores with spaces for the name variable. So the message actually looks better and I think the same can be used for ntfy.
=> Replace _ with spaces for name variable for ntfy

exporting/send_data.c, libnetdata/socket/security.c
`SSL_read()` in `netdata_ssl_read()` returning 0 bytes is currently being treated as an error, and returning `-1` instead. If the connection is closed on the other end, 0 bytes should be returned to the calling method, so the connection is properly closed on both sides.
Check that connector response methods now correctly handle a closed socket and don't treat 0 returns bytes as an error case.
</details>
=> don't return `-1` if the socket was closed

packaging/installer/kickstart.sh
The existing code fails in dry run mode because it blindly expects the files to be copied. However, we don’t actually need to copy them at all since we just want to read them.
The failure cases here are only seen when running in dry-run mode against an existing install. Without this PR, such a run of the kickstart script should fail in a manner like what is reported in #15875. With this PR, the run should complete successfully.
Fixes: #15875
=> Skip copying environment/install-type files when checking existing installs.

collectors/proc.plugin/proc_diskstats.c
Add the following labels to disks:
(removed `rotational` and `removable` since the kernel seems to provide wrong information about them.
=> Disk Labels

netdata.spec.in
* enable build_ids for c8s & c9s
* possibility to build netdata in closed environments (without Internet)
Fixed RPM issue
```
TODO: Temporary fix for the build-id error during go.d plugin set up
```
=> RPM: build go.d.plugin native for CentOS-Stream

packaging/bundle-ebpf-co-re.sh, packaging/bundle-ebpf.sh, packaging/bundle-libbpf.sh, packaging/bundle-protobuf.sh
This fixes an issue that shows up when building packages for some distros (most notably CentOS 7) with a rootless container runtime (such as using Podman for the build as a regular user).
This one is a bit tricky to test. It requires using a rootless container runtime (either Podman or rootless Docker, run as a regular user other than root) to attempt to build one of our native packages, but the failure is only observed with some target distributions (CentOS 7 is the only one I’ve currently confirmed to be affected, but I suspect it affects most of the other target distributions as well), and it may be dependent specific aspects of configuration of the build host as well.
On affected setups without this PR, error messages should be seen complaining about failing to change file ownership …
=> Skip trying to preserve file owners when bundling external code.

collectors/systemd-journal.plugin/systemd-journal.c, libnetdata/facets/facets.c
=> Facets: fixes 5

collectors/apps.plugin/apps_plugin.c
This reverts the locks optimization for apps.plugin related to the execution of functions.
The function `processes` uses the internal structures of the
=> apps.plugin function is not thread safe

database/rrd.h, database/rrdfunctions.c, libnetdata/required_dummies.h, libnetdata/threads/threads.c, streaming/rrdpush.c
Sometimes functions of children become unavailable. It seems that somehow the collector is not marked as running, although there is a collector running...
This PR makes sure a collector is always in running state when it runs.
The problem was the GLOBAL functions. If they were added after netdata connected to a parent, they were not propagated to that parent. Now, a host flag has been added to enable sending them again to the parent, once they have been updated.
=> Functions: allow collectors to be restarted

database/rrd.h, database/rrdcalc.c, health/health.c
This PR addresses the following issue:
When a chart with X dimensions is created and is linked to an rrdcalc, then only those present X dimensions are added to the charts's rrdvars.
When a new dimension of this chart arrives after this, it is not stored in rrdvars. This PR adds a check that if the chart is already linked to at least one rrdcalc, then it re-stores the data we need in rrdvars.
To check the bug exists, a modified charts.d example is used, that sends the random3 dimension 60 seconds after it sends the initial 2. e.g.:
```
@@ -92,11 +92,14 @@ example_create() {
CHART example.random '' "Random Numbers Stacked Chart" "% of random numbers" random random stacked $((example_priority)) $example_update_every '' '' 'example'
DIMENSION random1 '' percentage-of-absolute-row 1 1 …
```
=> Re-store rrdvars on late dimensions

ml/Config.cc, ml/README.md
Now that we have a [default ml alert](https://github.com/netdata/netdata/pull/14687) (albeit to: silent) we should think about extending the default training data size (as was always planned) to something closer to 2 days by default. 
This will help reduce the probability of "once daily" type jobs triggering as anomalies. 
"one daily" is a common enough pattern that it merits using 2 days by default. This will also end up overall improving anomaly detection performance. 
We have been dogfooding this in the [ml demo room](https://app.netdata.cloud/spaces/netdata-demo/rooms/machine-learning/overview) for a few months.
- `ml-demo-nightly`: current defaults
- `ml-demo-nightly-48h-training`: ~48h config as per [here](https://github.com/netdata/community/tree/main/configuration-management/ansibl …
=> extend ml default training from ~24 to ~48 hours

collectors/systemd-journal.plugin/systemd-journal.c
Properly check if the UID and GID have names.
=> Systemd-Journal: fix crash when the uid or gid do not have names

libnetdata/threads/threads.c
We noticed that some Netdatas are crashing on start on a host with 80 ND instances (docker containers). This PR fixes the following coredumps:
<details>
<summary>coredump1</summary>
```c
#0  pthread_setname_np (thread=0x0, name=name@entry=0x7fca6f1cf6d0 "ACLKSYNC") at src/thread/pthread_setname_np.c:20
#1  0x00005646b9672862 in uv_thread_set_name_np (ut=<optimized out>, name=<optimized out>) at libnetdata/threads/threads.c:242
#2  0x00005646b9703b69 in aclk_synchronization (arg=0x5646b99f1ba0 <aclk_sync_config>) at database/sqlite/sqlite_aclk.c:365
#3  0x00007fca71cacbd2 in start (p=0x7fca6f1cf7a0) at src/thread/pthread_create.c:207
#4  0x00007fca71caef40 in __clone () at src/thread/x86_64/clone.s:22
```
</details>
<details>
<summary>coredump2</summary>
```c
#0  pthread_setname_np …
```
=> fix crash on setting thread name

netdata.spec.in
When switching from Alma Linux to Rocky Linux for our RHEL package builds, we missed one place in our RPM spec file where a conditional was checking whether we were building on Alma or not.
This fixes that conditional so it also checks for Rocky, which otherwise fails the build in the same way that Alma would without the conditional.
It also future-proofs things so that we behave correctly on RHEL 10 when that finally comes out.
Rocky Linux CI jobs pass on this PR.
=> Fix package builds on Rocky Linux.

collectors/plugins.d/pluginsd_parser.c, collectors/plugins.d/pluginsd_parser.h, collectors/systemd-journal.plugin/systemd-journal.c, libnetdata/buffer/buffer.c, libnetdata/buffer/buffer.h, streaming/receiver.c, streaming/rrdpush.h
Pluginsd had a line limit of 15KiB.
This had a lot problems for functions than need to send minified JSON data.
This PR removes this limit, so that plugins can send lines of any length.
=> remove the line length limit from pluginsd

netdata.spec.in, packaging/makeself/jobs/70-netdata-git.install.sh
Some quirks on specific platforms mean it doesn’t build cleanly right now in a couple of our pre-built platforms, so just disable it for them.
Static builds and Oracle Linux package builds pass on this PR.
=> Disable mongodb exporter builds where broken.

packaging/installer/methods/macos.md
Docs for fixing https://github.com/netdata/learn/issues/1789
Instaling via Homebrew on Apple Silicon Macs uses different path prefix with Intel Macs.
Describe separately for them.
It's just markdown document updates.
This change would update netdata document. For users using Apple Silicon Macs, it will help them installing netdata via Homebrew.
</details>
=> add description for Homebrew on Apple Silicon Mac(netdata/learn/#1789)

database/sqlite/sqlite_db_migration.c, database/sqlite/sqlite_functions.c
In some cases the `summary` field does not exist in `health_log_detail`. This PR adds another migration to v13 and adds the field again.
Run this PR on an older (e.g. from stable) agent, and on a new one. Make sure the `summary` field exists in both the `health_log_detail` and `alert_hash` tables.
</details>
=> Fix summary field in table

database/rrd.h, database/rrdhost.c, database/sqlite/sqlite_db_migration.c, database/sqlite/sqlite_functions.c, database/sqlite/sqlite_metadata.c
Store the last connected time per node. This will be useful to handle ephemeral nodes
and other optimizations
=> Maintain node's last connected timestamp in the db

health/Makefile.am, health/health.d/upsd.conf
This PR adds alerts for [go.d/upsd](https://github.com/netdata/go.d.plugin/tree/master/modules/upsd#ups-nut-collector) (replacement for [charts.d/nut](https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin/nut#upspdu-collector)). That collector is not yet in the master branch, will be added next week.
Install this branch and check if upsd alerts are installed.
</details>
=> health: add upsd alerts

.github/scripts/get-static-cache-key.sh, .github/workflows/packaging.yml, packaging/building-native-packages-locally.md, packaging/docker/Dockerfile, packaging/makeself/build-static.sh
Second part of https://github.com/netdata/helper-images/pull/242. This updates our CI to actually used the new version tags for the various Docker images it’s using.
This needs to be merged before https://github.com/netdata/helper-images/pull/223 gets merged.
=> Update to use versioned base images for CI.

database/sqlite/sqlite_metadata.c
- CID 402975:  High impact quality  (Y2K38_SAFETY)
/database/sqlite/sqlite_metadata.c: 368 in store_host_metadata()
Use sqlite3_bind_int64 to resolve issue
=> Fix coverity 402975

database/sqlite/sqlite_context.c, database/sqlite/sqlite_db_migration.c, database/sqlite/sqlite_db_migration.h, database/sqlite/sqlite_functions.c, database/sqlite/sqlite_functions.h, database/sqlite/sqlite_metadata.c, database/sqlite/sqlite_metadata.h, ml/ml.cc, ml/ml.h
Change the ML database to use WAL mode and be able to use vacuum to shrink the database size. 
It will set the database journal_mode to WAL and set auto_vacuum to incremental. For this change
to tale effect a database `vacuum` command is required. 
After introducing the PR that deleted old entries #15720, the database may occupy more disk space than needed. This PR will shrink the database size by freeing the unused space and maintain that size by issuing frequent incremental vacuum commands. 
- Check the size of `ml.db` (found in var/cache/netdata) of an agent with ML enabled before and after running this PR.
=> Convert the ML database 

integrations/gen_docs_integrations.py
This adds a logic to append a badge right after the title and plugin/module info.
Example:
Plugin: apps.plugin
Module: apps
Monitor Applications for optimal software performance and resource usage.
=> [Integrations Docs] Add a badge for either netdata or community maintained

aclk/schema-wrappers/alarm_config.cc, aclk/schema-wrappers/alarm_config.h, aclk/schema-wrappers/alarm_stream.cc, aclk/schema-wrappers/alarm_stream.h, database/contexts/api_v2.c, database/contexts/rrdcontext.h, database/sqlite/sqlite_aclk_alert.c, database/sqlite/sqlite_health.c
This PR sends the `summary` field of the alerts (both from alarm log events and configs) to the cloud. It also exposes the field to `v2/alert_transitions` and `v2/alert_config`.
Will be tested with backend, points to test:
* Field is transmitted in normal alert stream
* Field is transmitted in alert snapshots
* Field is transmitted in alert configs
</details>
=> Send alerts summary field to cloud

collectors/cgroups.plugin/metadata.yaml, collectors/cgroups.plugin/sys_fs_cgroup.c
Fixes #14943
This PR is reorganizing the way we are showing our services charts.
1. Compile this branch on environment that has systemd.
2. Run and take a look how charts are now shown on dashboard. 
| Linux Distribution | Bare metal / VM | Kernel version | 
|----------------------------|-------------------------|-----------------------|
|Arch Linux | Libvirt | 6.5.2-arch1-1 | 
|Ubuntu 22.04 | Libvirt | 5.15.0-76-generic|
|Debian 11 | Libvirt| 5.10.191-1|
- Which area of Netdata is affected by the change? cgroup plugin
- Can they see the change or is it an under the hood? If they can see it, where? Yes, when user access dashboard they will have charts inside …
=> Split cgroup charts

database/rrdlabels.c
Partially fixes #15923
- Add proper check to avoid duplicate keys (same key with multiple values) in labels.
=> Avoid duplicate keys in labels

collectors/python.d.plugin/python.d.plugin.in
Adds support for env variable added in #14727.
Tested by running from terminal with different values.
```
NETDATA_LOG_SEVERITY_LEVEL=err ./python.d.plugin example
```
</details>
=> python.d: respect env NETDATA_LOG_SEVERITY_LEVEL

collectors/charts.d.plugin/charts.d.plugin.in
Adds support for env variable added in #14727.
Tested by running from terminal with different values.
```
NETDATA_LOG_SEVERITY_LEVEL=err ./charts.d.plugin
```
</details>
=> charts.d: respect env NETDATA_LOG_SEVERITY_LEVEL

collectors/apps.plugin/apps_plugin.c, collectors/cgroups.plugin/cgroup-name.sh, collectors/cgroups.plugin/cgroup-network-helper.sh, collectors/cgroups.plugin/cgroup-network.c, collectors/cups.plugin/cups_plugin.c, collectors/debugfs.plugin/debugfs_plugin.c, collectors/ebpf.plugin/ebpf.c, collectors/freeipmi.plugin/freeipmi_plugin.c, collectors/ioping.plugin/ioping.plugin.in, collectors/nfacct.plugin/plugin_nfacct.c, collectors/perf.plugin/perf_plugin.c, collectors/slabinfo.plugin/slabinfo.c, collectors/systemd-journal.plugin/systemd-journal.c, collectors/xenstat.plugin/xenstat_plugin.c, health/notifications/alarm-notify.sh.in, libnetdata/log/log.c, libnetdata/log/log.h
Adds support for the env variable added in #14727 to:
python.d addressed in #16084, charts.d in #16085, go.d in netdata/go.d.plugin#1351
Tested by running from the terminal with different values:
```
NETDATA_LOG_SEVERITY_LEVEL=<Level> ./<Plugin>
```
</details>
=> external plugins: respect env NETDATA_LOG_SEVERITY_LEVEL

collectors/systemd-journal.plugin/README.md
- Remove a br that Learn was indicating as broken, replace it by the markdown way of having two spaces at the end of the line
- Move the index below heading 1, because Learn freaks out if heading 1 is not first in the file
- Remove some redundant `:` in two of the headings
Also I tested the file on Learn, so we should be good to go.
It will be added under data collection, with name `SystemD-Journal`
=> Fix systemd-journal.plugin README and prepare it for Learn

database/sqlite/sqlite_db_migration.c, database/sqlite/sqlite_db_migration.h, database/sqlite/sqlite_functions.c, database/sqlite/sqlite_health.c
Currently on a new agent installation the database migration steps are followed. Initially this was needed when the migration process was set in place and the database version for older agents was not known (set to 0).
With this PR if the database user version is 0 and no tables are found the migration steps are skipped (no needed)
=> Skip database migration steps in new installation

collectors/ebpf.plugin/ebpf.c
To collect `oomkill` events, it is necessary to have integration with apps enabled, this PR removes the initialization of `oomkill` when apps is not set.
1. Compile branch
2. start ebpf with apps integration disabled and check that we do not have the chars.
</details>
=> Do not force OOMKill

streaming/sender.c
Fixes #16074
This bug is in developer only code at this time (only compiled when DYNCFG CFLAG is used).
When FUNCTION_PAYLOAD was sent over streaming the parser stripped newlines accidentally.
Use some HTTP client of your choice (you can use https://github.com/netdata/netdata/pull/16113, or insomnia, curl, wget) to set plugin config trough parent.
New lines should not be stripped anymore.
</details>
=> dont strip newlines when forwarding FUNCTION_PAYLOAD

collectors/cgroups.plugin/metadata.yaml, collectors/python.d.plugin/beanstalk/metadata.yaml
Due to a bug/misbehavior in integrations/gen_integrations.py when there are multiple categories on an integration, they get randomly written in the .js file, and the documentation generation script uses the first one, resulting in constant rotation of the categories.
We comment the category we don't want until we find a fix for this.
=> Remove multiple categories due to bug

collectors/apps.plugin/apps_plugin.c, collectors/apps.plugin/metadata.yaml
Removing `_` because it is a bit problematic for UI (menu.js - icon, description, etc.). As it is now it reuses `user` for `user_group`.
Install, check charts
</details>
=> apps: change user_group to usergroup

integrations/gen_integrations.py
It was found that using sets was writing the categories in random order to the final js file, thus making Learn (which uses always the first one in the list) to keep moving documents around.
This fix uses a list comprehension to get the list of the elements and then remove those that are not present in the `actual_cats` set, which is shuffled sometimes.
The list always retains its order, thus solving the above-mentioned issue.
=> Retain a list structure instead of a set for data collection integrations categories

packaging/installer/kickstart.sh
Fixes: #16119
`netdata-uninstaller.sh` is 750 root root. We need to run as roo `text -x` check.
```bash
sudo ./kickstart.sh --static-only
./kickstart.sh --uninstall
```
</details>
=> fix `test -x` check for uninstaller script

collectors/systemd-journal.plugin/README.md, collectors/systemd-journal.plugin/systemd-journal.c, libnetdata/facets/facets.c
=> journal: updates

packaging/installer/netdata-uninstaller.sh
Fixes: #16147
I think the only missing part is `systemctl daemon-reload` after stopping ND/deleting ND systemd files, but that is a different issue and subject to a separate PR.
```bash
sudo ./kickstart.sh --static-only
./kickstart.sh --uninstall
find /usr/lib/systemd -iname "*netdata*"
find /tmp -iname "*netdata*"
```
Check `/tmp`
</details>
=> uninstaller: remove ND systemd preset and tmp dir

database/sqlite/sqlite_aclk_alert.c
When there is a configuration change in an alert that does not involve it's name and chart, the agent starts a new alert chain (with a different alarm_id). It will then transmit a REMOVED for the previous chain, and a new status for the new one.
However, for the cloud, if the name and chart remain the same it's still considered the same alert. With the way it works, the cloud will receive the new alert and then the REMOVED.
This PR adds an additional check when it queues REMOVED events. If there is a newer (based on the alarm_id) alert with the same name and chart, it will not send that REMOVED event.
Test requires some digging on the sqlite database, or using the `converstation log` to check the messages to the cloud.
When running this PR on a claimed running agent, pick a random alert …
=> Don't queue removed when there is a newer alert

collectors/ebpf.plugin/ebpf.c, collectors/ebpf.plugin/ebpf.h, collectors/ebpf.plugin/ebpf_cachestat.c, collectors/ebpf.plugin/ebpf_cgroup.c, collectors/ebpf.plugin/ebpf_dcstat.c, collectors/ebpf.plugin/ebpf_disk.c, collectors/ebpf.plugin/ebpf_fd.c, collectors/ebpf.plugin/ebpf_filesystem.c, collectors/ebpf.plugin/ebpf_functions.c, collectors/ebpf.plugin/ebpf_hardirq.c, collectors/ebpf.plugin/ebpf_mdflush.c, collectors/ebpf.plugin/ebpf_mount.c, collectors/ebpf.plugin/ebpf_oomkill.c, collectors/ebpf.plugin/ebpf_process.c, collectors/ebpf.plugin/ebpf_shm.c, collectors/ebpf.plugin/ebpf_socket.c, collectors/ebpf.plugin/ebpf_softirq.c, collectors/ebpf.plugin/ebpf_swap.c, collectors/ebpf.plugin/ebpf_sync.c, collectors/ebpf.plugin/ebpf_vfs.c
After a talk with @ktsaou I am modifying variables used to shutdown plugin fixing the issue:
```sh
Program terminated with signal SIGSEGV, Segmentation fault.
#0  rrd_functions_worker_globals_reader_main (arg=0x7f3ebc000b70) at libnetdata/functions_evloop/functions_evloop.c:161
161	        *wg->plugin_should_exit = true;
[Current thread is 1 (Thread 0x7f3ebbfff6c0 (LWP 2476))]
(gdb) bt
#0  rrd_functions_worker_globals_reader_main (arg=0x7f3ebc000b70) at libnetdata/functions_evloop/functions_evloop.c:161
#1  0x0000555fa6f40721 in netdata_thread_init (ptr=<optimized out>) at libnetdata/threads/threads.c:279
#2  0x00007f3ed84aa9eb in start_thread (arg=<optimized out>) at pthread_create.c:444
#3  0x00007f3ed852e7cc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```
1. Compile …
=> Modify eBPF exit

collectors/apps.plugin/apps_plugin.c
This PR removes `mem_private_usage` (rss - shared) apps.plugin chart on FreeBSD because we don't collect shared.
https://github.com/netdata/netdata/blob/f7789e1a83fa819cb072b7d818aef1ceb79c1bcb/collectors/apps.plugin/apps_plugin.c#L1518-L1525
- install on Linux, check `mem_private_usage` - exists.
- install on FreeBSD, check `mem_private_usage` - doesn't exist.
</details>
=> apps: remove mem_private on FreeBSD

daemon/main.c
Just log the agent version on startup 
```
2023-10-13 22:46:50: netdata INFO  : MAIN : Netdata agent version "v1.42.0-345-gb7ef34c3d" is starting
```
=> Add agent version on startup

collectors/freebsd.plugin/metadata.yaml, collectors/proc.plugin/metadata.yaml, health/health.d/net.conf
Instead of `net.packets` which is very confusing when you "go to chart".
Check net interface drops ratio alarms.
</details>
=> health: attach drops ratio alarms to net.drops

libnetdata/facets/facets.c
=> add order in available histograms

database/contexts/api_v2.c
Adds the `summary` field to `/api/v2/alerts` under the `alerts` array (it was only added to `alert_instances`).
Start an agent and visit e.g. `http://localhost:19999//api/v2/alerts?options=summary,instances,values`. Summary (as `sum`) should be under the `alerts` array.
</details>
=> add summary to /alerts

libnetdata/log/log.c
It can be configured by changing the destination value to `syslog` (the default is a path to the file).
Install Netdata, check /var/log/syslog (and journalctl -u netdata).
</details>
=> disable logging to syslog by default

collectors/cgroups.plugin/cgroup-network.c
`cgroup-network` tries to [read **cgroup.procs** and **tasks**](https://github.com/netdata/netdata/blob/b1121d4e02bd62a150e5cab849778624c67db2ea/collectors/cgroups.plugin/cgroup-network.c#L319-L328). The latter doesn't always exist, so it is not an error to fail to open it.
Check logs.
</details>
=> cgroup-network: don't log an error opening pid file if doesn't exist

collectors/systemd-journal.plugin/README.md, collectors/systemd-journal.plugin/passive_journal_centralization_guide_no_encryption.md, collectors/systemd-journal.plugin/passive_journal_centralization_guide_self_signed_certs.md, docs/category-overview-pages/logs.md
- small grammar changes on base README (no need for `"journals' centralization"` wording)
- Extract the two guides about passive setups and make them their own pages with minimal changes (introductory changes mainly)
- Add links in the base README's FAQ section
- Add a category overview page, that summarizes the wanted `Logs` section on Learn. We need this in order to properly function with Learn and not resort to hacky operations
@ktsaou take a look and let me know if I need to make any more changes.
I will make the changes to Learn once we merge this (so I can actually test that the whole thing plays together nicely).
=> Changes to `systemd-journal` docs

collectors/apps.plugin/apps_groups.conf
We run a couple of Elixir apps in production and would like Netdata to report their compute usage. A command starts usually like this:
```
/app/erts-12.3.2.13/bin/beam.smp -- -root /app -progname erl -- -home /app -- -noshell -s elixir start_cli ...
```
ERTS is the Erlang Runtime System, BEAM is the virtual machine where the code is executed. Therefore, I suggest to search for `erts` in `apps_groups.conf`, as its the "lowest" component of the Erlang stack.
Note that RabbitMQ also uses Erlang, but I placed the line lower than RabbitMQ, so that those rules apply first.
- Run a Erlang-based application, like an [Elixir console](https://hub.docker.com/_/elixir), on a monitored Netdata node.
- The apps plugin should now report separate data for this Erlang process.
<details> <summary>For …
=> Add Erlang to Apps configuration

database/engine/rrdengine.c, database/engine/rrdengine.h, database/rrd.h
- Use uint64_t to prevent overflow on reported `disk_used` in 32bit systems
- Changed also when calculating target data file size
before
```
"tier":0,
"disk_used":3951299944,
"disk_max":8589934592,
"disk_percent":45.9991855,
"from":1696413590,
"to":1697532300,
"retention":1118710,
"expected_retention":2432021,
```
after
```
"tier":0,
"disk_used":8299235868,
"disk_max":8589934592,
"disk_percent":96.6158214,
"from":1696413590,
"to":1697535541,
"retention":1121951,
"expected_retention":1161249,
```
</details>
=> Fix statistics calculation in 32bit systems

packaging/installer/netdata-uninstaller.sh
Remove the updater file added for `crontab` updater type
https://github.com/netdata/netdata/blob/3af70c8f9ea269d7324a5be7ebc4dd69eb0495b3/packaging/installer/netdata-updater.sh#L238-L241
Not needed
</details>
=> uninstaller: remove /etc/cron.d/netdata-updater-daily

packaging/installer/methods/packages.md
Prompted by users requesting info about mirroring our repos.
The details here are _very_ intentionally vague, as most of what needs to be done is going to depend on the exact use case of the user who is mirroring the repos.
n/a
=> Add info to native packages docs about mirroring our repos.

database/rrdlabels.c
- Adds more tests in various functions
- Handle attempt to add duplicate label more efficiently
- Add unit test for duplicate label check and labels migration
=> Improvements for labels handling

packaging/installer/kickstart.sh
Fixes: #16226.
It is `auto-update-type` in usage.
</details>
=> kickstart: rename auto-update-method to auto-update-type

database/sqlite/sqlite_metadata.c, ml/ml-dummy.c, ml/ml.cc, ml/ml.h
- ML models to be loaded are grouped together and handed of to a separate worker thread for batch load. Right now the worker thread will not release the prepared statement resources when done (kept to be reused when that same worker thread
is selected to do a batch ML load in the future). Since this may not be the case this PR changes this behavior and releases the resources on each batch load. 
- Fix parameter to ML model load to be in seconds not usec and also bind as int64. This would result in more models to be loaded than needed due to an overflow during the param binding.
=> Reuse ML load prepared statement

daemon/unit_test.c, database/sqlite/sqlite_aclk.c, database/sqlite/sqlite_aclk_alert.c, database/sqlite/sqlite_db_migration.c, database/sqlite/sqlite_functions.c, database/sqlite/sqlite_metadata.c
- The index `aclk_alert_index_xxx`  where x is a nodes machine guid, is not used.  The corresponding table column (alert_unique_id) is defined as `unique` and has an automatic index created anyway. This PR will drop it to save some space.
- Switch 3 log messages that refer to internal cleanup to appear only when compiled with NETDATA_INTERNAL_CHECKS
=> Drop an unused index from aclk_alert table

collectors/cgroups.plugin/sys_fs_cgroup.c
During agent shutdown sometimes there is a deadlock when stopping the cgroups `discovery thread worker`. The result is the agent may need more that 15 seconds (the grace period for the discovery thread to properly shutdown). The error.log will have several messages similar to: 
```
netdata INFO  : MAIN : SERVICE CONTROL: waiting for the following 1 services [ COLLECTORS ] to exit: 'P[cgroups]' (226967)
netdata INFO  : MAIN : SERVICE CONTROL: waiting for the following 1 services [ COLLECTORS ] to exit: 'P[cgroups]' (226967)
netdata INFO  : MAIN : SERVICE CONTROL: waiting for the following 1 services [ COLLECTORS ] to exit: 'P[cgroups]' (226967)
```
The problem is identified in 
```
#4  0x00007ff445b569ad in uv_mutex_lock () from /lib/x86_64-linux-gnu/libuv.so.1
#5  0x0000559e7e6307f2 in …
```
=> Terminate cgroups discovery thread faster during shutdown

collectors/cgroups.plugin/cgroup-name.sh, packaging/docker/run.sh
Proxmox virtual machine/container names, CPU and memory limits are found in the configuration files:
|  Type   | Dir |
| :-------- | :-------: |
| VMs  | `/etc/pve/qemu-server/`    |
| Containers | `/etc/pve/lxc/`     |
This PR:
- Adds `netdata` user to the host's `www-data` group (only if the host is a Proxmox host, needed to read the configuration file).
- Adds support for `NETDATA_HOST_PREFIX` in `cgroup-name.sh` for Proxmox name resolution.
Test that name resolution works by installing this PR on Proxmox:
- docker ND (`-v /etc/pve:/host/etc/pve:ro` mount is needed).
- regular ND.
</details>
=> docker install: support for Proxmox vms/containers name resolution

collectors/python.d.plugin/smartd_log/smartd_log.chart.py
As [discussed](https://github.com/netdata/netdata/pull/10872#issuecomment-819652811) in https://github.com/netdata/netdata/pull/10872, it would be nice to have Total LBAs written/read metrics available.
Additionally, [Samsung drives use attribute 177 Wear Levelling Count](https://download.semiconductor.samsung.com/resources/others/SSD_Application_Note_SMART_final.pdf) for erase cycles currently only supported as [attribute 233 for Intel drives](https://www.thomas-krenn.com/en/wiki/SMART_attributes_of_Intel_SSDs), so I added that too.
Component: `python.d/smartd_log` collector
I've tested this manually with two Samsung drives:
SSDs are typically guaranteed for a maximum amount of drive writes within their warranty period, so this is an extremely useful metric to track.
=> python.d(smartd_log): collect Total LBAs written/read

daemon/main.c, libnetdata/dictionary/dictionary.c, libnetdata/dictionary/dictionary.h
call `cleanup_destroyed_dictionaries()` while waiting for collectors to finish
=> shutdown while waiting for collectors to finish

collectors/systemd-journal.plugin/systemd-journal.c
This PR allows systemd journals explorer to support selecting multiple sources.
This is useful when you want to explore, query and filter a subset of the remote systems available.
=> Journal multiple sources

health/notifications/alarm-notify.sh.in
Removes a trailing comma to make the Discord/Slack payload valid JSON.
Otherwise the Discord notification is not sent.
https://learn.netdata.cloud/docs/alerting/notifications/agent-dispatched-notifications/discord#test-notification
Fixes #16256
Discord notifications should be sent again.
</details>
=> Fix Discord webhook payload

web/api/queries/query.c
Use the additional tiers to query, only when they provide data to the requested time-frame.
=> QUERIES: use tiers only when they have useful data

collectors/systemd-journal.plugin/README.md, collectors/systemd-journal.plugin/systemd-journal.c
=> journal minor updates

collectors/systemd-journal.plugin/systemd-journal.c
When selecting multiple journal sources, do the match properly.
=> fix sources match

collectors/plugins.d/pluginsd_parser.c, libnetdata/dyn_conf/README.md, streaming/rrdpush.c
Fixes https://github.com/netdata/netdata/issues/16075
additionally adds clarification to documentation.
If reason string is to be omitted (it makes no sense for example if status is OK) originally the intention was that plugin will not send this parameter at all. However this was not documented and as consequence `go.d` sent `""` empty string as reason in such case.
This PR makes it work both ways `""` empty string is considered equal to no reason string at all. Also fixes the streaming of the command to parent.
2 agents with streaming
create `go.d/httpcheck` job using `POST api/v2/go.d/httpcheck` 
streaming will not disconnect anymore after job starts running (and reports running status)
</details>
=> DYNCFG fix REPORT_JOB_STATUS streaming

packaging/VERSIONING_AND_PUBLIC_API.md
To go into effect with the release of v2.0.0.
This is intended to specifically cover when breaking changes may happen, and indicate when they are guaranteed not to happen.
n/a
=> Add document outlining our versioning policy and public API.

streaming/sender.c
In a parent - child setup if the child is RPI with static build installed then the following scenario can cause a crash
- Connect child to parent
- Stop parent and wait a few seconds
- Start parent
If the child connects to the parent but it gets a response to retry later because the parent is still initializing, the child
may crash.
=> Prevent wrong optimization armv7l static build

collectors/plugins.d/pluginsd_parser.c, database/rrdlabels.c, database/rrdset.c
increase metadata version to resend chart upstream when labels and other metadata are updated
=> fix missing labels from parents

collectors/systemd-journal.plugin/systemd-journal.c
On busy centralization servers, accessing the journal for the first time can be slow because the plugin has to go through a lot of files to query and extract the time-frame available in each journal file.
Now the plugin scans the journal files every minute, so that when a user accesses the journal function, it will only have to scan journal files that have been updated during the last minute.
=> update journal sources once per minute

packaging/makeself/bundled-packages
[Sec Adv 20231024](https://www.openssl.org/news/secadv/20231024.txt)
Not a blocker for the patch release 
</details>
=> bump openssl for static in 3.1.4

collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh, health/health.d/apcupsd.conf
I propose to add a new chart for the SELFTEST status of the APCUPSD.  When it fails, i.e. that status code is NG or BT, it fires off an alarm to the sitemgr.  The SELFTEST failing is the first sign of APC battery problems, before the apcupsd status changes.
I'm not sure of a way to generate a bad SELFTEST code from apcaccess status, but you can inverse the logic to make sure that a good status code sends out a warning to know that it's working properly.  So  If you change this line in the acupsd.conf file:
crit: $this > 1
to:  
crit: $this < 0
It will fire off an alarm with a "good status", to test that it is working properly.
- This affects people that have enabled the apcupsd metric, and it allows people to optionally add the chart apcupds.selftest
=> Apcupsd selftest metric

daemon/main.c, database/rrd.h, database/sqlite/sqlite_functions.c, database/sqlite/sqlite_metadata.c, streaming/receiver.c
Currently we queue dimension ML load commands as dimensions are created. We can take advantage of the metadata
event loop that already processes all dimensions to perform the model load. 
This PR sets `RRDDIM_FLAG_ML_MODEL_LOAD` to the dimension that need ml model load. 
Additional code cleanup and switch to using a spinlock instead of mutex to queue / dequeue commands
=> Improve dimension ML model load

collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py
Fixes #16254 
Replaces `distutils.version` with `packaging.version` as suggested in https://peps.python.org/pep-0632/
Make sure python.d.plugin continues to work when it uses the `UrlService`.
</details>
=> Replace distutils with packaging for version

integrations/deploy.yaml
I think the Docker Swarm config should be the same as Docker Compose. The current version is missing some privileges and mounts from [Recommended Way](https://learn.netdata.cloud/docs/installing/docker#create-a-new-netdata-agent-container) => Docker Swarm install fails to resolve container names and monitor container network interfaces.
Fixes: #16307
</details>
=> update docker swarm deploy info

collectors/ebpf.plugin/ebpf_socket.c, libnetdata/ebpf/ebpf.c, libnetdata/ebpf/ebpf.h
On kernels where `tcp_v6_connect` is `static` it is not possible to monitor calls for this function and `socket` thread would not work. To avoid this issue, present with the last kernels, this PR adds a variable to store symbol type and load the trampoline/probe only when it is possible.
2. Access `Ebpf_socket` function and verify whether you have data.
- Which area of Netdata is affected by the change? eBPF.plugin
- Can they see the change or is it an under the hood? If they can see it, where? When they access socket plugin.
- How is the user impacted by the change? Avoid wrong initialization and chart without data.
- What are there any benefits of the change? …
=> `tcp_v6_connect` monitoring

database/sqlite/sqlite_functions.c
Perform recommended optimization before closing the metadata database. Refer to [sqlite analyze command](https://www.sqlite.org/lang_analyze.html) for details
=> Optimize database before agent shutdown

database/engine/journalfile.c
The internal journal file index would fail to add entries properly. This can lead to a crash during shutdown when the agent is compiled with NETDATA_INTERNAL_CHECKS
This could also affect queries
=> Fix journal file index when collision is detected

collectors/cgroups.plugin/cgroup-top.c
Due to configuration settings, some metrics may not be generated. This is true even for basic things like CPU and RAM, we can't assume they always exist.
</details>
=> fix: check for null rrdim in cgroup functions

collectors/proc.plugin/proc_net_dev.c
- highlight (yellow) interfaces with drops.
- rename the Name field to Interface.
- add Group By Type option.
</details>
=> Network-interfaces function small improvements

database/sqlite/sqlite_health.c, database/sqlite/sqlite_health.h, web/api/web_api_v1.c
When alarm_log is executed, keep the prepared statements to reused them in future calls to improve performance.
Check `/api/v1/alarm_log` before and after this PR (access.log)
eg.
Before
```
2023-11-02 15:23:56: 3: 183893 '[localhost]:35292' 'DATA' (sent/all = 127589/1405240 bytes -91%, prep/sent/total = 430.88/16.19/447.07 ms) 200 '/api/v1/alarm_log'
```
After
```
2023-11-02 15:29:07: 6: 202910 '[localhost]:51322' 'DATA' (sent/all = 128202/1403214 bytes -91%, prep/sent/total = 70.41/10.68/81.09 ms) 200 '/api/v1/alarm_log'
```
=> Keep precompiled statements for alarm log queries to improve performance

collectors/proc.plugin/plugin_proc.c, collectors/proc.plugin/proc_diskstats.c
Make sure the Block-devices function reports correct values and doesn't crash ND.
</details>
=> proc/diskstats: add block-devices function

collectors/proc.plugin/proc_net_dev.c
Add the field that indicates whether the network interface is used by a cgroup or by the host system.
Check UsedBy values.
</details>
=> network-interfaces function: add UsedBy field to 

system/systemd/netdata.service.in, system/systemd/netdata.service.v235.in
Services in After were added long before we implemented "autodetection_retry" in python.d/go.d. Not needed anymore.
Removing because for each of them systemd creates a non-found/inactive/dead service on every system.
Not needed.
</details>
=> cleanup systemd unit files After

database/rrdlabels.c
- Improve rrdlabels unittests
- Update the internal flags when copying from label set A to B 
- Set to `old` if the label already exists in B
=> Improve unittests

web/server/h2o/http_server.c
This adds `api/v2` support for h2o and as a result enables the new dashboard to work trough h2o.
Enable h2o, connect your browser to h2o port. Before this PR you cannot see new dashboard, after this PR it looks better.
</details>
=> h2o add api/v2 support

collectors/statsd.plugin/README.md, collectors/statsd.plugin/statsd.c
This PR adds an obsoletion functionality to statsd private charts. It attempts to address #16149 
A new configuration option is added called `set charts as obsolete after secs`. The default value is 0, which in this case statsd should operate as before. Setting the option to a number of seconds, statsd will set the private chart of the metric to obsolete after those seconds have passed since the last received metric and will stop updating the metric. The chart will be freed by the service thread, and the metrics from statsd.
Set the option `set charts as obsolete after secs` to a value, e.g. 60.
Start Netdata and start sending random metrics and values (e.g. using `echo "deploys.test.myservice_1:40|g" | nc -w 1 -u localhost 8125`).
Stop sending metrics and wait 60 seconds
Observe the …
=> Add an obsoletion time for statsd private charts

database/sqlite/sqlite_aclk_node.c, database/sqlite/sqlite_aclk_node.h
Currently the agent will send node update information as soon as possible after a child connects to the parent. This can cause inconsistencies if replication is still in progress. 
This change adds a check to make sure replication has finished before sending a node update information to the cloud
=> Improve agent to cloud status update process

collectors/statsd.plugin/statsd.c
After https://github.com/netdata/netdata/pull/16269 `rrdset_isnot_obsolete` and `rrdset_is_obsolete` need to be replaced by new versions.
CI
</details>
=> Replace rrdset_is_obsolete & rrdset_isnot_obsolete

collectors/cgroups.plugin/cgroup-charts.c
Bug introduced in #16314. `cgroup.throttled` and `cgroup.throttled_duration` charts have the same context. This PR fixes it.
Not needed
</details>
=> cgroups: fix throttle_duration chart context

collectors/cgroups.plugin/cgroup-charts.c, collectors/cgroups.plugin/cgroup-discovery.c, collectors/cgroups.plugin/cgroup-internals.h, collectors/cgroups.plugin/cgroup-top.c, collectors/cgroups.plugin/sys_fs_cgroup.c
This PR adds [pids/pids.current](https://www.kernel.org/doc/Documentation/cgroup-v1/pids.txt) metric to cgroups and systemd services.
It is `PIDS` value from `docker stats`.
```bash
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O     PIDS
57baa46ca32c   nd        5.14%     278.7MiB / 503.7GiB   0.05%     1.1MB / 570kB   3.81MB / 0B   117
```
Check that the new metric value ==  pids/pids.current (charts, functions). Check cgroup v1 and v2.
</details>
=> cgroups: collect pids/pids.current

docs/store/change-metrics-storage.md
Small mistake in the docs: 60 times a minute is not a minute again :)
Simply discovered it while reading the docs and got confussed
=> docs: Correct time unit for tier 2 explanation

collectors/systemd-journal.plugin/systemd-internals.h, collectors/systemd-journal.plugin/systemd-journal-annotations.c, collectors/systemd-journal.plugin/systemd-journal.c, collectors/systemd-journal.plugin/systemd-main.c
systemd has predefined message ids that are used to specify commonly used and interesting system events.
This PR adds `MESSAGE_ID` list which annotates the hex IDs with human readable descriptions.
=> use pre-configured message_ids to identify common logs

libnetdata/os.c
Noticed that ND incorrectly determines the number of cores when running in a container. In `netdata.conf` I see
```ini
[global]
```
[get_netdata_cpus()](https://github.com/netdata/netdata/blob/487e2b99676293b3e9d879d76bcefcd25bfc3ff7/daemon/common.c#L28):
```bash
2023-11-11 13:50:09: netdata INFO  : MAIN : System CPUs: 1, (system: 16, cgroups cpuset v1: 0, cgroups cpuset v2: 1, netdata.conf: 1)
```
Because `cpuset.cpus` is not really empty:
```bash
1 0 1 /sys/fs/cgroup/cpuset.cpus
```
Check `cpu cores` in netdata.conf.
</details>
=> skip spaces when reading cpuset

collectors/ebpf.plugin/ebpf.c, collectors/ebpf.plugin/ebpf.h, collectors/ebpf.plugin/ebpf_apps.c, collectors/ebpf.plugin/ebpf_apps.h, collectors/ebpf.plugin/ebpf_cachestat.c, collectors/ebpf.plugin/ebpf_cgroup.c, collectors/ebpf.plugin/ebpf_dcstat.c, collectors/ebpf.plugin/ebpf_dcstat.h, collectors/ebpf.plugin/ebpf_disk.c, collectors/ebpf.plugin/ebpf_fd.c, collectors/ebpf.plugin/ebpf_filesystem.c, collectors/ebpf.plugin/ebpf_hardirq.c, collectors/ebpf.plugin/ebpf_mdflush.c, collectors/ebpf.plugin/ebpf_mount.c, collectors/ebpf.plugin/ebpf_oomkill.c, collectors/ebpf.plugin/ebpf_process.c, collectors/ebpf.plugin/ebpf_shm.c, collectors/ebpf.plugin/ebpf_socket.c, collectors/ebpf.plugin/ebpf_socket.h, collectors/ebpf.plugin/ebpf_softirq.c, collectors/ebpf.plugin/ebpf_swap.c, collectors/ebpf.plugin/ebpf_sync.c, collectors/ebpf.plugin/ebpf_vfs.c, collectors/ebpf.plugin/metadata.yaml
Update eBPF charts to have same pattern used with apps.plugin.
1. Change your configuration file `/etc/netdata/ebpf.d.conf` to:
```sh
[global]
ebpf load mode = return
cachestat = yes
dcstat = yes
fd = yes
process = yes
shm = yes
socket = yes
swap = yes
vfs = yes
```
3. Start netdata confirming we have charts per app. You can also confirm this through our API accessing http://localhost:19999/api/v1/charts?all
- Can they see the change or is it an under the hood? If they can see it, where? Yes, now we won't have more one chart grouping apps data.
- How is the user impacted by the change? …
=> Split chars (eBPF <-> Apps integration)

web/api/formatters/rrdset2json.c
The old (v0) dashboard and custom dashboard use `charts.data_url` from `/api/v1/charts`.
Install, check the `/v0` endpoint.
</details>
=> fix v0 dashboard

integrations/deploy.yaml, packaging/docker/README.md
To sync the time with the host. This way the timestamp of the logs will reflect the host time.
Mount `/etc/loca/time`, and check the timestamp of the logs.
</details>
=> docker: mount /etc/localtime

collectors/cgroups.plugin/sys_fs_cgroup.c
=> fix "differ in signedness" warn in cgroup

collectors/ebpf.plugin/ebpf_oomkill.c, collectors/ebpf.plugin/ebpf_socket.c
@ilyam8  suggested three changes for eBPF plugin in this https://github.com/netdata/netdata/pull/16139#pullrequestreview-1718079096 PR. Two changes are addressed in this PR:
- Move OOMkill to bottom in memory family
- Move Net after disk on dashboard.
The third request will be addressed with PR https://github.com/netdata/netdata/pull/16030 .
1. Enable socket thread:
```sh
[global]
ebpf load mode = return
socket = yes
```
2. Compile branch and verify dashboard position
It is not necessary to test on different kernels.
- Can they see the change or is it an under the hood? If they can see it, where? Yes, when …
=> eBPF apps order

collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh, collectors/charts.d.plugin/apcupsd/metadata.yaml, health/health.d/apcupsd.conf
I propose to add a chart representing the status code from apcaccess.  Although there is currently a chart that checks the status code for certain conditions and determines if the apc is either online or not, i see value in having a granular chart so you know what the exact status is (i.e. you know when you need to replace the battery) 
the health check:   template: apcupsd_status_warning has the following line:
`     warn: $this == 1`
You can set it to be equal to zero to test out that warning sends an email
=> Add a apcupsd status code metric

database/sqlite/sqlite_health.c, libnetdata/buffer/buffer.c, libnetdata/buffer/buffer.h
Switch the alarm_log api endpoint to use the new buffer json functions.
The `/api/v1/alarm_log` endpoint output should be the same before and after this PR
=> Switch alarm_log to use the buffer json functions

collectors/python.d.plugin/adaptec_raid/adaptec_raid.chart.py
Fixes: #16394
Test using `arcconf GETCONFIG 1 PD` output from #16394.
</details>
=> adaptec_raid: fix parsing PD without NCQ status

web/server/web_client_cache.c
Fixes: #16410
The number of connected clients ("Netdata Web Clients") should be ~= (CONNECTED - DISCONNECTED) from `access.log`.
</details>
=> fix: don't count reused connections as new

web/api/formatters/rrdset2json.c
Fixes: #16415
@stelfrag if there is no reason to remove it, I think we need to keep it for now.
Check the chart titles using /v1 or /v0.
</details>
=> /api/v1/charts: bring back chart id to `title`

health/health_config.c
This PR suppresses errors from when loading alert config files that their alerts have been filtered with `enabled alarms` config option.
Filter an alarm with `enabled alarms` config option in health, e.g. `enabled alarms = !*ram* *`. Notice in error.log there are errors in the form `Health configuration at line 26 of file '/usr/lib/netdata/conf.d/health.d/windows.conf' has unknown key 'class'. Expected either 'alarm' or 'template'.
With this PR there should not be any errors.
</details>
=> Don't print errors from reading filtered alerts

packaging/installer/kickstart.sh, packaging/installer/methods/packages.md, packaging/repoconfig/debian/changelog, packaging/repoconfig/netdata-repo.spec
- Explicitly pull in EPEL on all systems where it’s required in kickstart.sh
- Explicitly depend on EPEL in our repository config packages for systems where it’s required.
- Document the requirement to use EPEL on these systems.
Resolves #16404
=> Improve handling around EPEL requirement for RPM packages.

libnetdata/socket/socket.c
It is possible to run multiple instances of ND and listen on the same port. This PR disables reusing TCP port.
Start 1+ Netdata instances and make sure only the one is running, the rest should fatal " Cannot listen on any API socket. Exiting...".
</details>
=> disable socket port reuse

collectors/proc.plugin/proc_net_dev.c, health/health.d/net.conf
This PR removes the variable network interface speed chart conversion to kilobits.
This fixes an issue where we are showing the wrong value on [interface_speed](https://github.com/netdata/netdata/blob/183a7fb84f85885a3d91f8e28d4e9780f964f659/health/health.d/net.conf#L7). That is 10G interface, should be 10000Mbit.
<details open>
<summary>screenshot</summary>
</details>
I've adjusted the alarms using interface_speed, we need to convert interface_speed to kilobits.
Check interface_speed value.
</details>
=> fix proc net dev: keep iface speed chart var in Mbits

health/REFERENCE.md
As mentioned in #15973, the docs in https://learn.netdata.cloud/docs/alerting/health-configuration-reference#alert-line-chart-labels have a lone backtick at the end.
</details>
=> Minor: Remove backtick from doc

daemon/main.c, packaging/docker/README.md
Fixes: #16396
Start docker container with/without mounted /host/etc/hostname and check the hostname in `/netdata.conf`.
</details>
=> docker: use /host/etc/hostname if mounted

packaging/installer/kickstart.sh
This adds a new option to the kickstart script called `--install-major-version` which allows the user to specify a particular major version of Netdata to attempt to install.
When this is used, it calls out to `https://repo.netdata.cloud/releases` to check what the latest published release for the requested major version is, and then proceeds as if the user had specified that version for the existing `--install-version` option and asked for auto-updates to be disabled.
If an issue is encountered when calling out to the release info URL, behavior is as follows:
- If running interactively, prompt the user with info about the error, and ask whether they want to abort the install or install the latest version overall instead.
- If running non-interactively and the failure was a result of the …
=> Add support for installing a specific major version of the agent on install.

collectors/proc.plugin/proc_net_dev.c, health/health.d/net.conf
Fixes https://github.com/netdata/netdata/pull/16418#issuecomment-1815985358
</details>
=> proc_net_dev: keep nic_speed_max in kilobits

collectors/systemd-journal.plugin/systemd-journal.c, collectors/systemd-journal.plugin/systemd-main.c, libnetdata/facets/facets.c, libnetdata/facets/facets.h
When dealing with very large journals, the dashboard can get quite slow.
This PR adds the ability the sample parts of the data to render the dashboard.
By default sampling has a target of about 1M log entries. The parameter `sampling:ENTRIES` is exposed for the UI to change this default.
- Sampling is activated at 50% of the target. So, as long as the number of lines are below 500k, 100% sampling is performed.
- The target is distributed like this:
- 50% of the target is used to trigger sampling. So, as long as the total number of events processed so far is below 50% of the target, sampling is disabled.
- 25% of the target is allocated to each journal file evenly, with a minimum of `last x 2` items (usually 200 x 2 = 400). So, as long the total number of events processed so far for each …
=> Journal sampling

collectors/systemd-journal.plugin/systemd-internals.h, collectors/systemd-journal.plugin/systemd-journal-files.c, collectors/systemd-journal.plugin/systemd-main.c
On very busy journal servers, the plugin times out while Netdata is waiting for it to start.
1. change the main loop of systemd-journal.plugin so that it registers functions before scanning files,
2. pings netdata while scanning files
3. allows only 1 scan at a time, so that functions execution will not stuck at updating the files registry.
=> journal startup

web/api/health/README.md
For example commands using curl in the health API documentation page I replaced the spaces with: %20
=> Doc change: Curl no longer supports spaces in the URL.

packaging/docker/Dockerfile
daemon.log was introduced in #16357
why this PR - see #15813
</details>
=> fix: link daemon.log to stderr in docker

libnetdata/log/README.md, libnetdata/log/log.h
This PR relaxes flood protection: period 3600 => 60. 3600 is huge.
Additionally, this PR improves logs readme by changing some lists into tables (better readability).
I think not needed because the only change is changing the ND_LOG_DEFAULT_THROTTLE_PERIOD define value.
</details>
=> log flood protection to 1000 log lines / 1 minute

.gitignore, collectors/cgroups.plugin/Makefile.am, collectors/cgroups.plugin/cgroup-name.sh.in, collectors/cgroups.plugin/cgroup-network-helper.sh.in, collectors/charts.d.plugin/charts.d.plugin.in, health/notifications/alarm-notify.sh.in
An alternative to #16453
This is needed for `systemd-cat-native` users:
- cgroup-name.sh
- cgroup-network-helper.sh
- charts.d.plugin
- alarm-notify.sh
</details>
=> add sbindir_POST to PATH of bash scripts that use `systemd-cat-native`

system/systemd/netdata.service.in, system/systemd/netdata.service.v235.in
This PR adds the [LogNamespace](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#LogNamespace=) setting to the ND systemd unit file. Netdata logs will go in the `netdata` journal namespace.
`journalctl --namespace=netdata`
</details>
=> add LogNamespace to systemd units

aclk/aclk.c, aclk/aclk.h, collectors/plugins.d/pluginsd_parser.c, collectors/plugins.d/pluginsd_parser.h, daemon/main.c, daemon/service.c, daemon/unit_test.c, database/rrd.h, database/rrdhost.c, database/sqlite/sqlite_aclk.c, database/sqlite/sqlite_aclk.h, health/health.c, health/health.h, streaming/receiver.c, streaming/stream.conf
Related #15868
---
- Add a new `cleanup ephemeral hosts after secs` config option under the `[db]` section
- Handle the `_is_ephemeral` host label on agent start
- Use the child's last connected time + ephemeral indication to decide if a node should be loaded on startup
- Node is loaded if `(current_time - last connected time)` < `ephemeral hosts after secs`
- New option in the stream.conf on the parent side, to indicate a node is ephemeral `is ephemeral node = yes | no` or `true | false`
- The ephemeral indication can be set on the child side under the `[global]` section (previously under `[health]`)  
The child will be eligible to go away after the specified number of seconds passes provided it is not connected.
=> Handle ephemeral hosts

collectors/charts.d.plugin/charts.d.plugin.in
Fixes: #16470
charts.d plugin tries to load wrong configuration files. Bug was introduced in #16357.
```log
Nov 24 12:19:55 pve-deb-work charts.d.plugin[1805163]: main: Configuration file '/opt/netdata/usr/lib/netdata/conf.d/charts.d.plugin.conf' not found.
Nov 24 12:19:55 pve-deb-work charts.d.plugin[1805168]: main: Configuration file '/opt/netdata/etc/netdata/charts.d.plugin.conf' not found.
```
Check charts.d plugin logs, make sure it load correct configuration files.
</details>
=> fix charts.d plugin loading configuration

libnetdata/log/log.c
Set the log every to prevent a flood of messages when error limit is specified
=> Fix error limit to respect the log every

Makefile.am, collectors/systemd-journal.plugin/systemd-internals.h, collectors/systemd-journal.plugin/systemd-journal-annotations.c, collectors/systemd-journal.plugin/systemd-journal-files.c, collectors/systemd-journal.plugin/systemd-journal-watcher.c, collectors/systemd-journal.plugin/systemd-journal.c, collectors/systemd-journal.plugin/systemd-main.c, libnetdata/datetime/rfc3339.c, libnetdata/datetime/rfc3339.h, libnetdata/facets/facets.c, libnetdata/libnetdata.h, libnetdata/log/log.c, libnetdata/log/systemd-cat-native.c, streaming/sender.c
=> journals management improvements

logsmanagement/circular_buffer.c, logsmanagement/db_api.c, logsmanagement/functions.c, logsmanagement/query.c, logsmanagement/query.h, logsmanagement/stress_test/run_stress_test.sh
This PR adds the ability to cancel logs management function calls.
Test that cancelling a logs-management function call can be performed either by timeout or by submitting a cancel request from the UI. 
</details>
=> logs-management: Add function cancellability

integrations/deploy.yaml, packaging/docker/README.md
Follow-up on #15823. This mount is needed for systemd-journal plugin.
Build a docker image, run it using the "recommended way", and check the "Systemd-journal" function.
</details>
=> add /var/log mount to docker

collectors/proc.plugin/proc_net_dev.c, daemon/common.h
We never remove sections for each network device in the config. This PR fixes it. Reported in https://github.com/netdata/netdata/issues/16412#issuecomment-1829590822.
- Start multiple docker containers.
- Stop/remove them.
- Check `[plugin:proc:/proc/net/dev:*`] sections in `/netdata.conf`. Shouldn't see any sections for veth* interfaces.
</details>
=> proc_net_dev: remove device config section

daemon/main.c, database/engine/rrdengine.c, database/engine/rrdengineapi.c
Wait for CTX_QUIESCE command to complete before attempting to finalize collection for all hosts
This may cause a report of collectors still running during shutdown, or a deadlock between the 
- flush_all_hot_and_dirty_pages_of_section_tp_worker
- rrdhost_finalize_collection
=> Fix occasional shutdown deadlock

collectors/plugins.d/pluginsd_parser.c, database/sqlite/sqlite_aclk.c, database/sqlite/sqlite_metadata.c, database/sqlite/sqlite_metadata.h
This PR adds support to clean chart labels when unregistering an ephemeral host.
=> When unregistering an ephemeral host, delete its chart labels

daemon/analytics.c
Check both parameters for NULL
Fixes CID 410152 [Dereference after null check]
=> Fix CID 410152 Dereference after null check

collectors/diskspace.plugin/plugin_diskspace.c, collectors/proc.plugin/proc_diskstats.c
This PR by default removes the creation of block devices and mount points configuration sections at runtime. If the section is added manually, all configuration options will be applied.
diskstats:
- check `[ plugin:proc:/proc/diskstats:*]` in `/netdata.conf` - shouldn't exist.
- add `[ plugin:proc:/proc/diskstats:*]` and set any block device option in `netdata.conf` - should be applied.
diskspace:
- check `[plugin:proc:diskspace:*]` in `/netdata.conf` - shouldn't exist.
- add `[plugin:proc:diskspace:*]` and set any mount point option in `netdata.conf` - should be applied.
</details>
=> diskspace/diskstats: don't create runtime disk config by default

collectors/proc.plugin/proc_net_dev.c
This PR by default removes the creation of network device configuration sections at runtime. If the section is added manually, all configuration options will be applied.
- check `[plugin:proc:/proc/net/dev:*]` in `/netdata.conf` - shouldn't exist.
- add `[plugin:proc:/proc/net/dev:*]` and set any network device option in `netdata.conf` - should be applied.
</details>
=> proc_net_dev: don't create runtime device config by default

aclk/aclk.c, collectors/proc.plugin/proc_diskstats.c, collectors/proc.plugin/proc_spl_kstat_zfs.c, libnetdata/procfile/procfile.c
This PR:
- `procfile_open()` uses info if the file doesn't exist instead of error. The caller should log an error if needed.
- ~ fix to zfs and diskstats collectors.
Restart netdata, check error level log/journal entries.
</details>
=> convert some error messages to info

database/sqlite/sqlite_metadata.c
* CID 410232:  Error handling issues  (CHECKED_RETURN)
/database/sqlite/sqlite_metadata.c: 1480 in start_metadata_hosts()
=> Resolve coverity issue 410232

Makefile.am, logsmanagement/README.md, logsmanagement/defaults.h, logsmanagement/file_info.h, logsmanagement/flb_plugin.c, logsmanagement/flb_plugin.h, logsmanagement/logsmanag_config.c, logsmanagement/logsmanagement.c, logsmanagement/stock_conf/logsmanagement.d.conf, logsmanagement/stock_conf/logsmanagement.d/default.conf, logsmanagement/stock_conf/logsmanagement.d/example_forward.conf, logsmanagement/stock_conf/logsmanagement.d/example_mqtt.conf, logsmanagement/stock_conf/logsmanagement.d/example_serial.conf, logsmanagement/stock_conf/logsmanagement.d/example_syslog.conf, logsmanagement/unit_test/unit_test.c
This PR adds the configuration option `# submit logs to system journal = no` to certain log sources, so that when enabled, logs from those sources will be submitted to the system journal once they are collected.
This option is _not_ mutually exclusive with the `db mode = full` option, so that collected logs can be both stored in the logs management DB and also be submitted to the system journal at the same time.
Also, some other minor changes:
1. There is some refactoring taking place in 
```
do{
switch(p_file_info->log_type){
case FLB_TAIL:
case FLB_WEB_LOG:
case FLB_SERIAL: 
.......
.......
}
```
that was using an `if / else` statements before.
2. The `prio_level` configuration option is added to `flb_kmsg` type logs.
3. A bug is fixed where the `min bytes` configuration option for …
=> logs-management: Add option to submit logs to system journal

packaging/installer/functions.sh
Because the Docker image doesn't have `wget`
Build docker image, and check netdata.conf.
</details>
=> add curl example to create_netdata_conf()

packaging/docker/README.md
ssia
Mount `/run/dbus` and check if systemd units monitoring works.
</details>
=> docs: add with-systemd-units-monitoring example to docker

collectors/apps.plugin/apps_plugin.c
ssia
See output using
```bash
./apps.plugin debug without-users without-groups 2>&1 | grep "has aggregated"
```
</details>
=> apps: fix "has aggregated" debug output

collectors/plugins.d/pluginsd_parser.c, daemon/buildinfo.c, daemon/main.c
There is no need to log system info variables on every start/restart (33 lines!). 
Additionally, this PR changes the "Function cancel" log message level to debug (discussed with ktsaou).
Not needed.
</details>
=> remove system info logging

collectors/python.d.plugin/python.d.plugin.in, collectors/python.d.plugin/python_modules/bases/FrameworkServices/SimpleService.py, collectors/python.d.plugin/python_modules/bases/loggers.py
Because journald adds the timestamp. The timestamp is only removed when stderr is connected to journald.
Before:
```bash
$ ndlogs --grep python.d
Nov 30 21:08:26 pve-deb-work netdata[1145877]: 2023-11-30 21:08:26: python.d INFO: plugin[main] : using python v3
Nov 30 21:08:28 pve-deb-work netdata[1145877]: 2023-11-30 21:08:28: python.d INFO: plugin[main] : '/opt/netdata/etc/netdata/python.d.conf' was not found
Nov 30 21:08:28 pve-deb-work netdata[1145877]: 2023-11-30 21:08:28: python.d INFO: plugin[main] : [adaptec_raid] is disabled by default, skipping it
```
After:
```bash
$ ndlogs --grep python.d
Nov 30 21:05:39 pve-deb-work netdata[1129911]: python.d INFO: plugin[main] : using python v3
Nov 30 21:05:41 pve-deb-work netdata[1129911]: python.d INFO: plugin[main] : …
```
=> python.d: logger: remove timestamp when logging to journald.

collectors/python.d.plugin/megacli/megacli.chart.py
As discussed with @ilyam8 on discord, this *temporarily* fixes the Issue of not being alerted about a `Partially Degraded` or `Failed` megacli raid array.
A correct fix would require rewriting bigger parts of this system, and is not an easy task, so this will be the best solution for the time being.
- Requires megacli and hardware raid
- Set raid state to failed or partially degraded (you can use `-PDOffline -PhysDrv [Enclosure:ID] -aN` to mark a disk as offline, which will cause either of the two, depending on your raid level, `-PDOnline` to bring it back up)
See Summary
- Megacli raid arrays are now also considered degraded if it is only partial, or fully failed
- Change will affect you only if you use that …
=> include more cases for megacli degraded state

libnetdata/log/log.c
When the log method is set to none, do not log anything.
=> log method = none is not respected

packaging/docker/Dockerfile
```cmd
$ docker exec nd-child-host6-1 ls -l /var/log/netdata
total 0
lrwxrwxrwx 1 netdata root    11 Dec  4 00:28 access.log -> /dev/stdout
-rw-r--r-- 1 netdata netdata  0 Dec  4 09:38 aclk.log
lrwxrwxrwx 1 netdata root    11 Dec  4 00:28 collector.log -> /dev/stdout
lrwxrwxrwx 1 netdata root    11 Dec  4 00:28 daemon.log -> /dev/stderr
lrwxrwxrwx 1 netdata root    11 Dec  4 00:28 debug.log -> /dev/stdout
lrwxrwxrwx 1 netdata root    11 Dec  4 00:28 error.log -> /dev/stderr
lrwxrwxrwx 1 netdata root    11 Dec  4 00:28 fluentbit.log -> /dev/stdout
lrwxrwxrwx 1 netdata root    11 Dec  4 00:28 health.log -> /dev/stdout
```
Not needed, the changes are straightforward.
</details>
=> link aclk.log to stdout in docker

collectors/apps.plugin/apps_plugin.c
Fixes the uptime metric for groups with 0 processes (`other` group).
Uptime of the `other` group with 0 processes should be 0, not == the host uptime.
</details>
=> apps: fix uptime for groups with 0 processes

daemon/main.c
SSIA.
- Enable netdata monitoring section.
- Start/stop the agent and wait in between by tinkering with the `[db] dbengine page type = raw|gorilla|...` options.
- Netadata monitoring section should display two additional gorilla charts when the gorilla page type is selected.
=> Add option to change page type for tier 0 to gorilla

database/engine/pdc.c
Suppress error such as
```
DBENGINE: metric 'b4789e58-f98c-4466-9652-fd8c16e57d72' loaded invalid page of type 2 from 1701843352 to 1701844375 (now 1701853367), update every 1, page length 3072, entries 1024 (flags: )
```
Pages with type 2 (gorilla compression) can be > 4096 bytes in multiples of GORILLA PAGE SIZE
=> Improve page validity check during database extent load

.github/workflows/monitor-releases.yml
Yesterday on the release, this workflow was skipped, probably due to the fact the the event trigger don't specify a branch, that's why I strongly believe that this PR will fix the issue 
CC @Ferroin
=> Fix release metadata workflow

daemon/analytics.c, daemon/main.c, system/Makefile.am
Fixes: #16511
I installed Netdata on FreeBSD using `netdata-installer.sh` and it failed to start `service netdata start`:
```cmd
time=2023-12-05T15:15:26.079+02:00 comm=netdata source=daemon level=alert errno="21, Is a directory" tid=100760  msg="Cannot create required directory '/'"
0x4684bc <netdata_logger_fatal+0x1ec> at /opt/netdata/usr/sbin/netdata
0x41ece3 <set_global_environment+0x1423> at /opt/netdata/usr/sbin/netdata
```
The problem is:
- main.c: on [this line](https://github.com/netdata/netdata/blob/6e049a523c3760c9f263a8469fdf3fb595b464cc/daemon/main.c#L1170-L1171) we set the home directory to the value of the “HOME” env var.
- analytics.c: on [this line](https://github.com/netdata/netdata/blob/6e049a523c3760c9f263a8469fdf3fb595b464cc/daemon/analytics.c#L845) we “verify” the …
=> set "HOME" after switching to netdata user

database/sqlite/sqlite_aclk.c, database/sqlite/sqlite_metadata.c
- Use at least one thread to do context load
- Check for uninitialized last connected timestamp on startup when creating archived hosts to prevent accidental removal when the host is also marked as ephemeral.
Fixes #16559
=> Resolve issue on startup in servers with 1 core

daemon/buildinfo.c
Fixes this issue in buildinfo
```
CPU Architecture ___________________________________________ : 33652752384
RAM Bytes __________________________________________________ : 214748364800
Disk Capacity ______________________________________________ : x86_64
```
</details>
=> fix cpu arch/ram/disk values in buildinfo

database/sqlite/sqlite_metadata.c
There is a memory leak that can occur if during an ephemeral host (child) chart label cleanup the host happens to reconnect.
=> Fix memory leak during host chart label cleanup

collectors/debugfs.plugin/debugfs_plugin.c
debugfs.plugin doesn't exit if you:
- Start Netdata manually.
- kill -9 $(pidof netdata)
This PR fixes it. 
Start Netdata manually, kill the main Netdata process, and make sure debugfs exits. I tested both from source and static installs.
</details>
=> make debugfs exit on sigpipe

database/engine/cache.c, database/engine/cache.h, database/engine/journalfile.c, database/engine/metric.c, database/engine/metric.h, database/engine/pagecache.c, database/engine/pagecache.h, database/engine/pdc.c, database/engine/rrdengine.h, database/engine/rrdengineapi.c
Update every is stored as uint32_t. This PR touches places where it is treated as time_t and converted back and forth to uint32_t causing coverity warnings. Some fields in structures have been changed to reduce memory usage as well.
=> Handle coverity issues related to Y2K38_SAFETY

.github/workflows/monitor-releases.yml, collectors/debugfs.plugin/debugfs_plugin.c, collectors/log2journal/README.md, collectors/proc.plugin/sys_class_drm.c, contrib/debian/netdata-plugin-perf.postinst, daemon/analytics.c, daemon/buildinfo.c, daemon/main.c, database/sqlite/sqlite_aclk.c, database/sqlite/sqlite_metadata.c, libnetdata/Makefile.am, libnetdata/gorilla/README.md, netdata.spec.in, packaging/installer/netdata-uninstaller.sh, system/Makefile.am
- uninstaller remove log2journal and systemd-cat-native (#16585)
- Change the workflow on how we set the right permissions for perf-plugin (#16558)
- make debugfs exit on sigpipe (#16569)
- Fix memory leak during host chart label cleanup (#16568)
- fix cpu arch/ram/disk values in buildinfo (#16567)
- Resolve issue on startup in servers with 1 core (#16565)
- Fix for AMD GPU drm different format proc file (#16561)
- set "HOME" after switching to netdata user (#16548)
- Fix release metadata workflow (#16563)
- Make  the systemd-journal mandatory package on Centos 7 and Amazon linux 2 (#16562)
- Update README.md
- Add README for gorilla (#16553)
=> Patch release 1.44.1

collectors/proc.plugin/proc_interrupts.c, collectors/proc.plugin/proc_net_softnet_stat.c, collectors/proc.plugin/proc_softirqs.c, collectors/proc.plugin/proc_stat.c
As announced in the [v1.44.0 release notes](https://github.com/netdata/netdata/releases/tag/v1.44.0#v1440-deprecation-notice), this PR disables per core CPU metrics by default. This change enhances performance and resource utilization.  Summary (per-system) metrics are still collected. 
Check per core metrics, should be disabled by default.
</details>
=> disable cpu per core metrics by default

integrations/cloud-notifications/metadata.yaml
use black version icon for Splunk in order to make it visible on learn website
=> fix: use black version icon for Splunk in order to make it visible

netdata-installer.sh
It guarantees:
- doesn't add duplicate entry.
- disables the feature before enabling it and vice versa.
ci, manual tests
</details>
=> improve enable_feature function in the installer

netdata-installer.sh
Generating web/gui/version.txt wasn't implemented in the cmake PR [because wontfix](https://github.com/netdata/netdata/issues/16573).
Not needed
</details>
=> remove v1 dashboard version check from installer

claim/claim.c
* CID 405078: Waiting while holding a lock
Release lock earlier to resolve this
=> Fix small coverity issue

packaging/installer/netdata-updater.sh
* Use curl -f so that non-existent URL is treated as failure
* Use uname -m for default arch when PREBUILT_ARCH is missing in .install-type
Not included
See #16609
=> Robustness improvements to netdata-updater.sh

collectors/freebsd.plugin/plugin_freebsd.c, daemon/analytics.c, daemon/analytics.h, daemon/commands.c, daemon/daemon.h, daemon/main.c, daemon/main.h, daemon/signals.c, exporting/exporting_engine.c, exporting/init_connectors.c, libnetdata/libnetdata.h, libnetdata/log/log.c, libnetdata/required_dummies.h, libnetdata/threads/threads.h, streaming/rrdpush.h, web/server/web_client.c
libnetdata ended up using the header daemon/main.h.
This commit tries to resolve this issue by:
- Moving the thread tags under libnetdata/threads/threads.h
- Dropping the definition of `send_analytics` from libnetdata/ and, thus, the requirement for an extra dummy function.
- Adding a new analytics_statistic_send() function.
- Changing netdata_cleanup_and_exit() to accept the raw parts of an analytics statistic.
After this whole ordeal, only the declaration of netdata_cleanup_and_exit() is required from libnetdata/
- CI jobs
- Start/stop the agent.
=> Remove includes outside of libnetdata.

.gitignore, collectors/xenstat.plugin/xenstat_plugin.c, database/engine/metric.c, database/engine/rrdenginelib.h, libnetdata/libjudy/src/JudyL/JudyLCascade.c, libnetdata/libjudy/src/JudyL/JudyLDecascade.c, libnetdata/libjudy/src/JudyL/JudyLDel.c, libnetdata/libjudy/src/JudyL/JudyLGet.c, libnetdata/libjudy/src/JudyL/JudyLIns.c, libnetdata/storage_number/storage_number.h, streaming/compression.h
Fix issues reported with `-fsanitize=undefined`:
- One unaligned load and store when checking DBEngine's CRCs,
- One unaligned load when computing the partition of a metric.
- A couple shifts of signed literals touching the sign bit.
Disabled annotations of `libjudy`.
- CI jobs.
=> Fix UB of unaligned loads/stores and signed shifts.

CMakeLists.txt
This fixes most of the scripts installed by cmake so that they correctly have execute permissions.
We need to do more work than just this (such as properly handling the SUID bit), but this is a solid starting point.
Install the agent using the updated code from this PR and check that scripts have the correct permissions.
=> Correctly handle basic permissions for most scripts on install.

CMakeLists.txt, contrib/debian/rules, web/gui/cmake_dashboard_v1.py, web/gui/cmake_dashboard_v2.py, web/gui/v1/dashboard_v1.cmake, web/gui/v2/dashboard_v2.cmake
Fixes: #16626
Closes: #16633
- Build/install debian package and check web dir: must be `/var/lib/netdata/www`
- Install from source and check web dir: 
- with a prefix, must be `/opt/netdata/usr/share/netdata/web`
- without prefix, must be `/usr/share/netdata/web`
</details>
=> cmake: make WEB_DIR configurable

daemon/global_statistics.c, daemon/main.c
Fix a compilation error when trying to compile without dbengine (`--disable-dbengine`) . 
This PR disables the failing statistics and internal page generation tests
Fixes #16643
=> Fix compilation error when using --disable-dbengine

packaging/installer/kickstart.sh
This should help resolve some issues we have with installing when dealing with unclean caches after dist-upgrades.
Actually testing this properly requires manually populating the APT cache of a Debian or Ubuntu system with an incorrect repository config package prior to attempting to install Netdata on the system.
Without this fix, the incorrect package will be what gets installed, and installing with native packages will fail.
With this fix, the correct package should be installed, and installing with native packages should succeed.
=> Remove Netdata packages from APT cache when attempting to install.

database/engine/rrdenginelib.h
- Prevent memory corruption by storing sizeof(uint32_t) instead of sizeof(uLong)
=> Fix overrun in crc32set

web/server/web_client.c, web/server/web_client.h
=> dont exceed buffer boundaries, when the buffer is empty

database/rrdset.c
These messages [confuse users](https://discord.com/channels/847502280503590932/1188118914362781787/1188118914362781787) and don't provide any value.
n/a
</details>
=> set log level of too-old-data message to debug 

exporting/send_internal_metrics.c, exporting/tests/test_exporting_engine.c, health/health.d/exporting.conf
=> fix exporting internal charts context and family

daemon/daemon.c
macOS's `dirname(3)` does not modify passed string.
This PR fixes a bug in Netdata's handling of `dirname()` on macOS.  Netdata can now correctly find the `netdata-claim.sh` script (which is located in the same directory as the main executable). 
Claim Netdata via UI on macOS.
</details>
=> fix claiming on macOS

database/engine/metric.c
Prevent fatal conditions with message: `METRIC: refcount is 0 (zero or negative) during release`
=> atomically load the metric reference count

packaging/makeself/jobs/70-netdata-git.install.sh
Building logs-management always fails. This PR disables it for static build to avoid wasting time on ci and when building locally.
<details>
<summary>build error</summary>
```c
[100%] Linking C shared library ../lib/libfluent-bit.so
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /openssl-static/lib64/libcrypto.a(libcrypto-lib-v3_genn.o): warning: relocation against `d2i_GENERAL_NAME' in read-only section `.text'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /openssl-static/lib64/libssl.a(libssl-lib-s3_lib.o): relocation R_X86_64_PC32 against symbol `tls12downgrade' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linu …
```
=> add --disable-logsmanagement when building static

system/install-service.sh.in, system/launchd/netdata.plist.in
Fixes: #13829
Fixes: #12578
This PR fixes 2 issues on macOS:
- installing the `netdata.plist` file. 
```bash
Installing macOS plist file for launchd.
install: system/launchd/netdata.plist: No such file or directory
ERROR: Failed to copy plist file.
```
- Stop Netdata service using `launchctl`.
- Install Netdata on macOS using `netdata-installer.sh`.
- Start/stop Netdata using `launchctl`.
</details>
=> fix installing service file and start/stop ND using `launchctl` on macOS

.github/data/distros.yml
Specifically, record the information required for them to be handled correctly by our native package repositories.
This will require a separate update to the tooling managing the repos before it actually takes effect.
n/a
First half of a fix for #16707.
=> Add info to distros.yml for handling of legacy platforms.

libnetdata/clocks/clocks.c
Closes: #16710
netdata reads the system's clock resolution to understand the steps it should pause to synchronize data collection.
On some systems `clock_getres()` is broken. It either returns an error, or it returns invalid values.
Now netdata checks that `clock_getres()` returns success and also that the the value in usec is bigger than zero and less than 10ms.
If successful, it rounds the clock precision in usec and returns it back. Resolutions smaller than 1 usec are rounded to 1 usec.
If unsuccessful, it returns the default clock resolution of 1ms.
=> fix clock resolution detection

.github/workflows/kickstart-upload.yml
This will be used for hosting of the script going forwards. Further changes will need to happen on the system itself to put the script in the right place and ensure it gets served properly.
The initial upload should happen automatically once this PR is merged. Subsequent uploads will happen either when teh workflow is updated or when the kickstart script itself is updated.
n/a
=> Add GHA workflow to upload kickstart script to our repo server.

collectors/cgroups.plugin/sys_fs_cgroup.c
I changed the global `update_every` to 10 and noticed that it takes a while to discover cgroups: 100 seconds. 
This PR changes the default `check for new cgroups every` value: it is 10 seconds if `update_every` < 10 or equal to `update_every`.
Not needed.
</details>
=> cgroups: don't multiply cgroup_check_for_new_every by update_every

collectors/cgroups.plugin/cgroup-discovery.c
The issue is [reported on Discord](https://discord.com/channels/847502280503590932/1191216299477585981/1192775743642542101).
After this PR the message will be logged only once per hour.
ci
</details>
=> fix excessive "maximum number of cgroups reached" log messages

collectors/proc.plugin/proc_stat.c
The issue is [reported on Discord](https://discord.com/channels/847502280503590932/1192515472151826534/1192515472151826534).
CPU core utilization metrics were disabled in #16572. As it turned out, all other per-core metrics (including frequency) depend on it - if it is disabled, then so are the others. This PR fixes it.
Keep CPU per-core utilization disabled, enable other per-core metrics, and make sure they work.
</details>
=> fix missing CPU frequency

system/netdata.conf
This PR removes all (outdated) configuration options from the `netdata.conf` file used for native packages (deb, rpm), the only data left is comments that explain how to get the latest version of the file. We have such `netdata.conf` in Docker images.
This file:
- contains outdated configuration (db settings in `[global]`) which of course [confuses for users](https://community.netdata.cloud/t/reduce-memory-footprint-of-netdata-agent/5026#what-i-expected-to-happen-4).
- contains just a few settings which is a [known problem](https://github.com/netdata/netdata/issues/12404) but it doesn't look like it will get fixed.
- contains uncommented settings which is a problem because we won't be able to change them for existing installs (e.g. we plan to change dbengine tiers disk space).
The lack of …
=> update default netdata.conf used for native packages

collectors/all.h
[Reported on Discord](https://discord.com/channels/847502280503590932/1192515472151826534/1194678175024824482).
This is necessary to ensure that the CPU section is second on the dashboard regardless of the enabled/disabled collector.
Not needed.
</details>
=> fix cpu per core charts priority

daemon/global_statistics.c, daemon/service.c, daemon/unit_test.c, database/contexts/api_v2.c, database/contexts/query_target.c, database/contexts/rrdcontext.h, database/contexts/worker.c, database/engine/rrdengineapi.c, database/engine/rrdengineapi.h, database/ram/rrddim_mem.c, database/ram/rrddim_mem.h, database/rrd.h, database/rrddim.c, database/rrdhost.c, database/rrdset.c, database/storage_engine.c, exporting/process_data.c, exporting/tests/netdata_doubles.c, exporting/tests/test_exporting_engine.h, ml/ml.cc, streaming/replication.c, web/api/queries/query.c
- `STORAGE_INSTANCE` -> `si`
- `STORAGE_METRIC_GROUP` -> `smg`
- `STORAGE_METRIC_HANDLE` -> `smh`
- `STORAGE_COLLECT_HANDLE` -> `sch`
- `STORAGE_ENGINE_BACKEND` -> `seb`
- `STORAGE_ENGINE_QUERY_HANDLE` -> `seqh`
Various different variable and struct field names were used for the same entity. With this PR we have a consistent naming pattern for variables and fields across the entire code base for storage engines.
- CI jobs.
=> Name storage engine variables consistently.

contrib/debian/netdata-plugin-go.postinst, netdata-installer.sh, netdata.spec.in, packaging/makeself/install-or-update.sh
Needed for [go.d/filecheck](https://github.com/netdata/go.d.plugin/tree/master/modules/filecheck#readme).
Install and check go.d.plugin capabilities:
- deb package
- rpm package
- static build
- from source
</details>
=> packaging: add cap_dac_read_search to go.d.plugin

libnetdata/query_progress/progress.c
The json output of progress queries, now includes the timestamps.
=> report timestamps with progress

database/rrdlabels.c, libnetdata/buffer/buffer.h, libnetdata/dictionary/dictionary.c, libnetdata/log/log.c
=> Fix sanitizer errors
