netdata/netdata

collectors/python.d.plugin/beanstalk/metadata.yaml
collectors/python.d.plugin/bind_rndc/bind_rndc.conf
collectors/python.d.plugin/bind_rndc/metadata.yaml
collectors/python.d.plugin/boinc/metadata.yaml
collectors/python.d.plugin/exim/metadata.yaml
collectors/python.d.plugin/gearman/gearman.conf
collectors/python.d.plugin/gearman/metadata.yaml
collectors/python.d.plugin/go_expvar/metadata.yaml
collectors/python.d.plugin/litespeed/metadata.yaml
collectors/python.d.plugin/retroshare/metadata.yaml
collectors/python.d.plugin/w1sensor/metadata.yaml
collectors/python.d.plugin/w1sensor/w1sensor.conf

Update metadata.yaml for some python collectors - 2

---

collectors/apps.plugin/multi_metadata.yaml
collectors/cgroups.plugin/multi_metadata.yaml
collectors/debugfs.plugin/multi_metadata.yaml
collectors/ebpf.plugin/multi_metadata.yaml
collectors/freebsd.plugin/multi_metadata.yaml
collectors/idlejitter.plugin/metadata.yaml
collectors/macos.plugin/multi_metadata.yaml
collectors/nfacct.plugin/metadata.yaml
collectors/proc.plugin/multi_metadata.yaml

fix schema validation for some meta files

---

integrations/deploy.yaml

Fixed deployment commands for Docker, Kubernetes and Linux

---

collectors/timex.plugin/metadata.yaml

Add description for `tc`  plugin.
</details>

Timex yaml update

---

collectors/ioping.plugin/metadata.yaml

Add description for `ioping`  plugin.
</details>

Update ioping yaml

---

collectors/xenstat.plugin/metadata.yaml

Add description for `xenstat`  plugin.
</details>

Xen yaml update

---

exporting/opentsdb/metadata.yaml

Creating the first exporter metadata (will add the rest if this looks good)
</details>

Create metadata.yaml for OpenTSDB Exporter

---

collectors/proc.plugin/multi_metadata.yaml

Update icon for power supply

---

collectors/python.d.plugin/adaptec_raid/metadata.yaml
collectors/python.d.plugin/ipfs/metadata.yaml
collectors/python.d.plugin/megacli/metadata.yaml
collectors/python.d.plugin/openldap/metadata.yaml
collectors/python.d.plugin/oracledb/metadata.yaml
collectors/python.d.plugin/riakkv/metadata.yaml
collectors/python.d.plugin/tomcat/metadata.yaml
collectors/python.d.plugin/uwsgi/metadata.yaml

WIP, open for comments
- Adaptec Raid controller
- Apache Tomcat
- OpenLDAP
- megacli
- oracledb
- riakkv
- uwsgi
- ipfs
</details>

Update metadata for multiple python collectors.

---

collectors/slabinfo.plugin/metadata.yaml

Updating the icon which is not rendered currently.

Update Slabinfo Logo

---

exporting/mongodb/metadata.yaml

Create metadata.yaml for MongoDB exporter

Create metadata.yaml for MongoDB exporter

---

exporting/aws_kinesis/metadata.yaml

Create metadata.yaml for AWS kinesis exporter

Create metadata.yaml for AWS kinesis exporter

---

exporting/pubsub/metadata.yaml

Create metadata.yaml for Google PubSub exporter

Create metadata.yaml for Google PubSub exporter

---

exporting/graphite/multi_metadata.yaml

Create multi_metadata.yaml for graphite exporters

---

collectors/COLLECTORS.md

Change nvidia_smi link to go version in COLLECTORS.md

---

collectors/tc.plugin/metadata.yaml

Add description for `tc`  plugin.
</details>

TC yaml update

---

collectors/ebpf.plugin/multi_metadata.yaml

This PR brings upates for eBPF yaml file.
1. Check CI, grammar and format.
</details>

eBPF Yaml complement

---

health/notifications/alerta/metadata.yaml

@Ferroin : I have added a sample Notifications metadata.yaml. Can you review please?

Added a sample metadata.yaml for Alerta

---

collectors/cups.plugin/metadata.yaml

Add description for `tc`  plugin.
</details>

CUPS yaml update

---

integrations/deploy.yaml

Updated icons in deploy section

Updated icons in deploy section

---

collectors/python.d.plugin/tomcat/metadata.yaml

Tomcat meta doesn't pass schema validation, this PR fixes it.
</details>

fix tomcat meta

---

collectors/python.d.plugin/pandas/metadata.yaml
collectors/python.d.plugin/pandas/pandas.conf

update pandas collector metadata

---

collectors/python.d.plugin/zscores/metadata.yaml

Update zscores metadata yaml

---

collectors/python.d.plugin/sensors/metadata.yaml

Update python sensors metadata yaml

---

collectors/python.d.plugin/dovecot/metadata.yaml
collectors/python.d.plugin/gearman/metadata.yaml
collectors/python.d.plugin/icecast/metadata.yaml
collectors/python.d.plugin/postfix/metadata.yaml
collectors/python.d.plugin/puppet/metadata.yaml
integrations/deploy.yaml

Reviewed icons for integrations across these categories
</details>

reviewed icos for a bunch of integrations

---

.yamllint.yml

It is better than adding comments to every metadata file. We don't follow this rule, so disabling it.
</details>

ci disable yamllint line-length check

---

collectors/python.d.plugin/anomalies/metadata.yaml

- this file is commented out as users are reccomended to use the native anomaly detection capabilities on the agent instead.
</details>

comment out anomalies metadata and add note

---

collectors/charts.d.plugin/ap/metadata.yaml
collectors/charts.d.plugin/apcupsd/metadata.yaml
collectors/charts.d.plugin/libreswan/metadata.yaml
collectors/charts.d.plugin/nut/metadata.yaml
collectors/charts.d.plugin/opensips/metadata.yaml
collectors/charts.d.plugin/sensors/metadata.yaml

Updates the metadata.yaml for charts.d modules.
</details>

Update metadata.yaml for charts.d collectors

---

collectors/python.d.plugin/memcached/metadata.yaml
collectors/python.d.plugin/oracledb/metadata.yaml

fix icons for db integrations

---

collectors/python.d.plugin/tomcat/metadata.yaml
collectors/python.d.plugin/uwsgi/metadata.yaml
collectors/python.d.plugin/varnish/metadata.yaml

fix icons for webservers integrations

---

collectors/python.d.plugin/beanstalk/metadata.yaml

fix icons for message brokers and hardware
</details>

fix icons for message brokers and hardware

---

integrations/cloud-notifications/metadata.yaml

Updated all cloud notifications except generic webhook

---

collectors/macos.plugin/multi_metadata.yaml

Add description for `mac`  plugin.
</details>

Macos yaml update

---

collectors/freebsd.plugin/multi_metadata.yaml

Add description for `freebsd`  plugin.
</details>

FreeBSD yaml update

---

integrations/schemas/notification.json

Consists of an optional mapping with keys for each section that might be displayed.
n/a

Add key for notifications to control what global config options get displayed

---

collectors/cgroups.plugin/multi_metadata.yaml
collectors/charts.d.plugin/apcupsd/metadata.yaml
collectors/python.d.plugin/adaptec_raid/metadata.yaml
collectors/python.d.plugin/ceph/metadata.yaml
collectors/python.d.plugin/hpssa/metadata.yaml
collectors/python.d.plugin/ipfs/metadata.yaml
collectors/python.d.plugin/samba/metadata.yaml
collectors/python.d.plugin/tor/metadata.yaml

review images for integrations from security to windows systems

---

collectors/debugfs.plugin/multi_metadata.yaml

Add description for `debugfs`  plugin.
</details>

Debugfs yaml update

---

exporting/prometheus/metadata.yaml

Fixed the issue with the schema (I guess).

The icon_filename value was not in quotes - Fixed

---

exporting/graphite/metadata.yaml

Update graphite metadata.yaml

---

collectors/python.d.plugin/alarms/metadata.yaml
collectors/python.d.plugin/example/metadata.yaml

Fix name in the yaml of example python collector

---

integrations/schemas/exporter.json

Fix exporter schema to support multiple entries per file.

---

integrations/categories.yaml

Add data-collection.notifications for some prometheus endpoints.

Update categories.yaml to add notifications

---

README.md

A few fixes to the readme file:
- format "What's New" table (unreadable as it was when open in IDE)
- small spelling fixes
</details>

small improvements to README.md

---

collectors/freeipmi.plugin/freeipmi_plugin.c

Fixes: #15662
Not needed
</details>

freeipmi change restart message to info

---

health/notifications/awssns/metadata.yaml

Fixing tables (aws sns)

---

health/notifications/custom/metadata.yaml

Fix table formatting (custom exporter)

Fix table formatting (custom exporter)

---

health/notifications/alerta/metadata.yaml
health/notifications/awssns/metadata.yaml
health/notifications/custom/metadata.yaml
health/notifications/discord/metadata.yaml
health/notifications/dynatrace/metadata.yaml
health/notifications/email/metadata.yaml
health/notifications/flock/metadata.yaml
health/notifications/irc/metadata.yaml
health/notifications/kavenegar/metadata.yaml
health/notifications/matrix/metadata.yaml
health/notifications/messagebird/metadata.yaml
health/notifications/msteams/metadata.yaml
health/notifications/ntfy/metadata.yaml
health/notifications/pagerduty/metadata.yaml
health/notifications/prowl/metadata.yaml
health/notifications/pushbullet/metadata.yaml
health/notifications/pushover/metadata.yaml
health/notifications/rocketchat/metadata.yaml
health/notifications/smstools3/metadata.yaml
health/notifications/syslog/metadata.yaml
health/notifications/telegram/metadata.yaml
health/notifications/twilio/metadata.yaml

Fix formatting

---

collectors/macos.plugin/metadata.yaml
integrations/deploy.yaml

meta MacOS => macOS

---

integrations/cloud-notifications/metadata.yaml

Update Webhook icon

---

packaging/docker/run.sh

fix: 🐛 docker bind-mount stock files creation

---

libnetdata/ebpf/ebpf.h

Fixes https://github.com/netdata/netdata/issues/15667
</details>

Extend eBPF default shutdown

---

.vscode/settings.json

update vscode yaml schemas association

---

collectors/python.d.plugin/beanstalk/metadata.yaml

Fix typo in categories for beanstalk collector metadata.

---

integrations/deploy.yaml

integrations: fix docker compose indent

---

integrations/deploy.yaml

fix meta deploy docker swarm NC env var

---

libnetdata/dyn_conf/dyn_conf.c
libnetdata/dyn_conf/dyn_conf.h
web/api/web_api_v2.c

fix the freez pointer of dyncfg

---

collectors/systemd-journal.plugin/systemd-journal.c

Check if SD_JOURNAL_ALL_NAMESPACES exists / fallback to SD_JOURNAL_LOCAL

Adjust namespace used for sd_journal_open

---

.gitignore

add systemd-journal.plugin to gitignore

---

integrations/templates/alerts.md
integrations/templates/metrics.md
integrations/templates/setup.md

I think it makes it easier to read, compare
<details>
<summary>Current</summary>
</details>
<details>
<summary>New</summary>
</details>
<details>
<summary>Current</summary>
</details>
<details>
<summary>New</summary>
</details>
<details>
<summary>Current</summary>
</details>
<details>
<summary>New</summary>
</details>
</details>

meta: align left metrics, alerts, and config options

---

collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py

Fixes: #15755
Tested by @TitanLabs-ai in https://github.com/netdata/netdata/issues/15755#issuecomment-1668011538
</details>

fix nvidia_smi power_readings for new drivers

---

collectors/proc.plugin/metadata.yaml

meta update proc drm icon

---

aclk/https_client.c

Name is self-explanatory. 
</details>

Fix CID 398318

---

collectors/proc.plugin/sys_class_drm.c
libnetdata/inlined.h

SSIA
- @thiagoftsm I'll need your help to run coverity locally and confirm this PR fixes the issues. 
- This one here: 
```
*** CID 398325:  Memory - illegal accesses  (INCOMPATIBLE_CAST)
/collectors/proc.plugin/sys_class_drm.c: 857 in do_sys_class_drm()
851                         collector_error("Cannot read asic_id from '%s'", filename);
852                         card_free(c);
853                         continue;
854                     }
855    
856                     snprintfz(filename, FILENAME_MAX, "%s/%s", c->pathname, "device/revision");
>>>     CID 398325:  Memory - illegal accesses  (INCOMPATIBLE_CAST)
>>>     Pointer "&c->id.pci_rev_id" points to an object whose effective type is "unsigned int" (32 bits, unsigned) but is dereferenced as a wider "unsigned long long" (64 …
```

Fix coverity issues introduced via drm proc module

---

.codacy.yml

ci: codacy exclude web/gui/v2/

---

packaging/docker/README.md

fix docker-compose example

---

collectors/plugins.d/pluginsd_parser.c
libnetdata/dyn_conf/dyn_conf.h
web/api/web_api_v2.c

small fixes of errors in code in master which were found during streaming support development
</details>

minor Dyncfg mvp0 fixes

---

collectors/python.d.plugin/hpssa/hpssa.chart.py

Fixes: #15792
Not needed.
</details>

fix hpssa handle unassigned drives

---

collectors/nfacct.plugin/plugin_nfacct.c

nfacct.plugin increase restart time from 4 hours to 1 day

---

web/gui/Makefile.am
web/gui/ilove.html

added ilove.html

---

.github/data/distros.yml
.github/scripts/ci-support-pkgs.sh
.github/scripts/pkg-test.sh
packaging/installer/install-required-packages.sh
packaging/installer/kickstart.sh
packaging/installer/netdata-updater.sh

Containers added https://github.com/netdata/helper-images/pull/219

Added CentOS-Stream to distros

---

packaging/makeself/jobs/20-openssl.install.sh

fix packaging static build openssl 32bit

---

ml/Config.cc
ml/ml-private.h
ml/ml.cc

Models for dimensions that are not actively trained should be deleted after some time. This PR adds support for deleting these models from each thaining thread, if they are older than one week.
- CI jobs

Unconditionally delete very old models.

---

collectors/all.h
ml/ad_charts.cc
ml/ml-private.h
ml/ml.cc

Adds a new chart that groups the anomaly rate of dimensions based on the chart's type.
- CI jobs
- ML VMs

Add a chart that groups anomaly rate by chart type.

---

ml/README.md

ssia. 
- small docs task to add new param introduced to ML here: https://github.com/netdata/netdata/pull/15720
- very unlikely anyone would want to change defaults but just documenting it regardless.
</details>

ML add new `delete old models param` to readme

---

database/sqlite/sqlite3.h

- Version update to 3.42.0
- Suppress a compilation warning

Update SQLITE version to 3.42.0

---

database/sqlite/sqlite_metadata.c

There is a race condition during shutdown which may result in an agent waiting forever the "metadata" thread
to complete a host scan.
In the case of the race condition, the agent would have something like the following in the logfile
```
2023-09-01 14:00:13: netdata INFO  : MAIN : METADATA: Sending a scan host command
2023-09-01 14:00:13: netdata INFO  : MAIN : METADATA: Waiting for host scan completion
```
and then wait forever. 
During shutdown a final "host scan" command is scheduled to make sure all metadata is stored. If a "host scan" is already in progress this may result in this race condition. 
This PR addresses this issue.

Improve shutdown of the metadata thread

---

packaging/docker/Dockerfile

- Drop old, pointless comments.
- Reorganize so that invariant layers are first, making build caching more efficient.
Docker CI passes on this PR.

Assorted Dockerfile cleanup.

---

packaging/installer/README.md
packaging/installer/UPDATE.md

Also includes suggestions for workarounds, in order of preference.
n/a
Resolves: #15877

Properly document issues with installing on hosts without IPv4.

---

README.md
docs/category-overview-pages/accessing-netdata-dashboards.md
web/gui/README.md

Fixes: #15924
Added information on how to access the dashboards based on some feedback we got [here](https://github.com/netdata/netdata-cloud/issues/912)
</details>

add specific info on how to access the dashboards

---

exporting/prometheus/prometheus.c
exporting/send_data.c
libnetdata/socket/security.c

Patch release 1.42.3

---

collectors/python.d.plugin/go_expvar/metadata.yaml
collectors/python.d.plugin/hpssa/metadata.yaml
collectors/python.d.plugin/tor/metadata.yaml

Adds notes to enable the collectors.
</details>

Integrations: Add a note to enable the collectors

---

collectors/systemd-journal.plugin/systemd-journal.c
libnetdata/clocks/clocks.h
libnetdata/facets/facets.c
libnetdata/facets/facets.h

facets optimizations

---

collectors/cups.plugin/metadata.yaml

We split plugins from main netdata package, so I am adding  a missing description for cups.
1. See grammar.
- Which area of Netdata is affected by the change? Integration
- Can they see the change or is it an under the hood? If they can see it, where? When they access integrations on dashboard.
- How is the user impacted by the change? A more complete description about how to use plugin.
- What are there any benefits of the change? Avoid confusions for user.
</details>

Add description about packages

---

aclk/aclk_otp.c
collectors/proc.plugin/sys_devices_pci_aer.c
collectors/systemd-journal.plugin/systemd-journal.c
database/engine/rrdengineapi.c
libnetdata/socket/socket.c
streaming/rrdpush.c
streaming/sender.c

streaming logs

---

collectors/systemd-journal.plugin/systemd-journal.c

Fix CID 400366

---

collectors/slabinfo.plugin/metadata.yaml

Add description about necessary package.
1. Grammar
- Which area of Netdata is affected by the change? Integration
- Can they see the change or is it an under the hood? If they can see it, where? When the access integration.
- How is the user impacted by the change? They have the necessary information to install the package.
- What are there any benefits of the change? A more complete description.
</details>

Update slabinfo metadata

---

database/engine/rrdengineapi.c
libnetdata/facets/facets.c

facets and journal improvements

---

packaging/installer/UPDATE.md

Clarifying the possible installation option
</details>

Clarifying the possible installation types

---

collectors/charts.d.plugin/ap/metadata.yaml
collectors/charts.d.plugin/apcupsd/metadata.yaml
collectors/charts.d.plugin/libreswan/metadata.yaml
collectors/charts.d.plugin/nut/metadata.yaml
collectors/charts.d.plugin/opensips/metadata.yaml
collectors/charts.d.plugin/sensors/metadata.yaml

Adds a note that charts.d plugin needs to be installed in some cases. Also a note to enable the sensors plugin.
</details>

Integrations: Add a note to install charts.d plugin

---

collectors/python.d.plugin/python.d.plugin.in

Fixes: #15962
Not needed
</details>

fix using undefined var when loading job statuses in python.d

---

collectors/systemd-journal.plugin/systemd-journal.c
libnetdata/facets/facets.c

when the histogram is empty, return it, but empty

facets histogram when empty

---

collectors/perf.plugin/metadata.yaml
collectors/python.d.plugin/hddtemp/metadata.yaml
collectors/python.d.plugin/nsd/metadata.yaml
collectors/python.d.plugin/samba/metadata.yaml
collectors/python.d.plugin/tomcat/metadata.yaml

This PR adds the info missing from the collectors READMEs, while also fixing some small hiccups.

Metadata fixes for some collectors

---

database/rrd.h
database/rrdcalc.c
health/health.c

Patch release 1.42.4
- https://github.com/netdata/netdata/pull/15984

Patch release 1.42.4

---

collectors/freeipmi.plugin/freeipmi_plugin.c
collectors/nfacct.plugin/plugin_nfacct.c
collectors/plugins.d/pluginsd_parser.c
database/engine/datafile.c
database/rrdset.c
streaming/sender.c

Fix compilation warnings when compiling with NETDATA_INTERNAL_CHECKS or NETDATA_DEV_MODE

Fix compilation warnings

---

collectors/python.d.plugin/changefinder/metadata.yaml
collectors/python.d.plugin/fail2ban/metadata.yaml
collectors/python.d.plugin/sensors/metadata.yaml

related to work i needed to do as part of this: https://github.com/netdata/learn/issues/1784
</details>

some collector metadata improvements

---

.github/data/distros.yml
integrations/deploy.yaml

Follow up PR of https://github.com/netdata/helper-images/pull/224
Do not merge this before   https://github.com/netdata/helper-images/pull/224 is merged
Closes https://github.com/netdata/netdata/issues/15397
</details>

Change the build image of EL packages from alma to rocky

---

packaging/installer/methods/packages.md

Clarify shipping repos cases
</details>

Clarify shipping repos cases

---

collectors/python.d.plugin/adaptec_raid/metadata.yaml
collectors/python.d.plugin/megacli/metadata.yaml

Update based based on the feedback here https://github.com/netdata/learn/issues/1784
@Ancairon these modules are enabled by default so we don't need to enable them. 
Skip
</details>

Update collector metadata for python collectors

---

ml/ad_charts.cc

use `status` as units for `anomaly_detection.detector_events`

---

integrations/gen_docs_integrations.py

As suggested, the script was a bit too hectic, I moved stuff into functions and simplified some of the logic.
Tested in both repos, and it gives the same results as the previous script

Simplify the script for generating documentation from integrations

---

docs/running-through-cf-tunnels.md

A couple of users provided a [very nice set of detailed instructions](https://discord.com/channels/847502280503590932/1154164395799216189/1154556625944854618), and it was decided we will add it to our documentation, in the misc section.
I made some grammar changes, but it should be pretty much as the user suggested it, I just added some bits here and there

Doc about running a local dashboard through Cloudflare (community)

---

integrations/gen_docs_integrations.py

Upon testing the go.d repo action, it failed, and I think I found the reason why

Bugfix on integrations/gen_docs_integrations.py

---

collectors/tc.plugin/metadata.yaml

Improve description about how to setup tc.plugin.
1. Take a look in format.
</details>

Improve description about tc.plugin

---

collectors/ebpf.plugin/ebpf.c

Fixes https://github.com/netdata/netdata/issues/16078
When socket was modified to bring functions, some variables were not properly modified, this PR address this issue.
1. Compile this branch.
2. Verify whether plugin is up and running.
</details>

Address reported socket issue

---

web/api/queries/query.c

if the db does not have any data to satisfy a query, cancel it.

fix querying out of retention

---

collectors/systemd-journal.plugin/systemd-journal.c
libnetdata/facets/facets.c

fix if_modified_since to not return empty responses and no overlapping data

journal: fix incremental queries

---

collectors/systemd-journal.plugin/systemd-journal.c

better journal logging

---

integrations/gen_docs_integrations.py

Add yet another dir that has an `integrations` documentation folder to the cleanup function

Add integrations/cloud-notifications to cleanup

---

libnetdata/dyn_conf/README.md

Documents Dynamic configuration
</details>

Documentation for Dynamic Configuration

---

collectors/systemd-journal.plugin/systemd-journal.c

On data only queries, calculate histogram and facets up to stop anchor, when it is given.

journal: go up to stop anchor on data only queries

---

integrations/gen_docs_integrations.py

fix in corner case of script, that was not crashing locally, but the action was failing.

Fix in generate integrations docs script

---

collectors/plugins.d/pluginsd_parser.c

fix crash on parsing clabel command with no source

---

collectors/apps.plugin/apps_plugin.c
collectors/apps.plugin/metadata.yaml

Fixes https://github.com/netdata/netdata/issues/14942
1. Compile branch
2. Take a look in charts and verify we have them running normally.
</details>

Split apps charts

---

collectors/systemd-journal.plugin/systemd-journal.c
database/contexts/api_v1.c
database/contexts/api_v2.c
database/contexts/query_target.c
libnetdata/libnetdata.c
libnetdata/libnetdata.h
web/api/queries/query.c
web/api/queries/weights.c

provide a relative_to_absolute function that does not touch the current realtime time

journal: fix the 1 second latency in play mode

---

libnetdata/threads/threads.c

`pthread_detach()` may crash if the created thread exits before calling it from the parent thread.
This is visible on parents that sometimes crash on startup, because the child that was connected happened to have disconnected immediately.
This PR adds a spinlock that will prevent the new thread to exit, until `netdata_thread_create()` has finished.

fix random crashes on pthread_detach()

---

integrations/gen_integrations.py
integrations/templates/alerts.md
integrations/templates/metrics.md
integrations/templates/setup.md

Fix for newlines inside tables breaking markdown.
Create a new function that sanitizes the string.

Introduce stringify function for integrations

---

integrations/gen_integrations.py
integrations/templates/setup.md

Fixes in integration generation script

---

health/health_config.c

health: don't log an unknown key error for "families"

---

collectors/apps.plugin/apps_plugin.c
collectors/cgroups.plugin/sys_fs_cgroup.c

Missed this in #16095 and #15975
</details>

make io charts "write" negative in apps and cgroups (systemd)

---

packaging/docker/run.sh

Fixes: #16151 and https://github.com/netdata/netdata/pull/14629#issuecomment-1566229876
I think #15118 fixes this problem too, it can be merged instead of this PR. 
Not needed, the changes are straightforward.
</details>

docker: make chmod o+rX /  non fatal

---

.github/data/distros.yml

fix repo path for openSUSE 15.5 packages

---

netdata.spec.in

enable _go_build only in centos>10

---

collectors/apps.plugin/apps_plugin.c
libnetdata/facets/facets.c

functions columns

---

health/health_config.c

- Suppress message see also #16145

Suppress "families" log

---

collectors/systemd-journal.plugin/systemd-journal.c

Journal updates

---

collectors/plugins.d/pluginsd_parser.c
collectors/systemd-journal.plugin/systemd-journal.c
database/rrdfunctions.c
database/rrdfunctions.h
libnetdata/facets/facets.c

stop the query 250ms before the timeout, to allow sending back partial responses

journal timeout

---

collectors/apps.plugin/apps_plugin.c

Create the "other" app group:
- Before: when the group contains 1+ processes.
- After: always.
Check for "other" app group charts.
</details>

apps: always expose "other" group

---

collectors/systemd-journal.plugin/README.md

Rework guide, add SSL with self-signed certs

---

collectors/apps.plugin/apps_plugin.c

apps: fix divide by zero when calc avg uptime

---

database/sqlite/sqlite_metadata.c

dynamic meta queue size

---

database/sqlite/sqlite_metadata.c

- Fix log message and unittest 
- Test with `netdata -W metatest`

Fix meta unittest

---

database/rrddim.c

- Fixes the dimension heterogeneous check (dimension added to have the same algorithm, multiplier and divisor as existing one)

Fix dimension HETEROGENEOUS check

---

collectors/systemd-journal.plugin/active_journal_centralization_guide_no_encryption.md

Active journal centralization guide no encryption

---

collectors/apps.plugin/metadata.yaml

fix apps plugin metric names in meta

---

database/rrdlabels.c

Fixes #16248
- There was a missing check in the internal label copy function that results in multiple keys with different value in the labels set. This PR adds the additional check to avoid that. 
- Unit tests have been updated

Fix label copy to correctly handle duplicate keys

---

libnetdata/facets/facets.c
libnetdata/simple_pattern/simple_pattern.c

SUBSTRING simple patterns fix

---

collectors/systemd-journal.plugin/systemd-journal.c

* CID 403725:  Resource leaks  (RESOURCE_LEAK)
/collectors/systemd-journal.plugin/systemd-journal.c: 2423 in function_systemd_journal()

Fix coverity issue 403725

---

collectors/python.d.plugin/haproxy/haproxy.chart.py

This PR introduces two changes to the Python-based HAProxy collector. First, it parses the backend server status up to the first space character, accounting for "transition" statuses such as `UP -1/3`, `UP 2/3`, and `DOWN 1/2`. Second, it adds a chart for backend servers with the `MAINT` status.
I deployed this change to my servers and have observed the desired effects. First time contributor here- please let me know if there's something more formal required!
While investigating a recent outage that affected some of my HAProxy servers, I turned to my Netdata dashboard to try to get a visual picture of what was happening. As it turned out- Netdata injected more confusion. There were brief moments where the total _combined_ number of backend servers in the `UP` & `DOWN` states equaled zero. …

Fix HAProxy server status parsing and add MAINT status chart

---

integrations/gen_docs_integrations.py

Edge case where semicolon was inside a string that was used as filename.
Closes #16275 
Tested on both repos, only the affected file changed, and got fixed.

Remove semicolons from strings

---

database/sqlite/sqlite_aclk_alert.c
database/sqlite/sqlite_functions.c

Creation of indexes needed to speed up queries during cloud sending alerts, (decision to send or not to cloud) on parents with many alerts per children.
</details>

Small optimization of alert queries

---

database/engine/metric.c

A wrong condition hides the retention from the dashboard.

fix retention loading

---

integrations/gen_integrations.py

I think yes/no looks better than True/False in the documentation.
</details>

integrations: yes/no instead of True/False in tables

---

collectors/plugins.d/pluginsd_parser.c
collectors/systemd-journal.plugin/systemd-journal.c
database/rrd.h
database/rrdset.c
streaming/compression.c
streaming/compression_brotli.c
streaming/compression_gzip.c

fix various issues identified by coverity

---

database/rrdlabels.c

- More detail in unittests
- Fix an issue after latest changes in label copy 
* CID 403954:  Control flow issues  (DEADCODE)
/database/rrdlabels.c: 1056 in rrdlabels_copy()

Fix label copy

---

integrations/gen_docs_integrations.py

**Typo has been fixed.**
</details>

typo fixed in gen_docs_integrations.py

---

collectors/plugins.d/pluginsd_parser.c
collectors/proc.plugin/proc_net_dev.c
collectors/systemd-journal.plugin/systemd-journal.c
database/rrdlabels.c
database/rrdset.c
database/sqlite/sqlite_aclk_alert.c
database/sqlite/sqlite_functions.c
streaming/rrdpush.c

- 4e9ba530a Fix label copy: allow new key with different value
- 2b5fa9b7d Do do propagate internal flags
- c74297d07 Small optimization of alert queries (#16282)
- 3c1f32a1f Marked charts exposed when labels change
- d527ae9d9 rrdlabel unmark/mark/delete unmarked restored
- 37ef85b11 Marked charts exposed when labels change
- https://github.com/netdata/netdata/pull/16302/commits/34c6c31c47fd219659b6a255406f8d422207c93d Fix rrdlabels type

Patch release 1.43.2

---

claim/netdata-claim.sh.in

Fixes: #16299
Not needed
</details>

claim.sh: use echo instead of /bin/echo

---

integrations/deploy.yaml

related to https://github.com/netdata/website/pull/382.

Use proper icons for deploy integrations

---

README.md
REDISTRIBUTED.md
docs/cloud/manage/organize-your-infrastrucutre-invite-your-team.md
docs/contributing/style-guide.md
docs/getting-started/introduction.md
docs/guides/monitor-hadoop-cluster.md
docs/quickstart/infrastructure.md

I now have made a 404 checker for Learn, so there will be more of these.
In spots where the link was something that doesn't exist anymore, I removed the whole thing.

Fix 404s in markdown files

---

packaging/docker/README.md

Refs https://github.com/netdata/netdata/issues/16244
</details>

Add a note for the docker deployment alongside with cetus

---

README.md

Update ObservabilityCon README.md

---

README.md

Please check the dark theme as well
</details>

Added section Blog posts README.md

---

collectors/cgroups.plugin/cgroup-discovery.c
collectors/cgroups.plugin/sys_fs_cgroup.c

fix coverity warnings in cgroups

---

integrations/deploy.yaml

Use `edge` instead of `latest`.
Not needed.
</details>

integrations: fix nightly tag in helm deploy

---

collectors/systemd-journal.plugin/systemd-main.c
collectors/systemd-journal.plugin/systemd-units.c
libnetdata/buffer/buffer.h

systemd-units improvements

---

collectors/proc.plugin/proc_net_dev.c

Add/remove network interfaces and make sure ND doesn't crash and the values returned by the function are correct.

proc netstat: add network interface statistics function

---

docs/cloud/visualize/dashboards.md

Updated documentation due to the outdated parts
</details>

Update info about custom dashboards

---

packaging/installer/methods/manual.md
packaging/installer/methods/source.md
packaging/makeself/README.md

1. Add repo clean up instructions for the netdata/netdata repo (clean up from previous builds)
2. Make the static build instruction to use the more generic script
Closes https://github.com/netdata/learn/issues/1876
Skip
</details>

Update packaging instructions

---

database/sqlite/sqlite_functions.c

Detect a database corruption during runtime and schedule a  recovery operation when the agent restarts

Better database corruption detention during runtime

---

configure.ac
packaging/makeself/jobs/70-netdata-git.install.sh

- build static image; install ND.
- check buildinfo (should have zstd).
- configure parent/child, check negotiated capabilities (should have ZSTD).
</details>

fix zstd in static build

---

docs/netdata-cloud-onprem/getting-started.md

This is the instruction on how to configure helm to be able to pull the helm chart for the Netdata Cloud On-Prem offering.
</details>
#ref netdata/infra#3790

Docs: getting started with netdata cloud onprem

---

collectors/cgroups.plugin/cgroup-top.c
collectors/diskspace.plugin/plugin_diskspace.c
collectors/proc.plugin/proc_diskstats.c
collectors/proc.plugin/proc_net_dev.c
database/rrd.h

ssia
Check internal collectors functions.
</details>

add rrddim_get_last_stored_value to simplify function code in internal collectors

---

database/rrdfunctions.c
database/rrdfunctions.h
database/rrdvar.c
web/api/formatters/charts2json.c
web/api/formatters/charts2json.h
web/api/formatters/json_wrapper.c
web/api/formatters/rrd2json.c
web/api/formatters/rrdset2json.c
web/api/formatters/rrdset2json.h
web/api/web_api_v1.c

Switch to buffer json function for better code readability. This PR handles charts / chart endpoint
</details>

Switch charts / chart to use buffer json functions

---

collectors/freeipmi.plugin/freeipmi_plugin.c

Make sure the ipmi-sensors function reports correct values.
</details>

collectors/freeipmi: add ipmi-sensors function

---

collectors/proc.plugin/proc_net_dev.c

An alternative for #16162. I don't think there is a reliable way to determine from inside the container that the network namespace is the host's network namespace.
- Install ND inside an LXC container.
- Check system.net - should exist.
- Check the interface_type label value of eth0 - should be real.
</details>

fix system.net when inside lxc 

---

integrations/cloud-notifications/metadata.yaml

Add configuration documentation for Cloud AWS SNS.

Add configuration documentation for Cloud AWS SNS

---

packaging/installer/install-required-packages.sh

Fixes: #16283
Test the script on various distros:
- debian/ubuntu
- alpine
- centos7/8
</details>

pacakging: add zstd dev to install-required-packages

---

collectors/cgroups.plugin/metadata.yaml

Forgot to do it in #16369
Not needed
</details>

add pids current to cgroups meta

---

packaging/VERSIONING_AND_PUBLIC_API.md

Based on internal discussion.
n/a

Add assorted improvements to the version policy draft.

---

health/REFERENCE.md

This alarm line was deprecated.
</details>

docs: remove 'families' from health reference

---

integrations/cloud-notifications/metadata.yaml

This PR fixes this problem:
</details>

fix cloud aws sns notification meta

---

collectors/systemd-journal.plugin/systemd-units.c

fix systemd-units func expiration time

---

collectors/ebpf.plugin/integrations/ebpf_processes.md
collectors/ebpf.plugin/metadata.yaml

Fix typo in eBPF metadata
</details>

Fix typo in metadata (eBPF)

---

integrations/cloud-notifications/metadata.yaml

Adds config info for the Telegram cloud notification.

Adds config info for Telegram cloud notification

---

README.md

Removes Observabilitycon banner README.md

---

health/REFERENCE.md

A small typo change in health's REFERENCE.md
</details>

Minor: Small health docs typo fix

---

aclk/aclk.c
database/rrd.h
database/sqlite/sqlite_aclk.c
database/sqlite/sqlite_aclk.h
database/sqlite/sqlite_aclk_alert.c
database/sqlite/sqlite_aclk_alert.h
database/sqlite/sqlite_aclk_node.c
database/sqlite/sqlite_functions.c
health/health.c

- Code cleanup
- Remove queue limit from ACLK sync event loop

Remove queue limit from ACLK sync event loop

---

collectors/xenstat.plugin/xenstat_plugin.c

SSIA.
Build the xenstat plugin

Add missing argument.

---

libnetdata/log/log.c

set the environment variable for the journal socket path, so that plugins can find it.

set journal path for logging

---

libnetdata/log/log2journal.c

fix log2journal incorrect log

---

netdata-installer.sh

SSIA. Accidentally removed in https://github.com/netdata/netdata/pull/15969.
Build with `--disable-ml`.

Add option to disable ML.

---

collectors/xenstat.plugin/metadata.yaml

SEO changes for Collector names

SEO changes for Collector names

---

Makefile.am
configure.ac
libnetdata/log/log2journal.c
libnetdata/log/log2journal.md

This PR allows `log2journal` to accept yaml configuration too.

Log2journal yaml configuration support

---

coverity-scan.sh

Bump new version to cov-analysis tool

---

docs/netdata-cloud-onprem/getting-started-light-poc.md
docs/netdata-cloud-onprem/getting-started.md
docs/netdata-cloud-onprem/troubleshooting-onprem.md

Some of the Netdata Cloud On-Prem docs had to face spelling fixes

Spelling fixes to documentation

---

database/sqlite/sqlite_aclk_node.c

Wait until the context post processing queue is empty before sending node and collector info to the cloud. 
When a node has a lot of charts / dimensions / labels, the context version calculation may take some time. 
In rare cases the cloud may request a context update with a version number that will not match (because the local calculation in still in progress).

Check context post processing queue before sending status to cloud

---

CMakeLists.txt
Makefile.am
libnetdata/endian.h
libnetdata/os.h

Fix builds on macOS due to missing endianness functions

---

README.md

It is broken ("invalid response data"). If someone knows how to fix and think we need to keep it - please do.
Not needed.
</details>

remove discourse badge from readme

---

collectors/log2journal/log2journal-params.c
collectors/log2journal/log2journal-rewrite.c
collectors/log2journal/log2journal-yaml.c
collectors/log2journal/log2journal.c
collectors/log2journal/log2journal.h

journal improvements part 3

---

collectors/freeipmi.plugin/freeipmi_plugin.c
database/rrdcalc.c
health/health.d/ipmi.conf
registry/registry_db.c

Found more error messages that are not errors.
Not needed.
</details>

convert some error messages to info

---

collectors/python.d.plugin/python.d.plugin.in
collectors/python.d.plugin/python_modules/bases/loggers.py

ssia
Check netdata journal entries: failed checks/check logs only for stock jobs.
</details>

python.d: mute stock jobs logging during check()

---

packaging/installer/methods/kickstart.md

It's just wrong to have a simple fail-safe of kickstart validity (checksum is calculated by CI independently) and communicate it after the actual installation.
</details>

Reorg kickstart guide's steps

---

database/rrdset.c

change level to debug "took too long to be updated"

---

collectors/log2journal/README.md

Changing the two links to ones that can be parsed by Learn

Proper Learn-friendly links

---

libnetdata/Makefile.am
libnetdata/gorilla/README.md

Add README for gorilla

---

.github/workflows/release.yml

Set-output will be deprecated and version 2.3 of this particular GHA was using it.
Special thanks to https://github.com/heinrichreimer for his instant response
</details>

Bump new version on the release changelog GHA

---

packaging/installer/netdata-uninstaller.sh

uninstaller remove log2journal and systemd-cat-native

---

integrations/categories.yaml

Add a `Logs` category on Integrations.

Update categories.yaml to add Logs

---

integrations/cloud-notifications/metadata.yaml

Adds docs for Splunk cloud notifications
xref: https://github.com/netdata/cloud-backend/issues/553

Adds docs for Splunk cloud notifications

---

collectors/systemd-journal.plugin/systemd-main.c

The systemd-journal plugin advertises its function whether it succeeds in finding the journal data directories or not. This results in all nodes, including those without relevant journal entries (e.g., Docker netdata children), appearing in the Nodes filter. This makes it hard to identify nodes with actual journal logs. Furthermore, when no journal data directories exist, there is little reason to run the systemd-journal plugin.
<details>
<summary>Screenshot</summary>
</details>
Check:
- systemd-journal plugin is running if journal data directories exist.
- systemd-journal plugin is not running if journal data directories don't exist.
</details>

systemd-journal: exit if unable to locate journal data directories

---

netdata-installer.sh

Fixed #16599
Not needed
</details>

fix not assigned proc_count in installer

---

daemon/unit_test.c
database/sqlite/sqlite_metadata.c

Remove assert

---

libnetdata/log/log.c

Fixes logically dead code and error checking

Fix coverity issues, logically dead code and error checking

---

collectors/cgroups.plugin/sys_fs_cgroup.c

Filter out `/system.slice/lxcfs.service/.control`
Tested manually
</details>

cgroups: filter lxcfs.service/.control

---

collectors/cgroups.plugin/sys_fs_cgroup.c
packaging/docker/README.md

docs: add "Rootless mode" to Docker install guide

---

README.md

Added energy efficiency img README.md

---

.github/workflows/build.yml
.github/workflows/packaging.yml

Done independently of dependabot because this requires special handling to make it work properly.

Update artifact-handling actions to latest version.

---

docs/cloud/alerts-configuration-manager.md

We can't mix numbers with bullets, and also indent must be 2 spaces and not a tab

Necessary changes for Learn

---

libnetdata/log/README.md

docs: add a few examples how to query Netdata logs using journalctl

---

health/REFERENCE.md

I think this way it's more clear what it's about and that it's actually different to host_labels one which confused me a bit.

docs: Correct chart_labels summary

---

cli/cli.c
collectors/plugins.d/pluginsd_parser.c
libnetdata/buffer/buffer.h

fix compiler warning when compiled without internal checks

fix compiler warnings

---

packaging/installer/kickstart.sh

kickstart: dont run install-required-packages.sh as root on macOS

---

.github/workflows/build.yml
.github/workflows/packaging.yml

We need to investigate further why some jobs are failing. Until then we will reverts netdata/netdata#16639

Revert "Update artifact-handling actions to latest version."

---

database/rrdfunctions.c

fixes https://github.com/netdata/netdata/discussions/16678

improve the error message when accessing functions

---

CMakeLists.txt
cli/cli.c
collectors/log2journal/log2journal.h

cmake log2journal netdatacli

---

collectors/cups.plugin/cups_plugin.c

cups exit on sigpipe

---

netdata-installer.sh

Enable/disable options for Prometheus remote write where always set to true
</details>

fix minor omission on netdata-installers arguments

---

netdata-installer.sh

Because building it fails anyway.
</details>

disable logsmanagement when installing on macOS

---

collectors/proc.plugin/proc_net_dev.c

The 15-second delay is not enough for systems with a large number of containers (more than 100), because for each container Netdata performs:
- name resolution (bash script).
- map the host virtual interface to the interface inside the container (helper binary).
This is an improvement of #15244. The improvement is to not delay the collection of all virtual interfaces (e.g. bridges).
Host with 200 containers, veth* interfaces: 
- don't appear in "Network Interfaces".
- appear in "Containers & VMs"
</details>

delay collecting double linked network interfaces

---

integrations/cloud-notifications/metadata.yaml

Add the Mobile App notification Integration

Add the Mobile App notification Integration

---

.github/ISSUE_TEMPLATE/config.yml

Add Netdata Mobile App to issue template config

---

collectors/ebpf.plugin/ebpf_functions.c
collectors/ebpf.plugin/ebpf_functions.h

- Rename: "Ebpf_socket" => "Network-connections".
- Improve column names.
- Fix default column sorting.
- Convert traffic from bytes to MB.
See screenshots for changes
<details>
<summary><b><i>This PR</i></b></summary>
</details>
<details>
<summary><b><i>Master branch</i></b></summary>
</details>
</details>

update ebpf-socket function name and columns

---

packaging/installer/methods/kickstart.md

Fix `--distro-override` parameter name in docs

Fix --distro-override parameter name in docs

---

health/health.d/httpcheck.conf

Fixes https://github.com/netdata/netdata/issues/16662#issuecomment-1879751428
Not needed
</details>

health: add httpcheck bad header alert

---

claim/README.md
docs/cloud/cheatsheet.md
exporting/WALKTHROUGH.md
integrations/deploy.yaml
packaging/installer/README.md
packaging/installer/REINSTALL.md
packaging/installer/UNINSTALL.md
packaging/installer/UPDATE.md
packaging/installer/methods/freebsd.md
packaging/installer/methods/kickstart.md
packaging/installer/methods/macos.md
packaging/installer/methods/offline.md

Relevant netdata/incidents#56
Closes #14157
</details>

change get kickstart url to https://get.netdata.cloud/kickstart.sh

---

database/engine/page.c
database/engine/pdc.c

Mostly to make the agent downgradable when
dealing with unknown page types.
- CI

Fatal relaxation of unknown page types.

---

database/sqlite/sqlite_aclk_alert.c

Fix compilation warning
- Fix compilation warning
- Remove unused file

Remove unused file

---

CMakeLists.txt
database/rrdlabels.c
libnetdata/buffer/buffer.h
libnetdata/dictionary/dictionary.c
libnetdata/log/log.c
tests/run-unit-tests.sh

SSIA.
- Check CI unit tests job.

Address sanitizer through CMake and use it for unit tests.

---

.github/CODEOWNERS

update codeowners, remove nonexistent accounts github complains about
</details>

minor - fix/update codeowners

---

CMakeLists.txt
collectors/systemd-journal.plugin/schema.d/systemd-journal:monitored-directories.json

add schemas to /usr/lib/netdata/conf.d/schema.d

---

mqtt_websockets/src/mqtt_wss_client.c

Delete unused variable.

---

libnetdata/buffer/buffer.c
libnetdata/buffer/buffer.h
web/server/h2o/connlist.c
web/server/h2o/http_server.c
web/server/h2o/http_server.h
web/server/h2o/streaming.c
web/server/h2o/streaming.h

Remove h2o header from libnetdata

---

collectors/diskspace.plugin/plugin_diskspace.c

final fix for https://github.com/netdata/netdata/pull/16784

diskspace: reworked the cleanup to fix race conditions

---

health/notifications/telegram/README.md
health/notifications/telegram/metadata.yaml

While I was given [support](https://community.netdata.cloud/t/telegram-not-receiving-some-alerts-while-gotify-works-ok/5042/3) for our users, I observed that Telegram modified the way to get the necessary information to send alerts. This PR addresses this issue.
1. Check grammar
- Which area of Netdata is affected by the change? Documentation
- Can they see the change or is it an under the hood? If they can see it, where? When they access documentation.
- How is the user impacted by the change? They will have a documentation aligned with latest versions of Telegram.
- What are there any benefits of the change? An updated documentation
</details>

Update telegram documentation

---

database/contexts/api_v2.c
database/rrdcalc.c
database/rrdcalc.h
health/health.c
health/health.h

- Use original summary for alert
- Fetch transaction and global id for transitions safely

Use original summary for alert transition

---

database/sqlite/sqlite_context.c
database/sqlite/sqlite_db_migration.c
database/sqlite/sqlite_functions.c
database/sqlite/sqlite_functions.h
ml/ml.cc

This will add additional info to telemetry (if enabled) to troubleshoot database initialization failures.

Add additional fail reason and source during database initialization

---

.github/scripts/docker-test.sh
.github/scripts/pkg-test.sh
packaging/makeself/jobs/90-netdata-runtime-check.sh
packaging/runtime-check.sh

- Centralize the logic used to perform basic runtime checks for builds in our CI.
- Expand the runtime checks to include verifying that the individual dashboards can be fetched.

CI runtime check cleanup

---

.github/workflows/build.yml
.github/workflows/packaging.yml

This time with proper fixes for upstream bugs.

Update GHA steps that handle artifacts to use latest versions of upload/download actions.

---

collectors/cgroups.plugin/cgroup-top.c

Add cgroup CPU throttling % to the "Containers-vms" function.
Visible by default in k8s, otherwise hidden.  
Check "Containers-vms".
</details>

cgroups: containers-vms add CPU throttling %

---

packaging/installer/kickstart.sh

Closes https://github.com/netdata/netdata/issues/16790
</details>

Apply ASCII-based comparisons to commands in kickstart script that rely on a particular language setting

---

web/api/netdata-swagger.json
web/api/netdata-swagger.yaml

minor but important update, changing the naming convention to update this info without changing too much on the CI.
CC @ilyam8 @Ferroin 
</details>

Update naming for swagger api

---

collectors/apps.plugin/apps_plugin.c
collectors/debugfs.plugin/sys_devices_virtual_powercap.c
collectors/ebpf.plugin/ebpf_cachestat.c
collectors/ebpf.plugin/ebpf_dcstat.c
collectors/ebpf.plugin/ebpf_fd.c
collectors/ebpf.plugin/ebpf_oomkill.c
collectors/ebpf.plugin/ebpf_process.c
collectors/ebpf.plugin/ebpf_shm.c
collectors/ebpf.plugin/ebpf_socket.c
collectors/ebpf.plugin/ebpf_swap.c
collectors/ebpf.plugin/ebpf_vfs.c

I notice some lable not set automatically, and it will not show in prometheus api, fixed it. 
</details>

set app_group label automatically

---

docs/netdata-cloud-onprem/getting-started-light-poc.md

Due to https://github.com/netdata/netdata-cloud-onprem/pull/80 we need to update docs too.
ref. netdata/infra#4042 
</details>

updates to light onprem docs

---

libnetdata/libnetdata.c

Fixes: #16812
Check host prefix verification.
</details>

use fs type to veryfiy procfs/sysfs

---

database/contexts/query_target.c
database/contexts/rrdcontext.h

- Group labels by key as described in the issue
Fixes #15203

Change query label matching logic

---

daemon/buildinfo.c

add brotli and libyaml to buildinfo

---

libnetdata/dictionary/dictionary.c
libnetdata/dictionary/dictionary.h

Add explicit callback types for readability.

---

packaging/check-for-go-toolchain.sh

SSIA
Still none currently for this.

Fix directory handling in Go toolchain handling script.

---

integrations/cloud-notifications/metadata.yaml

Adds documentation regarding the new Microsoft Teams Cloud integration.
Checked the .md to be generated as standalone and it looks ok.
</details>

adds docs for cloud MS Teams integration

---

packaging/installer/methods/kickstart.md

Make the kickstart checksum's placeholder value more concrete

---

README.md

Fix the CNCF link due to changes on their website.
</details>

CNCF link fix

---

.github/data/distros.yml
packaging/PLATFORM_SUPPORT.md

Dont merge it before 2024-01-20
Closes https://github.com/netdata/netdata/issues/16666
</details>

Remove Ubuntu 23.04 from the CI

---

database/README.md

closes https://github.com/netdata/learn/issues/1935

Remove old mention of save db mode

---

collectors/log2journal/log2journal-yaml.c

* CID 410250:    (RESOURCE_LEAK)
/collectors/log2journal/log2journal-yaml.c: 564 in yaml_parse_rewrites()

Fix coverity issue

---

CMakeLists.txt
collectors/network-viewer.plugin/network-viewer.c
collectors/plugins.d/local-sockets.h
collectors/plugins.d/local_listeners.c
contrib/debian/netdata.postinst
contrib/debian/rules
netdata-installer.sh
netdata.spec.in
packaging/docker/Dockerfile
packaging/docker/README.md
packaging/makeself/install-or-update.sh

Function to present all currently running sockets of system, without using ebpf.

Network Viewer (local-sockets version)

---

streaming/stream.conf

Rm refs to map and save modes

---

collectors/network-viewer.plugin/viewer.html
collectors/plugins.d/local-sockets.h
health/schema.d/health:alert:prototype.json

Network viewer fixes

---

packaging/dag/README.md
packaging/dag/requirements.txt

Add requirements.txt for dag

---

collectors/network-viewer.plugin/viewer.html

fixed missing collisions and drag on newly added apps

---

src/database/engine/metric.c

Use spinlock for reference counting.

---

packaging/installer/functions.sh

Build network-viewer only on linux

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/docker.yml
.github/workflows/packaging.yml

They’ve not been accurate for some time.

Update file match patterns in CI jobs.

---

docs/guides/configure/performance.md

1. format line length to 120
2. transform the table into an actual table (worked with magic atm)
3. Make the list of actions more consistent
4. Remove an old reference to memory mode save
5. Remove whitespace
</details>

Minor rework on document

---

src/daemon/main.c
src/daemon/main.h

Do not declare struct meant for internal usage

---

integrations/gen_integrations.py

Files were moved, so this needs a change

Fix path in health integrations

---

README.md

Updated txt - Prometheus section README.md

---

CMakeLists.txt
config.cmake.h.in
src/libnetdata/libnetdata.h
src/libnetdata/storage_number/storage_number.c
tests/profile/benchmark-registry.c

Remove config macros that are always set.

---

src/collectors/cgroups.plugin/cgroup-network.c
src/daemon/daemon.c
src/daemon/daemon.h
src/database/rrdset.c

Remove unused header includes and mark functions as static.
- CI jobs.

Small cleanup

---

daemon/analytics.c
daemon/analytics.h
daemon/main.c
database/rrd.h
database/sqlite/sqlite_aclk_alert.c
database/sqlite/sqlite_db_migration.c
database/sqlite/sqlite_functions.c
database/sqlite/sqlite_functions.h
database/sqlite/sqlite_health.c
health/health_log.c
web/server/web_server.c
web/server/web_server.h

- Check for agent already running (#16937)
- Prevent negative alert duration reported to the cloud (#16931)
- Protect analytics set data (#16929)
- Update statistics to address slow queries (#16838)

Patch release 1.44.3

---

src/daemon/main.c

SSIA. Enabled only for sentry builds, ie. Debian 12.
- CI jobs.

Abort on non-zero rc.

---

src/database/rrddim.c

- Protect metric release during dimension delete callback
The spinlock was added in `rrddim_finalize_collection_and_check_retention`.

Protect metric release in dimension delete callback

---

src/database/rrd.h
src/database/rrdset.c
src/health/health_event_loop.c

Code cleanup

---

src/libnetdata/log/log.c

Do not use backtrace when sentry is enabled.

---

src/collectors/proc.plugin/proc_spl_kstat_zfs.c

Fixes: #17053
Not needed.
</details>

fix zpool state chart family

---

.github/CODEOWNERS
.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/docker.yml
.github/workflows/packaging.yml

- Add @vkalintiris as a code owner for the CMake components.
- Ensure that GHA workflows properly flag changes to files in `packaging/cmake/` as being build system changes.
n/a

Fix a few minor bits of build-related infrastructure.

---

src/go/collectors/go.d.plugin/agent/module/job.go

Follow-up on #17028
</details>

go.d.plugin: set max chart id length to 1200

---

src/daemon/watcher.c

This will allow backtraces to display the
specific step that might timeout.
- CI jobs

Make watcher thread wait for explicit steps.

---

contrib/debian/netdata-plugin-cups.postinst
contrib/debian/netdata-plugin-cups.preinst

Somehow during the latest releases we missed this (cups-plugin is a separate package for quite some time)
</details>

Fix cups plugin group owner

---

src/go/collectors/go.d.plugin/modules/pulsar/charts.go

fix go.d.plugin/pulsar tests

---

src/health/REFERENCE.md

"foreach" was removed in #16779
n/a, docs only
</details>

remove "foreach" from health REFERENCE.md

---

src/go/collectors/go.d.plugin/README.md
src/go/collectors/go.d.plugin/docs/how-to-write-a-module.md
src/go/collectors/go.d.plugin/modules/coredns/metadata.yaml
src/go/collectors/go.d.plugin/modules/httpcheck/metadata.yaml
src/go/collectors/go.d.plugin/modules/isc_dhcpd/metadata.yaml
src/go/collectors/go.d.plugin/modules/mongodb/metadata.yaml
src/go/collectors/go.d.plugin/modules/openvpn/metadata.yaml
src/go/collectors/go.d.plugin/modules/openvpn_status_log/metadata.yaml
src/go/collectors/go.d.plugin/modules/postgres/metadata.yaml
src/go/collectors/go.d.plugin/modules/weblog/metadata.yaml
src/go/collectors/go.d.plugin/pkg/README.md
src/go/collectors/go.d.plugin/pkg/iprange/README.md
src/go/collectors/go.d.plugin/pkg/matcher/README.md
src/go/collectors/go.d.plugin/pkg/prometheus/selector/README.md
src/go/collectors/go.d.plugin/pkg/stm/README.md
src/go/collectors/go.d.plugin/pkg/tlscfg/README.md
src/go/collectors/go.d.plugin/pkg/web/README.md

fix links in go.d.plugin

---

src/go/collectors/go.d.plugin/logger/handler.go
src/go/collectors/go.d.plugin/logger/level.go
src/go/collectors/go.d.plugin/logger/logger.go

go.d.plugin add notice log level

---

src/health/REFERENCE.md

remove deprecated settings from the health ref doc

---

docs/maintenance/backup-restore.md

I think the sequence I edited looks better and that last note was intended to be outside of the numbered list.

very minor docs update

---

docs/netdata-cloud/netdata-cloud-on-prem/installation.md

minor fix; broken link on on prem installation doc

---

src/database/rrdlabels.c

- Fix memory leak in pattern_array_free

Fix memory leak

---

src/health/schema.d/health:alert:prototype.json

fix health alert dyncfg schema fullPage option

---

.github/workflows/docker.yml

Fix login to GHCR when publishing Docker images.

---

integrations/cloud-notifications/integrations/pagerduty.md

Documents new field on PagerDuty cloud integration.
https://github.com/netdata/cloud-backend/issues/601

Document new field on PagerDuty cloud integration

---

CHANGELOG.md
docs/cloud/alerts-notifications/manage-notification-methods.md
docs/cloud/manage/plans.md
docs/cloud/visualize/interact-new-charts.md
netdata-installer.sh
packaging/installer/methods/source.md
src/web/api/badges/README.md

remove repetitive words

---

src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/dockerd/docker.go
src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/dockerd/dockerd_test.go
src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/dockerd/sim_test.go
src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/dockerd/target.go
src/go/collectors/go.d.plugin/agent/discovery/sd/model/tags.go
src/go/collectors/go.d.plugin/agent/discovery/sd/pipeline/classify.go
src/go/collectors/go.d.plugin/agent/discovery/sd/pipeline/classify_test.go
src/go/collectors/go.d.plugin/agent/discovery/sd/pipeline/config.go
src/go/collectors/go.d.plugin/agent/discovery/sd/pipeline/pipeline.go
src/go/collectors/go.d.plugin/agent/discovery/sd/pipeline/pipeline_test.go
src/go/collectors/go.d.plugin/agent/discovery/sd/pipeline/promport.go
src/go/collectors/go.d.plugin/agent/discovery/sd/pipeline/sim_test.go
src/go/collectors/go.d.plugin/agent/hostinfo/hostinfo.go
src/go/collectors/go.d.plugin/agent/setup.go
src/go/collectors/go.d.plugin/config/go.d/sd/docker.conf
src/go/collectors/go.d.plugin/config/go.d/sd/net_listeners.conf

Fixes: #12153
Initial simple version: periodically (every 60 secs by default) calls [ContainerList](https://docs.docker.com/engine/api/v1.44/#tag/Container/operation/ContainerList).
</details>

go.d.plugin: add docker service discovery

---

packaging/docker/README.md
src/collectors/python.d.plugin/nvidia_smi/README.md

Fixes: #4736
Thanks to @D34DC3N73R for the heads up!
</details>

docs: add "With NVIDIA GPUs monitoring" to docker install

---

src/aclk/aclk_capas.c

-  Announce dynamic configuration capability to the cloud

Announce dynamic configuration capability to the cloud

---

src/go/collectors/go.d.plugin/config/go.d/sd/docker.conf

go.d sd docker add mongodb-community-server

---

src/go/collectors/go.d.plugin/agent/discovery/sd/pipeline/promport.go
src/go/collectors/go.d.plugin/config/go.d/sd/docker.conf

go.d sd docker use well-known port for app identification too

---

src/go/collectors/go.d.plugin/agent/discovery/sd/pipeline/config.go
src/go/collectors/go.d.plugin/agent/discovery/sd/sd.go
src/go/collectors/go.d.plugin/agent/discovery/sd/sd_test.go
src/go/collectors/go.d.plugin/config/go.d/sd/docker.conf
src/go/collectors/go.d.plugin/config/go.d/sd/net_listeners.conf

go.d sd config add "disabled"

---

docs/dashboard/import-export-print-snapshot.md

add callout that snapshots only available on v1
</details>

add callout that snapshots only available on v1

---

src/health/health.d/cpu.conf

Fixes: #17178
Not needed.
</details>

health: unsilence cpu % alarm

---

src/web/api/formatters/value/value.c

- Initialize sum to 0 instead of NAN

Fix sum calculation in rrdr2value

---

src/database/sqlite/sqlite_metadata.c

- Add missing columns to the table when installing new agent

Fix alert hash table definition

---

src/database/sqlite/sqlite_db_migration.c
src/database/sqlite/sqlite_metadata.c

- Handle installations with wrong alert hash table definition
- Add missing fields

Handle agents will wrong alert_hash table definition

---

src/go/collectors/go.d.plugin/modules/weblog/logline.go
src/go/collectors/go.d.plugin/modules/weblog/logline_test.go

go.d: weblog allow PURGE HTTP method

---

src/go/collectors/go.d.plugin/config/go.d/sd/net_listeners.conf

go.d: local-listeners sd: trust known ports to identify an app

---

src/go/collectors/go.d.plugin/agent/jobmgr/dyncfg.go

go.d: adjust dyncfg return codes

---

src/aclk/aclk_capas.c

- Reflect the latest changes in dynamic configuration

Dynamic configuration switch to version 2

---

.github/workflows/docker.yml

Fix job depdendencies in Docker workflow.

---

docs/cloud/visualize/dashboards.md
src/web/gui/custom/README.md

The objective was to:
* add warning on previous custom dashboard (HTML) page
* try to surface the existing page to come on top when searching for Custom Dashboards
</details>

add warning on old custom dashboards and rephrase existing page

---

docs/netdata-cloud-onprem/getting-started.md
docs/netdata-cloud/netdata-cloud-on-prem/installation.md

I made a mistake in docs regarding the onprem installation. The old way will not work at all (403 on helm pull attempt)
</details>

fixing the helm login command for the onprem installation

---

docs/netdata-cloud/netdata-cloud-on-prem/README.md

EMQX is directly connected by the ingress, it does not use Traefik.
</details>

update flowchart cloud-onprem

---

src/database/engine/cache.c

When a page cannot be acquired, repeat the call until it can or does not exist.
The bug is in the page lookup logic of the cache.
The call to `pgc_page_get_and_acquire()` is like a Judy traversal. So, you give a start time and by calling it repeatedly you get all the pages until it returns NULL.
However, if it finds a page that cannot be acquired (because it is currently being deleted), it returns NULL, breaking the loop.
So, when pages are evicted, any queries that happen to be executed matching pages that are currently being deleted, stop prematurely.
The solution is to retry the call when this happens (the page will be removed eventually), thus allowing the query to continue to the next pages.

dbengine: cache bug-fix when under pressure

---

src/database/engine/metric.c
src/database/rrddim.c
src/database/rrdhost.c
src/database/rrdset.c

Fix MRG Metric refcount issue

---

src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/netlisteners/netlisteners.go
src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/netlisteners/netlisteners_test.go

They are unusable and there can be many of them.
</details>

go.d: sd local-listeners: drop docker-proxy targets

---

integrations/cloud-notifications/metadata.yaml

include information about the JSON object sent on reachability alerts by the webhook integration.

include reachability alert fields

---

integrations/cloud-notifications/metadata.yaml

Changes from #17149
</details>

docs: update pagerduty meta

---

src/database/sqlite/sqlite_functions.c

- Set database handle to NULL on close

Reset database connection handle on close

---

src/collectors/ebpf.plugin/metadata.yaml
src/collectors/proc.plugin/metadata.yaml
src/collectors/python.d.plugin/beanstalk/metadata.yaml
src/collectors/python.d.plugin/litespeed/litespeed.chart.py
src/collectors/python.d.plugin/litespeed/metadata.yaml
src/collectors/python.d.plugin/puppet/metadata.yaml
src/collectors/python.d.plugin/puppet/puppet.chart.py
src/go/collectors/go.d.plugin/modules/logstash/metadata.yaml
src/go/collectors/go.d.plugin/modules/vernemq/metadata.yaml

fix duplicate chart context

---

integrations/cloud-notifications/metadata.yaml

https://github.com/netdata/cloud-backend/issues/608

add additional fields to webhook reachability notifications

---

.github/workflows/docker.yml

During the rework of the Docker workflow, we omitted this step. 
</details>

Trigger subsequent workflows for Helmchart and MSI

---

.github/data/distros.yml

SSIA.
N/A, need to wait for nightlies.

Enable sentry on all Debian and Ubuntu versions.

---

src/health/REFERENCE.md

Really just a small typo (or maybe an undocumented feature? :) )

REFERENCE - Fix small unligned typo

---

src/go/collectors/go.d.plugin/pkg/socket/client.go

go.d: socket package: don't set client on connect() err

---

src/go/collectors/go.d.plugin/config/go.d/sd/docker.conf

To try multiple status locations, same [as in network_listeners.conf](https://github.com/netdata/netdata/blob/9af7592fdbbf3ab7387c77accd2f9c93a8eee719/src/go/collectors/go.d.plugin/config/go.d/sd/net_listeners.conf#L274-L287).
</details>

go.d: sd docker: create multiple nginx configs

---

packaging/cmake/Modules/NetdataGoTools.cmake
src/go/collectors/go.d.plugin/cmd/godplugin/main.go
src/go/collectors/go.d.plugin/hack/go-build.sh
src/go/collectors/go.d.plugin/pkg/buildinfo/version.go
src/go/collectors/go.d.plugin/pkg/prometheus/client.go
src/go/collectors/go.d.plugin/pkg/web/request.go

go.d: set User-Agent automatically when creating HTTP req

---

.github/workflows/build.yml
.github/workflows/cloud_regression.yml
.github/workflows/docker.yml
.github/workflows/generate-integrations.yml
.github/workflows/monitor-releases.yml
.github/workflows/repoconfig-packages.yml
.github/workflows/review.yml

Many actions report errors, either in actions or in the scripts they run (via shellcheck) 
Trying to keep any commit as a single fix.
Note: I am NOT touching docker.yml workflow because it's under heavy rework
</details>

Fix action lints

---

src/go/collectors/go.d.plugin/agent/jobmgr/manager.go
src/go/collectors/go.d.plugin/config/go.d/sd/net_listeners.conf

go.d: don't create jobs with unknown module

---

src/database/rrdlabels.c

fix https://github.com/netdata/netdata/pull/17290

fix rrdlabels traversal

---

src/go/collectors/go.d.plugin/config/go.d/mysql.conf
src/go/collectors/go.d.plugin/config/go.d/sd/net_listeners.conf

go.d: sd ll: add mysql socket jobs

---

.github/workflows/docker.yml

Fix handling of post-release workflows triggered by Docker workflow.

---

.github/scripts/gen-docker-tags.py
.github/workflows/docker.yml

- Correctly handle publishing of images.
- Correctly add the `stable` tag in cases when it should be added.
- Send the proper version tag to the helmchart update workflow.
n/a

Fix assorted issues in the Docker build process.

---

src/go/collectors/go.d.plugin/modules/windows/config_schema.json

go.d: schema windows: fix url placeholder scheme

---

packaging/installer/kickstart.sh

fix invalid var in prepare_offline_install_source()

---

src/go/collectors/go.d.plugin/README.md
src/go/collectors/go.d.plugin/config/go.d.conf
src/go/collectors/go.d.plugin/config/go.d/intelgpu.conf
src/go/collectors/go.d.plugin/modules/init.go
src/go/collectors/go.d.plugin/modules/intelgpu/charts.go
src/go/collectors/go.d.plugin/modules/intelgpu/collect.go
src/go/collectors/go.d.plugin/modules/intelgpu/config_schema.json
src/go/collectors/go.d.plugin/modules/intelgpu/exec.go
src/go/collectors/go.d.plugin/modules/intelgpu/init.go
src/go/collectors/go.d.plugin/modules/intelgpu/intelgpu.go
src/go/collectors/go.d.plugin/modules/intelgpu/intelgpu_test.go
src/go/collectors/go.d.plugin/modules/intelgpu/metadata.yaml
src/go/collectors/go.d.plugin/modules/intelgpu/testdata/config.json
src/go/collectors/go.d.plugin/modules/intelgpu/testdata/config.yaml
src/go/collectors/go.d.plugin/modules/intelgpu/testdata/igt.json

add intel_gpu_top collector

---

integrations/gen_docs_integrations.py

add try except

---

src/go/collectors/go.d.plugin/modules/intelgpu/metadata.yaml

add prerequisites to go.d/intelgpu meta

---

packaging/installer/netdata-uninstaller.sh

uninstaller: remove LaunchDaemons plist file (macOS)

---

integrations/gen_docs_integrations.py

just a fix for the case a readme is not there

make file if not found

---

src/go/collectors/go.d.plugin/modules/intelgpu/charts.go
src/go/collectors/go.d.plugin/modules/intelgpu/metadata.yaml

go.d intelgpu: rename label engine to engine_class

---

src/go/collectors/go.d.plugin/config/go.d/intelgpu.conf
src/go/collectors/go.d.plugin/modules/intelgpu/metadata.yaml

Related #14931 and #17344
</details>

go.d intelgpu: uncomment stock config and update meta setup prerequisites

---

src/go/collectors/go.d.plugin/modules/intelgpu/intelgpu_test.go
src/go/collectors/go.d.plugin/modules/zfspool/config_schema.json
src/go/collectors/go.d.plugin/modules/zfspool/metadata.yaml

go.d zfspool minor schema and meta fixes

---

src/go/collectors/go.d.plugin/modules/intelgpu/metadata.yaml

go.d intelgpu meta update icon

---

src/collectors/plugins.d/ndsudo.c

add intel_gpu_top to ndsudo

---

src/collectors/plugins.d/ndsudo.c

hardcode ndsudo PATH

---

docs/dashboard/home-tab.md

"tab" should not be capitalized, looks funny

lowercase word

---

src/go/collectors/go.d.plugin/config/go.d/intelgpu.conf
src/go/collectors/go.d.plugin/modules/intelgpu/config_schema.json
src/go/collectors/go.d.plugin/modules/intelgpu/exec.go
src/go/collectors/go.d.plugin/modules/intelgpu/init.go
src/go/collectors/go.d.plugin/modules/intelgpu/intelgpu.go
src/go/collectors/go.d.plugin/modules/intelgpu/intelgpu_test.go
src/go/collectors/go.d.plugin/modules/intelgpu/metadata.yaml
src/go/collectors/go.d.plugin/modules/intelgpu/testdata/config.json
src/go/collectors/go.d.plugin/modules/intelgpu/testdata/config.yaml
src/go/collectors/go.d.plugin/modules/zfspool/init.go

go.d intelgpu switch to using ndsudo

---

src/go/collectors/go.d.plugin/modules/intelgpu/exec.go

go.d intelgpu: use cmd.Wait instead of process.Wait

---

src/go/collectors/go.d.plugin/config/go.d/zfspool.conf
src/go/collectors/go.d.plugin/modules/intelgpu/metadata.yaml
src/go/collectors/go.d.plugin/modules/nvme/config_schema.json
src/go/collectors/go.d.plugin/modules/nvme/exec.go
src/go/collectors/go.d.plugin/modules/nvme/init.go
src/go/collectors/go.d.plugin/modules/nvme/metadata.yaml
src/go/collectors/go.d.plugin/modules/nvme/nvme.go
src/go/collectors/go.d.plugin/modules/nvme/nvme_test.go

go.d nvme: drop using `nvme` directly

---

src/health/health_prototypes.c

Another regression...
Before dyncfg, alarms where having a higher priority compared to alarm templates. However they have been mixed in random order in prototypes.
This PR ensures alarms are applied before alarm templates, independently of the order they appear in configuration files.
@stelfrag this needs to go into minor bug fix release.

apply first alarms, then alarm templates

---

src/go/collectors/go.d.plugin/config/go.d/sd/net_listeners.conf

go.d sd ll set max_time_series for prometheus/clickhouse

---

src/go/collectors/go.d.plugin/modules/megacli/metadata.yaml

go.d megacli fix meta metrics_description

---

README.md

Updated CNCF link to Netdata
</details>

cncf changed the url

---

src/go/collectors/go.d.plugin/modules/adaptecraid/metadata.yaml

Invalid YAML format
```
:warning file=/home/runner/work/netdata/netdata/src/go/collectors/go.d.plugin/modules/adaptecraid/metadata.yaml:Failed to parse /home/runner/work/netdata/netdata/src/go/collectors/go.d.plugin/modules/adaptecraid/metadata.yaml as YAML.
```
</details>

go.d adaptec fix meta

---

src/go/collectors/go.d.plugin/modules/adaptecraid/metadata.yaml
src/go/collectors/go.d.plugin/modules/megacli/metadata.yaml

go.d fix adaptec/megacli meta name

---

src/database/sqlite/sqlite_health.c

* CID 425241:  Uninitialized variables  (UNINIT)
/src/database/sqlite/sqlite_health.c: 1551 in sql_alert_transitions()
- Add check for statement preparation failure
- Properly check for bind failure

Fix coverity issue 425241

---

integrations/gen_integrations.py

Indent generated files

---

src/go/collectors/go.d.plugin/modules/adaptecraid/metadata.yaml
src/go/collectors/go.d.plugin/modules/megacli/metadata.yaml

go.d mega/adaptec meta add alerts

---

src/daemon/main.c
src/daemon/sentry-native/sentry-native.c
src/daemon/sentry-native/sentry-native.h
src/registry/registry.h
src/registry/registry_internals.c

Need to figure out if multiple crash events occur on a single node.
- CI jobs,
- Wait for nightlies rollout.

Associate sentry events with guid.

---

docs/cloud/visualize/dashboards.md

Renamed the title to follow the pattern of the rest, if you don't like it I can revert it back to the old title
moved around some stuff and made certain edits.

dashboards doc edits

---

src/collectors/plugins.d/ndsudo.c

This is needed for #17454. A separate PR because it touches `c` code => much longer ci.
</details>

ndsudo add storcli

---

docs/cloud/alerts-notifications/manage-alert-notification-silencing-rules.md
src/claim/README.md

Add section for new feature on regenerating claiming token.
</details>

add section for regenerate claiming token

---

src/go/collectors/go.d.plugin/README.md
src/go/collectors/go.d.plugin/config/go.d.conf
src/go/collectors/go.d.plugin/config/go.d/sensors.conf
src/go/collectors/go.d.plugin/modules/init.go
src/go/collectors/go.d.plugin/modules/sensors/charts.go
src/go/collectors/go.d.plugin/modules/sensors/collect.go
src/go/collectors/go.d.plugin/modules/sensors/config_schema.json
src/go/collectors/go.d.plugin/modules/sensors/exec.go
src/go/collectors/go.d.plugin/modules/sensors/init.go
src/go/collectors/go.d.plugin/modules/sensors/metadata.yaml
src/go/collectors/go.d.plugin/modules/sensors/sensors.go
src/go/collectors/go.d.plugin/modules/sensors/sensors_test.go
src/go/collectors/go.d.plugin/modules/sensors/testdata/config.json
src/go/collectors/go.d.plugin/modules/sensors/testdata/config.yaml
src/go/collectors/go.d.plugin/modules/sensors/testdata/sensors-temp-in-curr-power-fan.txt
src/go/collectors/go.d.plugin/modules/sensors/testdata/sensors-temp.txt
src/go/collectors/go.d.plugin/modules/zfspool/zfspool_test.go

Related: #17456
Replacement for python.d/sensors.
</details>

go.d add sensors

---

src/go/collectors/go.d.plugin/agent/jobmgr/dyncfg.go
src/go/collectors/go.d.plugin/modules/windows/config_schema.json
src/go/collectors/go.d.plugin/modules/windows/testdata/config.json
src/go/collectors/go.d.plugin/modules/windows/testdata/config.yaml
src/go/collectors/go.d.plugin/modules/windows/windows.go

go.d windows add "vnode" to config schema

---

docs/guides/troubleshoot/monitor-debug-applications-ebpf.md
docs/quickstart/infrastructure.md
src/web/gui/custom/README.md

move dashboards file

---

src/go/collectors/go.d.plugin/config/go.d/nvidia_smi.conf
src/go/collectors/go.d.plugin/modules/nvidia_smi/config_schema.json
src/go/collectors/go.d.plugin/modules/nvidia_smi/metadata.yaml
src/go/collectors/go.d.plugin/modules/nvidia_smi/nvidia_smi.go

go.d nvidia_smi: use XML format by default

---

packaging/installer/methods/source.md

This documentation unfortunately was missed during the switch to the new build system.
n/a

Fix maintainer documentation to reflect the new build system.

---

src/go/collectors/go.d.plugin/modules/intelgpu/exec.go

Fixes: https://github.com/netdata/netdata/issues/17400#issuecomment-2069975414
</details>

go.d fix intelgpu with update_every > 3

---

src/collectors/plugins.d/ndsudo.c

ssia
Tested locally
</details>

add fail2ban-client to ndsudo

---

integrations/cloud-authentication/metadata.yaml

Add a better redirect
</details>

better redirect

---

src/go/collectors/go.d.plugin/README.md
src/go/collectors/go.d.plugin/config/go.d.conf
src/go/collectors/go.d.plugin/config/go.d/fail2ban.conf
src/go/collectors/go.d.plugin/modules/fail2ban/charts.go
src/go/collectors/go.d.plugin/modules/fail2ban/collect.go
src/go/collectors/go.d.plugin/modules/fail2ban/config_schema.json
src/go/collectors/go.d.plugin/modules/fail2ban/exec.go
src/go/collectors/go.d.plugin/modules/fail2ban/fail2ban.go
src/go/collectors/go.d.plugin/modules/fail2ban/fail2ban_test.go
src/go/collectors/go.d.plugin/modules/fail2ban/init.go
src/go/collectors/go.d.plugin/modules/fail2ban/metadata.yaml
src/go/collectors/go.d.plugin/modules/fail2ban/testdata/config.json
src/go/collectors/go.d.plugin/modules/fail2ban/testdata/config.yaml
src/go/collectors/go.d.plugin/modules/fail2ban/testdata/fail2ban-jail-status.txt
src/go/collectors/go.d.plugin/modules/fail2ban/testdata/fail2ban-status.txt
src/go/collectors/go.d.plugin/modules/init.go
src/go/collectors/go.d.plugin/modules/lvm/lvm_test.go

add go.d fail2ban

---

docs/netdata-cloud/enterprise-sso-authentication.md
integrations/cloud-authentication/metadata.yaml

Sso improvements

---

src/database/sqlite/sqlite_aclk.c
src/database/sqlite/sqlite_aclk_alert.c
src/database/sqlite/sqlite_context.c
src/database/sqlite/sqlite_db_migration.c
src/database/sqlite/sqlite_functions.c
src/database/sqlite/sqlite_functions.h
src/database/sqlite/sqlite_health.c
src/database/sqlite/sqlite_metadata.c

- Add macros for sqlite3_finalize and sqlite3_reset
- Use macro to make parameter binding more readable

Additional SQL code cleanup

---

src/go/collectors/go.d.plugin/modules/traefik/collect.go

go.d traefik fix "got a SET but dimension does not exist"

---

src/go/collectors/go.d.plugin/modules/prometheus/charts.go

go.d prometheus fix units for snmp_exporter

---

docs/category-overview-pages/accessing-netdata-dashboards.md

I also want to move the file, but let's do so in another PR so we can review this

update the file

---

packaging/installer/kickstart.sh

Fixes: #17525
Thanks to @zoberox for identifying the problem and solving it.
</details>

fix _ndpath in detect_existing_install()

---

integrations/cloud-authentication/metadata.yaml

Add  supported feature as request from Okta review process
Ref: Please add the Supported features section (https://developer.okta.com/docs/guides/submit-app-prereq/main/#supported-features) to the doc also
</details>

add features section requested on Okta review

---

.github/workflows/platform-eol-check.yml

Instead of assigning to individuals, assign directly to @netdata/agent-sre.
n/a

Fix platform EOL check issue assignment.

---

src/go/collectors/go.d.plugin/README.md
src/go/collectors/go.d.plugin/config/go.d.conf
src/go/collectors/go.d.plugin/config/go.d/smartctl.conf
src/go/collectors/go.d.plugin/go.mod
src/go/collectors/go.d.plugin/go.sum
src/go/collectors/go.d.plugin/modules/init.go
src/go/collectors/go.d.plugin/modules/smartctl/charts.go
src/go/collectors/go.d.plugin/modules/smartctl/collect.go
src/go/collectors/go.d.plugin/modules/smartctl/config_schema.json
src/go/collectors/go.d.plugin/modules/smartctl/exec.go
src/go/collectors/go.d.plugin/modules/smartctl/init.go
src/go/collectors/go.d.plugin/modules/smartctl/metadata.yaml
src/go/collectors/go.d.plugin/modules/smartctl/scan.go
src/go/collectors/go.d.plugin/modules/smartctl/smart_device.go
src/go/collectors/go.d.plugin/modules/smartctl/smartctl.go
src/go/collectors/go.d.plugin/modules/smartctl/smartctl_test.go
src/go/collectors/go.d.plugin/modules/smartctl/testdata/config.json
src/go/collectors/go.d.plugin/modules/smartctl/testdata/config.yaml
src/go/collectors/go.d.plugin/modules/smartctl/testdata/type-nvme/device-nvme0.json
src/go/collectors/go.d.plugin/modules/smartctl/testdata/type-nvme/scan.json
src/go/collectors/go.d.plugin/modules/smartctl/testdata/type-sat/device-hdd-sda.json
src/go/collectors/go.d.plugin/modules/smartctl/testdata/type-sat/device-ssd-sdc.json
src/go/collectors/go.d.plugin/modules/smartctl/testdata/type-sat/scan.json

Fixes: #15032
Fixes: #7388
</details>

go.d smartctl

---

src/go/collectors/go.d.plugin/modules/smartctl/charts.go

Add some heuristics to find the unit of the SMART attribute.
</details>

go.d smartctl improve units

---

docs/cloud/insights/events-feed.md

@netdata/product I need your help in this, I have used the feed from cloud and the agent and can't figure out:
1. If it has the same features
2. I don't know the plan time-limits (who would know?)
3. I don't know the available list of events for the last section.
(I removed the pro plan, but I don't know the rest of the details)

Events tab documentation updates

---

src/go/collectors/go.d.plugin/modules/smartctl/charts.go
src/go/collectors/go.d.plugin/modules/smartctl/config_schema.json
src/go/collectors/go.d.plugin/modules/smartctl/init.go
src/go/collectors/go.d.plugin/modules/smartctl/metadata.yaml
src/go/collectors/go.d.plugin/modules/smartctl/scan.go
src/go/collectors/go.d.plugin/modules/smartctl/smart_device.go
src/go/collectors/go.d.plugin/modules/smartctl/smartctl.go
src/go/collectors/go.d.plugin/modules/smartctl/testdata/config.json
src/go/collectors/go.d.plugin/modules/smartctl/testdata/config.yaml

go.d smartctl small improvements

---

src/go/collectors/go.d.plugin/modules/smartctl/metadata.yaml

Forgot to add in #17565
</details>

go.d smartctl add meta setup prerequisites

---

packaging/cmake/Modules/NetdataProtobuf.cmake

This takes advantage of a number of specific behaviors of CMake and the protobuf package configuration and find package modules that I was not aware of when I wrote the code originally, as well as a few things I simply forgot about at the time, to significantly simplify the code responsible for bundling protobuf and for normalizing the protobuf related variables independently of the particular protobuf configuration we’re using.

Significantly simplify the protobuf handling in CMake.

---

src/go/collectors/go.d.plugin/modules/prometheus/charts.go
src/go/collectors/go.d.plugin/modules/prometheus/collect.go

go.d prometheus remove apostrophe in label values

---

packaging/makeself/install-or-update.sh

fix ndsudo setuid bit for static builds

---

src/collectors/python.d.plugin/python.d.plugin.in
src/collectors/python.d.plugin/python_modules/bases/loggers.py
src/go/collectors/go.d.plugin/logger/level.go

Related issue: #17485
</details>

go.d/python.d respect all netdata log levels

---

packaging/cmake/Modules/NetdataEBPFCORE.cmake
packaging/cmake/Modules/NetdataEBPFLegacy.cmake
packaging/cmake/Modules/NetdataLibBPF.cmake

Update eBPF code to v1.4.1.

---

src/go/collectors/go.d.plugin/modules/systemdunits/charts.go
src/go/collectors/go.d.plugin/modules/systemdunits/client.go
src/go/collectors/go.d.plugin/modules/systemdunits/collect.go
src/go/collectors/go.d.plugin/modules/systemdunits/collect_unit_files.go
src/go/collectors/go.d.plugin/modules/systemdunits/collect_units.go
src/go/collectors/go.d.plugin/modules/systemdunits/config_schema.json
src/go/collectors/go.d.plugin/modules/systemdunits/init.go
src/go/collectors/go.d.plugin/modules/systemdunits/metadata.yaml
src/go/collectors/go.d.plugin/modules/systemdunits/systemdunits.go
src/go/collectors/go.d.plugin/modules/systemdunits/systemdunits_test.go
src/go/collectors/go.d.plugin/modules/systemdunits/testdata/config.json
src/go/collectors/go.d.plugin/modules/systemdunits/testdata/config.yaml

go.d systemdunits add unit files state

---

src/go/collectors/go.d.plugin/agent/jobmgr/dyncfg.go
src/go/collectors/go.d.plugin/agent/jobmgr/manager_test.go

go.d dyncfg return 200 on Enable for running jobs

---

src/health/health.d/isc_dhcpd.conf

health update isc dhcp alarms

---

src/collectors/plugins.d/ndsudo.c

Needed to rewrite/deprecate [python.d/hpssa](https://github.com/netdata/netdata/tree/master/src/collectors/python.d.plugin/hpssa).
</details>

ndsudo add ssacli

---

src/collectors/systemd-journal.plugin/systemd-journal.c

logs: add ND_ALERT_STATUS to facets

---

src/go/collectors/go.d.plugin/modules/ping/config_schema.json

go.d ping add missing setting to schema

---

src/go/collectors/go.d.plugin/README.md
src/go/collectors/go.d.plugin/config/go.d.conf
src/go/collectors/go.d.plugin/config/go.d/hpssa.conf
src/go/collectors/go.d.plugin/modules/hpssa/charts.go
src/go/collectors/go.d.plugin/modules/hpssa/collect.go
src/go/collectors/go.d.plugin/modules/hpssa/config_schema.json
src/go/collectors/go.d.plugin/modules/hpssa/exec.go
src/go/collectors/go.d.plugin/modules/hpssa/hpssa.go
src/go/collectors/go.d.plugin/modules/hpssa/hpssa_test.go
src/go/collectors/go.d.plugin/modules/hpssa/init.go
src/go/collectors/go.d.plugin/modules/hpssa/metadata.yaml
src/go/collectors/go.d.plugin/modules/hpssa/parse.go
src/go/collectors/go.d.plugin/modules/hpssa/testdata/config.json
src/go/collectors/go.d.plugin/modules/hpssa/testdata/config.yaml
src/go/collectors/go.d.plugin/modules/hpssa/testdata/ssacli-P212_P410i.txt
src/go/collectors/go.d.plugin/modules/hpssa/testdata/ssacli-P400ar.txt
src/go/collectors/go.d.plugin/modules/hpssa/testdata/ssacli-P400i-unassigned.txt
src/go/collectors/go.d.plugin/modules/init.go

Replacement for [python.d/hpssa](https://github.com/netdata/netdata/tree/master/src/collectors/python.d.plugin/hpssa).
</details>

go.d hpssa

---

src/go/collectors/go.d.plugin/modules/hpssa/charts.go
src/go/collectors/go.d.plugin/modules/hpssa/metadata.yaml

go.d hpssa fix cache battery chart ctx

---

src/go/collectors/go.d.plugin/modules/cockroachdb/collect.go

go.d cockroachdb fix calculation

---

src/claim/README.md

files movearound

---

src/collectors/apps.plugin/apps_groups.conf

add rspamd to apps_groups.conf

---

netdata.spec.in

Re-enable ML for RHEL 7 and AL 2 RPM packages.

---

src/go/collectors/go.d.plugin/config/go.d/sd/net_listeners.conf

go.d sd fix rspamd classify match

---

CMakeLists.txt
src/database/sqlite/sqlite_aclk.c
src/streaming/rrdpush.c

Check compilation with h2o and cloud disabled. It should build properly now
Fixes #17632

Fix compilation without h2o, cloud enabled

---

src/go/collectors/go.d.plugin/agent/jobmgr/dyncfg.go

go.d dyncfg rm space yaml contentType

---

src/collectors/perf.plugin/metadata.yaml
src/go/collectors/go.d.plugin/agent/confgroup/cache.go
src/go/collectors/go.d.plugin/examples/simple/main.go
src/go/collectors/go.d.plugin/modules/dnsquery/init.go
src/go/collectors/go.d.plugin/modules/haproxy/init.go
src/go/collectors/go.d.plugin/modules/k8s_state/init.go
src/go/collectors/go.d.plugin/modules/k8s_state/state.go
src/go/collectors/go.d.plugin/modules/openvpn/client/client_test.go
src/go/collectors/go.d.plugin/modules/phpdaemon/client.go
src/go/collectors/go.d.plugin/modules/pika/pika_test.go
src/go/collectors/go.d.plugin/modules/portcheck/init.go
src/go/collectors/go.d.plugin/modules/scaleio/client/client.go
src/go/collectors/go.d.plugin/modules/supervisord/supervisord_test.go
src/go/collectors/go.d.plugin/modules/traefik/collect.go
src/go/collectors/go.d.plugin/modules/traefik/init.go
src/go/collectors/go.d.plugin/modules/traefik/traefik.go
src/go/collectors/go.d.plugin/modules/vsphere/match/match.go
src/go/collectors/go.d.plugin/modules/vsphere/resources/resources.go
src/go/collectors/go.d.plugin/modules/vsphere/scrape/scrape.go
src/go/collectors/go.d.plugin/modules/x509check/collect.go
src/go/collectors/go.d.plugin/pkg/logs/reader.go
src/go/collectors/go.d.plugin/pkg/matcher/simple_patterns.go
src/go/collectors/go.d.plugin/pkg/matcher/string.go

go.d fix some JB code inspection issues

---

docs/dashboards-and-charts/events-feed.md
docs/developer-and-contributor-corner/style-guide.md
docs/netdata-agent/configuration/optimizing-metrics-database/change-metrics-storage.md
docs/observability-centralization-points/metrics-centralization-points/configuration.md
packaging/installer/README.md
packaging/installer/methods/macos.md
src/web/gui/README.md

some markdown fixes

---

docs/netdata-agent/configuration/common-configuration-changes.md

merge after https://github.com/netdata/learn/pull/2090

Change links to relative links in one doc

---

src/claim/README.md

minor fix on link

---

src/go/collectors/go.d.plugin/modules/systemdunits/client.go
src/go/collectors/go.d.plugin/modules/systemdunits/collect_units.go
src/go/collectors/go.d.plugin/modules/systemdunits/config_schema.json
src/go/collectors/go.d.plugin/modules/systemdunits/metadata.yaml
src/go/collectors/go.d.plugin/modules/systemdunits/systemdunits.go
src/go/collectors/go.d.plugin/modules/systemdunits/systemdunits_test.go
src/go/collectors/go.d.plugin/modules/systemdunits/testdata/config.json
src/go/collectors/go.d.plugin/modules/systemdunits/testdata/config.yaml

go.d systemdunits add "skip_transient"

---

docs/alerts-and-notifications/creating-alerts-with-netdata-alerts-configuration-manager.md
docs/alerts-and-notifications/notifications/centralized-cloud-notifications/centralized-cloud-notifications-reference.md
docs/alerts-and-notifications/notifications/centralized-cloud-notifications/manage-alert-notification-silencing-rules.md
docs/alerts-and-notifications/notifications/centralized-cloud-notifications/manage-notification-methods.md

capitalize stuff that is Netdata specific, and read the file to check for grammar mishaps. Also format the files

grammar pass on alerts and notifications dir

---

src/collectors/ebpf.plugin/ebpf_swap.h

fix ebpf cgroup swap context

---

src/collectors/apps.plugin/apps_groups.conf

Existing pattern never worked
</details>

fix clickhouse in apps groups

---

src/go/collectors/go.d.plugin/modules/clickhouse/charts.go
src/go/collectors/go.d.plugin/modules/clickhouse/clickhouse_test.go
src/go/collectors/go.d.plugin/modules/clickhouse/collect_system_metrics.go
src/go/collectors/go.d.plugin/modules/clickhouse/metadata.yaml

go.d clickhouse add running queries

---

docs/dashboards-and-charts/netdata-charts.md
docs/metric-correlations.md

closes https://github.com/netdata/learn/issues/2098

mention how to remove highlight in documentation

---

docs/collecting-metrics/application-metrics.md
docs/collecting-metrics/container-metrics.md
docs/collecting-metrics/system-metrics.md
docs/deployment-guides/README.md
docs/deployment-guides/deployment-strategies.md
docs/deployment-guides/deployment-with-centralization-points.md
docs/deployment-guides/standalone-deployment.md

I removed some sections that felt out of date and tried to simplify the pages a bit.
@ilyam8 can you fill in the containers-vms function snippet? I am not sure what it provides, as far as I can understand it gives "resource utilization" about containers and vms, but I could not find any other info about it.

Collecting metrics docs grammar pass

---

packaging/installer/README.md

Simplified the page, and put the gist of it at the top, this is the overview page, so it should just point to Cloud. Also removed some old stuff (added >2 yrs back).
the nightly vs stable section I don't like all that much, but I left it in.

simplify installation page

---

src/go/collectors/go.d.plugin/modules/clickhouse/metadata.yaml
src/health/health.d/clickhouse.conf

add clickhouse alerts

---

src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/netlisteners/netlisteners.go
src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/netlisteners/netlisteners_test.go

go.d sd local-listeners fix extractComm

---

docs/netdata-agent/configuration/running-the-netdata-agent-behind-a-reverse-proxy/Running-behind-apache.md
docs/netdata-agent/configuration/running-the-netdata-agent-behind-a-reverse-proxy/Running-behind-h2o.md
docs/netdata-agent/configuration/running-the-netdata-agent-behind-a-reverse-proxy/Running-behind-nginx.md

docs fix "Prevent the double access.log"

---

src/collectors/statsd.plugin/README.md

docs fix statsd conf dir

---

.github/scripts/pkg-test.sh

This fixes publishing of 32-bit x86 DEB packages.

Correctly handle eBPF check in package test script.

---

.github/data/distros.yml

Add Alpine 3.20 to CI checks.

---

src/collectors/cgroups.plugin/sys_fs_cgroup.c

```c
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f8351e2e537 in __GI_abort () at abort.c:79
#2  0x00007f8351e863e8 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f8351fa4187 "*** %s ***: terminated\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f8351f17582 in __GI___fortify_fail (msg=msg@entry=0x7f8351fa411d "buffer overflow detected") at fortify_fail.c:26
#4  0x00007f8351f15f60 in __GI___chk_fail () at chk_fail.c:28
#5  0x00007f8351f174d7 in __fdelt_chk (d=d@entry=2955) at fdelt_chk.c:25
#6  0x000055f2e4386d71 in cgroups_detect_systemd (exec=exec@entry=0x55f2e478aa66 "systemd --version") at ../src/collectors/cgroups.plugin/sys_fs_cgroup.c:115
#7  0x000055f2e438907e in cgroups_try_detect_version () at …
```

fix buffer overflow incgroups_detect_systemd()

---

src/collectors/freebsd.plugin/freebsd_devstat.c
src/collectors/freebsd.plugin/freebsd_getifaddrs.c
src/collectors/freebsd.plugin/freebsd_getmntinfo.c
src/collectors/freebsd.plugin/freebsd_sysctl.c

Compile on a FreeBSD vm.
</details>

remove "ingore zero metrics" from freebsd plugin

---

src/collectors/macos.plugin/macos_sysctl.c

remove "ingore 0 metrics" from macos plugin

---

src/go/collectors/go.d.plugin/modules/lvm/metadata.yaml
src/health/health.d/lvm.conf

Requested in https://github.com/netdata/netdata/issues/13588#issuecomment-2146324476
</details>

health: add go.d/lvm alerts

---

src/collectors/cgroups.plugin/tests/test_cgroups_plugin.c
src/collectors/proc.plugin/sys_fs_btrfs.c
src/collectors/proc.plugin/sys_kernel_mm_ksm.c
src/collectors/tc.plugin/plugin_tc.c

remove "ignore 0 metrics" from tc/btrfs/ksm

---

src/go/collectors/go.d.plugin/modules/ping/metadata.yaml

Typo: `round tripe` → `round trip`
</details>

fix typo: `round tripe` → `round trip`

---

src/collectors/freebsd.plugin/freebsd_kstat_zfs.c
src/collectors/proc.plugin/proc_pagetypeinfo.c
src/collectors/proc.plugin/proc_spl_kstat_zfs.c
src/collectors/proc.plugin/proc_vmstat.c
src/collectors/proc.plugin/sys_devices_system_node.c
src/collectors/proc.plugin/zfs_common.c
src/collectors/proc.plugin/zfs_common.h
src/daemon/common.h
src/daemon/main.c

remove "ignore 0 metrics" leftovers

---

src/collectors/ebpf.plugin/ebpf_fd.c
src/collectors/ebpf.plugin/ebpf_fd.h
src/collectors/ebpf.plugin/ebpf_filesystem.c
src/collectors/ebpf.plugin/ebpf_hardirq.c
src/collectors/ebpf.plugin/ebpf_hardirq.h
src/collectors/ebpf.plugin/ebpf_mdflush.c
src/collectors/ebpf.plugin/ebpf_mount.c
src/collectors/ebpf.plugin/ebpf_process.c
src/collectors/ebpf.plugin/ebpf_shm.c
src/collectors/ebpf.plugin/ebpf_softirq.c
src/collectors/ebpf.plugin/ebpf_swap.c
src/collectors/ebpf.plugin/ebpf_sync.c
src/collectors/ebpf.plugin/metadata.yaml

This PR continue with eBPF adjusts, this time we are updating the remaining threads, except the two largest threads (socket and VFS).
1. Take a look in CI for possible errors.
2. Compile locally and verify charts are visible.
</details>

Update contexts - eBPF.plugin (part II)

---

src/collectors/idlejitter.plugin/plugin_idlejitter.c
src/collectors/timex.plugin/plugin_timex.c
src/web/api/http_header.c

Add missing check
- Add missing check and proper check for thread pointer being NULL during cleanup
- CID 425866

Proper check for static_thread being NULL

---

src/claim/README.md

Follow up on netdata/cloud-frontend#4581
</details>

docs: claiming: rename connect button

---

src/collectors/ebpf.plugin/ebpf_socket.c
src/collectors/ebpf.plugin/ebpf_vfs.c

This is the last PR addressing issues with eBPF contexts. This PR address issues with the threads with more charts.
1. Take a look on CI
2. Compile branches and check charts.
</details>

Sockets VFS (context update)

---

src/health/health_dyncfg.c

health dyncfg userconfig: remove first newline

---

src/collectors/tc.plugin/plugin_tc.c

tc plugin simplify config

---

src/collectors/tc.plugin/plugin_tc.c

Leftovers from #17835
</details>

fix tc plugin undeclared vars

---

src/database/sqlite/sqlite_functions.c

Not needed by users.
</details>

hide sqlite config (netdata.conf)

---

src/aclk/aclk_proxy.c
src/claim/README.md
src/claim/netdata-claim.sh.in

aclk: move "proxy" from "netdata.conf" to "cloud.conf"

---

src/daemon/main.c
src/daemon/service.c
src/database/contexts/api_v2.c
src/web/api/queries/query.c

- Fix compilation error when disable-engine is requested

Fix compilation without dbengine

---

src/collectors/proc.plugin/proc_net_stat_synproxy.c

Remove unused variable

---

src/daemon/service.c

fix: check memory mode before creating dbengine retention chart

---

src/health/health_dyncfg.c
src/health/schema.d/health%3Aalert%3Aprototype.json
src/libnetdata/json/json-c-parser-inline.h

allow userconfig to generate incomplete configurations for health alerts

DYNCFG: health, generate userconfig for incomplete alerts

---

.github/scripts/package-upload.sh
.github/scripts/upload-new-version-tags.sh
.github/workflows/kickstart-upload.yml
.github/workflows/monitor-releases.yml
.github/workflows/packaging.yml
.github/workflows/repoconfig-packages.yml

Update CI infrastructure to publish to secondary packaging host.

---

.github/data/distros.yml
netdata.spec.in

Add openSUSE 15.6 to CI.

---

src/go/collectors/go.d.plugin/modules/filecheck/metadata.yaml

- Move it to the Other category, because it isn’t Linux specific and we have no other category that really fits it.
- Expand the description of the plugin to more concretely describe what it does.
- Expand the explanation of the required capabilities so that it’s more obvious why they are needed.
n/a

Improve filecheck module metadata.

---

netdata-installer.sh

fix detect_libc in installer

---

src/collectors/plugins.d/ndsudo.c

Needed for #17881
Add:
- list available GPUs (`igt-list-gpus`)
- monitor specific GPU (`igt-device-json`)
</details>

ndsudo update intel_gpu_top

---

src/go/collectors/go.d.plugin/modules/intelgpu/config_schema.json
src/go/collectors/go.d.plugin/modules/intelgpu/exec.go
src/go/collectors/go.d.plugin/modules/intelgpu/init.go
src/go/collectors/go.d.plugin/modules/intelgpu/intelgpu.go
src/go/collectors/go.d.plugin/modules/intelgpu/metadata.yaml
src/go/collectors/go.d.plugin/modules/intelgpu/testdata/config.json
src/go/collectors/go.d.plugin/modules/intelgpu/testdata/config.yaml

Fixes: #17881
Needs: #17883
</details>

go.d intelgpu add an option to select specific GPU

---

src/health/health_config.c
src/health/health_dyncfg.c
src/health/health_internals.h
src/health/health_prototypes.c
src/health/schema.d/health%3Aalert%3Aprototype.json

Alerts can now be created without requiring all the fields filled.

allow alerts to be created without too many requirements

---

src/go/collectors/go.d.plugin/modules/whoisquery/provider.go

go.d whoisquery: check if exp date is empty

---

src/go/collectors/go.d.plugin/modules/nvme/metadata.yaml

Add example how to use nvme in a docker.

Update nvme/metadata: add how to use in a docker

---

src/go/collectors/go.d.plugin/modules/whoisquery/provider.go
src/go/collectors/go.d.plugin/modules/whoisquery/whoisquery_test.go

go.d whoisquery: try requesting extended data if no expiration date

---

src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/dockerd/dockerd_test.go
src/go/collectors/go.d.plugin/go.mod
src/go/collectors/go.d.plugin/go.sum
src/go/collectors/go.d.plugin/modules/docker/collect.go
src/go/collectors/go.d.plugin/modules/docker/docker.go
src/go/collectors/go.d.plugin/modules/docker/docker_test.go

go.d bump github.com/docker/docker v27.0.0+incompatible

---

src/go/collectors/go.d.plugin/modules/whoisquery/provider.go

go.d whoisquery: use Domain.ExpirationDateInTime if provided

---

src/go/collectors/go.d.plugin/modules/whoisquery/config_schema.json
src/go/collectors/go.d.plugin/modules/whoisquery/metadata.yaml

go.d whoisquery fix defaults in config_schema

---

src/go/collectors/go.d.plugin/modules/storcli/charts.go
src/go/collectors/go.d.plugin/modules/storcli/collect.go
src/go/collectors/go.d.plugin/modules/storcli/collect_controllers.go
src/go/collectors/go.d.plugin/modules/storcli/collect_drives.go
src/go/collectors/go.d.plugin/modules/storcli/metadata.yaml
src/go/collectors/go.d.plugin/modules/storcli/storcli_test.go
src/go/collectors/go.d.plugin/modules/storcli/testdata/mpt3sas-controllers-info.json
src/health/health.d/storcli.conf

The issue with mpt3sas controllers was [reported on Discord](https://discord.com/channels/847502280503590932/1252285433224757329/1252285433224757329).
</details>

go.d storcli add initial support for mpt3sas controllers

---

src/exporting/prometheus/metadata.yaml

Fixes: netdata/learn#1944
</details>

add OpenSearch to exporting prom meta

---

src/collectors/plugins.d/ndsudo.c

add "dmsetup status --target cache --noflush" to ndsudo

---

src/go/collectors/go.d.plugin/config/go.d/dns_query.conf

The issue was [reported on Discord](https://discord.com/channels/847502280503590932/1252291417494257714/1252558231838920784).
</details>

fix indentation in go.d/dnsquery conf

---

src/go/collectors/go.d.plugin/README.md
src/go/collectors/go.d.plugin/config/go.d.conf
src/go/collectors/go.d.plugin/config/go.d/dmcache.conf
src/go/collectors/go.d.plugin/modules/dmcache/charts.go
src/go/collectors/go.d.plugin/modules/dmcache/collect.go
src/go/collectors/go.d.plugin/modules/dmcache/config_schema.json
src/go/collectors/go.d.plugin/modules/dmcache/dmcache.go
src/go/collectors/go.d.plugin/modules/dmcache/dmcache_test.go
src/go/collectors/go.d.plugin/modules/dmcache/exec.go
src/go/collectors/go.d.plugin/modules/dmcache/init.go
src/go/collectors/go.d.plugin/modules/dmcache/metadata.yaml
src/go/collectors/go.d.plugin/modules/dmcache/testdata/config.json
src/go/collectors/go.d.plugin/modules/dmcache/testdata/config.yaml
src/go/collectors/go.d.plugin/modules/init.go

go.d add dmcache collector

---

README.md

... and fix some typos.
</details>

remove Discord badge (rate limited by upstream service)

---

docs/netdata-agent/configuration/optimizing-metrics-database/change-metrics-storage.md

docs: add time-based retention to "Change how long Netdata stores metrics"

---

docs/netdata-agent/configuration/optimizing-metrics-database/change-metrics-storage.md

docs: clarify setting time/disk limits to 0

---

src/collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh

Fixes the issue when SLAVEDOWN triggers SLAVE. I missed that issue in #17960.
</details>

fix apcupsd status "slave"

---

src/go/collectors/go.d.plugin/agent/jobmgr/dyncfg.go

go.d dyncfg add job name validation

---

src/go/collectors/go.d.plugin/modules/rspamd/collect.go

fix go.d rspamd unexpected response check

---

src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/dockerd/docker.go
src/go/collectors/go.d.plugin/modules/docker/docker.go
src/go/collectors/go.d.plugin/pkg/dockerhost/dockerhost.go

go.d docker respect DOCKER_HOST env var

---

src/health/health.d/ping.conf

Fixes: #17976 I hope, although I can't reproduce it
</details>

improve ping_host_reachable alert calc

---

src/collectors/cgroups.plugin/sys_fs_cgroup.c

Prefer the `/sys/fs/cgroup/` type over heuristics.
From [systemd docs](https://github.com/systemd/systemd/blob/main/docs/CGROUP_DELEGATION.md#three-different-tree-setups-):
> If you wonder how to detect which of these three modes is currently used, use statfs() on /sys/fs/cgroup/. If it reports CGROUP2_SUPER_MAGIC in its .f_type field, then you are in **unified mode**. If it reports TMPFS_MAGIC then you are either in **legacy** or **hybrid mode**. To distinguish these two cases, run statfs() again on /sys/fs/cgroup/unified/. If that succeeds and reports CGROUP2_SUPER_MAGIC you are in **hybrid mode**, otherwise not.
This PR implements ^^ but for both hybrid and legacy we use v1 (same as before).
- cgroups v1 host (deb11, amazon linux2).
- cgroups v2 host (deb12).
<details> <summary>For …

make cgroups version detection more reliable

---

src/collectors/cgroups.plugin/cgroup-internals.h
src/collectors/cgroups.plugin/sys_fs_cgroup.c
src/database/engine/rrdengine.c
src/go/collectors/go.d.plugin/agent/confgroup/config.go
src/go/collectors/go.d.plugin/agent/jobmgr/dyncfg.go
src/go/collectors/go.d.plugin/modules/rspamd/collect.go
src/libnetdata/libnetdata.c

- Change logging to debug  (#17983)
- fix go.d rspamd unexpected response check (#17974)
- go.d dyncfg add job name validation (#17971)
- go.d replace colon in job name (#17967)
- cgroups: bring back "use unified cgroups" option (#17969)
- Fix space percentage calculation in dbengine retention chart (#17963)

Patch release 1.46.1

---

src/go/collectors/go.d.plugin/modules/whoisquery/whoisquery.go
src/go/collectors/go.d.plugin/modules/whoisquery/whoisquery_test.go

To reflect collectors' documentation.
The issue reported in #17994.
</details>

go.d whoisquery change  default days until expiration 90/30 => 30/15

---

src/collectors/apps.plugin/apps_output.c

Just useless charts.
</details>

apps.plugin: remove "Normalization Ratio" internal charts

---

integrations/templates/troubleshooting.md

This change applies only for go.d/python.d/charts.d collectors.
</details>

docs: add Troubleshoot->Getting Logs section to collectors

---

.github/workflows/packaging.yml
.github/workflows/repoconfig-packages.yml

Fix Slack error reporting for packaging workflows.

---

src/database/rrdlabels.c

We shouldn't lowercase A-Z in the label name.
</details>

rrdlabels: allow uppercase A-Z in label name

---

src/go/collectors/go.d.plugin/modules/ping/metadata.yaml

Same as #18019 
Thanks, @cuu508!
</details>

ping meta fix configuring ping_group_range

---

src/go/collectors/go.d.plugin/modules/snmp/collect.go
src/go/collectors/go.d.plugin/modules/snmp/config.go
src/go/collectors/go.d.plugin/modules/snmp/config_schema.json
src/go/collectors/go.d.plugin/modules/snmp/init.go
src/go/collectors/go.d.plugin/modules/snmp/metadata.yaml
src/go/collectors/go.d.plugin/modules/snmp/snmp.go
src/go/collectors/go.d.plugin/modules/snmp/testdata/config.json
src/go/collectors/go.d.plugin/modules/snmp/testdata/config.yaml

go.d snmp: add config options to filter interfaces by name and type

---

src/go/collectors/go.d.plugin/modules/k8s_state/collect.go
src/go/collectors/go.d.plugin/modules/k8s_state/update_pod_state.go

go.d k8state: skip jobs/cronjobs Pods

---

docs/alerts-and-notifications/notifications/centralized-cloud-notifications/manage-notification-methods.md
docs/netdata-cloud/authentication-and-authorization/role-based-access-model.md

Edits regarding changes in https://github.com/netdata/cloud-backend/issues/572.

Troubleshooter must be assigned to rooms docs

---

packaging/docker/README.md
src/collectors/diskspace.plugin/plugin_diskspace.c
src/collectors/proc.plugin/proc_self_mountinfo.c
src/collectors/proc.plugin/proc_self_mountinfo.h

Closes: #17899
Install ND Docker with `-v /:/host/root:ro,rslave` and check mount points charts.
</details>

fix diskspace plugin in Docker

---

src/go/collectors/go.d.plugin/modules/weblog/metadata.yaml

docs: fix go.d/weblog parser config

---

src/collectors/diskspace.plugin/plugin_diskspace.c

diskspace: update exclude paths/filesystems

---

src/collectors/proc.plugin/proc_diskstats.c

Fixes: #14089
See before/after for a low-latency device (nvme):
---
❗ Breaking change for the following metrics when exported as collected (`?sources=as-collected`) in Prometheus format:
- disk.svctm
- disk.await
- disk_ext.await
Milliseconds => microseconds.
</details>

proc/diskstats: Increase accuracy of average IO operation time

---

integrations/deploy.yaml

Follow up on #18035. Nightly version only.
</details>

docs: deploy docker add host root mount

---

src/go/collectors/go.d.plugin/modules/chrony/charts.go
src/go/collectors/go.d.plugin/modules/chrony/chrony.go
src/go/collectors/go.d.plugin/modules/chrony/chrony_test.go
src/go/collectors/go.d.plugin/modules/chrony/client.go
src/go/collectors/go.d.plugin/modules/chrony/collect.go

go.d chrony add serverstats query (disabled for now)

---

src/go/plugin/go.d/modules/vsphere/config_schema.json

go.d vsphere add update_every ui:help

---

src/daemon/static_threads.c

- Disable health thread only on windows

Disable health thread on windows

---

netdata.spec.in

Fixes https://github.com/netdata/netdata/pull/18063#issuecomment-2206924046
</details>

update golang version in netdata.spec

---

src/go/plugin/go.d/modules/ipfs/charts.go
src/go/plugin/go.d/modules/ipfs/ipfs_test.go
src/go/plugin/go.d/modules/ipfs/metadata.yaml

and update metadata
</details>

go.d ipfs fix tests

---

src/collectors/proc.plugin/plugin_proc.c
src/collectors/proc.plugin/plugin_proc.h
src/collectors/proc.plugin/proc_meminfo.c
src/collectors/proc.plugin/proc_vmstat.c

proc: collect ksm/swap/cma/zswap only when feature enabled

---

src/collectors/plugins.d/ndsudo.c
src/go/plugin/go.d/modules/fail2ban/exec.go
src/go/plugin/go.d/modules/fail2ban/metadata.yaml

go.d fail2ban: add docker support

---

.github/workflows/generate-integrations.yml
docs/developer-and-contributor-corner/collect-unbound-metrics.md
src/go/plugin/go.d/README.md
src/go/plugin/go.d/agent/README.md
src/go/plugin/go.d/docs/how-to-write-a-module.md
src/go/plugin/go.d/modules/bind/README.md
src/go/plugin/go.d/modules/coredns/config_schema.json
src/go/plugin/go.d/modules/example/README.md
src/go/plugin/go.d/modules/httpcheck/config_schema.json
src/go/plugin/go.d/modules/isc_dhcpd/config_schema.json
src/go/plugin/go.d/modules/mongodb/config_schema.json
src/go/plugin/go.d/modules/openvpn/config_schema.json
src/go/plugin/go.d/modules/openvpn_status_log/config_schema.json
src/go/plugin/go.d/modules/ping/config_schema.json
src/go/plugin/go.d/modules/prometheus/config_schema.json
src/go/plugin/go.d/modules/weblog/config_schema.json
src/go/plugin/go.d/pkg/README.md
src/go/plugin/go.d/pkg/iprange/README.md
src/go/plugin/go.d/pkg/matcher/README.md
src/go/plugin/go.d/pkg/prometheus/selector/README.md

update go.d path in docs and ci

---

src/go/logger/journal_linux.go
src/go/logger/journal_stub.go
src/go/logger/logger.go

go.d fix compiling for windows

---

src/go/plugin/go.d/modules/chrony/charts.go
src/go/plugin/go.d/modules/chrony/collect.go
src/go/plugin/go.d/modules/megacli/collect_bbu.go
src/go/plugin/go.d/modules/megacli/collect_phys_drives.go
src/go/plugin/go.d/modules/smartctl/smart_device.go

go.d megacli: return error if no adapters found (parsing failed)

---

integrations/deploy.yaml

`''` => `""` change is vscode auto-formatting. I didn't notice it before the PR.
The same change I did in #18051. This time for the stable version, the necessary changes are in version 1.46.2.
</details>

docs: deploy docker add host root mount (stable)

---

CMakeLists.txt
src/collectors/network-viewer.plugin/network-viewer.c
src/libnetdata/maps/system-services.h

The network connection function now get service names from /etc/services.

add port service names to network viewer

---

src/streaming/stream.conf

It is more convenient to have it right after "destination".
</details>

move "api key" option in stream.conf

---

src/claim/claim.c

minor to log in one log entry.

log in the same line

---

src/go/plugin/go.d/modules/whoisquery/config_schema.json

Forgot to change in #18000.
</details>

go.d whoisquery fix "days until" in config_schema.json

---

src/go/plugin/go.d/modules/filecheck/charts.go

go.d filecheck fix dir existence chart label

---

src/libnetdata/spawn_server/spawn_server.c

add a magic number to all spawn server replies to ensure they are not corrupted

Spawn server fixes No 4

---

src/go/plugin/go.d/modules/consul/collect.go
src/go/plugin/go.d/modules/couchbase/collect.go
src/go/plugin/go.d/modules/couchdb/collect.go
src/go/plugin/go.d/modules/dnsdist/collect.go
src/go/plugin/go.d/modules/elasticsearch/collect.go
src/go/plugin/go.d/modules/ipfs/collect.go
src/go/plugin/go.d/modules/logstash/collect.go
src/go/plugin/go.d/modules/nginxplus/nginx_http_api_query.go
src/go/plugin/go.d/modules/pihole/collect.go
src/go/plugin/go.d/modules/powerdns/collect.go
src/go/plugin/go.d/modules/powerdns_recursor/collect.go
src/go/plugin/go.d/modules/puppet/collect.go
src/go/plugin/go.d/modules/rabbitmq/collect.go
src/go/plugin/go.d/modules/rspamd/collect.go
src/go/plugin/go.d/pkg/web/request.go
src/go/plugin/go.d/pkg/web/request_test.go

go.d fix url path overwrite

---

src/go/plugin/go.d/modules/mysql/metadata.yaml

docs: go.d mysql: remove unix sockets from auto_detection

---

src/go/plugin/go.d/modules/smartctl/collect.go
src/go/plugin/go.d/modules/smartctl/config_schema.json
src/go/plugin/go.d/modules/smartctl/init.go
src/go/plugin/go.d/modules/smartctl/metadata.yaml
src/go/plugin/go.d/modules/smartctl/scan.go
src/go/plugin/go.d/modules/smartctl/smartctl.go
src/go/plugin/go.d/modules/smartctl/smartctl_test.go
src/go/plugin/go.d/modules/smartctl/testdata/config.json
src/go/plugin/go.d/modules/smartctl/testdata/config.yaml
src/go/plugin/go.d/modules/smartctl/testdata/type-nvme/device-nvme1.json

go.d smartctl add "extra_devices" option

---

src/collectors/plugins.d/ndsudo.c

ndsudo add smartctl scan-open

---

src/go/plugin/go.d/modules/smartctl/collect.go
src/go/plugin/go.d/modules/smartctl/config_schema.json
src/go/plugin/go.d/modules/smartctl/metadata.yaml
src/go/plugin/go.d/modules/smartctl/scan.go
src/go/plugin/go.d/modules/smartctl/smartctl.go

go.d smartctl: do scan only once on startup if interval is 0

---

.github/workflows/platform-eol-check.yml

Fix issue in platform EOL check workflow.

---

.github/scripts/platform-impending-eol.py

Fix logic bug in platform EOL check code.

---

src/health/notifications/alarm-notify.sh.in
src/health/notifications/health_alarm_notify.conf
src/health/notifications/telegram/metadata.yaml

[Requested on Discord](https://discord.com/channels/847502280503590932/1262269709697421413/1262269709697421413).
</details>

add support for sending Telegram notifications to topics

---

src/go/plugin/go.d/modules/smartctl/metadata.yaml

docs: add "install smartmontools" for Docker netdata

---

src/go/plugin/go.d/modules/postfix/metadata.yaml

small addition, while I was doing ap I saw we could add some stuff to postfix meta

Addition to postfix meta

---

src/go/plugin/go.d/modules/smartctl/exec.go
src/go/plugin/go.d/modules/smartctl/scan.go
src/go/plugin/go.d/modules/smartctl/smartctl.go
src/go/plugin/go.d/modules/smartctl/smartctl_test.go

go.d smarctl simplify scan open

---

src/go/plugin/go.d/modules/ap/metadata.yaml

docs: go.d/ap update data_collection description

---

.gitmodules

Not needed after #18186
</details>

remove fluent-bit submodule

---

src/database/sqlite/sqlite_aclk_alert.c

- Do not include alerts with status REMOVED in the alert snapshot. This will reduce the payload send to the cloud
All alerts not included in the snapshot are handled by the cloud

Do not include REMOVED status in the alert snapshot

---

docs/netdata-agent/sizing-netdata-agents/disk-requirements-and-retention.md

docs: simplify "Disk Requirements and Retention"

---

src/go/plugin/go.d/modules/megacli/charts.go
src/go/plugin/go.d/modules/megacli/collect_bbu.go
src/go/plugin/go.d/modules/megacli/megacli_test.go
src/go/plugin/go.d/modules/megacli/metadata.yaml

go.d megacli: add bbu capacity degradation %

---

CMakeLists.txt
netdata.spec.in

dont install test bash scripts by default

---

src/go/plugin/go.d/modules/chrony/client.go

go.d chrony fix client read/write timeout

---

src/go/go.mod
src/go/go.sum
src/go/plugin/go.d/agent/functions/function.go
src/go/plugin/go.d/agent/functions/input.go
src/go/plugin/go.d/agent/functions/manager.go
src/go/plugin/go.d/agent/functions/manager_test.go

It doesn't work properly on Windows.
</details>

go.d drop using cancelreader

---

src/collectors/plugins.d/ndsudo.c
src/database/contexts/context.c
src/database/contexts/worker.c
src/go/collectors/go.d.plugin/modules/filecheck/charts.go

- do not rely on the queued flag to queue a context (#18198)
- go.d filecheck fix dir existence chart label (#18126)
- ndsudo setuid before looking for command (#18189)

Patch release 1.46.3

---

src/go/cmd/godplugin/main.go

go.d fix netdata dir path on win under msys

---

packaging/windows/compile-on-windows.sh

Also, rework how we’re handling CFLAGS so that we pick them up properly from the environment.
Relevant to: #18213

Default to release with debug symbols for Windows builds.

---

src/database/sqlite/sqlite_aclk_node.c

- Update the node info payload to include all agent capabilities

Update node info payload

---

integrations/cloud-notifications/metadata.yaml

Fixes: #18224
Closes: #18250
</details>

docs: improve "Settings on Microsoft Teams" description

---

CMakeLists.txt

Also, restructure so everything for the updater is handled in one place.
Requires manual testing to confirm behavior.
Relevant to: #18213

Don’t install netdata-updater code on Windows.

---

src/collectors/apps.plugin/apps_groups.conf

apps conf add beanstalkd

---

.github/workflows/build.yml
packaging/installer/kickstart.sh

This fixes temporary file path handling issues in the kickstart script that were causing CI failures, and likely could have caused issues for users when installing Netdata.

Fix CI issues in build workflow.

---

src/go/plugin/go.d/modules/smartctl/scan.go

go.d smartctl: improve checking scsi-sat in scan

---

src/go/plugin/go.d/modules/smartctl/scan.go

go.d smartctl: undo extra_devices skip from #18269

---

src/go/plugin/go.d/modules/snmp/collect.go
src/go/plugin/go.d/modules/snmp/snmp.go
src/go/plugin/go.d/modules/snmp/snmp_test.go

go.d snmp: adjust max repetitions automatically

---

src/go/plugin/go.d/agent/module/charts.go
src/go/plugin/go.d/modules/rethinkdb/collect.go
src/go/plugin/go.d/modules/rethinkdb/rethinkdb_test.go
src/go/plugin/go.d/modules/rethinkdb/testdata/v2.4.4/stats.txt

go.d rethinkdb fix cluster_servers_stats_request

---

src/collectors/python.d.plugin/python.d.conf
src/go/plugin/go.d/README.md
src/go/plugin/go.d/config/go.d.conf
src/go/plugin/go.d/config/go.d/gearman.conf
src/go/plugin/go.d/config/go.d/sd/docker.conf
src/go/plugin/go.d/config/go.d/sd/net_listeners.conf
src/go/plugin/go.d/modules/gearman/charts.go
src/go/plugin/go.d/modules/gearman/client.go
src/go/plugin/go.d/modules/gearman/collect.go
src/go/plugin/go.d/modules/gearman/config_schema.json
src/go/plugin/go.d/modules/gearman/gearman.go
src/go/plugin/go.d/modules/gearman/gearman_test.go
src/go/plugin/go.d/modules/gearman/metadata.yaml
src/go/plugin/go.d/modules/gearman/testdata/config.json
src/go/plugin/go.d/modules/gearman/testdata/config.yaml
src/go/plugin/go.d/modules/gearman/testdata/priority-status.txt
src/go/plugin/go.d/modules/gearman/testdata/status.txt
src/go/plugin/go.d/modules/init.go
src/health/health.d/gearman.conf

add go.d/gearman

---

src/go/plugin/go.d/modules/gearman/metadata.yaml

go.d gearman fix meta

---

src/collectors/plugins.d/ndsudo.c

add nsd-control to ndsudo

---

src/collectors/plugins.d/ndsudo.c

add exim to ndsudo

---

src/collectors/python.d.plugin/python.d.conf
src/go/plugin/go.d/README.md
src/go/plugin/go.d/config/go.d.conf
src/go/plugin/go.d/config/go.d/exim.conf
src/go/plugin/go.d/config/go.d/nsd.conf
src/go/plugin/go.d/modules/exim/charts.go
src/go/plugin/go.d/modules/exim/collect.go
src/go/plugin/go.d/modules/exim/config_schema.json
src/go/plugin/go.d/modules/exim/exec.go
src/go/plugin/go.d/modules/exim/exim.go
src/go/plugin/go.d/modules/exim/exim_test.go
src/go/plugin/go.d/modules/exim/init.go
src/go/plugin/go.d/modules/exim/metadata.yaml
src/go/plugin/go.d/modules/exim/testdata/config.json
src/go/plugin/go.d/modules/exim/testdata/config.yaml
src/go/plugin/go.d/modules/init.go

add go.d/exim

---

src/go/plugin/go.d/modules/nvidia_smi/config_schema.json
src/go/plugin/go.d/modules/nvidia_smi/exec.go
src/go/plugin/go.d/modules/nvidia_smi/init.go
src/go/plugin/go.d/modules/nvidia_smi/metadata.yaml
src/go/plugin/go.d/modules/nvidia_smi/nvidia_smi.go
src/go/plugin/go.d/modules/nvidia_smi/nvidia_smi_test.go
src/go/plugin/go.d/modules/nvidia_smi/testdata/config.json
src/go/plugin/go.d/modules/nvidia_smi/testdata/config.yaml

and make it default.
Fixes: #14522
</details>

go.d nvidia_smi: add loop mode

---

packaging/repoconfig/deb.changelog
packaging/repoconfig/netdata.repo.dnf
packaging/repoconfig/rpm.changelog

Use system certificate configuration for Yum/DNF repos.

---

src/go/plugin/go.d/modules/nvidia_smi/metadata.yaml
src/go/plugin/go.d/modules/nvidia_smi/nvidia_smi.go

go.d nvidia_smi: enable by default

---

.github/workflows/build.yml
packaging/cmake/Modules/FindGo.cmake
packaging/cmake/Modules/NetdataGoTools.cmake

This should resolve the build issues we’re seeing in CI with Windows.

Handle GOROOT inside build system instead of outside.

---

src/go/plugin/go.d/modules/redis/config_schema.json

go.d redis: fix default "address" in config_schema.json

---

src/collectors/python.d.plugin/python.d.conf
src/go/plugin/go.d/README.md
src/go/plugin/go.d/config/go.d.conf
src/go/plugin/go.d/config/go.d/dovecot.conf
src/go/plugin/go.d/config/go.d/sd/docker.conf
src/go/plugin/go.d/config/go.d/sd/net_listeners.conf
src/go/plugin/go.d/modules/dovecot/charts.go
src/go/plugin/go.d/modules/dovecot/client.go
src/go/plugin/go.d/modules/dovecot/collect.go
src/go/plugin/go.d/modules/dovecot/config_schema.json
src/go/plugin/go.d/modules/dovecot/dovecot.go
src/go/plugin/go.d/modules/dovecot/dovecot_test.go
src/go/plugin/go.d/modules/dovecot/metadata.yaml
src/go/plugin/go.d/modules/dovecot/testdata/config.json
src/go/plugin/go.d/modules/dovecot/testdata/config.yaml
src/go/plugin/go.d/modules/dovecot/testdata/export_global.txt
src/go/plugin/go.d/modules/init.go
src/go/plugin/go.d/modules/openvpn/config_schema.json

Just rewrite pythond/dovecot, still uses [old_stats](https://doc.dovecot.org/configuration_manual/stats/old_statistics).
</details>

add go.d dovecot

---

src/collectors/python.d.plugin/python.d.conf
src/go/plugin/go.d/config/go.d.conf
src/go/plugin/go.d/config/go.d/sd/net_listeners.conf
src/go/plugin/go.d/config/go.d/uwsgi.conf
src/go/plugin/go.d/modules/init.go
src/go/plugin/go.d/modules/uwsgi/charts.go
src/go/plugin/go.d/modules/uwsgi/client.go
src/go/plugin/go.d/modules/uwsgi/collect.go
src/go/plugin/go.d/modules/uwsgi/config_schema.json
src/go/plugin/go.d/modules/uwsgi/init.go
src/go/plugin/go.d/modules/uwsgi/metadata.yaml
src/go/plugin/go.d/modules/uwsgi/testdata/config.json
src/go/plugin/go.d/modules/uwsgi/testdata/config.yaml
src/go/plugin/go.d/modules/uwsgi/testdata/stats.json
src/go/plugin/go.d/modules/uwsgi/testdata/stats_no_workers.json
src/go/plugin/go.d/modules/uwsgi/uwsgi.go
src/go/plugin/go.d/modules/uwsgi/uwsgi_test.go

add go.d/uwsgi

---

README.md

add dashboard v2 license to readme

---

src/collectors/apps.plugin/apps_groups.conf

add i2pd to apps_groups.conf

---

README.md

add license to readmes menu

---

src/go/plugin/go.d/modules/httpcheck/metadata.yaml

go.d httpcheck: add status description to docs

---

src/collectors/python.d.plugin/python.d.conf
src/go/plugin/go.d/README.md
src/go/plugin/go.d/config/go.d.conf
src/go/plugin/go.d/config/go.d/sd/docker.conf
src/go/plugin/go.d/config/go.d/sd/net_listeners.conf
src/go/plugin/go.d/config/go.d/tor.conf
src/go/plugin/go.d/modules/init.go
src/go/plugin/go.d/modules/tor/charts.go
src/go/plugin/go.d/modules/tor/client.go
src/go/plugin/go.d/modules/tor/collect.go
src/go/plugin/go.d/modules/tor/config_schema.json
src/go/plugin/go.d/modules/tor/metadata.yaml
src/go/plugin/go.d/modules/tor/testdata/config.json
src/go/plugin/go.d/modules/tor/testdata/config.yaml
src/go/plugin/go.d/modules/tor/tor.go
src/go/plugin/go.d/modules/tor/tor_test.go

add go.d/tor

---

integrations/cloud-authentication/metadata.yaml

Add SCIM integration docs

---

.github/workflows/generate-integrations.yml

ci gen integrations: add cloud-authentication dir

---

integrations/templates/troubleshooting.md

go.d docs: add a note that debug mode not supported for Dyncfg jobs

---

src/health/health_event_loop.c

Remove debug message

---

.github/workflows/packaging.yml

This updates our package signing for DEB packages so that they’re origin signed for all of our distribution mechanisms.
n/a

Origin-sign all DEB packages regardless of upload target.

---

src/go/plugin/go.d/modules/zfspool/charts.go
src/go/plugin/go.d/modules/zfspool/collect.go
src/go/plugin/go.d/modules/zfspool/collect_zpool_list.go
src/go/plugin/go.d/modules/zfspool/collect_zpool_list_vdev.go
src/go/plugin/go.d/modules/zfspool/exec.go
src/go/plugin/go.d/modules/zfspool/metadata.yaml
src/go/plugin/go.d/modules/zfspool/testdata/zpool-list-vdev-logs-cache.txt
src/go/plugin/go.d/modules/zfspool/testdata/zpool-list-vdev.txt
src/go/plugin/go.d/modules/zfspool/zfspool.go
src/go/plugin/go.d/modules/zfspool/zfspool_test.go
src/health/health.d/zfs.conf

go.d zfspool: collect vdev health state

---

src/go/plugin/go.d/modules/dnsmasq_dhcp/dhcp_test.go
src/go/plugin/go.d/modules/dnsmasq_dhcp/parse_configuration.go

go.d dnsmsasq_dhcp: improve parsing of dhcp ranges

---

src/go/plugin/go.d/modules/dnsmasq_dhcp/dhcp_test.go
src/go/plugin/go.d/modules/dnsmasq_dhcp/parse_configuration.go

go.d dnsmasqdhcp: simplify parseDHCPRangeValue

---

src/collectors/plugins.d/ndsudo.c

add "smbstatus -P" to ndsudo

---

src/go/plugin/go.d/modules/samba/metadata.yaml

fix hyperlink in go.d samba meta

---

REDISTRIBUTED.md
src/go/plugin/go.d/modules/sensors/lmsensors/LICENSE.md
src/go/plugin/go.d/modules/sensors/lmsensors/README.md
src/go/plugin/go.d/modules/sensors/lmsensors/currentsensor.go
src/go/plugin/go.d/modules/sensors/lmsensors/doc.go
src/go/plugin/go.d/modules/sensors/lmsensors/fansensor.go
src/go/plugin/go.d/modules/sensors/lmsensors/intrusionsensor.go
src/go/plugin/go.d/modules/sensors/lmsensors/powersensor.go
src/go/plugin/go.d/modules/sensors/lmsensors/scanner.go
src/go/plugin/go.d/modules/sensors/lmsensors/scanner_test.go
src/go/plugin/go.d/modules/sensors/lmsensors/sensor.go
src/go/plugin/go.d/modules/sensors/lmsensors/temperaturesensor.go
src/go/plugin/go.d/modules/sensors/lmsensors/voltagesensor.go

vendor https://github.com/mdlayher/lmsensors

---

.github/dockerfiles/Dockerfile.build_test

ci fix InvalidDefaultArgInFrom warn

---

src/go/plugin/go.d/modules/ap/ap_test.go
src/go/plugin/go.d/modules/clickhouse/clickhouse_test.go
src/go/plugin/go.d/modules/cockroachdb/cockroachdb_test.go
src/go/plugin/go.d/modules/dmcache/dmcache_test.go
src/go/plugin/go.d/modules/fail2ban/fail2ban_test.go
src/go/plugin/go.d/modules/filecheck/filecheck_test.go
src/go/plugin/go.d/modules/hddtemp/hddtemp_test.go
src/go/plugin/go.d/modules/hpssa/hpssa_test.go
src/go/plugin/go.d/modules/ipfs/ipfs_test.go
src/go/plugin/go.d/modules/litespeed/litespeed_test.go
src/go/plugin/go.d/modules/puppet/puppet_test.go
src/go/plugin/go.d/modules/rspamd/rspamd_test.go
src/go/plugin/go.d/modules/scaleio/scaleio_test.go
src/go/plugin/go.d/modules/smartctl/smartctl_test.go
src/go/plugin/go.d/modules/squidlog/squidlog_test.go
src/go/plugin/go.d/modules/storcli/storcli_test.go
src/go/plugin/go.d/modules/vernemq/vernemq_test.go
src/go/plugin/go.d/modules/weblog/weblog_test.go
src/go/plugin/go.d/modules/windows/windows_test.go

go.d remove duplicates in testing

---

docs/developer-and-contributor-corner/pi-hole-raspberry-pi.md
src/collectors/proc.plugin/README.md

fix charts.d/sensors leftovers

---

src/go/plugin/go.d/agent/vnodes/vnodes.go

go.d add support for symlinked vnode config files

---

src/go/plugin/go.d/agent/agent.go
src/go/plugin/go.d/agent/module/job.go
src/go/plugin/go.d/agent/vnodes/vnodes.go

Not needed anymore.
</details>

go.d remove vnode disable

---

src/go/plugin/go.d/modules/storcli/collect_drives.go

go.d storcli: fix unmarshal driveInfo

---

src/daemon/win_system-info.c

fix win sysinfo installed ram calculation

---

src/collectors/plugins.d/ndsudo.c

add varnishstat and varnishadm to ndsudo

---

src/go/plugin/go.d/pkg/dockerhost/dockerhost.go

go.d add function to execute a command inside a Docker container

---

src/go/plugin/go.d/modules/varnish/metadata.yaml

go.d/varnish update meta
