libnetdata/threads/threads.c

There is race conditions that sometimes crashes netdata when a thread is created and finishes before the creator can call pthread_detach().

fix phtread-detatch() call

---

collectors/ebpf.plugin/ebpf_apps.c

This PR address the reported issuee:
```sh
#3 0x555942444f62 in ebpf_get_pid_from_judy_unsafe /home/costa/src/netdata-ktsaou.git/collectors/ebpf.plugin/ebpf.c:708
#4 0x5559425273be in read_proc_pid_cmdline /home/costa/src/netdata-ktsaou.git/collectors/ebpf.plugin/ebpf_apps.c:869
#5 0x555942527fe9 in read_proc_pid_stat /home/costa/src/netdata-ktsaou.git/collectors/ebpf.plugin/ebpf_apps.c:932
#6 0x555942528518 in collect_data_for_pid /home/costa/src/netdata-ktsaou.git/collectors/ebpf.plugin/ebpf_apps.c:966
#7 0x55594252b2f9 in read_proc_filesystem /home/costa/src/netdata-ktsaou.git/collectors/ebpf.plugin/ebpf_apps.c:1347
#8 0x55594252bcbb in collect_data_for_all_processes /home/costa/src/netdata-ktsaou.git/collectors/ebpf.plugin/ebpf_apps.c:1432
#9 0x5559424524d5 in main …
```

Add missing call for aral_freez (eBPF)

---

mqtt_websockets/src/include/mqtt_ng.h
mqtt_websockets/src/mqtt_ng.c

This fixes the issue with the following code:
```
*WRITE_POS(frag) = (MQTT_CPT_SUBSCRIBE << 4) | 0x2 /* [MQTT-3.8.1-1] */;
```
assigning the constant 130 which is larger than
127.
- CI jobs.

Use unsigned char for binary data in mqtt.

---

collectors/systemd-journal.plugin/systemd-units.c

> warning: variable 'm' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
- CI jobs.

Fix warning.

---

collectors/diskspace.plugin/plugin_diskspace.c

Fix this:
```
==18202==ERROR: AddressSanitizer: heap-use-after-free on address 0x60200000c838 at pc 0x563059bb6549 bp 0x7f8472ed56e0 sp 0x7f8472ed56d0
READ of size 1 at 0x60200000c838 thread T50 (WEB[2])
#0 0x563059bb6548 in buffer_json_strcat /data/src/netdata-ktsaou.git/libnetdata/config/../buffer/buffer.h:284
#1 0x563059bb6548 in buffer_json_add_string_value /data/src/netdata-ktsaou.git/libnetdata/config/../buffer/buffer.h:710
#2 0x563059bb6548 in buffer_json_add_array_item_string /data/src/netdata-ktsaou.git/libnetdata/config/../buffer/buffer.h:841
#3 0x563059bb6548 in diskspace_function_mount_points /data/src/netdata-ktsaou.git/collectors/diskspace.plugin/plugin_diskspace.c:669
#4 0x56305962e018 in rrd_function_run_inline /data/src/netdata-ktsaou.git/database/rrdfunctions-inline.c:20 …
```

diskspace missing mutex use

---

collectors/log2journal/log2journal-yaml.c

* CID 410249:    (RESOURCE_LEAK)
- /collectors/log2journal/log2journal-yaml.c: 501 in yaml_parse_rewrites()
- /collectors/log2journal/log2journal-yaml.c: 564 in yaml_parse_rewrites()
* CID 410250:    (RESOURCE_LEAK)
- /collectors/log2journal/log2journal-yaml.c: 564 in yaml_parse_rewrites()
- /collectors/log2journal/log2journal-yaml.c: 467 in yaml_parse_rewrites()
* CID 410247:  Resource leaks  (RESOURCE_LEAK)
- /collectors/log2journal/log2journal-yaml.c: 564 in yaml_parse_rewrites()
</details>

Free key and search, replace patterns

---

coverity-scan.sh
netdata-installer.sh

Allows better integration with external tooling like IDEs.
CI still passes on this PR
Resolves: #16751

Change default build directory in installer to `build`.

---

.github/scripts/run-updater-check.sh
.github/workflows/build.yml
packaging/installer/UPDATE.md
packaging/installer/netdata-updater.sh
system/netdata-updater.conf

This adds new logic to the updater so that users can opt-out of updating to specific new major versions of Netdata. A new updater configuration variable called `NETDATA_ACCEPT_MAJOR_VERSIONS` has been added, which should contain a list of major version numbers that we’re allowed to update to. This will by default be populated by us in the updater itself, allowing us to easily block specific major versions if we discover serious issues, and also allowing us to have updates run by default 
Not specifying anything in the updater config file should get behavior exactly equivalent to the current behavior.
Setting `NETDATA_ACCEPT_MAJOR_VERSIONS` in the updater config file so that it doesn’t include the target major version should cause a non-interactive update to fail, or an interactive update …

Add check to avoid auto-installing new major versions of Netdata.

---

netdata-installer.sh

SSIA. The's not reason to have the deleted text in the output of `--help`.
Just run the installer with `--help`.

Remove help text that no longer applies.

---

packaging/installer/netdata-updater.sh

We should be checking the target version for the update, not the current version.
Testing is as outlined in https://github.com/netdata/netdata/pull/15898, except that explicitly setting `NETDATA_ACCEPT_MAJOR_VERSIONS="1"` in the updater config should exhibit different behavior with and without this change. Without this change, the update should continue without warning or prompting, while with this change it should result in a failure for non-interactive updates or a prompt for interactive ones.
Pointed out by @ilyam8 in https://github.com/netdata/netdata/pull/15898#discussion_r1455532491

Fix incorrect major version check in updater.

---

packaging/docker/README.md
packaging/docker/run.sh

Users can override what user ID is used inside of a container when creating the container. We don’t technically properly support this, but we should also ideally not _break_ such usage either as there are legitimate use-cases for it. This moves code that will only work when run as root inside the container inside a conditional in our entrypoint script so that it doesn’t break things otherwise.
Basic testing involves confirming that Docker images built from this branch still start when run with the `--user` option set to some user other than root.
This re-adds the section in our Docker documentation about limitations inherent to our Docker images which was completely dropped for some reason.

Better support running the Docker entrypoint code as a non-root user.

---

collectors/apps.plugin/apps_plugin.c
collectors/cgroups.plugin/cgroup-network.c
collectors/debugfs.plugin/debugfs_plugin.c
collectors/ebpf.plugin/ebpf.c
collectors/systemd-journal.plugin/systemd-main.c
daemon/main.c
libnetdata/libnetdata.c
libnetdata/libnetdata.h
logsmanagement/logsmanagement.c

The goal is to not log "Using host prefix..." from [cgroups.plugin/cgroup-network](https://github.com/netdata/netdata/blob/8bf8d095b8fbbe5aba4099816ce52c3939ff7415/collectors/cgroups.plugin/cgroup-network.c#L655-L669) (executed for every discovered container).
<details>
<summary>logs</summary>
```
kubectl logs netdata-child-9j5lb -c netdata 2>&1 | grep "host prefix"
time=2024-01-19T14:26:09.252+00:00 comm=netdata source=daemon level=info tid=2990974 thread=netdata msg="Using host prefix directory '/host'"
time=2024-01-19T14:26:10.426+00:00 comm=systemd-journal.plugin source=collector level=info tid=2991243 thread=SDMAIN msg="Using host prefix directory '/host'"
time=2024-01-19T14:26:10.428+00:00 comm=debugfs.plugin source=collector level=info tid=2991250 thread=debugfs.plugin msg="Using …
```

fix verify_netdata_host_prefix log spam

---

database/rrdlabels.c

- Preserve label source during migration of host labels
- Improve unit tests
Fixes #16807

Preserve label source during migration

---

system/edit-config

- Check for `/run/.containerenv`, which is used by modern versions of Podman and some other OCI stacks to signal that the environment is a container.
- Relax the PID 1 environment checking to not require `container` to be set to `podman` (some images override it), and not require it to be the first item in the list of environment variables (it will often not be).
- Explicitly return a non-zero exit status if no signs of being in a container are detected.
This needs to be manually tested in affected environments to confirm it works.
Testing should be as simple as copying the version of the edit-config script from the PR branch to the expected location in the test environment and running it there.
Fixes: #16819

Improve container detection logic for edit-config.

---

packaging/check-for-go-toolchain.sh

This will be used both by tooling in https://github.com/netdata/helper-images and by dependency handling scripts in this repo to ensure we have a working Go toolchain.
It’s being added here as it’s own file so that we have a central location for managing what version of the Go toolchain gets pulled in when a copy is not available on the system already.
No real testing at the moment for this, code to test it will be added indirectly when users are added.
Part of the first steps towards resolving #16808.

Add script to ensure a usable Go toolchain is installed.

---

packaging/installer/kickstart.sh

Fixes: #16842.
`grep` + `--only-matching` (`-o`) + `*` in pattern match is [broken on macOS Sonoma](https://forums.developer.apple.com/forums/thread/738862). 
The workaround is using `+` instead of `*`.
- master branch
```bash
$ curl https://github.com/netdata/netdata/releases/latest -s -L -I -o /dev/null -w '%{url_effective}' | grep -o "[^/]*$"
Assertion failed: (advance > 0), function procline, file util.c, line 732.
Abort trap: 6
```
- this PR
```bash
$ curl https://github.com/netdata/netdata/releases/latest -s -L -I -o /dev/null -w '%{url_effective}' | grep -Eo "[^/]+$"
v1.44.1
```
</details>

kickstart: use extended-regexp in `get_redirect()`

---

netdata.spec.in

We’re in the process of migrating the Go collectors to be part of the main repo (see #16808 for more details on that), and some of the intermediate steps don’t pay nice with the current code in the spec file for handling of the Go plugin, so stub it out for now.
Long-term this code is going to be removed completely (and some special stuff will be done to handle the dependencies correctly since we need a very recent version of Go that is not included on _most_ platforms), as the Go code will be handled automatically as part of the CMake build process, but for now it’s in the way and it’s simpler to just stub it out.

Disable local Go builds in our RPM packages.

---

daemon/main.c
daemon/service.c

- Ensure the service thread concludes first during shutdown.
- The service thread now pauses in one-second intervals.

Improve service thread shutdown

---

CMakeLists.txt
collectors/cgroups.plugin/sys_fs_cgroup.c
collectors/debugfs.plugin/debugfs_zswap.c
collectors/debugfs.plugin/sys_devices_virtual_powercap.c
collectors/plugins.d/local-sockets.h
collectors/plugins.d/local_listeners.c
collectors/proc.plugin/proc_diskstats.c
collectors/proc.plugin/proc_net_dev.c
collectors/proc.plugin/proc_net_sockstat.c
collectors/proc.plugin/proc_spl_kstat_zfs.c
collectors/proc.plugin/sys_class_infiniband.c
collectors/proc.plugin/sys_devices_system_edac_mc.c
collectors/proc.plugin/sys_fs_btrfs.c
collectors/systemd-journal.plugin/systemd-internals.h
collectors/systemd-journal.plugin/systemd-journal-files.c
collectors/systemd-journal.plugin/systemd-main.c
daemon/analytics.c
daemon/main.c
libnetdata/ebpf/ebpf.c
libnetdata/functions_evloop/functions_evloop.h
libnetdata/inlined.h
libnetdata/os.c

```
Netdata local-listeners
(C) 2024 Netdata Inc.
This program prints a list of all the processes that have a listening socket.
It is used by Netdata to auto-detect the services running.
Options:
The options:
udp, udp4, udp6, tcp, tcp4, tcp6, ipv4, ipv6
select the sources to read currently available sockets.
while:
listening, local, inbound, outbound
filter the output based on the direction of the sockets.
Prepending any option with 'no-', 'not-' or 'non-' will disable them.
Current options:
udp4 udp6 tcp4 tcp6 listening no-local no-inbound no-outbound
Option 'debug' enables all sources and all directions and provides
a full dump of current sockets.
DIRECTION DETECTION
The program detects the direction of the sockets using these rules:
- listening   are all the TCP sockets that are in …
```

detect sockets direction

---

health/health_prototypes.c

Fixed a bug where the first instance of an alert is applied, instead of the one that matches the chart.

apply the right prototype to instances

---

.github/workflows/build.yml
packaging/PLATFORM_SUPPORT.md
packaging/installer/kickstart.sh
packaging/makeself/build-static.sh
packaging/makeself/uname2platform.sh

This adds ARMv6 support to our static build infrastructure, including starting publishing ARMv6 static builds.
These are thus far minimally tested, but should work on any ARMv6zk hardware with hardware floating point support, including most 32-bit Raspberry Pi systems (other than the Pico) and a majority of equivalent-spec competitors of a similar vintage.
Relevant to #16846

Add ARMv6 static builds.

---

daemon/system-info.sh

Fixes: #16852
https://man.freebsd.org/cgi/man.cgi?jail(8)
> The read-only entry security.jail.jailed	can be used to determine if  a process is running inside a jail	(value is one) or not (value is	zero).
```bash
$ sysctl security.jail.jailed
security.jail.jailed: 0
```
Tested on FreeBSD.
</details>

add freebsd jail detection to system-info.sh

---

libnetdata/query_progress/progress.c

1. Gets the lock
2. zeros the structure that has the lock inside

fix crash on query_progress initializer

---

contrib/debian/rules

SSIA. Without this we are performing an unoptimized build.

Set build type to release with debug info.

---

.github/workflows/build.yml

We have not actually used GCS for much of anything WRT our nightly builds for quite some time now, but have continued uploading to it. This wastes a significant amount of money on bandwidth and storage for something we’re not actually using, so this PR just updates things to only upload the `latest-version.txt` file, which is still used by version checks for nightlies in the older dashboard code.
n/a

Limit what we upload to GCS for nightlies.

---

.github/workflows/packaging.yml

All of our package builder will have a SENTRY_DSN https://github.com/netdata/helper-images/pull/269 with a dummy value and if the NETDATA_SENTRY_DSN env var is not empty we will overwrite it. 
sue.
MERGE AFTER https://github.com/netdata/helper-images/pull/269
</details>

Add a constant env var for Sentry's  DSN when someone wants to build Agent and doesn't have access to GH secrets. 

---

ml/ml.cc

An atomic flag is used before every iteration
of the detection thread. The flag is set right
before the cancellation request. It is possible
for the detection thread to have already exited
prior to sending the cancellation request.
The training thread most probably suffers from
the same issue, a separate PR will be opened
to fix it.

Do not cancel detection thread.

---

daemon/sentry-native/sentry-native.c

This will allow sentry to compute crash-free sessions.

Enable sentry sessions

---

collectors/apps.plugin/apps_plugin.c
collectors/cgroups.plugin/cgroup-top.c
collectors/diskspace.plugin/plugin_diskspace.c
collectors/ebpf.plugin/ebpf_functions.c
collectors/freeipmi.plugin/freeipmi_plugin.c
collectors/network-viewer.plugin/network-connections-chart.html
collectors/network-viewer.plugin/network-viewer.c
collectors/plugins.d/local_listeners.c
collectors/plugins.d/pluginsd_functions.c
collectors/proc.plugin/proc_diskstats.c
collectors/proc.plugin/proc_net_dev.c
src/database/rrdfunctions-inflight.c
src/database/rrdfunctions-streaming.c
src/libnetdata/aral/aral.c
src/libnetdata/aral/aral.h
src/libnetdata/buffer/buffer.c
src/libnetdata/inlined.h
src/libnetdata/maps/local-sockets.h
src/libnetdata/query_progress/progress.c
src/libnetdata/socket/socket.c

- `aggregated` where it returns aggregated data of the sockets. Local and Remote IPs and Ports are not there anymore. The aggregation happens on "Server IP" (which is either Local or Remote depending on the direction). `aggregated` is currently disabled, until the UI can handle it.
- `detailed`, where it returns all data like it did before this PR.
The `aggregated` view should relax the pressure on web browser resources on very busy servers with thousands of inbound or outbound connections, allowing the visualization and the table to work efficiently.

add support for the info parameter to all external plugin functions

---

src/database/contexts/query_target.c

- Release label key to have correct reference count

Release label key if already in use

---

netdata-installer.sh

Fixes this problem:
```
The following warnings and non-fatal errors were encountered during the installation process:
- libfluent-bit.so is missing, Netdata Logs Management support will be disabled in this build.
```
`libfluent-bit.so` is in `"${NETDATA_PREFIX}"/usr/lib/netdata`.
</details>

fix installation of `libfluent-bit.so`

---

daemon/analytics.c
daemon/analytics.h

- Prevent race condition when setting analytics data

Protect analytics set data

---

.github/CODEOWNERS
.github/workflows/generate-integrations.yml
integrations/gen_docs_integrations.py
integrations/gen_integrations.py

@Ferroin mainly, I ran the workflow locally without this fix and it nuked the .md files under the new src/exporting, so I changed all references to that path, the change inside integrations.js and .json is huge and won't load on my machine, but I guess it is correct because the .md files were generated, which use the yamls.

Exporting moved, so changes needed for integrations, + CODEOWNERS change

---

health/health_log.c

- Add a check to prevent negative duration of an alert. This may result to an overflow ending up in 4294967295

Make sure the duration is not negative

---

src/libnetdata/log/log.c

- Removes a duplicate call to `netdata_thread_tag_exists()`

Remove duplicate check

---

daemon/main.c
web/server/web_server.c
web/server/web_server.h

Currently if we fail to bind to the agents listen ports we assume the agent is running and exit (with fatal)
With this change the agent will exit normally and log `Cannot setup listen port(s). Is Netdata already running?`
The ML initialization code has been moved until after socket listen is successful

Check for agent already running

---

src/libnetdata/log/log.c

There are two things in the logging library that are not documented and I believe are not bugs, but are implemented for a reason:
1. The default log level affects only the daemon and collector logs ([nd_log_set_priority_level()](https://github.com/netdata/netdata/blob/master/src/libnetdata/log/log.c#L654-L669)).
2. There is a way to [set the log level per source](https://github.com/netdata/netdata/tree/master/src/libnetdata/log#configuring-log-sources), but again, the filtering affects only the daemon and collector logs ([netdata_logger()](https://github.com/netdata/netdata/blob/e34730ea322aef32be77608d34bb96fad6e6b471/src/libnetdata/log/log.c#L2257-L2258)).
I think I understand 1. - we don't want to filter health (alerts transitions) and access sources (web server access logs) if the …

respect log level for all sources

---

collectors/charts.d.plugin/charts.d.plugin.in

`PROGRAM_NAME` is `charts.d.plugin`, we need [SHORT_PROGRAM_NAME](https://github.com/netdata/netdata/blob/85b274833bb01e5bdef3e230f4f2e7ec6c8f26e5/collectors/charts.d.plugin/charts.d.plugin.in#L25).
Before
```
thread=charts.d.plugin msg="apcupsd: not found module configuration: '/opt/netdata/usr/lib/netdata/conf.d/charts.d.plugin/apcupsd.conf'"
thread=charts.d.plugin msg="apcupsd: not found module configuration: '/opt/netdata/etc/netdata/charts.d.plugin/apcupsd.conf'"
```
After
```
thread=charts.d.plugin msg="apcupsd: loading module configuration: '/opt/netdata/usr/lib/netdata/conf.d/charts.d/apcupsd.conf'"
thread=charts.d.plugin msg="apcupsd: loading module configuration: '/opt/netdata/etc/netdata/charts.d/apcupsd.conf'"
``` …

fix charts.d.plugin configuration directory names

---

daemon/main.c

Needed to change the log level of an ND docker container without using netdata.conf.
Start docker container, NETDATA_LOG_LEVEL set to:
- [correct level](https://github.com/netdata/netdata/tree/master/src/libnetdata/log#log-levels): log messages <= level.
- incorrect level: log messages <= info.
- not set: log messages <= info.
</details>

respect NETDATA_LOG_LEVEL if set

---

src/daemon/main.c

- Remove the call to garbage collect any leftover deleted dictionaries to avoid possible double free of a metric causing an error `METRIC: refcount is nn (zero or negative) during release`

Remove cleanup_destroyed_dictionaries call during shutdown

---

collectors/network-viewer.plugin/network-viewer.c

network-viewer: aggregated view improvements

---

src/daemon/config/dyncfg-intercept.c
src/daemon/config/dyncfg.c
src/health/health_dyncfg.c

To support TEST action on new jobs:
1. Set the TEST command to templates
2. The callback of the template will be called with the ID of the new job (so the plugin will receive on the callback of the template a test action with ID the new job name)

DYNCFG: support test on new jobs

---

src/daemon/main.c
src/database/sqlite/sqlite_context.c
src/database/sqlite/sqlite_functions.c
src/database/sqlite/sqlite_metadata.c
src/ml/ml.cc

- Clear detection thread during shutdown. A fatal following ML stop will try to stop the ml threads again
- metadata sync prepare does not run twice
- metadata, ml, context db are closed once
- main threads termination is done once

Improve agent shutdown

---

src/collectors/proc.plugin/metadata.yaml
src/collectors/proc.plugin/sys_devices_system_edac_mc.c
src/health/health.d/memory.conf

Fixes: #16969
This PR changes the following metrics from incremental to absolute:
- `mem.edac_mc`: correctable/uncorrectable for each Memory Controller.
- `mem.edac_mc_dimm`: correctable/uncorrectable for each DIMM module.
See the reasoning in #16969. I am inclined to agree that it is incorrect to have them incremental. Because of this, I decided to change the existing metrics rather than add new ones. I think we can say that the incremental metric is somewhat of a bug and a misleading metric. If you do not agree, indicate the use case when you need rates.
Netdata aggregates charts by context, so **I changed the contexts** to avoid incorrect aggregation. I don't think there's a way around. Again, did that because I thought of it as a bug.
Install, check charts and alarms.
<details> …

change edac ecc errors from incremental to absolute

---

CMakeLists.txt
netdata-installer.sh
netdata.spec.in
packaging/installer/functions.sh

This is needed to properly support the latest versions of Protobuf.
Support for older systems is handled via:
- A new CMake option, `USE_CXX_11`, defaulting to disabled, which when set will switch to using C++11 instead of C++14 during the build.
- An explicit exception in the RPM spec file to set that option on the few platforms we build native RPM packages for that are known to need it.
- Additional checks in the installer code that constructs the CMake command line to verify compiler versions and enable the aforementioned CMake option if needed.
- A new option for the `netdata-installer.sh` script, `--force-legacy-cxx`, which overrides the above-mentioned compiler version checks to force-enable the aforementioned CMake option.
Supplementary testing should include …

Use C++14 by default when building on systems that support it.

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/docker.yml
.github/workflows/packaging.yml

Breaking  change in v42 https://github.com/tj-actions/changed-files/releases/tag/v42
Dir input pattern doesn't require globstar
This may fix the issue that we see, _workflows are running when we touch only  files_ignored_
</details>

Update input paths for tj-actions/changed-files

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/docker.yml
.github/workflows/packaging.yml

- negation must be after the match.
- `**.xyz` matches only the root folder
- `**/*.xyz` matches everything.
Changes: 
1. Fix minor typo:
- job name will be file-check in any workflow
- file-check job has a step which is check-file
2. Print any modified files (previous approach was not printing deleted)
3. Change glob patterns for all source files (*.c, *.h etc). With the previous approach they only matched the root folder
Co-authored-by: ilyam8 <22274335+ilyam8@users.noreply.github.com>
</details>

Update input skip patterns

---

src/database/rrdhost.c
src/database/sqlite/sqlite_metadata.c
src/database/sqlite/sqlite_metadata.h

Currently, if you copy the entire /var/cache/netdata folder to a newly installed agent and then start the agent, the new system will use the existing history by switching the parent agent found in the metadata to the newly installed agent. In essence, the historical data from the old system is inherited by the new system.
With this change, the parent found in the copied data will be switched to an archived child node. 
- Install a new agent (A) but don't start it
- Stop an `existing` agent (B) and copied it's /var/cache/netdata to agent (A)
- Start agent (A)
- You should see data being collected for A
- You should have an archived child with data from B

Detect machine GUID change

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/docker.yml
.github/workflows/packaging.yml

We hit a limit https://github.com/netdata/netdata/actions/runs/7869434508/job/21468539512?pr=16992 when too many files were changing. Most commonly the case will be moving too many files that's why we amend this.
</details>

Use changed files in check-files workflow

---

src/daemon/main.c
src/daemon/service.c
src/database/rrd.h
src/database/rrddim.c

- Protect metric release with a spinlock
During shutdown, finalizing all metrics can result in a race condition if a dimension directory delete callback is called at the same time. 
- Cleanup service thread. Remove duplicate code by calling rrddim_finalize_collection_and_check_retention

Add spinlock to protect metric release

---

src/database/engine/datafile.c
src/database/rrdhost.c

- Adjust storage tiers if we fail to create the requested number of tiers.
Although no datafiles were produced for this tier, there was an attempt to finalize files during shutdown
- Report correct number of tiers activated  
- Do not create a dbengine-tierX directory if the tier cannot be activated
Right now an empty directory is created
- Check for datafiles existence during finalize of ctx (sanity check)
Fixes #16888

Adjust storage tiers if we fail to create the requested number of tiers

---

src/daemon/analytics.c
src/database/rrddim.c
src/database/sqlite/sqlite_functions.c

- Use `spinlock init` for proper initialization so that it will work properly when compiling with NETDATA_INTERNAL_CHECKS
- Clear errno so that it will not report an error when logging output of the `sqlite-analyze` command

Misc improvements

---

src/collectors/ebpf.plugin/ebpf.c
src/collectors/ebpf.plugin/ebpf_apps.c
src/collectors/ebpf.plugin/ebpf_apps.h
src/collectors/ebpf.plugin/ebpf_functions.c
src/libnetdata/ebpf/ebpf.c
src/libnetdata/ebpf/ebpf.h

This PR is moving some code inside eBPF.plugin to `libnetdata/ebpf` allowing network viewer plugin to test environment before to select the way it will collect data.
1. Compile PR.
2. Verify whether eBPF.plugin is running
It is not necessary to test on different kernels, because this is only changing user ring code.
</details>

eBPF - Network Viewer (Move code)

---

packaging/utils/coverity-scan.sh

Fixes a bug introduced by https://github.com/netdata/netdata/pull/16938
Manual testing of the updated script is required.

Fix determining repo root in Coverity scan script.

---

src/database/rrd.h

Increase the allowed max for ids (chart/dimensions) RRD_ID_LENGTH_MAX
The following will be updated separately
NetdataChartIDMaxLength in `job.go`

Increase RRD_ID_LENGTH_MAX to 1200

---

src/database/engine/metric.c
src/database/engine/metric.h

Currently the metric release function will also fetch retention and report if the metric can be deleted. This is not used as the eligibility of the metric deletion is determined with a different function call.
This PR removes the extra function call during metric release

Metric release does not need to fetch retention

---

src/database/contexts/query_target.c

- Make sure we don't do a metric release twice after a query target cleanup

Improved query target cleanup

---

CMakeLists.txt

At the point at which we call `find_package()` to locate protobuf, we know that we do, in fact, need it for this build. Given this, we should be marking it as required in the `find_package()` call so that if it’s not found the configuration phase fails instead of things breaking in potentially strange ways later on during the build itself.
Confirmation of the behavior of this change requires testing a build on a system without protobuf _and_ without requesting usage of a bundled copy (which means building directly instead of using the installer).

Correctly mark protobuf as required in find_package.

---

src/database/contexts/api_v2.c
src/database/engine/journalfile.c
src/database/engine/metric.c
src/database/engine/metric.h
src/database/engine/rrdengine.c
src/database/engine/rrdengine.h
src/database/engine/rrdengineapi.c
src/database/engine/rrdengineapi.h
src/database/rrd.h

- Keep a count of metrics during agent startup
- Calculate number of samples during information from metric page data (start time, end time) and the update frequency
- Expose metric and sample count in api/v2/info

Keep a count of metrics and samples collected

---

src/libnetdata/locks/locks.c
src/libnetdata/locks/locks.h
src/ml/ad_charts.cc
src/ml/ml-private.h
src/ml/ml.cc

Otherwise it's not possible to compute the correct anomaly rate in every case.
For optimization reasons, this PR extends the spinlock API to allow spinlocks ops without changing the cancellation state of the thread.
- CI jobs.
- Manually by adding the appropriate checks in the code and running a parent with many children.

Protect type anomaly rate map

---

CMakeLists.txt
src/libnetdata/byteorder.h
src/libnetdata/os.h

- Rename file to avoid header search path conflicts.
- Do not include top-level directory in the headers search path.
- Link h2o library with the main agent binary instead of libnetdata.
- CI jobs.

Assorted build-related changes.

---

packaging/check-for-go-toolchain.sh

This only affects what we install when pulling in a Go toolchain, not the minimum version we check for.
n/a

Bump the version of the installed Go toolchain to 1.22.0.

---

src/daemon/watcher.c
src/libnetdata/completion/completion.c
src/libnetdata/completion/completion.h

SSIA.
- CI jobs
- Start/stop the agent with/without an explicit `sleep(x > 60)` in between the shutdown steps.

Abort the agent if a single shutdown step takes more than 60 seconds.

---

.github/scripts/get-go-version.py
.github/workflows/go-tests.yml

- Adds a GHA workflow which will run `go test`, `go fmt`, and `go vet` for each Go module located under `src/go`, auto-detecting the paths to the modules and the required version of Go.

Add CI checks for Go code.

---

src/health/notifications/alarm-notify.sh.in

Fixes: https://github.com/netdata/netdata/pull/12639#issuecomment-1965956418
Changes to method_names array in alarm-notify.sh: add "gotify" and sort it.
Not needed.
</details>

add missing "gotify" to list of notification methods in alarm-notify.sh

---

contrib/debian/control
contrib/debian/netdata-plugin-network-viewer-plugin.postinst
contrib/debian/netdata-plugin-network-viewer-plugin.preinst
contrib/debian/rules
netdata.spec.in

It should have been in it’s own package to begin with, especially with how potentially sensitive the information it can expose is.
Recommended by default for now, possibly shifted to suggested at some point in the future.

Split network viewer plugin to it’s own package.

---

packaging/installer/kickstart.sh

Given our current platform support spread, it’s far more likely that the user’s system has networking issues preventing access to GitHub than that they happen to be trying to install on a platform we don’t provide static builds for.
n/a
Based on discussion in https://github.com/netdata/netdata/issues/17068

Improve message in kickstart if a static build can’t be found.

---

src/collectors/ebpf.plugin/ebpf.c
src/collectors/ebpf.plugin/ebpf.d.conf
src/collectors/ebpf.plugin/ebpf.d/cachestat.conf
src/collectors/ebpf.plugin/ebpf.d/dcstat.conf
src/collectors/ebpf.plugin/ebpf.d/process.conf
src/collectors/ebpf.plugin/ebpf.d/shm.conf
src/collectors/ebpf.plugin/ebpf.d/swap.conf
src/collectors/ebpf.plugin/ebpf_apps.c
src/collectors/ebpf.plugin/ebpf_apps.h
src/collectors/ebpf.plugin/ebpf_cachestat.c
src/collectors/ebpf.plugin/ebpf_cachestat.h
src/collectors/ebpf.plugin/ebpf_dcstat.c
src/collectors/ebpf.plugin/ebpf_dcstat.h
src/collectors/ebpf.plugin/ebpf_fd.c
src/collectors/ebpf.plugin/ebpf_oomkill.c
src/collectors/ebpf.plugin/ebpf_process.c
src/collectors/ebpf.plugin/ebpf_shm.c
src/collectors/ebpf.plugin/ebpf_shm.h
src/collectors/ebpf.plugin/ebpf_socket.c
src/collectors/ebpf.plugin/ebpf_swap.c
src/collectors/ebpf.plugin/ebpf_vfs.c

This is the last PR before introduction of more eBPF functions.
Blocked by https://github.com/netdata/netdata/pull/16671
1. Configure your `ebpf.d.conf` with the following options:
```sh
[global]
ebpf load mode = return
apps = yes
cachestat = yes
dcstat = yes
fd = yes
oomkill = yes
process = yes
shm = yes
socket = yes
swap = yes
vfs = yes
```
2. Compile branch
3. Look for `libbpf` errors in our logs or using `journalctl`
| Linux Distribution | kernel version  | 
|----------------------------|-----------------------|
|Slackware Current | 6.6.11 | 
|Arch Linux | 6.7.0-arch3-1 |
|Ubuntu 22.04 | 5.15.0-76-generic |
|Alma 9 | 5.14.0-362.13.1.el9_3.x86_64|
|Alma 8.9 | 4.18.0-513.11.1.el8_9.x86_64 | …

Prepare to functions (eBPF)

---

contrib/debian/control
netdata.spec.in

We dont provide ebpf plugin for architectures other than x86_64 i386. We enhance network viewer plugin capabilities with the ebpf-plugin. The previous workflow assumed that in any case, during installation of network viewer plugin we suggest or require the ebpf-plugin. This doesn't work in archs other that (x86_64 i386)
</details>

Amend the logic of ebpf-plugin package suggestion for network-viewer plugin

---

contrib/debian/netdata.postinst

We applied changes on `ioping`, not to `ioping.plugin` 
deb package configurator logs  (ignore the versions)
```
Unpacking netdata-plugin-chartsd (1.52) over (1.50) ...
Preparing to unpack .../15-netdata-plugin-apps_1.52+ubuntu23.10_amd64.deb ...
Unpacking netdata-plugin-apps (1.52) over (1.50) ...
Preparing to unpack .../16-netdata-plugin-xenstat_1.52+ubuntu23.10_amd64.deb ...
Unpacking netdata-plugin-xenstat (1.52) over (1.50) ...
Setting up netdata (1.52) ...
chmod: cannot access '/usr/libexec/netdata/plugins.d/ioping': No such file or directory
Setting up netdata-plugin-pythond (1.52) ...
Setting up netdata-plugin-systemd-journal (1.52) ...
```
</details>

deb packages fix on ioping perms

---

src/collectors/plugins.d/pluginsd_parser.c
src/collectors/systemd-journal.plugin/schema.d/systemd-journal:monitored-directories.json
src/collectors/systemd-journal.plugin/systemd-journal-dyncfg.c
src/collectors/systemd-journal.plugin/systemd-journal-watcher.c
src/database/contexts/api_v2.c
src/database/contexts/query_target.c
src/database/contexts/rrdcontext.h
src/database/rrdhost.c
src/database/rrdlabels.c
src/database/rrdlabels.h
src/database/sqlite/sqlite_health.c
src/health/REFERENCE.md
src/health/health_config.c
src/health/health_dyncfg.c
src/health/health_internals.h
src/health/health_prototypes.c
src/health/health_prototypes.h
src/health/rrdcalc.c
src/health/schema.d/health:alert:prototype.json
src/libnetdata/simple_pattern/simple_pattern.c
src/libnetdata/simple_pattern/simple_pattern.h

Replaces https://github.com/netdata/netdata/pull/16953
Code of @stelfrag is copied to this one.

HEALTH: eliminate fields that should be labels

---

.github/scripts/gen-docker-build-output.py
.github/scripts/gen-docker-imagetool-args.py
.github/scripts/gen-docker-tags.py
.github/workflows/docker.yml

This is required to resolve the fact that we need a _lot_ more disk space for a full build than we used to, which has been leading to builds failing when attempting to publish them.
As a side benefit, this should actually speed up publishing Docker images, and also mostly unifies the code paths for building the images themselves between CI checks and publishing.
Initial testing involves verifying that CI passes on this PR.
Once that testing is done, the PR needs to be merged and a workflow dispatch trigger for the Docker workflow should be issued, with the version set to `nightly`. The current state of the code will attempt to publish images with the name `netdata/netdata-ci-test` on Docker Hub and Quay (repos have already been created on both platforms). Once it’s confirmed that _that_ …

Rework Docker CI to build each platform in it's own runner.

---

src/go/collectors/go.d.plugin/agent/discovery/manager.go
src/go/collectors/go.d.plugin/agent/discovery/sd/pipeline/config.go
src/go/collectors/go.d.plugin/agent/discovery/sd/pipeline/pipeline.go
src/go/collectors/go.d.plugin/agent/discovery/sd/sd.go

Job charts created from discovered (local listeners) configs have priority 0 because default configuration settings are not applied. This PR fixes it.
Before
```
DBG jobmgr/manager.go:293 creating ntpd[local] job, config: map[__provider__:sd:net_listeners __source__:discoverer=net_listeners,host=localhost,file=/opt/netdata/usr/lib/netdata/conf.d/go.d/sd/net_listeners.conf __source_type__:discovered address:127.0.0.1:123 collect_peers:false module:ntpd name:local] component="job manager"
```
After
```
DBG jobmgr/manager.go:293 creating ntpd[local] job, config: map[__provider__:sd:net_listeners __source__:discoverer=net_listeners,host=localhost,file=/opt/netdata/usr/lib/netdata/conf.d/go.d/sd/net_listeners.conf __source_type__:discovered address:127.0.0.1:123 autodetection_retry:0 …
```

fix discovered config default values

---

.github/workflows/docker.yml

Docker’s official GHA action for building and publishing images can _either_ push by digest (which is needed for split multiarch image builds like this) _or_ push to multiple registries, but not both. This means that we need to ‘build’ separately for each registry.
The upshot of this is that publishing to one registry will now work even if another registry is offline or fails in some way.
By building once and exporting the buildx cache, then loading the buildx cache in subsequent jobs we can avoid the need to actually build things multiple times. Note that this cache is _not_ persisted across workflow runs, just between steps in the workflow, so there should be no issues with invalidation.
Actual testing will require merging this and manually triggering a workflow run to confirm it works. …

Second pass at reworking Docker CI.

---

contrib/debian/control
netdata.spec.in

`nut` is not needed. @netdata/agent-sre please check if I missed something, changes are based on `git grep`.
ci and @netdata/agent-sre review
</details>

packaging: remove Suggests nut

---

src/daemon/main.c

Skip waiting when a static thread causes the
agent to exit (eg. the service thread by calling
a fatal).
- Add a non-aborting fatal somewhere in the service thread. Check waiting times with/without this PR.
- CI jobs.

Detect self thread when exiting.

---

src/collectors/plugins.d/functions-table.md

Update functions tables docs

---

src/database/sqlite/sqlite_aclk_alert.c

- Add an additional check for valid alert duration during submission to the cloud

Check alert duration on submission to the cloud

---

src/go/collectors/go.d.plugin/agent/discovery/sd/pipeline/compose.go
src/go/collectors/go.d.plugin/agent/discovery/sd/pipeline/compose_test.go
src/go/collectors/go.d.plugin/config/go.d/sd/net_listeners.conf

Needed to create multiple configs in a template instead of multiple compose config rules.
</details>

go.d.plugin: sd compose: allow multi config template

---

contrib/debian/rules

Install the correct service file based on systemd version

---

src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/netlisteners/netlisteners.go
src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/netlisteners/netlisteners_test.go
src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/netlisteners/sim_test.go

Before:
Discover local listeners only once on start.
After:
Discover local listeners periodically (every minute by default). Remove listeners if they are unavailable for more than the configured threshold (10 minutes by default). This is necessary so that data collection jobs are not immediately deleted if the application stops responding.
</details>

go.d.plugin: execute local-listeners periodically

---

packaging/installer/functions.sh
system/install-service.sh.in

This is not a proper fix but a workaround:
1. set the shell to false to hide from the login screen.
2. set the `IsHidden` flag to hide from System Preferences.
3. set home to a non-existent dir to not create a dir in /Users/.
4. set the user's GID to the `netdata` group GID. This fixes the problem with permissions: NETDATA_GROUP will be `netdata` and not `staff`, see [this line](https://github.com/netdata/netdata/blob/b2f1a09b05dac707a2e82c6f3cc28e5159ff7cf0/netdata-installer.sh#L1106).
The group is still visible in the System Preferences.
A proper fix would be:
- User: create a role account, not a system user. These are the requirements:
- name must be starting with `_`.
- UID must be in the 200-400 range.
- Group: GID must be < 500 to hide the group from System Preferences. …

Fix issues with permissions when installing from source on macOS

---

packaging/installer/kickstart.sh

- Properly handle braindead firewalls that block HTTP HEAD requests.
- Properly bail out early if we failed to download anything.
n/a

Improve offline install error handling.

---

src/database/engine/cache.c
src/database/engine/cache.h
src/database/engine/rrdengineapi.c

- After creating journal file v2, flush open cache only once

Reduce flush operations during journal build

---

src/daemon/main.c
src/database/engine/dbengine-unittest.c
src/database/engine/rrdengineapi.c

Switch to gorilla compression by default for dbengine.

DBENGINE: use gorilla by default

---

src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/netlisteners/netlisteners.go
src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/netlisteners/netlisteners_test.go
src/go/collectors/go.d.plugin/config/go.d/sd/docker.conf
src/go/collectors/go.d.plugin/config/go.d/sd/net_listeners.conf

- **Enhanced process discovery**: Previously, the code only discovered applications listening on IPv4 sockets (`/proc/net/tcp`). This fix ensures applications listening on all interfaces (including IPv6) are discovered by including entries from `/proc/net/tcp6`. Note: Applications might listen on IPv4 without a `/proc/net/tcp` entry.
- **Improved IPv6 handling**: This fix updates configurations to use _Address_ instead of the combination of _IPAddress_ and _Port_. _Address_ handles IPv6 better (uses brackets `[]` for formatting).
- **Fix Apache identification**: The code now reliably identifies Apache processes based on the process name `apache2` (tested on Debian).
</details>

go.d: sd local-listeners: discover /proc/net/tcp6 only apps

---

src/daemon/README.md
src/daemon/main.c
system/freebsd/rc.d/netdata.in
system/openrc/init.d/netdata.in

Fixes: #16981
I think  USR1 "Save internal DB to disk" was used by memory mode save/map - these modes were removed in #16604.
</details>

remove USR1 "Save internal DB to disk"

---

src/go/collectors/go.d.plugin/agent/agent.go

This is needed to set collector defaults (e.g. update_every, priority) for dyncfg jobs.
</details>

go.d: job manager: set config defaults

---

.github/workflows/monitor-releases.yml

The `on.release` event trigger can't support inputs (and defaults like workflow dispatch). Amend the workflow to overwrite the default values whenever we run it manually.
</details>

minor fix in monitor releases workflow

---

packaging/installer/kickstart.sh

This fixes a bug introduced by #13802 which would cause errors in scripts run by the kickstart script to correctly be reported as warnings by the kickstart script, but not actually cause the script to fail in cases when it should have.
The simplest test case involves forcing a local build on a system where a local build is not actually possible.

Correctly propagate errors from child scripts in kickstart.sh.

---

src/collectors/apps.plugin/apps_proc_pid_fd.c

In legacy versions TCP control block had a different pointer.  In modern FreeBSD the generic inpcb and protocol specific pcb is the same pointer.
For reference two FreeBSD commits:
* merge inpcb with tcpcb e68b3792440cac248347afe08ba5881a00ba6523
* netstat(1) to use the new pointer 8e813d07c6804f80e1380b54f6e5fa6d34a3be52 and a test build to detect software that uses legacy pointer:
* https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=277659

apps_proc_pid_fd: ignore kf_sock_inpcb on modern FreeBSD

---

CMakeLists.txt

It somehow got missed when moving the libyaml bundling into the CMake code.
Testing on a system that requires bundling libyaml is needed to confirm that this works.

Correctly handle libyaml linking for log2journal.

---

packaging/repoconfig/netdata-repo.spec

In Amazon Linux 2 the macros `centos_ver`, `amzn2` and `amzn` are defined.
Amazon Linux 2023 defines `fedora`, `amzn2023` and `amzn`.
I don't have the setup to test my changes. 
While running the kickstart.sh installer on my Amazon Linux 2023 instance I noticed a 404 while attempting to download the metadata for the repos 'netdata' and 'netdata-repoconfig'.
```
[/tmp/netdata-kickstart-FxlNJ0FCvi]$ sudo env dnf makecache 
Amazon Linux 2023 repository                                                                                                                                                 31 kB/s | 3.6 kB     00:00    
Amazon Linux 2023 Kernel Livepatch repository …
```

Fix conditional for Amazon Linux 2023 in repoconfig spec file.

---

src/collectors/ebpf.plugin/ebpf.c
src/collectors/ebpf.plugin/ebpf_cachestat.c
src/collectors/ebpf.plugin/ebpf_cgroup.c
src/collectors/ebpf.plugin/ebpf_dcstat.c
src/collectors/ebpf.plugin/ebpf_fd.c
src/collectors/ebpf.plugin/ebpf_oomkill.c
src/collectors/ebpf.plugin/ebpf_process.c
src/collectors/ebpf.plugin/ebpf_shm.c
src/collectors/ebpf.plugin/ebpf_socket.c
src/collectors/ebpf.plugin/ebpf_swap.c
src/collectors/ebpf.plugin/ebpf_vfs.c

eBPF.plugin was adding label for `services`, but we did not have for `cgorups`. This PR address this issue.
The `cgroup_name` will appear only for cgroups that are not services, to show them you can do the following steps:
1. Install docker 
2. Run `docker run -it alpine /bin/sh`
Now
3. Enable integration with cgroup:
```sh
[global]
cgroups = yes
```
4. Start netdata
5. Access `http://localhost:19999/api/v1/charts?all` and confirm `cgroup_name` appears.
</details>

Add label for cgroup

---

src/exporting/prometheus/prometheus.c
src/exporting/prometheus/prometheus.h
src/web/api/exporters/allmetrics.c
src/web/api/netdata-swagger.json
src/web/api/netdata-swagger.yaml

Fixes https://github.com/netdata/netdata/issues/17161
Our exporter was not showing the expected result for `HELP`, instead we were delivering for users `COMMENTS`. This PR address this issue, bringing the expected `HELP` and `TYPE` for prometheus exporter.
2. Access local URL `http://localhost:19999/api/v1/allmetrics?format=prometheus`. You must have `HELP` and `TYPE`
3. Access local URL `http://localhost:19999/api/v1/allmetrics?format=prometheus&types=0`. You should have only `HELP`.
- Which area of Netdata is affected by the change? Exporter
- Can they see the change or is it an under the hood? If they can see it, where? When they are using exporter or access …

Compatibility with Prometheus HELP

---

src/go/collectors/go.d.plugin/config/go.d/postgres.conf
src/go/collectors/go.d.plugin/config/go.d/sd/net_listeners.conf

Fixes: #17302
We didn't recommend this, but apparently, people use a passwordless connection over a Unix socket.
This PR
- Set method to `trust` for Unix connection in `pg_hba.conf`
- Check Postgres data collection job.
</details>

go.d: sd local listeners: add unix socket job

---

.github/workflows/repoconfig-packages.yml

They’re only supposed to go into the repoconfig repositories, not the edge or stable ones.
Somehow this got missed previously.
n/a
Relevant to: #16549

Fix repoconfig publishing.

---

src/daemon/analytics.h

- Change the metadata (alive) event interval to 6 hours (was every 2 hours)

Update metadata frequency

---

src/daemon/main.c

set min thread stack size to 1 MB

---

CMakeLists.txt
system/dinit/netdata.in
system/install-service.sh.in

This adds basic support for installing Netdata as a system service on systems using [dinit](https://davmac.org/projects/dinit/) as a service manager. Such systems are not particularly common, but support for them is also extremely simple to provide, so there’s not much downside to providing such support.
So far this is minimally tested, just enough to ensure that the detection logic works correctly and that the dinit service file passes `dinitcheck` once put in the right place. Testing has only been done thus far on [Chimera Liinux](https://chimera-linux.org/), as that is the only pre-built Linux distribution that uses dinit by default (some other distros, such as Artix, Devuan, and Gentoo, can theoretically use it, but they require a nontrivial amount of manual setup and are thus less …

Add basic support for dinit in our system service handling code.

---

src/collectors/proc.plugin/sys_class_power_supply.c

Use the property name (capacity, charge, energy, voltage) instead of the "power_supply" name (e.g. BAT0).
The issue reported in #17329
</details>

fix proc-power-supply charts family

---

src/libnetdata/dictionary/dictionary-hashtable.h

- The default option for dictionaries is DICT_OPTION_INDEX_JUDY but when DICT_OPTION_INDEX_HASHTABLE is used, it can fail with 
```
#5  0x000074e954a267db in __assert_fail_base (fmt=0x74e954bc5168 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5fb5908579c3 "sl != sl_started", 
function=function@entry=0x5fb5908581a0 <__PRETTY_FUNCTION__.19> "simple_hashtable_get_slot_DICTIONARY") at ./assert/assert.c:92
#6  0x000074e954a39206 in __assert_fail (assertion=0x5fb5908579c3 "sl != sl_started", 
#7  0x00005fb5904f9847 in simple_hashtable_get_slot_DICTIONARY (ht=0x5fb5927106b0, hash=18104129637449712647, key=0x7ffde467b590, resize=false)
```

Call with resize true when dictionary has DICT_OPTION_INDEX_HASHTABLE

---

src/database/engine/rrdengine.c
src/database/engine/rrdengine.h
src/database/rrdhost.c

Presently, each extent accommodates up to 64 pages, although theoretically, an extent could hold up to 109 pages. However, modifying the number of pages per extent and permitting pages exceeding 64 would lead to rejection by older versions of the agent due to certain checks in the code. This pull request aims to loosen this restriction, enabling future agents to utilize more pages per extent.
- Compile this PR and start the agent.
- Let it run for a few minutes (time A to time B)
- Switch to master branch, compile and restart the agent
- All data should be there (esp time frame A --> B)

Increase number of pages per extent in dbengine

---

src/collectors/apps.plugin/apps_groups.conf

A collector that uses `intel_gpu_top` was added in #17344.
</details>

add intel_gpu_top to apps_groups.conf

---

CMakeLists.txt

Snappy is only used by the Prometheus Remote Write exporter, so we should only be checking for it if that is enabled. We also should be checking with pkg-config _first_ instead of doing so after searching for the library directly.

Check for Snappy only when required.

---

.github/data/distros.yml

Skip Debian 10 because it’s known to not work with this, and will be EOL in a few months anyway.

Enable Sentry for Ubuntu and Debian native packages.

---

.github/scripts/build-static.sh
.github/scripts/run-updater-check.sh
.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/docker.yml
netdata-installer.sh
packaging/makeself/build-static.sh
packaging/makeself/build.sh
packaging/makeself/jobs/70-netdata-git.install.sh
packaging/makeself/run-all-jobs.sh

This adds logic to (most of) our CI jobs to skip building Go components during CI checks when they have not been modified. A specific exception is in place so that changes to the build system or CI itself, which inherently do need full testing, will still result in the Go components being built.
Our current infrastructure for handling of native packages does not readily allow this kind of skipping of specific components (RPM can do it easily, DEB packages cannot because they require altering the control file in nontrivial ways prior to the build), so the native package checks will continue to build the Go components in all cases.
All affected CI jobs should be running on this PR, and they should include the Go components in the builds because the changes are to the CI infrastructure …

Skip Go code in CI if it hasn’t changed.

---

packaging/installer/kickstart.sh

Such setups cause all kinds of problems, so properly detect and report them when possible (and refuse to continue until the situation is remidied) to help with debugging and avoid making things worse.
This is done by iteratively checking every directory in the search path, plus checking for the usual static install path without needing it explicitly specified. On regular runs without the issue at hand, this just makes the initial startup of the script a tiny bit slower (less than 0.01% in a Docker container on my laptop, likely similar on most other systems). On systems with multiple conflicting installs of the agent in the system search paths, it will instead bail at the second one it finds and report the issue.
The easiest way to test this is to install on a system that uses native …

kickstart: Add detection of multiple concurrent installs.

---

CMakeLists.txt
packaging/cmake/Modules/NetdataSentry.cmake

This brings it in-line with how we’re handling vendoring of other components as CMake subprojects.

Move vendoring of Sentry to it’s own module and switch to using Git instead of the releases page.

---

src/go/collectors/go.d.plugin/go.mod

As of Go 1.21, version 1.21.0 is the first official Go 1.21 release, and we should thus be explicitly calling out that as the required toolchain version, since depending on version 1.21 would allow use of prerelease versions of the toolchain for Go 1.21, which we very much do not want.
Versioning explanation in the official docs is here: https://go.dev/doc/toolchain#version
This discrepancy was originally spotted because it was flagged as a warning by CodeQL.

Fix required toolchain version for Go code.

---

packaging/installer/kickstart.sh

- Only flag multiple installs if subsequent searches produce a different install path.
- Only set the detected install path if a search actually finds an install path.
- Bail early if the initial search finds nothing.
The first two parts are required for correct operation of the code. The third is a performance optimization in the case of there being no existing install of the agent that would be detected by the kickstart script.
Testing involves using the script from this PR on a system with an existing install. Without these changes, it will always fail early claiming it found a duplicate install. With these changes, it should work correctly.
Fixes: #17368

Fix logic in detection of multiple installs.

---

src/collectors/proc.plugin/plugin_proc.c
src/go/collectors/go.d.plugin/README.md
src/go/collectors/go.d.plugin/config/go.d.conf
src/go/collectors/go.d.plugin/config/go.d/zfspool.conf
src/go/collectors/go.d.plugin/modules/init.go
src/go/collectors/go.d.plugin/modules/intelgpu/metadata.yaml
src/go/collectors/go.d.plugin/modules/zfspool/charts.go
src/go/collectors/go.d.plugin/modules/zfspool/collect.go
src/go/collectors/go.d.plugin/modules/zfspool/config_schema.json
src/go/collectors/go.d.plugin/modules/zfspool/exec.go
src/go/collectors/go.d.plugin/modules/zfspool/init.go
src/go/collectors/go.d.plugin/modules/zfspool/metadata.yaml
src/go/collectors/go.d.plugin/modules/zfspool/testdata/config.json
src/go/collectors/go.d.plugin/modules/zfspool/testdata/config.yaml
src/go/collectors/go.d.plugin/modules/zfspool/testdata/zpool-list.txt
src/go/collectors/go.d.plugin/modules/zfspool/zfspool.go
src/go/collectors/go.d.plugin/modules/zfspool/zfspool_test.go
src/health/health.d/zfs.conf

Fixes: #14937
This PR:
- adds a new collector to monitor the health and space usage of ZFS pools using the `zpool` command line tool ([zpool-list](https://openzfs.github.io/openzfs-docs/man/master/8/zpool-list.8.html)):
- Space utilization (%).
- Space usage (bytes).
- Fragmentation (%).
- Health state.
- disables `/proc/spl/kstat/zfs/pool/state` (c version, collects health state only)
- adds a new alarm for ZFS pools space utilization (%).
Dashboard info update: netdata/cloud-frontend#4521
I tested these changes locally.
</details>

add collector to monitor ZFS pools space usage

---

packaging/installer/kickstart.sh

For some arcane reason, many distros that have chose a merged `/usr` layout (https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/) insist on still putting both `/bin` and `/usr/bin` (and `/sbin` and `/usr/sbin`) in their default `$PATH`, despite the fact that this provides no real benefit (it’s questionable even for ‘backwards compatibility’, anything that truly _needs_ this on a system with a merged `/usr` layout is fundamentally broken).
To correctly handle the fact that it’s not only possible but actually extremely likely that Netdata will show up in more than one place in `$PATH` even if it’s a single install, we need to canonicalize the paths before comparing them when checking for multiple installs.
Unfortunately, despite path canonicalization being an extremely …

Canonicalize paths before comparison when checking for multiple installs.

---

src/libnetdata/log/log.c
src/libnetdata/log/log.h

`overwrite_thread_source` is only accessed in two locations:
- It gets written to only by `nd_log_set_thread_source`, which does not appear to ever be called anywhere in our current code.
- It is only ever read by `nd_log_validate_source`, which, because `nd_log_set_thread_source` is never called, should never end up resulting in any actual behavioral changes (since it will always be 0).
Based on this, the code is functionally dead, and therefore can safely be removed since libnetdata is intended to be for internal use only (and this seems to be relatively low-level even within libnetdata).
From a cursory look at changes, this code has actually _never_ been used in any version of the agent code that is publicly available, though there may have been some intent behind including them that I …

Remove seemingly dead logging related code from libnetdata.

---

src/go/collectors/go.d.plugin/modules/nvme/metadata.yaml

Is not needed because go.d/nvme relies on `ndsudo`.
</details>

go.d nvme meta: remove sudoers prereq

---

.github/workflows/docker.yml

It was broken due to a botched merge when rebasing #17077.
n/a

Fix publishing Docker images to Docker Hub.

---

src/daemon/main.c
src/database/sqlite/sqlite_context.c
src/database/sqlite/sqlite_db_migration.c
src/database/sqlite/sqlite_health.c
src/database/sqlite/sqlite_health.h
src/database/sqlite/sqlite_metadata.c

- Add option to perform a health table cleanup (`netdata -W sqlite-alert-cleanup`)
This operation will be added as a regular cleanup process when the agent is running in a future PR

Add option to cleanup health_log table 

---

.github/labeler.yml

I noticed that 
- issues have `collectors/go.d` label.
- PRs have `collectors/go.d.plugin` label. 
Removing the latter since other `collector/*` labels do not have the .plugin suffix.
</details>

gh labeler: go.d.plugin rm suffix

---

.github/data/distros.yml
.github/scripts/gen-matrix-packaging.py

And only enable it on 64-bit x86 for the moment.
Confirmation that this is working correctly consists of inspecting the generated build matrix for the packaging jobs and confirming that platforms other than 64-bit x86 have a value of `false` for the `bundle_sentry` key. Inspection can be done locally by checking out this PR and running `.github/scripts/gen-matrix-packaging.py 0` to produce the JSON representation of the build matrix.

Split Sentry enablement to be per-architecture.

---

docs/dashboard/logs-tab.md

@netdata/product I looked and the current file about logs (while being a wall of text) details everything about the tab.
To not duplicate info I point the users to the proper spots inside that file.

Logs tab docs in dashboard section

---

packaging/installer/functions.sh
packaging/installer/kickstart.sh
packaging/installer/netdata-updater.sh

Still try to use `curl` first if it exists, but if it fails, fall back to attempting with wget instead.
CI passes on this PR, and local testing confirms that everything still behaves correctly.

Add fallback logic in installer for fetching files.

---

src/database/sqlite/sqlite_aclk_alert.c
src/database/sqlite/sqlite_context.h
src/database/sqlite/sqlite_functions.h
src/database/sqlite/sqlite_health.c
src/database/sqlite/sqlite_health.h
src/database/sqlite/sqlite_metadata.h
src/health/health_prototypes.c

- Cleanup function sql_health_alarm_log_insert (use a separate function to write entries in health_log_detail)
- Use prepared statements to add and update records
- Use macros to simplify error checking and improve core readability

Alert transitions code cleanup

---

CMakeLists.txt

Without this change, it doesn’t fail until the build itself if the plugin is enabled but systemd could not be found.
Secondary testing involves checking a manual build (_without_ using the installer script) on a non-systemd system. Without this change, no failure will be seen until late in the actual build process, while with this change we will bail out during the CMake checks if the plugin is enabled.
Discovered while manually testing a different PR on Alpine.

Explicitly require systemd for systemd journal plugin.

---

src/go/collectors/go.d.plugin/README.md
src/go/collectors/go.d.plugin/config/go.d.conf
src/go/collectors/go.d.plugin/config/go.d/adaptec_raid.conf
src/go/collectors/go.d.plugin/modules/adaptecraid/adaptec.go
src/go/collectors/go.d.plugin/modules/adaptecraid/adaptec_test.go
src/go/collectors/go.d.plugin/modules/adaptecraid/charts.go
src/go/collectors/go.d.plugin/modules/adaptecraid/collect.go
src/go/collectors/go.d.plugin/modules/adaptecraid/collect_ld.go
src/go/collectors/go.d.plugin/modules/adaptecraid/collect_pd.go
src/go/collectors/go.d.plugin/modules/adaptecraid/config_schema.json
src/go/collectors/go.d.plugin/modules/adaptecraid/exec.go
src/go/collectors/go.d.plugin/modules/adaptecraid/init.go
src/go/collectors/go.d.plugin/modules/adaptecraid/metadata.yaml
src/go/collectors/go.d.plugin/modules/adaptecraid/testdata/config.json
src/go/collectors/go.d.plugin/modules/adaptecraid/testdata/config.yaml
src/go/collectors/go.d.plugin/modules/adaptecraid/testdata/getconfig-ld-current.txt
src/go/collectors/go.d.plugin/modules/adaptecraid/testdata/getconfig-ld-old.txt
src/go/collectors/go.d.plugin/modules/adaptecraid/testdata/getconfig-pd-current.txt
src/go/collectors/go.d.plugin/modules/adaptecraid/testdata/getconfig-pd-old.txt
src/go/collectors/go.d.plugin/modules/init.go
src/health/health.d/adaptec_raid.conf

The newer version offers several improvements:
- No need to reset CapabilityBoundingSet.
- No requirement to add netdata user to sudoers.
- Charts include labels, providing specific details about failing logical and physical devices in alerts.
- Includes tests and sample data, simplifying future extension or improvement.
</details>

go.d rewrite python.d/adaptec_raid

---

src/daemon/main.c

- Start the watcher thread after fork (`-D` option not specified)
Fixes #17435

Start watcher thread after fork

---

src/health/health_event_loop.c

- If resume from suspension is detected, schedule an node update to revive the connection

Reconnect to the cloud when resuming from suspension

---

packaging/makeself/functions.sh

Our static builder images now include GNU coreutils, as it is required for proper handling of libbpf during the build process, but this broke file checksum validation in the build process as `sha256sum` from coreutils lacks a single-letter version of the `--status` option that we use.
This fixes things in the build code to work correctly.

Fix usage of sha256sum in static builds.

---

src/database/rrdlabels.c

- Fix the case of labels name only matching. This is an  `or` operation since one of the label names need to match

Fix labels name-only matching

---

.github/workflows/build.yml
.github/workflows/go-tests.yml
.github/workflows/packaging.yml
.github/workflows/platform-eol-check.yml
.github/workflows/repoconfig-packages.yml

Upstream issue reference: https://github.com/microsoft/linux-package-repositories/issues/130
Not a complete workaround, but this is the best we can do without modifying code that runs on user systems.
Build matrix generation for CI jobs works correctly on this PR.

Work around MS’s broken infra in CI.

---

packaging/cmake/Modules/NetdataUtil.cmake

The syntax in the conditionals at the start was wrong, but the control flow was also semantically wrong as well. Fixing the semantic issue gets rid of the conditional with the incorrect syntax as well.

Fix handling of kernel version detection in CMake.

---

CMakeLists.txt

- Ensure that they have a properly descriptive help string that can be understood without detailed knowledge of Netdata.
- Ensure that options that are not intended to be used by regular users are flagged as advanced (and thus do not show up in the various CMake UIs by default).
- Ensure that options that are logically dependent on others are handled as such by CMake.
- Properly sort main options, and label the groups with comments describing them.
Other than the handling of conditional options, this should not result in any functional changes.
The conditional option handling should not result in any significant functional changes, other than ensuring correctness in the case of the logs management tests (the option is ignored if the plugin is not enabled) and disallowing a nonsensical …

Clean up CMake build options.

---

CMakeLists.txt

Our CMake code definitely works fine with all versions from our minimum suppored version of 3.13 up to and including 3.28, and any of the policies that are likely to affect us should use the new behavior anyway because the old behavior leads to the possiblity of incorrect builds, so explicitly request that CMake all CMake policies provided by the used version up to those provided by v3.28.0 are set to the new behavior.
Relevant CMake documentation entries explaining the implications of the change:
- https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#policy-settings
- https://cmake.org/cmake/help/latest/command/cmake_policy.html#setting-policies-by-cmake-version

Update CMake to request new behavior for all policies through v3.28.0.

---

CMakeLists.txt

#17442 broke option handling for cloud claiming in the build system. Revert the specific part that broke this so that it works again.
Fixes: #17526
Local testing.

Revert changes to ENABLE_CLOUD option.

---

packaging/makeself/build.sh

We’re using a separate build directory in all cases, so there is no longer any need to try to clean the repository before a static build. This enables running static builds in linked git worktrees.
Without this change, trying to run a static build in a linked git worktree will fail very early on with a complaint about something not being a git directory.
With this change, this failure will not happen.

Don’t unnescesarily clean repo during static builds.

---

CMakeLists.txt

Not a mandatory dependency, but it significantly speeds up the final linking step for builds.
Some local testing required, but there should be no differences in CI with this (yet).

Detect and use ld.mold instead of the system linker.

---

CMakeLists.txt
netdata.spec.in

Both `netdata.conf` and `netdata-updater.conf` should not be touched in `/etc/netdata` by the build system, but they currently are overwritten with the defaults on each install.
Originally broken by #17475.
Does not affect Docker images or native packages, only static builds and local builds.
Local testing is required to confirm that the files are not modified.

Fix handling of netdata.conf on install in build system.

---

src/daemon/commands.h
src/daemon/main.c

- Increase the command size to the spawn server to 8kbytes (currently 4kbytes). Normal this shouldn't be a problem unless there is a list of a lot of historical alerts (warn and critical) that will cause this overflow. The sender already sanitizes and expects the command size to be up to 8kbytes.
- A failure will cause the spawn server to exit but cause a core dump during the shutdown. Add a check that prevents the spawn server from crashing in this case (skip the watcher checks during shutdown).

Increase the message size to the spawn server

---

src/daemon/main.c
src/database/rrdhost.c

If we try to compile our current master with option `--disable-dbengine`, the compilation does not end due two different errors. 
This PR  addresses these two isseus.
1. Compile this PR with `dbengine` enabled. Run `netdata`.
2. Recompile this PR with option `--disable-dbengine`, and `netdata` should finish the compilation normally. When you start, it should use `memory mode = ram`.
</details>

Fix compilation without `dbengine`

---

packaging/cmake/Modules/Packaging.cmake

- Proper list joining
- Fix typo
- Run `cpack -G DEB` from within the build directory.
- Go to `build/packages` and run something like `dpkg-deb -R <package-name> <folder>`
- Inspect `<folder>/DEBIAN/control` to check deps.

Cpack fixes

---

packaging/cmake/control/netdata/postinst

We should not be referencing files from other packages in our postinst script.
To test, install the generated `netdata` package without installing recommended packages (just regular dependencies). Without this PR, there will be an error logged by chmod about the network-viewer plugin not being found. With this PR, there will be no such error.

Fix invalid item in postinst script for Netdata package.

---

docs/netdata-agent/versions-and-platforms.md

Minor documentation update to add Ubuntu AArch64 architecture which was missing from the list as well as minor grammar updates.
AArch64 is supported in the netdata repo as seen here (packages named arm64) http://repo.netdata.cloud/repos/stable/ubuntu/jammy/
</details>

docs: Add Ubuntu AArch64 that is missing from the list

---

packaging/cmake/control/netdata/postinst

It was previously working before the shift to CPack because the old dh_installinit code happened to also work to start systemd services. That part was not copied over though because we don’t really officially support non-systemd Debian/Ubuntu systems, which in turn broke things.
This updates the postinstall script to correctly handle this
Build the packages locally, install them, and confirm that the agent is running.
Fixes: #17588

Fix handling of service startup in DEB packages.

---

packaging/installer/kickstart.sh

Default behavior will still be to download all supported architectures (because there _will_ be users who do not pay attention to matching architectures between the system used to prepare the installl source and the system where they are actually installing), but this will allow those who know what they’re doing to just prepare things for a specific target system.
The new option is called `--offline-architecture`. It can be specified multiple times (in which case it will result in the full set of architectures being used), and will throw a fatal error if an unrecognized value is passed.
Requires manual local testing of the `--prepare-offline-install-source` option with and without the new option.

Add option to limit architectures for offline installs.

---

src/database/rrd.h
src/database/rrddim.c
src/database/rrdset.c
src/health/health_event_loop.c
src/health/rrdcalc.c
src/health/rrdcalc.h
src/streaming/receiver.c

When a child disconnects from a parent, remove all the running alerts from all charts.

reset health when children disconnect

---

packaging/makeself/install-or-update.sh
src/daemon/commands.h
src/daemon/main.c
src/database/rrd.h
src/database/rrddim.c
src/database/rrdlabels.c
src/database/rrdset.c
src/database/sqlite/sqlite_context.c
src/database/sqlite/sqlite_db_migration.c
src/database/sqlite/sqlite_health.c
src/database/sqlite/sqlite_health.h
src/database/sqlite/sqlite_metadata.c
src/health/health_event_loop.c
src/health/health_prototypes.c
src/health/rrdcalc.c
src/health/rrdcalc.h
src/health/schema.d/health:alert:prototype.json
src/streaming/receiver.c

- add update every to json schema (#17613)
- reset health when children disconnect (#17612)
- fix ndsudo setuid bit for static builds (#17583)
- fix compilation with `--disable-dbengine` : Add missing ifdef to daemon/main 
- Increase the message size to the spawn server (#17566)
- Report correct error code when data insert fails (#17508)
- Fix labels name-only matching (#17482)
- Reconnect to the cloud when resuming from suspension (#17444)
- Start watcher thread after fork (#17436)
- Add option to cleanup health_log table  (#17385)
- apply first alarms, then alarm templates (#17398)
---
Fixes: #17563
Fixes: #17549

Patch release 1.45.4

---

src/database/sqlite/sqlite_aclk_alert.c

In a claimed parent and child agent setup, when a child disconnects, all the child's alerts are removed. Up until now the REMOVED alert transition was not submitted to the cloud. This can result in an inconsistency when viewing alerts on the cloud dashboard.
This PR changes this behavior to send the REMOVED alert transition to the cloud if previous status of the alert is WARNING or CRITICAL.

Improve handling of an alert that transitions to the REMOVED state

---

packaging/installer/install-required-packages.sh

It is required - building on macOS (newly created VM) failed without this package.
</details>

add pcre2 to install-required-packages "netdata" for macOS

---

src/collectors/apps.plugin/apps_groups.conf

[Valkey](https://valkey.io) is a Redis alternative under the Linux Foundation.

Add valkey to apps_groups.conf

---

src/database/sqlite/sqlite_aclk_alert.c

- Fix incorrect bind warning that may appear in the logfile e.g.
`Failed to bind parameter 1 (@period) in sql_aclk_alert_clean_dead_entries`

Fix incorrect bind failure warning

---

src/go/collectors/go.d.plugin/cmd/godplugin/main.go

go.d update config dirs

---

.github/data/distros.yml
packaging/PLATFORM_SUPPORT.md

EOL upstream as of 2024-05-14.
n/a
Closes: #17546

Remove Fedora 38 from CI.

---

packaging/installer/kickstart.sh
packaging/installer/netdata-updater.sh

Add limited support for offline installs to the updater code.
This allows use of a prepared offline install source to update an existing offline install by simply following the usual offline installation instructions, instead of needing to manually specify the `--reinstall` option to run an update. This particular implementation has a couple of specific limitations:
- It only works if the _current_ version of the offline install includes the changes in this PR. This is because the updater script in an offline install cannot update itself, and thus is stuck with whatever functionality it had when installed.
- It does not support version comparison. There is little benefit to having support for this, and not implementing it significantly simplifies the code.
- The offline install source …

Support offline installs in the updater code.

---

src/aclk/https_client.c

- Adds the `Host:` in the HTTP header also for the CONNECT

Include the Host in the HTTP header

---

CMakeLists.txt
packaging/cmake/Modules/NetdataJSONC.cmake
packaging/cmake/Modules/NetdataLibBPF.cmake
packaging/cmake/Modules/NetdataProtobuf.cmake
packaging/cmake/Modules/NetdataYAML.cmake

`target_compile_definitions` can only be used for actual command line _macro definitions_. But the `*_CFLAGS_OTHER` may contain flags that are _not_ macro definitions, and when that happens, any use of `target_compile_definitions` with the relevant `*_CFLAGS_OTHER` variable will break the build.
Instead, we should be using `target_compile_options` for these variables.
Observe that the CI jobs for Rocky Linux 8 and CentOS 8 Stream pass on this PR, despite failing on the master branch.

Correctly handle required compilation flags for dependencies.

---

src/collectors/timex.plugin/plugin_timex.c

- Sleep per second and iterate as needed (be more responsive during shutdown)

Fix timex slow shutdown

---

src/collectors/plugins.d/pluginsd_parser.c

- Check for empty dimension or dimension creation failure and disable plugin
Fixes #17671

Check for empty dimension id from a plugin

---

packaging/cmake/Modules/NetdataUtil.cmake

Needed for correct configuration on systems that hide the libc implementation info in `ldd` output, like Gentoo.
This can be easily tested on a Gentoo system by trying to build Netdata by hand with eBPF enabled.
Without this PR, the configuration step will fail due to not being able to identify the libc implementation.
With this PR, the configuration step should succeed and correctly detect the libc implementation.
Fixes: #17651

Fall back to querying libc.so.6 if ldd can’t detect libc implementation.

---

src/collectors/perf.plugin/metadata.yaml

Corrected some grammar mistakes in the metadata file, plus amending the misspelling of the perf command.
N/A
N/A

Corrected grammar and mispelling

---

integrations/cloud-authentication/metadata.yaml

related to https://github.com/netdata/learn/issues/2086, the `&` is not escaped in plaintext, thus interferes with a symbol on Learn rendering, messing up the link

fix on link

---

src/collectors/windows.plugin/perflib-memory.c

As we have already talked in our meeting, I am adding a missing multiplier.
1. Compile on Microsoft and verify chart is working.
</details>

Fix multipler on Windows ("Memory")

---

src/collectors/plugins.d/pluginsd_parser.c
src/daemon/commands.c
src/daemon/commands.h
src/database/sqlite/sqlite_metadata.c
src/database/sqlite/sqlite_metadata.h

- Adds a new command `remove-stale-node` to `netdatacli`. It takes as a parameter a machine guid or a node id and it will unregister this node from the cloud
- Checks and prevents the local agent (parent) from being removed
- Checks and prevents a live child from being removed

Add agent CLI command to remove a stale node

---

src/daemon/commands.c
src/daemon/commands.h

- Fix compilation error when `disable-cloud` is specified
- `remove-stale-node` CLI command is not available when compiling with cloud disabled

Fix compilation with disable-cloud

---

src/collectors/freeipmi.plugin/freeipmi_plugin.c

This PR address an issue reported on Slack:
```sh
[105/370] Building C object CMakeFiles/freeipmi.plugin.dir/src/collectors/freeipmi.plugin/freeipmi_plugin.c.o
FAILED: CMakeFiles/freeipmi.plugin.dir/src/collectors/freeipmi.plugin/freeipmi_plugin.c.o 
/usr/bin/cc -D_GNU_SOURCE -I/usr/include/uuid -I/home/stelios/git/netdata/cmake-build-debug -I/home/stelios/git/netdata/src -I/usr/include/json-c -I/home/stelios/git/netdata/src/libnetdata/libjudy/src -I/home/stelios/git/netdata/src/libnetdata/libjudy/src/JudyCommon -Wall -Wextra -Wmaybe-uninitialized -g -std=gnu11 -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wno-builtin-macro-redefined -fexceptions -MD -MT CMakeFiles/freeipmi.plugin.dir/src/collectors/freeipmi.plugin/freeipmi_plugin.c.o -MF …
```

Rename a variable in FreeIMPI (WolfSSL support)

---

src/go/collectors/go.d.plugin/config/go.d/mongodb.conf

Indentation for the default mongodb config is wrong. This causes a lot of confusion when you just uncomment the provided config, and it doesn't work.

Fix mongodb default config indentation

---

src/collectors/proc.plugin/proc_diskstats.c

The last collected value is in bytes. It needs to be converted to sectors.
This bug was added in #17497.
</details>

fix proc plugin disk_avgsz

---

.github/workflows/build-macos.yml
CMakeLists.txt

- Fix dependency installation in CI.
- Switch to using an imported target for the TLS implementation.
- Keep the TLS related stuff together.
- Use the same name for the WolfSSL and OpenSSL targets, once detected the build system does not care which is being used beyond what the imported target tells it.

Fix handling of OpenSSL linking on macOS

---

CMakeLists.txt
netdata.spec.in
packaging/cmake/Modules/NetdataProtobuf.cmake
packaging/cmake/Modules/NetdataYAML.cmake
packaging/installer/kickstart.sh
packaging/installer/netdata-updater.sh
packaging/makeself/functions.sh
src/aclk/https_client.c
src/collectors/plugins.d/pluginsd_parser.c
src/database/sqlite/sqlite_aclk_alert.c
src/go/collectors/go.d.plugin/agent/jobmgr/dyncfg.go
src/go/collectors/go.d.plugin/modules/cockroachdb/collect.go
src/go/collectors/go.d.plugin/modules/windows/config_schema.json
src/go/collectors/go.d.plugin/modules/windows/testdata/config.json
src/go/collectors/go.d.plugin/modules/windows/testdata/config.yaml
src/go/collectors/go.d.plugin/modules/windows/windows.go
src/ml/ml-private.h
src/streaming/sender.c

- go.d windows add "vnode" to config schema (#17478)
- go.d cockroachdb fix calculation (#17659)
- Fix usage of sha256sum in static builds. (#17495)
- fix sender parsing when receiving remote input (#17696)
- Check for empty dimension id from a plugin (#17690)
- Re-enable ML for RHEL 7 and AL 2 RPM packages. (#17682)
- Fix CentOS 7 builds for ML. (#17667)
- Include the Host in the HTTP header (#17670)
- Improve handling of an alert that transitions to the REMOVED state (#17621)

Patch release 1.45.5

---

src/database/contexts/api_v2.c
src/database/rrdlabels.c
src/database/rrdlabels.h

- Adds additional information to /api/v2/alerts endpoint
Sample:
Before
```
{
"ati":8,
"nm":"ram_in_use",
"sum":"System memory utilization",
"cr":0,
"wr":0,
"cl":6,
"er":0,
"in":6,
"nd":6,
"cfg":2
}
```
After
```
{
"ati":8,
"nm":"ram_in_use",
"sum":"System memory utilization",
"cr":0,
"wr":0,
"cl":6,
"er":0,
"in":6,
"nd":6,
"cfg":2,
"ctx":["system.ram"],
"cl":["utilization"],
"cp":["memory"],
"ty":["system"],
"to":["sysadmin"]
}
```
- ctx -- context
- cl -- classification
- cp -- component
- ty -- type
- to -- receipient

Add alert meta info

---

src/aclk/mqtt_websockets/mqtt_wss_client.c

- Adds the Host: in the HTTP header also for the CONNECT to mqtt. This was missed in the original PR
Additional fix for #17670

Include the Host in the HTTP header (mqtt)

---

CMakeLists.txt
packaging/cmake/Modules/NetdataFetchContentExtra.cmake
packaging/cmake/Modules/NetdataJSONC.cmake
packaging/cmake/Modules/NetdataProtobuf.cmake
packaging/cmake/Modules/NetdataSentry.cmake
packaging/cmake/Modules/NetdataYAML.cmake

If not explicitly set using exported environment variables (or a toolchain file specified via the environment), the choice of compilers and compiler targets used by CMake does not get propagated to sub-porjects created with ExternalProject_Add or FetchContent_Declare in some situations.
In most cases this does not matter, because very few people are building using non-default compilers for their environment, but it can cause issues in two specific cases:
- If building for the same system that the build is happening on, but using a non-default compiler specified using CMake arguments (instead of via exported environment variables), sub-projects will still use the default compiler for the system, which may result in linking errors (or runtime failures even if the link succeeds).
- If …

Ensure that the choice of compiler and target is passed to sub-projects.

---

.github/data/distros.yml
packaging/PLATFORM_SUPPORT.md

End of life upstream as of 2024-05-23.
n/a
Closes: #17545

Remove Alpine 3.16 from CI.

---

src/daemon/commands.c

- Schedule a node info update on label reload via `netdatacli reload-labels`

Schedule a node info on label reload

---

src/collectors/diskspace.plugin/plugin_diskspace.c
src/collectors/proc.plugin/proc_diskstats.c

Netdata ignores some system metrics as long as their value is 0. This logic was originally applied to various types of errors, and the goal was to reduce the overall number of metrics collected (less memory usage, less disk space). This is no longer a problem with the current version of dbengine (zstd compression + gorilla compression).
Ignoring zero metrics leads to unobvious problems. For instance, missing charts after a server reboot.
There will be multiple PRs to remove this "ignore zero metrics" logic from different collectors. This PR removes it from:
- proc/diskstats
- diskspace
</details>

proc/diskstats and diskspace: remove "ignore zero metrics"

---

src/collectors/proc.plugin/proc_net_netstat.c
src/collectors/proc.plugin/proc_net_sctp_snmp.c
src/collectors/proc.plugin/proc_net_sockstat.c
src/collectors/proc.plugin/proc_net_sockstat6.c
src/collectors/proc.plugin/proc_net_stat_synproxy.c

This PR remove ignoring zero metrics logic from:
- proc/netstat
- proc/sockstat
- proc/socksta6
- proc/net_stat_synproxy
- proc/net_sctp_snmp
</details>

remove "ignore zero metrics" from proc network modules

---

src/go/collectors/go.d.plugin/go.mod
src/go/collectors/go.d.plugin/go.sum
src/go/collectors/go.d.plugin/modules/phpfpm/client.go

Because the upstream fcgi_client library:
- doesn't implement connection read/write timeout
- seems to be unmaintained: PR with read/write timeout has been hanging since 2021
Switching to fork with timeout - https://github.com/kanocz/fcgi_client.
See https://github.com/netdata/netdata/issues/17780#issuecomment-2139227972 for details.
Fixes: #17780
</details>

go.d phpfpm switch to github.com/kanocz/fcgi_client

---

src/collectors/proc.plugin/proc_meminfo.c
src/collectors/proc.plugin/proc_vmstat.c

This PR removes ignoring zero metrics logic from:
- proc/meminfo
- proc/vmstat
</details>

rm "ignore zero metrics" proc meminfo

---

src/collectors/proc.plugin/proc_net_dev.c

This PR removes ignoring zero metrics logic from:
- proc/net_dev
</details>

proc/net_dev: remove "ignore zero metrics"

---

CMakeLists.txt

SSIA.
`cpack -G DEB` should not print any missing files warnings.

Use correct path for package files.

---

src/collectors/cgroups.plugin/README.md
src/collectors/cgroups.plugin/cgroup-charts.c
src/collectors/cgroups.plugin/cgroup-discovery.c
src/collectors/cgroups.plugin/cgroup-internals.h
src/collectors/cgroups.plugin/sys_fs_cgroup.c
src/collectors/proc.plugin/proc_pressure.h

This PR adds the following updates to the groups plugin:
- Removes "ingore zero metrics" (reasoning in [17775](https://github.com/netdata/netdata/pull/17775)).
- Removes enable/disable specific metrics and path settings. There are a lot them and they don't provide any value in general.
<details>
<summary>all removed settings </summary>
```
```
</details>
Add/remove containers, and check charts on hosts with cgroup v1 and v2.
</details>

cgroup plugin: simplify and remove "ignore zero metrics"

---

src/database/sqlite/dbdata.c
src/database/sqlite/sqlite3.h
src/database/sqlite/sqlite3recover.c

- sqlite upgrade from version 3.42.0 to 3.45.3
- Recovery code files also updated

Upgrade sqlite version to 3.45.3

---

src/collectors/cgroups.plugin/sys_fs_cgroup.c

This PR fixes an issue introduced in #17795: we shouldn't "full" chart if the metric is not available, e.g.:
```
$ cat /sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod001f7c0e_a641_4538_84c3_06e5a67f4073.slice/cri-containerd-334ee75a65caba05a913a0e9908baea20a6448364a9a61583d6669fed25e721b.scope/cpu.pressure
some avg10=0.00 avg60=0.00 avg300=0.00 total=98464
```
</details>

fix cgroups pressure

---

.github/data/distros.yml

It’s EOL as of 2024-05-31.
n/a
Closes: #17595

Remove CentOS Stream 8 from CI.

---

src/database/contexts/api_v2.c

- Fix an issue with "cl" (classification) overriding clear count. It is changed to be "cls"

Change classification to "cls" since "cl" is clear count

---

src/collectors/proc.plugin/sys_kernel_mm_ksm.c

Last e-mail reported:
```sh
*** CID 426217:  Control flow issues  (DEADCODE)
/src/collectors/proc.plugin/sys_kernel_mm_ksm.c: 190 in do_sys_kernel_mm_ksm()
184                         , RRDSET_TYPE_LINE
185                 );
186     
187                 rd_savings = rrddim_add(st_mem_ksm_ratios, "savings", NULL, 1, 10000, RRD_ALGORITHM_ABSOLUTE);
188             }
189     
>>>     CID 426217:  Control flow issues  (DEADCODE)
>>>     Execution cannot reach the expression "0ULL" inside this statement: "rrddim_set_by_pointer(st_me...".
190             rrddim_set_by_pointer(st_mem_ksm_ratios, rd_savings, offered ? (saved * 1000000) / offered : 0);
191             rrdset_done(st_mem_ksm_ratios);
192         }
193     
194         return 0;
````
This PR remove the dead code.
1. Check CI …

Fix coverity report

---

src/aclk/mqtt_websockets/mqtt_wss_client.c
src/daemon/commands.c
src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/netlisteners/netlisteners.go
src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/netlisteners/netlisteners_test.go

- go.d sd local-listeners fix extractComm (#17763)
- Schedule a node info on label reload (#17762)
- Include the Host in the HTTP header (mqtt) (#17731)

Patch release 1.45.6

---

src/claim/netdata-claim.sh.in

We must set "proxy" in "cloud.conf" if a proxy was used during claiming for ACLK to continue using it.
</details>

claiming: add proxy to cloud.conf if set

---

src/database/contexts/api_v2.c

- Add an ni array (index to nodes that the alert applies)
Before
```
{
"ati":4,
"nm":"active_processes",
"sum":"System PIDs utilization",
"cr":0,
"wr":0,
"cl":1,
"er":0,
"in":2,
"nd":2,
"cfg":1,
"ctx":["system.active_processes"],
"cls":["workload"],
"cp":["processes"],
"ty":["system"],
"to":["sysadmin"]
}
```
after
Adding `"ni": [0,7]` index array to the nodes that the alert applies
```
{
"ati":4,
"ni":[0,7],
"nm":"active_processes",
"sum":"System PIDs utilization",
"cr":0,
"wr":0,
"cl":1,
"er":0,
"in":2,
"nd":2,
"cfg":1,
"ctx":["system.active_processes"],
"cls":["workload"],
"cp":["processes"],
"ty":["system"],
"to":["sysadmin"]
}
```

Add alert meta info (node index)

---

src/daemon/config/dyncfg-files.c

Fixes: https://github.com/netdata/netdata/pull/17694#issuecomment-2146918353
</details>

fix order of loading schema files in dyncfg_get_schema_from

---

src/collectors/python.d.plugin/python.d.conf

Fixes issues like ([mentioned on the forum](https://community.netdata.cloud/t/monitoring-netdata-itself/5499)):
> After Netdata update, MySQL monitoring stops running because the plugin changed from Python.d to go.d or something like that.
for existing installations.
Without explicit disabling, a race condition occurs depending on whichever starts first.
</details>

explicitly disable removed collectors in python.d.conf

---

src/collectors/proc.plugin/proc_net_dev.c

Remove:
- paths: not needed.
- enable/disable specific metrics: why would you want to disable collecting traffic or packets for all interfaces? I don't know either. If not desired, it can be filtered during streaming/exporting.
</details>

proc net dev: simplify config

---

netdata.spec.in
packaging/cmake/Modules/NetdataProtobuf.cmake

Their system copy is demonstrably problematic, and months of searching for a solution has so far been unsuccessful, so just use a bundled copy instead.
openSUSE package build CI jobs pass on this PR.

Use bundled protobuf for openSUSE packages.

---

src/libnetdata/aral/aral.c

SSIA.
- CI jobs
Not sure why this does not cause problems on non-Windows platforms. In theory, the spinlock would get the wrong initial value 50% of the time because the lock is just a boolean. A major difference between Windows vs. non-Windows platforms is that the minimum sleep duration on Windows is at least 1ms which is a pretty long time in comparison to the other platforms.

Properly initialize spinlock in ARAL.

---

src/database/engine/rrdengine.c

- change family "dbengine" => "dbengine retention"
- update priority to move the chart above "dbengine memory"
</details>

update dbengine retention chart family and priority

---

src/database/contexts/api_v2.c
src/database/engine/rrdengine.c

When memory mode is non dbengine
- Fix tier statistics when memory mode is not dbengine
- Avoid querying disk space
- Skip retention checks for non dbengine tiers

Fix tier statistics 

---

src/database/engine/rrdengine.c

- Verify localhost is created when retention check runs
- Agent init may take a long time in some cases (> 1 min)

Delay retention check until agent has initialized

---

packaging/installer/netdata-updater.sh

This attempts to detect when run under Anacron (by inspecting the parent process ID of the script itself), and if so it overrides the interactivity detection to disable the random delay during the update process. The detection is a bit fragile and may not work in all cases, but it should run properly (even if it may give a false negative) on any system that provides a version of `ps` that is either POSIX compliant _or_ that is provided by Busybox.
Testing is unfortunately complicated for this, but basic confirmation that it still works as intended for the normal case is relatively easy and should be mostly sufficient.
Fixes: #17745

Disable updater jitter when run from anacron.

---

src/daemon/service.c
src/database/engine/rrdengine.c

An agent with memory mode RAM or ALLOC may initialize dbengine if incoming children have requested
dbengine storage.
This PR will allow the creation of dbengine retention charts for tiers > 0

Create retention charts for higher tiers

---

packaging/installer/kickstart.sh
packaging/makeself/install-or-update.sh

Our current static builds include a bundled copy of the CA certificates available in the build environment, and will automatically fall back to using those if they can’t find a usable set of CA certificates on the target system.
This works in a majority of cases, but it has a couple of issues:
- It doesn’t properly support the case of users who want to just use our bundled certificates unconditionally for some reason.
- It doesn’t actually _test_ that the system certificates work to connect to Netdata infrastructure, and thus it’s entirely possible that we end up with an install we can’t claim because the users are refusing to follow security best practices and keep their CA certificate store up to date.
This PR works to remedy those issues. It adds additional logic to the installation …

Add improved handling for TLS certificates for static builds.

---

packaging/installer/netdata-updater.sh

Instead of only checking the parent and grandparent processes, walk up the process tree until we either find anacron or find init (or hit the recursion limit for the function, which is currently 50 iterations). This is needed because at least on some systems there is more than one intermediate process between the script and anacron.
Requires manual testing.

Improve anacron detection in updater.

---

src/go/collectors/go.d.plugin/modules/phpfpm/config_schema.json
src/go/collectors/go.d.plugin/modules/phpfpm/phpfpm.go

Dyncfg doesn't work for `go.d/phpfpm` because it doesn't have a configuration schema. The issue is [reported on the community forum](https://community.netdata.cloud/t/help-request-php-fpm-collector-something-went-wrong/5534/1).
</details>

go.d phpfpm add config schema

---

integrations/cloud-notifications/integrations/telegram.md
integrations/cloud-notifications/metadata.yaml

Updates the Telegram Cloud notification integration method docs, to include a new optional field
This was tested and validated in `staging` env.
Users asked for the addition of this optional field and we listened.

update Telegram Cloud notification docs to include new topic ID field

---

system/lsb/init.d/netdata.in

We seem to have been relying on some Debian-specific stuff instead of actually following LSB requirements.
This will require manual testing of a build on a system that actually uses LSB init scripts and does not provide the functions that are being removed. Most likely candidate is to produce a static build, install that on an RHEL/CentOS 6 system, and confirm there.
Without these changes, most operations will fail with complaints about commands not being found.
With these changes, everything _should_ work correctly.
Fixes: #17816

Make our LSB init script _actually_ LSB compliant.

---

src/daemon/main.c

The ML thread termination during shutdown has been restored  to it's previous order as it seems to cause some errors during shutdown or crash, so the previous thread termination order has been restored.
- Start/Stop agent with ML enabled before and after this PR

Restore ML thread termination to original order

---

integrations/gen_docs_integrations.py
integrations/templates/metrics.md
integrations/templates/setup.md

It seemed like all folded sections should be closed by default, but after using our documentation I changed my mind.
</details>

integrations make `<details>` open

---

src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/netlisteners/netlisteners.go
src/go/collectors/go.d.plugin/agent/discovery/sd/discoverer/netlisteners/netlisteners_test.go

Quick support for #17866 (if it will be merged). Use IPv4 for dual-stack LISTEN connections.
</details>

go.d ll netlisteners add support for wildcard address

---

packaging/docker/README.md

Related to item 3 in https://github.com/netdata/netdata/issues/17899.
Unrelated `restart:` and `hostname:` in Netdata docker-compose setup are updated to match ones in "Recommended way" section.
Manually reproduce setup from the doc.

Fix Caddy setup in Install Netdata with Docker

---

CMakeLists.txt
netdata-installer.sh
packaging/installer/functions.sh
packaging/installer/netdata-uninstaller.sh
packaging/makeself/install-or-update.sh
system/systemd/journald@netdata.conf

Related: #17737
The default limit for journal files (`SystemMaxUse`/`RuntimeMaxUse`) is 4GB.
It makes sense to install netdata journald config file with smaller values.
@Ferroin please update deb/rpm packages
</details>

add netdata journald configuration

---

src/go/collectors/go.d.plugin/modules/x509check/metadata.yaml

Schema smtp already works, it is already used in this file in an example, and it is mentioned in config_schema.json.

Update x509check/metadata: add missing smtp schema

---

system/systemd/netdata.service.in
system/systemd/netdata.service.v235.in

Added `network-online.target` conditions, because when expected that netdata web server will be avail on two interfaces
```ini
[web]
bind to = 127.0.0.1 192.168.250.1
allow connections from = 127.0.0.1 localhost 192.168.250.1
```
Netdata just ignore IP address that is not avail
```python
Jun 15 19:42:03 netdata.example.com netdata[496]: LISTENER: IPv4 bind() on ip '192.168.250.1' port 19999, socktype 1 failed.
Jun 15 19:42:03 netdata.example.com netdata[496]: LISTENER: Cannot bind to ip '192.168.250.1', port 19999
```
----
`nss-lookup.target` is a 'DNS' availability. For `go.d/ping` module, when `host` is a hostname
----
**Before**
```python
netdata.service +295ms
└─network.target @3.642s
└─frr.service @2.691s +950ms
└─network-pre.target @2.673s
└─iptables.service @2.535s +134ms …
```

systemd: start `netdata` after network is online

---

packaging/installer/netdata-updater.sh

Fixes: #17887
I think the issue is [_safe_download "${commit_check_url}"](https://github.com/netdata/netdata/blob/9c4aae6869c54c79a65160fa32e88240fd24cb88/packaging/installer/netdata-updater.sh#L541C20-L541C56) doesn't return any output if `curl` fails and the python script doesn't handle it. This PR fixes it. 
</details>

updater: handle json decode error in newer_commit_date()

---

src/database/contexts/api_v2.c

When disk space usage for a tier is set to unlimited, the max disk space reported in api/v2/node_instances should be space already used from the datafiles + available free space (minus 5%)

Fix disk max calculation

---

src/collectors/log2journal/log2journal-yaml.c
src/collectors/network-viewer.plugin/network-viewer.c
src/collectors/plugins.d/local_listeners.c
src/collectors/proc.plugin/sys_block_zram.c
src/database/KolmogorovSmirnovDist.c
src/database/engine/datafile.c
src/database/engine/dbengine-compression.c
src/database/engine/journalfile.c
src/database/engine/pdc.c
src/health/health_dyncfg.c

This PR is fixing [these](https://github.com/user-attachments/files/15879366/warnings.txt) warnings that appear when we are using CFLAGS:
```sh
CFLAGS="-O1 -ggdb -Wall -Wextra -fno-omit-frame-pointer -Wformat-signedness -fstack-protector-all -Wformat-truncation=2 -Wunused-result -DNETDATA_DEV_MODE=1 -DNETDATA_VERIFY_LOCKS=1"
```
1. Compile `master` branch with CFLAGS redirecting `stderr` and `stdout` to file that you can compare.
2. Compile current branch and check we do not have the same warnigs.
3. Run netdata to confirm everything is working.
</details>

Fix warnings

---

src/go/collectors/go.d.plugin/modules/systemdunits/systemdunits.go

Otherwise, "collect_unit_files" is not displayed if it is set to "false" (default).
</details>

go.d systemdunits: remove "omitempty" tag from collect_unit_files

---

CMakeLists.txt

Now
```bash
$ cat -p /usr/lib/systemd/journald@netdata.conf.d/netdata.conf/journald@netdata.conf
[Journal]
SystemMaxUse=256M
RuntimeMaxUse=64M
```
After fix
```bash
$ cat -p /usr/lib/systemd/journald@netdata.conf.d/netdata.conf
[Journal]
SystemMaxUse=256M
RuntimeMaxUse=64M
```
Tested by building & installing deb locally.
</details>

fix installing netdata journald conf for native packages

---

src/collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh

Related: https://github.com/netdata/netdata/discussions/17903
Was checking how we monitor APC UPS status and found a problem: instead of an exact match, we should do a "contains" check, since the "STATUS" line can include multiple statuses. For example:
> STATUS : ONLINE SLAVE REPLACEBATT
Tested locally by copying updated awk script and
```bash
echo "STATUS : ONLINE SLAVE REPLACEBATT" | awk ...
```
</details>

fix apcupsd status

---

src/database/engine/rrdengine.c

When disk space usage for a tier is set to unlimited (0 MB), the max disk space calculated is not correct and the space % used is incorrect.

Fix space percentage calculation in dbengine retention chart

---

src/go/collectors/go.d.plugin/agent/confgroup/config.go

Because it breaks dyncfg (dyncfg id is a ":" separated path). 
</details>

go.d replace colon in job name

---

src/go/collectors/go.d.plugin/modules/postgres/collect.go
src/go/collectors/go.d.plugin/modules/postgres/do_query_bloat.go
src/go/collectors/go.d.plugin/modules/postgres/do_query_indexes.go

Noticed these warnings in the NC k8s cluster
> `time=2024-06-20T07:51:45.370Z level=warn msg="error on adding chart  ... unacceptable symbol in ID : ' '`
</details>

go.d postgres index name replace space

---

src/collectors/cgroups.plugin/cgroup-internals.h
src/collectors/cgroups.plugin/sys_fs_cgroup.c

It is better to have it until we make our cgroup version detection reliable.
</details>

cgroups: bring back "use unified cgroups" option

---

packaging/docker/README.md
src/go/collectors/go.d.plugin/modules/smartctl/metadata.yaml

Fixes: #17977
1. Add an additional step to go.d/smartctl setup for Netdata running in a Docker container.
2. Add a note that the "With Docker socket proxy" setup hasn't been tested by the Netdata team.
</details>

docs: add "For Netdata running in a Docker container" to go.d/smartcl

---

src/libnetdata/libnetdata.c

- Change logging to "debug" when close_range() fails (fallback:  handle each fd separately)

Change logging to debug 

---

src/health/health.d/whoisquery.conf
src/health/health.d/x509check.conf

From https://github.com/netdata/netdata/discussions/17994
> I get for example expiration in 7468788 which is not very helpful, so i need to convert it into days
This PR addresses this issue. The value in days will improve the user experience.
</details>

health convert value to days in calc in whoisquery/x509check alarms

---

.github/scripts/deb-sign.sh
.github/workflows/packaging.yml
.github/workflows/repoconfig-packages.yml

This provides a stronger signature guarantee than we currently provide, and simplifies handling of multiple repository servers.
Currently, this only signs packages going to the backup repository server (repo2.netdata.cloud), allowing us to test the resultant packages more easily with minimal disruption for users.
RPM package signing will be handled in a separate PR.
This needs to be merged to be tested, as it was created from a branch from a fork, and therefore the signing keys are not accessible to the workflow run.
This signing will be, at least initially, happening in-parallel with the archive signing already being done by the repository servers themselves. Once we’ve confirmed that the origin signing from this PR is working, we will remove the archive signing, allowing us to ensure …

Sign DEB packages in the GHA runners that build them.

---

packaging/installer/kickstart.sh

Fixes
> grep: warning: stray \ before -
I get it on Fedora40.
```bash
$ sudo grep '\-\-enable-auto-updates' /usr/libexec/netdata/netdata-updater.sh
grep: warning: stray \ before -
--enable-auto-updates)
$ sudo grep '\--enable-auto-updates' /usr/libexec/netdata/netdata-updater.sh
--enable-auto-updates)
```
</details>

fix grep warning in kickstart

---

src/health/schema.d/health%3Aalert%3Aprototype.json

When creating an Alert you can:
1. use only `lookup`
2. use only `calc`
3. or both
The only way to remove the `lookup` line is to set "From" (after) to 0 (which is not intuitive). By default we set it to 0, so the user can choose 1, 2 or 3. But this is no less confusing, so we change it back.
</details>

alert prototype: set default "after" to -600

---

CMakeLists.txt
src/daemon/main.c
src/daemon/win_system-info.c
src/daemon/win_system-info.h
src/libnetdata/os/os-windows-wrappers.c
src/libnetdata/os/os-windows-wrappers.h
src/libnetdata/os/os.h

This PR enhances the Windows agent by enabling it to retrieve system information without the need for msys.
Please note that this update does not include support for containers, as further research is required to properly configure and utilize them on Microsoft platforms.
Additionally, I have not used WinSock to obtain cloud information. Incorporating WinSock would introduce an additional layer of complexity to Netdata, which we are not yet utilizing but should consider in the future.
1. Compile this branch on `msys` terminal
2. Start the agent 
3. Access http://localhost/api/v1/info
</details>

sysinfo (WinAPI)

---

src/aclk/https_client.c
src/aclk/https_client.h
src/aclk/mqtt_websockets/mqtt_wss_client.c
src/streaming/sender.c

- Fix an issue when connecting to cloud via a proxy and the response on the proxy connect command is `HTTP/1.0 200 Connection Established`
- Run claimed agent without proxy. It should connect to the cloud
- Stop agent (configure proxy) in `[cloud]` add a `proxy = http://proxy_host:port` option 
- Restart. It should connect to the cloud

Fix proxy connect response

---

src/daemon/global_statistics.c

- Make the global stats thread more responsive to agent shutdown if the update every of the agent (or the global statistics thread is large)
- Start agent with large update every (or set a section `[global statistics]` with `update every = 10`)
Notice during shutdown the agent is awaiting for `STATS_GLOBAL` to terminate
- Apply PR and retest.

Improve global statistics thread shutdown

---

CMakeLists.txt
src/collectors/common-contexts/common-contexts.h
src/collectors/common-contexts/system.interrupts.h
src/collectors/freebsd.plugin/freebsd_sysctl.c
src/collectors/proc.plugin/proc_stat.c
src/collectors/windows.plugin/perflib-processor.c

Add interrupt chart to Microsoft.
1. Compile this branch on Windows and take a look on charts.
2. Compile on Linux and verify it is still working.
This PR was tested on Slackware current and Microsoft Windows 11 Home
</details>

add Win CPU interrupts

---

packaging/utils/coverity-scan.sh

- Bail early in the script if the system isn’t 64-bit x86 Linux, since it doesn’t actually work elsewhere.
- If a specific version of the Coverity tools was not specified, use whatever version we end up with instead of failing. This means that the CI will _just work_ instead of needing to be updated every few months because the Coverity team does not understand the concept of providing properly versioned download links.
Needs to be merged to be tested properly, since the Coverity jobs don’t run correctly on PRs.

Fix Coverity scan CI.

---

CMakeLists.txt
netdata.spec.in

Build and install the package, check `ls -l /lib/systemd/system | grep -Eo "netdata-updater.(service|timer)"`
I didn't build and install the rpm packages, but I did check the ci packages/build of Centos7 and Fedora40. Everything seems to be fine.
</details>

fix installing netdata-updater svc/timer for native packages

---

src/collectors/plugins.d/ndsudo.c

- Currently, `chronyc serverstats` is restricted to connections via the Unix domain socket.
- To add this functionality to netdata, it would require adding the user to the "_chrony" group. However, attempts to establish a Unix socket connection weren't successful (I tried [chrony_exporter](https://github.com/SuperQ/chrony_exporter) - same problem, no response from chronyd). Additional chronyd configuration might be needed.
Solution: We'll grant netdata user access to chronyd serverstats through the `ndsudo` tool. Thus, it will work out of the box without any additional configuration.
Related PR #18055.
</details>

ndsudo add 'chronyc serverstats'

---

src/collectors/freeipmi.plugin/freeipmi_plugin.c

This PR adds "no-restart" command line option:
- It disables periodic plugin restarts.
- Added as a workaround for #17931 and will be removed once the issue is fixed.
</details>

freeipmi: add "no-restart" (workaround #17931)

---

src/exporting/prometheus/prometheus.c

Fixes: #18059
The bug was added in #17191
</details>

fix prometeus export: missing comma before "instance" label

---

src/collectors/python.d.plugin/puppet/puppet.chart.py

Simple fix that removes the hard-coded chart `url` setting/pinning from the python.d puppet plugin.
While this is not a _direct_ problem when monitoring the puppetserver in its default configuration as it usually runs bound to the FQDN address and on port 8140 this has at least two issues:
a) It prevents you from monitoring puppetserver on non-standard ports
b) It does not work with monitoring puppetdb as this one by default runs on port 8081 [*]
Without this fix any given config `url` chart parameter is overwritten by the url's fqdn, pinning the request to port 8140 without any way to disable this behaviour.
[*] See accompanying [example config](https://github.com/Hufschmidt/netdata/blob/master/src/collectors/python.d.plugin/puppet/puppet.conf) for this fact.
Running puppetserver and …

Remove hard-coded url from python.d puppet chart plugin

---

netdata.spec.in

Without this dependency, the go.d/sensors module is not work on RPM-based distros, see #18065

netdata.spec/plugin-go: added weak dependency for lm_sensors

---

packaging/cmake/Modules/Packaging.cmake

Outside of a few cases involving eBPF, we don’t actually need to have an exact match between individual package component versions.
Removing this constraint significantly simplifies our dependency graph, and should both speed up updates, and also make them much more reliable.
This will also simplify consolidation of dependency handling across package types, because our package names are identical between DEB and RPM packages.
Requires manually checking that the package dependencies are updated correctly.

Relax strict version constraints for DEB package dependencies.

---

.github/data/distros.yml
packaging/PLATFORM_SUPPORT.md

It went EOL upstream on 2024-06-30.
n/a

Remove Debian 10 from supported platforms.

---

.github/data/distros.yml
packaging/PLATFORM_SUPPORT.md

It went EOL upstream on 2024-07-01.
n/a

Remove Ubuntu 23.10 from supported platforms.

---

.github/data/distros.yml

This is required to ensure correct CI for existing releases where we support this platform.
CI jobs for CentOS 7 pass on this PR.
@netdata/agent Once merged this needs to be included in the v1.46.2 patch release, but can be skipped in the release notes.

Switch to legacy images for CentOS 7 CI.

---

.github/data/distros.yml
.github/scripts/gen-matrix-eol-check.py
.github/scripts/platform-impending-eol.py
.github/workflows/platform-eol-check.yml

Unlike most other platforms we support, it’s trivial for us to support Debian’s LTS distros, and we’ve effectively been doing that for quite some time now, so just make it official in the CI jobs.
n/a

Track LTS for Debian EOL status.

---

CMakeLists.txt
src/collectors/common-contexts/common-contexts.h
src/collectors/common-contexts/system.ipc.h
src/collectors/freebsd.plugin/freebsd_sysctl.c
src/collectors/proc.plugin/ipc.c
src/collectors/windows.plugin/perflib-objects.c
src/collectors/windows.plugin/windows_plugin.c
src/collectors/windows.plugin/windows_plugin.h

This PR is adding one more metric to windows dashboard. It also creates the basis to bring more metrics from `Objects` object.
Ideally this PR should be tested on FreeBSD, Windows and Linux.
2. Take a look on dashboard and verify if metric is present.
| Operate System | Version/Distribution | 
|-------------------------|-------------------------------|
|Linux                      | Slackware current | 
|FreeBSD                 |  14 | 
| Windows               | 11 Home|
|Linux                       | Arch |
</details>

Semaphore (common context)

---

src/collectors/plugins.d/ndsudo.c

#18089 reports that running `megacli` via `ndsudo` does not produce results due to insufficient permissions.
The effective user ID is 0 when executing but the real is not. Some programs check for both uid/euid ([example](https://github.com/lvmteam/lvm2/blob/f8aa073a8d1028173441771c687b458752b453dc/tools/lvmcmdline.c#L3540C6-L3541)). I assume that is the case for `megacli` (not open-source, can't check).
Fixes: #18089
Thanks to @ClaraCrazy for testing the fix.
</details>

ndsudo set uid/gid/egid to 0 before executing command

---

src/collectors/windows.plugin/perflib-network.c

- Read counter to properly set `sent` dimension for traffic and packets (Aggregated Bandwidth)

Fix network sent dimensions

---

src/collectors/network-viewer.plugin/network-viewer.c
src/collectors/plugins.d/local_listeners.c
src/libnetdata/libnetdata.c
src/libnetdata/maps/local-sockets.h
src/libnetdata/spawn_server/spawn_popen.c
src/libnetdata/spawn_server/spawn_server.c
src/libnetdata/spawn_server/spawn_server.h

The spawn server creates a socket file in the filesystem.
To protect from unauthorized access, there is now a token that only the valid clients and the spawn server know. Failure to put the right token in the request, leads to denied requests.
Each spawn server can now be configured to accept callback or exec requests, or both. Sending the wrong type of request will lead to denied requests.
A socket was leaked at the spawn server, in case of errors. Fixed it.

add authorization to spawn requests

---

packaging/utils/coverity-scan.sh

This correctly fixes the coverity-scan script to not care about the specific version it’s been asked to install.
n/a

Fix detection of Coverity archive in scan script.

---

src/claim/claim.c
src/daemon/main.c

Wrong parameters were passed to claiming scripts.
Make the UI work on netdata restart.

make claiming work again

---

src/libnetdata/spawn_server/spawn_server.c
src/libnetdata/spawn_server/spawn_server.h

spawn server fixes 3

---

src/go/plugin/go.d/modules/smartctl/charts.go
src/go/plugin/go.d/modules/smartctl/collect.go
src/go/plugin/go.d/modules/smartctl/metadata.yaml
src/go/plugin/go.d/modules/smartctl/smartctl_test.go
src/go/plugin/go.d/modules/smartctl/testdata/type-scsi/device-sda.json
src/go/plugin/go.d/modules/smartctl/testdata/type-scsi/scan.json

The issue was reported on the [Community Forum](https://community.netdata.cloud/t/monitor-drive-error-rates-now-that-smartd-log-has-been-removed). python.d/smartd_log collected these metrics.
</details>

go.d smartctl: add scsi read/write/verify error rate

---

src/daemon/commands.c
src/libnetdata/log/log.c
src/libnetdata/log/log.h
src/libnetdata/spawn_server/spawn_server.c

Corrupted data are found in the spawn server socket, because of the logging system.
The spawn server and its children uses the same logging system as netdata. So, the logs files and sockets need to be reopened when the spawn server starts.
Without this, an fd of the parent that is now closed, may use the same fd number of a random socket, which leads to corrupted data in the socket.

Spawn server fixes 6

---

src/go/plugin/go.d/modules/smartctl/exec.go
src/go/plugin/go.d/modules/smartctl/scan.go
src/go/plugin/go.d/modules/smartctl/smartctl.go
src/go/plugin/go.d/modules/smartctl/smartctl_test.go

[Issue on Discord](https://discord.com/channels/847502280503590932/1261747175361347644/1261747175361347644)
"sat" devices are identified as "scsi" with `--scan`, and then later code attempts to validate the type by calling `smartctl` with the "scsi" type. This validation can trigger unintended "Enabling discard_zeroes_data" messages in system logs (dmesg). To address this specific issue we use `--scan-open` as a workaround. This method reliably identifies device types.
The "Enabling discard_zeroes_data" message might be harmless. More investigation is needed.
</details>

go.d smartctl: use scan-open when "no_check_power_mode" is "never"

---

packaging/utils/coverity-scan.sh

Also, perform a bunch of cleanup in the install function, since a lot of the code there is unnecessarily complicated.
Requires manual testing with the script handling installation of Coverity tooling.

Fix detection of Coverity archive path in scan script.

---

netdata-installer.sh
packaging/build-package.sh

Ninja has a tendency to continue on after a failed build command in some cases, making it difficult to see where a build error actually happened.
This PR does two things to mitigate this issue:
- It disables verbose mode for Ninja by default. This makes the output significantly more terse, especially for interactive runs attached to a terminal (where Ninja will _rewrite_ the line indicating the job that just finished instead of appending it to the terminal like is done in verbose mode). This, in turn, should make it much easier to find the error messages. When the actual command is needed, it can be looked up relatively easily in the Ninja build file itself (by simply searching for the file name of the file that had the error).
- It tells Ninja to not create any new jobs after the first …

Stop a bit more quickly on a failure when using Ninja.

---

.github/scripts/prepare-release-base.sh

This is needed to support making patch releases for `X.0` releases.
n/a

Create release branches for major releases as well.

---

src/database/contexts/context.c
src/database/contexts/worker.c

On a just installed netdata, some contexts were not available on the dashboard until netdata was restarted, or deepscan was requested on the contexts API.
The problem was an optimization that prevent re-queuing of contexts, that was relaying on a flag that was managed by dictionary destructors. However the dictionaries support late destruction and the flag was not unset, even though the item was marked as deleted in the dictionary.
The new logic removes this optimization and now relies on dictionary conflict constructor to do the right job.

do not rely on the queued flag to queue a context

---

packaging/windows/installer.nsi
src/daemon/win_system-info.c

This PR is bringing two changes for netdata:
- Modify default installation path as required in https://github.com/netdata/netdata/issues/18213.
- Update `os_id` to match `winver.exe` output.
1. Compile on Windows and generate the installer.
2. Take a look in default path shown.
3. When installation ends, access `/api/v1/info` and check your `os_id`.
</details>

Improve windows agent

---

packaging/windows/compile-on-windows.sh
packaging/windows/msys2-dependencies.sh
packaging/windows/package-windows.sh

Instead of hard depending on Ninja for the Windows build, use it if available but still allow usage of Make if not. Also, skip installing Ninja by default as a dependency. This works around an issue with either MSYS2 or CMake as provided by MSYS2 in the GitHub Actions runners that is causing the build to fail during configuration.
While it’s theoretically preferable that we use Ninja for build performance, the CI process for Windows is already horribly dominated by the dependency handling step due to inefficiencies in pacman, so the overall relatively small difference in build time should be a non-issue.
Windows CI passes on this PR.

Windows build fix

---

packaging/cmake/Modules/NetdataEBPFCORE.cmake
packaging/cmake/Modules/NetdataEBPFLegacy.cmake
packaging/cmake/Modules/NetdataLibBPF.cmake

This pull request updates Netdata with the latest version of libbpf. While we have changed the way we work with the CentOS 7.x family, this pull request does not affect them, as we use a different libbpf version for CentOS 7.x.
1. Compile this branch and there is not error during compilation time.
2. Check `eBPF.plugin` is running.
</details>

Update libbpf (1.45.0)

---

.github/workflows/build.yml
CMakeLists.txt
packaging/cmake/Modules/FindGo.cmake
packaging/windows/compile-on-windows.sh

This gets rid of `-DDEFAULT_FEATURE_STATE` in our Windows build CMake options (this option was _NEVER_ intended to be used for anything but testing), enables the Go plugin, and hard-disables the known non-working Apps plugin on Windows.
Relevant to: #18213

Fix up CMake feature handling for Windows.

---

src/aclk/helpers/mqtt_wss_pal.h
src/aclk/https_client.c
src/aclk/mqtt_websockets/mqtt_ng.c
src/aclk/mqtt_websockets/mqtt_wss_client.c
src/aclk/mqtt_websockets/mqtt_wss_log.c
src/aclk/mqtt_websockets/ws_client.c

- Replace the mqtt ipv4-only connect function with connect_to_this_ip46 
- Replace mw_malloc, mw_calloc, mw_free, mw_strdup, mw_realloc
- Remove ws_client_get_nonce, (generate and use a UUID instead)
- Replace statistics pthread_lock with spinlock
- Start agent normally, it should connect to the cloud
- Test IPV6 connectivity (we have it enabled only in the **testing** environment)
- Check with direct connection
- Check via a proxy (add `proxy = http://host:port` in netdata.conf `[cloud]` section)
- Ideally check with a proxy on a VM that supports IPV6 and one that doesn't
- You can force IPV4 connection on an otherwise IPV6 capable system by editing /etc/gai.conf -- adjust 
`precedence ::ffff:0:0/96`

Support IPV6 when establishing MQTT connection to the cloud

---

packaging/installer/dependencies/alpine.sh
packaging/installer/dependencies/arch.sh
packaging/installer/dependencies/centos.sh
packaging/installer/dependencies/debian.sh
packaging/installer/dependencies/fedora.sh
packaging/installer/dependencies/freebsd.sh
packaging/installer/dependencies/gentoo.sh
packaging/installer/dependencies/ol.sh
packaging/installer/dependencies/opensuse.sh
packaging/installer/dependencies/rockylinux.sh
packaging/installer/dependencies/ubuntu.sh
packaging/installer/install-required-packages.sh

This removes the following dependencies from our dependency handling scripts, as they are no longer needed:
- automake
- autoconf
- autoconf-archive
- autogen
- bison
- flex
- libtool
It also ensures proper sorting of dependencies in most of the scripts, drops a few platform-specific dependencies we don’t really need anymore, and updates the Gentoo dependencies for gzip/tar to use the newer `app-alternatives` packages for those commands (thus ensuring consistency with best-current-practices for packaging on Gentoo).

Clean up unneeded depencdencies.

---

packaging/windows/installer.nsi

This PR addresses the bullet number `2.` in https://github.com/netdata/netdata/issues/18213 .
This will avoid some errors during installation.
It also improves the installation hidden the prompt used to manage the services.
1. Compile this branch on Windows
2. Run installer. Check if netdata dashboard is opening.
3. Use the installer again.
@Ferroin when I compiled this branch on Windows, I had to disable GO before.
</details>

Update Installer Code (Services)

---

src/go/plugin/go.d/agent/module/charts.go
src/go/plugin/go.d/agent/module/charts_test.go

Dimension Id is not exposed to Netdata if Name is set.
</details>

go.d fix dimension id check

---

packaging/cmake/Modules/NetdataGoTools.cmake

Fixes: #18273
It is `direct` on Fedora40 and [this causes checksum error => fail building Netdata](https://discord.com/channels/847502280503590932/1270534296330829824/1270534296330829824).
</details>

set GOPROXY when building go.d.plugin

---

packaging/installer/kickstart.sh

This adds info to the failure messages in the kickstart script to report the expected and actual checksum when a file fails validation. This allows us to verify if the issue is more likely to be a problem of at-rest data corruption, or something with the data transport mangling the data.
n/a

Add detailed reporting of failed checksums in kickstart script.

---

src/database/sqlite/sqlite_metadata.c

- Add trigger to delete charts and chart labels when all dimensions of a chart are deleted. (eg during rotation). This is more  efficient than waiting for the periodic cleanup job of the chart and chart label tables to do the work.
- Note: In a future PR the chart label table will be restructured to use less storage

Add trigger to clean up chart labels and charts

---

src/health/notifications/alarm-notify.sh.in

The issue is [reported on Discord](https://discord.com/channels/847502280503590932/1273564499374247968/1273564499374247968).
</details>

fix sending CLEAR notifications with critical severity modifier

---

docs/deployment-guides/deployment-strategies.md
docs/metric-correlations.md

Some links, particularly in the deployment guides, were broken due to a missing initial slash in the link target.
Verify that the newly generated docs have the affected links work properly, as well as in the GitHub repo browser.

Add missing initial slashes for internal documation links

---

src/collectors/ebpf.plugin/ebpf.c
src/collectors/ebpf.plugin/ebpf_apps.c
src/collectors/ebpf.plugin/ebpf_apps.h
src/collectors/ebpf.plugin/ebpf_cachestat.c
src/collectors/ebpf.plugin/ebpf_dcstat.c
src/collectors/ebpf.plugin/ebpf_fd.c
src/collectors/ebpf.plugin/ebpf_process.c
src/collectors/ebpf.plugin/ebpf_shm.c
src/collectors/ebpf.plugin/ebpf_socket.c
src/collectors/ebpf.plugin/ebpf_swap.c
src/collectors/ebpf.plugin/ebpf_vfs.c

In this PR, we are enhancing the plugin by adjusting the algorithm to discard and clean up data in the user and kernel ring when the PID is no longer active.
1. Compile this branch and enable at least one thread monitoring PIDs,  for example, `fd`.
2. Start netdata and check number of PIDs stored:
```sh
bpftool map dump name tbl_fd_pid| grep key| wc -l
```
Instead to have data increasing in your hash table, it should be more or less stable.
3. Repeat steps with current master.
</details>

eBPF (reduce CPU and memory usage)

---

src/go/plugin/go.d/modules/dnsmasq/collect.go

v2.90+ returns SERVFAIL if there is more than one question in the message.
Fixes: #18375
</details>

go.d dnsmasq: query metrics individually to handle v2.90+ SERVFAIL

---

src/daemon/commands.c

- When running `netdatacli remove-stale-node`, delete the host immediately

Remove host immediately on stale node removal

---

packaging/repoconfig/CMakeLists.txt
packaging/repoconfig/deb.changelog
packaging/repoconfig/netdata.list.in
packaging/repoconfig/netdata.sources.in
packaging/repoconfig/rpm.changelog

Most third-party repositories have long-since made the equivalent switch, and Ubuntu is apparently forcibly converting existing configuration when upgrading to 24.04 even if the configuration is owned by a package on the system.
This change also is required for us to eventually provide redundancy in our repository hosting, and will indirectly simplify a handful of other possible improvements.
Requires manual testing of the generated DEB repository configuration packages.
To build locally, run `docker run -it -v $PWD:/netdata <distroimage> /netdata/packaging/repoconfig/build-deb.sh` from the root of the git repository, replacing `<distroimage>` with the official Docker image for the target distribution (for example, `debian:12` for Debian 12). The packages will be put in …

Switch to DEB822 format for APT repository configuration.

---

packaging/installer/installer.nsi
packaging/installer/package-windows.sh
packaging/windows/fetch-msys2-installer.py
packaging/windows/installer.nsi
packaging/windows/package-windows.sh

l##### Summary
This PR is addressing https://github.com/netdata/netdata/issues/18213 some of remaining requirements for our installer. The unique missing action is the creation of a software to claim the agent instead to use our script. 
The following new features were added:
- Now installer have licenses (Cloud and GPL/3)
- Fields to add token and room (they are not used yet)
- Possibility to open a terminal
- Msys files were added to final installation without necessity to run another installer
1. Remove any previous installation in your `C:\msys64\opt\netdata`
2. Compile on windows using our script: `packaging/windows/compile-on-windows.sh`
3. Create the package: `packaging/windows/package-windows.sh`
4. Install the binary …

Update windows installer

---

src/daemon/commands.c

The `remove-stale-node` is now accepting a node name as a parameter to remove a stale node.  If ALL is specified then all nodes are checked and removed.

Modify CLI command remove-stale-node to accept hostname

---

packaging/docker/Dockerfile

Current Dockerfile emits warnings, this patch fixes them.
The warnings are visible on the Docker action:
Fixed with:
* use correct casing for "as" keyword
* remove legacy key/value format with whitespace separator for ENV
Running a Docker build action should show no more warnings.
Nobody likes warnings. This change has no impact on the behavior of the code, or on users.

fix warnings in Dockerfile

---

packaging/installer/kickstart.sh

[Reported on Discord](https://discord.com/channels/847502280503590932/1277069220575838229)
Fixes
> ./kickstart.sh: 1278: cannot create /opt/netdata/etc/netdata/claim.conf.tmp: Permission denied
WARNING  Failed to write claiming configuration. This usually means you do not have permissions to access the configuration directory.
This line is a problem
https://github.com/netdata/netdata/blob/c4ad1e0174776ee128cfcde957b71db582854437/packaging/installer/kickstart.sh#L1278
When you run a command with sudo, it runs with elevated privileges. However, the shell handles the redirection, which is still running with your regular user's privileges.
</details>

kickstart: fix write_claim_config when executed as a regular user

---

src/database/sqlite/sqlite_aclk.c

Removing a stale node that actually connected recently (e.g less than 24 hours ago -- 86400 seconds) removes it from memory but when the agent restarts it may re-register the node. It will then take the default of 24 hours to auto remove it. 
This PR will reset the last connected time of a node to prevent this from happening.
Fixes #18423

Reset last connected when removing stale nodes with netdatacli

---

src/go/plugin/go.d/modules/sensors/lmsensors/scanner.go
src/go/plugin/go.d/modules/sensors/lmsensors/scanner_test.go

go.d lmsensors improve performance

---

src/database/engine/datafile.c
src/database/engine/datafile.h
src/database/engine/rrdengine.c

During shutdown all datafiles are acquired for deletion before the necessary cleanup can be performed. This can (at times) delay the agent shutdown -- logs you may notice include
```
Waiting to acquire data file X of tier Y to close it...
```
This PR reduces the timeout and the number of attempts to acquire the datafile during shutdown

Improve agent shutdown time

---

src/database/engine/datafile.c

- Fix CID 443160:  Incorrect expression  (PRECEDENCE_ERROR)

Proper precedence when calculating time_to_evict

---

src/collectors/slabinfo.plugin/slabinfo.c

At the moment slabinfo.plugin does not exit when netdata is killed, this PR fixes the issue in exactly the same way it's handled in debugfs.plugin (https://github.com/netdata/netdata/pull/16569) and cups.plugin (https://github.com/netdata/netdata/pull/16691).
The issue may be reproduced the same way as in https://github.com/netdata/netdata/pull/16569:
* running netdata manually
* killing netdata (or spawn server and netdata if spawn server is present in used version) with SIGKILL
E.g.
```
$ docker run --rm -t -i --entrypoint bash netdata/netdata:stable
root@bc58059db6cc:/# cat >> /etc/netdata/netdata.conf << EOF
[plugins]
slabinfo = yes
EOF
root@bc58059db6cc:/# netdata >/dev/null 2>&1 & disown
[1] 8
root@bc58059db6cc:/# ps auxf
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START …
```

Exit slabinfo.plugin on EPIPE

---

src/health/notifications/alarm-notify.sh.in
src/health/notifications/health_alarm_notify.conf
src/health/notifications/ilert/metadata.yaml

This PR brings the integration between Netdata and ilert.
1. Create a Netdata alert source in ilert [documentation link](https://docs.ilert.com/inbound-integrations/netdata)
2. Following variables have to be set in health_alarm_notify.conf config file:
```
SEND_ILERT="YES"
ILERT_ALERT_SOURCE_URL="<alert source url of your netdata alert source in ilert>"
```

ilert Integration

---

.gitignore
CMakeLists.txt
packaging/windows/resources/netdata.manifest.in
packaging/windows/resources/netdata.rc
packaging/windows/resources/netdata_claim.manifest.in
packaging/windows/resources/netdatacli.manifest.in
packaging/windows/resources/netdatacli.rc

This PR adds the missing `manifests` and `resources` for our binaries and automates the versioning process for generating them. 
A subsequent PR will further clean up the code and implement the naming pattern requested by @ilyam8 .
2. Make an installer
3. Update your system and verify that Netdata is running on Microsoft Windows. In addition, go to your `NETDATA_INSTALL_PATH\usr\bin` and confirm all binaries have Netdata icon:
</details>

Windows Permissions

---

src/database/contexts/api_v2_contexts_alerts.c

- Init dictionaries with correct callback data structure
- Start agent and run `api/v2/alerts?options=values&status=clear&timeout=3000`
- Run another command `/api/v1/info`
- Run `api/v2/alerts?options=values&status=clear&timeout=3000` again
You might notice random values in `ni` eg
```
[{
"ni":367642961072,
"nm":"10min_cpu_usage",
"ch":"system.cpu",
"ch_n":"system.cpu",
"v":58.7957998,
"t":1725389442
},{
"ni":367642961072,
"nm":"10min_cpu_iowait",
"ch":"system.cpu",
"ch_n":"system.cpu",
"v":0.1835171,
"t":1725389442
},{
```

Fix node index in alerts

---

src/database/sqlite/sqlite_aclk_alert.c

There is a bug when processing pending alerts. The code would group and delete processed alerts within a range but this could cause alerts within that range that have been scheduled at a later time, to be lost. Those lost transitions can cause alert state inconsistencies. 
This PR fixes this issue

Improve processing of pending alerts

---

src/libnetdata/gorilla/gorilla.cc

The previous check was wrong and it could trigger an out-of-bounds access to the underlying buffer.
Triggering this issue was possible when feeding the entire gorilla page with incompressible data. In that case, data loss of one collection point was the primary impact.
Modify `src/libnetdata/gorilla/fuzzer.sh` to build with both the fuzzer and the address sanitizers (`-fsanitize=address,fuzzer`). Without this patch, it was easy to trigger a crash in seconds.

Check correct number of bits for LZC of XOR value.

---

src/collectors/ebpf.plugin/ebpf.c
src/collectors/ebpf.plugin/ebpf_apps.c
src/collectors/ebpf.plugin/ebpf_apps.h
src/collectors/ebpf.plugin/ebpf_cachestat.c
src/collectors/ebpf.plugin/ebpf_dcstat.c
src/collectors/ebpf.plugin/ebpf_fd.c
src/collectors/ebpf.plugin/ebpf_shm.c
src/collectors/ebpf.plugin/ebpf_swap.c

This PR removes warnings when eBPF plugin is compiled.
1. Compile this Branch with the following CFLAGS and verify there is no warnings in plugin files:
```sh
CFLAGS="-O1 -ggdb -Wall -Wextra -fno-omit-frame-pointer -Wformat-signedness -fstack-protector-all -Wformat-truncation=2 -Wunused-result
```
</details>

Remove Warnings (ebpf)

---

src/database/sqlite/sqlite_health.c

There is a bug when scheduling removed (deleted) alerts after an agent restart. If an alert has been in WARNING or CRITICAL it is not removed and appears stale.
This PR fixes this issue

Improve processing on removed alerts after agent restart

---

src/go/plugin/go.d/config/go.d/sd/docker.conf
src/go/plugin/go.d/modules/varnish/config_schema.json
src/go/plugin/go.d/modules/varnish/exec.go
src/go/plugin/go.d/modules/varnish/init.go
src/go/plugin/go.d/modules/varnish/metadata.yaml
src/go/plugin/go.d/modules/varnish/testdata/config.json
src/go/plugin/go.d/modules/varnish/testdata/config.yaml
src/go/plugin/go.d/modules/varnish/varnish.go
src/go/plugin/go.d/pkg/dockerhost/dockerhost.go

- go.d/varnish: add support for executing `varnishstat` inside a Docker container (`docker_container` option).
- sd: discover Varnish containers and create data collection jobs using the new option.
</details>

go.d/varnish: add docker support

---

src/daemon/commands.c

There is no such command.
</details>

remove save-database from netdatacli usage

---

src/collectors/windows-events.plugin/windows-events-query.c

Unfortunately the used size returned by EvtFormatMessage() may be more than the actual string length + null.
So, we need to recalculate it, every time.

Windows Events: recalculate the length of unicode strings returned every time

---

CHANGELOG.md
CMakeLists.txt
src/collectors/all.h
src/collectors/windows.plugin/perflib-memory.c
src/collectors/windows.plugin/perflib-thermalzone.c
src/collectors/windows.plugin/windows_plugin.c
src/collectors/windows.plugin/windows_plugin.h

This PR enhances the `windows.plugin` by adding support for the following metrics:
- Thermal Zone
- SWAP
- System POOL
These metrics were previously collected through the Windows Exporter, and this PR marks the first phase of migrating them.
This PR addresses two areas outlined in https://github.com/netdata/netdata/issues/18461. It introduces Memory Metrics and begins the migration of Windows Exporter metrics, which will be delivered via the `go.d.plugin`.
1. Compile on Windows.
2. Build the package.
3. Install and review the charts to ensure proper display of the metrics.
</details>

Windows Plugin Metrics (Thermal and Memory)

---

src/collectors/apps.plugin/apps_groups.conf

Add [Typesense](https://github.com/typesense/typesense) search engine to apps_groups.conf.
I think this more than covers [metrics.json](https://typesense.org/docs/27.0/api/cluster-operations.html#cluster-metrics) data.
Related #15844
</details>

add typesense to apps_groups.conf

---

packaging/repoconfig/CMakeLists.txt
packaging/repoconfig/deb.changelog
packaging/repoconfig/netdata.sources.in
packaging/repoconfig/rpm.changelog

This enables atomic updates to the repository metadata on the server side, which should mitigate some of the issues we’ve seen with bad hashes for packages.
It’s unlikely this will be a complete fix for issues like #18510, but combined with some other changes in how the repo metadata is being generated on the servers it should significantly reduce the prevalance of such issues.
Requires generating local copies of the repoconfig packages for testing.
To build locally, run the `packaging/repoconfig/build-*.sh` script for the package type in a Docker image for the target platform. For example, for Debian 12 run `docker run -it --rm -v $PWD:/netdata debian:12 /netdata/packaging/repoconfig/build-deb.sh` from the root of the repository.
Verifying the changes just requires confirming that …

Fetch metadata by hash for DEB repos.

---

src/web/api/queries/weights.c

In weights, we currently send back the machine_guid, which breaks compatibility with data queries.
With this PR, we send node id when it is available, otherwise the host id (machine_guid), as data queries do.

WEIGHTS: use node_id when available, otherwise host_id

---

src/aclk/aclk.c
src/aclk/aclk_otp.c
src/aclk/aclk_otp.h
src/aclk/https_client.c
src/aclk/https_client.h
src/aclk/mqtt_websockets/mqtt_wss_client.c
src/aclk/mqtt_websockets/mqtt_wss_client.h
src/libnetdata/socket/socket.c
src/libnetdata/socket/socket.h

When establishing an ACLK connection:
- Reduce initial connection timeout to 10 seconds (down from 30)
- Fallback to IPV4 connection if we get IPV6 connection timeout
- On successful connection the fallback flag is reset so that connecting with IPV6 will be retried if the connection needs to be reestablished

Reduce connection timeout and fallback to IPV4 for ACLK connections

---

CMakeLists.txt

After @stelfrag reports issues on his new environment, we are bringing back some DLLs installation inside our `CMakeLists.txt`.
1. Uninstall netdata on Windows and remove possible remaining files in installation directory.
3. Make the installer
4. Install netdata on your host. You should not have issues to start service.
</details>

Add DLLs to CmakeLists.txt

---

src/database/engine/rrdengine.h

- Changes the default number of pages that can be added to an extent from 64 to 109
- This can improve
- Data compression when storing metrics to datafile
- Reduce journal file v1 fragmentation.
- Improve I/O under certain workloads as an extent will transfer ~70% more pages
**Note**: Agents up to version v1.45.0-113-nightly will not be able to read newly created datafiles. 
If that is needed you need to overwrite the new default by adding 
```
[db]
dbengine pages per extent = 64
```
so that the agent will keep using up to 64 pages per extent

Change default pages per extent

---

src/daemon/main.c
src/database/sqlite/sqlite_metadata.c
src/database/sqlite/sqlite_metadata.h
src/streaming/stream_path.c
src/streaming/stream_path.h

- Store in the database agent startup and shutdown times. 
- Add the median start_time / shutdown_time in ms in the stream path payload
The median startup time of the last 30 days is reported when the agent starts.
Example
```
NETDATA STARTUP: completed in 1239 ms. Enjoy real-time performance monitoring!
```
after
```
NETDATA STARTUP: completed in 1308 ms (median start up time is 1303 ms). Enjoy real-time performance monitoring!
```
This information will be used in a future PR to estimate agent restart times (e.g. when a child disconnects for a version update)

Log  agent start / stop timing events

---

docs/deployment-guides/deployment-strategies.md
docs/developer-and-contributor-corner/raspberry-pi-anomaly-detection.md
docs/netdata-agent/configuration/README.md
src/collectors/charts.d.plugin/README.md
src/collectors/ebpf.plugin/README.md
src/collectors/profile.plugin/README.md
src/collectors/statsd.plugin/README.md
src/health/notifications/README.md
src/ml/ml-configuration.md
src/registry/README.md

We should more explicitly mention the use of edit-config for **all** configuration changes, so we can link from anywhere to this.

New wording about edit-config script in docs

---

src/collectors/apps.plugin/apps_os_windows.c

In older versions of windows, the uptime reported may be invalid for some process. This PR zeros the uptime calcuation for these processes.

Fix win apps uptime

---

packaging/PLATFORM_SUPPORT.md
packaging/VERSIONING_AND_PUBLIC_API.md
packaging/building-native-packages-locally.md
packaging/docker/README.md
packaging/installer/UNINSTALL.md
packaging/installer/UPDATE.md
packaging/installer/methods/ansible.md
packaging/installer/methods/aws.md
packaging/installer/methods/azure.md
packaging/installer/methods/freebsd.md
packaging/installer/methods/gcp.md
packaging/installer/methods/kickstart.md
packaging/installer/methods/kubernetes.md
packaging/installer/methods/macos.md
packaging/installer/methods/manual.md
packaging/installer/methods/methods.md
packaging/installer/methods/offline.md
packaging/installer/methods/packages.md
packaging/installer/methods/pfsense.md
packaging/installer/methods/source.md
packaging/installer/methods/synology.md
packaging/maintainers/README.md
packaging/windows/WINDOWS_INSTALLER.md

Let there be ~rock~ docs!
related to #18553 
I passed and checked the errors, warnings and info "Problems" on VScode, and fixed mistakes in links, typos and formatted all `.md` files. 
I will do some follow-up PRs once I am done to enforce some uppercase in-house words and also check block quote formatting, as right now there is not a default way of doing it across our docs.

Docs lint on `packaging/` dir

---

packaging/windows/resources/netdata.manifest.in
src/daemon/buildinfo.c
src/daemon/win_system-info.c

This PR address the following issues in https://github.com/netdata/netdata/issues/18624:
1. Compile this PR on windows
2. Create an installer
3. After installation, check `api/v1/info`.
</details>

Adjust content api/v1/info (Windows)

---

src/streaming/stream_path.c

- Stream path processing was missing the parsing of the new fields on the remote side (parent or child) 
This PR fixes this
- Setup parent/child  with current master
- Execute /api/v3/nodes on parent
- You will notice that start_time, shutdown_time report 0 for the child
- Install PR and do the test again

Properly set start/shutdown times to parent/child

---

.github/workflows/build.yml
packaging/windows/installer.nsi
packaging/windows/package-windows.sh

This ensures forward-portability, because I can all but guarantee that we _will_ eventually want to publish 64-bit ARM binaries for Windows, and we will then need to differentiate between the installer files.
Confirm that building the installer for Windows produces a file named `netdata-installer-x64.exe` instead of the older `netdata-installer.exe`.

Embed CPU architecture info in Windows installer filename.

---

src/collectors/cgroups.plugin/cgroup-name.sh.in
src/libnetdata/line_splitter/line_splitter.h
src/libnetdata/sanitizers/chart_id_and_name.c
src/libnetdata/sanitizers/chart_id_and_name.h

fix sanitization issues

---

src/aclk/aclk.c

When an ACLK connection timeout is detected, make sure to resend a node update information to revive
the node on the cloud when the connection is re-established

Send node info update after ACLK connection timeout

---

src/collectors/cgroups.plugin/cgroup-name.sh.in

When building container images "manually" (i.e., not with "docker build"), it is possible to create them with no environment variables specified. When containers are run with these images, they will have a non-existent `.Config.Env`.
This causes no problems for `docker_like_get_name_command()`, however, `docker_like_get_name_api()` will fail with:
> jq: error (at <stdin>:1): Cannot iterate over null (null)
When running netdata inside docker (or on a host that doesn't have docker/podman binaries available), the end result is that it is not able to resolve the cgroup IDs of those containers to their friendly display names.
Confirmed that cgroup names are able to resolve correctly for all containers. Both "normal" docker-built ones and "funny" manual ones with empty `.Config.Env`).
Example …

fix(cgroups.plugin): handle containers no env vars

---

src/collectors/cgroups.plugin/cgroup-network.c

Fixes a permission issue with the `cgroup-network-helper.sh` script.
</details>

cgroups.plugin: call `setresuid` before spawn server init

---

src/collectors/proc.plugin/proc_meminfo.c

When running within an LXC container, the KReclaimable metric is not a reliable indicator of the container's actual reclaimable memory (tested on a Proxmox server), as it reflects the host's overall value.
Noticed because of negative "used"
Fixes 
</details>

fix ram usage calculation in LXC

---

src/collectors/common-contexts/mem-swap.h
src/collectors/proc.plugin/proc_meminfo.c
src/health/health_event_loop.c

When swap is enabled but it is later on disabled when the agent is running, the corresponding chart stops being collected but it is not marked as obsolete. 
When a chart is marked as obsolete the health engine will automatically generate a REMOVED event. This will clear any warning or critical events

Detect when swap is disabled when agent is running

---

CMakeLists.txt

Compilers for some architectures e.g. RISCV32 do not have 64bit atomics therefore, its important to deduce that and use it to pass right flags to compiler to use them, e.g. h2o module
Fixes
nection.c.o): in function `h2o_create_connection': | /usr/src/debug/netdata/1.47.1/src/web/server/h2o/libh2o/include/h2o.h:1917:(.text.create_conn+0x5e): undefined reference to `__sync_add_and_fetch_8' | collect2: error: ld returned 1 exit status

Add check for 64bit builtin atomics

---

CMakeLists.txt
src/libnetdata/log/systemd-cat-native.c
src/libnetdata/socket/socket.c

systemd-cat-native negative timeout

---

.github/data/distros.yml
.github/workflows/packaging.yml

This ensures that they don’t pick up the host CPU and build for that instead, because apparently Go looks at the host CPU instead of itself to decide what the default build target is, so if you’re running a 32-bit build of Go on a 64-bit kernel, you get 64-bit binaries by default...
Once CI is complete on the PR, the packages produced as part of the build need to be inspected to confirm that the go plugin was built for the right architecture.
Fixes: #18716
@netdata/agent this needs to be included in our next patch release, and the issue probably is major enough to warrant a new patch release on it’s own.

Pass correct GOOS and GOARCH on to package builders in CI.

---

.github/workflows/build.yml
.github/workflows/docker.yml
.github/workflows/packaging.yml
packaging/makeself/jobs/99-makeself.install.sh

Something has broken in the latest version of `actions/upload-artifact` which is causing files to not be included correctly in the artifacts themselves (upstream bug https://github.com/actions/upload-artifact/issues/628), thus causing some CI jobs to fail. This PR explicitly rolls back to a known-working version of the action, as well as removing unnecessary usage of symlinks in the static build output as symlinks seem to make the problem worse.
Consolidated artifact tests pass on this PR and all workflows pass without warnings from `actions/upload-artifact`.

Fix handling of workflow artifacts.

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
CMakeLists.txt
packaging/windows/installer.nsi
src/claim/main.c
src/claim/ui.c

This PR addresses part of requests in https://github.com/netdata/netdata/issues/18624:
2. Install it
</details>

Improve windows installer

---

src/go/plugin/go.d/modules/storcli/charts.go
src/go/plugin/go.d/modules/storcli/collect_controllers.go
src/go/plugin/go.d/modules/storcli/metadata.yaml
src/go/plugin/go.d/modules/storcli/storcli_test.go

This change adds support for reported Raid-on-Chip (ROC) controller temperatures to be published into netdata.
The current storcli plugin doesn't report temperature information that's available on my card. This change adds it.
I manually tested this by running it on my netdata instance.
Attached is a screenshot of it working

[storcli] Support for controller ROC temperature.

---

src/aclk/aclk.c
src/database/sqlite/sqlite_aclk.c
src/database/sqlite/sqlite_aclk.h
src/health/health_event_loop.c
src/plugins.d/pluginsd_parser.c
src/streaming/receiver.c
src/streaming/rrdpush.h
src/streaming/stream_path.c
src/streaming/stream_path.h

When a child node disconnects from a parent delay sending the disconnect message to the cloud expecting the child
will be restarting. 
The parent will use information from the child (start and shutdown times) to calculate when the child is expected to reconnect before sending out the message to the cloud. 
It will wait `(start + shutdown) * 1.25` seconds (max of 30 seconds) before sending the message.

Delay child disconnect update

---

integrations/deploy.yaml
integrations/templates/platform_info.md
packaging/windows/WINDOWS_INSTALLER.md

integrations/deploy.yaml :point_right: format the file and replace the windows exporter deployment with the windows installer
integrations/templates/platform_info.md :point_right: include a sentence inside the if clause, so it does not appear everywhere
packaging/windows/WINDOWS_INSTALLER.md :point_right: the name of the .exe has changed
cc @netdata/product 
I tested the v3 UI locally and the result looks like:
and should have the `/TOKEN=` and `/ROOMS=` once it is merged and viewed in prod.

Windows deploy metadata

---

src/collectors/freebsd.plugin/freebsd_kstat_zfs.c
src/collectors/proc.plugin/proc_spl_kstat_zfs.c
src/collectors/proc.plugin/zfs_common.c
src/collectors/proc.plugin/zfs_common.h

fix(freebsd.plugin): fix sysctl arcstats.p fails on FreeBSD 14

---

.github/data/distros.yml
packaging/installer/install-required-packages.sh

Ubuntu 24.10 was released on 2024-10-10
Fedora 41 is expected to release on 2024-10-22
CI jobs pass on this PR.

Add Ubuntu 24.10 and Fedora 41 to CI.

---

src/go/plugin/go.d/agent/discovery/sd/discoverer/netlisteners/netlisteners.go

Exit if `local-listeners` times out 5 times and no successful executions have occurred.
</details>

fix(go.d/sd/net_listeners): exit if local-listeners constantly times out

---

src/daemon/main.c
src/ml/Config.cc
src/ml/ml-private.h

This PR changes the accepted values for the ML enabled option to  `auto`, `yes`, `no`. The `auto` option is now the default
The behavior will be the same on systems using `dbengine`, that is ML will be enabled. 
On systems not using `dbengine` the `auto` setting will not enable ML.
ML can always be enabled / disabled by setting this option explicitly to `yes`  or `no` respectively
- Start agent in dbengine mode with default settings
- *ML should be enabled*
- Start agent in RAM mode with default settings. 
- *ML should be disabled*
- Start agent in RAM mode with `enabled` set to  `yes`. 
- *ML should be enabled*

Expand ml enabled option

---

src/database/contexts/instance.c
src/database/contexts/internal.h
src/database/contexts/worker.c

Do not load labels on startup (add a new flag to request on demand). This will mostly apply to archived
hosts since charts that are being collected have labels.
Charts removed from memory have their labels deleted. The instance labels are also removed and are marked to be loaded on demand if needed.

Load chart labels on demand

---

src/ml/ml-configuration.md

- ML enabled is now set to `auto` by default. This will enable ML only if the `db = dbengine`,  that is,  there is enough retention to make sense to train the models. 
- You can still explicitly set `enabled = yes` or `enabled = no`

Document ML enabled `auto`

---

packaging/installer/netdata-updater.sh

fix(netdata-updater.sh): ensure `--non-interactive` flag is passed during self-update

---

src/collectors/proc.plugin/proc_net_dev.c
src/collectors/windows.plugin/perflib-network.c
src/database/rrdset.c
src/health/health.d/net.conf
src/health/rrdvar.c
src/health/rrdvar.h

Windows Alerts Improvements

---

src/collectors/ebpf.plugin/ebpf.c
src/collectors/windows.plugin/perflib-mssql.c
src/collectors/windows.plugin/perflib-network.c
src/daemon/winsvc.cc
src/database/engine/cache.c
src/database/rrdlabels.c
src/libnetdata/aral/aral.c
src/libnetdata/aral/aral.h
src/libnetdata/socket/socket.h
src/registry/registry.c
src/streaming/rrdpush.h
src/web/api/v2/api_v2_claim.c

Windows fixes (chart labels and warnings)

---

CMakeLists.txt

In a system like llvm+clang+compiler_rt+musl with no gcc neither binutils at all, netdata currently fails to compile because the atomic builtin check is invalid for this combination and then forces the linkage with the non existant libatomic.so.
This PR changes the test so that it looks for an implemented (and used in the code) `__atomic_load_n` instead of the current `__atomic_load_8` which is not implemented in compiler_rt neither used in the code.

Fix atomic builtins test that currently fails for llvm+compiler_rt when gcc is not present

---

.github/workflows/build.yml

macOS 12 is EOL as of approximately 1 month ago, and macOS 15 has been out for just as long, so it’s high time we updated our macOS CI jobs accordingly.
CI jobs are run correctly on this PR.
Note that if the build is broken on macOS 15, that _IS NOT_ a blocker for this PR to be merged, and should be dealt with in it’s own PR.

Remove macOS 12 from CI, and add macOS 15.

---

src/collectors/apps.plugin/apps_plugin.c
src/collectors/network-viewer.plugin/network-viewer.c
src/collectors/slabinfo.plugin/slabinfo.c
src/collectors/utils/local_listeners.c
src/libnetdata/aral/aral.c
src/libnetdata/log/nd_log-init.c
src/libnetdata/log/nd_log.h
src/libnetdata/maps/local-sockets.h
src/libnetdata/procfile/procfile.c
src/libnetdata/procfile/procfile.h
src/libnetdata/spawn_server/spawn_server_nofork.c

local-listeners improvements

---

src/database/sqlite/sqlite_health.c

- Variable needs to be within scope to perform the database insert

Fix variable scope to prevent invalid memory access

---

src/claim/claim.c

The function `claim_reload_and_wait_online()` should wait for a node id and claiming status ONLINE.
Before that PR it was checking for a machine guid and also claiming status INDIRECT, so the UI could not know when claiming is ready after claiming the agent.
@stelfrag this should probably go into the patch release.

claiming should wait for node id and status ONLINE only

---

CMakeLists.txt

Reverts netdata/netdata#18788
Compilation failure 
eg
```
/usr/bin/ld: liblibnetdata.a(libnetdata.c.o): undefined reference to symbol '__atomic_compare_exchange_8@@LIBATOMIC_1.0'
/usr/bin/ld: /lib/arm-linux-gnueabihf/libatomic.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
```
Linux rpi4b-1 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

Revert "Fix atomic builtins test that currently fails for llvm+compiler_rt when gcc is not present"

---

src/collectors/apps.plugin/apps_os_freebsd.c
src/collectors/apps.plugin/apps_os_linux.c
src/collectors/apps.plugin/apps_output.c
src/collectors/apps.plugin/apps_pid.c
src/collectors/apps.plugin/apps_pid_files.c
src/collectors/apps.plugin/apps_plugin.c
src/collectors/apps.plugin/apps_plugin.h
src/libnetdata/maps/local-sockets.h
src/libnetdata/maps/system-groups.h
src/libnetdata/maps/system-services.h
src/libnetdata/maps/system-users.h
src/libnetdata/query_progress/progress.c

optimizations for servers with vast amounts of sockets

---

docs/netdata-cloud/authentication-and-authorization/enterprise-sso-authentication.md

These changes update the documentation on how to use SSO, initiating the flow from Netdata sign-in page.
This now requires users to set up a `netdata-verification` code as a DNS record on their domain.

Update enterprise SSO docs

---

integrations/gen_integrations.py

Thanks to @car12o for bringing this up, integrations links should be absolute so that in the Website and App they can point to GitHub.
This change finds all `](/` in the integrations data and adds the https prefix
after this is merged, I will regen integrations and check Learn also, should not have changes there

Make integration links absolute

---

src/collectors/apps.plugin/apps_groups.conf
src/collectors/apps.plugin/apps_targets.c

Add https://github.com/krallin/tini. Some docker images use it (e.g. [mariadb/maxscale](https://hub.docker.com/r/mariadb/maxscale) (related issue #12830)).
Without this fix, `apps.plugin` fails to identify MaxScale (Docker) as an app and aggregates it into the `tini` group.
</details>

fix(apps.plugin): add tini to Linux managers

---

CMakeLists.txt
src/collectors/freebsd.plugin/freebsd_kstat_zfs.c
src/collectors/proc.plugin/proc_net_dev.c
src/collectors/proc.plugin/proc_spl_kstat_zfs.c
src/collectors/proc.plugin/zfs_common.c
src/collectors/proc.plugin/zfs_common.h
src/database/sqlite/sqlite_aclk_node.c
src/database/sqlite/sqlite_health.c
src/go/plugin/go.d/agent/discovery/sd/discoverer/netlisteners/netlisteners.go
src/go/plugin/go.d/modules/nvidia_smi/charts.go
src/go/plugin/go.d/modules/nvidia_smi/collect.go
src/go/plugin/go.d/modules/nvidia_smi/metadata.yaml
src/health/rrdvar.c
src/health/rrdvar.h

- fix(packaging): check for sys/capability.h only on Linux (#18849)
- add "index" label to GPU charts (#18833)
- fix(proc/proc_net_dev): delay collecting all virtual interfaces (#18812)
- fix(proc.plugin/zfs): fix arcstats.pm (#18758)
- fix(freebsd.plugin): fix sysctl arcstats.p fails on FreeBSD 14 (#18748)
- fix(go.d/sd/netlisteners): fix exec deadline exceeded check (#18774)
- fix(go.d/sd/net_listeners): exit if local-listeners constantly times out (#18757)
- Fix wrong variable scope
- Additional checks when acquiring/setting chart variable (https://github.com/netdata/netdata/pull/18804/commits/17ce74e66146955a870ba4e1f45c6d9470986a80) backport from (#18785) 
- Schedule a node state update after context load backport (#18795)
- Fix storing of repeat field (#18760)

Patch release 1.47.5

---

CMakeLists.txt

SSIA, anyone can override this with `ccmake build`.
- CI jobs.

Do not build H2O by default.

---

src/aclk/aclk_otp.c

- Allocate large enough buffer to prevent memory corruption

Prevent memory corruption during ACLK OTP decode

---

docs/netdata-agent/reload-health-configuration.md
docs/netdata-agent/start-stop-restart.md

Remove useless info, as we state that the Agent is set to start at boot at the top of the file
Add Windows information (tried to keep it short, no description)
Move reload health configuration to its own file (Will need to add to Learn after this PR)

Start-stop-restart for windows, plus move info to its own file

---

.github/workflows/build.yml
.gitignore
CMakeLists.txt
packaging/windows/compile-on-windows.sh
packaging/windows/get-win-build-path.sh
packaging/windows/install-dependencies.ps1
packaging/windows/package-windows.sh
packaging/windows/package.ps1
packaging/windows/win-build-dir.sh

We plan to switch to MSI packages long-term for installation on Windows.
In addition to the CI change, this PR also:
- Adds installation of WiX and the required WiX extensions to the dependency handling script. Note that this requires a working copy of the .NET SDK with NuGet set up correctly for it to work (having a working install of a recent version of Visual Studio will generally meet this requirement).
- Updates the Windows build/packaging scripts so that they use the same logic to determine build directories in all places.
- Updates the build directory handling code to use `cygpath` to convert paths between Windows/Unix style instead of a complicated `sed` expression.
- Updates the code that templates the WiX source file to put the generated file in the build directory instead of …

Update CI to generate MSI installer for Windows using WiX.

---

docs/netdata-agent/sizing-netdata-agents/README.md
docs/netdata-agent/sizing-netdata-agents/cpu-requirements.md

I think we should start calling "Netdata Parent Agents" as Parents and "Netdata Child Agents" as Children, I see a lot of combinations of the 3-word version and it does not make sense.
I renamed the section to "Resource Utilization" (checked, singular is correct)
removed optimization section that was duplicate of README, added the database mode option.

Docs: Changes to title and CPU requirements

---

docs/observability-centralization-points/metrics-centralization-points/faq.md

The Netdata CLI command for `remove-stale-node` was not yet documented.
This also adds more details on nodes marked as ephemeral in general, and fixes the section and configuration property name.

Improve the documentation on removing stale nodes

---

CMakeLists.txt
src/collectors/all.h
src/collectors/windows.plugin/perflib-hyperv.c
src/collectors/windows.plugin/windows_plugin.c
src/collectors/windows.plugin/windows_plugin.h
src/database/rrdlabels.h

Add hyper v metrics -- charts for 
- VM Memory Pressure
- VM Assigned Memory
- VM Guest Visible Memory
- VM Physical Pages Allocated
- VM Physical Pages Not Allocated from Preferred NUMA Node
- Virtual Machines Health Status
- Root Partition Device Space Pages
- Root Partition GPA Space Pages
- Root Partition GPA Space Modifications
- Root Partition Attached Devices
- Root Partition Deposited Pages
- Root Partition Illegal DMA Requests
- Root Partition Illegal Interrupt Requests
- Root Partition Throttled Interrupts
- Root Partition Flushes of I/O TLBs
- Root Partition Address Spaces in Virtual TLB
- Root Partition Pages Used by Virtual TLB
- Root Partition Flushes of Entire Virtual TLB
- VM Storage Device IOPS
- VM Storage Device IO
- VM Storage Device Errors
- Virtual Switch Traffic
- …

Add hyper-v metrics

---

src/database/sqlite/sqlite_aclk.c
src/database/sqlite/sqlite_aclk_node.c

- Avoid expensive checks on parents with a lot of children and charts

Improve ACLK sync CPU usage

---

CMakeLists.txt
packaging/cmake/config.cmake.h.in
src/libnetdata/os/random.c

random numbers No 3

---

packaging/repoconfig/CMakeLists.txt
packaging/repoconfig/deb.changelog
packaging/repoconfig/netdata.repo.dnf
packaging/repoconfig/netdata.repo.zypp
packaging/repoconfig/netdata.sources.in
packaging/repoconfig/rpm.changelog

This switches over to the new hosting for the repository data itself. Users should not see any difference other than the URLs and possibly the IP addresses being accessed.
n/a

Switch DEB/RPM repositories to new subdomain.

---

src/claim/claim-with-api.c

fix memory leak when using libcurl

---

CMakeLists.txt
src/database/contexts/api_v2_contexts.c
src/database/contexts/rrdcontext.h
src/database/rrd.h
src/database/sqlite/sqlite_metadata.c
src/streaming/stream-path.c
src/streaming/stream-path.h
src/web/api/v3/api_v3_calls.h
src/web/api/v3/api_v3_stream_path.c
src/web/api/web_api_v3.c

**Stream Path**: the ability of Netdata Agents to know the entire streaming path of each Netdata node. All Netdata nodes propagate the entire streaming path both forward (towards a Parent) and backward (towards a Child), so that all nodes involved in streaming are aware of the entire streaming path and all Netdata Agents involved.

added /api/v3/stream_path

---

src/daemon/main.c

The _vast_ majority of these reports are not useful.
We can always revert this, if we want to.
- CI jobs
- Nightlies

Do not intentionally abort on non-0 exit code.

---

src/health/health.d/disks.conf

fix: exclude volumes w/o drive letter from disk_space_usage_alert

---

packaging/windows/netdata.wxs.in

This PR is bringing as updates to installer:
-  Launch Netdata when installation ends
- Fix button redirect
- Does not allow a token larger than expected.
- Does not allow users advance filling either Token or Room.
2. Generate the installer
3. Install the final binary and verify that you do not have fields to claim the agent.
4. Remove Netdata and the claim.conf file.
5. Install netdata again, and this time you will have the fields to claim agent.
</details>

Improve Installer (Part II)

---

src/streaming/receiver.c
src/streaming/replication.c
src/streaming/rrdhost-status.c

backport of fixes from balance-parents

---

netdata-installer.sh

added --dev option to netdata-installer.sh to prevent it from removing the build directory

--dev option to installer

---

.github/data/distros.yml
.github/scripts/check-updater.sh
.github/scripts/ci-support-pkgs.sh
.github/scripts/run-updater-check.sh
.github/workflows/build.yml
.github/workflows/packaging.yml

This PR makes a number of changes to CI to reduce the overall runtime when possible by eliminating jobs and steps we don’t actually need.
- Removes older Alpine Linux build checks. Just checking edge and latest is almost certainly good enough here.
- Removes the old .gitignore consistency check. This hasn’t actually caught any issues in a _very_ long time, and it doesn’t even check everything it should be, so there’s not much point in keeping it.
- Drops the JSON-C vendoring check step in our local build checks. It’s astronomically unlikely that a failure in the code being checked by this would actually impact a user at this point (it only existed in the first place to handle updates when we added JSON-C as a mandatory dependency multiple years ago now), and it roughly doubles the runtime …

Tidy up CI to improve overall run times.

---

src/go/plugin/go.d/modules/nvidia_smi/nvidia_smi.go

Disable loop mode on Windows due to go.d.plugin's non-graceful exit, which can keep `nvidia_smi` processes running indefinitely.
On Windows, we'll rely on the [QUIT](https://github.com/netdata/netdata/pull/19038) command instead of signals (when implemented in the Agent).
</details>

fix(go.d/nvidia_smi): disable loop mode by default on Win

---

src/database/sqlite/sqlite_aclk_alert.c

- When the cloud includes version=1 in start streaming alerts  or version check, the agent will not perform a version check for snapshot

Add a special version number to bypass alert snapshots

---

packaging/windows/netdata.wxs.in

- Register Agent service to `Automatic (delay start)`  when rebooting / starting a windows machines
- We noticed that when it is configured as `Automatic` some metrics may be missing
- This requires a service restart to resolve
- Existing installed Agent need to reconfigure the service to ` Automatic (delay start)`

Register service to delay start

---

docs/glossary.md
docs/netdata-agent/configuration/common-configuration-changes.md
docs/netdata-agent/configuration/optimize-the-netdata-agents-performance.md
src/collectors/COLLECTORS.md
src/collectors/README.md
src/collectors/REFERENCE.md

@ilyam8 I would also consider the placing of this on Learn, it feels out of place being inside the "Collecting Metrics" section, it is an Agent configuration process mostly, what do you think?
I also don't like docs/netdata-agent/configuration/common-configuration-changes.md as a file, but I will decide what to do on it once the rest of the closed PR is split.

Collector configuration page edits

---

src/database/sqlite/sqlite_aclk_alert.c

- Fix an issue with parameter initialization during snapshot rebuild

Reset parameter when generating an alert snapshot

---

src/collectors/proc.plugin/run_reboot_required.c

I didn't notice that "not_required" was red.
</details>

change dim order because of colours in reboot_required

---

src/collectors/ebpf.plugin/ebpf.c
src/collectors/ebpf.plugin/ebpf_apps.c
src/collectors/ebpf.plugin/ebpf_apps.h

- Hold process ids in an judy array (as needed)) instead of pre-allocating structures

Reduce EBPF memory usage

---

src/database/sqlite/sqlite_aclk_node.c

- Avoid scanning charts for replication status (replication status is maintained per host anyway)
- This should further reduce CPU usage for children with a lot of charts during initial connection to the parent

Avoid scanning charts for replication status

---

packaging/windows/netdata.wxs.in

This PR is modifying our installer to hide all fields on Claim Screen when there is already a claim.conf file generated during installation time.
2. Make an installer
3. Remove your netdata using Windows Control Panel
4. If you already claimed your agent, rename your `c:\Program Files\Netdata\etc\netdata\claim.conf` and run the installer. You should have the following screen:
5. Stop the installation, and rename the file again to `c:\Program Files\Netdata\etc\netdata\claim.conf` . Run the installer again, this time you will have the following screen:
- Which area of Netdata is affected by the change? Installer
- Can they see the change or is it an under the hood? …

Modify Claim Screen (Windows Installer)

---

src/go/go.mod
src/go/go.sum

Reverts #19151
Fixes build on 32bit systems
```
/home/cm/go/pkg/mod/github.com/kamstrup/intmap@v0.5.0/map64.go:22:11: 0x9E3779B9 (untyped int constant 2654435769) overflows int
```
</details>

fix(build): fix building go.d on 32bit

---

packaging/installer/kickstart.sh

[Reported on Forum](https://community.netdata.cloud/t/install-script-kickstart-doesnt-work-with-native-only-or-general-deb-install-for-plain-ubuntu-2204-an-2404/6077)
</details>

fix(kickstart): netdata_avail_check on Ubuntu

---

src/libnetdata/locks/rw-spinlock.c
src/libnetdata/locks/rw-spinlock.h

revert preferring writers in rw_spinlocks - recursive read locks are required by dictionary

rw_spinlocks: allow recursive readers, even when writers are waiting

---

.github/scripts/get-go-version.py
.github/workflows/go-tests.yml

Initial version covers the five Linux-based Go platforms we care about, plus 64-bit x86 on Windows.
CI passes on this PR and the newly added jobs are present.

Add cross-architecture build tests for Go code.

---

src/ml/ml.cc

Parent logs are full of these lines on Child disconnect:
```
Dec 16 14:47:24 pve-deb-work netdata[2583401]: ML: Failed to create new model: could not acquire dimension (machine-guid: 9addbf46-b94a-11ef-8235-1a4d4a89f930, dimension: 'app.kernel_fds_open.event', reason: host is orphan or archived)
Dec 16 14:47:34 pve-deb-work netdata[2583401]: ML: Failed to create new model: could not acquire dimension (machine-guid: 9addbf46-b94a-11ef-8235-1a4d4a89f930, dimension: 'app.ksmd_cpu_context_switches.voluntary', reason: host is orphan or archived)
Dec 16 14:47:44 pve-deb-work netdata[2583401]: ML: Failed to create new model: could not acquire dimension (machine-guid: 9addbf46-b94a-11ef-8235-1a4d4a89f930, dimension: 'app.ksmd_disk_logical_io.reads', reason: host is orphan or archived)
``` …

fix(ml): remove logging for earch not acquired dimension

---

src/go/plugin/go.d/collector/mongodb/client.go

[Reported on Forum](https://community.netdata.cloud/t/prohibit-netdata-from-scanning-or-binding-to-port-range/6097/4).
</details>

fix(go.d/mongodb): add missing disconnect in initClient

---

src/database/sqlite/sqlite_metadata.c

- Use calculated cpus / 2 to speed up context load in parents with a lot of children

Allow more threads to load contexts during startup

---

src/database/engine/rrdengineapi.c
src/health/rrdcalc.c

- Do not call finalize, data file rotation can occur during shutdown
- Do not create alert removed state during shutdown. This is checked and created on startup

Do not call finalize on shutdown

---

src/database/sqlite/sqlite_aclk.c

- Run the event loop once and do not block when no pending events are expected

Avoid blocking waiting for an event during shutdown

---

src/health/health.h
src/health/health_event_loop.c
src/health/health_log.c
src/health/health_notifications.c
src/health/rrdcalc.c

- Use both sync or async save mode for health transitions. 
When a child disconnects health transitions will be stored asynchronously so as not to block the receiver thread cleanup process.
- The main health processing thread will store transitions synchronously. 
This will allow to better process alert snapshots and individual alert transitions that need to reach the cloud

Health transition saving optimization

---

.github/scripts/build-static.sh
packaging/makeself/build-static.sh
packaging/makeself/functions.sh
packaging/makeself/jobs/20-openssl.install.sh
packaging/makeself/jobs/50-bash-5.1.16.install.sh
packaging/makeself/jobs/50-curl.install.sh
packaging/makeself/jobs/50-ioping-1.3.install.sh
packaging/makeself/jobs/50-libnetfilter_acct-1.0.3.install.sh
packaging/makeself/jobs/70-netdata-git.install.sh
packaging/makeself/jobs/99-makeself.install.sh
packaging/makeself/run-all-jobs.sh

Part of the intent of our static builds is to work (almost) everywhere with a given CPU architecture. However, we currently don’t do any checks to ensure this.
This PR adds overrides for QEMU CPU architectures during static builds to ensure this for non-x86 architectures. The newly enforced baselines are:
- ARM1176 for ARMv6 builds. This is consistent with the Raspberry Pi 1, which was our original target platform for this build, and will work on most commonly used ARMv6 hardware as well.
- ARM Cortex-A7 for ARMv7 builds. This is the de-facto architectural baseline for ARMv7, so things that run on it will run on pretty much all ARMv7 systems.
- ARM Cortex-A53 for 64-bit ARM builds. Again, this is the de-facto architectural baseline here, so it should run everywhere.
- POWER8+ for 64-bit …

Fix static builds to ensure usability on intended baseline hardware.

---

src/database/sqlite/sqlite_metadata.c

- Skip label cleanup during metadata processing (it includes checks taking into account data retention which doesn't help that much)

Skip label cleanup during metadata processing

---

src/go/plugin/go.d/collector/rabbitmq/collect.go
src/go/plugin/go.d/collector/rabbitmq/collect_nodes.go
src/go/plugin/go.d/collector/rabbitmq/collector.go
src/go/plugin/go.d/collector/rabbitmq/collector_test.go
src/go/plugin/go.d/collector/rabbitmq/restapi.go
src/go/plugin/go.d/collector/rabbitmq/testdata/v4.0.3/cluster/whoami.json

In RabbitMQ, querying the `/api/definitions` endpoint requires administrative privileges.
</details>

fix(go.d/rabbitmq): handle insufficient perms when querying definitions

---

src/daemon/pulse/pulse-db-dbengine.c
src/database/engine/metric.c
src/database/engine/metric.h

-  fixed bug in mrg cleanup, not deleting metrics that do not have retention
-  fix for mrg acquired and referenced going negative

Fix metric retention check and cleanup

---

packaging/installer/netdata-updater.sh

When conditional parameters (`force-update`, `non-interactive`) were not set, the command construction led to improper argument handling, which caused the script to ignore the final parameter (`--tmpdir-path`).
</details>

fix(netdata-updater.sh): ensure tmpdir-path argument is always passed

---

src/collectors/debugfs.plugin/module-libsensors.c
src/collectors/proc.plugin/proc_diskstats.c
src/daemon/pulse/pulse-daemon-memory.c
src/daemon/pulse/pulse-http-api.c
src/daemon/pulse/pulse-http-api.h
src/daemon/pulse/pulse-ingestion.c
src/daemon/pulse/pulse-ml.c
src/daemon/pulse/pulse-queries.c
src/daemon/pulse/pulse-sqlite3.c
src/database/engine/cache.c
src/database/rrdlabels.c
src/libnetdata/local-sockets/local-sockets.h
src/libnetdata/log/systemd-cat-native.c
src/libnetdata/socket/poll-events.c
src/libnetdata/socket/socket.c
src/libnetdata/waiting-queue/waiting-queue.c
src/libnetdata/waiting-queue/waiting-queue.h
src/streaming/stream-sender-commit.c
src/streaming/stream-sender.c
src/web/server/web_client_cache.c

Streaming improvements No 12

---

src/daemon/daemon-shutdown.c
src/database/engine/cache.c

revert coverity fix; count also the number of entries to release shutdown

Fix shutdown

---

CMakeLists.txt
src/daemon/main.c
src/libnetdata/libnetdata.h
src/libnetdata/locks/benchmark-rw.c
src/libnetdata/locks/benchmark-rw.h
src/libnetdata/locks/benchmark.c
src/libnetdata/locks/benchmark.h
src/libnetdata/locks/rw-spinlock.c
src/libnetdata/locks/rw-spinlock.h
src/libnetdata/locks/waitq.c

```
=== Performance Summary (Million locks/sec) ===
Lock Type           1        2        4        8       16       32       64
------------------------------------------------------------------------------
Mutex           87.81    25.42    27.61    16.86    16.07    15.19    15.61
RWLock          55.10    12.10    10.72     7.04     6.17     0.21     0.54
Spinlock       149.16   150.38   146.49   140.79   129.87   123.25   119.32
RW Spinlock     81.00    80.94    79.86    76.91    69.93    65.11    61.80
WaitQ           51.61    51.49    51.40    48.03    40.17    38.65    29.24
```
- Good single-threaded performance (87.81M ops/sec)
- Performance drops significantly with 2+ threads (down to ~25M ops/sec)
- Stabilizes around 15-16M ops/sec with higher thread counts
- Behavior reflects …

Locks Improvements

---

src/collectors/cgroups.plugin/cgroup-name.sh.in

This PR adds support for container configuration via:
- Docker: container labels.
- Kubernetes: pod annotations.
to `cgroup-name.sh`. The next PR will add handling of `netdata.cloud/*` labels to groups.plugin.
Note: 
</details>

feat(cgroup-name.sh): Add support for `netdata.cloud/*` container labels

---

packaging/installer/netdata-updater.sh

Fixes: #19291
~~Using `TMPDIR` environment variable to control `mktemp`'s output directory
location was unreliable.~~ `TMPDIR` was set but not exported, so `mktemp` in a subshell wouldn't see it.
```bash
TMPDIR="/tmp"
mktemp -d -t netdata-updater-XXXXXXXXXX
TMPDIR="/tmp" mktemp -d -t netdata-updater-XXXXXXXXXX
```
Instead of relying on `TMPDIR` environment variable modification, this change
makes the temporary directory creation more explicit by using `mktemp`'s `-p` flag to specify the parent directory directly.
- Remount `/tmp` with `noexec`.
- Run the updater script manually and ensure it fallbacks to `pwd`.
</details>

fix(netdata-updater.sh): use explicit paths for temp dir creation

---

src/collectors/cgroups.plugin/cgroup-discovery.c
src/collectors/cgroups.plugin/sys_fs_cgroup.h

use labels `netdata.cloud/ignore` and `netdata.cloud/cgroup.name` to control the groups
Fixes: #12147

CGROUP labels

---

packaging/installer/functions.sh
packaging/installer/netdata-uninstaller.sh
packaging/installer/netdata-updater.sh
system/install-service.sh.in

This adds a new option to the updater script, intended to be run interactively, named `--auto-update-status`. When run with this option, the updater script will print out messages to indicate the default auto-update scheduling method for the system, as well as whether or not auto-updates are enabled for each supported scheduling method (and a warning if more than one scheduling method has auto-updates enabled). Output looks like:
```
Thu Dec 19 07:42:50 AM EST 2024 : INFO: netdata-updater.sh:  The default auto-update scheduling method for this system is: drop-in periodic script
Thu Dec 19 07:42:50 AM EST 2024 : INFO: netdata-updater.sh:  Auto-updates using a systemd timer unit are NOT SUPPORTED due to: Systemd not present
Thu Dec 19 07:42:50 AM EST 2024 : INFO: netdata-updater.sh: …
```

Add option to updater to report status of auto-updates on the system.

---

src/health/notifications/email/README.md
src/health/notifications/email/metadata.yaml

Add instructions on how to setup email notifications when running Docker Compose.
Please add this to metadata as well. 
Thanks!
(Related to this: https://github.com/netdata/helper-images/pull/307)

Add instructions for Docker Compose

---

packaging/installer/functions.sh
packaging/installer/netdata-uninstaller.sh
packaging/installer/netdata-updater.sh
system/install-service.sh.in

- Properly scope `set -e` changes to only affect `systemctl is-system-running` invocation.
- Skip checking for hard-coded unit file paths. Other paths may technically be used for unit files instead of what we hard-code, and the presence or abscence of any specific unit file path _does not_ reliably indicate the presence or abscence of systemd.
n/a

Assorted systemd detection fixes

---

src/daemon/pulse/pulse-daemon-memory.c

When memory is about 2GiB, sqlite memory status shows negative values. Fixed.

use sqlite3_status64()

---

src/database/engine/rrdengineapi.c

Prevent this memory corruption:

prevent memory corruption in dbengine

---

src/libnetdata/log/nd_log-init.c
src/libnetdata/log/nd_log-internals.h
src/libnetdata/log/nd_log-libunwind.c
src/libnetdata/spawn_server/spawn_server_nofork.c

libunwind does not work well after fork (it freezes), so we disable stack traces on forked processes

disable libunwind on forked children

---

CMakeLists.txt
src/daemon/pulse/pulse-daemon-memory-system.c
src/daemon/pulse/pulse-daemon-memory.c
src/libnetdata/libnetdata.c
src/libnetdata/libnetdata.h

Added 2 charts about memory maps.
- the first counts the number of mmap allocations by netdata and glibc (separately)
- the second is the percentage of mmaps vs the system max

added mmap count charts

---

src/daemon/pulse/pulse-daemon-memory.c
src/libnetdata/aral/aral.c
src/libnetdata/onewayalloc/onewayalloc.c

Reduce glibc memory fragmentation

---

CMakeLists.txt

This is required for us to properly handle testing of it in our various builds, will be required long-term for consistent behavior of builds (since it will allow us to ensure that a build that is supposed to include libunwind actually includes it), and is how it should have been done in the first place.
Fixes the current build failures on master.
CI passes on this PR instead of failing like it does on master.

Make libunwind opt-in at build time instead of auto-enabled.

---

.github/data/distros.yml

It went EOL upstream as of 2024-12-31.
n/a
Resolves: #19113

Remove openSUSE 15.5 from CI and package builds.

---

src/database/sqlite/sqlite_context.c
src/database/sqlite/sqlite_context.h
src/database/sqlite/sqlite_functions.c
src/database/sqlite/sqlite_metadata.c

- During database rotation, contexts may be deleted due to no data retention. Cleanup for those is now prioritized

Verify and cleanup deleted contexts

---

src/daemon/libuv_workers.c
src/daemon/libuv_workers.h
src/database/sqlite/sqlite_aclk.c
src/database/sqlite/sqlite_aclk.h
src/database/sqlite/sqlite_aclk_alert.c

- Use a worker thread to send the alert transitions to the cloud, ensuring the main event loop remains unblocked.

Use worker when dispatching alert transitions to the cloud

---

packaging/installer/kickstart.sh

Reverts netdata/netdata#18962
Something is broken with the repository that did not show up in testing. Reverting for now while we figure out what’s wrong.

Revert "Update kickstart script to use new repository host."

---

src/libnetdata/os/system_memory.c

cgroups v1 needs the controller path

system memory calculation for cgroups v1 fix

---

CMakeLists.txt
src/aclk/aclk.c
src/aclk/aclk.h
src/aclk/mqtt_websockets/mqtt_wss_client.c
src/aclk/mqtt_websockets/mqtt_wss_client.h
src/collectors/statsd.plugin/statsd.c
src/daemon/pulse/pulse-http-api.c
src/daemon/pulse/pulse-network.c
src/daemon/pulse/pulse-network.h
src/daemon/pulse/pulse.c
src/daemon/pulse/pulse.h
src/database/contexts/worker.c
src/database/sqlite/sqlite_aclk_node.c
src/streaming/stream-receiver.c
src/streaming/stream-sender.c
src/web/server/static/static-threaded.c

pulse now tracks network traffic for:
This is in real-time, not after processing requests. Pulse has been hooked to the reception and dispatch of all the above.

PULSE: network traffic

---

.github/data/distros.yml

It went EOL upstream 2024-11-06.
n/a

Drop Fedora 39 from CI and package builds.

---

src/database/sqlite/sqlite_metadata.c

- Cleanup context check list on startup 
Remove hosts that have been deleted and may be still in the checklist

Cleanup context check list on startup

---

src/database/sqlite/sqlite_aclk.c

- Run the event loop frequently, even if there are commands to process.
- Process up to 64 commands before returning to the event loop

Make sure ACLK synchronization event loop runs frequently

---

packaging/docker/Dockerfile

SSIA
Primary testing involves confirming that CI passes on this PR. Secondary testing involves building the Docker images locally and confirming that the executable in them is indeed linked to libunwind.
32-bit x86 images are being intentionally excluded from this, as libunwind does not appear to work correctly there and they are generally not used much.

Enable libunwind in Docker images.

---

packaging/build-package.sh
packaging/docker/Dockerfile

This actually needs to wait until after the release, likely even longer (because it breaks 32-bit builds on 64-bit hosts).
n/a

Revert libunwind being enabled in Docker and DEB builds.

---

src/database/rrdhost-status.c
src/database/rrdhost-status.h

- Use `rrdhost_get_ingest_status`  (a simplified version of `rrdhost_status`) to  return the injest status of a host. 
- The state is used to propagate a node state update message to the cloud

Simplify the rrdhost_ingestion_status call

---

src/database/rrdhost.c

- Verify that the child has finished replication and is online before initializing health
- This will avoid generating alert transitions if the child disconnects before replication finishes

Child should be online before initializing health

---

src/libnetdata/object-state/object-state.c
src/libnetdata/object-state/object-state.h
src/plugins.d/pluginsd_parser.c
src/streaming/stream-receiver.c

when the receiver is null, there is no need to wait for anything

fix crash when cleaning up virtual nodes

---

src/go/plugin/go.d/collector/ping/config_schema.json
src/go/plugin/go.d/collector/ping/metadata.yaml

The performance issue in privileged mode [was fixed](https://github.com/netdata/netdata/issues/15410#issuecomment-2612437503).
</details>

chore(go.d/ping): set privileged by default for dyncfg jobs

---

src/database/sqlite/sqlite_aclk_alert.c
src/database/sqlite/sqlite_health.c
src/health/health_event_loop.c

- Use precompiled statements when processing alert transitions (much faster than compiling each time)

Improve alert transition processing

---

src/daemon/pulse/pulse-daemon-memory-system.c
src/daemon/pulse/pulse-daemon-memory.c
src/daemon/pulse/pulse-daemon-memory.h
src/daemon/pulse/pulse.c
src/daemon/pulse/pulse.h
src/daemon/static_threads.c
src/database/engine/page.c
src/database/engine/rrdengineapi.c
src/database/ram/rrddim_mem.c
src/database/storage-engine.h
src/libnetdata/aral/aral.c
src/libnetdata/common.h
src/libnetdata/dictionary/dictionary-traversal.c
src/libnetdata/dictionary/dictionary.c
src/libnetdata/gorilla/gorilla.cc
src/libnetdata/log/nd_log.c
src/libnetdata/os/gettid.c
src/libnetdata/storage_number/storage_number.c
src/libnetdata/storage_number/storage_number.h
src/web/api/queries/query.c

This PR makes a number of adjustments in order for Netdata to have 2 critical paths fully inlined (LTO) eliminating most function calls:
1. Data Collection
2. Querying
The results are impressive:
When Netdata is compiled with this PR and LTO enabled:
- Data Collection: -20% in CPU consumption
- Querying: almost twice the speed (from 21M samples/s/thread to 39M samples/s/thread)
For critical functions, which are not inlined by default even with `-flto` given, we introduce an `ALWAYS_INLINE` macro which resolves to `__attribute__((always_inline))` on supported compilers (gcc, clang). This gives a strong hint to the compiler/linker that when LTO is enabled this function should be inlined.
---
The following additional changes are made:

LTO Benchmark

---

src/collectors/proc.plugin/plugin_proc.c

Reading of `/proc/spl/kstat/zfs/pool/state` was removed in #18389,
but not the related config option. Clean it up.
</details>

proc.plugin: remove traces of /proc/spl/kstat/zfs/pool/state

---

src/collectors/proc.plugin/proc_net_dev.c

The `ifb4*` names are used for IFB interfaces by the [sqm-scripts][1]
project.  Ignore them similarly to the `*-ifb` interfaces.
[1]: https://github.com/tohojo/sqm-scripts
- when using sqm-scripts to configure traffic shaping/policing, internal network
interfaces created by sqm-scripts will be ignored by default, matching the
behavior when using FireQOS.
</details>

proc.plugin: add `ifb4*` to excluded interface name patterns

---

packaging/makeself/build-static.sh

- Switch to using `tonistiigi/binfmt` instead of `multiarch/qemu-user-static`. This image is what Docker itself seems to recommend, and is both receiving more active updates than the old one _and_ supports usage on hosts other than 64-bit x86 systems.
- Only install emulation for the specific platform we need instead of installing for everything.
- Try to auto-detect an existing QEMU userspace emulation setup, and skip emulation if one is seen. This eliminates the need to manually override emulation setup, and thus also eliminates the possibility of accidentally breaking an existing emulation setup.
Needs local testing.

Make handling of cross-platform emulation for static builds smarter.

---

src/database/sqlite/sqlite_health.c

- Fix the alert transition delay from warning or critical to removed to be 10 seconds (it was 10 mins)
- A removed state could be due to a node reconnecting, the short delay may be enough to avoid transmitting two alert state changes to the cloud
- Use the actual alert trigger time (rather than the current time) to adjust the scheduled time to send to cloud
- As rate as it might be, additional delay may be added if processing takes longer than expected between trigger time and time to be added in the queue.

Fix alert transition

---

CMakeLists.txt
packaging/cmake/Modules/NetdataLibBPF.cmake
src/libnetdata/libnetdata.h

Nothing else in our code base uses libbpf, so there is exactly zero reason to be linking it through libnetdata. Linking directly will cut down on our dependency tree in our native packages, and also reduce the work that needs to be done by the linker for static builds, as well as narrowing any potential attack surface.
Needs review and build testing.

Link the ebpf plugin against libbpf directly instead of through libnetdata.

---

.github/workflows/build.yml

Nightly static aarch64 fails with
> 2025-01-29T05:26:49.5834294Z ##[warning]Attempt 1 failed. Reason: Timeout of 10800000ms hit
</details>

ci: increase static build timeout 180->300m

---

src/collectors/windows.plugin/perflib-mssql.c

This PR addresses issues related to the absence of default SQL Server instances.
1. Install a SQL Server using a [non default](https://docs.microfocus.com/doc/Operations_Bridge_Manager/24.4/SqlInstances) instance name 
2. Install this branch.
</details>

Fix MSSQL Instance

---

src/go/plugin/go.d/collector/snmp/collector.go
src/go/plugin/go.d/collector/snmp/config_schema.json
src/go/plugin/go.d/collector/snmp/metadata.yaml

ssia, following the [v2.2.0 deprecation notice](https://github.com/netdata/netdata/releases/tag/v2.2.0#v220-deprecation-notice). 
</details>

chore(go.d/snmp): enable create_vnode by default

---

src/streaming/stream-sender-execute.c

Function `rrd_function_run()` runs callback `stream_execute_function_callback()` which frees the buffer `wb`.
This is a long standing bug that corrupts memory in streaming, when remote functions fail.

fix heap use after free

---

src/database/contexts/instance.c
src/database/contexts/internal.h
src/database/contexts/metric.c
src/database/contexts/rrdcontext.c

The agent is caching a boolean about RRDDIMs being collected or not. It uses this boolean to avoid more expensive processing when simply collecting data (between iterations).
Unfortunately this cached boolean was not reset when children get reconnected and in some cases the contexts were left in an inconsistent state regarding their liveness.
Fixed it. Now these cached flags are reset or child reconnect.

Fix contexts stay not-live when children reconnect

---

src/database/engine/pdc.c

Despite the fact that the file format supports files above 4GiB, there were a couple of variables in 32-bits.

allow dbengine to read at offsets above 4GiB

---

CMakeLists.txt
packaging/cmake/Modules/NetdataCompilerFlags.cmake
src/daemon/main.c

The existing attempt in our code to require `-fexceptions` in the compiler flags is fundamentally broken because:
1. It only actually checks if the flag is _supported_, not if it’s enabled, and doesn’t try to enable it if it is supported.
2. It adds pointless code at runtime because the build itself will fail if the flag is not handled.
This PR:
- Fixes the location of the check at build time so that it’s actually handled with all of our other handling of compiler flags, like it should have been in the first place (and like was brought up in a review comment on the PR that added this...).
- Fixes the build time check itself to actually ensure the flag gets added to the compiler/linker flags, and throw a fatal error if that cannot be done.
- Drops the runtime check, which will never …

Actually handle the `-fexceptions` requirement correctly in our build system.

---

src/aclk/aclk.c
src/database/contexts/instance.c
src/database/contexts/internal.h
src/database/contexts/metric.c
src/database/contexts/rrdcontext.c
src/database/engine/pdc.c
src/database/rrdhost-status.c
src/database/sqlite/sqlite_metadata.c

- virtual hosts now get hops = 1 (#19546)
- allow dbengine to read at offsets above 4GiB (#19539)
- Fix contexts stay not-live when children reconnect (#19536)

Patch release 2.2.3

---

src/go/plugin/go.d/collector/mysql/collector_test.go

The mariadb patch version is 64 not 46, with respect to the test data.

fix(go.d/mysql): fix typo in test name

---

docs/netdata-agent/start-stop-restart.md

This update corrects a documentation error where the restart action incorrectly used stop commands. It now properly uses `sudo systemctl restart netdata` and `sudo service netdata restart`. Fixes #nnn.
Manually verified that the restart commands work correctly:
- **Systemd**: `sudo systemctl restart netdata`
- **Non-systemd**: `sudo service netdata restart`
This change fixes a typo in the documentation. Users can now restart Netdata correctly without confusion.
The net effect is an accurate documentation update, ensuring that restarting Netdata uses the proper commands.
</details>

docs(start-stop-restart): fix restart typo

---

src/collectors/cgroups.plugin/cgroup-network.c

Two fixes to cgroup name validation in cgroup.plugin:
- **cgroups.plugin: fix escape sequence validation in cgroup paths**
- **cgroups.plugin: accept `@` in cgroup paths**
- cgroup.plugin won't break with systemd-nspawn
- cgroup.plugin performs stricter cgroup name validation
</details>

cgroups.plugin: fixes to cgroup path validation

---

src/go/go.mod
src/go/plugin/go.d/collector/dnsquery/collector.go
src/go/plugin/go.d/collector/dnsquery/collector_test.go
src/go/plugin/go.d/collector/dnsquery/config_schema.json
src/go/plugin/go.d/collector/dnsquery/init.go
src/go/plugin/go.d/collector/dnsquery/metadata.yaml
src/go/plugin/go.d/collector/dnsquery/resolvconf.go

feat(go.d/dnsquery): support system DNS servers from /etc/resolv.conf

---

src/claim/cloud-status.c
src/claim/cloud-status.h

- Add a new "connecting" status on the agent splash screen (Agent to cloud link)
- The agent awaits a context checkpoint command to report "online" status

Add a new agent status when connecting to the cloud

---

src/database/sqlite/sqlite_health.c
src/database/sqlite/sqlite_metadata.c
src/web/api/v2/api_v2_claim.c

- Remove duplicate statement prepare in alert processing that results in memory leak (a few Kb)
- Finalize statement after chart metadata store (memory leak)
- Handle `CLOUD_STATUS_CONNECTING` state in `agent_can_be_claimed()` function

Fix memory leak

---

src/database/engine/journalfile.c
src/database/engine/journalfile.h
src/database/engine/pagecache.c
src/database/engine/rrdengine.c
src/database/engine/rrdengine.h

- Use a single worker thread to write data to both the datafile and journalfile.
Currently, separate worker threads handle these writes, using callbacks for coordination.
This PR updates the process to perform all writes within a single worker thread.

Improve data write

---

src/go/plugin/go.d/collector/nvme/collector_test.go
src/go/plugin/go.d/collector/nvme/exec.go

Fixes https://github.com/netdata/netdata/issues/19500#issuecomment-2635157839
</details>

fix(go.d/nvme): add missing "/dev/" prefix to device path for v2.11

---

.github/data/distros.yml
.github/workflows/docker.yml

This should improve build times at least a little bit.
Requires confirmation of 64-bit POWER8+ builds being successful in CI and taking less time than they currently do on the master branch.

Switch from x86 to ARM build host for POWER8+ builds.

---

src/collectors/systemd-journal.plugin/systemd-journal-watcher.c
src/libnetdata/dictionary/dictionary-item.h

Still valid bugs:
If a destination directory has more than one symlinks to it, deleting 1 of the symlinks stops watching the directory and all its files. So, the watcher does not keep a count of references. It just executes events without knowing that there are multiple links to the same destination.

fix incomplete implementation of journal watcher

---

src/database/engine/journalfile.c
src/database/engine/rrdengine.c

- Add missing call to `uv_fs_cleanup` to release resources
- Reorder release of the WAL when writing journal data

Free resources where writing datafile extents

---

src/database/contexts/worker.c

fix heap-use-after-free while loading contexts

dequeue from hub before deleting contexts

---

netdata.spec.in

The build is failing there at the moment with LTO enabled, so just disable LTO for it.
CI passes for openSUSE packaging job.

Disable LTO for openSUSE package builds.

---

src/database/sqlite/sqlite_metadata.c

- Close database when an error is detected and we will exit. 
This will prevent an attempt to access the database again during shutdown.

Close database if we encounter error during startup

---

src/claim/claim_id.c
src/claim/cloud-status.c
src/registry/registry.c

use the parent claim id when agent is claimed but not connected to netdata cloud

Allow indirect access when agent is claimed, but offline (indirect cloud connectivity)

---

src/database/sqlite/sqlite_aclk.c

- Detect if node has been removed and do not register on agent restart
- Setup claimed parent - child
- Config on parent should be 
```
[db]  
cleanup ephemeral hosts after = off
```
- Start both, notice child connecting to parent and cloud
- Stop child
- Run `netdatacli remote-stale-node ALL_NODES` 
- Notice child being unregistered -- eg. should not be in api/v3/node_instances
- Restart parent -- notice the child is registered again
- Repeat with this PR
- Child should not be registered after parent restart

Do not register removed node on agent restart

---

.github/data/distros.yml

The 24.04 runner images are apparently having serious stability issues, especially for ARM runners, and these are likely causing most of our current CI issues.
CI actually works correctly on this PR.

Switch to Ubuntu 22.04 runner images for CI build jobs.

---

src/libnetdata/log/nd_log-common.h
src/libnetdata/log/wevt_netdata_mc_generate.c

Since libunwind support (stack traces in logs), all windows event logs generated by netdata, lost their message.
This fixes it.

fix windows logs

---

system/systemd/netdata.service.in
system/systemd/netdata.service.v235.in

Add `Group=netdata` to the systemd unit file to grant the netdata user access to `/run/netdata/`. This allows netdata's IPC socket to be stored in a dedicated directory instead of `/tmp`.
</details>

add Group=netdata to systemd unit file

---

packaging/installer/kickstart.sh

- On all RHEL versions, correctly pull the EPEL release package from the Fedora project, since RHEL does not include it in their repos.
- On RHEL 9 and newer, as well as clones, enable the CodeReady Builder repo, which is apparently required there to make EPEL work at all, before installing EPEL.
Requires manual testing on affected systems.

Fix native package installation on RHEL.

---

src/go/go.mod
src/go/otel-collector/exporter/journaldexporter/go.mod

Fixes this issue
```
5-02-19T21:23:40.8732140Z -- Minimum required Go version determined to be 1.23.6
2025-02-19T21:23:40.9516263Z CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
2025-02-19T21:23:40.9517157Z   Could NOT find Go: Found unsuitable version "1.23.4", but required is at
2025-02-19T21:23:40.9517744Z   least "1.23.6" (found /mingw64/lib/go/bin/go.exe)
```
I have no idea why there is 1.23.4. I see that `Set Up Go` installs 1.23.6
<details><summary>screenshot</summary>
<details>
</details>

build: change go.mod version to 1.23.4 to fix win ci builds

---

.github/data/distros.yml

The Ubuntu 22.04 ARM runners seem to have serious performance issues when it comes to using QEMU’s userspace emulation.
n/a

Switch back to x86 hosts for POWER8+ builds.

---

src/go/plugin/go.d/collector/mysql/charts.go
src/go/plugin/go.d/collector/mysql/collect.go

The most of `Innodb_os_log_*` status variables was removed in Mariadb 10.8 except `InnoDB_os_log_written`. It still may be useful to collect it.
see https://mariadb.com/kb/en/innodb-status-variables/#innodb_os_log_written

chore(go.d/mysql): InnodbOSLogIO in MariaDB >= 10.8

---

src/collectors/debugfs.plugin/module-libsensors.c

Fixes https://github.com/netdata/netdata/issues/19742

pass NULL to sensors_init() when the standard files exist in /etc/

---

docs/netdata-agent/configuration/using-custom-ca-certificates-with-netdata.md

A custom CA certificate is needed when dealing with any TLS configuration for Netdata that involves a private CA for the remote endpoint (such as connecting to an on-premises Cloud instance that is using an internally-issued TLS certificate).
This document does not get into the details of all the specific cases where this may be needed, it’s only intended to cover _how_ to do it, with the intent that other parts of the documentation that cover the cases where it may be needed will link to this page instead of having to individually replicate the instructions.
n/a
I have tagged @shyamvalsan and @sashwathn for review on this because I specifically want their feedback on the document since this will primarily be relevant to business customers and they are the primary people interacting with …

Add documentation outlining how to use custom CA certificates with Netdata.

---

packaging/makeself/jobs/99-makeself.install.sh
packaging/makeself/makeself.lsm
src/database/engine/pdc.c
src/health/notifications/alarm-notify.sh.in

It seems there is some problem with static installs and muslc with a certain log that triggers a SIGSEGV inside a `vsprintf()`.
```
Thread 1 "netdata" received signal SIGSEGV, Segmentation fault.
0x00eda680 in memchr (src=src@entry=0x3c, c=c@entry=0, n=n@entry=2147483647) at src/string/memchr.c:17
17	src/string/memchr.c: No such file or directory.
(gdb) bt
#0  0x00eda680 in memchr (src=src@entry=0x3c, c=c@entry=0, n=n@entry=2147483647) at src/string/memchr.c:17
#1  0x00edae3c in strnlen (s=s@entry=0x3c <error: Cannot access memory at address 0x3c>, n=n@entry=2147483647) at src/string/strnlen.c:5
#2  0x00ed8d40 in printf_core (f=f@entry=0xbeff55f0, fmt=fmt@entry=0xf36934 "DBENGINE: metric '%s' %s page of type %u from %ld to %ld (now %ld), update every %u, page length %zu, entries %zu …
```

Fix SIGSEGV on static installs due to dengine log

---

src/go/plugin/go.d/collector/k8s_state/charts.go
src/go/plugin/go.d/collector/k8s_state/collect.go
src/go/plugin/go.d/collector/k8s_state/collector.go
src/go/plugin/go.d/collector/k8s_state/collector_test.go
src/go/plugin/go.d/collector/k8s_state/discover_cronjob.go
src/go/plugin/go.d/collector/k8s_state/discover_job.go
src/go/plugin/go.d/collector/k8s_state/discover_kubernetes.go
src/go/plugin/go.d/collector/k8s_state/discover_node.go
src/go/plugin/go.d/collector/k8s_state/discover_pod.go
src/go/plugin/go.d/collector/k8s_state/metadata.yaml
src/go/plugin/go.d/collector/k8s_state/resource.go
src/go/plugin/go.d/collector/k8s_state/state.go
src/go/plugin/go.d/collector/k8s_state/update_cronjob_state.go
src/go/plugin/go.d/collector/k8s_state/update_job_state.go
src/go/plugin/go.d/collector/k8s_state/update_state.go

This PR adds basic CronJob monitoring by tracking jobs by their status:
- **Complete**: Successfully finished jobs.
- **Failed**: Jobs that terminated with errors.
- **Running**: Currently active jobs.
- **Suspended**: Jobs paused by the system.
Note that the metrics history depth is controlled by the CronJob's `successfulJobsHistoryLimit` and `failedJobsHistoryLimit settings`, which determine how many completed/failed jobs are retained in the system.
</details>

improvement(go.d/k8s_state): collect cronjobs

---

src/daemon/daemon-status-file.c
src/daemon/daemon-status-file.h
src/daemon/daemon.c
src/daemon/daemon.h
src/daemon/libuv_workers.c
src/daemon/main.c
src/libnetdata/exit/exit_initiated.c
src/libnetdata/exit/exit_initiated.h
src/libnetdata/os/process_path.c
src/libnetdata/signals/signals.c
src/libnetdata/signals/signals.h
src/libnetdata/threads/threads.c
src/libnetdata/threads/threads.h

status file improvements 12

---

src/streaming/stream-receiver.c
src/streaming/stream-sender.c

When the receiver or the sender are disconnected due to stale replication, do not use their structures after the disconnection.

fix memory corruption in streaming

---

src/daemon/buildinfo.c
src/daemon/daemon.c
src/daemon/main.c
src/daemon/signal-handler.c
src/database/engine/journalfile.c
src/database/rrdhost.c
src/libnetdata/log/nd_log-internals.c
src/libnetdata/log/nd_log.h
src/libnetdata/spawn_server/spawn_server_nofork.c
src/streaming/stream-sender-api.c

Detect memory leaks

---

src/daemon/daemon-shutdown.c
src/daemon/main.c
src/daemon/signal-handler.c
src/database/contexts/api_v2_contexts_alerts.c
src/database/rrd.c
src/database/rrdhost-system-info.c
src/database/rrdhost-system-info.h
src/database/rrdhost.c
src/database/sqlite/sqlite_aclk.c
src/plugins.d/pluginsd_parser.c
src/streaming/stream-receiver-connection.c

Fix LSAN and memory leaks

---

src/database/engine/rrdengine.c

- Make sure the datafile is acquired before calculating first_time_s

Acquire datafile for deletion before calculating retention

---

CMakeLists.txt
packaging/cmake/Modules/NetdataGoTools.cmake
src/go/otel-collector/CMakeLists.txt
src/go/otel-collector/release-config.yaml.in

This adds initial integration of the new OpenTelemetry collector into our build system. Currently, this is disabled by default and must be explicitly enabled at build time with `-DENABLE_PLUGIN_OTEL=On`. It also does not include any packaging integration, and can only be used with local builds currently.
Additionally:
- The build configuration used by the OpenTelemetry Collector Builder is generated at runtime from a template file to ensure that:
- The version is matched to the the Netdata agent version being used for the build.
- The collector is built in debug mode if the CMake build type is set to `Debug`.
- The same version of the Go toolchain that has been selected by the build infrastructure is also used for building the collector (this mostly matters because it improves package …

Integrate OpenTelemetry collector build into build system.

---

src/daemon/commands.c
src/daemon/daemon-shutdown.c
src/database/contexts/rrdcontext.c
src/database/engine/cache.c
src/database/engine/cache.h
src/database/rrdhost.c
src/database/rrdhost.h
src/database/sqlite/sqlite_aclk_alert.c
src/libnetdata/dictionary/dictionary-unittest.c
src/libnetdata/dictionary/dictionary.c
src/web/server/h2o/http_server.c
src/web/server/web_client.c

Finding leaks No 2

---

src/database/rrdhost.c

rrdhost machine guid should not be linked, but copied to the dictionary, so that delayed destruction of the dictionary will not introduce heap-use-after-free

rrdhost name fix heap-use-after-free

---

src/go/otel-collector/CMakeLists.txt

SSIA
Requires confirmation that the build now works with the OTel collector enabled.

Fix typo in otel collector build infra.

---

src/daemon/daemon-status-file.c
src/daemon/daemon-status-file.h
src/database/rrdhost-system-info.c

store status file in /var/lib/netdata, not in /var/cache/netdata

---

src/database/contexts/api_v1_contexts.c
src/database/contexts/api_v2_contexts.c
src/database/contexts/instance.c
src/database/contexts/internal.h
src/database/contexts/query_target.c
src/database/rrdlabels.c
src/database/rrdlabels.h

Fixed the following bug.
The idea is that the rrdlabels pointer given to queries should never be freed while there is retention for the instance, since it may be used in queries.
```
=================================================================
==2291354==ERROR: AddressSanitizer: heap-use-after-free on address 0x6030039480a0 at pc 0x55a47794abdd bp 0x7f28b57ff4d0 sp 0x7f28b57ff4c8
READ of size 1 at 0x6030039480a0 thread T63
#0 0x55a47794abdc in spinlock_lock_with_trace /usr/src/netdata-ktsaou.git/src/libnetdata/locks/spinlock.c:22
#1 0x55a476170bd0 in rrdlabels_get_value_to_buffer_or_unset /usr/src/netdata-ktsaou.git/src/database/rrdlabels.c:454
#2 0x55a4753c5fea in query_group_by_make_dimension_key /usr/src/netdata-ktsaou.git/src/web/api/queries/query.c:2461
#3 0x55a4753cb131 in …
```

fix contexts labels to avoid clearing the rrdlabels pointer

---

src/collectors/cgroups.plugin/cgroup-charts.c
src/health/health_variable.c
src/libnetdata/datetime/rfc3339.c

fix crashes identified by sentry

---

src/collectors/macos.plugin/macos_fw.c

Fixes #19842
```
[plugin:macos:iokit]
```
</details>

improvement(macos.plugin): add options to filter net ifaces and mountpoints

---

src/database/engine/pagecache.c
src/database/sqlite/sqlite_metadata.c

- Free all METASYNC thread resources when the agent shuts down
- Add check for invalid extent index when processing metric data pages

Release memory on shutdown - detect invalid extent in journal files

---

src/libnetdata/exit/exit_initiated.h

Minor change in the classification of `EXIT_REASON_SIGABRT` and `EXIT_REASON_ALREADY_RUNNING`.
- `EXIT_REASON_SIGABRT` was incorrectly classified as deadly signal, but it is triggered by fatal conditions in the code, so it should be an abnormal condition and not a deadly signal.
- `EXIT_REASON_ALREADY_RUNNING` was missed from all classifications.

SIGABRT and already running are fatal conditions

---

CMakeLists.txt

@Ferroin we have the issue that many stack traces we get are useless, like this:
```
#0 _ZdaPv+0x375AB5
#1 <unknown>
#2 _ZdaPv+0x39F8D0
#3 _ZdaPv+0x3A191C
#4 _ZdaPv+0x2E6FFA
#5 _ZdaPv+0x174BD4
#6 _ZdaPv+0x1760B6
#7 _ZdaPv+0x17A315
#8 _ZdaPv+0x2F4FE3
#9 pthread_condattr_setpshared+0x513
#10 __xmknodat+0x230
```
The above is from binpkg-deb.
I read that there are a couple of options that significantly affect libunwind's ability to resolve functions names:
`-rdynamic` I had added this for backtrace(), now I am adding it always.
`-funwind-tables` I read this may have the compiler generate unwind tables.
Both of these options should not have any effect on performance. They may affect Netdata binary loading (when it starts) and the size of the binary, but there is no runtime impact.
There is …

add stack trace information to the compiler and linker

---

src/daemon/daemon-shutdown-watcher.c
src/daemon/daemon-shutdown.c
src/daemon/daemon-status-file.c
src/daemon/sentry-native/sentry-native.c
src/libnetdata/common.h
src/libnetdata/log/nd_log.c

3 minor changes:
These are not code/functionality changes and are safe to merge before release.

change log priorities on agent-events

---

src/daemon/daemon-shutdown.c
src/daemon/daemon-status-file.c
src/daemon/daemon-status-file.h
src/daemon/libuv_workers.c
src/daemon/sentry-native/sentry-native.c
src/daemon/signal-handler.c
src/daemon/signal-handler.h
src/database/engine/cache.c
src/libnetdata/log/nd_log-stacktrace.c
src/libnetdata/log/nd_log.h
src/libnetdata/threads/threads.c

- positive = the agent is gracefully restarting without errors
- negative = the agent is repeatedly crashing

daemon-status-18

---

packaging/installer/methods/packages.md
packaging/repoconfig/CMakeLists.txt
packaging/repoconfig/deb.changelog
packaging/repoconfig/netdata.repo.dnf
packaging/repoconfig/rpm.changelog

- Update key fingerprint in documentation.
- Indirectly re-sync key for APT by rebuilding packages (the package build pulls the key from the public URL, and it’s already deployed there on the server).
- Update the key URLs for the RPM packages so that package signing works until new packages are published with the new signing keys (the change will be reverted with another update once the next stable release has been published).
n/a

Update DEB/RPM package signing key info.

---

src/collectors/cups.plugin/cups_plugin.c
src/collectors/freebsd.plugin/plugin_freebsd.c
src/collectors/nfacct.plugin/plugin_nfacct.c
src/collectors/perf.plugin/perf_plugin.c
src/collectors/xenstat.plugin/xenstat_plugin.c
src/daemon/commands.c
src/daemon/daemon-service.c
src/daemon/daemon-shutdown.c
src/daemon/daemon-shutdown.h
src/daemon/daemon-status-file.c
src/daemon/daemon-systemd-watcher.c
src/daemon/main.c
src/daemon/signal-handler.c
src/daemon/winsvc.cc
src/database/engine/cache.c
src/database/engine/page.c
src/health/rrdcalc.c
src/libnetdata/exit/exit_initiated.c
src/libnetdata/exit/exit_initiated.h
src/web/server/web_client.c

do not recurse cleanup on shutdown

---

src/daemon/config/netdata-conf-backwards-compatibility.c
src/daemon/daemon-shutdown.c
src/daemon/pulse/pulse-daemon-memory.c
src/web/api/web_api_v1.c

- Fix compilation without dbengine support
- Fix compilation when FSANITUZE_ADDRESS and dbengine is off
- Fix warning when sentry is not enabled
Fixes #19901

Fix compile without dbengine

---

.github/workflows/build.yml
.github/workflows/release.yml

- Auto-retry changelog generation during the release process if it fails. This is a known flaky step that almost always works after 1-2 retries, so just automate retrying it.
- Cut the timeout on static builds to 150 minutes. This lets us actually get multiple retries in on them when things are running slow or have hung, and still gives plenty of time for the build to happen (current successful builds take at most 100 minutes).
n/a

Improve CI reliability by allowing for better retry behavior.

---

src/libnetdata/spawn_server/spawn_server_nofork.c

Align cmsgbuf to size_t to avoid unaligned memory access.

---

src/database/sqlite/sqlite_aclk.c

- During agent startup, make sure the ACLK sync thread initialization is complete before continuing.
- Additional input validation on queued commands

Make sure ACLK sync thread completes initialization

---

src/web/server/web_client.c

do not return back the absolute filename of files requested via the web server

do not expose web server filenames

---

src/database/engine/pdc.c

Adjust the max page validation to 5120 bytes. This will fix occasional errors like the following
```
DBENGINE: metric '45abdf91-e431-4c56-a6e6-cb3a942db8b8' loaded invalid page of type 2 from 1742197011 to 1742198034 (now 1742296131), update every 1, page length 5120, entries 1024
```

Fix max_page_length calculation for GORILLA_32BIT page type

---

src/database/rrdhost.c
src/database/sqlite/sqlite_aclk.c
src/database/sqlite/sqlite_metadata.c
src/database/sqlite/sqlite_metadata.h

- Add additional checks to prevent crash during shutdown 
- Allocate event loop in the stack
- Use explicit initialized variable instead of relying on the allocation of the loop
- Add check on every command submission
- Remove query counters from logs in debug mode (only timings are reported)

Metadata event loop code cleanup

---

CMakeLists.txt

It was backwards due to an oversight.
Needs manual confirmation that everything works.

Fix logic for libbacktrace enablement in CMakeLists,txt

---

packaging/makeself/jobs/15-libucontext.install.sh
packaging/makeself/jobs/20-libunwind.install.sh

We preferentially use libbacktrace on most platforms, so don’t waste time or resources building libunwind on them.

Don't build libunwind in static builds when it's not needed.

---

src/aclk/aclk.c
src/claim/cloud-status.c
src/claim/cloud-status.h
src/daemon/daemon-status-file.c
src/daemon/daemon-status-file.h
src/daemon/main.c
src/daemon/sentry-native/sentry-native.c
src/libnetdata/log/nd_log-stacktrace.c
src/registry/registry.c
src/web/api/v2/api_v2_claim.c
src/web/server/web_server.c
src/web/server/web_server.h

daemon status 22

---

src/database/sqlite/sqlite_functions.c
src/database/sqlite/sqlite_functions.h

- When under memory pressure the sqlite library will be able to release non-essential memory allocations (eg. caches)
- `int freed_bytes = sqlite_release_memory(bytes)` can be used to attempt to free `bytes` 
According to the sqlite docs, bytes actually freed, may be more or less than the amount requested.
- If compiled with NETDATA_INTERNAL_CHECKS, agent with release memory during shutdown in 1MB chunks

Enable interface to release sqlite memory

---

packaging/cmake/Modules/NetdataBacktrace.cmake

Without this, the way our build works causes it to get updated and rebuilt (and thus trigger relinking of multiple parts of the agent) when `cmake --install` is called, which in turn makes installs take much longer.
n/a

Use UPDATE_DISCONNECTED mode for libbacktrace.

---

src/database/engine/datafile.h

Open cache needs about twice the size of a single data file in memory.
So, we are now limiting the max data file to 1GiB.

set max datafile size to 1GiB

---

src/database/sqlite/sqlite_metadata.c

- Do not use a precompiled statement to store host info and metadata
This may result in a precompiled statement in the main thread that can cause a crash during shutdown

Fix random crash during shutdown

---

src/web/api/queries/weights.c

- This will make sure when running with sanitizer we don't get a report for memory leak (no-op otherwise)

Release memory when calculating metric correlations

---

src/database/engine/rrdengine.c
src/database/sqlite/sqlite_aclk.c
src/database/sqlite/sqlite_health.c
src/database/sqlite/sqlite_metadata.c

- Eliminate additional cases in alarm_log and contexts API calls when alerts are included in the payload
- Remove more precompiled statements
- Add additional checks in ACLK synchronization thread 
- Avoid datafile rotation when journal indexing is in progress

Improve shutdown and datafile rotation

---

src/daemon/status-file.c

daemon status 24c

---

packaging/tools/agent-events/.gitignore
packaging/tools/agent-events/build.sh
packaging/tools/agent-events/run.sh
packaging/tools/agent-events/server.go
packaging/tools/agent-events/server_test.go

The key problem is duplicate requests received from cloudflare.
Now the web server uses the ephemeral_id of the JSON object to deduplicate requests received. It caches hashes of it for 30min.

agent-events: add deduplicating web server

---

src/daemon/machine-guid.c
src/daemon/status-file.c

blacklist the pattern of github runners machine-guids, that where leaking into static builds.

blacklist leaked machine guids

---

packaging/makeself/jobs/81-netdata-runtime-check.sh

Prevent the contents of `/var/lib/netdata` and `/var/cache/netdata` from leaking from the CI environment to the install image.
Requires manual testing to confirm

Properly clean up install paths after runtime checks in static builds.

---

src/libnetdata/memory/nd-mmap.c

- Simplify file creation when building a v2 journal file
- Use ftruncate instead of lseek / write / ftruncate
- Make sure file is closed on fruncate failure
- Verify size after ftruncate

Additional checks then creating a v2 journal file

---

packaging/installer/kickstart.sh

Add information about the `--offline-install-source option` of kickstart.sh
when running `kickstart --help` the option is described
</details>

kickstart.sh: add missing option --offline-install-source to USAGE

---

src/daemon/pulse/pulse-db-dbengine-retention.c
src/database/engine/rrdengine.c
src/database/engine/rrdengine.h

- Enhance protection of the structures used in disk space calculation.
- Prevent queuing the database rotate opcode on every extent write.

Improve estimated disk space usage for data file rotation

---

src/daemon/libuv_workers.c
src/daemon/libuv_workers.h
src/database/sqlite/sqlite_aclk.c
src/database/sqlite/sqlite_metadata.c

- Add a close callback to improve handle management and replace duplicate code
- Check if the handle is closing before attempting a close otherwise this can lead to a crash

Fix ACLK synchronization fatal on shutdown

---

src/daemon/signal-handler.c
src/daemon/status-file.c
src/libnetdata/log/nd_log-stacktrace.c
src/libnetdata/log/nd_log.c
src/libnetdata/log/nd_log.h

daemon status 26d

---

src/collectors/proc.plugin/proc_net_dev.c
src/collectors/proc.plugin/proc_net_dev_renames.c
src/collectors/proc.plugin/proc_net_dev_renames.h

SIGSEGV:
```
#0 <unknown> [0x7F642DF1562F]
#1 <unknown> [0x7F642B8BE079]
#2 <unknown> [0x7F642B8E9178]
#3 vsnprintfz [0xADA803] (/src/libnetdata/libnetdata.c:68)
#4 snprintfz [0xADA803] (/src/libnetdata/libnetdata.c:81)
#5 netdev_rename [0xA3C249] (/src/collectors/proc.plugin/proc_net_dev.c:407)
#6 netdev_rename_this_device [0xA470B3] (/src/collectors/proc.plugin/proc_net_dev.c:470)
#7 do_proc_net_dev [0xA470B3] (/src/collectors/proc.plugin/proc_net_dev.c:1058)
#8 netdev_main [0xA493A2] (/src/collectors/proc.plugin/proc_net_dev.c:1722)
#9 nd_thread_starting_point [0xAFB6F9] (/src/libnetdata/threads/threads.c:362)
#10 <unknown> [0x7F642DF0DEA4]
#11 <unknown> [0x7F642B96FB2C]
#12 <unknown> [0xFFFFFFFFFFFFFFFF]
```
Looking at line 407 in proc_net_dev.c, that points to:
```c
snprintfz(buffer, …
```

added checksum to detect corruption in netdev rename tasks

---

src/collectors/proc.plugin/proc_net_dev.c
src/collectors/proc.plugin/proc_net_dev_renames.c
src/collectors/proc.plugin/proc_net_dev_renames.h

SIGSEGV:
```
#0 <unknown> [0x7F642DF1562F]
#1 <unknown> [0x7F642B8BE079]
#2 <unknown> [0x7F642B8E9178]
#3 vsnprintfz [0xADA803] (/src/libnetdata/libnetdata.c:68)
#4 snprintfz [0xADA803] (/src/libnetdata/libnetdata.c:81)
#5 netdev_rename [0xA3C249] (/src/collectors/proc.plugin/proc_net_dev.c:407)
#6 netdev_rename_this_device [0xA470B3] (/src/collectors/proc.plugin/proc_net_dev.c:470)
#7 do_proc_net_dev [0xA470B3] (/src/collectors/proc.plugin/proc_net_dev.c:1058)
#8 netdev_main [0xA493A2] (/src/collectors/proc.plugin/proc_net_dev.c:1722)
#9 nd_thread_starting_point [0xAFB6F9] (/src/libnetdata/threads/threads.c:362)
#10 <unknown> [0x7F642DF0DEA4]
#11 <unknown> [0x7F642B96FB2C]
#12 <unknown> [0xFFFFFFFFFFFFFFFF]
```
This is use-after-free.
The problem appears when multiple netdev renames …

fix cgroup netdev renames

---

CMakeLists.txt
packaging/tools/agent-events/server.go
src/daemon/sentry-native/sentry-native.c
src/daemon/status-file-dedup.c
src/daemon/status-file-dmi.c
src/daemon/status-file-dmi.h
src/daemon/status-file-product.c
src/daemon/status-file-product.h
src/daemon/status-file.c
src/daemon/status-file.h
src/database/rrdhost-system-info.c
src/libnetdata/inlined.h

daemon status 27

---

.github/scripts/gen-docker-tags.py
.github/scripts/rotate-docker-tags.sh
.github/workflows/docker.yml

This adds new Docker tags for our nightly builds to track prior nightly builds relative to the current one.
The new tags take the form `edge-x` where the `x` is a number that represents how many builds previous to the current build the tag tracks. For example, `edge-1` is the build just prior to the current nightly version, while `edge-3` is three builds prior to the current nightly build.
These tags are rotated every time a nightly build is published. This approach was chosen to avoid the significant complexity that would be required to properly clean up old nightly build tags if we were tagging by actual nightly version instead of tagging relative to the current build.
The current configuration will track the 4 most recent nightly builds.
The special tag `edge-0` is a new alias for the …

Add Docker tags for the last few nightly builds.

---

src/database/engine/rrdengine.c

- Release memory structure during DBENGINE shutdown / destroy semaphore

Cleanup during shutdown

---

src/database/engine/rrdengine.c

During shutdown, do not try to create journal v2 files as this will slow down the shutdown process.

Do not try to index jv2 files during shutdown

---

src/collectors/windows.plugin/perflib-hyperv.c
src/collectors/windows.plugin/windows_plugin.c

Figure 1: Chart showing the metric responsible for the issue.
This PR address the issue:
```sh
AE_FATAL_STACK_TRACE
#0 daemon_status_file_save_twice_if_we_can_get_stack_trace [0x1005CFE24] (/src/daemon/status-file.c:1073)
#1 daemon_status_file_register_fatal [0x1005CFBA6] (/src/daemon/status-file.c:1129)
#2 nd_log_fatal_hook [0x10069B0B5] (/src/libnetdata/log/nd_log.c:135)
#3 nd_logger_log_fields [0x10069B0B5] (/src/libnetdata/log/nd_log.c:154)
#4 nd_logger [0x1006982D7] (/src/libnetdata/log/nd_log.c:342)
#5 netdata_logger_fatal [0x1006AD19F] (/src/libnetdata/log/nd_log.c:515)
#6 rrdset_create_custom [0x10076C9F9] (/src/database/rrdset-index-id.c:409)
#7 rrdset_create [0x1005EB93A] (/src/database/rrdset-index-id.h:41)
#8 rrdset_create_localhost [0x1005EB93A] …
```

Address Chart name (Windows Hyper V)

---

src/database/sqlite/sqlite_aclk.c

- Add correct callback data when cancelling a timer

Fix memory allocation for timer callback data when cancelling a timer

---

.github/scripts/gen-matrix-docker.py
.github/scripts/gen-matrix-static.py
.github/workflows/build.yml
.github/workflows/docker.yml

They will still be run if changes are made to the infrastructure used for those specific build types.
The detection can be overridden to force running using the `run-ci/non-native` label.
n/a

Skip non-native builds in CI on PRs in most cases.

---

.github/scripts/gen-docker-tags.py

It’s currently breaking publishing of Docker images.
n/a

Fix typo in .github/scripts/gen-docker-tags.py

---

docs/netdata-agent/versions-and-platforms.md

Even though we document that static builds can be used on platforms that
are not, or no longer, supported, we do not explain how to _switch_ from
a native package to a static build. This PR addresses that.

Document switching from a native package to a static build

---

src/daemon/status-file.c

daemon status 27d

---

src/aclk/aclk_util.c
src/aclk/aclk_util.h

- Fix ACLK reconnect delay calculation to return values in milliseconds if a min and max seconds has been returned by the environment call.

Fix ACLK Backoff Timeout Logic

---

src/collectors/windows.plugin/windows_plugin.c
src/daemon/main.c
src/daemon/unit_test.h
src/libnetdata/os/windows-perflib/perflib-names.c
src/libnetdata/os/windows-perflib/perflib.h

This commit addresses two key issues with Windows performance counter registry handling:
1. Fixes crashes due to improper registry data parsing:
- Added comprehensive validation of registry data structure
- Added bounds checking to prevent buffer overruns
- Added validation of ID string conversion
- Improved error logging for malformed registry entries
2. Optimizes memory usage with Judy arrays:
- Replaced fixed-size array with memory-efficient Judy array
- Memory usage now scales with actual data rather than highest ID
- Eliminated arbitrary limit on registry ID values
- Added proper resource cleanup on shutdown
Added unit tests to verify functionality and demonstrate memory efficiency
with sparseness statistics. Run with: -W perflibnamestest

Fix Windows registry name crashes

---

src/daemon/commands.c

Reorders commands in the help output to match the typical execution sequence.
</details>

netdatacli remove/mark stale, swap order in help output

---

.github/scripts/docker-test.sh
.github/scripts/pkg-test.sh
.github/workflows/build.yml
packaging/makeself/jobs/89-buildinfo.install.sh
packaging/windows/compile-on-windows.sh

This adds logging of the output of `netdata -W buildinfo` for most of our build jobs in CI:
- For static builds this is done during the build step.
- For Windows builds, this is also done during the build step, but it is not working consistently right now (I plan to dig into that in a separate PR).
- For macOS builds, Docker builds, and DEB/RPM builds this is done during the build test step.
- In all cases, the data is in a log group called ‘Netdata buildinfo’ that is collapsed by default.
CI jobs pass on this PR and include the information outlined in the summary.

Dump Netdata buildinfo during CI.

---

src/collectors/diskspace.plugin/plugin_diskspace.c
src/collectors/proc.plugin/plugin_proc.c
src/collectors/proc.plugin/plugin_proc.h
src/collectors/proc.plugin/sys_devices_pci_aer.c
src/collectors/statsd.plugin/statsd.c
src/daemon/daemon-shutdown.c
src/daemon/dyncfg/dyncfg-inline.c
src/daemon/dyncfg/dyncfg.c
src/daemon/dyncfg/dyncfg.h
src/database/pattern-array.c
src/database/pattern-array.h
src/database/rrdhost.c
src/health/health_prototypes.c
src/health/rrdcalc.c
src/health/rrdcalc.h
src/plugins.d/plugins_d.c
src/plugins.d/plugins_d.h
src/plugins.d/pluginsd_parser.c

Extracted from: https://github.com/netdata/netdata/pull/20106
- cleanup on exit for many modules
- plugins.d threads are now joinable
- fix memory leaks in diskspace plugin
- fix strings leak in pattern-arrays

fix cleanup and exit and memory leaks

---

src/libnetdata/dictionary/dictionary-internals.h
src/libnetdata/dictionary/dictionary-item.h

- Fix compilation when using only FSANITIZE_ADDRESS without NETDATA_INTERNAL_CHECKS

Fix compilation when using FSANITIZE_ADDRESS

---

src/collectors/windows.plugin/perflib-mssql.c

Fix issue:
```c
#8 do_mssql_locks [0x100548CA0] (/src/collectors/windows.plugin/perflib-mssql.c:892)
#9 dict_mssql_charts_cb [0x100534C17] (/src/collectors/windows.plugin/perflib-mssql.c:1422)
#10 dictionary_sorted_walkthrough_rw [0x100537EAA] (/src/libnetdata/dictionary/dictionary-traversal.c:247)
#11 do_PerflibMSSQL [0x10053D71C] (/src/collectors/windows.plugin/perflib-mssql.c:1439)
#12 win_plugin_main [0x1007BB961] (/src/collectors/windows.plugin/windows_plugin.c:196)
#13 nd_thread_starting_point [0x1005F7DD0] (/src/libnetdata/threads/threads.c:362)
``` 
1.  Check CI
2. Compile build locally
3. Make an installer.
4. Install on host running MSSQL Server.
</details>

Fix Locks (Windows Locks)

---

src/collectors/cgroups.plugin/sys_fs_cgroup.c

Follow-up to #20155
Ran a single systemd-nspawn container. Modified the filters till there was a single entry.
</details>

improvement(cgroups): improve systemd-nspawn filter for default

---

src/collectors/apps.plugin/apps_os_macos.c
src/collectors/apps.plugin/apps_plugin.h
src/collectors/timex.plugin/plugin_timex.c
src/daemon/static_threads_macos.c
src/database/rrddim.h
src/libnetdata/buffer/buffer.h
src/libnetdata/os/adjtimex.c
src/libnetdata/os/adjtimex.h
src/libnetdata/os/uuid_generate.c
src/ml/ml_kmeans.cc

With these fixes `netdata` can be built on macOS 10.6.8.
There should be no effects on other systems. No new functionality is implemented, this only addressed build errors.
P. S. If someone could help improving fallbacks, it will be great.

Some fixes for macOS < 11

---

src/health/health_notifications.c

- Fix crash in repeating alerts
- In the case the alert was not actually queued

Fix repeating alert crash

---

src/daemon/signal-handler.c

Fix this:
```
AE_EXIT_CAUSE
fatal on exit
AE_FATAL_FAULT_ADDRESS
0x0
AE_FATAL_FUNCTION
execute_command
AE_FATAL_SIGNAL_CODE
SIGABRT/SI_TKILL
AE_FATAL_STACK_TRACE
#0 <unknown> [0x7FBFFBE5B04F]
#1 <unknown> [0x7FBFFBEA9EEC]
#2 <unknown> [0x7FBFFBE5AFB1]
#3 <unknown> [0x7FBFFBE45471]
#4 <unknown> [0x7FBFFC61A201]
#5 execute_command [0x5589D20CB28B] (/src/daemon/commands.c:586)
#6 process_triggered_signals [0x5589D20CA536] (/src/daemon/signal-handler.c:240)
#7 nd_process_signals [0x5589D20CA78E] (/src/daemon/signal-handler.c:298)
#8 main [0x5589D1F791A4] (/src/daemon/main.c:1174)
#9 <unknown> [0x7FBFFBE46249]
#10 <unknown> [0x7FBFFBE46304]
#11 <unknown> [0x5589D20B83A0]
#12 <unknown> [0xFFFFFFFFFFFFFFFF]
```
Reloading health or exiting are ignored while we are exiting.

ignore maintenance signals on exit

---

src/daemon/config/netdata-conf-global.c
src/daemon/config/netdata-conf-global.h
src/daemon/main.c

We see a lot of crashes on `work_dispatch()`, during startup. These crashes happen because the system cannot handle the number of libuv threads we configure (cpus x 6).
In cases the system has a small memory (e.g. 1 - 3 GiB of RAM), but a high number of CPUs (e.g. 23-64), the amount of memory requested just the threads stacks exceeds the total amount of memory. In these cases, glibc calls `abort()` making the program to exit.
The fix in this patch takes into account the total and available system memory when configuring libuv:
1. It starts with cpus x 6
2. But then checks the total and available RAM.
3. It takes MIN(5% of total, 10% of available) and based on this it limits the max number of threads that libuv will use.
The number of libuv threads cannot be less than 16 (as before).

limit the max number of threads based on memory too

---

src/libnetdata/locks/waitq.c

BEFORE THESE CHANGES ON MY DEV MACHINE:
```
=== Performance Summary (Million locks/sec) ===
Lock Type           1        2        4        8       16       32       64
------------------------------------------------------------------------------
Mutex           86.47    22.15    20.00    13.30    11.62    11.02    11.99
RWLock          54.52    11.23     9.73     7.09     5.73     0.71     0.75
Spinlock       121.25   115.18   110.27   107.83   103.61    98.21    90.24
RW Spinlock     71.67    66.57    63.50    61.32    58.84    55.51    50.87
WaitQ           39.01    38.65    38.76    35.43    32.22    28.25    23.71  <<< THIS
```
WITH THESE CHANGES:
```
=== Performance Summary (Million locks/sec) ===
Lock Type           1        2        4        8       16       32       64 …
```

add fast path to waitq

---

src/database/sqlite/sqlite_functions.c
src/database/sqlite/sqlite_functions.h
src/database/sqlite/sqlite_metadata.c

- Switch a message to warning instead of error
- Configure a busy timeout for database operations

Add a default busy timeout

---

src/database/engine/journalfile.c
src/database/engine/journalfile.h

- Use one spinlock to access the mmap and v2 data (instead of two -- in most cases they were acquired in pairs)

Use one spinlock to access v2 and mmap related data

---

src/web/api/http_auth.c
src/web/api/queries/weights.c

Small fixes

---

src/daemon/analytics.c
src/daemon/analytics.h
src/daemon/main.c

- The analytics thread is now started even when disabled to support data population for the `/api/v1/info` endpoint. Data is collected locally but not sent when analytics is disabled.

Enable analytics data collection 

---

src/daemon/config/netdata-conf-global.c

- Let the user override the default stack size. 
This is used to estimate the maximum number of threads we can use based on the available memory

Let the user override the default stack size

---

src/daemon/libuv_workers.c
src/database/sqlite/sqlite_metadata.c

- Remove uv_sleep that causes compilation failure
Fixes #20242

Fix build issue on old distros

---

src/daemon/libuv_workers.c
src/daemon/libuv_workers.h
src/database/engine/rrdengine.c
src/database/engine/rrdengine.h

If a journal indexing job can't be scheduled immediately, set a flag to trigger it after the database rotation job completes.
This ensures more predictable indexing and helps avoid increased memory usage in the database engine due to cache buildup.

Schedule journal file indexing after database file rotation

---

src/libnetdata/socket/nd-poll.c

- Disable epoll for now -- (random high cpu usage observed in kernels 6.14.4+) 
https://lists.linaro.org/archives/list/linux-stable-mirror@lists.linaro.org/message/6ADQXH5GBYZKRWOE3RHPFAO7BOOXMYO7/
Fixes #20266.

Switch to poll from epoll

---

src/collectors/windows.plugin/metadata.yaml
src/collectors/windows.plugin/perflib-mssql.c

When running on busy servers, or computer with slow memory, it was observed gaps on charts. To address this issue, we are isolating the queries in a thread.
This PR also fixes a small issue when running on SQL Express. Previously, if a variable was not initialized, strange values could appear.
Update metdata.
This PR also does small cleanup and renames to keep a pattern.
1. Compile this branch.
2. Install it on a host running SQL server
3. Configure your netdata.conf as  shown in metadata..
This PR was tested with SQL Server 2022 and SQL Server Express 2019.
</details>

Improve MSSQL (Part III)

---

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_generic-tcp.yaml

@ilyam8 here maybe the `tcpActiveOpens` need unit `"{SYN-SENT}"` (and so on)? Not sure, so didn't change to that.

_generic-tcp.yaml pass

---

src/plugins.d/pluginsd_parser.c

Vnodes don't have dyncfg.
This should fix
```c
#0 <unknown> [0x7F6C1A5C772F]
#1 dictionary_set_and_acquire_item_advanced [0x555B7852B1EF] (/src/libnetdata/dictionary/dictionary.c:690)
#2 rrd_function_add [0x555B781C2F73] (/src/database/rrdfunctions.c:246)
#3 dyncfg_host_init [0x555B78619778] (/src/daemon/dyncfg/dyncfg-tree.c:287)
#4 pluginsd_host_define_end.constprop.0 [0x555B78619778] (/src/plugins.d/pluginsd_parser.c:229)
#5 parser_execute [0x555B7814E8DB] (/src/plugins.d/pluginsd_parser.c:1314)
#6 parser_action [0x555B7814E8DB] (/src/plugins.d/pluginsd_parser.h:229)
#7 pluginsd_process [0x555B7816403D] (/src/plugins.d/pluginsd_parser.c:1216)
#8 pluginsd_worker_thread [0x555B7814044B] (/src/plugins.d/plugins_d.c:162)
#9 nd_thread_starting_point [0x555B7854EE77] …
```

dont init dyncfg for vnode

---

docs/security-and-privacy-design/netdata-cloud-security.md

Added the SOC 2 Type 1 attestation blog link (https://www.netdata.cloud/blog/soc2-type1/) under :::info at the top of the page.
This placement immediately reassures the reader without cluttering the main text.

SOC 2 cloud doc update

---

packaging/cmake/Modules/NetdataEBPFCORE.cmake
packaging/cmake/Modules/NetdataEBPFLegacy.cmake
packaging/cmake/Modules/NetdataLibBPF.cmake
src/collectors/windows.plugin/metadata.yaml
src/collectors/windows.plugin/perflib-mssql.c
src/daemon/daemon-shutdown-watcher.c
src/daemon/daemon.c
src/daemon/dyncfg/dyncfg.c
src/daemon/libuv_workers.c
src/daemon/libuv_workers.h
src/database/engine/rrdengine.c
src/database/engine/rrdengine.h
src/database/rrdfunctions-inflight.c
src/database/rrdfunctions.h
src/database/rrdhost.c
src/database/rrdset-collection.c
src/database/sqlite/sqlite_metadata.c
src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/sysinfo.go
src/go/plugin/go.d/agent/module/job.go
src/plugins.d/pluginsd_dyncfg.c
src/plugins.d/pluginsd_functions.c
src/plugins.d/pluginsd_parser.c
src/streaming/stream-parents.c
src/streaming/stream-sender-api.c

1. dont init dyncfg for vnode (#20324)
1. Update libbpf (#20316)
1. Improve MSSQL (Part III) (#20230)
1. replace newline control chars with spaces in system info (#20301)
1. fix(go.d): sanitize vnode labels before creating vnode (#20293)
1. plugins dyncfg is always on localhost (#20312)
1. Improve metasync shutdown (#20303)
1. Improve user transition log messages (#20308)
1. fix use after free of streaming current parent (#20305)
1. fix heap-use-after-free in plugins.d inflight functions (#20304)
1. Minor fixes (#20263)
1. Schedule journal file indexing after database file rotation (#20264)

Patch release 2.5.2

---

src/daemon/libuv_workers.c
src/database/sqlite/sqlite_aclk.c
src/database/sqlite/sqlite_metadata.c

- Fix shutdown timeout calculation for metadata thread
- Adjust get_worker function to set the request data before returning worker
- Remove checks for get_worker failure (always returns worker)
- Variable renames for clarity

Code cleanup and improvements

---

src/libnetdata/socket/nd-poll.c

Reverts #20273.
The bug is fixed in kernel [6.14.8](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.14.8) (commit 7631dca012593c95d36199082546a24a0058fc50).
</details>

Switch back to epoll from poll

---

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_generic-ups.yaml

@ilyam8 there could be family `UPS/Input/Lines` or `UPS/Lines/Input`. I went with the first one.

SNMP: _generic-ups.yaml

---

src/database/engine/datafile.c
src/database/engine/datafile.h
src/database/engine/journalfile.c
src/database/engine/rrdengine.c
src/database/engine/rrdengine.h

- Reduce number of scheduled jobs, check if opcodes already pending
- Pause indexing if quota is exceeded and allow db rotation to run
- Allow indexing to process at least one file
- Add datafile locking and allow indexing to run alongside with datafile rotation again

Improve datafile rotation and indexing

---

src/collectors/apps.plugin/README.md
src/collectors/apps.plugin/apps_groups.conf
src/collectors/apps.plugin/apps_pid_match.c
src/libnetdata/string/string.c
src/libnetdata/string/string.h

apps.plugin documentation and grouping matches improvements

---

src/database/engine/rrdengine.c

- Reduce bsearch dataset after every match
- Detect when all metrics have been processed to avoid scanning all datafiles
- Detect agent shutdown during retention calculation 
- Cancel retention calculation to speedup shutdown

Improve retention calculation after datafile deletion

---

CMakeLists.txt

- Rename `nd-mcp` to `nd-mcp.exe` on windows

Rename nd-mcp on windows

---

src/streaming/stream-connector.c

When shutdown is initiated, adjust the connector default timeout from 1000ms to 250ms to improve shutdown responsiveness
- Do agent shutdown on a child node
Notice messages similar to
```
SERVICE CONTROL: waiting for the following 1 services [ ] to exit: 'SNDR-CN[0]' (871733)
SERVICE CONTROL: waiting for the following 1 services [ ] to exit: 'SNDR-CN[0]' (871733)
```
- Install PR and retry

Adjust stream connector timeout during agent shutdown

---

src/daemon/dyncfg/dyncfg-intercept.c
src/database/rrdfunctions.h
src/plugins.d/pluginsd_functions.c
src/streaming/stream-sender-execute.c
src/web/api/v1/api_v1_config.c
src/web/api/v1/api_v1_function.c
src/web/api/web_api.c
src/web/api/web_api.h

The issue occurred when web_client was freed while plugin threads were still trying to access it through progress callbacks. The progress callback stored a pointer to web_client, which became invalid after the connection was closed.
Solution: Modified the progress callback signature to include the transaction UUID as a parameter, eliminating the need to store web_client pointers.
Changes:
- Updated rrd_function_progress_cb_t typedef to include nd_uuid_t *transaction
- Modified all progress callback implementations to use the transaction parameter
- Updated all callback invocations to pass the transaction from inflight structures
- Removed web_client pointer dependencies by passing NULL as callback data
This ensures that progress updates only use data that remains valid for the lifetime of …

Fix heap-use-after-free in query progress updates

---

src/registry/registry_db.c
src/registry/registry_internals.h

The registry save functions were accumulating byte counts from fprintf() calls, which could exceed INT_MAX on large registries, causing the dictionary_walkthrough_read() to return negative values and fail.
This fix:
- Changes save functions to return item counts (1 per saved item) instead of accumulated byte counts
- Adds exponential backoff (60s, 120s, 240s... up to 1 hour) to prevent repeated save attempts after failures
- Tracks consecutive failures to implement the backoff mechanism
- Returns 0 on success instead of -1 from registry_db_save()

Fix registry save integer overflow and add failure backoff

---

src/go/plugin/go.d/collector/snmp/charts.go
src/go/plugin/go.d/collector/snmp/collect_profiles.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collect_scalar.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collect_table.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector_test.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/table_cache.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/table_cache_test.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/utils.go

The table cache converts repeated SNMP walks into efficient GET operations:
- First collection: Full walk, cache structure and tags
- Subsequent collections: GET metrics only, use cached tags
- Per-table TTL with jitter prevents simultaneous refreshes
</details>

improvement(go.d/ddsnmp): add table metrics and tags caching optimization

---

packaging/cmake/patches/apply-patches.sh

When trying to process a patch that has already been applied, `patch` will return a non-zero exit code. Additionally, there is no option to override this behavior and simply ignore patches that are already applied.
Given this, restructure our patching script so that it just ignores patches that have already been applied, since we obviously don’t need to apply them.
Requires testing to confirm the change is working.

Correctly ignore patches that are already applied.

---

.github/data/distros.yml
packaging/PLATFORM_SUPPORT.md
packaging/docker/README.md
packaging/installer/kickstart.sh
packaging/makeself/README.md
packaging/makeself/build-static.sh
packaging/makeself/jobs/10-libucontext.install.sh
packaging/makeself/jobs/82-cpu-arch-check.sh
packaging/makeself/uname2platform.sh

A few years back we started providing static builds and Docker images for 64-bit little-endian POWER8+ hardware under the assumption that they would be of interest for corporate users. Interested corporate users have completely failed to materialize, and these builds (especially the static builds) have persistently been a significantly greater maintenance burden than most other platforms we build for. Additionally, even on the Community plan, we have so few users using these that they look more like a rounding error than actual interest.
Given this, continuing to provide these builds is not worth the time or effort for us at the moment.
If there is significant demand in the future this decision may be revisited.
n/a

Drop POWER8+ builds.

---

src/go/plugin/go.d/collector/snmp/charts.go
src/go/plugin/go.d/collector/snmp/collect_profiles.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddprofiledefinition/metrics.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collect_scalar.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collect_table.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector_test.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/utils.go
src/go/plugin/go.d/collector/snmp/ddsnmp/load.go
src/go/plugin/go.d/collector/snmp/ddsnmp/metric.go
src/go/plugin/go.d/collector/snmp/ddsnmp/transform.go
src/go/plugin/go.d/config/go.d/snmp.profiles/default/mikrotik-router.yaml

This PR adds a Go template-based transformation system for SNMP metrics, allowing dynamic metric processing directly within SNMP profile definitions. This feature is particularly useful for handling heterogeneous SNMP tables where different rows represent fundamentally different types of data (e.g., MikroTik sensor tables with temperature, voltage, fan speed, etc. in the same table).
Previously, SNMP profiles had limited ability to handle tables where:
- Different rows require different metric names, units, and families
- Values need different scaling factors based on row type
- Some rows need value mappings (e.g., status indicators)
- Metric names need to be dynamically constructed based on row data
The workaround involved special tags (`_unit`, `_metric_suffix`) that required …

improve(go.d/snmp): add Go template-based metric transformations for SNMP profiles

---

src/go/plugin/go.d/collector/snmp/charts.go
src/go/plugin/go.d/collector/snmp/collect_profiles.go
src/go/plugin/go.d/config/go.d/snmp.profiles/default/_generic-if.yaml
src/go/plugin/go.d/config/go.d/snmp.profiles/default/mikrotik-router.yaml

This PR introduces support for non-identifying tags in SNMP table metrics by using an underscore (`_`) prefix convention. Tags prefixed with `_` are excluded from metric ID generation but are still included in the metric data (with the prefix removed).
When collecting SNMP table metrics, we generate unique IDs by combining the metric name with all tag values. However, not all tags contribute to the uniqueness of a metric - some are purely descriptive. Including these non-identifying tags in the ID makes it unnecessarily long without adding value.
For example, in interface metrics:
- `interface` tag (e.g., "eth0") - identifying: different interfaces have different metrics.
- `if_type` tag (e.g., "ethernetCsmacd") - descriptive: provides context but doesn't identify unique metrics.

improve(go.d/snmp): dd support for non-identifying tags in table metrics

---

src/database/sqlite/sqlite_functions.c

- Get the lock before checking for the statement pool

Lock before checking the statement pool

---

CMakeLists.txt
netdata-installer.sh
packaging/installer/functions.sh
packaging/makeself/jobs/70-netdata-git.install.sh
src/collectors/systemd-journal.plugin/systemd-journal-fstat.c
src/crates/jf/Cargo.toml

This also adds an option to the `netdata-installer.sh` script to enable it when running that script, called `--internal-systemd-journal`.
Basic testing requires confirming that CI passes on this PR.
Prior to merging this requires additional testing to confirm that the systemd-journal plugin is built and included in the static builds.

Enable Rust-based journal file reader in static builds.

---

src/database/sqlite/sqlite_aclk.c
src/database/sqlite/sqlite_db_migration.c
src/database/sqlite/sqlite_functions.c
src/database/sqlite/sqlite_functions.h
src/database/sqlite/sqlite_health.c
src/database/sqlite/sqlite_metadata.c
src/ml/ml.cc

- Ensure the database is valid before executing any commands.
- Update db_execute calls to include an sqlite_rc parameter (currently not used). This will return the actual db error and in future improvements, help refine error handling from the caller.

Additional checks for valid db during db_execute

---

src/database/sqlite/sqlite_aclk.c

- Check that the ACLK sync thread has been properly initialized during shutdown
- This will ensure that the thread exists and completion structure has been initialized

Check that there is a valid thread when performing ACLK sync shutdown

---

integrations/cloud-authentication/metadata.yaml

add "Push Now" as not supported, requested by Okta team.

doc: update SCIM doc

---

src/collectors/apps.plugin/apps_os_windows.c

- Fix windows build  -- no functions from strsafe are used

Fix compilation on windows

---

packaging/windows/netdata.wxs.in

This PR adds the same message we have in our learning page to installer:
2. Build an installer.
3. Execute it and check message in last page.
</details>

Add Screen to Windows installer

---

src/go/plugin/go.d/collector/httpcheck/metadata.yaml

In the documentation `headers_match` is used but it is `header_match`.
</details>

Fix documentation regarding header_match

---

packaging/windows/msys2-dependencies.sh
src/collectors/windows.plugin/README.md
src/collectors/windows.plugin/metadata.yaml
src/collectors/windows.plugin/perflib-mssql.c
src/collectors/windows.plugin/windows_plugin.c
src/daemon/analytics.c

This PR allows users to configure custom update intervals for each monitored service:
Additionally, it fixes timezone detection:
Finally, it modifies documentation and metadata.
1. Compile this PR
2. Make an installer
3. Change your netdata.conf according to documentation setting different `update every` for some threads.
4. Install it.
5. Access dashboard or API and confirm data are correct.
This PR were tested on Windows 11, Windows 2019, and Windows 2022. All threads were tested and they are running as expected.
</details>

Windows Pluging (Freedom to update every)

---

docs/ml-ai/ml-anomaly-detection/ml-accuracy.md
docs/welcome-to-netdata.md

@ktsaou when using `<` and `>` make sure to escape them if they are not some html element. It breaks Learn
This has been deployed on local Learn and it works.

Escape chars on documentation

---

src/plugins.d/pluginsd_parser.c

- Fix the format of the log message

Fix log message format for buffered reader error

---

.github/data/distros.yml

It went EOL upstream on 2025-05-13.
n/a
Closes: #20193

Remove Fedora 40 from CI and package builds.

---

src/web/mcp/mcp-web-client/web/app.js

This small PR adds an early check to ensure the chat exists before proceeding with message handling. It prevents runtime errors caused by referencing an undefined `chat` object when attempting to send a message (in `if (!chat.isSubChat) {` part).

Ensure chat exists before handling message input

---

src/database/engine/rrdengine.c

- Signal that we done in from worker thread instead of the callback

Mark the completion from the worker thread

---

src/collectors/windows.plugin/perflib-network.c

- Set to null after release. Can prevent a double release that can cause a crash

Reset chart variable after release

---

src/collectors/windows.plugin/perflib-mssql.c
src/collectors/windows.plugin/windows_plugin.c
src/collectors/windows.plugin/windows_plugin.h

- Add an optional cleanup function to be called when shutting down of the win_plugin
This will help cleanup additional resources (in this case join the mssql queries helper thread)

Improve thread shutdown handling for MSSQL plugin

---

src/aclk/aclk.c
src/aclk/aclk_otp.c
src/aclk/aclk_proxy.c
src/aclk/aclk_proxy.h
src/aclk/aclk_util.c
src/aclk/aclk_util.h
src/aclk/https_client.c
src/aclk/https_client.h
src/aclk/mqtt_websockets/mqtt_ng.c
src/aclk/mqtt_websockets/mqtt_wss_client.c
src/aclk/mqtt_websockets/mqtt_wss_client.h
src/daemon/commands.c

- Log if a proxy is specified and used in establishing ACLK connection (via proxy ....) or (no proxy)
- Add `ACLK Proxy:` in `netdatacli aclk-state` output (and /api/v1/aclk)

Record proxy information when establishing ACLK

---

src/collectors/windows.plugin/perflib-storage.c

When running current master on different Windows Server it was observer scenarios like this:
In this example, Netdata does not reflect the same data as Windows Exporter. This discrepancy is not directly related to our previous code. Rather, it appears that Microsoft does not expose all files through the API, which can lead to inaccurate results.
This PR improves the situation slightly. However, differences due to temporary files, cache, and rounding can still cause mismatches between the displayed data.
2. Install it on your host.
</details>

Improve Disk Usage Measure (Windows.plugin)

---

src/database/rrdhost-system-info.c
src/database/rrdhost-system-info.h
src/database/sqlite/sqlite_metadata.c

- Add the detected default network interface information to system info and host labels

Add default iface info to host labels

---

src/aclk/aclk.c
src/aclk/mqtt_websockets/mqtt_ng.c
src/daemon/pulse/pulse-network.c
src/daemon/pulse/pulse-network.h

- Add publish latency to the `aclk-state cli` command (and api/v1/aclk) end point. 
This shows latest message publish latency in (usec) based on the publish acknowledgement packet received
Of course more detailed information (histogram chart) is available by enabling extended statistics in the `[pulse]` section of netdata.conf
Example: 
```
ACLK Available: Yes
ACLK Version: 2
Protocols Supported: Protobuf
Protocol Used: Protobuf
MQTT Version: 5
Claimed: Yes
Claimed Id: xxxxxxxxxxxxx
Cloud URL: https://app.netdata.cloud
ACLK Proxy: none
Publish Latency: 121ms 159us
Online: Yes
Reconnect count: 0
```

Add publish latency to the aclk-state command

---

src/aclk/aclk.c
src/aclk/aclk_query_queue.c
src/aclk/aclk_rx_msgs.c
src/aclk/mqtt_websockets/common_public.h
src/aclk/mqtt_websockets/mqtt_ng.c
src/aclk/mqtt_websockets/mqtt_wss_client.c
src/daemon/pulse/pulse-network.c

- Add periodic cleanup of pending pubacks instead of waiting for buffer full or ping response
- Fix lock order to prevent deadlocks
- Add additional statistics in aclk-state (pending puback messages)
```
Last Connection Time: 2025-08-07 10:54:38
Last Connection Time + 3 PUBACKs received: 2025-08-07 10:54:40
Received Cloud MQTT Messages: 5
MQTT Messages Confirmed by Remote Broker (PUBACKs): 6
Pending PUBACKS: 0
```
- Graph number of pending puback messages (extended pulse statistics) (`netdata.network_aclk_send_queue`)
Sample:

Aclk improvements

---

src/collectors/windows.plugin/perflib-mssql-queries.h
src/collectors/windows.plugin/perflib-mssql.c

Some of the MSSQL charts were displaying a value of zero because Perflib was not returning accurate results.
This PR addresses the issue as part of the ongoing effort to fix https://github.com/netdata/netdata/issues/20123.
Master Branch:
This PR:
1. Compile this branch.
2. Install it on a host running Microsoft SQL Server.
3. Verify that the metrics are no longer zero.
</details>

Fix MSSQL Charts

---

.github/data/distros.yml

Expected upstream release date is 2025-08-09.
Fixes: #20773

Add Debian 13 to CI and package builds.

---

src/go/plugin/go.d/collector/snmp/ddsnmp/ddprofiledefinition/metrics.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddprofiledefinition/profile_definition.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddprofiledefinition/virtual_metrics.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector_table.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector_table_test.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector_vmetrics.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector_vmetrics_test.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collectors_meta.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/metric_builder.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/table_row_processor.go
src/go/plugin/go.d/collector/snmp/ddsnmp/metric.go
src/go/plugin/go.d/collector/snmp/ddsnmp/profile.go
src/go/plugin/go.d/config/go.d/snmp.profiles/default/_std-if-mib.yaml

Adds support for virtual metrics in SNMP profiles, allowing aggregation of table metrics into single scalar values. This allows to create summary metrics like total traffic across all interfaces without additional SNMP queries.
**Note**: This is a simple implementation that supports sum aggregation only. It does not support status distribution metrics (e.g., counting interfaces by status: up: 3, down: 4) - only numeric aggregation is available.
</details>

feat(go.d/ddsnmp): add metric aggregation support for SNMP profiles

---

.github/scripts/platform-impending-eol.py

Fixes #20789
Fixes #20790
Fixes script failure when checking EOL status for newly released distributions (e.g., Debian 13) where the API returns boolean values instead of date strings.
The script was failing with a `ValueError` when calling `datetime.date.fromisoformat()` on boolean values returned by the endoflife.date API. This occurs for:
- Newly released distributions where `eol: false` (no EOL date set yet)
- Distributions with `extendedSupport: true` (LTS available but date not determined)
Added explicit type checking and handling for boolean values in both `eol` and `extendedSupport` fields:
- **`eol: false`** → Not impending (still actively supported)
- **`eol: true`** → Impending (conservative approach for unusual case)
- **`extendedSupport: false`** → Failure (unexpected when …

ci: handle boolean values in EOL API responses for newly released distros

---

src/aclk/mqtt_websockets/common_public.h
src/aclk/mqtt_websockets/mqtt_ng.c
src/daemon/pulse/pulse-network.c

This PR introduces several new charts to the internal 'pulse' telemetry system to provide deeper insight into ACLK performance, including detailed latency and queue wait time statistics. All new timing charts are in milliseconds.

feat(aclk): Add detailed pulse metrics for ACLK telemetry

---

src/go/plugin/go.d/config/go.d/zfspool.conf

Adds the Ubuntu-specific zpool binary path (`/usr/sbin/zpool`) to the zfspool collector configuration. This ensures the collector can properly locate the zpool binary on Ubuntu systems.
</details>

improve(go.d/zfspool): add Ubuntu zpool binary path to config

---

src/go/plugin/go.d/collector/snmp/collect.go
src/go/plugin/go.d/collector/snmp/collector.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collectors_meta.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collectors_meta_test.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/utils.go
src/go/plugin/go.d/collector/snmp/ddsnmp/profile.go
src/go/plugin/go.d/collector/snmp/ddsnmp/profile_test.go
src/go/plugin/go.d/config/go.d/snmp.profiles/default/aruba-mobility-controller.yaml
src/go/plugin/go.d/config/go.d/snmp.profiles/default/cisco-legacy-wlc.yaml
src/go/plugin/go.d/config/go.d/snmp.profiles/default/ruckus-unleashed.yaml

Fixes critical issues in SNMP profile matching and metadata collection that were causing incorrect device identification and metadata assignment.
**Problem**: The SNMP collector wasn't properly handling sysobjectid-specific metadata. When profiles defined both general metadata and sysobjectid-specific metadata, the more specific values weren't being applied correctly. This meant devices couldn't have model-specific metadata without creating separate profiles.
**Solution**: Fixed metadata collection logic to process sysobjectid-specific metadata before base metadata, ensuring specific values take precedence over generic defaults.
**Example**: cisco-asa.yaml supports 80+ ASA models, but couldn't specify individual model names - all devices would report generic metadata instead of their …

fix(go.d/ddsnmp): correct profile matching, metadata precedence, and OID handling

---

.github/scripts/docker-test.sh

The CI script did not exit with a non-zero code when `runtime-check.sh` failed.
Although the script was executed, the `if` branch ended with a successful command (`echo`), so the overall job exited with 0 and masked the failure.
</details>

ci: fix docker-test.sh handling to fail on error

---

src/go/plugin/go.d/config/go.d/snmp.profiles/default/mikrotik-router.yaml

When querying SFP module temperatures via SNMP (OID: 1.3.6.1.4.1.14988.1.1.19.1.1.6), MikroTik devices return a sentinel value of `4294967168` (near max uint32) for empty SFP slots instead of a valid temperature reading. This causes incorrect temperature data in monitoring.
Added a transform that detects these invalid values (anything > 4294967000) and converts them to 0, indicating no module present.
</details>

fix(go.d/snmp): handle invalid SFP temperature readings for empty slots

---

docs/exporting-metrics/README.md
docs/exporting-metrics/enable-an-exporting-connector.md
src/exporting/README.md
src/exporting/prometheus/README.md

designed for optimised human and llm scanning, @Ancairon please place all exporting connectors under enable an exporting connector (makes intuitive sense and will declutter initial clickdown)

Improve exporting documentation clarity and structure

---

src/collectors/cgroups.plugin/cgroup-name.sh.in

KubeVirt’s virt-launcher pods include helper containers that don’t represent the VM workload:
- `volumerootdisk` — containerDisk helper
- `guest-console-log` — serial console tailer
Only the `compute` container runs QEMU and reflects the VM’s CPU/IO. Including the helpers creates noisy entries and can mislead per-container views. This PR makes `k8s_get_kubepod_name()` ignore those helpers by returning 3 (same “skip/ignore” semantics already used elsewhere).
We **hard-code skipping** these two containers because we assume they are never of interest for monitoring.
</details>

improve(cgroups): skip KubeVirt helper containers in virt-launcher pods

---

docs/.map/README.md
docs/.map/map.csv

This was requested by @ktsaou (https://github.com/netdata/learn/issues/2542) and it makes sense, as it provides everyone with the ability to publish and change stuff (before only I was doing it), as it also allows for one PR to make changes, and not two.
I will send an internal message with the notice that now any PR that adds a new docs file must also touch the map, so we can review both at once.
after this, https://github.com/netdata/learn/pull/2550 should be merged.

Migrate the map from Learn repo to netdata/netdata

---

integrations/templates/setup.md

This PR improves the consistency and usability of collector documentation:
1. **Added a new "via UI" subsection** under **Configuration** for go.d collectors. It explains how to create and manage data-collection jobs directly from the Netdata web interface.
2. **Restructured the Configuration** section to follow a clearer sequence:
- Options
- via UI
- via File
- Examples
This makes the setup flow more logical (options first, then methods of applying them) and helps users quickly choose between UI or file-based configuration.
</details>

docs(go.d): add UI configuration instructions and restructure Configuration section

---

integrations/schemas/shared.json
integrations/templates/setup.md
src/go/plugin/go.d/collector/snmp/metadata.yaml

This PR improves the presentation of configuration options in collector documentation by introducing grouping:
- Adds a new `group` field for options in `metadata.yaml`.
- Updates the Jinja template to render a single table with a "Group" column when at least one option has a group.
- If no options define a group, the table remains unchanged (no extra column).
- The **first option in each group shows the group name in bold**.
- Subsequent options in the same group leave the group column blank.
- **Ordering of groups is defined by the order of options in** `metadata.yaml`, giving full control to the integration author.
- Ensures tables remain compact and consistent in width while making groups visually distinct.
As a proof of concept, the SNMP collector options have been updated with …

docs: improve config options table with grouped section headers

---

src/go/plugin/go.d/agent/module/job.go

This change updates Job.Cleanup() to avoid sending a HOST line for virtual nodes that have a stale configuration label (_node_stale_after_seconds). Previously, cleanup always emitted HOST <guid>, which incorrectly kept vnodes marked as "active".
</details>

chore(go.d): skip HOST for vnodes during Cleanup with stale label

---

src/go/go.mod
src/go/go.sum

Temporarily switching to a forked version of gosnmp to fix critical SNMPv3 authentication issues with UniFi APs.
Our SNMP collector intermittently fails when polling UniFi APs due to incorrect handling of unauthenticated REPORT PDUs in the upstream gosnmp library. The collector gets stuck in a retry loop with stale engine times, receiving "incoming packet is not authentic" errors.
This is a temporary change until the [fix](https://github.com/gosnmp/gosnmp/pull/532) is merged upstream.
</details>

chore(go.d): use forked gosnmp to fix SNMPv3 REPORT handling for UniFi APs

---

src/go/plugin/go.d/collector/snmp/ddsnmp/ddprofiledefinition/virtual_metrics.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector_vmetrics.go
src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector_vmetrics_test.go

This PR extends the virtual metrics system with support for **alternatives**.  
Many SNMP devices expose both 64-bit counters in `ifXTable` and 32-bit counters in `ifTable`.  
Until now, profiles could only declare a single source set, which meant that ifXTable-based virtual metrics would fail on devices that only had ifTable.
- New `alternatives` field in `VirtualMetricConfig`.
- Each alternative is defined as a list of sources.
- At runtime, the collector picks the **first alternative whose sources produced data**.
- All subsequent alternatives are ignored once a winner is found.
- Parent aggregator emits metrics using its configured name and chart meta,
while sourcing values from the selected child aggregator.
- Grouped/per_row rules (same-table enforcement, group key construction) …

improve(go.d/ddsnmp): add alternatives support for virtual metrics

---

docs/realtime-monitoring.md

- Fixed MDX compilation errors that were preventing the Learn documentation from building
- Replaced '<5%' with 'Less than 5%' and '<200' with 'Less than 200'
The MDX parser was interpreting '<5' and '<200' as the start of JSX elements, causing compilation to fail with:
```
Error: MDX compilation failed for file "/docs/welcome-to-netdata/real-time-monitoring.mdx"
Cause: Unexpected character `5` (U+0035) before name, expected a character that can start a name
```
Changed the text to use 'Less than' instead of the '<' symbol to avoid MDX parsing issues.

Fix MDX parsing errors in realtime-monitoring.md

---

docs/.map/map.csv

- Fix duplicate 'Top Consumers' and 'top-consumers' entries in the documentation ToC
- Change learn_rel_path from 'root' to 'Top Consumers' (self-referential) following the same pattern as 'AI & ML' category
The documentation was showing two entries:
- 'Top Consumers' at the root level
- 'top-consumers' auto-generated from the folder structure
Updated map.csv to use the self-referential pattern where a category has its learn_rel_path set to itself, preventing Docusaurus from creating duplicate entries.
This follows the established pattern used by other categories like 'AI & ML'.

Fix duplicate ToC entries for Top Consumers

---

src/go/plugin/go.d/collector/snmp/collect.go
src/go/plugin/go.d/collector/snmp/config.go
src/go/plugin/go.d/collector/snmp/config_schema.json
src/go/plugin/go.d/collector/snmp/ddsnmp/profile.go
src/go/plugin/go.d/collector/snmp/ddsnmp/profile_test.go
src/go/plugin/go.d/collector/snmp/testdata/config.json
src/go/plugin/go.d/collector/snmp/testdata/config.yaml

This PR adds a new configuration option, `manual_profiles`, to the SNMP collector.
**Problem**:
- Some rare devices (e.g. certain printers) do not provide a sysObjectID, making it impossible to apply SNMP profiles automatically. Until now, these devices could not benefit from profile-based metric collection.
**Solution**:
- Added `manual_profiles` config option (array of profile names).
- Profile names should be given without file extensions (e.g. `generic-device`, not `generic-device.yaml`).
- When sysObjectID is missing and no automatic match is possible, the collector falls back to applying the profiles specified in `manual_profiles`.
- If both sysObjectID matching and `manual_profiles` are unavailable, no profiles are applied. …

improve(go.d/snmp): add `manual_profiles` option

---

src/database/engine/mrg-internals.h
src/database/sqlite/sqlite_aclk.c
src/database/sqlite/sqlite_metadata.c

- During startup give priority to vnode context load
- Make sure vnode context is before continuing
- Fix a race condition during metric deletion

Context loading priority to vnodes

---

docs/.map/map.csv
docs/netdata-agent/configuration/using-custom-ca-certificates-with-netdata.md

The [existing documentation on configuring custom CA certificates](https://github.com/netdata/netdata/blob/master/docs/netdata-agent/configuration/using-custom-ca-certificates-with-netdata.md) was missing from Learn. Adding this to the map file so it is included like its sibling documents.

Add documentation on using custom CA certificates to Learn

---

src/go/plugin/go.d/collector/ping/prober.go
src/go/plugin/go.d/collector/snmp/charts.go
src/go/plugin/go.d/collector/snmp/collect.go
src/go/plugin/go.d/collector/snmp/collector.go
src/go/plugin/go.d/collector/snmp/config_schema.json
src/go/plugin/go.d/collector/snmp/init.go
src/go/plugin/go.d/collector/snmp/metadata.yaml

This PR enables ping metrics collection by default for the SNMP collector.
- **Feature**: Ping probing is now on by default, improving visibility into device reachability and latency without requiring explicit configuration.
- **Chore**: Internal refactoring and cleanup (method restructuring, error handling improvements) to keep the codebase more maintainable.
No changes are required in existing configs unless ping probing should be explicitly disabled.
</details>

feat(go.d/snmp): enable ping by default

---

src/go/plugin/go.d/collector/ping/prober.go
src/go/plugin/go.d/collector/snmp/collect.go
src/go/plugin/go.d/collector/snmp/collector.go
src/go/plugin/go.d/collector/snmp/collector_test.go
src/go/plugin/go.d/collector/snmp/config.go
src/go/plugin/go.d/collector/snmp/config_schema.json
src/go/plugin/go.d/collector/snmp/metadata.yaml
src/go/plugin/go.d/collector/snmp/testdata/config.json
src/go/plugin/go.d/collector/snmp/testdata/config.yaml

This PR introduces a new `ping_only` configuration option for the SNMP collector.
New option:
- `ping_only` (boolean, default: false)
- When enabled, the collector collects only ICMP round-trip time metrics during Collect().
- SNMP is still used during Check() and vnode setup to query sysInfo and profile metadata required for Virtual Node creation and labeling.
- SNMP profile metrics are skipped during the periodic Collect() loop.
</details>

feat(go.d/snmp): add `ping_only` option

---

packaging/cmake/Modules/NetdataLibBPF.cmake

In 64-bit architectures other than x86_64, libbpf by default [installs libbpf.a in /usr/lib64](https://github.com/netdata/libbpf/blob/02bdeb7a2c2e7cb2c9cecb125527a9c5a6bbf139/src/Makefile#L88) instead of /usr/lib, which netdata requires. This is fixed by expliciting making them the same.
Probably [enable eBPF plugin on platforms other than x86_64](https://github.com/netdata/netdata/blob/4ed7d239c49e56432cb99cc9ff2368abfe4c24e9/packaging/build-package.sh#L68)?
Users are not affected by this change.
</details>

Fix libbpf.a build path

---

packaging/windows/netdata.wxs.in

The Netdata installer failed to stop the Netdata service during installation. It also did not raise errors or provide feedback about this failure.
This PR addresses these issues by modifying the service management mechanism.
1. Install Netdata version 2.7.1.
2. Compile this branch.
3.  Run the installer. You will receive a warning, which is expected. For the specific features we are working on, `ServiceConfig` functions correctly.
4. Open Task Manager and search for netdata.
5. Install this branch. You will now observe that the installer displays warnings and successfully terminates the Netdata software.
6. Let Netdata run for a short while, and then run the installer again. You will see that it is faster now. …

Improve installer (Windows)

---

src/database/engine/cache.c
src/database/engine/journalfile.c
src/database/engine/pagecache.c
src/database/engine/pagecache.h
src/database/engine/pdc.c
src/database/engine/rrdengine.c
src/database/engine/rrdengine.h

-  Use datafile block numbers instead of offsets
- Reduce internal structure size (improved performance, reduced memory use)

Use datafile block pos

---

packaging/cmake/Modules/NetdataIBMPlugin.cmake

This should resolve issues with libraries not being found when trying to run the IBM plugin.
Requires manual testing to confirm the issue is resolved.

Properly include client compoents for IBM MQ libraries.
