src/cli/README.md
=> improve netdatacli docs

src/go/plugin/go.d/modules/snmp/entnum/lookup.go
It is needed for #18500. Apparently, we can get a vendor/company using these PENs.
</details>
=> go.d snmp add private enterprise numbers mapping

src/go/plugin/go.d/modules/snmp/charts.go, src/go/plugin/go.d/modules/snmp/collect.go, src/go/plugin/go.d/modules/snmp/collect_sys_info.go, src/go/plugin/go.d/modules/snmp/entnum/lookup.go, src/go/plugin/go.d/modules/snmp/snmp_test.go
=> go.d/snmp: add "organization" label (vnode)

src/go/plugin/go.d/agent/module/job.go, src/go/plugin/go.d/modules/snmp/collect.go, src/go/plugin/go.d/modules/snmp/collect_sys_info.go
=> go.d snmp handle multiline sysDescr

src/go/plugin/go.d/agent/vnodes/vnodes.go, src/go/plugin/go.d/modules/snmp/collect_sys_info.go, src/go/plugin/go.d/modules/snmp/init.go
=> go.d add vnode guid validation

src/go/plugin/go.d/modules/snmp/collect.go
=> go.d snmp fix vnode host labels

src/go/plugin/go.d/modules/snmp/charts.go, src/go/plugin/go.d/modules/snmp/collect.go
=> go.d snmp change label name organization->vendor

src/go/plugin/go.d/modules/typesense/metadata.yaml
=> go.d typesense: fix name in meta

docs/dashboards-and-charts/alerts-tab.md, docs/dashboards-and-charts/anomaly-advisor-tab.md, docs/developer-and-contributor-corner/collect-apache-nginx-web-logs.md, docs/netdata-agent/backup-and-restore-an-agent.md, docs/netdata-agent/configuration/common-configuration-changes.md, packaging/installer/methods/ansible.md, packaging/maintainers/README.md, src/aclk/mqtt_websockets/README.md
@Ancairon we have a lot of broken links/unresolved header references. This PR fixes just a few. I don't have enough patience to fix them need your help.
</details>
=> fix some docs issues

src/go/plugin/go.d/README.md, src/go/plugin/go.d/config/go.d.conf, src/go/plugin/go.d/config/go.d/nginxunit.conf, src/go/plugin/go.d/config/go.d/sd/docker.conf, src/go/plugin/go.d/config/go.d/sd/net_listeners.conf, src/go/plugin/go.d/modules/init.go, src/go/plugin/go.d/modules/nginxunit/charts.go, src/go/plugin/go.d/modules/nginxunit/collect.go, src/go/plugin/go.d/modules/nginxunit/config_schema.json, src/go/plugin/go.d/modules/nginxunit/metadata.yaml, src/go/plugin/go.d/modules/nginxunit/nginxunit.go, src/go/plugin/go.d/modules/nginxunit/nginxunit_test.go, src/go/plugin/go.d/modules/nginxunit/testdata/config.json, src/go/plugin/go.d/modules/nginxunit/testdata/config.yaml, src/go/plugin/go.d/modules/nginxunit/testdata/v1.29.1/status.json
=> add go.d/nginxunit

src/go/plugin/go.d/modules/nginxunit/config_schema.json, src/go/plugin/go.d/modules/nginxunit/metadata.yaml, src/go/plugin/go.d/modules/typesense/metadata.yaml
=> go.d fix typesense/nginxunit meta

src/collectors/apps.plugin/apps_groups.conf
Additional monitoring for #12204
</details>
=> add nginx unit to apps_groups.conf

src/go/plugin/go.d/modules/prometheus/charts.go, src/go/plugin/go.d/modules/prometheus/config_schema.json, src/go/plugin/go.d/modules/prometheus/metadata.yaml, src/go/plugin/go.d/modules/prometheus/prometheus.go, src/go/plugin/go.d/modules/prometheus/testdata/config.json, src/go/plugin/go.d/modules/prometheus/testdata/config.yaml
=> go.d/prometheus: add label_prefix config option

src/database/rrd.h, src/database/rrdhost.c
Requested in https://github.com/netdata/netdata/issues/15150#issuecomment-1640553203
</details>
=> add cpu model to host labels

src/collectors/windows-events.plugin/windows-events-publishers.c, src/collectors/windows-events.plugin/windows-events-query.c, src/collectors/windows-events.plugin/windows-events-unicode.h, src/collectors/windows-events.plugin/windows-events.c, src/collectors/windows-events.plugin/windows-events.h
=> Windows Events Log Explorer improvements 3

src/go/plugin/go.d/agent/discovery/sd/discoverer/dockerd/docker.go
=> go.d sd docker: remove unnecessary info message

src/go/plugin/go.d/modules/portcheck/charts.go, src/go/plugin/go.d/modules/portcheck/check_tcp_port.go, src/go/plugin/go.d/modules/portcheck/check_udp_port.go, src/go/plugin/go.d/modules/portcheck/collect.go, src/go/plugin/go.d/modules/portcheck/config_schema.json, src/go/plugin/go.d/modules/portcheck/init.go, src/go/plugin/go.d/modules/portcheck/metadata.yaml, src/go/plugin/go.d/modules/portcheck/portcheck.go, src/go/plugin/go.d/modules/portcheck/portcheck_test.go, src/go/plugin/go.d/modules/portcheck/testdata/config.json, src/go/plugin/go.d/modules/portcheck/testdata/config.yaml
=> go.d/portcheck: add UDP support

src/go/plugin/go.d/modules/portcheck/metadata.yaml
=> go.d portcheck update meta

src/go/plugin/go.d/modules/portcheck/config_schema.json, src/go/plugin/go.d/modules/portcheck/metadata.yaml
=> go.d/portcheck schema add tabs

src/go/plugin/go.d/modules/portcheck/check_tcp_port.go, src/go/plugin/go.d/modules/portcheck/check_udp_port.go, src/go/plugin/go.d/modules/portcheck/collect.go, src/go/plugin/go.d/modules/portcheck/portcheck_test.go
=> go.d/portcheck: update status duration calculation

src/go/plugin/go.d/modules/sensors/collect.go, src/go/plugin/go.d/modules/sensors/metadata.yaml, src/go/plugin/go.d/modules/sensors/sensors_test.go
=> go.d/sensors update meta

src/go/plugin/go.d/modules/sensors/metadata.yaml
=> go.d/sensors fix meta

.github/workflows/build.yml
Also do some general cleanup of the build workflow, including a bit of reorganization.
Needs to be merged to be tested.
=> Publish Windows installers on nightly builds.

src/web/server/web_client.c
This is needed for reliable operation on Windows. Otherwise, when the socket buffer in the kernel gets full, we get an error and we break the socket.
=> WEB SERVER: retry sending data when errno is EAGAIN

src/aclk/aclk.c, src/aclk/aclk_otp.c, src/aclk/aclk_otp.h, src/aclk/https_client.c, src/aclk/https_client.h, src/aclk/mqtt_websockets/mqtt_wss_client.c, src/aclk/mqtt_websockets/mqtt_wss_client.h, src/libnetdata/socket/socket.c, src/libnetdata/socket/socket.h
- Reduce connection timeout and fallback to IPV4 for ACLK connections (#18568)
=> Patch release 1.47.2

.github/workflows/build.yml
This was missed in #18603.
n/a
=> Correctly include Windows installer in release creation.

src/go/plugin/go.d/modules/uwsgi/client.go, src/go/plugin/go.d/modules/uwsgi/collect.go, src/go/plugin/go.d/modules/uwsgi/uwsgi.go, src/go/plugin/go.d/modules/uwsgi/uwsgi_test.go, src/go/plugin/go.d/pkg/socket/client.go
=> go.d/uwsgi: don't write just connect and read

src/go/plugin/go.d/modules/hddtemp/client.go, src/go/plugin/go.d/modules/hddtemp/collect.go, src/go/plugin/go.d/modules/hddtemp/hddtemp.go, src/go/plugin/go.d/modules/hddtemp/hddtemp_test.go
use socket.ConnectAndRead instead of connect; write; read; disconnect.
</details>
=> go.d/hddtemp: connect and read

src/collectors/plugins.d/ndsudo.c
=> Revert "Add ceph commands to ndsudo"

src/go/plugin/go.d/modules/ceph/charts.go, src/go/plugin/go.d/modules/ceph/metadata.yaml, src/health/health.d/ceph.conf
=> go.d/ceph: fix leftovers after #18582

src/go/plugin/go.d/modules/postgres/collect.go, src/go/plugin/go.d/modules/postgres/do_query_global.go, src/go/plugin/go.d/modules/postgres/postgres_test.go, src/go/plugin/go.d/modules/postgres/queries.go
=> go.d/postgres: fix checkpoints query for postgres 17

src/go/plugin/go.d/modules/smartctl/collect.go, src/go/plugin/go.d/modules/smartctl/scan.go
=> go.d/smartctl: fix exit status check in scan

packaging/installer/netdata-updater.sh
Instead of using `/dev/stdout` as a hack to pipe the JSON response from GitHub directly to the JSON parsing tool, just use a temporary file. This should be more portable and reliable, and there should be next to no performance difference.
Needs manual testing to confirm that the modified script works.
Fixes #18642
=> Use temporary file for commit date check.

src/go/plugin/go.d/agent/discovery/sd/pipeline/funcmap.go
=> go.d sd fix sprig funcmap

packaging/check-for-go-toolchain.sh
=> bump go toolchain v1.22.8

src/go/plugin/go.d/modules/postgres/collect.go, src/go/plugin/go.d/modules/postgres/do_query_global.go, src/go/plugin/go.d/modules/postgres/postgres_test.go, src/go/plugin/go.d/modules/postgres/queries.go, src/go/plugin/go.d/modules/smartctl/collect.go, src/go/plugin/go.d/modules/smartctl/scan.go, src/go/plugin/go.d/modules/uwsgi/client.go, src/go/plugin/go.d/modules/uwsgi/collect.go, src/go/plugin/go.d/modules/uwsgi/uwsgi.go, src/go/plugin/go.d/modules/uwsgi/uwsgi_test.go, src/go/plugin/go.d/pkg/socket/client.go
- go.d/uwsgi: don't write just connect and read (#18618)
- go.d/postgres: fix checkpoints query for postgres 17 (#18629)
- go.d/smartctl: fix exit status check in scan (#18635)
=> Patch release 1.47.3

src/aclk/aclk.c, src/aclk/aclk.h, src/aclk/aclk_rx_msgs.c, src/aclk/mqtt_websockets/mqtt_ng.c, src/aclk/mqtt_websockets/mqtt_ng.h, src/aclk/mqtt_websockets/mqtt_wss_client.c, src/claim/claim.c
Configure a PING timeout and check for ping response. 
If none is received then close the connection and reconnect to the cloud.
=> Handle mqtt ping timeouts

src/collectors/apps.plugin/apps_groups.conf
=> apps_groups.conf: add oracledb

src/collectors/python.d.plugin/README.md
we nuked the file, so the link has to go
=> Remove section in python plugin readme

src/go/go.mod, src/go/go.sum
v2.8.21 [fails to build on 32 arch](https://github.com/sijms/go-ora/pull/604).
</details>
=> go.d downgrade go-ora to v2.8.20

src/go/plugin/go.d/modules/nvidia_smi/config_schema.json, src/go/plugin/go.d/modules/nvidia_smi/exec.go, src/go/plugin/go.d/modules/nvidia_smi/metadata.yaml
=> go.d/nvidia_smi: use configured "timeout" in loop mode

src/daemon/system-info.sh
=> fix system-info disk space in LXC

src/collectors/apps.plugin/README.md
- Fix botched merge from #18676.
- Remove stale information.
- Improve wording.
</details>
=> improve apps.plugin readme

packaging/windows/WINDOWS_INSTALLER.md
This updates the documentation, along with some wording recommendations.
I installed Netdata with both functions and tested the uninstall script too.
=> Update windows documentation

src/go/plugin/go.d/modules/sensors/charts.go, src/go/plugin/go.d/modules/sensors/config_schema.json, src/go/plugin/go.d/modules/sensors/metadata.yaml, src/go/plugin/go.d/modules/sensors/sensors.go, src/go/plugin/go.d/modules/sensors/testdata/config.json, src/go/plugin/go.d/modules/sensors/testdata/config.yaml
<details>
<summary>Dyncfg screenshot</summary>
</details>
</details>
=> feat(go.d/sensors): add a config option to update/add sensor label value

src/go/plugin/go.d/modules/coredns/metadata.yaml, src/go/plugin/go.d/modules/httpcheck/metadata.yaml, src/go/plugin/go.d/modules/mongodb/metadata.yaml, src/go/plugin/go.d/modules/openvpn/metadata.yaml, src/go/plugin/go.d/modules/openvpn_status_log/metadata.yaml, src/go/plugin/go.d/modules/oracledb/metadata.yaml, src/go/plugin/go.d/modules/postgres/metadata.yaml, src/go/plugin/go.d/modules/weblog/metadata.yaml
=> fix wrong config file name in go.d/oracledb meta

integrations/templates/setup.md
@ilyam8 simple addition to a file, so that the edit config is not just give without the link to the conf readme
This will produce a mega PR for integrations and hence learn
=> Add link to meta section on integrations template

integrations/cloud-authentication/metadata.yaml
- Adding instructions to configure SCIM in Okta
- Some minor reorganization of the document
=> add instructions to configure SCIM integration in Okta

src/go/logger/journal_linux.go
=> go.d: use lib function to check if stderr connected to journal

src/collectors/windows.plugin/metadata.yaml, src/collectors/windows.plugin/metdata.yaml
This PR is adding missing metadata to the PR https://github.com/netdata/netdata/pull/18494
1. Check CI
2. Check grammar. 
</details>
=> Windows Plugin metadata

src/go/plugin/go.d/modules/portcheck/collect.go
=> fix(go.d/portcheck): stop checking UDP ports on ICMP listen error

src/libnetdata/facets/logs_query_status.h
Adapt to the payload for dashboard v3
=> fix logs POST query payload parsing

src/libnetdata/facets/logs_query_status.h
=> reset the log sources to apply user selection

packaging/windows/installer.nsi
Fixes https://github.com/netdata/netdata/issues/18704
1. Compile the branch
2. Generate the installer.
3. Have a look in texts on screen and finish the installation.
</details>
=> Windows installer (Change descriptions add helping)

src/collectors/perf.plugin/perf_plugin.c
=> fix(perf.plugin): disable if all events disabled during init

packaging/makeself/bundled-packages.version
=> static install: bump openssl and curl to latest stable versions

.github/data/distros.yml, .github/workflows/packaging.yml, CMakeLists.txt, packaging/makeself/bundled-packages.version, src/collectors/common-contexts/mem.swap.h, src/collectors/proc.plugin/proc_meminfo.c, src/daemon/system-info.sh, src/go/plugin/go.d/modules/nvidia_smi/config_schema.json, src/go/plugin/go.d/modules/nvidia_smi/exec.go, src/go/plugin/go.d/modules/nvidia_smi/metadata.yaml, src/health/health_event_loop.c, src/libnetdata/socket/socket.c
- Detect when swap is disabled when agent is running (#18702)
- static install: bump openssl and curl to latest stable versions (#18719)
- Pass correct GOOS and GOARCH on to package builders in CI. (#18717)
- go.d/nvidia_smi: use configured "timeout" in loop mode (#18692)
- fix ram usage calculation in LXC (#18695)
- fix system-info disk space in LXC (#18696)
- Add check for 64bit builtin atomics (#18565)
=> Patch release 1.47.4

src/go/plugin/go.d/modules/sensors/lmsensors/parse.go, src/go/plugin/go.d/modules/sensors/lmsensors/scanner_test.go
[Reported on Discord](https://discord.com/channels/847502280503590932/1293594405776658474/1293594405776658474).
</details>
=> fix(go.d/sensors): fix parsing power accuracy

integrations/cloud-notifications/metadata.yaml
Add `ilert` cloud notification integration.
=> Add `ilert` cloud notification integration

src/collectors/apps.plugin/README.md
=> docs(apps.plugin): fix prefix/suffix pattern example

src/collectors/apps.plugin/apps_os_freebsd.c, src/collectors/apps.plugin/apps_os_macos.c
=> fix(apps.plugin): fix debug msg spam on macOS/freeBSD

src/database/sqlite/sqlite_aclk.c
Fix a crash when agent is not connected to the cloud (delayed ACLK config initialization)
=> Fix crash on agent initialization

integrations/cloud-notifications/integrations/amazon_sns.md, integrations/cloud-notifications/integrations/discord.md, integrations/cloud-notifications/integrations/ilert.md, integrations/cloud-notifications/integrations/mattermost.md, integrations/cloud-notifications/integrations/microsoft_teams.md, integrations/cloud-notifications/integrations/netdata_mobile_app.md, integrations/cloud-notifications/integrations/opsgenie.md, integrations/cloud-notifications/integrations/pagerduty.md, integrations/cloud-notifications/integrations/rocketchat.md, integrations/cloud-notifications/integrations/slack.md, integrations/cloud-notifications/integrations/splunk.md, integrations/cloud-notifications/integrations/splunk_victorops.md, integrations/cloud-notifications/integrations/telegram.md, integrations/cloud-notifications/integrations/webhook.md, integrations/cloud-notifications/metadata.yaml
There are a ton of issues in the files, I will inform the team internally once I am done with the pass on the docs.
I included the generated .md files, I think this should be a prerequisite, so people can see what they write in YAML (indentations on lists and .md formatting mainly). Also makes review more trivial.
=> Fix issues with Cloud Notification Integrations metadata

integrations/cloud-notifications/metadata.yaml
=> Simplify sentence on cloud notification integrations

src/collectors/python.d.plugin/python.d.plugin.in
Use "EXIT" command instead of relying on parsing error.
</details>
=> fix(python.d.plugin): fix plugin exit if no python found

src/collectors/utils/local_listeners.c, src/libnetdata/maps/local-sockets.h, src/libnetdata/os/gettid.c, src/libnetdata/os/gettid.h, src/libnetdata/spawn_server/spawn_server_nofork.c
=> local-listeners without libmnl

src/collectors/proc.plugin/proc_spl_kstat_zfs.c
Mistake from #18748
</details>
=> fix(proc.plugin/zfs): fix arcstats.pm

src/claim/main.c
Address comment https://github.com/netdata/netdata/pull/18649#issuecomment-2402121374
</details>
=> Adjust option (Windows claim)

src/go/plugin/go.d/agent/discovery/sd/discoverer/netlisteners/netlisteners.go
=> fix(go.d/sd/netlisteners): fix exec deadline exceeded check

src/database/sqlite/sqlite_health.c
- Properly store the repeat field (if configured) in the alert hash table
=> Fix storing of repeat field

src/database/sqlite/sqlite3.h, src/database/sqlite/sqlite_functions.c
- Change to the new recommended way to optimize the databases
=> Sqlite upgrade to version 3.46.1

packaging/installer/kickstart.sh
SSIA
Confirm that the updated kickstart script from this PR works corrrectly on affected systems.
=> Fix broken claiming via kickstart on some systems.

src/collectors/systemd-journal.plugin/systemd-internals.h, src/collectors/systemd-journal.plugin/systemd-journal-files.c, src/collectors/systemd-journal.plugin/systemd-journal-watcher.c
=> systemd-journal; support querying archived files

docs/netdata-agent/configuration/README.md, docs/netdata-agent/configuration/dynamic-configuration.md
not much, just a note change, and a link to main conf file
=> Add ref to dyncfg

README.md
=> docs: fix grammar in readme

integrations/gen_docs_integrations.py
improper custom_edit_url, had to follow the cloud-notification integrations style.
=> bugfix for logs integrations

src/collectors/apps.plugin/apps_groups.conf
=> feat(apps.plugin): add vernemq to apps_groups.conf

src/collectors/proc.plugin/proc_net_dev.c
double-linked check is not reliable at all.
</details>
=> fix(proc/proc_net_dev): delay collecting all virtual interfaces

src/libnetdata/dictionary/dictionary-hashtable.h, src/libnetdata/dictionary/dictionary.c, src/libnetdata/dictionary/dictionary.h
- The hashtable implementation is not currently used (setting aside for now / clears coverity warnings)
=> Comment out dictionary with hashtable code for now

CMakeLists.txt, src/claim/claim.c, src/collectors/common-contexts/common-contexts.h, src/collectors/common-contexts/disk-busy.h, src/collectors/common-contexts/disk-iotime.h, src/collectors/common-contexts/disk-ops.h, src/collectors/common-contexts/disk-qops.h, src/collectors/common-contexts/disk-util.h, src/collectors/proc.plugin/proc_diskstats.c, src/collectors/windows.plugin/perflib-storage.c, src/libnetdata/clocks/clocks.h, src/libnetdata/os/windows-perflib/perflib.c, src/libnetdata/os/windows-perflib/perflib.h
All the the above are unified as common metrics (windows and linux).
=> Windows storage metrics

src/go/plugin/go.d/modules/nvidia_smi/charts.go, src/go/plugin/go.d/modules/nvidia_smi/collect.go, src/go/plugin/go.d/modules/nvidia_smi/metadata.yaml
=> feat(go.d/nvidia_smi): add "index" label to GPU charts

packaging/installer/install-required-packages.sh
=> fix(packaging): fix installing libcurl_dev on FreeBSD

src/go/plugin/go.d/agent/discovery/sd/discoverer/netlisteners/ll.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/netlisteners/netlisteners.go
=> feat(go.d/sd/nl): make timeout and interval configurable

CMakeLists.txt
=> fix(packaging): check for sys/capability.h only on Linux

.github/scripts/check-updater.sh
=> chore(ci): print versions in check_successful_update

src/go/plugin/go.d/modules/ping/metadata.yaml
=> docs(go.d/ping): clarify permissions

src/health/schema.d/health%3Aalert%3Aprototype.json
=> fix: correct health schema typo preventing Action alert rendering.

netdata-installer.sh
Reported in https://github.com/netdata/netdata/pull/18868#discussion_r1817103455
</details>
=> fix: correct go.d.plugin permission for source builds

src/libnetdata/sanitizers/utf8-sanitizer.c
- Adjust sanitizer so if the value is NULL to accept the default value
=> Adjust text_sanitizer to accept the default value

src/collectors/windows.plugin/perflib-storage.c, src/collectors/windows.plugin/windows-internals.h
=> Windows storage fixes

src/collectors/log2journal/log2journal-params.c, src/collectors/log2journal/log2journal-pcre2.c, src/collectors/log2journal/log2journal-rewrite.c, src/collectors/log2journal/log2journal-yaml.c, src/collectors/log2journal/log2journal.h
=> log2journal: fix config parsing memory leaks

src/aclk/aclk.c, src/daemon/main.c, src/database/engine/rrdengine.c, src/database/rrd.h, src/database/sqlite/sqlite_health.c, src/health/health_event_loop.c, src/health/rrdcalc.c
- Code cleanup and coverity fixes (12 issues)
=> Coverity fixes

docs/netdata-agent/start-stop-restart.md, packaging/installer/UPDATE.md
=> Updating Netdata docs

packaging/installer/UNINSTALL.md
=> uninstall docs edits

src/collectors/debugfs.plugin/debugfs_extfrag.c
=> fix(debugfs/extfrag): add zone label

src/collectors/proc.plugin/sys_devices_system_node.c, src/collectors/proc.plugin/sys_fs_btrfs.c
=> proc.plugin: log as info if a dir not exists

src/aclk/mqtt_websockets/mqtt_wss_client.c
- Adjust timeout to avoid waiting forever
=> Fix potential wait forever in mqtt loop

README.md, REDISTRIBUTED.md, packaging/windows/WINDOWS_INSTALLER.md
=> docs: fix ui license link

src/go/plugin/go.d/modules/portcheck/config_schema.json
=> go.d/portcheck: separate tabs for tcp/upd ports

src/collectors/apps.plugin/apps_groups.conf
add dagster which is a popular data orchastration tool similar to airflow
https://github.com/dagster-io/dagster
Tested locally and all looks good:
</details>
=> add `dagster` to apps_groups.conf

docs/netdata-agent/sizing-netdata-agents/README.md, packaging/installer/UNINSTALL.md, packaging/windows/WINDOWS_INSTALLER.md
I think the next section is the "Sizing Agents" one.
@ilyam8 I read the file, the innovations stuff does not amaze me, and I would argue the title of the file is a bit vague. I fixed grammar and broke up huge paragraphs to nice blocks of text, when sentence meaning changes over the paragraph (was hard for me to read a >5 line paragraph with just plain text)
plus some small fixes for windows stuff
=> Docs: small fixes and pass on sizing Agents

src/go/plugin/go.d/config/go.d/nvidia_smi.conf
=> chore(go.d/nvidia_smi): remove use_csv_format (deprecated) from config

src/go/plugin/go.d/pkg/prometheus/client.go, src/go/plugin/go.d/pkg/prometheus/client_test.go
=> fix(go.d/prometheus): correct unsupported protocol scheme "file" error

CMakeLists.txt, src/aclk/mqtt_websockets/ws_client.c, src/libnetdata/common.h, src/libnetdata/os/random.c, src/libnetdata/os/random.h
random numbers use RAND_bytes() by default and fallback to others
=> Random numbers improvements

packaging/docker/README.md
=> docs: fix Caddy docker compose example

src/collectors/README.md
[Causing Learn to fail on build](https://github.com/netdata/learn/pull/2245)
=> Fix br elements

src/database/engine/pdc.c, src/database/engine/rrdengine.h
- Adjust max extent size
Fixes #18958
=> Adjust max possible extent size

.github/workflows/build.yml, netdata.spec.in, packaging/check-for-go-toolchain.sh
=> build(deps): update go toolchain to v1.23.3

src/go/go.mod, src/go/go.sum
=> go mod tidy

src/go/plugin/go.d/modules/rabbitmq/metadata.yaml, src/health/health.d/rabbitmq.conf
=> add rabbitmq alerts

src/go/go.mod
=> ci: fix win jobs

src/go/plugin/go.d/agent/module/job.go
This allows to create a table for a quick overview of the status of running data collection jobs.
<details>
<summary>table</summary>
</details>
</details>
=> improvement(go.d.plugin): add data collection status chart

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
=> update GH bug report

src/health/health.d/go.d.plugin.conf
=> health: enable go.d data collection job status alert

src/health/health.d/go.d.plugin.conf
=> update plugin_data_collection_status alert summary/info

integrations/deploy.yaml
=> docs: single line win deploy

integrations/deploy.yaml
=> docs: win deploy remove `./`

src/go/plugin/go.d/modules/x509check/charts.go, src/go/plugin/go.d/modules/x509check/collect.go, src/go/plugin/go.d/modules/x509check/config_schema.json, src/go/plugin/go.d/modules/x509check/init.go, src/go/plugin/go.d/modules/x509check/metadata.yaml, src/go/plugin/go.d/modules/x509check/testdata/config.json, src/go/plugin/go.d/modules/x509check/testdata/config.yaml, src/go/plugin/go.d/modules/x509check/x509check.go, src/health/health.d/x509check.conf
=> improvement(go.d/x509check): support checking full chain expiry time

src/go/plugin/go.d/modules/x509check/collect.go
=> fix(go.d/x509check): correct check revocation code

src/web/server/web_client.c
- Use now + 1 day as expires
Fixes #18998
=> Set expires header when serving files

src/go/plugin/go.d/modules/windows/metadata.yaml
=> docs(go.d/windows): add deprecation notice

src/streaming/rrdhost-status.c
fix has_receiver condition in rrdhost_status()
=> fix has_receiver condition in rrdhost_status()

packaging/windows/netdata.wxs.in
=> Remove MSI test

src/go/go.mod, src/go/go.sum, src/go/plugin/go.d/modules/ping/config_schema.json, src/go/plugin/go.d/modules/ping/init.go, src/go/plugin/go.d/modules/ping/metadata.yaml, src/go/plugin/go.d/modules/ping/prober.go
=> fix(go.d/ping): fix "interface" option

src/collectors/windows.plugin/metadata.yaml, src/go/plugin/go.d/modules/windows/metadata.yaml
This PR adds IIS metrics to `windows.plugin` metadata. It also fixes wrong pair of dimensions in `go.d.plugin`.
1. Take a look in CI
2. Verify if something is missed.
</details>
=> IIS Metadata

src/collectors/windows.plugin/metadata.yaml
=> docs: just iis

src/collectors/windows.plugin/perflib-mssql.c, src/collectors/windows.plugin/perflib-netframework.c, src/collectors/windows.plugin/perflib-thermalzone.c, src/collectors/windows.plugin/perflib-web-service.c
- iis
- mssql
- thermalzone
- netframework
it has wild indentation
</details>
=> chore(windows.plugin): format win collectors code

src/go/plugin/go.d/modules/windows/metadata.yaml
=> docs(go.d/windows): remove references to old MSI

src/go/cmd/godplugin/main.go, src/go/go.mod, src/go/go.sum
to match Linux container CPU quota.
</details>
=> improvement(go.d.plugin): automatically set GOMAXPROCS

src/collectors/windows.plugin/perflib-web-service.c
+ simplify dimensions id
</details>
=> fix(windows/iis): dont sanitize site name for labels

system/freebsd/rc.d/netdata.in
=> add `shutdown` keyword to ensure graceful service termination on FreeBSD

src/collectors/windows.plugin/perflib-netframework.c, src/collectors/windows.plugin/perflib-thermalzone.c
=> fix(windows/netframework): dont sanitize proc name for labels

src/go/plugin/go.d/agent/agent.go, src/go/plugin/go.d/agent/functions/manager.go, src/go/plugin/go.d/agent/functions/manager_test.go, src/go/plugin/go.d/agent/module/job.go
=> improvement(go.d.plugin): terminate on QUIT command

src/go/plugin/go.d/modules/nvidia_smi/nvidia_smi.go
Forgot to add in #19039
</details>
=> fix(go.d/nvidia_smi): disable loop mode on Win

packaging/windows/netdata.wxs.in
After talking with @stelfrag, this PR is adding `customactions` to address specific issues.
1. Make binary
2. Uninstall netdata. Check if after to be installed, everything is ok.
</details>
=> Add Custom Actions (Installer)

src/collectors/windows.plugin/perflib-mssql.c
This PR address some issues identified with SQL Server.
We still have to work with large values that are shown as negative on cloud, but we are storing positive values.
2. Generate an installer
3. Test it on environment with MS SQL
</details>
=> Fix MSSQL algorithm (Windows.plugin)

src/go/plugin/go.d/pkg/web/client_config.go
=> fix(go.d/pkg/web): correct close idle connections

packaging/installer/methods/packages.md
- Update URLs to point to the new base URL.
- Add info about by-hash metdata handling for DEB repos.
- Add deb822 style example for DEB repos.
n/a
=> Update documentation about our native package repos.

packaging/installer/UNINSTALL.md, packaging/installer/UPDATE.md
Edits for updating and uninstalling
=> Windows doc updates

docs/netdata-agent/securing-netdata-agents.md, src/web/server/README.md
@ilyam8 I read through the docs, made changes both to syntax and order of content. Removed some fluff, and made the examples collapsible in the Web Server README.(as we do on integration configuration examples)
I also want to move the files from their current position, but that will come after the merge of these changes.
=> Securing Agents section docs cleanup

src/collectors/windows.plugin/perflib-mssql.c
=> add links to mssql perflib object docs

packaging/windows/netdata.wxs.in
- Register service to delay start (#19063)
=> Patch Release 2.0.3

README.md, docs/dashboards-and-charts/README.md, docs/deployment-guides/deployment-strategies.md, docs/deployment-guides/standalone-deployment.md, docs/glossary.md, docs/security-and-privacy-design/netdata-agent-security.md, docs/top-monitoring-netdata-functions.md, integrations/deploy.yaml, packaging/docker/README.md, packaging/installer/methods/freebsd.md, packaging/installer/methods/kickstart.md, packaging/installer/methods/macos.md, packaging/windows/WINDOWS_INSTALLER.md, src/claim/README.md
"claiming" as a concept is a Legacy term, we now use "connecting".
The Token still is the "claiming token", but the process is "connecting a node"
as these files are below the Agent section on Learn, I didn't do any grammar checks or read-through, as that will be done when we tackle each section.
=> claim -> connect in docs

src/collectors/systemd-journal.plugin/README.md
=> docs(systemd-journal.plugin): correct "Full-text search"

src/daemon/global_statistics.c
=> update gorilla comp internal charts family

docs/DICTIONARY.md
We will use this file to dictate how we call things when we want to refer to a certain section of Netdata.
=> Create a terminology dictionary for Netdata

src/collectors/systemd-journal.plugin/README.md
=> docs(systemd-journal.plugin): correct full-text search

src/claim/claim-with-api.c
Will probably help in https://github.com/netdata/netdata/issues/19096
=> Claiming proxy defaults and additonal log info

docs/dashboards-and-charts/dashboards-tab.md, docs/dashboards-and-charts/nodes-tab.md, docs/glossary.md, docs/netdata-agent/configuration/organize-systems-metrics-and-alerts.md, docs/netdata-cloud/organize-your-infrastructure-invite-your-team.md, packaging/installer/README.md, packaging/installer/methods/macos.md
The document is better fitted as a "Spaces and Rooms" document, that explains how they work. I think the concept of "inviting" is self-explanatory when you talk about stuff like "Spaces" and "Rooms"
=> Edit the organize doc

docs/DICTIONARY.md, src/claim/README.md
Fix language, make it more readable (tables) and update terms on the dictionary.
=> Update connecting documentation

docs/netdata-cloud/organize-your-infrastructure-invite-your-team.md
=> docs: fix img tag

docs/DICTIONARY.md, docs/netdata-cloud/netdata-cloud-on-prem/README.md, docs/netdata-cloud/netdata-cloud-on-prem/installation.md, docs/netdata-cloud/versions.md
read-through and made necessary changes.
=> Docs edits on Cloud versions and On Prem

docs/netdata-cloud/netdata-cloud-on-prem/installation.md
=> docs: update On-Prem System Requirements

src/collectors/proc.plugin/run_reboot_required.c
=> fix(proc/reboot_required): disable on non Debian-based systems

src/collectors/python.d.plugin/python.d.conf
Forgot to do it in #18369
</details>
=> disable python.d/example

src/libnetdata/ebpf/ebpf.c
=> Fix undefined behaviour.

src/daemon/daemon.c
=> change default nice level to 0

src/daemon/system-info.sh
=> fix(system-info): change id_like and name mac -> macOS

packaging/check-for-go-toolchain.sh
=> fix(packaging): correct go linux 386 checksum

src/collectors/windows.plugin/metadata.yaml
=> docs(windows/hyperv): add Hyper-V metadata

src/collectors/windows.plugin/perflib-hyperv.c
=> chore(windows/hyperv): small Hyper-V fixes

.github/workflows/build.yml
=> ci: fix build/Prepare Artifacts

README.md
The readme introduction is crucial for first-time visitors and potential users.
</details>
=> docs: restructure readme intro for better readability

src/database/engine/rrdengineapi.c, src/streaming/stream-receiver.c, src/streaming/stream-sender-internals.h, src/streaming/stream-sender.c, src/streaming/stream-thread.c, src/streaming/stream-thread.h
Left-over use of POLLIN instead of ND_POLL_READ.
=> fixed bug in streaming sender read

.github/workflows/build.yml
=> ci: fix build/create release

docs/netdata-cloud/view-plan-and-billing.md, src/aclk/README.md
Made changes as I was reading the doc
=> docs: Plans and ACLK docs edits

src/go/pkg/netdataapi/api.go, src/go/pkg/netdataapi/api_test.go, src/go/pkg/netdataapi/opts.go, src/go/plugin/go.d/agent/agent.go, src/go/plugin/go.d/agent/functions/manager.go, src/go/plugin/go.d/agent/jobmgr/di.go, src/go/plugin/go.d/agent/jobmgr/dyncfg.go, src/go/plugin/go.d/agent/module/job.go
=> chore(go.d.plugin): simplify netdataapi pkg

src/go/cmd/godplugin/config.go, src/go/cmd/godplugin/main.go, src/go/plugin/go.d/agent/agent.go, src/go/plugin/go.d/agent/setup.go, src/go/plugin/go.d/agent/setup_test.go, src/go/plugin/go.d/examples/simple/main.go
=> chore(go.d.plugin): simplify main

src/collectors/windows.plugin/metadata.yaml
This PR is adding missing metadata for windows.plugin.
1. Take a look on CI and grammar copied from go.d.plugin metadata.
</details>
=> MSSQL Metadatas (windows.plugin)

src/go/plugin/go.d/agent/filelock/filelock.go, src/go/plugin/go.d/agent/filelock/filelock_test.go
Follow up on #19153
</details>
=> fix(go.d): correct unlockall impl

src/go/cmd/godplugin/config.go
=> fix(go.d): correct sd dir

src/collectors/windows.plugin/metadata.yaml
This PR brings the metdata for metrics already merged in master branch.
1. Check CI
</details>
=> NET Framework metadata (Windows.plugin Part 1)

docs/netdata-cloud/authentication-and-authorization/README.md, docs/netdata-cloud/authentication-and-authorization/enterprise-sso-authentication.md, docs/netdata-cloud/authentication-and-authorization/role-based-access-model.md
Edits and updates on the section.
=> docs: edit Authentication and Authorization section

src/plugins.d/pluginsd_parser.c
- Notify cloud if a virtual host changes hostname
=> Update cloud virtual host name

src/collectors/windows.plugin/metadata.yaml, src/health/health.d/cpu.conf
Add missing metrics to processor.
1. Check CI
</details>
=> Processor Metadata (Windows Plugin)

src/collectors/windows.plugin/metadata.yaml
Continue adding metadata for charts merged, this PR brings IPC metadata.
1. Check CI
</details>
=> Add Objects metadata (Windows Plugin)

packaging/installer/methods/packages.md
Combined with the new index generation code in the repository backend, fixes issues like https://github.com/netdata/netdata/pull/19049#issuecomment-2522765937
n/a
=> Fixup URLs in package repo documentation to use index files.

src/collectors/windows.plugin/metadata.yaml
1. Check CI
2. Check Grammar
</details>
=> Disks Metadata (Windows plugin)

.github/workflows/generate-integrations.yml, .github/workflows/update-website.yml
Label the "Generate Integrations" PR with "integrations-update". Once a PR with this label is merged, it automatically triggers the "Update website" workflow.
</details>
=> ci: fix update-website workflow

src/libnetdata/log/README.md
=> docs: remove a duplicated row

src/collectors/windows.plugin/metadata.yaml
Add metadata information for network and protocols
1. Check CI
</details>
=> Network Metadata (Windows plugin)

packaging/makeself/install-or-update.sh
=> fix: use setuid as a fallback for static builds when setcap fails for plugins

packaging/build-package.sh, packaging/installer/functions.sh
=> disable h20

docs/netdata-cloud/netdata-cloud-on-prem/installation.md, src/aclk/README.md
- bumping traefik version,
- removing information about IP addresses as we want to go for the edge network.
</details>
=> removing IP address information. Bumping traefik version

src/collectors/utils/ndsudo.c
=> add MegaCli64 to ndsudo

CMakeLists.txt, src/database/rrd.h, src/database/rrdhost.c, src/database/sqlite/sqlite_health.c, src/database/sqlite/sqlite_metadata.c, src/health/health-alert-entry.h, src/health/health-alert-log.h, src/health/health_event_loop.c, src/health/health_log.c, src/health/health_notifications.c, src/health/health_prototypes.c, src/health/rrdcalc.c
=> Fix: fix heap use after free in health

REDISTRIBUTED.md
=> docs: update ui 3rd party link

integrations/deploy.yaml
=> docs: fix win deploy command for nightly

CMakeLists.txt, src/aclk/aclk.c, src/aclk/aclk_rx_msgs.c, src/daemon/analytics.c, src/daemon/analytics.h, src/daemon/buildinfo.c, src/daemon/buildinfo.h, src/daemon/main.c, src/database/contexts/api_v2_contexts.c, src/database/rrd.h, src/database/rrdfunctions.c, src/database/rrdhost-system-info.c, src/database/rrdhost-system-info.h, src/database/rrdhost.c, src/database/rrdlabels.h, src/database/sqlite/sqlite_aclk.c, src/database/sqlite/sqlite_aclk_node.c, src/database/sqlite/sqlite_metadata.c, src/libnetdata/buffer/buffer.h, src/plugins.d/pluginsd_parser.c, src/streaming/rrdhost-status.c, src/streaming/stream-connector.c, src/streaming/stream-receiver-connection.c, src/web/api/v1/api_v1_info.c
isolate struct system_info from the rest of netdata and provide an API to access it
No feature changes. Just code cleanup.
=> RRDHOST system-info isolation

src/go/cmd/godplugin/main.go, src/go/plugin/go.d/cli/cli.go
=> chore(go.d): simplify cli is help

src/aclk/mqtt_websockets/mqtt_ng.c
=> chore(aclk/mqtt): remove client_id len check

docs/netdata-cloud/node-rule-based-room-assignment.md
=> docs: change "node-membership-rules" filename/title

src/collectors/proc.plugin/sys_class_drm.c
=> fix crash when the DRM file does not contain the right information

src/health/guides/reboot_required/system_post_update_reboot_status.md
This complements the metric and alert added in #19109 as part of #19106.
=> Add an alert guide for reboot required

src/exporting/prometheus/prometheus.c, src/libnetdata/libjudy/judyl-typed.h
do not output HELP and TYPE multiple times when exporting multiple nodes to prometheus
=> HELP and TYPE in prometheus fix

src/go/plugin/go.d/collector/nats/charts.go, src/go/plugin/go.d/collector/nats/collect.go, src/go/plugin/go.d/collector/nats/collector.go, src/go/plugin/go.d/collector/nats/collector_test.go, src/go/plugin/go.d/collector/nats/metadata.yaml, src/go/plugin/go.d/collector/nats/restapi.go, src/go/plugin/go.d/collector/nats/testdata/v2.10.24/routez.json
=> improvement(go.d/nats): add routez metrics

packaging/check-for-go-toolchain.sh
=> build(deps): update go toolchain to v1.23.4

docs/netdata-cloud/netdata-cloud-on-prem/poc-without-k8s.md, docs/netdata-cloud/netdata-cloud-on-prem/troubleshooting.md
After dealing with some client cases, I think these points should be available for everyone.
</details>
=> Updates to onprem docs

src/go/plugin/go.d/collector/nats/charts.go, src/go/plugin/go.d/collector/nats/collect.go, src/go/plugin/go.d/collector/nats/collector.go, src/go/plugin/go.d/collector/nats/metadata.yaml
=> improvement(go.d/nats): add server_id label

docs/netdata-cloud/netdata-cloud-on-prem/troubleshooting.md
We need to improve the structure of "Common Issues". Every issue should have the following headers:
- Issue
- Symptoms
- Cause
- Solution
- Information to gather before contacting Netdata support.
The table view is great, but it's only for quick reference, we need a more detailed version. 
</details>
=> docs: improve on-prem troubleshooting readability

src/go/plugin/go.d/collector/nats/cache.go, src/go/plugin/go.d/collector/nats/charts.go, src/go/plugin/go.d/collector/nats/collect.go, src/go/plugin/go.d/collector/nats/collector_test.go, src/go/plugin/go.d/collector/nats/metadata.yaml, src/go/plugin/go.d/collector/nats/restapi.go, src/go/plugin/go.d/collector/nats/testdata/v2.10.24/leafz.json
=> improvement(go.d/nats): add leafz metrics

src/go/plugin/go.d/collector/nats/collect.go, src/go/plugin/go.d/collector/nats/collector_test.go
=> fix go.d/nats tests

src/go/plugin/go.d/collector/nats/charts.go, src/go/plugin/go.d/collector/nats/collect.go, src/go/plugin/go.d/collector/nats/collector_test.go, src/go/plugin/go.d/collector/nats/metadata.yaml, src/go/plugin/go.d/collector/nats/restapi.go, src/go/plugin/go.d/collector/nats/testdata/v2.10.24/jsz.json
=> improvement(go.d/nats): add basic jetstream metrics

packaging/dag/requirements.txt
Just to fix [dependabot warnings](https://github.com/netdata/netdata/security/dependabot?q=package%3Ajinja2+manifest%3Apackaging%2Fdag%2Frequirements.txt+is%3Aopen).
</details>
=> bump dag req jinja version

packaging/installer/netdata-updater.sh
=> fix(netdata-updater.sh): remove commit_check_file directory

packaging/installer/dependencies/alpine.sh, packaging/installer/dependencies/arch.sh, packaging/installer/dependencies/centos.sh, packaging/installer/dependencies/clearlinux.sh, packaging/installer/dependencies/debian.sh, packaging/installer/dependencies/fedora.sh, packaging/installer/dependencies/freebsd.sh, packaging/installer/dependencies/gentoo.sh, packaging/installer/dependencies/ol.sh, packaging/installer/dependencies/opensuse.sh, packaging/installer/dependencies/rockylinux.sh, packaging/installer/dependencies/ubuntu.sh, packaging/installer/install-required-packages.sh
=> build(deps): add bison and flex

src/collectors/debugfs.plugin/module-libsensors.c
=> fix(debugfs/sensors): correct driver label value

CMakeLists.txt, src/collectors/debugfs.plugin/module-libsensors.c, src/libnetdata/locks/rw-spinlock.c, src/libnetdata/locks/rw-spinlock.h, src/libnetdata/socket/nd-poll.c, src/libnetdata/socket/nd-poll.h, src/libnetdata/socket/poll-events.c, src/streaming/stream-receiver.c, src/streaming/stream-sender.c, src/streaming/stream-thread.c
=> nd_poll() fairness

src/streaming/stream-conf.c
=> Improve stream sending thread error message

src/go/plugin/go.d/collector/nats/charts.go, src/go/plugin/go.d/collector/nats/collect.go, src/go/plugin/go.d/collector/nats/collector.go, src/go/plugin/go.d/collector/nats/collector_test.go
=> improvement(go.d/nats): add cluster_name label and jetstream status chart

src/libnetdata/locks/waitq.c, src/libnetdata/locks/waitq.h
Within the same priority, ordering was reversed.
=> WAITQ: fixed mixed up ordering

src/daemon/pulse/pulse-daemon-memory.c, src/libnetdata/aral/aral.c
Fix negative memory accounting in aral
=> fix aral memory accounting

src/go/plugin/go.d/collector/nats/metadata.yaml
=> docs(go.d/nats): add missing labels to meta

src/go/plugin/go.d/collector/nats/charts.go
=> fix(go.d/nats): add missing cid label to gw charts

src/go/plugin/go.d/agent/discovery/sd/model/tags.go, src/go/plugin/go.d/agent/discovery/sd/pipeline/classify.go, src/go/plugin/go.d/agent/discovery/sd/pipeline/classify_test.go
=> fix(go.d/sd): correctly adding tags in classify

src/collectors/apps.plugin/apps_groups.conf, src/collectors/apps.plugin/apps_targets.c
=> add yugabytedb docker manager

src/collectors/cgroups.plugin/cgroup-name.sh.in
=> fix(cgroup-rename): prevent leading comma in Docker LABELS when IMAGE empty

packaging/installer/kickstart.sh
=> fix(kickstart.sh): correct wrong function name in perpare_offline_install

packaging/installer/netdata-updater.sh, src/collectors/proc.plugin/sys_class_drm.c, src/exporting/prometheus/prometheus.c, src/go/plugin/go.d/collector/rabbitmq/collect.go, src/go/plugin/go.d/collector/rabbitmq/collect_nodes.go, src/go/plugin/go.d/collector/rabbitmq/collector.go, src/go/plugin/go.d/collector/rabbitmq/collector_test.go, src/go/plugin/go.d/collector/rabbitmq/restapi.go, src/go/plugin/go.d/collector/rabbitmq/testdata/v4.0.3/cluster/whoami.json, src/health/health_event_loop.c, src/libnetdata/libjudy/judyl-typed.h
- use explicit paths for temp dir creation (#19293)
- fix(netdata-updater.sh): ensure tmpdir-path argument is always passed (#19289)
- fix(netdata-updater.sh): remove commit_check_file directory (#19288)
- fix(go.d/rabbitmq): handle insufficient perms when querying definitions (#19277)
- HELP and TYPE in prometheus fix (#19261)
- fix crash when the DRM file does not contain the right information (#19258)
- FD Leaks Fix (#19327)
=> Patch release 2.1.1

src/go/plugin/go.d/collector/docker/collect.go, src/go/plugin/go.d/collector/docker/collector.go, src/go/plugin/go.d/collector/docker/config_schema.json, src/go/plugin/go.d/collector/docker/metadata.yaml, src/go/plugin/go.d/collector/docker/testdata/config.json, src/go/plugin/go.d/collector/docker/testdata/config.yaml
=> improvement(go.d/docker): add option to filter containers

src/go/plugin/go.d/collector/docker/metadata.yaml
=> docs(go.d/docker): fix syntax error in meta

src/go/plugin/go.d/collector/docker/collect.go, src/go/plugin/go.d/collector/docker/collector_test.go
=> improvement(go.d/docker): respect ignore label

src/go/plugin/go.d/collector/k8s_state/discover_pod.go
=> improvement(go.d/k8sstate): respect ignore annotation

src/aclk/aclk.c, src/database/sqlite/sqlite_aclk_alert.c, src/database/sqlite/sqlite_aclk_alert.h
- Adds alert version to `netdatacli aclk-state` output (and api/v1/aclk)
=> Add alert version to aclk-state

src/daemon/pulse/pulse-daemon-memory.c, src/database/engine/cache.c
=> PGC wanted size

src/aclk/aclk.c, src/database/contexts/contexts-loading.c
reformatted the metadata report, to provide the complete picture
=> RRDCONTEXTS: loading report

src/streaming/stream-sender-api.c, src/streaming/stream-sender-commit.c, src/streaming/stream-sender-commit.h, src/streaming/stream-sender.c
clear cached buffer on reconnect
=> Stream Compression Fix

CMakeLists.txt, src/web/api/functions/function-metrics-cardinality.c, src/web/api/functions/function-metrics-cardinality.h, src/web/api/functions/functions.c, src/web/api/functions/functions.h
A function to explore the cardinality and ephemerality of metrics
=> metrics-cardinality function

src/database/engine/rrdengineapi.c
=> Revert "prevent memory corruption in dbengine"

src/streaming/stream-thread.c
Realloc was using a different spinlock than the intended when reallocating the messages buffer.
=> stream-thread fix memory corruption

src/libnetdata/aral/aral.c
When multiple threads allocate memory from a newly created ARAL page, there is significant contention on `aral_page_available_lock()`. This happens because all threads try to get elements from the same page, using the same lock to access the available list. The high lock contention impacts performance during memory allocation spikes, especially at 00:00 of each hour, when all dbengine tiers mark their pages dirty and want to allocate new ones.
- Added a 64-bit atomic counter (`elements_segmented`) to each aral page, initialized to 0 with RELEASE memory ordering when the page is created
- When allocating memory:
- First try a lock-free fast path using atomic fetch_add on `elements_segmented`
- If the returned slot number is < max_elements, directly use that slot without any locks
- The …
=> ARAL: fast path to quickly allocate elements on a new page

src/daemon/pulse/pulse-daemon-memory.c
=> used_arena should exclude unused memory

packaging/installer/kickstart.sh
- Account for Debian/Ubuntu still not including sbin directories in user $PATH.
- Report an inability to detect netdatacli location instead of trying to invoke an empty string when claiming.
Needs manual testing for runs as a non-root user on Debian/Ubuntu systems.
=> Fix issues with $PATH and netdatacli detection.

src/database/sqlite/sqlite_metadata.c
- Delay context cleanup checks after agent restart
=> Delay context cleanup checks after startup

packaging/windows/package-windows.sh
=> packaging(windows): use local copy of GPL-3

.github/ISSUE_TEMPLATE/BUG_REPORT.yml, .github/ISSUE_TEMPLATE/FEAT_REQUEST.yml
=> add 'type' to GH report forms

src/go/plugin/go.d/collector/ethtool/charts.go, src/go/plugin/go.d/collector/ethtool/collect.go, src/go/plugin/go.d/collector/ethtool/collect_module_eeprom.go, src/go/plugin/go.d/collector/ethtool/collector.go, src/go/plugin/go.d/collector/ethtool/collector_test.go, src/go/plugin/go.d/collector/ethtool/config_schema.json, src/go/plugin/go.d/collector/ethtool/exec.go, src/go/plugin/go.d/collector/ethtool/init.go, src/go/plugin/go.d/collector/ethtool/metadata.yaml, src/go/plugin/go.d/collector/ethtool/testdata/config.json, src/go/plugin/go.d/collector/ethtool/testdata/config.yaml, src/go/plugin/go.d/collector/ethtool/testdata/ddm-no-fiber.txt, src/go/plugin/go.d/collector/ethtool/testdata/ddm.txt, src/go/plugin/go.d/collector/ethtool/testdata/no-ddm.txt, src/go/plugin/go.d/collector/init.go, src/go/plugin/go.d/config/go.d.conf, src/go/plugin/go.d/config/go.d/ethtool.conf
=> feat(go.d/ethtool): collect module ddm info using ethtool

src/go/plugin/go.d/collector/ethtool/collector.go, src/go/plugin/go.d/collector/ethtool/collector_test.go, src/go/plugin/go.d/collector/ethtool/config_schema.json, src/go/plugin/go.d/collector/ethtool/exec.go, src/go/plugin/go.d/collector/ethtool/init.go, src/go/plugin/go.d/collector/ethtool/metadata.yaml, src/go/plugin/go.d/collector/ethtool/testdata/config.json, src/go/plugin/go.d/collector/ethtool/testdata/config.yaml
=> fix(go.d/ethtool): use ndsudo for module info

src/go/plugin/go.d/collector/ethtool/metadata.yaml
=> docs: fix go.d/ethtool meta

src/go/plugin/go.d/collector/ethtool/config_schema.json
=> fix go.d/ethtool config schema

src/collectors/utils/ndsudo.c
=> add 'ethtool -m' to ndsudo

packaging/check-for-go-toolchain.sh
=> build(deps): update go toolchain to v1.23.5

src/database/sqlite/sqlite_aclk.c
The agent uses a set number of query threads to handle incoming queries from the cloud (based  on system cpu count)
If all threads are busy, the event loop would try to run the query synchronously, causing issues.
This PR adds a queue to store queries and run them as soon as threads are available.
=> Do not run queries synchronously in the event loop

docs/netdata-cloud/node-rule-based-room-assignment.md
improvements and adding missing information to rule based membership document.
=> Add missing information in rule based membership document

src/go/plugin/go.d/collector/upsd/charts.go, src/go/plugin/go.d/collector/upsd/collector_test.go
Fixes: #19454
Closes: #19455
</details>
=> fix(go.d/upsd): remove UPS load charts if UPS load not found

src/database/sqlite/sqlite_aclk.c
- Allocate memory using aral when queuing commands to ACLK sync event loop
- Code cleanup
=> Use aral in ACLK

.github/workflows/build.yml, .github/workflows/docker.yml
=> Don’t fail fast on static builds and Docker builds.

src/health/health_event_loop.c
- Add worker for alert queue processing to monitor health resource usage in more detail
=> Add worker for alert queue processing

src/aclk/aclk_util.c
=> ACLK: allow encoded proxy username and password to work

packaging/cmake/config.cmake.h.in, src/daemon/buildinfo.c
=> update buildinfo 

src/database/engine/page.c
This will allow us to figure out if it's the caller pushing more points than what the page can hold.
- CI jobs.
=> Invert order of checks in pgd_append_point().

CMakeLists.txt, packaging/cmake/config.cmake.h.in, src/daemon/buildinfo.c, src/daemon/main.c
=> compile time and runtime check of required compiler flags

src/go/plugin/go.d/collector/nvme/exec.go
=> chore(go.d/nvme): fix :dog: warning

src/go/plugin/go.d/collector/httpcheck/metadata.yaml
=> docs(go.d/httpcheck): add alerts to metadata

src/web/README.md
Forgot to update the readme in #19523 🫤 
</details>
=> docs(web/gui): remove info about old dashboard from readme

src/daemon/pulse/pulse-ingestion.c, src/database/contexts/instance.c, src/database/contexts/rrdcontext.c, src/database/engine/cache.c, src/database/engine/rrdengineapi.c, src/database/rrddim-collection.c, src/libnetdata/atomics/refcount.h, src/libnetdata/buffer/buffer.c, src/libnetdata/buffer/buffer.h, src/libnetdata/inlined.h, src/libnetdata/line_splitter/line_splitter.h, src/ml/ml.cc, src/ml/ml_public.cc, src/plugins.d/pluginsd_internals.h, src/plugins.d/pluginsd_parser.c, src/plugins.d/pluginsd_replication.c, src/streaming/protocol/command-begin-set-end-init.c, src/streaming/protocol/command-begin-set-end-v2.c, src/streaming/protocol/command-nodeid.c, src/streaming/stream-connector.c, src/streaming/stream-receiver.c, src/streaming/stream-sender-internals.h, src/streaming/stream-sender.c
=> inline functions related to metrics ingestion

src/database/engine/page.c
=> Format PGDs on fatal()

src/collectors/windows.plugin/perflib-ad.c, src/collectors/windows.plugin/perflib-netframework.c
Apply formatting defined in the project
</details>
=> chore(windows.plugin): format perflib ad and netframework

src/collectors/windows.plugin/metadata.yaml
Blocked by https://github.com/netdata/netdata/pull/19008
This PR should be merged only after #19008 to be merged
1. Check CI
</details>
=> Add CLR Remoting metadata

src/collectors/windows.plugin/GetSystemCPU.c, src/collectors/windows.plugin/GetSystemRAM.c, src/collectors/windows.plugin/GetSystemUptime.c, src/collectors/windows.plugin/perflib-hyperv.c, src/collectors/windows.plugin/perflib-memory.c, src/collectors/windows.plugin/perflib-mssql.c, src/collectors/windows.plugin/perflib-network.c, src/collectors/windows.plugin/perflib-objects.c, src/collectors/windows.plugin/perflib-processes.c, src/collectors/windows.plugin/perflib-processor.c, src/collectors/windows.plugin/perflib-rrd.c, src/collectors/windows.plugin/perflib-rrd.h, src/collectors/windows.plugin/perflib-storage.c, src/collectors/windows.plugin/perflib-thermalzone.c, src/collectors/windows.plugin/perflib-web-service.c, src/collectors/windows.plugin/windows-internals.h
Following previous [eBPF PR](https://github.com/netdata/netdata/pull/19553), this PR formats all files to separate formatting changes from necessary modifications in next PRs.
1. Check CI
</details>
=> Format Windows.plugin

src/collectors/windows.plugin/metadata.yaml, src/collectors/windows.plugin/perflib-ad.c, src/collectors/windows.plugin/perflib-adcs.c, src/collectors/windows.plugin/windows_plugin.c
This PR adds the missing metadata and corrects some dimension names.
</details>
=> Metadata (AD and ADCS), and small fixes

src/claim/cloud-status.c, src/claim/cloud-status.h, src/collectors/windows.plugin/perflib-mssql.c, src/database/sqlite/sqlite_health.c, src/web/api/v2/api_v2_claim.c
- MSSQL Multiple Instances (windows.plugin) (#19559)
- Backport fix for memory leak in the health from (#19569)
- Add a new agent status when connecting to the cloud (#19564)
=> Patch release 2.2.4

src/go/plugin/go.d/agent/agent.go
Obsolete charts for stopped/removed jobs to prevent stale alarms.
</details>
=> fix(go.d): clean up charts for stopped and removed jobs

.github/workflows/build.yml
Unintentionally broken by: #19427
n/a
=> Fix static build conditions to run on release and nightly builds.

packaging/check-for-go-toolchain.sh
=> build(deps): update go toolchain to v1.23.6

src/go/plugin/go.d/collector/apache/collector_test.go, src/go/plugin/go.d/collector/apache/init.go
=> fix(go.d/apache): make ?auto param check non-fatal

.gitignore, CMakeLists.txt, packaging/cmake/Modules/NetdataProtobuf.cmake, src/aclk/aclk_query.c, src/aclk/schema-wrappers/connection.cc, src/database/sqlite/sqlite_aclk.c, src/exporting/prometheus/remote_write/remote_write_request.cc
SSIA. Currently, we generate those files in the repository checkout.
CI jobs.
=> Generate protobuf source files in build dir.

src/collectors/ebpf.plugin/ebpf.c
While working with https://github.com/netdata/netdata/pull/19572 I observed one file was without correct format, this PR address this issue.
1. Check CI
</details>
=> Format missing file (eBPF.plugin)

src/go/plugin/go.d/collector/zookeeper/metadata.yaml
=> docs(go.d/zookeeper): fix ZooKeeper server scope name

src/health/REFERENCE.md
=> docs(health): clarify "special user of the cond operator"

src/health/REFERENCE.md
=> docs(health): clarify "special user of the cond operator" p2

src/aclk/aclk_otp.c
- Add agent version in the challenge response
- Agent connects to the cloud
Fixes #19581
=> Add agent version during ACLK handshake

src/database/contexts/worker.c
- Fix coverity issue -- possible div by 0
=> Add check for available active instances when checking for extreme cardinality

docs/nodes-ephemerality.md
=> docs: reword nodes-ephemerality for clarity

src/collectors/statsd.plugin/statsd.c, src/libnetdata/statistical/statistical.c, src/libnetdata/statistical/statistical.h
Fixes https://github.com/netdata/netdata/issues/19605
=> add interpolation to median and percentile

src/health/health.d/clickhouse.conf
=> improvement(health): clarify clickhouse_replicated_readonly_tables info

src/daemon/daemon-shutdown.c, src/daemon/sentry-native/sentry-native.c, src/daemon/sentry-native/sentry-native.h
=> Add sentry fatal message breadcrumb.

packaging/cmake/Modules/NetdataCompilerFlags.cmake
=> fix: correct typo in NetdataCompilerFlags

src/collectors/windows.plugin/perflib-hyperv.c
Reverts netdata/netdata#19623
Netdata crashes on a server without Hyper-V.
=> Revert "HyperV Adjusts (windows.plugin)"

src/exporting/graphite/metadata.yaml
v2 doesn't support Graphite protocol.
</details>
=> docs(exporting): remove influxdb (via graphite) exporter

src/exporting/graphite/metadata.yaml
=> docs(exporting): clarify graphite exporters

src/exporting/graphite/metadata.yaml
=> docs: add missing prop to graphite meta

src/libnetdata/log/nd_log-common.h, src/libnetdata/log/wevt_netdata_mc_generate.c
=> Revert "fix windows logs"

integrations/deploy.yaml, packaging/docker/README.md
=> docs: move /run/dbus mount to Docker recommended way

src/go/plugin/go.d/collector/k8s_state/charts.go, src/go/plugin/go.d/collector/k8s_state/collect.go, src/go/plugin/go.d/collector/k8s_state/collector_test.go, src/go/plugin/go.d/collector/k8s_state/metadata.yaml, src/go/plugin/go.d/collector/k8s_state/state.go, src/go/plugin/go.d/collector/k8s_state/update_deployment_state.go
=> improvement(go.d/k8sstate): add deployment conditions

src/health/health.d/k8sstate.conf
=> add k8s_state_deployment_condition_available alert

src/go/plugin/go.d/agent/jobmgr/dyncfg.go, src/go/plugin/go.d/agent/jobmgr/dyncfg_collector.go, src/go/plugin/go.d/agent/jobmgr/dyncfg_vnode.go
=> improvement(go.d dyncfg): add user to source

src/collectors/python.d.plugin/python.d.plugin.in, src/go/cmd/godplugin/config.go, src/go/cmd/godplugin/main.go, src/go/plugin/go.d/agent/agent.go, src/go/plugin/go.d/agent/jobmgr/di.go, src/go/plugin/go.d/agent/jobmgr/dyncfg_collector.go, src/go/plugin/go.d/agent/jobmgr/manager.go
=> chore: remove lock files from go.d/python.d

src/go/plugin/go.d/collector/k8s_state/collect.go, src/go/plugin/go.d/collector/k8s_state/collector_test.go
copy/paste error 😮‍💨 
</details>
=> fix(go.d/k8sstate): correct deployment conditions

src/go/plugin/go.d/agent/jobmgr/dyncfg_collector.go
=> improvement(go.d dyncfg): log collector dyncfg actions

src/go/plugin/go.d/agent/jobmgr/dyncfg_collector.go, src/go/plugin/go.d/agent/jobmgr/dyncfg_vnode.go
=> fix(go.d dyncfg): don't overwrite source

src/go/plugin/go.d/agent/jobmgr/manager_test.go
=> test(go.d dyncfg): fix tests

src/go/go.mod, src/go/otel-collector/exporter/journaldexporter/go.mod
=> build: change go.mod version to 1.23.6

src/collectors/freebsd.plugin/freebsd_devstat.c, src/collectors/freebsd.plugin/freebsd_getifaddrs.c, src/collectors/freebsd.plugin/freebsd_getmntinfo.c, src/collectors/freebsd.plugin/freebsd_sysctl.c
- Replace leftover `config_get_boolean_ondemand` calls with `inicfg_get_boolean_ondemand` on freebsd
- Compile and run on freebsd
=> Fix freebsd compilation

src/daemon/dyncfg/dyncfg-tree.c
=> improve dyncfg src type anon message

src/go/plugin/go.d/pkg/iprange/README.md, src/go/plugin/go.d/pkg/iprange/iterator.go, src/go/plugin/go.d/pkg/iprange/range.go, src/go/plugin/go.d/pkg/iprange/range_test.go
=> chore(go.d/pkg/iprange): add iterator

src/daemon/daemon-status-file.c, src/daemon/daemon-status-file.h, src/daemon/main.c, src/database/rrdhost-system-info.c, src/database/rrdhost-system-info.h
=> add host/os fields to status file

src/claim/claim-with-api.c, src/claim/cloud-conf.c, src/daemon/daemon-status-file.c, src/daemon/daemon-status-file.h, src/daemon/main.c, src/database/rrd.c, src/database/rrdhost-system-info.c, src/libnetdata/spawn_server/spawn_server_nofork.c, src/registry/registry.h, src/registry/registry_internals.c
=> daemon status improvements 3

src/daemon/daemon-status-file.c
=> Check for final step

src/daemon/daemon-shutdown.c, src/daemon/daemon-status-file.c, src/daemon/daemon-status-file.h, src/daemon/main.c, src/daemon/signals.c
=> Avoid post initialization errors repeateadly

packaging/windows/netdata.wxs.in
Some PR was merged breaking windows fresh installation. This PR address this issue.
1. Create installer
2. Do a fresh installation
</details>
=> Fix Fresh Installation on Microsoft

src/daemon/daemon-status-file.c
=> more status file annotations

src/daemon/buildinfo.h, src/daemon/config/netdata-conf-global.c, src/daemon/daemon-status-file.c, src/daemon/daemon-status-file.h
also fixed bug with multiple json version in the status file
=> status has install type

packaging/windows/WINDOWS_INSTALLER.md
=> docs: clarify Windows Agent limits on free plans

src/go/plugin/go.d/agent/agent.go
=> fix(go.d): ignore sigpipe to exit gracefully

src/daemon/daemon-status-file.c, src/daemon/daemon-status-file.h, src/daemon/signals.c
Also async safe calls for saving the status files
=> allow coredumps to be generated

src/daemon/analytics.c, src/database/rrdhost-system-info.c
=> more strict parsing of the output of system-info.sh

src/aclk/aclk_proxy.c, src/daemon/daemon-status-file.c, src/daemon/daemon-status-file.h, src/daemon/main.c, src/libnetdata/common.h, src/libnetdata/exit/exit_initiated.c, src/libnetdata/exit/exit_initiated.h, src/libnetdata/log/nd_log-stacktrace.c
=> status file improvements (dedup and signal handler use)

src/go/cmd/godplugin/config.go, src/go/cmd/godplugin/main.go, src/go/go.mod, src/go/go.sum, src/go/plugin/go.d/agent/agent.go, src/go/plugin/go.d/agent/discovery/manager.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/dockerd/target.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/netlisteners/target.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/config.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/discoverer.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/discoverer_test.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/entnum.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/sim_test.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/status.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/sysinfo.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/target.go, src/go/plugin/go.d/agent/discovery/sd/pipeline/accumulator.go, src/go/plugin/go.d/agent/discovery/sd/pipeline/config.go, src/go/plugin/go.d/agent/discovery/sd/pipeline/pipeline.go, src/go/plugin/go.d/agent/filepersister/persister.go, src/go/plugin/go.d/agent/jobmgr/filestatus.go, src/go/plugin/go.d/agent/jobmgr/manager.go, src/go/plugin/go.d/collector/snmp/charts.go, src/go/plugin/go.d/collector/snmp/collect.go, src/go/plugin/go.d/collector/snmp/collector.go, src/go/plugin/go.d/collector/snmp/collector_test.go, src/go/plugin/go.d/config/go.d/sd/snmp.conf, src/go/plugin/go.d/pkg/confopt/duration.go, src/go/plugin/go.d/pkg/confopt/duration_test.go
=> feat(go.d): add snmp devices discovery

src/go/plugin/go.d/config/go.d/sd/snmp.conf
=> chore(go.d/sd/snmp): comment out  defaults in snmp.conf

src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/discoverer.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/status.go, src/go/plugin/go.d/config/go.d/sd/snmp.conf
=> improvement(go.d/sd/snmp): support device cache ttl 0

src/daemon/daemon-status-file.c, src/daemon/daemon-status-file.h
=> status file timings per step

src/go/plugin/go.d/collector/nvidia_smi/charts.go, src/go/plugin/go.d/collector/nvidia_smi/collect.go, src/go/plugin/go.d/collector/nvidia_smi/gpu_info.go
=> fix(go.d/nvidia_smi): handle xml gpu_power_readings change

src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/config.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/discoverer.go
Forgot to add this check in #19756
</details>
=> fix(go.d/sd/snmp): use rescan and cache ttl only when set

src/go/plugin/go.d/agent/discovery/sd/discoverer/dockersd/docker.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/dockersd/dockerd_test.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/dockersd/sim_test.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/dockersd/target.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/k8ssd/config.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/k8ssd/kubernetes.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/k8ssd/kubernetes_test.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/k8ssd/pod.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/k8ssd/pod_test.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/k8ssd/service.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/k8ssd/service_test.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/k8ssd/sim_test.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/netlistensd/ll.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/netlistensd/netlisteners.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/netlistensd/netlisteners_test.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/netlistensd/sim_test.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/netlistensd/target.go, src/go/plugin/go.d/agent/discovery/sd/pipeline/config.go, src/go/plugin/go.d/agent/discovery/sd/pipeline/pipeline.go
=> chore(go.d/sd): rename discoverers pkgs

src/go/plugin/go.d/agent/discovery/sd/sd.go
=> fix(go.d/sd): fix logging cfg source when disabled

packaging/installer/kickstart.sh
=> kickstart: install native pkg on RPi2+

packaging/repoconfig/CMakeLists.txt, packaging/repoconfig/deb.changelog, packaging/repoconfig/netdata-deb-repo-priority, packaging/repoconfig/rpm.changelog
This should avoid issues with users making strange custom modifications to repository priorities, as well as issues with Ubuntu ESM repos having higher priority than the default.
n/a
=> Add repository priority configuration for DEB package repositories.

packaging/installer/functions.sh
- Don’t blindly trust that the service manager actually shut down the agent.
- Bump timeouts between each method of shutting down the agent to 30 seconds to make it more likely that the agent actually shuts down before we try to shut it down a different way.
- Add logic to handle different possible locations for netdatacli pipe.
Needs some manual testing to confirm that the new logic works.
=> Restructure shutdown logic used during updates.

src/go/plugin/go.d/collector/snmp/metadata.yaml
=> docs(go.d/snmp): add snmp discovery information

src/go/plugin/go.d/collector/k8s_state/charts.go, src/go/plugin/go.d/collector/k8s_state/collect.go, src/go/plugin/go.d/collector/k8s_state/collector_test.go, src/go/plugin/go.d/collector/k8s_state/metadata.yaml, src/go/plugin/go.d/collector/k8s_state/state.go, src/go/plugin/go.d/collector/k8s_state/update_cronjob_state.go, src/go/plugin/go.d/collector/k8s_state/update_job_state.go
=> improvement(go.d/k8s_state): add more CronJob metrics

packaging/dag/requirements.txt
To fix a dependabot alert. @vkalintiris, do you use dag? If not, please remove.
</details>
=> bump dag jinja to 3.1.6

src/go/plugin/go.d/collector/k8s_state/metadata.yaml, src/health/health.d/k8sstate.conf
=> add k8s_state_cronjob_last_execution_failed alert

src/go/plugin/go.d/collector/filecheck/config_schema.json
=> fix(go.d/filecheck): remove dyncfg path validation pattern 

src/libnetdata/os/machine_id.c
=> use notice log level for "machine ID found"

src/database/rrdset-index-id.c, src/database/rrdset-index-name.c, src/libnetdata/dictionary/dictionary.h
=> Revert "fix rrdset name crash on rrdset obsoletion"

src/go/plugin/go.d/collector/k8s_state/charts.go, src/go/plugin/go.d/collector/k8s_state/collect.go, src/go/plugin/go.d/collector/k8s_state/collector_test.go, src/go/plugin/go.d/collector/k8s_state/metadata.yaml, src/go/plugin/go.d/collector/k8s_state/state.go, src/go/plugin/go.d/collector/k8s_state/update_cronjob_state.go
=> improvement(go.d/k8state): add CronJob suspend status

src/daemon/daemon-service.h, src/daemon/daemon-shutdown-watcher.c, src/daemon/daemon-shutdown.c, src/daemon/main.c, src/database/contexts/api_v2_contexts.c, src/database/rrdfunctions.c, src/health/health_dyncfg.c, src/health/health_log.c, src/libnetdata/json/json-c-parser-inline.h, src/libnetdata/string/string.c, src/libnetdata/string/string.h, src/plugins.d/plugins_d.c, src/streaming/stream-connector.c, src/streaming/stream-receiver-connection.c, src/streaming/stream-receiver.c
=> free strings judy arrays to show leaked strings

src/exporting/prometheus/remote_write/remote_write_request.cc
SSIA.
- Build with bundled protobuf v30.0
- CI jobs.
=> Fix for building with protobuf 30.0

packaging/installer/netdata-updater.sh
Forgot to add in #19773
</details>
=> fix updating on RPi2+

.github/workflows/docker.yml, packaging/docker/Dockerfile
Add OCI labels, as I use `version` in scripts to determine whether to update automatically or wait for manual upgrade in case of new major versions.
</details>
=> Add oci meta info

packaging/installer/netdata-uninstaller.sh
Based on [this Discord discussion](https://discord.com/channels/847502280503590932/1349457259650088960/1349457259650088960).
</details>
=> netdata-uninstaller: improve input prompt with more descriptive guidance

src/collectors/macos.plugin/macos_fw.c
- Add labels.
- Fix title/family.
</details>
=> fix(macos.plugin): correct disks/network devices charts

src/collectors/freebsd.plugin/freebsd_devstat.c, src/collectors/freebsd.plugin/freebsd_getifaddrs.c, src/collectors/freebsd.plugin/freebsd_getmntinfo.c
- Add labels
- Remove instance-specific info from title.
</details>
=> fix(freebsd.plugin): correct disks/network devices charts

.github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/docker.yml, .github/workflows/go-tests.yml, .github/workflows/packaging.yml
The action has been compromised and thus should not be used.
n/a
=> Remove tj-actions/changed-files from CI jobs.

src/daemon/daemon-status-file.c
=> do not lose exit reasons

.github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/docker.yml, .github/workflows/go-tests.yml, .github/workflows/packaging.yml
=> ci: use step-security/changed-files

src/go/plugin/go.d/collector/snmp/metadata.yaml
=> docs(go.d/snmp): improve auto-detection section

src/daemon/daemon-status-file.c, src/daemon/daemon-status-file.h, src/daemon/sentry-native/sentry-native.c, src/daemon/signal-handler.c
=> daemon status 18b

src/go/go.mod, src/go/go.sum, src/go/plugin/go.d/collector/snmp/ddsnmp/load.go, src/go/plugin/go.d/collector/snmp/ddsnmp/load_test.go, src/go/plugin/go.d/collector/snmp/ddsnmp/profile.go, src/go/plugin/go.d/collector/snmp/ddsnmp/profile_test.go
=> chore(go.d/snmp/ddsnmp): use dd profile definition

src/daemon/config/netdata-conf-backwards-compatibility.c, src/daemon/daemon-shutdown.c, src/daemon/pulse/pulse-daemon-memory.c, src/web/api/web_api_v1.c
=> Revert "Fix compile without dbengine"

src/daemon/daemon-status-file.c, src/libnetdata/exit/exit_initiated.h
if the status has exited in it, the agent is successfully exited
=> fix reliability calculation

.github/codeql/c-cpp-config.yml, .github/workflows/codeql.yml
Covers both things bundled as part of the build process, and things we vendor. Security issues in this code should be handled upstream, not by us.
n/a
=> Exclude external code from CodeQL scanning.

src/daemon/daemon-status-file.c
On essentially all UNIX systems, including Linux, macOS, and FreeBSD, the `chmod()` function will follow symlinks if called on a symlink. This means that any code that uses `chmod()` to apply permissions to a known filename can be exploited to apply those same permissions to an arbitrary file on the system that the user the code is running as could call `chmod()` on by simply replacing the known file with a symlink pointing to the target file after the known file is created but before its permissions are modified.
Because we are already opening the file in question in this case, we should instead use `fchmod()` to modify the permissions via the file descriptor before closing the file, which is not vulnerable to this race condition.
Requires minimal manual testing to confirm that …
=> Fix TOCTOU race in daemon status file handling.

CMakeLists.txt, src/claim/claim-with-api.c, src/claim/cloud-conf.c, src/daemon/config/netdata-conf-global.c, src/daemon/config/netdata-conf-global.h, src/daemon/daemon-status-file.c, src/daemon/daemon-status-file.h, src/daemon/daemon.h, src/daemon/machine-guid.c, src/daemon/machine-guid.h, src/daemon/main.c, src/database/rrd.c, src/libnetdata/common.h, src/registry/registry.h, src/registry/registry_init.c, src/registry/registry_internals.c, src/registry/registry_internals.h
=> status file v21

src/daemon/daemon-status-file.c, src/daemon/daemon-status-file.h, src/libnetdata/memory/nd-mallocz.c, src/libnetdata/memory/nd-mallocz.h
=> status file 21b

CMakeLists.txt
=> Set default CMake build type to include debug info.

src/claim/claim-with-api.c
- Fix heap-buffer-overflow when processing rooms during claiming on startup
=> Fix claiming on startup

src/daemon/daemon-status-file.c, src/database/engine/cache.c, src/libnetdata/log/nd_log-stacktrace.c
=> status file 22b

.github/scripts/build-static.sh, .github/workflows/build.yml
Fixes issues in CI.
Static build CI passes on this PR.
=> Don’t skip building Go code on static builds.

packaging/installer/methods/kickstart.md
=> Doc Linux improved order in kickstart

packaging/installer/methods/ansible.md, packaging/installer/methods/aws.md, packaging/installer/methods/azure.md, packaging/installer/methods/kickstart.md, packaging/installer/methods/kubernetes.md
Ansible, Azure, Aws, Kickstart, K8s
Edited, rearranged order, fixed wording
=> Installation section Improvements

src/web/api/queries/rrdr.c
=> Revert "fix undefined"

packaging/docker/README.md, packaging/installer/methods/macos.md, packaging/installer/methods/no_ipv4.md, packaging/installer/methods/offline.md, packaging/installer/methods/packages.md
macOs, offline, ipv4, native packages, docker
Made the texts more concise, shorter, and used active language.
=> Installation + docker, improvements

src/daemon/daemon-status-file.c, src/daemon/daemon-status-file.h, src/daemon/sentry-native/sentry-native.c, src/database/engine/datafile.c, src/database/engine/datafile.h, src/database/engine/journalfile.c, src/database/engine/rrdengine.c, src/database/engine/rrdengineapi.c, src/database/sqlite/sqlite_metadata.c, src/libnetdata/worker_utilization/worker_utilization.c, src/libnetdata/worker_utilization/worker_utilization.h, src/plugins.d/pluginsd_internals.h
=> added worker last job id to status file

.github/CODEOWNERS
=> add kanelatechnical to CODEOWNERS

docs/deployment-guides/README.md, docs/deployment-guides/deployment-with-centralization-points.md, docs/deployment-guides/standalone-deployment.md
Deployment guides, standalone, deployment centralization points fixed
=> Deployment Guides Improved

src/go/plugin/go.d/collector/megacli/collect.go, src/go/plugin/go.d/collector/megacli/collector.go
=> fix(go.d/megacli): handle BBU hardware component is not present

src/collectors/cgroups.plugin/cgroup-discovery.c, src/database/rrddim.c, src/database/rrdset-collection.c, src/database/rrdset-index-id.c
=> Fix crashes No 3

CMakeLists.txt, src/collectors/systemd-journal.plugin/systemd-units.c, src/daemon/daemon-systemd-watcher.c, src/daemon/static_threads.c
=> Minor changes when handling systemd integration.

src/daemon/daemon-shutdown-watcher.c, src/daemon/status-file.c, src/daemon/status-file.h, src/libnetdata/log/nd_log-stacktrace.c
=> daemon status 24d

src/database/engine/pagecache.c
- Add additional checks to make sure calculated metric and metric data page regions are within the file size
=> Validate journal file headers to prevent invalid memory access

src/collectors/systemd-journal.plugin/systemd-internals.h, src/collectors/systemd-journal.plugin/systemd-journal-annotations.c, src/collectors/systemd-journal.plugin/systemd-journal-dyncfg.c, src/collectors/systemd-journal.plugin/systemd-journal-files.c, src/collectors/systemd-journal.plugin/systemd-journal-fstat.c, src/collectors/systemd-journal.plugin/systemd-journal-sampling.h, src/collectors/systemd-journal.plugin/systemd-journal-watcher.c, src/collectors/systemd-journal.plugin/systemd-journal.c, src/collectors/systemd-journal.plugin/systemd-main.c, src/collectors/systemd-journal.plugin/systemd-units.c, src/libnetdata/libjudy/judyl-typed.h
- Commented code has been removed (we can use git for that).
- Use appropriate name prefixes to easily identify their source (netdata vs libsystemd).
- Format the code.
- Mark as unused macro-expanded functions from judy.
- CI jobs.
=> Series of NFCs to make the code more maintainable.

src/daemon/status-file.c, src/daemon/status-file.h
=> daemon status 25

.github/scripts/docker-test.sh, .github/scripts/pkg-test.sh, .github/workflows/build.yml
=> More completely disable our own telemetry in CI.

src/go/plugin/go.d/agent/module/job.go
So it can be used by [Node Rule-Based Room Assignment](https://github.com/netdata/netdata/blob/master/docs/netdata-cloud/node-rule-based-room-assignment.md).
</details>
=> improvement(go.d): add `_hostname` label for virtual nodes

src/database/sqlite/sqlite_aclk.c
- When a host is deleted, stop any pending ACLK update timers
=> Check for host timer validity in ACLK synchronization

src/go/otel-collector/exporter/journaldexporter/convert.go, src/go/otel-collector/exporter/journaldexporter/convert_test.go, src/go/otel-collector/exporter/journaldexporter/exporter.go, src/go/otel-collector/exporter/journaldexporter/sys.go
=> chore(otel/journaldexporter): add trusted journald fields

src/database/engine/cache.c, src/database/engine/cache.h, src/database/engine/journalfile.c, src/database/engine/journalfile.h
- Handle out of memory when trying to create a new journval v2 file
=> Handle journal_v2 file creation failure due to OOM

src/database/engine/journalfile.c
=> trace crashes No 4

src/daemon/status-file-dmi.c, src/daemon/status-file.c, src/daemon/status-file.h, src/database/rrdhost-system-info.c
=> daemon status 26b

src/daemon/status-file-dmi.c, src/daemon/status-file.c
=> daemon status 26c

src/go/plugin/go.d/collector/megacli/collect_phys_drives.go, src/go/plugin/go.d/collector/megacli/collector_test.go, src/go/plugin/go.d/collector/megacli/testdata/mega-phys-drives-info-no-drives.txt
=> fix(go.d/megacli): handle Adapters with no drives

src/database/sqlite/sqlite_functions.c
- Automatic release of compiled statements should not happen if we have already closed all database connections
=> Fix releasing statements after databases are closed

src/libnetdata/log/nd_log-stacktrace.c
=> daemon status 26e

integrations/cloud-authentication/metadata.yaml
We have added support for OIDC Discovery, so we no longer need these three parameters
https://github.com/netdata/cloud-backend/issues/732
=> Remove unnecessary parameters for oidc configuration

src/collectors/log2journal/README.md
this is needed to comply with MDX 3.
=> nested code block in doc

.gitignore, packaging/tools/agent-events/.gitignore, packaging/tools/agent-events/run.sh, packaging/tools/agent-events/server.go, packaging/tools/agent-events/server_test.go
- Add strict JSON validation to correctly reject malformed input
- Modernize logging using structured logging (slog)
- Add comprehensive OTEL & Prometheus metrics
- Extract and include Cloudflare headers in output
- Implement graceful shutdown handling
- Add health endpoint with server status
- Improve error handling and status reporting
- Update tests to cover various scenarios and edge cases
- Update .gitignore to exclude agent-events binary and test files
=> Improve agent-events web server

.github/workflows/codeql.yml
=> ci: remove codeql-action build-mode none

src/go/plugin/go.d/collector/prometheus/charts.go
=> fix(go.d/prometheus): don't use "ratio" as unit

packaging/tools/agent-events/run.sh, packaging/tools/agent-events/server.go, packaging/tools/agent-events/server_test.go
1. Enhanced run.sh with multiple dedup keys and a dedicated log file
2. Added Cloudflare headers processing for all requests, not just successful ones
3. Implemented logging of duplicated requests to a separate file
4. Added health check endpoint improvements with more deduplication info
5. Improved test code structure with output capture
=> agent events No 7

src/database/engine/rrdengine.c, src/database/engine/rrdengineapi.c
Optimize metric retention loading during agent initialization to utilize all CPU cores.
=> Improve jv2 load

docs/alerts-and-notifications/creating-alerts-with-netdata-alerts-configuration-manager.md, docs/alerts-and-notifications/notifications/README.md, src/health/README.md, src/health/notifications/README.md
Improved the Alerts & Notifications documentation for clarity, structure, and user experience. Rewrote content for Netdata Cloud, Agent notifications, alert configuration, and troubleshooting. Added quick-starts, examples, and visual aids where helpful.
=> Alerts and Notifications

src/daemon/status-file.c, src/libnetdata/log/nd_log-stacktrace.c, src/libnetdata/worker_utilization/worker_utilization.c
have a more meaningful fatal.function on signals without a root cause
=> daemon status 27c

src/database/engine/journalfile.c, src/streaming/stream-replication-sender.c
=> Release memory after journalfile creation

src/daemon/protected-access.c, src/daemon/protected-access.h, src/database/engine/journalfile.c, src/database/engine/pagecache.c
- Replace single state with a stack of frames (up to 8 levels deep)
- Modified signal handler to find and recover from the correct nesting level
- Proper unwinding of frames when errors occur
- Extend API to require resource name and operation type for all callers
- Capture signal codes using SIGNAL_CODE type with human-readable representations
- Automatically log detailed error messages at the macro level
- Format errors with contextual information about signal, memory region and offsets
=> Protection access improvements 1

src/daemon/protected-access.h, src/database/engine/pagecache.c, src/database/engine/rrdengine.c
- Improve journal file access error logging 
- Handle corrupted journal files during retention calculation
=> Improve journal file access error logging protect retention recalculation

src/daemon/daemon-shutdown-watcher.c, src/daemon/daemon-shutdown.c, src/daemon/status-file.c, src/daemon/status-file.h, src/libnetdata/log/nd_log-stacktrace.c, src/libnetdata/log/nd_log.h
while shutting down, keep track of the shutdown timings
=> daemon status 27f

src/database/sqlite/sqlite_aclk.c
- Better coordination between the ACLK synchronization and ACLK MQTT threads during shutdown
=> Further improve ACLK synchronization shutdown

docs/netdata-agent/versions-and-platforms.md
=> docs: clarify static build transition process for EOL platforms

src/database/sqlite/sqlite_aclk.c
- Make sure to unblock the caller when removing a stale node that does not have a node info updater timer defined
This can affect the `netdatacli remove-stale-node ALL_NODES` command
=> Fix completion marking in ACLK cancel node update timer logic

src/daemon/win_system-info.c, src/daemon/win_system-info.h, src/libnetdata/os/os-windows-wrappers.h
Add detailed OS ID_LIKE values for Windows systems with:
- Better categorization of Windows versions
- Addition of edition information (Professional, Datacenter, etc.)
- Standardized format with capitalized words and dashes
=> feat(system-info): improve Windows OS detection and categorization

src/go/otel-collector/exporter/journaldexporter/config.go, src/go/otel-collector/exporter/journaldexporter/convert.go, src/go/otel-collector/exporter/journaldexporter/convert_test.go, src/go/otel-collector/exporter/journaldexporter/exporter.go, src/go/otel-collector/exporter/journaldexporter/factory.go, src/go/otel-collector/exporter/journaldexporter/journal_remote.go, src/go/otel-collector/exporter/journaldexporter/journal_remote_test.go, src/go/otel-collector/exporter/journaldexporter/journal_socket.go
Not a properly tested version. Will improve in the next PR.
</details>
=> chore(otel/journaldexporter): add socket/remote clients

src/database/engine/journalfile.c
- Protect the MRG population from corrupted data in the mmaped journal file that can lead to a crash
- The corrupted file will be ignored when populating the MRG
=> Handle corrupted journal data when populating the MRG during startup.

src/database/pattern-array.c, src/database/pattern-array.h
- Pattern array items should be evaluated  in order
=> Make sure pattern array items are added and evaluated in order

src/database/engine/datafile.c, src/database/engine/journalfile.c, src/database/engine/journalfile.h, src/database/engine/rrdengine.c, src/database/engine/rrdengine.h
- Better handling of errors when writing to datafiles and journalfile
- Fatal errors such as disk full / disk read only will not be retried
- Correctly update the current disk usage internal metrics
=> Improve error handling and logging for journal and data files

README.md
This commit updates the README file to improve grammar and enhance the overall clarity of the text.
</details>
=> docs: cleanup language and fix minor grammar issues

src/go/plugin/go.d/collector/apcupsd/collect.go
=> chore(go.d/apcupsd): log UPS response in debug mode

src/collectors/cgroups.plugin/sys_fs_cgroup.c
=> improvement(cgroups): filter systemd-nspawn payload by default

src/daemon/main.c, src/daemon/status-file.c, src/database/rrddim-backfill.c, src/database/sqlite/sqlite_metadata.c
- Fix compilation error when asked to compiled without DBENGINE
=> Fix compilation with DBENGINE disabled

src/health/schema.d/health%3Aalert%3Aprototype.json
[Reported on Discord](https://discord.com/channels/847502280503590932/1363903843020308520/1363903843020308520).
</details>
=> fix(dyncfg/health): correct db lookup absolute option name

docs/netdata-agent/versions-and-platforms.md
=> docs: update macOS/freeBSD versions in  Versions & Platforms

.github/data/distros.yml, packaging/installer/install-required-packages.sh
Add the following platforms:
- Alpine 3.21
- CentOS Stream 10
- Ubuntu 25.04
CI for the new platforms passes on this PR
=> Update platforms for CI and package builds.

.github/workflows/build.yml, netdata.spec.in, packaging/check-for-go-toolchain.sh, src/go/otel-collector/exporter/netdataexporter/go.mod, src/go/otel-collector/exporter/netdataexporter/go.sum
=> build(deps): update go toolchain to v1.24.2

src/database/rrdlabels.c
- Fix memory accounting for labels (drops to negative)
=> Fix labels memory accounting

src/go/go.mod, src/go/otel-collector/exporter/journaldexporter/go.mod, src/go/otel-collector/exporter/netdataexporter/go.mod
=> bump go mod 1.24.0

.github/workflows/release.yml
It fails regularly for unknown reasons, but retries usually get it working.
n/a
=> Retry nightly changelog generation.

src/database/engine/cache.c, src/libnetdata/threads/threads.c
=> improve pgc fatal errors

src/collectors/all.h, src/ml/ad_charts.cc, src/ml/ml.cc, src/ml/ml_host.h, src/ml/ml_public.cc
=> Group anomaly rate per chart context instead of type.

src/libnetdata/log/nd_log.c
Fix this:
```
==2446760==ERROR: AddressSanitizer: heap-use-after-free on address 0x60f03c169f30 at pc 0x558efd5f0fe3 bp 0x7fba989fbfd0 sp 0x7fba989fbfc8
READ of size 1 at 0x60f03c169f30 thread T2678
#0 0x558efd5f0fe2 in nd_logger_logfmt /usr/src/netdata-ktsaou.git/src/libnetdata/log/nd_log-format-logfmt.c:91
#1 0x558efd5f2ae7 in nd_logger_file /usr/src/netdata-ktsaou.git/src/libnetdata/log/nd_log-to-file.c:34
#2 0x558efd83b8ec in nd_logger_log_fields /usr/src/netdata-ktsaou.git/src/libnetdata/log/nd_log.c:218
#3 0x558efd83d94c in nd_logger.constprop.0 /usr/src/netdata-ktsaou.git/src/libnetdata/log/nd_log.c:381
#4 0x558efd4c8595 in netdata_logger /usr/src/netdata-ktsaou.git/src/libnetdata/log/nd_log.c:423
#5 0x558efcad681d in stream_receiver_replication_check_from_poll …
```
=> ensure atomicity when logging pending message

src/libnetdata/log/nd_log.c
fixes recursive lock introduced with: https://github.com/netdata/netdata/pull/20185
=> fix recursive lock

src/libnetdata/log/nd_log.c
fix use-after-free
fixes https://github.com/netdata/netdata/pull/20185 which has been fixed by https://github.com/netdata/netdata/pull/20188
=> ensure atomicity when logging pending message 3/3

src/collectors/systemd-journal.plugin/README.md
This PR improves the documentation for systemd journal logs, addressing formatting and clarity.
=> Improve systemd journal logs documentation

src/collectors/windows.plugin/perflib-web-service.c
This PR reorganizes the current IIS file, establishing a unified standard across the entire codebase.
1. Compile the branch.
2. Generate a binary.
3. Install it on a host running `IIS`.
4. Open the Netdata dashboard in one tab and request data from `IIS` in another.
</details>
=> Reorganize code (IIS)

src/collectors/proc.plugin/proc_loadavg.c, src/daemon/pulse/pulse-workers.c, src/database/rrddim.c, src/database/rrddim.h, src/database/rrdset-index-id.c, src/database/rrdset-index-id.h, src/health/health_variable.c, src/ml/ml_dimension.h, src/plugins.d/pluginsd_internals.h, src/streaming/stream-replication-sender.c, src/streaming/stream-sender-execute.c, src/web/api/queries/backfill.c, src/web/api/v1/api_v1_alarms.c, src/web/api/v1/api_v1_badge/web_buffer_svg.c, src/web/api/v1/api_v1_charts.c, src/web/api/v1/api_v1_data.c, src/web/server/web_client.c
rrdset/rrddim find calls now have an extra option to enable/disable searching for obsolete metadata
fixes https://github.com/netdata/netdata/pull/20200 https://github.com/netdata/netdata/pull/20196
=> rrd metadata search fix

src/database/engine/rrdengine.c
- Avoid indexing while deleting files
- Add macro to make tests more intuitive
=> Avoid indexing journal files when db rotation is running

src/health/health_log.c
- Defer cleanup if a write lock cannot be acquired
=> Improve health log cleanup

src/database/engine/journalfile.c
=> fix crashes 7

src/database/engine/journalfile.c
=> fix crashes 8

src/database/engine/journalfile.c
- Fix crash if datafile is null
=> Fix potential null pointer dereference when accessing journalfile

src/daemon/status-file-product.c, src/daemon/status-file.h, src/daemon/system-info.sh, src/plugins.d/pluginsd_functions.c
=> status file 28

docs/developer-and-contributor-corner/dyncfg.md
=> docs: rename DynCfg developer doc to avoid title conflict

src/database/rrdhost-system-info.c, src/database/rrdhost-system-info.h, src/web/api/v2/api_v2_claim.c
- Detect localhost in docker and show correct command to get the session claim id
Fixes #20214
=> Session claim id in docker

src/go/plugin/go.d/collector/snmp/collect_if_mib.go
=> fix(go.d/snmp): use ifDescr for interface name if ifName is empty

README.md
> remove GH alerts syntax from FAQ
Doesn't work in expandable sections.
</details>
=> docs: fix license link and remove GH alerts syntax from FAQ

src/go/plugin/go.d/README.md
Sync the part `To debug specific module` of https://github.com/netdata/netdata/blob/v2.5.1/src/collectors/go.d.plugin/README.md with https://github.com/netdata/netdata/blob/v2.5.1/src/collectors/python.d.plugin/README.md for abosult path to `plugins.d/go.d.plugin`
</details>
=> Clearify the path of `plugins.d/go.d.plugin` in docs

src/go/plugin/go.d/README.md
=> docs: reword go.d Troubleshooting section for clarity

README.md
Please check CNCF properly renders in both dark and light themes, same for the mermaid fc. I added an origin story in the who we are section and updated the menu bar.
=> Update Netdata README with improved structure

src/collectors/windows.plugin/metadata.yaml
=> docs: update mssql meta

src/collectors/statsd.plugin/README.md
=> Improved StatsD documentation

src/aclk/aclk_tx_msgs.c, src/collectors/cgroups.plugin/sys_fs_cgroup.c, src/collectors/statsd.plugin/statsd.c, src/daemon/daemon-shutdown.c, src/database/sqlite/sqlite_metadata.c, src/exporting/exporting_engine.c, src/health/health_event_loop.c, src/libnetdata/threads/threads.c, src/web/server/static/static-threaded.c
- Signal services to terminate
- Join all threads during shutdown
=> Improve agent shutdown

src/go/plugin/go.d/agent/module/job.go
=> fix(go.d): sanitize vnode labels before creating vnode

src/database/rrd-retention.c, src/database/rrd-retention.h
- Simplify code -- this will also silence some coverity issues reported
=> Minor code adjustments

docs/security-and-privacy-design/README.md
Updating SOC2 compliance status
=> Updating SOC2 compliance status

src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/sysinfo.go
=> fix(go.d/snmp): replace newline control chars with spaces in system info

docs/nodes-ephemerality.md, src/streaming/README.md
=> docs: fix `<br>` in streaming

src/database/sqlite/sqlite_metadata.c
- Check if metasync shutdown command submission failed (event loop is shutting down) and  proceed with shutdown anyway
=> Improve metasync shutdown

src/daemon/daemon.c
=> Improve user transition log messages

src/streaming/README.md
Erasing a space, obliterating anything that occupied that space as well.
</details>
=> docs: fix tip in streaming readme

docs/netdata-assistant.md
Fixed netlify build error.
</details>
=> docs: fix netdata-assistant.md

.github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/docker.yml, .github/workflows/packaging.yml
=> ci: ignore changes in src/go/otel-collector/release-config.yaml.in

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_generic-if.yaml
pass on the yaml file, as we said, one yaml per PR
=> SNMP: _generic-if.yaml pass

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_generic-ospf.yaml
=> generic-ospf.yaml pass

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_generic-ip.yaml
=> _generic-ip.yaml

src/go/plugin/go.d/agent/jobmgr/dyncfg_collector.go
=> fix(go.d/dyncfg): fix duplicate potential "name" in userconfig action

src/go/plugin/go.d/config/go.d/sd/net_listeners.conf
=> improvement(go.d/sd): better prometheus exporters detection

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_generic-ucd.yaml
=> SNMP: _generic-ucd.yaml

src/go/plugin/go.d/agent/confgroup/config.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/dockersd/docker.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/dockersd/dockerd_test.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/k8ssd/kubernetes.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/netlistensd/netlisteners.go, src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/sim_test.go, src/go/plugin/go.d/agent/discovery/sd/model/tags.go, src/go/plugin/go.d/collector/apcupsd/collect.go, src/go/plugin/go.d/collector/bind/collect.go, src/go/plugin/go.d/collector/boinc/client.go, src/go/plugin/go.d/collector/dnsquery/init.go, src/go/plugin/go.d/collector/docker/collect.go, src/go/plugin/go.d/collector/dockerhub/charts.go, src/go/plugin/go.d/collector/elasticsearch/collect.go, src/go/plugin/go.d/collector/k8s_state/discover_kubernetes.go, src/go/plugin/go.d/collector/mysql/collector.go, src/go/plugin/go.d/collector/postgres/collector.go, src/go/plugin/go.d/collector/prometheus/charts.go, src/go/plugin/go.d/collector/samba/charts.go, src/go/plugin/go.d/collector/samba/collect.go, src/go/plugin/go.d/collector/varnish/collect.go
=> chore(go.d): fix some golangcilint warning

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_cisco-voice.yaml
@ilyam8 left a comment in there for a metric I am not sure will work
=> _cisco-voice.yaml

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_cisco-wlc.yaml
families here were weird, Cisco has acquired Airespace, so I was going back and forth between a Cisco prefix on the family. Rest comes from reading the description that the browser gives and making sense of the metric
</details>
=> SNMP: _cisco-wlc.yaml

src/go/otel-collector/exporter/netdataexporter/convert.go
=> chore(otel.plugin): fix building

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_cisco-ipsec-flow-monitor.yaml
=> SNMP: _cisco-ipsec-flow-monitor.yaml

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_fortinet-fortigate-vpn-tunnel.yaml
=> SNMP: _fortinet-fortigate-vpn-tunnel.yaml

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_fortinet-fortigate-cpu-memory.yaml
=> SNMP: _fortinet-fortigate-cpu-memory.yaml

src/go/otel-collector/builder-config.yaml, src/go/otel-collector/release-config.yaml.in
Needed for developing
</details>
=> chore(otel.plugin): add more receivers/exporter

src/go/plugin/go.d/config/go.d/snmp.profiles/default/aruba-switch.yaml
=> SNMP: aruba-switch.yaml

src/go/plugin/go.d/collector/httpcheck/collect.go
Related [topic on Discord](https://discord.com/channels/847502280503590932/1378760656366469130/1378760656366469130).
</details>
=> improvement(go.d/httpcheck): add resp validation debug logging

src/go/cmd/godplugin/main.go, src/go/plugin/go.d/agent/agent.go, src/go/plugin/go.d/agent/jobmgr/manager.go, src/go/plugin/go.d/cli/cli.go
Related [topic on Discord](https://discord.com/channels/847502280503590932/1378760656366469130/1378760656366469130).
</details>
=> feat(go.d): allow to debug a specific job

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_juniper-firewall.yaml
=> SNMP: _juniper-firewall.yaml

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_juniper-userfirewall.yaml
=> SNMP: _juniper-userfirewall.yaml

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_juniper-scu.yaml
SCU = Source Class Usage
</details>
=> SNMP: _juniper-scu.yaml

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_juniper-dcu.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/_juniper-scu.yaml
DCU = Destination Class Usage
the table is per interface and per address family (I guess one interface has N address families)
</details>
=> SNMP: _juniper-dcu.yaml

src/database/contexts/rrdcontext-queues.c
- Adjust condition to remove contexts from the hub queue
=> Fix context updates

src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collect_device_meta.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collect_scalar.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector_test.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/utils.go
Metrics mapping can be:
- int->string
- string->int
- int->int
</details>
=> chore(go.d/ddsnmp): correctly handle all mapping types

packaging/windows/WINDOWS_INSTALLER.md, packaging/windows/netdata.wxs.in
Update the Windows Installer to fix an issue with nightly updates. 
1. Check CI.
2. Take a look in grammar.
</details>
=> update_installer: Update remove instruction

src/go/plugin/go.d/collector/snmp/charts.go, src/go/plugin/go.d/collector/snmp/collect.go, src/go/plugin/go.d/collector/snmp/collect_profiles.go, src/go/plugin/go.d/collector/snmp/collector.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddprofiledefinition/metrics.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collect_scalar.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector.go
=> feat(go.d/snmp): enable profile scalar metrics collection

integrations/templates/troubleshooting.md
Merge after #20394 is included in stable release.
</details>
=> docs(go.d): add example how to debug a specific job

src/go/plugin/go.d/collector/snmp/ddsnmp/profile.go
=> chore(go.d/ddsnmp): lazy ddsnmp profile loading

src/collectors/windows.plugin/README.md, src/collectors/windows.plugin/metadata.yaml
This PR adds supplementary metadata information, which is also documented in the `README.md` file.
1. Verify CI and file format.
</details>
=> Update MSSQL Metadata

src/go/plugin/go.d/config/go.d/snmp.profiles/default/mikrotik-router.yaml
=> update ddsnmp mikrotik-router.yaml

src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector.go, src/go/plugin/go.d/config/go.d/snmp.profiles/default/mikrotik-router.yaml
=> improvement(go.d/ddsnmp): use dev type and vendor from meta for family

src/go/plugin/go.d/collector/snmp/charts.go, src/go/plugin/go.d/collector/snmp/collect_profiles.go, src/go/plugin/go.d/collector/snmp/collector.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collect_table.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector_test.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/table_cache.go, src/go/plugin/go.d/config/go.d/snmp.profiles/default/_generic-if.yaml
Table metrics collection is still disabled. Will be enabled for all users after additional testing.
</details>
=> improvement(go.d/snmp): create table charts

src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/table_cache.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/table_cache_test.go
=> chore(go.d/ddsnmp): add dependency-based expiration to table cache

src/go/plugin/go.d/collector/redis/init.go
=> fix(go.d/redis): don't clear tls for rediss

src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collect_table.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector_test.go
=> chore(go.d/ddsnmp): collect cross-table metrics and tags

packaging/windows/netdata.wxs.in
After running a series of tests during development, I observed that a change introduced in [this PR](https://github.com/netdata/netdata/pull/20418) is not entirely necessary. The only required modification to ensure a proper update is the instruction added to the manual. Therefore, I am reverting to the previous option.
1. Check CI.
</details>
=> Modify Uninstall Action (windows.installer)

src/go/plugin/go.d/collector/snmp/collect_profiles.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collect_table.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector_test.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/table_cache.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/table_cache_test.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/utils.go
=> chore(go.d/ddsnmp): fix table metrics collection

src/go/plugin/go.d/agent/discovery/sd/discoverer/snmpsd/sysinfo.go, src/go/plugin/go.d/agent/module/job.go, src/go/plugin/go.d/collector/snmp/charts.go, src/go/plugin/go.d/collector/snmp/collect_if_mib.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/utils.go
=> chore(go.d/ddsnmp): better label values sanitization

src/go/plugin/go.d/config/go.d/snmp.profiles/default/mikrotik-router.yaml
=> fix snmp prof mikrotik mem tagging

src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collect_table.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector_test.go
=> chore(go.d/ddsnmp): fix table collection with caching

docs/learn/mcp.md
=> docs: add Netdata MCP Server preview announcement

src/database/sqlite/sqlite_metadata.c
- Fix coverity issues 471886, 471887, 471888
Cleanup pending structures if we timeout during shutdown of metadata sync
=> Cleanup pending statements during shutdown

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_base.yaml
for system uptime monitoring
</details>
=> improve(go.d/snmp-profiles): Add hrSystemUptime metric

src/go/plugin/go.d/collector/snmp/ddsnmp/profile.go, src/go/plugin/go.d/collector/snmp/ddsnmp/profile_test.go
=> improve(go.d/snmp-profiles): metrics deduplication

src/go/plugin/go.d/collector/snmp/ddsnmp/profile.go
=> upd generic check in snmp prof metrics deduplication

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_generic-if.yaml
=> update units in _generic-if.yaml

src/go/plugin/go.d/collector/snmp/collect.go
=> improve(go.d/snmp): log device profiles matched by sysObjectID

src/database/sqlite/vendored/sqlite3.h
- Update sqlite library version 3.49.1 to 3.50.1
=> Update SQLITE to version 3.50.1

src/database/engine/rrdengine.h, src/database/engine/rrdengineapi.c
- No need to load first and last files
- One load opcode is used (one completion is needed)
=> Simplify MRG loading mechanism logic

src/go/plugin/go.d/collector/smartctl/charts.go, src/go/plugin/go.d/collector/smartctl/collect.go, src/go/plugin/go.d/collector/smartctl/collector.go, src/go/plugin/go.d/collector/smartctl/collector_test.go, src/go/plugin/go.d/collector/smartctl/exec.go, src/go/plugin/go.d/collector/smartctl/init.go, src/go/plugin/go.d/collector/smartctl/scan.go, src/go/plugin/go.d/collector/smartctl/smart_device.go
=> improve(go.d/smartctl): enable direct smartctl execution on non-Linux

src/daemon/commands.c, src/daemon/commands.h
- Add `node-update-info` cli command to schedule an update to Netdata cloud
=> Add CLI command to schedule update information

src/daemon/commands.c, src/database/sqlite/sqlite_metadata.c
- Add defines for some cleanup statements
=> Add defines for cleanup statements

src/go/plugin/go.d/collector/snmp/charts.go, src/go/plugin/go.d/collector/snmp/ddsnmp/transform.go
=> ddsnmp add pow transform func and allow mapping duplicate values

src/go/plugin/go.d/config/go.d/snmp.profiles/default/3com-huawei.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/3com.yaml
=> SNMP: 3com profiles

src/go/plugin/go.d/config/go.d/snmp.profiles/default/avaya-aura-media-server.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/avaya-cajun-switch.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/avaya-media-gateway.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/avaya-nortel-ethernet-routing-switch.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/avaya.yaml
=> SNMP: avaya profiles

src/go/plugin/go.d/config/go.d/snmp.profiles/default/brother-net-printer.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/brother.yaml
=> SNMP: brother profile

src/go/plugin/go.d/config/go.d/snmp.profiles/default/barracuda-cloudgen.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/barracuda.yaml
@ilyam8 Barracuda have a very weird MIB and I could not find descriptions for many things. I added a TODO comment everywhere that was needed.
</details>
=> SNMP: barracuda Profiles

README.md
=> docs: fix 404 link in README.md

src/go/plugin/go.d/collector/snmp/collect_profiles.go, src/go/plugin/go.d/config/go.d/snmp.profiles/default/_generic-host-resources-base.yaml
=> small snmp-related changes

src/go/plugin/go.d/config/go.d/snmp.profiles/default/mikrotik-router.yaml
=> improve mikrotik-router snmp profile

src/go/plugin/go.d/collector/snmp/collect.go, src/go/plugin/go.d/collector/snmp/config.go, src/go/plugin/go.d/collector/snmp/config_schema.json, src/go/plugin/go.d/collector/snmp/testdata/config.json, src/go/plugin/go.d/collector/snmp/testdata/config.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/_generic-tcp.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/_generic-udp.yaml
=> chore(go.d/snmp): add disable_legacy_collection option

src/database/sqlite/sqlite_metadata.c
- Running workers that store metadata should always respect the shutdown request
=> Metadata worker should respect shutdown request

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_generic-if.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/_generic-ip.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/cisco-nexus.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/netapp.yaml
=> improve netapp snmp profile

src/aclk/mqtt_websockets/mqtt_ng.c
- Fix unused packet ID generation to ensure unique values
=> Improve packet ID generation

src/database/engine/datafile.c, src/database/engine/datafile.h, src/database/engine/journalfile.c, src/database/engine/rrdengine.c, src/database/engine/rrdengine.h, src/database/engine/rrdengineapi.c
- Datafiles in judyL arrays instead of llinked list
- Code cleanup
=> Rework datafiles

src/aclk/mqtt_websockets/mqtt_wss_client.c
- Improve memory allocation and handling for proxy credentials in MQTT WSS  client (CID 451575)
- Handle case where password is not specified
=> Additional checks for ACLK proxy setting

src/go/plugin/go.d/config/go.d/snmp.profiles/default/_hp-driver-stats.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/_intel-lan-adapters.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/dell-poweredge.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/synology-disk-station.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/tp-link.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/tripplite-pdu.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/tripplite-ups.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/tripplite.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/ubiquiti-unifi.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/velocloud-edge.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/vertiv-liebert-ac.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/vertiv-watchdog.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/vmware-esx.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/watchguard.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/western-digital-mycloud-ex2-ultra.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/zebra-printer.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/default/zyxel-switch.yaml
=> SNMP Profiles pass ep1

src/libnetdata/completion/completion.c
- Calculate maximum deadline in advance
- Simplified calculation of remaining timeout to uv_cond_timedwait
=> Improve job completion handling with timeout mechanism

docs/netdata-cloud/README.md
=> docs: fix "Unsupported markdown: list" in NC readme diagram

src/database/engine/datafile.c, src/database/engine/datafile.h, src/database/engine/rrdengine.c
- Add a missing lock during new datafile creation
=> Fix datafile creation race condition

src/collectors/charts.d.plugin/charts.d.plugin.in
=> chore(charts.d): suppress broken pipe error from echo during cleanup

docs/ml-ai/ai-chat-netdata/vs-code.md
=> docs: update continue ext setup

.gitignore, docs/ml-ai/ai-chat-netdata/vs-code.md
=> docs: fix file location in continue setup

src/plugins.d/FUNCTION_UI_DEVELOPER_GUIDE.md, src/plugins.d/FUNCTION_UI_REFERENCE.md
=> Escape < character in plaintext

src/go/plugin/go.d/collector/snmp/collect.go, src/go/plugin/go.d/collector/snmp/collect_profiles.go, src/go/plugin/go.d/collector/snmp/ddsnmp/ddsnmpcollector/collector.go
=> improve(go.d/snmp): add profile device meta to vnode labels

src/aclk/aclk.c, src/aclk/mqtt_websockets/mqtt_ng.c
- Increase MQTT buffer size fr parent agent
- Implemented packet timeout tracking to prevent resource leaks
- Added timeout monitoring in the message handling loop to detect and handle stalled packets
=> Detect missing ACLK MQTT packet acknowledgents

docs/deployment-guides/README.md, docs/deployment-guides/deployment-strategies.md, docs/deployment-guides/deployment-with-centralization-points.md, docs/deployment-guides/standalone-deployment.md, docs/nodes-ephemerality.md, docs/observability-centralization-points/README.md, docs/observability-centralization-points/best-practices.md, src/streaming/README.md
Reverts netdata/netdata#20712
Will be merged next week as additional changes to the learn repository are required.
=> Revert "Deployment Guides: add and update documentation for deployment strate"

src/database/sqlite/sqlite_functions.c
- During shutdown, do not allow threads to attempt to finalize statements if we have closed the databases
=> Add additional database checks during shutdown 

packaging/makeself/bundled-packages.version
=> build(deps): bump openssl and curl version in static build

src/streaming/stream-sender-api.c
- Fix condition to startup SNDR thread (resolves CID 487465)
=> Fix SNDR thread startup

src/collectors/ebpf.plugin/ebpf.c, src/collectors/ebpf.plugin/ebpf.h, src/collectors/ebpf.plugin/ebpf_cachestat.c, src/collectors/ebpf.plugin/ebpf_cgroup.c, src/collectors/ebpf.plugin/ebpf_dcstat.c, src/collectors/ebpf.plugin/ebpf_disk.c, src/collectors/ebpf.plugin/ebpf_fd.c, src/collectors/ebpf.plugin/ebpf_filesystem.c, src/collectors/ebpf.plugin/ebpf_functions.c, src/collectors/ebpf.plugin/ebpf_hardirq.c, src/collectors/ebpf.plugin/ebpf_mdflush.c, src/collectors/ebpf.plugin/ebpf_mount.c, src/collectors/ebpf.plugin/ebpf_oomkill.c, src/collectors/ebpf.plugin/ebpf_process.c, src/collectors/ebpf.plugin/ebpf_shm.c, src/collectors/ebpf.plugin/ebpf_socket.c, src/collectors/ebpf.plugin/ebpf_softirq.c, src/collectors/ebpf.plugin/ebpf_swap.c, src/collectors/ebpf.plugin/ebpf_sync.c, src/collectors/ebpf.plugin/ebpf_vfs.c, src/database/rrdfunctions-inflight.c, src/libnetdata/functions_evloop/functions_evloop.c, src/libnetdata/locks/benchmark-rw.c, src/libnetdata/locks/locks.c, src/libnetdata/locks/locks.h, src/ml/ml_queue.cc, src/ml/ml_queue.h
- Switch 
pthread mutex init,lock,unlock,destroy to netdata ones
pthread cond init, wait, signal,destroy to netdata ones
=> Use netdata mutex cond and lock

src/aclk/mqtt_websockets/mqtt_wss_client.c
- Remove redundant defines (exist already)
Fixes #20736
=> Remove redundant defines

src/collectors/ebpf.plugin/ebpf.h, src/libnetdata/functions_evloop/functions_evloop.h, src/libnetdata/locks/benchmark.c
- Fix remaining cases for pthread_mutex_t and pthread_cond_t
=> Change remaining pthread_ cases

.gitignore, docs/streaming-routing.md
@Ancairon @kanelatechnical I think this should added somewhere in metrics centralization points.
=> streaming routing documentation

src/go/plugin/go.d/collector/snmp/collect.go
=> chore(go.d/snmp): add _clean_hostname host label

src/go/plugin/go.d/collector/snmp/collect.go
UI will dynamicly construct the name
</details>
=> chore(go.d/snmp): update hostname to not include IP

src/go/plugin/go.d/collector/ap/init.go, src/go/plugin/go.d/collector/nvidia_smi/init.go, src/go/plugin/go.d/collector/postfix/init.go, src/go/plugin/go.d/collector/zfspool/init.go, src/go/plugin/go.d/pkg/pathvalidate/validate_stub.go, src/go/plugin/go.d/pkg/pathvalidate/validate_unix.go
=> fix(go.d): validate custom binary path

src/aclk/mqtt_websockets/mqtt_ng.c
- Store the timeout in 32 bit to avoid corruption possible corruption in 32 bit systems
=> Fix packet timeout handling

src/go/plugin/go.d/collector/memcached/metadata.yaml
Related #20779
@luisj1983 hey, can you verify the instructions?
</details>
=> docs(go.d/memcached): add UNIX socket access prerequisite

src/go/plugin/go.d/collector/mysql/metadata.yaml
Fixes netdata/learn#2518
</details>
=> docs(go.d/mysql): add MariaDB 10.5.9+ SLAVE MONITOR privilege

src/database/rrdhost.h, src/database/sqlite/sqlite_aclk.c, src/database/sqlite/sqlite_aclk_node.c, src/plugins.d/pluginsd_parser.c
- Virtual node inherits the version of the parent agent
=> Virtual node version adjustment

src/go/plugin/go.d/pkg/pathvalidate/validate_stub.go
Forgot to add in #20798
</details>
=> fix pathvalidate non unix

src/aclk/mqtt_websockets/mqtt_ng.c
- Fix ping latency calculation
=> Fix ping latency calculation

src/aclk/aclk.c, src/aclk/mqtt_websockets/aclk_mqtt_workers.h, src/aclk/mqtt_websockets/mqtt_ng.c
- Add jobs to monitor memory reclamation and buffer compact events in the `workers aclk`
-  dimensions `compact` and `reclaim`
=> Monitor memory reclamation and buffer compact

src/daemon/pulse/pulse-network.c
- Move latency chart under the aclk online check
=> Render latency chart if ACLK online

src/go/plugin/go.d/config/go.d/snmp.profiles/meta_overrides.yaml
=> improve(go.d/snmp): add more models to meta_overrides.yaml

.github/data/distros.yml, packaging/docker/Dockerfile
=> Revert "Switch to a Debian 13 base for our Docker images."

src/go/plugin/go.d/config/go.d/snmp.profiles/metadata/cisco.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/metadata/huawei.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/metadata/other.yaml
Closes #20859
Closes #20858
Closes #20853
I'm copying updates from Copilot PRs because CLA is a hard requirement for merging PRs and I don't know how to work around it for Copilot yet.
</details>
=> improve(go.d/snmp): update snmp meta copilot

src/go/plugin/go.d/agent/module/job.go
=> fix(go.d): create vnode internal data_collection_status charts in the main context

src/go/plugin/go.d/pkg/dockerhost/dockerhost.go
Fixes a race condition in the Docker exec function that could cause a panic when writing to a closed channel and potential goroutine leak on context cancellation.
</details>
=> fix(go.d): fix goroutine leak and panic risk in Docker exec

src/go/plugin/go.d/config/go.d/snmp.profiles/metadata/other.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/metadata/tplink.yaml, src/go/plugin/go.d/config/go.d/snmp.profiles/metadata/zyxel.yaml
=> improve(go.d/snmp): update tplink snmp meta

src/go/plugin/go.d/config/go.d/snmp.profiles/default/mikrotik-router.yaml
Found that switch (CSS326-24G-2S+, SwOS) has it.
</details>
=> improve(go.d/snmp): add mikrotik mtxrHlProcessorTemperature

docs/troubleshooting/custom-investigations.md, docs/troubleshooting/troubleshoot.md
Structure to be published: 
[AI & ML]
-AI-Powered Alert Troubleshooting
-Custom Investigation
In AI powered alert troubleshooting please add screenshots as they appear in https://www.netdata.cloud/blog/automated-alert-troubleshooting/ (I have marked where)
=> Troubleshooting: add troubleshoot and custom investigations docs

src/go/plugin/go.d/config/go.d/snmp.profiles/metadata/allied.yaml
=> improve(go.d/snmp): update Allied Telesis meta

src/go/plugin/go.d/collector/snmp/config_schema.json
=> improve(go.d/snmp): make snmp v3 auth and priv keys hidden in UI

docs/Demo-Sites.md
- make sure its clickable
- currently does not seem to be clickable here https://learn.netdata.cloud/docs/live-demo
</details>
=> Update demo link formatting in documentation

packaging/installer/netdata-updater.sh
=> fix(netdata-updater): resolve "run: command not found" error in offline install

src/go/plugin/go.d/collector/weblog/config_schema.json
So it can work on Win
</details>
=> fix(go.d/weblog): remove path pattern validation in dyncfg

src/database/sqlite/vendored/sqlite3.h
- Update sqlite to version 3.50.4
=> Update sqlite to version 3.50.4

.github/workflows/trigger-learn-update.yml
=> Add map.csv to triggers for Docs ingest workflow

integrations/templates/setup.md, integrations/templates/setup/sample-go-config.md, src/go/plugin/go.d/collector/snmp/metadata.yaml
This PR improves go.d collector documentation consistency and accuracy:
- **Restructured Setup section**
- Added a comparison table at the start of Setup to highlight UI vs File configuration paths.
- Links directly to the detailed “via UI” and “via File” sections.
- **Added SNMP prerequisites**
- **Fixed SNMP Options issues**
</details>
=> docs: restructure Setup, update SNMP prerequisites, and fix SNMP options

integrations/gen_docs_integrations.py
This PR improves the `get_doc_integrations.py` script by adding a `-c` flag to regenerate documentation for a specific collector only.
Changes:
- Added `-c <plugin/module>` argument (e.g., `-c go.d.plugin/snmp`).
- When `-c` is used:
- Only the target collector’s integrations/ directory is cleaned and regenerated.
- All other docs remain untouched.
- If the provided collector does not exist:
- The script prints a clear message (`No matching collector found for: <name>`) and exits gracefully without making changes.
- Running without `-c` preserves the current behavior (full cleanup and regeneration of all docs).
</details>
=> chore: add `-c` option to gen docs for a single collector

src/collectors/systemd-journal.plugin/README.md
=> Document accuracy implications of sampling algorithm

.github/workflows/build.yml
=> ci: rm macos 13, add macos 26

src/collectors/proc.plugin/metadata.yaml
=> docs: add "per cpu core utilization" option to proc/stat meta

src/collectors/proc.plugin/metadata.yaml
=> docs: add "cpu idle state" procstat config option

src/web/mcp/bridges/stdio-golang/README.md, src/web/mcp/bridges/stdio-golang/build.bat, src/web/mcp/bridges/stdio-golang/build.sh, src/web/mcp/bridges/stdio-golang/go.mod, src/web/mcp/bridges/stdio-golang/go.sum, src/web/mcp/bridges/stdio-golang/nd-mcp.go
=> deps(mcp/bridge/stdio-golang): switch to github.com/coder/websocket

src/go/plugin/go.d/collector/snmp/collector.go
Not needed after #21009
</details>
=> chore(go.d/snmp): remove recreating client on "packet is not authentic"

.github/workflows/build.yml, netdata.spec.in, packaging/check-for-go-toolchain.sh
=> build(deps): update go toolchain to v1.25.1

docs/scalability.md
=> docs: fix mdx parsing scalability.md

packaging/makeself/bundled-packages.version
=> build(deps): bump openssl version in static build

src/collectors/cgroups.plugin/cgroup-network.c
- Fix spawn server orphaning in cgroup-network when fatal() is called
- Prevents zombie processes when running as PID 1 in Docker
When cgroup-network calls `fatal()` after creating its spawn server (line 759), the spawn server process is orphaned and reparented to PID 1. When in Docker netdata runs as PID 1 (not by default), and when the orphaned spawn server exits, it becomes a zombie because netdata is not reaping non-child processes.
Register a fatal callback that properly destroys the spawn server before exit:
- Add `cleanup_spawn_server_on_fatal()` callback
- Register callback immediately after spawn server creation
- Set `spawn_server = NULL` after destruction in both cleanup paths (fatal callback + normal exit)
- The fatal() call (line 759) occurs **before** any fork() (line 825)
- …
=> Fix cgroup-network spawn server cleanup on fatal exit

packaging/docker/Dockerfile
=> fix(packaging/docker): add missing nd-run

src/aclk/mqtt_websockets/mqtt_ng.c
- Switch log message severity level to warning
- Remove the packet from the monitor list to avoid repeated warnings
=> Improve logging and packet handling for unknown packet IDs

docs/.map/map.csv
=> Fix invalid map.csv

packaging/windows/WINDOWS_INSTALLER.md
Following user reports of installer issues, we should add more detailed instructions to help them complete the installation.
1. Take a look in grammar.
</details>
=> Update installer documentation

CMakeLists.txt, packaging/windows/netdata.wxs.in
- Fix directory path for executable and configuration
- Fix installation path prefix
=> Fix windows build
