- netdata.spec.in
- src/Makefile.am
Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>
> build: setuid apps.plugin if running under root

- netdata-9999.ebuild
Put this in your overlay so you can install/update/remove it properly into your system.
> build: ebuild: initial add

- netdata-installer.sh
Very simple fix, but github makes is so easy to create a pull request :)
> Fixed a typo

- src/plugins_d.c
Fixing grammar issue, a to an.
> CHORE - Fix grammar

- web/dashboard.html
- web/dashboard.js
- web/index.html
- web/netdata-swagger.yaml
> CHORE - remove trailing spaces

- src/plugins_d.c
> fix spelling error

- .gitignore
- web/Makefile.am
Possible implementation for #175
> Add a generated version.txt containing commit id

- system/Makefile.am
- system/netdata-init-d.in
Added init script generation for Redhat6/Centos6 in order to control daemon state from
/etc/init.d
> Added init script generation for Redhat6/Centos6

- web/Makefile.am
trivial change
noticed this `Makefile.am` had inconsistent formatting, as other .am files seemed to use tabs, reformatted using tabs.
> reformat with tabs

- system/netdata.service.in
> systemd: add Description= from .spec

- .travis.yml
using fakeroot as the installer requires uid=root
> travis: test also installer

- web/dashboard.js
- web/index.html
The toolbox button can be sped up using the following keys:
1. SHIFT x 2
2. ALT x 5
3. CONTROL x 10
Also, the help popover delays are now configurable.
> charts toolbox can be sped up using SHIFT, ALT, CONTROL keys #246

- src/proc_diskstats.c
> disks with major 253 do not have partitions #258

- web/dashboard.js
- web/index.html
> additional checks for detecting demo and when downloading charts 

- src/proc_diskstats.c
#259, #258
netdata now reads `/sys/dev/block/MAJOR:MINOR/partition` to get the partition id of the block device in question. The result is cached, so that for each disk, this file is read just once.
> auto-detection of partitions based on /sys/dev/block/MAJOR:MINOR/partition

- web/dashboard.js
> automatically disable online help if bootstrap is missing 

- charts.d/tomcat.chart.sh
Hi. This is a pull request to include a tomcat charts.d plugin. Tested on Tomcat version: 7.0.54. Thank you.
> tomcat.chart.sh plugin

- charts.d/Makefile.am
- charts.d/apache.chart.sh
- charts.d/nginx.chart.sh
- charts.d/phpfpm.chart.sh
- charts.d/tomcat.chart.sh
#276 phpfpm and suggestion for curl `-Ss` option
#277 tomcat
> curl error reports for charts.d charts; added phpfpm and tomcat to installation

- README.md
> Fix Arch Linux name

- src/web_buffer.c
The changes on buffer_jsdate and buffer_date we discussed...
> Now buffer_jsdate() and buffer_date() are a little bit faster.

- src/log.h
Build currently broken on musl without that header.
> Include time.h where used

- src/sys_fs_cgroup.c
> fix memory leack in cgroups

- charts.d/mysql.chart.sh
> fix for properly working when the name as given by the user and the calculated id of the mysql charts do not match

- src/daemon.c
- src/main.c
https://github.com/firehol/netdata/issues/115#issuecomment-214955066
> fixes for $HOME and supplementary user groups in netdata

- src/proc_self_mountinfo.c
- src/proc_self_mountinfo.h
> commented mountinfo optional_fields code

- charts.d/ap.chart.sh
- charts.d/apache.chart.sh
- charts.d/cpufreq.chart.sh
- charts.d/example.chart.sh
- charts.d/load_average.chart.sh
- charts.d/mysql.chart.sh
- charts.d/nginx.chart.sh
- charts.d/nut.chart.sh
- charts.d/opensips.chart.sh
- charts.d/phpfpm.chart.sh
- charts.d/postfix.chart.sh
- charts.d/sensors.chart.sh
- charts.d/squid.chart.sh
- charts.d/tomcat.chart.sh
- plugins.d/charts.d.plugin
- tests/stress.sh
If you want to update this in your other projects:
```sh
for file in `find "." -name "*.sh"`
do
perl -pi -e 's/\$\[([^\[\]]+|([^\[\]]*?\[[^\[\]]+?\][^\[\]]*?)+)\]/\$(($1))/' "$file"
done
```
> Fix #282 use modern arithmetic expansion in shell

- src/sys_fs_cgroup.c
> cgroups: disable by default certain cgroups

- src/sys_fs_cgroup.c
> cgroups: disable by default the machine and machine.slice cgroups

- src/sys_fs_cgroup.c
> fix for invalid JSON generation 

- plugins.d/cgroup-name.sh
- src/sys_fs_cgroup.c
now:
- all cgroups are evaluated by default
- up to 500 cgroups are allowed by default
- `.scope` are enabled by default
#329
> cgroups: update of default settings to cover RHEL

- charts.d/mysql.chart.sh
- query cache
- myisam key cache
- innodb buffer pool
- open files
#284
> added more mysql charts

- web/index.html
Fix for menu items containing a `.` that was converted to `_` in the menu but not the DOM id.
#361 
#340
> fix for not matching menu items

- LICENSE.md
- node.d/Makefile.am
- node.d/node_modules/netdata.js
- src/plugins_d.c
- web/index.html
- fixes #369, SNMP 64 bit counters
- plugins.d now accept SET = 0xHEXVALUE
- node-int64 removed;
> plugins can send HEX values to netdata; fix for SNMP 64 bit counters

- contrib/debian/changelog
- src/rrd.c
- web/dashboard.js
- web/demosites.html
> bugfixes and minor enhancements

- profile/benchmark-dictionary.c
- src/appconfig.c
- src/dictionary.c
- src/dictionary.h
- src/plugin_tc.c
dictionary.c will be used to replace all the name-value indexes netdata uses. This is the first complete commit of it. It is still unused by the rest of the code.
> finalized dictionary.c

- charts.d/tomcat.chart.sh
> add tomcat user:password to curl command

- plugins.d/cgroup-name.sh
without docker
~~~
stderr: Running API command: /containers/505341a8b07fde1b013595ade962183f8a5628ef6997b32096f8ba5df1a34c70/json
stderr: Docker container '505341a8b07fde1b013595ade962183f8a5628ef6997b32096f8ba5df1a34c70' is named 'netdata'
stderr: ./cgroup-name.sh: cgroup '/sys/fs/cgroup/systemd/docker/505341a8b07fde1b013595ade962183f8a5628ef6997b32096f8ba5df1a34c70' is called 'netdata'
stdout: netdata
~~~
with docker
~~~
stderr: Running command: docker ps --filter=id="505341a8b07fde1b013595ade962183f8a5628ef6997b32096f8ba5df1a34c70" --format="{{.Names}}"
stderr: Docker container '505341a8b07fde1b013595ade962183f8a5628ef6997b32096f8ba5df1a34c70' is named 'netdata'
stderr: ./cgroup-name.sh: cgroup '/sys/fs/cgroup/systemd/docker/505341a8b07fde1b013595ade962183f8a5628ef6997b32096f8ba5df1a34c …
> use docker binary if exists, fallback on docker api if exists

- src/daemon.c
Fix minor issue described in #400 .
> Remove warning in signal handler.

- src/registry.c
- web/dashboard.html
- web/dashboard.js
- web/demo.html
- web/demo2.html
- web/demosites.html
- web/index.html
- web/tv.html
> registry fixes

- system/netdata.logrotate.in
even if netdata is not managed by init.d/systemd
> have default logrotate file work in all cases

- system/netdata-init-d.in
follows LSB spec now
http://refspecs.linuxfoundation.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
changes adapted from pld package:
https://github.com/pld-linux/netdata/blob/master/netdata.init
> init.d: add try-restart, force reload

- src/daemon.c
- src/daemon.h
- src/main.c
- web/Makefile.am
- web/dashboard.js
- web/index.html
- web/registry.html
1. log files are now chowned by netdata to be owned by netdata - fixes #453 
2. my-netdata entries are now validated once clicked, before sending the browser to the other netdata. If a server can be accessed via multiple URLs, all URLs are searched until one working is found
> log files owned by netdata; my-netdata validates URLs

- web/index.html
change hash based on selection while scrolling
> Small enhancement to scrollspy

- netdata-installer.sh
Just fixed a very obvious typo, it jumped directly into my eye after updating netdata on my server :D
> Fixed a typo in netdata-installer.sh

- src/rrd2json.c
(netdata does its calculations from now to the past)
> incremental-sum flipped

- src/main.c
Just fixes some minor typos.
I hope this is ok.
Awesome work btw, I'm really impressed!
> Fixes typo in deprecated options warning

- charts.d/hddtemp.chart.sh
Add a module to monitor disk temperatures using running instance of daemonized hddtemp.
Script automatically connects to hddtemp running on localhost:7634, pulls disks data and presents them on one graph.
> monitor disk temperatures

- charts.d/sensors.chart.sh
> add an option to exclude some sensors

- charts.d/sensors.chart.sh
With this I have recorded about 1/4 less time used by `sensors_update()`
> remove extensive usage of cat

- charts.d/Makefile.am
- charts.d/README.md
Include hddtemp.chart.sh in Makefile and added some information about hddtemp and sensors plugins.
> updated charts.d readme and makefile

- charts.d/cpufreq.chart.sh
- web/index.html
1. browser history is now not poisoned when scrolling or clicking on the menu of the dashboard
2. support for middle mouse button on registry servers
3. current dashboard position is propagated to the destination server when using the my-netdata menu
4. cpufreq is optimized a bit - eliminated a cat command.
> dashboard improvements and cpufreq optimization

- charts.d/mysql.chart.sh
> Changes in MySQL plugin

- src/common.c
- src/common.h
- src/log.c
- src/main.c
- src/web_buffer.c
- src/web_client.c
- src/web_server.c
> small changes, adaptation of #428 from @fredericopissarra

- .gitignore
- Makefile.am
- configure.ac
- plugins.d/Makefile.am
- plugins.d/python.d.plugin
- python.d/Makefile.am
- python.d/README.md
- python.d/example.chart.py
> Initial support for python plugins

- conf.d/Makefile.am
- conf.d/python.d.conf
- conf.d/python.d/mysql.conf
- netdata-installer.sh
- plugins.d/python.d.plugin
- python.d/Makefile.am
- python.d/README.md
- python.d/mysql.chart.py
As I said here is MySQL plugin rewritten to python. Everything needed to run it is supplied in this PR. I am using [PyMySQL](https://github.com/PyMySQL/PyMySQL) module and it would be good to give them credit somewhere.
I have fixed some bugs in `python.d.plugin` and also in `Makefile.am` responsible for `python_modules` directory.
This PR is tested on clean Ubuntu 16.04, and it works.
> Python plugin for MySQL

- src/main.c
- src/sys_fs_cgroup.c
> added PYTHONUNBUFFERED=1 to environment and logged an error if cgroup mount info cannot be found

- charts.d/phpfpm.chart.sh
- web/index.html
Compatibility with PHP 5.3 + better titles for phpfpm. 
Ready to be merged.
> PR to issue #558

- web/index.html
The latest version comes with a js error which prevents the dashboard from being loaded.
> Fix a JavaScript error

- contrib/README.md
- contrib/debian/control.wheezy
- contrib/debian/netdata.default
Hi,
i changed the EXTRA_OPTS, so that netdata is going to create pidfile. adjusted the according files. so starting and stopping is now possible on a debian wheezy
KR
David
> changes for wheezy package

- python.d/README.md
As I am changing many things in `python.d.plugin` and `mysql.chart.py` to include functionalities discussed in #555, it may be a good idea to say something about current experimental status of python support.
> Information about experimental support of python plugins

- charts.d/tomcat.chart.sh
- contrib/README.md
@x4FF3x and @ktsaou I think you missed it in #575
> depreciated -pidfile in #575 + fix naming convention in 'tomcat.charts.sh'

- web/dashboard.js
> prevent another javascript error when the registry is not reachable

- conf.d/apps_groups.conf
Adding Zimbra, java and Bacula for applications.
> Adding new process type

- plugins.d/python.d.plugin
- python.d/example.chart.py
- python.d/mysql.chart.py
- python.d/pip_install.sh
- python.d/python_modules/base.py
Just like in title. It doesn't change any functionality. Everything is in comments.
Mergable.
> Add encoding (PEP263)

- conf.d/apps_groups.conf
Forgot amavis in my previous commit.
> Adding another application type

- plugins.d/python.d.plugin
- python.d/example.chart.py
- python.d/mysql.chart.py
@paulfantom it was not starting in my systems.
I did a few changes, mainly to logging, parsing of update_every (was not working) and detecting the `python.d` directory (was not working either).
I am missing a very important feature: I need to verify it has parsed everything properly and the main data collection loop works as expected. This can be verified if we add `debug` statements that log all key actions and timings. Unfortunately, I am not that good in python. Actually, I am a little bit confused. Could you please implement these?
I am not merging this, until you review it. Once this is merged, you can continue your work.
> python plugin fixes for better tracing debugging

- conf.d/python.d.conf
- plugins.d/python.d.plugin
- python.d/mysql.chart.py
- python.d/python_modules/base.py
Probably fixed your previous commit.
Global variable `UPDATE_EVERY` (previously `INTERVAL`) was used in a very strange way (it was very unreadable what was it doing). I fixed it, and now default value of `update_every` is stored properly in `BASE_CONFIG`.
To enable overriding it in debug mode (like `python.d.plugin debug mysql 1`) I have added `OVERRIDE_UPDATE_EVERY`.
Also passing `*sys.argv` to `parse_cmdline()` is probably resolved. I don't know since I don't know what was the issue, but it works.
> Fixing python

- plugins.d/python.d.plugin
Like in title.
Ready to be merged.
> Fixed issue with `python.d.plugin 1 debug`

- conf.d/python.d.conf
- conf.d/python.d/phpfpm.conf
- python.d/phpfpm.chart.py
- python.d/python_modules/base.py
@ktsaou while you were debugging `python.d.plugin` I have created new class "UrlService" which eases creating services which are getting data from some http requests (like phpfpm). To test it I have created new phpfpm (and nginx one, but this will be added later) module.
It doesn't use any 3rd party libraries and is compatible with python2 and python3.
> More python modules

- charts.d/apache.chart.sh
- conf.d/Makefile.am
- conf.d/python.d.conf
- plugins.d/python.d.plugin
- python.d/Makefile.am
- python.d/apache.chart.py
- python.d/nginx.chart.py
- python.d/phpfpm.chart.py
- python.d/python_modules/base.py
- web/index.html
I found two issues with previous version of `python.d.plugin`
1. every configuration file had to have `update_every` value
2. `python.d.config debug 1` raised an exception and exited program
Both are fixed in this PR.
There was also an issue in UrlService which prevented running more than one instance of child classes. 
I have been testing it with Apache and nginx plugins which are now working, so I am adding them too. 
While testing apache plugins I found one issue in `apache.chart.sh`. fixed it.
Currently every plugin can monitor many instances, so I've added formatting of apache and nginx modules in `index.html`. They can be shown the same way as MySQL. But later I have commented it out due to incompatibility with shell counterparts.
Finally I modified makefiles to include new python …
> Python and Shell fixes + apache and nginx python modules.

- plugins.d/python.d.plugin
- python.d/Makefile.am
- python.d/apache.chart.py
- python.d/example.chart.py
- python.d/python_modules/base.py
- python.d/python_modules/msg.py
Fixes #604
Implemented, tested, works. 
Also moved logging functions to new file so they can be used in other places.
> Python Threading

- web/dashboard.html
- web/demo.html
- web/demo2.html
- web/demosites.html
- web/index.html
- web/registry.html
- web/tv.html
Used by installable webapp platforms. Part of HTML5.
> Include HTML application name

- netdata-installer.sh
Using correct variable for killing netdata processes.
> Fixing uninstall script

- src/apps_plugin.c
ok, this is unbelievable:
A process forks a child. This child does something and exits. The resources used by this child are reported to the parent, only if the parent waited-for the child.
So, where are the resources of such a child reported? Are they lost? No! They are added to pid 1 (init).
Since these resources are added to init, init would have a spike at the netdata charts. If the child worked an hour at 100% CPU of a single core, a huge spike would appear at the chart, since the whole cpu time of the child would be considered that has happened in a second!
This PR attempts to fix this issue (not only the spike is eliminated, but the resource accounting done by netdata properly reports all tracked children to their real parents - except children that start and stop too frequently …
> apps.plugin, work-around kernel limitation not accumulating not-waited-for childs into parents

- Makefile.am
> removed gentoo ebuild from Makefile.am

- conf.d/Makefile.am
- conf.d/python.d.conf
- conf.d/python.d/apache.conf
- conf.d/python.d/apache_cache.conf
- conf.d/python.d/hddtemp.conf
- conf.d/python.d/mysql.conf
- conf.d/python.d/nginx.conf
- conf.d/python.d/phpfpm.conf
- conf.d/python.d/squid.conf
- conf.d/python.d/tomcat.conf
- python.d/Makefile.am
- python.d/README.md
- python.d/apache.chart.py
- python.d/apache_cache.chart.py
- python.d/hddtemp.chart.py
- python.d/mysql.chart.py
- python.d/nginx.chart.py
- python.d/phpfpm.chart.py
- python.d/python_modules/base.py
- python.d/squid.chart.py
- python.d/tomcat.chart.py
First of all I changed name of misleading method `_format_data` to `_get_data` and introduced `_get_raw_data` where it was needed.
Created `squid.chart.py` and `hddtemp.chart.py`, both of which are using new `NetSocketService` class.
Everything but `squid.chart.py` was tested. 
With `squid.chart.py` I've done some basic tests like autodetection and requests on `/squid-internal-mgr/counters`, but none of it was done on `squid` server.
> python.d squid + hddtemp + tomcat + minor fixes

- python.d/python_modules/base.py
After updating netdata to newest version I saw that with my last PR I introduced a pretty significant bug.
It didn't show multiple jobs from one module on dashboard. With this PR it is fixed.
Tested and ready to be merged.
Sorry.
> fix issues with python jobs not showing in dashboard

- conf.d/Makefile.am
- conf.d/python.d/cpufreq.conf
- conf.d/python.d/exim.conf
- conf.d/python.d/postfix.conf
- python.d/Makefile.am
- python.d/apache.chart.py
- python.d/apache_cache.chart.py
- python.d/cpufreq.chart.py
- python.d/example.chart.py
- python.d/exim.chart.py
- python.d/hddtemp.chart.py
- python.d/mysql.chart.py
- python.d/nginx.chart.py
- python.d/phpfpm.chart.py
- python.d/postfix.chart.py
- python.d/python_modules/base.py
- python.d/squid.chart.py
- python.d/tomcat.chart.py
Changed description for every python module (since they are modules not plugins)
Created `exim.chart.py` and `postfix.chart.py` which are based on `ExecutableService` class.
Also added `cpufreq.chart.py`.
Added their configuration files, which are almost empty (they can have also `retries` and `priority` just like every conf file).
I have tested it. It should be ready to merge.
(Modules left: 4)
> Cpufreq + exim + postfix

- src/apps_plugin.c
this means user and system cannot have different fix ratios
> apps.plugin nice can be both user and system time

- src/sys_fs_cgroup.c
> cgroups searches for containers in /sys/fs/cgroup/devices; added error logging

- src/sys_fs_cgroup.c
https://github.com/firehol/netdata/issues/673#issuecomment-232077188
> containers per cpu is in nanoseconds

- charts.d/nginx.chart.sh
- conf.d/Makefile.am
- conf.d/python.d.conf
- conf.d/python.d/exim.conf
- conf.d/python.d/redis.conf
- plugins.d/python.d.plugin
- python.d/Makefile.am
- python.d/exim.chart.py
- python.d/hddtemp.chart.py
- python.d/python_modules/base.py
- python.d/python_modules/msg.py
- python.d/redis.chart.py
- python.d/squid.chart.py
- web/index.html
1. Nginx is shown as `nginx: local` in dashboard while using python or bash module.
2. `NetSocketService` changed name to `SocketService`, which now can use unix sockets as well as TCP/IP sockets
3. changed and tested new python shebang (yes it works)
4. fixed issue with wrong data parsing in `exim.chart.py`
5. changed whitelisting method in `ExecutableService`. It is very probable that whitelisting is not needed, but I am not sure.
6. Added `redis.chart.py`
I have tested this and it works.
After merging this I need to take a break from rewriting modules to python. There are only 3 modules left, but I don't have any data to create `opensips.chart.py` as well as `nut.chart.py` (so I cannot code parsers). I also need to do some more research to create `ap.chart.py` since using `iw` isn't …
> Redis python module + minor fixes

- python.d/mysql.chart.py
- python.d/sensors.chart.py
- python.d/squid.chart.py
> fix charts types + six sensors issues

- plugins.d/python.d.plugin
- python.d/example.chart.py
- python.d/mysql.chart.py
- python.d/postfix.chart.py
- python.d/python_modules/base.py
Do not merge yet.
1. fixed mysql issue `invalid literal for int() with base 10: 'absolute'`
> bug fixes in python

- plugins.d/python.d.plugin
Like in title.
Now it should work.
> Fix `solve the mutual exclusion issue in python.d.plugin`

- charts.d/apache.chart.sh
- charts.d/exim.chart.sh
- charts.d/postfix.chart.sh
- charts.d/squid.chart.sh
like in title.
Also phpfpm already has `_local` suffix in default configuration.
> add `_local` to postfix and exim bash scripts

- plugins.d/python.d.plugin
- python.d/python_modules/base.py
> redis mutual exclusion

- plugins.d/python.d.plugin
- python.d/cpufreq.chart.py
- python.d/hddtemp.chart.py
- python.d/python_modules/base.py
- python.d/redis.chart.py
- python.d/squid.chart.py
I have added some logging messages and improved previous ones.
It is tested. Works as expected.
> better python logging

- python.d/hddtemp.chart.py
- python.d/python_modules/base.py
- python.d/squid.chart.py
> Better socket management in python

- system/netdata-init-d.in
Seems like it forgot to return the exit status code
> return RETVAL for condrestart()

- python.d/mysql.chart.py
> fix units in mysql charts

- plugins.d/python.d.plugin
- python.d/cpufreq.chart.py
- python.d/hddtemp.chart.py
- python.d/python_modules/base.py
- python.d/redis.chart.py
- python.d/squid.chart.py
Do not merge it yet. It needs testing.
Although I haven't found any issue, yet.
> non-blocking `SocketService`

- python.d/sensors.chart.py
> Support multiple same-name sensors

- system/netdata.conf
Also add a security warning.
Related to #164
> Bind to 127.0.0.1 by default

- netdata.spec.in
> RPM improvements / fixes

- netdata.spec.in
This fixes how RHEL handles installs vs upgrades vs uninstalls.
> fix %post, %preun and %postun

- netdata-installer.sh
1. dont use BASH 4 features when BASH 4+ is not available (related to #733 )
2. fallback to `systemctl` if `service` is not available - fixes start/restart by the installer on Arch Linux
> netdata-installer compatibility fixes

- python.d/apache_cache.chart.py
- python.d/python_modules/base.py
- python.d/tomcat.chart.py
1. Merged `BaseService` and `SimpleService` into one.
2. Added more comments and some debug statements
3. Little speed improvements with moving to local variables
4. Fix #720 
5. Fix #721 
6. replace `sys.stdout.write` with appropriate method
7. implement proxy handling in `UrlService` (currently commented-out since it is not tested)
8. Increase timeout for http responses
9. `_get_raw_data` in `LogService` now returns empty list if no new lines were added to log file. This should be used in module `_get_data` method.
> Code cleanup + bug fixes in base.py

- conf.d/Makefile.am
- conf.d/python.d/memcached.conf
- python.d/Makefile.am
- python.d/memcached.chart.py
- python.d/tomcat.chart.py
- web/index.html
Added support for memcached (fixes #751)
Also attempting to fix #719
> Memcached + fixes in tomcat

- LICENSE.md
- conf.d/Makefile.am
- conf.d/python.d.conf
- conf.d/python.d/hddtemp.conf
- conf.d/python.d/nginx_log.conf
- plugins.d/python.d.plugin
- python.d/Makefile.am
- python.d/hddtemp.chart.py
- python.d/nginx_log.chart.py
- python.d/python_modules/base.py
- python.d/python_modules/lm_sensors.py
- python.d/python_modules/msg.py
- python.d/sensors.chart.py
> New python modules + bug fixes

- python.d/README.md
- python.d/nginx_log.chart.py
- python.d/tomcat.chart.py
> minor changes + modules descriptions

- Dockerfile
- docker-build.sh
- plugins.d/alarm-email.sh
cc: https://github.com/firehol/netdata/pull/77#issuecomment-242011773
> added docker files from titpetric repo

- python.d/memcached.chart.py
Apply @ktsaou suggestion from #831.
> change memcached cache chart to stacked type

- python.d/README.md
> update mysql configuration

- README.md
@titpetric I am adding a docker pulls badge to netdata home, pointing to your docker hub project.
You have 107.000 pulls! nice!
> added docker pulls badge

- conf.d/health.d/disks.conf
- configs.signatures
> absorb 2 minute disk space spikes in alarms

- src/sys_fs_cgroup.c
> when 2 containers have the same name, prefer the new one over the old one, if the old is not available any more

- src/sys_fs_cgroup.c
> keep track of duplicate cgroups (cgroups with same name) and enable the first available when any cgroup is removed

- plugins.d/alarm-email.sh
- src/daemon.c
- src/log.c
- src/log.h
- src/main.c
- src/plugin_nfacct.c
- src/proc_interrupts.c
- src/proc_meminfo.c
- src/proc_net_ip_vs_stats.c
- src/proc_net_stat_conntrack.c
- src/proc_net_stat_synproxy.c
- src/proc_vmstat.c
- src/registry.c
- src/web_client.c
- system/netdata.logrotate.in
fixes #887 
fixes #889 
fixes #866
> minor bug fixes and enhancements

- conf.d/Makefile.am
- conf.d/health.d/retroshare.conf
- conf.d/python.d/retroshare.conf
- python.d/Makefile.am
- python.d/retroshare.chart.py
- web/index.html
this needs https://github.com/RetroShare/RetroShare/pull/488 to be merged which should happen in the near future
> add RetroShare statistics

- Makefile.am
- ansible/netdata.yml
- plugins.d/cgroup-name.sh
- src/health.c
fixes #897
fixes #922
contributes to #798 (added ansible playbook)
> minor fixes

- charts.d/opensips.chart.sh
> more elastic opensipsctl output match

- src/Makefile.am
- src/plugin_proc.c
- src/plugin_proc.h
- src/proc_net_rpc_nfs.c
- src/proc_net_rpc_nfsd.c
- web/index.html
This PR adds data collection for NFS clients (v2, v3, v4) and NFS v4 servers (it existed, but not collecting RPC calls properly).
> NFS v4 support, NFS client support

- conf.d/Makefile.am
- conf.d/health.d/tcp_resets.conf
- src/health.c
> added alarm to detect port scans or busy service crashes

- python.d/mysql.chart.py
- python.d/python_modules/base.py
> mysql.chart.py and SocketService improvements

- conf.d/health_alarm_notify.conf
- plugins.d/alarm-notify.sh
> Add telegram messages to health monitoring

- src/health.c
- src/rrd2json.c
- src/web_buffer.c
- src/web_buffer.h
- src/web_client.c
- web/Makefile.am
- web/dashboard.html
- web/dashboard.js
- web/dashboard_info.js
- web/demo.html
- web/demo2.html
- web/demosites.html
- web/goto-host-from-alarm.html
- web/index.html
- web/netdata-swagger.json
- web/netdata-swagger.yaml
- web/registry.html
- web/tv.html
1. dashboard static content information is now in `dashboard_info.js`
2. dashboard loads the required javascript files in parallel
3. a few optimizations suggested by sitespeed.io
4. health monitoring stops while netdata exits, to avoid alarms flood
> dashboard and web server optimizations

- conf.d/python.d/phpfpm.conf
- python.d/phpfpm.chart.py
* Get the fpm stats in json format for easy parsing
* Get stats for each process and track maximums and averages for each.
> Improve phpfpm module.

- python.d/sensors.chart.py
when only single sensor is available, everything is groupped into
temperature
fixes issue in https://github.com/firehol/netdata/issues/918
you may ignore white space changes to see a clear diff
> sensors: fix grouping

- python.d/sensors.chart.py
adds some range values for checking sensor values
> sensors: ignore overflow value

- netdata-installer.sh
even if git has not been updated
> netdata-updater.sh now support -f to force re-installation

- netdata-installer.sh
- web/dashboard.js
1. HTML5 notifications are now incremental (the same notifications are not shown again on refresh)
2. netdata-installer.sh is not a snake, it is a chart
> minor enhancements

- src/apps_plugin.c
- src/plugin_nfacct.c
- src/plugins_d.c
- src/proc_net_softnet_stat.c
- src/registry.c
- src/rrd.c
Fix some minor warnings found by cppcheck. The code base is generally clean :)
> Fix warnings found by cppcheck

- web/dashboard.html
- web/demo.html
- web/demo2.html
- web/demosites.html
- web/goto-host-from-alarm.html
- web/index.html
- web/tv.html
> increased the version to uncache older versions

- configure.ac
- plugins.d/loopsleepms.sh.inc
- src/common.h
- src/global_statistics.c
- src/health.c
- src/log.c
- src/web_client.c
1. fixes all warnings / errors when compiling against musl
2. fixes all other issues detected when the system is busybox based
3. fixes #860
> alpine linux compatibility fixes

- src/common.c
The problem is that `MAP_FAILED` is `(void *)-1`...
> prevent crash on start if shared or private anonymous memory cannot be allocated

- web/dashboard.js
- web/dashboard.slate.css
- web/index.html
This PR relieves the web browser from some pressure during scrolling. So, smoother page scrolling on netdata dashboards.
There is a new dashboard option added. If your browser is fast enough you can set page refreshes on scroll to be synchronous.
> better page scrolling

- configure.ac
- m4/ax_c_mallinfo.m4
- src/common.h
- src/main.c
@alonbl your suggestions implemented.
Thanks!
> autoconf best practices

- web/dashboard.html
- web/dashboard.js
- web/demo.html
- web/demo2.html
- web/demosites.html
- web/goto-host-from-alarm.html
- web/index.html
- web/registry.html
- web/tv.html
> fix for user supplied colors on chart dimensions

- conf.d/python.d/redis.conf
Just a minor "fix" in the instructions I stubled upon while browsing the config files.
> Updated redis.conf

- web/dashboard.html
- web/dashboard.js
- web/demo.html
- web/demo2.html
- web/demosites.html
- web/goto-host-from-alarm.html
- web/index.html
- web/registry.html
- web/tv.html
> allow functions to be given for easypiechart barColor;

- web/index.html
> added URL hash option always_update to remember the state of the refreshing

- contrib/README.md
- contrib/debian/netdata.postinst.in
added creation of registry folder wheezy.
> Wheezy Instructions for 1.4.0

- conf.d/health_alarm_notify.conf
- configure.ac
- plugins.d/Makefile.am
- plugins.d/alarm-notify.sh
- plugins.d/alarm-test.sh
Added pushbullet notifications support
This can be improved, but right now I have it working onmy environment.
It is using the user's api keys.
> Added pushbullet notifications support

- plugins.d/alarm-notify.sh
test alarms are now more realistic.
> alarm-notify.sh improvements

- conf.d/health.d/tcp_resets.conf
- configs.signatures
- src/sys_fs_cgroup.c
1. cgroups disk bandwidth charts are now area charts
2. fixes #1156 
3. fixes #1157
> minor bug fixes

- netdata.spec.in
> include markdown files in /etc

- charts.d/mysql.chart.sh
- charts.d/postfix.chart.sh
- netdata-installer.sh
- plugins.d/fping.plugin
- plugins.d/loopsleepms.sh.inc
- plugins.d/tc-qos-helper.sh
- web/index.html
1. alarm log visualizes certain columns properly
2. all shell scripts use `which` and `command` to find the commands they need
> minor improvements

- conf.d/apps_groups.conf
How did you forget about Plex =)
> Add "Plex*" Media Server to "media:"

- web/dashboard_info.js
This was just a trial run to see if this is what your looking for. I actually learned a lot about the Linux memory subsystem!
> Added info: to the charts in the // Memory Section

- conf.d/health_alarm_notify.conf
- plugins.d/alarm-notify.sh
Do not Merge, this needs attention. Fails to call send_twilio()
> Sms feature

- conf.d/health.d/swap.conf
- python.d/memcached.chart.py
- python.d/python_modules/base.py
- python.d/redis.chart.py
- python.d/squid.chart.py
- web/index.html
1. Another attempt to fix socketservice
2. fixes #549 
3. fixes #1235 
4. added more redis charts: bandwidth, connections
5. various minor memcached fixes (dimension names, colors, etc)
> SocketService and more improvements

- python.d/python_modules/base.py
python.d.plugin now uses the same algorithm the netdata core uses for iteration timing.
Interestingly enough there are slight differences between python2 and python3.
python2:
```
2016-11-14 23:21:06: python.d DEBUG: memcached_local sleeping for 0.996789216995 secs to reach frequency of 1.0 secs, now: 1479158466.34 , next: 1479158467.33
```
python3:
```
2016-11-14 23:22:02: python.d DEBUG: memcached_local sleeping for 0.9975037574768066 secs to reach frequency of 1.0 secs, now: 1479158522.3358295 , next: 1479158523.3333333
```
The difference is the number of decimal points in timestamps. Python3 is by far more precise.
Now python collects data 1/3 of the iteration duration later than expected. The reason is that due to timing incompatibilities between netdata and python, netdata ends up …
> python.d.plugin better iteration timing

- python.d/python_modules/base.py
it slows down data collection attempts instead; #999
this is what python.d.plugin now does:
In case of failures, python.d.plugin calculates a `penalty` which it adds to each iteration, until it manages to successfully collect data again:
1. for the first `retries` (by default `60`), `penalty = 0`. So, it does what it already does today.
2. for the next `retries`, `penalty = retries * update every / 2`, so for per-second data collection and 60 retries, it will do 60 more tries with 30 seconds between each retry.
3. for the next `retries` it will use `penalty = penalty * 1.5`, so 60 more retries with 45 seconds between them.
4. it will continue with 3, increasing `penalty` by `1.5` every time, until `penalty` reaches 600 seconds (10 minutes). At this point it will continue doing one check …
> python.d.plugin now never gives up data collection - 

- web/index.html
In the dashboard settings / synchronization, the resync button is buggy.
> default dashboard settings, duplicate option-crontrol leads to a visual bug

- conf.d/Makefile.am
- conf.d/health.d/netfilter.conf
- configs.signatures
- src/proc_diskstats.c
- src/proc_net_stat_conntrack.c
https://github.com/firehol/netdata/issues/161#issuecomment-261982544
> netfilter sockets chart when netfilter stats are not available and netfilter alarm

- netdata-installer.sh
> fix incorrect permissions on directories on fresh installs

- conf.d/Makefile.am
- src/web_client.h
> fix for bit-limited flags, not working properly in gcc versions

- src/web_client.c
- src/web_client.h
> removed error log that is triggered under normal conditions when the request is too big

- web/dashboard.js
- web/demosites.html
- web/index.html
> allow custom dashboards to link dimensions to DOM elements by name or id

- src/freebsd_sysctl.c
I've left full configuration implementation for later commits. I can't comprehend right now what is the suitable structure for configuration on FreeBSD.
> FreeBSD plugin: Add disk stats and do minor style cleanups

- conf.d/python.d/exim.conf
- conf.d/python.d/gunicorn_log.conf
- python.d/gunicorn_log.chart.py
Added .conf chart.py files for gunicorn. Mimicking the way that nginx_log.chart.py works. This will allow users to easily add and monitor different instances of gunicorn (with modification to the conf file)
> Added gunicorn log conf and chart.py files

- conf.d/health_alarm_notify.conf
- plugins.d/alarm-notify.sh
- src/web_buffer.c
- src/web_buffer.h
- src/web_client.c
1. added pushing of alarm notifications to kafka
2. fixed XSS issues when netdata shows API errors; fixes #1338
> kafka notifications; XSS fixes on API errors.

- web/demosites.html
cc: https://github.com/firehol/netdata/pull/1321
> fixed typo - fixes #1339 - added @vlvkobal to home page

- src/proc_diskstats.c
- src/proc_self_mountinfo.c
- src/proc_self_mountinfo.h
> do not monitor disk space metrics for read-only mounts

- plugins.d/alarm-notify.sh
> kafka success code is 204

- src/freebsd_sysctl.c
Along with it a mistake in the swap i/o chart have been corrected.
> FreeBSD plugin: extend interrupts stats and add netisr charts

- src/proc_diskstats.c
> show disk space stats when disk performance is not available

- src/common.c
- src/common.h
- src/rrd.c
> escape chart titles to have proper JSON formatted output

- system/netdata-init-d.in
…t, fixes #1381
also added support for user overrides as per https://fedoraproject.org/wiki/EPEL:SysVInitScript
> Fix sysvinit scripts status check #1381

- web/dashboard.js
- web/demosites.html
- web/index.html
> allow dashboards to retry fetching chart data on failures

- conf.d/Makefile.am
- python.d/Makefile.am
- python.d/README.md
- python.d/freeradius.chart.py
Also freeradius plugin is not in Makefile. Do I need to add it myself?
> Freeradius plugin bugfix; should return empty list if there is no command

- conf.d/Makefile.am
- conf.d/python.d.conf
- conf.d/python.d/ovpn_status_log.conf
- python.d/Makefile.am
- python.d/ovpn_status_log.chart.py
Unfortunately not so much information can be obtained from openvpn status log file. 
All 3 version of status log file parsed correctly.
Charts:
**Users:** 
- active users
**Traffic:** (overall for openvpn instance)
- in
- out
> Openvpn log plugin

- conf.d/python.d/sensors.conf
- python.d/sensors.chart.py
> Sensors chart py enhancement

- conf.d/python.d/hddtemp.conf
- python.d/hddtemp.chart.py
Now its very easy to add new options. The only you need is **tuple** where
tuple[0] = units of the chart
tuple[1] = function
`self.fahrenheit = ('Fahrenheit', lambda x: x * 9 / 5 + 32)  if self.configuration.get('fahrenheit') else False`
If there is N option and conf file looks like:
option1: True
option2: True
option3: True
The winner is fisrt function in
self.choice = (choice for choice in **[self.fahrenheit, self.whatever]** if choice)
> Hddtemp chart py enhancement

- conf.d/apps_groups.conf
- configs.signatures
- src/apps_plugin.c
1. allow process groups to span multiple lines
2. added more processed to fix #1442
> apps.plugin improvements

- python.d/isc_dhcpd.chart.py
> isc_dhcpd python2 compatibility

- web/dashboard.css
- web/dashboard.js
- web/dashboard.slate.css
- web/dashboard_info.js
- web/index.html
1. fixed in dashboard links; #1449 
2. on chart hover in firefox is now as fast as in chrome. Opera is also acceptable. Edge is still not that good (although a lot better to what it was before this commit).
To accomplish this, all the legends had to be cached and updated only on change, and also the nice little icon next to each value had to be removed, because it was triggering a DOM reparse on all browsers except chrome.
3. the chart legends are now a little bit bigger.
> dashboard improvements

- conf.d/python.d/postgres.conf
- configs.signatures
- netdata-installer.sh
- src/sys_fs_cgroup.c
- web/dashboard.js
- web/demosites.html
- web/index.html
1. fixed a few minor bugs in `dashboard.js` that prevented a few `data-X` options to be set.
2. fixed the logrotate file permissions; fixes #1456 
3. netdata javascript code is now inside an anonymous function; this probably fixes #1082 
4. fixed a but that prevented netdata from disabling by default `/user/` cgroups
5. added Amazon EC2, Azure and Alpine demo sites
6. added some directions for configuring postgres
> diverse improvements

- netdata-installer.sh
- system/netdata.logrotate.in
> allow logrotate to work on all its versions

- plugins.d/python.d.plugin
repl whitespaces with _ in job names if name specified in *.conf
> python.d.plugin minor fix

- web/dashboard.css
- web/dashboard.js
- web/dashboard.slate.css
- web/index.html
1. a little bit wider scrollbars
2. my-netdata menu pauses the dashboard for smoother scroll on slow machines
> dashboard fine-tunings

- python.d/mysql.chart.py
https://github.com/firehol/netdata/issues/1240
> add slave stats to mysql chart

- web/index.html
> Make icons in sidebar the same width

- src/proc_diskstats.c
1. Now disk statistics add another option: `performance metrics for disks with major X`, where X is the major number as shown in `/proc/diskstats`. By default it is `yes` for all disks. Turning this to `no`, will disable performance metrics for these disks.
2. disk statistics config options cleanup (leftovers from old logic).
fixes #1486
> disk performance metrics can now be disabled per device major

- src/plugins_d.c
> do not report as error plugins calling DISABLE

- conf.d/health.d/mdstat.conf
- python.d/mdstat.chart.py
reshape status added to mdstat
> mdstat improvements

- src/rrd2json.c
> allow nonzero setting to work when dimensions are set

- python.d/mdstat.chart.py
check() should not return True if no active arrays in mdstat
> mdstat_fix

- python.d/ipfs.chart.py
First I wanted just one thing (repo_size), and putting that in made me look at the code, which was very repetitious.  So I made it less so.  Which made it so easy to add new things that I added the repo_objects info.
> More IPFS stats in less code

- python.d/cpufreq.chart.py
A followup on my earlier pull request, after having some more time to play with it.
If we switch the 'schedutil' cpufreq governor on, the 'time_in_state'
data becomes useless. And since cpufreq governors can be switched at any
time, we might as well make it possible to support transitioning between
governors without any bogus data appearing in our charts.
Before this commit, switching to 'schedutil' results in zeroed values,
and switching back to any other governor causes a huge spike datapoint
in the timeline.
> cpufreq.chart.py: support dynamically falling back from accurate to inaccurate mode

- CMakeLists.txt
- src/Makefile.am
- src/clocks.h
- src/plugin_proc.c
- src/plugin_proc.h
- src/proc_loadavg.c
- src/proc_uptime.c
- src/web_buffer_svg.c
> uptime plugin

- conf.d/health.d/haproxy.conf
- python.d/haproxy.chart.py
Some optimization (https://github.com/firehol/netdata/issues/1551)
@hameno can you test it?
[new plugin](https://github.com/l2isbad/netdata/blob/haproxy_module_optimization/python.d/haproxy.chart.py)
[new alarm](github.com/l2isbad/netdata/blob/haproxy_module_optimization/conf.d/health.d/haproxy.conf)
> Haproxy module optimization

- src/sys_fs_cgroup.c
cgroups is a beast! tons of files to read and parse.
This PR:
1. Tries to make netdata smarter, so that files providing incremental values (like memory fail count, block I/O, etc) that are just zero, are processed once every 10 seconds (user configurable).
2. A lot of branch optimizations made.
3. Finer control over cgroups configuration:
```
[plugin:cgroups]
```
After this PR, cgroups processing is twice as fast! With the work made the latest 3 days, cgroups data collection is now 4 times faster than before!
> cgroups data collection optimizations

- conf.d/Makefile.am
- conf.d/health.d/varnish.conf
- conf.d/python.d/varnish.conf
- netdata-installer.sh
- python.d/Makefile.am
- python.d/varnish.chart.py
Not ready.
Must be tested.
@LeeNX @Bilge you are welcome guys.
I am not using varnish so i need your help
What additional charts do we need? (from varnishstat output)
**Literally any suggestion is super welcome!**
> varnish plugin (varnishstat)

- netdata-installer.sh
- python.d/freeradius.chart.py
1. freeradius plugin bugfix
2. https://github.com/firehol/netdata/issues/1591
> Some minor fixes

- python.d/varnish.chart.py
> varnish plugin: version3 support added

- src/apps_plugin.c
- src/plugin_proc_diskspace.c
1. fixes #1606 (alarms when remounting disks read-only)
2. improves the speed of apps.plugin by eliminating the buffering of the data to be sent to netdata
3. some code cleanup on apps.plugin for better readability and understanding
> diskspace and apps.plugin improvements

- src/adaptive_resortable_list.c
- src/adaptive_resortable_list.h
- src/proc_meminfo.c
- src/proc_net_netstat.c
- src/proc_net_snmp6.c
- src/proc_vmstat.c
- src/rrd.c
- src/sys_fs_cgroup.c
(only when -DNETDATA_INTERNAL_CHECKS=1)
> added ARL debugging info and errors on common pitfalls 

- python.d/README.md
- python.d/varnish.chart.py
plus minor varnish plugin update
> Update python readme

- python.d/tomcat.chart.py
Current version does not work on debian (tomcat8)
This PR fixes https://github.com/firehol/netdata/issues/801
Tested with tomcat7/tomcat8. Works for me.
> tomcat plugin: replace xml parse with regex

- src/web_buffer_svg.c
> properly display duration in badges

- python.d/tomcat.chart.py
https://github.com/firehol/netdata/issues/1623
Must be tested (works for me)
@KaelBaldwin
can you test this one?
> tomcat module: add desired port into account (multiple connectors)

- python.d/postgres.chart.py
Late night quick fix https://github.com/firehol/netdata/issues/1603
After PR you can restart/stop do whatever with postgres module never fail.
Pls test it @ktsaou seems you are postgres user
I am not fully understand python-postrges (never used) when and what errors can occur but this dirty fix works for me.
> postgres plugin: reconnect to postgres after restart/stop etc

- src/main.c
> enable cgroups only on Linux

- conf.d/python.d/elasticsearch.conf
- python.d/README.md
https://github.com/firehol/netdata/issues/1650
> python readme and elasticsearch conf file update: requests package

- src/rrd2json.c
remove dimensions that have been specified by the user if all values are zeros and nonzero option was also set
> remove user-specified zero dimensions with nonzero option

- src/rrd.h
- src/rrd2json.c
- src/rrd2json.h
> nonzero option should return all selected dimensions if they are all zero

- src/apps_plugin.c
- src/backends.c
- src/clocks.c
- src/clocks.h
- src/freebsd_sysctl.c
- src/macos_sysctl.c
- src/plugin_freebsd.c
- src/plugin_idlejitter.c
- src/plugin_macos.c
- src/plugin_proc.c
- src/plugin_proc_diskspace.c
- src/proc_diskstats.c
- src/proc_loadavg.c
- src/proc_net_dev.c
- src/proc_net_ip_vs_stats.c
- src/proc_net_rpc_nfsd.c
- src/sys_fs_cgroup.c
- src/sys_kernel_mm_ksm.c
Hi,
Let's begin to use monotonic clocks where this could prevent some issues.
It's not complete and there are some more controversial changes to discuss later, but I tried to start by most "benign" changes, and there is already a lot to comment I'm sure.
Also note that this is not very tested yet, I may require some help there once we are settled.
Thanks
PS: I do a review for myself on mobile because I can't modify the code right now, you can ignore those of you want (or not ;)
> Time improvements

- plugins.d/tc-qos-helper.sh
> find fireqos run dir automatically; 

- src/apps_plugin.c
> remove macros to detect if certain capabilities are supported by system

- src/Makefile.am
- src/common.c
- src/freebsd_sysctl.c
- src/plugin_freebsd.c
- src/plugin_freebsd.h
- src/plugin_macos.c
It fixes issues 3. and 4. in #1632.
3. @mmokhi I applied your FreeBSD port patches.
4. These were just needless comments.
> Remove some /proc remains from FreeBSD plugin

- python.d/elasticsearch.chart.py
https://github.com/firehol/netdata/issues/1695
> elasticsearch plugin: failed to collect data after ES restart fixed

- src/adaptive_resortable_list.c
- src/proc_net_netstat.c
> prevent a crash when the ARL is empty

- src/apps_plugin.c
- src/common.c
- src/common.h
- src/inlined.h
fixes #1698
check https://github.com/firehol/netdata/issues/1698#issuecomment-276771530
> apps.plugin detects in-place process changes

- configs.signatures
- plugins.d/fping.plugin
- web/dashboard.js
- web/index.html
1. dashboard.js: fixes a lot of typos, cleaned up and code and merged many fixes suggested by lint.
2. updates fping plugin to install fping 3.15; fixes #1720
> dashboard.js improvements

- web/dashboard.js
- web/index.html
fixes a compatibility issue introduced with #1730
> respect custom dashboards decimal digits settings

- .travis.yml
- packaging/packaging.functions
Fixes macOS part of https://github.com/firehol/netdata/issues/1667
> Add macOS build to travis.

- conf.d/Makefile.am
- configure.ac
- src/common.c
- src/common.h
- src/main.h
- src/rrd2json.c
- src/web_buffer_svg.c
- web/dashboard.js
- web/dashboard_info.js
- web/index.html
@simonnagl check this...
1. per OS alarms are configured in `conf.d/Makefile.am`.
2. `dashboard_info.js` is now multi-os by itself (it checks the dimensions available, but all attributes can be turned into javascript functions.
3. I also added some more information to `dashboard_info.js` (this thing is very time consuming).
4. when the min and max of all values of a chart are the same (i.e. a straight line), strip all the possible trailing zeros from the legend fraction values.
5. never use 3 fraction digits. use either 2 or 4.
> multi-os support (final touch)

- conf.d/Makefile.am
- netdata-installer.sh
- web/dashboard_info.js
- web/index.html
1. moved all linux specific alarms to linux section.
2. added just a bit more information at the dashboard.
> minor improvements for non-linux systems

- charts.d/nut.chart.sh
- conf.d/charts.d/nut.conf
> added NUT connected clients chart;

- conf.d/health.d/web_log.conf
- python.d/web_log.chart.py
> web_log fixes

- python.d/web_log.chart.py
it was a quick fix and it works for me.
but pls test it @ktsaou
> web_log plugin: change algorithm to incremental

- web/dashboard.js
- web/index.html
> properly reset charts after max refreshes

- python.d/web_log.chart.py
Now plugin works when additional variables appended to the end of the log format. Order is important. Not recommended but still an option.
https://github.com/firehol/netdata/issues/1764
> web_log plugin: support for additional log formats added

- web/netdata-swagger.json
- web/netdata-swagger.yaml
Added version to /charts. (#1740)
Updated other additions at this request too.
Please review the descriptions.
> Update /charts at API definition.

- python.d/web_log.chart.py
https://github.com/firehol/netdata/issues/1777
> web_log plugin: response statuses chart added

- web/dashboard_info.js
- web/index.html
> updated dashboard for new web_log chart

- web/index.html
> fix for double column charts on HiDPi resolutions

- python.d/freeradius.chart.py
https://github.com/firehol/netdata/issues/1800
> freeradius_plugin: python 2.6 compatibility fix

- python.d/freeradius.chart.py
https://github.com/firehol/netdata/pull/1801
> freeradius_plugin: python 2.6 compatibility fix2

- python.d/elasticsearch.chart.py
https://github.com/firehol/netdata/issues/1806
@ktsaou i know i need to fix compatibility for other plugins
> elasticsearch_plugin: python 2.6 compatibility fix

- plugins.d/alarm-notify.sh
> fix hipchat notifications

- conf.d/python.d/fail2ban.conf
- python.d/fail2ban.chart.py
https://github.com/firehol/netdata/issues/1808
Not ready. Should be tested.
i will say when it's ready @ktsaou
> fail2ban_plugin: can read config files from "conf_dir" now

- python.d/bind_rndc.chart.py
- python.d/isc_dhcpd.chart.py
- python.d/smartd_log.chart.py
- python.d/varnish.chart.py
https://github.com/firehol/netdata/issues/1824
> varnish_plugin: python 2.6 compatibility fix

- conf.d/health_alarm_notify.conf
- plugins.d/alarm-notify.sh
Add support for HipChat Server (self-hosted version of HipChat Cloud).
> Add HipChat Server support

- conf.d/health.d/web_log.conf
> set up-delay on web alarms; 

- python.d/fail2ban.chart.py
https://github.com/firehol/netdata/issues/1837
> fail2ban_plugin: parse both conf_path and conf_dir/; regex update

- python.d/python_modules/base.py
https://github.com/firehol/netdata/issues/1844
@netchild
Please test it (python 2.7+ needed).
You need to add `ss_cert: yes` to the job configuration.
Example:
```yaml
localipv4:
name : 'titan'
url  : 'https://100.100.0.1/stub_status'
ss_cert: yes
user : 'test'
pass: '123'
```
> self-signed certificate support for UrlService added

- src/apps_plugin.c
> apps.plugin: added calls counter and isolated file counter only to new files processed

- python.d/web_log.chart.py
> web_log_plugin: requests per http version chart added

- src/backends.c
```
{
"prefix": "netdata",
"hostname": "dev-pc",
"type": "netdata",
"family": "cgroups",
"context": "netdata.plugin_cgroups_cpu",
"units": "milliseconds/s",
"title": "NetData CGroups Plugin CPU usage (netdata.plugin_cgroups_cpu)",
"id": "netdata.plugin_cgroups_cpu",
"subid": "user",
"value": 0.2898883,
"timestamp": 1487364216
}
```
> New JSON backend

- src/rrd.h
- src/rrd2json.c
- src/rrdhost.c
- src/web_client.c
- web/index.html
> add mirrored hosts to the my-netdata menu

- netdata.spec.in
Please review carefully.
Please test as most is not tested.
The apps.plugin logic was an enigma, please specify how exactly it should behave, why and what is the difference between distros.
> Spec cleanups

- charts.d/Makefile.am
- conf.d/health.d/cpu.conf
- python.d/Makefile.am
fixes #1833 
contributes to #1819
> fix cpu alert; make python and bash modules non executable

- src/sys_devices_system_node.c
> fix numa plugin to work only on the expected values; 

- python.d/bind_rndc.chart.py
> bind_rndc_plugin: python 2.6 compatibility fix

- python.d/isc_dhcpd.chart.py
> isc_dhcpd_plugin: python2.6 comp fix

- python.d/postgres.chart.py
https://github.com/firehol/netdata/issues/1750
it was a quick fix.:
1. index and table stats charts are disabled by default 
2. database size (per database) added
Per database metrics are not wrong anymore... But there is a lot of room for improvements.
> postgres_plugin: database size chart added, code refactoring

- python.d/phpfpm.chart.py
https://github.com/firehol/netdata/issues/1888
I saw on the chart max and avg dimensions..
min was added. Not sure it was right but looks logical to me 😄
> php_fpm_plugin: avg dimension for cpu,mem,dur charts added + bugfix

- conf.d/python.d/web_log.conf
- python.d/web_log.chart.py
@alibo
```yaml
nginx_log:
name: 'nginx'
path: '/var/log/nginx/access.log'
detailed_response_aggregate: no  #    < ---- new option added
```
> Web log improvements

- python.d/web_log.chart.py
https://github.com/firehol/netdata/issues/1899
@alibo
> web_log_plugin: update regex to match nginx request_time > 10sec

- python.d/python_modules/base.py
ExecutableService class uses `find_binary()` method to find absolute path for binary (PATH) now. 
All other changes are code optimizations and additional checks (ex.: no reason to call Popen if "command" is not exist or not executable)
TODO: Other "problem" i found -  _get_data() method called minimum twice: in check() and create() methods when python.d.plugin starts. 
check() should return True only if _get_data() result is not empty dict. No reason to call _get_data() one more time in create(). The only we need is to pass data after check() to create(). 
This will allow us to significantly reduce the number of _get_data() calls when python.d.plugin starts.
> ExecutableService_class: optimization

- conf.d/Makefile.am
- conf.d/python.d/nsd.conf
- netdata-installer.sh
- python.d/Makefile.am
- python.d/README.md
- python.d/nsd.chart.py
**nsd**
https://www.nlnetlabs.nl/projects/nsd/
Tested on nsd-4.1.14(from EPEL), CentOS7
Thank you.
> nsd plugin

- README.md
- src/apps_plugin.c
- src/freeipmi_plugin.c
- src/main.c
> add common version options to all C programs

- src/locks.h
- src/rrd.h
- src/rrdhost.c
- src/rrdset.c
There was a case where a host was removed while another thread was adding it.
Fixed.
> improved locks

- python.d/mysql.chart.py
- python.d/python_modules/base.py
Initial version.
Should be tested (works ok for me).
> MySQLService class added + rewritten mysql_plugin

- plugins.d/cgroup-name.sh
> automatic naming for libvirtd virtual machines; 

- .gitignore
- python.d/cpufreq.chart.py
- src/main.c
- src/rrd.h
- src/rrd2json.c
- src/rrd2json_api_old.c
- src/rrdhost.c
- src/rrdpush.c
- web/Makefile.am
- web/dashboard_info_custom_example.js
- web/index.html
> allow custom defined information on the dashboard

- python.d/elasticsearch.chart.py
- python.d/python_modules/base.py
"python-requests" not needed anymore
> Elasticsearch plugin fixes

- web/dashboard.js
> fix gauge gradient colors; 

- src/backends.c
fixes #1962 
cc: @lfdominguez note this.
> rename chart fields to avoid conflicts with backends;

- configure.ac
This allows building a statically linked netdata
> do not include libmnl if nfacct is not enabled

- coverity-scan.sh
- src/proc_net_dev.c
> netdev_added cleanup and recalculation;

- src/freebsd_sysctl.c
> fix freebsd SIGBUS error

- src/adaptive_resortable_list.c
- src/freebsd_sysctl.c
> freebsd coverity fixes

- python.d/mongodb.chart.py
fixes https://github.com/firehol/netdata/issues/1985
> mongodb_plugin: take "arbiter" replica set member into account

- python.d/haproxy.chart.py
fixes https://github.com/firehol/netdata/issues/1997
> haproxy_plugin: get data via UrlService bugfix

- src/proc_net_snmp6.c
> ipv6 metrics swapped;

- conf.d/python.d/postgres.conf
- python.d/postgres.chart.py
https://github.com/firehol/netdata/issues/1979
> Postgres plugin option to exclude databases from poll added

- python.d/fail2ban.chart.py
Not sure it's ready @ktsaou 
I need feedback from @pschiffe
> Also, I have an idea for additional graph - number of currently blocked ips. 
This is it!
How it works:
1. if `Ban` then +1 for jail
2. if `Unban` then -1 for jail
> fail2ban_plugin: "Currently In Jail" chart added

- conf.d/Makefile.am
- conf.d/python.d.conf
- conf.d/python.d/dns_query_time.conf
- python.d/Makefile.am
- python.d/README.md
- python.d/dns_query_time.chart.py
required `python-dnspython`
https://github.com/firehol/netdata/issues/1393
> Dns query time

- python.d/dns_query_time.chart.py
- python.d/fail2ban.chart.py
- python.d/ovpn_status_log.chart.py
- python.d/smartd_log.chart.py
> dns_query_time plugin: replace "." with "_" in dimensions

- conf.d/python.d/fail2ban.conf
- python.d/fail2ban.chart.py
- python.d/redis.chart.py
@ktsaou this is not ready yet
Jail auto detection order now the same as in `man jail.conf`
- jail.conf
- jail.d/*.conf (in alphabetical order)
- jail.local
- jail.d/*.local (in alphabetical order)
@pschiffe
Can you test it before merging?
> fail2ban_plugin: jail auto detection improvements

- python.d/mysql.chart.py
> fix innodb dimension labels; 

- src/daemon.c
fixes #2036
netdata now reads environment variable `OOMScoreAdjust` and then consults `netdata.conf` for the OOM score.
Also, setting OOM score to any non numeric value, makes netdata let OOM score as it is.
> allow user to set out of memory score via environment and disable it in configuration file

- conf.d/apps_groups.conf
- configs.signatures
- src/main.c
> allow configuring TZ environment variable

- src/main.c
> do not set TZ variable if it is already set;

- python.d/ovpn_status_log.chart.py
https://github.com/firehol/netdata/issues/2075
@csamsel
@Zolotkey
Should work for both of you.
> ovpn_status_log plugin: support for "static key" status log files added

- src/main.c
> do not open listening ports when [web].mode = none

- src/appconfig.c
> fix access to uninitialized mutex in appconfig sections;

- plugins.d/python.d.plugin
https://github.com/firehol/netdata/issues/2109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firehol/netdata/2116)
> python.d.plugin: fixes #2109

- python.d/fail2ban.chart.py
https://github.com/firehol/netdata/issues/2118
> fail2ban plugin: regex update; fixes #2118

- src/plugins_d.c
- src/rrddim.c
> Slaves exposed dims fix

- src/proc_vmstat.c
remove space to not break the sent data to influxdb in inline mode and maybe other backend too
> Update proc_vmstat.c, remove space in rrd's name entry 

- conf.d/Makefile.am
- conf.d/python.d/samba.conf
- python.d/Makefile.am
- python.d/README.md
- python.d/Samba.chart.py
- python.d/samba.chart.py
- web/dashboard_info.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firehol/netdata/2094)
> First commit new Samba python plugin for smb2 uses smbd -P 1 profiling

- python.d/python_modules/base.py
- python.d/samba.chart.py
https://github.com/firehol/netdata/issues/2158
@ntlug
> Samba pluginx fix

- python.d/README.md
- src/plugin_proc.c
- src/plugin_proc.h
- src/proc_net_netstat.c
- src/proc_net_snmp.c
- src/statistical.c
- src/statistical.h
- src/statsd.c
- fixes #2172 
- fixes #2169 
- contributes to #827
> added sum dimension to statsd histograms; add TCPSynRetrans to TCP handshake chart

- src/statsd.c
- web/dashboard.js
> web dashboard optimizations for increased number of charts

- conf.d/Makefile.am
- conf.d/apps_groups.conf
- conf.d/python.d.conf
- conf.d/python.d/rabbitmq.conf
- python.d/Makefile.am
- python.d/README.md
- python.d/rabbitmq.chart.py
- python.d/redis.chart.py
https://github.com/firehol/netdata/issues/1813
Overview section from the management plugin. Better than nothing 😄
> Rabbitmq plugin

- python.d/mdstat.chart.py
@0x3333
I think i fixed it. Can you check it please?
> mdstat plugin: bugfix, fixes #2193

- plugins.d/alarm-notify.sh
> MIME encoded / multipart / text and html email notifications; 

- netdata-installer.sh
> Fix suggested command for auto updates

- python.d/haproxy.chart.py
- python.d/web_log.chart.py
> haproxy plugin: "idle percent" chart added; #2189

- src/socket.c
> silence error about SO_REUSEPORT if it is not available on the system

- python.d/haproxy.chart.py
- python.d/rabbitmq.chart.py
fixes bug in https://github.com/firehol/netdata/pull/2214
@dseira thx for reporting
> haproxy plugin: bugfix

- src/backends.c
fixes #2217 
Added option:
```
[backend]
opentsdb host tags = space separated list of TAG=VALUE
```
The above setting is only available when the backend is set to `opentsdb`
> added opentsdb host tags option;

- Makefile.am
- kickstart.sh
```
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```
> one line installation on linux

- Makefile.am
- kickstart-static64.sh
kickstart script for installing pre-built static netdata binaries.
> kickstart-static64.sh

- conf.d/health.d/mongo.conf
Requirements:
- Pymongo (in the host that is scraping the data)
> Added MongoDB alarm configuration

- src/statsd.c
> fix for synthetic chart gauge dimensions having the wrong divisor

- installer/functions.sh
- netdata-installer.sh
> allow netdata-updater.sh to run under non-bash

- src/daemon.c
> prevent logging error about supplementary groups when netdata is not started as root

- conf.d/python.d/web_log.conf
- python.d/web_log.chart.py
fixes https://github.com/firehol/netdata/issues/2298
fixes https://github.com/firehol/netdata/pull/2299
> web_log plugin: support upstreaming timing variable of nginx

- src/rrddim.c
> fixed typo in divisor override

- conf.d/python.d/isc_dhcpd.conf
- python.d/isc_dhcpd.chart.py
human readable names for pools
new pools format in the module configuration file
```yaml
leases:
pools:
wifi: '192.168.2.0/24'
office: '192.168.3.0/24'
dmz: '192.168.4.0/24'
192.168.5.0/24: '192.168.5.0/24'
```
> Isc dhcpd improvements

- conf.d/Makefile.am
- conf.d/health.d/lighttpd.conf
- python.d/apache.chart.py
- web/dashboard_info.js
fixes https://github.com/firehol/netdata/pull/997
> apache plugin: renames job to "lighttpd" if "IdleServers" in response

- python.d/bind_rndc.chart.py
- python.d/python_modules/base.py
1. `_add_new_dimension` methond added (for dynamic dimensions)
2. `bind_rndc` rewritten to use `_add_new_dimension`
~~not well tested~~
> Bind rndc improvements

- kickstart-static64.sh
- kickstart.sh
- makeself/makeself-header.sh
- makeself/makeself.sh
- src/apps_plugin.c
1. allow `kickstart.sh` and `kickstart-static64.sh` to run unattented - fixes #2305 
2. apps.plugin now properly checks that users and groups have a name - fixes #2321
> unattended kickstart.sh ; minon bugfixes

- python.d/web_log.chart.py
fixes https://github.com/firehol/netdata/issues/2322
> web_log: bugfix (squid)

- plugins.d/python.d.plugin
fixes https://github.com/firehol/netdata/issues/2340
> python.d.plugin: plugin crashes if exception raises on job init fixed

- conf.d/python.d/elasticsearch.conf
- python.d/elasticsearch.chart.py
plugin fails if there is no `'fetch_total'` or `'open_file_descriptors'` in `node_stats`. fixed.
> elasticsearch bugfix and conf file update

- src/freebsd_ipfw.c
> Disable ipfw charts for FreeBSD 10

- conf.d/health.d/ram.conf
- configs.signatures
- src/health_config.c
> excluded zfs arc from used memory alarm

- src/rrdpush.c
> log a line in error.log if multiple slaves are sending metrics for the same host

- src/common.c
- src/rrddim.c
- src/rrdset.c
attempt to avoid resetting database files loaded from disk and be more descriptive when a reset is required
> avoid database resets when possible

- python.d/cpufreq.chart.py
fixes https://github.com/firehol/netdata/issues/2374
@ktsaou ready
> cpufreq plugin: cpu ordering in chart fixed

- kickstart.sh
> kickstart.sh should also run the installer

- src/main.c
- src/rrd.h
- src/rrdhost.c
- src/rrdset.c
> on exit delete orphan hosts and obsolete chart files; 

- makeself/install-or-update.sh
> static installs update config files that have not been edited by users

- src/proc_diskstats.c
> diskstats now lookup /dev/mapper names

- node.d/README.md
It was empty... Adding it to the python.d/readme.md seemed wrong to me.
> Wiki page for Fronius plugin

- python.d/elasticsearch.chart.py
- python.d/mongodb.chart.py
fixes https://github.com/firehol/netdata/issues/2443
> Es and mongo bugfix

- conf.d/apps_groups.conf
- web/dashboard.html
- web/dashboard.js
- web/demo.html
- web/demo2.html
- web/demosites.html
- web/demosites2.html
- web/index.html
> allow min/max of easypiechart and gauge be non-zero-based

- installer/functions.sh
Place init-scripts for Oralce Linux 5/6 releases
>  Support for Oracle Linux #2480

- installer/functions.sh
> install openrc file on alpine;

- web/dashboard.html
- web/dashboard.js
- web/demo.html
- web/demo2.html
- web/demosites.html
- web/demosites2.html
- web/goto-host-from-alarm.html
- web/index.html
- web/registry.html
- web/tv.html
> allow easypiecharts to render arbitrary ranges; 

- python.d/python_modules/base.py
https://github.com/firehol/netdata/issues/2506
> python.d.plugin bugfix: wrap urllib3.disable_warnings in try/except

- .codacy.yml
- src/appconfig.c
- web/dashboard.js
fixes #2455 (easypiechart animation direction)
fixes #2493 (boolean config options accept: yes, true, on, auto, on demand: case insensitive)
updated `.codacy.yml` based on the directions of codacy support
> allow easypiecharts to animate clockwise and counter clockwise;

- .gitignore
- Makefile.am
- configure.ac
- diagrams/Makefile.am
- makeself/Makefile.am
- tests/Makefile.am
- web/dashboard.css
- web/dashboard.js
- web/dashboard.slate.css
- web/dashboard_info.js
- web/index.html
also minor makefiles re-organization
> containers and VMs get gauge charts

- src/sys_fs_cgroup.c
> max number of cgroups increased by default to 1000

- python.d/postgres.chart.py
Resolve issue raised in #2520 that led to non superuser instances
attempting to execute queries that require superuser privs.
> postgres.chart.py: Fix superuser bug.

- python.d/mysql.chart.py
- python.d/python_modules/base.py
disable `my.cnf` parsing for `pymysql`
#2500
> Mysql plugin bugfix

- python.d/postgres.chart.py
Prevents issue raised in #2569.
> Ensure configured user has the necessary permissions.

- src/freebsd_sysctl.c
- src/plugin_freebsd.c
- src/plugin_freebsd.h
Solves #2544. Unfortunately, coretemp sysctls are quite heavy calls.
> Add CPU temperature chart to FreeBSD plugin

- Makefile.am
- conf.d/Makefile.am
> Add missing entries from makefiles

- web/dashboard.html
- web/dashboard.js
- web/index.html
> allow dashboard.js to work under wordpress

- src/statsd.c
> 95th percentile should return the max value that the 95% of the values are below it

- python.d/elasticsearch.chart.py
- python.d/web_log.chart.py
Attempt to fix #2530
@ktsaou please check the fix
fixes https://github.com/firehol/netdata/issues/2603
> web_log bugfix: properly parse squid response codes

- conf.d/Makefile.am
- conf.d/python.d.conf
- conf.d/python.d/chrony.conf
- python.d/Makefile.am
- python.d/README.md
- python.d/chrony.chart.py
Following the suggestions in #2357, here a module for chrony based on ExecutableService.
Please comment.
> Statistics for precision of time data of local chrony

- python.d/fail2ban.chart.py
fixes https://github.com/firehol/netdata/issues/2702
@G4Zz0L1 
i think i fixed the bug, please check
> fail2ban: jailes search function bugfix

- python.d/cpufreq.chart.py
The way I was tracking it before was bad because if we were too early or late reading the time_in_state file, we might get really bogus results.
Now we remember the last snapshot we saw, and show the average frequency *since we last refreshed*.
> cpufreq.chart.py: use much more accurate accounting for average CPU frequency

- python.d/cpuidle.chart.py
I noticed that the cpuidle.chart.py script run time was spiking whenever all the CPUs were busy:
In retrospect this makes perfect sense. Busy CPUs would be slower to respond to some new thread being scheduled onto them via `sched_setaffinity`.
The fix is pretty straightforward. We only need to tickle CPUs we know are idle -- i.e. those which have counters that aren't changing in `/proc/schedstat`.
> cpuidle.chart.py: only tickle known-to-be-idle CPUs

- conf.d/python.d/chrony.conf
- configs.signatures
- python.d/chrony.chart.py
- system/netdata.service.in
- web/dashboard_info.js
- web/index.html
1. Added information on the metrics collected
2. Prettyfied the charts a bit (merged a few charts, added colors, etc)
3. forced update frequency to 5 seconds (to lower the number of forks made by netdata)
@l2isbad please review this.
cc: @domschl @fooltux
> chrony updates

- src/common.c
- src/rrdset.c
> escape invalid characters from chart parameters

- CMakeLists.txt
- src/Makefile.am
- src/common.h
- src/daemon.c
- src/daemon.h
- src/main.c
- src/popen.c
- src/signals.c
- src/signals.h
netdata was calling illegal system functions inside the signal handler.
Fixed it by moving everything outside the signal handler.
Also fixes #2727 (added SIGBUS handler)
> netdata new signal handler

- src/plugins_d.c
> prevent duplicate chart names when streaming; 

- src/main.c
- src/web_api_v1.c
- src/web_client.c
- src/web_client.h
> more access control lists

- src/rrd.h
- src/rrdhost.c
- src/rrdpush.c
- src/rrdset.c
> fixes for high traffic netdata proxies

- CMakeLists.txt
- src/Makefile.am
- src/plugin_proc_diskspace.c
> do not report inodes on filesystems that have dynamic inodes such a cephfs

- python.d/web_log.chart.py
fixes https://github.com/firehol/netdata/issues/2675
fixes #2201
@MartijnBraam
I did some changes can you test it?
> web_log: add support for empty requests

- conf.d/health.d/redis.conf
- python.d/redis.chart.py
fixes https://github.com/firehol/netdata/issues/2581
@ktsaou 
@jurgenhaas
please post the alarms you want here i will add them to the PR
> redis: "rdb_bgsave_in_progress" + "rdb_last_bgsave_status"

- src/health.c
- src/health.h
- src/health_config.c
- src/rrdcalc.c
- src/rrdcalctemplate.c
- src/rrdhost.c
https://github.com/firehol/netdata/issues/2382#issuecomment-332664288
> prevent log errors while freeing incompatible alarms and alarm templates

- README.md
As requested in #2818. /cc @ktsaou
> Update infographic in /README.md

- conf.d/python.d.conf
https://github.com/firehol/netdata/issues/2724
> disable chrony module by default

- python.d/tomcat.chart.py
> fix tomcat memory pool

- python.d/tomcat.chart.py
fix #2837 
I deep searched about JVM memory pool and found:
PS Old Gen: parallel GC
Tenured Gen: Serial GC
I'll send PR later.
ref. https://searchcode.com/file/125200329/src/share/vm/services/memoryService.cpp
> fix Tenured gen

- src/macos_sysctl.c
Using macOS version detection macros from `Availability.h` I can skip TCP ECN statistics and inline a missing header file to support netdata on mac OSX 10.10 and 10.9 as discussed in #1915 .
It seems th ECN stats struct members have been added with OSX 10.11 and this is a simple workaround to support the older versions.
Going back even further (someone mentioned OSX 10.5! in the issue) looks to be a more complicated endeavour, as at least some udp and vm statistics are missing as well. The XNU sources on github are a super useful resource for that: https://github.com/apple/darwin-xnu/blame/0a798f6738bc1db01281fc08ae024145e84df927/osfmk/mach/vm_statistics.h#L155
I tested the changes on 10.9 through 10.12 with vagrant VMs and everything builds fine. 10.11+ show the ECN stats, where as they …
> add backwards compatibility for mac OSX 10.10 and 10.9

- src/rrd.h
- src/rrdset.c
- web/dashboard.js
https://github.com/firehol/netdata/issues/2654#issuecomment-334742832
> do not allow duplicate chart names

- README.md
- conf.d/health_alarm_notify.conf
- plugins.d/alarm-notify.sh
Hi, I've added support for kavenegar.com (Iranian API based sms service) because twillo and messagebird banned iranian users. I've copied all of code from messagebird.com plugin.
> Add Kavenegar.com, Iranian API based sms service

- src/freebsd_sysctl.c
- src/plugin_freebsd.c
- src/plugin_freebsd.h
> Add CPU frequency chart to FreeBSD plugin

- plugins.d/alarm-notify.sh
> properly close the multi-part emails; 

- src/apps_plugin.c
- src/freebsd_sysctl.c
Fixes https://github.com/firehol/netdata/pull/1321#issuecomment-333936592
> Fix compilation errors for FreeBSD 12.0

- src/common.c
- src/macos_mach_smi.c
- src/macos_sysctl.c
Fixes https://github.com/firehol/netdata/issues/1915#issuecomment-333384278 and https://github.com/firehol/netdata/pull/2850#issuecomment-335258743
> Fix compilation errors for Mac OS X 10.5

- plugins.d/alarm-notify.sh
1. custom sender should require curl
2. fixed typos in conditions with ==
> alarm-notify.sh fixes

- src/freebsd_devstat.c
- src/freebsd_kstat_zfs.c
- src/plugin_freebsd.c
- src/plugin_freebsd.h
> Add ZFS TRIM statistics and additional dimensions for disk charts to FreeBSD Plugin

- src/plugin_tc.c
> sort tc classes the way they are exposed by tc

- plugins.d/alarm-notify.sh
This fixes a regression of https://github.com/firehol/netdata/pull/2915.
> fix pushbullet sender

- plugins.d/alarm-notify.sh
> fixed typo that affected the priority of pushover notifications

- conf.d/health_alarm_notify.conf
- plugins.d/alarm-notify.sh
Implemented compatible alarm notifications for flock.com webhooks similar to how the other webhooks are implemented.
> added support for flock notification webhooks

- installer/functions.sh
> install the init.d file on CloudLinux Server release 6.x

- python.d/varnish.chart.py
fixes https://github.com/firehol/netdata/issues/2986
> varnish module bugfix

- node.d/node_modules/netdata.js
- src/proc_net_sockstat.c
- src/proc_net_sockstat6.c
fixes #2955 
---
fixes the units of tcp and tcp6 sockstats charts
> handle exceptions in node processor functions

- node.d/named.node.js
- node.d/node_modules/netdata.js
> fix node.d.plugin responseProcessor failures; 

- python.d/tomcat.chart.py
> enable partial match for tomcat connector

- plugins.d/cgroup-name.sh
- plugins.d/cgroup-network-helper.sh
- src/sys_fs_cgroup.c
> support for .libvirt-qemu naming of cgroups; 

- web/index.html
> snapshot compression method is now selectable

- src/freeipmi_plugin.c
> freeipmi.plugin: added option to ignore sensor ids; 

- web/index.html
fix of the last PR, that prevented snapshots to be loaded.
> allow snapshots to be loaded

- web/dashboard.js
When panning with the mouse, all the charts are refreshed as soon as the the mouse button is released.
Fixed a bug that prevented the main chart from being refreshed, if the mouse button was held pressed for a prolong time, while panning.
Touch tap on chart did not work correctly with data padding (it seems this was a long standing bug - since the first day).
Touch tap on a chart, now selects this point on all charts (it was selecting it only on the tapped chart).
> pan and zoom fixes

- conf.d/python.d/smartd_log.conf
- python.d/README.md
- python.d/python_modules/bases/charts.py
- python.d/smartd_log.chart.py
- python.d/varnish.chart.py
WIP
@skibbipl
feel free to test 😄 
> Make the smartd plugin "smarter". Parse smartd_log files only if they're updated in the last X (configurable) days. 
Implemented. In minutes. 'age' option. Default is ~~60~~ 30.
> Allow plugin to detect external drives when they're connected to the machine
implemented
> smartd_log, varnish modules improvements + other minor bugfixes

- python.d/mdstat.chart.py
fixes https://github.com/firehol/netdata/issues/3092
> mdstat module regex bugfix

- src/statsd.c
statsd timers and histograms used to maintain their last value, until a new value is collected. This was providing misleading information, as the timers and histograms were presenting non-zero value, although no data had been collected.
This PR makes statsd timers and histograms report zero when no data are collected.
before and after this PR:
> statsd timers and histograms should report zeros if nothing is collected

- python.d/varnish.chart.py
fixes https://github.com/firehol/netdata/issues/3054
> varnish_module: memory usage calc fix

- conf.d/apps_groups.conf
Added daemons of [Ceph](//ceph.com/) - unified, distributed storage system.
> apps_groups: added ceph group.

- python.d/python_modules/bases/FrameworkServices/UrlService.py
fixes https://github.com/firehol/netdata/issues/2837#issuecomment-350039060
> UrlService: self signed certs verification disabled

- conf.d/python.d/postgres.conf
> fix typo in postgres config file

- conf.d/apps_groups.conf
Added several email applications, mostly related to Zimbra.
> Added some email and one logs applications.

- installer/functions.sh
- makeself/install-or-update.sh
- makeself/jobs/70-netdata-git.install.sh
- makeself/jobs/99-makeself.install.sh
- makeself/makeself.lsm
- netdata-installer.sh
and provide a sane default when this is not possible.
also the static installer lsm states the correct version of netdata.
> both installers download configuration netdata

- conf.d/apps_groups.conf
- conf.d/python.d.conf
- conf.d/python.d/dnsdist.conf
- python.d/Makefile.am
- python.d/README.md
- python.d/dnsdist.chart.py
I wrote a plugin for my dnsdist installation.
I am new to netdata so I took the powerdns plugin as base.
Maybe a dev can review, modify and merge (if useful) it...
https://dnsdist.org/
Best regards
> Support for dnsdist

- src/sys_fs_cgroup.c
> remove unecessary cgroup renames; 

- plugins.d/cgroup-network-helper.sh
> run virsh with -r for read-only access;

- kickstart-static64.sh
- makeself/install-or-update.sh
fixes https://github.com/firehol/binary-packages/issues/3
> support option --dont-start-it on static 64 bit installer; 

- conf.d/health.d/isc_dhcpd.conf
- python.d/isc_dhcpd.chart.py
fixes https://github.com/firehol/netdata/issues/3174
> Isc dhcpd ipv6

- plugins.d/alarm-notify.sh
> remove <small></small> from hipchat messages; 

- charts.d/apcupsd.chart.sh
- conf.d/charts.d/apcupsd.conf
> multiple APC UPSes; 

- charts.d/apcupsd.chart.sh
- conf.d/charts.d/apcupsd.conf
- src/socket.c
> Async connect

- conf.d/health_alarm_notify.conf
- plugins.d/alarm-notify.sh
Added suport for alerta.io
fixes: #3147
> add support for alerta.io 

- kickstart-static64.sh
> added --accept as a valid kickstart-static64.sh option;

- charts.d/libreswan.chart.sh
> check that the ipsec command is libreswan; 

- web/dashboard_info.js
see: https://github.com/firehol/netdata/issues/3227
> Change icon for network interfaces in dashboard

- src/common.h
- src/freebsd_sysctl.c
- src/macos_mach_smi.c
- src/proc_meminfo.c
- src/proc_vmstat.c
- src/sys_devices_system_edac_mc.c
- src/sys_devices_system_node.c
- src/sys_kernel_mm_ksm.c
> properly position memory charts on the dashboard;

- src/plugin_proc_diskspace.c
- src/proc_diskstats.c
- src/proc_self_mountinfo.c
- src/proc_self_mountinfo.h
- src/sys_fs_cgroup.c
avoid stack overflow due to recursion;
fixes #3254
> support for huge amount of mountpoints

- src/rrd.c
- src/rrd.h
- src/rrdhost.c
- src/rrdset.c
and removed it from each chart.
> add global config option gap when lost iterations above, 

- src/socket.c
ok, this is embarrassing.
PR #3248 broke also statsd UDP data reception.
This PR fixes it.
> handle incoming traffic on UDP sockets

- plugins.d/cgroup-network-helper.sh
- src/cgroup-network.c
- src/popen.c
- src/popen.h
> strip environment on cgroup-network;

- installer/functions.sh
- makeself/functions.sh
- makeself/jobs/50-bash-4.4.install.sh
- makeself/jobs/50-curl-7.53.1.install.sh
- makeself/jobs/50-fping-4.0.install.sh
- netdata-installer.sh
- src/apps_plugin.c
> apps.plugin freebsd fixes; 

- src/sys_kernel_mm_ksm.c
> KSM: saved pages is pages_sharing; 

- src/sys_kernel_mm_ksm.c
- web/dashboard_info.js
- web/index.html
fixes https://github.com/firehol/netdata/issues/3304#issuecomment-359145392
> KSM: remove to_scan metric;

- conf.d/Makefile.am
- conf.d/health.d/nginx_plus.conf
- conf.d/python.d.conf
- conf.d/python.d/nginx_plus.conf
- python.d/Makefile.am
- python.d/README.md
- python.d/nginx_plus.chart.py
~~WIP~~ (not a `nginx plus` user)
fixes https://github.com/firehol/netdata/issues/3049
[snapshot](https://github.com/firehol/netdata/files/1645530/netdata-workPc-20180119-153357-480.gz)
@kmhagan
> Nginx plus

- src/statsd.c
Restarting netdata all the statsd metrics are now loaded back, until an event is received for them.
This also makes statsd synthetic charts to disappear until the statsd metrics needed are received.
This PR allows a special value on all statsd metrics: `zinit`. This value makes netdata load the metrics, without affecting their values. Of course, gauges, sets, etc will be zero.
Using this feature, a simple shell script can be created to instantiate the required statsd metrics, which results in instantiating all the statsd synthetic charts.
I evaluated a few alternatives for this, like loading back all the statsd metrics that were loaded before restarting netdata.
The problem with all those solutions, is that only the user really knows which metrics are useful and should be loaded.
> allow statsd metrics to be initialized with value "zinit"

- python.d/mdstat.chart.py
fixes https://github.com/firehol/netdata/issues/3331
> mdstat fixes

- python.d/haproxy.chart.py
Added:
- hrsp_1xx, hrsp_2xx, hrsp_3xx, hrsp_4xx, hrsp_5xx, hrsp_other, hrsp_total for backands and frontends 
- qtime, ctime, rtime, ttime metrics for backand servers
- Backend Servers In UP State
> Improve haproxy 

- web/dashboard.js
> allow stacked charts to zoom vertically when dimensions are selected

- node.d/fronius.node.js
- tests/node.d/fronius.parse.spec.js
One could say I didn't test it enough ;) But now it works as it should.
> Fixes a bug in recent fronius plugin change

- conf.d/health.d/swap.conf
- configs.signatures
- plugins.d/cgroup-name.sh
- src/sys_fs_cgroup.c
fixes #3367 (systemd-nspawn support)
fixes #3380 (work-around for faulty reporting of swap free memory by kernel)
> support systemd-nspawn containers

- src/socket.c
- src/socket.h
- src/statsd.c
- src/web_server.c
1. configurable tcp idle timeout for statsd tcp clients
2. disabled request timeout for statsd tcp clients
3. added tcp statsd sockets monitoring charts
> statsd tcp improvements

- web/index.html
> print button URL should respect the URL path;

- python.d/python_modules/bases/FrameworkServices/ExecutableService.py
fixes https://github.com/firehol/netdata/issues/3406
> executable service: decode error fix

- src/proc_uptime.c
> use /proc/uptime for uptime when now_boottime_usec() differs; 

- Dockerfile.alpine
> add sync to overcome text file busy on docker hub; 

- plugins.d/python.d.plugin
- python.d/isc_dhcpd.chart.py
fixes https://github.com/firehol/netdata/issues/3442
@HammaBamma 
please check it
> isc_dhcp fix: do not include leases without "ends"

- src/proc_meminfo.c
- web/dashboard_info.js
- web/index.html
> transparent hugepages monitoring;

- src/web_api_v1.c
- src/web_buffer_svg.c
- src/web_buffer_svg.h
(scale >= 100)
https://github.com/firehol/netdata/issues/1921#issuecomment-368028528
> badges can be scaled by appending scale=X

- src/apps_plugin.c
> fix compilation of apps.plugin under freebsd;

- conf.d/Makefile.am
- conf.d/python.d/springboot.conf
- python.d/Makefile.am
- python.d/README.md
- python.d/springboot.chart.py
Support Java [spring-boot](https://projects.spring.io/spring-boot/)  application.
> add charts for springboot

- web/index.html
> allow alarms to use either chart IDs or chart names; 

- src/rrdset.c
> added more information to info logs about data collection timings; 

- python.d/python_modules/bases/FrameworkServices/SimpleService.py
- python.d/python_modules/bases/charts.py
requested in https://github.com/firehol/netdata/pull/3421#issuecomment-369424744
> python SimpleService: auto refresh obsolete charts added

- python.d/postgres.chart.py
> Postgres : Handle when server is in recovery

- python.d/python_modules/bases/FrameworkServices/UrlService.py
should fix #3448 decode() problem
> Fix httpcheck decode bug

- conf.d/Makefile.am
- conf.d/python.d.conf
- conf.d/python.d/icecast.conf
- python.d/Makefile.am
- python.d/README.md
- python.d/icecast.chart.py
closes https://github.com/firehol/netdata/issues/3486
@tommybuck
> Icecast module

- src/backend_prometheus.c
https://github.com/firehol/netdata/issues/3519#issuecomment-372737941
> fix prometheus parsing error 

- conf.d/python.d.conf
- conf.d/python.d/ntpd.conf
- python.d/README.md
- python.d/ntpd.chart.py
- web/dashboard_info.js
Documentation updated as requested in #3421.
I added descriptions for the system charts only. Because the peer charts are not shown by default and I do not know what those charts mean :smile: 
The wiki is updated as well.
> Update documentation for ntpd

- conf.d/Makefile.am
- conf.d/python.d/traefik.conf
- python.d/Makefile.am
- python.d/README.md
- python.d/traefik.chart.py
> Added charts for traefik reverse proxy

- web/dashboard.js
fixes https://github.com/firehol/netdata/issues/3571#issuecomment-376534259
> clear selection date when hover ends; #3571

- LICENSE-REDISTRIBUTED.md
- web/index.html
https://github.com/firehol/netdata/issues/651#issuecomment-376829669
> added six.py to LICENSE-REDISTRIBUTED.md and updated the missing licenses on index.html

- plugins.d/tc-qos-helper.sh
https://github.com/firehol/netdata/issues/2218 happened to me again.
So, this PR gives a descriptive error in netdata/error.log
> improved error logging when netdata cannot find fireqos class names

- python.d/mongodb.chart.py
> Fixing typo

- system/netdata-openrc.in
quote variables where able
switch to more posix double and
remove unused variables
> update openrc init script

- python.d/postgres.chart.py
fixes https://github.com/firehol/netdata/issues/3614 plus some identation fixes
> postgres module: TypeError fix in query_stats_

- web/demosites.html
> update copyright year

- python.d/python_modules/bases/FrameworkServices/UrlService.py
fixes https://github.com/firehol/netdata/issues/3641
@ktsaou 
should work on `py2` and `py3` after the fix
> UrlService decode fix

- src/statsd.c
fixes #3630 
2 issues fixed:
1. histograms with sampling rate had wrong calculations
2. for gauges when no `+` and no `-` is in the value should ignore the sampling rate. For gauges the sampling rate should only be used when there is sign (which increases or decreases the value of the gauge).
The smaller sampling rate allowed is now 0.001
> fix statsd sampling rates calculations;

- installer/functions.sh
> install init file on amzn-2018 distro; 

- src/rrddim.c
When multiple threads are adding dimensions to the same chart in parallel, one thread may end up consuming 100% cpu and the other being locked.
This is quite unusual, but may happen when streaming from a host that runs more than one netdata (headless collectors) and the master has memory mode `map` (in this mode, netdata depends on disk I/O so even if the receiving threads are started with a slight time difference, they most probably be synchronized at the chart/dimension it is not cached by the kernel).
This PR fixes it, by extending a bit a lock that was just too narrow to catch this case.
> fix 100% cpu when adding dimension in parallel to the same chart

- web/dashboard.js
> allow hidding each axis on dygraphs;

- conf.d/Makefile.am
- conf.d/python.d.conf
- conf.d/python.d/puppet.conf
- python.d/Makefile.am
- python.d/README.md
- python.d/puppet.chart.py
- Added universal module based on Puppet status API
- There is room for further improvement to increase metric count
> NEW: Puppet Server and Puppet DB basic monitoring

- netdata-installer.sh
> added option --disable-x86-sse to netdata-installer.sh; 

- .gitignore
- installer/functions.sh
- system/Makefile.am
- system/netdata.plist.in
>  install startup script on MacOS

- CMakeLists.txt
- src/Makefile.am
- src/common.h
- src/plugin_proc.c
- src/plugin_proc.h
- src/proc_net_netstat.c
- src/proc_net_sctp_snmp.c
- src/proc_net_snmp.c
- src/proc_net_sockstat.c
- src/proc_net_stat_conntrack.c
- src/proc_net_stat_synproxy.c
- web/dashboard_info.js
- web/index.html
> SCTP monitoring

- web/dashboard_info.js
- web/index.html
fixes #3707 
cc: @Ferroin your merge broke it...
> fix dashboard_info.js; 

- charts.d/nut.chart.sh
Add runtime value that indicates remaining time before UPS extinction
> Add runtime value

- installer/functions.sh
- netdata-installer.sh
> fix uninstaller on MacOS

- src/clocks.c
- src/rrdset.c
> debugging code for checking clock drifts

- plugins.d/python.d.plugin
- python.d/Makefile.am
- python.d/python_modules/bases/FrameworkServices/SimpleService.py
- python.d/python_modules/bases/monotonic.py
@ktsaou 
https://github.com/firehol/netdata/issues/3752
i have a question about `clock_gettime(CLOCK_MONOTONIC_RAW, ctypes.pointer(t)) != 0`
if i understand it right i have to [check](https://github.com/l2isbad/netdata/blob/py2_monotonic_time/python.d/python_modules/bases/monotonic.py#L29) it [only once on start](https://github.com/l2isbad/netdata/blob/py2_monotonic_time/python.d/python_modules/bases/FrameworkServices/SimpleService.py#L12-L14), not on every call, right?
> Py2 monotonic time

- conf.d/health_alarm_notify.conf
- plugins.d/alarm-notify.sh
I implemented notifications for rocketchat. 
My manual tests went very fine.
Nevertheless, I'm not quite sure if I got every possible config parameter. 
Therefore I would really appreciate feedback of you guys.
Regards,
Hermsi
> Add rocket.chat notifications

- conf.d/Makefile.am
- conf.d/python.d.conf
- conf.d/python.d/litespeed.conf
- installer/functions.sh
- python.d/Makefile.am
- python.d/README.md
- python.d/litespeed.chart.py
fixes https://github.com/firehol/netdata/issues/3781
@lucasRolff  please check
what should i change/add?
add:
> Litespeed module

- CMakeLists.txt
- node.d/node_modules/net-snmp.js
> update net-snmp.js to latest version

- python.d/python_modules/bases/FrameworkServices/SocketService.py
- python.d/redis.chart.py
Fixes #3783
Fixes #3140 
@zhangxin0112
please test it
any suggestions are welcome (not a `redis`/`pika` user)
> redis: refactor + pika support

- python.d/hddtemp.chart.py
- python.d/litespeed.chart.py
- python.d/w1sensor.chart.py
Fixes #3683 
`UNK` and `SLP` are reported as zero
@adrfantini
please test it
> hddtemp: refactor + correctly parse /disk/by-id

- src/plugin_proc_diskspace.c
> default excluded filesystems from disk space monitoring; 

- CONTRIBUTORS.md
> Sign the CLA.

- plugins.d/alarm-notify.sh
> alarm-notify.sh: allow sender names with spaces; 

- CONTRIBUTORS.md
see https://github.com/firehol/netdata/pull/3695#issuecomment-399771854
> Sign the CLA

- CONTRIBUTORS.md
- charts.d/nut.chart.sh
- conf.d/charts.d/nut.conf
Fixes https://github.com/firehol/netdata/issues/3829
> add ability to alias nut UPS names

- CONTRIBUTORS.md
- src/freebsd_getifaddrs.c
- web/dashboard.js
For monitor storm packages pps/Kpps/Mpps is crucial ;D
> Update freebsd_getifaddrs.c and dashboard.js to scalableUnits packages(pps)

- plugins.d/charts.d.plugin
> log failed commands return code; 

- conf.d/Makefile.am
- conf.d/health.d/megacli.conf
- conf.d/python.d/megacli.conf
- python.d/Makefile.am
- python.d/README.md
- python.d/megacli.chart.py
- python.d/python_modules/bases/FrameworkServices/ExecutableService.py
fixes #3757 
yo @petarkozic
please test it
make sure that the `megacli` command can be executed by the `netdata` user
```bash
sudo su -s /bin/bash netdata
megacli -LDPDInfo -aAll
```
This is wip version so i am open to any suggestion :smile: 
___
todo:
> python megacli plugin

- CONTRIBUTORS.md
> Sign CLA: glensc

- python.d/python_modules/bases/loaders.py
> python loaders: fallback to yaml package

- src/web_buffer_svg.c
> added boolean badges units with dash too;

- src/statsd.c
> statsd extracts and ignores datadog statsd tags

- python.d/README.md
- python.d/powerdns.chart.py
fixes #3970
yo @lwhitworth
One more thing to do (102nd), please test it :smile_cat:
> Powerdns recursor

- python.d/README.md
- python.d/beanstalk.chart.py
- python.d/python_modules/bases/loaders.py
> Beanstalk yaml load fix

- python.d/python_modules/bases/charts.py
> python.d: add 'hidden' option to charts

- src/log.c
> do not get the address of FILE pointer; 

- CONTRIBUTORS.md
- python.d/ipfs.chart.py
Avoid building (potentially large) unneeded list of strings
> Optimize counting of recusive pins

- system/netdata.service.in
> remove condition from netdata.service

- python.d/fail2ban.chart.py
fixes #4144
- ipv6 parse support added
- module simplification
> [WIP] fail2ban: ipv6 support added + module simplification

- .travis.yml
- .travis/create_artifacts.sh
Trying to introduce travis build stages, clean CI pipelines and introduce tests
Solves #4133
This is required to have a clean way to build distro packages in the future.
> [cleanup crusade] travis build stages

- .travis.yml
Follow-up to https://github.com/firehol/netdata/pull/4142 to fix error spotted in https://travis-ci.org/firehol/netdata/jobs/427588706
> Fix lack of dot

- src/proc_stat.c
This PR adds variable `$system.cpu.processors` that resolves to the number of processors on the system. For systems with dynamic number of processors, this variable is updated together with chart `system.cpu` to match the number of processors listed in `/proc/stat`.
fixes #3003
> add variable system.cpu.processors for alarms; 

- .travis.yml
- .travis/containerized_build.sh
- .travis/images/Dockerfile.alpine
- .travis/images/Dockerfile.centos6
- .travis/images/Dockerfile.centos7
- .travis/images/Dockerfile.ubuntu1804
PoC for building/installing netdata with travis in docker containers.
> CI builds in containers

- contrib/nc-backend.sh
- contrib/rhel/build-netdata-rpm.sh
Continuation of #4159. Can be merged independently.
> [cleanup crusade] shellcheck in contrib

- python.d/elasticsearch.chart.py
> elasticsearch: handle json parse error in threads

- src/proc_diskstats.c
> name veritas volume disk groups

- python.d/redis.chart.py
> redis plugin bugfix

- web/index.html
> added UTC to server timezones list;

- src/appconfig.c
> allow empty values in config settings; 

- web/dashboard.js
- web/index.html
> fix netdata server URL detection in dashboard.js;

- src/cgroup-network.c
- src/health.c
- src/plugin_tc.c
- src/sys_fs_cgroup.c
related to https://github.com/Semmle/ql/issues/199
> workaround for LGTM false-positives

- CONTRIBUTORS.md
Updated the CLA too to reflect this change.
https://cla-assistant.io/firehol/netdata
> CLA signing using cla-assistant.io

- python.d/varnish.chart.py
> varnish plugin bugfix

- docker/build.sh
> fix docker image tagging problem

- .github/CODEOWNERS
This will allow to automatically assign people to review code when PR is opened.
@ktsaou please read this before merging: https://help.github.com/articles/about-codeowners/
> [project management] add github CODEOWNERS

- docker/build.sh
- Set proper exit codes
- Fail whole script on failure of at least on component
> fail fast in docker builds

- .travis/create_artifacts.sh
- .travis/deploy-if-have-key
> [WIP] release less artifacts

- src/apps_plugin.c
Found 2 bugs:
1. there was a rare memory leak in apps.plugin - now fixed
2. PR #4233 introduced a few errors when clearing old files from processes (in its memory) - these errors also lead to memory leaks (not clearing the memory of obsolete files) - now fixed.
> apps.plugin fixes

- REDISTRIBUTED.md
- makeself/README.md
- plugins.d/README.md
- python.d/README.md
There's probably a lot more to fix, but it's better than nothing :slightly_smiling_face:
> Fix several typos in documentation

- .lgtm.yml
> better lgtm config

- python.d/megacli.chart.py
> megacli plugin: adapter regex update

- coverity-scan.sh
> fix typo in coverity scan script

- python.d/cpufreq.chart.py
- python.d/example.chart.py
- python.d/ipfs.chart.py
- python.d/mysql.chart.py
- python.d/phpfpm.chart.py
- python.d/python_modules/bases/FrameworkServices/LogService.py
- python.d/python_modules/bases/FrameworkServices/SocketService.py
- python.d/tomcat.chart.py
Mostly add @l2isbad as an author.
> give credit where credit is due

- coverity-scan.sh
Fix installation of coverity tool
> update variable after install

- python.d/mdstat.chart.py
- python.d/megacli.chart.py
- python.d/memcached.chart.py
- python.d/mongodb.chart.py
- python.d/monit.chart.py
- python.d/mysql.chart.py
PEP 8 compliance cleanups for python.d modules with names starting with M.
Relevant: #4167
> Python.d PEP 8 cleanup, modules M

- python.d/samba.chart.py
- python.d/sensors.chart.py
- python.d/smartd_log.chart.py
- python.d/spigotmc.chart.py
- python.d/springboot.chart.py
- python.d/squid.chart.py
- python.d/tomcat.chart.py
- python.d/traefik.chart.py
- python.d/unbound.chart.py
- python.d/varnish.chart.py
- python.d/w1sensor.chart.py
- python.d/web_log.chart.py
PEP 8 compliance cleanups for python.d modules with names starting with S, T, U, V, and W.
Relevant: #4167
> Python.d PEP 8 cleanup, modules S-Z

- .travis.yml
> Build OSX earlier than linux

- python.d/phpfpm.chart.py
- python.d/portcheck.chart.py
- python.d/postfix.chart.py
- python.d/powerdns.chart.py
- python.d/puppet.chart.py
- python.d/rabbitmq.chart.py
- python.d/redis.chart.py
- python.d/rethinkdbs.chart.py
- python.d/retroshare.chart.py
PEP 8 compliance cleanups for python.d modules with names starting with P and R.
Relevant: #4167
PostgreSQL module is handled separately in #4298.
> Python.d PEP 8 cleanup, modules P-R

- .travis.yml
It might be good to install libraries needed to build netdata.
> install some libs for coverity

- .travis.yml
- .travis/containerized_build.sh
- .travis/create_artifacts.sh
- charts.d/apache.chart.sh
- charts.d/cpu_apps.chart.sh
- charts.d/libreswan.chart.sh
- charts.d/load_average.chart.sh
- charts.d/mem_apps.chart.sh
- charts.d/mysql.chart.sh
- charts.d/nginx.chart.sh
- charts.d/nut.chart.sh
- charts.d/opensips.chart.sh
- charts.d/phpfpm.chart.sh
- charts.d/postfix.chart.sh
- charts.d/sensors.chart.sh
- charts.d/squid.chart.sh
- charts.d/tomcat.chart.sh
- coverity-scan.sh
- cppcheck.sh
- docker/build.sh
- installer/functions.sh
- kickstart-static64.sh
- kickstart.sh
- netdata-installer.sh
- plugins.d/alarm-test.sh
- plugins.d/cgroup-network-helper.sh
- plugins.d/charts.d.dryrun-helper.sh
- Disabling shellcheck for deprecated shell modules
- Linting more shell modules
- lint installer, kickstart, docker/build.sh and .travis/containerized_build.sh
> [cleanup crusade] Shellcheck

- docker/Dockerfile
Copy config files from builder image to final image.
Follow-up to #4182
> fix docker image

- .travis.yml
This was accidentally removed in #4328
Please merge ASAP
> reimplement #4332

- src/appconfig.c
- src/apps_plugin.c
- src/common.c
- src/common.h
- src/health_config.c
- src/log.h
- src/main.c
- src/statsd.c
fixes #4341 
fixes #4312
related to #4182
> better daemon errors about files; 

- conf.d/Makefile.am
- conf.d/health.d/linux_power_supply.conf
- conf.d/python.d.conf
- conf.d/python.d/linux_power_supply.conf
- python.d/Makefile.am
- python.d/README.md
- python.d/linux_power_supply.chart.py
- web/dashboard_info.js
This allows tracking battery statistics on Linux systems, as well as other energy storage devices that utilize the kernel's power_supply class (although i don't think there are drivers for any other type of energy storage device in the mainline kernel using this class right now).
The primary purpose of this module is twofold:
* To provide a way for battery powered IoT devices to easily alert about a low battery.
* To provide a way for all battery powered devices to alert on some easy to monitor battery health conditions.
It provides up to four charts, one which provides the remaining capacity as a percentage, and three others which report info about charge (in amp-hours), energy (in watt-hours), and voltage, each providing info about the current values, and possibly minimal and maximal …
> Add a python plugin for monitoring power supplies on Linux.

- conf.d/edit-config.in
- src/appconfig.c
- src/appconfig.h
Also, added some documentation to appconfig.{c,h}
> edit-config should use . instead of source with /bin/sh

- docker/build.sh
Fixing cron builds
@ktsaou this should fix broken builds.
> fix docker builds

- CMakeLists.txt
- collectors/freebsd.plugin/freebsd_kstat_zfs.c
- collectors/freebsd.plugin/freebsd_sysctl.c
- collectors/freebsd.plugin/plugin_freebsd.h
- web/server/web_client_cache.h
> fix compilation on FreeBSD; 

- collectors/charts.d.plugin/Makefile.am
- collectors/node.d.plugin/Makefile.am
- collectors/python.d.plugin/Makefile.am
- collectors/statsd.plugin/Makefile.am
- health/Makefile.am
- netdata.spec.in
> fix netdata.spec for new directory structure

- collectors/node.d.plugin/node.d.plugin.in
> fix node.d.plugin; 

- backends/README.md
- collectors/charts.d.plugin/ap/README.md
- collectors/node.d.plugin/named/README.md
- collectors/node.d.plugin/sma_webbox/README.md
- collectors/node.d.plugin/snmp/README.md
- collectors/node.d.plugin/stiebeleltron/README.md
- collectors/plugins.d/README.md
- collectors/python.d.plugin/sensors/README.md
- collectors/python.d.plugin/springboot/README.md
- collectors/python.d.plugin/w1sensor/README.md
Checked all `.md` files in the repo for dead links with this:
```sh
p="$(pwd)"
for x in $(find . -name \*.md)
do
echo
echo "${x}"
cd "$(dirname "$x")" || continue
markdown-link-check --progress -v "$(basename "$x")"
cd "${p}"
done
```
Fixed all the issues found.
> fixed README.md links

- .github/stale.yml
It will also need us to enable stale bot integration: https://probot.github.io/apps/stale/
Resolves #3914
> create stale bot integration

- .codacy.yml
- collectors/python.d.plugin/portcheck/portcheck.chart.py
- collectors/python.d.plugin/postgres/postgres.chart.py
- collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService.py
Removing variables which are not used in Python code
- python.d.plugin
- portcheck python module
- postgres python module
```paste below
```
> remove unused variables

- docker/Dockerfile
Change configuration file ownership inside a container.
Fixes #4453
docker container
```paste below
```
> fix permissions for config files in a container

- installer/functions.sh
> fix systemd detection; 

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
> unify headers in github templates

- collectors/python.d.plugin/mongodb/README.md
- collectors/python.d.plugin/mongodb/mongodb.chart.py
Fixes: #4407
:snake: python module `mongodb` :snake:
add version info for `python-pymongo` 
```paste below
```
> mongodb fix 

- collectors/python.d.plugin/icecast/icecast.chart.py
Fixes: #4432
:snake: python module `icecast`  :snake:
confirmed working by @tommybuck 
```paste below
```
> icecast bugfix

- .github/CODEOWNERS
Add @vlvkobal as a code owner for *.c and *.h files
GitHub management
> Add @vlvkobal as a code owner for C code

- collectors/README.md
Update docs to indicate that FreeIPMI works on FreeBSD
freeipmi
```paste below
```
> Indicate FreeIPMI support for FreeBSD

- .github/CODEOWNERS
Fix duplicate entry in CODEOWNERS file as this confuses GitHub
GitHub management
```paste below
```
> fix duplicate in CODEOWNERS file

- collectors/python.d.plugin/Makefile.am
- collectors/python.d.plugin/adaptec_raid/Makefile.inc
- collectors/python.d.plugin/adaptec_raid/README.md
- collectors/python.d.plugin/adaptec_raid/adaptec_raid.chart.py
- collectors/python.d.plugin/adaptec_raid/adaptec_raid.conf
- health/Makefile.am
- health/health.d/adaptec_raid.conf
Fixes #4396
python `adaptec_raid` module
:snake: new python module :snake:
Logical device charts:
- `Status Is Not OK` (Failed or Degraded)
Physical device charts:
- `State Is Not OK` (not Online)
- `S.M.A.R.T warnings` (count)
- `Temperature` (if present)
todo:
```paste below
```
screenshot:
@petarkozic
> adaptec_raid python module

- web/api/queries/query.c
Fixes bug introduced with #4443
Aligned queries were broken under conditions. They returned no data.
This was visible in badges and aligned alarms (none exists, so only custom alarms were affected).
The bug only appeared when the query time-frame was `before=0&after=-something`. Due to a calculation bug, it resulted in zero-duration to be queried.
```paste below
```
> bug-fix: fixed aligned queries that returned no data

- daemon/global_statistics.c
- daemon/global_statistics.h
- web/api/queries/README.md
- web/api/queries/query.c
- web/api/queries/rrdr.h
1. added queries readme;
2. added queries stats;
3. cleaned up global statistics
```paste below
```
> query engine documentation and stats

- web/api/queries/README.md
updated queries README
```paste below
```
> updated queries README

- web/api/queries/README.md
Fix queries README
```paste below
```
> Fix queries README

- web/api/queries/query.c
Prior to #4443 	the query engine was calculating min and max to be reported
to the caller. I checked then the source and found that it was not used.
I was wrong. It is used by `dashboard.js` to quickly decide the rounding of
numbers at charts' legends.
This PR restores it.
After #4443 and prior to this PR (variable number of fractional digits at the legend):
With this PR (common number of fractional digits at the legend):
```paste below
```
> restored min-max calculation of RRDR

- libnetdata/socket/socket.c
- web/api/Makefile.am
> fix RPM build

- .codacy.yml
Remove web/ugi/src from codacy checks
CI
More in #4496
> exclude web/gui/src from codacy checks

- collectors/node.d.plugin/snmp/snmp.node.js
this is a quickfix to make oidname replacement working in node.d snmp plugin.
node.d snmp plugin
> Fix(snmp): fix parse oidname and santilize dimension name

- CONTRIBUTORS.md
> Added @gmosx to CONTRIBUTORS.md

- .travis/releaser.sh
Change how releaser behaves so we can have a proper changelog when releasing new netdata version and so we won't have a duplicated changelog generation during nightly builds.
CI
```paste below
```
> first tag then generate changelog

- collectors/python.d.plugin/smartd_log/README.md
- collectors/python.d.plugin/smartd_log/smartd_log.chart.py
- collectors/python.d.plugin/smartd_log/smartd_log.conf
attempt to Fix: #4285
- scsi support
- change grouping/processing attributes (https://github.com/netdata/netdata/issues/4285#issuecomment-425654443)
:snake: `smartd_log` :snake: 
todo:
problems:
- netdata doesn't suppport deletion of dimension deletion in runtime
> smartd_log refactor plus SCSI support

- collectors/python.d.plugin/smartd_log/smartd_log.chart.py
Fidx: #4583
```paste below
```
> smartd_log: py2 compatibility fix

- HISTORICAL_CHANGELOG.md
- web/gui/demosites.html
Changed links to go to https://github.com/netdata/netdata/tree/master/web/api/badges as requested.
```paste below
```
> Update links to badges documentation.

- collectors/python.d.plugin/Makefile.am
- collectors/python.d.plugin/nvidia_smi/Makefile.inc
- collectors/python.d.plugin/nvidia_smi/README.md
- collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py
- collectors/python.d.plugin/nvidia_smi/nvidia_smi.conf
- collectors/python.d.plugin/python.d.conf
Fix: #4357
I couldn't commit to the #4357, maybe because it's [a fork of a fork](https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/).
:snake: nvidia_smi :snake: module
Uses `nvidia_smi` tool to collect GPU statistics.
It produces following charts (per GPU):
* GPU utilization
* memory allocation
* memory utilization
* fan speed
* power usage
* temperature
* clock speed
* PCI bandwidth
@madhavajay please test it
> nvidia_smi: init version added

- collectors/python.d.plugin/elasticsearch/README.md
Fixes a bad example config text.
> Bad text in example config

- web/gui/dashboard_info.js
Fixed tc-helper plugin broken link
```
> Fixed tc-helper plugin broken link

- web/gui/README.md
Took the little info we had in the wiki and put it here. This page needs a lot of work
> Added Dygraph and EasyPieChart info to README.md

- backends/WALKTHROUGH.md
Point to repo instead of the wiki
> Replace wiki links in backends WALKTHROUGH.md

- web/gui/custom/README.md
point ephemeral nodes to repo, web/ -> web/gui/
> Fix custom charts links

- web/gui/confluence/README.md
Link to api/badges instead of the wiki
> Replace link to creating badges

- doc/Third-Party-Plugins.md
The Nim third party plugin was a recent entry that was missed.
> Add Nim back to Third-Party-Plugins.md

- web/gui/main.js
> Minor cleanup of main.js

- collectors/python.d.plugin/Makefile.am
- collectors/python.d.plugin/openldap/Makefile.inc
- collectors/python.d.plugin/openldap/README.md
- collectors/python.d.plugin/openldap/openldap.chart.py
- collectors/python.d.plugin/openldap/openldap.conf
- collectors/python.d.plugin/python.d.conf
External python plugin for openldap monitoring
openldap plugin
This is an optional plugin turned off by default. Not sure if I have to include whole ldap python module under `python_modules`.
> openldap monitoring plugin added

- web/gui/demosites.html
- web/gui/main.js
Updated a few links to help with this issue.
```paste below
```
> Update Doc links for adding charts and alarms in sidebar. Isuue #4650

- collectors/python.d.plugin/python_modules/third_party/lm_sensors.py
- collectors/python.d.plugin/sensors/sensors.chart.py
This updates our copy of the libsensors Python bindings to the most recent upstream copy, which provides proper errors instead of just raising bare Exceptions, and updates our code to catch those errors instead of catching bare exceptions.
collectors/python.d.plugin/sensors
> Update lm_sensors and catch specific errors.

- .travis.yml
Currently nightly changelog generation is not using full git history which leads to problems.
CI
> clone full git history for changelog generation

- .github/CODEOWNERS
Assign code maintainers.
GitHub project management
```paste below
```
> allign code ownership

- HISTORICAL_CHANGELOG.md
- collectors/python.d.plugin/go_expvar/go_expvar.conf
- collectors/tc.plugin/tc-qos-helper.sh.in
- docker/Dockerfile
- netdata-installer.sh
- web/gui/dashboard_info.js
- web/gui/demosites.html
- web/gui/demosites2.html
- web/gui/index.html
- web/gui/main.js
Replaces links to wiki pages with links to the respective markdown files in the repo. The files with the updates in this PR are not MD files. 
Fixes #4650 
```paste below
```
> Wiki Link Updates

- web/gui/index.html
Replaces links to 3rd party tools with a link to REDISTRIBUTED.md
Updates the copyright notice.
> Cleanup of web/gui footer

- .github/stale.yml
> exempt feature requests from going stale

- htmldoc/buildyaml.sh
No need for a dropdown on the left navbar for a single file
> Make Getting Started just a top level link

- collectors/charts.d.plugin/ap/ap.chart.sh
- collectors/charts.d.plugin/apache/apache.chart.sh
- collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh
- collectors/charts.d.plugin/charts.d.dryrun-helper.sh
- collectors/charts.d.plugin/charts.d.plugin.in
- collectors/charts.d.plugin/cpu_apps/cpu_apps.chart.sh
- collectors/charts.d.plugin/cpufreq/cpufreq.chart.sh
- collectors/charts.d.plugin/example/example.chart.sh
- collectors/charts.d.plugin/exim/exim.chart.sh
- collectors/charts.d.plugin/hddtemp/hddtemp.chart.sh
- collectors/charts.d.plugin/libreswan/libreswan.chart.sh
- collectors/charts.d.plugin/load_average/load_average.chart.sh
- collectors/charts.d.plugin/loopsleepms.sh.inc
- collectors/charts.d.plugin/mem_apps/mem_apps.chart.sh
- collectors/charts.d.plugin/mysql/mysql.chart.sh
- collectors/charts.d.plugin/nginx/nginx.chart.sh
- collectors/charts.d.plugin/nut/nut.chart.sh
- collectors/charts.d.plugin/opensips/opensips.chart.sh
- collectors/charts.d.plugin/phpfpm/phpfpm.chart.sh
- collectors/charts.d.plugin/postfix/postfix.chart.sh
- collectors/charts.d.plugin/sensors/sensors.chart.sh
- collectors/charts.d.plugin/squid/squid.chart.sh
- collectors/charts.d.plugin/tomcat/tomcat.chart.sh
Lint all shell collector scripts
Collector/charts.d
```paste below
```
> lint all shell collectors code

- collectors/python.d.plugin/mongodb/README.md
Fixes: #4666
there was no info how to create `netdata` user in the readme file
```paste below
```
> mongodb: readme update

- web/api/queries/query.c
The query engine has a feature to resample the data to change the units. For example to turn "per second" metrics to "per minute" or "per hour".
This is done by passing `&gtime=SECONDS` to the `/api/v1/data` method.
This feature is not (yet) used in standard dashboards of netdata. it was created as part of the `d3pie` chart (which is also not used yet on standard dashboards), so that, for example the section head of the web log charts could show pie charts with per minute analysis of the data. It is currently available to be used in custom dashboards.
When we refactored the query engine, there was a bug: the time reported was incorrectly stating the ending time of the grouping, not the starting one. This made `d3pie` believe the data returned by netdata had a duration of 1 second, instead …
> bugfix: query engine resampling duration

- collectors/python.d.plugin/fail2ban/fail2ban.chart.py
Fixes: #4769
python `fail2ban` module
@winstonyin please check the fix
> fail2ban fix: add 'Restore Ban' action

- docs/a-github-star-is-important.md
Fixes a small typo in the title of one of the documentation pages.
Documentation
> Fix typo in "Github Star" documentation

- health/notifications/README.md
> Added a few more debugging instructions for notifications

- README.md
> Update README.md for release 1.11.1

- CONTRIBUTING.md
- docs/generator/buildyaml.sh
Fixes #4146 
I'd like to get final feedback here, so we can close the main CONTRIBUTING.md at the root level. I am thinking of later adding links to other, more specific files (e.g. for notifications) as they are created.
> Contributing.md updates

- .travis.yml
- .travis/labeler.sh
Add option to label feature requests.
Add `needs triage` label to bug reports and feature requests as those need to have `area/*` assigned
Run labeler.sh more frequently (every time travis is running on master)
Reduce number of issues which need to be checked
CI
> automatic labeling of new features

- docs/netdata-security.md
Removed false line that Netdata collects user IPs, capitalized headers, changed "netdata" to "Netdata"
> netdata-security doc corrections

- .travis.yml
- .travis/labeler.sh
- installer/netdata-updater.sh
Bring back #4790 
Start building docker containers before anything else in nightly stage as container building is slowest. For some reason nightlies aren't started after adding `deploy` section, this might fix this problem.
Fixes #4528
packaging
> auto-label PRs and minor cleanup

- docs/generator/buildyaml.sh
- docs/javascripts/cookie-consent.js
Show pop up that the site uses cookies. We don't collect any personal info, so no opt-in/opt-out required (GA will be configured with IP Anonymization)
Related to #4798
> Add cookie consent javascript to docs

- collectors/proc.plugin/README.md
Add a bit more explanation on the prerequisites for SYNPROXY, based on @ktsaou instructions in #4782
> Improve SYNPROXY documentation

- docs/generator/buildhtml.sh
Remove the Google analytics link that appears in the main README.md just from the docs (we are still keeping in the repo)
Exclude two more files that don't belong in the docs, to reduce the mkdocs INFO messages.
> Minor updates in htmldoc
