web/api/queries/README.md

Fixes #1628 by moving the information of PR #208 to the docs.

Add info from PR 208

---

web/api/netdata-swagger.json
web/api/netdata-swagger.yaml

add api/v1/info endpoint to swagger

---

collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py

[BUG] Fixes #4892
python module `nvidia_smi`

nvidia_smi: handle `N/A` values

---

collectors/freeipmi.plugin/freeipmi_plugin.c

Added more debugging info to freeimpi.plugin to help us trace #3977
collectors/freeipmi

added more debug outpput to freeipmi

---

health/health_config.c
libnetdata/libnetdata.c

Added debug statements to trace #4809

added debug statements when loading health config files

---

libnetdata/libnetdata.c

Added a few more debug statements for #4809

more health debugging to trace config files

---

libnetdata/libnetdata.c

treat DT_UNKNOWN files as regular files

---

docs/Charts.md
docs/generator/buildyaml.sh
health/README.md

Fixes #3468 
Added a page to explain Charts, Dimensions, Alarms, Contexts.
Modified instructions to create alarms to make it a bit clearer on the variables that can be used.
Documentation, Health

Added info on health configuration and page for Charts

---

collectors/python.d.plugin/postgres/postgres.chart.py

Fix: #4090
postgres python module

postgres module: locks count fix

---

.travis.yml
installer/netdata-updater.sh

- Stop using `UID` variable name since it is protected on some systems
- Execute `git pull` at the end of synchronizing git repository in updater.
- add `--allow-unauthenticated` to apt execution in travis pipeline to fix problems with some repositories
Fixes #4808
packaging
ci

do not use protected variable name in updater script

---

.travis.yml

Do not update apt repositories in operating systems used by CI. This fixes a problem which is now present on master branch.
Current problem on master can be seen in https://travis-ci.com/netdata/netdata/jobs/162414929#L475
ci

Do not update repositories in CI operating system 

---

web/api/web_api_v1.c

Fixed compilation warnings introduced by the new API `info` method

fix info api method compilation warnings

---

collectors/python.d.plugin/README.md

Add link to the example plugin.
Move PR checklist to the end (better flow)
Docs

Update python.d readme

---

docs/generator/buildyaml.sh
packaging/docker/README.md

Minor improvements to docker installation readme
Bug fix to stop presenting empty links in bash modules
Related to #4899

Improve docker installation readme, docs navbar fix

---

.travis/generate_changelog.sh
.travis/labeler.sh

- Use POST instead of PATCH method when creating labels for PRs. This should prevent automation from accidentally deleting labels.
- Automatically add "no changelog" label to issues which aren't going to be included in changelog.
- When creating changelog, do not look at issues with "no changelog" label
CI
github

better labeling

---

installer/netdata-updater.sh

Redirect stderr to fd3 for better log management in autoupdater script.
Resolves #4808
packaging
Merging this will result in a new [netdata release candidate] version.

send all git log msg to fd3

---

web/gui/index.html

PR #4913 referred to the logo using an absolute URL. This broke the logo when netdata is installed in a sub-directory of another web server.
cc: @gmosx

use relative path for logo

---

.travis/labeler.sh

Fix urls and http methods to use ones described in GitHub API docs: https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue
This should prevent from accidental label deletion by @netdatabot 
ci

use proper request types and urls to update labels

---

.travis/labeler.sh

Extract github API calls which adds labels to separate function to simplify codebase.
ci

cleaner labeler code

---

collectors/proc.plugin/proc_stat.c

Comment out the error line that is flooding the log until a proper fix is provided
proc collector (area/collectors)
Read #4945

Temporary workaround for #4945

---

collectors/node.d.plugin/sma_webbox/README.md

Fixes navbar link in generated documentation.

Add header to SMA webbox readme

---

collectors/python.d.plugin/dovecot/README.md
collectors/python.d.plugin/dovecot/dovecot.conf

Related to https://github.com/netdata/netdata/issues/4392
* config update (add new job)
* readme update
added info about v.2.3 compatibility
`/netdata/collectors/python.d.plugin/dovecot/`

dovecot readme update

---

.travis/labeler.sh

Although GitHub API documentation states to use POST to only add labels I observed that using that method also removes some labels when used multiple times after each other (like labeler does). This PR changes how labeler behaves and instead of only trying to add new labels it first fetches old set and merges it with new one. After that it uses PUT to update all label set in GitHub issue.
This was already tested in https://github.com/netdata/netdata/pull/4928.
ci/labeler
PUT is used instead of POST due to this doc entry: https://developer.github.com/v3/issues/labels/#replace-all-labels-for-an-issue

allow label modification

---

.travis.yml

According to [travis docs](https://docs.travis-ci.com/user/deployment/gcs/) only secret_access_key needs to be encrypted.
ci

GCS access key shouldn't be encrypted

---

collectors/python.d.plugin/postgres/postgres.chart.py

Fixes: #4910
Fixes: #4904
python.d module `postgres`
add support for use specific query depending on server version
@anayrat 
@arenddeboer 
if you have free time please test, the issue should be fixed
@anayrat please look at all queries, I could break something :sweat_smile:

postgres fix: detect servers version and use the right query

---

collectors/python.d.plugin/web_log/README.md

Typo: `stab_status` -> `stub_status`
Docs / readme.
None.

Typo: `stab_status` -> `stub_status`

---

health/notifications/alarm-notify.sh.in

Kavenegar returns 200

---

web/gui/index.html
web/gui/main.css

Show a warning if JavaScript is disabled #2422

---

.travis.yml
.travis/README.md

SSIA
Fixes travis nightly jobs
CI
Also updates readme describing travis pipeline

fix location of encrypted file

---

installer/UNINSTALL.md
installer/netdata-uninstaller.sh
tests/lifecycle.sh

- Change behavior of `--force` option in uninstaller
- Add option to run uninstaller in non-interactive way
- add uninstaller to lifecycle test
Fixes #4791
packaging
installer
tests

Non-interactive uninstaller

---

build/subst.inc
collectors/charts.d.plugin/Makefile.am
collectors/node.d.plugin/Makefile.am
collectors/python.d.plugin/Makefile.am
collectors/statsd.plugin/Makefile.am
health/Makefile.am
system/netdata-freebsd.in

Make build system more modular by removing cross-module dependencies.
build system

remove cross-directory dependency in build system

---

.github/CODEOWNERS
.github/stale.yml

SSIA
github
Also add ownership of `.github/` directory

change number of days needed by issue to go stale

---

health/notifications/alerta/README.md

Fixed typo

---

collectors/node.d.plugin/snmp/README.md

Also moved the second example a bit earlier.
Related to #5028 
Fixes #4525 
docs

Add warning for offset in Counter64 metrics

---

docs/netdata-security.md

Made the proxy instructions more generic and added links to the other "running behind" docs.
documentation

Add other web servers to proxy instructions

---

collectors/proc.plugin/sys_class_power_supply.c

Fix issues found by Coverity Scan
`proc` plugin

Fix coverity issues

---

docs/configuration-guide.md

Related to #5068 
Add quick guide on how to add a new alarm.

Add how to add new alarm

---

collectors/cgroups.plugin/README.md

Add systemd pattern list parameter to the documentation

---

collectors/charts.d.plugin/mysql/mysql.chart.sh
collectors/charts.d.plugin/tomcat/tomcat.chart.sh

Resolution of #4711 for bash modules.
charts.d modules

fix IEC units in bash modules

---

web/gui/dashboard_info.js

Changes the message for Total Swap I/O to something that reads a little better to me, also adds a missing parentheses.
Default dashboard

Dashboard grammar change

---

.gitignore
netdata-installer.sh
tests/lifecycle.sh

Simplify installation of an updater script.
Fixes #4924
packaging
installer
- invert logic in some conditionals to have a cleaner code (short blocks first)
- save updater script in cron directory while modifying it with `sed` instead of copying file and linking to it

copy updater script instead of linking it

---

streaming/README.md

Related to #5098, corrects statement on how much memory netdata uses in memory=none.
Docs

Correct memory usage statement in memory=none

---

netdata.spec.in

Generate a configure script for RPM build (#4570)

---

.github/CODEOWNERS

change ownership of .gitignore

---

packaging/docker/Dockerfile
packaging/docker/README.md
packaging/docker/run.sh

Scramble packages in docker images with polymorphic linux

---

collectors/python.d.plugin/rabbitmq/rabbitmq.chart.py

Fixes: #5118
https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/rabbitmq
@vpapas please test it

rabbitmq: api/nodes requests fix

---

netdata-installer.sh

Option to disable telemetry during installation. Needed for #5113
packaging

add option to opt-out from telemetry program

---

.travis.yml
packaging/docker/build.sh
tests/lifecycle.sh

- Run lifecycle tests in ubuntu 18.04 (instead of alpine) as this is most probably the mostly widespread platform of our users.
- Use container building to test if installer works on alpine and if containers build properly
ci
This is mostly spawned by PRs like #5137 where we couldn't verify changes to Dockerfile before merging it. Now CI will test such things automatically.

test building docker container on every PR

---

collectors/plugins.d/README.md

Fix typo in plugins.d/README.md

---

collectors/cgroups.plugin/cgroup-name.sh.in

Unfortunately codacy doesn't check for code quality in this file due to wrong file extension. So I did it manually. Additionally I simplified code base a little.
cgroup collector
To allow easier code review changes are commited in two parts:
- commit with manual edits (first commit)
- commit with automatic code formatting done by `shfmt` (second commit)
Part of larger effort to cleanup bash scripts with file extension ending in `.sh.in`.
More in following PRs:
#5162
#5163
#5164
#5165

Lint cgroup name.sh.in

---

collectors/tc.plugin/tc-qos-helper.sh.in

fix for fireqos classname not showing

---

collectors/python.d.plugin/python.d.conf

Fixes: #5191
Added:
* adaptec_raid
* dockerd
* httpcheck
* megacli
* portcheck
* traefik

add missing modules to python.d.conf

---

packaging/installer/kickstart.sh

When installing using kickstart.sh use tarballs from GCS instead of git repo. This way if we break "master", people still will be able to easily install netdata.
packaging
Splited into a couple commits to simplify review at least a little.

Use tarballs from GCS in kickstart.sh

---

tests/health_mgmtapi/health-cmdapi-test.sh.in
web/api/health/README.md
web/server/web_client.c

#4969 was incorrectly updating the headers when the Authorization header was being sent. 
Fixes #5180

Bug fix for netdata behind authenticated proxies

---

collectors/python.d.plugin/dockerd/README.md
collectors/python.d.plugin/dockerd/dockerd.chart.py

Fixes: #5200
`collectors/python.d.plugin/dockerd`
Minimum required `docker` package version is `3.2.0`

python dockerd module: check version

---

packaging/installer/README.md

Fix checksum validation
installer docs

fix md5sum

---

packaging/installer/README.md

Update the md5sum string, for the verification of kickstart.sh.

Update kickstart.sh md5sum in docs

---

collectors/plugins.d/README.md

Just a small improvement noticed while reading the docs. Please just close if this was intended
plugins.d documentation

plugins.d doc: Remove empty similar headline

---

.travis/nightlies.sh

go through whole nightly before quiting
ci

More robust nightly pipeline

---

docs/netdata-for-IoT.md

Instruct users to use edit-config. Related to #5213 
Docs

Instruct users to use edit-config

---

docs/Performance.md

Added mention of python.d.
Also added a bit more info on memory usage, due to #5098 and a link to the proc plugin documentation. 
docs

Update info on plugins in performance doc

---

health/notifications/alarm-notify.sh.in

Fixes #5261
Had -o instead of -a in check of notifications

Bug fix for 5261

---

collectors/python.d.plugin/ceph/ceph.chart.py

Fixes: #3563
[/collectors/python.d.plugin/ceph](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/ceph)
Fix `osd df` invalid json response. [Detailes ](https://github.com/netdata/netdata/issues/3563#issuecomment-398631975).
@lets00 @cjd9023 @briancline

ceph module bugfix: fix invalid json response

---

packaging/maintainers/README.md

Fix capitalization and add SUSE link.  Still working on getting build service to auto-track releases (one version behind right now).
Also add missing pipe on Slackware row :)

SUSE addition

---

collectors/tc.plugin/README.md

Add configuration method provided by @laneshields at #4563 
Wording improvements.
Move additional example chart further up
Docs

Improvements to QoS (tc) documentation

---

packaging/installer/README.md
packaging/installer/kickstart.sh

SSIA
packaging/kickstart
After merging script needs to be uploaded to my-netdata.io

kickstart.sh: remove updater symlink

---

README.md

updated landscape url to present card-mode

updated cncf landscape url

---

netdata.spec.in

Minor improvements to rpm spec file

---

packaging/installer/UNINSTALL.md

Clarify that uninstaller.sh needs to be downloaded from github.
Also fix the header for the HTML docs. Related to #5290.
docs

Clarify that uninstaller.sh needs to be downloaded

---

.gitignore
Makefile.am
collectors/Makefile.am
collectors/README.md
collectors/cups.plugin/Makefile.am
collectors/cups.plugin/README.md
collectors/cups.plugin/cups_plugin.c
collectors/plugins.d/README.md
configure.ac
docs/Add-more-charts-to-netdata.md
docs/generator/buildyaml.sh
libnetdata/dictionary/dictionary.c
libnetdata/dictionary/dictionary.h

Adds a C plugin which collects metrics of the default cups daemon. See the new README.md for a list of charts provided.
Fixes #857
Replaces #1678

CUPS plugin

---

collectors/cups.plugin/cups_plugin.c

fix compilation of cups.plugin; fixes #5324

---

Makefile.am
netdata-installer.sh
packaging/go.d.checksums

Install go.d.plugin by default
Fixes #5006
packaging

install go.d.plugin

---

collectors/python.d.plugin/python_modules/bases/FrameworkServices/MySQLService.py

The `mysql` plugin is not working anymore using the latest version 1.4.x of MySQLdb library. The reason is the call to a deprecated API that was recently removed (see: https://github.com/PyMySQL/PyMySQL/pull/763). 
`mysql` python.d plugin
There using `with self.__connection as cursor:` does not work anymore. Commiting to the database is now solely handled by the `connection` object. When all queries were executed the cursor can simply be closed.

Remove deprecated API call

---

web/gui/dashboard_info.js
web/gui/main.js

Comment with global NETDATA for linter

---

collectors/python.d.plugin/ipfs/ipfs.chart.py
collectors/python.d.plugin/portcheck/portcheck.chart.py
collectors/python.d.plugin/postgres/postgres.chart.py
collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService.py

Fix some python errors reported by codacy
- [`/collectors/python.d.plugin/ipfs`](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/ipfs)
- [`/collectors/python.d.plugin/postgres`](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/ipfs)
- [`/collectors/python.d.plugin/portcheck`](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/portcheck)
- [`/collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService.py`](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService.py)

fix some python codacy errors

---

collectors/python.d.plugin/portcheck/portcheck.chart.py

codacy error fix
[collectors/python.d.plugin/portcheck](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/portcheck)

portcheck: remove unused var

---

.codacy.yml
web/gui/dashboard.js
web/gui/src/dashboard.js/charting/google-charts.js
web/gui/src/dashboard.js/main.js
web/gui/src/dashboard.js/registry.js

Ignore main.js which will be deprecated and fix some warnings in dashboard

Codacy js fixes

---

collectors/cgroups.plugin/cgroup-network.c

Fix cgroups Codacy issue

---

packaging/installer/UNINSTALL.md

Provide more precise uninstall instructions

---

web/gui/main.js

Fixes #5352 
Do replacement **after** atob!

Fix replacement of whitespace for versions retrieved from github

---

collectors/python.d.plugin/example/README.md

Add link to writing a new module in example readme

---

health/notifications/alarm-notify.sh.in

Unfortunately codacy doesn't check for code quality in this file due to wrong file extension. So I did it manually. Additionally I simplified code base a little.
This is blocked by #5132
alarm notifications
To allow easier code review changes are commited in two parts:
- commit with manual edits (first commit)
- commit with automatic code formatting done by `shfmt` (second commit)
Part of larger effort to cleanup bash scripts with file extension ending in `.sh.in`.
More in following PRs:
#5162
#5163
#5164
#5165

Lint alarm notify

---

packaging/installer/UPDATE.md

Fixed invalid [[Installer]] link

Correct Installation link in updating doc

---

collectors/python.d.plugin/sensors/sensors.chart.py

Fixes: #5402
[/collectors/python.d.plugin/sensors](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/sensors)
- fix get_data identation mistake
- fix energy and power charts divisor
thanks to @zivanfi

python module sensors fix

---

.travis/create_artifacts.sh

Upload latest available netdata tarball version to GCS in a simple text file. This provides alternative url to check for latest available netdata version.
ci
Relates to #5405

copy version file to GCS upload directory

---

packaging/installer/kickstart-static64.sh

Refactor `kickstart-static64.sh` script to be similar to `kickstart.sh`.
Fixes #5390
packaging/kickstart-static

Refactored static kickstart script

---

collectors/cgroups.plugin/cgroup-network-helper.sh
collectors/cgroups.plugin/cgroup-network.c

fixes #5383
This PR allows `cgroup-network` to also use `ip link` output to detect container network interfaces. `cgroup-network` now uses `netnsid` to assign network interfaces to containers.
collectors/cgroups

use netnsid for detecting cgroup networks; 

---

collectors/cgroups.plugin/cgroup-network-helper.sh

Removed duplicate pipes of #5413

remove redudant pipes for cgroup-network netnsid

---

packaging/installer/UPDATE.md

Related to #5405 
Fix to kickstart command and a bit more clarity on binary packages

Uninstall instruction improvements

---

.travis/generate_changelog.sh
.travis/nightlies.sh
.travis/releaser.sh

Change email address to one not associated with me. This email doesn't need to be real and present.
ci

change email address for automated commits

---

README.md

Fixes: #5436
News section includes 1.12
docs

Update README.md - add news for 1.12

---

web/server/web_client.c

Remove extra 'v' from Server response header

---

collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh

Fixes #5428 
apcupsd plugin
Status ONBATT should be equivalent to status ONLINE

apcupsd - Treat ONBATT the same as ONLINE

---

collectors/cgroups.plugin/sys_fs_cgroup.c
collectors/proc.plugin/sys_fs_btrfs.c

Fixed issues
`cgroup.plugin`
`proc.plugin`

Fix Coverity defects

---

collectors/cgroups.plugin/sys_fs_cgroup.c

Removed unconditional obsoleting of variables that might not exist (limits)
cgroups

Fix SEGV by removing free of vars of charts that do not exist

---

packaging/installer/README.md

Update md5sums on README.md

---

web/server/static/static-threaded.c

Fix timer crash during exit

---

netdata-installer.sh
packaging/installer/functions.sh
packaging/installer/kickstart-static64.sh
packaging/installer/kickstart.sh
packaging/installer/netdata-updater.sh
tests/lifecycle.bats

- Revert invalid changes from #5457 
- Provide `fatal` function in `functions.sh` library
- add rudimentary tests to check if files are installed
Fixes #5459 
packaging/installer
tests

revert #5457 and test if files exist after installation

---

health/notifications/alarm-notify.sh.in

This fixes #5470 so that notifications work with rocketchat.
health alarm-notify.sh

Added rocketchat to method-list

---

collectors/tc.plugin/README.md

Fix QoS docs code fragment for HTML

---

netdata-installer.sh
packaging/installer/kickstart-static64.sh
packaging/installer/kickstart.sh
packaging/installer/netdata-updater.sh

Fixes: #5484
installer/updater

 Make curl silent and show errors only if it fails

---

daemon/main.c

Fixes #5366
collectors/tc.plugin
Fix SIGSEGV crash during shutdown of tc plugin.

Fix SIGSEGV crash during shutdown of tc plugin.

---

.travis.yml
tests/installer/checksums.sh

Prevent issues like #5492 in the future.
kickstart installer

prevent merging changes to kickstart.sh when checksum in docs is wrong

---

netdata-installer.sh

To fully test kickstart/updater installations from stable channel we need to have installer script modified to include stable channel switch.
This change doesn't affect any current installations.
This unblocks #5487
packaging/installer

introduce "stable channel" placeholder

---

collectors/python.d.plugin/python.d.plugin.in

Fixes: #5491
[`collectors/python.d.plugin`](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python.d.plugin.in)
Add a simple print func, that prints '\n' every second to stdout. This is needed to exit on SIGPIPE.

python.d.plugin add heartbeat

---

collectors/python.d.plugin/Makefile.am
collectors/python.d.plugin/oracledb/Makefile.inc
collectors/python.d.plugin/oracledb/README.md
collectors/python.d.plugin/oracledb/oracledb.chart.py
collectors/python.d.plugin/oracledb/oracledb.conf
collectors/python.d.plugin/python.d.conf

Fixes: #1996
python.d.plugin oracledb module
- [system metrics]:
```sql
SELECT
metric_name,
value
FROM
gv$sysmetric
ORDER BY
begin_time
```
<details><summary>collected metrics</summary>
<p>
|   name| 
|---|
| average_active_sessions |
| session_count |
| session_limit_percent |
| logons_per_sec |
| physical_reads_per_sec |
| physical_writes_per_sec |
| disk_sort_per_sec |
| long_table_scans_per_sec |
| database_wait_time_ratio |
| shared_pool_free_percent |
| memory_sorts_ratio |
| sql_service_response_time |
| user_rollbacks_per_sec |
| enqueue_timeouts_per_sec |
| buffer_cache_hit_ratio |
| cursor_cache_hit_ratio |
| library_cache_hit_ratio |
| row_cache_hit_ratio |
| global_cache_blocks_corrupted |
| global_cache_blocks_lost |
</p>
</details>
</br>
- [tablespace]
```sql
SELECT …
```

oracledb py module

---

web/gui/main.js

Fixes #5482 
The streamed servers don't depend on the new cloud registry so we can always show the entries in the my-netdata menu.

Show streamed servers even for users that are not signed in! #5482

---

README.md

Add entries to news section. Wiki already updated

Add news for 1.12.1 and 1.12.2 to main readme

---

web/gui/main.js

Will allow for better UX and alternative authorization methods.

Pass agent id to authorization pages

---

collectors/python.d.plugin/spigotmc/spigotmc.chart.py

Fix [UnicodeDecodeError](https://github.com/netdata/netdata/pull/5507#issuecomment-471344661)
[`collectors/python.d.plugin/spigotmc`](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/spigotmc)

spigotmc fix UnicodeDecodeError

---

database/rrdset.c

Do not delete dimensions which are not marked as obsolete.
Fixes #5553
netdata daemon

Fix nonobsolete dimension deletion

---

packaging/installer/README.md

Fixes #3727 
Fixes #5526 
Docs, Packaging
See https://github.com/netdata/helmchart

Add link to k8s helm chart in installation

---

.github/CODEOWNERS
.travis.yml

Removing myself.
ci and github management
Adios.
Merge whenever you feel suitable.

remove paulfantom code ownership and TODO notices

---

collectors/python.d.plugin/beanstalk/beanstalk.chart.py

fix import
[/collectors/python.d.plugin/beanstalk](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/beanstalk)

Beanstalk fix

---

README.md

v1.13 news added to main README

Add v1.13 news to main README

---

web/gui/dashboard.js
web/gui/index.html
web/gui/src/dashboard.js/registry.js

Fixes #5577 
Load gtm.js only if anonymous statistics are enabled.

Load gtm only if anonymous_statistics are enabled

---

web/gui/index.html
web/gui/main.css
web/gui/main.js

Make sign-in functionality more visible

---

Makefile.am
netdata-installer.sh

I am uninstalling myself by bringing back uninstaller script installation :smile: 
Related to #5290
installer

bring uninstaller back

---

packaging/installer/UNINSTALL.md

Complementary PR for #5675, update doc
Parent issue #5290 
netdata/packaging/uninstaller
None

netdata/packaging/uninstaller: Update uninstall document

---

packaging/docker/publish.sh

Another gotcha on the publishing process, we are generating the manifest list too early.
By design, unfortunately we re-define the version automatically inside the script, so manifest list variable should be defined after that step.
We also added some extra logging for the future
netdata/packaging/docker/publish
This is a safe change, given the urgency and the hour i will take the responsibility to merge the PR without waiting for approval.

netdata/packaging/docker/publish: Fix docker publishing

---

packaging/installer/netdata-updater.sh

Remove temp log file if no update needed

---

collectors/python.d.plugin/postgres/postgres.chart.py
collectors/python.d.plugin/postgres/postgres.conf

Fixes: #5629
https://www.postgresql.org/docs/9.1/libpq-ssl.html
[/collectors/python.d.plugin/postgres](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/postgres)

postgres add ssl connection support

---

tests/installer/checksums.sh
tests/installer/slack.sh

Minor fixes spotted during code review (leftover from #5689)
netdata/packaging/ci - tests
N/A

netdata/packaging/ci: nits

---

collectors/apps.plugin/apps_groups.conf

Add kubernetes related processes to [apps_groups.conf](https://github.com/netdata/netdata/blob/master/collectors/apps.plugin/apps_groups.conf)
[/collectors/apps.plugin](https://github.com/netdata/netdata/tree/master/collectors/apps.plugin)

add some kubernetes to apps_groups.conf

---

collectors/fping.plugin/fping.plugin.in
packaging/makeself/jobs/50-fping-4.2.install.sh

Fping was updated to version 4.2
Closes #4227
fping plugin

Update fping version

---

collectors/Makefile.am

Fix dist build

---

health/Makefile.am
health/health.d/kubelet.conf

Add some alarms for kubelet module from #5720
[/health/health.d](https://github.com/netdata/netdata/tree/master/health/health.d)

add some kubelet alarms

---

.travis/generate_changelog.sh
.travis/nightlies.sh
packaging/docker/build.sh
packaging/docker/publish.sh

As it was initially reported on #5580, nightlies was facing two major issues: 1) We were not failing properly on errors, 2) Logging wasn't sufficient or easy to read in many cases, so that we can identify problems.
We are already in the process of refactoring the whole build pipeline. We took advantage of the reported issue on #5580 and we did another major step towards the direction of providing more fine grained processing in the pipeline. Below is a summary of the changes included in this PR. More will follow as part of separate issues, but for now this PR is enough to mitigate the reported issue (plus is better to make medium to small sized PRs so that they can be easily reviewed and fine tuned)
List of changes:
First commit
1) Add the necessary comments for documentation
2) Reinstate …

netdata/packaging/ci: Make Travis CI more strict on nightlies run

---

.github/CODEOWNERS

fix owners - remove mistyped username
netdata/git

access: fix codeowners

---

.travis/create_artifacts.sh
.travis/generate_changelog.sh
.travis/nightlies.sh

Calculate the version string earlier, so that we can emit it in the logs for troubleshooting.
netdata/packaging/ci
None

netdata/packaging/ci: small improvements in logging

---

backends/WALKTHROUGH.md
backends/prometheus/README.md
backends/prometheus/backend_prometheus.c

"homogeneus" to "homogeneous".

Fix some misspells in docs and code

---

collectors/python.d.plugin/ceph/README.md

Correct typo in ceph README

---

packaging/installer/README.md
packaging/installer/kickstart-static64.sh
packaging/installer/kickstart.sh

Fixes #5768 
netdata/packaging/kickstart

netdata/packaging/kickstart: fix kickstart

---

.github/CODEOWNERS

Add cakrit as global owner
netdata
None

netdata: Add another global owner

---

.travis.yml

Introduced from PR #5778 -- found after all why Travis didn't respond.
Wasn't really intuitive the way it failed, linter showed the syntax which means i need to make some adjustments on my process to avoid ending up in the same loop hole again.
netdata/packaging/ci
None

netdata/packaging/ci: fix travis syntax

---

packaging/installer/netdata-updater.sh

Two issues attended on this script:
1) imported safe_sha256sum method to the updater
2) fixed wrong usage of "failed" function, while "fatal" is the one defined in the script
Fixes #5781 issue report from our users
None

netdata/packaging/updater: fix updater

---

libnetdata/socket/socket.c

Fix unix socket access on FreeBSD

---

collectors/proc.plugin/README.md
collectors/proc.plugin/proc_diskstats.c

Closes #4957
proc plugin, diskstats module

Add preferred disk id pattern

---

.travis/README.md
packaging/docker/README.md
packaging/docker/build-test.sh
packaging/docker/publish.sh

Travis environment doesn't update the password, need to create new variable.
Note: Once confirmed this is the case i will just use different way for this
None

netdata/packaging/docker: Change password

---

packaging/installer/README.md

Following up #5807 we are updating our README to inform our users about the existence of stable channel option
Fixes #5807

netdata/packaging/installer: Update README

---

collectors/python.d.plugin/couchdb/couchdb.chart.py

Fixes: #5830
fix unhandled exception
[/collectors/python.d.plugin/couchdb](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/couchdb)

couchdb: _fetch_data TypeError fix

---

collectors/python.d.plugin/elasticsearch/elasticsearch.conf

fixes: #5179
add `scheme` option to configuration file
[/collectors/python.d.plugin/elasticsearch](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/elasticsearch)

elasticsearch: update config file

---

collectors/python.d.plugin/smartd_log/smartd_log.chart.py

Fixes: #5919
3, 194 attributes decode fix
[/collectors/python.d.plugin/smartd_log](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/smartd_log)

smartd_log: attrs 3, 194 fix

---

.travis.yml
packaging/docker/check_login.sh

Add some extra info on various stages, also introduce a check_login.sh step in prior to docker publishing, for early fail if credentials are messed up. Waiting the full build is overhead
netdata/packaging/ci
None

netdata/packaging/ci: minor improvements

---

collectors/python.d.plugin/web_log/README.md

The actual screenshot shows methods, not versions, so change the text to reflect that.
The screenshot used:
web_log docs

Change HTTP version to HTTP method

---

health/notifications/custom/README.md
health/notifications/health_alarm_notify.conf

Extend the example for the custom_sender that was already in `health_alarm_notify.conf`
Add the example to the documentation.
Related to #5984

Provide sample implementation for custom notifications

---

daemon/main.c
database/rrd.h
database/rrdhost.c
streaming/rrdpush.c
web/api/web_api_v1.c

Fixes incorrect system information reported by `host/<slave hostname>/api/v1/info` API call.
streaming, web

Add system info streaming

---

database/rrdhost.c
streaming/rrdpush.c
web/api/web_api_v1.c

When a slave was running an old version of netdata there was an issue with a segmentation fault on the latest master. 
streaming

Fix segmentation fault

---

health/notifications/alarm-notify.sh.in

Fixes #6021 
SEND_PROWL was missing from the list of notifications checked for enablement

Add prowl to list of methods checked for enablement of notifications

---

docs/generator/buildyaml.sh

The README for the new dbengine exists but it's not in the left menu.
docs

Add database engine doc to the menu

---

tests/k6/data.js

API load testing script using [loadimpact/k6](https://github.com/loadimpact/k6). 
Will be enhanced and used to stress test the new DB.
Needed for #5282 
tests
Install k6 and run it. The contents of the file are self-explanatory, it contains many things we can tweak.
Sample output:
```bash
[christopher@chris-msi k6]$ k6 run data.js 
/\      |‾‾|  /‾‾/  /‾/   
/\  /  \     |  |_/  /  / /    
/  \/    \    |      |  /  ‾‾\  
/          \   |  |‾\  \ | (_) | 
/ __________ \  |__|  \__\ \___/ .io
execution: local
output: -
script: data.js
duration: -,  iterations: -
vus: 1, max: 150
done [==========================================================] 1m40s / 1m40s
█ Requests
✓ status is 200
✓ check_failure_rate.........: 0.00%   ✓ 0     ✗ 6015 
checks.....................: 100.00% ✓ 6015  ✗ 0 …
```

Initial script for API load testing

---

backends/backends.c

Fix timestamps being reversed for backends

---

docs/configuration-guide.md

Add succinct instructions on how to persist configuration to the main configuration guid
docs
Many users still wonder why their configurations get lost after updating netdata. Provide a short section with the answer, so that we can reference it in these issues.

Reiterate the proper way to persist configurations in the Configuration guid

---

README.md

Add 1.15 to news section of main README

---

web/api/netdata-swagger.json
web/api/netdata-swagger.yaml

Fixes #5990 (bug due to missing documentation)
daemon, API
alarm_variables is now documented with this PR, adding the variables to other calls will be done via #6054

Update swagger with definition of api/v1/alarm_variables

---

database/engine/pagecache.h
database/engine/rrdengineapi.c

Fix race condition in DB engine API

Fix race condition in DB engine API

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.travis/labeler.sh

Instead of relying on travis, use github to assign labels to new issues.
ci, github
none

use github templating mechanisms to classify issues when they are created

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

This is a fix on the previously applied change that adds labels on the templates
netdata/issues
Fixes #5776

netdata: Fix labels usage, quotes are not needed

---

web/gui/dashboard_info.js

Fixes #6086 
web
dashboard_info.js had old links to web_log.conf

Corrected links to web_log.conf

---

daemon/config/README.md

Fix minor typos

---

health/Makefile.am
health/health.d/wmi.conf

add some alarms for [wmi collector](https://github.com/netdata/go.d.plugin/tree/master/modules/wmi)
- cpu usage
- memory usage(ram, swap)
- disk space usage
- network errors/discards
[health](https://github.com/netdata/netdata/tree/master/health)
___
i tested the PR installing the branch

wmi alarms

---

README.md
docs/anonymous-statistics.md
netdata-installer.sh
packaging/installer/README.md

Fixes #5863 
docs, installer
Add mention of telemetry to additional places as per #5863

Mention anonymous statistics in additional places in the docs

---

daemon/main.c
database/rrd.h
database/rrdhost.c
streaming/rrdpush.c

Fixes segmentation fault and missing system info introduced with #6096.
Fixes https://github.com/netdata/cloud/issues/779
daemon
streaming
database

Remove system_info copying

---

collectors/python.d.plugin/mysql/mysql.chart.py
web/gui/dashboard_info.js

Add innodb deadlock chart to mysql.
collectors

add mysql deadlocks chart

---

web/README.md

/usr/share/netdata/web/dashboard_info_custom.example.js -> /usr/share/netdata/web/dashboard_info_custom_example.js

Fix typo in README

---

database/engine/pagecache.c
database/engine/pagecache.h
database/engine/rrdengine.c
database/engine/rrdengineapi.c
database/engine/rrdenginelib.c

Fixes #6105
Add empty page detection in DB engine

Add empty page detection in DB engine

---

collectors/python.d.plugin/varnish/varnish.chart.py

Fixes: #6149
`varnishstat` v4 doesnt have `-t` option
[/collectors/python.d.plugin/varnish](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/varnish)

varnish v4 compatibility fix

---

health/notifications/custom/README.md

Related to #3641
docs
Ensure people don't get confused with which file they need to change and how to persist their configuration.

Make custom notification's instructions clearer

---

database/rrdset.c

Fixes #6186
database
Change print level from error to info

Change print level from error to info

---

collectors/python.d.plugin/smartd_log/README.md

Additions to #6203 
docs
Add more info on why the directory is needed.
cc @Steve8291

smartd documentation improvements

---

database/engine/pagecache.c
database/engine/rrdenglocking.c

Fixes  #6199
Fix page cache descriptor race condition.

Fix page cache descriptor race condition

---

CONTRIBUTING.md

Add basic code style guidelines
docs
Based on internal discussion on 4-Jun-19

Add code style guidance to CONTRIBUTING

---

database/engine/rrdengineapi.c
database/engine/rrdengineapi.h
database/rrdset.c

Fixes #6103
database
Fill chart gaps efficiently.

Fill chart gaps efficiently.

---

web/api/exporters/allmetrics.c

Fixing problems with previous allmetrics parser.

URL_parser fixing allmetrics!

---

database/engine/rrdengineapi.c
database/rrd.h
database/rrdset.c

Fixes #6104
Fixes #6239
database
Force page alignment per dimension of chart.

Force page alignment per dimension of chart.

---

web/api/health/health_cmdapi.c

To avoid buffer overflow I have the habbit to use functions that has the length as argument, but they are really not necessary here.
Health
Fixes #6238 .

PR to fix issue #6238

---

packaging/docker/README.md
packaging/docker/run.sh

1) dont do anything if there is no socket available
2) fix the socket ownership after adding the new group
3) fix comments/copyrights
Fixes #5823

netdata/packaging/docker: Fix docker socket utilization, first pass

---

.travis.yml
tests/updater_checks.bats
tests/updater_checks.sh

As an attempt to increase our coverage in testing and to guarantee cross-distribution stability,
we choose to extend our baseline tests across all currently supported distributions.
We run the stable to current transition test, to maximize scenarios coverage.
The missing distributions from the bare OS runs, are covered on the Artifacts validations stage
Fixes #6102

netdata/packaging: Add more distribution validations

---

.travis.yml
tests/installer/slack.sh

Add option for slack messages to be pushed on alternative channel, than the default. Push all info to #automation, make #ci-status error reporting only
netdata/packaging/ci
None

netdata/packaging: Adjust CI notification logic

---

packaging/installer/README.md

Fix wording on documentation - minor
netdata/packaging/documentation
None

netdata/packaging/documentation: Its Redhat, then came the others

---

collectors/nfacct.plugin/plugin_nfacct.c

Fix typo in nfacct.plugin

---

.travis.yml

Make sure beta infrastructure sends messages to a separate channel, we need to distinguish noise
netdata/ci/notifications
None

netdata/packaging: Separate beta messages from production messages

---

collectors/python.d.plugin/mysql/README.md
collectors/python.d.plugin/mysql/mysql.chart.py

Add new mysql charts based on such metrics https://mariadb.com/kb/en/library/user-statistics/
collectors

add userstats charts for mysql

---

README.md
docs/Demo-Sites.md

Searched briefly for links to the old `my-netdata.io` site to change them to `netdata.cloud`. There are perhaps more, but we only want to change links to the site itself, not links to demo sites or badge images, so a simple search & replace won't do here.
docs

Changed links from my-netdata.io to netdata.cloud

---

collectors/apps.plugin/apps_plugin.c

Add additional debug messages to see the process grouping on a target in a more compact form. It should help in debugging issues like #4698. An example of the message:
```
apps.plugin: target 'samba' has aggregated 6 processes: 470 948 950 951 952 1114
```
apps plugin

Add apps grouping debug messages

---

packaging/installer/README.md

These packages are not for basic install
netdata/packaging/documentation
References #6300

netdata/packaging/doc: Update documentation dependencies

---

.github/CODEOWNERS

We need more owners of the C code to be more responsive in PR reviews and merges.
repository configuration

Add more codeowners to the core

---

web/gui/dashboard_info.js

Links are broken because ZFS on Linux renaming the python scripts.
arcstat.py -> arcstat
arc_summary.py -> arc_summary3
Commit: https://github.com/zfsonlinux/zfs/commit/6e72a5b9b61066146deafda39ab8158c559f5f15#diff-791dc340d70e7e685d0a716b5c02b6ce

Fix broken links

---

docs/Running-behind-nginx.md
docs/netdata-security.md

This guide works fine but it isn't really beginner friendly.
So I explained why the user would perform certain actions and what some steps do.
I also tested the configuration files on actual servers with both Nginx and Netdata installed.
docs
This is a clean PR from a previously closed one.
It has the requested changes and updates

update Nginx guide with changes

---

collectors/diskspace.plugin/README.md

Make clear that Netdata needs search permission for a mount point in order to monitor it. 
Fixes #6401
diskspace plugin

Add a statement about permissions for the diskspace plugin

---

health/README.md
web/api/health/README.md

Update docs health monitoring and health management api to include missing information about time scheduling of notifications and permission on using the mamagement api.
Docs health monitoring and health management api
Is seems my code editor also removed some obsolete spaces, hence the many file changes even though I just added a couple of lines of text.

Update docs health monitoring and health management api

---

CONTRIBUTORS.md

Due to the discussion in PR #6485, we are adding the following statement to the CLA:
"We intend to keep the netdata agent forever FOSS"
All contributors will need to sign the new CLA .

Update CLA with intention to keep netdata FOSS

---

.github/CODEOWNERS

Update code owners
netdata/documentation
None

netdata/docs: Add @joelhans as co-owner on documentation

---

web/gui/index.html
web/gui/main.css
web/gui/main.js

Fixes #5812 
This PR affects top menu dropdown with hostname.
web
Solution based on different layouts for different display sizes.

Fix nodes menu sizing (responsive)

---

collectors/python.d.plugin/smartd_log/smartd_log.chart.py

Fixes: #6532
There is a bug in Disk `__eq__` func
https://github.com/netdata/netdata/blob/8e695f03c9e8425ff88222b2dfbc0f43f9962cf3/collectors/python.d.plugin/smartd_log/smartd_log.chart.py#L559-L570
`__eq__` uses `name`, but name is changed by `re.sub` **if there are several consecutive underscores in the file name**.
`smartd_log` does rescan of `smartd` directory every 60 seconds, if it finds new log files it adds them to the list of monitored disks.
`__eq__` is very important becuse it is used to check if log file already in list.
Since `__eq__` is broken `smartd_log` adds same files to the list on every rescan :sweat_smile: 
[collectors/python.d.plugin/smartd_log](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/smartd_log)
The fix:
- save `name` to `raw_name` …

smartd_log: Disk __eq__ fix

---

.travis.yml

Only white space changes, related to comments and indentation
Make .travis.yml use consistent indentation
Use two blank lines instead of three, as per yamllint suggestion
Use two spaces before EOL comments as per yamllint suggestion
.travis.yml
Please accept some cosmetic changes to .travis.yml

.travis.yml: Fix some yamllint errors

---

.travis.yml

Changed .travis.yml in order to build DEB and RPM packages in parallel instead of serially.
This should reduce the time needed for building the packages.
Travis CI
You can check the following test builds:
- DEBs: https://travis-ci.org/knatsakis/netdata/builds/566202948
- RPMs: https://travis-ci.org/knatsakis/netdata/builds/566203318

Build DEB and RPM packages in parallel

---

health/notifications/awssns/README.md

Fixed typo 'follwing' -> 'following'
README.md

Fixed typo 'follwing' -> 'following'

---

DOCUMENTATION.md
docs/generator/buildyaml.sh
docs/netdata-cloud/README.md
docs/netdata-cloud/nodes-view.md
docs/netdata-cloud/signing-in.md

This PR adds the first real documentation for features available in Netdata Cloud. There are three documents:
- `README.md`: An introduction to what Netdata Cloud is, the features is has, and links to information about signing in or using Nodes View.
- `signing-in.md`: A step-by-step guide to signing in to Netdata Cloud via the web dashboard.
- `nodes-view.md`: A walkthrough of all the visual elements of the Nodes View and what they do, along with a few tables about the services shown in the `Services` tab.
@gpapamathND and I think this is pretty solid, as we worked on them pretty closely a few weeks ago, but I'm adding `WIP` here in case we need to take more time to get these dialed in before sending them out.

Netdata Cloud documentation

---

.github/CODEOWNERS

Adding our new CTO to netdata codeowners
netdata
None

netdata: Add cosmix as codeowner, wherever cakrit is

---

docs/terms-of-use.md

Added "including without limitation U.S. export controls and economic sanctions regulations"

Update terms of use for U.S. legal reasons

---

packaging/installer/README.md

update package version requirements for LZ4 and libuv

update package version requirements for LZ4 and libuv

---

.travis.yml
tests/updater_checks.sh

Complete the list of bare OS validations, to be extra sure all cases are covered
netdata/ci
none

netdata/packaging: Bare OS validations

---

CONTRIBUTING.md
DOCUMENTATION.md
docs/contributing/contributing-documentation.md
docs/contributing/contributing.md
docs/contributing/style-guide.md
docs/generator/buildyaml.sh
docs/generator/custom/css/netdata.css

I've been asked a few times about what Netdata's standard practice on some grammatical or spelling is, and I thought it was about time we established some standards for our documentation. These will apply to both Netdata employees and anyone in the community who wants to contribute to docs.
I also wrote out instructions on the docs build process for anyone who wants to make sure things build correctly or to get a "real" preview before sending in a PR and seeing what Netlify comes up with.
This is a revived/revised version of #6548.

 Documentation style guide & build instructions

---

backends/backends.c

Fix a segmentation fault when Netdata is compiled with the Prometheus remote write support.
Fixes #6626
backends

Fix a segmentation fault in backends

---

docs/generator/buildyaml.sh

PR #6563 created an issue where an item named **None** appeared in the left-hand nav in the docs, under the **About Netdata** heading. It was because I moved the link to the `CONTRIBUTING.md` file down to a different heading. I've removed it from **About Netdata** in this PR.
docs

Fix 'None' in left nav

---

docs/Running-behind-apache.md

some help for Apache + CSP
docs/Running-behind-apache.md

Bugfix 931843 1

---

.remarkignore

CHANGELOG.md is automatically generated by [github_changelog_generator](https://github.com/github-changelog-generator/github-changelog-generator)
[Remark](https://github.com/remarkjs/remark) should ignore the file since it is regularly auto-generated.
The best way to achieve this was to create `.remarkignore` and add the file to be ignored.
doc

add CHANGELOG.md to .remarkignore

---

.travis.yml
.travis/trigger_package_generation.sh

With this PR we will finally automate the package build process for RPM and DEB, amd64
None

netdata/packaging: Add auto-generation of packages for nightly

---

.travis/create_artifacts.sh
.travis/package_management/common.py
contrib/debian/rules

Observed on #6666, we seem to have misconfigured parts of the implementation.
With this PR i correlate all configure commands to make sure no more discrepancies pop
None

netdata/packaging: [ci skip] Correlate configure command

---

health/health.c

As @mfundul detected doing a review, we had the file health/health.c with two patterns of tabulation, this PR fixes this problem.
Health

Tabulatin on health/health.c

---

database/engine/journalfile.c

Fix corrupted transaction payload handling during start-up of the database engine.
Fixes #6701

Fix corrupted transaction payload handling

---

.travis.yml
.travis/package_management/old_package_purging.sh

1) Introduce scriptlet that is executing the cleanup on a designated repository, with a designated retention period
2) Add .travis.yml configuration to execute purging logic with the right config on the nightly operations
Fixes #6689

netdata/packaging: Add purging logic for package cloud repositories

---

.travis.yml

Improve readability of commit_message predicates and package (DEB/RPM) building templates
.travis.yml
You can find test builds, here:
https://travis-ci.org/knatsakis/netdata/builds/572431794
and here:
https://travis-ci.org/knatsakis/netdata/builds/572433452

.travis.yml: Improve template and commit_message predicates readability

---

.travis.yml
coverity-install.sh

1) Add slack notification when things fail, we dont want to silently fail it
2) Change the tarball version, seems we now downloading a different version
netdata/ci
None

netdata/packaging: fix coverity problem in travis (2 issues)

---

.travis.yml

This is to enable auto-generation of packages for RPM and DEB, during stable release
netdata/ci
N/A

netdata/packaging: Trigger stable package generation upon release process

---

web/gui/console.html
web/gui/dashboard.html
web/gui/dashboard.js
web/gui/demo.html
web/gui/demo2.html
web/gui/demosites.html
web/gui/demosites2.html
web/gui/goto-host-from-alarm.html
web/gui/index.html
web/gui/src/dashboard.js/themes.js
web/gui/tv.html

update cache hashes after change introduced for #6587 
it's good to merge it, otherwise some users will have old js/css files. if that happens, for example they will have updated .js but not .css (which is very probable) - they will not see the history tip and the elements. Also, even if invisible, the elements will be rendered by browser (outside of visible boundaries) and that scenario haven't been tested enough
web

update cache hashes for js and css

---

.travis/trigger_package_generation.sh

Use the right user as author for the commits that trigger packaging process from travis
netdata/ci
None

netdata/ci: Fix author on triggering commits for packaging

---

.travis/package_management/common.py

netdata/packaging: nit - missed trailing slash

---

.travis/package_management/build_judy.sh
.travis/package_management/build_libuv.sh

This is only introducing the scriptlets, nothing affects any pipeline yet.
I have an issue with libuv script though, under the 32 bit of the docker image for CentOS 7 we fail a test.
This is part of the solution for #6849 
N/A

netdata/packaging: Bring on board two scripts that build libuv and judy from source

---

backends/prometheus/README.md

Based on #5504, this adds a clearer explanation of how to change the `source`, after the various sources are explained.
Thanks to @flippy1345 for the original PR.

Add example for prometheus archiving source parameter

---

collectors/python.d.plugin/Makefile.am
collectors/python.d.plugin/gearman/Makefile.inc
collectors/python.d.plugin/gearman/README.md
collectors/python.d.plugin/gearman/gearman.chart.py
collectors/python.d.plugin/gearman/gearman.conf
collectors/python.d.plugin/python.d.conf
health/Makefile.am
health/health.d/gearman.conf
web/gui/dashboard_info.js

This adds a Gearman chart plugin discussed in #4817.
python.d/gearman
health.d/gearman
I removed idle from the total graph because a worker could be counted more than once if it was registered to more than one job.

Gearman plugin for Netdata

---

collectors/python.d.plugin/README.md

It never got updated when the repo got restructured a while back.  This updates all the paths to match the current structure of the repository, and also updates the info about the makefile to reflect how things currently are handled.
docs

Update python.d module checklist to match the current paths and build system.

---

packaging/installer/README.md

Update docs for offline install

---

.travis.yml

netdata/ci: fix branch check

---

database/engine/rrdengine.c

Reduce CPU overhead when flushing dirty pages to disk.
Fixes #6957

Reduce overhead during write io

---

database/README.md
database/engine/README.md

This PR fixes remark lint warnings for all README files in the Database directory.
Related: #5941 
Docs

Fix Remark Lint for READMEs in Database

---

web/api/badges/README.md
web/api/badges/web_buffer_svg.c
web/api/badges/web_buffer_svg.h

#3925
Implements parameters to add fixed width to badges as requested in #3925 
web
If fixed width set the requester is responsible to actually making sure that the width is enough for data displayed.
How to use is documented in relevant docu file

#3925 implementation

---

backends/README.md
backends/WALKTHROUGH.md
backends/aws_kinesis/README.md
backends/mongodb/README.md
backends/opentsdb/README.md
backends/prometheus/README.md
backends/prometheus/remote_write/README.md

This PR fixes remark lint warnings for all README files in the backend directory. 
Related: #5941 
Docs
The entire doc was built and tested to see the HTML output of the changed files, they rendered fine.

Fix Remark Lint Warnings for Backends

---

docs/generator/custom/themes/material/partials/header.html

Installer README was translated to Portuguese from @lets00
docs
Add pt language option to the html docs.

Add Portuguese (Brazil) as a language option

---

health/notifications/alarm-notify.sh.in

Fixes #7002 
I am using netdata on Centos7.6, and When I set alarm scripts and execute it, it report this error. Not very big problem, but I think it's necessary to fix it :)

fix issue #7002

---

collectors/proc.plugin/sys_block_zram.c

Fixes #6924
zram module in proc plugin

Fix a resource leak

---

.github/CODEOWNERS

Add @knatsakis to CODEOWNERS
netdata
None

netdata: Add knatsakis as codeowner, wherever paulkatsoulakis was

---

docs/getting-started.md
docs/tutorials/dimension-templates.md
docs/tutorials/longer-metrics-storage.md
docs/tutorials/monitor-hadoop-cluster.md
docs/tutorials/offline-installations.md

I've written tutorials on HDFS/Zookeeper monitoring and the new dimension templates to support marketing around the upcoming v1.18 release. Would definitely appreciate feedback on these, especially @ilyam8 for the HDFS/Zookeeper tutorial, and @thiagoftsm for the dimension templates one.
I also tweaked a few other docs to clarify that dbengine is now the default database.
The goal is to have these fixed, approved, and merged by 10/10.
docs

Tutorials to support v1.18 features

---

README.md

Add release 1.18.0 to news
docs

Add release 1.18.0 to news

---

daemon/global_statistics.c

Fixes #7020
Add dbengine RAM usage statistics.

Add dbengine RAM usage statistics

---

collectors/python.d.plugin/python_modules/bases/FrameworkServices/SimpleService.py

ssia
fixes: #7079
That msg definitely not an error.
[`/collectors/python.d.plugin/python_modules/bases/FrameworkServices/SimpleService`](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python_modules/bases/FrameworkServices/SimpleService.py)

SimpleService: change chart suppress msg level to info

---

daemon/global_statistics.c
libnetdata/health/health.c
libnetdata/json/json.c
web/api/queries/query.c

Fixes #7089
This PR brings the necessaries fixes during the compilation time with clang,
Netdata installer.

Clang warnings

---

collectors/freebsd.plugin/freebsd_getifaddrs.c

See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237611

Add VMware VMXNET3 driver to the default interafaces list

---

CONTRIBUTORS.md
collectors/python.d.plugin/springboot/README.md

As I was searching around for broken links on the Learn site once all the core repo's `.md` files are pulled in, I noticed a few that were actually broken from the source, and not because of my linkchecking script. This PR fixes them!
docs

Fixing broken links in docs

---

contrib/debian/control
contrib/debian/control.buster
contrib/debian/control.jessie
contrib/debian/control.trusty
contrib/debian/control.xenial
contrib/debian/netdata.postinst.in
contrib/debian/netdata.postrm
contrib/debian/netdata.preinst

Fix upgrade path from v1.17.1 to v1.18.x for deb packages
contrib/debian
Fixes #7067

Fix upgrade path from v1.17.1 to v1.18.x for deb packages

---

health/notifications/health_alarm_notify.conf
health/notifications/telegram/README.md

Fix, add, and update documentation and comments for telegram alert configuration. Replace edited image.
health/notifications/telegram/README.md

telegram: fix broken links, add setup instructions

---

collectors/proc.plugin/plugin_proc.c

Disable pagetypeinfo by default

---

docs/getting-started.md

Fixes #7208. Changed the paragraph in question to make verbiage around the database engine less jargon-y and make it clearer that it uses both RAM and disk, unlike the `save` mode.
docs

Clarify database engine/RAM in getting started guide

---

packaging/installer/README.md

Spotted it while looking for that particular one-liner, it does not affect actual process but is a matter of consistency in naming
It was introduced in 545aa9745, i 'm surprised we didn't notice it earlier
netdata/docs
netdata/installer
None

netdata/docs: netdata installer documentation minor nit

---

Makefile.am

installer: add missing trailing backslash

---

docs/contributing/contributing-documentation.md
docs/contributing/style-guide.md
docs/getting-started.md
docs/netdata-cloud/README.md
docs/netdata-cloud/nodes-view.md
docs/netdata-cloud/signing-in.md
docs/tutorials/dimension-templates.md
docs/tutorials/longer-metrics-storage.md
docs/tutorials/monitor-hadoop-cluster.md
packaging/DISTRIBUTIONS.md

I've been neglecting to add GA links on new `.md` documents I've been creating in the documentation. I searched around for pages missing the link at the bottom and added them.
docs

Added GA links to new documents

---

collectors/apps.plugin/apps_groups.conf

Sync frr daemons with [frr 7.2](https://github.com/FRRouting/frr/releases/tag/frr-7.2) release.

collectors: apps.plugin: apps_groups: added new frr daemons.

---

packaging/installer/README.md

Correct versions of FreeNAS that Netdata is available on.

Correct versions of FreeNAS that Netdata is available on

---

web/gui/custom/README.md

Minor grammar change in /web/gui documentation

---

collectors/python.d.plugin/README.md

Underline in README the existence of multiple url plugins to facilitate plugin developers and offered 2 examples.
docs
Added also a comment regarding the existence of custom variables in the config. 
Thanks @ilyam8 for the info

Update python.d README 

---

collectors/plugins.d/README.md

PR #7335 introduced a few errors that I didn't have a chance to fix before it was merged, so this PR fixes those.
docs

Fixing errors in plugins.d/README.md

---

packaging/docker/README.md

As I was working on the Docker docs for another PR I found that the README throws up a lot of linter errors. This PR focuses on fixing mostly line length errors and list syntax.
docs

Fixing linter errors in packaging/docker/README

---

daemon/config/README.md
health/QUICKSTART.md
health/README.md
health/REFERENCE.md
health/tutorials/dimension-templates.md
health/tutorials/stop-notifications-alarms.md

With all the chaos around Netlify builds I failed to find a broken link in `daemon/config/README.md` that's halting all the builds now.
I also added in GA links for each of the new pages created by #7329.
docs
health/

Docs: Fixes to new health documentation structure

---

.gitignore
CMakeLists.txt
Makefile.am
cli/Makefile.am
cli/README.md
cli/cli.c
cli/cli.h
configure.ac
daemon/README.md
daemon/commands.c
daemon/commands.h
daemon/common.h
daemon/main.c
daemon/signals.c
database/engine/rrdengine.c
database/engine/rrdengine.h
database/engine/rrdengineapi.c
database/engine/rrdenginelib.h
libnetdata/libnetdata.h
packaging/installer/README.md
packaging/installer/netdata-uninstaller.sh

Fixes #7269
daemon
cli
Implement netdata command server and cli tool

Implement netdata command server and cli tool

---

.gitignore
CMakeLists.txt
Makefile.am
cli/Makefile.am
cli/README.md
cli/cli.c
cli/cli.h
configure.ac
daemon/README.md
daemon/commands.c
daemon/commands.h
daemon/common.h
daemon/main.c
daemon/signals.c
database/engine/rrdengine.c
database/engine/rrdengine.h
database/engine/rrdengineapi.c
database/engine/rrdenginelib.h
database/rrd.h
database/rrdhost.c
libnetdata/libnetdata.h
packaging/installer/README.md
packaging/installer/netdata-uninstaller.sh
web/api/web_api_v1.c

Rebase to include cli and add LABEL_SOURCE to struct

---

.gitignore
CMakeLists.txt
Makefile.am
cli/Makefile.am
cli/README.md
cli/cli.c
cli/cli.h
configure.ac
daemon/README.md
daemon/commands.c
daemon/commands.h
daemon/common.h
daemon/main.c
daemon/signals.c
database/engine/rrdengine.c
database/engine/rrdengine.h
database/engine/rrdengineapi.c
database/engine/rrdenginelib.h
database/rrd.h
database/rrdhost.c
libnetdata/libnetdata.h
packaging/installer/README.md
packaging/installer/netdata-uninstaller.sh
web/api/web_api_v1.c

Messed up my commits, this should bring everything up to speed.

Rebase to cli addition

---

daemon/main.c
database/rrd.h
database/rrdhost.c
web/api/web_api_v1.c

So we can tell where the labels came from.

Add LABEL_SOURCE enum to label struct

---

database/rrd.h
database/rrdhost.c
web/api/web_api_v1.c

Fixing the review comments on the initial commit in the branch.

[WIP] Cleaning up the initial commit

---

daemon/commands.c
daemon/commands.h
database/rrd.h
database/rrdhost.c
web/api/web_api_v1.c

Merging lists and updating on CLI command.

---

database/rrdhost.c

@thiagoftsm suggested some changes in the last PR from @amoss, they're here.

previous pr minor corrections

---

collectors/python.d.plugin/Makefile.am
collectors/python.d.plugin/hpssa/Makefile.inc
collectors/python.d.plugin/hpssa/README.md
collectors/python.d.plugin/hpssa/hpssa.chart.py
collectors/python.d.plugin/hpssa/hpssa.conf
collectors/python.d.plugin/python.d.conf

This module collects controller, logical and physical devices health metrics from HP Smart Storage Arrays.
hpssa python plugin
We run a couple HP servers with Smart Storage Arrays, this enables us to monitor the state and health of the SSAs and disks.

Add HP Smart Storage Array python plugin

---

database/rrdhost.c
libnetdata/config/appconfig.c
libnetdata/config/appconfig.h

Finish #7410 
This PR brings the last bullets that were missed o the issue 7410.
Daemon
Database

Labels fill list from netdata configuration

---

.travis.yml

Minor docker related cleanups
.travis.yml
[Test build](https://travis-ci.org/knatsakis/netdata/builds/605992367)

Minor docker related cleanups

---

README.md

I realized recently that our main README is out of date in regards to the database engine, which prompted these changes. Aside from changing references from `round-robin` to `database engine`, 
I also took this opportunity to integrate grammatical fixes in certain areas. Some of those fixes were pulled directly from #7073, which I'm going to close now. Others are just from me working my way down from the top of the page and making fixes and improving consistency.
I'll work on other fixes in future PRs.
docs

Updates and grammar fixes to README.md

---

daemon/commands.c

Fix valgrind errors in the command server code.
daemon

Fix valgrind errors

---

daemon/main.c
daemon/unit_test.c
daemon/unit_test.h
database/engine/pagecache.c
database/engine/pagecache.h
database/engine/rrdengine.c
database/engine/rrdengineapi.c
database/engine/rrdenglocking.c

We are removing this fix for further internal testing, it will be returning after we iron out
some bugs.
This reverts commit 53ab093d84919c743450199a31bca9a13412e451.

Revert "Fix race condition in dbengine (#7533)"

---

exporting/exporting_engine.c

There was a 5-second delay on Netdata exit and the following message:
```
netdata ERROR : MAIN : Master thread EXPORTING takes too long to exit. Giving up...
```
This is a quick fix. The complete exporting engine cleanup will be done later (#7172).
Fixes #7541

Cleanup the main exporting engine thread on exit

---

netdata-installer.sh
packaging/docker/Dockerfile
packaging/docker/run.sh
packaging/installer/README.md
packaging/installer/kickstart-static64.sh
packaging/makeself/install-or-update.sh
packaging/makeself/makeself-help-header.txt

Add anon tracking notice for installers

---

collectors/python.d.plugin/hpssa/hpssa.chart.py

Fixes #7575 
hpssa python plugin

Fix not detecting more than one adapter in hpssa collector

---

docs/step-by-step/step-01.md

Fixes small typo in Docu I found during reading.

Minor: Documentation Typo alamrs -> alarms

---

collectors/python.d.plugin/python_modules/bases/collection.py

Fixes: #7642
`/collectors/python.d.plugin/python_modules`

python.d logger: unicode_str handle TypeError

---

.github/ISSUE_TEMPLATE/bug_report.md

When reporting bugs, users doesn't seem to know what information to
report for the line "OS / Environment".
- `uname -a`: Provide the arch + kernel (which has the dist tag name)
- `grep -Hv ^# /etc/*release`: most of distribution provide some sort
of /etc/*release file. Adding -H to get the filename too. And -v ^#
to remove comments if any
Example on my Fedora:
```
uname -a; grep -Hv ^# /etc/*release
Linux munin 5.2.18-100.fc29.x86_64 #1 SMP Tue Oct 1 13:32:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/fedora-release:Fedora release 29 (Twenty Nine)
/etc/os-release:NAME=Fedora
/etc/os-release:VERSION="29 (Twenty Nine)"
/etc/os-release:ID=fedora
/etc/os-release:VERSION_ID=29
/etc/os-release:VERSION_CODENAME=""
/etc/os-release:PLATFORM_ID="platform:f29"
/etc/os-release:PRETTY_NAME="Fedora …
```

[github/templates] Add samples cmds to get OS env

---

web/server/web_client.c

Fixes #7539
Agent/Web_Client
Permanent redirect sent when detected /HOST/HOSTNAME url to  /HOST/HOSTNAME/

Redirect when url =~ \/host\/hostname$ (#7539)

---

docs/generator/buildyaml.sh

Based on https://github.com/netdata/netdata/pull/7640#discussion_r362519469.
area/docs

Fix buildyaml.sh script so that docs generation works correctly.

---

README.md
docs/anonymous-statistics.md
docs/netdata-security.md
packaging/docker/README.md
packaging/installer/README.md

Fixes #7403
This is new, simpler attempt to fix #7403, after receiving feedback on the previous attempt (#7502). 
This PR clarifies and improves the verbiage around anonymous statistics and how to opt-out. Most of the effort has been in `packaging/installer/README.md`, `docs/anonymous-statistics.md` and `docs/security-design.md`. I also tweaked the Docker page as well.
docs

Docs: Improve documentation of opting out of anonymous statistics

---

health/health.d/softnet.conf

Fix unclosed brackets in softnet alarm
heath alarm

Fix unclosed brackets in softnet alarm

---

daemon/main.c
database/rrd.h
database/rrdhost.c

Fixes #7504, When rrd_init fails for localhost exit with error code

error exit when rrdhost localhost init fails #7504

---

backends/prometheus/backend_prometheus.c

Fixes #7680 
use calculated value instead of raw value
Backend remote write

Fixes #7680 Remote write

---

aclk/README.md

adds INSTRUCTIONS for modified mosquitto:
had to search for it so next guys can find it here right away

minor - update README.md for ACLK

---

packaging/installer/README.md

Refs #7473 
This fixes some documentation bugs for NetData on pfSense (_there may be other related fixes so this is a draft PR of the moment_)

Fixes for pfSense Installation

---

README.md

Following up on the fixes from #7193, I wanted to fix any lingering linter errors on the main `README.md` page.
This PR fixes all errors except for the link to our LinkedIn page, which registers as broken despite it working correctly. LinkedIn doesn't like these kinds of crawlers, apparently.
There are a lot of diffs, but I only changed line lengths, properly fenced tables, and fixed links. No content was changed.
docs

Docs: Linter fixes for main README

---

docs/contributing/contributing-documentation.md
docs/contributing/style-guide.md

I was getting the docs build setup again on my machine after reinstalling my OS and noticed a few things that could be cleaned up in these two docs. Figured I'd fix linter errors while I was in there.
docs

Docs: Tweaks and linter fixes to contributing guidelines

---

.travis.yml

Remove unneeded travis notifications. (Keep only notifications about failures)
Travis CI
Remove "Starting..." and "Publishing..." notifications which are notifications unrelated to failures.

.travis.yml: Reduce notifications

---

.travis.yml
.travis/package_management/configure_deb_lxc_environment.py
.travis/package_management/configure_rpm_lxc_environment.py
packaging/installer/README.md
packaging/installer/install-required-packages.sh
packaging/installer/kickstart.sh
tests/updater_checks.sh

As outlined in #7561, move the `install-required-packages.sh` script into the main Netdata repo. This puts the file where it's most likely to be seen by the people who actually need to review any changes to it.
area/ci
area/docs
area/packaging
Fixes: #7561

Move the script for installing required packages into the main repo.

---

exporting/init_connectors.c

Fix an issue with an unchecked return value.

Fix a Coverity issue

---

web/api/netdata-swagger.json
web/api/netdata-swagger.yaml

Fixes #7761 
adds swagger docu for 2 new badge parameters introduced in #6903

add swagger docu for `fixed_width_lbl` and `fixed_width_val`

---

.github/ISSUE_TEMPLATE/bug_report.md

Fixes: #7656
`.github/ISSUE_TEMPLATE`

bug_report improvements

---

collectors/node.d.plugin/snmp/snmp.node.js

ssia
[adding snmpv3 support](https://github.com/netdata/netdata/pull/7802) i noticed that code is not properly fomatted.
[`node.d.plugin/snmp`](https://github.com/netdata/netdata/tree/master/collectors/node.d.plugin/snmp)

node.d/snmp.node.js: format code

---

docs/tutorials/collect-apache-nginx-web-logs.md

This is the same fix as #7503, but we haven't heard from that contributor about signing the CLA for some time.
docs

Update collect-apache-nginx-web-logs.md to deprecated

---

packaging/installer/README.md

Changed `--disable telemetry` to `--disable-telemetry`

Fixed typo in README

---

Makefile.am
collectors/charts.d.plugin/Makefile.am
collectors/node.d.plugin/Makefile.am
collectors/python.d.plugin/Makefile.am
collectors/statsd.plugin/Makefile.am
health/Makefile.am
netdata.spec.in

Remove all refernces to .keep files

---

netdata-installer.sh
packaging/installer/README.md
packaging/installer/kickstart-static64.sh
packaging/makeself/install-or-update.sh

Fixes CI failures in #7846
area/packaging

Fixes and improves the installer/updater shell scripts.

---

daemon/common.c
daemon/common.h
health/health.c
health/health.h
libnetdata/health/health.c
libnetdata/health/health.h
web/api/web_api_v1.c
web/api/web_api_v1.h

Fixes #7869 
This PR fixes the problem reported to compile Netdata.
Health and WEB

Missing extern

---

collectors/python.d.plugin/phpfpm/README.md
collectors/python.d.plugin/phpfpm/phpfpm.chart.py

ssia
Fixes: #7868
[/collectors/python.d.plugin/phpfpm](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/phpfpm)

collectors/python.d/phpfpm: fix readme and per process chart titles

---

.travis.yml
packaging/docker/Dockerfile
packaging/docker/build.sh
packaging/manual_nightly_deployment.sh

Adds release channel argument to docker build scripts.
Fixes #7295

Add release channel customization to docker build

---

docs/netdata-cloud/signing-in.md

Removed weird code fragments, where we have normal markdown. 
docs

Fix wrong code fragments in signing in

---

daemon/main.c

Fix cmake build error

---

packaging/installer/functions.sh

See #7195
As per title
area/packaging
Noticing this in trying to repro #7195 and wondering why my repro was failing :)

Fixes a typo in ./packaging/installer/functions.sh with wrong message for updater cron script

---

packaging/installer/methods/manual.md

Partially fixes #6967
area/docs

Adds docs for how to build/install NetData on CentOS 8.x

---

packaging/installer/netdata-updater.sh

See #7195
As per title
area/packaging

Re-formatts ./packaging/installer/netdata-updater.sh with shfmt -w -i 2 -ci -sr

---

system/edit-config.in

See #7179
As per title.
area/system

Re-formats ./system/edit-config.in with shfmt -w -i 2 -ci -sr

---

.github/CODEOWNERS

@cosmix => @cosmix @ilyam8 @Ferroin @prologic 
`CODEOWNERS`

CODEOWNERS: change collectors/charts.d.plugin/ owners

---

docs/step-by-step/step-06.md

In #7977, @marienfressinaud fixed a few typos, but did not want to sign our CLA to have the PR merged. I brought the same changes into this PR instead. 
Thank you for pointing these out, @marienfressinaud!
docs

Fix typos in docs/step-by-step/step-06.md

---

packaging/makeself/install-alpine-packages.sh

Support static build for prom remote write
Fixes #7068

Support static builds for Prometheus remote write

---

collectors/python.d.plugin/python_modules/third_party/monotonic.py

Fixes: #7976
`python.d.plugin` doesnt work on synology systems, this patch fixes it (py2).
[/collectors/python.d.plugin](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/python_modules/third_party)
@BH1NBN could you test it?
- `wget https://raw.githubusercontent.com/ilyam8/netdata/monotonic_synology/collectors/python.d.plugin/python_modules/third_party/monotonic.py`
- replace old `monotonic.py` with new one in python.d.plugin thirtd_party dir
- restart netdata
___
Tested by @BH1NBN in https://github.com/netdata/netdata/pull/7980#issuecomment-582281992

/collectors/python.d.plugin/third_party: patch monotonic synology6

---

docs/generator/buildhtml.sh

Fixes: #8007
We can use `metadata` to set page title:
> https://squidfunk.github.io/mkdocs-material/extensions/metadata/#usage
> Metadata is written as a series of key-value pairs at the beginning of the Markdown document, delimited by a blank line which ends the metadata context. Naturally, the metadata is stripped from the document before rendering the actual page content and made available to the theme.
- Before
```markdown
...
```
- After
```markdown
title: h1 header
___
...
```
___
<details>
<summary>find src/collectors/go.d.plugin/ -type f -name "*.md" -exec head -5 -v {} \;</summary>
```markdown
==> src/collectors/go.d.plugin/modules/rabbitmq/README.md <==
title: rabbitmq
---
==> src/collectors/go.d.plugin/modules/k8s_kubeproxy/README.md <==
title: k8s_kubeproxy
---
==> …
```

/docs/generator: use h1 heading as page title for collectors pages

---

.github/PULL_REQUEST_TEMPLATE.md

Updating the PR template to include testing section.
github

Adding testing section to the PR template.

---

.travis/create_artifacts.sh

Revert "Added hack to sha256sums.txt to force users of NetData on v1.19.0-483 with a broken updater to update to latest"

---

.github/labeler.yml
.github/workflows/labeler.yml

- add `Dockerfile*` to `area/packaging` (see https://github.com/netdata/netdata/pull/8047)
- bump labeler version to `v0.1.0`
`v0.1.0` supports:
- path exclusion [[link](https://github.com/ilyam8/periodic-pr-labeler#path-exclusion)]
- logs all unmatched PRs on every run (easy to see what is missing)
`github/workflow`
- compiled `v0.1.0` and executed it
<details>
<summary>click click</summary>
```console
743 ilyam:labeler (master *%)$ ./labeler -d
DEBU[0003] found 38 open pull requests
DEBU[0004] PR netdata/netdata#6447                       labels="has all"
DEBU[0004] PR netdata/netdata#6390                       labels="has all"
INFO[0005] PR netdata/netdata#7271                       labels="no match"
DEBU[0005] PR netdata/netdata#6145                       labels="has all"
DEBU[0005] …
```

github/actions: update labeler config and bump version

---

packaging/installer/netdata-updater.sh

As per title
Thanks @aamoss :D

Fixes text if current version is >= latest version and already installed

---

.github/CODEOWNERS

Add Patti to codeowners for everything in the `docs/` folder and all `.md` files so she can get better visibility into docs changes across the board and help out without me or others manually added her as a reviewer.

Add Patti to docs and .md codeowners

---

collectors/ebpf_process.plugin/README.md

After discussing the eBPF installation and enabling process with Thiago, I decided to go into the document to clarify the process of getting this collector working. We didn't have any details about the required `--enable-ebpf` option, which would have probably stumped a lot of our ambitious users.
I'm not sure if this qualifies as a bug fix, but if not, it should be merged immediately after the release goes out so users will be able to find the correct information right away.
docs
collectors/
I will look at the Netlify preview once it finishes building.

Update eBPF docs with better install/enable instructions

---

collectors/ebpf_process.plugin/ebpf_process.conf
netdata-installer.sh

Fixes #8127 
This PR fixes the missing directory when creating the symbolic link
It also removes future options from plugin file.
Installer
Plugin

Small ebpf fixes

---

.travis/create_artifacts.sh

This reverts commit fd64a54e244f4380cc4e4e694126ca2b68f7d6f8.

Removed hack to force users off of stuck NetData v1.19.0-432

---

collectors/apps.plugin/apps_groups.conf

backup group updated, added lsyncd

---

packaging/installer/netdata-updater.sh

Fixes: #8171
`packaging/installer`
Before:
- stable (OK)
```cmd
test@DEB10-1:/opt/netdata/usr/libexec/netdata$ sudo ./netdata-updater.sh
Sun 23 Feb 2020 11:17:00 AM EST : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Sun 23 Feb 2020 11:17:02 AM EST : INFO:  Current Version: 0
Sun 23 Feb 2020 11:17:02 AM EST : INFO:  Latest Version: 001020000000
...
```
- nighlty (BROKEN)
```cmd
test@DEB10-1:/opt/netdata/usr/libexec/netdata$ sudo ./netdata-updater.sh
Sun 23 Feb 2020 11:15:59 AM EST : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Sun 23 Feb 2020 11:15:59 AM EST : INFO:  Current Version: 0
Sun 23 Feb 2020 11:15:59 AM EST : INFO:  Latest Version: 000000000000
...
```
___
After:
- stable (OK)
```cmd …
```

packaging/installer: fix get_latest_version for nightly channel

---

libnetdata/log/log.c

As described on https://github.com/netdata/product/issues/340 , we are sending undesired messages to GA. This PR parses the tag message avoiding the send of undesired messages to GA.
Report

Restrict GA message

---

collectors/ebpf_process.plugin/README.md
docs/generator/buildhtml.sh
docs/generator/buildyaml.sh

Per a request from @cakrit, I've changed the title of the eBPF collector and added it to the left-hand navigation:
It's inconsistent with the other internal collector plugin names, but I'll make a note for me and Patti to investigate those and change them soon as well.
docs/

Added eBPF to docs navigation and improved title

---

claim/netdata-claim.sh.in

This PR fixes the netdata.cloud claiming script.

Fix claiming script to reflect API changes on netdata.cloud

---

Dockerfile
netdata-installer.sh
packaging/installer/install-required-packages.sh
packaging/installer/methods/manual.md

This adds a few fixes for issues that were not caught in #8144 prior to it's merge.
area/docs
area/packaging
Basic verification with complex CFLAGS, CXXFLAGS, and LDFLAGS on various Linux VM's.

Fixes for issues not caught at review in #8144.

---

.github/workflows/reviewdog.yml

We have no Go code in this repo, so there's no point in trying to run Go linting checks.
area/ci
Based on discussion with @ilyam8 on Slack.

Removed reviewdog golang check.

---

claim/netdata-claim.sh.in

The claiming script does not parse the new API errors correctly.
Closes  #8151

Adapt the claiming script to new API responses

---

collectors/python.d.plugin/exim/README.md

Fixes: #8087
I just add requirements for exim plugin. Requirements is for Linux and WHM (Cpanel) servers.
Readme (Documentation)

added requirements for exim. Issue #8087

---

docs/generator/custom/themes/material/main.html

~~@jlbriston found that the recent addition of Schema tags in #8224 results in an error from Google Console. I think I found this fix, but this is a WIP until Netlify deploys and I can test the fix properly.~~
```
Parsing error: Missing '}' or object member name
```
**Update**: After some testing, there are still errors with this implementation, as a `step` value is required when using this schema. `mkdocs` can't really handle this right now—not without some things specified in frontmatter—so I need to disable the Schema tags for now.
docs

Disable Schema tag in documentation

---

collectors/ebpf_process.plugin/README.md

This PR adds information about the eBPF collector's performance testing, and makes a few other tweaks about where it works and what's possible with it.
docs/
collectors/ebpf_process.plugin

Tweak eBPF documentation and add performance data

---

packaging/installer/install-required-packages.sh

Fixes #8200
Closes #8201 (_supercedes_)
This fixes the NetData Installer for RHEL / CentOS 8.x by making sure we also
install the Okay repo and directly install the `Judy-devel` dependency
(_it doesn't actually appear in the PowerTools repo despite all evidence_).
This also gets us off of using GetPageSpeed repo(s) (See #8200 ) which now
require a $9.99USD/month subscription.
- area/ci
- area packaging
Ran the following _until_ we successfully install `netdata-all` dependencies as dictated by our Installer's `install-required-packages.sh` script:
```sh
$ docker run -i -t --rm -v "$PWD":/netdata -w /netdata centos:8 /bin/sh -c './packaging/installer/install-required-packages.sh --dont-wait --non-interactive netdata || /bin/bash'
```
Output:
```sh
.
.
.
Installed: …
```

Fix RHEL / CentOS 8.x dependencies for Judy-devel and others

---

.travis.yml
web/gui/dashboard.js

We need to properly quote YAML metacharacters.
area/ci
Verified that `.travis.yml` parses correctly as YAML.
Fixes: #8287

Fixed Travis CI build handling.

---

.github/CODEOWNERS
.github/workflows/reviewdog.yml
.travis.yml
.yamllint.yml

Add YAML file linting to prevent issues like #8287 from happening again.
area/ci
Checks pass on this PR.
Fixes: #8295

Added yamllint to reviewdog PR checks.

---

.github/workflows/reviewdog.yml
.yamllint.yml

* Turn off a buggy check in the yamllint config.
* Drop yamllint flags. Reviewdog checks all changed files, and the line
was misspelled anyway.
area/ci
Verified that it runs correctly on this PR.

Minor fixes for the yamllint CI.

---

docs/contributing/style-guide.md

The marketing team decided we should clarify explicitly how we should introduce abbreviations/acronyms to documents. Part of our effort to add both spelled-out names and acronyms in collectors documentation.
docs

Add standards for abbreviations/acronyms to docs style guide

---

.travis.yml
.travis/clangformat.sh

Remvoed the use of clang-format that does not actually block PRs or surface anything to developers #8188

---

.travis.yml

Retries things like:
> Netdata updater process failed on
- area/ci
- `yamllint`
- Travis itself monitoring next Nightly manually

Add retries for more Travis transient failures

---

.travis.yml

* Consolidates the two 'Artifact Validation' stages into one, improving paralellization and removing duplicate lifecycle checks.
* Fixes the Ubuntu 16.04 lifecycle check to actually run on Ubuntu 16.04 instead of natively in the Ubuntu 18.04 environment provided by Travis.
* Fixed the retry logic for the lifecycle checks so they don't unconditionally run 5 times causing builds to take multiple hours.
area/ci
Travis checks still pass correctly.

Consolidate and clean up artifact validation.

---

aclk/aclk_common.h
aclk/aclk_lws_wss_client.c
aclk/agent_cloud_link.c
aclk/agent_cloud_link.h
aclk/mqtt.c
aclk/mqtt.h
claim/claim.c
libnetdata/socket/security.c
libnetdata/socket/security.h
libnetdata/socket/socket.c
libnetdata/socket/socket.h

Closes #7738 
ACLK
Extensive testing has been performed during the smoke-test sessions, and then again locally. The review should not try to test this PR - setting up the test-configuration is not a good investment of time when it was done in smoke-testing, this will be tested again extensively on the real test system.
Please perform the highest-quality review that you can within a limited amount of time (2-3 hours?). There is a list of known issues in the ACLK that this PR does not fix (#8279). Because functional correctness is being handled via separate testing please focus on code quality / safety.

Implement the ACLK Challenge-Response Authentication

---

Makefile.am
aclk/aclk_common.c
aclk/aclk_common.h
aclk/aclk_lws_wss_client.c
aclk/aclk_lws_wss_client.h
aclk/agent_cloud_link.c
aclk/agent_cloud_link.h
aclk/mqtt.c
aclk/mqtt.h
build_external/clean-install-arch-extras.Dockerfile
build_external/clean-install-arch.Dockerfile
build_external/projects/aclk-testing/agent-valgrind-compose.yml
claim/claim.c
libnetdata/config/appconfig.h
libnetdata/socket/security.c
libnetdata/socket/security.h
libnetdata/socket/socket.c
libnetdata/socket/socket.h

Improve ACLK according to results of the smoke-test.

---

web/gui/dashboard_info.js

Fixes a typo in the ebpf plugin info
`web`
not testing

ebpf plugin info typo fix 

---

aclk/agent_cloud_link.h

Change topics in ACLK
ACLK
Ran against VerneMQ and verified change.

Change topics for ACLK

---

.travis.yml

This fixes a bug that was missed in #8321.
area/ci
Verified the structure of the YAML file to be correct relative to what Travis CI expects.

Fixed Travis configuration for nightly builds.

---

.github/PULL_REQUEST_TEMPLATE.md

Improves the Pull Request template with a couple of changes:
- Shorter section on "testing" -- "Test Plan"
- Enhanced instructions to be clear on CI coverage that __iif__ sufficient tests exists can be the "Test Plan"
(_NOTE: This is mostly likely only true for the C sources with cmocka, its a bit harder to unit test scripts, packaging, automation, etc..._)
- Github
- This PR itself

Improve Pull Request template to have a shorter testing section with enhanced instructions

---

CONTRIBUTING.md

Changing the structure of commit mesages.
n/a
n/a
n/a

Format of commit messages

---

docs/generator/custom/css/netdata.css
docs/getting-started.md
docs/step-by-step/step-02.md
web/README.md
web/gui/README.md

Closes netdata/marketing#175
We're adding Patti's dashboard intro video to a few relevant spots in the documentation to get some more eyes on it. I decided to leave them inside of `<details>` elements so that we don't interrupt the existing flow of these 3 documentation pages too much.
We're also experimenting with adding `date` values to frontmatter as we interact with various documentation files to better help us understand where we could focus our efforts in the future.
docs

Add Patti's dashboard video to docs

---

.github/scripts/run_install_with_dist_file.sh
.github/workflows/checks.yml
.travis.yml

As per title
This is part of a larger effort to migrate off of Travis for CI/CD for
the NetData Agent repo.
- area/ci
- This PR itself and the new GHA workflow based CI checks

Migrate make dist validation to GHA Workflows

---

.travis/README.md

Correct a typo in .travis/README.md
misc

Correct a typo in .travis/README.md

---

health/Makefile.am
health/health.d/dns_query.conf

Fixes: #8419
This PR adds and alarm that detects dns query failure.
`health`
- installed the branch
- enabled [`dns_query`](https://github.com/netdata/go.d.plugin/tree/master/modules/dnsquery) module
- emulated network failure (`iptables`)

health: add dns_query module alarm

---

netdata-installer.sh

Fix the broken --cloud-testing flag from the premature merge of PR8430.
ALCK

Fix the ACLK installation with the installer switch

---

packaging/installer/UPDATE.md

Fixes #7881 
To support the upcoming Cloud release, we need to have better instructions to help users update their agents to the latest version and access the new features. If their agent is old and they try to access deprecated features, they'll be directed to this document.
I got rid of most of the existing document and replaced it with instructions specific to different methods of installing Netdata.
Putting this up as a WIP so we can discuss the broad strokes and figure out what major pieces might be missing from what I've whipped up today. I'm not sure how deeply we want to (or can) dive into various OS/distros/versions.
cc @manos-saratsis 
docs
packaging/installer

Update the update instructions with per-method details

---

claim/claim.c
claim/netdata-claim.sh.in

#Fixes https://github.com/netdata/product/issues/568
claiming
Fix syntax error in claiming script when input is not numerical.

Fix syntax error in claiming script.

---

collectors/idlejitter.plugin/plugin_idlejitter.c
libnetdata/clocks/clocks.c
libnetdata/clocks/clocks.h

Fixes #8409
libnetdata
collectors
Test idlejitter plugin in the affected systems.

Add high precision timer support for plugins such as idlejitter.

---

collectors/python.d.plugin/python.d.plugin.in
collectors/python.d.plugin/python_modules/bases/FrameworkServices/SimpleService.py

Fixes: #8471
`collectors/python.d.plugin`
There is no cross pythond module importing, the fix doesnt affect any module/pythond itself.
However i installed the branch and tested it. I tested it debug mode for both py2 and 3 - no problems.

python.d.plugin: add prefix to the module name during loading source file

---

collectors/python.d.plugin/python_modules/bases/FrameworkServices/SimpleService.py

Fixes #8490
Description in the issue

python.d/SimpleService: fix module name

---

aclk/aclk_lws_https_client.c
aclk/aclk_lws_wss_client.c

Relaxes SSL checks for testing

---

aclk/agent_cloud_link.c
aclk/agent_cloud_link.h
aclk/mqtt.c
claim/claim.c
daemon/commands.c
web/api/web_api_v1.c

Improve the stability of the ACLK
ACLK

Improved ACLK 

---

aclk/agent_cloud_link.c
web/api/web_api_v1.c

Closes 8044
Fulfils the requirements in product/277.
web api
aclk
* Check the info endpoint with the link connected and disconnected.

The 4th flag

---

.yamllint.yml

ssia
120 is ok these days (yamllint counts comments)
`github/workflow/yamllint`

github/workflow:  increase yamllint line length 80=>120

---

.yamllint.yml

ssia
python.d plugin and its modules configuration files are in YAML format. This PR adds all these files to the `yaml-files`.
`github/workflow/yamllint`

github/workflow: add python.d configuration files to the yaml-files

---

.travis/package_management/configure_deb_lxc_environment.py

I missed this in #8397 :/
Fixes #8393
- area/ci

Add missing override for Ubuntu eoan

---

aclk/aclk_common.c
aclk/aclk_lws_https_client.c
aclk/agent_cloud_link.c
claim/claim.c
libnetdata/libnetdata.c
libnetdata/libnetdata.h

Fix the outstanding Coverity defects before the release.
various
* Single-stepped through a debugger to check the loading of `claim_id` and the private key during the ACLK establishment for a claimed agent.

Coverity scan

---

claim/README.md
claim/netdata-claim.sh.in
health/notifications/alarm-notify.sh.in
libnetdata/libnetdata.h
tests/alarm_repetition/netdata.conf_with_repetition
tests/alarm_repetition/netdata.conf_without_repetition

Fixes #8587 
Change all https://app.netdata.cloud URLs to https://netdata.cloud to restore connectivity with netdata cloud.

Change all https://app.netdata.cloud URLs to https://netdata.cloud

---

collectors/charts.d.plugin/libreswan/libreswan.chart.sh

Fixes: #7520
If `libreswan_sudo` parameter is set (which is default) netdata executes `ipsec` with sudo without checking if it has permissions to do it. As a result a user receives security notices on daily bases:
>  user NOT in sudoers ; TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=/usr/sbin/ipsec whack --trafficstatus
This PR adds the check.
`collectors`
```cmd
netdata $ ./charts.d.plugin 2>&1 | grep libreswan
2020-04-01 09:06:18: charts.d: ERROR: libreswan: not enough permissions to execute ipsec with sudo. Disabling Libreswan plugin.
2020-04-01 09:06:18: charts.d: ERROR: libreswan: module's 'libreswan' check() function reports failure.
```
```cmd
netdata $ ./charts.d.plugin 2>&1 | grep -B 2 libreswan
whack: Pluto is not running (no "/run/pluto/pluto.ctl")
whack: Pluto is not …
```

charts.d/libreswan: fix sudo check

---

README.md
build_external/README.md
collectors/COLLECTORS.md
collectors/macos.plugin/README.md
daemon/config/README.md
docs/netdata-security.md
docs/step-by-step/step-00.md
docs/step-by-step/step-04.md
docs/tutorials/collect-unbound-metrics.md
docs/what-is-netdata.md
health/REFERENCE.md
packaging/installer/methods/macos.md
packaging/maintainers/README.md

Fixes netdata/marketing#180
At some point, Apple rebranded its OS as **macOS**, not **MacOS** or any other derivative. I did some find-replace through the repo to change these references whenever possible.
Some artifacts still exist, but only in `node_modules` and the historical changelog.
docs

Docs: Change MacOS to macOS

---

README.md

Update the **News** section **At a glance** content from the 1.21 release notes.

Update main README with 1.21 release news

---

aclk/agent_cloud_link.c
aclk/agent_cloud_link.h
aclk/mqtt.c

Add session-id using connect timestamp

---

.travis.yml
packaging/docker/build.sh
packaging/docker/publish.sh

Remove DEVEL support from packaging/docker/build.sh and packaging/docker/publish.sh

packaging/docker/{build,publish}.sh: Remove DEVEL support

---

health/health.d/x509check.conf

Template to monitor the certificate revocation
health.d
A certificate which is not revoked yet
A revoked certificate (https://revoked.grc.com/)

added certificate revocation alert

---

aclk/agent_cloud_link.c

Revert "Improved ACLK reconnection sequence "

---

.travis/utils.sh
packaging/docker/publish.sh

Docker publishing script: Wait for a recently published tag to appear in docker hub before proceeding.

packaging/docker/publish.sh: Wait for tag to appear in hub.docker.com

---

Dockerfile.docs

ssia
- area/ci
- Tested locally when fixing this

Fix docs Docker-based builder image

---

netdata-installer.sh

This takes advantage of the fact that cmake is now a required build dependency to allow building libmosquitto on FreeBSD and macOS systems.
area/packaging
Verified that the installer appears to work correctly on FreeBSD 11, FreeBSD 12, and macOS 10.15.
This will bring ACLK dependency support for FreeBSD and macOS installs using `kickstart.sh` on par with Linux. If we want people to actually have ACLK support on these platforms though, we need to get the Homebrew formula and the FreeBSD port updated to bundle libmosquitto and depend on LWS 3.x, as those are the installation methods most users are using on them.

Added support for building libmosquitto on FreeBSD/macOS.

---

collectors/plugins.d/plugins_d.c

Fixes #8771 
Stream
1 - Start a master
2 - Start a slave
3 - Restart slave
The master cannot die after the restart process.

fix_lock: Add the missing lock

---

health/Makefile.am
health/health.d/whoisquery.conf

This template is for the netdata whoisquery plugin written in Go.
health
A domain which expires in 365 days with `days_until_expiration_critical` of the default (30 days)
A domain which expires in 45 days with `days_until_expiration_critical` of 50 days

added whoisquery health templates

---

web/gui/demo2.html

web/gui/demo2.html: Silence Netlify's mixed content warnings

web/gui/demo2.html: Silence Netlify's mixed content warnings

---

streaming/README.md

capitalize title

---

netdata-installer.sh

Fixes a typo in the netdata-installer.sh script.

Fix typo in netdata-installer

---

.github/workflows/checks.yml

ssia
- area/ci
- This PR and the new Checks

Add CI check for building against LibreSSL

---

claim/claim.c
claim/netdata-claim.sh.in

Fix claiming error handling to cover more cases as described in https://github.com/netdata/product/issues/830 and improve error reporting.
Also fix bug when the root user runs claiming script.
claim

Fix claiming error handling

---

packaging/docker/README.md

correct typo

---

aclk/agent_cloud_link.h

Reduce ACLK_STABLE_TIMEOUT from 10 to 3 seconds

---

claim/netdata-claim.sh.in

Provide feedback to the user if they claimed through a proxy explaining they should update their netdata config.
claiming
Test successful / unsuccessful claims through a proxy / not through a proxy.

Provide feedback on proxy setting changes

---

aclk/agent_cloud_link.c
health/health_json.c

Fetch active alarms from the alarm log
ACLK

Fetch active alarms from alarm_log

---

daemon/config/README.md

Remove UNUSED word from flood protection documentation.

Remove UNUSED word from flood protection documentation

---

docs/tutorials/collect-apache-nginx-web-logs.md

Fix file name weblog.conf -> web_log.conf

---

README.md

Fairly self-explanatory. Part of the release process checklist.

Update news section of main README with 1.22 news

---

aclk/README.md
daemon/config/README.md

Per recommendation from @cakrit.
aclk/

Add text to ACLK doc mentioning WebSockets and port

---

daemon/README.md

Fixes netdata/marketing#215
Following up on #8937, this PR updates the example output from running `netdata -help` so that it reflects the changes @zack-shoylev made to the URLs and copyright years.

Update daemon output with new URLs and dates

---

claim/README.md

To address initial user feedback on how to move a node from one Space to another.
claim

Add text to claiming doc about reclaiming with id=

---

docs/step-by-step/step-03.md

removed simley face per Chris since it didn't show up

---

docs/tutorials/collect-apache-nginx-web-logs.md

Fixes #8848
I tried using a relative link to a go.d plugin, and while that works on the Learn site, it doesn't work on GitHub. This PR uses an absolute URL, so it'll work on both GitHub and Learn.
docs

Fix link in web server log guide

---

claim/README.md

Make sure the doc mentions that the agent must be restarted when a new uuid is generated when deleting/reclaiming a node.
docs
none

Add agent restart note for reclaiming

---

claim/README.md

ssia
we need to pass only args
https://github.com/netdata/netdata/blob/22b8f9498ad240055f7b63eb7d409dba60e4a5f4/packaging/docker/run.sh#L27
docs

claim: fix `New/ephemeral Agent containers` instruction

---

exporting/README.md
exporting/aws_kinesis/README.md
exporting/mongodb/README.md
exporting/prometheus/remote_write/README.md
exporting/pubsub/README.md

This PR adds some frontmatter to the existing exporting engine connector READMEs so that they will display better and have better SEO on Learn.
exporting

Add frontmatter to exporting connectors

---

collectors/proc.plugin/README.md

Fixes #8941
This PR adds some text to the proc.plugin collector to help users who have systems with high processor counts. The wording around this in indeed tricky, so please let me know any suggestions to improve it.
collectors/proc.plugin/

Add proc.plugin configuration example for high-processor systems

---

collectors/python.d.plugin/proxysql/README.md

Fixes: #9069
`python.d/proxysql`
`-`

python.d/proxysql: add `Requirements` to the readme

---

exporting/Makefile.am
exporting/README.md
exporting/TIMESCALE.md
exporting/WALKTHROUGH.md
exporting/exporting.conf
exporting/opentsdb/Makefile.am
exporting/opentsdb/README.md
exporting/prometheus/README.md
exporting/pubsub/README.md

The documentation for the exporting engine was prepared for the upcoming release.
Part of #7015

Update the exporting documentation

---

database/engine/datafile.h
database/engine/rrdengineapi.c
database/engine/rrdengineapi.h

Fixes #9083
database /engine
Set dbengine configuration option to `dbengine disk space = 64`.

Reduce minimum size for dbengine disk space

---

web/gui/dashboard_info.js

Fix a typo in a component description on the main dashboard
Memory used by kernel
N/A

Fix typo in dashboard description

---

docs/README.md
docs/contributing/contributing-documentation.md
docs/contributing/style-guide.md
docs/step-by-step/step-99.md
docs/what-is-netdata.md
packaging/DISTRIBUTIONS.md
packaging/docker/README.md

This PR changes some of the docs contributing guidelines considering that the old docs site (built with mkdocs) is going away soon (#8756). I removed information about running the docs locally, updated some links, and then did a general grammar/copyedit run through the document.
This also fixes a pesky broken link that I couldn't fix correctly otherwise, and renames a few mentions of **docs.netdata.cloud**.
docs

Docs: Update contributing guidelines

---

exporting/clean_connectors.c
exporting/exporting_engine.c
exporting/exporting_engine.h
exporting/send_data.c
exporting/tests/test_exporting_engine.c

Part of #7172
Run Netdata. Kill it with SIGTERM.

Prepare the main cleanup function for the exporting engine

---

aclk/README.md

Make IPs are documented as well as broad types of data currently uploaded (to be made more specific going forward)
doc update
none
https://github.com/netdata/marketing/issues/233

Add ACLK Connection Details

---

netdata-installer.sh

ssia
<details>
<summary>
Before:
</summary>
```#!sh
$ brew  sh
brew ~/NetData/netdata$ ./netdata-installer.sh --dont-wait --dont-start-it --disable-go --require-cloud --install /tmp/netdata.
.
.
checking if cloud functionality should be enabled... yes
configure: WARNING: OpenSSL required for agent-cloud-link but not found. Try installing 'libssl-dev' or 'openssl-devel'.
checking if libmosquitto static lib is present (and builds)... no
checking if libwebsockets static lib is present... yes
checking if netdata agent-cloud-link can be enabled... no
configure: error: User required agent-cloud-link but it can't be built!
FAILED
.
.
.
```
</details>
<details>
<summary>
After:
</summary>
```#!sh
$ brew  sh
brew ~/NetData/netdata$ ./netdata-installer.sh --dont-wait …
```

Fix macOS builds building and linking against openssl

---

.github/workflows/docs.yml
docs/getting-started.md

Docs workflow wasn't running on PRs that edit `.md` files, but this should fix it with the correct paths.
area/ci
area/docs

Fix paths to trigger docs CI workflow

---

packaging/installer/install-required-packages.sh

Fix incorrect issue link URL in install-required-packages.sh

---

docs/step-by-step/step-03.md

Fix a typo in one of the documentation pages.
Documentation
N/A

fix typo in step-03.md

---

exporting/send_data.c

Fixes #9179 
Exporting
1 - Configure a JSON exporting setting your `exporting.conf' like this
```
enabled = yes
send configured labels = yes
send automatic labels = no
[json:instance0]
enabled = yes
destination = localhost:5448
```
2 - start a database:
```
nc -lntp 5448
```
3 - Start Netdata
4 - Wait few minutes and stop Netdata again.
5 - Verify inside logs that Netdata finished gracefully

cov_358988: Remove coverity bug

---

collectors/ebpf.plugin/README.md

Fixing small typo in description of of the file chart for the README.md in eBPF Monitoring
/collectors/ebpf.plugin
Just documentation

fix small typo

---

backends/README.md
docs/export/README.md
exporting/README.md
exporting/mongodb/README.md

This PR creates a new "home base" for the exporting engine at `/docs/exporting/README.md` to let the original file at `/exporting/README.md` serve as a reference guide with the complete configuration options, and so on.
The goal here is to create a shorter document to help onboard users to exporting and/or get the migrated from backends quickly.
area/exporting
area/docs

Add new exporting "home base" document

---

collectors/apps.plugin/README.md
collectors/ebpf.plugin/README.md
web/gui/dashboard_info.js

Fixes #8915 
This PR brings the changes for the apps.plugin documentation and dashboard.info.
Docs
Compile Netdata and open your browser to see the information on dashboard.
The charts will be visible only after #9178 is merged.

Update apps.plugin documentation and dashboard.info

---

SECURITY.md

fixes a visual glitch in docs
docs
none

single quote apostrophe

---

collectors/ebpf.plugin/README.md

This gives an explanation on how mounts are created for ftrace.
It also provides and example for /etc/fstab

Add link to kernel docs for ftrace

---

health/notifications/Makefile.am
health/notifications/alarm-notify.sh.in
health/notifications/health_alarm_notify.conf
health/notifications/matrix/Makefile.inc
health/notifications/matrix/README.md

Previously pushed as Pull request
https://github.com/netdata/netdata/pull/5741/
Original authors: Fanis Dokianakis @infl00p & Pablo Ovelleiro Corral @pinpox
I did just rebase against master and merged commits for better readability.

Support for matrix notifications

---

health/notifications/matrix/README.md

I neglected to help the contributor add this to the document, so I have to follow up with a separate PR. I also made a few small linter fixes and added the GA tag since I was already in the document.
area/docs
area/notifications

Add frontmatter to Matrix notifications doc

---

SECURITY.md

minor copy edits

---

collectors/apps.plugin/apps_groups.conf

Fixes #9282 
Fixes #9283
Apps.plugin
Please, @TheOldMan2000, can you test this PR and verify that it is working?

update_apps_groups: Bring imunify and lsphp to apps groups

---

spawn/spawn.c

Related to https://github.com/netdata/netdata/issues/9113
daemon
This PR adds additional information to help debug issues such as #9113

Add verbose prints when spawn server fails to spawn.

---

docs/export/README.md
docs/guides/export/export-netdata-metrics-graphite.md
exporting/README.md

This PR creates a new guide for exporting metrics to Graphite using the exporting engine in support of the 1.23 release. Just the first of many similar guides for other exporting endpoints...
area/exporting
area/docs

Add guide to exporting metrics to Graphite

---

netdata-installer.sh
packaging/makeself/install-alpine-packages.sh
packaging/makeself/jobs/50-bash-4.4.18.install.sh
packaging/makeself/jobs/50-curl-7.60.0.install.sh
packaging/makeself/jobs/50-fping-4.2.install.sh
packaging/makeself/jobs/70-netdata-git.install.sh

This is a continuation from #9263 that makes it actually work correctly.
area/packaging
More thoroughly locally verified than last time.
Fixes: #9206

Override linker and include paths for static builds.

---

.github/workflows/build-and-install.yml

ssia -- Takes too long :/
- area/ci
N/A

Remove Gentoo from CI

---

CONTRIBUTING.md

ssia
- github
- spellcheck / grammar check
This was a PR once upon a time and @cosmix even had review comments which I
addressed, but for some reason I could not find this PR anywhere but I did
find the branch so I'm putting it backup.
See also #8575

Improve PR Guidelines for Developers and Contributors.

---

netdata-installer.sh
packaging/makeself/install-alpine-packages.sh
packaging/makeself/jobs/50-bash-4.4.18.install.sh
packaging/makeself/jobs/50-curl-7.60.0.install.sh
packaging/makeself/jobs/50-fping-4.2.install.sh
packaging/makeself/jobs/70-netdata-git.install.sh

Revert "Override linker and include paths for static builds."

---

collectors/freeipmi.plugin/freeipmi_plugin.c
daemon/commands.c
database/engine/datafile.c
database/engine/global_uuid_map/global_uuid_map.c
database/engine/journalfile.c
database/engine/metadata_log/compaction.c
database/engine/metadata_log/logfile.c
database/engine/metadata_log/metadatalog.c
database/engine/metadata_log/metadatalogapi.c
database/engine/metadata_log/metalogpluginsd.c
database/engine/pagecache.c
database/engine/pagecache.h
database/engine/rrdengine.c
database/engine/rrdengineapi.c
database/engine/rrdenginelib.c
database/engine/rrdenginelib.h
database/engine/rrdenglocking.c
database/rrdset.c
libnetdata/log/log.h
spawn/spawn.c
spawn/spawn_client.c
spawn/spawn_server.c

Replace all assert() calls with the new fatal_assert() for proper logging.
daemon

Replace assert calls

---

packaging/installer/methods/manual.md

Based on discussion earlier today with @zack-shoylev and @joelhans.
area/docs
I thought this would be a bigger PR, but I had not noticed earlier today that everything else I would have been adding was already there.

Added OpenSSL to list of dependencies for Netdata Cloud.

---

collectors/ebpf.plugin/README.md

Related to #9201
This PR adds a small notice to the eBPF docs that it's not currently compatible with static build installations. We'll remove this text once support is properly added back in.
area/docs

Add notice to eBPF documentation about incompatibility with static builds

---

netdata-installer.sh
packaging/installer/install-required-packages.sh

ssia
- Fixes #9163
- Fixes #9109
- Closes #8130
- Spin up a fresh FreeBSD VM
- Clone Netdata and Checkout this branch
- Run `./packging/installer/install-required-packages.sh`
- Run `./netdata-installer.sh`
Tested:
- `./packaging/installer/install-required-packages.sh --dont-wait --non-interactive`
- `./netdata-installer.sh --disable-go --require-cloud`
- `claim.sh ...`
- Successfully claimed and connected to Netdata Cloud.

Add first class support for FreeBSD

---

packaging/docker/README.md

The existing link to Polyverse is broken (I think they changed their URLs and don't have a redirect set up), so this PR fixes that link.
area/packaging
area/docs

Fix broken link to Polyverse in Docker documentation

---

database/engine/metadata_log/metadatalogapi.c
database/engine/metadata_log/metalogpluginsd.c
database/rrddim.c
database/rrdset.c

Fixes #9411 
database
Affected systems stop crashing with segfault.

Disallow dimensions and chart being obsolete and archived simultaneously.

---

daemon/system-info.sh

This updates our virtualization detection to report 'none' when it can't find any virtualization instead of reporting 'unknown', providing better consistency in the Cloud display of node information.
area/daemon
Script tested locally.
Fixes: #9114

Corrected virtualization detection in system-info.sh.

---

exporting/tests/test_exporting_engine.h

In exporting/tests/test_exporting_engine.h, wrap header definitions in compilation conditions
Fixes #9430
Tests
Run tests with mongo absent.

Wrap header definitions in compilation conditions

---

streaming/README.md

It appeared me that few words were missing a first letter in caps.
Documentation
None
Maybe it's just a _style_, so feel free to cancel this pull request in this case :wink:

Added missing caps letters

---

collectors/cgroups.plugin/sys_fs_cgroup.c

Fixes CID 360246:  Resource leaks  (RESOURCE_LEAK)
cgroups plugin

Fix a coverity defect

---

database/rrddim.c
database/rrdhost.c
database/rrdset.c
health/health.c

Fixes #9457
database
health
Have users that originally reported the issue verify it is fixed.
Disassociate health variables and alarms from archived charts and dimensions.

Remove health from archived metrics

---

.github/workflows/build-and-install.yml

ssia
- area/ci
This PR
See #8502 and search for "Judy" or "CentOS" in issues.

Disable CentOS 8.x CI (temporarily)

---

libnetdata/storage_number/storage_number.c
libnetdata/storage_number/tests/test_storage_number.c

Fixes #6839
Improves stored number accuracy
agent

Fixed stored number accuracy

---

collectors/proc.plugin/proc_mdstat.c
database/rrd.h

Fixes #9581
Fixes #9530
collectors
database
Have users verify that the original issues have been resolved.

Stop mdstat collector from looking up archived charts.

---

collectors/python.d.plugin/gearman/gearman.chart.py

Fixes: #9604
`python.d/gearmand`
@bokutin could you test this PR? [This case](https://github.com/netdata/netdata/issues/9604#issuecomment-664159099) should be handled.

python.d/gearmand: handle func prefixes in `status\n` response

---

README.md

This PR removed old news and updates it with new release notes.
I neglected to do this in sync with the actual release(s), which was an oversight on my part.

Add 1.23.1 and 1.23.0 to news section

---

collectors/ebpf.plugin/README.md

Command fails if `/bin/sh` is symlinked to `dash` since it was written for bash.
ebpf.plugin/README.md
Tested on Ubuntu.

Adjust check-kernel-config.sh to run in bash

---

.travis.yml

Fix Travis CI and remove deprecated/removed builds that have no upstream LXC image

---

claim/claim.c

Fix coverity defect 361022 Missing comma in a string array initialization
claim/

Fix missing comma.

---

collectors/proc.plugin/proc_mdstat.c
database/rrd.h

Fixes (maybe) #9581
collectors
database
Have users verify that the original issues have been resolved.

Hide archived chart from mdstat collector.

---

.travis/package_management/configure_deb_lxc_environment.py
CONTRIBUTORS.md

Quick fix to https://github.com/netdata/netdata/pull/9592

Fix print message when building for Ubuntu Focal

---

collectors/freebsd.plugin/freebsd_ipfw.c
collectors/freebsd.plugin/freebsd_sysctl.c
collectors/macos.plugin/macos_mach_smi.c
collectors/macos.plugin/macos_sysctl.c

Fixes #9485
collectors
Have users with macOS and FreeBSD verify the fix.

Fix collectors on MacOS and FreeBSD to ignore archived charts.

---

collectors/plugins.d/pluginsd_parser.c
daemon/system-info.sh

Fixes #9662
streaming
Create labels with empty values in the child node. Test that it does not crash.

Fix crash when receiving malformed labels via streaming.

---

streaming/sender.c

Fixes #9700 
streaming
1. Use @mfundul's CFLAGs from the issue to switch on the address sanitizer.
2. Stream from a child to a parent.
3. Check that the child does not abort.

Remove broken optimization in the sender thread

---

CONTRIBUTING.md
README.md

Adds a link to the new community website
README

Add community link to readme

---

collectors/python.d.plugin/isc_dhcpd/README.md
collectors/python.d.plugin/isc_dhcpd/isc_dhcpd.chart.py
collectors/python.d.plugin/isc_dhcpd/isc_dhcpd.conf

info package is needed
collectors/python.d.plugin/isc_dhcpd/

python.d/isc_dhcpd: add support for ip ranges

---

collectors/nfacct.plugin/plugin_nfacct.c

Fixes #9744 
This PR adds a signal callback to plugin for it closes if a SIGPIPE is received.
Netfilter plugin
1 - Create a "high" frequency alarm like this:
```
alarm: dev_dim_template
on: system.cpu
os: linux
lookup: sum -1s percentage foreach *
units: %
every: 1s
crit: $this > 4
```
2 - Start the `parent` and at least 1 `child` 
3 - Run the following script on parent:
```
bash-5.0# for i in `seq 1 10`; do curl -o stable http://localhost:19999/host/zeus/api/v1/data?chart=system.cpu ;  killall -USR2 
```
When Netdadata crashes we should not have netfilter plugin as zombie process .

fix_broken_pipe: Fix netfilter for it closes when sigpipe happens

---

docs/privacy-policy.md

The Learn site generator threw a warning for this one link in the privacy policy. I updated it to the new "format" of always beginning from the project root and always explicitly referencing an `.md` file.
docs
privacy policy

Fix broken link in privacy policy

---

.travis/package_management/create_lxc_for_build.sh

Fix Travis CI builds and skip Fedora 31 i386 build/test cycles

---

packaging/docker/README.md

Fix docker packaging caddyserver basicauth link

---

database/engine/README.md
docs/guides/longer-metrics-storage.md

Now that the dbengine calculator is updated for the new multihost dbengine, I wanted to update the dbengine doc to promote the calculator again as valid. I also did a bit of cleanup and reorganization along the way.
area/docs
area/database

Improve dbengine docs and add new multihost setting

---

health/QUICKSTART.md
health/README.md
health/REFERENCE.md

The brackets around the GitHub edit URL in the reference doc are throwing errors over on Learn. This PR removes the brackets. I also removed some unnecessary frontmatter code from adjacent docs as well.
area/docs
area/health

Fix broken link and clean up frontmatter in health docs

---

.github/workflows/build-and-install.yml
tests/updater_checks.sh

SSIA
area/ci
Build process tested locally in Arch Linux, checks verified on my fork.
Fixes: #9824

Ensure Arch Linux images are up to date in CI before running checks.

---

web/api/README.md

As requested by @jacekkolasa in #9796—we're removing some of this information as it's quite outdated, and thus no one really knows how it works or why the example code in jsfiddle fails in the user's tests. They're moving to the officially-supported dashboard features anyway.
area/docs
area/web

Remove Google Charts info from API doc

---

database/engine/rrdengineapi.c

Fixes #9675 
database
1. Set-up a netdata streaming scenario (1 parent, 1 child).
2.  Stop the child agent.
3. Clean up netdata caches of the parent host (`rm -rf /var/cache/netdata/*`) .
4. Check out code before the persistent metadata PR (`git checkout v1.21.0`)
5. Restart the parent agent twice, with a couple of minutes intervals, so that the cache is persisted with legacy metrics.
6. Install the code from the master branch.
7. Start the child agent. Its metric data should go into the multi-host db now.
8. Bring up the parent agent's dashboard. Make sure you can see the metrics for both hosts (via the parent's dashboard) in separate browser windows/tabs. Don't refresh.
9. Stop the child agent.
10. Restart the parent agent.
11. Observe new metric data in both browser windows, even in …

Fix multi-host DB corruption when legacy metrics reside in localhost.

---

docs/guides/monitor/stop-notifications-alarms.md
docs/guides/step-by-step/step-05.md

While I was working with an user to fix his problem #9827, he correctly [called my attention](https://github.com/netdata/netdata/issues/9827#issuecomment-684964776) for the fact we have a typo error in our health documentation.  
Documentation

health_fix_typo: Fix typo

---

.github/labeler.yml

`area/exporting` label was added, reflect these changes to the labeler action config
`github actions/labeler`

labeler: add `area/exporting`

---

daemon/system-info.sh

Summary
As talked in  https://github.com/netdata/netdata/issues/9868#issuecomment-686231142, fix macOS lack of ram info in the  system-info.sh script.
daemon/system-info.sh

fix lack macOS ram info in system-info.sh

---

netdata-installer.sh
netdata.spec.in

ssia
This PR.
Resolved [this broken
job](https://travis-ci.com/github/netdata/netdata/jobs/381373869)

Fix typod option name used to use bundled libJudy

---

netdata.spec.in

Fix missing newline concatentation slash causing rpm build to fail

---

.travis.yml
tests/installer/slack.sh

Correct version of #9897. I did not realize we were doing our own message handling instead of using Slack integrations for Travis itself.
area/ci
Tested on my local fork.

Correctly fix handling of CI Slack notifications.

---

docs/get/README.md

Moving on to the installation/setup doc. See netdata/netdata-learn-docusaurus#285 for additional context.
This page contains some elements that will only appear on the deployed Learn site, so see the deploy preview for this page for the full picture: https://deploy-preview-285--netdata-docusaurus.netlify.app/docs/get
**Some links will not work, as the target docs do not exist yet.**
For now, these PRs will get merged into the docsv2 but not go live on Netdata Learn. Once they're all available, or at least a workable majority, we'll merge them into master and deploy the project as a whole.
area/docs

Add Get doc to docsv2 project

---

docs/configure/invite-collaborate.md
docs/configure/nodes.md
docs/configure/secure-nodes.md
docs/configure/spaces-war-rooms.md
docs/overview/netdata-monitoring-stack.md
docs/overview/what-is-netdata.md
docs/overview/why-netdata.md

Moving into configuration. Two documents for Cloud-specific configurations, and then another two documents for node configuration basis and improving security of nodes.
>
>
>
area/docs

Add configure docs to docsv2 project

---

docs/guides/monitor/stop-notifications-alarms.md
docs/guides/step-by-step/step-05.md
health/QUICKSTART.md

@amoss  wrote something that we missed when we brought [netdatacli](https://github.com/netdata/netdata/issues/9827#issuecomment-685421668), so I am bringing this PR to update our documentation related to health.
Doc

Change instruction to reload HEALTH

---

collectors/COLLECTORS.md

This PR dramatically changes our supported collectors list document so collectors are organized by type, not orchestrator.
This builds off the work @ilyam8 did a few months back to help me put all the collectors into a single document, but since then it's become clearer that we should organize collectors by their service, not what orchestrator they belong to.
area/docs

Update supported collectors doc to organize by type

---

database/rrddim.c
database/rrdset.c

Fixes #9909
database
See the description [here](https://github.com/netdata/netdata/issues/9909#issue-697680196).

Fix memory mode none not marking dimensions as obsolete.

---

database/rrddim.c
database/rrdset.c

Fixes #9914
database
Check the description [here](https://github.com/netdata/netdata/issues/9914#issue-698048867)

Fix memory mode none not dropping stale dimension data

---

packaging/docker/README.md

Fixes #9916 
This PR brings the solution for 9916 according the comments made [here](https://github.com/netdata/netdata/issues/9916#issuecomment-691800685) and [here](https://github.com/netdata/netdata/issues/9916#issuecomment-691310254)
Documentation

Unix socket docker

---

aclk/aclk_rx_msgs.c

Fixes resource leak in case of malformed cloud request
CID 307146
Thanks for @thiagoftsm for noticing this.
ACLK v2 `http` request

Fix resource leak in case of malformed cloud request

---

docs/quickstart/infrastructure.md
docs/visualize/create-dashboards.md
docs/visualize/interact-dashboards-charts.md
docs/visualize/view-all-nodes.md

Three documents about Netdata's visualization features. The content is about 90% rehashing of existing content, which will be deprecated in the near future.
>
>
>
area/docs

Add visualize docs to the docsv2 project

---

health/notifications/Makefile.am
health/notifications/alarm-notify.sh.in
health/notifications/health_alarm_notify.conf
health/notifications/stackpulse/Makefile.inc
health/notifications/stackpulse/README.md

Fixes #9870 
After #9886 to be closed, I am creating this new PR with the code present there.
Everything wrote [here](https://github.com/netdata/netdata/pull/9886#issue-480200386)

Stackpulse integration

---

health/notifications/stackpulse/README.md

Removes duplication from the first paragraph.
Doc

Fix Stackpulse doc

---

web/server/web_client.c

Fixes #10004
When the fix to Proxy redirect was made, few `ssl` structure were kept outsife `#ifdefs`, this PR fixes the reported error.
Web
1 - Compile the PR on an environment without OpenSSL.

Add missing tests to the web server

---

docs/collect/application-metrics.md
docs/collect/container-metrics.md
docs/collect/system-metrics.md
docs/configure/nodes.md
docs/configure/secure-nodes.md
docs/get/README.md
docs/monitor/configure-alarms.md
docs/monitor/view-active-alarms.md
docs/overview/what-is-netdata.md
docs/overview/why-netdata.md
docs/quickstart/infrastructure.md
docs/store/distributed-data-architecture.md
docs/visualize/view-all-nodes.md

Cleaning up some of the `docsv2` project now that the whole package is deployed. I also added code to enable better icons in dark mode on the [Get Netdata page](https://learn.netdata.cloud/docs/get). (cc @OdysLam).
area/docs

Clean up and better cross-link new docsv2 documents

---

packaging/installer/functions.sh

SSIA
area/packaging
Fixes: #10025 
Credit goes to @marcingarski for spotting this.

Fixed incorrect condition in updater type detection.

---

.github/CODEOWNERS

As he’s moving on to a new job, I’m taking over ownership of all the agent CI/infra code as the sole remaining agent SRE (for now).
area/infra
n/a
Currently in discussion with the rest of the SRE team to decide how we will handle the things that now would have me as the sole code owner.

Removed @prologic from CODEOWNERS.

---

streaming/receiver.c
streaming/sender.c

Replace memcpy() with memmove() for overlapping memory ranges.
streaming
Set-up streaming. Observe nothing breaking.

Replace memcpy() with memmove() for overlapping memory ranges.

---

collectors/python.d.plugin/hpssa/hpssa.chart.py

Add support for disks in HBA mode on HP controllers. 
python.d/hpssa.chart.py
Manually tested in debug mode: /usr/libexec/netdata/plugins.d/python.d.plugin hpssa debug trace
Tested on HP ProLiant DL380p Gen8 with Smart Array P420i.
The following output proves that the values are parsed correctly
2020-10-17 21:11:21: python.d DEBUG: hpssa[hpssa] : Executing command '/usr/bin/sudo -n /usr/sbin/ssacli ctrl all show config detail'             
BEGIN hpssa.ctrl_temperature 4996794                                                                                                              
SET 'cache_0_temperature' = 41                                                                                                                    
SET 'ctrl_0_temperature' = 68 …

Add support for HBA drives in hpssa.chart.py

---

README.md

This PR is a significant rewrite/reconfiguration of the Netdata Agent's main README. The goal here is to simplify the structure, foreground Netdata's amazing features, update some of the graphical elements, and better align the messaging with the project's current goals.
Best reviewed using the **View file** option to see how it'll look once it's live on the repo.
The changes were already approved by @ktsaou in a [testing PR](https://github.com/netdata/marketing/pull/250), but this makes it more real. :astonished:

Rewrite the repository's main README

---

.github/CODEOWNERS

Added Konstas Kaskavelis as a code owner for CI.

---

packaging/docker/README.md

Fixes #9948
Documenting the three options that James recommended in the above issue.
area/docs

Add documentation for configuring/editing hostnames of Docker-run Agents

---

docs/guides/monitor/pi-hole-raspberry-pi.md
docs/guides/troubleshoot/monitor-debug-applications-ebpf.md
docs/visualize/overview-infrastructure.md

Got a warning about the broken link in the Overview doc after deploying it today, the others two came from Ahrefs.
area/docs

Fix broken links in docs

---

exporting/prometheus/remote_write/README.md

remote_write --> prometheus_remote_write

fix configuration category in docs/prometheus_remote_write

---

packaging/installer/methods/freebsd.md
packaging/installer/methods/pfsense.md

Users should be aware that these documents aren't actively maintained by the Netdata team.
I also cleaned up the beginning of the pfSense installation procedure. I didn't implement any of the suggestions from #9499, as those are more complex and forward-thinking. Just trying to stop the short-term support issues.
area/docs
area/packaging

Add notices to FreeBSD/pfSense docs that they are community-supported

---

docs/monitor/enable-notifications.md
health/notifications/README.md
health/notifications/flock/README.md
health/notifications/prowl/README.md

Add all of our supported notification platforms to the doc about enabling notifications platforms. This will help users find the platform they're interested in without having to search. I'll keep the list updated with new ones as they become available.
As I perused these notifications docs, I also did a tiny bit of cleanup.
area/docs
area/notifications

Add supported notification platforms to docs

---

exporting/pubsub/README.md

Related: #10193
Pub/Sub exporting connector documentation

Inform users about an issue with the newest gRPC versions

---

.github/dockerfiles/Dockerfile.clang
.github/workflows/checks.yml
netdata-installer.sh

Revival of #8862, summary is the same as there.
area/packaging
New CI check introduced by first commit fails before the second commit is added.
Fixes: #8854

Fixed builds using particular versions of Clang.

---

packaging/installer/methods/kubernetes.md

Given the new structure of the [Helm repo](https://github.com/netdata/helmchart), and the fact that we have the easier-to-use Helm repo now, I changed the k8s installation doc to follow that procedure instead of cloning the repo first.
area/docs
area/packaging
Tested each of the `helm install`/`helm upgrade` examples with a EKS cluster.

Update k8s docs with new Helm repo

---

exporting/graphite/README.md
exporting/json/README.md

In #9911 there was some repeated frontmatter (multiple `sidebar_label`) that's causing some hiccups on building the Learn site. This PR fixes those errors. My bad—should have caught it in the initial PR.
area/docs
area/exporting

Fix repeated frontmatter in exporting docs

---

streaming/README.md

ssia
`streaming`
Nothing to test

streaming: fix a typo in the README.md

---

collectors/xenstat.plugin/xenstat_plugin.c

Fixes a typo
`collectors/xenstat.plugin`

collectors/xenstat.plugin: recieved => received

---

CODE_OF_CONDUCT.md

Update CoC and widen scope to community

---

collectors/python.d.plugin/oracledb/README.md
collectors/python.d.plugin/oracledb/oracledb.chart.py

Add allocated space metrics to oracledb charts

---

docs/collect/application-metrics.md
docs/collect/container-metrics.md
docs/collect/enable-configure.md
docs/monitor/view-active-alarms.md
docs/store/distributed-data-architecture.md

Fixing a few broken links and typos.
area/docs

Docs: Cleanup and fix broken links

---

.github/ISSUE_TEMPLATE/bug_report.md

fix bug_report.md syntax error

---

aclk/README.md
claim/README.md
docs/get/README.md
docs/guides/step-by-step/step-09.md
exporting/prometheus/remote_write/README.md
packaging/installer/README.md
packaging/installer/REINSTALL.md
packaging/installer/UNINSTALL.md
packaging/installer/UPDATE.md
packaging/installer/methods/packages.md

Fixes #10124
This PR aims to better document how users can reinstall Netdata in certain situations, such as when they want to enable a new feature, or if they're having trouble updating manually.
`REINSTALL.md` is fairly tightly integrated with `UPDATE.md`, and they share some instructions, but I felt like breaking them into separate documents was the most understandable way to look at this somewhat complex problem, with multiple methods.
I did some minor cleanup on a few of the packaging-related documents along the way.
area/docs
area/packaging

Document the Agent reinstallation process

---

database/sqlite/sqlite_functions.c

Remove the unused function that computes the database size. It will be reworked and added again when needed.
database
- Coverity should not complain

Address coverity errors (CID 364045,364046)

---

collectors/python.d.plugin/haproxy/README.md

Spelling
HAProxy was spelled incorrectly. 
Plugin Documentation
NA

HAProxy spelling correction

---

aclk/README.md

add privacy information about aclk connection

---

collectors/ebpf.plugin/README.md
collectors/ebpf.plugin/ebpf.c
collectors/ebpf.plugin/ebpf.conf
collectors/ebpf.plugin/ebpf.h
collectors/ebpf.plugin/ebpf_apps.h
collectors/ebpf.plugin/ebpf_process.c
collectors/ebpf.plugin/ebpf_socket.h
web/gui/dashboard_info.js

After the meeting we have today, I am bringing this PR that addresses the following issues:
- Exclude IPv6 localhost inside `ebpf.conf`
- Remove "monitoring " from `network connection monitoring`
- Instead `disable apps` use only "apps" and describe better the information. 
- Update `dashboard_info.js`.
- Regroup `eBPF` apps charts.
- Update documentation
- Add documentation inside `ebpf.conf`.
`ebpf.plugin`
1 - Compile this PR.
2 - Change `ebpf.conf` file and check that `ebpf.plugin` will respect old options and renamed options.

eBPF synchronization

---

collectors/COLLECTORS.md

Updating the supported collectors list to accurately reflect the last ~2 weeks of new collectors. I also thought we could add some information about the collectors/code that gather and visualize metrics about Netdata itself. Since there's no documentation on those (...yet), I'm just linking to code. Happy to add more if anyone knows where they reside.
area/docs

Add new collectors to supported collectors list

---

packaging/installer/README.md

SSIA
area/docs
n/a
This is supposed to go with #10261, but I forgot to add it there before merging, so it’s just a separate PR instead.

Added info about network usage requirements for the update script.

---

collectors/apps.plugin/README.md
collectors/ebpf.plugin/README.md
docs/guides/monitor/process.md
docs/guides/troubleshoot/monitor-debug-applications-ebpf.md
web/README.md

A new guide for monitoring processes by editing `apps_groups.conf` and finding the right charts in a dashboard.
I also made a few tweaks/improvements to the apps.plugin and ebpf.plugin docs along the way.
area/docs

Add guide: Monitor any process in real-time with Netdata

---

.github/workflows/docker.yml
.travis.yml
packaging/docker/build.sh

Needed to accomodate our new handling of our base and builder images.
area/packaging
Travis and GHA CI now pass for Docker builds.

Explicitly set platform for Docker builds.

---

collectors/python.d.plugin/alarms/README.md

update readme image to use one from the related netdata PR as opposed to coming from a private repo.
docs

update alarms collector readme image to use one from the related netdata PR

---

docs/guides/configure/performance.md

fix typo in performance.md

---

collectors/python.d.plugin/anomalies/README.md

add paragraph in anomalies collector README to ask for feedback
docs

add paragraph in anomalies collector README to ask for feedback

---

README.md

Quick update to mention both 1.27.0 and 1.28.0 (the hotfix).

Update main README with release news

---

health/notifications/telegram/README.md

Added one line to the Telegram documentation to make it clear which file to edit. 
Telegram

Added instructions on which file to edit.

---

collectors/ebpf.plugin/README.md

Looked like this was just a typo but the command won't work as it was written.
Docs for ebpf.plugin
Tested command in bash.

Use bash shell as user netdata for debug

---

packaging/installer/kickstart-static64.sh
packaging/installer/kickstart.sh
packaging/installer/methods/kickstart-64.md
packaging/installer/methods/kickstart.md
packaging/installer/netdata-updater.sh

They now explain the most common cause of the failures and suggest the most direct way to fix the situation.
area/packaging
n/a
Fixes: #10340

Updated messages about checksum validation failures on install.

---

docs/contributing/contributing-documentation.md
docs/contributing/style-guide.md

This PR brings lots of enhancements to the Netdata style guide. Instead of covering only documentation, this new version is designed to cover all of Netdata's writing, from docs to blog posts to the corporate website. There is now more guidance about tone/voice and particular language/grammar conventions, in addition to some more clarity about some of our Markdown "quirks."
area/docs

Update and improve the Netdata style guide

---

docs/contributing/style-guide.md

Follow-up to #10433. As I was getting ready to push the updates live to Learn, I noticed a **T/K** section I failed to complete before submitting the PR. This one finishes up that section quickly and removes unnecessary symbols from the meta description.
area/docs

Add missing section to Netdata style guide

---

README.md
docs/get/README.md
packaging/installer/README.md
packaging/installer/methods/kickstart-64.md
packaging/installer/methods/kickstart.md
packaging/installer/methods/kubernetes.md
packaging/installer/methods/macos.md
packaging/installer/methods/manual.md
packaging/installer/methods/offline.md
packaging/installer/methods/packages.md

This PR updates the links present at the bottom (the **What's next?**) section of all Netdata-supported installation methods. These pages currently all link to disparate docs that aren't part of the current focus/structure.
This should help users get to the proper quickstart to learn about relevant features and learn about `edit-config` and the Netdata config directory.
area/docs
area/packaging

Change links at bottom of all install docs

---

collectors/python.d.plugin/anomalies/README.md
docs/guides/monitor/anomaly-detection.md

The first part of a 3-part guide that walks users through setting up the anomalies collector using Nginx as an example framework. Part 2 will cover how these metrics/charts/alarms propagate through the Netdata universe, and part 3 will cover advanced custom models.
area/docs

Add guide: Detect anomalies in nodes and applications with Netdata

---

.github/CODEOWNERS

Per discussion with him and @cakrit about this.
n/a
n/a
This _should_ cover everything @vkalintiris and I discussed adding him for. If I missed something we can always add it in later though.

Add vkalintiris to CODEOWNERS for CI, packaging, and installer code.

---

.github/workflows/docs.yml
.mlc_config.json

Tolerate GitHub `429`s as hit in https://github.com/netdata/netdata/pull/10428
This upgrades the action per gaurav-nelson/github-action-markdown-link-check#75
area/ci

GitHub action markdown link check update

---

health/health.c

Remove unused struct.
CI tests.

Remove unused struct in health code.

---

health/health.c
health/health.h
health/health_json.c
health/health_log.c

Mark internal functions as static in health code.

---

docs/guides/monitor/visualize-monitor-anomalies.md

I created a specific thread in the community that i want to try direct people to so we can try collect feedback and findings from different users in one place and maybe even get some discussion going between them.

Add link to specific feedback megathread for the anomalies collector

---

collectors/python.d.plugin/am2320/am2320.conf
collectors/python.d.plugin/anomalies/anomalies.chart.py
collectors/python.d.plugin/anomalies/anomalies.conf
collectors/python.d.plugin/elasticsearch/elasticsearch.chart.py
collectors/python.d.plugin/litespeed/litespeed.chart.py
collectors/python.d.plugin/openldap/openldap.chart.py
collectors/python.d.plugin/ovpn_status_log/ovpn_status_log.chart.py
collectors/python.d.plugin/proxysql/proxysql.chart.py
collectors/python.d.plugin/puppet/puppet.chart.py
collectors/python.d.plugin/springboot/springboot.chart.py
collectors/python.d.plugin/springboot/springboot.conf
collectors/python.d.plugin/varnish/varnish.chart.py

python.d.plugin
This is split from #10521 per https://github.com/netdata/netdata/pull/10521#issuecomment-762882803

Spelling python plugin

---

collectors/python.d.plugin/postgres/README.md

Add explicit mention that the package must be available to the `netdata` user.

Update README.md on postgres collector

---

docs/configure/common-changes.md
docs/guides/configure/performance.md

I noticed a few inconsistencies and opportunities to clean up as I've been working on some new assets involving configuration.
area/docs

Make some tweaks/improvements to conf docs

---

.travis.yml
.travis/trigger_docker_build.sh

This moves the actual cURL command to a script, which both properly handles the required parameters and also checks the results of the call so that it throws an error if triggering the Docker build fails.
area/ci
Manually tested the new script to verify that it works correctly.

Properly handle arguments and responses for triggering Docker builds.

---

.travis/trigger_docker_build.sh

This should have gone in with #10545 but I forgot to commit it after testing before opening the PR.
area/ci
Same as #10545

Fixed argument handling in `.travis/trigger_docker_build.sh`.

---

package-lock.json
package.json

Fix minor vulnerability alert, by updating socket-io dependency in package-lock.json.
This change does not have any impact on the Agent, the dependency was only used for automated testing one of the node collectors.

fix minor vulnerability alert, updating socket-io dependency

---

daemon/system-info.sh

Fixes #10568 
system-info.sh
Run it on a proxmox with lxc containers (will use the user's assistance for that)

Fix container detection from systemd-detect-virt

---

README.md

Small update to the main README with the latest release.

Update latest release on main README

---

collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService.py

Fixes #10597
Raw binary data should never be printed.

Fixes #10597 raw binary data should never be printed

---

web/gui/README.md

[**Time & date picker**](#time--date-picker)

Fix typo in web/gui/readme.md

---

docs/configure/nodes.md

fix wrong link on docs Netdata Agent Daemon

---

CHANGELOG.md
collectors/COLLECTORS.md
collectors/node.d.plugin/sma_webbox/README.md
docs/guides/monitor/dimension-templates.md
docs/guides/step-by-step/step-06.md
docs/store/distributed-data-architecture.md
health/notifications/opsgenie/README.md
libnetdata/clocks/README.md
libnetdata/dictionary/README.md
libnetdata/ebpf/README.md
libnetdata/locks/README.md
libnetdata/log/README.md
libnetdata/popen/README.md
libnetdata/socket/README.md
libnetdata/statistical/README.md
libnetdata/threads/README.md
libnetdata/url/README.md

An external Ahrefs audit revealed some broken links that aren't easily alerted on by the checks we already have in place (frontmatter, in particular). This PR fixes these, and adds two new collectors to the supported collectors list in addition.
area/docs

Fix broken links in docs and add collectors to list

---

collectors/statsd.plugin/README.md
web/gui/dashboard_info.js

Add statsd definition in dashboard_info.js

Statsd dashboard

---

docs/configure/nodes.md
docs/monitor/view-active-alarms.md
docs/quickstart/infrastructure.md
docs/visualize/overview-infrastructure.md

This PR updates some of the screenshots and text that address Netdata Cloud's new navigation.
area/docs

Update screenshots and text for new Cloud nav

---

docs/monitor/view-active-alarms.md

I neglected to properly link these in #10664.
area/docs

Fix broken links in active alarms doc

---

docs/guides/monitor/kubernetes-k8s-netdata.md
packaging/installer/methods/kubernetes.md

This PR improves the docs for deploying Netdata to a Kubernetes cluster using our Helm chart. It also includes the most up-to-date instructions (updating the default Helm chart configuration) on claiming parent/child nodes to Netdata Cloud.
area/docs

Improve the Kubernetes deployment documentation

---

collectors/cups.plugin/cups_plugin.c
collectors/freeipmi.plugin/freeipmi_plugin.c
collectors/nfacct.plugin/plugin_nfacct.c
collectors/xenstat.plugin/xenstat_plugin.c
configure.ac
daemon/buildinfo.c

This will reduce the number of predefined macros and the number of different code paths in plugins.
collectors
CI  builds & tests

Remove unreachable #else directives in plugins.

---

health/notifications/email/README.md

Correct spelling is msmtp, not mstmp

fix a typo in the email notifications readme

---

collectors/statsd.plugin/README.md

Signed-off-by: odyslam <odyslam@gmail.com>
Revampt docs for statsd collector
`collectors/statsd.plugin/README.md`

Revamp statsd docs

---

docs/guides/monitor/anomaly-detection.md
docs/guides/monitor/kubernetes-k8s-netdata.md
docs/guides/monitor/visualize-monitor-anomalies.md
docs/visualize/overview-infrastructure.md
packaging/installer/methods/kubernetes.md

This PR dramatically updates the existing k8s monitoring guide to include the recently-released visualizations in Netdata Cloud.
This PR also sneaks in a few small tweaks to the pair of anomaly detection guides to remove mention of a third part.
area/docs

Update guide: Kubernetes monitoring with Netdata: Overview and visualizations

---

backends/prometheus/backend_prometheus.c

Fix typo in backend_prometheus.c

---

collectors/apps.plugin/apps_groups.conf

Add wireguard, merge WIP https://github.com/netdata/go.d.plugin/pull/461

collectors/apps.plugin: Add wireguard to vpn

---

libnetdata/libnetdata.h

Skip C++ incompatible header in main libnetdata header

---

collectors/statsd.plugin/README.md

comment out memory mode mention in example

---

.travis.yml

This fixes a few issues with the config for Travis CI that were introduced by #9964.
None of these were caught at the time because the results of these issues are only visible in nightly builds.
area/ci
n/a

Fixed Travis config issues related to new packaging workflows.

---

docs/guides/monitor/raspberry-pi-anomaly-detection.md

This PR adds a new guide for enabling anomaly detection on a Pi, plus some info about performance that users might have worried about otherwise. 
Heads up, @andrewm4894! Gave your post some quick revisions and put it into the guide formatting. 
area/docs

Add guide: Unsupervised anomaly detection for Raspberry Pi monitoring

---

web/gui/dashboard_info.js

Fix typo in dashboard_info.js

---

web/gui/dashboard_info.js

web/gui: add max value to the nvidia_smi.fan_speed gauge

---

health/health.h
health/health_json.c
web/api/web_api_v1.c

Add a `chart` parameter to `/api/v1/alarm_log`. When specified, only charts matching the parameter (to `chart` attribute) will be returned.
Health
Call `/api/v1/alarm_log`.
Test by providing none of the available parameters
Test by providing either `after` or `chart`
Test by providing both `after` or `chart`

add a chart parameter to api alarm_log

---

docs/guides/monitor/statsd.md

Add the guide for adding any StatsD data source.
`docs/guides/monitor/statsd.md`

Add statsd guide

---

health/notifications/alarm-notify.sh.in

Replaced old alarm template with the new one.
There are few small things to do:
1. We'll need also to display "Global time", in UTC:
2. i'm not sure how to fill Agent installation path, ie. in 
> sudo {/etc/netdata}/edit-config health.d/{disks.conf}
3. "Warning for 10 minutes" - needs to be dynamic. Minutes should be shortened to "m", and when numbers are big, we should probably use hours

Alerts notify template

---

.github/workflows/docker.yml
.github/workflows/packaging.yml

This fixes a bug in our CI introduced by #10776. The syntax errors technically got flagged there in CI, but nobody noticed because they aren’t required checks (that will be changing shortly).
area/ci
Manually validated the files this time.

Fix typos in GHA workflows.

---

.github/workflows/docker.yml

The list of files to indicate changes was woefully incomplete, and we want this to be a required check anyway, so we have to run it unconditionally.
area/ci
n/a

Run the Docker CI checks unconditionally instead of only when we see changes.

---

libnetdata/libnetdata.c

Call closedir to avoid resource leak
health
- N/A

Fix coverity issue (CID 367566)

---

docs/guides/monitor/statsd.md

Fix broken link in StatsD guide

---

.github/ISSUE_TEMPLATE/bug_report.md

This PR adds `##### Installation method` to the github bug template.
In addition i applied md formatting to the file.
`github`

add Installation method to the bug template

---

collectors/python.d.plugin/example/example.chart.py
collectors/python.d.plugin/example/example.conf

Small changes to add a job and some params via the `example.conf` file to the example collector. Doing this so it can be referred to in a guide being created for how to create a custom collector in python. 
collectors/python.d.plugin/example
Tested locally on development machine.

adding a default job with some params and example of additional job.

---

web/gui/dashboard_info.js

Ssia
https://github.com/netdata/netdata/blob/a714066bcc47b4a0608e7d0eb601754054d114d3/web/gui/dashboard_info.js#L1060-L1066
`web/gui`
Not needed

web/gui: make network state map sytanx consistent in the dashboard info

---

docs/guides/python-collector.md

This PR adds a new guide, written initially by a community member, about developing a custom Python collector.
@OdysLam Let's review this together at first, and fix up any loose ends, and then we'll bring in another reviewer or two.
area/docs

Add guide: Develop a custom data collector for Netdata in Python

---

netdata-installer.sh

announce `--aclk-ng` flag in installer help
installer
`./netdata-installer --help`

minor - add info about --aclk-ng into netdata-installer

---

daemon/main.h

Fix typo in main.h

---

health/health.h
health/health_json.c
web/api/web_api_v1.c

Adds a `chart` parameter to `/api/v1/alarm_log`. When specified, only charts matching the parameter (to chart attribute) will be returned.
Health
Call `/api/v1/alarm_log`.
Test by providing none of the available parameters
Test by providing either `after` or `chart` parameters
Test by providing both `after` and `chart` parameters

Add a new parameter 'chart' to the /api/v1/alarm_log.

---

health/health_json.c
web/api/web_api_v1.c

This is just to bring the feature branch up-to-date with the code on master on this specific change (Add the chart parameter to api/v1/alarm_log, merged into master with https://github.com/netdata/netdata/pull/10788).
Health
No changes should be observed.
The code has already been reviewed as part of https://github.com/netdata/netdata/pull/10788

Update if statement and formatting changes

---

docs/Running-behind-caddy.md

The documented example for Caddy does not work for version 2 due to syntax changes; here are some minor amends.

Update syntax for Caddy v2

---

health/health_log.c

Store and read back the new attributes `class`, `component` and `type` from the health log.
Health
The agent should be able to read a health db log from a previous version which does not contain these 3 attributes.

Store and read new health attributes from the health log

---

health/notifications/alarm-notify.sh.in

Change the email subject on alarm-notify.sh script. It should now read for example `CRITICAL: exporting metrics lost = 96.1 metrics, on winterland`
It also adds the `$info` variable to the `Details` part of the email.
Health

Change notifications email subject

---

packaging/scripts/test.sh

Properly handle different netcat command names in binary package test code.

---

health/notifications/alarm-notify.sh.in

Small fix to html for the `Edit this alert's configuration...` link, as suggested by @nicolasparada here: https://github.com/netdata/netdata/commit/65b81771cfb5a74c0eef43b5d2bc3834b0403cb0#commitcomment-49129571
Health/Notifications
When getting an html email alert, make sure the `Edit` word points to the correct link: https://learn.netdata.cloud/docs/agent/health/notifications#:~:text=To%20edit%20it%20on%20your,have%20one%20or%20more%20destinations

Fix edit link html
