netdata/netdata

collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py
It solves monitoring of HTTP(S) endpoints which require POST data (allows passing "body"). This approach also adds more flexibility for other purposes.
Python UrlService
N/A
=> NEW: allow additional name argument passing to urllib3 request in UrlService

collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService.py
Fixes: #5541
This PR:
- removes `setblocking` calls
```python
def setblocking(self, v):
if v:
self.settimeout(None)
else:
self.settimeout(0.0)
```
- sets socket timeout before call to `connect`
- adds separate `connect`, `read` and `write` timeouts. Default is 2 seconds for all.
> socket.settimeout(value)
Set a timeout on blocking socket operations. The value argument can be a nonnegative float expressing seconds, or None. If a float is given, subsequent socket operations will raise a timeout exception if the timeout period value has elapsed before the operation has completed. Setting a timeout of None disables timeouts on socket operations. s.settimeout(0.0) is equivalent to s.setblocking(0); s.settimeout(None) is equivalent to s.setblocking(1). …
=> SocketService: set socket operation timeout before connecting

packaging/docker/Dockerfile, packaging/docker/build.sh, packaging/docker/publish.sh
1. User more consistent shebangs
2. Do not use default values on REPOSITORY, its confusing. Just fail with a message if REPOSITORY not there
3. Do not use cache on build
4. Set the ownership to root:netdata on the whole /usr/libexec/netdata directory
Fixes #5890
=> netdata/packaging/docker: fix docker permissions and other things

collectors/python.d.plugin/Makefile.am, collectors/python.d.plugin/energid/Makefile.inc, collectors/python.d.plugin/energid/README.md, collectors/python.d.plugin/energid/energid.chart.py, collectors/python.d.plugin/energid/energid.conf, collectors/python.d.plugin/python.d.conf
Adds monitoring of Energi Core Bitcoin-derived daemon monitoring. It is named after the contributing cryptocurrency team, but targets a wide range of projects.
As there is no strict RPC standardization, there is no 100% guarantee that it will work with other forks of Bitcoin. Although, most of them should be supported and can be used with this plugin.
New Python collector module.
Smoke tested with `make dist`.
Depends on https://github.com/netdata/netdata/pull/5893
Ignore `UrlService` changed here.
=> NEW: Energi Core daemon monitoring, suits other Bitcoin forks

.travis.yml, packaging/installer/netdata-updater.sh, tests/lifecycle.bats, tests/updater_checks.bats, tests/updater_checks.sh
The aim on this PR is to attempt a small enrichment on the tests we execute during our CI testing, to guarantee stable release generation for our customers.
In brief this PR includes the following changes/additions:
1. Introduce `tests/updater_checks.bats`, use it within travis a separate job in our testing stage.
Within this BATS we basically use the stable tarball to perform a netdata install and then we use the latest tarball to perform the update.
2. We adjusted our updater script, so that we can override with a parameter the source tarball selection. We introduced variable `NETDATA_LOCAL_TARBAL_OVERRIDE` that is basically instructing the updater to use that path as TARBALL context for the update. This way we let the updater run with whatever latest code we want to verify works to …
=> Fix lifecycle script

packaging/installer/UPDATE.md
A word was duplicated in the `UPDATE.md` documentation file.
One of the duplicate got removed 
It was only a typo
=> Fixing a typo in documentation

collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py
Fixes: #5939
Power chart algorithm is missed and divisor is used as multiplier.
[/collectors/python.d.plugin/nvidia_smi](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/nvidia_smi)
=> nvidia_smi: power chart algorithm,mul,div fix

web/api/formatters/charts2json.c, web/api/formatters/charts2json.h, web/api/netdata-swagger.json, web/api/netdata-swagger.yaml, web/api/web_api_v1.c
Minor improvements for the changes in PR #5889 
web api: /api/v1/info
- Return 503 instead of 400 when netdata hasnt started yet
- Move struct definitions in .c
- swagger API documentation update
=> info API minor enhancements

collectors/charts.d.plugin/charts.d.plugin.in
It has been identified that `timeout` command used within charts.d, has different syntax on Alpine linux, thus causing failures. With this change we attempt to use make timeout command usage cross-distribution compatible.
Installed netdata within a container, started it up and confirmed from the logs that charts.d is running properly.
Logs:
```
2019-04-30 10:26:27: charts.d: INFO: main: started from '/usr/libexec/netdata/plugins.d/charts.d.plugin' with options: 1
2019-04-30 10:26:27: charts.d: INFO: main: Configuration file '/usr/lib/netdata/conf.d/charts.d.conf' loaded.
2019-04-30 10:26:27: charts.d: WARNING: main: Configuration file '/etc/netdata/charts.d.conf' not found.
2019-04-30 10:26:27: charts.d: INFO: apache: is disabled. Add a line with apache=force in …
```
=> netdata/packaging/ci:  Make timeout usage more cross-distro compliant

daemon/system-info.sh
Fixes #5950 
Adds support for Mac OS X to `system-info.sh`
daemon system info
Mac OS X doesn't have `/etc/os-release`. Use `sw_vers` to get the OS NAME and VERSION for Darwin kernels.
=> Add support for Mac OS X Name and Version

daemon/main.c
Fixes #5937 
daemon
Fix tainted string usage and warning on checking `value`.
=> Fix coverity warnings

.travis/create_artifacts.sh, .travis/draft_release.sh, .travis/generate_changelog_and_tag_release.sh, .travis/generate_changelog_for_nightlies.sh, packaging/docker/build.sh, packaging/docker/publish.sh, packaging/manual_nightly_deployment.sh
This scriptlet is responsible to generate nightly deployments on both docker and GCS for the netdata software, from any development environment that has the right access.
1. Alter docker tools to shebang with /usr/bin/env, safer to detect the right BASH (>4.0)
2. Generate script packaging/manual_nightly_deployment.sh, that runs only from TLD of netdata GIT
and provides the means to deploy to docker and GCS the latest nightly build of netdata.
Only option passed to the script is whether you want to deploy in docker, gcs or both.
Note: for GCS deployment the user has to define which bucket to update.
Note2: this tool has a hard dependency on gsutil to be properly setup on the development environment
3. Reduce the unnecessary git configs from the various scriptlets. We can just override the …
=> netdata/packaging/ci: Create manual nightly deployment tool

collectors/python.d.plugin/mongodb/mongodb.chart.py
Fixes: #5929
- `locks` not always in `server status`.
- `mapped` not always in `server status`['mem'].
[/collectors/python.d.plugin/mongodb](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mongodb)
@donets420 please test the fix
=> mongodb: various KeyError  fixes

packaging/installer/README.md
As described in this issue there are a few things wrong with the current pfsense install instructions: https://github.com/netdata/netdata/issues/3469#issuecomment-490428325
Namely the URL to the netdata package is outdated so it 404's, it now also requires python36 be installed first. The "service netdata start" command also no longer works in pfsense (must use onestart). This PR addresses all of these as well as adding a helpful little note about the configuration file location. The screenshot needed to be updated as well, for now I'm hosting the new screenshot on imgur but I imagine you would like to replace that image URL with a github hosted one, if you give me the URL I will update the PR.
=> (Docs) fix pfsense instructions

collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py
Fixes: #5978
We don't need to be specific there, just use `Exception` to catch all possible exceptions
[`/collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService`](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py)
=> UserService self._get_raw_data except fix

web/api/web_api_v1.c, web/server/web_client.c
`/api/v1/info` and `/api/v1/alarms` are very important, time-sensitive calls that shouldn't be cached. 
Also modified the headers in all cases no no-cache to the following:
```
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
```
web/server/api
=> Do not cache alarms and info api calls. Extend no-cache headers.

web/gui/Makefile.am, web/gui/dashboard.js, web/gui/src/dashboard.js/charting.js, web/gui/src/dashboard.js/charting/textonly.js
Adds a "text-only" chart renderer. The idea is that you can do something like this:
```html
<div data-netdata="system.cpu" data-chart-library="textonly"></div>
```
And it'll just show the raw value within the element. Probably worth adding more options, but this is just a basic implementation to start with.
Demo: https://d.ls/netdata/textonly-test.htm
Fixes #5578 
web/gui
=> Add "text-only" chart renderer

netdata-installer.sh, packaging/installer/functions.sh
Fixes #5474 
After investigating more carefully the issue, the only problem that needs to be fixed on the latest version is the fact that we try to install the service scripts when running within docker.
Conceptually, docker containers do not run systemd or init and our process is not possible to succeed, plus we don't need a service script within docker.
None
=> netdata/packaging: Do not install netdata service when within docker

packaging/docker/Dockerfile
Having completed https://github.com/netdata/helper-images/pull/3 to build Judy within our docker builder images, we need to pull Judy binaries in from the builder image.
This PR does exactly that and it is required, in order to merge #5282 that is actually consuming these new packages that we have built on  https://github.com/netdata/helper-images/pull/3
=> netdata/packaging: Make docker image bring onboard the required packages for the new DB

.travis.yml
I noticed the build failed last night due to the way travis pulls repository content for each job.
`git describe` failed to resolve the required information because of the insufficient repo depth when fetch (--depth=50 is by default for travis in clone command)
Not 100% sure why it didn't fail before, on that step.
The last successful cron job had an increasing number less than 50, so i can only think that depth is affecting the amount of metadata historically available, thus popped now and not earlier
None
=> netdata/packaging: Fix failing CI nightly process

health/notifications/health_alarm_notify.conf, health/notifications/slack/README.md
Fixes #6003 
Instruct users to use the "Incoming Webhooks" app, to get a webhook that can post messages to multiple channels. 
The instructions to get the webhook from https://api.slack.com/incoming-webhooks were wrong
=> Correct instructions on Slack webhooks

packaging/docker/Dockerfile
1) Do not double COPY stuff at the second layer, that does not work like that.
The right way to do it is install judy on /, then move over the folder just like we did with netdata to bring everything over with one COPY command.
2) After you do `make install` for judy, remove the stuff you bring in to make install command work for judy, we need to keep image size optimal
The image has been tested with the latest fixes from the helper-images side.
This change should be merged in AFTER we merge in helper-images fix
This PR should be merged *AFTER* https://github.com/netdata/helper-images/pull/5 has been merged and new images has been prepared.
Also Fixes #6018
=> netdata/packaging: Fix broken netdata docker image for dbengine-enabled code

docs/generator/custom/css/netdata.css
Slightly HTML docs font size to fit .md lines.
docs
The editors used to create the .md documents expect a certain number of chars to fit on every screen. The produced HTML docs take more space per line, thus breaking some lines, with a poor result.
=> Reduce HTML documentation font size

docs/generator/buildyaml.sh
Remove nl2brt mkdocs addon to get the same view in html docs as in markdown
docs
github needs two successive new lines to break a paragraph. The nl2brt mkdocs addon converts every new line to a paragraph. Remove it to get consistent views.
=> Improve paragraphs in HTML docs

.travis/create_artifacts.sh, packaging/makeself/install-alpine-packages.sh
This PR is enabling new database engine capabilities of netdata within the static binary.
On top of that there are a couple more changes:
1) fixed comments
2) Changed that weird .gitignore check with a more robust
3) Added the option to pass the desired branch to build artifacts from, defaulting being master 
netdata/dbengine
None
=> netdata/packaging: Fix makeself packaging

packaging/docker/README.md
This is part of #5583, our team is now able to test and verify docker images end to end by either taking advantage of travis infrastructure or use the tools we have developed for this purpose.
This PR includes documenting Travis CI utilisation and how people can use their personal repositories (Github - Docker) and through travis deploy a docker image and test it end to end.
Fixes #5583
=> netdata/packaging: Fine tune documentation on how to test docker images

netdata-installer.sh
1) Always install updater script under libexec, together with the uninstall script
2) When the user asks for auto-update, then just link the script to the cron directory
3) When the user hasnt asked for auto-update, make sure the cron link is removed
Added extra info along all those lines.
There was also an algorithmic cleanup, in the way we do the checks so things are clearer
Note: When user hasnt provided auto-update flag, means he doesnt want auto-update so we remove it.
The automatic run of the updater knows it has to use the flag (its saved in .environment), so we wont face problems there
Fixes #5673
=> netdata/packaging: Adjust auto-updater installation logic

packaging/installer/README.md, packaging/installer/kickstart-static64.sh, packaging/installer/kickstart.sh
It has been identified on various occasions and with PR #5953 that our kickstart visuals are broken.
Checking at the code it has been noticed that the installer visuals are broken because not all required libs are not moved into the stand-alone scripts from the functions library.
This PR attends this
netdata/packaging/installer/kickstart
Fixes user request
=> netdata/packaging: Fix kickstart/kickstart-static64 formatting bugs

Makefile.am
Fix AWS Kinesis link error when building on Mac OS
netdata/backends
Fixes #6043 
https://www.gnu.org/software/automake/manual/html_node/Program-and-Library-Variables.html
```
maude_LINK
You can override the linker on a per-program basis. 
By default the linker is chosen according to the languages used by the program. 
For instance, a program that includes C++ source code would use the C++ compiler to link. 
The _LINK variable must hold the name of a command that can be passed all the .o file names
and libraries to link against as arguments.
Note that the name of the underlying program is not passed to _LINK; typically one uses ‘$@’:
maude_LINK = $(CCLD) -magic -o $@
If a _LINK variable is not supplied, it may still be generated and used by Automake 
due to the use of per-target link flags …
```
=> netdata/daemon/backends: Fix AWS Kinesis link error

netdata-installer.sh, packaging/installer/functions.sh, packaging/installer/netdata-uninstaller.sh
1) fix add/remove user and add/remove group to handle when running on mac
2) fix uninstaller to be more portable (function declarations that wont work everywhere)
3) add some portability code in the uninstaller, for add/remove user. Previously we just attempd a blind delete for linux
4) colorize uninstaller a little bit
Fixes #5737 
Was tested on mac OS 10.14.4 and also on Gentoo, CentOS 7 and Ubuntu 1804 to catch a broad variety of distros (Changes are not so much version specific, more like distro specific)
=> netdata/packaging: install/uninstall fixes for macOS case

database/engine/pagecache.c
Fix error conditions when deleting a datafile under certain cases. Fixes #6053.
netdata/dbengine
Some pages may contain invalid timestamps for any reason (such as old buggy code). These pages need to be handled gracefully by the datafile deletion code.
=> Fix delete datafile error

database/engine/rrdengineapi.c, database/rrd.c
Fix creating chart directories when not necessary with memory mode dbengine.
Fixes #6067, Fixes #6075.
=> Fix creating chart directories when not necessary with memory mode dbengine

daemon/anonymous-statistics.sh.in
Use less info on the netdata version, to allow more meaningful reports.
Correctly send OS_VERSION_ID.
anonymous statistics
Also tried to use matomo (hence the branch name), but it doesn't support this many custom dimensions.
=> Shorten netdata version and correctly send OS_VERSION_ID

netdata-installer.sh
Fix Error message in error.log:
netdata ERROR : PLUGINSD : cannot open plugins directory '/etc/netdata/custom-plugins.d' (errno 2, No such file or directory)
=> Create missing /etc/netdata/custom-plugins.d

.travis/run_install_with_dist_file.sh, daemon/main.c
Fixes #6095 
Moved the call to send_statistics as late in the startup process as possible. Got events from all containers in the k8s cluster. It may not be enough for all Docker container startup processes, but any other solution will be much more difficult.
=> Move call to send_statistics later, to get more events from docker

collectors/python.d.plugin/python.d.conf
I think this should be "energid" because that is the name of the module and currently setting it to "no" in the config file does not turn it off.
=> Fix incorrect module name: energi

daemon/main.c, database/rrd.h, database/rrdhost.c, streaming/rrdpush.c
Fixes #6130 
Remove unecessary 2nd call of get_system_info at startup
daemon
There is no need to have a second call to the system-info.sh script.
=> Optimize calls that gather system info

health/Makefile.am, health/health.d/processes.conf
Resolves #2239
This PR adds an alarm on abnormally high number of active processes.
The thresholds are as follow (roughly 80% and 90% of max pid value):
* FreeBSD (max process number: 999999, hardcoded):
* WARNING: 80000 (clear alarm on 75000)
* CRITICAL: 90000 (clear alarm on 85000)
* Linux (default max process number: 32768, can be manually changed with sysctl, up to 2^22 on 64-bit kernels and 32768 on 32-bit):
* WARNING: 26000 (clear alarm on 25000)
* CRITICAL: 30000 (clear alarm on 28000)
The value is taken from `system.active_processes.active`, measured every 5s (should be enough to send a notification before the limit is reached unless someone launches an exponential fork-bomb). There is no alarm for Mac OS X as the macos.plugin does not seem to return `system.active_processes`. …
=> Active processes number alert

netdata-installer.sh
Fixes #6129 
Move telemetry config before netdata is restarted and fix the console message
installer
The config option --disable-telemetry was being checked after restarting netdata, which means that we would still send anonymous statistics the first time netdata was started.
The new message had the wrong format.
=> Fix telemetry config in netdata-installer

health/health.d/x509check.conf
ssia
Fixes: #5851
> Hi, my case is the first one: if something is wrong with the cert, I don't see any metric at all, and can't use it in alerting. So yes, creating an empty metric is fine, I think.
[/health](https://github.com/netdata/netdata/tree/master/health)
=> x509check: add last_collected alarm

collectors/python.d.plugin/web_log/web_log.chart.py, collectors/python.d.plugin/web_log/web_log.conf
ssia 
Fixes: #6125
> upstream_response_time may contain "," if first upstream server return error and nginx request to second server.
[/collectors/python.d.plugin/web_log](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/web_log)
=> web_log: remove trailing space from nginx_ext2 pattern

packaging/makeself/install-or-update.sh
default netdata.conf file references this dir but installer doesn't create it. Trying to get rid of the following error from /var/log/netdata/error.log
ERROR : PLUGINSD : cannot open plugins directory '/etc/netdata/custom-plugins.d' (errno 2, No such file or directory)
=> Add "custom-plugins.d" to fix error in log file

SECURITY.md
Related to #4256, this adds SECURITY.md
A follow-up PR will remove `docs/Netdata-Security-and-Disclosure-Information.md` and update the HTML generation.
docs
https://help.github.com/en/articles/adding-a-security-policy-to-your-repository
=> Properly add security policy

CMakeLists.txt, Makefile.am, daemon/global_statistics.c, database/engine/README.md, database/engine/datafile.h, database/engine/journalfile.c, database/engine/pagecache.c, database/engine/pagecache.h, database/engine/rrdengine.c, database/engine/rrdengine.h, database/engine/rrdengineapi.c, database/engine/rrdengineapi.h, database/engine/rrdenginelib.c, database/engine/rrdenginelib.h, database/engine/rrdenglocking.c, database/engine/rrdenglocking.h, database/rrd.h
Fixes #6010
The memory requirements of the new `dbengine` mode are too high. This PR drops them to about half.
=> DB engine optimize RAM usage

collectors/python.d.plugin/web_log/web_log.chart.py, collectors/python.d.plugin/web_log/web_log.conf
http://london.my-netdata.io/#menu_web_log_nginx_submenu_responses;theme=slate;help=true
fixes the bug introduced in #6138
the problem that `"-"` can be either `$http_referer` or `$upstream_response_time`
`web_log` choose wrong regexp due to `?"`
> 127.0.0.1 - - [31/May/2019:06:34:06 +0000] "GET /stub_status HTTP/1.1" 200 123 97 0.000 "-" "-"
___
autodetection algorithm should be improved
[/collectors/python.d.plugin/web_log](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/web_log)
=> web log pattern fix

packaging/installer/netdata-updater.sh
Problem reported on #6170 indicated that updater was failing to correctly identify it needs to update when a variable was incorrectly set in .environment.
To overcome this, we allow triggering the update when the variable is empty or unset.
Fixes #6170
=> netdata/packaging/installer: Fix updater issue on empty config value

health/notifications/alarm-notify.sh.in
Fixes #6178
health
Use the `date` variable filled in in a cross-platform way instead of a single `date -d` call that fails at least in MacOS (probably a lot of other OSs as well).
=> Correct date used in pushbullet notifications

collectors/python.d.plugin/README.md
MySQL is not using SimpleService, however - ceph is an example that does.
=> Documentation: Correct example list for python.d SimpleService

web/gui/tv.html
Fixes #6188 
web
Now that netdata can serve https requests, the custom dashboard example should be pointing to https://my-netdata.io.
=> Turn tv.html links to https

database/engine/datafile.c, database/engine/journalfile.c, database/engine/rrdenginelib.c, database/engine/rrdenginelib.h
Fixes #6161
Support falling back to buffered I/O when direct I/O is unavailable.
=> Support falling back to buffered I/O when direct I/O is unavailable

CONTRIBUTORS.md, collectors/apps.plugin/apps_groups.conf
Perforce Helix has a variety of [Linux server processes](http://filehost.perforce.com/perforce/r18.2/bin.linux26x86_64/) named `p4d` (server daemon), `p4broker` (broker daemon), `p4p` (proxy daemon). Under production scenarios, only one of these would likely be running on a server or container.
collectors/apps.plugin/apps_groups.conf
=> Add perforce server process monitoring

health/health.d/x509check.conf
`x509check` collector default update every is 60
> netdata ERROR : PLUGINSD[go.d] : Health alarm > 'x509check_example.site.time_until_expiration.x509check_last_collected_secs' has update every 10, less than chart update every 60. Setting alarm update frequency to 60.
Fixes: #6193
[/health/health.d/x509check.conf](https://github.com/netdata/netdata/blob/master/health/health.d/x509check.conf)
=> health: change x509check_last_collected_secs alarm every to 60s

web/gui/dashboard_info.js, web/gui/index.html
Add `wmi` collector to the `dashboard_info.js`
I wanted to use `fa-windows` brand icon, but...
so `fa-server` :smile: 	
[/web/gui](https://github.com/netdata/netdata/tree/master/web/gui)
=> wmi collector: `fa-server` icon

health/notifications/alarm-notify.sh.in
https://tools.ietf.org/html/rfc2822#section-2.2
> Header fields are lines composed of a field name, followed by a colon (":"), followed by a field body, and terminated by CRLF
I guess most clients handle it fine anyway if the threading is working, I saw it in BSD mailx which doesn't support threading.
Emails sent when alarms change state.
Introduced in https://github.com/netdata/netdata/pull/3768
=> Terminate email header lines with \r\n

libnetdata/libnetdata.h, libnetdata/socket/security.c, libnetdata/socket/security.h, libnetdata/socket/socket.c, libnetdata/socket/socket.h, streaming/rrdpush.c
Some users are reporting that they can't compile Netdata successfully when no SSL support present. The unique files that did not have any verification of the SSL were the following two files, so I changed them to fix the problem.
```
libnetdata/socket/security.h
libnetdata/socket/security.c
```
netdata/daemon
Fixes #6200
=> netdata/daemon: SSL fix - broken compilation case when ssl library not present!

collectors/cgroups.plugin/sys_fs_cgroup.c
Resolution for the cpu_limit chart was 1% as shown in #6171. It was slightly increased with this PR.
cgroups plugin
=> Increase the cpu_limit chart precision in cgroup plugin

collectors/proc.plugin/proc_mdstat.c
The total number of disks in mdstat.XX_disks chart was displayed incorrectly. As it was suggested, the total number of disks was changed to the number of disks marked "down". Now "inuse" and "down" disks are stacked correctly.
Fixes #6108
mdstat module in proc plugin
=> Fix mdstat disks chart

docs/anonymous-statistics.md
List at the end did not appear properly
docs
Added space in front of dashes
=> Visibility fix in anonymous-statistics.md

.travis.yml, health/notifications/alarm-notify.sh.in, tests/updater_checks.sh
As part of #6102 we had to introduce more cross-distribution runs, to guarantee that we don't allow failed code reaching our users.
On top of that, through #6200 we realised that our current CI infrastructure did not provide enough visibility on possible issues coming from missing package dependencies.
Until now we used our own pre-compiled docker images to run our installers, which was hiding possible issues like the one on #6200.
Hopefully  with this PR we put an end to such issues and we get closer in the cross-distro builds
References #6102
=> netdata/packaging/ci: Add lifecycle checks to bare operating system installations

daemon/main.c, web/server/web_client.c
This PR fixes style issues on a file (stray tabs while the whole file is indented with spaces).
It also attends two warnings seen during compilation, due to the fact some part of the code being hidden within ifdefs. 
netdata/daemon
=> netdata/daemon: Eliminate a couple of warnings, plus tabs removal

libnetdata/socket/security.c, libnetdata/socket/socket.c
The two files that I am doing the pull do not have the proper format that we agreed when we write C code, so I am creating this PR to fix this.
libnetdata/socket/security.c
libnetdata/socket/socket.c
PR #6212
=> SSL_fix_format Fix wrong format used with SSL!

README.md
Your use of the CNCF logo and mention of the TOC presentation create the
false impression that Netdata is a CNCF-hosted project. I would appreciate
if you accept this PR to clarify that it is not.
=> Remove CNCF logo and TOC presentation reference

packaging/docker/run.sh
During the latest fixes for the container name resolution on our  docker image, we introduced a hidden bug. Users have been creating groups with ID 999, while group ID 999 already exist on Alpine thus resulting into failing to start the docker image successfully.
To work around this problem, we make group creation failure a soft error and attempt to consume whatever group exists with the user-provided ID
Fixes #6251
=> netdata/packaging: Fix netdata/netdata docker image failure, when users passing PGID that already exists on the system

collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py
Fixes: #6248
Related: #5182, #5108
Min required version is `1.9`
> https://github.com/urllib3/urllib3/blob/master/CHANGES.rst#19-2014-07-04
> New retry logic and urllib3.util.retry.Retry configuration object. (Issue #326)
[/collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/dockerd/dockerd.chart.py)
=> UrlService: add min required version check

netdata-installer.sh
It seems that --libexecdir may deviate the expected path. 
Explicitly set this on configure, to avoid uncomfortable situations because throughout our installation we expect libexecdir to be /usr/libexec/netdata already.
There are multiple different strategies to this, but this change seems to have the smallest impact to existing installations
Fixes #6153
=> netdata/packaging: During install,  many file not found were raised

packaging/installer/functions.sh, system/netdata-lsb.in
There is a debian derivative distribution that we want to support on installing netdata service on it.
It is a non-systemd machine, thus we need to do the following for installer to work:
* Make the installer libraries aware of devuan, so that the right workflow is triggered
* Do some fixes for the netdata LSB init scriptlet, seems to be out of date. In detail:
1) Dont depend on services we may or may NOT have available for monitoring
2) Fix comments
3) Use a more standard shebang, that will provide the right bash version
Fixes #6230
=> Fix devuan support for initd

health/health.d/ram.conf
`$used_ram_to_ignore` was empty in `mem.available` health check on Linux, probably because of a namespace issue
netdata health check
I was positively surprised to see that netdata already takes ZFS arc into account when calculating available memory (:+1:) for the health check. Unfortunately the alarm did not work for me and reported the much lower `mem.available` value. I suspect it was just a namespace issue, because the check works on `mem.available` and not on `system.ram`. A quick test fixed the value for me at least.
=> Fix variable namespace in memory health check

backends/aws_kinesis/README.md
By default, AWS SDK for C++ is installed to `/usr/local/lib64`. There are Linux distributions which don't have this path as a default one for the library search. We are adding a comment to the Netdata documentation to help users install the SDK correctly.
Fixes #6002
kinesis backend
=> Add comments about AWS SDK for C++ installation

streaming/README.md, streaming/stream.conf
Fixes #6266 
docs
Update streaming documentation and config file with more info on how health enabled by default = auto works, so that users know to gracefully terminate slave netdata instances to prevent `last_collected` alarms.
=> Add more info on the stream.conf health enabled by default = auto option

docs/Performance.md
Support for single/multi-threaded server configuration was removed in https://github.com/netdata/netdata/pull/4969 (only the static-threaded server was kept), but https://docs.netdata.cloud/docs/performance/#6-use-the-single-threaded-web-server still recommends configuring it as single-threaded.
This removes the obsolete paragraph.
Documentation
=> doc: remove single/multi-threaded web server configuration

.github/stale.yml
Fixes: #6280
- change `daysUntilStale` from 45 to 30
- change `daysUntilClose` from 60 to 7
- update `markComment`
[stale bot](https://github.com/apps/stale)
=> stale bot limits update

daemon/config/README.md, health/notifications/README.md, health/notifications/email/README.md
Fixes #3433
docs
Add note for alarm-notify.sh that in certain cases it would be under a different directory.
=> Add note regarding libexecdir

database/rrdset.c, streaming/README.md
It was not clear how to name charts on a `slave` to get the correctly replicated names on its `master`.
Netdata had to be restarted to update chart names when they had been changed on the slave.
This PR updates the documentation and adds an automatic update for changed names.
Fixes #6177
streaming
=> Chart name streaming

collectors/python.d.plugin/elasticsearch/elasticsearch.chart.py
* Fix cluster_health_nodes should be area not stack because `data_nodes` is a part of `nodes`.
* Fix cluster_stats_nodes not show correct metrics.
sample raw data:
```json
"nodes": {
"count": {
"total": 10,
"data": 7,
"coordinating_only": 0,
"master": 3,
"ingest": 7
}
}
```
Python Collector
Elasticsearch module
=> fix elasticsearch plugin

collectors/cgroups.plugin/README.md, collectors/diskspace.plugin/README.md, collectors/proc.plugin/README.md, collectors/tc.plugin/README.md, daemon/config/README.md, docs/configuration-guide.md
By default, Netdata will enable monitoring metrics for disks, memory, and network only when they are not zero. We need the corresponding statements across the documentation.
Closes #5845 
documentation
=> Update the documentation on charts with zero metrics

collectors/freeipmi.plugin/freeipmi_plugin.c
Feature #6284 : do not append the sensor ID when the name is already unique.
collector/freeipmi.plugin
When deployed to any parc with different hardware, same hardware but different generation or even different bios updates, the ID of the sensors is not the same.
The sensor Name is provided by freeipmi, and can be overriden in freeipmi.conf
However, freeipmi.plugin appends the sensor ID in the displayed name. This is an issue when sending centralizing data in a backend: you'll have multiple fields like
"Inlet Temp i4" and "Inlet Temp i5" while they are the same metric, just from different hardware generations.  
Regarding implementation, I took 2 values from freeipmi source: 
```
// From libipmimonitoring/ipmi_monitoring_defs.h
#define IPMI_MONITORING_MAX_SENSOR_NAME_LENGTH      32
// …
```
=> [freeipmi] Remove id in sensor name when already unique

health/Makefile.am, health/health.d/dnsmasq_dhcp.conf
Alarm for [`dnsmasq_dhcp`](https://github.com/netdata/go.d.plugin/tree/master/modules/dnsmasq_dhcp) collector.
The alarm monitors dhcp-range utilization.
The alarm:
```
template: dnsmasq_dhcp_dhcp_range_utilization
on: dnsmasq_dhcp.dhcp_range_utilization
every: 10s
units: %
calc: $used
warn: $this > ( ($status >= $WARNING ) ? ( 80 ) : ( 90 ) )
crit: $this > ( ($status >= $CRITICAL) ? ( 90 ) : ( 95 ) )
delay: down 5m
info: dhcp-range utilization above threshold!
to: sysadmin
```
[health/](https://github.com/netdata/netdata/tree/master/health)
Test:
- i installed the branch
- checked the dashboard alarm section
Alarms are there.
___
=> dnsmasq_dhcp: dhcp-range utilization alarm

web/gui/dashboard_info.js, web/gui/index.html
This PR adds `Pi-hole` section to the [dashboard_info.js](https://github.com/netdata/netdata/blob/master/web/gui/dashboard_info.js)
- changes icon to `fa-ban`
- adds some info
[web/gui](https://github.com/netdata/netdata/tree/master/web/gui)
I installed the branch, it works w/o problem for me.
=> pihole: add to the dashboard_info

health/Makefile.am, health/health.d/pihole.conf
Alarm for [`pihole`](https://github.com/netdata/go.d.plugin/tree/master/modules/pihole) collector.
Arlarms to monitor:
- Pi-hole availability
- blocked dns queries precentage
- blocklist last update time
- gravity.list file existence
- Pi-hole blocking functionality status (on/off)
Related: #6204
[health/](https://github.com/netdata/netdata/tree/master/health)
Test:
- i installed the branch
- checked the dashboard alarm section
Alarms are there.
=> pihole collector: add alarms

libnetdata/socket/security.c, libnetdata/socket/security.h, streaming/rrdpush.c
During the talks to bring SSL to the backends, it was asked by @vlvkobal the change of name of the context used by client , because the previous name was not clear. This PR fixes this problem.
stream
Talk happened in #6220
=> Better context name to client context

collectors/python.d.plugin/adaptec_raid/adaptec_raid.chart.py
Fixes: #6337
This PR fixes `arcconf GETCONFIG 1 LD` output
old output:
```
Logical device number 0
Logical Device name                      : LogicalDrv 0
Block Size of member drives              : 512 Bytes
RAID level                               : 10
Unique Identifier                        : 488046B2
Status of logical device                 : Optimal
```
new output:
```
Logical Device number 0
Logical Device name                      : LogicalDrv 0
Block Size of member drives              : 512 Bytes
RAID level                               : 10
Unique Identifier                        : 488046B2
Status of Logical Device                 : Optimal
```
New regex is able to parse both outputs
[collectors/python.d.plugin/adaptec_raid](https://github.com/netdata/netdata/tree/master/collecto …
=> adaptec_raid: logical device regex fix

health/health.d/pihole.conf
Fixes pihole collector alarms `delay`lines , somehow i used wrong keyword.
I didn't notice the bug, because alarms were up and running, just delay option was not applied.
[/health/health.d/pihole.conf](https://github.com/netdata/netdata/blob/master/health/health.d/pihole.conf)
i tested these changes:
- installed the branch
- checked error.log
- checked alarms section on the dashboard
Delay option works correctly.
=> pihole: alarms delay fix

packaging/docker/README.md, packaging/docker/run.sh
netdata docker image does not depend on the docker binary any more.
There is a legacy implementation left in place that uses the docker binary as a fail over solution, to support older docker versions.  So we remove the reference from the documentation as this is not needed on the latest version.
At this PR, we also adding a patch top stop failures of docker container when socket ownership can't change.  Rather warn the user and let the start up continue properly.
References #6293
=> netdata/packaging/docker: Fix docker documentation and a fix to avoid failures

collectors/python.d.plugin/tomcat/tomcat.chart.py
Quick fix to replace single quotes ending content in single quote attributes in Tomcat status XML response, as it would produce an error when parsing the XML.
This is a tentative fix, a more robust approach would be to replace the single quote attributes by double quotes, but it can't be done via a simple regular expression.
Fixes #6343
`collectors/python.d.plugin/tomcat/tomcat.chart.py`
=> Tomcat status invalid XML fix

configure.ac
Netdata cannot be compiled on CentOS 6 because it has an old version of the `nfnetlink_conntrack.h` header. We should check for symbols declared in the header, not just for its existence.
nfacct plugin
=> Better checks for nfacct headers

web/gui/demosites.html
Set an html redirect to point to the new Netdata web site, hosted on Netlify.
web
=> Redirect old site to new site at www.netdata.cloud

collectors/python.d.plugin/monit/monit.chart.py
Fixes: #5074
monit module collects [monit](https://mmonit.com/monit/) service checks statistics.
These checks can be added/removed during runtime, current implementation is unable to obsolete removed service.
This PR fixes the problem.
- module mantains a list of active services
- on every iteration it checks if there are any missing services on the list
- if there are any it sets obsolete flag for the services and removes them from the charts
[/collectors/python.d.plugin/monit](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/monit)
@n0guest @ossjet
I tested the PR with py2.7, py3.5, no problem for me.
=> monit: obsolete service in runtime

collectors/apps.plugin/apps_groups.conf
This adds the `slapd` process to the default `auth:` process group configured for apps.plugin.
Debian provides openldap server as `/usr/sbin/slapd` hence this process was not detected by default.
https://packages.debian.org/stretch/amd64/slapd/filelist  
https://packages.debian.org/stretch/slapd
apps.plugin (configuration change)
=> apps.plugin: detect openldap server processes by default on Debian

health/health.c
During the implementation of the repeating alarm, it looks like there was a code movement that was not completed. This PR has been created to avoid the double free that the original code was creating.
Health.
Fix #6370
=> Health fix double Free Corruption

health/health.c
The health was not checking the size returned by fread, so it could work with less data than available. Considering that the next steps would be to parser the JSON content, this mean that it would not start correctly the SILENCERS.
Health
To test whether everything is ok, run the script to test stopping in sometime before a RESET command, stop and restart the Netdata. It cannot display the error message of the code, instead it must give the info message.
=> Health could not read properly the health silencers file

health/notifications/alarm-notify.sh.in, registry/registry_init.c
Fixes #5791 
This patch exports through netdata daemon as an environment variable the NETDATA_REGISTRY_CLOUD_BASE_URL in order for the alarm-notify.sh.in to be able to use it. Therefore we can skip the hardcoded reference to cloud URL inside the script.
registry, alarm-notify.sh.in
part of exploring the code, software usage and assessment testing
=> alarm-notify.sh should respect the cloud base url setting 

configure.ac
Old Linux kernels do not have declarations we need for `perf_event_open()`. So, we add a check for the `PERF_COUNT_HW_REF_CPU_CYCLES` macro.
Fixes #6321
perf plugin
=> Add a check for a macro declaration for the perf plugin

collectors/apps.plugin/apps_groups.conf
For Ubuntu 16.04 encountered this:
* The output for the 'ps -e' and '/proc/PID/stat' is "systemd-timesyn".
* The output for the substring mode '/proc/PID/cmdline' is "systemd-timesyn" as well
In order to check this group correctly systemd-timesyncd service has to be searched as substring with value "systemd-timesyn*"
Update apps_groups.conf
=> Update apps_groups.conf for time group

database/rrdcalc.c
The health was given wrong message when the Netdata was closed, because there was not a proper check of  the index before to clean it. This PR fix the appear of improper  "ERROR : MAIN : Cannot remove the health alarm index" that was happening when we close netdata, no less important it let more clear which index is raising errors when they really happen.
Health
=> Health giving wrong message

collectors/plugins.d/plugins_d.c
To debug the root cause of the #6371 issue we need to know more about an error on pipe close.
pluginsd orchestrator
=> Add more debug messages for pluginsd pipe errors

health/health.d/disks.conf
There were useless alerts for `/dev` and `/run` space/inode usage on a fresh Debian 9 installation. We are disabling these checks by default.
Fixes #6361
health
=> Ignore /dev and /run space/inode usage

collectors/tc.plugin/plugin_tc.c, libnetdata/libnetdata.h, libnetdata/popen/popen.c
Reimplemented mypopen() function family based on posix_spawn() instead of fork() and execl().
Fixes #6335
daemon
Reimplemented `mypopen()` function family based on `posix_spawn()` instead of `fork()` and `execl()`.
The problem with `fork()` is that if the parent process has a large address space then the `fork()` may fail due to insufficient free memory in the system if memory overcommit is not enabled.
`posix_spawn()` does not call `fork()` and does not suffer from this problem. It is also more portable than `vfork()` which is deprecated and `clone()` which is linux only.
=> Reimplemented mypopen() function family

CMakeLists.txt, Makefile.am, collectors/all.h, collectors/proc.plugin/plugin_proc.c, collectors/proc.plugin/plugin_proc.h, collectors/proc.plugin/sys_block_zram.c, web/gui/dashboard_info.js
Implemented ZRAM collector module (#2578) in ```proc.plugin```.
The module gets the ZRAM device list by reading /proc/devices, obtaining an device ID from it, then enumerating the devices in /dev filtering them by corresponding major device number it got from previous step.
It takes the data from ```/sys/block/{name}/mm_stat```.
netdata/collectors
Here is a screenshot (a bit zoomed out, but you should get the idea):
[Click me!](https://i.imgur.com/HCzrwWS.png)
My C is a little bit rusty, I hope I haven't missed something important. Feedback and criticism is very welcome :wink:
Fixes: #2578
=> ZRAM info collector module (proc.plugin)

collectors/plugins.d/plugins_d.c
Disables collection threads killed with `SIGTERM` to stop the cleanup function from attempting to kill them again.
daemon
Fixes #6190
=> Daemon fix double kills of collection threads on shutdown

web/gui/dashboard.js, web/gui/src/dashboard.js/main.js
Fixes #6384 
When generating uniqueId for the snapshot, `NETDATA.options.current.eliminate_zero_dimensions` was taken into account and in some scenarios the keys were not matching (for example when exporting the snapshot `eliminate_zero_dimensions` were always `true`). I've removed the presence of `nonzero` key, so there's no conflict now.
Also, from what I understand `All` / `Non Zero` option in "Which dimensions to show?" option should not result in different representation in charts.
=> Snapshot uniqueId fix

web/api/health/README.md
The health API documentation was missing ```  and this was not allowing to do the correct format to display information to the user.
It was also verified that we were missing some spaces after paragraphs and examples, so I am also using this PR to fix this.
Health documentation
=> Fix Web API Health documentation 

.travis.yml, .travis/package_management/common.py, .travis/package_management/configure_deb_lxc_environment.py, .travis/package_management/configure_rpm_lxc_environment.py
With this PR we attempting to fix the following two issues with RPM packaging generation:
1) It was impossible to produce the binaries prior to publishing a release, because we fetched the tarbal from the github release page (No BUG report, bumped into it when i went ahed to generate the packages and started fixing it asap)
To mitigate this problem, we took the obvious step of generating the tarball for the stable line, the same way we do for the nightlies, from the repo.  That way we decouple packaging from github releases.
2) Stable RPM package was still having the 'v' keyword which was wrong #6409 
By following the same process of nightlies for the tarball generation, it was easier to mitigate the elimination of 'v' from the generated package too.  So basically with a single change …
=> netdata/packaging: Fix RPM packaging workflow issues, plus draft changes for .DEB packaging

README.md, backends/opentsdb/README.md, docs/Running-behind-nginx.md, streaming/README.md, web/server/README.md
With TLS landing in the stable v1.16.0 release I wanted to make sure that we're being clear and as consistent as possible about the fact that we're using TLS 1.2 as the encryption protocol, not any of the obsolete SSL protocols.
The fact that "SSL" is colloquially used to refer to any encrypted web connection—it's kind of like "Kleenex" being used for any brand of tissue—complicates this a bit. In certain places I try to ease the transition with `TLS/SSL`, but in my opinion we should be consistent in using `TLS` whenever possible, as that is technically correct.
docs
I've also included some grammatical/stylistic fixes to the areas relevant to TLS.
In an ideal world, any references in configuration files are changed from `ssl` to `tls`, but that's probably a huge project without any real …
=> SSL vs. TLS consistency and clarification in documentation

docs/generator/buildyaml.sh, packaging/DISTRIBUTIONS.md, packaging/installer/README.md
Here's the first version of the packaging documentation.
Note: also added one small nit on the package dependencies that require python and we only mention it on one distribution set
Documentation
=> Netdata/packaging: Add documentation for binary packages, plus draft table for distributions support

collectors/python.d.plugin/rethinkdbs/rethinkdbs.chart.py
Fixes: #6429
There are some breaking changes in rethinkdb python driver
https://pypi.org/project/rethinkdb/2.4.0/
Before 2.4.0
```python
import rethinkdb
connection = rethinkdb.connect(db='test')
```
After 2.4.0
```python
from rethinkdb import RethinkDB
r = RethinkDB()
connection = r.connect(db='test')
```
The driver still can be used as a drop in replacement.
[/collectors/python.d.plugin/rethinkdbs](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/rethinkdbs
)
The fix:
- check if rethinkdb lib has `RethinkDB` attribute (class,was added in 2.4.0)
- use appropriate object based on check
Tests:
- [tested](https://github.com/netdata/netdata/issues/6429#issuecomment-510532874) by @sloaizav
=> rethinkdb collector new driver support

docs/generator/buildhtml.sh, docs/generator/buildyaml.sh, docs/generator/checklinks.sh
PR #6428 brought up a bug with the html build process and specifically with `checklinks.sh`. 
This PR addresses the issues will enable that PR to be tested and merged.
docs/generator
`checklinks.sh` assumed it would be executed from the root directory and need to validate the links in the file immediately under the root directory. However, that was incorrect, as the actual source files for the HTML generation were under `docs/generator/doc`. Therefore:
- Files excluded from the population of the `docs/generator/doc` directory were not properly checked. 
- Any modification/renaming of files confused checklinks.sh
- We had two cases of broken links in documents that were not caught, because of the previous reasons.
=> Fix issue with HTML docs generation

collectors/python.d.plugin/sensors/sensors.chart.py
Fixes: #6462
List of allowed chip names is not gathered from the module configuration file in `init()`.
https://github.com/netdata/netdata/blob/b548214e35454cd1a4f36cd3fa39703b2c270e50/collectors/python.d.plugin/sensors/sensors.conf#L48-L55
[collectors/python.d.plugin/sensors](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/sensors/sensors.chart.py)
The fix:
- get list of allowed chip names in `init()`
Tests:
- i tested the fix, it works
=> python sensors collector: sensor chips filtering fix

docs/generator/buildyaml.sh
The little book icon on the top-left of the documentation, left of `Netdata Documentation`, links to `docs.netdata.cloud/streaming` instead of the docs root for some very, very strange and silly reason. I found this out quite randomly just a few moments ago.
I added a `site_url` to the mkdocs config to make sure it links to `docs.netdata.cloud` and stops sending our poor users over to the streaming page.
docs
I guess this will [break](https://github.com/mkdocs/mkdocs/issues/1414) the `mkdocs serve` feature, but I never could figure that out anyway. :man_shrugging:
=> Stop docs icon from linking to streaming page instead of docs root

docs/README.md, docs/generator/buildyaml.sh, docs/generator/custom/css/netdata.css
I've been trying to improve the look and feel of the docs here and there in all my different WIP branches and decided it was finally time to put them all together.
- Move away from the `highlight` plugin and to the `pymdownx.highlight` plugin, as the latter is better supported and doesn't do weird things with inline code blocks.
- Add some padding to the bottom of each page.
- Change the colors to grey and green to better match our new site (it's not perfect but it's way closer than the blue).
- Add a `docs/README.md` file to direct people toward the docs site.
- A few CSS tweaks to make things look nicer.
docs
=> Styling improvements to documentation

README.md, packaging/installer/README.md
Fixes #6366. Clarifies that by default, when using kickstart scripts, users should append `--stable-release` so that they get automatic updates for major releases only, not nightly updates.
docs
This covers the `kickstart.sh` and `kickstart-static64.sh` scripts, but not manual installations, Docker installations, or other OSes. In order to update those I'll need some verification that users can append the `--stable-release` and it'll work as intended. And I'm not yet sure how to pass options to Docker containers, so we'll need to clarify that when someone can help fill me in.
=> Change default installation to stable in documentation

daemon/anonymous-statistics.sh.in
There was no functional reason to write the environment variables in `/tmp/as.log` and it was breaking the script if the permissions did not allow it. Removed the entire section.
Telementry - anonymous statistics
=> Stop anonymous stats from writing log in /tmp

README.md, collectors/apps.plugin/apps_plugin.c, packaging/docker/README.md
When Netdata runs inside a container, it can't display correct names for "User" and "User Groups" sections. That is because Netdata uses `getpwuid()` and `getgrgid()` functions, which get local user and group names, while we want to monitor processes outside the container.
We will read `/etc/passwd` and `/etc/group` files and fall back to `getpwuid()` and `getgrgid()` only if the files can't be read. To read the host files from the container the `/etc` folder should be mounted with the `-v /etc:/host/etc:ro` option.
Fixes #5585
apps plugin
=> Get user and group names from files 

system/Makefile.am
As part of #6165, we faced an issue with mac OS installation where edit-config file was havint the wrong variables setup.
After deep investigation on the way Formulae was building netdata, we realized that generated edit-config was delivered
together with the generated edit-conf, thus resulting on not re-creating it with the right variables.
So the fix here is to not deliver edit-config with the distribution tarball, so that it gets generated as it should
Fixes #6165
=> netdata/packaging: Do not deliver edit-config as part of the distribution tarball

health/notifications/alarm-notify.sh.in, health/notifications/health_alarm_notify.conf
Fixes https://github.com/netdata/netdata/issues/6458
Email alarms notifications
To enable the functionality add `EMAIL_PLAINTEXT_ONLY="YES"` in `health_alarm_notify.conf`
=> Add support for plain text only emails

docs/generator/buildhtml.sh
Links in Mandarin docs home page would lead back to the English site after PR #6428 
docs
The PR to add a new docs homepage included a difficult to avoid hack during the docs html generation process, that involved copying an index.html from a subdirectory to the root of the tree. The links for the left navbar are relative, so they all contained '../'. This worked fine for the English docs site, since we were already at the root directory and there was no upper directory to go. But for the `/zh/index.html` , it had the effect of sending us back to the English site. 
Replaced the copy with a sed to fix it. Also modified an `=` to a `==` in an `if` condition.
=> Fixed broken left navbar links in translated docs

docs/Running-behind-haproxy.md, docs/generator/buildyaml.sh
Add a documentation page for running netdata via HAproxy. The example includes: 
* A simple configuration over http 
* A more complex example over https 
* Instructions on how to use HTTP authentication 
* A full configuration example 
docs
Fixes #6446
=> Add netdata haproxy documentation page

collectors/python.d.plugin/mongodb/mongodb.conf
Fixes: #6512
There is a wrong keyword in the `authsample` job in the module configuration file
https://github.com/netdata/netdata/blob/fb49bb93a9195bf09bcf2e58f5fde7af428d5ad1/collectors/python.d.plugin/mongodb/mongodb.conf#L86-L92 
Correct keyword is `pass`.
- config file
https://github.com/netdata/netdata/blob/aaf31295c35f790ebb3880b3f94cd787213ab98b/collectors/python.d.plugin/mongodb/mongodb.conf#L69-L72
- code
https://github.com/netdata/netdata/blob/fb49bb93a9195bf09bcf2e58f5fde7af428d5ad1/collectors/python.d.plugin/mongodb/mongodb.chart.py#L422-L429
- [readme](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mongodb#configuration)
[collectors/python.d.plugin/mongodb](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mongodb)
=> mongodb: change `password` to `pass` in the module config

collectors/apps.plugin/apps_plugin.c, collectors/cgroups.plugin/cgroup-network.c, collectors/statsd.plugin/statsd.c, configure.ac, database/rrddim.c, database/rrdvar.c, libnetdata/locks/locks.c, libnetdata/socket/security.c
This pull request comprises eight commits
This updated pull request obeys the coding style and converts tabs to spaces.
Updated again for coding style consistency with surrounding code.
configure.ac: Add support for GCC's __attribute__((unused))
collectors/statsd.plugin: Mark a function argument as __maybe_unused
collectors/apps.plugin: Mark a function argument as __maybe_unused
libnetdata/locks/locks: Mark function arguments as __maybe_unused
libnetdata/socket/security: Mark a function argument as __maybe_unused
collectors/cgroups.plugin: Mark a function argument as __maybe_unused
database/rrddim: Mark function arguments as __maybe_unused
database/rrdvar: Mark a function argument as __maybe_unused
I like compiling with -Wall and -Wextra to catch various classes of potential problems. …
=> Make use of GCC's __attribute__((unused))

docs/generator/custom/css/netdata.css
I realized that in a previous PR for styling fixes for the docs that when I used CSS to hide `md-nav__title` in left-hand navigation menu, it also inadvertently hid various essential items in the mobile navigation. With `md-nav__title` set to `display: none`, you can't navigate up a level in the navigation.
In this PR, the element I want hidden is only done on wide screens when the mobile nav is not active.
**Current**:
*Top level*
*One level deep*
**Restored in this PR**:
*Top level*
*One level deep*
docs
I also added an underline to links in the body of docs to make them stand out a bit better, per @cakrit's comment.
=> Documentation navigation fix

web/gui/main.js
After logging via clicking `Nodes`, user should be redirected to `console.html`. Because it was hard to detect it in the `message` that cloud generates, i decided to add a separate param to the cloud window url. This param is passed through and (after sign in) returns to `handleSignInMessage`
main.js (Dashboard)
Fixes #6542
=> redirect after clicking Nodes > SignIn

packaging/installer/README.md
When I deployed the new text about nightly vs. stable versions of Netdata, I failed to remove the old text from the 64-bit static binary section of the installation page. I've replaced that with the new boilerplate about nightly vs. stable releases and a link to the section that explains it more.
docs
=> Docs: Remove text about nightly version

web/server/web_client.c, web/server/web_client.h
Just a minor code cleanup for better readability of code that I didn't want to include in UTF8 URL parser PR due to IMHO being unrelated
libnetdata/server
No behavior change. Just code readability - something that annoyed me a bit when I was going trough code. *(not all people keep all the codes in memory (besides 200/400/404))*
Additionally one compiler warning fixed if compiling with `-Wpointer-sign`
=> minor - code readability HTTP CODES as defines && clear warnings

collectors/cgroups.plugin/cgroup-name.sh.in, packaging/docker/Dockerfile, packaging/docker/README.md, packaging/docker/build-test.sh, packaging/docker/run.sh
The current method of getting Docker container names is risky and non-standard. This is documented in #5680 and #6293. This new diff will allow a safer method of querying as well as allow the user of a proxy between the docker socket (as described on #5680).
There is one issue I encountered when testing. For some reason, when I run the application configured to access `/var/run/docker.sock`, I'm seeing `curl: (7) Couldn't connect to server`. However, if I run the plugin directly via `docker exec`, it works perfectly. Eg: `/usr/libexec/netdata/plugins.d/cgroup-name.sh docker_a1c9bbf558a66841ba5b9b465ee3d6e9f6369cab6423e2fd8fb2a931e0adc407`
I'm not sure if there is some other complication due to how the script is being executed, but any pointers on where to go to resolve that would be …
=> Safer container names

netdata-installer.sh, packaging/installer/netdata-updater.sh, packaging/makeself/jobs/70-netdata-git.install.sh
Since we already ship netdata-updater.sh with our static64 installer, all that is left is to make sure that the updater can handle the proper update of a static installation with the latest version.
This change introduces the necessary artifacts that gets us there.
In simple words, the updater becomes aware of the installation type (static or not) and then with minor adjustments we just execute a different type of install process.
Fixes #4122
=> netdata/packaging: Adopt netdata-updater to run properly for static64 installations.

.travis.yml, .travis/check_changelog_last_modification.sh
Throw a notification when changelog generation gets too old.
It is a soft error, but we do want to know about it
netdata/ci
None
=> netdata/packaging: Notify us when CHANGELOG.md gets too old

netdata-installer.sh, packaging/installer/UNINSTALL.md, packaging/installer/netdata-updater.sh
1) Introduce NETDATA_LIB_DIR within environment file, we are going to need to refer to it
2) move NETDATA_TARBALL_CHECKSUM to /netdata.tarball.checksum
3) Make sure you support transitional period, which means load and remove the variable from the old location then move it to the new one
Fixes #6550
=> netdata/packaging: Move tarball checksum information into lib dir of netdata

collectors/python.d.plugin/smartd_log/smartd_log.chart.py
`smartd_log` does `cleanup` every 60 seconds, during cleanup it removes inactive disks (last update time > 30min) from the list of monitored disks and from charts.
Module uses [`hide_dimension`](https://github.com/netdata/netdata/blob/2f7962c9e154dcce1684f2275387c9b6ac4d0b4c/collectors/python.d.plugin/python_modules/bases/charts.py#L214-L220) function. The function doesn actually obsolete dimension.
This PR changes `hide_dimension` to [`del_dimension`](https://github.com/netdata/netdata/blob/2f7962c9e154dcce1684f2275387c9b6ac4d0b4c/collectors/python.d.plugin/python_modules/bases/charts.py#L203-L212). `del_dimension` sets dim `obsolete` flag.
[collectors/python.d.plugin/smartd_log](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/smartd_log)
Tests:
- i tested it, …
=> smartd_log: use `del_dimension` instead of `hide_dimension` to delete inactive disks

collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService.py, collectors/python.d.plugin/unbound/unbound.chart.py
This adds an explicit check for the case of a socket that's already
disconnected and skips logging an error message.  The conditionn
technically is an error, but it's one that we can recover from trivially
by just doing nothing in this case (we were trying to disconnect the
scoket anyway, so if it's already disconnected, we don't need to change
anything).
This uses Python's `errno` module so that we can detect this situation
in a system-agnostic manner.
collectors/python.d
Fixes #6434
-----
@ilyam8 I'm of the opinion that this check should probably just go into the `SocketService` base class instead of being an as-needed thing in specific modules.  I honestly can't think of any case where a socket being disconnected as reported in #6434 would be an actual error in the disconnect method …
=> Handle disconnected sockets in unbound collector.

tests/urls/request.sh.in, web/server/web_client.c
The netdata has a random error to allocate memory in some requests according with outputs  we were receiving from our demo server.
After to check the valgrind output, it was possible to verify that the malloc error could happen steps before due a set of values in an address NULL. This pull request fixes this checking the existence of a valid address before to set the value.
web/ url parser
It fixes #6582
=> Fix crash in malloc

configure.ac
Fix configure.ac allowing deprecated LZ4 library call.  Fixes #6580
Previously it was possible for older versions of LZ4 libraries to succesfully pass the ./configure phase of the build process even though they shouldn't.
By requiring the most recent API call of LZ4 that is being used by netdata, which is LZ4_compress_default(), we eliminate the risk of a false positive LZ4 flag in the ./configure phase of the build.
As a result, any system with a deprecated LZ4 library will build netdata without LZ4 support (and subsequently without dbengine support).
=> Fix configure.ac allowing deprecated LZ4 library call

collectors/python.d.plugin/mongodb/mongodb.chart.py, collectors/python.d.plugin/mongodb/mongodb.conf
Fixes: #5884, #6464
The PR adds ssl connection support to the `mongodb` python collector.
Ref: https://api.mongodb.com/python/current/examples/tls.html#certificate-verification-policy
Following config options were added:
```yaml
ssl: yes                             # connect to the server using TLS
ssl_cert_reqs: yes                   # require a certificate from the server when TLS is enabled
ssl_ca_certs: '/path/to/ca.pem'      # use a specific set of CA certificates
ssl_crlfile: '/path/to/crl.pem'      # use a certificate revocation lists
ssl_certfile: '/path/to/client.pem'  # use a client certificate
ssl_keyfile: '/path/to/key.pem'      # use a specific client certificate key
ssl_pem_passphrase: 'passphrase'     # use a passphrase to decrypt encrypted private keys
``` …
=> mongodb: ssl connection

collectors/python.d.plugin/mysql/mysql.chart.py
Fixes: #6353
Ref: https://dev.mysql.com/doc/refman/8.0/en/replication-channels.html
> To provide compatibility with previous versions, the MySQL server automatically creates on startup a default channel whose name is the empty string (""). This channel is always present; it cannot be created or destroyed by the user. If no other channels (having nonempty names) have been created, replication statements act on the default channel only, so that all replication statements from older slaves function as expected
> SHOW SLAVE STATUS reports the status for all channels, except the group_replication_applier channel.
___ 
As we can see in https://github.com/netdata/netdata/issues/6353#issuecomment-507095714
`SHOW SLAVE STATUS` returns several rows, one row per replication channel.
Before this PR: …
=> mysql collector: slave_status charts per replication channel

packaging/installer/functions.sh
Fixes #6601 
Basically we do not want to enable netdata, if it was previously disabled
netdata/installer
None
=> netdata/installer: do not enable netdata, if it was previously disabled

collectors/python.d.plugin/mysql/mysql.chart.py
Fixes: #6616
bug was added in #6597
MySQLService removes query itself in  case of error
https://github.com/netdata/netdata/blob/66d6498ed4fa433fdd397da5ef1470312e539bd6/collectors/python.d.plugin/python_modules/bases/FrameworkServices/MySQLService.py#L144-L151
[/collectors/python.d.plugin/mysql](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mysql)
=> mysql: do not remove `slave_status` from queries in module

daemon/system-info.sh
Better system OS detection for RHEL6 and Mac OS X
Fixes: #6608
system-info.sh
RHEL6 has `/etc/lsb-release` file that contains something like:
```
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
```
so only output from `lsb_release` command contains something useful:
For Mac OS X i made some trimming for strings so they don't contain additional white chars anymore.
=> Better system OS detection for RHEL6 and Mac OS X

.travis.yml
Remove 'sudo: true' from .travis.yml because it has been deprecated
.travis.yml
According to the following blog post, the 'sudo: true/false' setting in .travis.yml has been deprecated:
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
Some more information can be found here as well:
https://changelog.travis-ci.com/linux-builds-run-on-vms-by-default-77106
Also a test build with all stages and jobs can be found here:
https://travis-ci.org/knatsakis/netdata/builds/569643721 (There are some failures, but they are not related to the sudo change as far as I can tell).
=> .travis.yml: Remove 'sudo: true' as it is now deprecated

collectors/python.d.plugin/spigotmc/spigotmc.chart.py
* Fix spigotmc plugin can't reconnect.
* Prior to this, the connection will continue to try to reconnect when it is normal.
* After the connection is interrupted, it will not try to reconnect.
* Improve the compatibility of spigotmc plugin player count check
* Previously, the color output would give the wrong result.
* And does not support counting the number of invisible players.
collectors/python.d.plugin/spigotmc/
For the new regular, you can test with the following code:
```python3
import re
r = re.compile(r'[^§](\d+)(?:.*?(?=/).*?[^§](\d+))?', re.X)
m = r.search('§6当前有 §c2§6 个玩家在线,最大在线人数为 §c50§6 个玩家.')
(m.group(1), m.group(2))
m = r.search('§6There are §c2§6/§c1§6 out of maximum §c50§6 players online.')
(m.group(1), m.group(2))
m = r.search('§6There are §c2§6 / §c1§6 out of maximum …
```
=> fix spigotmc plugin bugs

README.md
I made some small cosmetic fixes for typos, especially additional space or missing dot in: README.
=> Fix typos in: 'README.md' file.

collectors/python.d.plugin/riakkv/README.md, docs/generator/checklinks.sh
Accept syntax of markdown links that encapsulates links inside '<>'. 
docs generator
Strips the '<>' from the link before applying the logic.
=> Accept <> around links in markdown

packaging/installer/README.md, packaging/installer/kickstart-static64.sh, packaging/installer/kickstart.sh
One of our users reported an issue occurring with our kickstart installer, when it is executed with a non-privileged user.
Our kickstart has the capability to selectively run commands with sudo where needed, when the user executing kickstart is not root.
During the end of the execution, we had a set of commands that were not executed with sudo and were masked to hide the failure, thus only resulting on a non-zero exit code of the script execution when user is not root.
This PR mitigates this problem and helps cleaning up after installation properly.
Fixes:
1) Make sure we always have a proper TMPDIR variable
2) Make sure we use sudo variable on the deletions 
3) Guard deletions for the cases we shouldn't be deleting anything (for example when /tmp is the TMPDIR)
netdata/installer
Fixes …
=> netdata/installer: Fix error running kickstart as a non-privileged user

tests/Makefile.am
After some merges the Makefile inside tests had garbage messages, this PR is removing the git lines from it.
Tests
Thanks @mfundul !
=> Remove texts inside tests/Makefile

configure.ac
As part of the gentoo overlay creation, we bumped into an interesting compilation problem on SSL.
During investigation i realised that the and/or condition mix that checks for SSL libs when dbengine or https is enabled, didn't work as expected.
Beats me why we didn't notice this earlier, it could be because on packaging we rely on auto-detection and probably this is not raised then.
netdata/https
netdata/dbengine
Fixes #6669
=> netdata/packaging: separately identify dependency resolution for HTTPS and DB engine

.travis/package_management/common.py, contrib/debian/rules, netdata-installer.sh, netdata.spec.in
As part of #6666 we had to go through the configure process across all distributions channels and evaluate the behaviour of our end to end build systems.
It seems that we are in need to align libdir option in our configure command, so that we can guarantee consistent layout of our installation across all distributions.
None
=> netdata/packaging: Align libdir in all configure commands

database/rrdvar.c, health/health.h, web/api/formatters/json_wrapper.c, web/api/formatters/rrdset2json.c, web/api/netdata-swagger.json, web/api/netdata-swagger.yaml, web/api/queries/rrdr.h, web/api/web_api_v1.c
Implements feature #6054 
Now requests like 
http://localhost:19999/api/v1/chart?chart=example.random
http://localhost:19999/api/v1/data?chart=example.random&options=jsonwrap&options=showcustomvars
- return chart variables in their responses. Chart variables include only those with options set to RRDVAR_OPTION_CUSTOM_CHART_VAR
- for /api/v1/data requests chart variables are returned when parameter options=jsonwrap and options=showcustomvars
[/database](https://github.com/netdata/netdata/tree/master/database/)
[/web/api/formatters](https://github.com/netdata/netdata/tree/master/web/api/formatters)
To test functionality the collectors/python.d.plugin/example chart has been configured to have the following variables:
```python
CHARTS = {
'random': {
'options': [None, 'A random number', …
```
=> Add alarm variables to the response of chart and data (#6054)

.travis.yml, packaging/docker/build.sh, packaging/docker/publish.sh
Build docker images for the four supported architectures in parallel, in order to minimize the time needed.
.travis.yml
You can find test builds here:
https://travis-ci.org/knatsakis/netdata/builds/572437353
and here:
https://travis-ci.org/knatsakis/netdata/builds/572439557
Please, also find test docker images and manifests here:
https://cloud.docker.com/repository/registry-1.docker.io/knatsakis/netdata/tags
Also, let me mention that, I had to change the manifest updating logic a bit in order to accommodate a parallel build. Instead of always creating a manifest list of the four architectures, the packaging/docker/publish.sh script now:
1. Checks the currently uploaded list of tags for the current version
2. Creates a manifest list containing the discovered tags only
The …
=> .travis.yml: Build docker images in parallel

health/health.h, health/health_json.c, web/api/netdata-swagger.json, web/api/netdata-swagger.yaml, web/api/web_api_v1.c, web/api/web_api_v1.h
This is implementation of a prerequisite for the requested feature #6536 (Generate an overall status badge/chart for the health of category)
web/api/
health/
Command line used for testing and response format:
curl "http://localhost:19999/api/v1/alarm_count?context=system.cpu,system.ram&status=clear"
[4]
curl "http://localhost:19999/api/v1/alarm_count?context=system.cpu,system.ram&status=undefined"
[1]
curl "http://localhost:19999/api/v1/alarm_count?status=critical"
[0]
curl "http://localhost:19999/api/v1/alarm_count"
[0]
=> Add alarm status counter api call

backends/backends.c, daemon/unit_test.c, database/README.md, database/engine/README.md, database/engine/pagecache.c, database/engine/pagecache.h, database/engine/rrdengine.c, database/engine/rrdengineapi.c, database/engine/rrdengineapi.h, database/engine/rrdenginelib.h, database/rrd.h, database/rrddim.c, web/api/queries/average/average.c, web/api/queries/query.c, web/api/queries/rrdr.h
Fixes #6254 
Fixes #6255
Fixes #6487
Fixes #6573
Variable Granularity support for data collection in netdata.
daemon
database
web
backends
Allow users to change data collection frequency of metrics without:
- deleting older chart data
- invalidating existing alarm data
- affecting streaming
- invalidating web server data queries of older data
- affecting backends
=> Variable Granularity support for data collection

.gitignore
Signed-off-by: Katharina Drexel <katharina.drexel@bfh.ch>
adding system/netdata.conf in the .gitignore file instead of netdata.conf
.gitignore
When building a netdata debian package there are config files under debian/local. Excluding only "netdata.conf" in .gitignore is a nuisance because elementary config files will be missing and the package won't build. Full paths will prevent build errors.
=> exact path to netdata.conf in .gitignore

collectors/plugins.d/plugins_d.c
Today when I compiled Netdata using netdata-installer.sh, I notice that there was the following warning:
`
collectors/plugins.d/plugins_d.c: In function 'pluginsd_process':
collectors/plugins.d/plugins_d.c:271:29: warning: 'readfrom' may be used uninitialized in this function [-Wmaybe-uninitialized]
271 |                 readfrom =  pluginsd_get_from_buffer(line, &bytesleft, readfrom, host->ssl.conn, tmpbuffer);
|                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`
I am creating this PR to remove the warning from the compilation process.
Collectors
=> Netdata-installer warning removed

web/server/web_client.c
With the recent changes on URL parsing, we caused an issue in the registry. Requests were not being logged, so the counters remained the same. The reason was that we modified the request buffer and the daemon couldn't access the cookie required to store the info.
After @cosmix review, I notice that there was a code that is not necessary on Netdata. I executed tests with the stress.sh and urls/request.sh scripts, this last I used  during 4 hours with cron calling it each hour.
@paulkatsoulakis is it possible we test this specific PR in a computer where the registry is with wrong count? I am not sure yet that this can fix the problem discovered.
web server
A proper buffer is shown below
```
v1.16.0 w->response.data->buffer = "GET /api/v1/registry?action=access&machine=7e972e74-19a7-11e9-9c78 …
```
=> Remove of unecessary NULL web server

web/gui/dashboard.css, web/gui/dashboard.js, web/gui/dashboard.slate.css, web/gui/main.js, web/gui/src/dashboard.js/charting/dygraph.js
Fixes #6587 
Changed the note in sidebar - grammatical fixes and added history tip with links
Also added "sticky" note on the left side of Dygraph Plot
here's how it looks when it's clipped:
I haven't used any special styling for text formatting. The text if centered vertically, and it's 25 pxs on the left from first point in the chart, there is no additional background for that block. Please let me know if you need some more styling tweaks.
I saw that `history` in description here: https://github.com/netdata/netdata/issues/6587#issuecomment-522661131 was formatted as `code`, @joelhans is it ok if i use **bold** instead? There's bold in other places in dashboard.
The "sticky note" is added manually, i was experimenting with issues provided by Dygraph, but they were not a good match: …
=> History tips

.travis.yml
Change .travis.yml so that the script packaging/docker/check_login.sh can cause the build to fail promptly (Publish for release & Nightly release stages).
.travis.yml
I believe that packaging/docker/check_login.sh was meant to cancel the release build if the credentials are wrong. But currently the build keeps running even if check_login.sh fails.
With the current .travis.yml, this is in accordance with the [documented](https://docs.travis-ci.com/user/job-lifecycle#customizing-the-build-phase) behaviour:
> When one of the build commands returns a non-zero exit code, the Travis CI build **runs the subsequent commands as well**, and accumulates the build result.
This PR makes the check_login.sh failure to fail the build promptly.
You can find before and after test builds here: …
=> .travis.yml: packaging/docker/check_login.sh can cause the build to fail

packaging/makeself/install-or-update.sh, packaging/makeself/makeself-header.sh
As per the #6692 issue, it has been identified that a BUG exists on the static installation regarding the preservation of existing configuration files when the installer runs for the second time.
After investigating the scenarios, it seems that the static installer was always re-creating the folder structure, thus resulting into always having a clean installation of netdata regardless of any customisations a user may have done in the config folder.
With this PR we attempt to mitigate the issue by touching two places:
1) Initial entry point script of makeself, to trigger the back-up of the configuration folder if it already exists
2) Adjust the install or update scriptlet and make it reinstate the existing folder and also trigger stock config files clean up (if the files weren't modified) …
=> netdata/installer: fix static64 installer always overwriting configuration

.gitignore, coverity-install.sh, coverity-scan.sh
`./coverity-scan.sh` should be easily usable by hand.
Prior to this PR, developers should remember to export certain variables (`REPOSITORY` and `COVERITY_SCAN_SUBMIT_MAIL`). They were given to option to configure `COVERITY_SCAN_TOKEN` and configure the path of the `cov-build` by configuring separate files for each of them. So, a developer was not able to just configure its environment and then just run the script every time it is needed.
This PR allows devs to create the file `.coverity-scan.conf` with the following information:
```sh
REPOSITORY="netdata/netdata"
COVERITY_SCAN_SUBMIT_MAIL="you@example.com"
COVERITY_SCAN_TOKEN="TOKEN taken from Coverity site"
COVERITY_BUILD_PATH="/opt/cov-analysis-linux64-2019.03/bin/cov-build"
COVERITY_SUBMIT_DEBUG=1
```
The script is also updated to …
=> make coverity-scan.sh usable by hand

collectors/apps.plugin/README.md, collectors/apps.plugin/apps_plugin.c
Update the documentation in order to make clear that additional command-line options are available for apps plugin.
Fixes #6708
documentation
=> Add command-line option descriptions for apps.plugin

.travis.yml
We had to move our CI process on the newer ubuntu distribution, which resulted on different needs on the packaging pipeline.
Adding this dependency should fix the errors on packaging
I also added the packages on the RPM template
netdata/ci
=> netdata/packaging: Add python3-lxc dependency

.travis/generate_changelog_for_release.sh
Travis build for release fails while generating changelog, due to the number of issues. Increased the minimum tag taken into consideration.
CI/CD
=> Increase minimum release for changelog

.travis/generate_changelog_for_release.sh
Make release changelog same as nightly changelog, skipping the issues. 
CI/CD
Changelog generation takes too long and errors during releases, because the issues shouldn't be added (too many requests to github).
=> Skip issues from release changelog

.travis/generate_changelog_and_tag_release.sh
Changelog generation keeps failing in the release publishing, removing it from the process. Nightlies will generate it again.
CI/CD
=> Remove changelog generation from release, as it keeps breaking

web/api/badges/web_buffer_svg.c, web/api/exporters/allmetrics.c, web/api/exporters/allmetrics.h, web/api/formatters/rrd2json.c, web/api/formatters/rrd2json.h, web/api/health/health_cmdapi.c, web/api/web_api_v1.c, web/server/web_client.h
When we merged an PR in the last sprint, Netdata has a new pattern for the file web_client.c, every time it returned an HTTP error, it did not have explicit the error number, the codes was changed for the error name, but this was not carry for all the Netdata web files. This PR fixes this creating again one unique pattern to give the error.
Web
Fixes #6559
=> HTTP response message

libnetdata/threads/threads.c
When calling netdata_thread_create, you can provide a tag to identify
the thread in the error message
This patch uses this tag to rename the thread if supported by the
pthread distribution to allow better identification of the thread.
This have helped identify the bug #6741
Sample output:
```
ps -L -o tid,pid,comm,args -p $(pgrep netdata)
TID   PID COMMAND         COMMAND
5123  5123 netdata         ./netdata -D
5133  5123 PLUGIN[proc]    ./netdata -D
5134  5123 netdata         ./netdata -D
5135  5123 PLUGIN[cgroups] ./netdata -D
5136  5123 netdata         ./netdata -D
5137  5123 STATSD          ./netdata -D
5138  5123 BACKENDS        ./netdata -D
5139  5123 netdata         ./netdata -D
5140  5123 PLUGINSD        ./netdata -D
5141  5123 netdata         ./netdata -D
5142  5123 HEALTH …
```
=> [libnetdata/thread] Set thread name from tag

.travis/package_management/configure_deb_lxc_environment.py, contrib/debian/control.buster
On debian/buster, there is a different library available for protoc runtime
Fixes #6774
=> netdata/packaging: override control file for debian/buster

.travis/package_management/trigger_deb_lxc_build.py
We bumped into an error that caused debian/jessie package generation to fail.
When building stable release, we don't properly detect the change from previous stable to this one.
So the changelog generation fails and only on some distros causes the process to fail.
With this change we attempt to detect this peculiarity and just try fo decrease latest release version, to properly fetch the full changes
References #6774
=> netdata/packaging: fix changelog generation failing the build

netdata.spec.in
This is to work around the build failure for rhel 6/7 over the go.d binary installation
We basically fool the process by removing the executable permission at install time.
This way end result will remain the same but build won't fail since the system won't try to do anything with the binary
It has been manually tested on a build system.
End result binary has the execute permission after this
```
[builder@netdata-builder03 ~]$ rpm -qp --dump rpmbuild/RPMS/x86_64/netdata-v1.17.0-1.el7.x86_64.rpm|grep go.d.plugin
/usr/libexec/netdata/plugins.d/go.d.plugin 31586073 1565126182 53b7fe7f36927881ed94c42b2f4bef26d3358a48d1a981ca5a77663000db2390 0100755 netdata netdata 0 0 0 X
```
`--dump` option provides the following items on the output seen above `#path size mtime digest mode owner group …
=> netdata/packaging: work around redhat complaining on build-id binary

web/gui/dashboard.js, web/gui/src/dashboard.js/units-conversion.js
Add a two more units that allow auto-scaling and conversion: nanoseconds and num.
As a result, e.g. 1000 nanoseconds -> 1 microseconds, 1000000 nanoseconds -> 1 milliseconds, 1000 num -> 1 num (K) etc.
web/gui/dashboard
This PR just expands the existing auto-scaling units (e.g. packets/s, milliseconds, etc.) and follow the corresponding coding style.
=> Expand dashboard auto-scaling and convertible units

.travis.yml
Fedora/28 is no longer on the list of supported software (https://fedoraproject.org/wiki/Releases)
Removing it's generation from our packaging
N/A
=> netdata/packaging: remove fedora/28, is no longer available

.travis.yml
We noticed that builds were breaking at the execution of `git semver`, during changelog generation.
When we debugged the process on travis, we realised that version 0.3.1 (latest available from travis) is broken.
We fall back to the last good version that we found on travis build history until they fix it (or forever, if the version doesn't become deprecated)
netdata/ci
N/A
=> netdata/ci: Force last good version of git-semver, they broke it

.travis/package_management/configure_deb_lxc_environment.py, contrib/debian/control.xenial
Yet another distribution with runtime version issues
libjson-c3 -> libjson-c2
libprotoc10 -> libprotoc9v5
```
root@af0192542851:/netdata# apt-get install libprotoc9v5 libjson-c2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libjson-c2 is already the newest version (0.11-4ubuntu2).
libprotoc9v5 is already the newest version (2.6.1-1.3).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
root@af0192542851:/netdata# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial …
```
=> netdata/packaging: fix ubuntu/xenial runtime dependencies

.travis.yml, .travis/package_management/common.py
When we built binary package tooling, we had to perform some git operations in order to create tarballs of the source code to push on the build machines for package generation.
What happened now is that when we built stable, we checkout to the latest patch or release version. This is resulting into switching the whole repository there, which in turn results into messing up the CI tooling code because we basically go back in history when half of the code has been executed.
With this change, we take the repository on a temporary directory and build the required tarballs there, so that we don't mess with CI scripts along the way.
So now we can have CI implementation from the tip of master, to build the stable version of binary packages
N/A
=> netdata/packaging: Ensure that we do not mess with CI tooling, when building stable

web/server/web_client.c
The host field in the web_client is to store the value of the Host HTTP header,
but it is an arbitrary size and there are no length checks. I could not see an
easy way to exploit it but this checks it will not overflow the buffer.
daemon / web_server
Splitting out from PR#6796.
=> Buffer overflow

.travis.yml, .travis/package_management/common.py, netdata.spec.in
As per the #6662 report, the time has come to consider separating all plugins that are easy to split on separate packages. 
This is the first plugin from a series of plugins that can be separated.
Once we fine grain the results of this PR we will mass-change the rest of the plugins following the same templated way given here.
Note: won't be touching .DEB sub-packaging yet as i need more context to get through
Fixes #6662
=> netdata/packaging: Split CUPS plugin to separate package (RPM)

collectors/python.d.plugin/python.d.plugin.in
Fixes #6841
[/collectors/python.d.plugin](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin)
=> python.d.plugin: no job config build fix

web/gui/README.md
This PR fixes the broken links mentioned in #6851 
The **Contexts** link for instance  in the current page https://docs.netdata.cloud/web/gui/ simply falls back to https://docs.netdata.cloud/#contexts instead of https://docs.netdata.cloud/web/#contexts
This PR corrects the path and links on the page work fine.
Docs
=> Resolve broken links in The standard web dashboard doc

docs/high-performance-netdata.md
when grepping for openfiles the netdata example is not exact enough and will return results from too many processes, just adding `.pid` to the grep _should_ pick up the correct process.
=> update grep to be more specific

packaging/installer/netdata-uninstaller.sh
For the uninstall script, the command used to delete de netdata user in linux (userdel -f "${username}") deletes the group as well because of the -f option, so the netdata group deletion step fails.
This pull request adds a conditional to only delete the netdata group if it still exists, otherwise just print a message and mark step as OK.
Uninstall script.
From userdel man page:
```
-f, --force
This option forces the removal of the user account, even if the user is still logged in. It also forces userdel to remove the user's home directory and mail spool, even if another user uses the
same home directory or if the mail spool is not owned by the specified user. If USERGROUPS_ENAB is defined to yes in /etc/login.defs and if a group exists with the same name as the deleted user,
then this …
```
=> Fixes netdata group deletion on linux for uninstall script

web/gui/main.js
A change requested by the cloud team, since they're using snake_case for query string params and want to use more generic `uri` (instead of `url`)
This param was introduced recently to fix this issue: https://github.com/netdata/netdata/issues/6542
This PR needs also corresponding change in the [Cloud](https://github.com/netdata/cloud/pull/1237), and if only 1 change will be applied, there will be no breaking error because of this, but the minor issue described in #6542 will be happening again, until both Agent and Cloud will be updated.
redirectUrl > redirect_uri in query params for cloud sign-in call
redirectUrl > redirectUri in response object from iframe's window.parent.postMessage
=> changed naming for redirect_uri param

web/gui/main.js
somehow we get redirectURI from the cloud on every sign-in, which causes redirect loop. I think something has changed on the Cloud side, but i don't have time to check it now.
This change prevents constant loop, and redirects only when it's needed
=> dont redirect when redirectURI is the same

collectors/cgroups.plugin/cgroup-network.c, tests/profile/benchmark-line-parsing.c
This comprises a couple of commits
collector: cgroups: Fix a cppcheck warning
tests/profile: Remove somewhat redundant code
The first removes a superfluous line from a function. This should not be controversial.
The second commit also removes some code, that *I* believe is somewhat redundant. See the commit message for the details and also https://github.com/netdata/netdata/issues/6378
Yes, this one may be more controversial...
Cheers,
Andrew
=> Cppcheck fixes

health/notifications/email/README.md
Adds info on how to use `msmtp` as an alternative to `sendmail`, in order to have a simple MTA configuration for sending emails and auth to an existing SMTP server.
health/notifications/email
Based on #6270 and the info @panpash provided.
=> Instructions for simple SMTP transport

contrib/debian/netdata.postrm
When removing/purging the Debian package
```
root netdata 775 /var/lib/netdata/registry
```
was being left behind in the `/var/lib/dpkg/statoverride` file. This causes subsequent installations to fail with:
```
dpkg: unrecoverable fatal error, aborting:
unknown group 'netdata' in statoverride file
```
packaging/debian
e.g.:
```
$ sudo apt-get purge netdata
...
$ sudo grep netdata /var/lib/dpkg/statoverride
root netdata 775 /var/lib/netdata/registry
$ sudo dpkg -i netdata_1.17.1_amd64.deb
dpkg: unrecoverable fatal error, aborting:
unknown group 'netdata' in statoverride file
```
=> /var/lib/netdata/registry was being left behind after purge

health/Makefile.am, health/health.d/vcsa.conf, web/gui/dashboard_info.js
This PR adds:
From [documentation](https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vcsa.doc/GUID-52AF3379-8D78-437F-96EF-25D1A1100BEE.html):
```
The vCenter Server Appliance API offers health status indicators for several key components of the appliance:
- green  The component is healthy.
- yellow The component is healthy, but may have some problems.
- orange The component is degraded, and may have serious problems.
- red The component is unavailable, or will stop functioning soon.
- gray No health data is available.
```
Alarms added for following components:
- applmgmt
- databasestorage
- load
- mem
- softwarepackages
- storage
- swap
- system
[/web/gui](https://github.com/netdata/netdata/tree/master/web/gui)
[health/health.d](https://github.com/netdata/netdata/tree/maste …
=> vcsa collector: charts descritpion and alarms

netdata-installer.sh, packaging/installer/README.md, packaging/installer/kickstart-static64.sh, packaging/installer/kickstart.sh
We introduce the option `--local-files` to allow our users to manually define the source and the checksum file for the kickstart to use in the installation process.
This option is useful for cases that users do not want to run kickstart with an internet connection
Note: we still require internet though for the dependency management
netdata/installer/kickstart
netdata/installer/kickstart-static64
Fixes #6684
=> netdata/installer: Add support for offline installs using kickstart or kickstart-static64

collectors/cgroups.plugin/cgroup-name.sh.in
Fixes #6878 
All containers in a kubernetes pod were not being resolved, as there was a hard-limit on the first item in `containerStatuses[]`
Thanks to @majodev for the catch and the fix
collectors/cgroup-name.sh
=> Resolve all Kubernetes container names

.gitignore, CMakeLists.txt, Makefile.am, collectors/Makefile.am, collectors/README.md, collectors/apps.plugin/apps_groups.conf, collectors/plugins.d/README.md, collectors/slabinfo.plugin/Makefile.am, collectors/slabinfo.plugin/README.md, collectors/slabinfo.plugin/slabinfo.c, configure.ac, contrib/debian/rules, docs/Add-more-charts-to-netdata.md, docs/generator/buildyaml.sh, netdata-installer.sh, netdata.spec.in
Provide new collector parsing `/proc/slabinfo` to provide details on kernel slab structures.
Asked by issue #13 (very happy for the oldest issue in backlog) 
collectors/slabinfo.plugin
This slabinfo details allows to have clues on actions done on your system.
In the following screenshot, you can clearly see a `find` done on a ext4 filesystem (the number of `ext4_inode_cache` & `dentry` are rising fast), and a few seconds later, an admin issued a `echo 3 > /proc/sys/vm/drop_cached` as their count dropped.
=> Collector slabinfo

database/rrdset.c
As far as the `CHART` command of the Netdata API can be used to redefine chart names in the database, it is a valid operation, so it should not be reported as an error.
Fixes #6819
Netdata database
=> Change the log level for chart updates

collectors/node.d.plugin/snmp/README.md, collectors/python.d.plugin/dnsdist/README.md, docs/configuration-guide.md
A revised and simplified PR compared to #6746, which I'm going to close in favor of this one.
The Gatsby build (Learn site) errors out due to Markdown syntax errors on these pages. Mostly some stray Markdown syntax that `mkdocs` is silently ignoring but should be fixed regardless.
docs
=> Markdown syntax fixes for MDX parser

docs/netdata-security.md, libnetdata/socket/socket.c, libnetdata/socket/socket.h, web/server/static/static-threaded.c, web/server/web_client.c, web/server/web_client.h, web/server/web_server.c
The Access Control List (ACL) configuration parameters can now use hostnames with simple patterns. Incoming connections are resolved using reverse DNS to obtain the hostname. Where a hostname is resolved, forward DNS resolution is performed to check the IP address is really associated with the hostname. If the checks pass then the patterns supplied are checked. Any patterns supplied for numeric ip addresses are also checked.
daemon
Fixes #6438
=> Allow hostnames in Access Control Lists

collectors/charts.d.plugin/apache/README.md, docs/Running-behind-haproxy.md, docs/contributing/contributing-documentation.md, packaging/installer/README.md, packaging/installer/UNINSTALL.md, web/api/formatters/json/README.md, web/server/README.md
In the [one-line installation](https://docs.netdata.cloud/packaging/installer/#one-line-installation), click "copy to clipboard" button. 
Pasting it on any terminal (or anywhere else) to begin the installation of Netdata:
Below is what gets pasted. 
```sh
$ bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```
This is the output:
```
$: command not found
```
Installation code, of course, works perfectly without the `$` being copied. 
This works as expected:
```
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```
Another way to tackle this would be to prevent the starting `$` in bash or shell code from getting copied on MkDocs when that button is clicked. 
However, there are already other bash/shell codes that do not have the dollar signs starting them. 
I resolved some remark-lint …
=> Remove Dollar sign from Bash code in documentation and fix remark-lint warnings

packaging/installer/README.md, packaging/installer/kickstart-static64.sh
We missed the argument parsing fix on static installer. It's a bug that was caught and fixed on kickstart.sh, but slipped through on kickstart-static64.sh
Fixes #6891
=> netdata/packaging: fix kickstart-static64 argument parsing

web/server/web_client.c
Fixes #6893
web
Ajax requests were being blocked with `Request header field x-auth-token is not allowed by Access-Control-Allow-Headers in preflight response.`
=> Permit x-auth-token in Access-Control-Allow-Headers

collectors/slabinfo.plugin/slabinfo.c
Makes pagesize dynamic at startup instead of fixed at compile time
Some arches does not export PAGE_SIZE in `<sys/user.h>`.
ARM (raspberry pi) provides `/usr/include/arm-linux-gnueabihf/sys/user.h` which does not provide it.
Changed `#define` to `static long` fetched from POSIX `sysconf(_SC_PAGESIZE)` (defined in `<unistd.h>`) [manpage](http://man7.org/linux/man-pages/man3/sysconf.3.html)
collectors/slabinfo.plugin
Fixes #6896 : Fail to build on raspberry pi
=> [collector/slabinfo] Fix pagesize not defined in non-x86 arches

.travis/generate_changelog_and_tag_release.sh, .travis/generate_changelog_for_nightlies.sh, .travis/generate_changelog_for_release.sh
Preparation for #6899 
Make changelog generation faster and ensure it won't crash. Put it back to the pipeline. 
CI/CD
- Added correct max-issues specification. Note that the number of issues affects the number of displayed PRs. There's no way to ensure that all the PRs in a tag will be displayed, but with a limit of 500 we know that the most recent releases will be complete.
- Let the CHANGELOG show links to diffs
- Put an invalid Bug tag, to ensure that fixed bugs are not listed (the result with the defaults was incorrect)
- Enable running the changelog generation again
=> Improve changelog generation and add it back to the pipeline

web/gui/dash-example.html
=> fix LGTM warnings

health/health.c
Fix potential issue reported by coverity, length should be > 1 to proceed with processing of the file read.
health
```
** CID 349499:  Error handling issues  (NEGATIVE_RETURNS)
/health/health.c: 58 in health_silencers_init()
*** CID 349499:  Error handling issues  (NEGATIVE_RETURNS)
/health/health.c: 58 in health_silencers_init()
52             fseek(fd, 0 , SEEK_SET);
53     
54             if (length && length < HEALTH_SILENCERS_MAX_FILE_LEN) {
55                 char *str = mallocz((length+1)* sizeof(char));
56                 if(str) {
57                     size_t copied;
>>>     CID 349499:  Error handling issues  (NEGATIVE_RETURNS)
>>>     "length" is passed to a parameter that …
```
=> Correct read length of silencers file

web/server/README.md
Fixes #3347
docs
Don't use /tmp for unix sockets
=> Suggest using /run or /var/run for the unix socket

contrib/README.md
This PR fixes remark lint warnings for the README files in the Contrib directory.
Related: #5941
Docs
`~/netdata$` was removed to avoid it being copied to clipboard.
=> Fix remark lint for Contrib 

collectors/python.d.plugin/python.d.plugin.in
ssia
> 2019-09-23 17:17:15: python.d WARNING: plugin[main] : {0}[{1}] : unhandled exception on check : {2}, skipping the job web_log nginx_log UnicodeEncodeError('ascii', u'/opt/\xfc.log', 5, 6, 'ordinal not in range(128)')
> plugin[main] : {0}[{1}]
[collectors/python.d.plugin/python.d.plugin](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python.d.plugin.in)
=> python.d: fix log warnings in start_job

contrib/debian/rules
sym linked www directories were not correctly defined, was missing the www.
netdata/packaging/deb
Fixes #6925
=> netdata/packaging: fix broken links on web files, for deb

netdata.spec.in
Do not build CUPS plugin subpackage on CentOS 6 and CentOS 7
RPM packaging
According to #5350 the CUPS plugin needs a cups library newer than 1.7, but CentOS 6 and CentOS 7 include versions 1.4.2 and 1.6.3 respectively. This causes the library to not be detected by ./configure and the CUPS plugin to not being build. This, in turn causes the packaging jobs for CentOS 6 and CentOS 7 to fail.
This pull request disables the CUPS plugin for CentOS 6 and CentOS 7. A test build can be found here:
https://travis-ci.org/knatsakis/netdata/builds/588618391
=> netdata.spec.in: Do not build CUPS plugin subpackage on CentOS 6 and CentOS 7

web/api/queries/query.c
Restore original alignment behaviour of RRDR so that after and before timestamps are more inclusive with database points during queries.
web
Fixes #6835
=> Restore original alignment behaviour of RRDR

health/Makefile.am, health/health.d/hdfs.conf, health/health.d/zookeeper.conf, web/gui/dashboard_info.js
This PR adds:
`zookeeper` alarms:
- availability
`hdfs` name node alarms:
- availability
- capacity usage
- missing blocks
- stale nodes
- dead nodes
`hdfs` data node alarms:
- availability
- capacity usage
- failed volumes
[/web/gui](https://github.com/netdata/netdata/tree/master/web/gui)
[health/health.d](https://github.com/netdata/netdata/tree/master/health/health.d)
- i tested the PR installing it, it works - i see all info/alarms on the dashboard.
cc: @killerwhile
=> zookeeper and hdfs: alarms and dashboard_info

tests/stress.sh
Very small change -> Check for `curl` presence in system.
Before if `curl` is not installed you will get error message (and start investigating what is wrong with netdata):
```bash
using netdata server at: http://127.0.0.1:19999
Cannot download charts from server: http://127.0.0.1:19999
```
even if netdata running and responding well.
tests/stress.sh
=> minor - check for curl to not get wrong error message

libnetdata/socket/socket.c
When Netdata was run under valgrind, it reported memory leaks on exit.
Fixes #6944
libnetdata/socket
=> Fix a memory leak

web/api/exporters/shell/allmetrics_shell.c
This PR adds family to `allmetrics?format=json` response.
Sometimes we encode meaningful things in family.
Example: vsphere collector [vm charts family](https://github.com/netdata/go.d.plugin/blob/master/modules/vsphere/charts.go#L154)
- virtual machine name
- host name
The main problem is lack of labels of course. But still i dont see any reason to not include family in json allmetrics response .
rel issue: https://github.com/netdata/go.d.plugin/issues/274
[/web/api/exporters](https://github.com/netdata/netdata/tree/master/web/api/exporters/shell)
=> web api: include family into allmetrics json response

netdata.spec.in, packaging/DISTRIBUTIONS.md
Sice we have identified that we missed a critical CUPS version dependency, we need to update our spec file so that we guarantee we always depend on the right versions of CUPS.
This way we ensure we won't bump into build problems in the future.
Also, take note of the CUPs version required in the distributions table
netdata/docs
N/A
=> netdata/packaging: Make spec file more consistent with version dependencies, plus some documentation nits

database/rrddim.c
Fixes #6969 
We had a deadlock inside the database after to merge template to dimension, this commit fixes this error.
Health
=> Fix coverity erro (CID 349552) double lock

database/engine/pagecache.h, database/engine/rrdengineapi.c
Fix dbengine consistency when a writer modifies a page concurrently with a reader querying its metrics.
Fixes  #6978
=> Fix dbengine consistency

collectors/apps.plugin/apps_plugin.c, daemon/main.c, libnetdata/health/health.c, libnetdata/json/jsmn.c
Fixes part of #6924 
This PR fixes 4 issues that are present in our code according Coverity. I did not touch some collectors, because I will need to study more the code to understand what we have there and the database engine that Markos is already taking care.
Health
Daemon
=> Coverity 20190924

daemon/main.c, daemon/unit_test.c, daemon/unit_test.h, database/README.md, database/engine/README.md, database/engine/rrdengine.c, database/engine/rrdenginelib.c, database/rrd.c
Make dbengine the default memory mode.
Combine and parallelize dbengine validation unittest with dataset generator into a multithreaded dbengine benchmark that validates data integrity while constantly generating new data.
Fixes #6767
=> Make dbengine the default memory mode

collectors/python.d.plugin/elasticsearch/README.md, collectors/python.d.plugin/elasticsearch/elasticsearch.chart.py, collectors/python.d.plugin/elasticsearch/elasticsearch.conf
Fixes: #6541
This PR adds per index metrics:
- docs count
- store size
- number of replicas
- health status
Modules gathers these metrics from `_cat/indices` endpoint. Per index metrics is optional and disabled by default.
[`/collectors/python.d.plugin/elasticsearch`](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/elasticsearch/elasticsearch.chart.py)
=> elasticsearch: collect metrics from _cat/indices

collectors/python.d.plugin/mysql/README.md, collectors/python.d.plugin/mysql/mysql.chart.py, health/health.d/mysql.conf, web/gui/dashboard_info.js
Fixes: #6934
Info sources:
- https://mariadb.com/kb/en/library/galera-cluster-status-variables
- https://www.percona.com/doc/percona-xtradb-cluster/LATEST/wsrep-status-index.html
This PR adds:
New collected metrics:
- `wsrep_cluster_weight`
- `wsrep_cluster_size`
- `wsrep_cluster_status`
- `wsrep_local_state`
- `wsrep_open_transactions`
- `wsrep_connected`
- `wsrep_ready`
- `wsrep_thread_count`
[`/collectors/python.d.plugin/mysql`](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mysql)
cc: @ekexcello
=> mysql: collect galera cluster metrics

collectors/python.d.plugin/rabbitmq/README.md, collectors/python.d.plugin/rabbitmq/rabbitmq.chart.py
Fixes: #6686
This PR adds per vhost message stats metrics.
Message stats:
-  ack
-  confirm
-  deliver
-  get
-  get_no_ack
-  publish
-  redeliver
-  return_unroutable
Modules gathers these metrics from `/api/vhosts` endpoint.
[`/collectors/python.d.plugin/rabbitmq`](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/elasticsearch/rabbitmq.chart.py)
=> rabbitmq: collect vhosts msg metrics from `/api/vhosts`

daemon/README.md
This PR fixes remark lint warnings for the README Daemon.
Related: #5941
Docs
Fixing this warning `[table-pipe-alignment] Misaligned table fence` causes the table not to render on GitHub and MkDocs. That's why I am leaving it as is.
=> Fix remark warnings for Daemon README

health/notifications/README.md
Add a supporting command after the line describing recipient group notification.
Fix list -> numbering
=> Clarification on configuring notification recipients

database/rrdcalc.c, libnetdata/eval/eval.c
Coverity reported us that on CID 348642 that we have an unnecessary check on our code, this PR is moving up the code inside ```if``` to remove the issue reported.
Database
Health
=> Remove warning from Coverity

database/engine/rrdengineapi.c
Fixes #6999
Handle cases where metric timestamps are inversed and data collection interval rounds to 0.
=> Fix handling of illegal metric timestamps in database engine

collectors/freebsd.plugin/freebsd_sysctl.c
fixes #7010
Fix for the issue #7010. I am not 100% sure if it is valid, but i made it in accordance with other plugins in the freebsd collector code. Please review. For me it fix crashe and valgrind report.
FreeBSD plugin
See #7010 and [valgrind report](https://github.com/netdata/netdata/issues/7010#issuecomment-539354446)
=> Fix crash on FreeBSD due to do_dev_cpu_temperature stack corruption

docs/generator/checklinks.sh
Fixes #6982 
- Fix a bug that adds unecessary `../` before some links
- Better indentation to make debug messages easier to see.
docs
@joelhans  found a bug in `checklinks.sh`.
> In the getting started guide (since the PR was merged in) there's a link to tutorials/longer-metrics-storage.md. That's a valid relative link, but then the script uses sed to add an extra ../ that breaks the link once the build completes. It links to tutorials/longer-metrics-storage/ instead of docs/tutorials/longer-metrics-storage/.
There's other places with broken links to/from files in the netdata-cloud/ and contributing/ folders, too.
I found two lines on checklinks.sh that add the ../: if [ "$fname" != "README.md" ] ; then s="../$s"; fi. They're on 148 and 167. When I comment those out the build finishes and …
=> Checklinks fix

collectors/python.d.plugin/rabbitmq/rabbitmq.chart.py
fixes: #7018
[`/collectors/python.d.plugin/rabbitmq`](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/elasticsearch/rabbitmq.chart.py)
bug was added in https://github.com/netdata/netdata/pull/6976
=> rabbitmq: survive lack of vhosts

collectors/plugins.d/plugins_d.c, collectors/slabinfo.plugin/README.md
There are a lot of metrics in slabinfo charts. Hundreds or even thousands (depends on host). Thus, we are disabling the slabinfo charts by default.
Fixes #7053
slabinfo plugin
=> Disable slabinfo plugin by default

database/rrddim.c, database/rrdset.c
Fixes #7057
database
Fix dbengine not working when mmap fails. This mostly happens with BSD kernels.
=> Fix dbengine not working when mmap fails

health/notifications/health_alarm_notify.conf
Typo fix
health_alarm_notify.conf
=> Fix typo in health_alarm_notify.conf

collectors/freebsd.plugin/freebsd_sysctl.c
While reviewing #7014 @mfundul found a mistake in the size calculation for a zeroed block.
freebsd plugin
=> Fix size of a zeroed block

database/rrddim.c
Fixes #7058 
Netdata has yet problems with dashes and  underscores and this was creating problems with the new features like template for all dimension. The bug reported from our users were happening because Netdata uses the chart id to create charts from template (`database/rrdcalctemplate.c` function `rrdcalctemplate_link_matching_test`)  instead the chart name and name and id sometimes are not matching, the same problem does not happen when we created the alarm using `alarm`, because in this case the user must type write the name that he is seeing on his screen and Netdata uses this information to set the chart( `health/health_config.c` function `health_readfile` ).
Health
=> Fix problems with names when alarm is created

collectors/freeipmi.plugin/freeipmi_plugin.c
Fix the update frequency check for freeipmi which was warning that 5 was too frequent an it was setting it to 5.
collectors/freeipmi
=> fix(freeipmi): Update frequency config check

.travis.yml
In order to prevent the issue described in #7063 from happening, the package triggering jobs (`Trigger deb and rpm package build`) are moved to a stage of their own
.travis.yml
Test builds:
https://travis-ci.org/knatsakis/netdata/builds/598286299
https://travis-ci.org/knatsakis/netdata/builds/598287332
=> Run the triggers for deb and rpm package build in separate stages

collectors/python.d.plugin/megacli/megacli.chart.py
fixes: #7107
- search for `MegaCli` binary (FreeBSD)
- use `sudo -n -l` instead of `sudo -n -v` for sudo check
[/collectors/python.d.plugin/megacli](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/megacli)
=> megacli: search binary and sudo check fix

collectors/statsd.plugin/statsd.c
Netdata was crashing on FreeBSD when statsd was disabled due to the 
peculiarities of `pthread_cleanup_push` behavior in FreeBSD.
Fixes #7064
statsd plugin
=> Fix segmentation fault in FreeBSD when statsd is disabled

backends/prometheus/backend_prometheus.c
As far as 204 is a success response, we don't need to show it in logs.
Fixes #7034
prometheus remote write backend
=> Don't write an HTTP response 204 to logs

web/api/netdata-swagger.json, web/api/netdata-swagger.yaml
Fixes #7005 and some small miscellaneous problems and reviewing the source and documentation.
Fix the initial typo so that the response schema for /api/v1/data? is used instead of the /api/v1/chart? scheme.
Improve the structure of the "result" property in the object to show the fields.
Introduce polymorphic structure so that the different data formats are described.
area/docs
The responses of the `api/v1/data` endpoint are now documented in swagger to match the behaviour in the code.
Tested request / response pairs against the demo system in the swagger editor.
The `400` response was missing from `api/v1/chart`.
Changed the description of the `api/v1/allmetrics` endpoint (but not the schema of the response).
Added missing fields to the `api/v1/chart_summary` endpoint.
Some quoted strings …
=> Documenting the structure of the data responses.

collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService.py, collectors/python.d.plugin/unbound/unbound.chart.py
fixes: #7111
This PR:
- fixes `ssl.PROTOCOL_TLS` import (added in py 2.7.13, it deprecates `ssl.PROTOCOL_SSLv23`)
- fixes unhandled `IOError`, `OSError` exceptions in `SocketService._connect2socket` method during `ssl.wrap_socket` (it happens if ssl key or cert is not exists/readable)
- adds two checks to the unbound module check method: check if ssl key is readable, check if ssl cert is readable
- moves load unbound config logic to a sep method
[/collectors/python.d.plugin/unbound/unbound](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/unbound)
=> unbound: fix init

collectors/apps.plugin/apps_plugin.c
CPU charts in apps plugin showed less CPU usage than it was in fact.
Fixes #7087
Relevant: #5038, #3245, #4037
apps plugin
=> Fix CPU charts in apps plugin on FreeBSD

netdata-installer.sh, packaging/installer/functions.sh, packaging/makeself/install-or-update.sh
Partial fix for #7039
- Moved updater installation code from netdata-installer.sh to packaging/installer/functions.sh
- packaging/makeself/install-or-update.sh uses above code to install
netdata updater
packaging/makeself/install-or-update.sh
Another PR will be needed, in order to update kickstart-static64.sh and enable the netdata installer by default
=> Partial fix for #7039

CONTRIBUTORS.md, collectors/plugins.d/plugins_d.c, collectors/tc.plugin/plugin_tc.c, daemon/main.c, daemon/main.h, daemon/signals.c, libnetdata/popen/popen.c, libnetdata/popen/popen.h
Add a child process reaper to the main netdata app if running as init (pid = 1).
This prevents zombie processes when a child is re-parented to netdata when its running in a container.
Also:
* Few style cleanups to match surrounding code.
Fixes: #6033
netdata binary
This re-purposes old commented out code in `popen.c`, which already implemented part of the required process tracking.
Without this on a standard netdata docker install we saw at least one zombie `timeout` process straight after the container was started.
=> feat(reaper): Add process reaper support

collectors/python.d.plugin/unbound/unbound.chart.py
This avoids them being mangled to the point of being useless when the
locale settings are configured to convert seconds to times.
These were originally implemented as seconds because that's how Unound
itself reports them.
collectors/python.d/unbound
Fixes #7120 
Shows no issues in testing, though the switch-over doesn't drop old data or convert it properly (that's probably a bug elsewhere though, and I don't feel it should block this PR).
=> Convert recursion timings to miliseconds.

packaging/installer/functions.sh, packaging/makeself/install-or-update.sh
Partial fix for #7040 
- install-or-update.sh now accepts the --stable-channel option and updates the environment file
packaging/makeself/install-or-update.sh
Another PR will be needed, in order to update kickstart-static64.sh and pass the --stable-channel options when needed
=> 7040 enable stable channel option

CMakeLists.txt, Makefile.am, collectors/all.h, collectors/proc.plugin/plugin_proc.c, collectors/proc.plugin/plugin_proc.h, collectors/proc.plugin/proc_pagetypeinfo.c
The buddyallocator is the system memory allocator: the whole memory space is split
in **physical pages** (whose size is determined by the CPU Architecture & MMU). These physical pages are grouped into "page groups" of 2^10 (order 10) physical pages. (also numa node & zones).
When the kernel or an application requests some memory, the buddyallocator provides a page that matches closest the request. 
If an application requests 100KB, the buddy allocator will try to find a page of 128KB (order 7: 2^7).
If there is no such order available, it will find a page frm a superior order, and split it in 2 * 128K page. If no super page is available, it will try to reclaim memory from buffer / cache (reclaimable).
In x86, this translates to:  
- each physical page is 4KB,
- minimal size (order 0) of a …
=> [collector/proc.plugin] Add /proc/pagetypeinfo parser

health/health.d/mysql.conf
galera cluster status alarm suggested by @ekexcello in https://github.com/netdata/netdata/pull/6962#issuecomment-537002612
Added as a separate PR because the alarm is false positive until #6980 is fixed.
Should be merged after #6984
[health/health.d/mysql.conf](https://github.com/netdata/netdata/blob/master/health/health.d/mysql.conf)
=> mysql: add cluster_status alarm

BUILD.md
Fixes #4310 
area/deamon
This is a summary of the investigation results from the spike. Everything is contained in `BUILD.md` in the root of the repo. The tl;dr is "yes, we should switch to cmake", and we know how to implement each of the cases that we will encounter. This is not a strict recipe for how to do this as we had to control the scope of the investigation and start writing a prototype of the new build-system.
Everybody who is affected by changing build-systems should review the file. [If I've missed anybody as reviewer that is affected please add them]. If you any major problems please comment straight away so that we can start discussing them. If you don't see anything major then the next step will be an internal meeting to check that we have a common understanding of how the …
=> Results of the spike investigation into CMake.

collectors/python.d.plugin/mysql/README.md
Related to: #7126 
It is not stated in the documentation that `netdata` MySQL user has to be created for the MySQL charts to show on the dashboard. 
docs
=> Add user information to MySQL Python module documentation

collectors/statsd.plugin/statsd.c, daemon/main.c, libnetdata/simple_pattern/simple_pattern.c, libnetdata/simple_pattern/simple_pattern.h, libnetdata/socket/socket.c, libnetdata/socket/socket.h, registry/README.md, web/server/README.md, web/server/static/static-threaded.c, web/server/web_server.c, web/server/web_server.h
Fixes #7116 
area/daemon
area/web
The performance problems are avoided by adding a heuristic check to decide if the pattern might
match a DNS FQDN or if it can only match IP-addresses. The heuristic uses the presence of
alphabetical characters somewhere in the string (as the TLD much contain at least one non-numeric
characters) and the absence of ':' to rule out IPv6 false positives.
Added new configuration options to explicitly control the DNS checks so that the heuristic can
be overridden if it does not match the intention.
Added description of the options and a performance warning to the documentation.
The placement of the heuristic procedure in the simple_pattern.c code is not ideal, but the `struct simple_pattern` is deliberately defined in the `.c` file to prevent extension / access …
=> Fixing DNS-lookup performance issue on FreeBSD.

contrib/debian/control, contrib/debian/control.buster, contrib/debian/control.jessie, contrib/debian/control.trusty, contrib/debian/control.wheezy, contrib/debian/control.xenial
=> contrib/debian: Fix typo in Description

collectors/proc.plugin/proc_pagetypeinfo.c
Fixes #7160 
Coverity reported us that the callocz was allocating to a pointer to pointer a simple vector, this was using more memory than necessary and thanks this we did not have any bug reported, this PR fixes this problem
Collectors
=> Fix sizeof inside callocz

packaging/installer/README.md, packaging/installer/UPDATE.md, packaging/installer/kickstart-static64.sh
This should complete the fix for #7039. It modifies kickstart-static64.sh in order to pass the --auto-update option to netdata-latest.gz.run
packaging/installer/kickstart-static64.sh
Please do not merge this, before #7060 gets merged **and released**
After merging and deploying this, the kickstart scripts at https://my-netdata.io/ must be updated
=> kickstart-static64.sh passes --auto-update to netdata-latest.gz.run

docs/Running-behind-nginx.md
Additional fix to #3342
(in another location in docs)
docs
Don't use /tmp for unix sockets.
=> Suggest using /var/run/netdata for the unix socket

packaging/installer/README.md, packaging/installer/kickstart-static64.sh, packaging/installer/kickstart.sh
- pass --stable-channel option
- append --dont-wait option to list of passthrough options
Passes through kickstarter options to the installer
Packaging - Installer
Fixes #7040
=> kickstart: pass options to installer

libnetdata/libnetdata.h
Include limits.h before using LONG_MAX. This fixes build with musl standard C library.
database
=> database: include limits.h before using LONG_MAX

.travis.yml
Increase the timeout for docker image builds to 20 minutes
.travis.yml
Fixes #7213
=> .travis.yml: Increase timeout for docker image builds to 20 minutes

collectors/cgroups.plugin/cgroup-network-helper.sh
add a check for 'emulator' subdirectory
add full cgroup-path with 'cgroup.procs' filename to 'c' variable
collectors/cgroups.plugin/cgroup-network-helper.sh
=> fixed - cgroup-network-helper doesn't work on Proxmox 6

health/notifications/alarm-notify.sh.in
This fixes IRC notifications not working (being ignored even when configured).
Added IRC as method and updated author name.
`alarm-notify.sh`
There's still some bugs using IRC notifications but adding it to the method list at least enables the notification method and sends alerts as expected.
Basically, `/usr/lib/netdata/plugins.d/alarm-notify.sh` throws error code 421 for IRC, which is false, as the alert is seen on IRC with these changes when configured in `health_alarm_notify.conf`.
Error 421 = `ERR_UNKNOWNCOMMAND | "<command> :Unknown command"`
@ktsaou @manosf Is there was a way for `alarm-notify.sh` to print the entire command that IRC is trying with the variables? As `bash -x` does not and: https://github.com/netdata/netdata/blob/5d82cb5a2407fd2d983fcbcd81ecc2ca41dd0f53/health/notifi …
=> Update alarm-notify.sh to enable IRC notifications

collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py
Fixes: #7222
Do not check scheme applying `tls_verify` option.
[/collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py)
=> UrlService: allow to skip tls_verify for http scheme

collectors/python.d.plugin/rabbitmq/rabbitmq.chart.py
Fixes: #7218
`/api/nodes` endpoint returns `disk_free_monitoring_disabled` as a value for `disk_free` and `disk_free_limit` if rabbitmq failes to get this data.
rel: 
> https://stackoverflow.com/questions/43460638/can-rabbitmq-disk-free-monitoring-be-enabled?rq=1
[/collectors/python.d.plugin/rabbitmq](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/rabbitmq)
=> rabbitmq: handle "disk_free": "disk_free_monitoring_disabled"

.travis.yml, .travis/utils.sh
Prevent nightlies from timing out (again). Using a different approach this time because the first attempt was not good enough.
.travis.yml
[Test build output](https://travis-ci.org/knatsakis/netdata/jobs/605792730)
=> .travis.yml: Prevent nightly jobs from timing out (again)

tests/api/fuzzer.py, web/api/netdata-swagger.json, web/api/netdata-swagger.yaml
Fixes #7163 
Writing a fuzzer for the web API. Validates responses against the data-model defined in swagger. Because this performs model-checking against the swagger (in addition to using it for generating the docs) - upgrading the swagger model to be machine-checkable in addition to human-readable.
area/daemon
area/web
Currently generates a small set of negative / positive test-cases and validates the responses as fully as is currently possible. The documentation-related issues within the same epic (#6968 and #7029) are areas of the swagger that needs to be implemented to allow full validation. The incorrect response codes that are found during the fuzzing process will be fixed during the replacement of the url parsing code in #7164. A deeper scanning depth for a larger fuzzing set will …
=> Building a fuzzer against the API (issue #7163)

health/health.d/tcp_listen.conf
Based on discussion from #6998
This should make the alarms much less noisy in cases where SYN cookies aren't being used with a particularly high frequency.
=> Update SYN cookie alarm to be less aggressive.

netdata-installer.sh, packaging/installer/functions.sh
- netdata-installer.sh: Improve message about updater installation
- packaging/installer/functions.sh: get_crondir fails if crondir is not found
- packaging/installer/functions.sh: mark get_crondir and check_crondir_permissions functions as private
netdata-installer.sh
Some follow-up corrections to netdata-installer.sh based on review comments in #7060
=> netdata-installer.sh follow-up based on #7060 review

packaging/installer/README.md, packaging/installer/kickstart-static64.sh
This should complete the fix for #7040 (kickstart-static64.sh only). It modifies kickstart-static64.sh in order to pass the --stable-channel option to netdata-latest.gz.run
packaging/installer/kickstart-static64.sh
Please do not merge this, before #7082 gets merged **and released**
After merging and deploying this, the kickstart-static64.sh script at https://my-netdata.io/ must be updated
=> Second part of fix for #7040

netdata-installer.sh
As per our #7025 report, we missed to add https and dbengine disable options to the list of available options for our `netdata-installer.sh`
This PR mitigates that issue
**Note**: Haven't tested it, @knatsakis please help with verification and approval of PR
netdata/installer
Fixes #7025
=> netdata/installer: add missing flags on installer

packaging/installer/UPDATE.md
Until the netdata updater starts working with kickstart-static64.sh with issue #7197
documentation
=> Remove documentation about kickstart-static64.sh and netdata updater

health/notifications/alarm-notify.sh.in
Fixes #7233 
When Netdata is sending messages to IRC channels, the messages are generating the error 421, because our default message is not according RFC1459(https://tools.ietf.org/html/rfc1459#section-2.3.1 ), this PR replaces the line break with commas to fix the problem.
Alarms
I used the server ircd-hybrid to develop, because I wanted to have messages from both sides, but it is possible to do a simpler test, this PR must avoid the error.log to have error messages 421 when we send an alarm.
=> fix_irc_notification: Remove line break from message

collectors/apps.plugin/apps_groups.conf
Signed-off-by: Matthew McGinn <mamcgi@gmail.com>
balenaEngine is a moby-based container engine often used in IoT: https://github.com/balena-os/balena-engine/
apps_groups.conf
=> container-engines: add balena* to apps_group.conf

collectors/python.d.plugin/web_log/web_log.chart.py, web/gui/dashboard_info.js
The web_log chart module currently treats requests with a 401 status code as bad requests. However, the 401 answers just say that the incoming request wasn't authorized properly and are often followed by a request with the correct authorization.
We're using Kerberos based authentication on our internal pages, and for this authentication method, _every_ request needs to be sent in two steps:
* Client sends an unauthenticated request
* Server replies 401 with WWW-Authenticate:Negoatiate <token>
* Client sends request again with Authorization: Negotiate <much-more-data>
* Server replies 200
The token sent in the first request will be different for every request, thus it is required to send two requests - and there will be (if all authentication tries are successful) around 50% requests with …
=> web_log: treat 401 Unauthorized requests as successful

collectors/Makefile.am, collectors/charts.d.plugin/Makefile.am, collectors/node.d.plugin/Makefile.am, collectors/python.d.plugin/Makefile.am, collectors/statsd.plugin/Makefile.am, contrib/debian/rules, health/Makefile.am, netdata-installer.sh, netdata.spec.in, packaging/makeself/install-or-update.sh, system/Makefile.am, web/Makefile.am
Improve ownership and permissions of /etc/netdata based on suggestions in #6619 
This PR should address points 1-4 of #6619 
netdata-installer.sh (kickstart.sh installations)
install-or-update.sh (kickstart-static64.sh installations)
debian/rules (.deb packages)
netdata.spec.in (.rpm packages)
The following use cases have been tested:
- clean kickstart.sh installation (uses root)
- upgrade with kickstart.sh (uses root)
- clean netdata-installer.sh as knatsakis (uses non-root user)
- clean kickstart-static64.sh installation (uses root)
- ./configure && make && make install installation (used root)
- .deb package installation
- .rpm package installation
The most significant change is on the ownership/permissions of /etc/netdata/netdata.conf that change to root:root 0644. This means that our …
=> Ownership and permissions of /etc/netdata

collectors/apps.plugin/apps_groups.conf
Add git/software forge related processes to [apps_groups.conf](https://github.com/netdata/netdata/blob/master/collectors/apps.plugin/apps_groups.conf):
- Gitea self-hosted Git service https://gitea.io/en-us/
- Gitlab continuous integration runner https://docs.gitlab.com/runner/
[/collectors/apps.plugin](https://github.com/netdata/netdata/tree/master/collectors/apps.plugin)
Default configuration change. Group called 'git' for lack of a better name.
=> apps.plugin: add process group for git-related processes

collectors/plugins.d/plugins_d.c, database/rrd.h, database/rrdhost.c, streaming/rrdpush.c
Fixes #7291 
Our user detected that when the slaves has SSL certificate enabled and it was connecting to a master with SSL, some of the metrics were not being sent, this PR fixes this problem.
Stream
=> Fix missing streaming when slave has SSL activated.

.travis.yml, .travis/clangformat.sh, CONTRIBUTING.md, daemon/main.c, libnetdata/simple_pattern/simple_pattern.c
Fixes #7189 
The current build doesn't match our conventions during development on the team. We have a different build configuration in Travis to the one that we should use to keep the code warning free. There is no indication on how the code matches our coding style.
* Added a linting pass. This is non-blocking but will output a measure of how much each .c and .h file deviates from our current `.clang-format`.
* Changed the standard built to include all of the warning that we are using in dev.
=> Updating the Travis pipeline (issue 7189)

health/health.d/dnsmasq_dhcp.conf, health/health.d/megacli.conf, health/health.d/net.conf, health/health.d/pihole.conf, health/health.d/ram.conf, health/health.d/softnet.conf, health/health.d/tcp_listen.conf, health/health.d/udp_errors.conf
Make some of the alarms that are seriously annoying people less aggressive. Also fix formatting in a few of the alarm configuration files so that everything lines up and is easy to read.
health/alarms
This tweaks the remaining TCP queue alarms, as well as the softnet alarms. The idea here is to use an average over a shorter period of time and trigger if that goes above 1 instead of looking at a sum over a long period of time and triggering if that goes above 0.
It also updates the UDP error alarms to work like the TCP queue alarms for consistency.
The tweaks to the softnet alarms may be scaling things back a bit too much, but should at least keep the alarms from bugging most people needlessly with their previous high rate of false positives.
Fixes: #7314
Relevant to: #4727 #5630
=> Fine tune various alarm values.

collectors/proc.plugin/proc_stat.c
start an idle thread (wake_cpu_thread) if the core is not  in
the allowed cpu set.
Fixes #6741
Prevent isolated CPUs from being used by the idle thread 
This is done by reading the current affinity of the process and making sure
that the excluded cores do not spawn an idle thread (`wake_cpu_thread`)
=> - Retrieve current affinity of the process and make sure not to

packaging/docker/README.md
Fixes #7075 
I tested this new line for the `docker-compose.yml` file on a VPS and it works fine.
I bet the old line works in _some_ cases, but hard-coding the location of the SSL files seems safer to me overall and should work in more cases so the location of the SSL files isn't dependent on where the user puts `docker-compose.yml` file.
docs
=> Fix to docker-compose+Caddy installation

collectors/python.d.plugin/nvidia_smi/README.md, collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py, collectors/python.d.plugin/nvidia_smi/nvidia_smi.conf
Fixes: #7143 
nvidia_smi module executes `nvidia-smi` program in the loop mode
```
-l SEC, --loop=SEC
Continuously report query data at the specified interval, rather than the default of just once.  The application will sleep in-between queries.  Note that on Linux ECC error or XID error events will print out during the sleep period if the -x flag was  not  specified.   Pressing
Ctrl+C at any time will abort the loop, which will otherwise run indefinitely.  If no argument is specified for the -l form a default interval of 5 seconds is used.
```
This PR makes it configurable and allows to execute the program in normal mode.
[/collectors/python.d.plugin/nvidia_smi](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/nvidia_smi)
I tested it on my linux pc with Nvidia …
=> nvidia-smi: not loop mode

collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService.py, collectors/python.d.plugin/python_modules/bases/collection.py, collectors/python.d.plugin/python_modules/bases/loggers.py
There is an issue with logging UTF-8 characters when Netdata is run under Python 2. I've explained it in detail here: https://github.com/netdata/netdata/issues/7190#issuecomment-557563779.
Effectively, the response from ntp can sometimes contain UTF-8 characters and this would cause the ntp plugin to crash. This is because the message is put through the `str` function and this isn't expecting UTF-8 characters in Python 2. However, the debugging should be able to handle UTF-8 strings. Using the `unicode` function fixes this issue, but this function has been removed in Python 3 because UTF-8 is the default and `str` is sufficient. Therefore, I've added a helper which will try `unicode` and if it doesn't exist, fall back to `str`.
An alternative would be to use …
=> Do not crash when logging UTF-8 data in Python 2

collectors/python.d.plugin/smartd_log/smartd_log.chart.py
Fixes: #7383
[/collectors/python.d.plugin/smartd_log](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/smartd_log)
[Reallocated Sectors Count](https://www.stellarinfo.com/blog/how-to-fix-reallocated-sector-count-warning/)
> the reallocated sector—also known as bad sector or bad block—is an area on the disk that is no longer safe to store data. When a system can’t read, write, or verify data stored at a particular sector, it marks the sector bad and reallocates or remaps the stored data to a reserved area (spare area) on the hard drive. The reserved area is set aside by the disk for normal operation of the drive and to prevent immediate data loss due to bad sectors.
> There is no ‘fix’ for reallocated sector count warning other than cloning the affected drive with …
=> smartd_log: change ATTR5 chart algorithm to absolute

packaging/installer/README.md
Fixed a typo and freed some markup from an extraneous code block, improving readability.
?
Before: ![Before SS](https://user-images.githubusercontent.com/6709544/69592670-f9783e80-0ff6-11ea-9903-11b73d0c2ede.png)
After: ![After SS](https://user-images.githubusercontent.com/6709544/69592673-fda45c00-0ff6-11ea-8e01-1217f68ab117.png)
=> Fix typo and markup in packaging/installer README

CMakeLists.txt, Makefile.am, collectors/all.h, collectors/cgroups.plugin/sys_fs_cgroup.c, collectors/proc.plugin/README.md, collectors/proc.plugin/plugin_proc.c, collectors/proc.plugin/plugin_proc.h, collectors/proc.plugin/proc_pressure.c, collectors/proc.plugin/proc_pressure.h, web/gui/dashboard_info.js
Add [PSI](https://www.kernel.org/doc/html/latest/accounting/psi.html) monitoring to proc.plugin. Fixes #5901.
collectors/proc.plugin
This is WIP because:
Things I'd like to make sure before continuing:
```
% python                   
Python 3.7.4 (default, Oct  4 2019, 06:57:26) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> open('/proc/pressure/cpu', 'rb').read()
b'some avg10=3.22 avg60=4.15 avg300=4.07 total=11747246754\n'
```
Is this intended or is it a bug? Currently, I'm using `lines > 2` to workaround this behavior. What would be a better way to handle this?
<details><summary>Screenshot</summary>
</details>
=> proc.plugin: add pressure stall information

collectors/python.d.plugin/monit/monit.chart.py
Fixes lgtm warning from #7385
Rule is
> https://lgtm.com/rules/9990086/
It is a recomendation, in our specific case we could ignore it because it is more false positive then not, but in general it sounds good and there is no reason to no apply it imo.
[/collectors/python.d.plugin/monit](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/monit)
=> monit: overwrite __eq__, __ne__ in child classes (lgtm warnings)

.travis.yml
Remove CentOS 6 package building and lifecycle tests
Travis CI
A decision has been made to stop producing packages for CentOS 6, due to missing libuv1 package. This PR adjusts our the CI/CD pipeline.
=> .travis.yml: Remove CentOS 6 package building and lifecycle tests

.remarkrc.js, web/gui/dash-example.html, web/gui/main.js
Fixes javascript lgtm warning from #7385
1 error silenced: https://lgtm.com/rules/1979240340/
because it's a false-positive - LGTM thinks that redirect is caused by user input (sees the `event` property), but actually it only comes from iframe.
The rest is just lint (semicolons added) and unused code removal
web
=> address lgtm alerts

docs/generator/checklinks.sh
In migrating over my big tutorial over to the existing docs site I noticed that the current `checklink.sh` script doesn't very much like when a header has an apostrophe in it.
For example, the following anchor link and heading don't work together:
```
[this is an anchor link to the heading below](#lets-try-this-test)
```
This tweak to the line cuts out apostrophes, the same way it cuts dashes, from the checking logic so the script can properly verify that the heading exists.
docs
=> Docs: Change build process to allow apostrophes in headers

.gitignore
When building the docs, and the build fails due to some reason (like broken links), all the files created by the `buildhtml.sh` script in the `docs/generator/doc` folder start getting tracked by Git, in addition to the `doc/generator/localization/` folder. I then I have to unstage everything and `rm -rf` the localization folder to have a clean slate to work from when committing my actual work.
These two additions should streamline the process of building docs locally without losing information, as those directories are always cleaned up during a successful build.
.gitignore
docs
=> Add docs generator directories to .gitignore

daemon/Makefile.am, daemon/commands.c, daemon/get-kubernetes-labels.sh.in, daemon/main.c, database/rrd.h, database/rrdhost.c, web/api/web_api_v1.c
- Get labels from the kubernetes pod (all of #7411). Note that **there are test return values** in  ` daemon/get-kubernetes-labels.sh.in`, so we can all test the process, regardless of whether we run in k8s. 
- Execute reload_labels at startup
- Log labels in reload_labels
- Output labels when reloading from the command CLI
- Add info to commandcli help
- Fix enums
- enum to text translation for the log messages
There is one improvement I'd like to make, get back and process the exit code of the executable, so I can present an ERROR message when it exits with 1. Right now, I only output lines not matching the pattern, if the error message for jq contained a ':' in it, it would be considered a label. 
If you don't see anything seriously wrong I suggest you merge and I can add more fixes in …
=> Add k8s labels and other label-related additions

database/engine/rrdengineapi.c
Fixes #7468 
Fixes false positive "10min dbengine global flushing errors" alert.
=> Fix dbengine dirty page flushing warning

collectors/python.d.plugin/rabbitmq/rabbitmq.chart.py
Fixes: #7218
`handle_disabled_disk_monitoring` uses `isinstance(obj, str)` to check if disk_free value is string, it doesnt work in py2, because value is unicode.
[/collectors/python.d.plugin/rabbitmq](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/rabbitmq/)
=> rabbitmq: fix handle_disabled_disk_monitoring

health/health.d/softnet.conf
Missing parenthesis in alarm: 1min_netdev_backlog_exceeded
Fixed typo for missing closing parenthesis.
health.d/softnet.conf
=> Fix missing parenthesis on softnet.conf

collectors/python.d.plugin/sensors/sensors.chart.py
Currently `sensors` module does only `sensors.init()` in `check` and returns `True` if there is no error. 
https://github.com/netdata/netdata/blob/7953472f1190b96c46ce3180c935bdcc9b5d2717/collectors/python.d.plugin/sensors/sensors.chart.py#L156-L165
It is not enough to be sure module can get some data.
Solution is to invoke `get_data` at the end of the `check` and see if it returns any data.
[/collectors/python.d.plugin/sensors](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/sensors)
=> sensors: check fix

.gitignore, database/rrdhost.c
Fixes #7460
For I do not do two PRs for kubernets, considering that both are small, I am also bring a change inside `rrdhost.c` that check whether a label is valid before to add it to the link list.
Database
=> Check valid label inside kubernet and .gitignore

database/engine/pagecache.c, database/engine/rrdenglocking.c
Fixes #7440
Fix rare race condition that can cause memory corruption.
=> Fix race condition with page cache descriptors

.travis.yml
Add timestamps to travis output. These timestamps can be invaluable in helping with debugging timing issues.
.travis.yml
[Test build](https://travis-ci.org/knatsakis/netdata/builds/605954639) with timestamped output of various build stages
=> .travis.yml: Add timestamps to output

database/rrdcalc.c, database/rrdcalc.h, database/rrdcalctemplate.c, database/rrdcalctemplate.h, database/rrdhost.c, health/REFERENCE.md, health/health.c, health/health_config.c, libnetdata/simple_pattern/simple_pattern.c, libnetdata/simple_pattern/simple_pattern.h
Closes #7369 
This PR brings the labels feature to alarms.
Health
While I was developing, I used the following alarm
```
alarm: dev_dim_template_user
on: system.cpu
os: linux
lookup: sum -3s at 0 every 3 percentage of user
units: %
every: 1s
crit: $this > 4
label: label1 = 123 
```
and I changed `netdata.conf` to 
```
[host labels]
label1 = 123
label2 =456
label3= 789
```
I executed the following tests:
1 - I run netdata to confirm I had alarms.
2 - change `label1 = 123 ` to invalid value `label1 = 123456`, I cannot have alarms
3 - Use only the label name  inside `label:`, for example, `label1` I will have alarms again.
4 - Use simple patterns with `label:`, for example `label*` instead `label1`
5 - Change the previous lookup line for one with `foreach`:
`lookup: sum -3s …
=> Labels to alarms

daemon/get-kubernetes-labels.sh.in, database/rrdhost.c
Fixes #7411 
- Add check for script exit code and handle it appropriately (logging, freeing)
- Fix length check for label value 
- Add log message when a label is ignored due to invalid name
- Remove test return values for the script
- Convert "Attempting to" msg from info to debug
=> Finalize kubernetes labels

.travis/package_management/common.py, .travis/package_management/configure_deb_lxc_environment.py
Debian Jessie only ever had libuv1 as a backport, not part of the base
release. This means that we need the backports repository on Jessie for
the build to work, which has been archived.
This updates the environment prep script for building Debian packages
for Jessie to inject a file into `/etc/apt/sources.list.d` to add in the
archived repository so that everything works correctly.
areas/ci
Fixes: #7492 
This is realistically a quick hack calling out to a shell to inject a file using the `echo` builtin and shell redirection. I am not exactly an expert at Travis, and did not see any better approach from a quick look at the docs either, but I may have missed something that would allow this to be much cleaner.
=> Inject archived backports repository on Debian Jessie for CI package builds.

netdata.spec.in
This adds the `netdatacli` binary to the RPM spec file for Netdata, fixing the current RPM package build failures.
area/packaging
Sample successful build with this change: https://travis-ci.org/Ferroin/netdata/jobs/624291381
=> Update Netdata RPM spec file to package netdatacli.

packaging/docker/build.sh
Docker, for reasons I cannot fathom, insists on all image tags not having any uppercase letters. This has not been an issue thus far as everyone who is doing automated CI builds of Netdata has a lowercase username on GitHub, as well as their forked repo having a lowercase name. I, however, don't meet that first criteria (my username starts with a capital letter), meaning that when I try to run CI builds on my fork of the repo, I get failures on the docker build step that look like this: https://travis-ci.org/Ferroin/netdata/jobs/624140530.
This updates the script used for the docker builds to force the repository name to lowercase on expansion as part of the tag (utilizing Bash 4's `${foo,,}` expansion syntax), preventing this from being an issue.
areas/ci
areas/packaging
Strictly …
=> Force the repo name to be lowercase in the tag for docker builds.

packaging/installer/netdata-uninstaller.sh
The `-f` option forces removal of a group even if it is the primary group for a user. We should not be using this option for three reasons:
* It's not universally supported. Gentoo, for example, does not provide a version of `groupdel` with this option.
* We shouldn't need it. Short of unusual user configurations, the `netdata` user should be the only one who has a primary group of `netdata`, and we remove the `netdata` user before trying to remove `netdata` group.
* In the unlikely event that the above point is not the case on a given system, removing the `netdata` group will actually break things.
area/packaging
Fixes: #6348
=> Remove `-f` option from `groupdel` in uninstaller.

libnetdata/config/appconfig.c
While integrating the new exporting engine into Netdata we changed configuration parsing rules for the `[backend]` section in the `netdata.conf`. This change is not actually useful so we reverting it.
Fixes #7527
backends
=> Fix backend config

daemon/main.c, daemon/unit_test.c, daemon/unit_test.h, database/engine/pagecache.c, database/engine/pagecache.h, database/engine/rrdengine.c, database/engine/rrdengineapi.c, database/engine/rrdenglocking.c
Fixes #7440
Fix race condition in dbengine and add reproduction support in stress test.
=> Fix race condition in dbengine

collectors/proc.plugin/proc_pressure.c
Also increment `fail_count` if read fails.
proc.plugin > proc_pressure
This is an improvement to the behavior seen in #7531.
=> proc_pressure: increment fail_count on read fail

.travis.yml
Fedora 31 has been out for roughly 2.5 months (release date was 2019-10-29). It's about time we add package generation and publishing for it to CI.
area/packaging
Sample build results: https://travis-ci.org/Ferroin/netdata/jobs/624623473?utm_medium=notification&utm_source=email
I've not rigorously tested that the generated RPM works perfectly, but it appears to install correctly, and it looks like it runs, collects data, and serves the Web UI correctly. However, it would be good to have som additional testing of this before merging. Note that I've only tested the amd64 package (I don't have an arm64 system I can test against).
=> Add Fedora 31 CI integrations.

.travis.yml
The `matrix` key is officially deprecated and gets auto-merged with the `jobs` key during config parsing.
If this auto-merging occurs, then the config will fail config validation, which will in turn cause odd failues during the build because of how Travis handles config validation (namely, it falls back to a default config for the detected language).
This change allows us to enable the Config Validation feature in Travis, which will in turn cause the build to fail very quickly if the configuration is invalid in some way.
area/ci
Successful test build with this change: https://travis-ci.org/Ferroin/netdata/builds/625727800
This is based on discussion with @knatsakis in Slack when I ran into issues setting up Travis for my fork and discovered that the main repo does not have config …
=> Merge the matrix and jobs keys in Travis config.

packaging/docker/Dockerfile, packaging/docker/run.sh
In container runtime with arbitrary user (e.g. [Openshift](https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines)) there are permission problems when trying to start. These changes will make the image runnable as any arbitrary user, as long as this user belongs to root group.
Docker image
This is necessary in Kubernetes/Openshift environments with much restricted Security contexts. In Openshift, images run as a very high user id (e.g. 94000334) and group 0. Without the changes in this PR, we would need to extend and maintain a custom image with just the permission changes.
I'm aware of https://docs.netdata.cloud/docs/netdata-security/#netdata-directories, but maybe in Docker environment this might need a review. …
=> Make the docker image to run as arbitrary user

health/health.c
Fixes #7477 
As it was correctly pointer for our user, the error message that Netdata is giving is not properly an error, because nobody used the API so the file is not present. The correct would be to give an information about what Netdata will do.
Health
=> silencers_info: Change error to info

docs/Running-behind-apache.md
Issue #7568 resurfaced an issue that Netdata's dashboard has with Apache's `mod_evasive` module, which protects from DDoS attacks. Because accessing the dashboard creates a high volume of requests, the module's default config gets the user blocked pretty quickly.
This PR adds text to the Apache proxy guide to give notice about this module and tell users to edit their `mod_evasive.conf` file to mitigate the issue.
docs
=> Docs: Add notice about mod_evasive to Apache proxy guide

.github/CODEOWNERS
Using @netdata/automation in CODEOWNERS does not work the way we want it to, so switching back to individual team members
CODEOWNERS
In particular, any team member's review counts as a review from the whole team. (GitHub says: 'xxx reviewed on behalf of @netdata/automation') which is not what we want, especially when a team member is reviewing another member's PR.
=> CODEOWNERS: Replace @netdata/automation with individual team members

.travis.yml, .travis/README.md, .travis/run-unit-tests.sh
Our current unit testing takes almost 20 minutes on average during the CI process, which is almost twice as long as any other step, and it's only going to get longer as we get better test coverage.
This commit slightly alters how we handle unit testing during CI so that only those unit tests which are actually needed get run.
This is achieved by using the `$TRAVIS_COMMIT_RANGE` environment variable provided by Travis to determine which commits we're actually testing, and then using that information to query Git for what files actually changed.
As of right now, the only unit testing we're doing is in the dbengine code, so we check to see if any of 
those files or the C unit testing files are modified by the PR and only runs the unit tests for those if they were modified. The checks are a …
=> Skip unit testing during CI when it's not needed.

collectors/proc.plugin/proc_stat.c, daemon/commands.c, database/engine/rrdengineapi.c, exporting/init_connectors.c, libnetdata/threads/threads.c, libnetdata/threads/threads.h
Using the same logic as libnetdata' `thead_set_name()`, we should set the name of the other threads.
Implementing `uv_thread_set_name` within libnetdata for libuv threads
Came from issue #7531 / [comment #566285792](https://github.com/netdata/netdata/issues/7531#issuecomment-566285792) 
- libnetdata/threads/
- exporting
- database/engine
- daemon/command
- collector/proc.plugin/proc_stat
Generated output: 
```
1886  1886 17848 netdata         ./netdata -D
1886  1896 17848 DBENGINE        ./netdata -D
1886  1897 17848 PLUGIN[proc]    ./netdata -D
1886  1898 17848 PLUGIN[diskspac ./netdata -D
1886  1899 17848 PLUGIN[cgroups] ./netdata -D
1886  1900 17848 PLUGIN[tc]      ./netdata -D
1886  1901 17848 PLUGIN[idlejitt ./netdata -D
1886  1902 17848 STATSD          ./netdata -D
1886  1905 17848 …
```
=> Set standard name to non-libnetdata threads (libuv, pthread)

netdata.spec.in
The newly added `netdata-claim.sh` script was not added to the RPM spec file, which was causing the RPM build to fail due to the presence of an 'installed but unpackaged' file.
This adds the script to the specfile, which fixes the build process.
area/packaging
=> Add netdata-claim.sh to the RPM spec file.

docs/Running-behind-apache.md
This pull request adds additional documentation as requested by #7578. The documentation contains how to properly configure the `DOSPageCount` from the `mod_evasive` apache module for a virtual host.
docs
=> Docs: add configuration details for vhost about DOSPageCount to Apache proxy guide

collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py, collectors/python.d.plugin/python_modules/bases/collection.py
fixes: https://github.com/netdata/netdata/issues/3656#issuecomment-567931801
`/collectors/python.d.plugin/python_modules`
I tested, with the changes `httpcheck` module works with `https://google.ru` URL in both py2 and py3.
=> python.d.plugin: UrlService bytes decode, logger unicode encoding fix

CMakeLists.txt, backends/prometheus/remote_write/remote_write.cc, configure.ac
`ByteSize()` is deprecated. `ByteSizeLong()` should be used instead.
backends
=> Fix a warning in prometheus remote write backend

collectors/python.d.plugin/python_modules/bases/collection.py
Fixes: #7613
`/collectors/python.d.plugin/python_modules`
=> python.d logger: do not unicode decode if it is already unicode

collectors/python.d.plugin/redis/redis.chart.py
Fixes: #7635
Following stats appear in the redis `INFO` output only if there are some keys in the database.
```console
db0:keys=2,expires=0,avg_ttl=0
```
We need to check this stats on every iteration. If there is new db we add dimension to the `keys_redis` chart.
`/collectors/python.d.plugin/redis`
i tested the PR, it works (tests: set key via `redis-cli` in runtime, remove key, etc.).
=> redis: populate `keys_redis` chart in runtime

libnetdata/threads/threads.c
Reduce log for `uv_thread_set_name_np` from `error` to `info`.
Thread renaming is not a requirement, but ease bug reporting. On bug #7644 for an unknown reason, libuv could not rename its threads on CentOS6. So the logs showed an error log that was reported.
- libnetdata/threads/thread.c
=> [libnetdata/threads] Change log level on error

.travis.yml
This adds a check to prevent the 'Support activities on main branch' stage from running on forked repos. In such repos, it will automatically fail without special effort from the user, requiring them to carry local patches on their master branch.
Without this, CI builds of the 'master' branch will fail for users who do not go through the effort of setting up the custom patches to disable this stage in their repo.
area/ci
Sample build on a forked repo that demonstrates the issue this is fixing: https://travis-ci.org/Ferroin/netdata/builds/624598589
Sample build on the same repo with this commit on the master branch: https://travis-ci.org/Ferroin/netdata/builds/625732675
I can't really test that this won't break the stage on the master branch of the main repo, but I've validated the …
=> Limit 'support activities on main branch' to main repo.

collectors/proc.plugin/proc_stat.c
Reported by #7626 on Docker, this segfault occurs with cpuidle plugin.
The name setting was set after a pthread_join, thus occuring after the
thread was terminated. While glibc handles this correctly, musl segfault
- collectors/proc.plugin/proc_stat.c
Reverts [2dc0170](https://github.com/netdata/netdata/commit/2dc0170)
=> [Fix] remove pthread_setname_np segfault on musl

health/REFERENCE.md, health/health_config.c
Fixes #7599 
This PR brings the necessary changes for Netdata to have `host labels` instead `label` parsed on alarms.
Health
During the development, I created few labels inside my netdata.conf in the new setion `[host labels]`, after this I ran `cp tests/template_dimension/system_cpu.conf.unique_alarm /etc/netdata/health.d/system_cpu.conf` and I inserted the labels for each alarm, the labels were defined following these steps:
- All alarms with the same label defined using `host labels:`
- Different labels for each alarm, here I also used valid labels.
- Change the labels to invalid values inside the alarm, but I kept one with correct values.
=> Adjust alarm labels

netdata-installer.sh, packaging/installer/README.md, packaging/installer/netdata-updater.sh
As per the bug report in #6863, we had to extend netdata-installer.sh functionality so that a user is able to also pass LDFLAGS when running the installer.
We updated also the MacOS documentation to instruct the user what he should to in order to get SSL enabled on Mac.
The reason we followed this approach is because we didn't want to make non-standard changes on our compilation method and based on the following information from openssl on Mac, this looked like the best solution
```
$ brew info openssl
openssl: stable 1.0.2s (bottled) [keg-only]
SSL/TLS cryptography library
https://openssl.org/
/usr/local/Cellar/openssl/1.0.2s (1,795 files, 12.0MB)
Poured from bottle on 2019-06-26 at 18:23:08
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl.rb
==> Caveats
A CA …
```
=> netdata/installer: Make netdata installer more flexible, to accommodate install with ssl on MacOS

collectors/python.d.plugin/python_modules/bases/FrameworkServices/ExecutableService.py, collectors/python.d.plugin/samba/samba.chart.py
Fixes: #7651
We want to be sure we are allowed to run command with sudo before executing it.
Old approach:
- `sudo -v`
Is not good, see https://github.com/netdata/netdata/issues/7651#issuecomment-570163063
After this PR:
- execute `sudo -n -l COMMAND`, read output, compare output with `COMMAND`
[`/collectors/python.d.plugin/samba`](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/samba)
@camjesus2 could you test it?
- `git clone https://github.com/ilyam8/netdata --branch=samba_check_fix netdata_samba_fix`
- `cd netdata_samba_fix`
- install netdata
- check the dashboard
=> samba: properly check if it is allowed to run smbstatus with sudo

packaging/docker/Dockerfile
Add freeipmi support to the docker image.
docker container (netdata/netdata)
Also speed up docker build by copying dependencies instead of installing them, which eliminates the need to install make and alpine-sdk apk only to run make install for judy and then remove them, which takes a good amount of time.
=> feat(docker): Add freeipmi support

database/rrdvar.c, health/health_json.c, web/api/formatters/charts2json.c, web/api/formatters/json_wrapper.c, web/api/formatters/rrdset2json.c, web/api/netdata-swagger.json, web/api/netdata-swagger.yaml, web/api/web_api_v1.c
Host labels were deleted from
Fixes #7615
web
=> Clean up host labels in API responses

backends/backends.c, backends/backends.h, configure.ac, exporting/read_config.c
"Prometheus" was spelled wrong. The misspelling in configure.ac caused #7673
Prometheus
=> Fix spelling of Prometheus (#7673)

packaging/installer/functions.sh, packaging/installer/netdata-uninstaller.sh
This improves the logic in the update and uninstall scripts used for kickstart installations so that they more reliably stop the Netdata agent process. This will help mitigate the impact of bugs in the shutdown code for the agent itself.
area/packaging
Fixes: #7585 
Fixes: #7248 
Fixes: #7320
---
The new logic is intended to work like so:
1. If we can find `netdatacil` in `$PATH` and there appears to be an agent running, use that to try and shutdown the agent, then wait for 20 seconds before proceeding.
2. For each live Netdata PID, spend up to 60 seconds trying to stop it with SIGTERM, and then up to another 60 seconds trying with SIGKILL if SIGTERM fails.
This can technically still leave a live agent process running, though it is very unlikely. I plan to update the installer and updater …
=> Update handling of shutdown of the Netdata agent on update and uninstall.

CMakeLists.txt, backends/prometheus/remote_write/remote_write.cc, configure.ac
After #7609, where the protobuf version was restricted to 3.1 and newer, Coverity scan fails because only protobuf 3.0.0 is available for the build. Therefore, we are bringing back support for the old version.
Fixes #7679
backends
=> Restore support for protobuf 3.0

packaging/installer/functions.sh, packaging/installer/netdata-uninstaller.sh
This fixes an issue introduced by the merge of #7595 which snuck in due to us not using shellcheck on all scripts.
area/packaging
=> Add missing quoting in shell scripts.

packaging/installer/functions.sh
Plain `[]` does not support pattern matching, only `[[]]`.
area/packaging
The error this is fixing means that the startup script installation does not work on most systems right now when using the kickstart and kickstart-static64 methods.
=> Fix a syntax error in the packaging functions.

.github/workflows/labeler.yml
This updates the access token in the labeler action to use permissions of the netdatabot account instead of using the generic access token provided by GitHub.
This allows the labeling to work correctly even for forks owned by people who do not have write access to the repo.
area/ci
=> Fix PR labeling GitHub Action.

.github/workflows/labeler.yml
This updates the PR labeling via GHA to not depend on the access level of the owner of the PR relative to the repository, which should finally make it work correctly.
area/ci
=> Fix PR labeling (again).

packaging/installer/functions.sh
This includes a couple of simple quality of life fixes for the installer. It ensures that we try to start netdata from the location it was installed to, as well as making the detection of where the `nologin` command is work correctly.
area/packaging
Fixes: #7692 
Fixes: #7687
@thiagoftsm
=> General fixes to the installer.

collectors/python.d.plugin/litespeed/litespeed.chart.py
Add support for different .rtreport format
Some .rtreport files do not contain `MAXCONN` and `MAXSSL_CONN` variables, but simply list the in use connections.
This PR adds support for this by looking for lines starting with `PLAINCONN:` as well.
python.d litespeed
I'm ops @ LiteSpeed Technologies
=> litespeed: add support for different .rtreport format

docs/generator/buildhtml.sh
Explicitly specify which translations to include in the docs localization options.
We need that in order to run a proper test of a new language, before we show the option for it. 
Previously, we automatically added any new languages present in the netdata/localization project, without ensuring that:
- An option for the language appears on the language selection menu
- The links in the new language are valid (`checklinks.sh` script)
docs
Pre-requisite to add support for the Korean translations in https://github.com/netdata/localization/pull/25
=> Control introduction of new languages in docs translation

netdata-installer.sh, packaging/installer/README.md, packaging/installer/kickstart-static64.sh, packaging/installer/netdata-updater.sh, packaging/makeself/install-or-update.sh
This PR makes auto-updating work correctly for installations done using the `kickstart-static64.sh` installer.
It consists of two logical parts:
1. Update handling of the `.environment` file to store only the options to be used for reinstallation instead of the full command. We currently only have two possible 'commands', and they are trivially differentiated based on whether the install is with `kickstart.sh` or `kickstart-static64.sh`, so we don't really need to store the command that was used.
2. Actually enable the currently dead code in `netdata-updater.sh` that handles the case of static installs, and adds some extra support code to make it work correctly.
area/packaging
Fixes: #7197 
Fixes: #7198 
Minimally tested so far (passes CI lifecycle checks without issue), will mark ready …
=> Make auto-updates work on kickstart-static64 installs.

configure.ac
A bug was introduced in #6351. Netlink Connection Tracker charts didn't work because HAVE_LINUX_NETFILTER_NFNETLINK_CONNTRACK_H was not defined after successful checks for `nfacct.plugin`.
Closes #7707 
nfacct plugin
=> Fix a check for nfnetlink_conntrack.h

.github/CODEOWNERS, Dockerfile.docs, docs/contributing/contributing-documentation.md
This is part of a larger body of work related to CI/CD in general where we have decided to use [Docker](https://www.docker.com) to facilitate easier packaging, builds and reproducibility. This PR introduces a new `Dockerfile` specifically for building our documentation.
The intention is to publish this image to our [NetData Docker Hub Org](https://hub.docker.com/netdata) so other maintainers/contributors can also more easily and quickly get going on contributing to our docs.
=> Adds a Dockerfile.docs for more easily and reproducibly building/rebuilding docs

collectors/cgroups.plugin/sys_fs_cgroup.c
Since LXC 3.1.0 there are new directories in lxc hierarchy - `lxc.monitor`, `lxc.payload`, and `lxc.pivot` instead of `lxc`. We need to filter out unuseful directories and containers.
Fixes #6481
cgroups plugin
=> Filter out lxc cgroups which are not useful

web/gui/main.js
On error from `/api/v1/accounts/${cloudAccountID}/agents` call, change the error info in the dropdown in top-left corner, from:
> Cannot load known netdata agents from netdata.cloud!
to
> Cannot load known netdata agents from netdata.cloud! Please make sure you have the latest netdata version.
This is a temporary measure, when we'll update Cloud API in the future, users should have additional info that a breaking change have occurred and they should update Netdata to use new cloud features
Web Dashboard
=> on cloud error, inform user to update their netdata.

.github/workflows/labeler.yml
This limits runs of the PR labeler to the main repo only, which should cut down on noise people get from GitHub.
area/ci
Tested on personal fork that this prevents the labeler from actually trying to do anything, as well as verifying that it does indeed match repos correctly.
=> Limit PR labeler runs to the main repo.

packaging/installer/README.md, packaging/installer/functions.sh, packaging/installer/kickstart-static64.sh
Fixes support for SystemD based systems with a read-only `/lib` such as CoreOS where only `/etc` is writeable and thus the `SYSTEMD_DIRECTORY` should be `/etc/systemd/system`. This PR finally makes netdata work correctly on such systems.
Fixes #5558 
And finally Fixes #68 proper.
Packaging
There are still some warnings/errors on installation; but I will handle those separately. I can confirm the NetData against is successfully installed, running and the Web interface operational:
```bash
core@localhost ~ $ bash <(curl -s http://10.0.0.104:8000/kickstart-static64.sh) --non-interactive
--- Installation sources were given as input, running installation using "/home/core/netdata-v1.19.0-305-g26abdeab.gz.run" ---
[/tmp/netdata-kickstart-Qv8laH]$ cp …
```
=> Fixes support for read-only /lib on SystemD systems like CoreOS in  kickstart static64

contrib/debian/changelog
As per the [Debian Policy Manual, section 4, sub-section 4](https://www.debian.org/doc/debian-policy/ch-source.html#s-dpkgchangelog), the trailer line containing the maintainer information and the date in the changelog file must have a single space preceding the two dashes that mark the start of the line.
This fixes warnings in the package build process, as well as enabling the builds to work with older more pedantic versions of dpkg-buildpackage.
area/packaging
This is required for successful builds on Ubuntu 18.04 and 16.04 with the new package builder images added by https://github.com/netdata/helper-images/pull/32
=> Fix the formatting of the trailer line in the Debian changelog template.

web/api/netdata-swagger.json, web/api/netdata-swagger.yaml
The [`variables`](https://docs.netdata.cloud/backends/prometheus/#netdata-host-variables) parameter in the `/api/v1/allmetrics` call was missing from the API documentation in the Swagger Editor.
web API
=> Add a missing parameter to the allmetrics endpoint in Swagger Editor

daemon/commands.c, packaging/installer/netdata-uninstaller.sh
Fixes #7734 
When netdata fails to delete any pre-existing unix domain sockets due to permission or other reasons it should gracefully disable the command server. Moreover, the uninstaller should help clean up given sufficient permission.
=> Fix libuv IPC pipe cleanup problem

web/api/formatters/ssv/README.md
Minor typo fix in the SSV formatter (probably originally introduced through copy-paste)
=> Fix CSV -> SSV in docs

tests/installer/checksums.sh
Similar to #7714 this further reduces noise in our #automation Slack Channel so we do not receive notifications from failed checksum failures in PR(s) where it would fail the CI check and resulting PR would be blocked anyway.
Its very important for SRE that alarms and notifications are as high signal as possible and actionable :)
Automation / Alerting / CI
=> Do not alert the #automation channel on checksum failures that will fail a PR in CI anyway

packaging/makeself/build-x86_64-static.sh
This is just a little PR to cleanup and remove the use of `sudo` of the script used to build/rebuild the self-extracting tarballs we use in the `kickstart-static64.sh` installer.
Couple of things here:
- Use POSIX Sh here `#!/bin/sh` as we're not really using any Bash(isms) anyway and its a simple script
- Remove the use of `sudo`; mostly used in `sudo docker ...` which is not necessary as typically you would have read/write permissions to the Docker daemon UNIX socket on your system (_if you don't; you should!_)
- One less thing run as root
Packaging
On first run (_wasn't able to repro again_) `tar` complains it cannot find `bash-4.18.4/ChangeLog` despite it actually being available on the file system when this script is executed.
=> Cleanup packaging/makeself/build-x86_64-static.sh to use /bin/sh and remove use of sudo

packaging/installer/netdata-updater.sh
This was left over from testing, and I forgot to remove it before merging the changes needed to make the updater work for static installs.
area/packaging
Fixes: #7779
=> Remove unnessecary `echo` call in updater.

packaging/installer/functions.sh
Fixes support for isntalling NetData Agent (_from source_) by fixing our
invocations of `sed -e ... -i`. Specifically the version of `sed` on BSD
systems don't handle parsing command-line arguments the same way as GNU Sed
and so `sed -e ... -i <file>` gets interpreted incorrectly.
Be sure to use the form `sed -i -e ... file` :D
TODO: Write/Create a CI linter to protect outselves from this in future?
Fixes #7788
area/packaging
I've confirmed the correct behaviour of both BSD and GNU `sed` and to be
consistent and portable we should use the form `sed -i -e ... file` and *not*
`sed -e ... -i file`.
=> Fixes install on FreeBSD systems with non GNU sed (do't use -i)

.github/workflows/reviewdog.yml
Fixes #7793 by introducing `shellcheck` checks against changed shell scripts `*.sh*` in PR(s) via [reviewdog](https://github.com/reviewdog) which has support for quite a few Github Actions we can utilise.
area/ci
Due to security limitations of Github Actions it is not possible to use the IHMO nicer `github-pr-review` reporter on our triangular forking model. See [this section](https://github.com/reviewdog/reviewdog/blob/9abb5e45a11e4e3826a7ccc5cba82d21cef465c8/README.md#graceful-degradation-for-pull-requests-from-forked-repositories) in the reviewdog README.
=> Adds reviewdog/shellcheck to CI via Github Actions on changed shell scripts in PRs

collectors/node.d.plugin/node_modules/net-snmp.js, collectors/node.d.plugin/snmp/README.md, collectors/node.d.plugin/snmp/snmp.node.js
Fixes: #1363
SNMPv3 support is merged to the library we use in `snmp` collector
> https://github.com/netdata/netdata/issues/1363#issuecomment-574898634
The change is pretty trivial, according @markabrahams
> There's only one new public API call added to the net-snmp library:
snmp.createV3Session(target, user, [options])
> which you would call for v3 instead of snmp.createSession(target, [community], [options]) for v1 or v2c.
[`node.d.plugin/snmp`](https://github.com/netdata/netdata/tree/master/collectors/node.d.plugin/snmp)
i dont think we really need to test snmpv3 since it would be testing the library.
=> node.d/snmp: snmpv3 support

netdata.spec.in
Purpose of this pull request is to separate the installation and dependency management for free IPMI from the core netdata package and create netdata-plugin-freeipmi
Changes in this PR:
1) Update spec file to split freeipmi binary to sub-package `netdata-plugin-freeipmi`
2) Fix permission to be 4750 just like we do through our netdata installer
netdata/collectors
References #6907 (It will close once we deliver the DEB version also)
=> netdata/packaging: split free IPMI for RPM

docs/generator/buildhtml.sh, docs/generator/custom/themes/material/partials/header.html
Thanks to @wonsangki we have some docs translated to Korean in https://github.com/netdata/localization/pull/25
This PR adds those pages to docs.netdata.cloud
docs
Verified locally that we have no broken links, the translation itself will need to be checked.
=> Add Korean translation to docs

CMakeLists.txt, Makefile.am, exporting/init_connectors.c, exporting/tests/netdata_doubles.c, exporting/tests/test_exporting_engine.c
#7584 broke unit tests for the exporting engine. We should wrap `uv_thread_set_name_np` to make the tests work again. 
=> Fix unit tests for the exporting engine

.travis.yml
This allows us to control whether nightly builds run based on the presence or absence of an environment variable, instead of requiring us to remove and then re-add a scheduled build job. The primary advantage to using this approach is that nightlies will run at the same time each day, instead of moving to whenever they happen to be re-enabled.
The variable in question is named `RUN_NIGHTLY`, and must be defined with a value of 'yes' for nightly builds to run.
When this is merged, I will open a PR to update the release process documentation to reflect this change.
area/ci
When an environment variable is not present, Travis will expand it to an empty string just like POSIX sh does, thus ensuring the check will fail if the environment variable is not defined.
=> Add an environment variable check to Travis configuration to allow disabling nightlies.

contrib/debian/netdata.postrm
Fixes #6933
As per discussion in team meeting. We should not remove users/groups in Debian postrm.
area/packaging
=> Don't remove groups/users in Debian postrm

packaging/installer/functions.sh, packaging/installer/netdata-uninstaller.sh
This updates the installer and uninstaller to attempt to use the system service management interface to shut down netdata when running as root.
This will allow us to properly shut down Netdata from the perspective of the system service manager, thus avoiding cases where it gets restarted immediately.
If this step succeeds, we wait 20 seconds before checking for a successful shutdown. If the shutdown was unsuccessful or this step failed, we continue with the same logic we already had, first attempting to use `netdatacli` and then falling back to direct usage of signals for shutdown.
area/packaging
Minimally tested to verify that it doesn't break the build and that the correct code gets run on systemd, OpenRC, and classic init.d based systems. I do not have a system immediately available to …
=> Attempt to use system service manager to shut down Netdata.

collectors/python.d.plugin/retroshare/README.md
[Formatting python.d modules code](https://github.com/netdata/netdata/pull/7832) i noticed that `restroshare` module readme file is empty. This PR fixes it.
[`/collectors/python.d.plugin/retroshare`](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/retroshare)
=> python.d/retroshare: add readme

.github/workflows/reviewdog.yml
Similar to #7795 adds CI check for JavaScript source code in Pull Requests
(_changed only_).
area/ci
We will remove a lot of the Travis CI checks that do the same thing once we're
happy enough with the way reviewdog CI checks against changed files
in PR(s) work.
=> Adds ReviewDog CI checks for JavaScript

.github/workflows/reviewdog.yml
Similar to #7795 adds CI check for Golang source code in Pull Requests
(_changed only_).
area/ci
We will remove a lot of the Travis CI checks that do the same thing once we're
happy enough with the way reviewdog CI checks against changed files
in PR(s) work.
=> Adds ReviewDog CI checks for Golang

.travis.yml
-fno-common will be set by default in GCC 10, see https://gcc.gnu.org/PR85678
Therefore, netdata should test with that configuration to be ready for this change.
See https://github.com/netdata/netdata/issues/7869
=> .travis.yml: Add -fno-common to CFLAGS

netdata.spec.in
Fixes the `Source0` URL in the `netdata.spec.in` RPM spec file.
Adds the missing `v` prefix to the version strings.
Fixes #7141 
area/packaging
=> Fixes Source0 URL in RPM spec

daemon/anonymous-statistics.sh.in, daemon/main.c, docs/anonymous-statistics.md, netdata-installer.sh, packaging/docker/Dockerfile, packaging/docker/run.sh, packaging/installer/kickstart-static64.sh, packaging/installer/methods/kickstart-64.md, packaging/makeself/install-or-update.sh, packaging/makeself/makeself-help-header.txt, web/server/web_client.h
As per title
- Fixes #7366
- Fixes #7401
- Fixes #7404
area/packing
- Depends on #7847
=> Adds support for opting out of telemetry via the DO_NOT_TRACK envirnment variable

packaging/installer/methods/packages.md
This adds some basic documentation about how to use our package repositories through caching proxies, since PackageCloud's configuration doesn't really do anything to properly support it.
Relevant to: #7905
area/docs
area/packaging
=> Add docs about using caching proxies with our package repos.

health/QUICKSTART.md, health/tutorials/stop-notifications-alarms.md
Fixes #7855 
I've moved the section about editing to the top, and tried to emphasize in multiple places that users should not edit files in `/usr/lib/netdata/conf.d`, as they're only for reference.
@manos-saratsis Let me know if this helps clarify your questions! I figure this issue is done when the doc addresses your specific concerns.
docs
=> Clarify editing health config files in health quickstart

web/api/badges/README.md, web/api/badges/web_buffer_svg.c, web/api/badges/web_buffer_svg.h, web/api/netdata-swagger.json, web/api/netdata-swagger.yaml
Fixes #7791 - request of user to be able to specify color of the text in badge
__Additionally__
Fixes problem where the custom color given to `label_color` was ignored using both `#RRGGBB` and `RRGGBB` syntax (in contrast with specification in documentation which allows this).
Unifies all `/color/` values with same syntax. 2 options:
- one of predefined colors
- custom color specified as hex in `RGB` or `RRGGBB` format *(without preceeding `#` char)*
agent `api/v1/badge.svg` and related documetation
color can be specified with HEX value as in HTML without `#` character in the beggining. Either in `RGB` or `RRGGBB` format
=> add possibility to change badge text font color

netdata-installer.sh
This fixes an issue in plugin ownership introduced by #7632.
area/packaging
Fixes: #7922
=> Set ownership correctly for plugins in netdata-installer.sh

daemon/anonymous-statistics.sh.in, netdata-installer.sh, packaging/docker/run.sh, packaging/installer/kickstart-static64.sh, packaging/installer/methods/kickstart-64.md, packaging/makeself/install-or-update.sh
Fixes #7921
As per title. How embarassing 🤦‍♂️
area/packaging
None
Before:
```sh
$ DO_NOT_TRACK=; if [ ! "$DO_NOT_TRACK" -eq 0 ] || [ -n "$DO_NOT_TRACK" ]; then echo "foo"; fi
-bash: [: : integer expression expected
```
After:
```sh
$ DO_NOT_TRACK=; if [ ! "${DO_NOT_TRACK:-0}" -eq 0 ] || [ -n "$DO_NOT_TRACK" ]; then echo "foo"; fi
```
=> Fixes a bug in DO_NOT_TRACK expression

collectors/python.d.plugin/varnish/README.md, collectors/python.d.plugin/varnish/varnish.chart.py
Fixes: #7872
This PR adds [SMF metrics](https://varnish-cache.org/docs/trunk/reference/varnish-counters.html#smf-file-stevedore-counters) (cache on disk) collection to the `varnish` python module.
All available stats:
```
SMF.ssdStorage.c_req                      47686         0.51 Allocator requests
SMF.ssdStorage.c_fail                         0         0.00 Allocator failures
SMF.ssdStorage.c_bytes                668102656      7186.06 Bytes allocated
SMF.ssdStorage.c_freed                140980224      1516.37 Bytes freed
SMF.ssdStorage.g_alloc                    39753          .   Allocations outstanding
SMF.ssdStorage.g_bytes                527122432          .   Bytes outstanding
SMF.ssdStorage.g_space              53159968768          .   Bytes available
SMF.ssdStorage.g_smf …
```
=> /collectors/python.d/varnish: collect smf metrics

packaging/docker/Dockerfile
This is required when running Netdata as non-root user.
Docker image file permission.
=> Fix setuid for freeipmi.plugin in Docker images

packaging/installer/netdata-updater.sh
Fixes: #7954
> If n is omitted, the return status is that of the last command executed in the function body.
It returns `1` when running on terminal. 
We need return 0
https://github.com/netdata/netdata/blob/b5d8898ed9fecc62cf10e7522c0e2f1213dc91ac/packaging/installer/netdata-updater.sh#L215-L218
`/packagin/installer`
=> netdata-updater.sh: explicitly return 0 from update

netdata.spec.in
This includes an assortment of minor fixes and cleanups in the RPM spec file:
* Explicitly install the cache and log directories to avoid RPM build warnings/errors on certain systems.
* Build depend on `git-core` instead of `git`, as we don't use anything during the build that isn't in `git-core`.
* Remove the unused netcat build dependency.
The first one fixies an issue that shows up inconsistently when using the package builder docker images.
The other two reduce the build-time dependency footprint so that we don't require users to install as many packages to build the RPM's.
area/packaging
Build tested on all environments we build RPM packages for.
Fixes: #7941
=> Assorted cleanup items in the RPM spec file.

collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py
Fixes: #7953
This PR adds `body` parameter to the URLService based modules. This parameter is used to add body to the http request.
[/collectors/python.d.plugin](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py)
tested by @yasharne 
https://github.com/netdata/netdata/issues/7953#issuecomment-581337631
=> /pythond.d/UrlService.py: add body

packaging/installer/methods/macos.md
The existing macOS installation page is barebones and poorly-formatted—this update makes it more readable and encourages users to install Netdata with Homebrew. I also wanted to include details about where the config/stock config directory ends up, since that's caught me off-guard more than once.
I think the plan is to eventually have our own Homebrew repo with a formulae we supply ourselves, but that's TBD. Maybe @prologic or @Ferroin have some more details on that.
docs
=> Cleanup of macOS installation docs

Dockerfile
Fixes #7899
Usage:
```sh
$ docker build -t netdata . 
$ docker run --rm -p 19999:19999/tcp netdata
```
Or simply:
```sh
$ docker build -t netdata . && docker run --rm -p 19999:19999/tcp netdata
```
Passing installer options:
```sh
$ docker build --build-arg INSTALLER_ARGS="--disable-dbengine" -t netdata .
```
Timeing / Performance:
With Docker's caching and being rather careful here (see: [Best Practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)):
- Nothing Cached: ~1m42s to build/run
- Dependencies Cached: ~42s to build/run
- Everything Cached: ~3s to run (_nothing rebuilt_)
area/ci
area/packaging
Yes this is a little bit of duplication here; but this is a vastly more
simplified `Dockerfile` at the top-level to make the entire dev/test
cycle much faster …
=> Adds new simpler (Alpine based) Dockerfile for quick dev and testing

packaging/DISTRIBUTIONS.md
As per recent PRs, FreeIPMI is now supported in the Docker image.
=> Indicate FreeIPMI supported in Docker image

netdata-installer.sh
Fixes: #7799
netdata-installer
Tests:
download latest if:
skip downloading if:
=> install go.d.plugin only if there is new version

packaging/installer/install-required-packages.sh, packaging/makeself/build-x86_64-static.sh
This was the cause for our nightlies being broken for so long :/
#7725 broke this :/ So sorry :/
area/packaging
🤦‍♂️
**Beofre:**
```sh
prologic@Jamess-iMac
Tue Feb 04 17:12:28
~/NetData/netdata
(master) 0
$ dki -t -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/netdata -w /netdata debian:buster /bin/bash
root@9d864f5524d8:/netdata# ./packaging/makeself/build-x86_64-static.sh
./packaging/makeself/build-x86_64-static.sh: 327: ./packaging/makeself/../installer/functions.sh: Syntax error: "(" unexpected (expecting "then")
```
**After:**
```sh
prologic@Jamess-iMac
Tue Feb 04 17:16:44
~/NetData/netdata
(master) 0
$ dki -t -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/netdata -w /netdata debian:buster /bin/bash
root@f6bb12d81e86:/netdata# ./packaging/makeself/build-x86_64-static.sh …
```
=> Fixes static builds and nightlies

collectors/apps.plugin/apps_groups.conf
samba: added [ctdb](https://wiki.samba.org/index.php/CTDB_and_Clustered_Samba) tools and daemons.
ceph: fixed patterns for cover most of Ceph binaries and crush tools than can eat many of CPU.
Current list of Ceph /bin
```
ceph
ceph-authtool
ceph_bench_log
ceph-bluestore-tool
ceph-client-debug
ceph-clsinfo
ceph-conf
ceph-coverage
ceph-crash
ceph-create-keys
ceph-debugpack
cephdeduptool
ceph-dencoder
ceph_erasure_code
ceph_erasure_code_benchmark
cephfs-data-scan
cephfs-journal-tool
cephfs-shell
cephfs-table-tool
ceph-fuse
ceph_kvstorebench
ceph-kvstore-tool
ceph-mds
ceph-mon
ceph-monstore-tool
ceph_multi_stress_watch
ceph_objectstore_bench
ceph-objectstore-tool
ceph_omapbench
ceph-osd
ceph-osdomap-tool
ceph_perf_local
ceph_perf_msgr_client
ceph_perf_msgr_server
ceph_perf_objectstore …
```
=> collectors: apps.plugin: apps_groups: update ceph & samba collections.

packaging/makeself/build-x86_64-static.sh
For some reason, without `sudo` here, we get permissions issues in CI,so re-add it.
area/packaging
I'm honestly not even sure _why_ we're changing file ownership here. Looking at the git history gives no real insights.
This is, however, what's causing nightlies to fail.
=> Fix permissions issues caused by 986bc2052.

netdata.spec.in
This fixes the issue causing CentOS 7 RPM builds to fai, as well as removing a warning shown on all RPM builds of Netdata.
The issue on CentOS 7 arises from the fact that unless built with `cgo` (which we do not do), Go code compiled using `go build` does not contain debugging information in the format that the RPM build process expects, causing the process to terminate.
By not marking the `go.d.plugin` executable when putting it into the install staging area during the RPM build, we can force the check to be skipped for it, thus avoiding the issue.
area/packaging
Fixes: #7991
=> Fix CentOS 7 RPM build failures.

collectors/charts.d.plugin/ap/ap.chart.sh, collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh, collectors/charts.d.plugin/example/example.chart.sh, collectors/charts.d.plugin/libreswan/libreswan.chart.sh, collectors/charts.d.plugin/nut/nut.chart.sh, collectors/charts.d.plugin/opensips/opensips.chart.sh
Auto format modules, it seems my bash shell linter has (almost) same rules as @prologic 
i changed only 2 things:
- indent switch will be indented
- redirect operator will be followed by a space
I tested it by auto formatting [install-requred-packages.sh](https://github.com/netdata/netdata/blob/master/packaging/installer/install-required-packages.sh) script - zero changes.
[`/collectors/charts.d.plugin`](https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin)
i format following modules:
- ap
- apcupds
- example
- libreswan
- nut
- opensips
Ohter modules will be removed (i hope) after https://github.com/netdata/netdata/pull/7962 is merged.
=> /collectors/charts.d.plugin: format modules

docs/generator/checklinks.sh
Similar to #7431, I found that when you putting parentheses in headings in the documentation you can't link to them using an anchor link. I struggled with this when trying to work on collectors docs with @ilyam8 and #7878.
For example, this pair of anchor link and header will fail during build.
```
[this is an anchor link to the heading below](#lets-try-this-test)
```
This change will cut parentheses from the string when building the anchor tag so it all works OK.
docs
=> Docs: Change sed to allow parentheses in heading links

.travis/trigger_package_generation.sh
We're not actually building any i386 RPM packages, and it makes essentially no sense to do so as the various major RPM-based distros don't even really support 32-bit x86 installs anymore.
This will actually speed up the builds for the other package types because they won't be competing for CI resources. It will also make the commit history tidier in the repo.
area/ci
area/packaging
As far as I can tell, we've never actually built any i386 RPM packages.
Fedora dropped support for 32-bit x86 installs with Fedora 29.
CentOS/RHEL dropped official support for 32-bit x86 installs with RHEL/CentOS 7.0.
OpenSUSE does not appear to support 32-bit x86 installs, but I cannot figure out when they dropped support.
=> Don't pretend we're building i386 RPM packages when we aren't.

collectors/apps.plugin/apps_groups.conf
- added group for column oriented databases - `columndb`
- added `clickhouse-server` to group `columndb`
- added influxd to `timedb` group
=> Update database servers group in apps_groups.conf

health/QUICKSTART.md, health/REFERENCE.md
Fixes #7910 
This PR clarifies the allowed names for `alarm` and `templates`
Heath
=> health_doc_name: Clarify the rules to create an alarm name

docs/generator/buildyaml.sh
Fixes: netdata/marketing#79 (try number 2)
This PR adds `useLastDirAsPageName` option to the `navpart` func. It allows to use last directory name as a page name.
I use this option for python.d and go.d modules.
As a result `buildyaml.sh` generates (syntax from [mkdocs documentation](https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation)):
Result
```yaml
- Go:
- 'collectors/go.d.plugin/README.md'
- Modules:
- 'activemq' : 'collectors/go.d.plugin/modules/activemq/README.md'
- 'apache' : 'collectors/go.d.plugin/modules/apache/README.md'
- 'bind' : 'collectors/go.d.plugin/modules/bind/README.md'
- 'cockroachdb' : 'collectors/go.d.plugin/modules/cockroachdb/README.md'
- 'consul' : 'collectors/go.d.plugin/modules/consul/README.md'
- 'coredns' : …
```
=> /docs/generator: add an option to use last dir name for page name 

docs/generator/buildhtml.sh
We need to use only modules README files for Modules section.
See
> https://docs.netdata.cloud/collectors/go.d.plugin/pkg/matcher/
`/docs`
- BEFORE
```console
test@DEB10-1:~/netdata/docs/generator$ ls -l src/collectors/go.d.plugin/
total 16
drwxr-xr-x 41 test test 4096 Feb  7 11:13 modules
drwxr-xr-x  3 test test 4096 Feb  7 11:13 pkg
-rw-r--r--  1 test test 6246 Feb  7 11:13 README.md
```
- AFTER
```console
test@DEB10-1:~/netdata/docs/generator$ ls -l src/collectors/go.d.plugin/
total 12
drwxr-xr-x 41 test test 4096 Feb  7 11:06 modules
-rw-r--r--  1 test test 6246 Feb  7 11:06 README.md
```
=> /docs/generator: build docs only for go.d itself and its modules

collectors/python.d.plugin/elasticsearch/elasticsearch.chart.py
Fix for missing terabyte unit parsing
```
File "/usr/libexec/netdata/python.d/elasticsearch.chart.py", line 534, in w
method(*args)
File "/usr/libexec/netdata/python.d/elasticsearch.chart.py", line 659, in _get_indices
size = convert_index_store_size_to_bytes(idx['store.size'])
File "/usr/libexec/netdata/python.d/elasticsearch.chart.py", line 517, in convert_index_store_size_to_bytes
return round(float(size[:-1]))
ValueError: invalid literal for float(): 1.0t
```
python.d/elasticsearch.chart.py
=> invalid literal for float(): NN.NNt

collectors/charts.d.plugin/charts.d.plugin.in
Fixes: #7998
This PR improves os_id detection in docker container. See https://github.com/netdata/netdata/issues/5935
- alpine `timeout`
```console
Usage: timeout [-t SECS] [-s SIG] PROG ARGS
```
- NOT alpine `timeout`
```console
Usage: timeout [OPTION] DURATION COMMAND [ARG]...
```
netdata docker info
```json
"os_id": "debian",
"container_os_id": "alpine",
```
Correct os_id detection order:
- `NETDATA_CONTAINER_OS_ID` // not set if netdata is not running in a container
- `NETDATA_SYSTEM_OS_ID`
[`/collectors/charts.d.plugin`](https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin)
Current `netdata/netdata` image
- BEFORE
```console
test@DEB10-1:~$ docker logs netdata  2>&1 | grep upsc -A 3
2020-02-07 14:18:06: charts.d: : nut: command 'upsc -l ' failed with code 127: …
```
=> /collectors/charts.d.plugin: fix `os_id` detection in `run`

database/README.md
Documentation states in one place default is dbengine and in another save is default which might confuse user.
=> Fix: Documentation states in one place default is dbengine and in another save is default

.github/labeler.yml, .github/workflows/labeler.yml
Switch to new labeler
>  https://github.com/marketplace/actions/periodic-pr-labeler
This labeler uses @gobwas (👋) [glob](https://github.com/gobwas/glob) library for file pattern matching which supports `**`.
In addition our current labeler has zero tests, which is pretty bad
> https://github.com/paulfantom/periodic-labeler
In addition we can add any features we need to the new pretty fast (like label based on author team membership, etc if we need), because it is written by @ilyam8 
`github/workflow`
I made a PR with `**` fix to the upstream
> https://github.com/paulfantom/periodic-labeler/pull/8
but it seems its author on vacation or something, that is why i decided to write a new one
=> github/workflow: change labeler

health/notifications/alarm-notify.sh.in
Fixes #7756 
According with our `health_alarm_notify.conf ` when we append `|critical` to notification, Netdata will  send only `critical` events for the users, but sometimes this was not happening when the `ROLE` was set to `root`. This PR fixes this problem.
Health ( Alarm notify)
I used Slack to replicate the error, my configuration was:
```
SEND_SLACK="YES"
SLACK_WEBHOOK_URL="https://hooks.slack.com/services/X/Y/Z"
DEFAULT_RECIPIENT_SLACK="myalarms|critical"
```
And I used the following alarm:
```
alarm: fix_or
on: example.random
lookup: average -3s at 0 every 3
units: %
every: 1s
warn: $this > 20
crit: $this > 120 
```
When we use the master branch I received `warning` and 'critical` events on Slack, but with this PR I began to receive only `critical.
=> Fix notification report

Makefile.am, aclk/mqtt.h, configure.ac
Closes #7740, to be used together with PR #8025 .
Check if ACLK can be built:
- is static lib build of forked mosquitto present?
- is libwebsockets present (standard library)?
By default `autodetect`. If `--enable-aclk` and ACLK cannot be build error during build. If `--disable-aclk` don't build even if possible.
Currently this switch is purposefully undocumented and hidden behind ACLK=yes enviroment variable.
=> Check if ACLK can be built

packaging/installer/netdata-updater.sh
This commit changes the check for updated releases when running in manual mode
Fixes #8027 
This PR provides a quick fix for running manual updates.
Netdata-updater
=> Fixes conditional for NetData Updater when checking for new updates

collectors/apps.plugin/apps_groups.conf
I found that `unbound` placed in `email` group, but actually is a validating, recursive, caching DNS resolver. Also I was add another name server daemons in new `dns` group:
- [unbound](https://nlnetlabs.nl/projects/unbound/about/) 
- [nsd](https://www.nlnetlabs.nl/nsd/)
- [powerdns](https://www.powerdns.com)
- [knot](https://www.knot-dns.cz)
- [gdnsd](https://gdnsd.org/)
- [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html)
- [yadifa](https://www.yadifa.eu/)
- [systemd-resolved](https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html)
=> collectors: apps.plugin: apps_groups: create 'dns' group.

.gitignore, netdata-installer.sh
This corrects the invocations of `mktemp` so that they produce temporary directories in `$TEMPDIR` instead of the current directory. We need to use `-t` for this for compatibility with busybox `mktemp`.
area/packaging
Fixes: #8064
=> Make temporary directories relative to $TEMPDIR.

packaging/mosquitto.checksums, packaging/mosquitto.version
As in the title.
area/packaging
For future reference, this is all that's needed on this side. The `mosquitto.version` file just contains the exact tag from the release, and `mosquitto.checksums` is the output of `sha256sum` run on the source archive produced by the release.
=> Update to new release of libmosquitto fork.

.travis/create_artifacts.sh
See #8056
Commented out a bunch of irrelevant things in `./.travis/create_artifacts.sh`
so I could make sure this change will work and is correct. Then ran inside
a Docker container:
```sh
/netdata # ./.travis/create_artifacts.sh
.
.
.
--- Copy artifacts to separate directory ---
checksums:
70294f6daf017811448658fd415286773a8fead2372f39c67521fdb4a617ff61  ./latest-version.txt
b63ef24a57d013e63da383f9e89c6aedc2ad1e400048fdafb91da7d708279169  ./netdata-latest.tar.gz
```
Observed that the `netdata-vx.y.z` lines are removed.
The result is the broken logic in the NetData Updater should not be able to
find a valid version and there fail the condition and fall through.
Even though it will still error with `[: : integer expression expected`
the next condition will run as demonstrated by this …
=> Added hack to sha256sums.txt to force users of NetData on v1.19.0-483 with a broken updater to update to latest

Dockerfile
This ensures that we have OpenSSL development files when building the Docker image, so that we can build the libmosquitto component of the ACLK functionality.
area/packaging
This is literally the only change needed now for libmosquitto to work in the Docker images.
=> Add required build dep for ACLK dependencies to Dockerfile.

docs/generator/buildyaml.sh
This PR follows up on #8074 to change the titles of Node/Bash collector modules in the left-hand navigation, to return them to their previous state and make them consistent with the Go/Python navigation after #8009.
**Before**
**After**
docs/
collectors/
Launched local webserver with generated documentation and verified the titles changed properly.
=> Docs: Fix Node and Bash collector module titles

contrib/debian/rules, netdata.spec.in, packaging/bundle-mosquitto.sh
This adds code to handle bundling our custom fork of libmosquitto into our binary packages. It pulls down the required sources, builds them, and copies the build artifacts into the right place so that the build of Netdata actually uses them.
area/packaging
Tested locally on all platforms we currently build packages for by building with the packager images (using `packaging/Dockerfile.packager` and running the resulting images to verify that the package was built, isntalled, and ran correctly.
This is the last remaining item for the libmosquitto support required for the agent-cloud link.
=> Add handling of libmosquitto to binary packages.

Makefile.am, netdata.spec.in
This fixes the issues with the RPM nightly builds resulting from the bundled libmosquitto functionality that was recently merged.
area/packaging
area/ci
Sample working Travis builds:
https://travis-ci.org/Ferroin/netdata/jobs/651505255
https://travis-ci.org/Ferroin/netdata/jobs/651505259
https://travis-ci.org/Ferroin/netdata/jobs/651505256
Fixes: #8108
=> Fix nightly RPM builds.

netdata-installer.sh
Kills two birds with one stone:
- Fixes #8116 
- Fixes #8119 
Blame(s):
- #8075
- #8085
Theres a lesson to be learned here 😀
See: #8120
This PR fixes a whole bunch of issues I discovered post our custom
libmosquitto fork (#8085) and our new highly experimental / tech preview
eBPF Collector(s) (#8075) (_amazing how these are just 10 pRs apart!_).
Some notable things:
- Always make sure you use the _right_ options for UNIX tools -- BSD implemtnations of many tools are especially picky about this. We got `mktemp -t -d ...` wrong in so many places :/ TODO: Create a ReviewDog check for this.
- We just weren't handling errors and we just don't have `set -e` on the NetData Installer. We should: TODO: Create Issue and PR for this and fix other places we do not handle errors properly.
- _and a few …
=> Fixes NetData installer on *BSD systems post libmosquitto / eBPF

collectors/ebpf_process.plugin/ebpf_process.c, libnetdata/ebpf/ebpf.c
Fixes #8134
This commit brings fixes to problems reports for Coverity.
Collector
The problems were present in the functions that closes the collector, so it is expected the collector will close without errors.
** CID 354249:  Resource leaks  (RESOURCE_LEAK)
/libnetdata/ebpf/ebpf.c: 67 in get_kernel_version()
*** CID 354249:  Resource leaks  (RESOURCE_LEAK)
/libnetdata/ebpf/ebpf.c: 67 in get_kernel_version()
61         int fd = open("/proc/sys/kernel/osrelease", O_RDONLY);
62         if (fd < 0)
63             return -1;
64     
65         ssize_t len = read(fd, version, sizeof(version));
66         if (len < 0)
>>>     CID 354249:  Resource leaks  (RESOURCE_LEAK)
>>>     Handle …
=> Ebpf coverity

packaging/installer/methods/manual.md
This fixes the URI's in the manual install documentation to point to the correct location for the `install-required-packages.sh` script (it got moved to the main repo and is not kept up to date in the demo-site repo anymore), as well as adding more explicit instructions for CentOS / RHEL 6 about needing to enable EPEL and an additional repo.
area/docs
Relevant to: #8081
=> Update the manual install documentation with better info.

.travis/create_artifacts.sh
This reverts commit bf62726bc632d1c65e8f2960af0052523f420266.
Closes #8056
=> Forces users stuck on `v1.19.0-432` to upgrade.

aclk/aclk_lws_wss_client.c, aclk/aclk_lws_wss_client.h, aclk/agent_cloud_link.c, aclk/agent_cloud_link.h, aclk/mqtt.c
Added retry on connection failure with exponential delay before retry attempts
- Start agent without a broker
- Started broker and connection was established
- Start broker and then start agent
- Connection immediately established
- Killed broker while agent connected
- Connection failed and re-connection attempts started with exponential delay
- Broker started, agent connected (after the re-connection delay)
=> ACLK retry on connection failure

packaging/installer/install-required-packages.sh
This adds basic support for Clear Linux to our installation process.
Of note, Clear Linux does not package libJudy, which means that as of right now dbengine support will not be available on Clear Linux systems unless the user manually installs libJudy.
area/packaging
Verified that the basic required packages needed for an install of Netdata are correctly installed with these changes added.
Fixes: #8137 
@jptuomi If you could test this that would be greatly appreciated (let me know if you need instructions on how to test).
To any reviewers who want to test this, be advised that setting Clear Linux up in a VM is a royal pain in the arse as it refuses to boot if the emulated CPU does not report certain instruction set extensions, refuses to install (even if the install ISO boots fine) …
=> Added support for Clear Linux in `install-required-packages.sh`.

aclk/aclk_lws_wss_client.c, aclk/aclk_lws_wss_client.h
Fix the reconnection issues on the ACLK.
ACLK
To reproduce the failure case - use the docker-compose.
```
build_external/bin/clean-install arch current
docker-compose -f build_external/projects/aclk-testing/vernemq-compose.yml up
docker-compose -f build_external/projects/aclk-testing/agent-compose.yml up --build
...
docker-compose -f build_external/projects/aclk-testing/vernemq-compose.yml down
...
docker-compose -f build_external/projects/aclk-testing/vernemq-compose.yml up
```
To recover the output more effectively at each state you can do this:
```
docker-compose -f build_external/projects/aclk-testing/agent-compose.yml logs | grep ACLK
```
Each up/down operation is effectively switching machine on/off in the virtual network.
Tried cycling both the broker and agent in different periods …
=> Fixed reconnect issues on the ACLK.

collectors/python.d.plugin/openldap/openldap.chart.py
Fixes the following error:
Feb 22 19:38:23 eve netdata[11810]: 2020-02-22 19:38:23: python.d WARNING: plugin[main] : openldap[localhost] : unhandled exception on check : TypeError("'dict_values' object is not subscriptable"), skipping the job
openldap
Testing it on my server: netdata.thalheim.io
Happens with python3.7 on NixOS.
=> openldap: fix dict access with python3

.github/workflows/build.yml, .github/workflows/installer.yml, .github/workflows/reviewdog.yml
Use `actions/checkout@v2` instead of `actions/checkout@v1` in all actions.
v2 is current stable version
It is faster, better ~~stronger~~
See
> https://github.com/actions/checkout#checkout-v2
`github/actions`
No testing, `checkout@v2` is stable.
=> gihtub/actions: switch to checkout@v2

web/gui/custom/README.md
It seems `` was replaced by ".
Docs
Checked up resulting render on GitHub.
=> Fix formatting in "Custom dashboards" section

CONTRIBUTING.md
PR titles are usually too cryptic and hide the problem they solve in technical jargon. 
We need to agree on guidelines that will make the changelog easier to read & understand. This will also greatly facilitate writing the release notes.
docs
As @prologic suggested, if we agree on such a format, we can have CI run regexp checks on the titles, to request improvements.
=> docs: Added PR title guidelines to the contribution guidelines, to make CHANGELOG more meaningful

docs/Running-behind-apache.md
Corrected instruction to install `apache2-bin` to `apache2`, as the former doesn't install `a2enmod` on Ubuntu 18.04
=> docs: Corrected instructions for running Netdata behind Apache

collectors/ebpf_process.plugin/README.md, docs/tutorials/monitor-cockroachdb.md
In working with Ian on the `learn` repo, we found some new errors in that Markdown parser due to me not properly closing image tags.
Before: `<img src="...">`
After: `<img src="..." />`
I confirmed this will fix the errors we're currently seeing in Gatsby by editing the files locally and loading them into Gatsby that way instead of from Git.
docs
=> Docs: Fixed figure+image without closing tag

backends/README.md
Fix documentation formatting: there was two stars surplus for that bold text. 
(aka. Reducing the amount of stars (I Am Entropy))
=> Fix bold text surplus stars

collectors/xenstat.plugin/xenstat_plugin.c
The compilation of netdata fails #7803  This is because of removal of tmem functionality from Xen 4.13 and thus from libxenstat.
collectors/xenstat.plugin
=> Removed tmem stat collection from xenstat plugin for Xen 4.13

netdata-installer.sh
Fixes #8164 
This brings two missing kernels necessary to extend the collector installation for more platforms. The problems were identified at Debian 10.2 and Ubuntu 18.04
Netdata installer
It is only necessary to run `netdata-installer.sh`.
=> Add support to new kernels

netdata-installer.sh
Installer always bundles `libwebsockets`
There is a wrong check in the `bundle_libwebsockets` function.
`packaging/installer`
I did 
> sudo ./netdata-installer.sh --install /opt --disable-cloud
Installer doesnt try to bundle libwebsockets
=> packaging/installer: fix bundle_libwebsockets

Makefile.am, configure.ac
~~If shared library libwebsockets > 3.0.0 not present in system try if static version was built by installer. If yes use static lib otherwise dont build ACLK.~~
Update:
After discussion it has been decided to only use our custom build of LWS (by installer) or disable ACLK. This PR has been updated to mirror that decision.
Closes #8152
=> Use static-build of LWS library created by installer

Dockerfile, Makefile.am, configure.ac, netdata-installer.sh, packaging/installer/install-required-packages.sh, packaging/installer/methods/manual.md
Closes #8152.
Work by @Ferroin and @underhood to improve the installer / build-system so that a working configuration exists for the ACLK.
installer
Tested that the installer works correctly in the following configurations:
* Debian 10 with libcap unavailable, ACLK both enabled and disabled.
* The Arch Linux container in the build_external system.
* FreeBSD
* MacOS
In each case the ACLK can be enabled when the dependencies are met, and the build also works with it disabled in the other cases.
More specific cases on Debian 10:
1. Without -lcap in system build with and without ACLK, build with ACLK and --without-libcap (should not error)
2. With -lcap in system build with ACLK, without ACLK, --without-libcap (error on configure "cant build ACLK without lcap" and --without-libcap …
=> Adding support for ACLK build-configuration

collectors/python.d.plugin/postgres/README.md, collectors/python.d.plugin/postgres/postgres.chart.py, web/gui/dashboard_info.js
PostgreSQL monitoring is missing the total connections in use against the specified maximum (as defined in PG server config file).
This PR adds this metric (% of Connections in use) under backend processes.
area/external/python
Tested against several PostgreSQL servers ranging from v9.4 to v12. Should be backwards compatible until v7.2
=> Added connections (backend) usage to postgres monitoring

.github/CODEOWNERS
This adds the SRE team as code owners for `contrib/debian`, which is where all the files needed for Debian packaging are. Long-term, this probably needs to be cleaned up and moved to the root directory where it belongs, but for the moment we just need to make sure the right people are being requested for review for these files.
area/packaging
=> Added SRE team as code owners for Debian packaging files.

.github/workflows/docker.yml
This adds PR checks to verify that Docker builds work correctly when PR's change the packaging code. It verifies all four architectures that we currently build Docker images for.
These checks only run on PR's which either modify the workflow itself, or alter the packaging or installer code.
area/ci
area/packaging
Verified that the checks run and pass correctly on my personal fork.
This is part of an ongoing conversion from Travis CI to GitHub Actions for CI/CD.
=> Added Docker build tests to PR checks.

web/gui/src/dashboard.js/main.js
Fixes some commas found right after the "Help" in "Help can be disabled from the settings."
web
N/A
N/A
=> Fixed misplaced commas in help disable strings

Makefile.am
This adds the version and checksum files for LWS to the files preserved by `make dist`. Without this, they aren't present when users try to install.
area/packaging
Verified that the installer script completes correctly after running `make dist`.
Fixes #8274
=> Added libwebsockets files to `make dist`.

collectors/python.d.plugin/ceph/ceph.chart.py, collectors/python.d.plugin/ceph/ceph.conf
Allows the ability to change ID used to connect to ceph instead of default "admin"
[`collectors/python.d.plugin/ceph`](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/ceph)
Changed file to pull rados ID from config file and pass it along to the connector.
Adding a user with read only caps to mon and mgr seemed to be enough to pull all relevant ceph data.  For my clusters, #8248 needed to be merged as well for this to be fully functional. I don't have a cluster that I can test this on "bare".  There are no reasons to believe it wouldn't work.
=> Added ability to change ID used to connect to ceph.

collectors/python.d.plugin/ceph/ceph.chart.py
Fixes: #8247
Ceph module uses 'osd_perf_infos' data from `osd perf` response. Its been moved under `osdstats` since 14.2.
cc @lets00
[`collectors/python.d.plugin/ceph`](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/ceph)
I did no tests, solution is pretty simple and proposed by @olobarius in #8247
Tested by @paulmezz
___
This PR backward compatible with older versions.
Before 14.2 we got `osd_perf_infos` directly from `ceph osd perf --format json` response. In current version it is in `osdstats` section of the response.
=> python.d/ceph: fix get_osd_perf() for 14.2+

collectors/cgroups.plugin/cgroup-name.sh.in
In those cases when kubernetes and netdata are manually installed on bare metal, the`cgroup-name.sh` script cannot get the names of the containers due to empty variables:
* `$KUBERNETES_SERVICE_HOST`
* `$KUBERNETES_PORT_443_TCP_PORT`
Also missing file `/var/run/secrets/kubernetes.io/serviceaccount/token`
My edits add an alternative opportunity to get the name of the container if no variables are set and `kubelet` is running on the system and `kubectl` binary is available.
By default, `/etc/kubernetes/admin.conf` is used to access kubectl, if an error occurs during execution, an entry will be added to the log with the warning level, but if you specify the path in the variable `$KUBE_CONFIG`, then it will be used your custom config.
For example, you can use systemd daemon:
```
[Service] …
```
=> Added ability to get pod name from cgroup with kubectl in bare metal deployment

.github/labeler.yml
This updates the configuration used for labeling PR's to utilize the newly added `area/build` label for PR's that change the build system.
area/ci
Verified configuration against what files are actually part of the build system and ensured that the file parses correctly.
I've added @netdata/core for review on this one so that someone there can help verify that the split in the config as to what's `area/build` and what's `area/packaging` is correct.
=> Updated PR labeling to utilize new area/build label.

packaging/installer/install-required-packages.sh
Most distros have Python 3, and some are already looking at dropping Python 2 in upcomming releases. All of our code works correctly on Python 3, so just use it by default for platforms that have it.
area/packaging
Verified that package installation still works correctly on all platforms we officially support.
Fixes: #8316 
Fixes: #7364
=> Switched to using Python 3 by default instead of Python 2.

netdata.spec.in
This reverts commit 1477784048319e84127e466add6eb4a092c235e1.
Fixes #8283
As discussed internally we believe we changed something between `v1.18.x` and
`v1.20.x` where we no longer strip the `v` prefix for what evetually becomes
`%{version}) in the `netdata.spec.in`.
Evidence
See `TBD` above.
=> Revert "Fixed Source0 URL in RPM spec (#7794)"

contrib/debian/netdata.postinst.in, contrib/debian/netdata.postrm, contrib/debian/rules
This commit creates the following folders during the installation
of Debian packages:
- /var/log/netdata (missing in Ubuntu 18.04)
- /var/cache/netdata (missing in Debian Buster as described in #8173 and Ubuntu 18.04)
- /var/run/netdata (missing in Debian Buster as described in #8173)
During the purge of the package, these folders are removed if empty.
Note that the permissions of `/var/log/netdata` allow the members of
the `adm` group to read the content.
Fixes #8173
* contrib/debian
I built the package locally with `dpkg-buildpackage -us -uc -rfakeroot` and installed the package locally with `dpkg -i ../netdata_*.deb`.
I made sure the service was running correctly after the installation.
Note: only tested on Ubuntu 18.04.
None.
=> Fixed missing folders in `/var/` by creating them during postinst

packaging/installer/kickstart.sh, packaging/installer/methods/kickstart.md
When running the installation script, a lot of `\n` got printed before the return status `[OK]` or `[ERROR]`.
Installer
Ran the install script locally
=> Removed extra printed `\n`

packaging/installer/install-required-packages.sh, tests/updater_checks.bats, tests/updater_checks.sh
This adds specific overrides for a couple of packages on Arch Linux that we were trying to install using the wrong names.
This also switches the lifecycle tests to use the `install-required-packages.sh` script from the branch being tested instead of always pulling from `master`, which will help prevent issues like this from happening again in the future.
area/packaging
Verified the script on a local Arch VM.
This fixes the recurring lifecycle failures for Arch in CI. I'm not sure why they were working before.
=> Fixed dependency names for Arch Linux.

Makefile.am, aclk/aclk_common.c, aclk/aclk_common.h, aclk/aclk_lws_wss_client.c, aclk/agent_cloud_link.h, libnetdata/config/appconfig.h
Closes #8089 
We read config value `agent_cloud_link` value `proxy`. Which can have following values:
- `none` - don't use proxy
- `env` - use environment variable`socks_proxy` if can otherwise disabled
- `socks5[h]://[user:pass@]host:port` - use this configured proxy regardless of any environment variables
ACLK
VerneMQ running in VM (listening on port 9002 on VM, all ports to VM blocked except ssh), socks proxy created by `ssh user@VM -D 8888`, `netdata -D -x socks5://127.0.0.1:8888` and set to connect to verneMQ `127.0.0.1:9002` (this IP is interpreted from proxy server side).
`export ACLK=yes` must be set before running netdata installer. If testing with selfsigned certificate on VernMQ then `-DACLK_SSL_ALLOW_SELF_SIGNED` must be set.
=> Add support for SOCKS5 proxy to the ACLK.

.github/CODEOWNERS
This is something that came up in an SRE Daily Sync where we agreed that it
doesn't make a whole lot of sense for us to be code owners of the build system
itself where we often get pulled into reviews on things we just simply have
no context on and can't provide meaningful input.
This will help reduce notifications on PRs we don't really review anyway.
- github
=> Cleans up CODEOWNERS for the build system itself (not to be confused with packaging)

packaging/installer/install-required-packages.sh, packaging/makeself/makeself-header.sh
Assorted fixes and improvements related to the installers:
* Stop rotating old Netdata configuration during a static install (this should have been removed when we quit shipping stock configs in `/etc/netdata`).
* Stop using a loop over multiple invocations of the package manager when installing dependencies. It hides errors, hurts efficiency, and also is a pain in the arse when installing interactively.
* Fixes another package naming issue for Arch Linux.
* Properly completes the switch to Python 3 as the default for new installs (I missed a number of things in #8318.
area/ci
area/packaging
Verified using the PR checks and manual testing in Docker.
Fixes: #8155
Fixes: #8294
=> Added various fixes and improvements to the installers.

docs/generator/buildhtml.sh, docs/generator/custom/css/netdata.css, packaging/installer/README.md
A user pointed out that while the links to "other methods" in the installation guide (`packaging/installer/README.md`) work fine in the published documentation, they do not work on GitHub itself. This PR fixes that issue by ensuring the links between these documents reference specific `.md` files.
I had to reconfigure the Markdown, and a bit of the CSS, to ensure the links work properly on GitHub but also render into the nice grid that we currently have in the [documentation](https://docs.netdata.cloud/packaging/installer/#have-a-different-operating-system-or-want-to-try-another-method).
cc @jlbriston 
docs
packaging/
I tested this locally, but I'll test again when the Netlify deploy preview finishes.
=> Fix links in packaging/installer to work on GitHub and docs

packaging/installer/install-required-packages.sh
As pointed out in #8080 by @8080 (_Thank you!_)
__Before__:
```sh
$ version="6.10"; if [ "$version" -eq 8 ]; then echo "CentOS 8.x"; else echo "NOT CentOS 8.x"; fi
-bash: [: 6.10: integer expression expected
NOT CentOS 8.x
```
__After__:
```sh
$ version="6.10"; if [[ "${version}" =~ ^8\..*$ ]]; then echo "CentOS 8.x"; else echo "NOT CentOS 8.x"; fi
NOT CentOS 8.x
```
=> Fix cosmetic error checking for CentOS 8 version in install-required-packages

.github/workflows/coverity.yml, .travis.yml
Fixes #6749 
- area/ci
- Test in my fork with temporary Github secrets added to my fork.
I need the following secrets / enviornment variables currently in Travis:
- `COVERITY_SCAN_SUBMIT_MAIL`
- `COVERITY_SCAN_TOKEN`
If someone can get those to me (_preferably @knatsakis_) and added to our SRE secrets repo that would be awesome :)
=> Migrate coverity-scan to Github Actions

packaging/installer/README.md
My latest PR #8319 introduced an MDX parsing error into the work @Soviut is doing on the new documentation site. I need to change `markdown=1` to `markdown="1"` for the MDX parser to not panic.
docs
packaging/
Tested this by running the docs generator locally.
=> Fix MDX parsing in installation guide

DOCUMENTATION.md, README.md, docs/generator/buildhtml.sh
I neglected to add in some logic in the `buildhtml.sh` script to strip the comments around our new frontmatter tags, which has resulted in some weirdness with page titles in the current documentation. This PR adds that logic and also fixes 2 other frontmatter items that did not handle the bulk add well.
docs
=> Add proper parsing/stripping of comments around docs frontmatter

netdata-installer.sh
This adds some code to the Netdata installer to allow deferring non-fatal errors so that their messages get printed at the end of the install process. It does this by constructing the list of errors as they occur and then printing them all at the end if the list is non-empty.
With these changes, failures to download, validate, or install libmosquitto, LWS, or the go.d plugin will cause the errors to be reported when the install script otherwise finishes successfully, making it much easier for users to notice that there was a non-fatal error.
area/packaging
Verified locally by artificially inducing the errors in question that this is now deferring messages for.
=> Added deferred error message handling to the installer.

libnetdata/url/url.c, streaming/rrdpush.c
Fixes #8022 
This PR fixes the missing characters described in the issue #8022 , we began to encode texts before to send from slave to master
Stream
It is necessary to set master and slave with this PR and verify using the endpoint `/api/v1/info` on slave and `host/name/api/v1/info` on master that the fields are exactly the same. 
The problem reported on #8022 was discovered using Raspberry-PI, ideally the slave should be it.
=> Enconde slave fields

.github/workflows/coverity.yml, coverity-scan.sh
As per title
- area/ci
- This PR itself
I originally got a CI failure for this, so the workflow works but it
was previously not tested orrectly, hence the addition of `pull_request:`
to the workflow to ensure it runs inside a pull request that touches either
the workflow or the script itself.
=> Fix coverity scan

aclk/agent_cloud_link.c, aclk/agent_cloud_link.h
Fixes #8350 
- The agent stability status during pop-corning is now checked every second. 
- The agents switches to a stable state after ACLK_STABLE_TIMEOUT+1 seconds (currently 10+1)
- Commands from the cloud during pop-corning are ignored
- Run the agent in local dev environment
- Notice a new message similar to 
`Waiting for agent collectors to initialize. Last activity was 7 seconds ago` while the agent is waiting for the collectors to initialize
=> ACLK: Improved the agent "pop-corning" phase

.codacy.yml, aclk/aclk_lws_wss_client.c, aclk/aclk_lws_wss_client.h, aclk/agent_cloud_link.c, aclk/mqtt.c, aclk/mqtt.h, aclk/tests/launch-paho.sh, aclk/tests/paho-inspection.py, aclk/tests/paho.Dockerfile
Initial work on fixing the performance problems in LWS / MQTT. Reduces the visible latency from 120s for the initial on-connect payloads to 10-20s. May increase CPU. Fixes the encoding errors for the JSON messages on the link allowing the alarms to work.
ACLK
* Run against the cloud local dev env and ensure that performance is no worse that it was.
* Run the paho inspection container inside aclk/testing/ and verify that messages are arriving at VerneMQ.
Although this is not a complete fix for the performance problems - it does improve performance and allows other PRs to be merged on top.
=> Perf fixes

aclk/aclk_lws_wss_client.c, aclk/aclk_lws_wss_client.h, aclk/agent_cloud_link.c
Closes #8391 
* Introduced a docker container with a paho client that can be used as an inspection point on the link.
* The inspection point calculates the latency from  `aclk_send_message()`, out of LWS, via VerneMQ to the inspection point and the decoding in the container.
* Introduced a stress-tester to the ACLK to generate large payloads.
* Wrote a fragmentation layer to avoid large writes into LWS.
* Verified that the latency is low without saturating the CPU.
* Fixed the encoding of JSON messages on the link.
(part of these changes are in PR 8399)
ACLK
* Used the stress-tester, htop and the inspection point.
* Ran against the local cloud dev env.
* Verified that 2MB payloads had a constant latency of about 1s.
* Verified that the CPU-load was the same with the link running and not …
=> Improved the performance of the ACLK. (#8391)

aclk/agent_cloud_link.c
Fixes #8035 
Change the type value to `status-change` in the generated alarm update message
ACLK
* Start a claimed agent 
* Verify ACLK is up and running
* Force an alarm generation e.g. high cpu usage etc
* Monitor the alarm updates generated with a new type message of `status-change` instead of `alarms`  e.g
```
{
"type": "status-change",
"msg-id": "b2e46230-43d0-47a1-bdd4-9a346ea676ba",
"timestamp": 1584207884,
"version": 1,
"payload":  {
:
}
}
```
=> ACLK: Fixes the type value for alarm updates

collectors/ebpf_process.plugin/ebpf_process.c, daemon/main.c, database/engine/rrdengineapi.c, database/engine/rrdenginelib.h, database/rrdset.c, exporting/read_config.c, libnetdata/clocks/clocks.c, libnetdata/clocks/clocks.h, libnetdata/config/appconfig.c, libnetdata/config/appconfig.h, streaming/rrdpush.c, streaming/stream.conf, system/netdata.service.in, web/api/tests/valid_urls.c, web/api/tests/web_api.c
Fixes #8218
Related to #8251
database
streaming
health
daemon
Set-up a bare metal server with 500 lxc containers as netdata slaves connected to the master in the host. Used `dbengine` as `memory mode` for both `netdata.conf` and `stream.conf`.
=> Fix streaming scaling

CMakeLists.txt, backends/prometheus/remote_write/remote_write.cc, configure.ac
If Netdata was compiled using CMake, there was a compilation error
```
[ 31%] Building CXX object CMakeFiles/exporting_engine_testdriver.dir/exporting/prometheus/remote_write/remote_write_request.cc.o
/home/runner/work/netdata/netdata/exporting/prometheus/remote_write/remote_write_request.cc:4:10: fatal error: remote_write.pb.h: No such file or directory
#include "remote_write.pb.h"
```
It was because `remote_write.pb.h` and `remote_write.pb.cc` are created in the build directory in CMake, instead of the current directory of the source tree, like in Autotools. The PR fixes include paths.
build
```
sudo git clean -dxf
netdata-install.sh
```
```
sudo git clean -dxf
autoreconf -ivf
./configure
mkdir cmake-build-debug
cmake -DCMAKE_BUILD_TYPE="Debug" -DUNIT_TESTING=ON ..
make
```
=> Fix Prometheus Remote Write build

CMakeLists.txt
aclk_common.c/aclk_common.h missing from CMAKE list of files for ACLK.
Noticed when reviewing #8411
ACLK builds with CMAKE
=> Adds missing files to ACLK CMake build

aclk/aclk_common.c, aclk/agent_cloud_link.c, aclk/tests/paho-inspection.py, claim/README.md, claim/claim.c, claim/netdata-claim.sh.in
Closes #8090 
Closes #8263
Fix the problems in running the claiming script.
Merging from other PR (will integrete shortly).
some things in claiming script have to be fixed as well for this to be 100% (see #8263) - therefore this PR works and brings SOCKS5 proxy but there are error reporting issues that will be fixes in #8263.
If agent configured with SOCKS5 proxy [agent_cloud_link] key proxy it should pass that setting to curl when claiming script is called from within netdata agent with netdata -D -Wclaim.
ACLK
* Claiming against the local cloud env with a valid url.
* Claiming against the local cloud env with an invalid url.
* Claiming against the local cloud env with incorrect port.
* Claiming against the local cloud env with nonexistent hostname.
* The `-verbose` flag shows the JSON …
=> Fix outstanding problems in claiming and add SOCKS5 support.

aclk/aclk_lws_https_client.c, libnetdata/json/json.c
Fixes #8349
When the internal JSON parser was used the callback function supplied was not called in some cases so the calling function would not get the complete parsed results.
ACLK
Before the PR is applied
- Start a claimed agent without the optional json-c library
- When attempting to establish the ACLK, notice in the logfile error messages 
`Could not retrieve challenge from auth response:.....`
After the PR is applied
- Start a claimed agent without the optional json-c library
- Challenge response completes successfully
- ACLK is established
=> Fixed JSON parsing

aclk/aclk_lws_wss_client.c, aclk/agent_cloud_link.c, aclk/agent_cloud_link.h, aclk/mqtt.c, aclk/mqtt.h
Fixes #8369
Defines a Last Will and Testament message that the broker will send to the `outbound/meta`
topic if an unexpected (agent or link) failure occurs. 
When the agent performs a normal shutdown an MQTT disconnect packet notifies the broker
that the LWT message should not be sent. In that case a different disconnect message is transmitted and indicates a graceful agent shutdown.
ACLK
- Start a claimed agent
- Subscribe to the broker on the `outbound/meta` topic
- Verify ACLK is up and running
- Notice the on connect messages
- Press control - C or send a `kill` signal to the agent
- Notice a LWT message on `outbound/meta` similar to 
- `{ "type" : "disconnect", "version" : 1, "msg-id" : "e7558504-eb6f-4bdf-9700-df972e0940e6", "timestamp" : 1584372301, "payload" : "graceful" } ` …
=> ACLK: Implemented Last Will and Testament

configure.ac, netdata-installer.sh, web/api/web_api_v1.c
Added the fields to the `/api/v1/info` endpoint that the dashboard needs to display the status of the cloud support.
Changed the way the flags propagate through the installer and configure script.
**The ACLK environmental variable is no longer used**. It has been removed in preparation for flipping the feature flag. Supply `--cloud-testing` to the installer to enable everything. This is an internal only option as access to the cloud platform requires iauthentication.
ACLK
web/api
* Tested with a claimed / unclaimed agent.
* Tested with the cloud disabled / enabled.
* Checked the availability flag tracks the dependency state.
=> Add the new cloud info in the info endpoint

aclk/agent_cloud_link.c
Fixes #8124
Executing queries from the cloud mail fail so the payload response adjusted to include a code and a body section
The code is the HTTP response code from the internal webapi and the body carries the response
ACLK
- Start a claimed agent
- Verify ACLK is up and running
- Construct and send a query command to the agents listening topic e.g. `inbound/cmd` with a payload similar to: 
`{ "type" : "http", "version" : 1, "callback-topic" : "callback/topic", "msg-id" : "testmsg", "payload" : "/api/v1/info"}`
=> Fixed response payload to match the new specification

.travis/package_management/configure_deb_lxc_environment.py, contrib/debian/control.eoan
Fixes #8393
We _may_ have to temporarily add some CI to Travis since we're not fully
migrated yet to the new Docker-based GHA workflows for building Native Binary
Packages (_just yet_).
=> Fix broken dependencies for Ubuntu 19.10 (eoan)

packaging/installer/functions.sh
Closes #8422
- area/packacing
__Before__:
```sh
Starting netdata using command 'systemctl start netdata'
[/tmp/netdata-kickstart-8zP6rR/netdata-v1.20.0-186-g459bedf9]# systemctl start netdata  OK
OK  netdata started!
```
__After__:
```sh
Starting netdata using command 'systemctl start netdata'
[/home/prologic/netdata]# systemctl start netdata
OK
OK  netdata started!
```
#8422 was already fixed by #8326 #8325 and #8324. The OP was installing from the
current stable release of `v1.20.0` where the bug still existed.
This PR improves the output slightly more by removing the redundancy of the
command we're about to run (_we end up printing it twice_) and adds the `\n`
where it was really suppose to have gone in the first place.
#8446 also fixes similar things for the uninstaller.
=> Improve installer output re newlines

packaging/installer/functions.sh, packaging/installer/netdata-uninstaller.sh
As per title
- Fixes #8428
- Fixes #8189
#8428:
#8189:
=> Fixes support for uninstalling the eBPF collector in the uninstaller and fixes a minor bug

collectors/plugins.d/plugins_d.c
Fixes #8459 
This commit removes the memory leak present on Netdata.
Stream
It is necessary to set a master and slave with labels.
The labels visualized on Slave must be on master.
=> Memory leak with labels on stream

daemon/commands.c, database/engine/pagecache.c, database/engine/rrdengine.c, database/engine/rrdengine.h, database/engine/rrdengineapi.c, database/engine/rrdenginelib.h
Fixes #8421
Fixes #8384
database/dbengine
Test scenario with dbengine page cache size smaller than the amount of metrics being generated by collectors.
Test scenario with disks being slower than metric data generation throughput for potential regression detection.
Fix flushing error threshold to account for inactive producers of dbengine instance.
=> Fix flushing error threshold

packaging/docker/Dockerfile
The packaging Dockerfile did not include the claiming script in the white-list used to move files between stages.
packaging
Building the container
=> Adding the claiming script to the multi-stage whitelist

packaging/docker/Dockerfile
Fixes problems with claiming agents in the local dev env.
packaging
claiming
Claiming an agent in the local dev env.
=> Installer creates claim.d but is run as root, patch to correct ownership

packaging/docker/Dockerfile
This adds a build argument to the main Dockerfile to allow passing extra options to the netdata-installer script during the build process.
The value specified in the `EXTRA_INSTALL_OPTS` argument wil be added verbatm to the netdata-installer.sh script. The arguments `--dont-start-it` and `--dont-wait` are still implicitly passed to the script as those are required to get a correctly functioning Docker image.
area/packaging
Regular builds verified on PR checks, locally tested with arbitrary argument combinations to verify that the bild works correctly.
This originated as a way to build Netdata Cloud support in the Docker images while it's still being tested, but is intended to be kept moving forwards as an easy way to create custom Docker images and simplify testing optional features from …
=> Added Docker build arg to pass extra options to installer.

aclk/README.md, aclk/aclk_common.c, aclk/aclk_common.h, aclk/aclk_lws_https_client.c, aclk/aclk_lws_wss_client.c, aclk/aclk_lws_wss_client.h, claim/claim.c, claim/netdata-claim.sh.in
Fixes #8114
aclk, claiming, challenge/response
With following in the config file:
```ini
[cloud]
cloud base url = https://192.168.56.1:8443
[agent_cloud_link]
proxy = http://192.168.56.101:3128
```
In my case `192.168.56.101:3128` is squid proxy running in VM. `192.168.56.1` is machine connectible trough aforementioned proxy where local cloud environment is running. It is recommended using firewall to block access to cloud environment without proxy (or check with wireshark). Additional way to check connection is indeed made trough proxy is checking squids `access.log` where you should see something like `192.168.56.1 TCP_TUNNEL/200 2188 CONNECT 192.168.56.1:8443 - HIER_DIRECT/192.168.56.1 -`.
Squid proxy has to be correctly configured (if something doesn't work check `access.log` to check …
=> HTTP proxy support + some cleanup

packaging/installer/netdata-updater.sh
This PR adds some proper cleanup to the NetData Updater such that we actually
properly cleanup log files we created or temporary directories. We do so on
any signal we can intercept as well as normal script termination
(_regardless of exit status_).
Previously we would only cleanup _some_ limited number of things after
successive steps in the process and potentially leave things behind like
in #8128
- Tested this inside a simualted environment with simulated failures
1. Run `docker build -f Dockerfile.dev -t netdata:dev . | tee prepare.log && dki -t --rm -v "$PWD":/netdata -w /netdata --network none netdata:dev`
2. Make sure there are no `netdata-updater-*` directories: `find / -type d -name 'netdata-updater-*'`
3. Run the netdata updater (_cron does this automatically_): …
=> Fix the lack of cleanup in the netdata updater

netdata-installer.sh
Minor -> if Libmosquitto or Libwebsockets fail to build make the warning at the end of installer more prominent (yellow bold).
On request of Product
force one of the libs build failure or add `false && \` after line 502 of build script (to force script to think it failed).
Result should look like this:
=> Make mosq and LWS lib build fails more prominent

aclk/aclk_lws_wss_client.c, aclk/aclk_lws_wss_client.h
If ACLK fails to connect report it in case telemetry is enabled (e.g. respect DO_NOT_TRACK of course)
We send up to last 10 events of LWS to the GA to be able to analyse at what point connection failed.
Fixes #8051 
ACLK
Fail connection in different ways. Look at the reports in Google Analytics
Example of event data when connection failed on certificate verification: "30,1,58,19,29"
=> Report ACLK Connection Failure

packaging/installer/install-required-packages.sh
As per our title.
Also fixes (_hopefully_) breaking CI checks I'm seeing in various PR(s).
e.g: #8485
- area/ci
Our CI will test this change across many systems and the breakages I'm seeing
which I reported in actions/virtual-environments#624 automatically get resolved.
I _believe_ this is the root cause of why our CI would sometimes fail.
We would not update the `apt` cachce when installing extra things we need
in CI which runs on Ubuntu bionic.
If this works @al-cheb I apologize for the noise and actions/virtual-environments#624
can probably be closed :)
=> Fix install-required-packages script to self-update apt

packaging/installer/netdata-uninstaller.sh
As per title.
See #8422
__Beofre__:
```sh
Deleting netdata user from docker group ...
[/root]# gpasswd -d netdata docker \nRemoving user netdata from group docker
OK  gpasswd -d netdata docker
```
__After__:
```sh
Deleting netdata user from docker group ...
[/root]# gpasswd -d netdata docker
Removing user netdata from group docker
OK
```
When you do `printf "%s" "${foo}"` don't do `printf "%s" "${foo}\n"` it
doesn't do what you expect, it treats the `\n` as escapced raw text in the
subsitution.
=> Fix erroneous \n printed in uninstaller

.travis.yml
As per title.
- area/ci
I _think_ this was always wrong and just worked by accident :/
There seem to be no `openSUSE:15.0` upstream LXC Images anymore as of otday.
=> Fix openSUSE 15.1 RPM Package Buidls

configure.ac, daemon/main.c
Report reason why ACLK build failed. Respect opt out.
Fixes #8050
Simulate ACLK build failure (e.g. by removing libomosq.a from `externaldeps` folder and rerun configure without running installer).
You should see events in Google Analytics.
Keep in mind changes merged by Andrew meanwhile (you must pass --with-cloud to configure instead of ACLK=yes). If cloud is not enabled by purpose do not report anything.
=> Report Why ACLK build failed

.gitignore
Commit `Fake collector to provoke ACLK messages` *(9ee4478f9a9eedbaff5887a415a897d984e74828)* misses adding this file to .gitignore
=> Adds install-fake-charts.d.sh to gitignore

.github/labeler.yml
I noticed there are no labels in the https://github.com/netdata/netdata/pull/8499
This PR adds `aclk/` to the labeler config. 
`.github/workflow`
No tests are needed
=> github/workflow: add ACLK to the labeler config

packaging/installer/netdata-updater.sh
Fixes a longn standing bug with the static installation (`kickstart_static64.sh`)
where we use [Makeself](--auto-update) where we _were_ correctly reusing the
`REINSTALL_OPTIONS` we presist to `/etc/netdata/.environment`; but; we were not
passing this correctly to the embedded script inside the Makeself archive.
This is really hard to test because I have to fudge URL(s) everywhere to
properly test this e2e. So instead of doing that I tested the one piece
that was broken inside a VM by manually downloading the `netdata-nightlies/netdata-latest.gz.run`:
```sh
root@debian:~# curl -sSLO --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/netdata-latest.gz.run
root@debian:~# ls -lah
total 29M
drwx------  2 root root 4.0K Mar 27 06:57 .
drwxr-xr-x 18 …
```
=> Fix auto updates for static installs (kickstart_static64.sh)

aclk/README.md, aclk/aclk_common.c, aclk/mqtt.c, claim/README.md, libnetdata/config/appconfig.h
Removes config section `[agent_cloud_link]` and move it's keys under `[cloud]` so that they are all in a common place.
Agent/ACLK
@andrew I remember we wanted to put it all under `[cloud]` if not true just close this PR.
=> Cleans up cloud config files [agent_cloud_link] -> [cloud]

aclk/agent_cloud_link.c
Log the reason of the ACLK challenge  / failure. Right now when the initial challenge fails the `error.log` shows `Challenge failed`
In the case of password failure it says `Challenge-response failed`
ACLK
The `error.log` now contains the cloud response as follows (example) :
```
Challenge failed: {"errorCode":"TODO traceid","errorMsgKey":"ErrNodeNotFound","errorMessage":"node not found"}
```
```
Challenge-response failed: {"errorCode":"TODO trace-id","errorMsgKey":"ErrIncorrectResponse","errorMessage":"incorrect challenge response"}
```
=> Write the failure reason during ACLK challenge / response

collectors/charts.d.plugin/charts.d.plugin.in
Fixes: #8448
`charts.d.plugin` doesnt exit on `SIGPIPE`.
```cmd
[root@localhost ~]# cat /etc/centos-release
CentOS release 6.10 (Final)
[root@localhost ~]# kill -9 $(pidof netdata)
[root@localhost ~]# ps faxu | grep ^netdata
netdata  20364  0.1  0.1  11568  1812 ?        S    18:34   0:00 bash /opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin 1
netdata  20367  0.6  0.3  54312  3372 ?        S    18:34   0:00 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
```
___
Adding `PIPE` to [the list of trap signals](https://github.com/netdata/netdata/blob/74082011dfb7d3c33c7f2c972978b440666d2528/collectors/charts.d.plugin/charts.d.plugin.in#L28-L37) didnt work for me
So i added a keepalive function, it is executed in the beginning of every update loop.
It is simple `printf` exit …
=> charts.d.plugin: add keepalive to global_update

collectors/python.d.plugin/apache/apache.chart.py
This PR fixes python apache collector chart `bytespersec` context
`apache.bytesperreq` => `apache.bytespersec`
Test are not needed, the change is trivial
=> apache: fix `bytespersec` chart context

Makefile.am, aclk/agent_cloud_link.c, claim/claim.c, configure.ac, daemon/commands.c, daemon/common.c, daemon/common.h, daemon/main.c, database/rrddim.c, database/rrdset.c, health/health.c, health/health_log.c, netdata-installer.sh, web/api/web_api_v1.c
fixes #8378 
cloud
* Default behavior is to allow the cloud (the --cloud-testing flag is gone).
* The --disable-cloud switch in the installer will disable everything.
* The default config option is `[global] netdata cloud = coming soon` -> this currently disables cloud functionality.
* The feature is enabled with `[global] netdata cloud = enabled` -> this still requires a local copy of the infrastructure or auth for the testing platform.
* If the feature is enabled at compile-time then it can be switched off with `[global] netdata cloud = disabled`.
In cases where the cloud is enabled, check:
* The flag in the `/api/v1/info` endpoint.
* That the ACLK is successfully established.
=> Switching over to soft feature flag

netdata-installer.sh
This adds some basic logic to the installer to check if `cmake` is present or not and just skip attempting to build lbwebsockets.
area/packaging
Verified locally by checking in Docker containers that it behaves correctly.
Fixes: #8558
=> Added logic to bail early on LWS build if cmake is not present.

collectors/apps.plugin/apps_plugin.c
Apps plugin never died if a pipe to netdata was broken.
Fixes #8530
apps plugin
Kill `netdata` with `SIGKILL` in CentOS 6.10 - `apps.plugin` should stop.
=> Fix broken pipe ignoring in apps plugin

.github/workflows/build-and-install.yml, claim/netdata-claim.sh.in, configure.ac, netdata-installer.sh, packaging/mosquitto.checksums, packaging/mosquitto.version
Multiple bugs have been detected (while I was checking #8561) after recent changes in `configure.ac`. Fixes #8561 and 2 other bugs which do not have issues created.
List of found problems and their fixes:
- __*CRITICAL*__ (broken in master) the new detection, if mosquitto can be built, is not really working in `master` due to multiple problems *(syntax C `int main (int argc, char **argv)) {`, syntax configure, missing include, missing SSL link)*. This causes ACLK link to always fail - example OUTPUT of current master Fedora 31 CI build:
```
checking if libcap should be used... no
checking if libmosquitto static lib is present (and builds)... 
checking if libwebsockets static lib is present... yes
checking if netdata agent-cloud-link can be enabled... no
checking if netdata …
```
=> Fix regressions in cloud functionality (build, CI, claiming)

.travis.yml, .travis/package_management/trigger_rpm_lxc_build.py
SSIA
- area/ci
Hmmm 🤔 This is __really__ hard to test in Travis :/
```sh
$ OS=fedora30; git clean -d -f -x && dki -t --rm -e CFLAGS='-fPIC' -e VERSION="1.20.0" -v "$PWD":/netdata -w /netdata netdata/package-builders:"${OS}"
.
.
.
```
Discovered during recently nightly build:
- https://travis-ci.com/github/netdata/netdata/builds/157657428
- https://travis-ci.com/github/netdata/netdata/jobs/311796424
- https://travis-ci.com/github/netdata/netdata/jobs/311796425
I cannot explain currently why a normal build works on Fedora 30/31 but fails
inside the `rpmbuild` environment (_regardless of which CI is in usde_).
=> Fix broken Fedora 30/31 RPM builds

.github/workflows/build-and-install.yml, packaging/installer/install-required-packages.sh
ssia
- area/ci
```#!sh
$ dki -t --rm -v "$PWD":/netdata -w /netdata debian:jessie /bin/bash -c './packaging/installer/install-required-packages.sh netdata-all'
.
.
.
All done!
```
**NB:** `PRE` in our CI workflows are **NOT** for doings things that should
be done in our `install-required-packages.sh` :/
=> Fix Debian 8 (jessie) support

packaging/installer/install-required-packages.sh
ssia
- area/packacing
- Tested running `install-required-pacakges.sh` in a Debian 8 (jessie) container multiple times to ensure we only enable `jessie-backports` once.
=> Ensure we only enable jessie-backports for Debian 8 (jessie) once

libnetdata/config/appconfig.c, libnetdata/config/appconfig.h, streaming/rrdpush.c
Fixes #8415 
This PR fixes the bug reported on #8415.
Libnetdata
Streaming
It is necessary to set a Netdata `master` and at least one  Netdata `slave` with this PR.
When both are running, please access the follow links on master:
```
https://localhost:19999/api/v1/info
https://localhost:19999/host/SLAVE_NAME/api/v1/info
```
For the master we will have the label `_is_master` as `true` and for the slave it will be `false`.
=> Read configuration when section is open

.gitignore
After #7790 was merged, there is an annoying `system/netdata.service.v235` file, created during Netdata build. This PR hides the file from git.
build
=> Add netdata.service.* to .gitignore

claim/claim.c
When the `--disable-cloud` option is used to build Netdata there are compiler warnings
```
claim/claim.c: In function 'claim_agent':
claim/claim.c:42:24: warning: unused parameter 'claiming_arguments' [-Wunused-parameter]
42 | void claim_agent(char *claiming_arguments)
|                  ~~~~~~^~~~~~~~~~~~~~~~~~
At top level:
claim/claim.c:9:14: warning: 'claiming_errors' defined but not used [-Wunused-variable]
9 | static char *claiming_errors[] = {
|  
```
cloud
Run `sudo ./netdata-installer.sh --disable-cloud`.
=> Fix compiler warnings in the claiming code

Makefile.am, configure.ac
Fixes #8589 
also cleans up some ugly parts (`-lcap` in CFLAGS)
on ubuntu install both `libcap-dev` and `libcap-ng` packages. Try to build netdata with intaller.
`dpkg -l | grep libcap` should say:
```
ii libcap-dev:amd64 1:2.25-1.2 amd64 POSIX 1003.1e capabilities (development)
ii libcap-ng0:amd64 0.7.7-3.1 amd64 An alternate POSIX capabilities library
ii libcap2:amd64 1:2.25-1.2 amd64 POSIX 1003.1e capabilities (library)
ii libcap2-bin 1:2.25-1.2 amd64 POSIX 1003.1e capabilities (utilities)
```
To test for regressions also test without `libcap-dev` (run installer again to recompile LWS)
=> Fixes Ubuntu build with both libcap-dev and libcapng

.travis.yml, .travis/package_management/trigger_rpm_lxc_build.py, netdata.spec.in
Fedora builds it's packages using `-fPIC`, but we were not building LWS and mosquitto with this flag, causing the final link to fail.  This modifies the RPM file to ensure they get built with this flag independent of the environment, which will work everywhere unless someone tries to build the package with PIC disabled (which no distribution currently does).
area/packaging
Verified locally using Docker package builds. Verified in Travis at https://travis-ci.org/github/Ferroin/netdata/builds/670595759
This differs from the original attempts at fixing this in that it modifies the environment the scripts we use to bundle LWS and mosquitto run in directly, instead of relying on multiple layers to pass through the required environment variables.
=> Correctly fixed RPM package builds on Fedora.

collectors/apps.plugin/apps_plugin.c
Every 4 hours the apps plugin was restarting. It was done to be safe if there are any memory leaks in the plugin. I think the plugin is in active use for quite a long time and should be in good condition, so we can remove the restart.
Fixes #8469
apps.plugin
=> Remove an automatic restart of the apps.plugin

packaging/installer/install-required-packages.sh
My system:
```cmd
[ilyam@ilyam-pc ~]$ cat /etc/os-release
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
There are two errors during execution of `install-requred-packages.sh`.
- `Unknown distribution ID: manjaro`
- `validate_tree_arch: command not found`
First one is minor and is likely expected but it makes me thingking that something is going wrong.
This PR fixed both errors.
`packaging`
I did no tests, i think ci should be enough.
=> packaging: fix errors during install-requred-packages

collectors/python.d.plugin/mysql/mysql.chart.py
Fixes: #8634
`threads` and `threads_creation_rate` charts have same context
https://github.com/netdata/netdata/blob/3c4cb607d6b77b9fd9076dd6662d3bc13975c871/collectors/python.d.plugin/mysql/mysql.chart.py#L341-L354
This PR changes `threads_creation_rate` chart context to `mysql.threads_creation_rate`
No tests needed.
=> collectors/python.d/mysql: fix `threads_creation_rate` chart context

docs/generator/requirements.txt
After discovering that our docs site builds were failing, I also noticed that the mkdocs-material project released a new major version at the exact same time. Netlify was trying to pull this latest version, resulting in the build errors.
This PR pins `mkdocs-material` to the previous stable release (4.6.3), which is what Netlify was building with until this morning.
docs
See if Netlify respects the new requirements and builds the docs site again.
=> Docs: Pin mkdocs-material to older version to re-enable builds

health/notifications/alarm-notify.sh.in
This PR adds check to the `send_dynatrace` function. If method is disabled we need to exit early. 
`health`
- ask @mfundul to test it
=> health/alarm_notify: add dynatrace enabled check

aclk/agent_cloud_link.c, aclk/agent_cloud_link.h, aclk/mqtt.c
Fixes #8483 
- Improve the ACLK main thread shutdown sequence. 
- The thread's cancelability is disabled and the shutdown is detected by the `netdata_exit` variable.
- The netdata core would immediately cancel/kill the ACLK main thread during agent shutdown so the code outside the while loop would never be executed.
- The ACLK query thread empties the query queue and frees resources on shutdown
- Fixed memory leak (payload type parameter)
- Improved error / info message on disconnection from cloud
- When the connection is dropped due to the agent shutting down, it logs an information message
- When the connection actually fails, it logs an error message
- Trying to queue identical update commands to the query engine (i.e. an identical update is already in the queue) is now considered a …
=> Improved ACLK memory management and shutdown sequence

CMakeLists.txt, Makefile.am, exporting/aws_kinesis/aws_kinesis.c, exporting/exporting_engine.c, exporting/exporting_engine.h, exporting/graphite/graphite.c, exporting/json/json.c, exporting/mongodb/mongodb.c, exporting/mongodb/mongodb.h, exporting/opentsdb/opentsdb.c, exporting/process_data.c, exporting/prometheus/remote_write/remote_write.c, exporting/send_data.c, exporting/send_internal_metrics.c, exporting/tests/exporting_doubles.c, exporting/tests/netdata_doubles.c, exporting/tests/test_exporting_engine.c, exporting/tests/test_exporting_engine.h
Internal stats for the exporting engine are collected and displayed.
Closes #7171
Check internal statistics in "Netdta Monitoring" menu for every connector and for the main exporting engine thread
=> Show internal stats for the exporting engine

.github/workflows/build-and-install.yml, tests/updater_checks.sh
This explicitly pulls in libffi during CI checks on Arch Linux.
The `make` command depends on it (becaus it uses GNU Guile, which depends on libffi) but does not pull it in as a dependency. This isn't likely to affect user systems in most cases as they will almost certainly have Python installed, which also depends on libffi and pulls it in correctly, but our CI systems don't install anything unnecessary, so they don't have it.
area/ci
CI checks for Arch Linux pass on this PR.
This is a workaround for an upstream bug in Arch.
=> Fixed Arch Linux Ci checks.

collectors/ebpf_process.plugin/ebpf_process.c, collectors/ebpf_process.plugin/ebpf_process.h, libnetdata/ebpf/ebpf.c, libnetdata/ebpf/ebpf.h
Fixes #8621 
This PR brings the necessary changes inside the collector to it monitors correctly the kernel functions on RH 7.x and CentOS 7.x
Collector
Install Netdata with the option `--enable-ebpf`  and enable the collector insider your `netdata.conf`.
We detected a problem  with systemD that was not fixed yet.
=> Fixes compatibility with RH 7.x family

.yamllint.yml
Fixes: #8303
`check-keys` option was added in [v1.22.0](https://github.com/adrienverge/yamllint/releases/tag/v1.22.0)
> https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.truthy
`ci`
```dockerfile
FROM python:alpine
RUN pip install yamllint
WORKDIR /data
ENTRYPOINT ["yamllint"]
```
```cmd
0 ilyam:netdata (yamllint_enable_truthy_rule *)$ docker run --rm -v $(pwd):/data myyamllint -f colored --no-warnings . 2>&1 | grep truthy
1 ilyam:netdata (yamllint_enable_truthy_rule)$
```
=> yamllint: enable truthy rule

packaging/docker/publish.sh
Improve docker image publishing a little bit by not pushing in the background
=> packaging/docker/publish.sh: Publish docker images synchronously

aclk/agent_cloud_link.c
Fixes #8675
When ACLK fails and a reconnect is started, the LWS layer may fail immediately leaving
the agent in a false reconnecting state (but the lws layer is essentially dead)
ACLK
- Agent ACLK was tested on a link with simulated extreme timeouts (50000ms or more)
- Example (adjust as need; careful if test machine is remote)
```
sudo tc qdisc add  dev eth0 root netem delay 50000ms 
sleep 15m
sudo tc qdisc del  dev eth0 root netem
```
- The ACLK will fail in multiple stages
- LWS drops
- Challenge fails
- LWS cannot be established
- The agent enters a "connecting state",  `aclk_connecting` is set but the actual LWS layer has failed (no callbacks to reset `aclk_connecting`) and it stays there even after the network issues are resolved 
- This state does not happen always, but it *does* …
=> Improved ACLK reconnection sequence 

aclk/agent_cloud_link.c
Fixes #8675
When ACLK fails and a reconnect is started, the LWS layer may fail immediately leaving
the agent in a false reconnecting state (but the lws layer is essentially dead)
ACLK
Agent ACLK was tested on a link with simulated extreme timeouts (50000ms or more)
Example (adjust as need; careful if test machine is remote)
```
sudo tc qdisc add  dev eth0 root netem delay 50000ms 
sleep 15m
sudo tc qdisc del  dev eth0 root netem
```
- The ACLK will fail in multiple stages
- LWS drops
- Challenge fails
- LWS cannot be established
The agent enters a "connecting state", aclk_connecting is set but the actual LWS layer has failed (no callbacks to reset aclk_connecting) and it stays there even after the network issues are resolved
This state does not happen always, but it does happen randomly.
=> Improved ACLK reconnection sequence

collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh
Fixes: #8687
Fixes: https://github.com/netdata/netdata/issues/5428#issuecomment-589941219
Current implementation treats all statuses except `ONLINE` and `ONBATT` as failed statuses.
https://github.com/netdata/netdata/blob/231d19351d0ea20aa66fd204215cbb24f34d7575/collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh#L50-L51
All available statuses [according docs](https://www.systutorials.com/docs/linux/man/8-apcaccess/):
- One or more of the following (space-separated): CAL TRIM BOOST ONLINE ONBATT OVERLOAD LOWBATT REPLACEBATT NOBATT SLAVE SLAVEDOWN
- COMMLOST
- SHUTTING DOWN
We have 2 reported problems:
- add `CAL ONBATT` status ([link](https://github.com/netdata/netdata/issues/5428#issuecomment-589941219))
- add `TRIM ONLINE` status …
=> charts.d/apcupsd: fix ups status check

aclk/agent_cloud_link.c
This PR fixes a crash (segfault, `pthread_cancel()` on non-existent thread) when Netdata is shutdown with ACLK disabled, currently the default.
ACLK
Verify no crash is observed when Netdata is shutdown. Perform verification in official Docker container (Alpine Linux/musl).
=> Fix crash when shutdown with ACLK disabled

aclk/agent_cloud_link.c
Follow-up to 8725.
aclk
There were some additional thread exits in the ACLK that had the same problem as fixed in the previous PR. This adds fixes to those cases.
=> Additional cases for the thread exit fix

.github/workflows/build-and-install.yml
The beta release of Fedora 32, including official Docker images, is officially out as of 2020-03-17. Final release is expected on 2020-04-21.
This PR adds Fedora 32 to the list of distribution releases we run build tests on.
area/ci
Verified that checks pass on this PR.
This is intended to act as a bellwether for basic Fedora 32 support. It will be marked ready for review when Fedora 32 is formally released, but until then I will be rebasing it regularly onto master to verify the build checks, and filing issues for any problems that I see.
=> Add Fedora 32 to build checks.

docs/netdata-for-IoT.md
In the command line given to edit the file `charts.d.conf`, the path to the script `edit-config` is missing so if you type it or paste it that way it won't work. So I think the easiest way to fix it would be to add the path in the command line given in the documentation.
Documentation
Run the command as given in the documentation and with the added path to see the difference.
The other solution would be add to the path `/etc/netdata` to the global `PATH` variable.
=> Added missing path

collectors/ebpf_process.plugin/ebpf_process.c, collectors/ebpf_process.plugin/ebpf_process.h
Fixes #8742 
This PR fixes the problem reported on #8742 and https://github.com/netdata/kernel-collector/issues/133.
Collector
1 - Create a shell script that has an infinite loop to write and remove information from disk
2 - Keep the collector running.
This is an improvement from the previous version, it is not a bug fix.
=> Ebpf index size

packaging/installer/methods/offline.md
0. Amend an incorrect command in the document, also correct the link to _install-required-packages.sh_ script.(https://github.com/netdata/netdata/blame/9342704a41cbd20a315e55f0b1ff3efd9f039498/packaging/installer/methods/offline.md#L37)
1. Make the parts of the example command that need to be filled by the user be clearly separated from other parts.(https://github.com/IceCodeNew/netdata/commit/e13d9a60a6d587ae80b2bfc7326b9a809aa48d69#diff-40714f9627176dfafc102507b4ffb471R73)
None.
None. It's just a rewording of the document.
Re-open [PR#8626](https://github.com/netdata/netdata/pull/8626), As I re-commit this change, the PR was automatically closed. Never thought about such consequence before I issue `git reset --hard HEAD~N` and `git push -f` :-(
=> [ReOpen #8626] Improved offline installation instructions to point to correct installation scripts and clarify process

packaging/installer/methods/pfsense.md
* update to latest netdata package versions in pfSense installation documentation and add missing dependencies
* add warning when using apcupsd to prevent memory leak and high cpu usage
If netdata is started before `apcupsd` (happens when starting apcupsd automatically through checkbox in GUI and netdata through shellcmd mechanism) a `cat` process will eat up CPU and RAM. The `cat` process seems to be triggered by the default activated `apcupsd` netdata charts plugin (writes to `/tmp/.netdata-charts.d-foo/run.foo`). When disabling the netdata apcupsd plugin, the cat process is not spawned at boot.
But without disabling the netdata apcupsd plugin it can be prevented by ensuring apcupsd is started before netdata with for example the following as a shellcmd command:
`service apcupsd …
=> Update pfSense doc and add warning for apcupsd users

netdata-installer.sh, netdata.spec.in, packaging/installer/install-required-packages.sh
This adds support to the installer and the packaging code to properly pull in JSON-C so that we can use that instead of our buggy internal JSON parser.
area/packaging
Tested locally and verified in CI.
This will require netdata/helper-images#74 to be merged before the CI can pass
Fixes: #8775
=> Added JSON-C dependency handling to instlal and packaging.

aclk/README.md, claim/README.md
Fixes netdata/marketing#223
I've been getting requests to add instructions on how to claim a Docker-ized Agent, and this PR adds my best effort to document this process.
There seems to be a preference to tell users how to pass daemon command line options (see #8486), but I haven't been able to figure out how to successfully pass those. Using `docker exec -it` plus the claiming script straight from Cloud seems to work just fine, on the other hand, and seems much easier for users. Using `docker run` means they have to stop their container first.
If someone has successfully claimed a Docker node using a command like `docker run -it netdata --entrypoint '/usr/sbin/netdata -D -W "claim url=...."'`, and believes that is indeed the preferred method of claiming in this case, I'm happy to add it, …
=> Docs: Add Docker instructions to claiming

daemon/system-info.sh
When using `lscpu` to determine the CPU frequency, we want to preferentially use the `CPU max MHz` value over `CPU MHz`, as the later reflects the current CPU frequency in most cases, not the frequency that the CPU would be advertised with.
Unfortunately, the original code for parsing this info out of `lscpu` output did not take into account that some systems do not report a `CPU max MHz` value, but still report `CPU MHz`. Reporting something on such systems is better than reporting nothing, so we should fall back to `CPU MHz` if it's present.
area/daemon
Verified locally to not change behavior for systems that weren't affected, and to fix it for systems that were.
Originally spotted by @manos-saratsis.
=> Fixed issue in `system-info.sh`regarding the parsing of `lscpu` output.

health/health.d/portcheck.conf
ssia
Fixes: #8741
Reasoning in the issue
`health/alarms`
Not needed
=> health/portcheck: remove no-clear-notification option

health/health.d/mdstat.conf
Fixes: #8793
> The default alarm for failed mdstat disks no longer works, the "total" variable was replaced by "down" in #6164 but the alarm wasn't updated to reflect this change.
`health/alarms`
Not needed. It is pretty obvious change.
=> health: fix mdstat `failed devices` alarm

.travis.yml, packaging/docker/build.sh, packaging/docker/publish.sh
Simplify the docker packaging build and publish shell scripts. Support building and packaging only one ARCH at a time.
=> packaging/docker/{build,publish}.sh: Simplify scripts. Support only single ARCH

Makefile.am
ssia
Fixes broken package buidls:
```
packaging/bundle-dashboard.sh . /home/builder/netdata-1.21.183/debian/netdata/var/lib/netdata/www
make[1]: packaging/bundle-dashboard.sh: Command not found
make[1]: *** [debian/rules:68: override_dh_install] Error 127
make[1]: Leaving directory '/home/builder/netdata-1.21.183'
make: *** [debian/rules:22: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
DEB build script completed!
```
As seen [here](https://travis-ci.com/github/netdata/netdata/jobs/323238968)
Currently affecting nightlies.
- area/si
- Travis CI (_ we should have a test for this_)
=> Fix build and add bundle-dashbaord.sh to dist_noinst_DATA

netdata-installer.sh
When updating the dashboard handling code, I forgot to remove this call to a now nonexistent function.
area/packaging
Passes CI.
=> Removed old function call in netdata-installer.sh

system/netdata.conf, system/netdata.service.v235.in
1. In netdata.conf file, bind to is mentioned under [global] section but it should be under [web] section as per documentation here, https://docs.netdata.cloud/web/server/
2. Recently netdata.service.in was updated but same changes were not made to netdata.service.v235.in file. This PR does that.
=> bind to should be in [web] section and update netdata.service.v235.in too

aclk/agent_cloud_link.c, build_external/projects/aclk-testing/agent-compose.yml, build_external/projects/aclk-testing/agent-valgrind-compose.yml, claim/README.md, claim/claim.c, claim/claim.h, claim/netdata-claim.sh.in, daemon/commands.c, daemon/daemon.c, daemon/main.c, libnetdata/config/appconfig.c, netdata-installer.sh, packaging/docker/Dockerfile, registry/registry.c
Fixes https://github.com/netdata/product/issues/839
Fixes #8622
agent
claiming
cloud
Continuation of https://github.com/netdata/netdata/pull/8818
We agreed to:
- remove cloud enable and cloud base URL configuration from `netdata.conf` completely
- put them in the `claim.d` configuration folder
- move the `claim.d` folder to `/var/lib/netdata` and rename it to `cloud.d`
- update documentation
=> Fix claiming config

packaging/bundle-dashboard.sh
This removes some code from the dashboard bundling script that was left over from before we changed how we were handling prefixing the old dashboard. The script did not get properly tested after that change in design, so the code unfortunately made it into master and broke package builds.
area/packaging
Verified locally for both DEB and RPM packages.
=> Fixed bundling of dashboard in binary packages.

Makefile.am, configure.ac
1. If `json-c-devel` (or equivalent pkg in other distros) available use it.
1. If not try and check if static build is available in `externaldeps` folder (by installer) and use it.
1. If no json-c is available don't build ACLK in `detect` (default mode - build ACLK if you can but build netdata always) and error out in configure if `--enable-aclk` flag given (telling us user specifically wants ACLK to be built)
Test with and without system JSON-c dev package. Test with configure flags `--enable-cloud`, `--disable-cloud`, and no flag (default autodetect mode). Test with renaming `libjson-c.a` and running configure (without installer who would build new lib) to simulate the case where the installer was not able to build static json-c.
=> JSON-c as hard dep. for ACLK

.github/dockerfiles/Dockerfile.build_test, .github/workflows/build-and-install.yml
This adds CI code to verify the JSON-C bundling functionality introduced by #8838 and #8836.
area/packaging
The new CI check explicitly requires the cloud functionality to build successfully when JSON-C is not provided by the system itself.
We skip this check on Arch Linux as JSON-C is part of the base install there (as a result of it being a dependenc of `cryptsetup`, which is part of the Arch Linux base install).
We skip this check on CentOS 7 as the version of `cmake` it provides is incompatible with the JSON-C build infrastructure. Installs on CentOS 7 when JSON-C is not installed through the package manager will succeed but will not have Netdata Cloud functionality.
=> Added CI to verify JSON-C bundling code in installer.

packaging/installer/kickstart.sh, packaging/installer/methods/kickstart.md
Fixes this:
```#!sh
root@debian:~# bash <(curl -Ss https://my-netdata.io/kickstart.sh)
[/root]# '' rm -f /etc/cron.daily/netdata-updater /dev/fd/63: line 114: : command not found
FAILED
```
ssia
- Ran this manually with my own fork directly until I fixed the error.
```#!sh
root@debian:~# bash <(curl -Ss https://raw.githubusercontent.com/prologic/netdata/fix_kickstart_error/packaging/installer/kickstart.sh)
[/root]# rm -f /etc/cron.daily/netdata-updater  OK
.
.
.
```
Looks like `kickstart.sh` needs some ❤️
=> Fix kickstart error removing old cron symlink

web/api/web_api_v1.c
Make cloud-enabled flag in web/api/v1/info be independent of ACLK build success
web
Have ACLK build fail and check dashboard info page
=> Make cloud-enabled flag  be independent of ACLK

web/gui/main.js, web/gui/old/index.html
In 1.22, old dashboard will still be accessible via /old suffix. Since old cloud will not be available, i've removed:
- sign in button
- old Cloud CTA on bottom of the page
- Nodes View buttons: in top bar and dropdown menu
fixes https://github.com/netdata/product/issues/872
web/gui
=> remove old-cloud related UI from old dashboard

packaging/installer/methods/manual.md
This is based on discussion today during the standup about the handling of issue #8854. It ideally should be merged before the 1.22 release.
area/docs
n/a
I'm not 100% certain that the place I'm putting this documentation is the best one, but I can't think of anywhere better myself. If anyone from the documentation/marketing team has suggestions for a better place to put it in the docs, I'll be happy to move it.
Long-term, the issue this is documenting a workaround for is planned to be fixed, but we've decided that it should not be put in the upcoming release as a fix would require modifying things in a way that would require rigorous re-testing o the cloud functionality in the agent, which we really don't have time for at the moment. This should be removed/reverted once #8863 is merged.
=> Added docmentation about workaround for clang build errors.

netdata-installer.sh, packaging/installer/functions.sh
ssia
Looks like this was always missing in our packaging tooling :/
=> Fix missing NETDATA_STOP_CMD in netdata-installer.sh

collectors/python.d.plugin/postfix/README.md
Fix command name for getting postfix queue
python.s.plugin/postfix
Change Readme, so not test needed
=> Fix command name for getting postfix queue

daemon/commands.c
Fixes clean shutdown via `netdatacli shutdown-agent` when using musl C library.
- Fixes #8945
daemon
Link with musl C library (e.g. alpine linux).
Run `./netdata -D`.
Shut it down with `netdatacli shutdown-agent`
=> Fix shutdown via netdatacli with musl C library

health/health_json.c
Fixes CID 358436
Remove check for old alarm status. We only care about events being in
CRITICAL or WARNING status and not superseded by another event 
ACLK
- Connect agent to the cloud
- Setup an alarm that will be triggered easily e.g.
```
template: 1min_cpu_usage
on: system.cpu
os: linux
hosts: *
lookup: average -1m unaligned of user,system,softirq,irq,guest
units: %
every: 30s
warn: $this > 2
crit: $this > 3
delay: down 15s multiplier 1.5 max 30s
info: average cpu utilization for the last 1 minute (excluding iowait, nice and steal)
to: sysadmin
```
- When the alarm fires
- Stop the agent
- In the cloud the node will be marked as unreachable
- Start the agent
- When ACLK is established the alarm status will be available to the cloud via the on_connect message
=> Remove check for old alarm status (CID 358436)

packaging/bundle-dashboard.sh
This fixes an error in the code used to bundle the React dashboard in our DEB and RPM packages which caused it to not be installed correctly, resulting in the packages only displaying the old dashboard.
area/packaging
Verified locally by reproducing the error and then re-running with the fixed code.
The particular issue this fixes can be verified without actually building the packages by using the following set of steps:
1. Create a test directory.
2. Run `packaging/bundle-dashboad.sh` from the Netdata source tree with the path to the source tree and the path to the test directory as arguments.
3. Check the contents of the test directory.
The result of those steps _should_ be that the test directory contains the contents of the `build` directory from the dashboard repo. The result before …
=> Fixed bundling of React dashboard in DEB and RPM packages.

Makefile.am
These got missed due to a lack of CI checking the case of installing from an archive produced using `make dist` on a system without JSON-C.
area/packaging
Manually verified that `make dist` produces an archive with these files after this change.
This can be tested locally by creating a dist tarball (`autoreconf -ivf && ./configure && make dist` from the top level of the Netdata source tree), and then running the `netdata-installer.sh` script included in the dist tarball.
Fixes: #8970
@prologic This got bumped to top priority by @cakrit as needing to go into an imminently upcoming v1.22.1 bugfix release.
=> Added JSON-C packaging fils to make dist.

claim/README.md, daemon/main.c
#Fixes https://github.com/netdata/netdata/issues/8969
Restore old semantics of "netdata -W set" command
daemon
Make sure that claiming by command line and docker dashboard work.
=> Restore old semantics of "netdata -W set" command

aclk/aclk_lws_wss_client.c, aclk/agent_cloud_link.c, aclk/mqtt.c
Fix a latency issue on the ACLK.
The on-connect payloads were large enough to trigger a massive increase in latency on the link and prevent chart updates due to head-of-line blocking. The default window detection in libwebsockets was under-reporting the size of the available window in the network. Overwritten with some sensible values.
The large volume of ACLK per-message info-logging is not produced unless the agent is compiled with NETDATA_INTERNAL_CHECKS. The logging now includes latency measurements on the link.
ACLK
Connected / disconnected multiple times to staging / production. Checked the table view and chart view of the agent.
=> Fix the latency issue on the ACLK and suppress the diagnostics

collectors/python.d.plugin/varnish/varnish.chart.py
Adds compatibility for varnish-plus
varnish
Varnish-plus is required in order to perform tests.
Changes were tested with varnish and varnish-plus versions
Currently netdata cannot load varnish module when using varnish-plus package due to the regex to parse the version:
python.d ERROR: varnish[varnish] : failed to parse reply from '/usr/bin/varnishstat -V', used regex :'varnish-(?P\d+).(?P\d+).(?P\d+)', reply : [u'/usr/bin/varnishstat (varnish-plus-6.0.6r1 revision )\n', u'Copyright (c) 2006 Verdens Gang AS\n', u'Copyright (c) 2006-2019 Varnish Software AS\n']
=> [varnish] : added compatibility for varnish-plus

collectors/python.d.plugin/postgres/postgres.chart.py
template1 and template0 are system postgres tables. It's no need to monitor them, which was intended by a code, but it regex contains space that breaks everything.
postgres.chart.py
template0/tempate1 should not be visible
=> postgres.chart.py: fix template databases ignore

packaging/docker/README.md
The Docker Compose example in the Caddy section didn't include the important volumes:
- netdatalib:/var/lib/netdata
- netdatacache:/var/cache/netdata
documentation
=> Caddy section lacked data persist volumes

collectors/ebpf_process.plugin/ebpf_process.c, collectors/ebpf_process.plugin/ebpf_process.h
Fixes #8716 
This PR brings the features described on #8716 and also brings the basis to develop #8731, #7873 and #8727.
Collector
Compile this PR with the option `-DNETDATA_INTERNAL_CHECKS=1` and add the following options inside your `netdata.conf`:
```
[plugin:ebpf_process]
command options = --global --all --net --process --return
#command options = -a -r
#command options = -a -n -p -r
#command options = -g -n -p -r
```
When Netdata starts it is expected it will show messages related the option given.
There are two options that needs to be tested using terminal:
```bash
```
=> Ebpf options

health/health.d/ram.conf
ram_in_use was not correctly deducting the used_ram_to_ignore -
it deducted it from both the 'used' and 'unused' side of the equation,
which made a large ZFS ARC (like all of them) report high ram
utilization all the time, firing off the 90% alert despite 40% of the used
ram being reclaimable cache.
Fixes #7871
health.d/ram.conf
Review the system - ram alarm on a system with ZFS which has been running long enough to fill up the ZFS arc.  Without this patch, you see the entire size of the arc reflected in this alarm as unavailable RAM.  With this patch, the ZFS arc (minus the minimum size) is treated as available cached memory when calculating this alert.
=> Account for zfs.arc_size.min, and correct calc

web/api/netdata-swagger.json
This change adds a missing bracket to the Netdata API swagger json file. 
web/api
Before this change, passing this swagger document into openapi-generator (https://github.com/OpenAPITools/openapi-generator) would fail with syntax errors. After this change, the client and models are properly generated.
I'm not sure if this file is generated from the `.yml` file or maintained by a real person. Let me know if this is the right place for this type of change.
=> Fixed formatting in API swagger json file

CMakeLists.txt, Makefile.am, exporting/exporting_engine.c, exporting/exporting_engine.h, exporting/process_data.c, exporting/tests/exporting_doubles.c, exporting/tests/test_exporting_engine.c, exporting/tests/test_exporting_engine.h
Error handling in the exporting engine was revised. Any breaks while locks are hold were changed to flag checking/changing.
Closes #7173 
The output of every connector was checked.
=> Fix error handling in exporting connector

CMakeLists.txt, Makefile.am, configure.ac, daemon/common.h, daemon/main.c, database/rrd.h, health/health.c, health/health.h, libnetdata/popen/popen.c, libnetdata/popen/popen.h, spawn/Makefile.am, spawn/spawn.c, spawn/spawn.h, spawn/spawn_client.c, spawn/spawn_server.c
Fixes #8368
Fixes #8251
Improve netdata scalability by reducing the impact of alarm execution and notification to critical sections in the main health thread.
health
daemon
Set-up a bare metal server with 500 lxc containers as netdata slaves connected to the master in the host. Used dbengine as memory mode for both netdata.conf and stream.conf.
Make sure the spawn server process shuts down correctly.
Make sure the spawn server process does not fail to start.
Run: `/etc/netdata/edit-config health.d/cpu.conf` and set contents such as:
```
template: 1min_cpu_usage
on: system.cpu
os: linux
hosts: *
lookup: average -1m unaligned of user,system,softirq,irq,guest
units: %
every: 30s
crit: $this > 2
delay: down 15s multiplier 1.5 max 30s
info: average cpu utilization for the last …
```
=> Improve the impact of health code on netdata scalability

web/gui/dash-example.html
This update brings a couple of changes:
* Hosts are sorted alphabetically by default. User configured sorting preferences are still respected.
* When clicking on a host name in the Alarms menu/list, that link will scroll you to the correct host within `dash.html` rather than the node's own netdata page
Fixes: #8749
=> Sort alphabetically and automatic scroll

collectors/python.d.plugin/samba/samba.chart.py
Only use sudo when not running as root user
python.d samba collector
I have applied this patch to my instance and all is good so far monitoring samba.
=> [python.d/samba] Only use sudo when not running as root user

packaging/docker/Dockerfile, packaging/docker/README.md, packaging/docker/run.sh
This cuts the final Docker image sizes for 64-it x86 by approximately 140MB.
The functionality being removed here only ever gets used on 64-bit x86 Docker images.
The claimed benefit to the functionality being removed is improved resistance to exploits that rely on knowledge of the memory layout of certain structures. This is great in theory, but is of questionable benefit in practice for a couple of reasons:
* Because it's being done at build time and not startup, each instance of our containers started from a given image is the same. That consistency at least partially undermines the randomization being done. It was deemed in the original request that doing this unconditionally at runtime would be too much overhead.
* It doesn't actually protect Netdata itself, which is the primary …
=> Removeed Polyverse Polymorphic Linux from Docker builds.

packaging/installer/methods/freebsd.md
After going through the installation on my FreeBSD system, I was told that the websockets couldn't be installed because cmake wasn't on my system. I believe 'cmake' is requred for websockets to be installed, but it isn't included for the FreeBSD installation. 
cmake
I'm not sure if this was left out intentionally for some reason. Thank you for reading.
=> Included 'cmake' in the list of pkgs installed

packaging/makeself/jobs/70-netdata-git.install.sh
The current code overwrites netdata.conf when updating a static install because we include a copy of the default empty netdata.conf in the package itself.
This removes that file from the generated package, but does not modify the install-time logic which attempts to create the file if it does not already exist (which appears to be working correctly.
area/packaging
Locally built and verified that the static installer does not include `netdata.conf` in the archive anymore.
Fixes: #8531 
Fixes: #8679 
To all our users who were affected by this, sorry it took so long to fix it.
=> Don't overwrite netdata.conf on update on static installs.

daemon/main.c, daemon/signals.c, daemon/signals.h
Fixes #9084
Fixes #9070
daemon
Install in netdata docker image, observe no zombie processes.
As described [here](https://github.com/libuv/libuv/issues/154) libuv `uv_spawn()` uses `SIGCHLD` internally:
https://github.com/libuv/libuv/blob/cc51217a317e96510fbb284721d5e6bc2af31e33/src/unix/process.c#L485
and inadvertently replaces the netdata signal handler which was setup during initialization. Thusly, we must explicitly restore the signal handler for SIGCHLD. Note to self: extreme care is needed when mixing and matching POSIX and libuv.
=> Restore SIGCHLD signal handler after being replaced by libuv

aclk/agent_cloud_link.c, claim/claim.c, web/api/web_api_v1.c
Closes #9032 
If the agent is re-claimed at run-time then the new claim_id is not applied to the base-topic for the ACLK. This causes the broker to kick the agent for writing to the wrong topic.
ACLK
* Start a claimed agent
* Remove the agent from its room
* Re-claim the agent (without stopping it), using -id=$(uuidgen)
* Re-connect the agent
=> Regenerate topic base on connect

collectors/ebpf.plugin/README.md
The main motivation behind the PR is to follow up on #8665, which enables eBPF by default on new installations. The documentation now reflects that while also directing users with older/non-nightly versions to explicitly enable it. In addition, I moved some of the old information about KPROBES and the required filesystems to a **troubleshooting** section.
I also took this opportunity to run through the doc and make additional fixes to the text where applicable.
collectors
=> Update eBPF documentation to reflect default enabled status

exporting/exporting_engine.c, exporting/mongodb/mongodb.c
Part of #7172
Configure a MongoDB exporting connector instance. Run Netdata. Kill it with SIGTERM.
=> Dynamic memory cleanup for MongoDB exporting connector

contrib/debian/netdata.postinst.in, contrib/debian/rules
Signed-off-by: Arthur Outhenin-Chalandre <arthur@cri.epita.fr>
Fixes #8888 
Fix installation of suid plugins in debian packaging
packaging
`chown -R root:netdata /usr/libexec/netdata/plugins.d` in postint also remove the suid bit for all binaries in the directory. This PR fix that by adding some `chmod` in postint after the `chown`.
=> Fix suid bits on plugin for debian packaging

daemon/system-info.sh
This contains the following overall changes:
* We now properly count APFS instances only once instead of once per mount point (note that I'm avoiding the term 'volume' here because APFS uses it like a logical volume manager and not a filesystem).
* On Linux, we now look up device major numbers in `/proc/devices` instead of hard coding them, This simplifies handling of device types which use dynamically assigned device major numbers, as well as making the code more robust and easier to update in the future. We still need to do device number matching for reliability reasons.
* We now also look at NVMe devices (we were ignoring them previously).
* We now handle BTRFS on Linux in a manner similar to APFS on macOS, except we're able to use simpler deduplication logic because BTRFS behaves like …
=> Improve system-info.sh to better handle certain cases when gathering info on the system's disk capacity.

netdata.spec.in
EPEL is splitting the main netdata package into 3:
- **netdata** that gets updated by our upstream package and is the core
- **netdata-data** that contains the dashboard (/usr/share/)
- **netdata-conf** that contains the configuratio (/etc/netata)
When users try to use netdata installer, it'll update only the "netdata" package. As this package also provides `/etc/netdata` and `/usr/share` files (currnetly belonging to netdata-conf and netdata-data) it'll fail during the post-transaction check.
Using "obsoletes" keyword, if official netdata package is installed, it'll also remove the 2 conflicting epel packages.
I didn't want to add the keyword "Provides", and rather break external packages that are dependant on EPEL versions.
That way, they can either:
* update their `Require` field to …
=> Package: obsoletes conflicting EPEL packages (#6879 #8784)

exporting/pubsub/pubsub.c, exporting/pubsub/pubsub.h, exporting/pubsub/pubsub_publish.cc, exporting/pubsub/pubsub_publish.h, exporting/tests/test_exporting_engine.c
Part of #7172
Configure a Pub/Sub exporting connector instance. Run Netdata. Kill it with SIGTERM.
=> Dynamic memory cleanup for Pub/Sub exporting connector

exporting/aws_kinesis/aws_kinesis.c
When a buffer was larger than the maximum allowed size, it was split incorrectly and some messages didn't end with the new line character.
Part of #8461 
Define a small value for `KINESIS_RECORD_MAX`, send metrics to a Kinesis stream. Check if every message ends with the new line character
=> Fix buffer splitting in the Kinesis exporting connector

contrib/debian/netdata.postinst, contrib/debian/netdata.postrm, contrib/debian/netdata.preinst, contrib/debian/rules
Signed-off-by: Arthur Outhenin-Chalandre <arthur@cri.epita.fr>
Fixes #8878 
Fixes start/enable of netdata because of missing `#DEBHELPER#` in debian scripts.
I also removed the templating for postinst, AFAIK It is unused as the templated script and the final script are identical.
packaging
=> Fixes enable/start of netdata service in debian package

backends/backends.c, exporting/exporting_engine.c, exporting/exporting_engine.h, exporting/init_connectors.c, exporting/read_config.c
In order to make the transition from backends to the new exporting engine smoother, we need to understand if Netdata users are ready for removing the backends subsystem completely.
Part of #8461
Check `error.log`.
=> Send anonymous statistics from backends and exporting engine

netdata-installer.sh
Reverts netdata/netdata#8865
This PR broke our static builds. SEe https://github.com/netdata/netdata/pull/9130
Rather than delay the fix (_it needs cleaning up and a proper CI in place_) I'd like to revert this so we can get correctly build static builds back out ASAP.
Fixes #9135
=> Revert "Fix macOS builds building and linking against openssl"

exporting/read_config.c
Warn a user if the update interval of an exporting connector instance is not a multiple of the database update interval.
Part of #8461
Set the "update interval" option in the `[general]` section of `netdata.conf` and for a connector instance. Check `error.log`.
=> Check update interval for exporting connector instance

.github/workflows/build-and-install.yml, packaging/installer/install-required-packages.sh
We somehow forgot to include the bundle for libuuid in our dependencies on ClearLinux, this fixes that.
area/packaging.
Checked locally that the correct package is installed and verified the build of Netdata.
Fixes: #9051
=> Added required bundle for libuuid on ClearLinux.

.github/scripts/build-static-x86_64.sh, .github/scripts/functions.sh, .github/workflows/build-and-install.yml, packaging/makeself/build-x86_64-static.sh, packaging/makeself/build.sh, packaging/makeself/install-alpine-packages.sh, packaging/makeself/jobs/70-netdata-git.install.sh
ssia
- Fixes #9147
- area/ci
- This PR.
In working on #9093 I discovered by acciden that something somewhere,
somehow had borkne our ability to build Netdata and statically link it.
~This means our recent kickstart-static64 builds are in very likely no longer
static and will start to cause problems for our users.~ They were in fact broken by #8865
~This PR is to prove that by putting up a CI check that fails if the following
shell expression also fails:~ This PR now ensures we do not break the static builds.
=> Add CI for our Static Netdata builds (which kickstart-static64 uses)

packaging/installer/netdata-updater.sh, tests/updater_checks.bats
ssia
Tested the shell expression:
```#!sh
sleep $(((RANDOM % 10) + 1))s
```
This will hopefully aliviate the stampede like effect we're seeing in Netdata
Cloud Production where we see spikes of disconnections and reconenctions.
The timing lines up with the default Debian crontab entry for "daily" jobs
and thus adding a random sleep into the updater should help spread this out
a bit and reduce load on our system9s) in short intervals.
=> Introduce a random sleep in the Netdata updater

parser/parser.c
Fixes #9156
Empty lines should be ignored and not trigger an error
=> Fixed bug in accepting empty lines in parser

exporting/aws_kinesis/aws_kinesis.c, exporting/read_config.c
This PR brings the missing error report  as specified at #8461.
Exporting
1 - Compile the branch
2 - Configure `exporting.conf` without the necessary parameter:
```
[kinesis:my_instance2]
enabled = yes
destination = us-east-1
#stream name = netdata
#aws_secret_access_key = 
data source = as collected
#data source = sum
update every = 2
send charts matching = system.processes
```
3 - Run Netdata
4 - Verify if the message was written inside error.log
This PR does not brings everything listed on #8461 and it is not a blocker for any other action there.
=> Missing error aws

packaging/installer/netdata-updater.sh, tests/updater_checks.bats
Reverts netdata/netdata#9079
This is still causing Travis CI builds to fail and bail out because of the sleep. I missed that this is a bit more complicated to do in Cron but not do in our Lifecycle tests because of the intricacies of how our lifecycle tests are tied up with kickstart and the netdataer-updater.
=> Revert "Introduce a random sleep in the Netdata updater"

exporting/send_internal_metrics.c, health/Makefile.am, health/health.d/backend.conf, health/health.d/exporting.conf
This PR brings the new alarms as specified at #8461.
Exporting
Backend
1 - Create an `exporting.conf`
```
enabled = yes
send configured labels = yes
send automatic labels = no
[json:my_instance0]
enabled = yes
destination = localhost:5448
[opentsdb:http:instance1]
enabled = yes
destination = localhost:5449
```
2 - Start the servers
```
$ nc -lntp 5448 &
$ nc -lntp 5449 &
``` 
3 - Start Netdata
4 - Download `http://localhost:19999/api/v1/alarms?all` and verify that you have the 6 alarms expected.
1 - Remove the previous `exporting.conf`
2 - Configure `netdata.conf`
[backend]
enabled = yes
type = json
destination = localhost:5448
3 - Start the server:
```
$ nc -lntp 5448 
``` 
4 - Start netdata
5 - Access `http://localhost:19999`, you will receive an alarm saying to …
=> New alarms (exporting and Backend)

exporting/aws_kinesis/aws_kinesis.c, exporting/graphite/graphite.c, exporting/json/json.c, exporting/opentsdb/opentsdb.c, exporting/prometheus/remote_write/remote_write.c
This PR brings the missing tests to returns for `uv_`  functions as specified at #8461.
Exporting
1 - Start hbase
2 - Start zookeper
3 - Start opentsdb running: ./tsdb tsd --port=4242 --staticroot=staticroot/ --cachedir=/tmp/tsd --zkquorum=localhost:2181 --auto-metric
4 - Start JSON backend running:  `nc -lntp 5448`
5 - Start MongoDB: The command here depends of the distribution.
6 - Configure `exporting.conf`:
```
enabled = yes
send configured labels = yes
send automatic labels = no
[json:my_instance]
enabled = yes
destination = localhost:5448
[opentsdb:http:my_instance2]
enabled = yes
destination = localhost:4242
[mongodb:instanceA]
enabled = yes
destination = mongodb://localhost
database = netdata
collection = instanceA
```
@vlvkobal , please, update the example …
=> Missing checks exporting

collectors/plugins.d/pluginsd_parser.c
Fix coverity issue CID 358971
```
*** CID 358971:  Null pointer dereferences  (FORWARD_NULL)
/collectors/plugins.d/pluginsd_parser.c: 317 in pluginsd_chart()
311             size_t len = strlen(type);
312             if (strncmp(type, name, len) == 0 && name[len] == '.')
313                 name = &name[len + 1];
314     
315             // if the name is the same with the id,
316             // or is just 'NULL', clear it.
>>>     CID 358971:  Null pointer dereferences  (FORWARD_NULL)
>>>     Passing null pointer "id" to "strcmp", which dereferences it.
317             if (unlikely(strcmp(name, id) == 0 || strcasecmp(name, "NULL") == 0 || strcasecmp(name, "(NULL)") == 0))
318                 name = NULL;
319         }
320     
321         int priority = 1000;
322         if …
```
=> Fixed coverity warning (CID 358971)

exporting/exporting_engine.h, exporting/opentsdb/opentsdb.c, exporting/opentsdb/opentsdb.h, exporting/read_config.c, exporting/send_data.c, libnetdata/socket/security.c
Fixes #8111
Fixes #8847
This PR also brings another feature described at #8461.
Exporting
To test this PR, the suggestion is to use OpenTSDB to confirm that it continues sending data using `HTTP` and InfluxDB to test `HTTPS`, this is the simplest road.
1 - Start hbase
2 - Start zookeper
3 - Run OpenTSDB with the command: `tsdb tsd --port=4242 --staticroot=staticroot/ --cachedir=/tmp/tsd --zkquorum=localhost:2181 --auto-metric` 
4 - Configure your `exporting.conf`:
```
enabled = yes
[opentsdb:http:my_instance0]
enabled = yes
destination = localhost:4242
#database = netdata
```
5 - Start Netdata
6  - Access localhost:4242 and confirm the metrics are there.
1 - Stop Netdata and OpenTSDB
2 - Edit `influxdb.conf` and uncomment the lines related to OpenTSDB:
```
[[opentsdb]] …
```
=> OpenTSDB and TLS

exporting/README.md
The exporting engine is ready. It's not an experimental subsystem anymore.
=> Remove the experimental label from the exporting engine documentation

.github/CODEOWNERS
Based on discussion within the SRE team. They are not directly involved anymore with the agent components maintained by the SRE team, so there's no point in pestering them all the time with review requests when the rest of the SRE team is suficient for a complete review.
In the event that a change warrants their attention, they'll be explicitly added as reviewers by hand.
Infrastructure
n/a
=> Remove knatsakis and ncmans from CODEOWNERS for the agent.

CMakeLists.txt
Fixes #9185
Added missing source code files to handle compilation errors using cmake e.g
```
[ 99%] Linking CXX executable netdata
/usr/bin/ld: CMakeFiles/netdata.dir/collectors/plugins.d/plugins_d.c.o: in function `pluginsd_worker_thread':
/home/vlad/netdata/collectors/plugins.d/plugins_d.c:346: undefined reference to `pluginsd_process'
/usr/bin/ld: CMakeFiles/netdata.dir/streaming/rrdpush.c.o: in function `rrdpush_receive':
/home/vlad/netdata/streaming/rrdpush.c:1295: undefined reference to `pluginsd_process'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/netdata.dir/build.make:2286: netdata] Error 1
make[1]: *** [CMakeFiles/Makefile2:773: CMakeFiles/netdata.dir/all] Error 2
make: *** [Makefile:115: all] Error 2
```
- Should compile using cmake
=> Fixed cmake build affected by #9074

exporting/clean_connectors.c
Clean a string with a connector type on Netdata exit.
=> Clean type_name in exporting connector instance configuration

collectors/python.d.plugin/ceph/ceph.chart.py, web/gui/dashboard_info.js
Added OSD size (=capacity) collection to the ceph plugin.
This will usually not vary:  an osd has a defined capacity based on the
underlying disk.
So it might not make sense to collect it, contrary to the osd_usage, which is the used space and varies as data is written to ceph.
But not collecting the osd_size prevents from computing used ratio (osd_usage / osd_size) or available space (osd_size - osd_usage), which are useful metrics.
Ceph python plugin
I use the modified plugin on a production cluster:
- PROXMOX Virtual Environment 6.1-8
- Ceph version 14.2.8
I verified that the additional data was collected.
The 'kb' field has the same format as the 'kb_used' field in `ceph osd df --json` output.
Sample  `ceph osd df --json` output:
{
"nodes": [
{
"id": 12,
"device_class": "ssd",
"name": …
=> Ceph: Added OSD size collection

exporting/tests/test_exporting_engine.c
Unit tests for the exporting engine were broken after #9075.
Run `sudo make check` in Netdata build directory
=> Fix exporting unit tests

.github/scripts/build-artifacts.sh, .github/scripts/bump-packaging-version.sh, netdata-installer.sh, packaging/installer/functions.sh, packaging/makeself/build.sh, packaging/makeself/functions.sh, packaging/makeself/install-alpine-packages.sh, packaging/makeself/jobs/10-prepare-destination.install.sh, packaging/makeself/jobs/50-bash-4.4.18.install.sh, packaging/makeself/jobs/50-curl-7.60.0.install.sh, packaging/makeself/jobs/50-fping-4.2.install.sh, packaging/makeself/jobs/50-ioping-1.1.install.sh, packaging/makeself/jobs/70-netdata-git.install.sh, packaging/makeself/jobs/99-makeself.install.sh, packaging/makeself/run-all-jobs.sh
ssia
- Fixes #9093
TBD
**NB:** This effectivly disables the error resulting from `check-kernel.sh`
and instead displays a warning. This means `./netdata-installer.sh` will still
install the eBPF kernel-collector package but it _may_ not work on a user's
system that either a) Lack a Linux Kernel (_currently_) or b) Lack required Kernel
config options.
This is okay; because the `ebpf.plugin` will just fail to load and backoff.
(_at some point we should build logic inot the Agent to disable plugins that continue to fail_)
=> Add support for eBPF for Netdata static64 (kickstart-static64.sh)

database/engine/README.md
Fixes part of #9106. The other work is at netdata/netdata-learn-docusaurus#159.
I came into the dbengine doc to make a few tweaks around multiple instances and streaming configs, but ended up doing a bit more refactoring. The primary goal here is to help users understand that in streaming setups, the dbengine uses separate instances for each node, despite sharing the same `page cache size` and `dbengine disk space` settings.
agent/database
=> Improve dbengine docs for streaming setups

aclk/aclk_lws_https_client.c, aclk/aclk_lws_wss_client.c, configure.ac
This PR allows building netdata in operating systems:
1. that `clock_gettime()` is not part for libc, but `librt` or `libposix4`
2. that have an openssl version that does not support `X509_VERIFY_PARAM_set1_host()`
netdata-installer.sh
On Centos 6 ACLK was disabled because of this:
```
checking if libmosquitto static lib is present (and builds)... no
```
The log was giving the error:
```
configure:8965: checking if libmosquitto static lib is present (and builds)
configure:8978: gcc -std=gnu99 -o conftest -O2    conftest.c externaldeps/mosquitto/libmosquitto.a -lcrypto -lssl >&5
externaldeps/mosquitto/libmosquitto.a(mosquitto.o): In function `mosquitto_lib_init':
mosquitto.c:(.text+0x5f): undefined reference to `clock_gettime'
externaldeps/mosquitto/libmosquitto.a(time_mosq.o): In function …
```
=> fix compilation for older systems

packaging/makeself/jobs/70-netdata-git.install.sh
The previous fix was incompletely tested and didn't actually workdue to
using an incorrect variable name. This fixes that.
area/packaging
Original testing only looked at intermediate stages, this one is now confirmed by testing the final output.
Fixes: #8531
=> Really prevent overwriting netdata.conf on static installs.

.github/scripts/build-artifacts.sh, netdata-installer.sh, packaging/installer/functions.sh, packaging/installer/kickstart-static64.sh, packaging/installer/kickstart.sh, packaging/installer/methods/kickstart-64.md, packaging/installer/methods/kickstart.md, packaging/installer/netdata-updater.sh
ssia
- Fixes #8967
For end-users:
1. Run the following on your system of choice:
```#!sh
NETDATA_TARBALL_BASEURL=https://storage.googleapis.com/netdata-dev-nightlies bash <(curl -q -sSL https://storage.googleapis.com/netdata-dev-nightlies/kickstart.sh)
```
2. Ensure you are on the right version `netdata -v` and that things are
working okay for you.
3. Confirm/Report that you don't see checksum failures inconsistently
anymore.
Replace `kickstart.sh` with `kickstart-static64.sh` to test the x86_64
static Netdata agent or if you cannot build from source.
----
For Contributors/Maintainers:
1. Run: `git clean -d -f -x`
2. Run: `.github/scripts/build-artifacts.sh`
If you are on macOS it will fail the first time with:
```#!sh
$ .github/scripts/build-artifacts.sh
Preparing build …
```
=> Fix reliability of kickstart/kickstart-static64 with checksums sometimes failing

packaging/installer/netdata-updater.sh, tests/lifecycle.bats, tests/updater_checks.bats
This reuses the code from #9079 but adds a CLI option to the script itself to disable the random offset when running from CI.
area/packaging
Verified locally that the offset code works correctly.
CI fixes verified on this PR.
=> Add a random offset to the update script when running non-interactively.

health/REFERENCE.md
Fixes #8239
After studying the code, testing, and then verifying with colleagues the functionality works but the syntax is a bit different than the expected *(which confuses people and makes them think it is broken)*. The issue is therefore solved by small clarification in the documentation.
Documentation
=> Fixes documentation ambiguity leading into issue #8239

libnetdata/circular_buffer/README.md
There's a missing dash `-` in the frontmatter for the `libnetdata/circular_buffer/README.md` document introduced in #9214, which is causing build failures on Learn. This PR adds that dash.
I should have caught this in the initial PR. That's my mistake.
libnetdata
docs
=> Fix frontmatter in circular_buffer README

claim/README.md, packaging/installer/README.md
Fixes #8306 
I added this notes section to the installation page where we can put notices like SSL and workarounds for various distros. I don't love cluttering up that page any more, but I can't figure out where else we could put this information with the best mix of discoverability and not being too in-your-face.
packaging/
=> Add notes/known issues section to installation page

daemon/commands.c, streaming/rrdpush.c, streaming/rrdpush.h, streaming/sender.c
Fix Coverity defects 359164, 359165 and 358989.
cli
streaming
The thread deadlocks have not been noticed in the three years that they've been in the code. There is not a test-case, please read the code and analyze if they fix the problem.
CIDs 359164-5 were caused by `done_push` acquiring the host lock while holding the chart lock (to control the spawning of the sender thread). Replaced this with the new fine-grained mutex that guards the sender buffer instead.
=> Fix Coverity defects 359164, 359165 and 358989.

packaging/installer/install-required-packages.sh
This adds basic support for macOS with Homebrew to `install-required-packages.sh`.
It installs everything required to actually build Netdata (except Judy, which is not available through Homebrew).
It has two significant limitations compared to using it on Linux:
* It requires the user to have already installed bash via Homebrew. macOS only includes an ancient version of bash for licensing reasons, and the script requires bash 4.x or newer.
* It can't run as root. Homebrew explicitly refuses to run as EUID 0 for safety reasons.
area/packaging
Verified operational on my local mac Mini running macOS Catalina.
This will preferentially use libraries provided directly by macOS to ones installed through Homebrew. It also forces Python 3 as Homebrew does not provide Python 2.7 (and it's a pain to …
=> Added support for macOS/Homebrew in `install-required-packages.sh`.

streaming/receiver.c
Fixes the crash part of #9291 - Did not account for the path where rrdhost_find_or_create fails and terminates the thread before setting rpt->host to a valid pointer.
streaming
Not sure how to replicate the database failure, but the code change is simple enough to read.
=> Fix crash in #9291

collectors/apps.plugin/apps_groups.conf
This service available only in k8s.
`collectors/apps.plugin`
=> apps_groups.conf: add agent-service-discovery

netdata-installer.sh
When we made eBPF default enabled, we removed the `--enable-ebpf` flag that had been used to enable it. This broke updates of existing installs that had explicitly enabled it, so re-add the flag as a functional no-op.
area/packaging
Tested locally in Docker, passes CI.
=> Added dummy `--enable-ebpf` flag to avoid breaking updates.

CMakeLists.txt, Makefile.am, daemon/unit_test.c, database/engine/global_uuid_map/global_uuid_map.c, database/engine/metadata_log/compaction.c, database/engine/metadata_log/compaction.h, database/engine/metadata_log/logfile.c, database/engine/metadata_log/logfile.h, database/engine/metadata_log/metadatalog.c, database/engine/metadata_log/metadatalog.h, database/engine/metadata_log/metadatalogapi.c, database/engine/metadata_log/metadatalogapi.h, database/engine/metadata_log/metalogpluginsd.c, database/engine/metadata_log/metalogpluginsd.h, database/engine/rrdengine.c, database/engine/rrdengine.h, database/engine/rrdengineapi.c, database/engine/rrdengineapi.h, database/rrd.h, database/rrddim.c, database/rrdhost.c, database/rrdset.c
Fixes #8902
The metadata log needs to be limited in disk space size. This PR implements a log compaction algorithm as described in #8902.
database
daemon
You may start/stop the agent many times so as to accelerate the rate at which the metadata logs grow. Observe in `error.log` the ratio of `records` to `objects`:
```
netdata INFO  : MAIN : records=2057 objects=1661
```
When this ratio is over 1.5 the compaction process should trigger, which should decrease the ratio and replace the metadata log files with new ones.
You may also kill the agent during compaction to test fault-tolerance. During start-up, the agent should decide what to do with the compaction temporary files and the original metadata log files.
=> Metadata log compaction

aclk/agent_cloud_link.c, database/rrd.h, database/rrddim.c, database/rrdhost.c, database/rrdset.c, parser/parser.c, streaming/receiver.c
Fixes #8924 
Expand the attributes of a chart / dimension / Host that can be dynamically updated
- Handle changes in dimensions (already there)
- Queue a metadata log update by calling `metalog_commit_update_dimension`
- Perform checks on chart updates
- Queue a metadata log update by calling  `metalog_commit_update_chart`
- TBA
=> Add support for collectors updating their metadata

exporting/tests/test_exporting_engine.c
A Unit test was failing after HTTP header formatting was changed in #9302.
=> Fix check for remote write header in unit tests

database/rrddim.c, database/rrdhost.c
Fixes issues to avoid coverity errors
- `Read from pointer after free (USE_AFTER_FREE)`
- Invalid memory access in `rrddim_free_custom` 
- `Explicit null dereferenced (FORWARD_NULL)`
- Use of NULL host variable if the host already exists  in `rrdhost_create`
agent
=> Fixed invalid memory access

backends/README.md, backends/prometheus/README.md, build_external/README.md, collectors/proc.plugin/README.md, daemon/config/README.md, database/engine/README.md, docs/guides/longer-metrics-storage.md, docs/guides/monitor-hadoop-cluster.md, docs/guides/step-by-step/step-09.md, docs/guides/using-host-labels.md, docs/netdata-security.md, exporting/README.md, exporting/prometheus/README.md, packaging/DISTRIBUTIONS.md, packaging/installer/methods/cloud-providers.md, packaging/installer/methods/macos.md, streaming/README.md, web/server/README.md
This PR replaces the usage of master/slave with parent/child when referencing streaming configurations/setups in Netdata. This is actually a more precise way to describe the relationship between these nodes, and modernizes the language we use in general.
@amoss Is working on a parallel change to the actual code. His PR should be merged before this so that we don't point users toward configs that don't yet exist, such as host labels.
area/docs
=> Change streaming terminology to parent/child in docs

database/engine/metadata_log/metadatalog.c, database/rrddim.c, database/rrdset.c
Fixed compiler warnings e.g. if agent compiled with the `--disable-cloud` flag
```
CC       database/rrddim.o
database/rrddim.c: In function 'rrddim_free_custom':
database/rrddim.c:497:21: warning: unused variable 'rrd_memory_mode' [-Wunused-variable]
497 |     RRD_MEMORY_MODE rrd_memory_mode = rd->rrd_memory_mode;
|                     ^~~~~~~~~~~~~~~
database/rrddim.c:461:53: warning: unused parameter 'db_rotated' [-Wunused-parameter]
461 | void rrddim_free_custom(RRDSET *st, RRDDIM *rd, int db_rotated)
|                                                 ~~~~^~~~~~~~~~
...
CC       database/rrdset.o
database/rrdset.c: In function 'rrdset_delete_custom':
database/rrdset.c:414:43: warning: unused parameter 'db_rotated' [-Wunused-parameter]
414 | void rrdset_delete_custom(RRDSET *st, int …
```
=> Fixed compiler warnings

database/rrdhost.c, database/rrdset.c
Fix New Defects reported by Coverity Scan for netdata/netdata
database 
New defect(s) Reported-by: Coverity Scan
Showing 2 of 2 defect(s)
** CID 359774:  Memory - illegal accesses  (USE_AFTER_FREE)
/database/rrdset.c: 1901 in rrdset_done()
*** CID 359774:  Memory - illegal accesses  (USE_AFTER_FREE)
/database/rrdset.c: 1901 in rrdset_done()
1895     
1896     #ifdef ENABLE_DBENGINE
1897                         if (rd->rrd_memory_mode == RRD_MEMORY_MODE_DBENGINE) {
1898                             rrddim_flag_set(rd, RRDDIM_FLAG_ARCHIVED);
1899                             rrddim_flag_clear(rd, RRDDIM_FLAG_OBSOLETE);
1900                             /* only a collector can mark a chart …
=> Fix coverity errors CID 359774 and CID 359773

daemon/daemon.c, daemon/daemon.h, daemon/main.c, spawn/spawn.c
Fixes #9331 
Fixes #9113 
daemon
Run it in affected CentOS 6 systems, see if the problem is resolved.
For some unknown reason some CentOS 6 installations fail to get the netdata binary execution path with libuv library calls and get "permission denied" errors. This PR attempts to get the path early before switching user to work around potential permission issues in path resolution or elsewhere.
=> Get netdata execution path early to avoid user permission issues

aclk/aclk_stats.c, aclk/agent_cloud_link.c
During the development of #9355 and also independently by Markos it was noticed that Aclk stats thread is accessing RRDDIMs and RRDSETs sometimes after they are already gone during the shutdown.
This fixes that and Fixes #9365
=> Fixed ACLK shutdown sequence

database/engine/metadata_log/compaction.c, database/engine/metadata_log/logfile.c, database/engine/metadata_log/metadatalog.c, database/engine/metadata_log/metadatalog.h, database/engine/metadata_log/metadatalogapi.c, database/engine/metadata_log/metalogpluginsd.c, database/engine/rrdengineapi.c
Fixes #9336
Add additional checks 
1. Recover from possible missing chart GUID compaction records that can result to incomplete metadata log replay information
- When a dimension compaction request is received  a check will ensure that it's chart is also *force compacted* if needed
1. Metric GUID generation to detects and recovers from collisions (caused by inconsistent metadata log information)
- This can happen when a corrupted metadata log file already exists due to case 1
1. Log unsuccessful GUID context switch (also due to corrupted metadata log file due to case 1)
database
=> Improved error handling and recovery during compaction and metadata log replay
