- database/rrdhost.c
- streaming/receiver.c
- streaming/rrdpush.c
- streaming/rrdpush.h
Fixes #9369 
The streaming component detects when a receiver stream has closed, and stops an attached sender on the same host. This is to support proxy configurations where the stream is passed through. During the shutdown sequence, once `netdata_exit` has been set no thread should touch any `RRDHOST` structure as the non-static threads are not joined before the database shuts down. 
During the shutdown sequence any attached sender is killed by the database during cleanup, so this patch just stops the receiver from trying to do the same.
streaming
* Connect many Child nodes to stream to the Parent.
* Shutdown the Parent and observe the valgrind output.
> Fixes the race-hazard in streaming during the shutdown sequence

- configure.ac
- libnetdata/log/log.c
- libnetdata/threads/threads.c
- libnetdata/threads/threads.h
Add support for the` fatal()` family of calls to detect non-netdata thread names from the OS.
daemon
Make the following change to trigger fatal error to a libuv thread.
```
--- a/spawn/spawn_client.c
+++ b/spawn/spawn_client.c
@@ -202,6 +202,8 @@ void spawn_client(void *arg)
spawn_thread_shutdown = 0;
/* wake up initialization thread */
complete(completion);
+sleep(1);
+fatal_assert(1 == 0);
prot_buffer_len = 0;
ret = uv_read_start((uv_stream_t *)&spawn_channel, on_read_alloc, on_pipe_read);
```
You should observe the real name and not `"MAIN"` in `error.log` .
I've been having problems building netdata in freeBSD and I don't have macOS access so please test those 2 platforms.
> Add libuv thread names support to FATAL log level

- streaming/sender.c
Fixes #9375 
We were not copying properly the data between buffer and with this the HOST variables were not properly copied to the parent.
Stream
1 - Compile this PR mainly on children hosts.
2 - Start parent and after few seconds start the slave.
3 - Do the following request for the parent `https://localhost:19999/host/CHILD_NAME/api/v1/alarm_variables?chart=system.load` and check if the variable `active_processors` is present.
4 - Repeat the steps 1, 2 and 3 at least three times.
> Fix missing host variables on stream

- exporting/read_config.c
- exporting/send_data.c
If `opentsdb:https` was configured along with another simple exporting connector (`graphite`, `json`), Netdata crashed when data was sent to the simple connector.
Configure `opentsdb:https` and `graphite` exporting instances. Check if Netdata doesn't crash when `nc -l -p 2003` is run.
> Fix a bug in the simple exporting connector

- database/rrdhost.c
- libnetdata/threads/threads.c
@mfundul 's analysis of the defect report:
1. Receiver thread disconnects from stream and pops `rrdpush_receiver_thread_cleanup()` during shutdown of pthread.
2. Skips this:
```
if (netdata_exit && rpt->host) {
rpt->exited = 1;
return;
}
```
because netdata has not exited yet.
3. Takes this branch for the same reason:
```
if (!netdata_exit && rpt->host) {
```
4. Before taking the `receiver_lock` it's scheduled out by the OS.
5. Now netdata exits. netdata_exit is set to 1 and rrdhost_free() runs the following code:
```
netdata_mutex_lock(&host->receiver_lock);
if (host->receiver) {
if (!host->receiver->exited)
netdata_thread_cancel(host->receiver->thread);
while (!host->receiver->exited)
sleep_usec(50 * USEC_PER_MS);
```
6. The receiver thread is scheduled back in, and hangs on:
``` …
```
> Fix Coverity Defect CID 304732

- collectors/cgroups.plugin/sys_fs_cgroup.c
unified cgroups setting is now `autodetect` by default.
Autodetects systems where systemd is compiled with unified cgroups as default and switches to unified cgroups automatically.
If autodetection fails revert to cgroupsv1 as default. This means if something fails in the new code we will behave same as before -> defaulting to cgroupsv1
If the user has specifically set the value in the config file. Do not autodetect and listen to the master.
Fixes #8907
Test on `debian` where cgroups v1 is used. Test on Fedora 32 with unified cgroups (default since Fedora31). Test on Fedora 32 with unified cgroups diabled (for example for docker) by setting `systemd.unified_cgroup_hierarchy=0` kernel parameter during boot.
Log should say the result of detection:
```
2020-06-02 12:06:48: netdata INFO  : …
```
> Autodetects unified cgroups

- README.md
- packaging/installer/README.md
- packaging/installer/methods/kickstart-64.md
- packaging/installer/methods/kickstart.md
This PR adds two notices to the packaging docs:
1. Instructions for fixing `Access to file is not permitted` issues: #8015
2. A mention alongside each `kickstart.sh`/`kickstart-static64.sh` script that these scripts install dependencies to connect to Netdata Cloud (cc @manos-saratsis)
area/packaging
area/docs
> Add notices to packaging docs for access errors and Cloud dependencies

- libnetdata/ebpf/ebpf.c
`ebpf.plugin` and several parts of the `kernel-collector` sibling project either read `/proc/sys/kernel/osrelease` directly or use it as a fallback. This file ends with a newline, which is read into the `kernel_string` variable. `ebpf.plugin` then fails to find the eBPF libraries because it's looking for a filename that ends with a newline.
Since it never makes sense for `osrelease` to include a newline, update `ebpf.plugin` to stop reading by the newline. This fixes the eBPF plugin on my system (which is running a custom kernel) and allows it to load the `kernel-collector` components.
`ebpf.plugin`
I haven't added any tests, but it'd be a good thing to add a test for. I assume a test for this doesn't already exist or it wouldn't have been a problem. 😊 
Similar commit for the …
> Stop reading from /proc/sys/kernel/osrelease at trailing newline.

- daemon/main.c
- database/rrdhost.c
Fixes #9427 
The spawn server was initialized before the registry to be initialized, but environment variables set for the function `registry_init()` must be set before the spawn server to be called. This PR moves the registry initialization position to fix this bug. 
Spawn Server
1 - Set registry server inside `netdata.conf`:
```
[registry]
enabled = yes
registry db directory = /var/lib/netdata/registry
registry to announce = https://localhost:19999
registry hostname = hades
```
2 - Create an alarm inside `/etc/netdata/health.d`, for example:
```
alarm: dev_dim_template
on: system.cpu
os: linux
lookup: sum -3s at 0 every 3 percentage foreach *
units: %
every: 1s
crit: $this > 4
```
3 - Configure `health_alarm_notify.conf` to send the alarm for a channel.
4 - Start Netdata …
> Fix internal registry 

- streaming/receiver.c
Fixes #9437 
When we brought updates for the stream, instead we give as argument the children version to create or update the host structure we are given the global local variable. This commit fixes this bug.
Stream
1 - Install this branch on the `parent`.
2 - Install an old stable version on the `child` node.
3 - Do the request `https://localhost:19999/host/CHILD_HOSTNAME/api/v1/info`  on the `parent` node, you need to see the `child` version instead `parent` version defined for `version` variable.
> Fix children version on stream

- daemon/main.c
Fixes https://github.com/netdata/netdata/issues/9435#issuecomment-651201925
This PR  fixes the missing call to `registry_init()` during the unittests.
Unit test
1 - Compile the branch
2 - Execute `/usr/sbin/netdata -W unittest`
3 - Confirm the final output:
```
ALL TESTS PASSED
```
>  Fix the unittest execution

- database/rrdcalc.c
- database/rrdhost.c
- health/health_log.c
The metadata log replay creates charts with linked alarms that may not reuse alarm_ids already present in the
heath-log.db. This will result in entries with different alarm ids for the same chart / name e.g. when shown 
via `http://localhost:19999/api/v1/alarm_log`, used in ACLK etc
To make sure we reuse the alarm id originally assigned and recorded in the `health-log.db` and `health-log.db.old` files process those files before metadata log replay
Add check to recover from corrupted files (`health-log.db` and `health-log.db.old`) that may already have different alarm_id for the
same chart / name
1. For each recorded alarm_id
- If it exists in another chart / name already loaded, generate a new one
health
ACLK
> Fixed duplicate alarm ids in health-log.db

- collectors/cgroups.plugin/cgroup-name.sh.in
Fixes #9287 
If a container is detected to be a k8s one, try the k8s naming. If it fails, default to normal container naming.
> Show cgroups ran by kubelet without access to k8s cluster info

- packaging/installer/README.md
- packaging/installer/methods/kubernetes.md
After wading my way through a crash-course in k8s over the last few days, I've realized we need some better information about how users can install Netdata on their k8s clusters. I'm no longer convinced simply linking to the Helm chart is enough, particularly when you add in things like service discovery.
I'm working on a second part to this—a guide that focuses on finding and interpreting all the charts this deployment creates (especially service discovery, which is awesome!), but I need a bit more time to put all the pieces together.
area/docs
area/packaging
> Add documentation for installing Netdata on k8s clusters

- CMakeLists.txt
- Makefile.am
- collectors/all.h
- collectors/proc.plugin/README.md
- collectors/proc.plugin/plugin_proc.c
- collectors/proc.plugin/plugin_proc.h
- collectors/proc.plugin/sys_class_infiniband.c
Implement infiniband monitoring. Fixes #2620 
Infiniband is a fabric heavily used in HPC and supercomputers. It's designed for short range (local to  datacenter), provides RDMA, low latency communication and is handled directly by MPI libraries.
It often is coupled with "IPoIB" (IP over InfiniBand) which adds the IP connectivity over Infiniband messaging and is also seen as a simple network card. However, the MPI libraries doesn't use it, and talk directly to IB cards. 
From the drivers, there's no single file that provides details and summary over all IB interfaces, so we have to parse `/sys/class/infiniband/<verb>/ports/<portid>/counters/` path to get the counters provided by driver.
Each statistics are per-port.
This prevents to use the `procfile` helpers. As there is a lot of single …
> Add infiniband monitoring to collector proc.plugin

- streaming/README.md
Changed `ndoes` to `nodes`.
Documentation
None
Just fixed a typo found during reading.
> Fixed typo in the streaming readme

- collectors/python.d.plugin/ipfs/ipfs.chart.py
python.d plugin for IPFS
https://docs.ipfs.io/reference/http/api/#api-v0-stats-bw
Tested in the default installation under arch-linux
> ipfs-plugin: change HTTP method to make it compatible with ipfs 0.5.0+

- web/api/netdata-swagger.json
- web/api/netdata-swagger.yaml
Fixes #9416
Fixes #8512
<details><summary>Sample of actual object generated by Netdata:</summary>
```
{
"hostname": "timowss",
"alarms": {
"system.active_processes.active_processes_limit": {
"id": 1593082694,
"value":1638,
"status": "CLEAR"
},
"netdata.dbengine_global_errors.10min_dbengine_global_fs_errors": {
"id": 1593082695,
"value":0,
"status": "CLEAR"
},
"netdata.dbengine_global_errors.10min_dbengine_global_io_errors": {
"id": 1593082696,
"value":0,
"status": "CLEAR"
}
}
}
```
</details>
OpenAPI Docu
Open in the swagger editor:
https://editor.swagger.io/?url=https://raw.githubusercontent.com/netdata/netdata/d1fd2949d7dc121eec3d4232203ef2fb53f0ac51/web/api/netdata-swagger.json
> Fixes error in Swagger Documentation

- exporting/tests/netdata_doubles.c
- exporting/tests/test_exporting_engine.c
After #9324 has been merged the exporting engine unit tests are failing.
Check if the exporting engine unit tests pass.
> Fix the exporting engine unit tests

- exporting/clean_connectors.c
- exporting/exporting_engine.c
- exporting/exporting_engine.h
- exporting/graphite/graphite.c
- exporting/json/json.c
- exporting/opentsdb/opentsdb.c
- exporting/prometheus/remote_write/remote_write.c
- exporting/read_config.c
- exporting/tests/exporting_doubles.c
- exporting/tests/exporting_fixtures.c
- exporting/tests/test_exporting_engine.c
The prefix option can be set in the global section only. It should be configurable for any separate instance as well.
Fixes #9405
Test different exporting connectors with the prefix option set in the global and instance sections.
> Read the prefix option from instance config sections

- .github/CODEOWNERS
When an user created a PR for exporting engine, neither I nor @vlvkobal was assign as reviewer and @ilyam8 called our attention for something important, we were missing directory [owners](https://github.com/netdata/netdata/pull/9458#issuecomment-652575815). This PR fixes this missing configuration.
github
> Bring code owner for missing directory

- docs/guides/monitor/kubernetes-k8s-netdata.md
- packaging/installer/methods/kubernetes.md
Same content as #9429, but without the mangled Git history.
@ncmans & @knatsakis: I made one more commit after you both approved, to link from the install doc to the guide, and then proceeded to accidentally add a bunch of unrelated commits and couldn't figure out how to clean up the history.
> Title is fairly self-explanatory. My idea is that k8s users first use the install instructions I'm hoping to add with #9364, then hop over to this guide to explore the various charts that they can now access once they've installed the Helm chart. I'm hoping it's helpful to explain what each of these sections does and what the capabilities are for each, as the UX around k8s isn't very refined right now.
> This guide depends on and links to the file added in #9364, hence the broken link-check CI …
> Add guide for monitoring a k8s cluster with Netdata

- health/notifications/kavenegar/README.md
Fixes netdata/netdata-learn-docusaurus#215
This is a direct link to Kavenegar's user admin pages, and it's showing up as a broken link on the documentation site. Let's just put it into a code block, since I don't like the idea of deep linking into something that's gated behind a sign-in.
area/docs
area/notifications
> Fix broken link in Kavenegar notification doc

- libnetdata/json/json.c
If JSON-C is used function:
```
static inline void json_jsonc_set_string(JSON_ENTRY *e,char *key,const char *value) {
size_t length = strlen(key);
e->type = JSON_STRING;
memcpy(e->name,key,length);
e->name[length] = 0x00;
e->data.string = (char *) value;
}
```
will use `memcpy` without checking length is less than `256`. Reason `JSON_NAME_LEN` is defined as `256`:
```
typedef struct json_entry {
JSON_ENTRY_TYPE type;
char name[JSON_NAME_LEN + 1];
char fullname[JSON_FULLNAME_LEN + 1];
union {
char *string;			// type == JSON_STRING
long double number;		// type == JSON_NUMBER
int boolean;			// type == JSON_BOOLEAN
size_t items;			// type == JSON_ARRAY
} data;
size_t pos;					// the position of this item in its parent
char *original_string;
void *callback_data;
int (*callback_function)(struct …
```
> fixes vulnerability in JSON parsing

- database/rrdset.c
The condition check on whether a chart name change should take place was was incorrect which can
cause unpredictable results all over the code.
database
The original code for that part was:
```
if(unlikely(name))
rrdset_set_name(st, name);
else
rrdset_set_name(st, id);
```
There is already a check in `rrdset_set_name` if  `st->name` and the provided name are the same. The faulty code would only call the function if st->name and new_name  were identical which would result in a no-op.
> Fixed the check condition for chart name change

- aclk/agent_cloud_link.c
- libnetdata/json/json.c
If you add log in master branch file `agent_cloud_link.c` function `int aclk_handle_cloud_request(char *payload)` after line `1974` like following:
```
int rc = json_parse(payload, &cloud_to_agent, cloud_to_agent_parse);
error("!!!!!!!!!!!!!!!!!!! VERSION %d", cloud_to_agent.version);
```
Then visit the agent on the cloud so that Agent is Queried. You will see the version is always 0!!
Reason is in function `int cloud_to_agent_parse(JSON_ENTRY *e)` the branch `case JSON_NUMBER:` is never taken. This is due to this not being implemented with JSON-C.
This PR fixes that.
We should think about hotfix release together with buffer overflow fix from yesterday (#9491 10e6b747dae6fa42ccfeeb7b4511e8fec31c61b2) as this is important for ACLK upgrades so that the old agent will detect and reject …
> fix ACLK protocol version always parsed as 0

- database/rrdset.c
Disables the recently added ability to change a chart's family on the fly. 
The code removed may deallocate structures already in use in other parts of the agent
database
> Fixed an issue with random crashes when updating a chart's metadata on the fly

- collectors/python.d.plugin/python_modules/bases/collection.py
Fixes: #9486
All jobs (threads) use `safe_print` to send charts (wrtie to stdout), this PR adds a lock to this function.
`python.d/`
> python.d: thread safe safe_print (stdout write)

- collectors/charts.d.plugin/loopsleepms.sh.inc
Fixes: #9493
Bug and fix descriptions are in https://github.com/netdata/netdata/issues/9493#issuecomment-656117588
```cmd
By default, date  pads  numeric  fields  with  zeroes.   The  following
optional flags may follow '%':
-      (hyphen) do not pad the field
```
We need to remove leading zeros from the `%-N` or treat it as base 10 number because of leading zeros.
```cmd
[ilyam@ilyam-pc ~]$ date +'%-N'
603606142
[ilyam@ilyam-pc ~]$ date +'%-N'
046524868
[ilyam@ilyam-pc ~]$ date +'%-N'
419173701
```
> Constants with a leading 0 are interpreted as octal numbers. A leading ‘0x’ or ‘0X’ denotes hexadecimal. Otherwise, numbers take the form [base#]n, where the optional base is a decimal number between 2 and 64 representing the arithmetic base, and n is a number in that base. If base# is …
> charts.d: loopsleepms: fix now_ms

- collectors/python.d.plugin/python_modules/bases/FrameworkServices/MySQLService.py
Fixes #7518
MySQLService.py
Have original users who raised the issue verify it
As mentioned in one of the issue comment, the requisite code block responsible for the issue has been removed so that no one faces this issue again
> mysql: respect `my.cnf` parameter using PyMySQL library

- contrib/debian/rules
- netdata.spec.in
- packaging/bundle-dashboard.sh
- packaging/bundle-ebpf.sh
This adds the required logic to properly bundle the eBPF collector code in our binary DEB and RPM packages.
area/packaging
Package builds locally verified using Docker
Packages verified by installing on clean VM instances and then confirming that the required files are where they're supposed to be.
This is intentionally based on master and not develop as it's assumed it will not be merged prior to the patch release that's occurring tomorrow.
Fixes: #9423
> Properly include eBPF collector in binary packages.

- database/rrdset.c
Fixes #9534
health
database
- stop netdata
- delete dbengine data
- start netdata
- check all alarms
- restart netdata
- check all alarms
> Fix transition from archived to active charts not generating alarms.

- .github/workflows/build-and-install.yml
- .travis.yml
It went EOL on 2020-05-26.
area/ci
n/a
> Removed Fedora 30 from CI.

- .github/workflows/tests.yml
- CMakeLists.txt
Fixes cmake build if ACLK is disabled. It was causing link error `undefined reference to `aclk_get_proxy'`.
This was causing `cmocka` test `build` step to always fail in CI (as ACLK is disabled there for some reason).
Does not fix other preexistent/possible problems with `cmocka`.
Problem was if you compile `claim` you need to also compile `aclk_common`. This was not reflected in Cmake makefiles (only in autotools) and shows only when building without ACLK.
cmake buildsystem
rename `*.a` files in `externaldeps` folder (keep headers in). Make sure `config.h` has no `#define ENABLE_ACLK` (as this file is done by autotools and if autotools/cmake don't agree on ACLK it will fail 100%).
It should be possible to compile using CMake without ACLK now
> Fixes cmake build failing if ACLK is disabled

- Makefile.am
It got missed when initially adding eBPF support to our packaging process.
area/packaging
Verified locally that the file is properly included.
This fixes the currently broken production RPM builds, which we still have not fixed to not use `make dist` and just use the regular source tree.
@prologic This needs to go in before any patch release is made, as we otherwise will not have working RPM builds.
> Add eBPF bundling script to `make dist`.

- database/engine/journalfile.c
- database/engine/metadata_log/compaction.c
- database/engine/metadata_log/logfile.c
- database/engine/pagecache.c
- database/engine/rrdengineapi.c
- database/engine/rrdenginelib.c
Initialize variables in the database engine to avoid compilation warnings we have with the `-Og` flag.
database engine
Build Netdata with the `-Og` flag.
> Fix compilation warnings

- CMakeLists.txt
We have two unit tests that are failing because our code don't conform to the standards we are checking. As far as fixing the code was deprioritized, we disable the tests until the fixes are in.
web api
Build Netdata using CMake, run `make test`. All tests should pass.
> Disable failing unit tests in CMake build

- packaging/bundle-ebpf.sh
This makes it compatible both with busybox and older GNU userspaces.
area/packaging
Verified locally by building in a CentOS 7 environment.
@prologic This will fix the currently broken CentOS 7 RPM builds, and should go in before the upcoming patch release.
> Fix SHA256 handling in eBPF bundling code.

- aclk/aclk_query.c
- aclk/aclk_stats.c
We truncate there on purpose (`thread_set_name_np` would do that later anyway). This is just to remove the following warning _(we don't really care about the retval)_:
```
CC       aclk/aclk_query.o
aclk/aclk_query.c: In function ‘aclk_query_threads_start’:
aclk/aclk_query.c:491:49: warning: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 5 [-Wformat-truncation=]
491 |         snprintf(thread_name, TASK_LEN_MAX, "%s_%d", ACLK_THREAD_NAME, i);
|                                                 ^~
aclk/aclk_query.c:491:45: note: directive argument in the range [0, 2147483647]
491 |         snprintf(thread_name, TASK_LEN_MAX, "%s_%d", ACLK_THREAD_NAME, i);
```
when flags `-Og -ggdb -pg -DACLK_SSL_ALLOW_SELF_SIGNED -D_FORTIFY_SOURCE=2 …
> Suppress warning -Wformat-truncation in ACLK

- health/health.d/megacli.conf
Degraded RAID array was not triggering an alarm in megacli.conf
Amended all instances of alarm to template as per https://github.com/netdata/netdata/issues/9551
This has started triggering alarms as expected.
Fixes: #9551
> health/megacli: change all instances of alarm to template

- collectors/plugins.d/pluginsd_parser.c
- database/engine/global_uuid_map/global_uuid_map.c
- database/engine/metadata_log/compaction.c
- database/engine/metadata_log/logfile.c
- database/engine/metadata_log/metadatalogapi.c
- database/engine/metadata_log/metadatalogapi.h
- database/engine/metadata_log/metalogpluginsd.c
- database/engine/metadata_log/metalogpluginsd.h
- database/engine/rrdengineapi.c
- database/rrd.h
- database/rrdhost.c
- database/rrdset.c
- parser/parser.h
Fixes #9453 
Register the HOST command in the metadata log parser and the corresponding action. Improve the detection of the
HOST GUID type (correctly registered in the global GUID map now) and make sure that during compaction the HOST
is written to the metadata log files before any CHART / DIMENSION
database
- Start agent and wait for compaction to run
- Example the metadata log files using
`cat /home/stelios/netdata-inst/netdata//var/cache/netdata/dbengine/metadatalog-* | strings -n | head -n 30`
You should always observe the HOST command at the top e.g. (sample)
```
HOST "d6b37186-74db-11ea-88b2-0bf5095b1f9e" "futura" "futura" 1 "linux" "Europe/Athens" ""
LABEL "_os_name" = 0 Ubuntu
LABEL "_os_version" = 0 20.04 LTS (Focal Fossa)
LABEL "_kernel_version" = 0 5.4.0-40-generic
LABEL …
```
> Implemented the HOST command in metadata log replay

- collectors/apps.plugin/apps_groups.conf
Pi-hole https://github.com/pi-hole/pi-hole is an open source DNS server of sorts. I recently had an issue I needed to debug and sadly netdata showed the useful application data in the "other" bucket for pi-hole. This PR includes pi-hole related processes in the appropriate app group.
The primary daemon process is pihole-FTL but pihole as a stand-alone command can also be expensive to run, so I'm capturing both via `pihole*`.
Thanks in advance.
apps.plugin
Installed pi-hole, updated apps_groups.conf with the proposed change, ensured that data for pihole was captured correctly.
> Adding pihole to the dns app group

- system/netdata.service.in
Runing netdata service in simple sandbox mode on systmed based systems.
Installer, service file
Tested on a NixOS OS
Based on this PR - https://github.com/NixOS/nixpkgs/pull/87867
> enable simple sandboxing on systemd service

- packaging/installer/kickstart-static64.sh
- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart-64.md
- packaging/installer/methods/kickstart.md
This adds more robust checks to our Kickstart install scripts to prevent users from accidentally installing Netdata over top of an existing install (which can lead to all kinds of problematic situations).
The logic for these checks works as follows:
* See if `netdata` is located somewhere in `$PATH` (using `command -v`), and if present assume there's an existing install.
* Otherwise, check if `/opt/netdata/bin/netdata` exists, if so assume there's an existing install, otherwise continue under the assumption there isn't.
* If there is an existing install, check if it's one done through our install scripts, if not stop the installation process.
* If it is one of our installs, look for and attempt to use the updater script to update the existing install (exiting with an error message if that …
> Add better checks for existing installs to the kickstart scripts.

- Makefile.am
This makes 3e84239ff work properly when using the kickstart installer.
area/packaging
Verified that the required file is included in the dist archive and tested that the kickstart script works with the generated archive.
Partial fix for #9570.
> Added libbpf patch to make dist.

- system/netdata.service.in
This is a mitigation for an issue caused by #9234, whereby the eBPF collector's attempts to call `setrlimit()` (in preparation for locking memory) fail on systemd-based systems.
I do not consider this a final fix (yet) because it's not clear that we actually _need_ to lock memory, and therefore we may not actually need this `setrlimit()` call. I suspect that locking memory allows for more accurate data collection, but is not actually required for the plugin to work, in which case it should be optional and not mandatory, but we should still merge this PR (so that people who want it don't have to change anything else). If, however, we truly gain no benefit from locking memory, then this change should be scrapped and we should just remove the calls to `setrlimit()` and `memlock()` instead. …
> Added CAP_SYS_RESOURCE to capability bounding set.

- REDISTRIBUTED.md
- collectors/python.d.plugin/Makefile.am
- collectors/python.d.plugin/python.d.plugin.in
- collectors/python.d.plugin/python_modules/third_party/filelock.py
Fixes: #9447
This PR adds https://github.com/benediktschmitt/py-filelock library (one file).
Technically this PR does nothing until #9347 is implemented.
`/collectors/python.d.plugin`
`NETDATA_LOCKS_DIR` unset:
`NETDATA_LOCKS_DIR` set, directory doesnt exist:
```cmd
[netdata@ilyam-pc plugins.d]$ export NETDATA_LOCKS_DIR="/opt/netdata/var/lib/netdata/locks111"
[netdata@ilyam-pc plugins.d]$ ./python.d.plugin sensors
2020-07-20 11:40:20: python.d INFO: plugin[main] : using python v3
2020-07-20 11:40:20: python.d INFO: plugin[main] : [sensors] built 1 job(s) configs
2020-07-20 11:40:20: python.d INFO: plugin[main] : sensors[sensors] : check success
CHART netdata.runtime_sensors '' 'Execution time for sensors' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' …
```
> python.d: add job file lock registry

- collectors/charts.d.plugin/charts.d.plugin.in
Fixes: #9565
We switched from alpine `3.9` to `3.12` in https://github.com/netdata/helper-images/pull/80.
It uses `Busybox 1.31.1`. There is no `-t` parameter since `Busybox 1.30.0`
> https://www.busybox.net/
>  timeout: fix arguments to match coreutils
`collectors/charts.d`
Changes look straightforward, we no longer need `-t`. Tested by @kmlucy in https://github.com/netdata/netdata/issues/9565#issuecomment-661077363.
> charts.d.plugin: never use `-t` option for `timeout`

- aclk/aclk_stats.c
Due to typo, we call `mempcpy` instead of `memcpy`. Surprisingly function `mempcpy` actually exists (the reason why the compiler doesn't complain) in GNU but not everywhere. As a result, the compilation fails on FreeNAS.
`mempcpy` and `memcpy` do the same job and differ only in return value (which is not used anyway).
Fixes #9563
Credit to @mfundul and @abrbon for bringing attention to this.
> Fixes mempcpy->memcpy

- collectors/ebpf.plugin/README.md
- collectors/ebpf.plugin/ebpf.c
- collectors/ebpf.plugin/ebpf.conf
- collectors/ebpf.plugin/ebpf.h
- collectors/ebpf.plugin/ebpf_socket.c
- collectors/ebpf.plugin/ebpf_socket.h
- daemon/main.c
Fixes #9455
Collector
1 -  Compile Netdata with the option `-DNETDATA_INTERNAL_CHECKS`
2 - Configure your `ebpf.conf` inside `/etc/netdata/`, for example, use
```
[global]
ebpf load mode = return
#ebpf load mode = entry
disable apps = no
process = yes
network viewer = yes
[network viewer]
maximum dimensions = 20
ports = !145 !139 100-1024 144  ssh * https 3128:2000 60000-70000 78945 !compressnet iafservers
hostnames = netdata.cloud netdata.io    !*example*
ips = 127.0.0.1 192.168.0.0/6 172.20.0.0-172.20.2.255 4204:14c:5b72:1234:5678:1aee:ac11:cbb5/24 1200:10c:1234:5678:1ee2:1aee:ac11:cbb5/90 192.168.0.100-192.168.0.50 192.168.0.0/24     c704:14c:5b72:888d:1ee2:1aee:ac11:cbb5  9436:14c:1234:5678:1ee2:1aee:ac11:cbb0-9436:14c:1234:5678:1ee2:1aee:ac11:cbff …
```
> Network Viewer options

- packaging/docker/README.md
- packaging/docker/run.sh
This removes our runtime support for Polyverse's Polymorphic Linux from our Docker containers. The actual support is currently broken due to upstream changes, but we have decided to just remove it instead of fixing it due to it providing limited practical benefit to our users and not being supported across all of our supported platforms.
We had previously removed build-time usage of this functionality for the same reasons to reduce the final image size for our 64-bit x86 Docker images.
Users who still want to use this can derive their own container images from our official image and inject the required repositories and package updates. Note that we will ask any users who take this approach to reproduce any bugs they find on our official Docker images.
area/packaging
Container locally …
> Removed runtime support for Polymorphic Linux from our Docker containers.

- packaging/installer/install-required-packages.sh
Ubuntu 18.04 really does have autogen, even though we claim it doesn't. Fix our dependency handling script to recognize this.
area/packaging
Verified locally that the autogen package on Ubuntu 18.04 works as we need it to.
Fixes: #8869
> Added proper handling for autogen on Ubuntu 18.04

- .github/CODEOWNERS
It's part of the packaging code, so it should be owned by the people responsible for packaging.
GitHub infra
n/a
> Added explicit CODEOWNERS rule for `system/`.

- packaging/installer/kickstart-static64.sh
- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart-64.md
- packaging/installer/methods/kickstart.md
Our updater script has a built-in random delay of up to 1 hour when run non-interactively to avoid a stampede effect for reconnections to Netdata Cloud due to auto-updates. Due to an oversight in handling of updates to existing installs in the installer scripts, this delay was also occurring when the installer scripts were run non-interactively. This fixes that so that non-interactive runs complete without a delay.
area/packaging
Verified locally that running the updates via the kickstart scripts non-interactively now has no delay (checked using `nohup`).
Fixes: #9588
> Removed delay in updater script for non-interactive runs from install scripts.

- collectors/python.d.plugin/python.d.plugin.in
- daemon/common.c
- daemon/common.h
- daemon/daemon.c
- daemon/main.c
In order to prevent python and go plugins from mutual conflicts, we are adding a directory for lock files.
Fixes #9347
daemon
Run Netdata, check if `/var/lib/netdata/lock` is created and contains lock files only for running python plugins.
> Add lock dir

- claim/claim.c
- claim/netdata-claim.sh.in
Send Netdata public unique id (machine GUID) when claiming. In case `claiming ID != machine GUID` cloud still knows the GUID.
This will be more important with MVP1 (Streaming support for Cloud)
run claiming script with `-verbose` flag. You should see that we send also line:
```
Request to server:
{
"node": {
"id": "XXXX",
"hostname": "timowss"
},
"token": "CENSORED",
"rooms" : [ "YYYY" ],
"publicKey" : "-----BEGIN PUBLIC KEY-----\nCENSORED\n-----END PUBLIC KEY-----\n",
"m_guid" : "BBBB"
}
```
`BBBB` can be the same as `XXXX` if -id parameter not given to claiming script.
> Sends netdata.public.unique.id (machine GUID) with claim

- health/health.d/net.conf
This PR add alarms for FreeBSD interface errors, inbound and outbound, based on net.drops alarms.
health.d
Used for weeks on multiple FreeBSD routers running Netdata 1.19.0.
> Add alarms for FreeBSD interface errors

- system/netdata.service.in
This marks `/run/netdata` as writable in our systemd unit files so that users who are listening on a UNIX socket in the 'standard' location can do so witout the sandboxing getting in their way.
area/packaging
Verified through a local install that this lets Netdata listen on a UNIX socket located under `/run/netdata`.
Fixes: #9606
> Added sandboxing exception for `/run/netdata`.

- collectors/plugins.d/pluginsd_parser.c
- daemon/main.c
- database/engine/README.md
- database/engine/metadata_log/compaction.c
- database/engine/metadata_log/logfile.c
- database/engine/metadata_log/metadatalog.c
- database/engine/metadata_log/metadatalog.h
- database/engine/metadata_log/metadatalogapi.c
- database/engine/metadata_log/metadatalogapi.h
- database/engine/metadata_log/metalogpluginsd.c
- database/engine/rrdengine.c
- database/engine/rrdengine.h
- database/engine/rrdengineapi.c
- database/engine/rrdengineapi.h
- database/engine/rrdenginelib.c
- database/rrd.h
- database/rrddim.c
- database/rrdhost.c
- database/rrdset.c
- streaming/README.md
- streaming/receiver.c
- streaming/rrdpush.c
- web/api/formatters/charts2json.c
- web/api/web_api_v1.c
Fixes #9454
New children streaming to a parent with storage mode `dbengine` will now have their metrics stored in the parent's database. 
Old children that already have a database created in the parent will continue to use that one to store metrics.
database
- TBA
- TBA
> Implemented multihost database

- .travis.yml
- .travis/package_management/common.py
- .travis/package_management/functions.sh
- Makefile.am
- configure.ac
- contrib/debian/rules
- netdata.spec.in
- packaging/bundle-dashboard.sh
- packaging/bundle-ebpf.sh
- packaging/bundle-libbpf.sh
This PR adds working support for the eBPF plugin to our DEB and RPM packages. It adds code to prepare our local build of libbpf as well as properly bundling the actual eBPF programs into the final packages.
It also adds basic DEB and RPM build checks to our normal Travis workflow (done on Debian 10 and Fedora 31), as well as adding code to make the package build process actually show full output in the Travis log, and updating the configure script to explicitly show all the things we're checking for the eBPF collector build.
area/packaging
area/ci
Verified both using local package builds and in Travis using the new DEB and RPM build checks.
> Added eBPF collector support to DEB and RPM packages.

- netdata.spec.in
Fixes #9620 : bad default permission in specfile lead to all files in /usr/libexec/netdata to be setuid.
netdata.spec.in
```
git clone https://github.com/netdata/netdata.git
cd netdata
./contrib/rhel/build-netdata-rpm.sh
rpm -qvlp ~/rpmbuild/RPMS/x86_64/netdata-*.rpm | grep /usr/libexec/netdata 
```
> Fixed RPM default permissions for /usr/libexec/netdata

- packaging/installer/README.md
- packaging/installer/methods/manual.md
- packaging/installer/methods/source.md
This adds a guide for package maintainers, power users, and distribution engineers explaining how to build and install Netdata without using either our kickstart scripts or the `netdata-installer.sh` script. It also serves to provide general high-level documentation of how our installer scripts work.
- area/docs
I've manually verified the steps outlined here other than the manual build of the eBPF code.
Fixes: #8734
> Add documentation to provide a comprehensive guide for package maintainers

- .github/scripts/run_install_with_dist_file.sh
- .github/workflows/checks.yml
This updates our `make dist` check to only pass if building with Netdata Cloud functionality succeeds.
area/ci
CI check passes on this PR.
Fixes: #8284
> Require cloud build to succeed in make dist checks.

- collectors/charts.d.plugin/loopsleepms.sh.inc
Fixes: #9635
macOS `date` doesnt support `%N`
```cmd
0 ~ $ /bin/date +'%N'
N
0 ~ $ gdate +'%N'
672878000
```
It stopped to work on macOS after https://github.com/netdata/netdata/pull/9510
Before [the PR](https://github.com/netdata/netdata/pull/9510) it was `(( ... N / 1000000))` which is 0 (var `N` was not set, bash arithmetic expansion treats it as zero), after it - `10#N`.
```cmd
1 ~ $ ((10#N))
-bash: ((: 10#N: value too great for base (error token is "10#N")
```
`collectors/charts.d`
- run `charts.d.plugin` in debug mode, ensure it works
- change `= "N"` condition to `!= "N"`, run `charts.d.plugin` in debug mode, ensure it works
- i didnt install netdata on macOS but i am sure the problem is fixed because it was working before #9510
> charts.d: fix `current_time_ms_from_date` on macOS

- netdata-installer.sh
I noticed that installer downloads `v0.19.2` binary despite i have `v0.20.0` in the `/plugins.d`. This PR fixes it.
`installer`
> installer: fix `govercomp`

- collectors/python.d.plugin/python_modules/bases/collection.py
Fixes: #9640
`/collectors/python.d`
The correct way is to use `os.path.join` and not `'/'.join()` 😄
> python.d: fix `find_binary`

- collectors/ebpf.plugin/ebpf_socket.c
Fixes #9647 
The plugin code has a wrong length that was reported only when compiled on `gcc 10.1`. I also used coverity to try catching the error, but it was not shown.
ebpf.plugin
1 - Compile this PR with a `gcc 10.1` or newer redirecting stderr to a file
2 - Verify that the error reported is not more present.
> Fix warning when compiled with gcc-10.1

- .github/scripts/build-artifacts.sh
- .travis/create_artifacts.sh
- netdata-installer.sh
- packaging/makeself/install-alpine-packages.sh
- packaging/makeself/jobs/20-openssl.install.sh
- packaging/makeself/jobs/50-bash-4.4.18.install.sh
- packaging/makeself/jobs/50-curl-7.60.0.install.sh
- packaging/makeself/jobs/50-fping-4.2.install.sh
- packaging/makeself/jobs/70-netdata-git.install.sh
ssia
1. Build a new static binary:
```#!sh
$ .github/scripts/build-artifacts.sh
```
2. Copy it on a box somewhere and run it:
```#!sh
$ scp ./artifacts/*.run user@yourboxen:
$ ssh user@yourboxen
$ ./netdata-*.run --accept
```
3. Claim it in [Netdata Cloud](https://app.netdata.cloud)
> I did this for Debian 10 and CentOS 7
Few things to note here:
- Missing `--require-cloud` and therefore we weren't enabling the build
of the Netdata Cloud dependencies.
- Typo in some path names.
- Missing CMake flags to correctly build against the custom
`/openssl-static` (_without it was incorrectly trying to build against
and build test programs against the system openssl -- Alpine 3.7_).
- In both Travis and the GHA Workflow that does CI for static builds we were not cleaning the local …
> Fix Static Netdata to correctly build with Netdata Cloud support.

- contrib/debian/rules
- netdata-installer.sh
- packaging/installer/netdata-uninstaller.sh
We removed user-side shared libraries from kernel-collector repository https://github.com/netdata/kernel-collector/pull/172. We have to delete them from install/uninstall scripts as well.
eBPF plugin, packaging
Run `netdata-installer.sh` and `netdata-uninstaller-sh`. Check if there are no errors related to `libbpf_kernel.so` or `libnetdata_ebpf.so`.
> Remove obsoleted libraries from install/uninstall scripts

- .travis.yml
- .travis/package_management/configure_deb_lxc_environment.py
- contrib/debian/control.focal
- Fixes #8906
```#!sh
root@ubuntu2004:~# apt-get update
Get:1 http://10.0.0.109:8000 focal InRelease [2,774 B]
Get:2 http://10.0.0.109:8000 focal/main amd64 Packages [2,120 B]
Hit:3 http://au.archive.ubuntu.com/ubuntu focal InRelease
Hit:4 http://au.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://au.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:6 http://au.archive.ubuntu.com/ubuntu focal-security InRelease
Fetched 4,894 B in 1s (3,315 B/s)
Reading package lists... Done
root@ubuntu2004:~# apt-get install netdata
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be upgraded:
netdata
1 upgraded, 0 newly installed, 0 to remove and 63 not upgraded.
1 not fully installed or removed.
Need …
```
> Add support for DEB packages for Ubuntu 20.04 (focal)

- daemon/global_statistics.c
Fix multi-host DB statistics.
dbengine
Connect multiple hosts to multihost DB. Observe dbengine statistics not being magnified contrary to what it was before.
> Stop multi-host DB statistics from being counted multiple times.

- health/notifications/alarm-notify.sh.in
As per #9487, the redirection links only work now with private registries. Temporarily replacing the goto_url with a simple link to the cloud, until we re-implement the functionality.
> Replace alarm redirection link for cloud, to stop showing 404

- netdata-installer.sh
Added an LDFLAG export to macOS to properly find openssl when compiling with netdata-cloud.
Fixes compile issue while installing netdata with cloud support in macOS
netdata-installer.sh
compile on macOS system with force cloud and get a successful compilation.
> Update netdata-installer.sh to fix #8862

- SECURITY.md
Fixes #9691 
Update instructions to report vulnerabilities, all that is needed is an email to security@netdata.cloud.
docs
> Correct vulnerability reporting instructions

- daemon/common.c
- daemon/main.c
Fixes #6865 (?)
For the default environment value of "HOME", use the user's "HOME", as defined in the environment.
daemon
Test in various environments, including AWS SNS.
I don't know how to properly test this, I'll leave it up to @Ferroin
> Set the default value of the home directory to the environment's HOME

- database/rrddim.c
- database/rrdset.c
Fixes #9706
When the health subsystem is configured, archived charts are skipped to avoid unnecessary configuration that slows
down the metadata log replay. 
Health related configuration for those charts is performed when a chart switches from archived to active by having a collector gather metrics for any dimension of that chart.
The following init code (found in the health configuration initialization) did not run in that case
```
rrddim_foreach_read(rd, st) {
rrdcalc_link_to_rrddim(rd, st, host);
}
```
database
health
- Before the PR
- Configure an alarm as described in #9706 
- Restart the agent 
- The alarm is not raised
- Perform health reload
- Alarm is now raised
- Note that during health reload the init process is done properly because the chart is not archived anymore
- Apply …
> Fixed issue with missing alarms

- database/engine/global_uuid_map/global_uuid_map.c
Fixes #9724
The object memory is now released if the object already exists in the map.
The memory leak only affects the `GUID_TYPE_CHAR` objects. 
database
- Run valgrind to track the  `GUID_TYPE_CHAR` object creation during the creation of `GUID_TYPE_DIMENSION` or `GUID_TYPE_CHART` object in `find_or_generate_guid`
> Fixed global GUID map memory leak

- collectors/cgroups.plugin/cgroup-name.sh.in
- collectors/cgroups.plugin/sys_fs_cgroup.c
There are [changes in LXC container layout](https://linuxcontainers.org/lxc/news/#major-changes) since version 4.0. The PR fixes the default configuration for ignored LXC containers. In addition, the renaming script removes `lxc.payload.` from container names.
Fixes #9697
cgroups plugin
Run Netdata on a machine with LXC 4.x containers. Check if they are displayed correctly and there are no unnecessary containers. Check if there aren't a lot of disabled containers in the `[plugin:cgroups]` section in `http://localhost:19999/netdata.conf`.
> Fix for ignored LXC containers

- .travis.yml
Our current infrastructure depends on availability of appropriate architecture LXC containers for the distros we're building for, and
there are no 32-bit x86 LXC images for Ubuntu 20.04, so we cannot build these packages.
area/ci
area/packaging
Verified the new commit message regex locally.
> Removed Ubuntu 20.04 32-bit x86 package builds.

- system/netdata.service.in
Netdata service doesn't have the ability to change namespaces. As a consequence, cgroups plugin can't read information about network interfaces in LXD 4.x containers. We need to add `CAP_SYS_CHROOT` to the `netdata.service` unit file to fix that.
Fixes #8359
Fixes #9368
daemon
Run Netdata on a machine with LXD 4.x.
Check if there are no errors `Cannot switch to mount namespace` in `error.log`.
Check if virtual network interfaces are displayed under the corresponding container section and not in "Network Interfaces".
> Add CAP_SYS_CHROOT for netdata service

- packaging/makeself/jobs/50-curl-7.60.0.install.sh
The default behavior of cURL when validating TLS certificates is to use a CA certificate bundle located at a path either specified on the command line or at a default location detected at build time, and then fail if it cannot find this file.
This causes failures when the system on which cURL was built had different paths for the CA certificate bundle than those used on the system it's being run on.
This adds configure options to the build of cURL during our static build which will cause it to use the same central dispatch that we are configuring OpenSSL to use to find the CA certificate bundle and to make it fall back to asking OpenSSL to do the validation if it cannot find the CA bundle.
area/packaging
Build verified locally.
Actual runtime behavior verified using a local install of the …
> Added proper certificate handling cURL in our static build.

- health/notifications/health_alarm_notify.conf
Explain that with the recipient "|critical" option, a user will receive warnings only if an alarm goes to critical first.
Covers the comment in https://github.com/netdata/netdata/pull/9698#discussion_r468592201
@thiagoftsm I lost my laptop and don't have everything set up on this one, so this is a different PR.
> Clarify which notifications are received when the "|critical" limit is set

- health/notifications/alarm-notify.sh.in
Fixes #8739 
When Netdata sends an alarm notification that matches the configured filters, it's supposed to send follow-up notifications, until the alarm is cleared. This feature was erroneously broken by #7769, due to an incorrect handling of #7756.
Returning the previous functionality.
Run the notifications test, to verify that the initial WARNING alarm is not sent, but the CRITICAL and CLEAR alarms are sent, when a recipient has the `|CRITICAL` filter.
More detailed tests:
- Run `bash -x /usr/libexec/netdata/plugins.d/alarm-notify.sh test`, with debug enabled (https://learn.netdata.cloud/docs/agent/health/notifications#testing-notifications)
- Look in the output for the alarm-notify.sh calls. There are three of them. 
- Run them one by one and after each execution …
> Send follow up alarms when the initial status matches the notification

- database/engine/README.md
- database/engine/metadata_log/metadatalog.c
- database/engine/metadata_log/metadatalog.h
- database/engine/metadata_log/metadatalogapi.c
- database/engine/metadata_log/metadatalogapi.h
- database/engine/pagecache.c
- database/engine/rrdengine.c
- database/engine/rrdengineapi.c
Fixes  #8384
Fixes  #9730
database
1. Make sure that `2 * 4096 * number-of-metrics-being-collected` bytes is more than the disk space quota. This should trigger the `Failed to flush dirty buffers quickly enough in dbengine instance` error message in the old code.
2. Make sure that a collector that has collected at least 34 minutes worth of metric data points stops collecting a specific metric (2 4K pages of metrics with 1 second collection interval). After a full database rotation you should start seeing the aforementioned error message.
> Fix flushing errors

- collectors/python.d.plugin/mysql/README.md
Both `root` and `netdata` users will try to connect using the socket connection and only `root` user was specified in the doc.
Just added `netdata` and some quick comment
Enhance MySQL plugin documentation
Mysql
just some documentation
I added that by default, both users `root` / `netdata` will try to connect using the socket connection by default.
> doc: netdata user is also a default

- collectors/python.d.plugin/varnish/varnish.chart.py
Add the possibility to have multiple storage backends and rename "disk" to "storage"
Tested on debian 10 with varnish 6.4
Fixes: #9657
> python.d/varnish: multiple storage backends fix

- collectors/python.d.plugin/ipfs/README.md
- collectors/python.d.plugin/ipfs/ipfs.chart.py
- collectors/python.d.plugin/ipfs/ipfs.conf
Fixes: #9505
Using python ipfs collector results in [high CPU load of IPFS](https://user-images.githubusercontent.com/614929/86942195-27a12d80-c145-11ea-8ffd-9084dfcacfd7.png).
There is an open bug in the IPFS repo
> https://github.com/ipfs/go-ipfs/issues/7528
This PR disables call to the `/api/v0/stats/repo` endpoint by default. Can be enabled in the module config file.
Same as we did in https://github.com/netdata/netdata/pull/4224
`python.d/ipfs`
> python.d/ipfs: disable call to the `/api/v0/stats/repo` endpoint by default

- exporting/process_data.c
Data was sent to an external storage service at the beginning of an update interval which caused Graphite to not update metrics at some points. We will send data at the end of the configured update interval as it was in the backends subsystem.
Fixes #9512
Configure an exporting connector instance
```
[graphite:netdata]
enabled = yes
destination = localhost:2003
data source = as collected
prefix = netdata
update every = 10
buffer on failures = 10
timeout ms = 20000
send charts matching = system.uptime* !*
send hosts matching = localhost *
send names instead of ids = yes
```
Run a Graphite container
```
docker run -d\
--name graphite\
--restart=always\
-p 80:80\
-p 2003-2004:2003-2004\
-p 2023-2024:2023-2024\
-p 8125:8125/udp\
-p 8126:8126\
graphiteapp/graphite-statsd
``` …
> Fix exporting update point

- exporting/aws_kinesis/aws_kinesis.c
- exporting/exporting_engine.c
- exporting/exporting_engine.h
- exporting/mongodb/mongodb.c
- exporting/process_data.c
- exporting/pubsub/pubsub.c
- exporting/send_data.c
@mfundul thanks for pointing this out
http://docs.libuv.org/en/v1.x/threading.html#conditions
> Callers should be prepared to deal with spurious wakeups on uv_cond_wait() and uv_cond_timedwait().
https://linux.die.net/man/3/pthread_cond_wait
> When using condition variables there is always a Boolean predicate involving shared variables associated with each condition wait that is true if the thread should proceed. Spurious wakeups from the pthread_cond_timedwait() or pthread_cond_wait() functions may occur. Since the return from pthread_cond_timedwait() or pthread_cond_wait() does not imply anything about the value of this predicate, the predicate should be re-evaluated upon such return.
> Add check for spurious wakeups

- collectors/python.d.plugin/redis/redis.chart.py
Fixes: #9764
Collect [`maxmemory`](https://redis.io/commands/info#notes) metric
> maxmemory: The value of the maxmemory configuration directive
`/collectors/python.d/redis`
Tested by @TheOldMan2000
> https://github.com/netdata/netdata/issues/9764#issuecomment-674788164
> python.d/redis: collect `maxmemory`

- exporting/tests/exporting_fixtures.c
After applying #9751 unit tests for the exporting engine were broken.
Run `sudo make check`. Unit tests for the exporting engine should pass.
> Fix unit tests for exporting engine

- backends/backends.c
- exporting/prometheus/remote_write/remote_write.c
- exporting/tests/test_exporting_engine.c
Fixes #7676
exporting engine, backends
1. Configure an exporting connector
```
[prometheus_remote_write:test_instance]
enabled = yes
destination = localhost:1234
remote write URL path = /receive
data source = as collected
update every = 2
send charts matching = system.processes
```
Check the HTTP Host filed using `nc -l -p 1234`, it should be set to `localhost:1234`.
2. Configure the backends subsytem
```
[backend]
enabled = yes
type = prometheus_remote_write
data source = as collected
destination = localhost:1234
send charts matching = system.processes
```
Check the HTTP Host filed using `nc -l -p 1234`, it should be set to `localhost:1234`.
> Fix HTTP header for the remote write exporting connector

- packaging/docker/Dockerfile
Fixes the `netdata/netdata` Docker image size by ensuring that we
install Python dependencies in pre-built (_wheels_) form and only
install/build things in the `netdata/buidler` image and only include
runtim dependencies in the `netdata/base` runtime image.
Depends on:
- netdata/helper-images#84
Fixes:
- #9664 
- area/packacing
```#!sh
$ dki -t --rm --entrypoint /bin/sh netdata/netdata:amd64
/ # python3
Python 3.8.5 (default, Jul 20 2020, 23:11:29)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymongo
>>> import psycopg2
>>>
```
```#!sh
$ docker images netdata/netdata:amd64
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
netdata/netdata     amd64               37fe4941b674        7 minutes ago …
```
> Fix netdata/netdata Docker image size

- collectors/cgroups.plugin/README.md
- collectors/cgroups.plugin/cgroup-name.sh.in
Fixes #7391 (somewhat). 
This is not as seamless as I'd like it to be, but Podman really doesn't want other people to look at your containers (and for good reason), so this is probably as much as we can do without rewriting the entire mechanism. I've also added a section to the documentation describing the issue and possible solutions for now.
On the implementation side, Podman's API both on the command line tool and on the Unix socket is intentionally identical to Docker's, so most of the Docker logic can be reused.
cgroups.plugin
Tested on a server running Podman 2.0.1 and Netdata 1.23.1 with this patch applied, both with `docker-socket-proxy` and changed socket permissions.
> cgroups.plugin: add and document support for reading container names from Podman

- streaming/rrdpush.h
Fixes #9768 
The read buffer in the streaming receiver was too small to allow the longest lines in the protocol.
streaming
https://github.com/vince-lessbits/netdata-test
> Fix long stats.d chart names (suggested by @vince-lessbits)

- daemon/main.c
- web/server/static/static-threaded.c
Fixes #8962 
During the tests I made, I observed that Unix socket is presented with UNKNOWN client_ip, this value was not present in the default list of simple patterns associated to the variable `web_allow_netdataconf_from`.
I have to call attention for an important thing in this PR, I could never recreate the problem using nginx and doing normal compilation, this is one of the various problems that are appearing only on kickstart-static64.
I am also using this PR to remove an old comment that is not doing any contribution for the code.
Web
kickstart-static64
First test, check if nothing was breaking:
1 - Compile this branch
2 - Start Netdata
3 - Access  http://localhost:19999/netdata.conf
Stop Netdata and do the next steps to confirm the problem was really fixed.
1 - Install docker on …
> Fix UNIX socket access with kickstart-static64

- packaging/installer/kickstart-static64.sh
- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart-64.md
- packaging/installer/methods/kickstart.md
This fixes three bugs in the installer relating to the handling of duplicate installs:
* The existing checks for duplicate installs were being run before we parsed options, but trying to use variables assigned by the option parsing code. As a result, some of the cases they were supposed to handle did not work correctly. This PR moves the checks to the correct place so these cases work properly.
* In the specific case of trying to reinstall over top of an existing installation that had a functioning 'netdata-updater' script, there was no easy way to make the script explicitly reinstall instead of just attempting to update the existing install. This adds a new option (`--reinstall`) that explicitly requests a reinstall if the script would normally update an existing install.
* For the …
> Fixed numerous bugs in duplicate install handling.

- libnetdata/socket/security.h
- web/server/web_client.c
- web/server/web_client.h
- web/server/web_client_cache.c
Fixes #9065 
This PR fixes the wrong Location returned by Netdata. Previously Netdata was considering only direct access to dashboard, but when a proxy is put between the browser and Netdata, it is necessary to parse more headers to build the correct URL that proxy has condition to redirect.
Web
The user reported the error while he was using GCP HTTPS, but this test plan is based on Nginx proxy.
1 - Configure your Netdata `parent` to support a port with SSL and another port without it:
```
[web]
ssl key = /etc/netdata/ssl/key.pem
ssl certificate = /etc/netdata/ssl/cert.pem
bind to = *=dashboard|registry|streaming|management|netdata.conf|badges *:20000=dashboard|registry|streaming|netdata.conf|badges|management^SSL=optional
```
please, do not forget to create the SSL certificate inside …
> Fix proxy redirect

- collectors/ebpf.plugin/ebpf_socket.c
The merge of 9591 probably fixed some problems that users were having, but it also brings unnecessary debug messages, this PR fixed this problem.
ebpf.plugin
1 - Compile this branch
2 - Enable network viewer.
3 - Take a look on logs, the messages should not be there.
> Remove debug messages from ebpf.

- backends/prometheus/backend_prometheus.c
- exporting/prometheus/prometheus.c
Prometheus [drops global variables from responses](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness) by default
> If no sample is found (by default) 5 minutes before a sampling timestamp, no value is returned for that time series at this point in time. 
We will provide current time as a timestamp for the global variables to be sure they are available in Prometheus' responses.
Fixes #6470
Web API
Query Netdata with the following URL
```
http://localhost:19999/api/v1/allmetrics?format=prometheus&source=raw&variables=yes&help=yes
```
Timestamps for global host and chart variables should represent the current time.
> Change timestamps for global variables in Prometheus output

- .travis.yml
- .travis/package_management/create_lxc_for_build.sh
Testing that the package builds work prior to actually building the packages is a waste of time and is causing issues for certain package builds. Just skip our packaging CI checks on those builds instead.
area/ci
Verified using Travis on my fork with dummy packaging commits.
Sample test build that demonstrates this working: https://travis-ci.org/github/Ferroin/netdata/builds/719593095
> Don't run packaging checks on Travis builds that build packages.

- daemon/main.c
- database/engine/global_uuid_map/global_uuid_map.c
- database/engine/global_uuid_map/global_uuid_map.h
- database/engine/rrdengineapi.c
- database/rrddim.c
- database/rrdhost.c
- database/rrdset.c
Fixes #9728
Cleanup the memory allocated for the global GUID map and release the associated Judy arrays.
database
- Run with `valgrind` or address sanitizer before and after the cleanup code
As this uses memory to keep track of the objects we need to release, we may want to enable this with a compile flag so that the code is activated only during debugging.
> Added code to release memory used by the global GUID map

- netdata.spec.in
If `@HAVE_LIBBPF@` is not enabled from `config.h` do not try to embed libbpf plugin.
This is required for work with CentOS6, as libbpf is not available on 2.6.32 kernels. So bpf doesn't work, but the `bundle-libbpf.sh` is still executed, making the packaging fail.
Fixes #9705 
netdata.spec.in 
```.
./contrib/rhel/build-netdata-rpm.sh
rpm -qvp ~/rpmbuild/RPMS/x86_64/netdata-*.rpm | grep bpf
```
> Package ebpf plugin only if enabled in config.h

- contrib/debian/netdata.postinst
When the ebpf.plugin is not available for a debian/ubuntu based system, the install fails. This fixes just that.
Debian package
Did not test. The idea is to just give a correct exit status when the chmod fails.
Fixes #9707
> Fix install if system does not have ebpf.plugin

- packaging/installer/kickstart-static64.sh
- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart-64.md
- packaging/installer/methods/kickstart.md
When updating the handling of duplicate installs in our installers, I unintentionally broke offline install support. This PR fixes this by explicitly bypassing attempts to use the updater script if the user requested an offline installation of Netdata.
area/packaging
Tested locally in Docker containers.
Fixes: #9791
> Fixed handling of offline installs.

- build-artifacts.sh
- packaging/installer/netdata-updater.sh
Fixes #8782
Fixes #9763 
ssia
__WARNING:__ Testing this is a _bit tricky_ to say the least. It's a bit of a chicken 'n egg type problem until this PR is merved.
1. First of all, you need to patch the `netdata-updater.sh` on your system with teh following patch:
```#!diff
--- a/packaging/installer/netdata-updater.sh
+++ b/packaging/installer/netdata-updater.sh
@@ -123,13 +123,12 @@ set_tarball_urls() {
if [ "$1" = "stable" ]; then
local latest
-    # latest="$(curl -sSL https://api.github.com/repos/netdata/netdata/releases/latest | grep tag_name | cut -d'"' -f4)"
latest="$(download "https://api.github.com/repos/netdata/netdata/releases/latest" /dev/stdout | grep tag_name | cut -d'"' -f4)"
export NETDATA_TARBALL_URL="https://github.com/netdata/netdata/releases/download/$late …
```
> Fix the netdata-updater.sh to correctly pass REINSTALL_OPTIONS (finally)

- system/netdata.service.in
Since commit #9234 the following has been showing up in my journal logs:
>  /lib/systemd/system/netdata.service:63: Unknown lvalue 'PrivateMounts' in section 'Service'
Running `systemd-analyze verify netdata.service`
> /lib/systemd/system/netdata.service:63: Unknown lvalue 'PrivateMounts' in section 'Service'
> Attempted to remove disk file system, and we can't allow that.
It would appear that the `Attempted to remove disk file system, and we can't allow that.` message is due to a [bug](https://github.com/systemd/systemd/issues/8592) in version 237 of systemd, which is what my Ubuntu 18.04 is currently running. But that doesn't explain the "PrivateMounts" issue.
Looking at the [systemd man page](https://www.freedesktop.org/software/systemd/man/systemd.exec.html) for PrivateMounts it would …
> Remove PrivateMounts

- claim/claim.c
- daemon/commands.c
- database/rrd.h
- database/rrdhost.c
- streaming/receiver.c
- streaming/rrdpush.c
- streaming/rrdpush.h
- streaming/sender.c
- web/api/web_api_v1.c
claimed_id of nodes is streamed to parents. For easy testing also added to `/api/v1/info` (where cloud will need it anyway sooner or later)
Example of 3-level streaming from the view of top-level parent:
Streaming
Have some streaming setup and look at `/api/v1/info`. Check nothing breaks with Cloud by connecting this node to `staging.netdata.cloud`. Claim nodes and see if their claiming Id propagates up the network by checking `/api/v1/info` of the topmost node. All nodes have to be running this PR for it to work.
What was tested together with the cloud team:
1. Claim node to Staging and connect it. Node had 2 children.
1. Message as per screenshot above (with new `mirrored_hosts_status` field) is send to cloud as part of `onconnect` payload over ACLK
1. Checked Cloud GUI still works as …
> Stream Claim Id

- web/gui/main.js
relates to https://github.com/netdata/netdata/issues/9035
We host the old dashboard under /old suffix. To make it work, we had to change few paths in old js code. Netdata packaged by third party is sometimes using the old dashboard as standard, but our before mentioned changes have broken few functionalities, like opening the alarms modal.
I've added a detection to check if we are using /old suffix, or not, so 3rd party packages are not partially broken.
web/dashboard
1. Install Netdata using external package, for example `yum install netdata` in CentOS
2. Configure Nginx so that Dashboard is hosted under subpath (like http://localhost/netdata), example configuration: https://learn.netdata.cloud/docs/agent/running-behind-nginx#as-a-subfolder-to-an-existing-virtual-host
3. Go to dashboard, …
> fix old dashboard 3rd party packaging

- netdata-installer.sh
- packaging/installer/kickstart-static64.sh
- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart-64.md
- packaging/installer/methods/kickstart.md
- packaging/installer/netdata-updater.sh
This updates the checks that our installer and updater make to choose what to use for a temporary directory to be both more robust and more portable.
The original logic directly checked the mount options for `/tmp`, which is unfortunately unreliable as it doesn't work at all on FreeBSD (no procfs), probably doesn't work on macOS (different paths), and fails in some configurations on Linux (rare cases where `/tmp` is not actually a mount point, such as systems where `/` is inherently on tmpfs). The new check instead explicitly writes a temporary file at the location under test, marks it executable, and tries to run it (similar to how Autoconf generated configure scripts handle this type of thing), which will always tell us if that location is usable.
The new checks use the following logic …
> Improved temporary directory checking in installer and updater.

- database/engine/datafile.c
- database/engine/datafile.h
- database/engine/journalfile.c
- database/engine/journalfile.h
- database/engine/metadata_log/logfile.c
- database/engine/metadata_log/logfile.h
- database/engine/metadata_log/metadatalog.c
Fixes #9521
database
1. Stop the agent.
2. Go to the cache folder:
```
cd /var/cache/netdata/dbengine
```
3. Create an empty file for the metadata log:
```
touch metadatalog-00000-00013.mlf
```
4. Create empty files for dbgengine:
```
touch datafile-1-0000000333.ndf
touch journalfile-1-0000000333.njf
```
5. Start the agent.
6. The agent should operate normally from now on.
This PR changes the handling of empty dbengine and metadata-log files. Previously the dbengine instance would abort. Now it deletes the corrupted files and continues.
> Fix empty dbengine files

- packaging/installer/netdata-updater.sh
In short, you can't do default value substitution in Bash if the default value has parameter expansion meta-characters in it. Simple local test that demonstrates this: `echo ${foo:-http://example.com}` will echo an empty string in Bash.
The result of this is that the updater tries to use a malformed URL for the version check, which in turn always fails.
Users will need to manually handle updates once the next nightly goes out after this is merged.
area/packaging
Verified via local testing.
Fixes: #9829 
Originally introduced by #8808
> Fixed bug in installer introduced by #8808

- streaming/rrdpush.c
- streaming/sender.c
Imagine 3 level streaming setup child->proxy->parent where parent is v2 streaming (older version of agent) but proxy and child are latest v3 version.
When proxy connects to parent it checked the parent streaming version is at least v3 before sending `claim_id`:
```
if (s->version >= STREAM_VERSION_CLAIM)
rrdpush_claimed_id(s->host);
```
but when already connected and child sends the `claim_id` update (by `netdatacli reload-claiming-state`) the proxy forwarded it without checking version of parent trough following call chain `streaming_claimed_id->rrdpush_claimed_id`. This leads to parent disconnecting proxy with error. Then proxy reconnects to parent and continues working normally.
Therefore this is low impact bug (only happens when parent is old version while proxy is new version and …
> Fixes proxy forwarding claim_id to old parent

- packaging/installer/netdata-updater.sh
#8808 renamed a variable in `netdata-updater.sh`, but did not rename all instances of the variable, resulting in a failure in some cases for the update process. This finishes the rename so that things work properly again.
This also reverts the changes from #9831 which were intended to fix this issue but did so incorrectly due to not understanding the real underlying issue.
area/packaging
Properly locally verified in a clean environment.
Fixes: #9829 
Supersedes: #9831 
Originally bug introduced by #8808 
The original testing I did for #9831 which suggested that that would fix it was in fact bogus (I had forgotten I had a really strange `.bashrc` left over from before I switched to ZSH for normal interactive usage, and that caused the failures that I was seeing in manual testing).
> Fixed updater bug introduced by incomplete variable rename in #8808.

- collectors/cgroups.plugin/cgroup-network.c
Change a log level reported by the `cgroup-network` helper from `FATAL` to `ERROR`.
Fixes #7202
cgroups plugin
Install `canonical-livepatch` using `snap` on Ubuntu 18.04. Check if there are no fatal errors emitted by the `cgroup-network` helper.
> Change a log level in cgroup-network helper

- packaging/installer/netdata-uninstaller.sh
The message "Group ${groupname} was not automatically removed, you might have to remove it manually" was displayed even if the group had already been deleted before the invocation of the `portable_del_group` method.
I added the missing return statements to fix this.
> Don't falsely report that the group was not deleted

- web/server/web_client.c
While I was testing #9779  I observed that when Netdata was doing redirects from `http` protocol to `https` protocol, it was not adding the query string when it was present.
This PR fixes this wrong redirect.
Web
1 - Create a TLS certificate inside `/etc/netdata/ssl/`
2 - Configure your netdata.conf:
```
[web]
ssl key = /etc/netdata/ssl/key.pem
ssl certificate = /etc/netdata/ssl/cert.pem
bind to = *=dashboard|registry|streaming|management|netdata.conf|badges *:20000=dashboard|registry|streaming|netdata.conf|badges|management^SSL=optional
```
please, pay attention for the fact that the port 19999 will always redirect requests from `HTTP` while 20000 won't do this.
3 - Start Netdata
4 - Access the following URLS, with browser network visible for you see the response received:
``` …
```
> Fix redirect with parameters

- aclk/aclk_lws_wss_client.c
- database/engine/rrdengineapi.c
Fixes compilation warning on FreeBSD:
```
aclk/aclk_lws_wss_client.c:204:50: warning: too many arguments in call to 'aclk_lws_wss_clear_io_buffers'
aclk_lws_wss_clear_io_buffers(engine_instance);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                ^
aclk/aclk_lws_wss_client.c:513:58: warning: too many arguments in call to 'aclk_lws_wss_clear_io_buffers'
aclk_lws_wss_clear_io_buffers(engine_instance);
```
and on Linux:
```
CC       database/engine/metadata_log/metalogpluginsd.o
database/engine/rrdengineapi.c: In function ‘rrdeng_store_metric_flush_current_page’:
database/engine/rrdengineapi.c:190:13: warning: unused variable ‘ret’ [-Wunused-variable]
190 |         int ret, page_is_empty;
|             ^~~
CC       database/engine/metadata_log/compaction.o
```
Netdata
Compilation should not show …
> fixes compilation warnings

- libnetdata/simple_pattern/README.md
Fixes netdata/netdata-learn-docusaurus#296
@OdysLam pointed out that the **Edit this page** link on the simple pattern doc leads to a 404. This doc didn't have any frontmatter to override the default and point to the correct location, so I added the frontmatter and the `custom_edit_url` field.
area/docs
> Fix broken `Edit this page` link in simple patterns doc

- netdata-installer.sh
- packaging/installer/kickstart-static64.sh
- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart-64.md
- packaging/installer/methods/kickstart.md
- packaging/installer/netdata-updater.sh
When writing the new temporary directory handling code, I forgot that POSIX versions of the `echo` command don't take any options, and as a result ended up breaking the installer and updater for systems that use a POSIX version of `echo`. This fixes the issue by just using `printf` instead.
area/packaging
Relevant code manually tested on macOS and FreeBSD.
Fixes: #9840
> Fixed tmpdir handling failure on macOS/FreeBSD.

- configure.ac
- netdata-installer.sh
Don't install eBPF components
- when eBPF plugin is explicitly disabled using the `--disable-ebpf` flag.
- on FreeBSD.
- on macOS.
Possibly fixes #9750
eBPF plugin
Check Netdata installation
- With the `--disable-ebpf` flag.
- On FreeBSD.
- On macOS.
> Don't install eBPF plugin components when they shouldn't be installed

- contrib/rhel/build-netdata-rpm.sh
When creating a package using this script, it's not straighforward that
the version is fetched at the "configure" stage, by "git describe" which
generates a 'lasttag-ncommits-lastcommit' format description. RPM
doesn't allow - in version, so the rpmbuild stage fails.
Add hints of actions to perform to get this script working
Use package standard functions for the message to be seen easily
Example failed message:
```
FAILED  Current version contains '-' which is fobidden by rpm. You must create a git annotated tag and rerun this script. Exemple: 
FAILED    git tag -a v1.24.0_0822113117 -m 'Release by adrien on munin' && ./build-netdata-rpm.sh 
```
Example ok message:
```
OK  All done! Packages created in '/home/adrien/rpmbuild/RPMS/x86_64' 
```
contrib/rhel/build-netdata-rpm.sh
1. Exec: …
> rpm: Fix rpm build script version issues

- packaging/installer/install-required-packages.sh
This fixes two bugs present in our current handling of Python 3 dependencies:
1. We unconditionally try to install the Python 3 MongoDB module whenever we have been told to install Python 3, instead of it being dependent on whether the user has asked us to install MongoDB deps or not. This PR removes the duplicate install line that was causing this.
2. We incorrectly claim alack of Python 3 packages on CentOS and RHEL systems (and their derivatives), as well as not having proper entries for these packges for some system types. This leads to installation failures in some cases. This PR fixes this by adding appropriate overrides for the relevant packages for specific versions of CentOS/RHEL based on what is actually available.
area/packaging
Verified locally on CentOS 7 and 8 systems. …
> Fixed bugs in handling of Python 3 dependencies on install.

- collectors/python.d.plugin/openldap/openldap.chart.py
- collectors/python.d.plugin/openldap/openldap.conf
Since [`ldaps:// `is deprecated](https://www.openldap.org/faq/data/cache/605.html), we use TSL over `ldap://` with `start_tsl` on our LDAP server; that case is not covered by the code.
I added the option `use_start_tls` by `sudo ./edit-config python.d/openldap.conf` and managed them in  `/usr/libexec/netdata/python.d/openldap.chart.py` .
python.d/openldap
I tested it for TSL over `ldap://` with `start_tls`;
we should test if TSL over `ldaps://` is not broken.
Related to [issue 9004](https://github.com/netdata/netdata/issues/9004).
> python.d/openldap: fix tls over ldap

- collectors/proc.plugin/proc_loadavg.c
- health/health.d/processes.conf
Added feature mentioned on #6133 and also applied changes mentioned on #9838 
Collectors and Health
Made it possible so we can read the value of `pid_max` for linux. After that, the notification calculates active processes percentage based on the given limit. The limit was added as a `VARIABLE` to the `active_processes` graph so we can use it in the processes.conf file. On freebsd the limit is static so made it to calculate % based on it
> collect active processes limit feature v2

- docs/overview/netdata-monitoring-stack.md
- docs/overview/what-is-netdata.md
- docs/overview/why-netdata.md
This is the first of many PRs for the project on rearchitecting Netdata's documentation. See netdata/netdata-learn-docusaurus#285 for additional context.
Starting with overview content of what Netdata is.
**Some links will not work, as the target docs do not exist yet.**
For now, these PRs will get merged into the `docsv2` but not go live on [Netdata Learn](https://learn.netdata.cloud). Once they're all available, or at least a workable majority, we'll merge them into `master` and deploy the project as a whole.
area/docs
> Add overview docs to docsv2 project

- packaging/installer/install-required-packages.sh
This updates how we handle libJudy in our dependency installation script. Instead of trying to install it everywhere and hoping it works, we now only install it on distros that we know both a system copy available that actually works.
area/packaging
Verified that this behaves correctly in our CI.
Followup to: #9776 
Fixes: #9267 
Fixes: #9356 
Fixes: #9605 
This functionally adds CI for #9776 because we test on platforms that will now not have libJudy installed in the testing environment.
> Removed dependency on libJudy for systems which don't have it.

- collectors/python.d.plugin/dnsdist/dnsdist.chart.py
The latency-avg values are in microseconds, not milliseconds.
https://dnsdist.org/statistics.html#latency-avg100
The latency average graph is currently labeled with ms/query (milliseconds), but it should be us/query (microseconds). I got a little panicy when I was reading that my DNS queries were taking 5 seconds on average. 
dnsdist collector
> python.d/dnsdist: fix latency-avg chart units

- database/engine/metadata_log/metalogpluginsd.c
- database/rrdhost.c
- streaming/receiver.c
- streaming/rrdpush.c
Fixes #9627
streaming
1. Create a 1000 node streaming set-up.
2. Use `dbengine`, disable health for streaming, delete the cache.
2. Use master code, observe crash.
3. Delete the cache again.
4. Use this PR, observe no crash.
5. Restart the agent, observe health is still disabled for all child hosts, no crash.
6. Enable health for streaming.
7. Restart the agent, observe health is enabled for all child hosts.
> Fix race condition with orphan hosts

- Makefile.am
- netdata.spec.in
- packaging/bundle-judy.sh
- packaging/installer/install-required-packages.sh
When preparing the libJudy bundling code, I forgot to account for the fact that we use `install-required-packages.sh` to set up build environments for our binary packages. Asa result, RPM builds are broken because of libJudy not being installed.
This PR adds the required code to the spec file to fix this, as well as adding Fedora to the list of systems which we will use a system copy of libJudy from (because it actually works there).
area/packaging
Locally verified in Fedora, CentOS and OpenSUSE containers by manually building the packages. The Travis CI failure is expected and is a result of limitations inherent to using LXC through Python (namely, we can't copy files from the 'host' environment, and thus are forced to use the older copy of `install-required-packages.sh` from the master …
> Fixed handling of libJudy bundling for RPM packages.

- streaming/receiver.c
Fix the following coverity defect:
** CID 361629:  Program hangs  (ORDER_REVERSAL)
```
*** CID 361629:  Program hangs  (ORDER_REVERSAL)
/streaming/receiver.c: 464 in rrdpush_receive()
458                 rpt->host->senders_disconnected_time = now_realtime_sec();
459                 rrdhost_flag_set(rpt->host, RRDHOST_FLAG_ORPHAN);
460                 if(health_enabled == CONFIG_BOOLEAN_AUTO)
461                     rpt->host->health_enabled = 0;
462             }
463             if (rpt->host->receiver == rpt) {
>>>     CID 361629:  Program hangs  (ORDER_REVERSAL)
>>>     Calling "rrdpush_sender_thread_stop" acquires lock "sender_state.mutex" while holding lock "rrdhost.rrdhost_rwlock" …
```
> Fix lock order reversal. (Coverity defect CID 361629)

- aclk/aclk_common.c
- aclk/aclk_common.h
- aclk/aclk_query.c
- aclk/agent_cloud_link.c
- aclk/agent_cloud_link.h
- aclk/mqtt.c
- aclk/mqtt.h
- claim/claim.c
Merge is possible after following cloud PRs are released to production:
The agent will send a `hello` message to the cloud as soon as the MQTT connection is made and the agent is subscribed.
The agent will wait up to 3 seconds for a reply from the cloud and if none arrives default to an oldest supported version _(this is done so we can merge this before cloud implements support for this messages)_.
If reply arrives _(in form of `version` message)_ the highest version supported by both Agent and Cloud is selected for communication.
Messages `hello`, `version`, and LWT are versioned separately as they are sent (in case of LWT set) before the negotiation was finished.
The first test is easy. Connect agent to staging and as it doesn't reply to `hello` message you should see it to revert to …
> ACLK Version Negotiation

- health/notifications/alarm-notify.sh.in
While I was working at #9886 , @ilyam8 [gave the idea](https://github.com/netdata/netdata/pull/9886#discussion_r483868644) that we could improve the message we are giving for our users when a HTTP connections fails.
Considering what is written in the [RFC](https://tools.ietf.org/html/rfc2616#section-6.1), I am bringing this PR to improve our error message.
Health
1 - Compile this PR
2 - Set a wrong URL inside your `/etc/netdata/health_alarm_notify.conf` for the channel you are using.
3 - Go to directory `/usr/libexec/netdata/plugins.d/` and run:
```
`./alarm-notify.sh test`
```
> Change HTTP error message

- .travis.yml
This stops Travis CI from sending internal notifications Slack/FOSSA notifications on branches other than `master`.
It also adds failure notifications to the DEB and RPM build checks.
area/ci
Validated the YAML for the config and checked the config itself on Travis for my own branch. Exact changes are not trivially testable, but match up with official documentation.
> Make internal Travis CI notifications behave better.

- web/api/queries/query.c
Fixes #9675
database
1. Set-up a parent-child streaming set-up where the parent is using `memory mode = dbengine`.
2. Let the system gather some metrics for 5 minutes.
3. Open the browser tab for localhost and the child host in the parent node's dashboard.
4. Turn off clock synchronization in the child node.
5. Get the current time of the parent node, e.g.:
```
root@Ubuntu-Test:~# date +%T
15:26:32
```
6. Wait 20 seconds and set that time at the child node, e.g.:
```
root@Ubuntu-Test2:~/netdata# date +%T -s "15:26:32"
```
7. This will set the child and the node out of sync.
8. Scroll back and forth, zoom in and out, until the tab crashes.
9. If it doesn't immediately crash move the child node's date forward and backwards until it does.
10. Alternatively you may let the system be idle for …
> Fix buffer overflow in rrdr structure

- docs/quickstart/infrastructure.md
- docs/quickstart/single-node.md
The two quickstart documents—single-node vs. infrastructure—that aim to help users find the most important features of Netdata based on their need and the features available to them. 
And the context:
>
>
>
> Add quickstart docs to docsv2 project

- build/subst.inc
- packaging/installer/functions.sh
- packaging/installer/netdata-uninstaller.sh
- system/Makefile.am
- system/netdata.crontab.in
This adds support for scheduling auto-updates by placing a crontab in `/etc/cron.d` on systems that do not have either `/etc/cron.daily` or `/etc/periodic/daily`. The crontab fragment used for this runs the updater as root at 02:57 daily (but still uses the same random delay that our current auto-update approach uses), with the time chosen arbitrarily to be different from the times used by most major distributions for their daily scheduled tasks.
area/packaging
Crontab verified to work correctly on a number of local test systems through manual testing. Detection logic in the installer tested on a couple of systems by explicitly removing `/etc/cron.daily` and `/etc/periodic/daily`.
Part of fixing #9077 
Partially supersedes #9577
> Added support for using `/etc/cron.d` for auto-updates.

- daemon/buildinfo.c
I just noticed #9913 from @Ferroin got merged yesterday.
This PR improves by adding better info if ACLK was disabled by user request
build with `--disable-cloud`
build with ACLK
@Ferroin good idea to bring this feature as it allows us to diagnose issues that users might have much more easily.
> adds ACLK DISABLE_CLOUD to -W buildinfo

- README.md
- packaging/docker/README.md
Related to https://github.com/netdata/netdata/issues/5516#issuecomment-687791386
This PR adds more details about configuring Netdata when it's run in a Docker container. The recommended method is using a bind mount, which doesn't require any additional steps. I also added details about editing the config _inside_ the container by first using `docker exec`.
I also added a new section using @ilyam8's instructions to populate a volume for a host-editable config directory.
area/docs
> Add persistent configuration details to Docker docs

- web/api/netdata-swagger.json
- web/api/netdata-swagger.yaml
In ab7ff3131f3698710e0bd9fa3c66d31a3a194725 `mirrored_hosts_status` field was added into `/api/v1/info` however this was not reflected in OpenAPI (swagger) documentation. This PR fixes that oversight
OpenAPI docu
Check the description of `mirrored_hosts_status` is valid and matches what gets delivered by `/api/v1/info`. Make sure you check on host that has some children.
> add mirrored_hosts_status into OpenAPI of api/info

- netdata.spec.in
Our current RPM spec file includes _all_ of our library dependencies as statically listed `Requires:` lines. This, in turn, requires a very large number of conditionals in the dependencies to account for package naming differences between RPM distros, and also makes it a pain in the arse to port the spec file to work with new releases of existing distros.
This changes the spec file to just use the automatic `Requires:` generation functionality that's already included in the RPM build process. The net effect is that the spec file ends up much cleaner, and it works just about anywhere with minimal modification., as well as us not having to track anything but build dependencies manually. It also results in a more accurate representation of our dependencies, because the resulting RPM depends …
> Updated RPM spec file to use automatic dependency list generation.

- docs/collect/application-metrics.md
- docs/collect/container-metrics.md
- docs/collect/enable-configure.md
- docs/collect/how-collectors-work.md
- docs/collect/system-metrics.md
Five new documents: 
- How Netdata's metrics collectors work
- Enable or configure a collector
- Collect system metrics with Netdata
- Collect container metrics with Netdata
- Collect application metrics with Netdata
>
>
>
area/docs
> Add collect docs to the docsv2 project

- .gitignore
`system/netdata.crontab` missing in gitignore. As a result I can't sleep as `git status` now triggers my OCD.
> adds missing file netdata.crontab to gitignore

- web/api/formatters/rrd2json.c
Updates the last accessed time for all charts matching a context during a data query
database
> Fixed chart's last accessed time during context queries

- docs/configure/nodes.md
- docs/monitor/configure-alarms.md
- docs/monitor/enable-notifications.md
- docs/monitor/view-active-alarms.md
Three documents about viewing alarms, editing alarms, and enabling notifications. Again, most content repurposed and reconfigured.
>
>
>
> Add monitor docs to docsv2 project

- .github/dockerfiles/Dockerfile.build_test
- .github/workflows/build-and-install.yml
- CMakeLists.txt
- configure.ac
- exporting/aws_kinesis/README.md
Starting from version 1.7.0 of AWS SDK for C++, [third-party dependencies](https://github.com/aws/aws-sdk-cpp#third-party-dependencies) were added. Netdata's installation instructions and build configuration were updated in this PR so that Netdata can be built with the newest versions of the SDK.
Fixes #8039
exporting engine, backends
[Install AWS SDK for C++](https://learn.netdata.cloud/docs/agent/exporting/aws_kinesis#prerequisites) either from a package or from the source. Check if Netdata can be built without errors and the Kinesis exporting connector is working.
> Fix build for the AWS Kinesis exporting connector

- netdata-installer.sh
Fixes #9961 
As discussed in the specified issue, this PR is fixing the typo that we have inside `netdata-installer.sh`
Installer.
Install Netdata on an environment that has Netdata is already running and verify that the error is fixed
> Fix typo inside netdata-installer.sh

- .github/workflows/build-and-install.yml
This prevents us from hanging in debconf prompts during the setup process, which in turn prevents us from hanging until the job gets auto-cancelled.
area/ci
The CI checks pass without being cancelled due to hanging.
> Use non-interactive backend for debconf in Kinesis CI setup.

- collectors/ebpf.plugin/README.md
We had our `yes` and `no` mixed up for this setting. This PR is a quick fix to flip the logic.
cc @OdysLam 
area/docs
Verified on my local system that setting `disable apps = yes` removed the eBPF charts from the **Applications** section. They were enabled and visible by default.
> Fix setting for disabling eBPF-apps.plugin integration

- docs/store/change-metrics-storage.md
- docs/store/distributed-data-architecture.md
One high-level document about the distributed data architecture, and another for changing metrics retention.
See [a preview of the inline calculator](https://deploy-preview-285--netdata-docusaurus.netlify.app/docs/store/change-metrics-storage#calculate-the-system-resources-ram-disk-space-needed-to-store-metrics).
>
>
>
> For now, these PRs will get merged into the docsv2 but not go live on Netdata Learn. Once they're all available, or at least a …
> Add store docs to docsv2 project

- aclk/aclk_common.c
- aclk/aclk_lws_wss_client.c
- aclk/agent_cloud_link.c
As a first step towards allowing usage of system LWS we allow building Netdata with LWS that was built without SOCKS5.
In case the user tries to use SOCKS5 we will log appropriate error into the logfile and ignore the setting.
More detailed discussion #8961 
ACLK
Build with LWS without SOCKS 5 support. Should build without error. Example how to do that: Cripple installer.sh (remove `LWS_WITH_SOCKS5:bool=ON`) here (in else branch):
```
build_libwebsockets() {
local env_cmd=''
if [ -z "${DONT_SCRUB_CFLAGS_EVEN_THOUGH_IT_MAY_BREAK_THINGS}" ]; then
env_cmd="env CFLAGS= CXXFLAGS= LDFLAGS="
fi
pushd "${1}" > /dev/null || exit 1
if [ "$(uname)" = "Darwin" ] && [ -d /usr/local/opt/openssl ]; then
run ${env_cmd} cmake \
-D OPENSSL_ROOT_DIR=/usr/local/opt/openssl \
-D …
```
> allow using LWS without SOCKS5

- database/engine/rrdengineapi.c
- database/engine/rrdengineapi.h
- database/rrd.h
- web/api/formatters/rrd2json.c
- web/api/formatters/rrd2json.h
- web/api/queries/query.c
- web/api/queries/rrdr.c
- web/api/queries/rrdr.h
- web/api/web_api_v1.c
Improved the processing of the data query when data for a `context` is requested
- Define a generic structure to pass along to functions (instead of RRDDIM linked list) to allow for easy changes in the future
- Collect the matching charts, dimensions and calculate first_entry_t / last_entry_t at the same time
- Speedup context match by using the context hash in RRDSET
- Add correct response `Chart is not found:` or `Context is not found:`
database
Example context call
```
http://127.0.0.1:19999/api/v1/data?context=cpu.cpu&options=jsonwrap
```
> Improved the data query when using the context parameter

- configure.ac
This will help ensure that people who are building on a compiler that does not support C99 get a more useful message about needing C99 and also avoid wasting time getting into the build itself.
area/build
Locally checked using a special wrapper for GCC that unconditionally passes `-std=c89` to fail the C99 check.
This is largely proactively preventing an issue we do not currently have. Linux, BSD, and macOS largely universally have working C99 support.  However, when we eventually branch out into IoT usage, we will likely have to deal with significantly more exotic build environments, and there are a surprising number of systems out there that only support ANSI C (C89), not C99.
> Added more stringent check for C99 support in configure script.

- packaging/installer/functions.sh
They're a side-effect of a botched merge on my end and break auto updates and installs with auto-updates enabled.
area/packaging
Verified more thoroughly this time that everything works...
Fixes: #9990
> Fixed typos in installer functions.

- database/rrdhost.c
Fixes #9363
database
First add a low timeout for cleaning up obsolete charts.
```
[global]
cleanup obsolete charts after seconds = 10
```
Then make the `/proc/net/dev` collector obsolete the chart itself, without obsoleting its dimensions, as follows:
1. Start a bunch of LXC containers that will create new network devices.
2. Stop those containers so that the collector obsoletes the relevant charts.
3. Start some more containers.
4. Wait for a minute to trigger the cleanup logic.
5. Gracefully shut down the agent.
At this point, the agent will crash with a double-free or use-after-free during shutdown of localhost `RRDHOST`. This PR should fix that situation.
> Fix cleanup of obsolete charts

- web/api/formatters/rrd2json.c
```
7             }
68     #endif
69             rd->next = (*param_list)->rd;
70             (*param_list)->rd = rd;
71         }
72     
>>>     CID 362348:  API usage errors  (LOCK)
>>>     "__netdata_rwlock_unlock" unlocks "st->rrdset_rwlock" while it is unlocked.
73         rrdset_unlock(st);
74     }
75     
76     void rrd_stats_api_v1_chart(RRDSET *st, BUFFER *wb) {
77         rrdset2json(st, wb, NULL, NULL, 0);
78     }
```
Change the locking order to handle CID_362348. The lock may be acquired and released by the functions
that calculate the first_entry_t and last_entry_t.
database
- Submit a build to coverity
> Fixed locking order to address CID_362348

- netdata-installer.sh
- packaging/installer/functions.sh
- packaging/installer/netdata-uninstaller.sh
- system/Makefile.am
- system/netdata-updater.service.in
- system/netdata-updater.timer
This adds two new features around auto-updates:
* Support for using  systemd timer unit and associated service to handle updates. This removes the need to have either a working cron daemon or a special shim on systemd systems if the user wants auto-updates. This will be used only if the `/etc/cron.daily` or `/etc/periodic/daily` methods don't work, as it does not provide email notifications for failures.
* Add the ability to override the auto-detection of the auto-update mechanism using a new `--auto-update-type` option. Takes one of `systemd`, `interval`, or `crontab` to select that type of auto-update scheduling. This should improve testability as well as allowing users who want something other than the default to actually use it.
area/packaging
Verified locally on a variety of …
> Added improved auto-update support.

- packaging/makeself/install-alpine-packages.sh
This removes the old code from our static build process for bundling libJudy in favor of leveraging the new bundling code in `netdata-installer.sh`. There is no net change from an end-user perspective, but this will make our static build more consistent with our other installation methods, simplifying maintenance for us and also marginally reducing the disk space needed for the static build process.
area/packaging
Verified that libJudy gets linked in using `netdata -W buildinfo` and checked that the dbengine stress testing works correctly.
I intended to do this as part of the changes that came shortly after adding the libJudy bundling code, but unfortunately forgot about it then.
> Switched to our installer's bundling code for libJudy in static installs.

- aclk/agent_cloud_link.c
Each message was prepended by the leading tab. This typo causes Cloud to have bothersome additional processing step for agent messages that skips leading whitespace before parsing JSON message.
ACLK
messages should not have leading space anymoar.
Before:
```
{"type": "hello",
"msg-id": "32a7e02e-8c68-498c-8f5c-a4e010e3f95c",
"timestamp": 1601307084,
"timestamp-offset-usec": 4898,
"connect": 1601307083,
"connect-offset-usec": 29813,
"version": 1,
```
After:
```
{       "type": "hello",
"msg-id": "32a7e02e-8c68-498c-8f5c-a4e010e3f95c",
"timestamp": 1601307084,
"timestamp-offset-usec": 4898,
"connect": 1601307083,
"connect-offset-usec": 29813,
"version": 1,
```
> minor - removes leading whitespace before JSON in ACLK

- aclk/agent_cloud_link.c
After meeting with Costa we had agreed to change the default ACLK Query Thread count to be following:
1. `available cores / 2`
1. but `max of 6`
1. and `min of 2`
This applies only for default value. User might configure more than 6 threads.
ACLK
> changes default query thread count

- .github/workflows/checks.yml
- .gitignore
- netdata-installer.sh
When adding systemd timer unit support for the updater, I unintentionally missed a few places that needed changed to avoid leaving the repo dirty after a build and install.
This also adds a CI check to help ensure this doesn't happen again.
area/packaging
area/ci
Newly added CI check passes correctly, but ails if run against the current `master` branch.
> Add a few changes that were missed by the systemd updater support.

- claim/README.md
- docs/guides/monitor/kubernetes-k8s-netdata.md
- docs/guides/monitor/pi-hole-raspberry-pi.md
- packaging/installer/methods/kubernetes.md
Fixes #8779
This PR improves our k8s documentation in two ways:
1. Adds details on how to claim a k8s cluster's parent Netdata pod.
2. Improves mentions of service discovery to include endpoints supported by the Prometheus collector.
Once this PR is merged, I'll add some additional text to the Helmchart repo with a link to the claiming process.
area/docs
Tested and verified the claiming instructions on a k8s cluster.
> Add documentation for claiming k8s parent pods and Prometheus service discovery

- collectors/proc.plugin/sys_class_infiniband.c
Fix a missing file-descriptor leak due to missing closedir() during discovery, reported by #10012 
proc.plugin
> collector infiniband: fix file descriptor leak

- aclk/aclk_common.c
- aclk/aclk_common.h
- aclk/aclk_lws_https_client.c
- aclk/aclk_lws_https_client.h
- aclk/agent_cloud_link.c
For easier testing of ACLK, it is useful to connect to an arbitrary MQTT WSS brokers. This allows doing that easily by adding `-DACLK_DISABLE_CHALLENGE` to the compiler.
This will disable challenge-response functionality which is supported and specific only to netdata cloud.
During the implementation, I noticed we are unnecessarily passing the port as both string and integer and carrying that around the code. This fixes also that problem.
Review the 2 commits separately for a clearer picture as one does code cleanup and the second one actually implements the feature,
ACLK
compile with `-DACLK_SSL_ALLOW_SELF_SIGNED -DACLK_DISABLE_CHALLENGE`, set up `cloud base url = 127.0.0.1:9002` in `cloud.conf`. Set mosquito broker (compiled with WSS support) to listen with WSS listener on port `9002`. …
> Allow connecting to arbitrary MQTT WSS broker for devs

- web/api/web_api_v1.c
When a chart and context is specified in a data query give priority to the chart
database
Before the PR
`http://127.0.0.1:19999/api/v1/data?chart=system.cpu&options=jsonwrap&format=array&after=-10&context=cpu.cpu`
will return a response for the **cpu.cpu**
With the change in this PR the `context=cpu.cpu` will be ignored and return information for the **system.cpu** chart
> Fixed the data endpoint to prioritize chart over context if both are present

- web/gui/dashboard_info.js
Add Go web_log gauges by duplicating from dashboard_full.js
Fixes #9810 
You can enable `go` `web_log` for nginx with this command `./go.d.plugin -d -m web_log`, make sure log path is correct, then restart netdata `systemctl restart netdata`, an at the end you should be able to see the gauges for go web_log module
> Fixed gauges for go web_log module

- collectors/python.d.plugin/rabbitmq/rabbitmq.chart.py
Takes 'churn_rates" data from RabbitMQ api/overview and adds the chart to netdata front end.  The structure of the data parser enables a simple addition of the metrics that are needed to the existing data structures.
> python.d/rabbitmq: Add chart for churn rates

- packaging/docker/Dockerfile
- packaging/docker/run.sh
Because it clashes with a kubernetes defined NETDATA_PORT variable: Our Helm
chart creates a service called netdata which in turn makes kubernetes export a
NETDATA_PORT environment variable with a value like tcp://\<ip\>:19999 which is
not parsable by the netdata agent as a value to the `-p` argument.
This PR should resolve the:
```
netdata ERROR : MAIN : LISTENER: Invalid listen port 0 given. Defaulting
to 19999. (errno 22, Invalid argument)
```
errors seen in Helm installations as reported in netdata/helmchart#161.
> Rename NETDATA_PORT to NETDATA_LISTENER_PORT

- health/health.d/portcheck.conf
Fixes: #10043
go.d portcheck has [`failed`](https://github.com/netdata/go.d.plugin/blob/7959eff02c96b23a994f1d1e532aa43203bb2138/modules/portcheck/charts.go#L26) dimension, py - [`no_connection`](https://github.com/netdata/netdata/blob/04344fda25733c674dd6db6bf59d75586293bbee/collectors/python.d.plugin/portcheck/portcheck.chart.py#L35)
`health/`
Tested locally, it works
> health/portcheck: add `failed` dim to the `connection_fails` alarm

- collectors/python.d.plugin/README.md
small docs update - adding note about using `nolock` when debugging
> small docs update - adding note about using `nolock` when debugging

- web/gui/dashboard_info.js
I randomly noticed that there was a missing period at the end of this sentence. See the image below (circled in red).
https://i.imgur.com/4qEvdWt.png
This PR adds the period to that sentence. Feel free to decline if you don't need this fix.
Thanks.
dashboard_info.js
> Add missing period in netdata dashboard

- .travis.yml
Package build runs on Travis only happen as part of release builds. Because they happen _after_ the rest of the release, the build checks have already run at least once because they're run as part of the initial release build. As such, there’s no point in running them again on the packaging builds, especially since they are the primary reason that the packaging builds experience transient errors.
This will both speed up the overall release process (quite a bit in fact, the redundant build checks account or more than half the time it currently takes to cut a release) and also reduce the false failure rate on package builds to near zero.
area/ci
Behavior of the conditional itself verified through prior usage in other parts of the Travis CI configuration.
> Skip all build checks on CI packaging builds.

- system/netdata.service.in
comments for systemd service files are only allowed in the beginning of a new line
https://www.freedesktop.org/software/systemd/man/systemd.syntax.html
otherwise you get error messages like
```
/usr/lib/systemd/system/netdata.service:48: Failed to parse capability in bounding/ambient set, ignoring: #
```
> Fix systemd comment syntax

- contrib/debian/control
https://lintian.debian.org/tags/build-depends-on-build-essential-package-without-using-version.html
> Removed redundant dependencies from Debian control file.

- packaging/installer/UPDATE.md
* Add a section to help users figure out which method they originally used to install Netdata.
* Update the description of how the manual update process works.
* Add a fallback command to help users deal with failures using the normal update process for the `kickstart.sh` and `kickstart-static64.sh` install methods.
* Don’t line wrap a long link that is causing problems with syntax highlighting in some editors when manually line-wrapped (it makes the whole document look like one big link).
area/docs
n/a
> Added more robust doucmentation around updates.

- web/gui/custom/README.md
Fixed a typo in formatting source code in Custom Dashboard page in "Prevent dashboard.js from starting chart refreshes" section.
Documentation about custom dashboards.
URL: https://learn.netdata.cloud/docs/agent/web/gui/custom#what-does-dashboardjs-do
1. Need to open page https://learn.netdata.cloud/docs/agent/web/gui/custom#what-does-dashboardjs-do
2. Check "Prevent dashboard.js from starting chart refreshes" section
3. Code blocks should not leak to text.
**Actual behavior:**
**Fixed behavior there is in "Files changed" tab.**
> Fix formatting source code blocks in custom dashboard page

- collectors/python.d.plugin/rabbitmq/README.md
- collectors/python.d.plugin/rabbitmq/rabbitmq.chart.py
- collectors/python.d.plugin/rabbitmq/rabbitmq.conf
- web/gui/dashboard_info.js
This PR adds new metrics to be collected and their associated charts to the rabbitmq python.d plugin.
Those metrics are per-queue stats, where metrics were global or per-vhost before.
collector / python.d / rabbitmq.chart.py
Using a local rabbitmq, configured to have multiple vhosts, multiple queues within those vhosts, I generated traffic to see the impact on Netdata
This is my first PR, I'm not sure everything's fine and I'd love guidance to make it work
> Add per queue charts in rabbitmq.chart.py

- collectors/cgroups.plugin/sys_fs_cgroup.c
This PR updates `enable by default cgroups matching` default value: as agreed in https://github.com/netdata/netdata/issues/10006#issuecomment-707314548 we filter pod level cgroups.
Cgroup tree structure on the GKE and minikube nodes
```cmd
#
```
All `*.slice` cgroups already filtered, so minikube case is ok.
`collectors/cgroups`
Changes are pretty straightforward, but i tested them on GKE - i see only container level cgroups.
> collectors/cgroups: filter pod level cgroups

- collectors/cgroups.plugin/cgroup-name.sh.in
Fixes: #10006
Correctly resolve all `kubepods/*` cgroups names when running inside the k8s cluster (http req to the API server) or installed on a k8 node (via `kubectl`).
New naming format (**breaking change**):
- pod level cgroup name format: `k8s_pod_<NAMESPACE>_<POD_NAME>`
- container level cgroup name format: `k8s_cntr_<NAMESPACE>_<POD_NAME>_<CONTAINER_NAME>`
**I don't add filtering to the cgroup-name.sh script**, so all level cgroup are collected. I think it is better to have filtering in the cgroups collector configuration options (`enable by default cgroups matching`).
**This PR doesn't contain** `enable by default cgroups matching` option updates, i plan to add them in a separet PR (added in https://github.com/netdata/netdata/pull/10095).
Cgroup tree structure on the GKE and …
> collectors/cgroups: fix resolving container names in k8s

- collectors/python.d.plugin/nvidia_smi/README.md
- collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py
- collectors/python.d.plugin/nvidia_smi/nvidia_smi.conf
Exclude from nr_user count users with zero memory allocated
Really small change;
just to avoid counting users with actually no memory allocated.
nvidia-smi python collector
> nvidia_smi: Not count users with zero memory allocated

- database/rrdcalc.c
- database/rrdcalc.h
- database/rrdcalctemplate.c
- database/rrdcalctemplate.h
- health/REFERENCE.md
- health/health_config.c
Fixes #10014 
This PR is bringing new entities for alarms that will help us to notify users that a specific module is deprecated for a plugin and we are using another plugin with the same features.
Health
The suggestion here is to simulate something near the next steps (the  alarm creation):
<details>
<summary>test setup click click!</summary>
1 - Configure the python example plugin
```bash
```
and uncommenting the following line:
```
example: yes
```
2 - Compile this PR.
3 - Now test this PR with the following alarms:
- Test if nothing was breaking:
```
alarm: dev_dim_template
on: example.random
os: linux
lookup: sum -3s at 0 every 3 percentage foreach *
units: %
every: 1s
crit: $this > 4
```
- Test a template with module:
```
template: disable_example_plugin
on: random …
```
> New alarm entities

- configure.ac
Fixes cross compilation by properly disabling ebpf detection. Fixes #9750.
> Don't check for ebpf dependencies if ebpf is disabled.

- collectors/perf.plugin/perf_plugin.c
- collectors/slabinfo.plugin/slabinfo.c
When adding debug calls, some printf formats (like uint64_t) are arch-dependent. On a 32bits, a uint64_t is "unsigned long long unsigned int", so expects %llu instead of %lu.
These different formats are set in `<inttypes.h>` and explained here: https://en.cppreference.com/w/cpp/types/integer 
This PR does the following changes:
- `size_t` => `%zu`
- `uint64_t` => `%"PRIu64"`
Fixes #10086 
slabinfo.plugin
Standard compilation flags (-Wformat)
> Fix platform dependent printf format

- streaming/receiver.c
Fixes #10114
Disregard host tags configuration pointer and keep duplicate string from streaming handshake.
streaming
Set up "host tags" in the `[backend]` section of `netdata.conf` of a slave node and enable backends, e.g.
```
[backend]
host tags = test1="1",test2="22",test3="33",test4="4444"
enabled = yes
```
Restart the slave node 3 times. The 3rd time the slave node connects yo the parent it corrupts the parent's heap.
> Disregard host tags configuration pointer

- web/gui/index.html
The SSO `iframe` is not completely hidden and it appears as a small visible square.
Web / Gui
Add / Remove `style="border: none;"` on the `iframe` with the web console
You can see the issue with the picture below:
After patch:
I've spotted the issue on the stable and nightly versions.
> Completely hide SSO iframe

- web/api/netdata-swagger.json
- web/api/netdata-swagger.yaml
- web/api/queries/query.c
- web/api/queries/rrdr.h
- web/api/web_api_v1.c
Adds a new query option `allow_past` for the data endpoint that will allow the after parameter to extend before the first timestamp stored.  The entries that do not exist will be returned as null
database
- Start agent will no history (e.g. if using dbengine memory mode, delete the dbengine files)
- Run a query such as: 
`/api/v1/data?chart=system.cpu`
- This should return just a few entries (the number of seconds the agent is up and running)
- Run the query 
`/api/v1/data?chart=system.cpu&options=allow_past`
- You should get 600 entries returned, most of them null
> Added new data query option "allow_past"

- .github/workflows/review.yml
This splits out the ReviewDog CI checks to only run on PRs that actually change files of types they are checking. This should keep the CI list cleaner, and make it less likely that issues with ReviewDog will affect PRs that are unrelated to the checks that are having issues.
area/ci
Of the three review checks, only the yamllint one actually runs the check itself, with the others skipping the reviewdog step of their job.
Prompted by current issues with the eslint checks in ReviewDog.
> Split ReviewDog check to only run when relevant.

- collectors/ebpf.plugin/ebpf.c
- collectors/ebpf.plugin/ebpf.h
- collectors/ebpf.plugin/ebpf_apps.c
- collectors/ebpf.plugin/ebpf_apps.h
- collectors/ebpf.plugin/ebpf_process.c
- collectors/ebpf.plugin/ebpf_socket.c
- collectors/ebpf.plugin/ebpf_socket.h
- libnetdata/ebpf/ebpf.c
- libnetdata/ebpf/ebpf.h
This PR fixes the memory cleanup when `ebpf.plugin` is closed.
I am also using this PR to remove some unnecessary code, because we are using `libbpf` now, but instead to remove the old code, I decided to comment it, because it can be useful where `libbpf` cannot be used.
Ebpf plugin
1 - Install `libasan` on your environment. 
2 - Compile this branch with the following flags: 
```
CFLAGS="-O1 -ggdb -Wall -Wextra -fsanitize=address -static-libasan -fno-omit-frame-pointer -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --disable-lto --dont-wait --dont-start-it
```
If you prefer you can use the dynamic `libasan`.
3 - Go to directory `/usr/libexec/netdata/plugins.d`
4 - Run `ebpf.plugin` redirecting …
> ebpf memory cleanup

- health/notifications/Makefile.am
- health/notifications/alarm-notify.sh.in
- health/notifications/health_alarm_notify.conf
- health/notifications/opsgenie/Makefile.inc
- health/notifications/opsgenie/README.md
Fixes #9858 
This PR brings the integration between Netdata and Opsgenie.
Health
1 - Require @cakrit access to Opsgenie platform ( I am sorry Chris, but this is the simplest way I know to test this PR).
2 - Access the Opsgenie platform and get the integration key in the following the path: Settings -> Integrations -> Configured Integrations -> API.
3 - Set inside your `health_alarm_notify.conf` the following variables:
```
SEND_OPSGENIE="YES"
OPSGENIE_API_KEY=""
```
4 - Go to directory `/usr/libexec/netdata/plugins.d` and run the following test:
```
./alarm-notify.sh test
```
5 - Access Opsgine platform and click on link `Alerts` you will have alarms like the image
> Opsgenie integration

- Makefile.am
- aclk/aclk_lws_https_client.c
- configure.ac
- daemon/buildinfo.c
- netdata-installer.sh
Allows using system `libwebsockets` instead of one bundled by the installer.
More detailed discussion #8961
If system LWS is used configure will check if the version is recent enough (min `3.2`)
Code has been updated to support up to the latest released LWS at the point of this PR creation (`4.1.4`)
Use configure with `--without-bundled-lws` on system with libwebsockets.
Use configure as normal on system without libwebsockets.
Everything should work as expected and/or appropriate error message should be printed.
Check with `ldd netdata` if output is correct.
> allows use of system libwebsockets instead of bundled one

- health/notifications/alarm-notify.sh.in
- health/notifications/hangouts/README.md
Fixes #9784 
Fixes #9785 
This PR brings a new feature for Hangout notification.
Health
1 - Create a room on Hangout.
2 - Create a webhook.
3 - Inside the room, create a specific thread and copy the link
4 - Configure the `healt_alarm_notify.conf` file :
```
SEND_HANGOUTS="YES"
HANGOUTS_WEBHOOK_URI[Alarms]="https://chat.googleapis.com/v1/spaces/AAAAxxxxxxx/messages?key=XXXXX&token=XXXXX"
#HANGOUTS_WEBHOOK_THREAD[Alarms]="spaces/XXXXXXXXX/threads/YYYYYYY"
DEFAULT_RECIPIENT_HANGOUTS="Alarms"
```
for the first test, we will keep the  variable `HANGOUTS_WEBHOOK_THREAD[Alarms]` commented.
4 - Run the following commands:
```
$ cd /usr/libexec/netdata/plugins.d/
$ ./alarm-notfy.sh test
```
the final result will be:
5 - Uncoment the line …
> Hangout thread

- collectors/statsd.plugin/statsd.c
Fixes #10176
statsd plugin
1) Insert `strcpy(buffer, ":");` in https://github.com/netdata/netdata/blob/master/collectors/statsd.plugin/statsd.c#L693
2) Run `echo "test:1|c" | nc -u localhost 8125`
3) Check if there is no infinite loop.
> Fix an infinite loop in the statsd plugin

- web/api/web_api_v1.c
Stop caching responses from the registry, in order to correctly record machine and person GUIDs
web
Verify that the registry doesn't cache responses (`expires` header is lower than 1 day in the future).
> Don't cache registry responses

- .github/CODEOWNERS
Based on discussion with him, he’s not readily able to review changes here, and the only changes I would be doing can be reviewed by the agent team (or would involve other changes that would pull him in anyway), so there’s not point in having him listed for review on them.
area/ci
n/a
> Remove knatsakis from makefile code ownership.

- collectors/charts.d.plugin/libreswan/libreswan.chart.sh
close #10188
fix for the libreswan plugin parsing of `ipsec trafficstatus` output using sed.
collectors
see steps in issue #10188
\{0,1\} is used instead of ? because standard sed doesn't support "?" https://stackoverflow.com/questions/6156259/sed-expression-doesnt-allow-optional-grouped-string
> fix: make comma optional when parsing ipsec trafficstatus

- aclk/aclk_query.c
- aclk/aclk_stats.c
- aclk/aclk_stats.h
- aclk/mqtt.c
Adds metric showing how long Cloud Query spent sitting in Queue until it got picked up by Query Thread for processing.
Additionally generalizes some code to prevent code duplication.
ACLK
Look at the Charts and smile
> Adds metric showing how long Query spent in Queue

- health/notifications/alarm-notify.sh.in
- health/notifications/health_alarm_notify.conf
- health/notifications/pagerduty/README.md
Fixes #10151 
The main goal of this PR is to use the API V2 that Pager duty, but as we agreed with @Ferroin we are also using this PR to change the indentation used inside the file.
Alarm notify
1 -  Ask @knatsakis to invite you for Pagerduty.
2 - Create a new service.
3 - Get a key for API V2.
4 - Set the variable `DEFAULT_RECIPIENT_PD` 
5 - Go to `plugins.d` directory `cd /usr/libexec/netdata/plugins.d/`
6 - Run the test: `./alarm-notify.sh test`
When I ran the tests, I also kept `telegram`, `slack` and `hangout` enabled, and I received the alarms on all channels.
@knatsakis it was the first time that I worked with `PagerDuty`. I could not see the alarms on the service that I created, but I am  always receiving `202` as you can see
```
*  subject: C=US; ST=California; L=San Francisco; …
```
> Page duty V2

- .github/workflows/build-and-install.yml
The libuv install error that originally prompted disabling them seems to be resolved.
area/ci
CentOS 8 CI checks pass on this PR.
Fixes: #9306
> Re-enable CentOS 8 CI checks.

- .github/workflows/checks.yml
- .github/workflows/review.yml
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ for details on the change.
area/ci
CI checks still pass correctly.
> Remove usage of deprecated GHA syntax.

- netdata-installer.sh
- packaging/installer/netdata-updater.sh
This fixes two issues with our version handling code:
* Due to how `git` handles tags, we can end up with ancient looking version numbers like `v1.11.1-2915-g6106dd7` that are actually quite recent copies of the code (the above example is actually from shortly before the v1.22.0 release). This can be mitigated by ensuring we have up-to-date tags in the local git repository we are building from, and this PR updates `netdata-installer.sh` to do this if it detects that it is running in a `git` repo.
* The version comparison code in the `netdata-updater.sh` script only allows for 3 digits worth of commits in the version string. This works fine, until the installed version is at least 1000 commits beyond the reference tag for the version, at which point it causes the user to get stuck on the …
> Fixed two bugs related to version handling in install and update code.

- collectors/proc.plugin/proc_meminfo.c
Fixes #10153
collectors
Allocate a lot of data on a tmpfs mount-point. Observe available memory going down and used memory going up.
> Move shared memory accounting from "cached" to "used" dimension

- packaging/installer/netdata-updater.sh
**Summary**
Fixes bug in auto-updater for FreeBSD systems (like FreeNAS/TrueNAS) #10198 
The netdata-updater.sh script which is used to automatically check for new versions of Netdata and install them if necessary
did not work in my TrueNAS jail (based on FreeBSD).
Problem is the RANDOM function which does not work in FreeBSD.
Build an extra check if running on FreeBSD system to use another method for the RANDOM function on FreeBSD.
**Component Name**
area/packaging
**Test plan**
Installed an older version of Netdata (v1.25) and ran the 'periodic daily' command to force the daily cron jobs to execute and checked if Netdata was automatically upgraded to latest version (v1.26 at time of writing).
All seemed to work fine.
**Additional Information**
@Ferroin  This is my first PR ever on …
> Fixed bug in auto-updater for FreeBSD (#10198)

- exporting/init_connectors.c
- exporting/send_data.c
- exporting/tests/test_exporting_engine.c
```
** CID 363765:  Null pointer dereferences  (FORWARD_NULL)
/exporting/init_connectors.c: 135 in simple_connector_init()
*** CID 363765:  Null pointer dereferences  (FORWARD_NULL)
/exporting/init_connectors.c: 135 in simple_connector_init()
129             else
130                 current_buffer->next = connector_specific_data->first_buffer;
131     
132             connector_specific_data->first_buffer = current_buffer;
133         }
134     
>>>     CID 363765:  Null pointer dereferences  (FORWARD_NULL)
>>>     Dereferencing null pointer "first_buffer".
135         first_buffer->next = connector_specific_data->first_buffer;
136         connector_specific_data->last_buffer = …
```
> Fix coverity issues

- exporting/prometheus/prometheus.c
- exporting/prometheus/remote_write/remote_write.c
- exporting/send_data.c
When chart filtering is configured for both, the Prometheus Web API and a Prometheus remote write connector instance, the Web API adds charts that are configured in a `prometheus_remote_write` section to its own filter.
Related: #10057
Configure chart filtering for the Prometheus Web API and for a Prometheus remote write connector instance. Check that `http://localhost:19999/api/v1/allmetrics?format=prometheus` doesn't return charts, configured for the Prometheus remote write instance.
> Fix chart filtering

- exporting/prometheus/remote_write/remote_write.c
If `data source = as collected` and there is no data available, Prometheus remote write collector stops with the following error
```
/var/log/netdata/error.log:2020-10-29 13:58:54: netdata ERROR : EXPORTING : EXPORTING: cannot format metric for victoria_metrics
```
The connector should continue processing data instead of exiting.
Fixes #10152
> Don't stop Prometheus remote write collector when data is not available for dimension formatting

- health/health.d/elasticsearch.conf
SSIA. Alarm is wrong - `_local` suffix is a job name 😅 
`health`
Changes are pretty straightforward, there is no need in testing them.
> health: convert `elasticsearch_last_collected` alarm to template

- docs/guides/deploy/ansible.md
This PR adds a new guide for deploying Netdata on any number of nodes using a simple Ansible playbook.
See `ansible-quickstart` in the [community repo](https://github.com/netdata/community/tree/main/netdata-agent-deployment/ansible-quickstart) for the playbook itself!
area/docs
> Add guide: Deploy Netdata with Ansible

- web/gui/dashboard_info.js
Fixes: #10228
ssia
`web/gui`
- use update `dashboard_info.js` file
- check `nvidia_smi` section on the dashboard, ensure new charts are in there and nothing is broken.
Unfortunately i couldn't find appropriate gpu related icon (https://github.com/FortAwesome/Font-Awesome/issues/12990) 😢 
---
@xgdgsc see ^^ Feel free to suggest change/add something.
> add `nvidia_smi` collector data to the dashboard_info.js

- database/rrdset.c
Fixes #9595
database
Start an agent that has tens of thousands of charts in the same host, and measure the time before it's up.
Creating a chart will trigger obsoletion cleanup code whose time complexity is directly proportional to the number of charts in that host. The metadata log replay will create those charts during start-up and come across this delay. This is not evident when there are multiple child-nodes in the multi-host DB where the number of charts is spread equally among them. The worst-case scenario is a single node (parent or child) where ephemeral charts have been generated over time.
> Disable chart obsoletion code for archived chart creation.

- database/rrdhost.c
Fixes a possible endless loop in `rrdhost_cleanup_obsolete_charts`. Should fix #10234.
database
> database: avoid endless loop when cleaning obsolete charts

- streaming/rrdpush.h
- streaming/sender.c
Since #9214 was merged the `buffer size bytes` option didn't work for streaming.
Fixes #10220
streaming
> Fix streaming buffer size

- .github/workflows/docs.yml
- .mlc_config.json
- claim/README.md
I've noticed that the Docs GitHub Action always fails due to failing to check the link `https://pi-hole.net`. There's two problems with this. First, it shouldn't always be checking links in the Pi-hole guide—that's a bug. Second, the link is functional, so I'm choosing to ignore the failure.
area/ci
> Fix Docs GitHub Action with ignore list and update

- packaging/makeself/build-x86_64-static.sh
- packaging/makeself/install-alpine-packages.sh
- packaging/makeself/jobs/50-bash-5.0.install.sh
- packaging/makeself/jobs/50-curl-7.73.0.install.sh
- packaging/makeself/jobs/50-fping-5.0.install.sh
- packaging/makeself/jobs/50-ioping-1.2.install.sh
- packaging/makeself/openssl.version
Update netdata static builds to latest 3rd party versions:
component|old version|new version
---:|:---:|:---:
bash|4.4.18|5.0
openssl|1.1.1g|1.1.1h
curl|7.60.0|7.73.0
fping|4.2|5.0
ioping|1.1|1.2
This version uses latest `alpine` release `3.12`. This version of alpine provides a static version of zlib with the package `zlib-static`, libuv with `libuv-static` and `lz4` with `lz4-static`.
Tested once. It works (dbengine and ACLK).
```
Version: netdata v1.26.0-204-g17db1415a
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--with-bundled-lws=externaldeps/libwebsockets' …
```
> updated 3rd party static dependencies and use alpine 3.12

- claim/README.md
- packaging/installer/UPDATE.md
A mash-up of two small fixes to the docs.
First, a new section to address some [ongoing community feedback](https://github.com/netdata/netdata/issues/9202#issuecomment-712097853) for the `netdata-claim.sh` script not being in the user's PATH.
Second, removing the example `docker run` command from the update page, as it conflicts with the up-to-date examples found in the official Docker installation page. Let's direct users to that page instead of duplicating the command.
area/docs
area/claim
area/packaging
> Remove Docker example from update docs and add section to claim troubleshooting

- collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py
Fixes: #10264
[`pwd`](https://docs.python.org/3/library/pwd.html) is python standard library. But it doesn't allow to set _host_ prefix - that is why we don't want to use it inside a docker container.
This PR changes find username by uid logic to:
- if installed directly on host (env var `NETDATA_HOST_PREFIX` not set): use `pwd`.
- if not: `/etc/passwd` file using custom function that respects `NETDATA_HOST_PREFIX`.
If we fail (both cases): use process `st_uid` (User ID of owner) as username.
`collectors/python.d/nvidia_smi`
> python.d/nvidia_smi: use `pwd` lib to get username if not inside a container

- health/notifications/alarm-notify.sh.in
Fixes #10245 
This PR changes the variable used to reported host inside syslog, previously we were having logs like this:
```
Nov 23 19:56:41 hades thiago: netdata CRITICAL on  at Mon Nov 23 19:56:40 UTC 2020: system.cpu 4.23%
Nov 23 19:56:59 hades thiago: netdata CRITICAL on  at Mon Nov 23 19:56:58 UTC 2020: system.cpu 7.12%
Nov 23 19:56:59 hades thiago: netdata CRITICAL on  at Mon Nov 23 19:56:58 UTC 2020: system.cpu 18.3%
```
After the fix we start to have the expected logs for `parent` and `child`:
```
Nov 23 20:13:26 hades thiago: netdata CRITICAL on zeus at Mon Nov 23 19:55:09 UTC 2020: mem.available 4%
Nov 23 20:13:33 hades thiago: netdata CRITICAL on zeus at Mon Nov 23 20:13:32 UTC 2020: system.cpu 4.78%
Nov 23 20:13:39 hades thiago: netdata CRITICAL on hades at Mon Nov 23 …
```
> Fix host name when syslog is used

- web/api/web_api_v1.c
When the context param is supplied to the data endpoint the context matched charts available to the localhost. 
This would return results for the parent even if a data query in the form 
`/host/<host>/api/v1/data?context=xxx` 
query was given. 
database
To make the difference stand out select a parent and child that have different cpu core count
- Execute a query for a parent as
- localhost:19999/api/v1/data?context=cpu.cpu&dimension=system
- Execute a query for a child **XX** as
- localhost:19999/host/XX/api/v1/data?context=cpu.cpu&dimension=system
Repeat after applying this PR to notice the difference in the child data query results
> Fixed the data endpoint so that the context param is correctly applied to children

- health/health.d/web_log.conf
Not really a critical event, warning is enough. [Critical scares people](https://community.netdata.cloud/t/web-log-nginx-excluded-requests-web-log-1m-unmatched/504), should use it only if it is really a critical event.
`health/`
Not needed.
> health/web_log: remove `crit` from unmatched alarms

- aclk/aclk_common.c
- aclk/aclk_common.h
- aclk/aclk_query.c
- aclk/aclk_rx_msgs.c
- aclk/agent_cloud_link.c
- aclk/agent_cloud_link.h
- claim/claim.c
- database/rrd.h
- database/rrdhost.c
- database/rrdset.c
- streaming/receiver.c
- streaming/rrdpush.c
- web/api/web_api_v1.c
Implements messages which indicate the availability of children to the Cloud.
New messages implemented:
`child_connect` - indicates a child connected to the node sending the message. This is the equivalent of agent connecting on MQTT
`child_disconnect` - clear from the name
Additionally, popcorning is started (which is now per host), and `connect` payload is sent to Cloud upon timer expiration.
Agent/ACLK
Test with streaming setup. Tested with 3 layered set up during development. Listen for messages mentioned above and check their validity
> ACLK Child Availability Messages

- database/rrd.h
- database/rrddim.c
- health/health.c
- web/api/exporters/shell/allmetrics_shell.c
- web/api/formatters/json_wrapper.c
- web/api/formatters/rrd2json.c
- web/api/formatters/rrdset2json.c
- web/api/queries/query.c
Remove the race condition that has been in the code for a very long time. It could be causing random issues to users that are not reproducible.
> Fix race condition in rrdset_first_entry_t() and rrdset_last_entry_t()

- CONTRIBUTING.md
This also removes mention of the WIP check that we are planning to stop using and corrects a grammar error in a nearby sentence.
n/a
n/a
Based on discussion on Slack within the agent team and general support for getting rid of the buggy WIP CI check.
> Updated contributing guidelines to suggest use of Draft PRs.

- exporting/send_data.c
Move variable declaration out of ifdef, it is not https specific.
Fixes #10278
Core
Compile with https disabled (--enable-https=no)
> Fix compilation with https disabled. Fixes #10278

- collectors/python.d.plugin/alarms/alarms.conf
- collectors/python.d.plugin/python_modules/bases/charts.py
`alarms` collector has no charts after init/check.
As a result i get
```cmd
2020-11-30 17:30:50: netdata ERROR : PLUGINSD[python.d] : requested a BEGIN on chart 'netdata.runtime_alarms_local', which does not exist on host 'pc'. Disabling it. (errno 9, Bad file descriptor)
```
---
runtime chart is being created right after `check` and only if there are any charts 
https://github.com/netdata/netdata/blob/95407a625c6a55f157cdf8b0e59096d178098d41/collectors/python.d.plugin/python_modules/bases/FrameworkServices/SimpleService.py#L136-L178
https://github.com/netdata/netdata/blob/95407a625c6a55f157cdf8b0e59096d178098d41/collectors/python.d.plugin/python_modules/bases/charts.py#L43-L48
`collectors/python.d/`
> python.d: always create a runtime chart on `create` call

- aclk/aclk_common.h
- aclk/aclk_query.c
- aclk/aclk_query.h
- aclk/aclk_rx_msgs.c
Enables querying children in ACLK Protocol v3 by their GUID.
ACLK
Connect agent to your own broker. Send `http` messages to query data. Try for master and try for child with `/host/[GUID]/api/v1/info/data?`
If you can emulate `hello` response with `version` message. Otherwise you can build agent modified with `ACLK_VERSION_MIN 3` and thus forcing v3 to agent.
> ACLK allow child query

- aclk/aclk_rx_msgs.c
@kaskavel reported on latest master UUID_STR_LEN is undefined on MacOS.
For some reason `uuid.h` doesn't define this on MacOS.
He also tested the fix on MacOS machine.
ACLK
> fix UUID_STR_LEN undefined on MacOS

- database/engine/rrdengine.c
- database/engine/rrdengine.h
- database/engine/rrdenginelib.h
Choose a big enough time period in the netdata dashboard and create a snapshot.
Measure disk I/O and time to completion. Compare with the code in master.
You can measure disk I/O reads before and after the experiment by looking at `/proc/diskstats` and subtracting the values of the 6th column. Those are 512-byte sectors.
- The typical netdata query will only fetch 1 dimension from disk for a specific chart.
- Subsequent queries will fetch the rest of the dimensions.
- As a result, the extents will be read from disk multiple times.
A small extent cache will speed this up.
> dbengine extent cache

- collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py
`nvidia-smi` sometimes returns _Unknown_ as a fan speed, we need to filter all values which are not numbers.
Fixes: #10311
- ✅ install this PR, ensure `nvidia_smi` works.
> python.d/nvidia_smi: fix gpu data filtering

- collectors/python.d.plugin/varnish/README.md
- collectors/python.d.plugin/varnish/varnish.chart.py
The current Varnish collector is only able to collect metrics from the **SMF** (File) and the **SMA** (Malloc) storages. This pull request is adding support for the [**MSE** (Massive Storage Engine)](https://docs.varnish-software.com/varnish-cache-plus/features/mse/) from Varnish-Plus.
I have also renamed some variables/functions to make them more generic, and updated the documentation.
Related to #9657
Affected component: Varnish collector (python.d plugin)
I have tested the change in Varnish-Cache 6.4.0 (Free version) and Varnish-Plus 6.0.6r10 (Commercial/Enterprise version).
Anyway, the change should not break the compatibility with previous versions.
I have just added the prefix `MSE` as a valid one for containing Storage metrics.
Example of MSE stats returned in `varnishstat -1`:
``` …
```
> Added support for MSE (Massive Storage Engine) in Varnish-Plus

- database/engine/rrdengine.c
```
CC       database/engine/metadata_log/metadatalogapi.o
database/engine/rrdengine.c: In function 'read_extent_cb':
database/engine/rrdengine.c:296:23: warning: 'uncompressed_payload_length' may be used uninitialized in this function [-Wmaybe-uninitialized]
296 |                 (void)memcpy(xt_cache_elem->pages, uncompressed_buf, uncompressed_payload_length);
|                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
dbengine
> Fix a compilation warning

- health/health.d/apps_plugin.conf
The alarm and `fdperc` chart variable were added in https://github.com/netdata/netdata/pull/10192
However it seems buggy, see #10327
Unfortunately we have no time to fix and i think we need to disable it to not get into the release (wrong `crit` level alarm).
`health/`
Nothing to test.
> health: disable 'used_file_descriptors' alarm

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
- packaging/installer/netdata-updater.sh
This makes a number of changes to the updater to make it more user-friendly and more generally robust, including:
* If the installer is not where we expect it to be and there is _exactly_ one directory in the location we expected the installer to be, try changing to that directory and running it from there. This should fix #9863, as well as related issues with new installs.
* Each time the updater is run, check if a newer version exists in the repo, and if so download that and run it instead of using the current updater code. This will allow automatic recovery from a wide variety of bugs that may show up in the updater (especially since it runs very early in the update process). The actual check involves making a call to GitHub’s API to check the commit date on the master branch for the …
> Made the update script significantly more robust and user friendly.

- exporting/read_config.c
- exporting/tests/test_exporting_engine.c
- web/api/exporters/allmetrics.c
- web/api/tests/valid_urls.c
- web/api/tests/web_api.c
The `prefix` and `send names instead of ids` options didn't work in the `prometheus:exporter` section of `exporting.conf`. The options should also inherit values from the `backend` section of `netdata.conf` if they are not set in `exporting.conf`. The PR fixes the issue.
exporting engine, Web API
Check the `http://localhost:19999/api/v1/allmetrics?format=prometheus` endpoint with different settings of `prefix` and `send names instead of ids` in `exporting.conf` and `netdata.conf`.
> Fix exporting config

- netdata-installer.sh
Patch the LWS sources on macOS to work around an error encountered during the build.
area/packaging
Build tested locally by running the modified script directly on a mac Mini.
Fixes: #10297
> Added patch to build LWS properly on macOS.

- exporting/read_config.c
A bug was introduced in #10323 - metric names in http://localhost:19999/api/v1/allmetrics?format=prometheus response miss units and data source (e.g. `netdata_apps_mem` instead of `netdata_apps_mem_MiB_average`). The PR brings back missing backend options.
Fixes #10341
Exporting engine
Do the http://localhost:19999/api/v1/allmetrics?format=prometheus request and check if units and data source are present in metric names.
> Fix backend options

- netdata-installer.sh
- packaging/installer/methods/macos.md
This ensures we get the version from Homebrew instead of the version from XCode.
area/packaging
Without this change, Judy fails to build on macOS, and thus we have no dbengine. With this change, Judy builds correctly, and the dbengine is available.
Fixes: #10325
> Use `glibtoolize` on macOS instead of regular `libtoolize`.

- packaging/installer/install-required-packages.sh
- packaging/installer/methods/manual.md
They appear to have changed DNF to be case-sensitive for repo naming, and the repo name that is expected is all lower case.
area/packaging
Verified through local testing in a CentOS 8 container. Without this change, installing Netdata from sources with `netdata-installer.sh` fails in a clean environment because it cannot install certain required dependencies. With this change, it works correctly.
> Fixed handling of PowerTools repo on CentOS 8.

- .github/workflows/review.yml
- packaging/docker/Dockerfile
- packaging/docker/run.sh
* General cleanup of our Docker entry-point (removed pointless messages and added proper copyright).
* Added hadolint to CI to check our Docker files and fixed any errors it reported.
* Added the ability to automatically claim nodes running the Docker image by specifying claiming parameters in environment variables. Currently uses four variables, all prefixed with `NETDATA_CLAIM_`, one each corresponding to the `-token`, `-url`, `-rooms`, and `-proxy` options for the claiming script. The token and url variables are required for claiming, the other two are optional. Claiming will only be attempted if the node is not already claimed.
* Shuffled some of the layers and changed how we are grouping commands to cut down on the total number of layers and reduce the average number of changed …
> Added numerous improvements to our Docker image.

- netdata.spec.in
CentOS 8 insists on being a pain in the arse and not providing a generic ‘python’ package that pulls in the newest verison, or a generic ‘python3’ package that pulls in the newest version of Python 3.x. As such, we need to special-case it in our RPM spec file.
This also switches dependencies on other platforms to explicitly pull in Python 3.
area/packaging
Build tested locallyin a CentOS 8 container.
> Fix handling of Python dependency for RPM package.

- packaging/installer/netdata-updater.sh
There’s a bug in the code used to locate the script itself (used for determining whether to self-update or not) that causes either an infinite loop or an immediate failure to run right after invoking the script depending on how it’s invoked.
Also fixes a typo in one of the option names.
area/packaging
Same testing regimen as #10261, which now seems to correctly fail for the broken code now. When the timestamp is explicitly overridden it should get stuck in an infinite loop _after_ checking for a new version of the updater script (because it will pull the version with the bug).
Fixes: #10351 
Not sure how this made it past manual testing. Checking now it seems to not work correctly at all (gets stuck in an infinite loop), and looking back at the code it was obviously broken from the start. …
> Fixed handling of self-updating in updater script.

- .github/workflows/docker.yml
This will make us more forward-portable, simplify eventual migration to GHA for release builds, and make it trivial to set up pushing images to multiple registries.
area/ci
Checks pass on this PR.
This is essentially a quick and easy investment in making life simpler when we finally get the whole release workflow migrated to GitHub. It aligns our workflow with BCP for handling of building Docker images in GHA, which will make any troubleshooting much easier. It unfortunately increases run times for Docker CI checks (and will significantly increase run times for actual image builds), but IMO that is an acceptable trade-off for significantly easier maintenance, better consistency of our builds, and the ability to leverage buildx (which will eventually let us shrink our Docker images …
> Switch to using official Docker actions for GHA CI.

- packaging/docker/build.sh
Our actual usage of the image was never actually correct, it just happened to work up until some recent changes were made.
area/ci
Docker builds all pass at: https://travis-ci.org/github/Ferroin/netdata/builds/748782070
> Fixed use of multiarch/qemu-user-static image for Docker builds.

- collectors/python.d.plugin/varnish/README.md
- collectors/python.d.plugin/varnish/varnish.chart.py
Currently, for each of the Varnish Storages (SMF, SMA, or MSE) we are only providing the free and allocated space in KiB. This Pull Request is also adding a new graph with the number of allocated/stored objects within each storage.
Affected component: Varnish collector (python.d plugin)
I have tested the change in Varnish-Cache 6.4.0 (Free version) and Varnish-Plus 6.0.6r10 (Commercial/Enterprise version).
The new added field `g_alloc` is available [at least from Varnish 5.0](https://varnish-cache.org/docs/5.0/reference/varnish-counters.html#per-malloc-storage-counters-sma).
This is an example of the new graphs for the `s0` and `Transient` (SMA) storages:
> Added number of allocated/stored objects within each Varnish storage

- collectors/python.d.plugin/anomalies/anomalies.chart.py
Following some discussion here: https://community.netdata.cloud/t/collector-anomalies-error-on-loading-source/581/11
The underlying python libraries, mainly numpy and sklearn can sometimes generate warnings for numerous, typically transient reasons relating to some quirk of the underlying data. For the purpose of the anomalies collector they don't really matter as worst case you would end up with the predict step failing and your predictions just becoming a constant values of last successful prediction and charts would just become flat lines making it obvious something is wrong. 
So warnings like this are expected to pop up every now and then from individual charts/models. 
For the most common and harmless ones we explicitly suppress them in the collector code itself so as to avoid risk …
> add two more insignificant warnings to suppress in anomalies collector

- collectors/python.d.plugin/alarms/alarms.chart.py
This PR:
- adds alarms obsoletion (remove alarms from the `alarms` chart).
- improves collector performance (`dimID in self.charts[chartID]` is very inefficient).
- disables collector by default.
That is what i noticed on one of our k8s nodes:
I checked number of dimensions in the `alarms` chart and it had 800+.
@andrewm4894 since we are about to release new version i suggest to disable it by default for now.
`python.d/alarms`
- run new version of `alarms.chart.py`, ensure it works.
> python.d/alarms: add alarms obsoletion and disable by default

- collectors/python.d.plugin/alarms/alarms.chart.py
Fix bug introduced in #10375
Any additional metrics should be added to `data` after `update_charts` method call.
Bug is adding `alarms_num` to the chart in first loop and remove in 2nd 😅 (should have tried to run it in the debug mode before merging #10375)
https://github.com/netdata/netdata/blob/6e0b9c97bafdd1bda8e501792c608da8d5328220/collectors/python.d.plugin/alarms/alarms.chart.py#L59-L71
`python.d/alarms`
> python.d/alarms: fix sending chart definition on every data collection

- exporting/clean_connectors.c
- exporting/exporting_engine.h
- exporting/graphite/graphite.c
- exporting/json/json.c
- exporting/opentsdb/opentsdb.c
- exporting/prometheus/remote_write/remote_write.c
- exporting/read_config.c
- exporting/tests/exporting_doubles.c
- exporting/tests/exporting_fixtures.c
- exporting/tests/test_exporting_engine.c
The `hostname` option in `exporting.conf` doesn't work if it is set in an instance section. It works only in the `exporting:global` section. The PR makes the exporting engine respect both levels of configuration.
Fixes #10339
Exporting engine
Configure the `hostname` option in an instance section. Check if the connector output contains the configured name. The `hostname` is visible in the output of `graphite`, `json`, `opentsdb`, `opentsdb:http`, and `prometheus_remote_write` connectors.
> Fix hostname configuration in the exporting engine

- database/rrd.h
- database/rrddim.c
- database/rrdset.c
Mark a chart as "need to send via ACLK" when a chart is created, has it's direct metadata changed, or a dimension is
added. 
Check if the chart needs to be sent via ACLK when metrics are collected.
database
- Enable cgroups
- Start an agent from the master branch (compile with -DNETDATA_INTERNAL_CHECKS=1)
- Notice the number of `Sending MQTT len=913 mid=438 wq=0 (0-bytes) readq=0: {	"type": "chart" ... `  msgs (**sample**)
- Apply the PR, compile and restart
- Notice the reduced number of `Sending MQTT len=913 mid=438 wq=0 (0-bytes) readq=0: {	"type": "chart" ... `  msgs
The type `chart` messages are individual chart updates
> Fix issue with chart metadata sent multiple times over ACLK

- exporting/opentsdb/opentsdb.c
There is a sporadic lock error if the plaintext OpenTSDB exporting connector is configured.
```
RRDHOST 'futura' should be read-locked, but it is not, at function format_host_labels_opentsdb_telnet() at line 155 of file 'exporting/opentsdb/opentsdb.c' # : Success
```
This PR should fix it.
Exporting engine
> Fix a lock check

- web/server/web_client.c
Fixes a buffer overflow when a server configured to accept only SSL connections from children is sent an unencrypted STREAM command with a large hostname.  The server will try to extract the hostname to report that it use should use SSL.
web
- Force agent to accept only SSL connections from children
- Connect to the agent and send a STREAM command with a large (more that 256 bytes) hostname as in
`STREAM hostname=*very large hostname over 255 characters*`
> Fix a buffer overflow when extracting information from a STREAM connection

- collectors/ebpf.plugin/ebpf.c
Fixes #10393 
This PR initializes variables to avoid crash when `ebpf.plugin` is closed.
`ebpf.plugin`.
1 -    Remove /etc/netdata/ebpf.conf
2 -   Go to plugins directory /usr/libexec/netdata/plugins.d/ and run ebpf.plugin.
3 -   Press CTRL+C to end the application
4-    Repeat The steps 2 and 3 at least 3 times, I never needed more than this to create a core dump. With this PR you should not have it more.
I tested this PR on `Ubuntu 20.04LTS`, the same distribution used by our user. I had problems with `master`, but I did not have more the problem with this PR.
> invalid_addr_cleanup: Initialize variables

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
The existing code is dependent on options specifically for the kickstart script coming before any options to be passed to the installer, resulting in some options being ignored if the were ordered in certain ways.
This fixes the parsing to explicitly parse _all_ options so that we are not dependent on option order.
area/packaging
1. Create a new install of Netdata in a test environment using the kickstart script with the `--disable-telemetry` option (any option that gets passed to the `netdata-installer.sh` script will work).
2. Try to reinstall in the same environment using the kickstart script by adding `--reinstall` to the end of the command you used in step 1 (note, option order is important here, the `--reinstall` _must_ come after the other options).
3. Without this PR, step 2 will …
> Fixed option parsing in kickstart.sh.

- aclk/aclk_query.c
Fixes #10380
When the ACLK connection drops while the agent is running and there is a failed attempt to queue an `on_connect` message
a lock is not properly released and will deadlock the agent. 
ACLK
Reproduce by 
- Simulate outgoing connection failure by blocking traffic to the cloud
- Wait until the connection fails similar to the log entries below (notice the `ACLK failed to queue on_connect command` entry)
```
2020-12-17 03:31:48: netdata ERROR : ACLK_Main : Connection to cloud failed
2020-12-17 03:31:48: netdata INFO  : ACLK_Main : Disconnect detected (0 queued queries)
2020-12-17 03:31:48: netdata ERROR : ACLK_Main : Closing lws connectino due to libmosquitto error.
2020-12-17 03:31:48: netdata INFO  : ACLK_Main : Processing callback LWS_CALLBACK_CLIENT_CLOSED
2020-12-17 03:31:48: …
```
> Fix locking after on_connect failure

- .travis.yml
This prevents it from failing due to missing LXC containers.
area/ci
n/a
> Bump Fedora version for RPM packaging to 32.

- docs/monitor/enable-notifications.md
- docs/monitor/view-active-alarms.md
This PR updates the docs to reflect that there will soon be multiple ways to receive alarm notifications from Netdata that work in parallel.
Should only be merged after first merging the related reference docs.
~~Failure of the **Docs** GHA is expected, as the linked reference docs is not yet live.~~ Reference doc is live, but the check still shows failure since it hasn't run since earlier this week.
area/docs
area/notifications
> Add centralized Cloud notifications to core docs

- collectors/freebsd.plugin/freebsd_getifaddrs.c
> Add Realtek network cards to the list of physical interfaces on FreeBSD

- aclk/agent_cloud_link.c
Since its inception ACLK collector list used hostname instead of guid. However we can have multiple children with same hostname and different guids. This prevents mixups between children.
> ACLK collector list use mguid instead of hostname

- .github/dependabot.yml
This will automatically create PRs to update any GitHub Actions we are using when new versions are published. It is set to check weekly, defaults to limiting such PRs to 3 at a time, and will lable them apprpriately with ‘no changelog’ and ‘area/ci’.
This is intended to reduce the manual overhead of maintaining our CI.
area/ci
n/a
AFAICT, we are already using the most recent versions of all GitHub Actions we are utilizing, so this should have no immediate effect. It’s also not likely to trigger very often, as it’s very uncommon that an action gets updated in a backwards incompatible way and we are only using major versions.
See https://github.com/Ferroin/Roll35/pull/2 for an example of what a PR generated this way looks like (labels will obviously be different, but otherwise the general …
> Added Dependabot config to check for updates for GHA workflows.

- build_external/scenarios/aclk-testing/agent_netdata.conf
- collectors/diskspace.plugin/README.md
- collectors/diskspace.plugin/plugin_diskspace.c
autofs's point is to be mounted on explicit request, and "automatically by netdata" is not one.
diskspace.plugin i guess
Add this to your existing netdata installation and see that autofs mounts aren't always instamounted.
> Exclude autofs by default in diskspace plugin

- packaging/installer/netdata-updater.sh
At least on my raspbian i do not have python but python 3. So Additional check is needed. Also this value `commit_date="9999-12-31T23:59:59Z"` is not valid for `date -d $commit_date`
Updater
Ensure you have only python3 and not python available.
> Qick and dirty fix for #10420

- .remarkrc.js
I was talking to @ilyam8 about the annoyance that our Markdown linter insists on lists having three spaces after the `-`, which is a setting that precedes both of our tenure at Netdata. This PR changes the standard to a single space, which is the most common behavior for developers, so that there's less friction when anyone updates the docs (and less of me nitpicking PRs for Markdown syntax).
Before:
```
-   This is a list.
-   And another one.
```
After:
```
- This is a list.
- And another one.
```
area/docs
> Change linting standard for Markdown lists

- CMakeLists.txt
- Makefile.am
- aclk/aclk_common.h
- aclk/aclk_rrdhost_state.h
- database/rrd.h
Older compilers (PRE C11) will complain:
```
./database/../aclk/aclk_common.h:71: error: redefinition of typedef 'RRDHOST'
./database/rrd.h:7: note: previous declaration of 'RRDHOST' was here
```
The 2011 C standard allows redeclaration of typedef names. 6.7 3 says:
> typedef name may be redefined to denote the same type as it currently does, provided that type is not a variably modified type
This caused error on older systems like CentOS6 with old compiler version, see user reported issue:
Fixes https://github.com/netdata/netdata/issues/10421
ACLK, Build System
Should build on older systems like CentOS 6 (tested)
> Fix for older compilers

- contrib/debian/rules
- netdata.spec.in
Unintentionally broken by #9984. This re-enables cloud support in binary packages.
area/packaging
Without this patch, our binary packages do not have cloud support.
With this patch, they have cloud support again.
Fixes: #10457 
Fixes: #10403 
Apologies to everyone affected by the bug this is fixing that it took so long to fix.
> Fixed bundling of libwebsockets in binary packages.

- backends/backends.c
- backends/backends.h
- exporting/exporting.conf
- exporting/read_config.c
- exporting/tests/test_exporting_engine.c
Fixes #10392
Exporting engine
Set `data source = raw` in the `[prometheus:exporter]` section of `exporting.conf`. Check the output of `http://localhost:19999/api/v1/allmetrics?format=prometheus` - it should not append `_average` to all metrics.
> Fix data source option for Prometheus web API in exporting configuration

- collectors/python.d.plugin/hddtemp/hddtemp.chart.py
Currently the HDD temp plugin reports 0 c when a drive fails to report temp correctly.
changing this to reporting None type resolves this issue and the failures simply leave gaps in the chart.
hddtemp
No tests should be needed.
I have patched this manually on my personal instance and it works as expected
If the original behaviour is preferred for some reason I'd be curious as to why or if there is a better way that doesn't add erroneous data to the chart?
> Change HDDtemp to report None instead of 0

- collectors/python.d.plugin/fail2ban/fail2ban.chart.py
1. `enable = yes` is handled by fail2ban, so we shall, too
2. `enable ________          = ________              true` (_ = space, somehow github eats multiple spaces!) is valid, however stupid it looks
python.d/fail2ban.chart.py
The change is trivial, unless there's a syntax error it shall work as intended.
Curiously the 'yes' / 'no' isn't mentioned in the new fail2ban doc but my old files contained such settings and handled.
> python.d/fail2ban: Add handling "yes" and "no" as bool, match flexible spaces

- collectors/apps.plugin/apps_plugin.c
- collectors/cgroups.plugin/sys_fs_cgroup.c
There is excessive information in the titles of apps and group charts. We should truncate it.
apps plugin, cgroups plugin
> Truncate excessive information from titles for apps and cgroups

- packaging/installer/netdata-updater.sh
Currently, when the script auto-updates, it is unable to find the environment file in many cases due to a coding oversight, causing auto-updates to fail due to the automatic updating of the updater script.
This updates the script to pass the environment file path to the updated copy, as well as more robustly looking for the file itself instead of just failing if it was not substituted in during install, which both fixes the script going forwards and allows a significant majority of existing installs to update properly.
area/packaging
The bug can be verified in existing installs by simply trying to update.
The fix can be verified by replacing the updater in a broken existing install with the copy from this PR, and then trying to update again.
Fixes: #10372 
Fixes: #10419 
Fixes: #10444
> Fixed handling of environment file in updater script.

- packaging/installer/netdata-updater.sh
Fixes a (mostly cosmetic) bug introduced by #10384. It was not caught in testing due to insufficient examination of the output in testing.
area/packaging
Observe that the error message reported in #10461 is gone with this PR.
Fixes: #10461
> Fixed function name in updater script.

- collectors/cgroups.plugin/sys_fs_cgroup.c
This is a quick fix for #10285. cgroup discovery will run in a separate thread and won't stop the main thread from collecting metrics and updating charts.
cgroups plugin
1) Start a container that gives you live charts in Netdata
2) Add `sleep 1` to the end of `/usr/libexec/netdata/plugins.d/cgroup-name.sh`
```
fi
sleep 1
info "cgroup '${CGROUP}' is called '${NAME}'"
echo "${NAME}"
exit ${NAME_NOT_FOUND}
```
3) Run with `sudo` the following script
```
#!/bin/bash
CGROUP_PATH="/sys/fs/cgroup/cpu/test"
number_of_containers=10
mkdir "${CGROUP_PATH}"
for i in $(seq 0 9)
do
echo "create cgroups, step ${i}"
seq_boundaries="$((i * number_of_containers + 1)) $((i * number_of_containers + number_of_containers))"
for j in $(seq ${seq_boundaries}); do mkdir "${CGROUP_PATH}/${j}"; done
echo "sleep..." …
```
> Dispatch cgroup discovery into another thread

- health/health.d/mdstat.conf
Fixes #10247
`mismatch_cnt` doesn always mean there is a problem. 
From [the serverfault conversation](https://serverfault.com/questions/885565/what-are-raid-1-10-mismatch-cnt-0-causes-except-for-swap-file/885574#885574):
```
Often, two reasons are given for high mismatch_cnt on a RAID1/10 array:
- swap on the array
- very fast file creation/writing/rewriting/deletion workloads
The above reason are harmless: while they do point to differences in the array (basically, a de-synchronized array), they are about unused disk space.
```
Current condition is too sensitive and [the alarm goes off during resyncing a raid](https://github.com/netdata/netdata/issues/10247#issue-744722823) (_very fast file creation/writing/rewriting/deletion workloads_ case).
---
This PR changes alarm condition and …
> health: make mdstat_mismatch_cnt alarm less strict

- docs/export/external-databases.md
PostgreSQL doesn't support Prometheus remote write natively. [PostgreSQL Prometheus Adapter](https://github.com/CrunchyData/postgresql-prometheus-adapter) can be used to export metrics to PostgreSQL.
Fixes #10485
Exporting engine documentation
> Mention PostgreSQL Prometheus Adapter in the documentation

- collectors/python.d.plugin/chrony/README.md
- collectors/python.d.plugin/dns_query_time/README.md
- collectors/python.d.plugin/dnsdist/README.md
- collectors/python.d.plugin/dockerd/README.md
- collectors/python.d.plugin/dovecot/README.md
- collectors/python.d.plugin/elasticsearch/README.md
- collectors/python.d.plugin/energid/README.md
- collectors/python.d.plugin/go_expvar/README.md
- collectors/python.d.plugin/hpssa/README.md
- collectors/python.d.plugin/logind/README.md
This PR adds instructions to the few collectors that are explicitly disabled on how users can enable them. Based on feedback on the community forum: https://community.netdata.cloud/t/where-does-chrony-monitoring-show-up/559/4
I also noticed an error in some of code comments, which I fixed in this PR.
area/docs
> Add instructions on enabling explicitly disabled collectors

- web/api/queries/stddev/stddev.c
Tunes the memory allocation when computing stddev. More memory is allocated than required -- 
the extra `entries * sizeof(LONG_DOUBLE))` is not used.
The stddev is computed only with the allocated variables in the 
`grouping_stddev` structure
database
- Run a query with group=stddev
> Fix memory allocation when computing standard deviation

- packaging/makeself/install-or-update.sh
- packaging/makeself/jobs/50-curl-7.73.0.install.sh
We should not be hard-coding the CA file or messing with cURL options to handle this, but should instead be relying on the config detected at setup time for the install to just get it right (as it will in 99% of cases).
area/packaging
Observe that cURL works correctly in the resultant images.
Fixes: #10359 
Fixes: #10463
> Fixed handling of TLS config so that cURL works in all cases.

- database/rrdset.c
Fix heap-use-after-free due to the chart using netdata_config memory for some strings.
health
database
Run with `valgrind --track-origins=yes -s /usr/sbin/netdata -D` or use address sanitizer.
Stop the agent with control - C and observe the [logged error](https://github.com/netdata/netdata/issues/10496#issue-784875612).
Check again with this PR, the error should go away.
> Fix segmentation fault in the agent

- database/rrd.h
- database/rrdlabels.c
- database/rrdset.c
- libnetdata/simple_pattern/simple_pattern.c
- libnetdata/simple_pattern/simple_pattern.h
- web/api/formatters/json_wrapper.c
- web/api/web_api_v1.c
When a data query with context is used, support `chart_label_key` with multiple labels instead of just one. Only one of the keys needs to exist for the query to succeed. 
Keys that do not exist will return a null result set. 
example
executing a query with `chart_label_key=key1,key2,key_not_found`
will return 
``` 
"chart_labels":  { "key1": ["val1", "val2"], "key2": ["val3", "val4"] , "key_not_found": [null, null] } 
```
database
- Test on an agent with label support that monitors K8S 
- Execute a data query to a known `context` with charts that have labels e.g. something like
- api/v1/data?context=target_context&after=-600&option=jsonwrap&chart_label_key=key1,key2
- You should see 
- `"chart_labels": ` in the json header for both keys
> Support multiple chart label keys in data queries

- daemon/unit_test.c
- database/engine/rrdenginelib.c
Since the introduction of multi-host DB and SQLite metadata the 3 `dbengine` tests (`unittest`, `createdataset`, `stresstest`) have been broken, some more than others.
dbengine
Run:
```
/usr/sbin/netdata -W stresstest=10,1,1,0,64,256
```
See that it works now.
> Fix broken dbengine stress tests.

- claim/netdata-claim.sh.in
Due to various network conditions claiming can fail. This is problem especially if run automatically trough Docker etc. where user just manually running script again is no go.
This implements retry independent of retry logic of wget/curl and common for them.
Me and bash are not best of friends :) so feel free to make alternative PR/proposal. This was supposed to quick & dirty do this for testing purposes.
Claiming
Block port temporarily and then unblock it.
> Claiming retry/backoff

- .travis/package_management/common.py
- netdata.spec.in
Also cleans up the configure statement in the RPM spec file.
area/packaging
area/ci
Verified locally for CentOS 7 and 8, Fedora 32 and 33, and OpenSUSE 15.1 and 15.2 by building in Docker containers.
This also coincidentally fixes a bug introduced by #10460 that is causing RPM package builds to consistently fail.
We unfortunately cannot do this for DEB packages yet due to the fact that the Debian and Ubuntu environments provide versions of LWS that are too old.
> Switched to using system libwebsockets for RPM builds.

- daemon/unit_test.c
Adds a check to avoid coverity complain on a possible division by zero
database
unit_test
- Running stress test should not finish in 0 time and trigger a div by zero (which doesn't actually)
- netdata -W stresstest=1,1,1,0,64,256
> Fix coverity issue CID 365322

- health/health.d/mysql.conf
Fixes: #10427
python mysql version:
- `1`: slave_sql_running/slave_io_running == `YES`
- `-1`: any other value.
go mysql version:
- `1`: slave_sql_running/slave_io_running == `YES`
- `0`: any other value.
`health/`
The changes are trivial.
> health/mysql: fix `mysql.slave_status` alarm for go mysql collector

- health/health_log.c
Send alarm updates only if the new or old status is warning or critical. 
aclk
health
- Compile agent with `-DNETDATA_INTERNAL_CHECKS=1` and cloud support. This will record and `Sending MQTT` messages as well as the PUBACK messages in the log file e.g. 
`ACLK_Query_4 : Sending MQTT len=1121 mid=534 wq=0 (0-bytes) readq=0: {	"type": "status-change"`
`ACLK_Main : Publish_callback: mid=5 latency=158ms`
**Note:**  A `status-change` message refers to an alarm status update
- Start the agent and notice the total of PUBACKS as the agent initializes. 
- Apply the PR, recompile and observe the reduced number of messages (PUBACKS)
> Reduce the number of alarm updates on ACLK

- collectors/python.d.plugin/postgres/postgres.chart.py
- collectors/python.d.plugin/postgres/postgres.conf
Fix bug on postgres collector where a `None` password was output as `*****` to the user. 
Add default password to default configuration, so that netdata can collect from containerised postgresql instances, as the no-password `trust` configuration doesn't work for non-local connections.
- Run Postgres in container and see that it automatically connects to the instance.
- Comment-out the configuration jobs that contain the password and see that the debug trace outputs `password: None`
> fix postgres password bug and change default config

- .travis.yml
The cURL command was missing an authorization header and one component in the URL.
area/ci
Manually verified the new command.
The problems here are a result of oversight on my part when preparing #10365.
Relevant GitHub API documentation: https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
The above docs do not explicitly call out the `Auhorization` header requirement, and I cannot seem to find it clearly documented anywhere else, but it is needed by the API.
> Fixed triggering of Docker image builds from Travis.

- packaging/installer/netdata-updater.sh
We should have been using the saved `TMPDIR` value as a prefix for a temporary directory, but where using it directly. This resulted in errors in the updater.
area/packaging
Verify that the custom temporary directory is not removed by the script on the first run of the updater.
Fixes: #10536
> Properly handle saved temporary directory on updates.

- exporting/prometheus/prometheus.c
- Keep values, collected by the Prometheus collector, unchanged in `as-collected` mode.
- Reduce code duplication for string generation in `as-collected` mode.
Fixes #10549
Web API
Enable the go.d Prometheus collector. Check if values of its metrics are correct floating-point numbers in `http://localhost:19999/api/v1/allmetrics?format=prometheus&source=raw`. Check if other exported metrics aren't broken.
> Fix values in Prometheus export for metrics, collected by the Prometheus collector

- exporting/prometheus/remote_write/remote_write.c
- exporting/tests/test_exporting_engine.c
When exporting metrics using the Prometheus remote write connector to TimescaleDB via Promscale, it refuses to accept the data:
```
level=error ts=2021-01-15T06:20:50.557Z caller=write.go:239 msg="Write header validation error" err="unsupported data format (not protobuf or json)
```
The header [should contain](https://github.com/timescale/promscale/blob/7581d0430fc97d0149fc864fcd0df0228271ce2a/pkg/api/write.go#L101) `Content-Type: application/x-protobuf` for exporting to work correctly.
Fixes #10537
The Prometheus remote write exporting connector
1. Run Promscale [in a container](https://github.com/timescale/promscale/blob/master/docs/docker.md#-running-docker).
2. Configure Netdata to export metrics using Prometheus remote write
``` …
```
> Fix prometheus remote write header

- aclk/legacy/agent_cloud_link.c
JSON parser at the cloud end reports error if anything is behind the last '}' of JSON message. This caused cloud to throw away graceful `disconnect` messages.
TEST 1:
Compile with `ACLK_DISABLE_CHALLENGE` point to your own broker. Subscribe to `meta` topic and listen for `disconnect` message sent when agent is shutting down. Hexdump that message and verify '}' is the last byte (no invisible characters after it)
TEST 2:
this should properly clear alarms on cloud
> bytes after last '}' trip JSON parser

- .github/workflows/build-and-install.yml
- .travis.yml
Intended to be merged on or after 2020-01-30 when it officially becomes EOL.
area/ci
n/a
> Remove OpenSUSE Leap 15.1 from CI.

- .github/workflows/build-and-install.yml
- .github/workflows/checks.yml
Alpine 3.13 was released on 2021-01-14
Alpine 3.9 went EOL on 2020-11-01
This also bumps an old Alpine 3.11 reference to use the lastest stable Alpine image.
area/ci
New checks pass correctly.
> Add Alpine 3.13 and remove Alpine 3.9 from our CI.

- netdata.spec.in
This fixes an incorrect configure option in our RPM package which has been causing cloud support to not work on platforms where we can’t use a native copy of libwebsockets.
area/packaging
Option name verified against our configure script.
Actual resultant build tested for CentOS 8 and OpenSUSE Leap 15.2 locally by verifying cloud support using `netdata -W buildinfo`.
Fixes the attempt at fixing this from #10507, orginally attempted to be fixed with #10460, with the bug originally introduced by #9984.
Relevant to #10403 and #10457.
> Fixed Netdata Cloud support in RPM packages.

- .travis.yml
They were being incorrectly tagged using the stable build tags.
area/ci
Re-checked locally.
> Fixed docker image tagging for nightly builds.

- collectors/cgroups.plugin/sys_fs_cgroup.c
Fixes #10611
collectors
Compile netdata in Alpine Linux 3.12 with musl libC. Observe crash during shutdown if the `cgroups` collector is enabled. This PR should not crash in that scenario.
> Fix crash during shutdown of cgroups internal plugin.

- .github/workflows/docker.yml
- .travis.yml
This fixes the handling of docker image tags for release bilds, ensuring that we actually get the current version of the repo correctly so that we don’t overwrite older images.
It also fixes the default value for the version parameter for the workflow that actually does the builds.
area/ci
> Fixed handling of Docker image tags for release builds.

- claim/README.md
This adds information about claiming Docker containers using environment variables (the currently preferred claiming method) and removes info about invoking the claiming script by passing options for the agent to the `docker run` command.
area/docs
n/a
Based on discussion with @manos-saratsis.
The diff is a bit disjoint because of how `git`’s diff algorithm works, the changes are really a lot less complicated than they look.
> Update claiming docs for Docker containers.

- aclk/legacy/aclk_lws_wss_client.c
Reduce the amount of logging from ACLK transport layer if not explicitly wanted (e.g. when debugging).
ACLK
There should be fewer logs.
> ACLK reduce excessive logging

- health/health_json.c
On agent startup if an alarm is found in REMOVED state without an updated entry and the old status
is WARN/CRIT then submit the update so the cloud can clear the alarm (if still on the list)
aclk
- Setup a cloud enabled and claimed agent so that it will trigger the following alarm
- Enable something like `/sys/class/power_supply = yes` in the netdata conf
- Change 
```
template: linux_power_supply_capacity
on: powersupply.capacity
calc: $capacity
units: %
every: 10s
warn: $this < 100
crit: $this < 5
delay: up 30s down 5m multiplier 1.2 max 1h
info: the percentage remaining capacity of the power supply
to: sysadmin
```
so that it will cause a warning
- Check that you see the warning in the cloud and local dashboard
- Stop the agent and disable  `/sys/class/power_supply = no`
- Start the …
> Allow the REMOVED alarm status via ACLK if the previous status was WARN/CRIT

- collectors/apps.plugin/apps_groups.conf
Add freeswitch to apps_groups.conf to regroup [freeswitch servers](https://en.wikipedia.org/wiki/FreeSWITCH) under its own value and not as "others"
collector / apps.plugin
Freeswitch processes includes `freeswitch` and `freeswitch-license-server`
> add freeswitch to apps_groups

- collectors/proc.plugin/sys_kernel_mm_ksm.c
Fixes: #3327, see the issue for details. Thx to @jacekkolasa our dashboard now supports negative values on stacked charts.
ssia
Suggested by @Ferroin
`collectors/proc`
Not needed
> collectors/proc: change ksm mem chart type to stacked

- collectors/python.d.plugin/elasticsearch/README.md
Document the `scheme` option of the elasticsearch collector.
`collectors/python.d/elasticsearch`
N/A - this is a documentation change
Introduced option in config file example in #5834
> collectors/elasticsearch: document `scheme` option

- health/health_config.c
- libnetdata/libnetdata.c
Fixes #8641 
This PR brings new option to disable stock alarms when it is necessary.
@underhood I am bringing a fix that you requested, but it is necessary to clarify something, I had a request from to @ktsaou to avoid `negative` variables inside our configuration files as you suggested, so I had to change the variable name.
Health
1 - Edit your `netdata.conf`
``` 
[health]
enable stock health configuration = yes
```
2 - Compile this branch
3 - Start Netdata and confirm that all alarms are present using the request `http://localhost:19999/api/v1/alarms?all`.
4 - Stop Netdata ans change the new variable ( `enable stock health configuration = yes` )
5 - Start Netdata and do another request `http://localhost:19999/api/v1/alarms?all`, this time only alarms listed at `/etc/netdata/health.d` …
> Disable stock alarms

- aclk/legacy/aclk_common.c
- aclk/legacy/aclk_common.h
- database/rrdhost.c
Add ACLK proxy setting as label.
ACLK
Set different ACLK proxies and check `/api/v1/info`
> Add ACLK proxy setting as host label

- collectors/python.d.plugin/adaptec_raid/README.md
- collectors/python.d.plugin/hpssa/README.md
- collectors/python.d.plugin/megacli/README.md
- collectors/python.d.plugin/samba/README.md
Fixes: #10079
Fixes: #10430
Related #10201
We had a lot of issues with collectors that use `sudo` since we [hardened](https://github.com/netdata/netdata/pull/9234) our netdata systemd unit file.
Affected python collectors:
- [adaptec_raid](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/adaptec_raid)
- [hpssa](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/hpssa)
- [megacli](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/megacli)
- [samba](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/samba)
To make them working by defaul we need to add `CAP_SETGID`, `CAP_SETUID` and some others i am not aware of (perhaps specific per a collector). If i understand it correctly we don't want to add …
> add resetting CapabilityBoundingSet workaround to the python.d collectors (that use `sudo`) readmes

- daemon/get-kubernetes-labels.sh.in
Fixes: netdata/product#1800
This PR extends [`get-kubernetes-labels.sh`](https://github.com/netdata/netdata/blob/master/daemon/get-kubernetes-labels.sh.in) script.
In addition to the pod labels it adds `k8s_cluster_id` label. Its value is kube-system namespace uid (immutable, not configurable by a user, unique value).
Now script does two http requests:
- `https://$HOST/api/v1/namespaces/$MY_POD_NAMESPACE/pods/$MY_POD_NAME`
- `https://$HOST/api/v1/namespaces/kube-system`
In case of any problems during http requests or during parsing responses it exits with code `1` and writes an error message to stdout.
```cmd
bash-5.0# ./get-kubernetes-labels.sh
app:netdata
controller-revision-hash:55d85f8f6b
pod-template-generation:7
release:netdata
role:child …
```
> add k8s_cluster_id host label

- health/notifications/alarm-notify.sh.in
Fixes: #10630
Netdata's docker image `sendmail` has not `-F` option.
<details>
<summary>sendmail -F output click click </summary>
```cmd
[ilyam@pc ~]$ docker exec -it lucid_kilby netdata -v
netdata v1.29.1
[ilyam@pc ~]$ docker exec -it lucid_kilby sendmail -F
sendmail: unrecognized option: F
BusyBox v1.31.1 () multi-call binary.
Usage: sendmail [-tv] [-f SENDER] [-amLOGIN 4<user_pass.txt | -auUSER -apPASS]
[-w SECS] [-H 'PROG ARGS' | -S HOST] [RECIPIENT_EMAIL]...
Read email from stdin and send it
Standard options:
-t		Read additional recipients from message body
-f SENDER	For use in MAIL FROM:<sender>. Can be empty string
Default: -auUSER, or username of current UID
-o OPTIONS	Various options. -oi implied, others are ignored
-i		-oi synonym, implied and ignored
Busybox specific options: …
```
> fix sendmail unrecognized option F error

- collectors/proc.plugin/proc_net_dev.c
Fixes: #10628
For some reason we don't collect `operstate` (`/sys/class/net/<DEV>/operstate`) for virtual interfaces. This PR fixes it.
`collectors/proc`
Install this PR, ensure virtual interfaces Bandwidth charts contain `operstate` variable.
> collectors/proc: fix collecting operstate for virtual network interfaces

- collectors/apps.plugin/apps_plugin.c
We should print aggregation debug messages when Netdata is compiled without `CFLAGS="-DNETDATA_INTERNAL_CHECKS=1"`.
Fixes #10622
apps.plugin
Run `sudo ./apps.plugin debug 2>&1 | grep "has aggregated"`, you should see target aggregation messages:
```
apps.plugin: target 'netdata' has aggregated 8 processes: 446552 446587 446728 446743 446745 446746 446749 446750
```
> Enable apps.plugin aggregation debug messages

- health/health.d/tcp_resets.conf
Fixes: #9799
As we've figured out in #9799 - a short spike after Netdata restart is expected (OutRsts, AttemptFails).
This PR adds 20s up delay to the following alarms:
- [10s_ipv4_tcp_resets_sent](https://github.com/netdata/netdata/blob/master/health/health.d/tcp_resets.conf#L39)
- [10s_ipv4_tcp_resets_received](https://github.com/netdata/netdata/blob/master/health/health.d/tcp_resets.conf#L64)
`health/`
> add small delay to the ipv4_tcp_resets alarms

- daemon/system-info.sh
Fixes: #10646
`systemd-detect-virt -c` returns `none` if there is no container virtualization. We need to treat `none` as `unknown` later in the code.
`daemon/`
Ensure `/api/v1/info` returns correct info when Netdata Agent installed on the host.
- Current
```cmd
[ilyam@pc ~]$ curl -s http://127.0.0.1:19999/api/v1/info | grep -E '"os_*|"container_*'
"os_name": "unknown",
"os_id": "unknown",
"os_id_like": "unknown",
"os_version": "unknown",
"os_version_id": "unknown",
"os_detection": "unknown",
"container_os_name": "Manjaro Linux",
"container_os_id": "manjaro",
"container_os_id_like": "arch",
"container_os_version": "unknown",
"container_os_version_id": "unknown",
"container": "none",
"container_detection": "systemd-detect-virt",
```
- After this PR
```cmd
[ilyam@pc ~]$ curl -s …
```
> fix container/host detection in system-info script

- netdata.spec.in
The original intent was to only use a static copy of LWS if we couldn’t use a system copy. Due to two incorrect conditionals in the spec file though, what was actually happening was that we were using a static build of LWS on systems where we could use a system copy, and not linking against LWS at all on other systems.
This fixes those conditionals so that we use a system copy if available, and provide a static copy if a system copy is not available.
area/packaging
Verified locally with manual build tests on all platforms we build RPM packages for.
Fixes: #10594
> Fixed condition controlling use of static LWS in RPM builds.

- collectors/proc.plugin/proc_net_dev.c
Fixes #10656
collectors
The net_dev collector of the proc plugin should not reuse health variables after obsoleting the corresponding charts.
> Invalidate RRDSETVAR pointers on obsoletion.

- database/engine/pagecache.c
- database/engine/pagecache.h
- database/engine/rrdengine.c
Try to keep all the pages that belong to an extent in the page cache, whenever an extent is read from disk. This should improve spatial and temporal locality and consequently cache hit ratio. It is expected to improve performance and reduce disk I/O volume.
1. Populate 64MB worth of dbengine history (in `/var/cache/netdata/dbengine`)
2. Zoom out fully in the dashboard.
3. Export a snapshot.
4. Compare read disk I/O before the export and after (See column 6 [here](https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats))
The PR code should do significantly less I/O than the code in master.
> Try to keep all pages from extents read from disk in the cache.

- aclk/legacy/aclk_query.c
- aclk/legacy/aclk_query.h
- aclk/legacy/aclk_stats.c
- aclk/legacy/aclk_stats.h
Adds a cpu usage chart for each query thread.
ACLK
The agent node must be claimed. 
View the agent from the cloud to create queries to the agent.
Observe the charts by e.g. adding load when requesting non visible charts via the cloud.
Observe the charts also on idle.
Query threads are measured only when they are responding to queries.
> cpu stats per query thread

- exporting/prometheus/prometheus.c
There are metrics with the `_total` suffix in the generic Prometheus endpoint collector. We shouldn't duplicate the suffixes on export in the Prometheus format.
Fixes #10669
Prometheus exporting (Web API)
Enable the generic Prometheus endpoint collector.
Check `http://localhost:19999/api/v1/allmetrics?format=prometheus&source=raw`. You shouldn't see any metrics with the `_total_total` suffix.
> Don't add duplicate _total suffixes for the prometheus go.d module

- web/gui/main.js
This PR fixes outdated documentation links in web GUI. Old ones lead to 404 error pages, new ones work as expected.
netdata/web/gui
Examples of old links and their replacements:
- https://docs.netdata.cloud/collectors/quickstart/ vs https://learn.netdata.cloud/docs/agent/collectors/quickstart/
- https://docs.netdata.cloud/health/quickstart/ vs https://learn.netdata.cloud/docs/agent/health/quickstart/
- https://docs.netdata.cloud/changelog/ vs https://learn.netdata.cloud/docs/agent/changelog/
It might be easier to sync netdata/web/gui with [dashboard/src](https://github.com/netdata/dashboard/tree/master/src).
> web/gui: Fix broken external links

- aclk/legacy/aclk_query.c
- aclk/legacy/aclk_query.h
- aclk/legacy/aclk_rx_msgs.c
- aclk/legacy/aclk_stats.c
- aclk/legacy/aclk_stats.h
`http` cloud query can query different `/api/v1/info` endpoints. Add chart counting how many queries of each type have been requested by the cloud.
ACLK
Look at the new charts through the cloud (you need to have through cloud traffic to see anything)
> add stats per cloud query type

- aclk/legacy/agent_cloud_link.c
As TBEB added max of 1s of randomness even for longer off times (e.g. 10 minutes would cause approx 10s spread only) in situations when Cloud disconnected all agents at the same time they will still connect almost at the same time.
This adds bigger randomness up to + half of the raw TBEB delay.
ACLK
> increases ACLK TBEB randomness

- database/engine/rrdengine.c
Add support for changing the number of dbengine pages per disk extent in `netdata.conf`. Also support changing dynamically during runtime.
Play around with `netdata.conf`. Default and maximum value is (Supported range 1-64):
```
[global]
dbengine extent pages = 64
```
You can change it dynamically by executing:
```
netdatacli write-config 'netdata|global|dbengine extent pages|32'
```
You can only observe the difference after a lot of extents have been written to disk, and most of the database files have rotated. Small extents will have significantly larger metadata:data ratio and as a result much smaller retention period (metric history).
You can play around with various workloads and compare performance with default settings (e.g. export a snapshot from the dashboard).
> Add support for changing the number of pages per extent

- registry/README.md
- registry/registry.c
- registry/registry_init.c
- registry/registry_internals.h
Fixes #8094
This PR fixes the problem to access cloud with Netdata.
Webserver
1 - Access Netdata dashboard and verify that you do not have the error `Some cookies are misusing the recommended “sameSite“ attribute 11` using browser developer tools
> Add new cookie to fix 8094

- libnetdata/ebpf/ebpf.c
On CentOS when we compile with libasan `ebpf.plugin` it crashes with the following error:
```
#1 0x51a508 in main collectors/ebpf.plugin/ebpf.c:1903
#2 0x7ff05f5d07b2 in __libc_start_main (/lib64/libc.so.6+0x237b2)
#3 0x40893d in _start (/usr/libexec/netdata/plugins.d/ebpf.plugin+0x40893d)
Address 0x7fff1f60cc10 is located in stack of thread T0 at offset 176 in frame
#0 0x587ae4 in get_kernel_version libnetdata/ebpf/ebpf.c:65
This frame has 4 object(s):
[32, 48) 'major'
[96, 112) 'minor'
[160, 176) 'patch' <== Memory access at offset 176 overflows this variable
[224, 480) 'ver'
```
This is happening because `/proc/sys/kernel/osrelease` has a different pattern, this bug is probably affecting Ubuntu, because both distributions are appending `-` and additional information for the kernel …
> update_kernel_version: Fix overflow on Centos and probably Ubuntu

- collectors/all.h
- collectors/proc.plugin/proc_diskstats.c
- web/gui/dashboard_info.js
The disk backlog and utilization charts displayed wrong data. We fix that and add a chart for disk busy time.
Fixes #10700
diskstats module in proc plugin
> Fix disk utilization and backlog charts

- collectors/freeipmi.plugin/README.md
- collectors/freeipmi.plugin/freeipmi_plugin.c
Fixes #7066
freeipmi plugin
Run the freeipmi plugin with `noauthcodecheck` flag. Check if it works for protocol 1.5.
> Add noauthcodecheck workaround flag to the freeipmi plugin

- .github/scripts/build-dist.sh
- .github/scripts/check-updater.sh
- .github/workflows/updater.yml
Add workflow for installing latest version of netdata, building from source of this branch & running the updater. Add script build-dist to create the artifacts used for the update.
We add a new pipeline, meant to run in PRs and merges to master, that uses the kickstart script to install the latest version of netdata, then checkout the branch of the PR, build netdata and update to this version of the agent. 
Currently the pipeline has been tested for latest Debian and Fedora, more distributions will be added in the near future, along with more checks regarding the updater's behavior.
> Add a new workflow to test that updater works as expected

- .github/scripts/gen-docker-tags.py
- .github/workflows/docker.yml
- packaging/docker/README.md
This allows users to use image names like `netdata/netdata:1` or `netdata/netdata@1.29` and track the most up-to-date release that matches that version prefix.
Such usage is a common practice for projects using semantic versioning like we are.
area/ci
area/packaging
The tag generations cript can be tested locally, it takes a single argument which is a version string as we normally use them (so `vX.Y.Z`) and outputs a list of version tags to push.
Short term, the `1` tag will be functionally identical to the `stable` tag. Long-term, we may eventually end up with a new major version of Netdata, at which point having the `1` tag to let users stick with the old version is important during the transition period.
> Changed Docker image tagging to use semver tags for releases.

- daemon/buildinfo.c
- daemon/buildinfo.h
- daemon/main.c
This adds a variant of the `-W buildinfo` option called `-W buildinfojson` which outputs JSON instead of plain text, allowing for easier parsing and simpler handling in our anonymous statistics reporting.
Sample output (with JSON syntax hilighting):
```json
{
"features": {
"dbengine": "NO",
"native-https": "YES",
"cloud": "NO",
"tls-host-verify": "YES"
},
"libs": {
"jemalloc": "NO",
"jsonc": "YES",
"libcap": "YES",
"libcrypto": "YES",
"libm": "YES",
"lws": "NO",
"mosquitto": "NO",
"tcmalloc": "NO",
"zlib": "YES"
},
"plugins": {
"apps": "YES",
"cgroup-net": "YES",
"cups": "YES",
"ebpf": "NO",
"ipmi": "NO",
"nfacct": "YES",
"perf": "YES",
"slabinfo": "YES",
"xen": "NO",
"xen-vbd-error": "NO"
},
"exporters": {
"kinesis": "NO",
"pubsub": "NO",
"mongodb": "NO",
"prom-remote-write": "YES"
}
} …
```
> Add JSON output option for buildinfo.

- collectors/python.d.plugin/smartd_log/smartd_log.chart.py
Summary
This chart monitor the media wearout indicator  for disks ssd's.
Component Name
area/collectors/python.d.plugin/postgres/smartd_log.chart.py
Test Plan
Tested with multiple servers with and without ssd's.
> python.d/smartd_log: collect attribute 233 (Media Wearout Indicator (SSD)).

- database/sqlite/Makefile.am
- database/sqlite/sqlite_functions.c
The `name` parameter when storing charts in SQLite was not correctly reset (re-bind). This (under certain conditions) could result in additional chart entries being created. 
It could also result in metrics being inaccessible if : 
- A new chart was created instead of being reused
- This would result into a new dimension entry being created and assigned to collect metrics
- Previously collected metrics with a different dimension UUID (due to the duplicate chart) would be inaccessible
Parameter binding should always happen.
database
- With the agent stopped, backup the `netdata-meta.db` file if you don't want to lose data.
- Before patch
- Clear metadata database (/var/cache/netdata/netdata-meta.db)
- Have the `sqlite3` client installed
- Start agent with children connected 
- Connect to …
> Fix a parameter binding issue when storing chart names in the database

- collectors/python.d.plugin/alarms/README.md
- collectors/python.d.plugin/alarms/alarms.chart.py
- collectors/python.d.plugin/alarms/alarms.conf
Add option `show_alarm_values` to `alarms.conf` which will show the alarm values themselves over time below the alarm status chart. 
`show_alarm_values` will be set to `false` by default such that a user would have to explicitly enable this in `alarms.conf` if they want the "Values" chart.
For example: 
/collectors/python.d.plugin/alarms
Tested locally for when both show_alarm_values was `true` and `false` in situations where i used `stress-ng --all 2` to trigger lots of alarms.
> Alarms collector add alarm values

- aclk/legacy/aclk_lws_wss_client.c
minor - remove compile warning if `ACLK_TRP_DEBUG_VERBOSE` not defined:
```
aclk/legacy/aclk_lws_wss_client.c:351:20: warning: 'aclk_lws_callback_name' defined but not used [-Wunused-function]
351 | static const char *aclk_lws_callback_name(enum lws_callback_reasons reason)
|                    ^~~~~~~~~~~~~~~~~~~~~~
```
ACLK
The warning should be gone.
> Removes unused fnc warning in ACLK Legacy

- database/rrdset.c
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
- This PR will create a new database table chart_label if it does not exist
- Store chart labels as they are attached to a chart
The information stored is
- chart_id blob (unique chart UUID)
- source_type int
- label_key text
- label_value text
- date_created (time since epoch)
database
- Start an agent that define chart labels (e.g. k8s cluster)
- Connect to the database via `sqlite3`
- Type `.schema` 
- Observe the new table `chart_label` table
example:
```
fccdbc1e-52c6-411c-b8fa-fb5e27523356,4,container_name,qemu_ubuntu18.04
fccdbc1e-52c6-411c-b8fa-fb5e27523356,4,label,value
c4d3832a-5138-464b-9a2a-11147b0b3e8c,4,container_name,qemu_ubuntu18.04
c4d3832a-5138-464b-9a2a-11147b0b3e8c,4,label,value
902891fb-12dc-4f0c-b3bd-d2c1c242308f,4,container_name,qemu_ubuntu18.04 …
```
> Add the ability to store chart labels in the database

- database/engine/rrdengine.h
- database/rrd.h
This change, which does not change the memory layout of the parent
structs, allows inclusion of daemon/common.h in C++ without relying
on -fpermissive.
agent, database
Built and run locally + CI builds.
> Use of out-of-line struct definitions.

- database/rrdhost.c
Fixes #10684
Always configure a multihost database context when dbengine is compiled
database
- As described in #10684 
- The agent should not crash if
- is compiled with dbengine
- default agent memory mode is ram
- statsd configuration is set to dbengine
> Always configure multihost database context

- collectors/proc.plugin/proc_net_dev.c
- health/health.d/net.conf
- libnetdata/libnetdata.h
To allow alerting on network interface status we are adding new charts for `speed`, `duplex`, and `operstate`. There is no need for `netdata_net_*_duplex` and `netdata_net_*_operstate` host variables so they are deleted.
Fixes #10671
proc plugin
Check `http://localhost:19999/api/v1/allmetrics?format=prometheus_all_hosts&variables=yes`, you should see `netdata_net_*_nic_speed_max` variables but not `netdata_net_*_duplex` and `netdata_net_*_operstate`.
Check for new charts in the dashboard -> Network Interfaces section
```
net_speed.*
net_duplex.*
net_operstate.*
```
> Move network interface speed, duplex, and operstate variables to charts

- packaging/docker/run.sh
The name of the path we are checking was incorrect, which resulted in the check not correctly skipping claiming on startup of containers that are already claimed.
area/packaging
Verified that the check now correctly skips attempting to claim a node that is already claimed.
Credit to @ilyam8 for noticing this bug.
> Fixed detection of already claimed node in Docker images.

- web/gui/dashboard_info.js
SSIA
dashboard
Check in the dashboard if `net.duplex` and `net.operstate` charts have status maps in their info.
> Add state map to duplex and operstate charts

- web/gui/dashboard_info.js
This PR adds [supervisord](https://github.com/netdata/go.d.plugin/tree/master/modules/supervisord#supervisord-monitoring-with-netdata) data collection module icon/description and processes states map to the dashboard_info.
`web/gui`
Install this PR, ensure the dashboard is not broken, ensure there is added info on the dashboard.
> web/gui: add supervisord to the dashboard_info.js

- collectors/cgroups.plugin/sys_fs_cgroup.c
- health/health.d/cgroups.conf
- web/gui/dashboard_info.js
SSIA
Closes #10681
cgroups plugin
Enable detailed memory charts for systemd services
```
[plugin:cgroups]
enable systemd services detailed memory = yes
```
Check `services.mem_working_set` and `cgroup_<cgroup_name>.mem_working_set` charts.
> Add Working Set charts to the cgroups plugin

- collectors/cgroups.plugin/sys_fs_cgroup.c
Fixes: #10670
> cpuset.cpus
> specifies the CPUs that tasks in this cgroup are permitted to access. This is a comma-separated list, with dashes ("-") to represent ranges.
`collectors/cgroups`
Tested the following combinations:
| cpuset.cpus   | limit in netdata   |
| :-----------: | :----------------: |
| 5             | 100                |
| 0,2,5         | 300                |
| 2-5           | 400                |
| 0,1-3,5       | 500                |
| 0-1,2,3-5     | 600                |
| 0-1,2-5       | 600                |
> collectors/cgroups: fix cpuset.cpus count

- health/health_log.c
Fixes #10522 
This PR is a copy from the original PR #10559, because the user could not sign the CLA. A more detailed description about this fix was given from user [here](https://github.com/netdata/netdata/issues/10522#issuecomment-767881289).
health
1 - Compile this Branch.
2 - Change a line inside your `/var/lib/netdata/health/health-log.db` to have less values than expected.
3 - Start Netdata.
4 - Verify if there is the warning `..should have at least 27 entries, but it has..` inside your `/var/log/netdata/error.log`.
5 - Now access `http://localhost:19999/api/v1/alarm_log` and check that all log were loaded.
> Fix wrong count for entries

- contrib/debian/netdata.postinst
- contrib/debian/rules
- netdata-installer.sh
- netdata.spec.in
* Removed pointless capabilities in our RPM spec file.
* Shifted slabinfo and perf plugins to use proper capabilties instead of being SUID root.
area/packaging
Verification is needed to ensure that the perf and slabinfo plugins still report data correctly with this change.
Fixes: #8673
> Fixed handling of permissions for some plugins.

- netdata-installer.sh
`CAP_PERFMON` is only available with Linux kernel 5.8 or newer, and needs a sufficiently up-to-date userspace to be able to set it.
With this change, we fall back to `CAP_SYS_ADMIN` (which `CAP_PERFMON` is a proper subset of) if we cannot set `CAP_PERFMON` for the perf plugin.
area/packaging
Check that the script does not report any errors or failures on older Linux systems.
> Fixed handling of perf.plugin capabilities.

- Makefile.am
- database/rrd.h
- database/rrddim.c
- database/rrdhost.c
- database/rrdset.c
- database/sqlite/sqlite_functions.c
We need to store metadata independent of the memory mode. 
- Compile sqlite always (it used to be enabled with ENABLE_DBENGINE)
- Store hosts, charts, dimensions and chart_labels by removing the check for memory mode = dbengine
database
Current status
- If you compile the agent without dbengine functionality there will be no dbengine folder created
and no `netdata-meta.db` created under (/var/cache/netdata) (default directory)
- If you compile the agent with dbengine functionality and set the memory mode to `ram` 
there will be a dbengine folder and `netdata-meta.db` file created under (/var/cache/netdata) but will
contain no data
Testing the PR
Remove the dbengine directory under `/var/cache/netdata` and `/var/cache/netdata/netdata-meta.db` 
**Warning**: Backup those files otherwise you …
> Enable metadata persistence in all memory modes

- health/health.d/vernemq.conf
Related netdata/product#1179
vernemq alarms are very sensitive, basically logic is _sent a notification if there is any error_.
The plan was to use ratio (percentage) instead of exact values whenever is possible. 
Unfortunately, it is not possible. So this PR adds a [`delay up`](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-delay) to all the alarms (we discussed it with @knatsakis).
---
> Unfortunately, it is not possible
**Reason is lack of job scope variables lookup.**
We have:
- chart A, which contains _total_ metric.
- chart B, which contains _specific_ metric.
If we want to calculate % of _specific_, we need to create an alarm for chart A and use its name as a variable in the chart B.
I've talked with @stelfrag and looks like that is how we do variables lookup, …
> health: make vernemq alarms less sensitive

- collectors/statsd.plugin/Makefile.am
- collectors/statsd.plugin/k6.conf
This PR adds our first (to my knowledge) stock collector based on StatsD. It collects data out-of-the-box about [K6](https://k6.io/), a load testing tool for developers. 
The user only needs to have Netdata installed on the machine where it runs the experiments and run ` k6 run --out statsd script.js`. If the user wants to support K6 tags, they will need to run `k6 run --out datadog script.js`.
The data have been organized after coordination with the K6 team.
This example and the new StatsD guide currently in PR should serve as an all-encompassing guide on how to vendor any StatsD collector for Netdata.
> add k6.conf

- health/health.d/wmi.conf
Templates/alarms names must be unique. Using `collectorName_` as a prefix is a common pattern.
`health`
> health: add `wmi_` prefix to the wmi collector network alarms

- health/notifications/alarm-notify.sh.in
Add a dump_methods parameter to the alarm-notify.sh.in script. This will be used by the posthog analytics. The agent will execute the script from the user's directory, and will report back the available notification methods.
It also adds a check for `MSTEAM`, `PD` & `PROWL` methods. (Without them, they will be always set to `YES`). Presumably they are set somewhere later, but we need them to be there too for the dump_methods to be accurate.
Comments are very much encouraged, and if there is something I'm missing especially for the methods above.
One thing this PR can't detect is whether `SEND_CUSTOM` is set. Any ideas would be great!
Health
When run with the dump_methods parameter, the script should just print the available methods and should NOT try to send anything. 
Normal execution …
> add a dump_methods parameter to alarm-notify.sh.in

- collectors/apps.plugin/apps_groups.conf
Added additional postfix processes to "email servers" group: pickup showq
Removed from group email: clamd freshclam
These are in the group "antivirus" and they don't show up there if they are also in "email" group.
Also added to group cron: incrond
Also added to group ups: apcupsd
> Add processes and move clamav

- aclk/aclk.c
- aclk/aclk_otp.c
- aclk/legacy/aclk_common.c
1. Adds `_aclk_impl` label with values of `Legacy` or `Next Generation` or not present if ACLK not available
2. Removes unneeded include from aclk_otp which references file from legacy ACLK
ACLK
build agent with aclk-ng and look at `/api/v1/info`, build with legacy and do the same.
> Adds _aclk_impl label

- daemon/unit_test.c
- database/rrddim.c
- database/rrdset.c
- health/health_config.c
- libnetdata/eval/eval.c
- libnetdata/libnetdata.h
- libnetdata/tests/test_str2ld.c
- web/api/queries/query.c
Fixes: #10353
I have renamed the abs macro to ABS, similarly to already existing MIN and MAX macros. I have replaced all ocurences in the code (although it compiled fine with the "standard" macro in the gcc headers) to use this "internal" version. Resolves the issue described in #10353 for me.
libnetdata, netdata core.
Code compiles natively on amd64 linux, cross compiles on aarch64. Native linux version tested fine.
> Rename abs to ABS to avoid clash with standard definitions. Fixes #10353.

- health/health.d/net.conf
We need different dropped packets thresholds for wifi and not wifi network interfaces. It is completely expected to have much more drops in wireless networks. I see no other way, than having 2 sets of alarms. 
This PR adss packets_dropped_ratio alarms for wifi network interfaces. 
I use [`families`](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-families) filter. Wifi iface [prefix is `wl`](https://github.com/systemd/systemd/blob/fa92d38428cdac260e72e280bf1d43539f4ea805/src/udev/udev-builtin-net_id.c#L839-L841) on systemd systems ([PredictableNetworkInterfaceNames](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/)). I understand that it doesn't cover other cases, but at least it fixes part of them.
I really get tired of having this …
> health: use separate packets_dropped_ratio alarms for wifi network interfaces

- .github/workflows/docker.yml
- .github/workflows/packaging.yml
SSIA
area/ci
Directly replicated from other places we are using Slack notifications from GitHub Actions.
Fixes: #10776 
This intentionally flags failures for merges to master as well as actual release build failures.
> Added Slack notifications for build failures.

- coverity-scan.sh
The version served by the download link has changed, which means the filename has changed as well, which was causing the scan process to fail.
area/ci
Verified that the version now matches the downloaded tarball name.
I’ll be opening a followup PR to add alerts to ensure this does not go unnoticed for so long again.
> Update Coverity version so that scanning works again.

- .travis.yml
DEB package builds expect no leading letters in version numbers, and we don’t want them in our RPM builds either.
area/packaging
Verified that the changes properly mangle the version information.
> Properly prepare version for binary package builds.

- claim/netdata-claim.sh.in
This PR attempts to fix slow DNS lookups, 5 seconds is not enough. I change it to 15 because we use 15 [when using wget](https://github.com/netdata/netdata/blob/e66b02ff6a936454acd63788c7b0e7953f0c1480/claim/netdata-claim.sh.in#L292).
see, sometimes it takes 5+ seconds
- https://github.com/netdata/netdata/issues/9319#issuecomment-773674215
- https://community.netdata.cloud/t/error-return-code-28-when-trying-to-claim-node/1047/19?u=ilyam8
The changes:
- increate curl --connect-timeout from 5 to 30
- decrease number of claim attempts from 5 to 3
⚠️ [We do 3 attempts](https://github.com/netdata/netdata/blob/e66b02ff6a936454acd63788c7b0e7953f0c1480/claim/netdata-claim.sh.in#L344-L355), so the maximum possible script execution time is up to 90 after this PR.
`claim`
Nothing to test.
Difference …
> claiming: increase curl connect-timeout and decrease number of claim attempts

- packaging/docker/run.sh
Fixes: #10809
netdata-claim.sh script expects -token, -url, -rooms and proxy params to be -param=
`packaging/docker`
- create docker image
- try to claim netdata container using env vars(`NETDATA_CLAIM_TOKEN`, `NETDATA_CLAIM_URL` and `NETDATA_CLAIM_ROOMS`
- start a new container with empty `/var/lib/netdata`, ensure it is claimed successfully and it is reachable on the Cloud ✅ 
- restart container, ensure it is reachable on the Cloud ✅ 
- delete container, create a new one using old `/var/lib/netdata`, ensure it is reachable on the Cloud ✅
> fix claiming via env vars in docker container

- health/health.d/net.conf
The following alarms don't work for cgroups
- [inbound_packets_dropped_ratio](https://github.com/netdata/netdata/blob/3b5a69c2a29817f4fe114c09107f7e57e5a4d26d/health/health.d/net.conf#L75-L87)
- [outbound_packets_dropped_ratio](https://github.com/netdata/netdata/blob/3b5a69c2a29817f4fe114c09107f7e57e5a4d26d/health/health.d/net.conf#L89-L101)
They use other other alarms as variables and those alarms attached to another charts.
It works for network interfaces in general, because of [variables lookup logic](https://learn.netdata.cloud/docs/agent/health/reference#variables) - network interfaces have unique family and there is family index.
> family variables.
Families are used to group charts together. For example all eth0 charts, have family = eth0. This 
index includes all local variables, …
> health: exclude cgroups net ifaces from packets dropped alarms

- libnetdata/ebpf/ebpf.c
- libnetdata/ebpf/ebpf.h
When compiled with the flags `-O0 -ggdb -pg -DACLK_SSL_ALLOW_SELF_SIGNED -DNETDATA_INTERNAL_CHECKS=1 -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_VERIFY_LOCKS=1` , eBPF plugin cannot be compiled on few distributions (`CentOS` and `Fedora`), this PR is removing `inline` that was creating the errors.
ebpf.plugin
1 - Compile this branch with the flags `-O0 -ggdb -pg -DACLK_SSL_ALLOW_SELF_SIGNED -DNETDATA_INTERNAL_CHECKS=1 -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_VERIFY_LOCKS=1`
2 - Check if compilation finishes with success.
3 - Start Netdata.
Errors were detected only when we tried to compile on RH family.
> Fix eBPF compilation

- backends/backends.c
- database/rrd.h
- exporting/check_filters.c
- exporting/prometheus/prometheus.c
- health/health_json.c
An alarm can't work when a corresponding chart doesn't have any data or is obsolete, archived, or disabled. We should neither show such alarms in the dashboard nor provide them through the `api/v1/alarms?all` API response.
Fixes #10797
health alarms
1. Run a docker container.
2. Check `Alarms` -> `All` in the dashboard - no `veth*` alarms should be shown.
3. Check `http://localhost:19999/api/v1/alarms?all` - no `net.veth*` alarms should be in the response.
> Don't show alarms for charts without data

- streaming/receiver.c
When an agent is compiled without dbengine support and a child is configured to use dbengine, as soon
as the child attempts to connect to the parent agent, the parent agent will shutdown with an error: 
`netdata FATAL : netdata : RRD_MEMORY_MODE_DBENGINE is not supported in this platform. # : Success`
This PR adds a check and rejects the connection to prevent the parent agent from shutting down
database
streaming
Before the PR
- Setup streaming such as the parent is configured to use memory mode RAM
- Compile the parent agent with the `--disable-dbengine` flag
- Configure a child to use `default memory mode = dbengine` in `stream.conf`
- Start the parent 
- Start the child
- Observe that the parent will shutdown
After the PR
- Repeat the steps above
- Observe that the parent will not …
> Add check for children connecting to a parent agent with unsupported memory mode

- .github/workflows/packaging.yml
- packaging/scripts/install.sh
Assorted fixes that were missed previously for the GHA packaging workflows.
area/ci
area/packaging
Thoroughly verified the RPM packaging changes in `packaging/scripts/install.sh`.
Simply verified that the conditional changes in the workflow more accurately represent the behavior we want.
> Fix handling of nightly and release packages in GHA workflows.

- collectors/python.d.plugin/adaptec_raid/adaptec_raid.chart.py
- health/health.d/adaptec_raid.conf
I think it is better to to apply LD status/PD state alarms per every device. Back then [`foreach`](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-lookup) wasnt implemented.
cc @kozicpetar
i have a question, is having a LD/PD not in desired state is CRIT level alarm in general? Or we can change it to WARN?
`health`
> health: apply adapter_raid alarms for every logical/physical device

- health/notifications/alarm-notify.sh.in
ssia 
We were debugging a problem yesterday and @dimko shared the log line
> alarm-notify.sh: ERROR: failed to send email notification for: 254b9fa2a7d8 system.cpu.custom_crit is CRITICAL to 'dkoutsourelis@netdata.cloud' with error code 78.
There is only error code and no the actuall error message. Recently i had similar problem - email notifications doesn't because of systemd capabilities and it was impossible to debug. When i added logging of the error message it became clear (_exim: setgroups() failed: Operation not permitted_).
Before this PR
```cmd
[netdata@pc plugins.d]$ ./alarm-test.sh
./alarm-notify.sh: line 888: /usr/bin/sendmail2: No such file or directory
2021-03-19 13:57:01: alarm-notify.sh: ERROR: failed to send email notification for: pc test.chart.test_alarm is WARNING to …
```
> health: log an error if any when send email notification

- database/engine/rrdengineapi.c
- database/engine/rrdengineapi.h
- database/rrd.h
- database/rrddim.c
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
- web/api/formatters/json/json.c
- web/api/formatters/json/json.h
- web/api/formatters/json_wrapper.c
- web/api/formatters/json_wrapper.h
- web/api/formatters/rrd2json.c
- web/api/queries/query.c
- web/api/queries/rrdr.c
- web/api/web_api_v1.c
- web/server/web_client.c
Add the ability to query archived charts. This will only work if the dbengine memory mode is used.
After an agent restart the archived charts are not loaded in memory. When a `/api/v1/data` request is received for such a chart it will lookup the chart in the sqlite database, build the necessary chart and dimension structures and perform the query.
database
- Setup a dbengine-enabled parent with a child (the parent should use dbengine to store the data at least for the child)
- Start the parent and the child e.g. **child1**
- On the parent you can execute a query 
`http://parent_ip:19999/host/child1/api/v1/data?chart=system.cpu&after=-10` 
and receive the collected values for the child
- Stop the parent and child
- Start only the parent and try to execute …
> Add data query support for archived charts

- health/health.d/exporting.conf
We have
https://github.com/netdata/netdata/blob/32344ec967caa60cf1bac7dad1c8baf4a471babc/health/health.d/exporting.conf#L14-L23
if sent % != 100 => there is some metrics lost. No need in having both of these alarms.
`health`
> health: remove exporting_metrics_lost template

- collectors/python.d.plugin/adaptec_raid/adaptec_raid.chart.py
- health/health.d/adaptec_raid.conf
- health/health.d/anomalies.conf
- health/health.d/apcupsd.conf
- health/health.d/beanstalkd.conf
- health/health.d/ceph.conf
- health/health.d/fping.conf
- health/health.d/httpcheck.conf
- health/health.d/ioping.conf
- health/health.d/kubelet.conf
- health/health.d/megacli.conf
- health/health.d/memcached.conf
- health/health.d/portcheck.conf
- health/health.d/riakkv.conf
It is a good practice to add a component/collector name to the alarms as a prefix (or at least use somewhere in the alarm/template name) and we do it pretty often (name is clear, protection against accidental redefinition in another file, etc.).
However, there are some cases where we don't follow thar practice. This PR fixes it for external collectors.
`health`
- install this PR 
- check for health configuration load errors in the error.log - there is no any (`grep "Health configuration" error.log`)
In most of the cases these chages are comspetic (a name change).
There are several cases when we use a template as a variable:
- [httpcheck](https://github.com/ilyam8/netdata/blob/health_add_app_prefix_to_alarms/health/health.d/httpcheck.conf)
- …
> health: add collector prefix to the external collectors alarms/templates

- .github/workflows/packaging.yml
Binary package uploads have been failing due to a mismatch in the name of the API token secret for Package Cloud between the workflow and the repository configuration.
This fixes that by reaming the secret in the workflow, as that0s easier to change than the name used in the repository configuration.
area/ci
Properly verified that the secret name matches now.
> Fix name of PackageCLoud API token secret in workflows.

- health/health.d/megacli.conf
I think it is better to to apply adapter/physical disks alarms per every device. Back then [`foreach`](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-lookup) wasnt implemented.
`health`
Not really needed, i basically add `foreach *` to the lookup, [which is the correct syntax](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-lookup).
> health: apply megacli alarms for all adapters/physical disks

- web/api/formatters/value/value.c
- web/api/queries/rrdr.c
- web/api/queries/rrdr.h
#10832
Add a lock check to avoid agent shutdown when compiled with internal checks and verify lock checks. This is a quick 
fix and it will be improved in the future.
database, web
-  Verify  as  described in #10832, then apply PR and verify that the agent does not shutdown
> Add lock check to avoid shutdown when compiled with internal and locking checks

- .github/workflows/coverity.yml
This should hopefully ensure we notice the workflow itself failing in the future.
area/ci
Exactly replicates working code found elsewhere in the repo.
> Add basic failure notifications for the Coverity workflow.

- daemon/main.c
- database/sqlite/sqlite_functions.c
- web/api/formatters/json_wrapper.c
- web/api/formatters/rrd2json.c
- Properly release memory used for the charts when accessing archived data (charts are archived) 
- Properly shutdown the SQLite database connection
- Database close was not issued during agent shutdown
- Store and finalize SQL statements to release memory during shutdown (Quick Fix)
- Keep a list of statements to finalize and do sqlite3_finalize on shutdown
- Address coverity 
- CID 369624:  Resource leaks  (RESOURCE_LEAK)
- CID 369623:  API usage errors  (LOCK)
database
- SQLite Reported memory leaks during shutdown should vanish (or greatly reduced)
- e.g. run with `valgrind --leak-check=full --show-leak-kinds=all`
> Fix memory leak when archived data is requested

- packaging/installer/netdata-updater.sh
This fixes three issues in the updater:
* Fixed handling of the `NETDATA_TMPDIR_PATH` value passed to the script when it’s been re-invoked after a self-update. This bug was causing the `create_tmp_directory` function to not output anything if this variable was set, causing the update process to fail if the updater script had self-updated.
* Fixed the name of an option passed during re-invocation of the updater after a self-update. This bug was causing the updater to make spurious update checks, wasting time and bandwidth as well as producing unnecessary output from the script.
* Fixed handing of the temporary directory WRT the installer script when invoked from the updater. We were previously just letting the installer inherit the value of `TMPDIR` from the environment, but we need to …
> Assorted updater fixes.

- health/health.c
Fixes #10332 
Health
1 - Compile the PR
2 - Configure `/etc/netdata/python.d/example.conf`:
```conf
python_example:
v: 1
```
3 - Add an alarm to `/etc/netdata/health.d`:
```conf
alarm: my_example
on: example_python_example.random
units: boolean
lookup: sum -3s foreach *
warn: $this > 200
crit: $this > 250
every: 20s
repeat: warning 15s critical 10s
module: example
info: Testing repeat
to: sysadmin
```
4 - Confirm that you received an alarm before the expected repeat time:
```
2021-03-23 19:39:19: alarm-notify.sh: INFO: sent telegram notification for: hades example_python_example.random.my_example_random1 is WARNING to '-3'
2021-03-23 19:39:25: alarm-notify.sh: INFO: sent telegram notification for: hades example_python_example.random.my_example_random3 is WARNING to '-3'
2021-03-23 …
```
> fix_repeat: Update repeat_every and avoid unecessary test

- health/health_json.c
Include the `host->timezone` to the payload to the cloud. This way, the cloud can include a local time for the alerts email notifications based on timezone and timestamp.
Health
Compile this PR, and check the payload to cloud for type `status-change` for `outbound/alarms`. It should include the timezone like this:
2021-03-23 18:41:40: netdata DEBUG : HEALTH : (0247@aclk/legac:aclk_queue_quer): Added query (outbound/alarms) ({	"type": "status-change",
"msg-id": "c7234f91-2d32-4137-80a6-5e81d3e3ffdf",
"timestamp": 1616517700,
"timestamp-offset-usec": 65761,
"connect": 1616517686,
"connect-offset-usec": 72920,
"version": 2,
"payload": 
{
"hostname": "winterland",
"timezone": "Europe/Athens",
"unique_id": 1612383578,
"alarm_id": 1615304162,
"alarm_event_id": 595,
"name": …
> Add timezone to payload for cloud to be able to deduce the local time for timestamps

- collectors/proc.plugin/proc_diskstats.c
- collectors/proc.plugin/proc_self_mountinfo.c
- collectors/proc.plugin/proc_self_mountinfo.h
We are checking device names in addition to major/minor numbers to ensure we distinguish devices from each other. 
Fixes #10841
diskstats module of proc plugin
Check if all diskstats charts are available for all disks in the system. Verify if the names of charts and families are correct.
> Check device names in diskstats plugin

- web/api/web_api_v1.c
Fix an agent crash when executing a data query with a context and chart_label_key that does not exist.
The extended functionality of chart label key is not supported for archived queries for now. 
This PR will ignore non-matching chart labels keys that do not exist in active (in-memory charts) and do no
attempt to access the sqlite metadata
database, web
- Compile agent from master and execute
`http://localhost:19999/api/v1/data?context=system.cpu&options=jsonwrap&chart_label_key=this_breaks`
- Apply the PR and try again
> Fix agent crash when executing data query with context and non-existing chart_label_key

- health/notifications/alarm-notify.sh.in
- fixed most of the styling problems, especially for outlook (online) and thunderbird
- updated colors based on status (both for active alarms list and the main part of template)
Most of the differences between email and the design is caused by the fact, that it's hard to make sure the proper font is loaded. Most of the time the needed one (IBM Plex Sans) is not loaded, and Helvetica is used instead. Sometimes it results in *bold* fonts (font-weight: 500) to look differently than in design.
second part:
Health / alarm template
> Alerts template styling fixes

- health/notifications/alarm-notify.sh.in
- health/notifications/health_alarm_notify.conf
This enables the IRC notification plugin to choose the IRC port, this is needed on some IRC servers, moreover, it's required if you want to usually connect to SSL/TLS-enabled IRC servers (just using `ncat --ssl` as nc and changing the port to 6697 for example).
Health notifications / Alarms
Try a SSL/TLS server with port 6697 and `ncat --ssl` as an external tool.
> alarm(irc): add support to change IRC_PORT

- .travis.yml
We’re already doing the same thing in GitHub Actions, and they apparently can break on Travis due to infrastructure issues in such a way that we can’t restart the build at all.
area/ci
n/a
> Remove corss-platform builds on Travis.

- collectors/proc.plugin/proc_net_dev.c
- web/gui/dashboard_info.js
SSIA
Fixes https://community.netdata.cloud/t/network-iface-status-params/953
cc @k0ste
proc plugin
Run Netdata, check `net_carrier.<interface>` and `net_mtu.<interface>` charts.
> Add carrier and mtu charts for network interfaces

- health/health_json.c
- health/health_log.c
- libnetdata/libnetdata.c
- libnetdata/libnetdata.h
Finds and replaces `$family` and `${family}` in health info strings. Continues from https://github.com/netdata/netdata/pull/10801. 
Health
Insert a `$family` or `${family}` variable in an alarm's configuration info string. Observe it to be replaced with the family value in dashboard, aclk, v1/api and notification emails.
We should merge this in the feature branch so it can be tested generally. When it goes into master we should have decided if we're going to support both variable formats, or just one of them, and whether we need more (i.e. `$this`, `$units`, etc).
> Find and replace $family variable in health info strings.

- health/notifications/alarm-notify.sh.in
Changes format for the html email subject, and makes the `Edit` a link to the documentation.
Health
When an alarm is raised, and an html mail is sent, the subject should be in the format:
`Warning|Critical|Clear, alarm_name = value, on host`
The `Edit` word in `Edit Edit this alert's configuration...` should be a link to netdata docs part for editing alarms.
> Change the html email subject and add a link to Edit part

- .travis.yml
- Makefile.am
This ensures we actually bundle the `mqtt_websockets` code into our nightly and release tarballs so that people can properly build it without needing to build from a git clone of the repo.
area/packaging
Locally verified that the tarball produced by `autoreconf -ivf && ./configure && make dist` can be used to successfully build the agent with the new ACLK code.
The Tavis CI change can be verified by looking at the build logs for this PR.
This also sorts the `dist_noinst_DATA` list in the top level Makefile so that future changes are cleaner.
Fixes: #10891
> Fixed bundling of ACLK-NG components in dist tarballs.

- .github/workflows/packaging.yml
PackageCloud does not allow duplicate uploads, and we currently have no good way to avoid duplicate nightly builds, so we need to remove any existing packages with the same name before we upload newly built packages.
area/ci
n/a
The original plan was to update the CI to not run nightly builds if we haven’t seen any changes to `master` since the last nightly build. However, there’s not really any practical way to do that with Travis CI, so while it is still planned, it’s dependent on eventually getting everything moved to GitHub Actions (where it is _very_ easy to do). As a result, we’re just going with this stopgap until such time as we can do it properly (probably some time late Q2 or early Q3 2021).
> Properly handle binary package reuploads.

- daemon/common.c
- daemon/common.h
- daemon/main.c
- health/health_json.c
Get the local utc offset from strftime, and pass it to alarms. This is for the cloud to produce a local time for the email notification from utc time.
Health
> Get the local utc offset, and pass it to alarms

- packaging/makeself/openssl.version
This includes a number of security fixes relative to the version we are currently bundling.
area/packaging
Manually build the version from the PR (run `packaging/makeself/build-x86_64-static.sh` from the root of the repository) and verify the resultant static build.
> Bumped version of OpenSSL bundled in static builds to 1.1.1k.

- health/health.c
This PR excludes the current alert from the count of all active alerts (in warning or critical state), when sending an alert notification. It also won't appear on the table at the bottom part of the new html notifications email.
Health
Enable mail alerts, and observe if in an email, the current alert is included in the count or not, and also if it appears on the table of active/raised alerts.
> Don't include the current alert in host's alerts counter in notification.

- health/health.d/disks.conf
- health/health.d/mdstat.conf
- health/health.d/net.conf
This PR adds $family variables to the following sets of alarms:
- net ($family is a network device name)
- disks ($family is a device or partition name)
- mdstat ($family is an array name)
`health`
> health: use $family variable in the alarms info

- web/api/formatters/rrd2json.c
Fixes #10929
Then executing queries in RAM / SAVE mode, the metric_uuid was never properly allocated and
would result in memory corruption. 
database
web
- Start agent with memory mode not being dbengine e.g RAM / SAVE
- Execute a query `http://127.0.0.1:19999/api/v1/data?context=net.net`
- This will attempt to free a copy of a `rd->state->metric_uuid` that belongs to the original rrddim and result to a crash
- Apply the PR
- Agent should not crash
Note: This is a temporary fix. A new PR in the next version avoids the memory allocation of the metric_uuid
> Fix memory corruption issue when executing context queries in RAM/SAVE memory mode

- collectors/all.h
- collectors/proc.plugin/README.md
- collectors/proc.plugin/proc_diskstats.c
- web/gui/dashboard_info.js
There are extended stats for disks in new kernels. We are adding new charts for them.
Fixes #10848
diskstats module of proc plugin
Check charts:
- `disk_ext.<disk>`
- `disk_ext_ops.<disk>`
- `disk_ext_mops.<disk>`
- `disk_ext_iotime.<disk>`
- `disk_ext_await.<disk>`
- `disk_ext_avgsz.<disk>`
> Add new charts for extended disk metrics

- health/health.d/mysql.conf
- web/gui/dashboard_info.js
Fixes: #10940
This PR adds checking for _Inconsistent_ state to the [mysql_galera_cluster_state](https://github.com/netdata/netdata/blob/8bc32ad6e61ace3408e4983e020800e8c4c79637/health/health.d/mysql.conf#L127-L136) alarm.
Corresponding chart info is also updated in the dashboard_info.js.
`health/`
`web/gui`
I think no tests needed. (but @ekexcello please check the changes visually at least 😄 )
> health: add Inconsistent state to the mysql_galera_cluster_state alarm

- collectors/ebpf.plugin/ebpf.c
- collectors/ebpf.plugin/ebpf_apps.c
- collectors/ebpf.plugin/ebpf_apps.h
- collectors/ebpf.plugin/ebpf_cachestat.c
- collectors/ebpf.plugin/ebpf_cachestat.h
- collectors/ebpf.plugin/ebpf_process.c
- collectors/ebpf.plugin/ebpf_socket.c
- collectors/ebpf.plugin/ebpf_socket.h
Fixes #10955 
Fixes #10953
It probably fixes #10682, I could not recreate the problem, so I am not sure about this last, @vlvkobal , please, test also on an environment that you reported the problem.
This PR fixes almost all reports that valgrind gives, the unique exceptions is the next:
```
==7720==    at 0x40A58E: compare_sockets (ebpf_socket.c:882)
==7720==    by 0x4156D6: avl_search (avl.c:26)
==7720==    by 0x415F7A: avl_search_lock (avl.c:388)
==7720==    by 0x40BD52: store_socket_inside_avl (ebpf_socket.c:1174)
==7720==    by 0x40C1D1: hash_accumulator (ebpf_socket.c:1308)
==7720==    by 0x40C470: read_socket_hash_table (ebpf_socket.c:1371)
==7720==    by 0x40C687: ebpf_socket_read_hash (ebpf_socket.c:1475)
==7720==    by 0x42E3DC: thread_start (threads.c:184)
==7720==    by …
```
> Fix epbf crash when process exit

- exporting/aws_kinesis/aws_kinesis_put_record.cc
- exporting/exporting_engine.c
- exporting/graphite/graphite.c
- exporting/opentsdb/opentsdb.c
- exporting/prometheus/remote_write/remote_write.c
- exporting/pubsub/pubsub_publish.cc
- exporting/tests/netdata_doubles.c
> Spelling exporting

- health/health.c
- health/health_log.c
> Spelling health

- backends/backends.c
> spelling: backend

- daemon/common.h
- daemon/main.c
- daemon/signals.c
- daemon/unit_test.c
> Spelling daemon

- spawn/spawn.c
> spelling: bidirectional

- streaming/receiver.c
- streaming/sender.c
> Spelling streaming

- collectors/python.d.plugin/README.md
- packaging/installer/methods/alpine.md
- packaging/installer/methods/macos.md
- packaging/installer/methods/manual.md
We use git submodules for ACLK-NG (and later for protobuf payload definitions for Agent/Cloud comms). Update docu where cloning Netdata repository is mentioned to ensure users get also the submodules downloaded.
Docs
When you use new command the `mqtt_websocets` directory gets populated with files after the clone
> Adds --recursive to docu git clones

- health/Makefile.am
[health/health.d/synchronization.conf](https://github.com/netdata/netdata/blob/master/health/health.d/synchronization.conf) was added in https://github.com/netdata/netdata/pull/10726, but @thiagoftsm forgot to update Makefile. This PR fixes it.
`health`
- install this PR, ensure synchronization.conf in the alarms stock dir.
> health: add synchronization.conf to the Makefile

- health/Makefile.am
- health/health.d/systemdunits.conf
This PR adds alarms for the [systemdunits collector](https://github.com/netdata/go.d.plugin/tree/master/modules/systemdunits#systemd-units-state-monitoring-with-netdata) charts.
States:
- `active`: started, bound, plugged in, etc. depending on the unit type. 
- `inactive`: stopped, unbound, unplugged, etc.
- `activating`: in the process of being activated.
- `deactivating`: in the process of being deactivated.
- `failed`: very similar to inactive and is entered when the service failed in some way (process returned error code on exit, or crashed, an operation timed out, or after too many restarts).
New alarms check if there are any systemd units in the failed state.
I tried to add those alarms using [foreach](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-lookup) (for …
> health: add systemdunits alarms

- web/gui/dashboard_info.js
This PR adds [systemunits](https://github.com/netdata/go.d.plugin/tree/master/modules/systemdunits#systemd-units-state-monitoring-with-netdata) collector and its charts description to the dashboard.
`web/gui`
> web/gui: add systemdunits info to the dashboard_info.js

- health/REFERENCE.md
It is `options`, not `option`
https://github.com/netdata/netdata/blob/1cc1ec718c84b64a9ef2b1c0d582f31b135d4c23/health/health.h#L51
`health`
Not needed
> health: fix alarm line options syntax in the docs

- docs/Running-behind-nginx.md
- docs/guides/step-by-step/step-10.md
The Nginx configs proposed in the documentation only listen for IPv4 traffic. If you have both IPv4 and IPv6 DNS hooked up, then `certbot` seemingly tests both.
I didn't notice the missing IPv6 configuration in the Nginx config I copied from your documentation until after some debugging, googling, and comparing to my other Nginx configs.
In short, I just added the following to the docs:
```diff
server {
listen 80;
+    listen [::]:80;
#server_name netdata.example.com;
```
I did not find an open issue on the case.
Documentation
I'm quite new to Nginx and found the solution here: <https://community.letsencrypt.org/t/certbot-invalid-response-from/126715/5>.
Full credit to [DAMO238](https://community.letsencrypt.org/u/DAMO238) and [JuergenAuer](https://community.letsencrypt.org/u/JuergenAuer) …
> Add docs on Nginx with IPv6 listen for certbot to work

- collectors/python.d.plugin/smartd_log/smartd_log.chart.py
This enables the collection of NAND Writes 1GiB attribute, this enable measurement of write amplification phenomenon: https://en.wikipedia.org/wiki/Write_amplification
python.d/smartd_log collector
Tested on a `SAMSUNG MZ7LN256HMJP-00000`, I suppose that consumer grade SATA SSD might expose a similar attribute compared to a real host writes metric. Knowing the WA, it's possible to guess the host writes metric, which is an important metric knowing the endurance of disks.
---
On another note, I would like to add Total LBAs written/read, would that be a good idea? (see https://www.thomas-krenn.com/en/wiki/SMART_attributes_of_Intel_SSDs)
> python.d(smartd_log): collect attribute 249 -- NAND Writes 1GiB

- collectors/charts.d.plugin/opensips/opensips.chart.sh
Fixes: #10947
[require_cmd](https://github.com/netdata/netdata/blob/a94408c0cda105e3e68214c16a03c7038a5c2560/collectors/charts.d.plugin/charts.d.plugin.in#L82-L92)
`collectors/`
Not needed
> collectors/charts.d/opensips: fix detection of `opensipsctl` executable 

- collectors/fping.plugin/fping.plugin.in
The #10241 have updated fping version for netdata static builds, but missed the same for the `fping.plugin install` command. This PR updates default fping version for `fping.plugin install` command and adds option to specify needed version.
`agent/collectors/fping.plugin`
As the [fping.plugin docs](https://learn.netdata.cloud/docs/agent/collectors/fping.plugin) state, install fping by running
```sh
/usr/libexec/netdata/plugins.d/fping.plugin install
```
Also, specific version could be set too:
```sh
/usr/libexec/netdata/plugins.d/fping.plugin install 4.2
```
The [packaging/makeself/jobs/50-fping-5.0.install.sh](https://github.com/netdata/netdata/blob/master/packaging/makeself/jobs/50-fping-5.0.install.sh) has changed source of fping from GitHub to `fping.org` (#10241), same could be done …
> Update fping version

- .clang-format
During the last meetup, we vote for a new `.clang-format` configuration. As far as we didn't try to see how actually code is looking for every parameter, there were some misunderstandings.
I propose some subtle changes to the format. The most important are `BinPackArguments` and `BinPackParameters`. It's very difficult to read code when there are multiple rows with multiple parameters in a row like in the following example:
```
buffer_sprintf(
b, "%s.%s.%s.%s%s%s " COLLECTED_NUMBER_FORMAT " %llu\n", prefix, hostname, chart_name, dimension_name,
(host->tags) ? ";" : "", (host->tags) ? host->tags : "", rd->last_collected_value,
(unsigned long long)rd->last_collected_time.tv_sec);
```
Start of the discussion https://github.com/netdata/netdata/pull/7149#discussion_r341551942
> Fine tune clang-format

- packaging/installer/install-required-packages.sh
The OKay repository has recently change his GPG key but the netdata installer use old RPM to setup the Okayt repository that causes error during installation process.
Fix : #10970
Packaging ?
Run the installer with the version fix
> Upgrade OKay repository RPM for RHEL8

- libnetdata/popen/popen.c
When issuing a SIGTERM with `systemctl restart netdata.service` an ERROR message is created in the log for every plugin:
> netdata ERROR : PLUGINSD[apps] : child pid 23901 killed by signal 15.
> netdata ERROR : PLUGINSD[python.d] : child pid 23908 killed by signal 15.
> netdata ERROR : PLUGINSD[nfacct] : child pid 23909 killed by signal 15.
> netdata ERROR : PLUGINSD[go.d] : child pid 23899 killed by signal 15.
Seems like it would be worth silencing this to an INFO message if we did a proper restart or shutdown.
Also, I wasn't sure what the proper return code should be so I put it in as `return(0);`
> Remove error message on netdata restart

- collectors/ebpf.plugin/ebpf_cachestat.c
- web/gui/dashboard_info.js
Fixes #10967
ebpf.plugin
1 - Enable chacestat inside your `ebpf.d.conf`:
```conf
cachestat = yes
```
2 - Compile this PR
3 - Start `netdata` and let it running during 1 minutes, during this interval of time you cannot have gaps described [here](https://github.com/netdata/netdata/issues/10967#issue-856917401)
I tested only on Slackware current running kernel `5.10.29`, because we did not bring any modification for eBPF programs.
> Remove condition that was creating gaps

- .travis.yml
- .travis/create_changelog.sh
* Remove some dad code left over from when we were building Docker images using Travis CI.
* Authenticate against Docker Hub before trying to pull a Docker image, avoiding the anonymous pull limits.
area/ci
Needs to be verified in a nightly build (can’t be properly tested outside of that context).
This should fix the issues we’ve been seeing with the nightly builds intermittently not working correctly.
> Assorted fixes for Travis CI code.

- aclk/aclk.c
- aclk/aclk_otp.c
- aclk/aclk_util.c
- aclk/aclk_util.h
- aclk/https_client.c
- aclk/https_client.h
Implements more smart/full HTTPS client for ACLK (although in the future other code can use it too(currently it depends on ACLK-NG but after Legacy is removed we can move it to libnetdata to be usable in wider agent))
This is a prerequisite for redesigned new Cloud architecture (/env endpoint etc.)
Currently this is not fully compliant HTTPS client by far (mostly implements what we need) but is made to be extensible so that further features are easy to add without rewrite etc.
ACLK
Everything should work as expected. The agent connects to the cloud without issue.
I also retested the connection through HTTP proxy (squid).
> implements new https client for ACLK

- aclk/aclk.c
- aclk/aclk_otp.c
- aclk/aclk_otp.h
Fixes MQTT connection being attempted when we couldn't get the OTP.
ACLK-NG
Fail OTP (block cloud IP) see that MQTT connection attempt is not being made until next reconnect attempt (after honoring TBEB)
> prevents mqtt connection attempt on OTP failure

- aclk/aclk.c
- aclk/aclk_query.c
- aclk/aclk_stats.c
- aclk/aclk_util.c
@vkalintiris correctly noted some of the ACLK-NG files were missing SPDX license info as first line. This PR fixes that
ACLK-NG
Non functional change
> adds missing SPDX license info into ACLK-NG

- daemon/global_statistics.c
SSIA
Fixes #10968
global statistics plugin
Check the `netdata.uptime` chart.
> Add a chart with netdata uptime

- .github/workflows/build-and-install.yml
build doesn't work when using [v1.9+](https://github.com/aws/aws-sdk-cpp#version-19-is-now-available)
let's use latest 1.8 (1.8.186)
`ci/`
> ci: fix aws-kinesis builds

- backends/backends.c
- backends/backends.h
- database/rrd.h
- database/rrdset.c
- exporting/check_filters.c
- exporting/exporting_engine.h
- exporting/prometheus/prometheus.c
- exporting/read_config.c
- exporting/tests/exporting_fixtures.c
- exporting/tests/test_exporting_engine.c
The PR fixes a couple of issues:
- The chart filtering pattern from the `backend` section of `netdata.conf` wasn't applied to the Prometheus web API endpoint.
- backend and exporting filtering configuration options were mixed up and resulted in an unexpected filtering pattern.
Fixes #11001
backends, exporting engine
1. Configuration
`netdata.conf`:
```
[backend]
enable = yes
send charts matching = system.processes
```
`exporting.conf`:
```
[prometheus:exporter]
send charts matching = system.ram
```
2. Run `nc -l -p 2003`, wait for metrics
4. Access `http://localhost:19999/api/v1/allmetrics?format=prometheus`
You should see:
```
netdata_info{instance="arch-esxi",application="netdata",version="v1.30.1-57-g330ba6bfc"} 1 1618933809451 …
```
> Backend chart filtering backward compatibility fix

- collectors/python.d.plugin/python_modules/bases/charts.py
This PR adds plugin and module names to the runtime [charts definitions](https://learn.netdata.cloud/docs/agent/collectors/plugins.d#chart).
These charts can be found in `Netdata Monitoring -> python.d`
> CHART type.id name title units [family [context [charttype [priority [update_every [options [plugin [module]]]]]]]]
We plan to use them for [deprecation alarms](https://github.com/netdata/netdata/issues/10248).
- check python.d debug output, plugin/module names should be in the charts definitions
```cmd
CHART netdata.runtime_example_Four_Lines '' 'Execution time for example_Four_Lines' 'ms' 'python.d' netdata.pythond_runtime line 145000 1 '' 'python.d.plugin' 'example'
```
- check on the dashboard
> python.d: add plugin and module names to the runtime charts

- aclk/aclk.c
- aclk/aclk.h
- aclk/aclk_query.c
- aclk/aclk_rx_msgs.c
- aclk/aclk_rx_msgs.h
- aclk/aclk_tx_msgs.c
- aclk/aclk_tx_msgs.h
Removes version negotiation code `hello`/`version` messages which have been obsoleted in favor of feature flags/capabilities mechanism in new cloud architecture
ACLK-NG
Should still work OK with cloud as before
> remove vneg from ACLK-NG

- exporting/exporting_engine.h
- exporting/prometheus/remote_write/remote_write.c
- exporting/send_data.c
- exporting/tests/test_exporting_engine.c
Prometheus remote write requires the HTTP Host: header to be correct. We use the destination option as a value of the header. When we configure multiple destinations, the header contains all hosts configured. We should use only the host we are connected to.
Fixes #10608
1. Configure the remote write exporting connector with two destinations:
```
[prometheus_remote_write:my_prometheus_remote_write_instance]
enabled = yes
destination = localhost:1234 localhost:1235
```
2. Build two versions of an [example remote write adapter](https://github.com/prometheus/prometheus/tree/main/documentation/examples/remote_storage/example_write_adapter). One for port 1234 and another one for port 1235.
3. Run both adapters. When you kill the first adapter, the second should show received …
> Allow the remote write configuration have multiple destinations

- claim/claim.c
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
- streaming/receiver.c
- Store the claim id in the local database
- Add a node_id column to be filled when an aclk connection is established
- Initially empty
database
aclk
- Creates a new table in the metadata database called `node_instance`
- Verify that you have the new entries there for the parent and children
- use sqlite3 to access the local database `sqlite3 netdata-meta.db` which is stored under `/var/cache/netdata/`
- Do `select count(*) from node_instance ni, host h where ni.host_id = h.host_id;`
> Persist claim ids in local database for parent and children

- collectors/cgroups.plugin/cgroup-name.sh.in
Signed-off-by: git@end.re git@end.re
**Summary**
Added support for libvirtd LXC containers to the `cgroup-name.sh` cgroup name normalization helper script found in `netdata/collectors/cgroups.plugin`.
**Component Name**
**Description of testing that the developer performed**
The bash script `cgroup-name.sh`, a "Script to find a better name for cgroups" had support for libvirtd QEMU VMs but not for LXC containers. This PR adds support to get the libvirtd LXC container names normalized as well.
**Additional Information**
Example outputs:
```
$ ./cgroup-name.sh.in 'machine.slice_machine-lxc/x2d9192/x2datvie0ximta01.scope'     
2020-03-05 09:32:22: cgroup-name.sh.in: INFO: cgroup 'machine.slice_machine-lxc/x2d9192/x2datvie0ximta01.scope' is called 'lxc/atvie0ximta01' …
```
> [area/collectors] Added support for libvirtd LXC containers to the `cgroup-name.sh` cgroup name normalization script

- daemon/anonymous-statistics.sh.in
This PR adds `--max-time=2` timeout.
I set it to 2 because 
- it [was 2](https://github.com/netdata/netdata/blob/9580ed4d13125adac01483bac14a18c952afd13e/daemon/anonymous-statistics.sh.in#L33) before switching to [PostHog](https://github.com/netdata/netdata/pull/10636)
- @andrewm4894 didn't change `wget` timeout ([it is 1](https://github.com/netdata/netdata/blob/b6d729f96a0b1e17abffb2cf69d1ff29e62004f4/daemon/anonymous-statistics.sh.in#L85-L87))
`anonymous-statistics`
> anonymous-statistics: add a timeout when using `curl`

- database/rrd.h
- database/rrdcalc.c
- database/rrdcalc.h
- database/rrdcalctemplate.h
- health/health.c
- health/health.h
- health/health_config.c
- health/health_json.c
- health/health_log.c
These fields made our headers incompatible with C++, because `class` is
a reserved keyword.
Build the kmeans-poc branch which uses C++ source files without errors.
> Rename struct fields from class to classification.

- aclk/aclk.c
- aclk/aclk.h
- aclk/aclk_otp.c
- aclk/aclk_util.c
- aclk/aclk_util.h
Parses error messages from cloud and honors backoff returned by cloud.
Implements new TBEB and uses parameters from env endpoint.
ACLK-NG
- error messages can be tested by starting the agent a few times and killing it quickly. Eventually, the password endpoint will return 409 with 1-minute backoff. E.g. you will get rate limited by cloud for a minute or two.
- rest can be tested by checking parameters from cloud are used to do the bacoff
> ACLK new cloud architecture new TBEB

- collectors/proc.plugin/proc_mdstat.c
- health/health.d/mdstat.conf
Relevant discussion: https://github.com/netdata/netdata/issues/10247#issuecomment-824429429
This PR:
- adds raid level to the family (e.g.: `md0 => md0 (raid1)`)
- excludes raid1 and raid10 arrays in the [mdstat_mismatch_cnt](https://github.com/netdata/netdata/blob/7b6362767e71b09ad1604de45c754e798c7dd169/health/health.d/mdstat.conf#L27-L38) alarm due to too many false positives (thanks to @mailinglists35)
`collectors/proc/`
- create several arrays using `mdadm`
- delete them
- recreate them again - ensure nothing breaks.
That is how it looks on the dashboard:
> proc/mdstat: add raid level to the family

- claim/claim.c
- database/sqlite/sqlite_functions.c
- streaming/receiver.c
- Properly enable the storage of NULL claim ids in the local (parent) database for children
- Resets claim ids to NULL when the children are unclaimed
Previously a check would prevent this from storing null claim ids
database
aclk
- Verify that you have the new entries there for the parent and children
- Note unclaimed children would be omitted from this table before this PR
- use sqlite3 to access the local database `sqlite3 netdata-meta.db` which is stored under `/var/cache/netdata/`
- Do `select count(*) from node_instance ni, host h where ni.host_id = h.host_id;`
- Connect an unclaimed child to the parent
- Entry should be available in the node_instance table which claim id NULL
- Connect a claimed child to the parent
- Entry should be available in the node_instance table 
- Unclaim …
> Fix storing an NULL claim id on a parent node

- health/health.d/vernemq.conf
From our experience using `sum` makes VerneMQ alarms too sensitive, this PR changes the `lookup` method to `average`.
`health/`
- install new alarms
- ensure there are no syntax errors checking `error.log`
> health/vernemq: use `average` instead of  `sum`

- packaging/bundle-ebpf.sh
Fixes #11017 
Create ebpf.d directory in PLUGINDIR
netdata
For Debian
1. Build the debian package of netdata
2. Install the netdata deb and check  the directory in PLUGINDIR
For RPM
1. Build the rpm package of netdata
2. Install the netdata rpm and check the directory in PLUGINDIR
> Create ebpf.d directory in PLUGINDIR for debian and rpm package(netdata#11017)

- collectors/cgroups.plugin/sys_fs_cgroup.c
If there are dots in the id of a cgroup on a child node, the dashboard on the parent node shows a truncated name for the cgroup. It happens because our current streaming protocol uses dots to distinguish chart type and id. After streaming of `type.with.dots.id.with.dots` we get type = `type` and id = `with.dots.id.with.dots`.
The solution is to replace dots with dashes in the cgroup id.
Fixes #11049
cgroups plugin
1. Create a docker container on a child node with the name, containing dots: docker run -d --name "first.second.third" nginx
2. Configure streaming.
3. Check the name of the container in the main menu on the parent node - it should be `first-second-third`.
> Remove dots in cgroup ids

- database/rrdcalctemplate.c
- database/rrdcalctemplate.h
- health/REFERENCE.md
- health/health_config.c
Fixes #11000 
This  PR adds `charts` entity for alarm `templates`. 
Health
1 - Compile this PR
2 - Create file `/etc/health/go.d/example.conf`:
```
jobs:
- name: go_example
````
3 - Create an alarm, for example, `/etc/netdata/health.d/example.conf`:
```
template: go_example
on: example.random
plugin: go.d
module: example
calc: $last_collected_t
units: boolean
charts: *random_0*
every: 1m
warn: $this != nan || $this == nan
info: go.d.plugin example module is up
to: sysadmin
```
4 - Start Netdata, you will receive an alarm.
5 - Comment the line `#charts: *random_0*` in the  previous alarm.
6 - Restart `health` running `netdatacli reload-health` or restart `netdata`.
7 - You will receive another alarm
8 - Finally set `charts` as `charts: !*random_0*`
9 - Repeat step 6
10 - You won't receive …
> Add `charts` to templates

- daemon/analytics.c
Fix memory leak
```
*** CID 370510:  Resource leaks  (RESOURCE_LEAK)
/daemon/analytics.c: 462 in analytics_gather_mutable_meta_data()
456         analytics_mirrored_hosts();
457         analytics_alarms_notifications();
458     
459         analytics_set_data(
460             &analytics_data.netdata_config_is_parent, (localhost->next || configured_as_parent()) ? "true" : "false");
461     
>>>     CID 370510:  Resource leaks  (RESOURCE_LEAK)
>>>     Failing to save or free storage allocated by "is_agent_claimed()" leaks it.
462         if (is_agent_claimed())
463             analytics_set_data(&analytics_data.netdata_host_agent_claimed, "true");
464         else {
465             analytics_set_data(&analytics_data.netdata_host_agent_claimed, "false");
466         }
467     
```
analytics …
> Fix coverity issue (CID 370510)

- .github/workflows/build-and-install.yml
- .github/workflows/packaging.yml
- .github/workflows/updater.yml
Our current GitHub plan limits us to 60 concurrent CI jobs. Because of the very high number of jobs being run in our agent CI, we are regularly running up against that limit and blocking other CI.
This PR limits the most egregious offenders within the agent CI to only run at most 8 jobs in parallel on a per-workflow basis. This makes the best-case scenario for CI run times somewhat worse, but in exchange improves the average CI run times.
area/ci
Behavior verified on this PR (looks like it’s working correctly, but it’s only visible when you actually start the CI process).
The choice of 8 concurrent jobs is largely arbitrary. It’s intended to provide enough of a limit to improve the common case without making the best case significantly worse than it currently is. The exact value may need …
> Limit maximum concurrent CI jobs to avoid blocking other CI.

- claim/claim.c
- database/rrd.h
- database/rrdhost.c
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
- Get a list of nodes stored in the database
- Update the node id for a host
- Check or retrieve the node id for a host
It adds support to set the `node_id` field of the  `node_instance` database table
aclk
database
- This is part of the new architecture design and provides basic functionality to be used in subsequent PRs
> Add functionality to store node_id for a host

- daemon/analytics.c
As @ilyam8 observed, the last analytics PR sends the whole `anonymous-statistics.sh` command we run to the log, including all the parameters, which can add up quickly to the size of logs. This PR reduces the logging to just the script, `action`, `action_result` and `action_data` information (as it practically was before adding parameters to the script).
Analytics
Observe that only the script, `action`, `action_result` and `action_data` are logged.
> Reduce send statistics logging

- web/server/static/static-threaded.c
Fixes #11081 
This PR fixes the reported problem with old OpenSSL version and multithreading webserver.
I am also using this PR to fix the tabulation that was completely wrong for the thread function.
Web server
1 - Compile this PR on an environment that has OpenSSL newer than `1.1.0.`
2 - Create TLS certificate and TLS key and store them inside `/etc/netdata/ssl/`, use the following command to generate them:
```bash
openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -sha512 -subj "/C=US/ST=Denied/L=Somewhere/O=Dis/CN=www.example.com" -keyout key.pem  -out cert.pem
```
3 - Change the permissions for:
```bash
bash-5.1$ ls -lh /etc/netdata/ssl/
total 8.0K
-rw-r--r-- 1 netdata netdata 1.3K Apr 14  2020 cert.pem
-rw------- 1 netdata netdata 1.7K Apr 14  2020 key.pem
```
4 - Run Netdata, …
> fix SSL random failures when using multithreaded web server with OpenSSL < 1.1.0

- netdata-installer.sh
Installation script does not build libwebsockets with IPv6 support
enabled. This results in Netdata Cloud being unreachable by agents
running in IPv6-only environments with Internet access via NAT64
gateway. 
This change adds `LWS_IPV6` CMake flag to libwebsockets build options
in netdata-installer.sh. Binaries built with that flag will be able to reach app.netdata.cloud
in environments where access to Internet via IPv4 is done through a NAT64 gateway.
Fixes #11079   
netdata-installer
aclk
1. Build and start Netdata agent on a IPv6-only machine with NAT64 gateway
2. Claim the node in Netdata Cloud
3. Check if the node is marked as reachable in Cloud panel
> netdata-installer.sh: Enable IPv6 support in libwebsockets

- collectors/cgroups.plugin/cgroup-network-helper.sh
- collectors/cgroups.plugin/cgroup-network.c
Fixes: #11088
`collectors/cgroups`
Tested by @Izorkin (https://github.com/netdata/netdata/issues/11088#issuecomment-832851379)
> cgroups: fix network interfaces detection when using `virsh`

- packaging/installer/methods/alpine.md
Improve installation method for Alpine
Documentation
- the `python` package doesn't exist since Alpine 3.5 (dec 2016), use `python3` instead
- create a proper start script instead of using `/etc/local.d`
> Improve installation method for Alpine

- collectors/cgroups.plugin/sys_fs_cgroup.c
SSIA
Fixes #11098
cgroups plugin
Restart Netdata. Check if the "waiting for discovery thread to finish..." message appears only once.
> Don't repeat the cgroup discovery cleanup info message

- daemon/analytics.c
- daemon/analytics.h
- daemon/anonymous-statistics.sh.in
Adds a new attribute `host_cloud_enabled` to posthog analytics. The attribute will be false if `--disable-cloud` was used during install, or `enabled = no` is defined in `/var/lib/netdata/cloud.d/cloud.conf`
Analytics
To test, enable debug with analytics debug flag `0x0000000080000000`, or observe the host's page on posthog.
If `--disable-cloud` is used, the attribute should be `false`.
If `enabled = no` is specified in `/var/lib/netdata/cloud.d/cloud.conf`, the attribute should also be `false`.
Otherwise, it should be `true`
> Add host_cloud_enabled attribute to analytics

- aclk/legacy/aclk_stats.c
This PR changes [`aclk_write_q`](https://github.com/netdata/netdata/blob/bebd56cd603bd4a2e68e71dd9021ea4e34c41dc1/aclk/legacy/aclk_stats.c#L125-L130) and [`aclk_cloud_req`](https://github.com/netdata/netdata/blob/bebd56cd603bd4a2e68e71dd9021ea4e34c41dc1/aclk/legacy/aclk_stats.c#L147-L152) units to KiB/s so our dashboard [auto-scale](https://github.com/netdata/dashboard/blob/a4bf51a827856ce68c897a8ee8fa6c5d378e584d/public/dashboard.js#L777-L923) these charts metrics properly.
`kB` is 1000 bytes, `KiB` is 1024 bytes. Those charts metrics are in `KiB`.
Before this PR:
`aclk/legacy`
No tests needed
> aclk/legacy: change aclk statistics charts units from kB/s to KiB/s

- collectors/cgroups.plugin/sys_fs_cgroup.c
- configure.ac
- libnetdata/libnetdata.h
The PR adds an additional check for the default cgroup mount point. It's a stopgap that fixes incorrect detection of cgroups v1, when `default-hierarchy=hybrid` but only a cgroups v2 hierarchy is mounted.
Fixes #11094
cgroups plugin
Run Netdata with cgroups v2 mounted on `/sys/fs/cgroup` and `default-hierarchy=hybrid`. Unified cgroups should be enabled and working.
> Check the version of the default cgroup mountpoint

- .github/workflows/dashboard-pr.yml
See #11072 and #11073 for info.
area/ci
General process is equivalent to https://github.com/netdata/helmchart/blob/master/.github/workflows/agent-pr.yml. Actual testing will require this PR to be merged, but is inherently non-destructive.
Closes: #11073
> Add a workflow to generate version bump PRs for the dashboard.

- netdata-installer.sh
Use `find_processors` to specify the number of jobs in make(1) when building `libwebsockets`.
area/build
Run netdata-installer.sh locally.
> Support mulitple jobs in make(1) when building LWS.

- daemon/analytics.c
This PR changes log level to `debug`
https://github.com/netdata/netdata/blob/e58768dfff3c2d4dc0382fc702ee1c4c1af30715/daemon/analytics.c#L304-L308
---
We usually ask users to `grep alarm-notify.sh` when debugging health notifications problems.
> Executing /opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.sh dump_methods
The line doesn't really provide any value and just an additional noise, see https://community.netdata.cloud/t/not-all-alarms-send-to-the-telegram/1263/3
`daemon/analytics`
- set `[global] -> debug flags = 0x0000000080000000`
- check `debug.log`
> analytics: reduce alarms notifications dump logging

- .github/workflows/docker.yml
This will automatically trigger the workflow in the netdata/helmchart repo that generates a PR to bump the agent version bundled with the helmchart when we bpulish a docker image for a release.
area/ci
Needs to be actually merged to be able to properly verify that it correctly triggers the workflow in netdata/helmchart, but there is no risk of it breaking the existing build infrastructure.
Actually having this integration was the roiginal intent of automating the process of generating the PRs in the netdata/helmchart repo, though it got kind of forgotten about until just recently.
> Automatically trigger Helmchart PR on agent release.

- database/rrd.h
- database/rrdset.c
Reduce the number of full chart update messages when a lot of charts are being deleted
aclk
- Start agent with memory mode RAM
- Set low chart obsoletion timeout (e.g. 20 seconds)
- Repeat the following a few times
- Start a docker container
- Wait a few seconds
- Stop the container
- Start the container to trigger chart obsoletion
- Notice low ACLK traffic in the corresponding graphs
> Reduce the number of ACLK chart updates during chart obsoletion

- collectors/freebsd.plugin/freebsd_sysctl.c
This fixes memory allocation errors on arm64
sysctl -t vfs.bufspace
vfs.bufspace: long integer
Same output on both amd64 and arm64
Thanks to Mikael Urankar for troubleshooting and providing a fix
Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>
> Use size_t instead of int for vfs_bufspace_count in FreeBSD plugin

- docs/guides/configure/performance.md
Added use cases in performance optimization that can warrant using memory modes `ram` or `none`. 
Docs
See it on the generated site.
I tried to add a link to https://learn.netdata.cloud/docs/agent/database for more info at the very end that would work both from github and on the site, but I don't think that's possible any more. @joelhans please free to improve.
> Add info on other memory modes to performance.md

- health/REFERENCE.md
Add initial sections in the documentation for the new `class`, `component` and `type` attributes, that the PR https://github.com/netdata/netdata/pull/10961 adds to the stock alarms configuration files.
Health
Not needed.
The documentation can be perhaps extended to provide information on how those attributes are used in the cloud.
> Add sections for class, component and type.

- collectors/python.d.plugin/postgres/README.md
- collectors/python.d.plugin/postgres/postgres.chart.py
* standby lag time
* average blocking transactions
It is such a nice project, we work on deploying it company wide (company has 1000+ servers). Our next step is monitoring postgres, but we found we lack some metrics - especially lag measured in seconds. I add info to doc, as it was not advertising standby info.
Also I included average number of blocking transactions per database - the rationale is that 'bad' transactions have the potential to impact many more transactions and effectively increase average more significantly than other queries.
python.d.plugin/postgres
I have run plugin after changes against our cluster and it looked fine.
> Adding more postgres metrics

- health/health.d/disks.conf
- health/health.d/net.conf
- health/health.d/ram.conf
- health/health.d/web_log.conf
Continuation of https://github.com/netdata/netdata/pull/10688
| Alarm       | Change      | Reason      |
| ----------- | ----------- | ----------- |
| [inbound_packets_dropped_ratio](https://github.com/netdata/netdata/blob/98c27ffbc5c04e853cb0e055e7b89eb0a4d45527/health/health.d/net.conf#L90-L105)      | increase packets trigger limit      | We calc using 10 min sum, 1k per min is ok for rx |
| [wifi_inbound_packets_dropped_ratio](https://github.com/netdata/netdata/blob/98c27ffbc5c04e853cb0e055e7b89eb0a4d45527/health/health.d/net.conf#L124-L139)      | increase packets trigger limit      | We calc using 10 min sum, 1k per min is ok for rx              |
| [10min_disk_backlog](https://github.com/netdata/netdata/blob/98c27ffbc5c04e853cb0e055e7b89eb0a4d45527/health/health.d/disks.conf#L162-L …
> health: make stocks alarms less sensitive (2)

- health/Makefile.am
- health/health.d/timex.conf
This PR adds an alarm for the system clock synchronization state.
It takes into account that `ntpd` needs several minutes to select a reliable time server and sync with it.
`health`
Requested in https://community.netdata.cloud/t/add-timex-alerts/1339
> health: add system clock synchronization state alarm

- collectors/python.d.plugin/anomalies/README.md
- collectors/python.d.plugin/anomalies/anomalies.conf
- Rename default job from 'local' to 'Anomalies'.
'Anomalies local' is not as nice as a 'Anomalies' menu item when using default settings and just enabling it for local node.
So by default users would then have this:
as opposed to the "Anomalies local" like here:
It's just cleaner and nicer to have it be called "Anomalies" as opposed to "Anomalies local" where the "local" part could just confuse people. 
collectors/python.d.plugin/anomalies
Tested locally on dev agent.
> rename default from job 'local' to 'anomalies'

- collectors/ebpf.plugin/ebpf_cachestat.c
- collectors/ebpf.plugin/ebpf_dcstat.c
- collectors/ebpf.plugin/ebpf_process.c
- collectors/ebpf.plugin/ebpf_socket.c
- collectors/ebpf.plugin/ebpf_swap.c
Fixes #11202
**collectors/ebpf.plugin/ebpf_process.c:**
Sometimes, ebpf_load_program may fail and return null pointer, then function ebpf_process_cleanup will be called,
bpf_link__destroy(probe_links[i]) will cause segfault, because the probe_links is null.
Same problems in **collectors/ebpf.plugin/ebpf_cachestat.c
collectors/ebpf.plugin/ebpf_dcstat.c
collectors/ebpf.plugin/ebpf_socket.c
collectors/ebpf.plugin/ebpf_swap.c
collectors/ebpf.plugin/ebpf_sync.c**
```
void *ebpf_process_thread(void *ptr)
{
netdata_thread_cleanup_push(ebpf_process_cleanup, ptr);
...........
...........
probe_links = ebpf_load_program(ebpf_plugin_dir, em, kernel_string, &objects, process_data.map_fd);
if (!probe_links) {
pthread_mutex_unlock(&lock);
goto endprocess;
}
...........
...........
endprocess: …
```
> fix ebpf.plugin segfault when ebpf_load_program return null pointer

- .github/labeler.yml
Add `ACLK` label if there are any "mqtt_websockets" changes.
Related #11196
`ci`
> labeler: add "mqtt_websockets" to the ACLK

- packaging/installer/netdata-updater.sh
SSIA, reported in https://github.com/netdata/netdata/pull/11157#issuecomment-850229556
Fixes: #11200
`installer/`
- clean install Netdata from the source **not in `/opt`**
- run `netdata-updater.sh` script
- check `.install-type` file, it shouldn't be empty
> fix `install_type` detection during update

- daemon/analytics.c
- daemon/anonymous-statistics.sh.in
This PR adds some checks on the execution of `anonymous-statistics.sh` script as discussed in #11115. It adds a check on the exit_code of `mypclose`, a check on `fp`, and tries to force both `curl` and `wget` to output the http response code (and check that too).
Analytics
On normal cases, no error should be reported in the log file.
If an error is found in either the exit code of `mypclose`, or an http response other than `200` is produced, it should be printed in the error.log
`wget`'s way of producing the http code is hacky... I don't know if we're comfortable forcing them to give us the http response and parsing it... If not, we can only keep the checks on `mypopen` and `fp`.
> Check return status of execution of anonymous statistics script

- claim/netdata-claim.sh.in
This PR changes claiming script exit code to 0 when 
- the claim was successful, and
- the agent could not be notified, and
- `-daemon-not-running` option was passed to the script
<details>
<summary>We execute claiming script before starting `netdata` process.</summary>
https://github.com/netdata/netdata/blob/e4f0ae2290a36bb1b9184fffac1e9ed1f707c52e/packaging/docker/run.sh#L23-L31
</details>
Docker restarts a container if the exit code is not 0.
`claiming`
Build custom image; install Netdata in k8s using the image; ensure there are no restarts and parent/children are connected to the Cloud.
Discovered it working on https://github.com/netdata/helmchart/pull/212
---
@Ferroin likely we shouldn't even try to use `netdatacli` if `-daemon-not-running` option is passed. If so then we need more …
> claiming: exit 0 when daemon not running and the claim was successful

- daemon/analytics.c
- daemon/common.c
- daemon/common.h
- daemon/unit_test.c
- database/rrd.h
- database/rrdhost.c
- database/sqlite/sqlite_functions.c
- health/health.h
- health/health_config.c
- health/health_json.c
- streaming/receiver.c
- streaming/rrdpush.c
- streaming/rrdpush.h
- streaming/sender.c
For the cloud to be able to include an agent local time in the alerts email notification, the agent needs to send the UTC offset in seconds for each host (parent and/or children), together with the abbreviated time zone format. It also constructs and sends an  `edit_command` string, which when parsed by the cloud, will appear on the email message to provide the user with a copy-paste command to use to edit the alert's configuration:
The UTC offset is calculated based on the string returned from `strftime` using the `%z` field, i.e. from a string with format `+hhmm` or `-hhmm`. For example, for `+0300` the UTC offset will be `10800`.
The `edit_command` string is constructed from the `source` string, and includes the line number of the configuration file to edit. Example: `sudo …
> Provide UTC offset in seconds and edit health config command

- database/engine/journalfile.c
When a read fails when processing dbengine journal files, the agent terminates by calling fatal.
This will ignore the error skip the rest of the transactions in that journal file and attempt to continue.
database
- This is hard to reproduce (probably caused by disk/file corruption). However any attempt to alter
the journal file is almost always gracefully handled with a CRC error warning as in
`netdata ERROR : MAIN : Transaction 16 was read from disk. CRC32 check: FAILED`
> Ignore dbengine journal files that can not be read

- daemon/main.c
- database/rrdhost.c
When the agent is built without dbengine support (on purpose or because the dependencies are not met) then if
memory mode dbengine is specificed in the netdata.conf, the agent will fail to start with the message
`RRD_MEMORY_MODE_DBENGINE is not supported in this platform.`
with this PR the dbengine memory mode will be ignored and memory RAM will be used instead
and the following  message will be logged
`RRD_MEMORY_MODE_DBENGINE is not supported in this platform. The agent will use memory mode ram instead.`
This PR will also tries to further pinpoint failures during `rrd_init` and whether it happens during
- sql_init_database
- rrdeng_init
Statistics show a large number of agents going into a restart loop because dbengine is not available. 
agent
- Compile agent without dbengine support …
> Use memory mode RAM if memory mode dbengine is specified but not available

- database/engine/rrdengineapi.c
- database/engine/rrdengineapi.h
- database/rrd.h
- database/rrddim.c
- database/rrdhost.c
- database/rrdset.c
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
- web/api/formatters/rrd2json.c
- The metric_uuid is now stored as `uuid_t` in the dimension state instead of `uuid_t *`
It used to be compiled only if dbengine was available but now it is used in all memory modes so no need to do the extra malloc
- Remove `create_dimension_uuid` and include the functionality in `find_dimension_uuid`
database
- There shouldn't be any change in the functionality
- Start the agent with memory mode dbengine (the metric UUID is directly linked with stored metrics in dbengine)
- Observe metrics being collected
- Build an agent with the PR
- Stop old agent, restart with the PR applied
- You should have access to the old metrics
> Reduce memory needed per dimension

- database/rrdcalctemplate.c
This PR changes [alarm-line-charts](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-charts) matching from `chart.id OR chart.name` to `chart.name`.
<details>
<summary>Chart name is on the dashboard and as a user I want the pattern to match against it.</summary>
</details>
We convert some characters to `_`, so id sometimes != name.
```JSON
"id": "cgroup_bla-cloud-crdb-cdc-streamer-service-bla.mem_utilization",
"name": "cgroup_bla_cloud_crdb_cdc_streamer_service_bla.mem_utilization",
```
In that case, I have to **write 2 patterns to exclude the char**t. That is pretty confusing.
`health/`
- ensure `charts` pattern matches against chart name only.
> health: fix alarm-line-charts matching

- health/health_log.c
It appears that in some `health-log.db` files, there are random characters in the `family` field of the lines. Sometimes those random characters will contain a tab character, so the count of fields will be wrong. When this happens, the code that reads `class`, `component` and `type` gets executed, and result in a crash... This is fixed by reading these 3 items when at least 31 entries are in a line (instead of previously 29).
However, at that point, because of the extra tab, fields have been most likely assigned to wrong variables, and those characters even if read in correct variables will break json. So a check for non-ascii characters is added, and when it detects one, it will ignore the whole line.
We could just keep the change in line `388`, and it will prevent a crash, but there …
> Check for non ascii characters in health log

- collectors/python.d.plugin/python.d.plugin.in
This PR changes loading stock/user `python.d.plugin` configuration files logic (python.d.conf).
❗ yes, the changes concern only plugin configuration loading, not its modules (e.g.: apache.conf, mysql.conf) 
Current:
- load user config if it exists.
- if not load stock config.
After this PR:
- load user config if it exists.
- load stock config file.
- merge user into stock.
In addition, `python.d.plugin` no longer fails to start if there are any problems on loading configuration files (e.g.: invalid YAML syntax), it starts and uses internal defaults.
---
Motivation: the feature/change was requested on our forum. See the following topics: 
- [override-config-files](https://community.netdata.cloud/t/override-config-files/1342)
- [local-support-for-on-off-plugins](https://community.netdata.clo …
> python.d: merge user/stock plugin configuration files

- health/health.c
- health/notifications/alarm-notify.sh.in
This PR adds the new email template for notifications.
Health
Requires an agent host to be able to send emails (sendmail, etc), and the agent to be configured to send emails on alerts.
There are a few things to notice in the emails if they are correct:
* The "Go to chart" link if it's ok.
* If global and local time are ok.
* The edit command if it correctly executes on the node.
* If the small table on the bottom of the email correctly contains the list of other active alerts, along with the time they are active for.
> New email notification template

- health/health.d/cockroachdb.conf
We used [cockroach/monitoring/rules/alerts.rules.yml](https://github.com/cockroachdb/cockroach/blob/master/monitoring/rules/alerts.rules.yml) as a source for alarms. Since then several alarms were deleted from the file, this PR removes them from our repo.
`health/`
Not needed
[`cockroachdb_sql_executed_statements_total_last_5m`](https://github.com/netdata/netdata/blob/e02095b438ab8e4fdc55313e8c7ed5bd7de50835/health/health.d/cockroachdb.conf#L88-L99) alarm seems to be false positive according to our experience and it doesn't work properly when there are 2+ CockroachDB instances on a host (health monitoring variables indexes limitation).
> health: update cockroachdb alarms

- daemon/common.h
PR #11225 broke `--disable-cloud`.
Build with `--disable-cloud` this warnings should be gone:
```
database/rrdhost.c:1018:18: warning: implicit declaration of function 'add_aclk_host_labels'; did you mean 'reload_host_labels'? [-Wimplicit-function-declaration]
1018 |     label_list = add_aclk_host_labels(label_list);
|                  ^~~~~~~~~~~~~~~~~~~~
|                  reload_host_labels
database/rrdhost.c:1018:16: warning: assignment to 'struct label *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
1018 |     label_list = add_aclk_host_labels(label_list);
|                ^
```
> Fixes error on --disable-cloud

- daemon/analytics.c
- daemon/buildinfo.c
Send correct `aclk` implementation to posthog, since now both variants are built together.
Analytics
Use the configuration variable `aclk implementation` to switch between `legacy` and `ng`, and observe that it get's picked by analytics correctly. If none of the aclk implementation is present, it will send an empty string.
> Send correct aclk implementation used by agent to posthog.

- collectors/freebsd.plugin/freebsd_getifaddrs.c
Add support for Intel 2.5G and Synopsys DesignWare nic (and variants) driver
Ref: https://reviews.freebsd.org/D30668
https://github.com/freebsd/freebsd-src/blob/master/sys/dev/dwc/if_dwc.c
Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>
> Add more nics to FreeBSD plugin

- collectors/slabinfo.plugin/slabinfo.c
Instead of only displaying chart during the first iteration, keep track of number of parsed columns, and refresh the chart when that number changes to account for kernel modules added after initial discovery.
Fixes #11254 
slabinfo
- start slabinfo collector,
- grep on "CHART"
- load a module (like kvm)
- unload the module
Both actions should regenerate the CHART
> slabinfo: Handle slabs added after discovery

- aclk/README.md
After recent commits both ACLK implementations can be compiled in the agent. Adds info into the docs on how to choose which one to use and how to verify which one is used
docs
Read the docs and see if the info is understandable for our users.
> Updates the docu with info about dual ACLK

- packaging/installer/install-required-packages.sh
See https://community.netdata.cloud/t/nodes-shown-as-unreachable/1345/61?u=austin_hemmelgarn
area/packaging
CentOS 8 CI now passes.
> Fix libjudy installation on CentOS 8.

- packaging/installer/kickstart-static64.sh
- packaging/installer/methods/kickstart-64.md
Fixes: #11228
Making this PR because #11246 was closed by its author.
using @Ferroin comment as a fix
> The correct fix here is to wrap the whole function body in a conditional checking for the existence of the file referenced by ${install_type_file}
`packaging/`
@Ferroin a reminder - upload kickstart filed needed after the merge.
> fix kickstart-static64.sh install script fail when trying to access `.install-type` before it is created

- packaging/installer/install-required-packages.sh
The version of CMake currently shipped in CentOS 8 has an incorrect version limit in it0s dependency on libarchive. As a result, building LWS without an up to date copy of libarchive on such a system will result in a build failure.
This explicitly updates libarchive so that CMake will work properly. It can be removed again when we finally end support or the legacy ACLK code that depends on LWS.
area/packaging
CentOS 8 CI checks pass again.
> Explicitly update libarchive on CentOS 8 when installing dependencies.

- aclk/aclk_api.c
Switches NG to be the default.
ACLK
If both ACLKs available NG will be chosen if user doesn't specify otherwise in `netdata.conf`
> makes ACLK-NG the default if available

- .github/workflows/build-and-install.yml
- .github/workflows/updater.yml
This adds Alpine 3.14 (released over the weekend) to our CI checks and removes Alpine 3.10 (EOL for just short of two months).
area/ci
Checks in CI pass.
> Add Alpine 3.14 to CI.

- aclk/legacy/aclk_query.c
As we are not maintaining ACLK Legacy anymore we want to keep it as a fallback without any significant changes. For that reason, #10649 was closed unmerged (not to have a big change in Legacy same time as moving to NG). This removes the error message that is not an error anymore as plans on the Cloud side were changed and version negotiation will never be implemented (+new cloud arch coming).
This is done to remove users confusion so they not consider it as something went wrong..
> fixes confusing error in ACLK Legacy

- daemon/analytics.c
- daemon/analytics.h
- daemon/anonymous-statistics.sh.in
- daemon/buildinfo.c
- daemon/daemon.c
- daemon/main.c
- exporting/exporting_engine.c
This PR adds a few more attributes to posthog, and makes a few changes.
Changes:
* Moves `set_late_global_environment()` before starting any threads to make sure that any events from other threads (e.g. exporting) carries those attributes.
* Provides the full agent version to analytics, instead of the short string of just the major version.
* Changes the first `META` event to be `META_START`
Adds:
* `netdata_is_in_ci`: To indicate whether this agent is in a CI environment.
* `config_oom_score`: The OOM score of the agent (assuming it can be read, and set).
* `netdata_install_type`: Tries to read the string from the `.install-type` file, in /etc/. If it doesn't exist, it will be set to an empty string.
* `config_private_registry_used`: If the user has specified a different than the default …
> Extra posthog attributes

- daemon/analytics.c
Removes the check with `access` for the `.install-type` file. The file will be opened right after, so it doesn't make much sense to be there, and fixes a coverity warning on this part.
Analytics
> Remove access check for install-type file

- collectors/ebpf.plugin/ebpf.c
After we have a short talk using Slack, I am bringing this PR to remove the possibility to have multiple eBPF plugins running in parallel.
I could not recreate the cited problem using kernel 5.12 many times, when the problem happened, it was thanks the fact I started another `netdata` instance before `eBPF.plugin` to be finished.
ebpf.plugin
1 - Compile this PR
2 - Start Netdata, take a look at new file `/usr/libexec/netdata/plugins.d/ebpf.d/ebpf.pid`, it must have the current `PID` of `ebpf.plugin`
3 - Restart netdata and verify that you have only one `ebpf.plugin` running and the PID was updated inside the file.
> eBPF plugin remove parallel plugins

- backends/prometheus/README.md
- exporting/prometheus/README.md
Discovered in https://community.netdata.cloud/t/feedback-or-suggestion-on-export-metrics-to-prometheus/1492, see the topic for details.
I updated the rule expression to be == [`10min_cpu_usage`](https://github.com/netdata/netdata/blob/365a8fb8bad397856f110595a65373c0b5ec47a1/health/health.d/cpu.conf#L4-L18) alarm.
❗ see [changes with hidden whitespaces](https://github.com/netdata/netdata/pull/11309/files?w=1)
`backends/`
`exporting/`
[Tested by our community member](https://community.netdata.cloud/t/feedback-or-suggestion-on-export-metrics-to-prometheus/1492/14).
> [docs] fix prometheus node cpu alert rule

- daemon/main.c
- database/rrd.h
- streaming/rrdpush.c
- streaming/sender.c
- web/api/web_api_v1.c
Adds a hop count for children in the system_info of the host structure. 
The local agent is hop 0 and each time a child connects to a parent it will send a `hops` variable that will +1 of its hop count.
The `hops` parameter is added to the initial STREAM connect command (child --> parent)
A parent that accepts a STREAM command (child) will initially assume that the hop count will be 1 and then:
-  Remain 1 (if the child runs an older version of the agent and therefore cannot supply a hops parameter)
- Update it to the value supplied in the STREAM command
If a child running a version with this PR connects to a parent running an older version, then the parents error.log will
have the following
```
STREAM [receive from XXXX]:nnnnnn]: request has parameter 'hops' = '1', which is not used. …
```
> Add hop count for children

- .gitmodules
- CMakeLists.txt
- Makefile.am
- aclk/aclk.c
- aclk/aclk.h
- aclk/aclk_api.c
- aclk/aclk_api.h
- aclk/aclk_query.c
- aclk/aclk_query_queue.c
- aclk/aclk_query_queue.h
- aclk/aclk_rx_msgs.c
- aclk/aclk_rx_msgs.h
- aclk/aclk_tx_msgs.c
- aclk/aclk_tx_msgs.h
- aclk/aclk_util.c
- aclk/aclk_util.h
- aclk/legacy/agent_cloud_link.c
- aclk/legacy/agent_cloud_link.h
- aclk/schema-wrappers/connection.cc
- aclk/schema-wrappers/connection.h
- aclk/schema-wrappers/node_connection.cc
- aclk/schema-wrappers/node_connection.h
- aclk/schema-wrappers/node_creation.cc
- aclk/schema-wrappers/node_creation.h
- aclk/schema-wrappers/schema_wrapper_utils.h
- aclk/schema-wrappers/schema_wrappers.h
- configure.ac
- database/sqlite/sqlite_functions.c
- database/sqlite/sqlite_functions.h
- streaming/receiver.c
Implements new NodeInstance connectivity-related messages as per new Cloud Architecture specs.
Currently under dev only flag until chart messages are also ready. Use `-DACLK_NEWARCH_DEVMODE` with staging/testing only for now. Future PRs will allow this to be switched by Cloud `/env`endpoint
The review has to be done by somebody who read the new cloud architecture docs.
Additionally this PR introduces:
- ability to use old queries in new architecture
- ability to query child by node_id
Fixes netdata/product#2126
Fixes netdata/product#2132
ACLK-NG
use staging, not production!
compile with `-DACLK_NEWARCH_DEVMODE`
can compile with `#define ACLK_LOG_CONVERSATION_DIR "/home/[SOMETHING]/MSG_CAPTURE"` to get all messages sent and received recorded
You can view the recording using this internal …
> ACLK-NG New Cloud NodeInstance related msgs

- Makefile.am
- aclk/aclk_query.c
- aclk/aclk_query.h
- aclk/aclk_query_queue.c
- aclk/aclk_query_queue.h
Fixes https://github.com/netdata/netdata/issues/10746
Logs a message to access.log for HTTP messages for aclk-ng similar to aclk-legacy.
aclk
Compile your local netdata agent with ACLK-NG enabled.
Connect your local netdata to some Netdata cloud endpoint via ACLK.
Go & view your claimed node on the cloud, scrolling around different charts.
Tail the access.log file to see logs like this:
```
2021-07-07 11:29:45: 0: 56495 '[ACLK]:0' 'DATA' (sent/all = 1729/14555 bytes -88%, prep/sent/total = 3.41/2.52/5.93 ms) 200 '/api/v1/data'
2021-07-07 11:29:48: 0: 56496 '[ACLK]:1' 'DATA' (sent/all = 1570/12875 bytes -88%, prep/sent/total = 0.12/1.47/1.60 ms) 200 '/api/v1/data'
2021-07-07 11:29:48: 0: 56496 '[ACLK]:1' 'DATA' (sent/all = 1743/14567 bytes -88%, prep/sent/total = 0.76/4.76/5.53 ms) 200 …
```
> Add HTTP access log messages for ACLK-NG

- packaging/docker/run.sh
Improve the `ENTRYPOINT` script so that it auto-detects the correct PGID for the virtualization technology. This is required for correct name resolution. 
Beforehand, the user must supply the correct PGID as an environment variable. Now it detects the PGID by reading the appropriate `.sock` file, e.g `/var/run/docker.sock`. 
Ideally, we should add support for the most widely used virt engines (e.g podman, LXD containers, etc.)
`/packaging/docker/run.sh`
1. Create a container with a new dockerfiler, based on `netdata/netdata` and supply a new ENTRYPOINT, using the edited `run.sh` script. Example that I am running ATM: https://github.com/OdysLam/home-urbit/tree/master/netdata
> Auto-detect PGID in Dockerfile's ENTRYPOINT script

- Makefile.am
This ensures `aclk-schemas` submodule files are distributed in the `dist` tarball.
Fixes #11337
Fixes netdata/product#2193
netdata build system
get git submodules (`git submodule update --init --force --recursive`), build agent and then run `make dist`. The generated tarball should now contain `aclk/aclk-schemas` folder with all proto files in it.
> Adds aclk-schemas to dist_noinst_DATA

- collectors/python.d.plugin/postgres/README.md
- collectors/python.d.plugin/postgres/postgres.conf
According to [this](https://github.com/netdata/netdata/blob/77c07842b1111576f521e8ee23fe0494202f31d6/collectors/python.d.plugin/postgres/postgres.chart.py#L172), postgres at version 11 is compatible
> add postgresql version to requirements section

- aclk/aclk_query.c
- aclk/aclk_query_queue.c
- aclk/aclk_stats.c
- aclk/aclk_stats.h
Fixes https://github.com/netdata/netdata/issues/10747
This PR adds 2 charts:
- `netdata.aclk_cloud_req_http_type` will show a breakdown of HTTP query types, e.g. `/api/v1/data` vs. `/api/v1/chart` etc.
- `netdata.aclk_cloud_req_type` will show a breakdown at a higher-level, e.g. `http` vs `alarm_update` vs `metadata_alarms` etc. This is based off of the entries found in `aclk/aclk_query.c#aclk_query_handlers`.
aclk
Simply go to the ACLK chart submenu and see these new charts.
> Add ACLK-NG cloud request type charts

- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
* Use the correct path for the claiming script when installing to a non-default installation prefix with `kickstart.sh`.
* Just assume that `install-required-packages.sh` knows if it can install packages on a given OS or not instead of trying to decide that in `kickstart.sh`.
area/packaging
Both of these issues broke things on macOS. The version of `kickstart.sh` from this PR should now properly handle dependencies there and properly claim the node.
> Assorted kickstart install fixes.

- configure.ac
This eases build for systems that do not have google protobuf available.
By default bundled lib will be used if present and system one as fallback. This behaviour can be changed by:
```
--with-bundled-protobuf -> only use bundled one and fail if cannot be used
--without-bundled-protobuf -> use only system shared lib
```
build system
Provide protobuf built from source to `externaldeps/protobuf` folder. Should be used by default if present instead of shared lib.
Can verify by `ldd ./netdata | grep proto`
> Allows bundled protobuf

- health/notifications/alarm-notify.sh.in
`sendmail` from `busybox` does not support the `-F` parameter (setting the full name of the email sender), that the real `sendmail` command does. This patch will try to better check for this, by running `sendmail -F` and checking if the output of this contains `option requires an argument`.
Fixes #11261 
Health
Set `EMAIL_SENDER` in `health_alarm_notify.conf` to something like `MyName some@email.com`. 
Running in a system where `sendmail` is a symlink to `busybox` it won't set the parameter, and no errors should occur.
Running in a system where `sendmail` is a real binary, it should set the name of the email sender to `MyName`.
Real sendmail when run as `sendmail -F` returns: `sendmail: option requires an argument -- F`.
When run inside our docker instance, it returns `sendmail: …
> Check if sendmail supports -F parameter

- health/notifications/alarm-notify.sh.in
Fixes: #11354
`health/`
- configure [msteams](https://github.com/netdata/netdata/tree/master/health/notifications/msteams#microsoft-teams) with multiple channels.
- run `./alarm-notify.sh test`.
- ensure the script tries to send data to all the channels.
> fix sending MS Teams notifications to multiple channels

- collectors/ebpf.plugin/ebpf_vfs.c
This PR is fixing a wrong reference present in our code, users are not affected by this wrong reference, because `process` and `VFS` right now have the same number of elements, but this will change with next PRs, so I am fixing this here, else it will be necessary to change `VFS` files when I am changing `process` files.
ebpf.plugin
1 - Compile the branch
2 - Verify that all VFS charts are on dashboard.
It is not necessary to test on different kernel versions.
> FIX index reference

- health/health.d/cockroachdb.conf
This PR:
- fixes `cockroachdb_unavailable_ranges` alarm description.
- adds `cockroachdb_underreplicated_ranges` alarm.
`health/`
Not really needed.
> health: fix cockroachdb replication alarms

- .github/workflows/build-and-install.yml
- .github/workflows/packaging.yml
- .github/workflows/updater.yml
To be merged when Ubuntu 20.10 goes EOL in 2021-07-22.
area/ci
n/a
> Remove Ubuntu 20.10 from CI checks.

- health/health.d/ram.conf
This PR disables [oom_kill alarm](https://github.com/netdata/netdata/blob/0c7db731f8dabbd8debe668f5d8fe60ebffb7878/health/health.d/ram.conf#L49-L59) for Kubernetes nodes.
Feedback from @netdata/infra: oom kill is not a warning event in Kubernetes in general (this alarm tracks the number of oom kills per host, not specific containers). It is expected to have some containers get killed by OOM killer from time to time.
`health/`
- `oom_kill` works if the node is not k8s node.
> disable oom_kill alarm if the node is k8s node

- health/health.d/gearman.conf
It is [Pending](https://github.com/netdata/netdata/blob/e58e59c0f4848a100e9390f8234a83e7b1368c19/collectors/python.d.plugin/gearman/gearman.chart.py#L26), not Queued.
`heath/`
Not needed.
> fix `gearman_workers_queued` alarm

- netdata.spec.in
- packaging/bundle-ebpf.sh
This stops trying to make the eBPF build conditional in the RPM spec file, as all the distros we’re building for are supported by our code. This, in turn, results in actually including eBPF support in our RPM packages.
A check is also added to the script used for bundling the eBPF programs to avoid installing them if the eBPF plugin did not get built for some reason.
area/packaging
The packages can be built for testing by running `docker run -it --rm -v $PWD:/netdata -e VERSION=0.1 netdata/package-builders:fedora34` in the root of the Netdata source directory (you can replace `fedora34` with another distro and version number if desired, though do note that our CentOS 8 package builds are currently broken for reasons unrelated to this PR), which will put the built packages in the …
> Properly handle eBPF plugin in RPM packages.

- aclk/aclk.c
With Legacy Cloud, some big single JSON payloads can be bigger than the buffer. This allows the buffer to grow on the next connection with a maximum limit.
This is a workaround for now. The final solution will not need this buffer at all (its size will be 0Bytes). Also, the new cloud architecture doesn't try to do crazy things like send 10MB single message to the cloud.
ACLK
Make your charts list `/api/v1/charts` sth like 5MB long. After some time agent should connect to the cloud.
Don't `ACLK_NEWARCH_DEVMODE`
> Allows ACLK-NG to grow MQTT buffer

- collectors/ebpf.plugin/ebpf_filesystem.c
- web/gui/dashboard_info.js
We are accepting Ilya's [suggestion](https://github.com/netdata/netdata/pull/11348#issuecomment-882898320) and this PR is centralizing Latency description for eBPF latency charts.
ebpf.plugin
1 - Enable filesystem inside `/etc/netdata/ebpf.d.conf`:
```
filesystem = yes
```
2 - Compile this Branch
3 - Access dashboard using `private mode` or forcing browser reload to see new description.
It is not necessary to test on different kernels, because we are changing only dashboard.
> Ebpf latency description

- netdata-installer.sh
This adds parallelization of the builds of the bundled dependencies (this provides a few percent build time reduction on most systems), and switches them all to use the same version of `make` that Netdata will be built with (this changes nothing on most systems, but means that we will now uniformly use `gmake` on BSD systems).
area/packaging
CI passes without issue.
The actual performance difference here is rather dependent on the specifics of the system it’s being tested on. On my lapto, running with `/tmp` in memory, 12 CPU cores, and exceedingly fast NVMe storage, it actually slows down the build by about a tenth of a second. Artificially limiting the storage bandwidth to match up with a typical SATA III SSD causes this to break even, and limiting it to about 1/5 of that (roughly like …
> Update handling of builds of bundled dependencies.

- collectors/charts.d.plugin/ap/ap.chart.sh
- collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh
- collectors/charts.d.plugin/charts.d.plugin.in
- collectors/charts.d.plugin/example/example.chart.sh
- collectors/charts.d.plugin/libreswan/libreswan.chart.sh
- collectors/charts.d.plugin/opensips/opensips.chart.sh
- collectors/charts.d.plugin/sensors/sensors.chart.sh
Fixes part of #11388
ssia, this is needed for accounting plugins usage statistics.
All the changes follow [external plugins API](https://learn.netdata.cloud/docs/agent/collectors/plugins.d#chart):
> CHART type.id name title units [family [context [charttype [priority [update_every [options [plugin [module]]]]]]]]
"module" is the last parameter (12th).
`collectors/charts.d.plugin`
Tested using (only) [example](https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin/example#example) module.
```cmd
[ilyam@pc ~]$ curl -s localhost:19999/api/v1/info | jq '.collectors[] | select(.plugin=="charts.d.plugin")'
{
"plugin": "charts.d.plugin",
"module": "example"
}
```
> charts.d.plugin: set "module" when sending CHART

- collectors/ebpf.plugin/ebpf_disk.c
We received a report on our [fórum](https://community.netdata.cloud/t/compiler-warning-about-strncpy/1568) that when eBPF plugin is compiled using an old GCC version the following warning is shown:
```
GEN      netdata
In function 'update_disk_table',
inlined from 'read_local_disks' at collectors/ebpf.plugin/ebpf_disk.c:347:13:
collectors/ebpf.plugin/ebpf_disk.c:292:9: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
strncpy(disk_list->family, name, length);
^
collectors/ebpf.plugin/ebpf_disk.c: In function 'read_local_disks':
collectors/ebpf.plugin/ebpf_disk.c:288:18: note: length computed here
length = strlen(name);
^
In function 'update_disk_table',
inlined from 'read_local_disks' at collectors/ebpf.plugin/ebpf_disk.c:347:13: …
```
> Remove warning when GCC 8.x is used

- exporting/README.md
- exporting/clean_connectors.c
- exporting/exporting.conf
- exporting/exporting_engine.h
- exporting/graphite/README.md
- exporting/graphite/graphite.c
- exporting/init_connectors.c
- exporting/json/README.md
- exporting/json/json.c
- exporting/opentsdb/README.md
- exporting/opentsdb/opentsdb.c
- exporting/prometheus/remote_write/README.md
- exporting/prometheus/remote_write/remote_write.c
- exporting/read_config.c
- exporting/tests/exporting_doubles.c
- exporting/tests/exporting_fixtures.c
- exporting/tests/test_exporting_engine.c
Two new options were added to the configuration of the Prometheus remote write and HTTP versions of Graphite, JSON, OpenTSDB exporting connectors
```
username = my_username
password = password
```
The credentials are used for basic HTTP authentication.
Closes #11382
1. Configure a Graphite exporting connector with basic HTTP authentication credentials
```
[graphite:http:my_graphite_instance]
enabled = yes
destination = localhost:2003
username = testuser
password = testpasswd
send charts matching = system.processes
```
2. Check the output of `nc -l -p 2003` - the HTTP headers should contain
```
Authorization: Basic dGVzdHVzZXI6dGVzdHBhc3N3ZA==
```
> Add HTTP basic authentication to some exporting connectors

- backends/prometheus/README.md
Just removing an extra 's' in the docs :)
Btw. I've tested that "source" without "s" is indeed correct.
> Docs: Remove extra 's'

- collectors/statsd.plugin/statsd.c
Fixes a coverity warning 
```
*** CID 372222:  Security best practices violations  (STRING_OVERFLOW)
/collectors/statsd.plugin/statsd.c: 1222 in statsd_readfile()
1216     
1217                         if (!strncmp(
1218                                 filename,
1219                                 netdata_configured_stock_config_dir,
1220                                 strlen(netdata_configured_stock_config_dir))) {
1221                             char tmpfilename[FILENAME_MAX + 1];
>>>     CID 372222:  Security best practices violations  (STRING_OVERFLOW)
>>>     You might overrun the 4097-character fixed-size string "tmpfilename" by copying "filename" without checking the length.
1222                             strcpy(tmpfilename, filename);
1223 …
```
> Fix coverity issue 372222

- Makefile.am
- configure.ac
During review of https://github.com/netdata/netdata/pull/11374 @stelfrag noticed on 32 bit Raspbian `netdata` binary will fail to link due to missing libatomic which protobuf needs on some systems (like RPi 32bit).
If bundled/static protobuf is going to be used:
- Detects the need for `-latomic` using same mechanism as protobuf does during build
- links it if detected necessary
Buildsystem
- static protobuf possible to be used on 32bit RPi
- latomic added as shared lib dep check with `ldd netdata`
On regular system like AMD64 Fedora 34 latomic is not needed and should not be linked.
When system protobuf is used (as shared library) this check is skipped entirely and latomic is not linked
> Fix bundled protobuf linkage on systems needing -latomic

- web/gui/dashboard_info.js
We discovered that it is not possible to calculate messages currently in the queue using ["queue_message_*"](https://github.com/netdata/go.d.plugin/blob/3e6dd58663d8d5a4803fc2cdb9f433c411d91f52/modules/vernemq/metrics.go#L105-L109) metrics.
"queue_messages_current" metric is [removed](https://github.com/netdata/go.d.plugin/pull/601) from `vernemq` collector.
`web/gui`
Not needed
> remove "vernemq.queue_messages_in_queues" from dashboard_info.js

- health/Makefile.am
When runing `autoreconf -ivf` on netdata source you get annoying warning
```
health/Makefile.am:47: warning: whitespace following trailing backslash
```
This removes it
trivial, run `autoreconf -ivf` warning mentioned above should not be present anymore
> minor - Remove autoreconf warning

- packaging/installer/kickstart-static64.sh
- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart-64.md
- packaging/installer/methods/kickstart.md
This adds code to allow for using the kickstart script to claim existing installs of Netdata.
For this code to be run, the following conditions must be met:
* The user must supply correct claiming options.
* The user must not request a reinstall.
Under such circumstances, if the script can find an existing install of the correct type (using the same logic used to prevent accidental duplicate installs), it will attempt to run the claiming script from that install with the correct claiming arguments and then exit.
area/packaging
See the description. When invoked correctly on a system with an existing install, the kickstart scripts from this PR should attempt to run the claiming script from that install.
Fixes: #11346 
A sizable chunk of the changes here are just moving the claiming code in …
> Added support for claiming existing installs via kickstarter scripts.

- .github/workflows/repoconfig-packages.yml
This got missed when removing it from CI.
area/ci
n/a
> Remove Ubuntu 20.10 from repository config package builds.

- .github/workflows/packaging.yml
- .github/workflows/repoconfig-packages.yml
This properly uses only the file name instead of the full path when attempting to delete packages on PackageCloud in preparation for uploading new ones.
area/ci
n/a
This should get rid of the bogus build failure messages we get when A new build is made with no changes.
> Properly handle reuploads of packages to PackageCloud.

- configure.ac
- netdata-installer.sh
This significantly speeds up the build process (cutting build times roughly in half) and avoids strange linking errors such as what we’re seeing with Debian 9 in #11374.
area/build
Verified that the build still works correctly without LTO and that the CI runs much faster.
We _might_ consider enabling this again at some time in the future, but right now we can’t even quantify the performance benefits of using LTO.
Users who _really_ want this can still enable it by passing `--enable-lto` to the installer or configure script.
> Default to not using LTO for builds.

- collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh
Fixes: #11434
Fix an inconsistent status check on `apcupsd`. After PR #8688, it checks for "COMMLOST" or "SHUTTING DOWN" to check if ups is online, but the PR missed the same check on the `apcupsd_update()` function.
`apcupsd`
I created a file with output from `apcaccess` and run through all possible values for status. Now it consider online all options for status except "COMMLOST" or "SHUTTING DOWN".
I got these alarms(`apcupsd_last_collected_secs`) for several months, but I didn't dig, just ignored them. Today I got upset and started looking what was happening, for my surprise, it was indeed a bug.
> Fix issue #11434 regarding inconsistent status check on  component.

- database/sqlite/sqlite3.h
Update the SQLite version from v3.33.0 to v3.36.0
SQLite build from source using
`configure --disable-load-extension --enable-memsys5 --enable-all --enable-update-limit --enable-tempstore=yes --enable-shared=no --enable-static=no`
The generated sqlite3.c / sqlite3.h files added under database/sqlite
Included necessary definitions
```
#define SQLITE_ENABLE_UPDATE_DELETE_LIMIT 1
#define SQLITE_OMIT_LOAD_EXTENSION 1
#define SQLITE_ENABLE_DBSTAT_VTAB 1
```
and fix 4 compilation warnings 
```
atabase/sqlite/sqlite3.c:205538:9: warning: unused parameter 'pAux' [-Wunused-parameter]
database/sqlite/sqlite3.c:205594:40: warning: unused parameter 'tab' [-Wunused-parameter]
database/sqlite/sqlite3.c:206076:27: warning: unused parameter 'idxStr' [-Wunused-parameter] …
```
> Update SQLite version from v3.33.0 to 3.36.0

- .github/workflows/build-and-install.yml
- .github/workflows/updater.yml
We’ve never really officially supported it and it’s causing CI failures due to upstream infrastructure issues.
This is not removing any of our code supporting it, just the CI checks for ClearLinux. Officially, we still have some level of support, but it’s community supported.
area/ci
n/a
> Remove ClearLinux from CI.

- database/sqlite/sqlite_aclk.c
- Correctly check that an item does not exist in the aclk thread list and ignore it (instead of accessing
invalid memory and crash)
- Ignore error when attempting to wake up event loop (do not fatal)
aclk
- The code is not active yet
> Fix list corruption in ACLK sync code and remove fatal

- configure.ac
- netdata-installer.sh
This PR adds a check in `netdata-installer.sh` for the status of configure and make phases of protobuf. If any of those fails, it makes sure it returns back to original directory to continue with the rest of the installer.
It also does not bail out from the configure phase of the agent if bundled protobuf is not found. ACLK Legacy should be available in this case, since the builds with NG are separate.
Installer
If dependencies are there (i.e. g++), ACLK NG should be built with protobuf.
If configure phase (uninstall g++) or build of protobuf (`ctrl-z` after configure, break a protobuf file, `fg`), observe that installer continues with the rest of components, and does not build ACLK NG.
This does not solve the big problem, which is how to eventually "force" use of ACLK NG with protobuf.
> Check for failed protobuf configure or make

- configure.ac
- netdata-installer.sh
Due to having two ACLK implementations, failing to build any arbitrary set of cloud dependencies is not guaranteed to prevent us from building a working cloud implementation, so we should fall back to relying on the configure script for determining if the cloud can be built.
This also ensures that the configure script properly bails if we can’t enable either ACLK implementation _and_ were asked to require the cloud.
area/packaging
CI passes
Fixes: #11443
> Don’t bail early if we fail to build cloud deps with required cloud.

- .github/scripts/build-static.sh
- .github/workflows/build-and-install.yml
- .travis/create_artifacts.sh
- packaging/makeself/build-static.sh
- packaging/makeself/build-x86_64-static.sh
- packaging/makeself/jobs/99-makeself.install.sh
This allows installer code to select a static build for a specific architecture, which is a prerequisite for providing static builds for other architectures.
These changes have been done in a way that attempts to preserve compatibility with the existing `kickstart-static64.sh` script and existing static installs. Long-term, we ideally want to drop this legacy support, but it’s essentially free (it just consists of a couple of extra symlinks in the GCS bucket) so it’s not a high priority.
This also includes some preliminary work to support ARMv7 and AArch64 static builds (both highly requested by users).
area/packaging
area/ci
The primary changes to the static build process can be tested directly on any system with a working Docker install. The new `packaging/makeself/build-static.sh` …
> Embed build architecture in static build archive names.

- packaging/docker/Dockerfile
- packaging/docker/README.md
- packaging/docker/run.sh
This adds functionality to the Docker image allowing users to specify a custom UID and/or GID for Netdata to run as using the `NETDATA_UID` and `NETDATA_GID` environment variables.
The changes involve pushing the `netdata` user and group creation from the build process to the entrypoint script, and then adding some code to handle a handful of the most likely edge-cases, aswell as setting things up to automatically fix permissions on startup.
This new behavior is only exhibited if neither `DOCKER_USR` (kept for compatibility) nor `NETDATA_USER` (added for consistency) are set. This behavior was chosen on the assumption that a user who is specifically requesting that Netdata run as a particular user knows what they’re doing, and therefore we shouldn’t risk getting in their way.
This also …
> Add support for runtime configuration of UID/GID for Netdata user.

- aclk/aclk_alarm_api.c
- aclk/aclk_charts_api.c
- aclk/aclk_query_queue.h
Use QUEUE_IF_PAYLOAD_PRESENT in alarm api.
This prevents query mem leak in case of unlikely failure to generate binary payload by protobuf.
This is currently unused code (new cloud architecture).
ACLK
Coverity CID 372861, 372862 should be gone.
> Fix issues in Alarm API

- packaging/docker/Dockerfile
- packaging/makeself/jobs/70-netdata-git.install.sh
We know both environments provide a reliably stable copy, and this greatly improves build times.
area/packaging
area/packaging
This should have been done when we first added protobuf to the installer.
> Use system copy of protobuf in Docker images and static builds.

- collectors/python.d.plugin/elasticsearch/elasticsearch.chart.py
In some cases, e.g. index closed or error on creation
it can happen that the docs.count and the store.size
values are null.
This patch solves this issue by checking for None
and returning -1.
Elasticsearch python plugin
> Fix elasticsearch null values returned by _cat/indices API

- health/notifications/alarm-notify.sh.in
- health/notifications/email/README.md
This was [requested by a user in the community forum](https://community.netdata.cloud/t/custom-headers-in-email-notifications/1489). Although the user seems to have requested it for the cloud e-mails, it is a simple change to also have in agent e-mails. If we need perhaps to also include it in cloud e-mails, we can wait before merging and synchronize as to not create confusion.
The PR adds some custom headers, which can then be used for filtering from an email client.
Health notifications
Raise an alert e-mail notification from an agent. Observe in the e-mail headers e.g.:
```
X-Netdata-Severity: warning
X-Netdata-Alert-Name: exporting_metrics_sent
X-Netdata-Chart: netdata.exporting_my_graphite_instance_bytes
X-Netdata-Family: exporting_my_graphite_instance
X-Netdata-Classification: …
```
> Add custom e-mail headers

- health/notifications/alarm-notify.sh.in
Continuing from https://github.com/netdata/netdata/pull/11283, it appears that `sendmail` from the `ssmtp` package, responds differently when executing `sendmail -F` as opposed to other sendmail versions.
So to recap, this is what I've got (only the fist line of response):
1) Real sendmail: `sendmail: option requires an argument -- F`
2) Postfix: `sendmail: option requires an argument -- 'F'`
3) Ssmtp: `sendmail: No recipients supplied - mail will not be sent`
4) Msmtp: `sendmail: option requires an argument -- 'F'`
5) Exim: `exim abandoned: unknown, malformed, or incomplete option -F` (but does support it).
6) Qmail: `sendmail: option requires an argument -- F`
7) Busybox: `sendmail: unrecognized option: F`
So the plan is, unless we get `sendmail: unrecognized option: F` we pass the …
> Better check for supported -F parameter in sendmail

- collectors/ebpf.plugin/Makefile.am
- collectors/ebpf.plugin/README.md
- collectors/ebpf.plugin/reset_netdata_trace.sh.in
- netdata-installer.sh
As we talked in this [issue](https://github.com/netdata/netdata/issues/11409), after we start using `libbpf`, we do not need more the script `reset_netdata_trace.sh`, this PR is updating our documentation, and removing the unused script.
eBPF.plugin
1 - Compile this PR
2 - Verify that after installation you do not have more the file `/usr/libexec/netdata/plugins.d/reset_netdata_trace.sh`.
It is not necessary to run on different kernels, because this file is not called from `eBPF.plugin` anymore.
> Remove unused script

- system/netdata.service.in
The script was deleted in https://github.com/netdata/netdata/pull/11516, but we forgot to update `netdata.service` file.
`packaging`
Not needed.
> remove `reset_netdata_trace.sh` from netdata.service

- netdata.spec.in
- packaging/installer/install-required-packages.sh
This consists of assorted cleanup work in our CentOS and RHEL dependency handling, specifically:
* Eliminating dependencies on EPEL and OKay repositories. We don’t actually need anything from either repo, so not trying to use them at all makes us more portable and more robust.
* Allowing use of DNF on CentOS.
* Switching to using DNF in preference to YUM. The only reason we still need support for yum is CentOS 7 and other distros based on it.
area/packaging
Relevant CI checks still pass.
There will be an associated follow up PR in the helper images repo to remove OKay and EPEL from the CentOS 8 package builder image, which will in turn enable us to offer ARM support for our CentOS RPMs.
This is also part of the prep work to eventually pivot to Rocky Linux for our RHEL 8 compatible builds.
> Clean up dependency handling for CentOS/RHEL

- packaging/installer/install-required-packages.sh
This changes the default behavior of the `install-required-packages.sh` script to be equivalent to if the user had specified the `netdata` package set.
area/packaging
CI checks pass.
This has been a known bug for some time, but never really got fixed due to the script not being intended to be run by a normal user.
> Install basic netdata deps by default.

- aclk/aclk.c
- aclk/aclk.h
- aclk/aclk_api.c
- aclk/aclk_api.h
- aclk/legacy/agent_cloud_link.c
- aclk/legacy/agent_cloud_link.h
- daemon/commands.c
- daemon/commands.h
Implements product ask to have current aclk/cloud state available trough `netdatacli`. This is useful for example in cases where the local dashboard is not accessible or is disabled.
Us still having the ACLK Legacy here adds some awkwardness to the thing.
Try with various ACLK implementations. (Hopefully we will get rid of ACLK legacy soon)
run
`netdatacli aclk-state` and/or `netdatacli aclk-state json`
> Adds aclk/cloud state command to netdatacli

- web/gui/dashboard_info.js
This PR adds dashboard info for [ipc](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/ipc.c) (System V IPC) collector's charts.
`web/`
> add ipc semaphores charts info

- daemon/analytics.c
- daemon/analytics.h
- daemon/main.c
Fixes #8926
Rearrange the logs initialization so that lines do not appear in the terminal output as described in #8926 
Typically the following lines appear  (example)
```
netdata INFO  : MAIN : TIMEZONE: using the contents of /etc/timezone: 'Europe/Athens'
netdata INFO  : MAIN : TIMEZONE: fixed as 'Europe/Athens'
netdata INFO  : MAIN : SIGNAL: Not enabling reaper
```
- Build the agent and start from the command line
- You should see those messages appear in the `error.log` instead of the terminal
> Fix issue with log messages appearing in the terminal instead of the error.log on startup

- packaging/installer/netdata-updater.sh
fixes 3b41c79afdd7d5b2d6f2ed0225a51b0df7e63158
Fixes #10472
who knows
run the updater and don't get `/netdata-updater.log.asjkf` files hopefully
fifty years of UNIX! how did this pass review
> Don't write updater log under root

- web/gui/dashboard_info.js
This PR adds missing dashboard info for [diskstats](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_diskstats.c) collector's charts.
`web/`
Install this PR; check the IPC semaphores charts; ensure the info is on the dashboard.
> add diskstats charts info 

- CMakeLists.txt
- Makefile.am
- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_aclk_node.c
- database/sqlite/sqlite_aclk_node.h
Add initial support for node info message
aclk, database
The code is not active yet (it is tested with the new architecture in a separate branch)
> Add node message support for ACLK new architecture

- CMakeLists.txt
Adds missing files for New Cloud Protocol support to cmake.
build/cmake
CI, build with cmake
> Add New Cloud Protocol files to CMake

- web/gui/dashboard_info.js
This PR adds missing dashboard info for [proc_mdstat](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_mdstat.c) collector's charts.
`web/`
Install this PR; check the mdstat charts; ensure the info is on the dashboard.
> add proc_mdstat charts info

- health/health_config.c
Fixes coverity issues introduced from https://github.com/netdata/netdata/pull/11399
Fixes `CID 373229` and `CID 373228`.
Health
Should not have any functional differences. Tested an alert config load table from #11399 against a same load from this PR.
> Fix coverity issues for health config

- web/gui/dashboard_info.js
This PR adds missing dashboard info for [proc_meminfo](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_meminfo.c) collector's charts.
`web/`
Install this PR; check the proc_meminfo charts; ensure the info is on the dashboard.
> add proc_meminfo charts info

- packaging/installer/netdata-updater.sh
This fixes a minor bug in the updater script which causes it to potentially return a non-zero exit status on a successful update of a static install when there is a newer version of the updater in the repo than is installed locally.
area/packaging
Verified locally.
Fixes: #11519
> Use the correct exit status for the updater with static updates.

- web/gui/dashboard_info.js
This PR adds missing dashboard info for [proc_net_dev](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_net_dev.c) collector's charts.
`web/`
Install this PR; check the proc_net_dev charts; ensure the info is on the dashboard.
> add proc_net_dev charts info

- web/gui/dashboard_info.js
This PR adds dashboard info for [proc_net_ip_vs_stats](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_net_ip_vs_stats.c) collector's charts.
`web/`
Install this PR; check the proc_net_ip_vs_stats charts; ensure the info is on the dashboard.
> add proc_net_ip_vs_stats charts info

- web/gui/dashboard_info.js
This PR adds dashboard info for [proc_net_netstat](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_net_netstat.c) collector's charts.
`web/`
Install this PR; check the proc_net_netstat charts; ensure the info is on the dashboard.
> add proc_net_netstat charts info

- web/gui/dashboard_info.js
This PR adds dashboard info for [proc_net_snmp](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_net_snmp.c) collector's charts.
`web/`
Install this PR; check the proc_net_snmp charts; ensure the info is on the dashboard.
> add proc_net_snmp charts info

- web/gui/dashboard_info.js
This PR adds dashboard info for [proc_net_sctp_snmp](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_net_sctp_snmp.c) collector's charts.
`web/`
Install this PR; check proc_net_sctp_snmp charts; ensure the info is on the dashboard.
> add proc_net_sctp_snmp charts info

- .github/workflows/build-and-install.yml
- .github/workflows/packaging.yml
- .github/workflows/repoconfig-packages.yml
- .github/workflows/updater.yml
It’s actually been EOL upstream for a while now, and the recent transition back into support via Cannoncial’s ESM support tier does not actually change our own support status.
area/ci
area/packaging
n/a
> End of support for Ubuntu 16.04

- netdata-installer.sh
This PR is bringing the same fix added by @Ferroin [here](https://github.com/netdata/netdata/commit/f6d966909bb5c443e771d312f1686ec3fa2c2aff) for Netdata source-code.
We have plans to bring eBPF plugin for different platforms, but while it is not merged and considering the reported problems per Slack when we use the latest `libbpf`, the safest is to disable.
netdata-installer
1 - Compile this PR on `X86_64`, and verify that `eBPF.plugin` is compiled and it runs normally
2 - Compile this PR on different platform, and verify that `eBPF.plugin` is not compiled.
> Disable eBPF compilation in different platforms

- web/gui/dashboard_info.js
This PR adds dashboard info for [proc_net_sockstat](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_net_sockstat.c) and [proc_net_sockstat6](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_net_sockstat6.c) collector's charts.
`web/`
Install this PR; check the proc_net_sockstat and proc_net_sockstat6 charts; ensure the info is on the dashboard.
> add proc_net_sockstat and sockstat6 charts info

- web/gui/dashboard_info.js
This PR adds dashboard info for [proc_net_uptime](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_uptime.c) collector's charts.
`web/`
Install this PR; check the proc_uptime charts; ensure the info is on the dashboard.
> add proc_uptime charts info

- Makefile.am
- collectors/cgroups.plugin/sys_fs_cgroup.c
- collectors/cgroups.plugin/sys_fs_cgroup.h
This is the second step to bring integration between eBPF and cgroups https://github.com/netdata/netdata/issues/11558.
This PR is creating shared memory with cgroup plugin.
cgroup
ebpf.plugin
1 - Enable flag inside your `netdata.conf`
2 - Compile this branch
3 - Take a look in the logs to verify whether shared memory was filled
This PR is part of a huge branch that has almost all modifications proposed for #11558 , and it was tested on:
- Manjaro 21.1 (cgroup version 2)
- CentOS 7.9
- Debian 10.10
- Ubuntu 18.04
> Add shared memory to cgroup

- collectors/python.d.plugin/mysql/README.md
The "netdata" MySQL users needs the "REPLICATION CLIENT" privilege to monitor the slave status. Otherwise, the charts "Slave Status" and "Slave Behind Seconds" are missing and the corresponding alerts don't work either.
MySQL collector
> add missing privilege to fix MySQL slave reporting

- .github/workflows/build-and-install.yml
- .github/workflows/checks.yml
- .github/workflows/packaging.yml
This should speed up the testing loop for verifying changes related to the static builds, native package builds, and dist archive generation.
area/ci
Artifacts are correctly visible on CI on this PR.
> Add archive uploads for dist, package build, and static build checks.

- collectors/python.d.plugin/postgres/postgres.chart.py
Sorting the list of databases in the postgres cluster in alphabetical order
to simplify the search for charts for clusters with a large number
of databases.
collectors/python.d.plugin/postgres
> Sorting the Postgres cluster databases in the postgres collector

- web/gui/dashboard_info.js
This PR adds dashboard info for [proc_net_stat_conntrack](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_net_stat_conntrack.c) collector's charts.
`web/`
Install this PR; check the proc_net_stat_conntrack charts; ensure the info is on the dashboard.
> add proc_net_stat_conntrack charts info

- collectors/cgroups.plugin/sys_fs_cgroup.c
- collectors/cgroups.plugin/sys_fs_cgroup.h
- collectors/ebpf.plugin/ebpf_disk.c
Last PR merged changing `cgroup.plugin` created the following warning:
```
CID 339027 (#1 of 1): Extra sizeof expression (SIZEOF_MISMATCH)suspicious_pointer_arithmetic: Adding 24UL /* sizeof (netdata_ebpf_cgroup_shm_header_t) */ to pointer shm_cgroup_ebpf.header of type netdata_ebpf_cgroup_shm_header_t * is suspicious because adding an integral value to this pointer automatically scales that value by the size, 24 bytes, of the pointed-to type, netdata_ebpf_cgroup_shm_header_t. Most likely, sizeof (netdata_ebpf_cgroup_shm_header_t) is extraneous and should be replaced with 1.
``` 
This PR is fixing this warning and also is reverting arguments that could create a problem like [this](https://github.com/netdata/netdata/pull/11573#issuecomment-927744895).
cgroup.plugin
ebpf.plugin
1 - …
> Fix CID 339027 and reverse arguments

- web/gui/dashboard_info.js
This PR adds dashboard info for [proc_net_stat_synproxy](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_net_stat_synproxy.c) collector's charts.
`web/`
Install this PR; check the proc_net_stat_synproxy charts; ensure the info is on the dashboard.
> add proc_net_stat_synproxy charts info

- daemon/analytics.c
- daemon/main.c
This PR moves the call of `analytics_free_data()` from `netdata_cleanup_and_exit` to `analytics_main_cleanup`. It should address the second core case in https://github.com/netdata/netdata/issues/11571.
This core could happen during exit, if an external tool was quering the `allmetrics` page during agent shutdown. In that case, analytics would try to log this call by setting e.g. `analytics_data.netdata_allmetrics_prometheus_used`. If `analytics_free_data()` was called already, there could be a double free situation resulting in a crash.
Valgrind also picked this up:
```
==23744== Invalid read of size 1
==23744==    at 0x4846063: strlen (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==23744==    by 0x14035B: analytics_set_data (analytics.c:117)
==23744==    by 0x140466: …
```
> Free analytics data when analytics thread stops

- .github/workflows/build-and-install.yml
It’s a recurring source of build failures due to upstream problems, and we don’t really officially support it anyway.
area/ci
n/a
> Remove OpenSUSE Tumbleweed from CI.

- web/gui/dashboard_info.js
This PR adds dashboard info for [proc_stat](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_stat.c) collector's charts.
`web/`
Install this PR; check the proc_stat charts; ensure the info is on the dashboard.
> add proc_stat charts info

- web/gui/dashboard_info.js
This PR adds dashboard info for [sys_devices_system_edac_mc](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/sys_devices_system_edac_mc.c) collector's charts.
`web/`
Install this PR; check the sys_devices_system_edac_mc charts; ensure the info is on the dashboard.
> add sys_devices_system_edac_mc charts info

- web/api/web_api_v1.c
Minor PR. Adds `api/v1/aclk` to get ACLK status by the local dashboard and everyone else who wants it. This status will be extended in the future with more information about sync state, buffers, etc. (exact list TBD)
go to the local dashboard and add `api/v1/aclk` to the URL
> Adds local webserver API/v1 call "aclk"

- Makefile.am
- aclk/aclk.c
- aclk/aclk_otp.c
- aclk/aclk_query.c
- aclk/aclk_rx_msgs.c
- aclk/aclk_rx_msgs.h
- aclk/aclk_tx_msgs.c
- aclk/aclk_tx_msgs.h
- aclk/aclk_util.c
- aclk/aclk_util.h
- configure.ac
- daemon/buildinfo.c
- database/sqlite/sqlite_aclk_alert.c
- database/sqlite/sqlite_aclk_chart.c
- database/sqlite/sqlite_aclk_node.c
- web/api/web_api_v1.c
ACLK-NG doesn't really need the protobuf and CXX compiler. It is the New Cloud Protocol/Architecture who needs it. This PR allows building ACLK-NG without a new cloud.
Default behavior adds New Cloud Support if possible. This can be overridden by configuring the flag.
This will allow us to remove Legacy ACLK (not maintained anymore) more quickly and thus simplifying the whole thing (code, build system, installer) as the majority of people will be able to build ACLK-NG by default.
build system + aclk + database/sqlite
build with `--without-new-cloud-protocol`, `--with-new-cloud-protocol` and without flag.
Build without any flag and missing protobuf should still make ACLK-NG available with old JSON cloud protocol only.
> Makes New Cloud architecture optional for ACLK-NG

- web/gui/dashboard_info.js
This PR adds dashboard info for [sys_kernel_mm_ksm](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/sys_kernel_mm_ksm.c) collector's charts.
`web/`
Install this PR; check the sys_kernel_mm_ksm charts; ensure the info is on the dashboard.
> add sys_kernel_mm_ksm charts info

- web/gui/dashboard_info.js
This PR adds dashboard info for [proc_vmstat](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_vmstat.c) collector's charts.
`web/`
Install this PR; check the proc_vmstat charts; ensure the info is on the dashboard.
> add proc_vmstat charts info

- aclk/https_client.c
Introduced in https://github.com/netdata/netdata/pull/8358 since then moved and modified it was not doing dull chain verification.
This fixes it.
full chain verification was and is done right after in mqtt_websockets.
aclk
> fix https client 

- web/gui/dashboard_info.js
This PR adds dashboard info for [cgroups.plugin](https://github.com/netdata/netdata/tree/master/collectors/cgroups.plugin#cgroupsplugin) collector's charts.
`web/`
Install this PR; check the cgroups.plugin charts; ensure the info is on the dashboard.
> add cgroups.plugin charts descriptions

- .github/workflows/packaging.yml
- contrib/debian/rules
- netdata.spec.in
- packaging/bundle-lws.sh
This adds ARMv7 and ARMv8 binary package builds to our CI for all the platforms we can support them on. These still need some testing, but are ready enough to be released as an open beta.
area/packaging.
CI passes correctly (ensures that packages build and are successfully installable).
Fixes: #7824 (wow, I did not realize how old this issue was)
Relevant to: #7826, #10481
> Added ARM binary package builds to CI.

- collectors/cgroups.plugin/sys_fs_cgroup.c
It is stated in the [cgroups memory controller documentation](https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt):
>rss		- # of bytes of anonymous and swap cache memory (includes transparent hugepages).
rss_huge	- # of bytes of anonymous transparent hugepages.
Therefore, we shouldn't add the values to avoid doubling of transparent hugepages size.
cgroups plugin
> Fix RSS memory counter for systemd services

- collectors/cgroups.plugin/sys_fs_cgroup.c
We should subtract RAM usage to get correct swap size for cgroups v1. Look at the [documentation](https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt):
>  memory.memsw.usage_in_bytes	 # show current usage for memory+Swap
cgroups plugin
> Fix swap size calculation for cgroups

- web/gui/dashboard_info.js
This PR adds dashboard info for [proc sys_class_power_supply](https://github.com/netdata/netdata/tree/master/collectors/proc.plugin/sys_class_power_supply.c) collector's charts.
`web/`
Install this PR; check the proc sys_class_power_supply charts; ensure the info is on the dashboard.
> add sys_class_power_supply charts info

- web/gui/dashboard_info.js
This PR adds dashboard info for [cgroups.plugin](https://github.com/netdata/netdata/tree/master/collectors/cgroups.plugin#cgroupsplugin) collector's systemd units charts.
`web/`
Install this PR; check the cgroups.plugin systemd units charts; ensure the info is on the dashboard.
> add cgroups.plugin systemd units charts info

- web/gui/dashboard_info.js
This PR adds dashboard info for [proc_net_wireless](https://github.com/netdata/netdata/tree/master/collectors/proc.plugin/proc_net_wireless.c) collector's charts.
`web/`
Install this PR; check the proc_net_wireless charts; ensure the info is on the dashboard.
> add proc_net_wireless charts info

- spawn/spawn_client.c
Zero initialize `write_ctx` to remove a valgrind warning in `spawn/spawn_client.c`.
This should remove this warning:
```
==7869== Thread 2:
==7869== Syscall param writev(vector[...]) points to uninitialised byte(s)
==7869==    at 0x55D3C1D: writev (in /lib64/libc-2.33.so)
==7869==    by 0x4E29909: ??? (in /usr/lib64/libuv.so.1.0.0)
==7869==    by 0x4E29AD8: ??? (in /usr/lib64/libuv.so.1.0.0)
==7869==    by 0x4E2AC25: uv_write2 (in /usr/lib64/libuv.so.1.0.0)
==7869==    by 0x28E641: spawn_process_cmd (spawn_client.c:160)
==7869==    by 0x28E641: spawn_client (spawn_client.c:215)
==7869==    by 0x54C8E5D: start_thread (in /lib64/libpthread-2.33.so)
==7869==    by 0x55DCEFE: clone (in /lib64/libc-2.33.so)
==7869==  Address 0x5a67d54 is 196 bytes inside a block of size 240 alloc'd
==7869== …
```
> Initialize struct with zeroes

- web/gui/dashboard_info.js
This PR adds dashboard info for [proc_net_rpc_nfs](https://github.com/netdata/netdata/tree/master/collectors/proc.plugin/proc_net_rpc_nfs.c) and [nfsd](https://github.com/netdata/netdata/tree/master/collectors/proc.plugin/proc_net_rpc_nfsd.c) collector's charts.
`web/`
Install this PR; check the proc_net_rpc_nfs and nfsd  charts; ensure the info is on the dashboard.
> add proc_net_rpc_nfs and nfsd charts info

- web/gui/dashboard_info.js
This PR adds dashboard info for [proc_pagetypeinfo](https://github.com/netdata/netdata/tree/master/collectors/proc.plugin/proc_pagetypeinfo.c) collector's charts.
`web/`
Install this PR; check the proc_pagetypeinfos charts; ensure the info is on the dashboard.
> add proc_pagetypeinfo charts info

- aclk/aclk.c
Due to mistake the ACLK online chart could show online status longer than it should.
ACLK-NG
tested manually by
- iptables block OUTPUT to cloud IP (takes time to be detected)
- iptables block INPUT from cloud IP (takes time to be detected)
- ss -K dst IP (instant)
tested automatically by inducing drops at random times
tested in all cases:
1. re-connection happens after network conditions are restored normal
2. chart properly shows valid data
> Fix online chart in NG not updated properly

- .github/workflows/build-and-install.yml
To be merged 2021-11-01 when Alpine 3.11 officially goes EOL.
area/ci
n/a
> Remove Alpine 3.11 from CI.

- web/api/web_api_v1.c
Small PR to make sure to print a comma after `metrics-count` in `api/v1/info` only if there is also `ml-info` to print.
web/api
Compile with default parameters (to enable ml) and using `--disable-ml`. Check that in both cases there is no error emitted when requesting `/api/v1/info`.
> Change comma possition in v1/info if ml-info is missing

- web/gui/src/dashboard.js/dependencies.js
Fixes: #11742
"master" branch now has jQuery 3.6.0 (https://github.com/netdata/netdata/tree/master/web/gui/dashboard/lib) but the dependency still calls jQuery 2.2.4 (https://github.com/netdata/netdata/blob/master/web/gui/src/dashboard.js/dependencies.js Line: 7)
Web GUI
> Update jQuery Dependency

- Makefile.am
Disable sign comparison and type size warning flags for dlib.
Local builds & CI jobs.
> Disable C++ warnings from dlib library.

- .github/workflows/build-and-install.yml
- .github/workflows/packaging.yml
- .github/workflows/repoconfig-packages.yml
- .github/workflows/updater.yml
Expected release date is 2021-11-02.
area/ci
CI checks pass on this PR.
This ideally needs to be merged prior to our next stable release.
> Add Fedora 35 to CI.

- netdata-installer.sh
- packaging/installer/kickstart-ng.sh
This adds some basic telemetry to the new kickstart script. This new code properly honors the `--disable-telemetry` option and the `DO_NOT_TRACK` environment variable.
The following PostHog events are used for this purpose:
* `INSTALL_SUCCESS`: Sent after a successful install finishes.
* `INSTALL_FAILED`: Sent when an installation fails via an expected (and properly handled) failure path. Includes the error message shown to the user and an error code for easy searching within the script.
* `INSTALL_CRASH`: Sent when an installation fails via an unexpected exit path or due to an external signal. Includes the signal number (or `0` for an unguarded call to `exit`), and the line number if it was due to an unguarded call to exit.
The following properties are used with these events (note that …
> Add basic telemetry to the new kickstart script.

- netdata-installer.sh
- packaging/installer/kickstart.sh
- packaging/installer/methods/kickstart.md
This adds checks to our installer script to sanely handle installation on systems with limited RAM. By default, it involves the following specific behavior:
* If the system has less than 1GB of RAM, disable the ML code by default.
* If the user has specified a number of jobs to use in `MAKEOPTS`, check to see if we have enough RAM (defined as 1.25GB for `-j2`, +250MB per additional CPU core used beyond 2) and refuse to build if we don’t. This is _probably_ more aggressive than it needs to be, but that should not be an issue in most cases.
* If the user did not specify a number of jobs to use in `MAKEOPTS`, use the total amount of RAM in the system to try to decide on a sane default (1 job for anything with 1GB or less, one additiona job for every 250MB above that).
This also adds …
> Sanely handle installing on systems with limited RAM.

- aclk/aclk.c
It was unnecessarily prolonging popcorn timer in case of lot of children. Should speed up connection in case there are lot of kids and old cloud protocol is used.
> Don't interrupt popcorn timer for children

- aclk/aclk.c
In case netdata is exiting while we called env already allow us to bail before OTP.
ACLK-NG
> Adds exit points between env and OTP

- collectors/cgroups.plugin/cgroup-name.sh.in
Fixes: #4868
This PR fixes containers/pods name resolution when using containerd/cri-o container runtime.
`collectors/cgroups.plugin`
- k8s cluster with docker cr: tested, this PR doesn't break it.
- k8s cluster with containerd cr: [tested](https://github.com/netdata/netdata/issues/4868#issuecomment-961764250) by @aharonh.
- k8s cluster with crio-o cr: tested by a person from our Discord server.
> fix (cgroups.plugin): containers name resolution for crio/containerd cri

- libnetdata/socket/security.c
This PR adds the flag `SSL_MODE_ENABLE_PARTIAL_WRITE` to `netdata_srv_ctx`. It thus allows `SSL_write` to return bytes written, instead of an error, if a partial write has been done.
If it's not enabled, `SSL_write` might return error (probably `SSL_ERROR_WANT_WRITE`) and it will be treated as error with no retries from `web_server_snd_callback`.
If it's enabled, `web_server_snd_callback` will be called repeatedly until no more data is left to send.
Closes https://github.com/netdata/netdata/issues/10886
SSL
(Major kudos to @ilyam8 for managing to re-create the problem in https://github.com/netdata/netdata/issues/10886)
Try the scenario on an SSL enabled agent:
* From a different host, try: `curl --insecure https://pc:19999/api/v1/charts`. 
Curl will probably respond with: `(18) transfer …
> Add SSL_MODE_ENABLE_PARTIAL_WRITE to netdata_srv_ctx

- configure.ac
- daemon/buildinfo.c
protobuf is now optional for ACLK, and used by at least one other feature, so we really should have it in the output of the `-W buildinfo` switch (and in the associated anonymous statistics).
area/daemon
Verified locally that the output is correct for protobuf being both present and absent.
This also re-sorts the macros in `daemon/buildinfo.c` so that they are grouped properly by feature type.
> Add protobuf to `-W buildinfo` output.

- packaging/installer/functions.sh
nproc does not exists as a base part of macOS, but both Homebrew and Macports contain 'coreutil' with gnproc.
area/packing
> Minor improvement to CPU number function regarding macOS.

- collectors/diskspace.plugin/plugin_diskspace.c
In `netdata.service` two protection options [are set by default](https://github.com/netdata/netdata/blob/f2826332672c2486c643ffcc5ecf67c647491cde/system/netdata.service.in#L67-L68). It means, that some mount points are marked as read-only and additional mount points may be added by systemd.
We will display the diskspace charts for some protected mount points by default. For the full list of protected mount points look at [ProtectHome=read-only](https://github.com/systemd/systemd/blob/1eb3ef78b4df28a9e9f464714208f2682f957e36/src/core/namespace.c#L142-L149) and [ProtectSystem=full](https://github.com/systemd/systemd/blob/1eb3ef78b4df28a9e9f464714208f2682f957e36/src/core/namespace.c#L180-L194) lists.
Fixes #3716
Fixes #9585
Fixes #11498
diskspace.plugin
1. Run Netdata without a mount in …
> Show stats for protected mount points in diskspace plugin

- database/rrdset.c
- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_aclk_chart.c
- database/sqlite/sqlite_aclk_chart.h
- Add new dimension_delete table and delete trigger on dimension table to record dimension deletions
- Submit the deleted dimensions to the cloud
A follow up PR will cleanup the dimension_delete table if ACLK is disabled
ACLK, database
- Code is being tested in testing and staging environments
> Store and submit dimension delete messages for new cloud architecture

- aclk/aclk.c
- aclk/aclk.h
- aclk/aclk_otp.c
- aclk/aclk_util.c
- aclk/aclk_util.h
Announces to cloud this agent is capable of proto.
In case the cloud then returns encoding proto we will switch to the new protocol.
ACLK
Test together with the cloud team. Test without `#define ACLK_NEWARCH_DEVMODE`.
At the time of my last testing, not every cloud environment behaved correctly (testing/staging/prod). You might have to check with the cloud on which one is the latest code.
> Announce proto capability and enable if cloud supports

- database/sqlite/sqlite_aclk.c
- database/sqlite/sqlite_aclk.h
- database/sqlite/sqlite_aclk_alert.c
- database/sqlite/sqlite_aclk_chart.h
Changes the way alerts are inserted in aclk_alert_XXXX. Instead of queuing with an `ACLK_DATABASE_ADD_ALERT` opcode, it inserts it directly to the DB.
ACLK/New architecture
This code is under test in staging environment.
> Insert alert into aclk_alert directly instead of queuing it

- collectors/cgroups.plugin/cgroup-name.sh.in
- collectors/cgroups.plugin/sys_fs_cgroup.c
After #11050 some of regular expressions in [`cgroup-name.sh`](https://github.com/netdata/netdata/blob/9676eff1bc6dfc28e8f1c4857786ec05613b2646/collectors/cgroups.plugin/cgroup-name.sh.in) work incorrectly. We should use `cg->id` and fix the script, but we decided to make a simple temporary fix because the next release is coming.
Fixes #11760
cgroups plugin
Start as many different types of containers as you can. Check if they are named correctly in the dashboard or charts API.
> Temporary fix for cgroup renaming

- README.md
Add a dynamic badge to README.md to display latest nightly version. 
Badge is dynamically read from this url: https://img.shields.io/badge/dynamic/xml?url=https://storage.googleapis.com/netdata-nightlies/latest-version.txt&label=nightly%20release&query=/text()
Which just picks up the text from https://storage.googleapis.com/netdata-nightlies/latest-version.txt file.
docs
README.md
> add nightly release version to readme

- collectors/proc.plugin/proc_interrupts.c
This fixes the same bug as the one highlighted in #4051, with the same fix as in #4055.
This bug surfaces with systems with a very high number of interrupts (especially true for ARM arch): in this case, netdata doesn't parse /proc/interrupts correctly and ends up creating new metrics every few seconds, which eventually leads to insane RAM & CPU usage. See #4051 for more context.
We hit this bug in production with netdata latest stable (v1.31.0).
The bug seems to have been re-introduced during collector refactoring. I did not check if other bugs might have been re-introduced.
collector -> proc.plugin
As the fix was already present in former netdata release, it has not been re-tested
> Fix proc/interrupts parser
